gh-99110: Initialize frame->previous in _PyFrame_InitializeSpecials
python/cpython pull request #100182
Opened 2022-12-12 00:52 UTC by byllyfish

This PR fixes a segmentation fault caused by an uninitialized variable. One way to trigger the seg. fault is to use the PyFrame_New() C API. I've also run across this segmentation fault by calling `asyncio.Task.get_stack()` on cython based asyncio Task (in the grpcio module).

The fix for #99110 needs to be back-ported to 3.11.

2022-12-13 06:18 UTC, kumaraditya303 commented on Lib/test/test_ctypes/test_python_api.py
> +        assert frame.f_back is None
Use self.assertEqual

2022-12-13 10:06 UTC, markshannon commented
`_PyInterpreterFrame.previous` gets initialized when the frame is linked into the frame stack.
I'd rather not add extra code to `_PyFrame_InitializeSpecials`, as it is performance critical.

`_PyInterpreterFrame.previous` could be set to `NULL` [when initializing the frame object](https://github.com/python/cpython/blob/main/Objects/frameobject.c#L1016)

2022-12-16 14:41 UTC, markshannon requested changes

2022-12-16 14:41 UTC, markshannon commented on Include/internal/pycore_frame.h
> +    // frame->previous: initialized when frame is linked into the frame stack
This looks a bit like commented out code.
Could you move the comment to above the function.

2022-12-16 14:41 UTC, markshannon commented on Include/internal/pycore_frame.h
> +    // frame->previous: initialized when frame is linked into the frame stack
Maybe change `/* Consumes reference to func and locals */` to 
```C
/* Consumes reference to func and locals.
   Does not initialize frame->previous, which happens
   when frame is linked into the frame stack.
*/
```

2022-12-16 14:41 UTC, markshannon commented on Lib/test/test_ctypes/test_python_api.py
> +    def test_PyFrame_New_f_back(self):
This sort of test usually goes in `test_capi`.

First a function to call `PyFrame_New` in `_testcapimodule.c`, then call that function in the test.

So, `pythonapi.PyFrame_New(...)` below would be replaced with `_testcapimodule.new_frame(dummy.__code__, globals(), locals())`.

2022-12-18 04:04 UTC, byllyfish commented
I moved the test code into the `TestCAPI` unit test class in test_frame.py.

I have made the requested changes; please review again.

2022-12-23 10:57 UTC, kumaraditya303 approved these changes

2022-12-23 11:08 UTC, kumaraditya303 commented on Lib/test/test_frame.py
> +        self.assertEqual(frame.f_back, None)
```suggestion
        self.assertIsNone(frame.f_back)
```

2022-12-23 12:50 UTC, markshannon approved these changes
Looks good now. Thanks.

2022-12-23 13:11 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Core and Builtins/2022-12-12-01-05-16.gh-issue-99110.1JqtIg.rst
> +accessing frames created by ctypes.
```suggestion
accessing frames created by :c:func:`PyFrame_New`.
```

2022-12-23 14:45 UTC, merged

2022-12-23 14:45 UTC, miss-islington commented
Thanks @byllyfish for the PR, and @kumaraditya303 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2022-12-23 14:46 UTC, miss-islington commented
Sorry, @byllyfish and @kumaraditya303, I could not cleanly backport this to `3.11` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 88d565f32a709140664444c6dea20ecd35a10e94 3.11
                                ```