gh-100388: Change undefined __DATE__ to XXX XX XXXX
python/cpython pull request #100389
Opened 2022-12-21 03:23 UTC by fosslinux

This seems like the most reasonable fix, given the structure of `__DATE__` normally.

Should this fix be backported?

2023-02-05 12:26 UTC, arhadthedev commented
@malemburg (as the platform expert), would you mind to review and possibly merge this PR?

2023-04-05 11:40 UTC, iritkatriel requested changes
Please add a unit test that fails without this patch and passes with it, so we can understand what you are changing and why, and so that the issue you are fixing will not be accidentally re-introduced in the future.

2025-02-05 00:32 UTC, fosslinux commented
(I completely forgot about this PR, and was reminded of it today! Apologies)

@iritkatriel I'm a bit confused regarding how I am meant to create a unit test for this. This is a bug that only arises when Python (namely, the getbuildinfo module) is compiled with `CFLAGS=-U__DATE__`. This code path is not used by the preprocessor on any of the automated unit tests, so any unit test I do add will pass both before and after this PR....

2025-02-05 09:15 UTC, malemburg commented
Please rebase the PR for a review. Thanks.

2025-02-05 12:52 UTC, malemburg commented
The issue is that the platform.py parser expects the date string to only use \w chars. The "/" in the default string for `__DATE__ ` causes it to fail. A possible unit test for this would to check whether the platform.py parser accepts the new default string "XXX XX XXXX".

Now, regarding the default string itself, I think it would be better to use a valid date string, since "XXX XX XXXX" will make platform.py's parser happy, but fail to parse as a date string downstream (in code using the platform.py python_build() API). "Jan 01 1970" would work (the Unix epoch).

2025-02-05 23:46 UTC, fosslinux commented
On `main`:

```
$ ./python
Python 3.14.0a4+ (remotes/upstream/main:cdcacec79f, xx/xx/xx, xx:xx:xx) [GCC 14.2.1 20241221] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform._sys_version()
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    platform._sys_version()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/projects/cpython/Lib/platform.py", line 1201, in _sys_version
    raise ValueError(
        'failed to parse CPython sys.version: %s' %
        repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.14.0a4+ (remotes/upstream/main:cdcacec79f, xx/xx/xx, xx:xx:xx) [GCC 14.2.1 20241221]'
```

On this branch:

```
$ ./python
Python 3.14.0a4+ (heads/fix-undefined-date:5d72c723dc, Jan 01 1970, 00:00:00) [GCC 14.2.1 20241221] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform._sys_version()
('CPython', '3.14.0a4+', 'heads/fix-undefined-date', '5d72c723dc', 'heads/fix-undefined-date:5d72c723dc', 'Jan 01 1970 00:00:00', 'GCC 14.2.1 20241221')
```

2025-02-05 23:47 UTC, fosslinux commented
> Now, regarding the default string itself, I think it would be better to use a valid date string, since "XXX XX XXXX" will make platform.py's parser happy, but fail to parse as a date string downstream (in code using the platform.py python_build() API). "Jan 01 1970" would work (the Unix epoch).

No objections to that. Done. Also, to keep it consistent, I changed the default time string from "xx:xx:xx" to "00:00:00" (so now the default is Unix epoch).

2025-03-02 21:38 UTC, malemburg approved these changes
LGTM now. Thanks @fosslinux

2025-03-03 13:42 UTC, malemburg commented
@iritkatriel Are you fine with this now ?

2025-03-03 13:53 UTC, iritkatriel commented
Yes, the bad output was posted in a comment.

2025-03-03 13:54 UTC, iritkatriel approved these changes

2025-03-03 13:59 UTC, merged

2025-03-03 14:00 UTC, malemburg commented
Thanks, @fosslinux