gh-100689: Revert "bpo-41798: pyexpat: Allocate the expat_CAPI on the…
python/cpython pull request #100745
Opened 2023-01-04 08:53 UTC by sobolevn

… heap memory (GH-24061)"

This reverts commit 7c83eaa536d2f436ae46211ca48692f576c732f0.

This would need to be back-ported to 3.10 and 3.11

2023-01-04 09:40 UTC, kumaraditya303 requested changes
Please add a news entry as this is a bug fix.

2023-01-04 09:59 UTC, sobolevn commented
Done! I have made the requested changes; please review again

2023-01-04 17:41 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2023-01-04-12-58-59.gh-issue-100689.Ce0ITG.rst
> +Fix crash in ``_elementtree.c`` by reverting ``GH-24061``.
```suggestion
Fix crash in ``_elementtree.c`` by statically allocating ``PyExpat_CAPI`` capsule. 
```

2023-01-04 17:42 UTC, kumaraditya303 approved these changes

2023-01-04 17:43 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2023-01-04-12-58-59.gh-issue-100689.Ce0ITG.rst
> +Fix crash in ``_elementtree.c`` by statically allocating ``PyExpat_CAPI`` capsule.
```suggestion
Fix crash in ``_elementtree.c`` by statically allocating ``PyExpat_CAPI`` capsule.
```

2023-01-04 22:19 UTC, erlend-aasland commented on Misc/NEWS.d/next/Library/2023-01-04-12-58-59.gh-issue-100689.Ce0ITG.rst
> +Fix crash in ``_elementtree.c`` by statically allocating ``PyExpat_CAPI`` capsule.
I'd use the user visible module name instead of the source file name; the changelog is for users, not core devs :)

2023-01-07 18:09 UTC, SoulReaverFan commented
Thank you so much for your work on fixing this issue. It is very much appreciated 👍

2023-01-08 07:58 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2023-01-04-12-58-59.gh-issue-100689.Ce0ITG.rst
> +Fix crash in ``pyexpat`` by statically allocating ``PyExpat_CAPI`` capsule.
```suggestion
Fix crash in :mod:`pyexpat` by statically allocating ``PyExpat_CAPI`` capsule.
```

2023-01-08 07:58 UTC, kumaraditya303 approved these changes

2023-01-08 10:24 UTC, erlend-aasland approved these changes

2023-01-08 12:54 UTC, merged

2023-01-08 12:54 UTC, miss-islington commented
Thanks @sobolevn for the PR, and @kumaraditya303 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖