gh-100871: Improve `copy` module tests
python/cpython pull request #100872
Opened 2023-01-09 07:35 UTC by sobolevn

CC @AlexWaygood as the reviewer of https://github.com/python/cpython/pull/100818

2023-01-09 08:13 UTC, sobolevn commented
The failure is clearly not related.

2023-01-09 20:23 UTC, hauntsaninja approved these changes
Nice, thank you for this PR! (And good catch on the other PR, Alex!)

2023-01-09 20:23 UTC, hauntsaninja commented on Lib/test/test_slice.py
> +        # Corner case for mutable indicies:
```suggestion
        # Corner case for mutable indices:
```

2023-01-09 20:23 UTC, hauntsaninja commented on Lib/test/test_slice.py
> +        # Corner case for mutable indicies:
```suggestion
        # Corner case for mutable indices:
```

2023-01-09 23:03 UTC, AlexWaygood requested changes
Thanks! Mostly looks good, but two nits below:

2023-01-09 23:03 UTC, AlexWaygood commented on Lib/test/test_slice.py
> +        self.assertIsNot(s, c)
Nit: not sure we need this one. What behaviour or principle does this assertion demonstrate?

You could plausibly have an implementation of `deepcopy` where the exact same object was returned iff it was detected that it didn't contain any references to mutable objects, and I think that would be _fine_ — it's basically what we already do for deepcopying tuples: https://github.com/python/cpython/blob/e098137cd3250af05f19380590b8dec79dc5942f/Lib/copy.py#L200. But that alternative implementation would cause this assertion to fail. Which makes it seem to me like it's not a great assertion :)

```suggestion
```

2023-01-09 23:03 UTC, AlexWaygood commented on Lib/test/test_slice.py
> +        self.assertIsNot(s, c)
Same as above 

```suggestion
```

2023-01-09 23:05 UTC, AlexWaygood commented
> And if you don't make the requested changes, you will be poked with soft cushions!

I have them ready

2023-01-10 08:57 UTC, sobolevn commented on Lib/test/test_slice.py
> +        self.assertIsNot(s, c)
That's what `deepcopy` must do by default: create new identical object. So, generally `is not` rule holds.

There are exceptions to this rule due to performance reasons, but they are special cases and are tested separately. 

In my opinion `is not` here must be present - it checks the main behaviour.

2023-01-11 16:42 UTC, AlexWaygood commented on Lib/test/test_slice.py
> +        self.assertIsNot(s, c)
> In my opinion `is not` assertion here must be present - it checks the main behaviour.

I really disagree. The very fact that we're able to make exceptions to this rule for some special objects indicates that it's _not_ a fundamental invariant that `deepcopy` should always return a different object to the one passed in. It seems to me like we're asserting an implementation detail here, which obscures the intent of the test to the reader.

For example: suppose in the future it was discovered by somebody that this alternative implementation of deepcopying `slice`s vastly improved performance. (I have no idea how it compares, this is just an example.) They submitted a PR with this code: 

```python
def _deepcopy_slice(s):
    if (
        isinstance(s.start, (int, types.NoneType))
        and isinstance(s.stop, (int, types.NoneType))
        and isinstance(s.step, (int, types.NoneType))
    ):
        return s
    return slice.__reduce__(s)
```

This assertion you're introducing here would start failing on this hypothetical patch, for no good reason. That would be highly confusing for the contributor -- they would think that they were violating an invariant, when really their code would be fine!

2023-01-11 16:46 UTC, sobolevn commented on Lib/test/test_slice.py
> +        self.assertIsNot(s, c)
Ok, I don't have strong feelings about this piece of code, so I concure with your reasoning :)

2023-01-11 16:51 UTC, AlexWaygood approved these changes
Thank you!

2023-01-11 17:14 UTC, miss-islington commented
Status check is done, and it's a success ✅.

2023-01-11 17:14 UTC, merged

2023-01-11 17:14 UTC, miss-islington commented
Thanks @sobolevn for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖

2023-01-11 17:14 UTC, miss-islington commented
Sorry @sobolevn, I had trouble checking out the `3.11` backport branch.
                                Please retry by removing and re-adding the "needs backport to 3.11" label.
                                Alternatively, you can backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on the command line.
                                ```
                                cherry_picker 729ab9b622957fef0e9b494af9a71ab02986c741 3.11
                                ```

2023-01-11 17:15 UTC, miss-islington commented
Sorry, @sobolevn, I could not cleanly backport this to `3.10` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 729ab9b622957fef0e9b494af9a71ab02986c741 3.10
                                ```

2023-01-11 17:15 UTC, miss-islington commented
Thanks @sobolevn for the PR 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2023-01-11 17:16 UTC, miss-islington commented
Sorry @sobolevn, I had trouble checking out the `3.11` backport branch.
                                Please retry by removing and re-adding the "needs backport to 3.11" label.
                                Alternatively, you can backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on the command line.
                                ```
                                cherry_picker 729ab9b622957fef0e9b494af9a71ab02986c741 3.11
                                ```

2023-01-11 17:16 UTC, miss-islington commented
Thanks @sobolevn for the PR 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2023-01-11 17:16 UTC, miss-islington commented
Sorry, @sobolevn, I could not cleanly backport this to `3.11` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 729ab9b622957fef0e9b494af9a71ab02986c741 3.11
                                ```

2023-01-11 17:17 UTC, AlexWaygood commented
@sobolevn, would you be able to handle the backports here? :)

2023-01-11 17:17 UTC, sobolevn commented
Yeap, I will add this to my backports queue :)

2023-01-11 17:19 UTC, AlexWaygood commented
Thank you! Ping me for review when you do, and I'll merge them :)