gh-100989: Fix docstrings of `collections.deque`
python/cpython pull request #100990
Opened 2023-01-12 15:17 UTC by timoludwig

See gh-100989 for the issue description.

Thanks in advance for your feedback!

2023-01-12 15:21 UTC, timoludwig commented
> Most changes to Python [require a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
> 
> Please add it using the [blurb_it](https://blurb-it.herokuapp.com) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

In my opinion, it doesn't, but let me know if you think the bot is right.

2023-02-25 08:06 UTC, CAM-Gerlach reviewed
**Standard reminder: You can directly apply all the suggestions you want in one go with [`Files changed`](https://github.com/python/cpython/pull/100990/files) -> <kbd>Add to batch</kbd> -> <kbd>Commit</kbd>**

This change seems to have value overall, as it not only fixes the downstream Sphinx warnings, but is clearer and more explicit as well as more concise and consistent as to the parameter and return types of these methods (per Diataxis for reference docs), and provides much clearer and more detailed descriptions that fill in key missing details as to what the parameters actually do.

I did have a couple minor suggestions, see comments. Also, it would be good for someone familiar with both the docs and the C-API (like @erlend-aasland ) should probably also take a look at it. Thanks!

2023-02-25 08:06 UTC, CAM-Gerlach commented on Modules/_collectionsmodule.c
> +"Reverse the elements of the deque *IN PLACE*.");
Any reason to not do

```suggestion
"reverse()\n\n"
"Reverse the elements of the deque *IN PLACE*.");
```

2023-02-25 08:06 UTC, CAM-Gerlach commented on Modules/_collectionsmodule.c
> +"If n is negative, rotates left.");
This appears to only be a style change, as far as I can tell. Is it really necessary, or can it be reverted?

```suggestion
"Rotate the deque n steps to the right (default n=1).  If n is negative, rotates left.");
```

Or, if we do want to change this, would we not want to include the signature and format `n` appropriately, as with the others?

```suggestion
"rotate(n)\n\n"
"Rotate the deque *n* steps to the right (default ``n= 1``). "
"If *n* is negative, rotates left.");
```

2023-02-25 09:57 UTC, timoludwig commented on Modules/_collectionsmodule.c
> +"Reverse the elements of the deque *IN PLACE*.");
Thanks for the review!
I guess I omitted it initially because it does not add information, but for consistency reasons it totally makes sense.

2023-02-25 10:04 UTC, CAM-Gerlach approved these changes
LGTM from my side from one trivial fix to my own typo. Thanks!

2023-02-25 10:04 UTC, CAM-Gerlach commented on Modules/_collectionsmodule.c
> +"Rotate the deque *n* steps to the right (default ``n= 1``). "
```suggestion
"Rotate the deque *n* steps to the right (default ``n=1``). "
```

Oops—my mistake here, sorry.

2023-03-22 10:19 UTC, erlend-aasland requested changes
Seeing that Raymond (the code owner) specifically requested only the integer => int change to be applied, I think it would better to reduce this PR to that specific change only.

2023-03-22 10:39 UTC, timoludwig commented
> Seeing that Raymond (the code owner) specifically requested only the integer => int change to be applied, I think it would better to reduce this PR to that specific change only.

@erlend-aasland Thanks a lot for your thoughts on this. As explained in https://github.com/python/cpython/issues/100989#issuecomment-1381069788, this suggested change would not solve the Sphinx warning, since Sphinx does not recognize the `--` pattern as separation of type and description. I would open a ticket on Sphinx' side if this code style is somehow a defined standard other projects should respect, but I did not find any resources on this. Do you know more about this, or in general a guideline docstrings should follow?

The smallest possible changes that would resolve the warning would be to also replace `--` by two new lines, do you think this would be justified as well?

I still think that if the [documentation of `PyDoc_STRVAR`](https://docs.python.org/3/c-api/intro.html#c.PyDoc_STRVAR) tells us that we should write the docstrings according to [PEP-7](https://peps.python.org/pep-0007/), we should do one of two things:
1. Actually write the docstrings according to that guideline
2. Or remove that passage from the docs and either require a (newer?) guideline or state that docstrings don't have to follow any specific formatting (in which case I would suggest that we also don't use the signature-like format `function(params) -> return type (but not really)`, because it makes other tools like e.g. Sphinx' [autodoc_docstring_signature](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_docstring_signature) think it's a machine parsable format, which it is not in that case).

2023-03-22 11:20 UTC, erlend-aasland commented
@timoludwig: thanks for the explanation! I'll review it with this in mind.

2023-03-22 11:46 UTC, erlend-aasland approved these changes

2023-03-22 11:46 UTC, merged

2023-03-22 11:47 UTC, miss-islington commented
Thanks @timoludwig for the PR, and @erlend-aasland for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖