GH-101097: Switch from standard interval notation to greater or less than signs for random.random()'s documentation
python/cpython pull request #101119
Opened 2023-01-18 07:29 UTC by novialriptide

Fixes: https://github.com/python/cpython/issues/101097

2023-01-18 08:21 UTC, rhettinger requested changes

2023-01-18 08:21 UTC, rhettinger commented on Doc/library/random.rst
> +   Return the next random floating point number in the range ``0.0 <= x < 1.0``
Please use a capital `X` which is the norm for random variables.

2023-01-18 08:24 UTC, rhettinger commented
Also update the corresponding docstring in `Lib/random.py`.

2023-01-18 15:26 UTC, novialriptide commented
I have made the requested changes; please review again

2023-01-19 06:54 UTC, rhettinger requested changes

2023-01-19 06:54 UTC, rhettinger commented on Lib/random.py
> +        """Return the next random floating point number in the range ``0.0 <= X < 1.0``"""
No backticks here.  This is a docstring and doesn't use markup.

2023-01-19 06:54 UTC, rhettinger commented on Lib/random.py
> +        """Return the next random floating point number in the range ``0.0 <= X < 1.0``"""
Also, let's keep the wording as-is and only change the  interval.  I know it's a little different that the mains but that is okay.

2023-01-19 06:54 UTC, rhettinger commented on Doc/library/random.rst
> +generates a random float uniformly in the semi-open range ``0.0 <= X < 1.0``.
While we're at it, change "semi-open" to "half-open".

2023-01-19 07:35 UTC, novialriptide commented
I have made the requested changes; please review again

2023-01-22 20:58 UTC, rhettinger approved these changes

2023-01-22 20:58 UTC, merged

2023-01-22 20:58 UTC, miss-islington commented
Thanks @novialriptide for the PR, and @rhettinger for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!