Provided better example for logging cookbook (GH-101164)
python/cpython pull request #101164
Opened 2023-01-19 20:28 UTC by galqiwi

This change is trivial, so, according to guidelines, i haven't created an issue.

I just made a small fix to the code from logging cookbook. The rotator function should compress file. And, to compress file, you need to use gzib library, not zlib.

To save you some time, this fact is clearly stated in [zlib docs](https://docs.python.org/3.11/library/zlib.html)
> For reading and writing `.gz` files see the [gzip](https://docs.python.org/3.11/library/gzip.html#module-gzip) module.

2023-01-19 21:57 UTC, vsajip requested changes
While we're doing this, we might as well change this snippet into a runnable script:
```python
import gzip
import logging
import logging.handlers
import os
import shutil

def namer(name):
    return name + '.gz'

def rotator(source, dest):
    with open(source, 'rb') as f_in:
        with gzip.open(dest, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)
    os.remove(source)

rh = logging.handlers.RotatingFileHandler('rotated.log', maxBytes=1024, backupCount=5)
rh.rotator = rotator
rh.namer = namer
root = logging.getLogger()
root.setLevel(logging.INFO)
root.addHandler(rh)
f = logging.Formatter('%(asctime)s %(message)s')
rh.setFormatter(f)
for i in range(1000):
    root.info(f'Message no. {i + 1}')
```
and show that it seems to work:
```
$ gzip -dc rotated.log.1.gz | head -n 5
2023-01-19 21:55:12,677 Message no. 955
2023-01-19 21:55:12,678 Message no. 956
2023-01-19 21:55:12,678 Message no. 957
2023-01-19 21:55:12,678 Message no. 958
2023-01-19 21:55:12,709 Message no. 959
```

2023-01-19 23:40 UTC, galqiwi commented
I have made the requested changes; please review again

2023-01-20 08:45 UTC, vsajip commented on Doc/howto/logging-cookbook.rst
> +snippet, which shows gzip compression of the log file::
```suggestion
runnable script, which shows gzip compression of the log file::
```

2023-01-20 08:46 UTC, vsajip approved these changes

2023-01-20 08:54 UTC, merged

2023-01-20 08:55 UTC, miss-islington commented
Thanks @galqiwi for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖

2023-01-20 08:55 UTC, miss-islington commented
Thanks @galqiwi for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2023-01-20 15:46 UTC, vsajip commented
@galqiwi : Thanks for this patch, now merged, but you signed the CLA using your `@yandex-team.ru`. However, this information was lost when the PR was squashed and merged, and the backport PRs can't be merged because they only have your GitHub profile email address `galqiwi@galqiwi.ru`, which is not recorded as having signed the CLA. Can you please sign the CLA again, but using your `@galqiwi.ru` email? Thanks!