GH-84783: Make the slice object hashable
python/cpython pull request #101264
Opened 2023-01-23 20:08 UTC by furkanonder

2023-02-05 21:17 UTC, rhettinger requested changes

2023-02-05 21:17 UTC, rhettinger commented on Objects/sliceobject.c
> +/* code based on tuplehash() of Objects/tupleobject.c */
This is all nice work; however, a simpler solution will suffice.

```
def slice_hash(s):
    # Multiply by two randomly chosen primes
    return hash(s.start) * 314898481 | hash(s.stop) * 4822421 | hash(s.step)
```

2023-02-05 21:40 UTC, rhettinger commented on Objects/sliceobject.c
> +/* code based on tuplehash() of Objects/tupleobject.c */
After more thought, I think we can leave your version as-is.  If someone wants to propose a simplification and test collision rates, they can do so at a later time.  It is reasonable to stick with the known solution.

2023-02-05 21:40 UTC, rhettinger approved these changes

2023-02-05 21:42 UTC, rhettinger requested changes
We do need to add a NEWS blurb and a `versionchanged` entry to the docs.

2023-02-05 21:44 UTC, rhettinger commented
We're getting some test failures:

```
======================================================================
[3683](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3684)
ERROR: test_sequence_del_slice (test.test_capi.test_misc.CAPITest.test_sequence_del_slice)
[3684](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3685)
----------------------------------------------------------------------
[3685](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3686)
Traceback (most recent call last):
[3686](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3687)
  File "/Users/runner/work/cpython/cpython/Lib/test/test_capi/test_misc.py", line 459, in test_sequence_del_slice
[3687](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3688)
    _testcapi.sequence_del_slice(mapping, 1, 3)
[3688](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3689)
KeyError: slice(1, 3, None)
[3689](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3690)

[3690](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3691)
======================================================================
[3691](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3692)
FAIL: test_sequence_set_slice (test.test_capi.test_misc.CAPITest.test_sequence_set_slice)
[3692](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3693)
----------------------------------------------------------------------
[3693](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3694)
Traceback (most recent call last):
[3694](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3695)
  File "/Users/runner/work/cpython/cpython/Lib/test/test_capi/test_misc.py", line 419, in test_sequence_set_slice
[3695](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3696)
    with self.assertRaises(TypeError):
[3696](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3697)
AssertionError: TypeError not raised
[3697](https://github.com/python/cpython/actions/runs/4006251040/jobs/6877559173#step:7:3698)
```

2023-02-05 21:45 UTC, rhettinger commented on Objects/sliceobject.c
> +#define _PyHASH_SLICE_PART(com) { \
It would look nicer if this macro were replaced with a `static inline function`.

2023-02-11 23:24 UTC, OTheDev commented on Lib/test/test_slice.py
> +        self.assertNotEqual(slice(5), slice(6))
Can we add more tests here?

For example, test that `hash(slice(1, 2, []))` raises `TypeError` (to test the portion of the code where `PyObject_Hash()` fails).

2023-02-11 23:29 UTC, OTheDev commented on Lib/test/test_slice.py
> +        self.assertNotEqual(slice(5), slice(6))
I think there should also be tests for the multiple argument forms of `slice()` (:

2023-02-12 01:38 UTC, OTheDev commented on Doc/library/functions.rst
> +   .. versionchanged:: 3.10
I don't think this can be backported?

2023-02-12 01:54 UTC, OTheDev commented on Doc/library/functions.rst
> +   .. versionchanged:: 3.10
```suggestion
   .. versionchanged:: 3.12
      Slice objects are now :term:`hashable` (provided :attr:`~slice.start`,
      :attr:`~slice.stop`, and :attr:`~slice.step` are hashable).
```

2023-02-12 23:02 UTC, furkanonder commented on Lib/test/test_slice.py
> +        self.assertNotEqual(slice(5), slice(6))
I added some test cases. Please do not hesitate to write if any other situations come to mind. Thank you so much for your wonderful feedback and contributions!

2023-02-13 14:00 UTC, OTheDev commented on Lib/test/test_slice.py
> +        self.assertNotEqual(slice(5), slice(6))
Thanks! I suggest removing these two lines.

Comparison of slice objects and comparisons of tuple hashes can be left to `test_cmp()` and `test_tuple.py`, respectively.

2023-02-13 19:09 UTC, furkanonder commented on Lib/test/test_slice.py
> +        self.assertNotEqual(slice(5), slice(6))
It make sense. Thanks!

2023-02-13 21:06 UTC, OTheDev commented on Lib/test/test_slice.py
> +        self.assertNotEqual(slice(5), slice(6))
Why test this (line 86)? Isn't that what `test_cmp()` is for?

2023-02-19 00:22 UTC, merged