GH-90744: Fix erroneous doc links in the sys module
python/cpython pull request #101319
Opened 2023-01-25 14:58 UTC by furkanonder

2023-01-26 16:07 UTC, hugovk commented
This removes the bad links, but they're no longer formatted as code:

<table>
<tr>
	<th>Before
	<th>After
<tr>
	<td>
<img width="781" alt="image" src="https://user-images.githubusercontent.com/1324225/214884936-a3663166-7a91-46f3-be48-f3a18c168e54.png">
	<td>
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1324225/214881776-7b110eb2-8797-46af-a7d2-a65e63d51001.png">
<tr>
    <td><a href="https://docs.python.org/3.12/library/sys.html#sys.float_info">https://docs.python.org/3.12/library/sys.html#sys.float_info</a>
    <td><a href="https://deploy-preview-101319--python-cpython-preview.netlify.app/library/sys.html#sys.float_info">https://deploy-preview-101319--python-cpython-preview.netlify.app/library/sys.html#sys.float_info</a>
</table>


And when running Sphinx in nit-picky mode (re: https://github.com/python/cpython/issues/101100), we're getting warnings about all of those:

```
Doc/library/sys.rst:14: WARNING: py:const reference target not found: epsilon
Doc/library/sys.rst:19: WARNING: py:const reference target not found: dig
Doc/library/sys.rst:22: WARNING: py:const reference target not found: mant_dig
Doc/library/sys.rst:27: WARNING: py:const reference target not found: max_exp
Doc/library/sys.rst:30: WARNING: py:const reference target not found: max_10_exp
Doc/library/sys.rst:39: WARNING: py:const reference target not found: min_exp
Doc/library/sys.rst:42: WARNING: py:const reference target not found: min_10_exp
Doc/library/sys.rst:45: WARNING: py:const reference target not found: radix
Doc/library/sys.rst:47: WARNING: py:const reference target not found: rounds
```

So shall we change all of them like this?

```diff
-    :const:`max`
+    ``max``
```

And we could also do the macros too, although that will also require adjusting the column width:

```diff
-    DBL_MAX
+    ``DBL_MAX``
```

2023-02-01 10:10 UTC, furkanonder commented
> This removes the bad links, but they're no longer formatted as code:
> 
> Before	After
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/1324225/214884936-a3663166-7a91-46f3-be48-f3a18c168e54.png">	<img alt="image" width="780" src="https://user-images.githubusercontent.com/1324225/214881776-7b110eb2-8797-46af-a7d2-a65e63d51001.png">
> https://docs.python.org/3.12/library/sys.html#sys.float_info	https://deploy-preview-101319--python-cpython-preview.netlify.app/library/sys.html#sys.float_info
> And when running Sphinx in nit-picky mode (re: #101100), we're getting warnings about all of those:
> 
> ```
> Doc/library/sys.rst:14: WARNING: py:const reference target not found: epsilon
> Doc/library/sys.rst:19: WARNING: py:const reference target not found: dig
> Doc/library/sys.rst:22: WARNING: py:const reference target not found: mant_dig
> Doc/library/sys.rst:27: WARNING: py:const reference target not found: max_exp
> Doc/library/sys.rst:30: WARNING: py:const reference target not found: max_10_exp
> Doc/library/sys.rst:39: WARNING: py:const reference target not found: min_exp
> Doc/library/sys.rst:42: WARNING: py:const reference target not found: min_10_exp
> Doc/library/sys.rst:45: WARNING: py:const reference target not found: radix
> Doc/library/sys.rst:47: WARNING: py:const reference target not found: rounds
> ```
> 
> So shall we change all of them like this?
> 
> ```diff
> -    :const:`max`
> +    ``max``
> ```
> 
> And we could also do the macros too, although that will also require adjusting the column width:
> 
> ```diff
> -    DBL_MAX
> +    ``DBL_MAX``
> ```

Changing ``` :const:`max` ``` to ``` ``max`` ``` made sense to me. The gray background behind the texts, in my opinion, makes the words stand out more. We can also make these corrections for other words in the documents.

2023-02-21 12:52 UTC, hugovk requested changes
Marking as changes requested, re: https://github.com/python/cpython/pull/101319#issuecomment-1405239460

2023-02-27 13:26 UTC, hugovk approved these changes
Looks good now, and the warnings fixed 👍 

![image](https://user-images.githubusercontent.com/1324225/221575439-3655bc1f-411f-432e-b43b-d7d059881412.png)

https://deploy-preview-101319--python-cpython-preview.netlify.app/library/sys.html#sys.float_info

Thanks!

2023-02-27 13:29 UTC, hugovk reviewed
Actually, one last little thing :)

2023-02-27 13:29 UTC, hugovk commented on Doc/library/sys.rst
> +   |                     |                     | value of the system FLT_ROUNDS macro at          |
```suggestion
   |                     |                     | value of the system ``FLT_ROUNDS`` macro at      |
```

2023-02-27 13:29 UTC, hugovk commented on Doc/library/sys.rst
> +   |                     |                     | All other values for FLT_ROUNDS characterize     |
```suggestion
   |                     |                     | All other values for ``FLT_ROUNDS`` characterize |
```

2023-02-28 11:43 UTC, merged

2023-02-28 11:43 UTC, miss-islington commented
Thanks @furkanonder for the PR, and @hugovk for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖

2023-02-28 11:43 UTC, hugovk commented
Thank you!

2023-02-28 11:43 UTC, miss-islington commented
Sorry, @furkanonder and @hugovk, I could not cleanly backport this to `3.11` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 85b1fc1fc5a2e49d521382eaf5e7793175d00371 3.11
                                ```

2023-02-28 11:43 UTC, miss-islington commented
Sorry @furkanonder and @hugovk, I had trouble checking out the `3.10` backport branch.
                                Please retry by removing and re-adding the "needs backport to 3.10" label.
                                Alternatively, you can backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on the command line.
                                ```
                                cherry_picker 85b1fc1fc5a2e49d521382eaf5e7793175d00371 3.10
                                ```