gh-101317: Add ssl_shutdown_timeout parameter for StreamWriter.start_tls()
python/cpython pull request #101335
Opened 2023-01-26 00:58 UTC by beavailable

* Issue: [](https://github.com/python/cpython/issues/101317) #101317

2023-01-31 13:11 UTC, kumaraditya303 requested changes
You need to add this param to docs with a version changed directive.

2023-02-01 01:38 UTC, beavailable commented
I have made the requested changes; please review again.

2023-02-01 10:28 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2023-01-26-01-25-56.gh-issue-101317.vWaS1x.rst
> +Add ``ssl_shutdown_timeout`` parameter for ``StreamWriter.start_tls()``.
```suggestion
Add *ssl_shutdown_timeout* parameter for :meth:`asyncio.StreamWriter.start_tls()`.

```

2023-02-01 10:32 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2023-01-26-01-25-56.gh-issue-101317.vWaS1x.rst
> +Add *ssl_shutdown_timeout* parameter for :meth:`asyncio.StreamWriter.start_tls()`.
```suggestion
Add *ssl_shutdown_timeout* parameter for :meth:`asyncio.StreamWriter.start_tls`.
```

2023-02-01 10:39 UTC, kumaraditya303 approved these changes

2023-02-01 11:04 UTC, merged

2023-02-01 11:04 UTC, kumaraditya303 commented
Thanks.