gh-101892 : Updated Cython/objects/iterobject.c Line 217
python/cpython pull request #101896
Opened 2023-02-14 09:04 UTC by workingpayload

Updated Cython/objects/iterobject.c Line 217

2023-02-14 09:14 UTC, Eclips4 commented
It's good to coverage this case in tests.

2023-02-14 19:21 UTC, arhadthedev commented
Added a test copied from the issue with readability changes.

2023-02-15 04:59 UTC, OTheDev commented on Objects/iterobject.c
> +    if (result != NULL && it->it_callable != NULL) {
Sorry, but this won't fix it. Notice the first `if` statement in the function. If `it->it_callable == NULL` is true, `NULL` is returned. So `it->it_callable != NULL` is already guaranteed at this point.

2023-02-15 05:04 UTC, workingpayload commented on Objects/iterobject.c
> +    if (result != NULL && it->it_callable != NULL) {
What if we check it->it_sentinel != NULL ?

2023-02-15 06:02 UTC, OTheDev reviewed
It looks like `NULL` is being passed to `PyObject_RichCompareBool()` through `it->it_sentinel` when it expects an object?

If we add the check

```C
if (result != NULL && it->it_sentinel != NULL) {
```

and get rid of that `Py_DECREF(result)` and place a new

```C
Py_XDECREF(result);
```

just before `return NULL;`

Then the code in the issue will raise a `StopIteration` (no longer `SystemError`) and tests pass.

I'm not entirely sure if this is correct, TBH, but this is my guess.

2023-02-15 06:03 UTC, OTheDev commented on Lib/test/test_iter.py
> +        next(spam.iterator)
What's the expected behaviour here? `StopIteration`?

2023-02-15 07:07 UTC, arhadthedev commented on Lib/test/test_iter.py
> +        next(spam.iterator)
Thank you for noticing the oversight! Fixed.

2023-02-15 07:15 UTC, workingpayload commented
> @workingpayload What do you think? Worth a try?

Yeah! Why not?

2023-02-15 08:04 UTC, arhadthedev commented on Lib/test/test_iter.py
> +                list(spam.iterator) # Implicitly call ourselves
This evening (after getting access to my dev machine) I'll check whether the inner `list()` is required to throw `StopIteration` to trigger the bug. If no, I will simplify the test:

```suggestion
                try:
                    list(spam.iterator) # Implicitly call ourselves.
                except StopIteration:
                    pass
```

2023-02-15 18:21 UTC, arhadthedev commented on Lib/test/test_iter.py
> +                list(spam.iterator) # Implicitly call ourselves
I confirmed that `SystemError` on the top level is thrown both with and without propagation of `StopIteration` from the bottom level. So I'm applying the change.

2023-02-15 18:23 UTC, arhadthedev commented on Lib/test/test_iter.py
> +                list(spam.iterator) # Implicitly call ourselves
I got it wrong. `list()` cannot throw an exception because it returns a ready-to-use list (possibly empty) processing `StopIteration` by itself.

2023-02-15 22:14 UTC, furkanonder approved these changes

2023-02-15 22:23 UTC, furkanonder commented
LGTM. By the way PR title can be more meaningful. Ex: Fix SystemError when a callable iterator call exhausts the iterator.

2023-02-16 05:23 UTC, workingpayload commented
> LGTM. By the way PR title can be more meaningful. Ex: Fix SystemError when a callable iterator call exhausts the iterator.

Okay!
Thanks for the suggestion.

2023-02-16 05:33 UTC, arhadthedev approved these changes
Tests are green here and expectedly fails on `main`.

2023-02-16 05:43 UTC, arhadthedev commented
@vstinner would you mind reviewing and possibly merging this PR, please?

2023-03-04 07:20 UTC, kumaraditya303 requested changes
There are merge conflicts.

2023-03-04 10:02 UTC, arhadthedev commented
@kumaraditya303 I have made the requested changes; please review again

2023-03-04 10:18 UTC, kumaraditya303 commented on Lib/test/test_iter.py
> +    # Test two-argument iter() with function that exhausts its
Comment should be in function body with link to issue

2023-03-04 10:18 UTC, kumaraditya303 commented on Lib/test/test_iter.py
> +def exhaust(iterator):
Inline this in the test itself

2023-03-04 11:34 UTC, arhadthedev commented
@kumaraditya303 Thank you, addressed.

2023-03-04 14:18 UTC, kumaraditya303 approved these changes

2023-03-04 14:21 UTC, merged

2023-03-04 14:21 UTC, miss-islington commented
Thanks @workingpayload for the PR, and @kumaraditya303 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2023-03-04 14:21 UTC, miss-islington commented
Sorry, @workingpayload and @kumaraditya303, I could not cleanly backport this to `3.10` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 705487c6557c3d8866622b4d32528bf7fc2e4204 3.10
                                ```