expand the warning about untrusted archives in the `tarfile` docs
python/cpython pull request #101812
Opened 2023-02-10 23:23 UTC by oconnor663

The current warning mentions one class of attacks, but there's at least one other major class that relies on links. Are there other classes? If so we should probably add something like "This list is not exhaustive; do not try to solve this problem yourself."

2023-02-17 19:06 UTC, arhadthedev commented
The pull request seems good so we just need to wait until a few core developers get here via their lines of requested reviews, new issues and PRs.

Unfortunately, the tarfile module has nobody separately assigned so I cannot call someone out-of-order.

2023-02-21 20:13 UTC, ethanfurman requested changes

2023-02-21 20:13 UTC, ethanfurman commented on Doc/library/tarfile.rst
> +      *path*, and that a subsequent member might write through the link.
Please change the entire paragraph to:

```
      Never extract archives from untrusted sources without prior inspection.
      It is possible for files to be created or written to outside of *path*.
      Some examples include members that have absolute or relative filenames
      that are not in the current path, and symbolic or hard links pointing
      outside of *path*.
```

2023-04-05 05:40 UTC, oconnor663 commented
@ethanfurman updated as you suggested.

2023-04-05 05:41 UTC, oconnor663 commented
I have made the requested changes; please review again.

2025-07-29 17:08 UTC, StanFromIreland commented
Thanks for the contribution, however, the default behavior and docs have been since changed, and this PR is no longer necessary.

2025-07-29 17:08 UTC, closed without merging