gh-102069: Fix `__weakref__` descriptor generation for custom dataclasses
python/cpython pull request #102075
Opened 2023-02-20 13:50 UTC by sobolevn

Since we recreate a class, we have a descriptor from a previous type. This is why `check_descr` fails.

2023-03-11 08:36 UTC, sobolevn commented
@carljm maybe you will be interested in this PR as well? :)

2023-03-13 20:45 UTC, carljm requested changes
One typo in the added comment, otherwise this LGTM.

2023-03-13 20:45 UTC, carljm commented on Lib/dataclasses.py
> +    # Clear exiting `__weakref__` descriptor, it belongs to a previous type:
```suggestion
    # Clear existing `__weakref__` descriptor, it belongs to a previous type:
```

2023-03-13 21:01 UTC, carljm approved these changes
Oops, just remembered that I can make trivial fixes to the PR myself :)

2023-03-13 21:42 UTC, merged

2023-03-13 21:42 UTC, miss-islington commented
Thanks @sobolevn for the PR, and @carljm for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2023-03-13 21:42 UTC, carljm commented
Thanks for the fix!