bpo-34945: Buffer output in test suite only when creating junit file
python/cpython pull request #10204
Opened 2018-10-28 22:56 UTC by pablogsal

After commit d0f49d2f5085ca68e3dc8725f1fb1c9674bfb5ed, the output of the
test suite is always buffered as the test output needs to be included in
the JUnit file in same cases (as when a test fails). This has the
consequence that printing or using debuggers (like pdb) in the test
suite does not result in a good user experience anymore.

This commit modifies the test suite runner so it only captures the test
output when the JUnit file is requested to fix the regression so prints
and debuggers are usable again.

CC: @matrixise

2018-10-28 23:09 UTC, pablogsal commented
Hummm..... there is a problem when the test fail as the capture is expected. I am fixing this.

2018-10-28 23:20 UTC, vstinner commented on Lib/test/support/testresult.py
> +            if self._stderr_buffer:
Stdout?

2018-10-28 23:24 UTC, pablogsal commented on Lib/test/support/testresult.py
> +            if self._stderr_buffer:
Ups! I forgot to add that file when pushing the latest fix

2018-10-29 10:33 UTC, zooba approved these changes

2018-10-29 13:58 UTC, vstinner requested changes
It doesn't work for me: I don't see my print(). It works before the JUnit change.

```
vstinner@apu$ ./python -m test test_os
Run tests sequentially
0:00:00 load avg: 0.34 [1/1] test_os
git dif
== Tests result: SUCCESS ==

1 test OK.

Total duration: 1 sec 436 ms
Tests result: SUCCESS
vstinner@apu$ git diff
diff --git a/Lib/test/test_os.py b/Lib/test/test_os.py
index 3f6e48f0c8..716b079a21 100644
--- a/Lib/test/test_os.py
+++ b/Lib/test/test_os.py
@@ -99,6 +99,7 @@ class FileTests(unittest.TestCase):
 
     def test_access(self):
         f = os.open(support.TESTFN, os.O_CREAT|os.O_RDWR)
+        print("test_access")
         os.close(f)
         self.assertTrue(os.access(support.TESTFN, os.W_OK))
```

2018-10-29 14:21 UTC, pablogsal commented
Can you run it in verbose mode?

2018-10-29 14:23 UTC, pablogsal commented
@vstinner Can your run it in verbose mode?

    ./python -m test test_os -v

2018-10-29 14:35 UTC, pablogsal commented
@vstinner @matrixise Commit 0735296 should fix this :)

2018-10-29 15:05 UTC, pablogsal commented
I am working to fix the test suite errors

2018-10-29 16:35 UTC, pablogsal commented
I have made the requested changes; please review again

2018-10-29 18:16 UTC, vstinner approved these changes
LGTM. The functional test now works as expected: adding print("XXX") now displays XXX in stdout ;-)

Just a minor suggestion.

2018-10-29 18:16 UTC, vstinner commented on Lib/test/support/testresult.py
> +            if self._stdout_buffer:
Maybe use "is not None"?

2018-10-29 20:09 UTC, merged

2018-10-29 20:31 UTC, vstinner commented
Since JUnit has been added to other branches, this change should be ported to other branches, no?

2018-10-29 20:46 UTC, miss-islington commented
Thanks @pablogsal for the PR 🌮🎉.. I'm working now to backport this PR to: 3.6.
🐍🍒⛏🤖

2018-10-29 20:46 UTC, miss-islington commented
Thanks @pablogsal for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!