gh-101961 Do not pass encoding if binary mode
python/cpython pull request #102068
Opened 2023-02-20 09:49 UTC by ghkim3221

* `fileinput.hook_compressed`  doesn't pass `encoding` if the given `mode` contains `b`.

2023-02-20 10:24 UTC, corona10 commented
@ghkim3221 Please add the NEWS.d by using blurb tool :)

2023-02-20 10:38 UTC, corona10 requested changes
You can verify the encoding at this line if the user assigns the encoding explicitly.
The correct error should be raised.
https://github.com/python/cpython/blob/b1b375e2670a58fc37cb4c2629ed73b045159918/Lib/fileinput.py#L402-L403

2023-02-20 10:57 UTC, corona10 commented on Misc/ACKS
> +Gihwan Kim
It looks like you have to move up the name to the following order.
````
Gihwan Kim
Jan Kim
Taek Joo Kim
````

2023-02-21 01:25 UTC, corona10 commented on Lib/test/test_fileinput.py
> -
Please revert the unrelated change :)

2023-02-21 02:02 UTC, ghkim3221 commented on Lib/test/test_fileinput.py
> -
Oh, thank you

2023-02-21 02:18 UTC, corona10 commented on Misc/NEWS.d/next/Library/2023-02-21-10-05-33.gh-issue-101961.7e56jh.rst
> +``locale`` if the given ``mode`` contains ``b``.
```suggestion
For the binary mode,  :func:`file input.hookcompressed` doesn't set the ``encoding`` value
even if the value is ``None``. Patch by Gihwan Kim.
```

2023-02-21 02:27 UTC, corona10 commented
@ghkim3221 Did you sign up for the CLA?

2023-02-21 02:34 UTC, corona10 approved these changes
LGTM.
I verified several things in the local environment too.
Thanks for the hard work @ghkim3221 !!

2023-02-21 02:34 UTC, ghkim3221 commented
@corona10 Yes, I signed in. Yesterday, Internal Server Error was returned but the badge was changed to signed.

2023-02-21 02:45 UTC, corona10 commented on Misc/NEWS.d/next/Library/2023-02-21-10-05-33.gh-issue-101961.7e56jh.rst
> +For the binary mode,  :func:`file input.hookcompressed` doesn't set the ``encoding`` value
```suggestion
For the binary mode, :func:`fileinput.hookcompressed` doesn't set the ``encoding`` value
```

2023-02-21 03:10 UTC, merged

2023-02-21 03:10 UTC, miss-islington commented
Thanks @ghkim3221 for the PR, and @corona10 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖