Sync `__new__` sigs of `_CRLock` and `_PyRLock` in `threading`
python/cpython pull request #102071
Opened 2023-02-20 12:46 UTC by sobolevn

I hope that this is not really a breaking change. Here's my reasoning:
1. `_PyRLock` was the first one (since python2). People are familiar with it: and it signatures was always correct
2. Since passing values never made any sense, I hope nobody does rely on it
3. Subclasses still work correctly, eventhough they are not really recommened (and `RLock` is exposed as a function)
4. `typeshed` always had `RLock` defined as `() -> RLock` with no complains: https://github.com/python/typeshed/blob/40d853cbe239bcf1479e25c2c59615158b672610/stdlib/threading.pyi#L115-L122
5. I was not able to find any references to `RLock` with arguments

As the next step, I will propose to deprecate the Python version.

2023-03-11 11:43 UTC, sobolevn commented
@pablogsal friendly ping :)

2023-05-29 00:16 UTC, gpshead reviewed
This makes sense to me, but I want to run it through a huge pile of tests at work just to see what - if any - oddball code was relying on passing ignored values. I hope nothing. I'll do that this week.

2023-05-29 08:05 UTC, sobolevn commented
Thank you! In the meantime, I will change the `What's new` entry.

2023-05-30 21:16 UTC, gpshead commented
note to self: I included this PR in an internal test run today, I'll have results by tonight/tomorrow.

2023-05-31 20:21 UTC, gpshead requested changes

2023-05-31 20:21 UTC, gpshead commented on Doc/whatsnew/3.13.rst
> +  but they were just ignored. Python version never allowed any arguments.
This statement isn't accurate; Python <= 2.7 and 3.1 accepted a single undocumented `verbose` argument.

2023-05-31 20:21 UTC, gpshead commented on Lib/threading.py
> +def RLock():
Lets do a regular DeprecationWarning API change cycle on this.

```
if args or kwargs:
    warnings.warn(DeprecationWarning, ...)
```

we can put that in 3.12 remove the ignored args/kwargs in 3.14.

2023-06-01 07:05 UTC, sobolevn commented on Lib/threading.py
> +def RLock():
I thought that 3.12 is now only accepting bugfixes, isn't it? I would prefer to have this change as safe as possible and to put it in 3.13+. Unless you insist :)

2023-06-01 07:34 UTC, sobolevn commented
I have made the requested changes; please review again

2023-06-01 07:35 UTC, sobolevn commented on Doc/whatsnew/3.13.rst
>  Optimizations
```suggestion
Optimizations
```

2023-08-11 08:38 UTC, sobolevn commented
@gpshead now this is deprecated in 3.13 and stated to be changed in 3.15 :)

2023-08-11 14:22 UTC, ambv commented
Closing and re-opening to retrigger CLA checks. Sorry for the noise.

2023-08-11 19:30 UTC, gpshead approved these changes

2023-08-11 20:39 UTC, sobolevn commented
Thanks everyone! CI is now green :)

2023-08-17 07:18 UTC, sobolevn commented
Can someone please click "merge"? :)

2023-08-17 16:19 UTC, merged