gh-102120: Added an iter function that doesn't cache
python/cpython pull request #102128
Opened 2023-02-21 20:25 UTC by PurityLake

Refers to #102120

This is a proposed solution to the linked issue which is to provide a way to iterate over a tar object so that it doesn't cache.

My suggestion is to reuse the code from `Tarfile._next()` to yield a tarinfo each time instead of caching it. This way it doesn't take up a tonne of memory.

I am looking for feedback on this so I will mark this as a draft.

2023-02-22 02:50 UTC, ethanfurman commented
I would rather add a new keyword to the `TarFile` signature -- perhaps `stream` -- and update the relevent locations in the code to not update `members`.

2023-02-22 10:26 UTC, PurityLake commented
That would probably be better

2023-02-26 19:58 UTC, PurityLake commented
I'll be adding some tests later today

2023-03-14 16:20 UTC, PurityLake commented
I believe this is working as intended now. I'm open to criticism in the implementation

2023-05-23 20:06 UTC, ethanfurman commented on Doc/library/tarfile.rst
> +      The *stream* parameter has been added.
```suggestion
   .. versionchanged:: 3.13
      Add the *stream* parameter.
```

2023-05-23 20:08 UTC, ethanfurman requested changes
Overall, looks good.  I missed feature-freeze, though, so this will have to go in 3.13.  Update the `3.12`s to `3.13`s and I'll get it merged.

2023-05-23 20:15 UTC, PurityLake commented
I have made the requested changes; please review again

2023-05-23 20:17 UTC, ethanfurman approved these changes

2023-05-23 20:44 UTC, merged