gh-62480: Remove first-person usage for some docs
python/cpython pull request #102295
Opened 2023-02-27 13:28 UTC by nw0

Additionally: clean up the text explanation for one mock example which this commit touches.

2023-03-07 14:31 UTC, bumper-furkan-onder approved these changes

2023-03-07 14:32 UTC, furkanonder approved these changes

2024-11-14 05:05 UTC, hauntsaninja requested changes
I'm not sure this is an improvement. It also introduces a typo

2025-07-19 10:09 UTC, RafaelWO commented
Hey @nw0, do you mind if I pick this up? :slightly_smiling_face: 

Except if @hauntsaninja thinks it should be closed?

2025-07-19 14:30 UTC, nw0 commented
> Hey @nw0, do you mind if I pick this up? 🙂

Please do. I'm going to close this PR, as it's not had meaningful feedback.

2025-07-19 14:30 UTC, closed without merging