GH-102341: Improve the test function for pow
python/cpython pull request #102342
Opened 2023-02-28 21:37 UTC by ppmfloss

Currently in the powtest function in Lib/test/test_pow.py file we are not testing the results of calling pow with negative exponents.
This PR will add appropriate assert statements to test the results of calling pow with negative exponents.

2023-02-28 23:00 UTC, terryjreedy commented
Mark and Raymond, a one-line addition to test_pow that looks plausible but I am not sure.

Pipelines win32 failure is unrelated of type seen before.

2023-03-01 19:36 UTC, mdickinson commented
Thanks for the ping, @terryjreedy. I'll take a look this weekend.

2023-03-04 09:00 UTC, mdickinson approved these changes
LGTM. Can we drop the `for othertype in (int,):` outer loop while we're here? (I'm guessing that it stems from Python 2 days, and was originally spelled `for othertype in (int, long):`.

2023-03-04 18:15 UTC, terryjreedy requested changes

2023-03-04 18:15 UTC, terryjreedy commented on Lib/test/test_pow.py
>                          jj = -othertype(j)
```suggestion
                for jj in range(-10, 0):
```

2023-03-04 18:15 UTC, terryjreedy commented on Lib/test/test_pow.py
> +                    inv = pow(ii, -1) # inverse of ii
```suggestion
            for i in list(range(-10, 0)) + list(range(1, 10)):
                ii = type(i)
                inv = pow(ii, -1) # inverse of ii
```

2023-03-04 18:15 UTC, terryjreedy commented on Lib/test/test_pow.py
>              for othertype in (int,):
Mark is correct: (int,) used to be (int, float). If this line is deleted, other changes below must be applied.  For some reason, I could not make them all at once.
```suggestion
```

2023-03-04 18:19 UTC, terryjreedy commented
Please recheck after deletion, dedent, and condensation.

2023-03-04 20:28 UTC, ppmfloss commented
I have removed some indentation spaces and retested it locally successfully.

2023-03-05 09:27 UTC, mdickinson approved these changes
LGTM!

2023-03-05 17:31 UTC, merged

2023-03-05 17:31 UTC, miss-islington commented
Thanks @ppmfloss for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖