gh-102302 Make Parameter.__hash__ use the actual values r.t properties
python/cpython pull request #102303
Opened 2023-02-27 15:56 UTC by Gouvernathor

Aligns it with __eq__, enables default properties in subclasses to access hash(self), quickens execution.

2023-02-28 11:17 UTC, sobolevn approved these changes
It is now consistent with `__eq__` and `__reduce__`. LTGM.

2023-02-28 12:26 UTC, AlexWaygood reviewed
I'm a little more sceptical about this change; I've posted some questions on the issue.

> No news because imho it's more akin to a fix than to a new feature.

Every change that has a user-visible impact (whether it's a bug fix, performance optimisation or feature) needs to have a news entry. If this change _doesn't_ have a user-visible impact, we need to ask why it's worth making this change at all.

2023-03-03 18:59 UTC, AlexWaygood commented
Closing; see discussion on the issue for the rationale

2023-03-03 19:37 UTC, sobolevn commented
I still think that this is a good idea: using properties here does not make any practical sense.

And direct attribute access is slightly faster.

2023-03-03 19:42 UTC, AlexWaygood commented
If somebody can give a benchmark showing a meaningful performance improvement here, I'm happy to reconsider, but the motivation put forward in the issue was not primarily to do with performance. I don't find the rationale in the issue convincing, and I also don't consider an argument to do with "consistency" a strong enough reason to make a change to the stdlib.

This doesn't really fix anything I'd consider a user-visible bug (and if it does, it needs a test/NEWS), so I can't see how it's worth the code churn.

2023-03-03 22:01 UTC, sobolevn commented
@AlexWaygood here are my micro-benchmarks.

Old code (`hash((self_name, self.kind, self.annotation, self.default))`):

```
(.venv) ~/Desktop/cpython  main ✗                                                    
» pyperf timeit --setup 'import inspect; p = inspect.Parameter("p", inspect.Parameter.POSITIONAL_ONLY, default=4567890, annotation=int)' 'hash(p)'
.....................
Mean +- std dev: 1.87 us +- 0.16 us
```

New code (`hash((self_name, self._kind, self._annotation, self._default))`):

```
(.venv) ~/Desktop/cpython  main ✗                                                    
» pyperf timeit --setup 'import inspect; p = inspect.Parameter("p", inspect.Parameter.POSITIONAL_ONLY, default=4567890, annotation=int)' 'hash(p)'
.....................
Mean +- std dev: 1.05 us +- 0.05 us
```

I think that the speed-up is quite big for just 4 chars of code :)

2023-03-04 01:33 UTC, AlexWaygood requested changes
Please add a short news entry. Something like this should suffice:

```
Micro-optimise ``inspect.Parameter.__hash__``, reducing the time it takes to hash an instance by around 40%.
```

2023-03-04 14:42 UTC, Gouvernathor commented
So, my overriding the default property will happen to work in the next version, but not be considered a documented feature and could break in future versions without warning ? Just asking to be sure we're on the same page.

2023-03-04 14:45 UTC, AlexWaygood commented
> So, my overriding the default property will happen to work in the next version, but not be considered a documented feature and could break in future versions without warning ? Just asking to be sure we're on the same page.

Correct -- I'm happy to accept this patch on the basis of the microbenchmark @sobolevn provided, but I still wouldn't recommend doing what you're currently doing :)

Something along the lines of what I suggested in https://github.com/python/cpython/issues/102302#issuecomment-1448187236 would be safer and less prone to inadvertent breakage.

2023-03-04 14:49 UTC, Gouvernathor commented
Judging from [this](https://raw.githubusercontent.com/python/cpython/main/Doc/whatsnew/3.12.rst), the :class: should work.

2023-03-04 14:50 UTC, AlexWaygood approved these changes
Thanks for the patch, and thanks @sobolevn for persuading me to change my mind :)

2023-03-04 15:08 UTC, merged

2023-03-04 16:42 UTC, sobolevn commented
🎉