gh-96471: Add queue shutdown, next step.
python/cpython pull request #102499
Opened 2023-03-07 15:32 UTC by YvesDup

I just created this new PR from @EpicWink's original PR, to resume and continue working on the 'queue shutdown' feature with sufficient rights. Currently, I'm on Mac OSX and I need to have the results of the tests on Win and Linux.

About this PR, here is the list of concerned classes:
+ `threading.Queue` and its derived classes,
+ `asyncio.Queue` and its derived classes,
+ `multiprocessing.queue.Queue` and `multiprocessing.queue.JoinableQueue`.

As a reminder, here is a list of features, which I I've collected from [discuss.org](https://discuss.python.org/t/queue-termination/18386/44), the gh-96471 issue and the [first PR](https://github.com/python/cpython/pull/96474):

A queue is created with a new `shutdown_state` attribute with a list of possible values as: `alive`, `shutdown` or `shutdown-immediate`. When created, the new attribute is set to `alive`.

The allowed transitions are:
+ `alive` to `shutdown`,
+ `alive` to `shutdown-immediate`,
+ `shutdown` to `shutdown-immediate`.

When the `shutdown` method is called to stop the queue:
+ all calls to `put`, `put_nowait` raise a `ShutDown` exception.
+ all tasks or threads blocked in `put` methods are released and raise a `ShutDown` exception.
+ when the shutdown_state is '**shutdown**' :
  + all calls to `get`, `get_nowait`, `task_done`, `join` raise `ShutDown` exception as soon as the queue is empty.
+ when the shutdown_state is '**shutdown-immediate**' :
  + all calls to `get`, `get_nowait`, `task_done`, `join` raise the `ShutDown` exception,
  + all tasks or threads blocked in the `get`, `join` methods are released and raise a `ShutDown` exception.

Currently, there is a solution for each class, with dedicated tests. 
Thanks you all for your comments.

2023-03-08 19:28 UTC, YvesDup commented
I had a simple case with a unexpected result about `multiprocessing.queue.JoinableQueue`class.
I put a value "L" in the queue, call shutdown(immediate=False), and just want to get the last put item.
This case raises an ShutDown exception that is unexepected because **queue is not empty**. 
If I add a `time.sleep(1e-5)` just after the call of shudown, result is correct. So what's wrong ? 
```py
import multiprocessing
import time

def test_find_bug_joinablequeue():
    q = multiprocessing.JoinableQueue()
    q.put("L")
    q.shutdown(False)
    # time.sleep(1e-5) # when this line is uncommented, no exception raises, why ?
    assert(q.get() == "L")

test_find_bug_joinablequeue()
```
Any multiprocessing expert is welcome, thank !

2023-03-20 10:28 UTC, YvesDup commented
At this point, the dev is stopped because I had '**Fatal Python error: Segmentation fault**' in Ubuntu tests,  only regarding the `multiprocessing.Queue` class.
These errors don't occur on dedicated unit tests (files 'test_multiprocessing_*', but on `ProcessPoolExecutor` tests in 2 parts `concurrent_futures` and `compileall` Here are two examples:
+ ./python -m unittest test.test_concurrent_futures.ProcessPoolForkserverProcessPoolShutdownTest.test_submit_after_interpreter_shutdown, on https://github.com/python/cpython/actions/runs/4461678241/jobs/7835693302?pr=102499#step:17:4833
+ ./python -m unittest test.test_compileall.CommandLineTestsWithSourceEpoch.test_workers, on (https://github.com/python/cpython/actions/runs/4461678241/jobs/7835693302?pr=102499#step:17:466)

Partially result for each test is:
```bash
stdout:
---
runtime-error
---

stderr:
---
Fatal Python error: Segmentation fault

Current thread 0x00007f7db45f34c0 (most recent call first):

  File "<string>", line 3 in getvalue
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/multiprocessing/queues.py", line 113 in get
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/concurrent/futures/process.py", line 246 in _process_worker
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/multiprocessing/process.py", line 108 in run
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/multiprocessing/process.py", line 314 in _bootstrap
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/multiprocessing/spawn.py", line 133 in _main
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/multiprocessing/forkserver.py", line 313 in _serve_one
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/multiprocessing/forkserver.py", line 274 in main
  File "<string>", line 1 in <module>
```

in `asyncio` module, the `test_events.TestPyGetEventLoop.test_get_event_loop_new_process` test fails too, seems to me to have the same origin.

I guess that the problem came from `ProcessPoolExecutor` where a queue derivated from `multiprocessing.Queue` is used. Error occurs at the first call of `get` when tests the `stutdown_state` attr. This attr is a `multiprocssing.Value`. Currently, I m trying to have a simpler use case but it is  not easy because I am working with OSX.
So work still in progress .....

2023-03-24 11:23 UTC, YvesDup commented
Bug was fixed 2 days ago. I finalize unit tests to each class,  and ask for review

2023-03-28 09:02 UTC, EpicWink requested changes
Some docs changes requested, also see my failing test script above.

In addition, the documentation will need to be updated.

2023-03-28 09:02 UTC, EpicWink commented on Lib/asyncio/queues.py
> +                    # or a shutdown call.
```suggestion
                    # previous get_nowait call or a shutdown call.
```

2023-03-28 09:02 UTC, EpicWink commented on Lib/asyncio/queues.py
> +        Raise a QueueShutDown if _shutdown_state is not set to `ALIVE`.
```suggestion
        Raises QueueShutDown if the queue has been shut down.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/asyncio/queues.py
> +        `ALIVE`.
```suggestion
        Raises QueueShutDown if the queue has been shut down.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/asyncio/queues.py
> +        `SHUTDOWN` and queue is empty.
```suggestion
        Raises QueueShutDown if the queue has been shut down and is empty, or
        if the queue has been shut down immediately.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/asyncio/queues.py
> +        `SHUTDOWN` and queue is empty.
```suggestion
        Raises QueueShutDown if the queue has been shut down and is empty, or
        if the queue has been shut down immediately.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/asyncio/queues.py
> +        `SHUTDOWN_IMMEDIATE`.
```suggestion
        Raises QueueShutDown if the queue has been shut down immediately.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/asyncio/queues.py
> +        `SHUTDOWN_IMMEDIATE`.
```suggestion
        Raises QueueShutDown if the queue has been shut down immediately.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/multiprocessing/queues.py
> +            (self._is_shutdown() and self.empty()):
```suggestion
        if (
            self._is_shutdown_immediate()
            or (self._is_shutdown() and self.empty())
        ):
```

See [PEP 8](https://peps.python.org/pep-0008/#maximum-line-length): backslash line-breaks are discouraged where possible

2023-03-28 09:02 UTC, EpicWink commented on Lib/queue.py
> +        `_queue_shutdown_immediate`.
```suggestion
        Raises ShutDown if the queue has been shut down immediately.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/queue.py
> +        `_queue_shutdown_immediate`.
```suggestion
        Raises ShutDown if the queue has been shut down immediately.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/queue.py
> +        `_queue_alive`.
```suggestion
        Raises ShutDown if the queue has been shut down.
```

Doc-strings are for humans

2023-03-28 09:02 UTC, EpicWink commented on Lib/queue.py
> +        `_queue_shutdown_immediate`
```suggestion
        Raises ShutDown if the queue has been shut down and is empty,
        or if the queue has been shut down immediately.
```

Doc-strings are for humans

2023-03-29 13:55 UTC, YvesDup commented
> Immediate shutdown hangs for multiprocessing; see [my test script](https://gist.github.com/EpicWink/2eb68def04c1f3aaaeb828e3a5aeaebd)

I ran your script with a version 3.12.0a6+ on Mac OSX 13.1. I dont have the same result as you.

With a a call to `shutdown(True)`,  there are around 18 items in the queue, and the **expected behavior happens** such as:
+ one `ShutDown` exception in producer process on the call of  `put`  method.
+ three `ShutDown` exceptions, one for each consumer, on the call of `get` method.
Only 15/16 items are retrieved.

With a call to `shutdown(False)`,  there are around 18 items in the queue, and the **expected behavior happens** such as:
+ one `ShutDown` exception in producer process on the call of  `put`  method.
+ three `ShutDown` exceptions, one for each consumer, on the call of `get` method.
All items from the queue are retrieved.

Do you have the expected results with queues of `asyncio` and `threading` modules ? Is your `lib/multiprocessing/queues.py`file updated  ? Could you test again with `multiprocessing`, because it looks like the result of your first version?

2023-03-30 02:35 UTC, EpicWink commented
> I ran your script with a version 3.12.0a6+ on Mac OSX 13.1

I think that's the issue: I'm on Ubuntu 22.04. Try running the following commands in a Ubuntu Docker container (`docker run -it --rm ubuntu:latest`)

<details>
<summary>commands</summary>

```shell
apt update
apt install --yes --no-install-recommends ca-certificates gcc git libc-dev libffi-dev make pkg-config
git clone https://gist.github.com/2eb68def04c1f3aaaeb828e3a5aeaebd.git /root/testq
git clone https://github.com/YvesDup/cpython.git /root/cpython
mkdir /root/cpython/build
cd /root/cpython/build
git switch queue-shutdown
../configure
make -j15
./python /root/testq/testq.py
```

</details>

---

> Do you have the expected results with queues of asyncio and threading modules ?

Yes, and with multiprocessing when `immediate` is false

> Is your Lib/multiprocessing/queues.pyfile updated ?

Yep, latest commit checked out

2023-04-07 08:46 UTC, arhadthedev commented on Misc/NEWS.d/next/Library/2023-03-07-15-42-27.gh-issue-96471.oWZtwQ.rst
> +Add "shutdown" method to multithreading.Queue, asyncio.Queue and multiprocessing.queue.Queue and multiprocessing.queue.JoinableQueue
```suggestion
Add "shutdown" method to multithreading.Queue, asyncio.Queue, multiprocessing.queue.Queue, and multiprocessing.queue.JoinableQueue
```

2023-04-07 08:50 UTC, arhadthedev commented
Also, this PR incorrectly replaces tabs with spaces in `Tools/c-analyzer/cpython/_parser.py`. I propose to put tabs back, wait until gh-103335 gets merged, and click the Update Branch button.

2023-04-07 09:12 UTC, arhadthedev commented on Misc/NEWS.d/next/Library/2023-03-07-15-42-27.gh-issue-96471.oWZtwQ.rst
> +Add "shutdown" method to multithreading.Queue, asyncio.Queue and multiprocessing.queue.Queue and multiprocessing.queue.JoinableQueue
Or even:

```suggestion
Add "shutdown" method to :class:`multithreading.Queue`,
:class:`asyncio.Queue`, :class:`multiprocessing.queue.Queue`, and
:class:`multiprocessing.queue.JoinableQueue`.
```

2023-04-10 19:46 UTC, arhadthedev commented
gh-103335 is merged so updating the branch of this PR.

2023-04-11 22:53 UTC, gvanrossum commented
> Hi @gvanrossum , I read [your previous comment in Dec 2022 ](https://github.com/python/cpython/pull/96474#issuecomment-1332985740) from the original [PR 'EpicWink: Adding the queue stop'](https://github.com/python/cpython/pull/96474) I am wondering how and who I should contact for a review of each target affected by this PR. As expected there are 3 separate solutions, one for asyncio, a second for threading, and a third for multiprocessing. Thank you for your help.

Hi @YvesDup, unfortunately this has stalled and I don't think I will have time to get back to it before PyCon. And after PyCon there are only about two weeks until beta 1 (feature freeze), during which time I'll likely be occupied with helping out with the PEP 695 implementation.

I'm a bit concerned that this PR of yours has 67 commits, most of which have meaningless commit messages like "Update of queues.py". Perhaps you can explain how it relates to @EpicWink's original PR?

One way to proceed might be to split the work into three new, clean PRs, each targeting one of asyncio, threading, and multiprocessing. Then you could get separate reviews. For example, the only two people able to review asyncio PRs are @kumaraditya303 and myself; for threading there are several core devs (but none eager to jump); for multiprocessing it may be near impossible to find a reviewer who's willing and capable. And really, it would be okay of not all three PRs made it into 3.12.

2023-04-12 01:03 UTC, EpicWink commented
Having one PR for each target would help with the architecture here with one assigned reviewer per PR.

Might I suggest using an interactive rebase (on top of `main`) to improve the commits. You can use the co-authored-by commit message footer to keep attribution.

You should put the list of high-level changes from my PR in this PR's description.

Reminder to update the documentation: check out my PR against this branch doing this.

2023-04-13 13:11 UTC, YvesDup commented
> Also, my test script [above](https://github.com/python/cpython/pull/102499#issuecomment-1489598106) still hangs. Are you sure you fixed the problem?

Sometimes, your test script freezes. I identify two sources not in the implementation but in your script:
1. a call to `process_producer.join()` in the main process after end of `_producer`  causes an infinite wait
2. a call of `get` in `_consumer` process when there is no more message in the queue 
But may be I miss something

If you decreases the `shutdown_delay` from 2.0 to 1.6 (depend of your conf), everything is fine.

2023-04-13 13:31 UTC, YvesDup commented
> Having one PR for each target would help with the architecture here with one assigned reviewer per PR.

I agree with splitting the PRs but following Guido's answer, should we continue the multiprocessing target ?
 
> Might I suggest using an [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) (on top of `main`) to improve the commits. You can use the [co-authored-by](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) commit message footer to keep attribution.

I agree, this is a good solution, but I have never done it before. Your link will be very helpful, I will do it ASAP (I will out of office the next two weeks).

> You should put the list of high-level changes from [my PR](https://github.com/python/cpython/pull/96474) in this PR's description.

Can you explain what are you expecting please ?

> Reminder to update the documentation: check out [my PR](https://github.com/YvesDup/cpython/pull/4) against this branch doing this.

Okay, but how about changing the `.. versionadded:: 3.12` to `.. versionadded:: 3.13` in all documentations files ?

2023-04-14 04:51 UTC, EpicWink commented
> Can you explain what are you expecting please ?

My PR didn't have multiprocessing working, and I hadn't changed `task_done` and `wait`. I think you've fixed a few bugs as well.

> Okay, but how about changing the .. versionadded:: 3.12 to .. versionadded:: 3.13 in all documentations files ?

You're free to make commits to the branch, you have write access.

2023-04-18 01:21 UTC, EpicWink commented
Here's the current state of the difference from [my draft PR](https://github.com/python/cpython/pull/96474)

### Miscellansous

* Add news entry

<details>
<summary>diff</summary>

```diff
diff --git a/Misc/NEWS.d/next/Library/2023-03-07-15-42-27.gh-issue-96471.oWZtwQ.rst b/Misc/NEWS.d/next/Library/2023-03-07-15-42-27.gh-issue-96471.oWZtwQ.rst
new file mode 100644
index 0000000000..61af8d77ae
--- /dev/null
+++ b/Misc/NEWS.d/next/Library/2023-03-07-15-42-27.gh-issue-96471.oWZtwQ.rst
@@ -0,0 +1 @@
+Add "shutdown" method to multithreading.Queue, asyncio.Queue and multiprocessing.queue.Queue and multiprocessing.queue.JoinableQueue
```

</details>

### Asyncio

* Queue state enum members are capitalised
* Termination state in `str`/`repr`
* Include raised exception in docstrings
* Factor out queue-state checks and updates to methods
* Logic fixes in `get_nowait` and `shutdown`
* Handle queue shutdown in `task_done` and `join`
* Updated tests

<details>
<summary>diff</summary>

```diff
diff --git a/Lib/asyncio/queues.py b/Lib/asyncio/queues.py
index d591d0ebab..ae2d554783 100644
--- a/Lib/asyncio/queues.py
+++ b/Lib/asyncio/queues.py
@@ -32,9 +32,9 @@ class QueueShutDown(Exception):
 
 
 class _QueueState(enum.Enum):
-    alive = "alive"
-    shutdown = "shutdown"
-    shutdown_immediate = "shutdown-immediate"
+    ALIVE = "alive"
+    SHUTDOWN = "shutdown"
+    SHUTDOWN_IMMEDIATE = "shutdown-immediate"
 
 
 class Queue(mixins._LoopBoundMixin):
@@ -60,7 +60,7 @@ def __init__(self, maxsize=0):
         self._finished = locks.Event()
         self._finished.set()
         self._init(maxsize)
-        self._shutdown_state = _QueueState.alive
+        self._shutdown_state = _QueueState.ALIVE
 
     # These three are overridable in subclasses.
 
@@ -101,6 +101,8 @@ def _format(self):
             result += f' _putters[{len(self._putters)}]'
         if self._unfinished_tasks:
             result += f' tasks={self._unfinished_tasks}'
+        if not self._is_alive():
+            result += f' state={self._shutdown_state.value}'
         return result
 
     def qsize(self):
@@ -132,8 +134,10 @@ async def put(self, item):
 
         Put an item into the queue. If the queue is full, wait until a free
         slot is available before adding item.
+
+        Raises QueueShutDown if the queue has been shut down.
         """
-        if self._shutdown_state != _QueueState.alive:
+        if not self._is_alive():
             raise QueueShutDown
         while self.full():
             putter = self._get_loop().create_future()
@@ -147,14 +151,14 @@ async def put(self, item):
                     self._putters.remove(putter)
                 except ValueError:
                     # The putter could be removed from self._putters by a
-                    # previous get_nowait call.
+                    # previous get_nowait call or a shutdown call.
                     pass
                 if not self.full() and not putter.cancelled():
                     # We were woken up by get_nowait(), but can't take
                     # the call.  Wake up the next in line.
                     self._wakeup_next(self._putters)
                 raise
-            if self._shutdown_state != _QueueState.alive:
+            if not self._is_alive():
                 raise QueueShutDown
         return self.put_nowait(item)
 
@@ -162,8 +166,10 @@ def put_nowait(self, item):
         """Put an item into the queue without blocking.
 
         If no free slot is immediately available, raise QueueFull.
+
+        Raises QueueShutDown if the queue has been shut down.
         """
-        if self._shutdown_state != _QueueState.alive:
+        if not self._is_alive():
             raise QueueShutDown
         if self.full():
             raise QueueFull
@@ -176,11 +182,14 @@ async def get(self):
         """Remove and return an item from the queue.
 
         If queue is empty, wait until an item is available.
+
+        Raises QueueShutDown if the queue has been shut down and is empty, or
+        if the queue has been shut down immediately.
         """
-        if self._shutdown_state == _QueueState.shutdown_immediate:
+        if self._is_shutdown_immediate():
             raise QueueShutDown
         while self.empty():
-            if self._shutdown_state != _QueueState.alive:
+            if self._is_shutdown():
                 raise QueueShutDown
             getter = self._get_loop().create_future()
             self._getters.append(getter)
@@ -193,14 +202,15 @@ async def get(self):
                     self._getters.remove(getter)
                 except ValueError:
                     # The getter could be removed from self._getters by a
-                    # previous put_nowait call.
+                    # previous put_nowait call,
+                    # or a shutdown call.
                     pass
                 if not self.empty() and not getter.cancelled():
                     # We were woken up by put_nowait(), but can't take
                     # the call.  Wake up the next in line.
                     self._wakeup_next(self._getters)
                 raise
-            if self._shutdown_state == _QueueState.shutdown_immediate:
+            if self._is_shutdown_immediate():
                 raise QueueShutDown
         return self.get_nowait()
 
@@ -208,13 +218,16 @@ def get_nowait(self):
         """Remove and return an item from the queue.
 
         Return an item if one is immediately available, else raise QueueEmpty.
+
+        Raises QueueShutDown if the queue has been shut down and is empty, or
+        if the queue has been shut down immediately.
         """
+        if self._is_shutdown_immediate():
+            raise QueueShutDown
         if self.empty():
-            if self._shutdown_state != _QueueState.alive:
+            if self._is_shutdown():
                 raise QueueShutDown
             raise QueueEmpty
-        elif self._shutdown_state == _QueueState.shutdown_immediate:
-            raise QueueShutDown
         item = self._get()
         self._wakeup_next(self._putters)
         return item
@@ -232,7 +245,11 @@ def task_done(self):
 
         Raises ValueError if called more times than there were items placed in
         the queue.
+
+        Raises QueueShutDown if the queue has been shut down immediately.
         """
+        if self._is_shutdown_immediate():
+            raise QueueShutDown
         if self._unfinished_tasks <= 0:
             raise ValueError('task_done() called too many times')
         self._unfinished_tasks -= 1
@@ -246,9 +263,15 @@ async def join(self):
         queue. The count goes down whenever a consumer calls task_done() to
         indicate that the item was retrieved and all work on it is complete.
         When the count of unfinished tasks drops to zero, join() unblocks.
+
+        Raises QueueShutDown if the queue has been shut down immediately.
         """
+        if self._is_shutdown_immediate():
+            raise QueueShutDown
         if self._unfinished_tasks > 0:
             await self._finished.wait()
+            if self._is_shutdown_immediate():
+                raise QueueShutDown
 
     def shutdown(self, immediate=False):
         """Shut-down the queue, making queue gets and puts raise.
@@ -259,20 +282,39 @@ def shutdown(self, immediate=False):
         All blocked callers of put() will be unblocked, and also get()
         and join() if 'immediate'. The QueueShutDown exception is raised.
         """
+        if self._is_shutdown_immediate():
+            return
+        # here _shutdown_state is ALIVE or SHUTDOWN
         if immediate:
-            self._shutdown_state = _QueueState.shutdown_immediate
+            self._set_shutdown_immediate()
             while self._getters:
                 getter = self._getters.popleft()
                 if not getter.done():
                     getter.set_result(None)
+            # Release all 'blocked' tasks/coros in `join()`
+          [...]

2023-04-26 22:33 UTC, willingc commented
> One way to proceed might be to split the work into three new, clean PRs, each targeting one of asyncio, threading, and multiprocessing. Then you could get separate reviews.

I agree that the reviews would be easier if this PR is split into three. Feel free to ping me when you open one for asyncio.

2023-04-26 22:48 UTC, willingc reviewed
Please split this PR into 3 PRs to make it easier for reviewers. Thanks.

2023-05-05 00:48 UTC, EpicWink commented
@YvesDup If you want I can split them up and include your authorship

2023-05-05 08:11 UTC, YvesDup commented
> @YvesDup If you want I can split them up and include your authorship

I am very busy at this time, so yes I agree with your proposal. 
Can you confirm this is independant from the '**interactive rebase**' operation on this PR ? I would really like to improve all commits.
Thanks for taking over.

2023-05-06 03:18 UTC, EpicWink commented
> Can you confirm this is independant from the '**interactive rebase**' operation on this PR ? I would really like to improve all commits.

I'm planning to squash all commits into two (for each library), one for each of my work and yours, and include the changes in longer commit messages (which I'll copy to the PR description). Almost all PRs in this repo are squashed to one commit anyway, which GitHub adds co-authorship commit message footers for each commit author.

2023-05-06 05:23 UTC, EpicWink commented
Added new PRs, one for each concurrency type: #104225, #104228 and #104230

2023-05-06 17:12 UTC, YvesDup commented
> Added new PRs, one for each concurrency type: #104225, #104228 and #104230

thank you for this !

2023-05-09 18:01 UTC, closed without merging