GH-66646: Explain __base__ attribute in the docs
python/cpython pull request #102554
Opened 2023-03-09 11:11 UTC by furkanonder

2023-03-09 16:23 UTC, merwok commented
I’m not sure that this implementation detail should be documented in three places.
One place with an index should be enough.  Please also use the right markup to mark it as an impl. detail.

2023-03-13 21:17 UTC, furkanonder commented
@merwok Since ``class.__bases__`` is defined in ``stdtypes.rst`` and ``datamodel.rst `` files, I wanted to define ``class.__base__`` in these files.

2023-03-13 21:26 UTC, merwok commented
I understand your reason, but still think one place would be better than 3.  I would like to see other people’s opinion!

For the markup, I meant this: https://devguide.python.org/documentation/markup/#codecell33 🙂

2023-05-11 14:07 UTC, merwok commented on Doc/reference/datamodel.rst
> +
```suggestion
      :attr:`~class.__base__`
         ``__base__`` corresponds to the :c:member:`~PyTypeObject.tp_base` in a
         type object.  At the C level, Python has a single inheritance model
         that determines the memory layout of instances.  There is a chain
         involving base classes that contribute to the instance layout.
         ``__base__`` is the base class that is involved in that chain.

         .. impl-detail::
            The behavior of the ``__base__`` attribute is dependent on the :term:`CPython` implementation.

```

2023-05-17 20:00 UTC, furkanonder commented
> I understand your reason, but still think one place would be better than 3. I would like to see other people’s opinion!

CC: @hugovk @CAM-Gerlach

2023-07-23 06:36 UTC, hugovk commented
I don't have a strong opinion, but if it's an implementation detail, fewer places might be better. The search should help people find it when they're looking.

2024-01-17 17:15 UTC, erlend-aasland commented
@furkanonder, can you please rework this PR to align with the comments Raymond, Guido, and Éric gave on the issue?

2024-01-20 23:49 UTC, furkanonder commented
@erlend-aasland Based on Raymond, Guido, and Éric's feedback, I believe changes have been made. Could you please let me know if there is anything I missed?

2024-01-21 18:24 UTC, merwok commented on Doc/c-api/object.rst
> +   Another function, :attr:`__base__` that is specific to CPython and also
Should this say function?

2024-01-21 18:32 UTC, erlend-aasland commented
> @erlend-aasland Based on Raymond, Guido, and Éric's feedback, I believe changes have been made. Could you please let me know if there is anything I missed?

Not at all. I will repeat their comments here:

Raymond said in https://github.com/python/cpython/issues/66646#issuecomment-1093664965:

> I think that __base__ was intended to be a non-guaranteed implementation detail for new-style classes just like __dictoffset__ and __flags__ .

Guido followed up in https://github.com/python/cpython/issues/66646#issuecomment-1093664966:

> Raymond is correct. __base__ is closely tied to the C implementation. I think it might be worth a mention, but with an explicit note that it is CPython-specific. It is sometimes useful, e.g. when wondering why a certain case of multiple inheritance is rejected.

So, we're talking about a non-guaranteed implementation detail. You've also been told multiple times that a single mention is sufficient, yet you do not follow up this; your PR still changes _three_ doc files, _including the reference_. "Worth a mention" is far from your PR which adds 64 (!) lines.

I'm sorry, but I cannot see that you've taken any review or issue remarks into account.

2024-01-21 18:48 UTC, merwok commented on Doc/c-api/object.rst
> +   Another function, :attr:`__base__` that is specific to CPython and also
Also, I think the rst warning could be fixed with:
```
:attr:`~class.__base__`
```

2024-01-21 22:15 UTC, furkanonder commented
> I understand your reason, but still think one place would be better than 3. I would like to see other people’s opinion!

I didn't think that the idea of repetition here was stated unequivocally, since he said `I would like to see other people's views!`.

> So, we're talking about a non-guaranteed implementation detail.

This has already been stated in three parts.

In [object.rst](https://github.com/python/cpython/pull/102554/commits/01c2912df532f397a0621964b9a820b8f6ca8547#diff-a1262fdbd9b2a2f959d66805b2782258bbcf740a719bf33340746930cef31561L352)

In [stdtypes.rst](https://github.com/python/cpython/pull/102554/commits/01c2912df532f397a0621964b9a820b8f6ca8547#diff-08a31a70dd1f6d97aa8dacdce77db4de04c700d9949be1af611a595186aad5b3L5504)

In [datamodel.rst](https://github.com/python/cpython/pull/102554/commits/53bd224ee64d3aaf8d14482ac5d64dffac106cc3#diff-9125871b063a1ef80aa4bd3e46d7060921032c8437160c7cb8c1497756b02d61L993)

2024-01-21 22:28 UTC, furkanonder commented
> "Worth a mention" is far from your PR which adds 64 (!) lines.

`I think it might be worth a mention, but with an explicit note that it is CPython-specific.`

The statement does not include a line count for the topic to be documented. Hence I did not consider the amount of lines for the documented part.

2025-08-19 22:20 UTC, merwok commented on Doc/c-api/object.rst
> +   Another function, :attr:`~class.__base__` that is specific to CPython and also
1. not a function
2. incorrect reference

2025-08-21 12:31 UTC, merwok commented
I re-read the original ticket — I think this PR adds too much text.
«A mention» was meant to be a line or two, possibly all in an impl-detail block.
Here we have many paragraphs, going into details about inheritance that should be already covered somewhere else!

2025-08-25 08:12 UTC, furkanonder commented
> I re-read the original ticket — I think this PR adds too much text.
> «A mention» was meant to be a line or two, possibly all in an impl-detail block.
> Here we have many paragraphs, going into details about inheritance that should be already covered somewhere else!

I've shortened the explanation as requested. I was thinking that keeping the examples would make it easier to understand. Regarding your comment about _"inheritance that should be already covered somewhere else"_ - it actually hasn't been covered anywhere else in the documentation. Could you point me to where you think this information should be documented instead?

2025-08-25 12:42 UTC, merwok commented
You’re right, the specific docs for \_\_bases\_\_ and \_\_mro\_\_ don’t explain how base classes (included parent classes) are collapsed. But https://docs.python.org/3/howto/mro.html does.

If you think clarifications are helpful, I would expand the notes for one of these official attributes, not \_\_base\_\_.

(edit: _I would expand_ means _if I were you, I would expand_ — not that I-real-me will make a PR!)

2025-08-30 07:16 UTC, furkanonder commented
> If you think clarifications are helpful, I would expand the notes for one of these official attributes, not __base__.

Yes, that would be great.

2025-09-18 10:52 UTC, erlend-aasland requested changes
I discussed this briefly with @encukou at the core dev sprint, and we concluded with the following:

- The C API reference is the wrong place for documenting data model implementation details.
- The _mention_ of `__base__` should be put in `Doc/reference/datamodel.rst`, similar to the `__bases__` attribute, but with a `impl-detail` attached to it.

(Moreover, `PyObject_IsSubclass` docs should probably be worded more succinctly and to the point[^1], instead of expanded[.)

[^1]: for the record: out of scope for this issue/PR

2025-10-15 12:56 UTC, encukou commented on Doc/reference/datamodel.rst
> +
I'd put it all under `impl-detail`, and remove some duplication:
```suggestion
     - .. impl-detail::

          The single base class in the inheritance chain that is responsible
          for the memory layout of instances. This attribute corresponds to
          :c:member:`~PyTypeObject.tp_base` at the C level.
```
The directive already points out it's a *CPython* implementation detail.

2025-10-15 21:36 UTC, merwok commented on Doc/reference/datamodel.rst
> +          :c:member:`~PyTypeObject.tp_base` at the C level.
```suggestion
          :c:member:`~PyTypeObject.tp_base` at the C level.

```

2025-10-16 08:22 UTC, encukou approved these changes
@erlend-aasland, do you want to request more changes?

2025-10-16 14:54 UTC, merwok approved these changes

2025-10-16 15:49 UTC, willingc approved these changes
Thanks for rebooting this @encukou.

2025-10-16 16:28 UTC, merwok commented
I disagree a bit with the label `type-feature`: shouldn’t we backport this small but maybe useful doc addition?

(`skip news` is fine)

2025-10-17 08:56 UTC, encukou commented
Yeah, we generally backport docs improvements.

2025-10-20 12:15 UTC, merged

2025-10-21 12:32 UTC, merwok commented
Thanks to all involved!