Rename redundant enum tests so that they run
python/cpython pull request #102535
Opened 2023-03-08 16:31 UTC by JosephSBoyle

No issue for this, as I believe that it's trivial.

There are three methods named `test_doc_1` in this class and since only one will ever be executed we should delete two. 
I don't have a particular preference for which but it seems natural to leave the `Single` `Double` enum examples.

2023-03-11 19:57 UTC, hauntsaninja approved these changes
Thanks, good spot!

2023-03-11 20:26 UTC, furkanonder approved these changes

2023-03-11 20:26 UTC, furkanonder commented
Good catch!

2023-03-14 17:18 UTC, corona10 requested changes
I don't think that the change is correct.
Please rename them as the `test_doc_3` and `test_doc_4` instead of removing them.

2023-03-14 17:21 UTC, corona10 commented
@hauntsaninja  
Oops, I read your comment just after I requested changes.
IMO, It looks like that tests were implemented to be run rather than not run.
So let's keep them even if they look redundant.

2023-03-14 18:50 UTC, ethanfurman commented
As @corona10 said, let's rename them to `3` and `4` instead of deleting them.  Thank you for finding that!

2023-03-14 21:20 UTC, JosephSBoyle commented
Thanks for the feedback guys:)

Added the tests back and renamed them

2023-03-14 22:16 UTC, merged

2023-03-14 22:16 UTC, miss-islington commented
Thanks @JosephSBoyle for the PR, and @hauntsaninja for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖

2023-03-14 22:16 UTC, miss-islington commented
Sorry, @JosephSBoyle and @hauntsaninja, I could not cleanly backport this to `3.10` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker a028778d4c813914ae1e6ef3a04bb96dbf92ace6 3.10
                                ```

2023-03-14 22:19 UTC, hauntsaninja commented
JosephSBoyle, thanks again!
corona10, no worries! I'd held off on merging the PR in case ethanfurman or anyone else had a different opinion :-)