Fix spacing issues in warning.warn messages
python/cpython pull request #10268
Opened 2018-10-31 22:02 UTC by scorphus

Some warn messages miss space between words, such as:

```
Use of 'buffering' argument is deprecated  and ignoredsince Python 3.0.
```

in `bz2` library, and:

```
keyfile and certfile are deprecated, use acustom context instead
```

in many libraries, such as `poplib` and `smtplib`.

Other warn messages contain too much spaces between words, such as:

```
The 'filename' attribute will be removed in future versions.  Use 'source' instead.
```

in `configparser` library.

As _"Trivial changes, like fixing a typo, do not need an issue"_, I closed the one I had previously opened ([issue35128][https://bugs.python.org/issue35128])

2018-10-31 23:54 UTC, NuclearLemon commented
Hi @scorphus, to address some of the errored and failing checks you're receiving, I'd recommend putting the Python BPO issue number in the title of your PR as detailed in the devguide.

e.g. "bpo-35128: Fix spacing issues in warning.warn messages"

2018-11-01 05:17 UTC, serhiy-storchaka reviewed
Double space after a period is not a bug.

2018-11-01 05:25 UTC, ezio-melotti requested changes
Double spaces after the "." are intentional and should be kept, the others are bugs and should be fixed.

2018-11-01 10:13 UTC, scorphus commented
Great! Can I help backporting!?

2018-11-01 10:33 UTC, merged

2018-11-01 10:33 UTC, miss-islington commented
Thanks @scorphus for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖

2018-11-01 10:33 UTC, miss-islington commented
Sorry, @scorphus and @serhiy-storchaka, I could not cleanly backport this to `3.7` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker 4b5e62dbb22a3593e0db266c12f805b727a42b00 3.7
                            ```

2018-11-01 10:33 UTC, miss-islington commented
Sorry, @scorphus and @serhiy-storchaka, I could not cleanly backport this to `3.6` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker 4b5e62dbb22a3593e0db266c12f805b727a42b00 3.6
                            ```