Fix nonsense error messages in shutil.py
python/cpython pull request #102827
Opened 2023-03-19 12:31 UTC by eric-wieser

Attempting to copy a file onto a symlink to itself previously gave the error
```
shutil.Error: ['<', 'D', 'i', 'r', 'E', 'n', 't', 'r', 'y', ' ', "'", 's', 't', 'y', 'l', 'e', '.', 'c', 's', 's', "'", '>', ' ', 'a', 'n', 'd', ' ', "'", 'b', 'u', 'i', 'l', 'd', '/', 'h', 't', 'm', 'l', '/', 's', 't', 'y', 'l', 'e', '.', 'c', 's', 's', "'", ' ', 'a', 'r', 'e', ' ', 't', 'h', 'e', ' ', 's', 'a', 'm', 'e', ' ', 'f', 'i', 'l', 'e']
```

2023-03-22 18:36 UTC, iritkatriel commented
For a change like this you need to create an issue explaining what the problem you are fixing is (with a script to reproduce it). 
The patch would also need a unit test to prevent regressions.

2023-03-22 18:37 UTC, iritkatriel requested changes
See https://github.com/python/cpython/pull/102827#issuecomment-1480075796.

2023-03-23 19:12 UTC, arhadthedev commented
@iritkatriel The review got addressed: gh-102931

2023-03-23 19:21 UTC, arhadthedev commented
@eric-wieser Could you add a NEWS entry please?

*The Bedevere bot didn't post a reminder for some reason even after retriggering it with a merge commit.*

2023-03-23 19:34 UTC, eric-wieser commented
> @iritkatriel The review got addressed: [gh-102931](https://github.com/python/cpython/issues/102931)

I didn't get around to adding a test to this PR though (and may not for some time).

2026-05-03 17:04 UTC, StanFromIreland commented
Hello! I'm sorry but I'm closing this PR as it is stale and has requested changes that have not been addressed in quite some time.

2026-05-03 17:04 UTC, closed without merging