gh-102192: remove unused _PyErr_ChainExceptions
python/cpython pull request #102935
Opened 2023-03-22 22:38 UTC by iritkatriel

2023-03-31 09:21 UTC, erlend-aasland commented
I'm not sure we can simply remove this from the C API, as it is unfortunately exposed via Python.h:

```console
$ echo '#include "Python.h"' | gcc -E $(./python.exe ./python-config.py --includes) - | grep _PyErr_ChainExceptions
__attribute__ ((visibility ("default"))) void _PyErr_ChainExceptions(PyObject *, PyObject *, PyObject *);
__attribute__ ((visibility ("default"))) void _PyErr_ChainExceptions1(PyObject *);
```

cc. @encukou

2023-03-31 09:25 UTC, markshannon requested changes
The code looks fine, but it will need documenting.

2023-03-31 09:25 UTC, markshannon commented on Include/cpython/pyerrors.h
> -PyAPI_FUNC(void) _PyErr_ChainExceptions(PyObject *, PyObject *, PyObject *);
This is marked as an API function, so it will need to be added to the "porting to 3.12" section and any other relevant sections in the "what's new".

2023-03-31 10:05 UTC, markshannon commented
> I'm not sure we can simply remove this from the C API, as it is unfortunately exposed via Python.h:
> 

It is prefixed with an underscore so we can, in theory, remove it. But we will need to document how to upgrade to 3.12.
We could leave `_PyErr_ChainExceptions` in as a deprecated shim that calls `_PyErr_ChainExceptions1` for a couple of releases, if we think removing it will cause breakages.

2023-03-31 10:28 UTC, iritkatriel commented
> We could leave `_PyErr_ChainExceptions` in as a deprecated shim that calls `_PyErr_ChainExceptions1` for a couple of releases

Currently it normalises the exception so just calling _PyErr_ChainExceptions1 with the second arg would be a change in semantics.

2023-03-31 10:59 UTC, erlend-aasland commented
Since it is exposed via Python.h, someone is bound to be using it, so we cannot just remove it. I'd say we mark it as deprecated using the `Py_DEPRECATED` macro. There's practically no maintenance overhead in keeping it around.

BTW, we should consider unexposing the new API (`_PyErr_ChainExceptions1`) by moving it to Include/internal before 3.12 is frozen.

2023-03-31 11:06 UTC, iritkatriel commented
I searched on GitHub and found quote a few usages. So I agree with just deprecating it for now.

Not sure it's reasonable to not expose the alternative though, given people are using it.

2023-04-01 18:22 UTC, erlend-aasland approved these changes
LGTM. 


We should consider making the new API official and documenting it, in a follow-up PR.

2023-04-01 18:22 UTC, erlend-aasland commented on Doc/whatsnew/3.12.rst
> +  to replace the legacy-api ``_PyErr_ChainExceptions``, which is now
Nit: api => API

2023-04-01 18:48 UTC, iritkatriel commented on Doc/whatsnew/3.12.rst
> +  to replace the legacy-api ``_PyErr_ChainExceptions``, which is now
```suggestion
  to replace the legacy-API ``_PyErr_ChainExceptions``, which is now
```

2023-04-01 20:30 UTC, merged