gh-103059: Clarify gc.freeze documentation
python/cpython pull request #103058
Opened 2023-03-27 18:17 UTC by raylu

The current advice seems to mean you should gc.disable() and gc.freeze() right before os.fork(), which doesn't do anything.

Łukasz explained the advice in https://bugs.python.org/issue31558#msg302780.

This moves the advice around gc.disable out of the gc.freeze docs.

* Issue: gh-103059

2023-03-29 00:59 UTC, carljm requested changes
Thanks for the proposal and PR!

I definitely agree that the `gc.freeze()` docs should be cleaned up and clarified, but I don't agree with adding a bunch of fork-specific text to the `gc.disable()` docs. There are lots of possible reasons to disable GC; "I'm going to fork-without-exec later" is only one of them, and probably not the most common. And in that use case, `gc.disable()` is still useless unless you also `gc.freeze()`. So the only API that is specific to the fork-without-exec use case is `gc.freeze()`, and the explanation of how to handle fork-without-exec belongs there.

Here's my full suggested rewrite for the `gc.freeze()` documentation:

> Freeze all objects tracked by the garbage collector: move them to a permanent generation and ignore them in all future collections.

> If a process will `fork()` without `exec()`, avoiding unnecessary copy-on-write in child processes will maximize memory sharing and reduce overall memory usage. This requires both avoiding creation of freed "holes" in memory pages in the parent process, and ensuring that GC collections in child processes won't touch the memory of long-lived objects originating in the parent process. To accomplish both, call `gc.disable()` early in the parent process, `gc.freeze()` right before `fork()`, and `gc.enable()` early in child processes.

2023-03-29 15:36 UTC, carljm approved these changes
This change looks accurate and like a solid improvement to me. Thanks for the PR!

Process nit for future contributions to CPython: it's better to never force-push your PR. It can make life more difficult for reviewers (can't see changes since previously-reviewed version), and there's no benefit, since we always squash on merge anyway.

2023-04-09 08:21 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Documentation/2023-03-27-18-19-35.gh-issue-103059.55_kOa.rst
> +Clarify ``gc.freeze()`` docs to explain when/why using it can help.
New entry is not required.

2023-04-10 16:30 UTC, merged

2023-04-10 16:30 UTC, miss-islington commented
Thanks @raylu for the PR, and @carljm for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖