Add --tempdir option for test run
python/cpython pull request #10322
Opened 2018-11-04 15:55 UTC by zooba

2018-11-04 19:49 UTC, zooba commented
Happy to change the name of the option, or convert it to an environment variable (which is where I started, but then preferred an option instead).

2018-11-06 17:28 UTC, zooba commented
@vstinner I think you'd be a good person to review this as well, so I'll wait for your comments. But I also think this is very safe, so I won't wait forever :)

2018-11-07 06:02 UTC, serhiy-storchaka approved these changes
Maybe update comments around line 18 in main.py?

2018-11-07 06:02 UTC, serhiy-storchaka commented on Lib/test/libregrtest/main.py
>              except FileExistsError:
Catching FileExistsError no longer needed?

2018-11-13 00:01 UTC, vstinner requested changes

2018-11-13 00:01 UTC, vstinner commented on Lib/test/libregrtest/main.py
>              except FileExistsError:
Use makedirs(exist_ok=True) to avoid the try/except.

2018-11-13 00:01 UTC, vstinner commented on Lib/test/libregrtest/main.py
> +        if not os.path.isdir(TEMPDIR):
Maybe just remove the if and always call makedirs(), no?

2018-11-17 12:14 UTC, merged

2018-11-17 12:14 UTC, miss-islington commented
Thanks @zooba for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖