gh-83004: Harden msvcrt further
python/cpython pull request #103420
Opened 2023-04-10 19:08 UTC by erlend-aasland

2023-04-10 19:16 UTC, erlend-aasland commented
The old `insert*` helpers were buggy: conversion errors were cleared, insert dict errors simply ignored (could theoretically end up overwriting the previous exception over and over again).

2023-04-18 10:51 UTC, kumaraditya303 commented on PC/msvcrtmodule.c
> +    int st = PyModule_AddObjectRef(m, "CRT_ASSEMBLY_VERSION", version);
```suggestion
    st = PyModule_AddObjectRef(m, "CRT_ASSEMBLY_VERSION", version);
```

2023-04-18 11:01 UTC, kumaraditya303 requested changes
missing error label

2023-04-18 17:05 UTC, erlend-aasland commented on PC/msvcrtmodule.c
> +    int st = PyModule_AddObjectRef(m, "CRT_ASSEMBLY_VERSION", version);
I prefer to remove line 600 instead.

2023-04-18 19:13 UTC, erlend-aasland commented
> missing error label

Thanks for the heads-up. I removed those gotos. PTAL.

2023-04-19 10:41 UTC, kumaraditya303 approved these changes
LGTM, thanks!

2023-04-19 14:15 UTC, merged