Typo/trivial mistake
python/cpython pull request #10343
Opened 2018-11-05 20:00 UTC by tashrifbillah

The last argument should be `msg.line`. Having `line=msg.line` generates an error message:
`got an unexpected keyword arugument line=msg.line`

Compare with Ln 99, the discrepancy should be apparent.

2018-11-05 20:00 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-11-05 20:05 UTC, tashrifbillah commented
CLA has been signed separately

2018-11-05 20:13 UTC, serhiy-storchaka commented
Please open an issue on [the bug tracker](https://bugs.python.org/) and describe how to reproduce the error.

2018-11-06 15:02 UTC, tashrifbillah commented
cc: @serhiy-storchaka 

```
2018-11-06 09:51:27,314 /home/tb571/Downloads/pnlpipe/pnlscripts/wmql.py DEBUG  Running ['/home/tb571/Downloads/pnlpipe/soft_dir/tract_querier-c57d670/scripts/tract_math', '/home/tb571/Downloads/pnlpipe/_data/003_GNX_007/Ukf-003_GNX_007-761f2a551e.vtk', 'tract_remove_short_tracts', '2', '/tmp/tmpq2z9fmfc/ukfpruned.vtk']
Traceback (most recent call last):
  File "/home/tb571/Downloads/pnlpipe/soft_dir/tract_querier-c57d670/scripts/tract_math", line 115, in main
    tractography, *args.operation_parameters)
  File "/home/tb571/Downloads/pnlpipe/soft_dir/tract_querier-c57d670/tract_querier/tract_math/decorator.py", line 141, in wrapper
    process_output(out, file_output=file_output)
  File "/home/tb571/Downloads/pnlpipe/soft_dir/tract_querier-c57d670/tract_querier/tract_math/decorator.py", line 176, in process_output
    tractography_to_file(file_output, output)
  File "/home/tb571/Downloads/pnlpipe/soft_dir/tract_querier-c57d670/tract_querier/tractography/__init__.py", line 85, in tractography_to_file
    return tractography_to_vtk_file(filename, tractography, **kwargs)
  File "/home/tb571/Downloads/pnlpipe/soft_dir/tract_querier-c57d670/tract_querier/tractography/vtkInterface.py", line 29, in tractography_to_vtk_file
    tractography.tracts_data()
  File "/home/tb571/Downloads/pnlpipe/soft_dir/tract_querier-c57d670/tract_querier/tractography/vtkInterface.py", line 324, in write_vtkPolyData
    poly_data = tracts_to_vtkPolyData(tracts, tracts_data=tracts_data)
  File "/home/tb571/Downloads/pnlpipe/soft_dir/tract_querier-c57d670/tract_querier/tractography/vtkInterface.py", line 267, in tracts_to_vtkPolyData
    vtk_ids = ns.numpy_to_vtkIdTypeArray(ids, deep=True)
  File "/home/tb571/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/vtk/util/numpy_support.py", line 198, in numpy_to_vtkIdTypeArray
    return numpy_to_vtk(num_array, deep, vtk.VTK_ID_TYPE)
  File "/home/tb571/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/vtk/util/numpy_support.py", line 137, in numpy_to_vtk
    assert not numpy.issubdtype(z.dtype, complex), \
  File "/home/tb571/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/numpy/core/numerictypes.py", line 743, in issubdtype
    FutureWarning, stacklevel=2
  File "/home/tb571/miniconda3/envs/pnlpipe3/lib/python3.6/warnings.py", line 101, in _showwarnmsg
    _showwarnmsg_impl(msg)
  File "/home/tb571/miniconda3/envs/pnlpipe3/lib/python3.6/warnings.py", line 28, in _showwarnmsg_impl
    text = _formatwarnmsg(msg)
  File "/home/tb571/miniconda3/envs/pnlpipe3/lib/python3.6/warnings.py", line 116, in _formatwarnmsg
    msg.filename, msg.lineno, line= msg.line)
TypeError: custom_formatwarning() got an unexpected keyword argument 'line'
```

2018-11-06 15:07 UTC, tashrifbillah commented
Submitted issue on https://bugs.python.org/issue35178?@ok_message=pull_request%209663%20created%0Amsg%20329363%20created%0Aissue%2035178%20created&@template=item

2018-11-07 23:51 UTC, vstinner requested changes
Please write a test checking that replacing warnings.formatwarning() with a new function, and the last parameter of this function is not called 'line', still works.

2019-02-22 21:26 UTC, tashrifbillah commented
Hi guys,

Grammatically, there is nothing that prevents specifying the last argument with keyword `line= `. Based on this understanding, I found a [monkey patching](https://stackoverflow.com/questions/2187269/print-only-the-message-on-warnings) in the repo I was working on:
```
def custom_formatwarning(msg, *a):
    # ignore everything except the message
    return '\nWarning: ' + str(msg) + '\n'

warnings.formatwarning = custom_formatwarning
```

I believe the above patch was responsible for the error I got (can't see straight how though). I removed the monkey patch, and it's working fine now.

So, you are welcome to close the PR w/o merging.

2019-02-25 08:42 UTC, vstinner commented
https://bugs.python.org/issue35178 is a real bug and I like your fix, but a test must be written. Do you want to write a test? If not, I can ask someone else to do it.

2019-02-25 14:15 UTC, tashrifbillah commented
Hi @vstinner , based on my timing, I am unable to make a promise. So, please feel free to ask someone. Thanks!

2019-03-07 17:27 UTC, vstinner commented
Thanks @tashrifbillah! I merged PR #12033 written by @tirkarthi based on this PR.

2019-03-07 17:27 UTC, closed without merging