gh-103556: [inspect.Signature] disallow pos-or-kw params without default after pos-only with default
python/cpython pull request #103557
Opened 2023-04-15 09:47 UTC by sobolevn

I consider this a bug fix, not a new feature. So, backport to 3.11 should probably be done.

2023-04-15 11:28 UTC, sobolevn commented
`test_nntplib` failure seems unrelated, but I cannot re-trigger Azure build.

2023-04-15 11:42 UTC, sobolevn commented on Lib/test/test_inspect.py
> +        # all arg kinds in a single one.
```suggestion
        # We need two functions, because it is impossible to represent
        # all param kinds in a single one.
```

2023-04-16 11:45 UTC, sobolevn commented
@hauntsaninja if you are interested in this as well after https://github.com/python/cpython/pull/103554 I would be very grateful :)

2023-04-17 16:10 UTC, carljm requested changes
Thanks for finding and fixing this!

I think the fix can be even simpler, though; see inline comment.

2023-04-17 16:10 UTC, carljm commented on Lib/inspect.py
> +                            kind_defaults = False
non-default-after-default is only checked for `_POSITIONAL_ONLY` and `_POSITIONAL_KEYWORD` (see line 3032.) So if we want to keep the value of `kind_defaults` across the transition from PO to POK (which I do agree is correct and matches the parser behavior), then really we always want to keep it, and it is no longer `kind_defaults` but simply `seen_default`. So I think we can eliminate all of this, here's the full version I'd recommend (which passes all tests): https://gist.github.com/carljm/6779e601d04e0b1135444b4e0263e281

2023-04-19 08:39 UTC, sobolevn commented on Lib/inspect.py
> +                            kind_defaults = False
Yes, I agree, thank you for the suggestion.

2023-04-19 08:40 UTC, sobolevn commented
I have made the requested changes; please review again

2023-04-22 05:44 UTC, carljm approved these changes

2023-04-22 05:45 UTC, merged

2023-04-22 05:45 UTC, miss-islington commented
Thanks @sobolevn for the PR, and @carljm for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖