gh-103650: Fix perf maps address format
python/cpython pull request #103651
Opened 2023-04-20 16:00 UTC by art049

Fixes #103650

2023-04-20 16:55 UTC, sunmy2019 requested changes

2023-04-20 16:55 UTC, sunmy2019 commented on Python/perf_trampoline.c
> +    fprintf(method_file, "%llx %x py::%s:%s\n", code_addr, code_size, entry,
What if it's a 32-bit machine? Python still supports that https://www.python.org/downloads/release/python-3120a7/

Also, the compiler reports a lot of warnings. This should be fixed.

2023-04-20 16:56 UTC, sunmy2019 commented on Python/perf_trampoline.c
> +    fprintf(method_file, "%llx %x py::%s:%s\n", code_addr, code_size, entry,
%p is an implementation-defined format specifier; the c11 specs don't clarify if it contains "0x"

2023-04-20 17:13 UTC, art049 commented on Python/perf_trampoline.c
> +    fprintf(method_file, "%llx %x py::%s:%s\n", code_addr, code_size, entry,
I casted to `uintptr_t` and used `PRIxPTR` to handle the format. This fixed compiler warnings and should work both on 32 and 64-bit machines.

2023-04-20 18:46 UTC, terryjreedy commented
I think that this should wait until Pablo verifies that it is indeed the implementation that should be changed.

2023-05-05 15:27 UTC, carljm commented
@art049 did you verify that the new output after this PR works the same with `perf`?

@terryjreedy since the relevant docs here are the external perf map specification, not the CPython docs, it seems clear that the implementation in CPython should match the specification. There is no option to change the specification, we don't own it.

2023-05-07 11:56 UTC, pablogsal commented
Running this PR with the buildbots as the perf stuff is not checked on regular CI.

2023-05-07 19:42 UTC, pablogsal approved these changes

2023-05-07 19:42 UTC, merged