gh-103848: Adds checks to ensure that bracketed hosts found by urlsplit are of IPv6 or IPvFuture format
python/cpython pull request #103849
Opened 2023-04-25 19:45 UTC by JohnJamesUtley

2023-05-09 15:48 UTC, gpshead requested changes

2023-05-09 15:48 UTC, gpshead commented on Lib/urllib/parse.py
> +            hostname, _, port = bracketed.rpartition(']')
Is the change from partition(']') to rpartition(']') important?

That means this will be finding the final ] instead of the first ] after the opening [.

not that I expect it matters given that a ] appearing within [] in a hostname is presumably always invalid.

2023-05-09 15:48 UTC, gpshead commented on Lib/urllib/parse.py
> +        if not re.match(r"\Av[a-fA-F0-9]+\..+\Z", hostname):
Add a comment linking to the spec (RFC or WHATWG) that defines this.

2023-05-09 15:48 UTC, gpshead commented on Lib/test/test_urlparse.py
> +    def test_splitting_bracketed_hosts(self):
split this into two test methods: error cases and allowed cases.

2023-05-09 15:48 UTC, gpshead commented on Lib/urllib/parse.py
> +        if '[' in netloc and ']' in netloc:
being pedantic, can you add a test that something like `scheme://]v6a.ip[/` with the [ and ] swapped on something that'd have been valid won't be accepted?

all of the code merely looking for [ and ] within the netloc sans obvious specific order could use it.  (i expect it properly fails, it's just a nice testcase to have).

2023-05-09 23:52 UTC, gpshead approved these changes

2023-05-10 00:18 UTC, merged

2023-05-10 00:18 UTC, miss-islington commented
Thanks @JohnJamesUtley for the PR, and @gpshead for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2023-05-10 00:18 UTC, miss-islington commented
Sorry @JohnJamesUtley and @gpshead, I had trouble checking out the `3.11` backport branch.
                                Please retry by removing and re-adding the "needs backport to 3.11" label.
                                Alternatively, you can backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on the command line.
                                ```
                                cherry_picker 29f348e232e82938ba2165843c448c2b291504c5 3.11
                                ```

2023-05-10 06:10 UTC, miss-islington commented
Thanks @JohnJamesUtley for the PR, and @gpshead for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2024-11-20 21:38 UTC, BitterDone commented
Hi @miss-islington and @gpshead - how do I ensure I'm using a version of Python with this vulnerability fixed?

I'm supporting a team that uses hardened containers from Iron Bank and I don't believe the approved containers will get the back port updates. 

Since 3.11 is the newest version mentioned here for a back port, does the initial release of 3.12 include this fix?

2024-11-29 01:35 UTC, CharlieZhao95 commented
> Since 3.11 is the newest version mentioned here for a back port, does the initial release of 3.12 include this fix?

The release date of Pyton3.12 is 2023-10, so of course, 3.12 contains this patch. BTW miss-islington is a bot for PR. 😉