gh-NNNN: Skip creating GatheringFuture if all futures finished eagerly
python/cpython pull request #104138
Opened 2023-05-03 17:51 UTC by itamaro

2023-05-04 00:10 UTC, carljm reviewed
This looks pretty straightforward and reasonable to me, but would prefer for asyncio experts to take a look.

2023-05-04 00:10 UTC, carljm commented on Misc/NEWS.d/next/Library/2023-05-03-16-50-24.gh-issue-104144.yNkjL8.rst
> +without blocking - for up to 3x speedup
I'm not sure about advertising 3x speedup here; IIUC that's the absolute best-case scenario when _everything_ finishes eagerly, probably not very realistic for most users.

Also the grammar is a little confused here, let's clean that up and maybe add some cross-references.

```suggestion
Optimize :func:`asyncio.gather` when using :func:`asyncio.eager_task_factory`.
Skip creating gathering future and scheduling done callbacks when all futures finish
without blocking.
```

2023-05-04 01:56 UTC, jbower-fb requested changes
If you look at `gather._done_callback()` you'll see it has a bunch of logic which gets executed at the moment all the futures have finished (starting from `if nfinished == nfuts:` on line 781). If all args can complete eagerly then this will be executed eagerly too.

This might have a few issues:
* At this point `outer` will be `None` and this will cause trouble on line 803. (Maybe I missed something because I'm surprised this hasn't come up yet).
* Handling for futures that were cancelled during eager execution is processed but the results discarded.
* We inefficiently create a result list which we discard and then repeat when creating the eagerly completed future result.

Fortunately, I *think* an easy fix is to move creation of the eager result future to before the argument processing loop. See my in-line comments for specifics.

I'm not 100% sure how this will affect the issue described in bpo-46672, but it has a test so we'll see.

2023-05-04 01:56 UTC, jbower-fb commented on Lib/asyncio/tasks.py
> +        outer = futures.Future(loop=loop)
This should be moved up to replace the existing line 817.

2023-05-04 01:56 UTC, jbower-fb commented on Lib/asyncio/tasks.py
> +        outer.set_result([c.result for c in children])
This can be removed as it will be implemented in the `_done_callback()` if everything finishes eagerly.

2023-05-04 01:56 UTC, jbower-fb commented on Lib/asyncio/tasks.py
> +    if all_finished:
```suggestion
    if nfuts == nfinished:
```

2023-05-04 01:56 UTC, jbower-fb commented on Lib/asyncio/tasks.py
> +    all_finished = True
(See suggestions below)
```suggestion
```

2023-05-04 01:56 UTC, jbower-fb commented on Lib/asyncio/tasks.py
> +                all_finished = False
```suggestion
```

2023-05-04 01:56 UTC, jbower-fb commented on Lib/asyncio/tasks.py
> +        outer = _GatheringFuture(children, loop=loop)
```suggestion
        outer.__self_log_traceback = False
        outer = _GatheringFuture(children, loop=loop)
```

2023-05-05 19:04 UTC, carljm commented
The title no longer accurately describes the updated PR, since the `_GatheringFuture` is always created.

2023-05-05 19:05 UTC, itamaro commented
thanks for the review @jbower-fb !

I pushed a new version of the PR based on your suggestions, but not identical.
summary of my changes:
- instead of immediately calling the done callbacks for eagerly completed futures in the loop, I add them to a list and call their callbacks only at the end, after creating the outer future
- this helps because now outer is defined the same way, and the children list is fully populated, which is also important because the done callback uses the children list
- I always create a GatheringFuture so I get the same cancellation treatment, but it will still finish eagerly if all futures completed eagerly thanks to the last done callback right before returning
- there shouldn't be any issues with bpo-46672 since outer looks the same as before

2023-05-05 19:06 UTC, itamaro commented
> The title no longer accurately describes the updated PR, since the `_GatheringFuture` is always created.

thanks, I updated the title!

2023-05-06 14:49 UTC, gvanrossum approved these changes
LGTM, will fix the typo. Maybe @carljm can merge when you all are agreed on this. Nice fix!

2023-05-06 14:49 UTC, gvanrossum commented on Misc/NEWS.d/next/Library/2023-05-03-16-50-24.gh-issue-104144.yNkjL8.rst
> +Avoid scheduling done callbacks for fututres that complete eagerly.
Typo
```suggestion
Avoid scheduling done callbacks for futures that complete eagerly.
```

2023-05-06 14:51 UTC, gvanrossum commented
PS. In _general_ there's no need to click the "Update branch" button (or otherwise merge main back into the PR) *unless* there are fixes/changes that might affect the PR (e.g. if touching the same file).

2023-05-06 14:53 UTC, kumaraditya303 approved these changes

2023-05-06 15:15 UTC, merged