gh-69152: add method get_proxy_response_headers to HTTPConnection class
python/cpython pull request #104248
Opened 2023-05-06 20:25 UTC by nametkin

Correction according to this comment: https://github.com/python/cpython/pull/26152#discussion_r1186507045

2023-05-08 12:53 UTC, nametkin commented
@gpshead, please look at this PR. Did I understand your idea correctly?

2023-05-09 15:01 UTC, gpshead requested changes
yep, this is what I had in mind. Thanks for the followup PR.

2023-05-09 15:01 UTC, gpshead commented on Misc/NEWS.d/next/Library/2023-05-08-11-52-56.gh-issue-69152.tlH-q1.rst
Instead of a new NEWS entry file, I suggest just editing and rewording Misc/NEWS.d/next/Library/2021-05-16-14-28-30.bpo-24964.Oa5Ie_.rst from the original PR #26152 as this changes its implementation.

Don't mention internal _private_attributes in the NEWS entry, just describe the new public API.  Line 4 onwards in the text you have in here.

2023-05-09 15:01 UTC, gpshead commented on Lib/http/client.py
> +    def get_proxy_response_headers(self):
Document this new method in Doc/library/http/client.rst and include a `.. versionadded:: 3.12` marker.

2023-05-10 09:42 UTC, nametkin commented
@gpshead, thank you for review.
I have made the requested changes; please review again

2023-05-15 18:17 UTC, arhadthedev commented
The PR will be merged after the feature freezing 3.12b1 is published next week. Currently core devs implement remaining PEPs and fix bugs introduced by them.

2023-05-16 05:54 UTC, gpshead approved these changes

2023-05-16 06:20 UTC, merged

2023-06-10 09:13 UTC, sobolevn commented
Sorry for being late for the review, but I would like to note that `get_proxy_response_headers` now is not consistent in its return type. If there are headers, it returns `HTTPMessage` class (which has this `mro`: `(<class 'http.client.HTTPMessage'>, <class 'email.message.Message'>, <class 'object'>)`), but if there no headers it returns `{}`. Why?

I think that the source of this confusion is that `email.message.Message` behaves like a `Mapping`, but I still think that we should change the default value to `None` before it is too late.

This way we can say that this method returns `Optional[HTTPMessage]` and not `HTTPMessage | dict[str, str]` (or `Mapping[str, str]`, which will erase a lot of useful methods).

I will open a new PR for this.