gh-104400: pygettext: use an AST parser instead of a tokenizer
python/cpython pull request #104402
Opened 2023-05-11 21:17 UTC by tomasr8

This PR replaces the token-based message extraction with one that uses the AST parser instead.
See the [issue](https://github.com/python/cpython/issues/104400) or the [forum discussion](https://discuss.python.org/t/modernize-and-add-missing-features-to-pygettext/26455) for more info.

This change fixes some issues just by virtue of using AST instead of working directly with tokens:

- docstrings with leading blank lines are extracted correctly
- dosctrings like `"""Hello, {}!""".format('world')` are no longer extracted
- docstrings are cleaned with  `inspect.cleandoc()` via `ast.get_docstring()`
- This is now correctly extracted:
```python
def test(x=_('param')):
    pass
```

I added a CLI argument `--charset` (same as in pybabel and `--from-code` in xgettext) to force a file encoding, e.g. `--charset=utf-8` will open the source files with `utf-8` encoding. This is useful because currently we are relying on the system default which is error-prone. For example on Windows, `open()` in my locale defaults to `cp1250` which mangles up `utf-8` files and vice versa (with some `UnicodeDecoreError`s in between).

This PR has lots more tests to make sure we don't regress on anything. The tests now compare the script output to a `.po` file rather than just comparing the `msgid`s (basically snapshot tests). This ensures that we also catch issues with formatting, line locations or anything else.

I moved the test files into a separate folder, so the diff of `test_i18n.py` is not that useful.. Check out just the last commit to see a better diff.

@warsaw if you feel like having a look (or anyone else ;))

2023-06-12 18:42 UTC, arhadthedev commented on Tools/i18n/pygettext.py
> +        # "Höhe"' would result not result in 'msgid "H\366he"'.  Otherwise we
The `would result not result` part is confusing. It should be either `would result` or `would not result` since the PR touches this line anyway.

2023-06-12 18:44 UTC, arhadthedev commented on Tools/i18n/pygettext.py
> +        # "Höhe"' would result not result in 'msgid "H\366he"'.  Otherwise we
(I forgot to press the `Submit review` button until I noticed the Pending badge here today)

2023-08-03 08:17 UTC, tomasr8 commented
@ambv This is what I talked to you about at EuroPython. If you have time I'd be very happy if you could have a look :)

The TL;DR is pygettext has a couple of bugs which stem from it using a tokenizer-based extraction (and overall the code needs modernizing). I fix those bugs in this PR by switching to a parser. Otherwise I try to keep the functionality as close as possible. I also added lots more tests which compare the entire output and not just the messages as it was previously.

There are also lots of features missing in pygettext - handling ngettext, pgettext and others, format flags, etc..
Once this is done, I will submit patches for those missing features as well - I didn't want to put everything in one giant PR as it's already pretty big.

Thank you!

2023-08-08 06:25 UTC, AA-Turner commented
@tomasr8 would it be possible to break this PR up into several chunks / stages? You may have more luck with reviewers & progress -- I'm happy to help if wanted.

A

2023-08-08 07:08 UTC, tomasr8 commented
> @tomasr8 would it be possible to break this PR up into several chunks / stages? You may have more luck with reviewers & progress -- I'm happy to help if wanted.

I can definitely give it a try! I think it'll be difficult to separate the actual change from tokens to AST, since that's kind of an all-or-nothing change but I could start with improving the tests first in a separate PR. That should be an added value regardless of whether the rest gets merged or not. I'll see if I can get a separate PR for the tests in the coming days.

Any help/review is greatly appreciated of course! :)

2023-08-20 17:13 UTC, tomasr8 commented
@AA-Turner I opened a separate [PR](https://github.com/python/cpython/pull/108173) just adding extra tests, if you wanna have a look ;)

2024-10-19 07:50 UTC, Wulian233 commented
There was a recent issue in support of f-string https://github.com/python/cpython/issues/113604 , that mentioned this. AST makes this feature easier to add

https://github.com/python/cpython/pull/108173/files already contains the required tests, can you remove them in this PR, so that the diff will be smaller and easier to review

2024-10-19 20:21 UTC, tomasr8 commented
> There was a recent issue in support of f-string #113604 , that mentioned this. AST makes this feature easier to add
> 
> https://github.com/python/cpython/pull/108173/files already contains the required tests, can you remove them in this PR, so that the diff will be smaller and easier to review

Don't waste your time reviewing this PR just yet, we should get the tests merged before moving on with this :) Actually, it's been a while since I opened the tests PR, it might need updating first..

2024-11-30 19:40 UTC, tomasr8 commented
Alright, I think this is reviewable again. With https://github.com/python/cpython/pull/126912 merged, it was possible to simplify this PR quite a bit since the data structures are already in place. The main change is really just about replacing the tokenizer with a parser.

Using a parser fixes a lot of issues that would've been hard and/or annoying to fix within the tokenizer (see the first post for a list).

I also added some additional tests for error messages. Feedback welcome!

2024-12-16 21:37 UTC, tomasr8 commented
cc @serhiy-storchaka in case you missed this :slightly_smiling_face:

2025-02-02 13:28 UTC, AA-Turner requested changes
General points: 

* Please adhere to PEP 8 (several lines here exceed 79 characters).
* There are a few changes that increase the diff and could be extracted to a preparatory PR -- extracting `write_pot_file()` to a module-level function, moving `key_for` to the class, sorting imports, adding extra whitespace.
* We could consider defining the public interface of `pygettext` to just the command-line interface; otherwise, this PR does affect non-underscored names

A

2025-02-02 13:28 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +from ast import AsyncFunctionDef, ClassDef, FunctionDef, Module, NodeVisitor
```suggestion
```

2025-02-02 13:28 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +class GettextVisitor(NodeVisitor):
```suggestion
class GettextVisitor(ast.NodeVisitor):
```

2025-02-02 13:28 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +            self._extract_docstring(node)
```suggestion
        if isinstance(
            node,
            (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
        ):
            self._extract_docstring(node)
```

However, you could also use try/except, as `ast.get_docstring()` has an internal check identical to this:

```suggestion
        try:
            self._extract_docstring(node)
        except TypeError:
            pass
```

2025-02-02 13:28 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +        if (spec := self.options.keywords.get(funcname)) is None:
I generally only use assignment expressions when the variable is only used within the relevant block.
```suggestion
        func_name = self._get_func_name(node)
        spec = self.options.keywords.get(func_name)
        if spec is None:
```

2025-02-02 13:28 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +    def _get_funcname(self, node):
```suggestion
    def _get_func_name(self, node):
```

2025-02-02 13:28 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +    def _key_for(self, msgid, msgctxt=None):
```suggestion
    @staticmethod
    def _key_for(msgid, msgctxt=None):
```

2025-02-02 13:28 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +            visitor.visit(ast.parse(fp.read()))
```suggestion
            module_tree = ast.parse(fp.read())
            visitor.filename = filename
            visitor.visit(module_tree)
```

2025-02-03 17:21 UTC, tomasr8 commented
Thanks a lot for the review!

> There are a few changes that increase the diff and could be extracted to a preparatory PR -- extracting write_pot_file() to a module-level function, moving key_for to the class, sorting imports, adding extra whitespace.

Good point! I'll do that :)

> We could consider defining the public interface of pygettext to just the command-line interface

Yes I think that makes sense, it is a CLI tool after all (eventually some of the functionality such as writing POT files could be made available but I think that is a long way off). How do we go about doing that? A note in the docs?

2025-02-03 17:33 UTC, AA-Turner commented
> How do we go about doing that? A note in the docs?

I don't think `pygettext` is documented anywhere beyond a passing reference in the `gettext` module (it is in `Tools/`, after all). A note in the docstring would probably suffice, or a comment at the top of the file?

A

2025-02-03 17:47 UTC, tomasr8 commented
Yeah, it doesn't have a dedicated docs page. The module dosctring seems like the best choice

2025-02-03 20:49 UTC, m-aciek commented on Tools/i18n/pygettext.py
Introduction in docstring with statements about GNU Gettext are no longer up-to-date, as far as I'm concerned. I believe nowadays it extracts from Python code ~just fine. Would you be willing to update it at the occasion?

```
There's one problem though; xgettext is the program that scans source code
looking for message strings, but it groks only C (or C++). Python
introduces a few wrinkles, such as dual quoting characters, triple quoted
strings, and raw strings. xgettext understands none of this.
```

2025-02-03 21:15 UTC, tomasr8 commented on Tools/i18n/pygettext.py
Yeah, you're right, xgettext supports Python these days. I will update the docstring :+1:

2025-02-05 22:08 UTC, tomasr8 commented
Thank you once again for the review! I think this can be reviewed again :) I believe I addressed all your points. I also fixed the lines to not exceed 79 characters, however there are more long lines in parts of the script which this PR does not touch. Do you want me to fix them as well or would you prefer to keep the diff smaller?

I have made the requested changes; please review again :slightly_smiling_face:

2025-02-06 16:18 UTC, AA-Turner reviewed
I'm not an amazing fan of reusing the same visitor for every file. There's not massive performance benefits, and it means we have tricks with resetting the filename, etc.

However, if you'd prefer to keep the current design, could we add a `walkabout` or `initiate_visit` or etc method that takes the node tree and filename, to conceptually keep the two together during tree traversal?

2025-02-06 16:18 UTC, AA-Turner commented on Lib/test/test_tools/i18n_data/messages.py
> -_(("invalid"))
Perhaps this was intended to be a one-tuple? The following elements are a single-element list and set.

```suggestion
_(("invalid",))
```

2025-02-06 16:18 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +    def __init__(self, options, filename=None):
```suggestion
    def __init__(self, options):
```

2025-02-06 16:18 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +            lineno = node.body[0].lineno
Could you add a comment to explain which node the line number comes from?

2025-02-06 16:18 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +        self.filename = filename
The filename argument is never used
```suggestion
        self.filename: str = ''
```

2025-02-06 16:18 UTC, AA-Turner commented on Tools/i18n/pygettext.py
> +        self.messages = {}
Add a type annotation?

2025-02-06 20:53 UTC, serhiy-storchaka reviewed
Great! It is now much simpler. And it works more correctly!

There are still some issues with var-positional arguments. Since we cannot determine the argument position in such case, it should be rejected.

2025-02-06 20:53 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +        if type(node) in {Module, FunctionDef, AsyncFunctionDef, ClassDef}:
Why not use visit_Module etc?

2025-02-06 20:53 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +        if (docstring := ast.get_docstring(node, clean=True)) is not None:
I do not think that using `:=` makes this code more clear.

2025-02-06 20:53 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +        if (docstring := ast.get_docstring(node)) is not None:
Please do not use `:=` without need. It does not improve readability.

2025-02-06 20:53 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +            self._extract_docstring(node)
Should not it only be called in `visit_Module`?

2025-02-06 20:53 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +        if not matches_spec(msg_data, spec):
This is no longer needed, because we iterated all `spec` items above.

2025-02-06 20:53 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +        if max(spec) >= len(node.args):
Note that this (and the code in the loop below) does not work well for `dgettext(*a, "msg")`. We cannot statically determine the number of arguments before "msg". We should check that there are no var-positional arguments before `max(spec)`.

2025-02-06 20:53 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +            module_tree = ast.parse(fp.read())
Since we need all file content at once instead of reading it line by line, we can simplify reading. Read it by
```
source = sys.stdin.buffer.read()
```
and
```
with open(filename, 'rb') as fp:
    source = fp.read()
```
and get rid of `closep` and `try`/`finally`.

2025-02-06 20:53 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +        self.messages = {}
Since type annotations were not used in this file, this is not needed. It will introduce a lot of unrelated changes.

2025-02-06 20:53 UTC, serhiy-storchaka commented on Lib/test/test_tools/i18n_data/messages.py
> -_(("invalid"))
No, it tested a literal string nested in parentheses. Now this is supported.

2025-02-06 21:49 UTC, tomasr8 commented on Tools/i18n/pygettext.py
> +            self._extract_docstring(node)
Adam pointed out that `ast.get_docstring` internally checks the type of the node being passed, so this is safe to call on an arbitrary node

2025-02-06 22:05 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +            self._extract_docstring(node)
But this is ineffective.

2025-02-06 22:29 UTC, tomasr8 commented on Tools/i18n/pygettext.py
> +            self._extract_docstring(node)
ok, I added a visit method for each node that can contain a docstring :)

2025-02-06 22:29 UTC, tomasr8 commented on Tools/i18n/pygettext.py
> +        if not matches_spec(msg_data, spec):
Removed!

2025-02-06 22:30 UTC, tomasr8 commented on Tools/i18n/pygettext.py
> +        if max(spec) >= len(node.args):
I added an explicit check for var-positional arguments

2025-02-06 22:30 UTC, tomasr8 commented on Tools/i18n/pygettext.py
> +            module_tree = ast.parse(fp.read())
Done :)

2025-02-06 22:36 UTC, tomasr8 commented
> I'm not an amazing fan of reusing the same visitor for every file. There's not massive performance benefits, and it means we have tricks with resetting the filename, etc.

I didn't really do this for performance but so that I don't need to pass the `messages` dictionary. If I create a new visitor for each file, I still need to pass the messages to it. I thought that passing the filename was simpler, so I did it this way, but if you prefer it the other way, just tell me and I'll change it :slightly_smiling_face:  For now, I added `GettextVisitor.visit_file(module_tree, filename)` which sets the filename before extracting the messages.

2025-02-06 22:39 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +    def visit_ClassDef(self, node):
You can also use aliases if you prefer.
```py
visit_ClassDef = ... = visit_Module
```

2025-02-06 22:39 UTC, serhiy-storchaka commented on Tools/i18n/pygettext.py
> +        if message := self.messages.get(key):
`:=` is not needed here too.

2025-02-07 18:17 UTC, tomasr8 commented
(The Windows failure is some unrelated build failure)

2025-02-11 11:46 UTC, serhiy-storchaka approved these changes

2025-02-11 11:51 UTC, merged

2025-02-11 11:55 UTC, tomasr8 commented
Woohoo! 🎉🎉 it took almost two years but we got there :) Thanks @serhiy-storchaka and @AA-Turner for your patience and help!