gh-104523: use dynamic rule for compiling libmpdec and libexpat
python/cpython pull request #104574
Opened 2023-05-17 04:14 UTC by indygreg

Before we had a separate rule for each source/object file. We can use `$(foreach $(eval $(call ...)))` to dynamically derive rules to avoid the repetition.

I _think_ this is sufficiently portable. If not, there are alternatives to `$(patsubst)` that can be leveraged.

2023-05-18 21:18 UTC, erlend-aasland commented
cc. also @ned-deily who has opinions about the build process.

2023-05-18 21:39 UTC, indygreg commented
FWIW I have a follow-up change to the module freezing code that is a net -100 lines on the diff which uses a similar approach to reduce make boilerplate and redundancy. That one more clearly demonstrates value in the general pattern than this one. But the justifications are basically the same.

2023-05-18 22:19 UTC, zware commented
Is this really more portable than the pattern rule approach?  It's certainly more cryptic :)

In these particular cases, I'd personally like to work towards getting `libmpdec` and `expat` out of our repository entirely (i.e., make `--with-system-expat --with-system-libmpdec` the default and later only way to build), though that's a bigger project with a longer timeline.  I wonder if it would make sense to pull in a bit extra from these packages for now in order to delegate to their own build system to build them instead of shoehorning them into ours, but a cursory look says that's probably more effort than it's worth.

This looks reasonable enough to try it on the buildbots, at least.

2023-05-19 16:31 UTC, zware commented
The buildbot failures don't look related to this change.

2023-05-19 18:40 UTC, ned-deily commented
> The buildbot failures don't look related to this change.

@zware, it looks like the FreeBSD buildbot build didn't or hasn't run yet? I *think* this is the relevant [buildrequest](https://buildbot.python.org/all/#/buildrequests/1209653).

2023-05-19 18:45 UTC, zware commented
That worker has apparently been down for about 4 months now, though I can't tell at a glance if the fault lies on the client or server side (@koobs?)

2023-05-20 15:47 UTC, erlend-aasland commented
IMO, we should wait for 3.13 to open before landing this.

2023-05-20 23:19 UTC, indygreg commented
I didn't realize we were only days away from the end of the 3.12 new features window. I guess I'm so used to Rust and its 6 week release cadence.

Anyway, yes, I'm fine waiting until the 3.13 window to land more invasive build system changes. (Not like I have much choice in the matter.)

2023-06-22 10:21 UTC, erlend-aasland commented
@indygreg: How does this fare on BSD Make?

2023-09-04 10:11 UTC, vstinner commented
On my FreeBSD, I can no longer build Python :-( 

```
$ make
make: "/usr/home/vstinner/python/main/Makefile" line 1047: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1050: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1052: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1062: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1065: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1067: Invalid line type
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/vstinner/python/main
```

I have;

```
$ make -V MAKE_VERSION
20220208
```

2023-09-04 10:21 UTC, erlend-aasland commented
> On my FreeBSD, I can no longer build Python :-(

Could you build it on FreeBSD before this PR?

2023-09-04 22:25 UTC, vstinner commented
> Could you build it on FreeBSD before this PR?

Sorry. I mean: currently, on the **main** branch of Python (without this PR), I can no longer build Python :-(

2023-09-05 07:26 UTC, erlend-aasland commented
> > Could you build it on FreeBSD before this PR?
> 
> Sorry. I mean: currently, on the **main** branch of Python (without this PR), I can no longer build Python :-(

Aha, so this PR does not change the status quo! I suspected that. I guess we should clarify _if_ was want to restore BSD Make compatibility, _or_ carry on with GNU Make only.

2023-09-05 16:52 UTC, vstinner commented
Please fix building Python on FreeBSD before making the situation worse.

2023-09-05 16:53 UTC, vstinner commented
Sadly, the maintainer how our two FreBSD decided to remove them. Right now, there is no FreeBSD CI. We should consider CirrusCI.

2023-09-05 18:33 UTC, vstinner commented
I tested FreeBSD again, and I'm sorry, I didn't test make correctly previously.

* Building Python in the main branch on FreeBSD is fine!
* Building Python with this PR on FreeBSD no longer works

This PR introduces these issues in Makefile:

```
$ make
make: "/usr/home/vstinner/python/main/Makefile" line 1047: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1050: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1052: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1062: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1065: Invalid line type
make: "/usr/home/vstinner/python/main/Makefile" line 1067: Invalid line type
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/vstinner/python/main
```

Surprise, surprise, it's the "non portable" part of this PR which introduces the issue. Like:

```
# "%.o: %c" is not portable
define libmpdec_compile
$(1): $$(srcdir)/$$(patsubst %.o,%.c,$(1)) $$(LIBMPDEC_HEADERS) $$(PYTHON_HEADERS)
        $$(CC) -c $$(LIBMPDEC_CFLAGS) -o $$@ $$<
endef
```

2023-09-05 18:34 UTC, vstinner requested changes
While it's appealing to use cool GNU make features to make the Makefile shorter, I don't think that it's worth it if in exchange we break FreeBSD support.

FreeBSD is a Tier-3 platform: https://peps.python.org/pep-0011/

Is there another command which is compatible with GNU make **and** bsdmake?

2023-10-04 10:56 UTC, vstinner commented
@erlend-aasland: Is this change worth it if it breaks FreeBSD support? Should we just close it?

2023-10-04 11:00 UTC, erlend-aasland commented
!buildbot .*freebsd.*

2023-10-04 11:01 UTC, erlend-aasland commented
!buildbot .*FreeBSD.*

2023-10-04 11:03 UTC, erlend-aasland commented
> @erlend-aasland: Is this change worth it if it breaks FreeBSD support? Should we just close it?

If it breaks FreeBSD support it is not worth it. There might be a more portable approach, though. cc. @indygreg

2023-10-04 11:17 UTC, erlend-aasland commented
> Do you expect that FreeBSD buildbot will behave differently than my previous manual test? [#104574 (comment)](https://github.com/python/cpython/pull/104574#issuecomment-1707119051)
> 
> The PR didn't change in the meanwhile.

Oh, I forgot you already tested this!

2023-10-04 12:00 UTC, vstinner commented
> buildbot/AMD64 FreeBSD PR — Build done.

Fail to build:

```
 using PTY: False
make: "/buildbot/buildarea/pull_request.ware-freebsd/build/Makefile" line 1049: Invalid line type
make: "/buildbot/buildarea/pull_request.ware-freebsd/build/Makefile" line 1052: Invalid line type
make: "/buildbot/buildarea/pull_request.ware-freebsd/build/Makefile" line 1054: Invalid line type
make: "/buildbot/buildarea/pull_request.ware-freebsd/build/Makefile" line 1064: Invalid line type
make: "/buildbot/buildarea/pull_request.ware-freebsd/build/Makefile" line 1067: Invalid line type
make: "/buildbot/buildarea/pull_request.ware-freebsd/build/Makefile" line 1069: Invalid line type
make: stopped in /buildbot/buildarea/pull_request.ware-freebsd/build
make: Fatal errors encountered -- cannot continue
```

2023-10-04 12:07 UTC, indygreg commented
There’s a gmake port on FreeBSD, no? What’s wrong with requiring people to use gmake? Are there actually platforms where GNU Make isn’t trivially installable?

2023-10-05 08:50 UTC, vstinner commented
> What’s wrong with requiring people to use gmake?

It makes building Python on FreBSD more annoying and complicated.

2023-10-05 08:51 UTC, vstinner commented
If someone wants to use more advanced Makefile rule, I suggest to rewrite the whole Python build system with CMake, Meson or anything else.

2026-04-14 05:59 UTC, koobs commented
unstale

2026-04-14 10:42 UTC, vstinner commented
This change breaks support for BSD make on FreeBSD. I don't think that it's worth it, so I prefer to close it.

@zware:
> In these particular cases, I'd personally like to work towards getting libmpdec and expat out of our repository entirely

For libmpdec, there is a concrete plan for that: https://github.com/python/cpython/issues/115119. This PR is mostly about libmpdec, it only changes 6 lines about expat.

> Building Python with this PR on FreeBSD no longer works
>  (...)
> While it's appealing to use cool GNU make features to make the Makefile shorter, I don't think that it's worth it if in exchange we break FreeBSD support.

If someone disagrees, please open a discussion on discuss.python.org suggesting to drop support for BSD make and require GNU make on FreeBSD.

There are also generic discussions about changing the whole Python build system, such as [What do you want to see in tomorrow’s CPython build system?](https://discuss.python.org/t/what-do-you-want-to-see-in-tomorrow-s-cpython-build-system/28197)

@indygreg:
> I think this is sufficiently portable. If not, there are alternatives to $(patsubst) that can be leveraged.

If someone wants to propose a PR using `$(patsubst)`, please go ahead. I can test it on FreeBSD.

Another approach would be to generate the code for `libmpdec`, as we already do to build stdlib extension modules. (I'm not sure which code is involved, maybe `Modules/makesetup`.)

2026-04-14 10:42 UTC, closed without merging