bpo-34864: warn if "Prefer tabs when opening documents" set to "Always"
python/cpython pull request #10464
Opened 2018-11-11 14:48 UTC by taleinat

2018-11-11 21:26 UTC, ned-deily requested changes
The idea is good in principle, thanks.  But the code cannot assume that the preference is always available.

2018-11-11 21:26 UTC, ned-deily commented on Lib/idlelib/macosx.py
> +        return ("WARNING: The version of Tcl/Tk in use ({0}) may"
One reason the wording is as it is is that there may be more than one version of Tk available at a particular patch level, in other words, just knowing the patch level does not uniquely qualify the version of Tk in use.  For example, it might be a Tk built for X-Windows on macOS rather than an Cocoa Aqua version.  Suggest leaving this unchanged.

2018-11-11 21:26 UTC, ned-deily commented on Lib/idlelib/macosx.py
> +def readSystemPrefereces():
`Prefereces` -> `Preferences` (also below)

2018-11-11 21:26 UTC, ned-deily commented on Lib/idlelib/macosx.py
> +    with open(plist_path, 'rb') as plist_file:
This code should handle the case where, for some reason, .`GlobalPreferences.plist` isn't present or readable.

2018-11-11 21:26 UTC, ned-deily commented on Lib/idlelib/macosx.py
> +    if prefs['AppleWindowTabbingMode'] == 'always':
This will get a `KeyError` exception on older versions of macOS before the tabs feature was introduced.

2018-11-11 21:26 UTC, ned-deily commented on Lib/idlelib/macosx.py
> +            'WARNING: The system preferece "Prefer tabs when opening documents"'
`preferece` again

2018-11-11 21:26 UTC, ned-deily commented on Lib/idlelib/macosx.py
> +            ' For the best expereince, change this setting before running IDLE'
`expereince` -> `experience`

2018-11-11 21:26 UTC, ned-deily commented on Lib/idlelib/pyshell.py
> +        # prference is set to "Always".
`prference`

2018-11-11 21:39 UTC, taleinat commented
Thanks for the review @ned-deily!

I have made the requested changes; please review again.

2018-11-11 22:53 UTC, ned-deily approved these changes
LGTM, thanks for making the changes.  BTW, I notice that, with macOS 10.13 at least, if a change to "Always" is made while IDLE is running, the change is honored on the next window open; no need to restart IDLE. So perhaps the message can be simplified. Also, just an FYI, if a tab (rather than a window) is created, it can be converted to a window by control-clicking on the tab title bar and selecting the "Move Tab to New Window" option; this is a standard macOS feature with tabs and seems to work OK with IDLE.

2018-11-12 02:38 UTC, srinivasreddy commented on Lib/idlelib/outwin.py
> -        if isinstance(s, (bytes, bytes)):
:smiley:

2018-11-12 03:05 UTC, terryjreedy requested changes
Thank you both for PR and review.  IDLE still start normally on Windows with patch.
I removed 2.7 backport only because it will have to be done by hand.
Besides CI tests, I think manually testing it on Mac should be enough.

2018-11-12 03:05 UTC, terryjreedy commented on Lib/idlelib/macosx.py
> +    """
tkVersionWarning immediately and pretty obviously returns False on non-Mac systems.
I would like this function to do the equivalent (return None).
`platform` is already imported from sys.
```
if platform == 'darwin':
    return None
```
An alternative would be to put the guard around both calls in pyshell, but if so, a comment would be needed here saying only called on Macs.

2018-11-12 03:05 UTC, terryjreedy commented on Lib/idlelib/outwin.py
> -        if isinstance(s, (bytes, bytes)):
This is 'if isinstance(s, str) in 2.7.  Strange 3.0 conversion, backport not needed.

2018-11-12 03:05 UTC, terryjreedy commented on Lib/idlelib/pyshell.py
>  import tokenize
These might not be in this order in 2.7.

2018-11-12 03:05 UTC, terryjreedy commented on Lib/idlelib/macosx.py
>  """
macosx were macosxSupport and PyShell in 2.7
Imports here were different.

2018-11-12 03:05 UTC, terryjreedy commented on Misc/NEWS.d/next/IDLE/2018-11-11-17-13-50.bpo-34864.cw0PvO.rst
> +On macOS, warn if "Prefer tabs when opening documents" is set to "Always".
For the idlelib/News.txt entry, I am thinking about the more specific
```
When opening IDLE with Shell on macOS, warn if System
Preference "Prefer tabs when opening documents" is set to "Always".
```
Do what you like best for the blurb.

2018-11-12 06:25 UTC, taleinat commented on Misc/NEWS.d/next/IDLE/2018-11-11-17-13-50.bpo-34864.cw0PvO.rst
> +On macOS, warn if "Prefer tabs when opening documents" is set to "Always".
I prefer not mentioning the shell, since that's an implementation detail of how we currently show warnings, and could change in the future.

2018-11-12 06:28 UTC, taleinat commented
Thanks for the review @terryjreedy!

I have made the requested changes; please review again.

Regarding the 2.7 backport, I'll do it manually after this goes in.

2018-11-15 19:56 UTC, terryjreedy commented on Misc/NEWS.d/next/IDLE/2018-11-11-17-13-50.bpo-34864.cw0PvO.rst
> +On macOS, warn if "Prefer tabs when opening documents" is set to "Always".
The issue I addressed is when the check is made, which appears to at at startup if Shell is opened and no code is run by command line options.  Where messages go is a different issue.

2018-11-15 22:14 UTC, terryjreedy commented
If people changes to 'alway' while IDLE is running, there will be no warning until IDLE is started again.  It is up to them to connect 'I changed the setting' to 'IDLE changed behavior'.

2018-11-15 22:14 UTC, terryjreedy approved these changes

2018-12-07 04:19 UTC, terryjreedy commented
Since this was written, there has been a question (report) about this on Stackoverflow.  I added a note to idlelib/NEWS.txt and will merge when CI passes to get this in the upcoming rcs.

2018-12-07 06:32 UTC, merged

2018-12-07 06:32 UTC, miss-islington commented
Thanks @taleinat for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖