[3.11] gh-103606: Improve error message from logging.config.FileConfig (GH-103628)
python/cpython pull request #104687
Opened 2023-05-20 12:40 UTC by Agent-Hellboy

(cherry picked from commit 152227b569c3a9b87fe0483706f704762ced6d75)

2023-05-20 12:44 UTC, Agent-Hellboy commented on Doc/library/logging.config.rst
> +    .. versionadded:: 3.12
I guess we need to change 3.12 to 3.11

2023-05-20 17:24 UTC, gpshead commented on Doc/library/logging.config.rst
> +    .. versionadded:: 3.12
I used versionchanged:: 3.11.4

2023-05-20 17:31 UTC, gpshead requested changes
I wouldn't merge this in 3.11 yet, there are some things to cleanup in main from the original PR first.

2023-05-20 17:37 UTC, Agent-Hellboy commented
>I wouldn't merge this in 3.11 yet, there are some things to cleanup in main from the original PR first.

what are those things?

2023-05-20 18:40 UTC, Agent-Hellboy commented
I have added a PR, #104701

2023-05-20 22:27 UTC, gpshead commented
> Hi @gpshead I have added a PR, https://github.com/python/cpython/pull/104701

merged.  feel free to just apply those edits to this PR as the backport.

2023-05-21 02:30 UTC, Agent-Hellboy commented
I have made the requested changes; please review again

2023-05-21 19:15 UTC, gpshead approved these changes

2023-05-21 19:17 UTC, merged