gh-101282: Revert some M4 style for BOLT configuration
python/cpython pull request #104751
Opened 2023-05-22 15:25 UTC by corona10

2023-05-22 15:48 UTC, ned-deily approved these changes
LGTM, thanks!

2023-05-22 15:58 UTC, corona10 commented
@ned-deily cc @erlend-aasland 

I am preparing another PR too.

2023-05-23 02:04 UTC, corona10 commented
cc @indygreg  Not decided yet which PR will be merged

2023-05-24 06:46 UTC, erlend-aasland requested changes
If we go for this variant, I'd make the list more "git diff" friendly. I left a suggestion for this.

2023-05-24 06:46 UTC, erlend-aasland commented on configure.ac
> + -frame-opt=hot"
```suggestion
  BOLT_APPLY_FLAGS="\
 -update-debug-sections\
 -reorder-blocks=ext-tsp\
 -reorder-functions=hfsort+\
 -split-functions\
 -icf=1\
 -inline-all\
 -split-eh\
 -reorder-functions-use-hot-size\
 -peepholes=none\
 -jump-tables=aggressive\
 -inline-ap\
 -indirect-call-promotion=all\
 -dyno-stats\
 -use-gnu-stack\
 -frame-opt=hot\
"
```

2023-05-24 07:47 UTC, erlend-aasland approved these changes
LGTM, but I prefer #104752

2023-05-24 10:10 UTC, closed without merging