gh-104690 Disallow thread creation and fork at interpreter finalization
python/cpython pull request #104826
Opened 2023-05-24 00:25 UTC by chgnrdv

Fixes #104690

In the following functions, check if interpreter is finalizing and in this case raise `RuntimeError` with appropriate message:
* `_thread.start_new_thread`
* `posix.fork`
* `posix.fork1`
* `posix.forkpty`
* `_posixsubprocess.fork_exec`

2023-05-26 04:23 UTC, gpshead requested changes

2023-05-26 04:23 UTC, gpshead commented on Lib/test/test_threading.py
> +        self.assertIn(b"can't fork at interpreter shutdown", err)
This test_fork_at_exit() test doesn't seem to make sense to be in test_threading anymore after this PR's primary change.  you added an equivalent without the misleading no longer true functionality to test_os anyways.

2023-05-26 04:23 UTC, gpshead commented on Misc/NEWS.d/next/Core and Builtins/2023-05-24-12-10-54.gh-issue-104690.HX3Jou.rst
> +Starting new threads and process creation through fork/vfork at interpreter exit is no longer supported, as it can lead to race condition between main Python thread freeing existing thread states and
Don't mention internal APIs like `_thread.start_new_thread` in the news entry, just say something like "while the Python threading internals try to allocate ..."

2023-05-26 04:23 UTC, gpshead commented on Modules/_posixsubprocess.c
> +                        "can't create child process at interpreter shutdown");
blocking all subprocess.Popen calls from working seems unnecessary. If anything add a `preexec_fn != Py_None &&` to this conditional as that is the only thing that could ever try to use the interpreter in the child process.

2023-05-26 09:36 UTC, chgnrdv commented
I have made the requested changes; please review again

2023-05-26 17:19 UTC, gpshead commented
FYI - if you want an example of real world code that was spawning threads from atexit (I'm not claiming that this was a _good idea_... just that it inadvertently happened): See the example given in #86813.

2023-05-26 17:26 UTC, gpshead approved these changes

2023-05-26 17:50 UTC, gpshead requested changes
I think the one thing this PR still needs is an Docs/library/atexit.rst documentation update noting that creating new threads or forking new processes from an atexit handler results in undefined behavior.  With a versionchanged:: 3.12 saying we now attempt to make such things raise a RuntimeError.

2023-05-26 19:01 UTC, chgnrdv commented
I have made the requested changes; please review again

2023-06-03 05:58 UTC, sunmy2019 approved these changes

2023-06-03 15:42 UTC, gpshead approved these changes

2023-06-04 04:06 UTC, merged

2023-06-04 04:06 UTC, miss-islington commented
Thanks @chgnrdv for the PR, and @gpshead for merging it 🌮🎉.. I'm working now to backport this PR to: 3.12.
🐍🍒⛏🤖

2023-06-04 04:06 UTC, miss-islington commented
Sorry @chgnrdv and @gpshead, I had trouble checking out the `3.12` backport branch.
                                Please retry by removing and re-adding the "needs backport to 3.12" label.
                                Alternatively, you can backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on the command line.
                                ```
                                cherry_picker ce558e69d4087dd3653207de78345fbb8a2c7835 3.12
                                ```

2023-06-04 04:07 UTC, miss-islington commented
Thanks @chgnrdv for the PR, and @gpshead for merging it 🌮🎉.. I'm working now to backport this PR to: 3.12.
🐍🍒⛏🤖

2023-09-07 02:33 UTC, vstinner commented
This change introduced a test_concurrent_futures regression: issue #109047. Well, right now I'm not sure about the root cause analysis.