gh-104924: Fix `read()able` in `http.client` log messages
python/cpython pull request #104926
Opened 2023-05-25 11:04 UTC by arhadthedev

https://github.com/search?q=repo%3Apython%2Fcpython%20read()able&type=code shows no other occurrence of this typo.

2023-05-25 11:18 UTC, gaogaotiantian requested changes
I think `sendIng` is an obvious typo. On line 1057, from some brief reading, it's not "sending" a readable, but "reading" from a readable(as indicated by the function name).

2023-05-25 11:18 UTC, gaogaotiantian commented on Lib/http/client.py
> +                print("sendIng a readable")
```suggestion
                print("sending a readable")
```

2023-05-25 11:18 UTC, gaogaotiantian commented on Lib/http/client.py
> +            print("sendIng a readable")
```suggestion
            print("reading a readable")
```

2023-05-25 11:20 UTC, gaogaotiantian approved these changes

2023-05-25 21:30 UTC, LyingDalai commented
I have looked for any related typo with “Ing the read()”. I know PyCharm can make funny replacements but I still haven’t found where this would come from.

2023-05-26 11:39 UTC, corona10 approved these changes
lgtm

2023-05-26 11:39 UTC, merged

2023-05-26 11:39 UTC, miss-islington commented
Thanks @arhadthedev for the PR, and @corona10 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11, 3.12.
🐍🍒⛏🤖