gh-105052:update timeit function's description
python/cpython pull request #105060
Opened 2023-05-29 13:56 UTC by Cherrymelon

Update  time unit description in `timeit` function and add note to timeit doc page
- issue: #105052

2023-05-29 16:29 UTC, terryjreedy requested changes
The PR could have waited for more discussion on the issue.  See [this comment](https://github.com/python/cpython/issues/105052#issuecomment-1567324058) for what I think the most important change for this issue should be, and where.

The Timer docstring has an obsolete and now wrong statement about the timer that should be deleted: `; the timer function is platform-dependent (see the module doc string)`

2023-05-29 16:29 UTC, terryjreedy commented on Lib/timeit.py
> +    return src.replace("\n", "\n" + " " * indent)
Revert.  See PEP 8, Other Recommendations
```suggestion
    return src.replace("\n", "\n" + " "*indent)
```

2023-05-29 16:29 UTC, terryjreedy commented on Lib/timeit.py
> +
Methods are single-spaced.  See PEP 8, Blank Lines
```suggestion
```

2023-05-29 16:29 UTC, terryjreedy commented on Doc/library/timeit.rst
> +      statement a number of times, measured in seconds as a float by default timer.
```suggestion
      statement a number of times.  The default timer returns seconds as a float.
```

2023-05-29 16:29 UTC, terryjreedy commented on Misc/NEWS.d/next/Documentation/2023-05-29-14-10-24.gh-issue-105052.MGFwbm.rst
> +timeit doc update
```suggestion
Update ``timeit`` doc to specify that time in seconds is just the default.
```

2023-05-29 18:28 UTC, Cherrymelon commented on Lib/timeit.py
> +
sry,I'm confused about the max blank number defination around top-level class and function.It shouldn't be 2 blank?If I changed to one blank,IDE tell me `PEP 8: E302 expected 2 blank lines, found 1`

2023-05-29 19:17 UTC, Cherrymelon commented on Lib/timeit.py
> +    return src.replace("\n", "\n" + " " * indent)
Pycharm default formatter add spaces ignore the priority of statements.Any good advice?

2023-05-29 23:42 UTC, terryjreedy commented on Lib/timeit.py
> +
Ignore.

2023-08-27 03:28 UTC, terryjreedy commented on Lib/timeit.py
> +        timer.Thus,time unit could be changed if giving other timer.  The
```suggestion
        a number of times, as a float measured in seconds if using the default
        timer. Thus, the time unit could be changed if using other timer.  The
```

2023-08-27 03:31 UTC, terryjreedy approved these changes

2023-08-27 03:57 UTC, terryjreedy commented on Lib/timeit.py
> +        timer. Thus, the time unit could be changed if using other timer.  The
```suggestion
        a number of times, as float seconds if using the default timer.   The
```

2023-08-27 07:22 UTC, merged

2023-08-27 07:22 UTC, miss-islington commented
Thanks @Cherrymelon for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11, 3.12.
🐍🍒⛏🤖