gh-105288: wake up exit waiters after sub-process exits
python/cpython pull request #105289
Opened 2023-06-04 18:50 UTC by keuin

2023-06-05 17:24 UTC, gvanrossum commented
@kumaraditya303 Once you are convinced of the validity of the issue (which I expect you will be), will you review ad merge this PR? I was on vacation for 10 days and am way behind.

2023-06-08 06:23 UTC, kumaraditya303 commented
As evident by the failing CI this is wrong.

2023-06-08 15:10 UTC, keuin commented
I will fix my test in these days. Sorry because I'm not familiar with the test framework and testing a frozen event loop is much harder than usual.

2023-06-08 15:34 UTC, kumaraditya303 requested changes
See my explanation on the issue

2023-08-18 10:29 UTC, Hels15 commented
What's going on here?

2024-10-22 08:02 UTC, graingert commented on Lib/test/test_asyncio/test_subprocess.py
> +                self.loop.run_until_complete(main())
the problem is in asyncio.run - so this doesn't actually test the issue

2024-10-23 05:05 UTC, keuin commented
I think this issue is a duplicate of others. The misuse of argument shows some deep resource leak, but is hard to find the root cause.
I'm glad to see others want to fix the similar issue. I want to wait to see if it can fix this too.

2024-10-23 05:05 UTC, closed without merging