gh-105310: add decorator to skip rerunning tests
python/cpython pull request #105311
Opened 2023-06-05 12:26 UTC by sunmy2019

2023-06-05 12:32 UTC, erlend-aasland requested changes

2023-06-05 12:32 UTC, erlend-aasland commented on Lib/test/support/__init__.py
> +def skip_rerun(reason: str):
See [this Discourse topic](https://discuss.python.org/t/type-annotations-in-the-stdlib/21487?u=erlendaasland) for the discussion regarding adding typing annotations to the stdlib. Since `Lib/test` is part of the stdlib, please do not add type annotations for now.

2023-06-05 12:33 UTC, sunmy2019 commented on Lib/test/support/__init__.py
> +def skip_rerun(reason: str):
```suggestion
def skip_rerun(reason):
```

2023-06-05 12:33 UTC, sunmy2019 commented on Lib/test/support/__init__.py
> +    def decorator(test_case: type[unittest.TestCase]):
```suggestion
    def decorator(test_case):
```

2023-06-05 12:35 UTC, sunmy2019 commented
I have made the requested changes; please review again

I think we need news for this one, right?

2023-06-05 12:37 UTC, erlend-aasland commented
> I think we need news for this one, right?

Well, test changes rarely get their own NEWS items. Personally, I would not bother with it. Related: also note that a lot of the `test.support` methods intentionally lack docs.

2023-06-20 05:52 UTC, sunmy2019 commented
Closed. See https://github.com/python/cpython/pull/104796#discussion_r1234484344

2023-06-20 05:52 UTC, closed without merging