gh-105522: Simplify `test_enum` by removing extra exception handling
python/cpython pull request #105523
Opened 2023-06-08 19:01 UTC by sobolevn

This is simlier now! 🎉

2023-06-12 10:54 UTC, sobolevn commented
Here's how a potential exception looks like:

```
======================================================================
ERROR: test_pickle_enum (test.test_enum.TestSpecial.test_pickle_enum)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 1458, in test_pickle_enum
    raise Stooges
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 65, in <module>
    class Stooges(Enum):
  File "/Users/sobolev/Desktop/cpython/Lib/enum.py", line 494, in __prepare__
    raise RuntimeError('Exc', cls)
RuntimeError: ('Exc', 'Stooges')
```

And here's how it looks if there are multiple exceptions:

```
======================================================================
ERROR: test_floatenum_fromhex (test.test_enum.TestSpecial.test_floatenum_fromhex)
----------------------------------------------------------------------
  + Exception Group Traceback (most recent call last):
  |   File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 55, in inner
  |     raise ExceptionGroup('Enum Exceptions', excs)
  | ExceptionGroup: Enum Exceptions (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 81, in <module>
    |     class FloatStooges(float, Enum):
    |   File "/Users/sobolev/Desktop/cpython/Lib/enum.py", line 494, in __prepare__
    |     raise RuntimeError('Exc', cls)
    | RuntimeError: ('Exc', 'FloatStooges')
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/Users/sobolev/Desktop/cpython/Lib/test/test_enum.py", line 108, in <module>
    |     class IntFlagStooges(IntFlag):
    |   File "/Users/sobolev/Desktop/cpython/Lib/enum.py", line 494, in __prepare__
    |     raise RuntimeError('Exc', cls)
    | RuntimeError: ('Exc', 'IntFlagStooges')
    +------------------------------------
```

2023-08-16 07:41 UTC, sobolevn commented
@ethanfurman friendly ping (x2) 😄

2023-08-16 16:44 UTC, ethanfurman requested changes
One minor change and it looks good!

2023-08-16 16:44 UTC, ethanfurman commented on Lib/test/test_enum.py
> +def reraise_enum_exceptions(*enum_types_or_exceptions):
```suggestion
def reraise_if_not_enum(*enum_types_or_exceptions):
```

2023-08-16 18:18 UTC, sobolevn commented on Lib/test/test_enum.py
> +def reraise_enum_exceptions(*enum_types_or_exceptions):
Done! 👍

2023-08-16 18:18 UTC, sobolevn commented
I have made the requested changes; please review again

2023-08-16 19:05 UTC, ethanfurman approved these changes

2023-08-16 19:17 UTC, merged