Fix the french used in the email documentation
python/cpython pull request #106279
Opened 2023-06-30 11:44 UTC by faltad

The french used in one of the example was either machine translated a while ago or written by someone who does not speak french. Fixed it by using grammatically correct french.

I could also change it to english if this is the preferred approach.

Since it is a trivial doc change, I did not make an issue.

2023-06-30 13:46 UTC, bitdancer requested changes

2023-06-30 13:46 UTC, bitdancer commented on Doc/includes/email-alternative.py
> +msg['Subject'] = "Pourquoi pas des asperges pour ce midi?"
The problem with this particular fix is that part of the point of the test is to have a non-ascii character in it, and this fixed version does not.  Choose a whole new sentence if you want to, but it must contain a non-ascii character.

2023-06-30 13:46 UTC, bitdancer commented on Doc/library/email.examples.rst
> +    Subject: Pourquoi pas des asperges pour ce midi?
Same here

2023-06-30 13:47 UTC, bitdancer commented
Oh, nevermind, I missed the fact that this was the docs.  It looks fine.

2023-06-30 13:50 UTC, bitdancer approved these changes

2023-07-02 14:26 UTC, JulienPalard commented on Doc/includes/email-alternative.py
> +msg['Subject'] = "Pourquoi pas des asperges pour ce midi?"
```suggestion
msg['Subject'] = "Pourquoi pas des asperges pour ce mid i?"
```

French typography have spaces before "?", "!", ":", ...

2023-07-02 14:27 UTC, JulienPalard commented on Doc/library/email.examples.rst
> +    Subject: Pourquoi pas des asperges pour ce midi?
```suggestion
    Subject: Pourquoi pas des asperges pour ce midi ?
```

2023-07-16 17:14 UTC, merged

2023-07-16 17:14 UTC, JulienPalard commented
Thanks!! :))

2023-07-16 20:34 UTC, deronnax commented
I wish we stuck closer to the original French. It looked deliciously outmoded, typically an American trying to write French from what he had learned in school. It definitively had some charm. But thanks anyway

2023-07-16 20:41 UTC, deronnax commented on Doc/includes/email-alternative.py
> -msg['Subject'] = "Ayons asperges pour le déjeuner"
pretty correct, it would have been:
*Ayons des asperges pour le déjeuner*

2023-07-16 20:41 UTC, deronnax commented on Doc/includes/email-alternative.py
> -Cela ressemble à un excellent recipie[1] déjeuner.
A bit more wrong. The correct form would have been:
*Cela ressemble à une excellente recette pour le déjeuner*