Save a reference to the task, to avoid it disappearing
python/cpython pull request #106203
Opened 2023-06-28 12:09 UTC by anio

> Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done.
>
> [python docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task)

2023-06-29 11:38 UTC, erlend-aasland commented
@arhadthedev: the bar for _skip issue_ is very high; all code changes need an issue and a rationale.

2023-06-29 11:40 UTC, erlend-aasland commented
@anio, please sign the CLA (https://github.com/python/cpython/pull/106203#issuecomment-1611286682)

2023-06-29 12:03 UTC, anio commented
@erlend-aasland Thanks! I did.

2023-07-27 07:10 UTC, kumaraditya303 requested changes
What issue does this solve?

2023-08-10 06:25 UTC, kumaraditya303 commented
Closing because of no response.

2023-08-10 06:25 UTC, closed without merging