gh-106490: Fixed binomialvariate BG algorithm to use `>=` comparison
python/cpython pull request #106491
Opened 2023-07-06 20:02 UTC by trag1c

Issue: #106490

2023-07-07 03:15 UTC, sunmy2019 approved these changes

2023-07-07 03:38 UTC, sunmy2019 requested changes

2023-07-07 03:38 UTC, sunmy2019 commented on Misc/NEWS.d/next/Library/2023-07-06-20-09-15.gh-issue-106490.HC-ZvO.rst
> +Fixed ``random.binomialvariate`` BG algorithm inaccuracy
How about adding more explanations for what part is wrong?

2023-07-07 03:38 UTC, sunmy2019 commented on Lib/test/test_random.py
> +        self.assertEqual(set(c), {0, 1, 2, 3})
This is definitely wrong. `B(n, p)` should has value `{0, 1, 2, ..., n}`

2023-07-07 03:43 UTC, sunmy2019 commented on Lib/test/test_random.py
> +        self.assertEqual(set(c), {0, 1, 2, 3})
Binomial distrubution table for `B(4,p)`

p | .01 | .05 | .10 | .15 | .20 | .25 | .30 | .35 | .40 | .45 | .50 | .55 | .60 | .65 | .70 | .75 | .80 | .85 | .90 | .95
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
r | 0 | .961 | .815 | .656 | .522 | .410 | .316 | .240 | .179 | .130 | .092 | .062 | .041 | .026 | .015 | .008 | .004 | .002 | .001 | .000 | .000
  | 1 | .039 | .171 | .292 | .368 | .410 | .422 | .412 | .384 | .346 | .300 | .250 | .200 | .154 | .112 | .076 | .047 | .026 | .011 | .004 | .000
  | 2 | .001 | .014 | .049 | .098 | .154 | .211 | .265 | .311 | .346 | .368 | .375 | .368 | .346 | .311 | .265 | .211 | .154 | .098 | .049 | .014
  | 3 | .000 | .000 | .004 | .011 | .026 | .047 | .076 | .112 | .154 | .200 | .250 | .300 | .346 | .384 | .412 | .422 | .410 | .368 | .292 | .171
  | 4 | .000 | .000 | .000 | .001 | .002 | .004 | .008 | .015 | .026 | .041 | .062 | .092 | .130 | .179 | .240 | .316 | .410 | .522 | .656 | .815

Taken from https://www.thoughtco.com/binomial-table-n-2-through-6-3126258

2023-07-07 08:37 UTC, trag1c commented
Closed because of https://github.com/python/cpython/issues/106490#issuecomment-1624654035

2023-07-07 08:37 UTC, closed without merging

2023-07-10 20:11 UTC, rhettinger commented
Also note that this PR fails simple statistical tests such as:

```
def test(n, p, times = 10 ** 6):
    data = [binomialvariate(n, p) for i in range(times)]
    q = 1.0 - p
    print(f'{n=}  {p=}')
    print(mean(data), n*p, 'mean')
    print(stdev(data), sqrt(n*p*q), 'stdev')
    print(mode(data), floor((n+1) * p), ceil((n+1) * p) - 1, 'mode')
```

With the suggested change, the results are wildly off the expected values:

```
n=2  p=0.4
0.400411 0.8 mean
0.48998190901427285 0.6928203230275509 stdev
0 1 1 mode

n=2  p=0.6
1.601059 1.2 mean
0.4896808331008253 0.6928203230275509 stdev
2 1 1 mode

n=5  p=0.75
4.000037 3.75 mean
0.8666797273299692 0.9682458365518543 stdev
4 4 4 mode

n=12  p=0.25
2.750983 3.0 mean
1.4347855562140959 1.5 stdev
3 3 3 mode

n=18  p=0.49
8.327508 8.82 mean
2.059205854271192 2.1208960370560366 stdev
8 9 9 mode

n=18  p=0.51
9.67141 9.18 mean
2.062238799152238 2.120896037056036 stdev
10 9 9 mode
```