GH-104909: Split `LOAD_ATTR_INSTANCE_VALUE` into micro-ops
python/cpython pull request #106678
Opened 2023-07-12 10:36 UTC by markshannon

2023-07-12 14:13 UTC, markshannon commented
I've change the code generator to allow micro-ops to be shared between instructions. 
@gvanrossum Why was that prohibited?

2023-07-12 16:34 UTC, iritkatriel commented on Python/bytecodes.c
> +            _SKIP_CACHE + _TYPE_CHECK + _CHECK_MANAGED_OBJECT_HAS_VALUES + _LOAD_ATTR_INSTANCE_VALUE;
This should be rewritten in the style you ended up merging in the previous PR.

2023-07-13 10:09 UTC, iritkatriel requested changes
There are merge conflicts, and my comment above.

2023-07-13 14:55 UTC, iritkatriel approved these changes

2023-07-13 15:00 UTC, gvanrossum approved these changes

2023-07-13 15:36 UTC, merged