gh-106886: Ensure f_locals returns a Python object
python/cpython pull request #106885
Opened 2023-07-19 08:51 UTC by P403n1x87

According to the comments in [pycore_frame.h](https://github.com/python/cpython/blob/e6f96cf9c62e38514e8f5465a1c43f85d861adb2/Include/internal/pycore_frame.h#L55C30-L55C30), the field `f_locals` of `_PyInterpreterFrame` may be `NULL`. This would result in `frame_getframe`, which is used to implement the `f_locals` attribute on a Python `frame` object, to return `NULL` instead of `Py_None`.

* Issue: gh-106886

2023-07-19 08:57 UTC, P403n1x87 commented
Apologies for the poor quality around the workflow of opening this PR. I created this PR directly from the in-browser VS Code editor and I didn't quite know what to expect. I'll try to improve by first of all creating an issue.

2023-07-19 10:12 UTC, sunmy2019 requested changes

2023-07-19 10:12 UTC, sunmy2019 commented on Objects/frameobject.c
> +        Py_RETURN_NONE;
the return value is expected to be a `PyDictObject*` or `NULL`

`None` is unacceptable here.

2023-07-19 10:12 UTC, sunmy2019 commented on Objects/frameobject.c
>      return Py_NewRef(locals);
```suggestion
    return Py_XNewRef(locals);
```

2023-07-19 10:19 UTC, sunmy2019 commented on Objects/frameobject.c
> +        Py_RETURN_NONE;
It should not be called with `f_locals == NULL`, and it's an invariant here.

2023-07-19 10:31 UTC, P403n1x87 commented on Objects/frameobject.c
> +        Py_RETURN_NONE;
Agreed. Should this be an `assert` then? I believe `locals == NULL` would reflect an invalid internal state. What is the convention for handling this sort of internal issues?

2023-07-20 06:22 UTC, sunmy2019 commented on Objects/frameobject.c
> +        Py_RETURN_NONE;
I think `assert` works here.

2023-10-12 14:48 UTC, markshannon commented
@P403n1x87 Did you get to the root cause of the issue?
Can we close this PR?

2023-10-12 17:14 UTC, P403n1x87 commented
Ah this particular instance was likely due to some missing opcodes in our instrumentation. The issues was caused by a tracer but only detectable by the profiler stack sampler. So this can be closed, even though it is still unclear if the bytecode fix from our side fixes all the segfaults that have been reported to us

2023-10-14 11:55 UTC, closed without merging