Add 2 missing commas
python/cpython pull request #10698
Opened 2018-11-25 13:08 UTC by PedanticHacker

Fixed the typing docs by adding 2 missing commas.

2018-11-25 13:08 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-11-25 13:14 UTC, PedanticHacker commented
I've signed the PSF contributor agreement (CLA), but it indicates here that I have not done that. Strange.

2018-11-25 16:29 UTC, gvanrossum commented on Doc/library/typing.rst
> +Note that these checks are enforced only by the static type checker. At runtime,
I think this sentence reads fine without the comma.

2018-11-25 17:02 UTC, PedanticHacker commented
This is English orthography, nothing personal. 😉

2018-12-23 04:09 UTC, rhettinger requested changes
I think only the first of these two is correct.

2018-12-23 12:14 UTC, PedanticHacker commented on Doc/library/typing.rst
> +Note that these checks are enforced only by the static type checker. At runtime,
This particular sentence needs a comma. But the second change where I added a comma was incorrect.

2018-12-23 12:36 UTC, PedanticHacker commented
I have made the requested changes; please review again.

2018-12-23 16:38 UTC, rhettinger approved these changes

2018-12-23 16:45 UTC, merged