gh-71261: Add paragraph on shadowing submodules with star imports
python/cpython pull request #107004
Opened 2023-07-22 11:00 UTC by wulmer

This PR extends the tutorial on modules and packages by adding a paragraph on the `from abc import *` problem in case of duplicate names for submodules and locally defined objects (e.g. functions).

It intends to solve #71261 by providing an example of how a locally defined function breaks the import of submodules.

2023-07-22 13:16 UTC, evildmp requested changes

2023-07-22 13:16 UTC, evildmp commented on Doc/tutorial/modules.rst
> +        return msg[::-1]    #     in case of an 'from sound.effects import *'
I suggest: "in the case of a ..."

2023-07-22 13:21 UTC, wulmer commented on Doc/tutorial/modules.rst
> +        return msg[::-1]    #     in case of an 'from sound.effects import *'
Thanks. Done.

2023-07-22 13:24 UTC, evildmp approved these changes

2023-07-23 09:00 UTC, merged

2023-07-23 09:00 UTC, miss-islington commented
Thanks @wulmer for the PR, and @hugovk for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2023-07-23 09:00 UTC, miss-islington commented
Thanks @wulmer for the PR, and @hugovk for merging it 🌮🎉.. I'm working now to backport this PR to: 3.12.
🐍🍒⛏🤖