gh-107015: Remove async_hacks from the tokenizer
python/cpython pull request #107018
Opened 2023-07-22 12:36 UTC by pablogsal

2023-07-22 21:45 UTC, Gobot1234 commented on Lib/keyword.py
>      'await',
Why do these appear twice?

2023-07-25 12:15 UTC, lysnikolaou approved these changes
Looks good! Great improvement! 🚀

2023-07-25 12:18 UTC, lysnikolaou requested changes
I didn't see all the test failures. Most of them are about grammar errors or tests about using `async`/`await` as soft keywords. @pablogsal Would you like me to take a deeper look into them?

2023-07-25 15:40 UTC, pablogsal commented
@lysnikolaou I have updated the tests in a separate commit. Please, review again

2023-07-25 15:42 UTC, lysnikolaou approved these changes

2023-07-25 15:43 UTC, lysnikolaou commented
Changes to the test look good. Let's wait for all the tests to pass and merge! Thanks!

2023-07-25 16:25 UTC, AlexWaygood commented on Doc/library/token.rst
The docs build is failing -- looks like you'll need to change all the references to `AWAIT` and `ASYNC` in this file from

```
:data:`ASYNC`
```

to

```
:data:`!ASYNC`
```

Since you've removed `.. data:: ASYNC` and `.. data:: AWAIT` from `Doc/library/token-list.inc`

2023-07-26 15:33 UTC, pablogsal commented on Doc/library/token.rst
Thanks @AlexWaygood ❤️

2023-07-26 15:34 UTC, merged