gh-76913: Add "merge extras" feature to LoggerAdapter
python/cpython pull request #107292
Opened 2023-07-26 12:31 UTC by romuald

By default, LoggerAdapter objects ignores all `extra=` parameter used in the individual log methods, which may be confusing for some users.

This commit is aimed at adding an option in the LoggerAdapter class to allow instances / subclasses to merge both the adapter and individual log call extra into a single entry

The default behavior is not changed

For example:

```
log = LoggerAdapter(..., extra={"component": "XYZ"})
log.info("return %r" % ret, extra={"duration": elapsed})
```

2023-07-26 12:33 UTC, romuald commented
I'm aware that the documentation / news were not updated. Waiting for some approval on the proposal first

2023-07-29 17:19 UTC, vsajip requested changes
Please see suggested changes, and add documentation and NEWS changes. Thanks!

2023-07-29 17:19 UTC, vsajip commented on Lib/logging/__init__.py
> +    def __init__(self, logger, extra=None, merge_extras=None):
I'd use `merge_extra=False` here - `merge_extra` to align with `extra`, and `False` as a default value as there's no need to consider the `None` case.

2023-07-29 17:19 UTC, vsajip commented on Lib/logging/__init__.py
> +        maps when logging, the indivicual call extra taking precedence
Typo `indivicual` -> `individual` and maybe quote 'extra' in the comment as in the previous paragraph.

2023-07-29 17:19 UTC, vsajip commented on Lib/logging/__init__.py
> +        if merge_extras is not None:
Don't need the condition, can always set `self.merge_extra = merge_extra`, right?

2023-07-30 13:45 UTC, romuald commented
I have made the requested changes; please review again

2023-07-30 13:46 UTC, romuald commented
(I did rewrite my commit I'm not sure what's the usual way is)

2023-07-30 22:02 UTC, vsajip commented
> (I did rewrite my commit I'm not sure what's the usual way is)

I don't see any sign of the changes I suggested. The normal way to do it is to make the changes and push again to your fork/branch. This will generate a new diff, but as you can see the current diff looks just like the previous diff. Check the [Python Developer's Guide ](https://devguide.python.org/getting-started/git-boot-camp/#creating-a-pull-request) if you need more help on creating and iterating pull requests.

2023-07-30 22:05 UTC, romuald commented
> I don't see any sign of the changes I suggested. The normal way to do it is to make the changes and push again to your fork/branch. This will generate a new diff, but as you can see the current diff looks just like the previous diff. Check the [Python Developer's Guide ](https://devguide.python.org/getting-started/git-boot-camp/#creating-a-pull-request) if you need more help on creating and iterating pull requests.

I've made the code changes (visible in the PR for me) but missed the part about the NEWS and doc. I'll work on this next

2023-07-31 14:34 UTC, vsajip commented
> (visible in the PR for me)

Well, it's not visible to me. See this screenshot:

![ss17](https://github.com/python/cpython/assets/130553/250c6773-a90e-4238-b5a2-347e22014322)

Note that it's showing "Changes from all commits" but only a commit count of 1, where I would have expected at least two commits (the initial commit, and one or more for your changes after my review). Also note that I made a review comment suggesting `merge_extras` be renamed to `merge_extra`, which appears not to be reflected in the screenshot.

2023-07-31 14:38 UTC, romuald commented
@vsajip thanks for the clarification. I've used a push -f to squash all changes, I'm guessing this is why it's only showing as one change

I'll try to recover this if I can access the previous state

I also missed the name change by reading too fast

2023-07-31 15:19 UTC, vsajip commented
Don't squash on push. We generally squash on merge, and reviewers need to see the whole commit history (initial, and after every review or noticed change)when reviewing.

2023-08-14 15:56 UTC, romuald commented
I have made the requested changes; please review again

2023-08-15 06:13 UTC, vsajip approved these changes

2023-08-15 06:39 UTC, vsajip commented
A seemingly unrelated test is failing, so I'll close and reopen this PR to see if that resolves it.

2023-08-15 07:23 UTC, merged