Add some missing errnos
python/cpython pull request #107486
Opened 2023-07-31 07:34 UTC by qqwqqw689

2023-07-31 07:35 UTC, qqwqqw689 commented
#107453

2023-07-31 16:20 UTC, AA-Turner commented on Doc/library/errno.rst
> +   operation canceled
```suggestion
   Operation canceled

   .. versionadded:: 3.2
```

2023-07-31 16:20 UTC, AA-Turner commented on Doc/library/errno.rst
> +   owner dead
```suggestion
   Owner died

   .. versionadded:: 3.2
```

2023-07-31 16:20 UTC, AA-Turner commented on Doc/library/errno.rst
> +   state not recoverable
```suggestion
   State not recoverable

   .. versionadded:: 3.2
```

2023-07-31 16:20 UTC, AA-Turner commented on Doc/library/errno.rst
> +   not supported
```suggestion
   Operation not supported

   .. versionadded:: 3.2
```

2023-08-01 03:37 UTC, qqwqqw689 commented
@AA-Turner I think sorting is dispensable because we can use "Ctrl+f" .😉

2023-08-23 17:39 UTC, hugovk requested changes
Please put the constants in order. Then people can either ctrl+F, or see things where they expect when they don't.

2023-08-23 17:50 UTC, AA-Turner commented
@hugovk -- mea culpa! I should have looked at linux's ordering before leaving a comment, it transpires only one constant was out-of-order (``ENOTSUP``, which is seemingly duplicates ``EOPNOTSUPP`` ([see errno(3)](https://man7.org/linux/man-pages/man3/errno.3.html)). As it was trivial, I've pushed a commit to fix, and reverted another inadvertent commit on the branch.

A

2023-08-24 18:00 UTC, AA-Turner commented
> But it seems that linux doesn't define ENOTSUP.

From the man page linked:

<dl>
<dt>EOPNOTSUPP</dt>
<dd>Operation not supported on socket (POSIX.1-2001).<br>
(ENOTSUP and EOPNOTSUPP have the same value on Linux, but
according to POSIX.1 these error values should be
distinct.)</dd>
</dl>

A

2023-08-25 03:40 UTC, qqwqqw689 commented
Yes, I found it from https://lists.gnu.org/archive/html/bug-glibc/2002-08/msg00017.html

        [ENOTSUP] "Not supported".  A function returns this error when
        certain parameter values are valid, but the functionality they request
        is not available. This can mean that the function does not implement
        a particular command or option value or flag bit at all.  For functions
        that operate on some object given in a parameter, such as a file
        descriptor or a port, it might instead mean that only that specific
        object (file descriptor, port, etc.) is unable to support the other
        parameters given; different file descriptors might support different
        ranges of parameter values.

        If the entire function is not available at all in the implementation,
        it returns ENOSYS instead.

        [EOPNOTSUPP] "Operation not supported". The operation you requested is
        not supported.  Some socket functions don't make sense for all types of
        sockets, and others may not be implemented for all communications
        protocols.  In the GNU system, this error can happen for many calls when
        the object does not support the particular operation; it is a generic
        indication that the server knows nothing to do for that call.

2023-08-27 05:19 UTC, hugovk approved these changes

2023-08-27 05:19 UTC, merged

2023-08-27 05:19 UTC, miss-islington commented
Thanks @qqwqqw689 for the PR, and @hugovk for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11, 3.12.
🐍🍒⛏🤖