GH-107812: extend `socket`'s netlink support to FreeBSD
python/cpython pull request #107813
Opened 2023-08-09 15:29 UTC by igalic

On FreeBSD, `netlink.h` lives under the `netlink` directory.
Extend the `AC_CHECK_HEADERS` to look there as well.

2023-08-09 15:54 UTC, corona10 requested changes
I think that you have to declare AF_NETLINK something like this way, no?

https://github.com/python/cpython/blob/0a7f48b9a8d54809f1e9272337aefe2444158e64/Modules/socketmodule.h#L98-L105

2023-08-09 16:34 UTC, igalic commented
Thanks, i missed that bit.
will try to get it fixed up today.

2023-08-09 18:17 UTC, igalic commented
I have made the requested changes; please review again!

2023-08-09 21:56 UTC, cjp256 reviewed
awesome, thanks @igalic!

2023-08-10 00:46 UTC, corona10 approved these changes
lgtm

2023-08-10 00:47 UTC, merged