gh-107607: Correct encoding name in docs
python/cpython pull request #107858
Opened 2023-08-11 08:30 UTC by sierrasevn

According to the Python codecs docs[1], Python calls UTF-8 with BOM as utf-8-sig. Therefore, using "UTF-8-Sig" seems more appropriate.

> (...) To increase the reliability with which a UTF-8 encoding can be detected, Microsoft invented a variant of UTF-8 (that Python calls "utf-8-sig")
> (...) On encoding the utf-8-sig codec will write 0xef, 0xbb, 0xbf as the first three bytes to the file.

2023-08-11 14:22 UTC, ambv commented
Closing and re-opening to retrigger CLA checks. Sorry for the noise.

2023-08-11 18:41 UTC, terryjreedy commented on Doc/reference/lexical_analysis.rst
>  among others, by Microsoft's :program:`notepad`).
```suggestion
among others, by Microsoft's :program:`Notepad`).
```

2023-08-11 18:42 UTC, terryjreedy commented on Doc/reference/lexical_analysis.rst
> +(``b'\xef\xbb\xbf'``), the declared file encoding is UTF-8-Sig (this is supported,
```suggestion
(``b'\xef\xbb\xbf'``), the declared file encoding is UTF-8 with BOM (this is supported,
```

2023-08-11 18:43 UTC, terryjreedy requested changes
This is not yet ready to merge.  I am working on a comment on the issue.

2023-08-12 14:37 UTC, sierrasevn commented
If we aren't limited to choosing just one of the terms between "UTF-8-Sig" and "UTF_8_Sig", I also agree to use "UTF-8 with BOM" which is already used in Windows, since this page is for Windows users.

2023-08-12 15:59 UTC, terryjreedy commented
As explained in https://github.com/python/cpython/issues/107607#issuecomment-1675967835, I now think that the entire sentence in question should be replaced with "If the implicit or explicit encoding of a file is UTF-8, a UTF-8 byte-order mark (b'\xef\xbb\xbf') is ignored rather than being a syntax error." or something very close to this.

2024-03-18 05:13 UTC, terryjreedy approved these changes

2024-03-19 15:51 UTC, merged