gh-107805: Fix signatures of module-level generated functions in `turtle`
python/cpython pull request #107807
Opened 2023-08-09 10:52 UTC by sobolevn

Now we are using `inspect.signature` which works correct for all possible parameter types.
There are no `/` params to test it, but it uses the same branch as regular pos-or-keyword params, so it should be fine.

Related https://github.com/python/cpython/pull/103974

2023-08-09 10:54 UTC, sobolevn commented
I think that this can go into rc2, because it fixes a bug which makes `turtle.teleport` unusable.

2023-08-10 06:30 UTC, gpshead requested changes
likely good, but i'll take a closer look tomorrow. one suggestion added.

2023-08-10 06:30 UTC, gpshead commented on Lib/turtle.py
> +        if kind == inspect.Parameter.VAR_POSITIONAL:
These could be 'elif`.  Or if you want to have fun with modern syntax, this series of comparisons is an opportunity for a match-case statement from https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching.

2023-08-11 06:04 UTC, serhiy-storchaka approved these changes

2023-08-18 06:35 UTC, gpshead commented on Lib/test/test_turtle.py
> +        for name in turtle.__all__:
The purpose of this test is only to verify known signatures, correct?

In that case, looping over `known_signatures.items()` rather than `turtle.__all__` makes more sense.  Otherwise a typo in a known_signatures name key would go silently unnoticed and we're otherwise creating subtests for all names in turtle even though most of them don't test anything.

2023-08-18 07:30 UTC, serhiy-storchaka requested changes
Well, I think that it would be nice to add also tests for the original issue:

* Call `teleport()` without arguments.
* Call `teleport()` with three positional arguments (it should fail).

2023-08-21 15:03 UTC, sobolevn commented
I've addressed @gpshead comments about the test case, but I don't think that I can actually test these functions:
1. Nothing similar is tested in `test_turtle`, it simply does not have any `Turtle` class tests at all
2. I don't know anything about `tkinter`
3. I don't really think that we should add test foundation for it in this specific PR
4. `inspect` works with real python function signature, so it is at least something

If anyone wants to contribute some `tkinter`-based tests for `Turtle` class, I would be happy to include `teleport` test there 👍

2023-08-27 13:07 UTC, serhiy-storchaka approved these changes
Well, testing module-level turtle function is a non-trivial task.

2023-09-01 08:17 UTC, gpshead approved these changes
I manually tested that turtle.Turtle() appears to work and that Turtle.teleport works.

2023-09-01 08:18 UTC, merged

2023-09-01 08:18 UTC, miss-islington commented
Thanks @sobolevn for the PR, and @gpshead for merging it 🌮🎉.. I'm working now to backport this PR to: 3.12.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!