bpo-25828: Fix PyCode_Optimize for handling exceptions
python/cpython pull request #1078
Opened 2017-04-11 08:08 UTC by lulouie

2017-04-11 20:47 UTC, serhiy-storchaka requested changes

2017-04-11 20:47 UTC, serhiy-storchaka commented on Python/peephole.c
> +        if (PyErr_Occurred())
Calling `PyErr_Occurred()` on every instruction can significantly slow down compilation. It should be called only after executing operations that can raise an exception.

2017-04-12 02:44 UTC, rhettinger commented on Python/peephole.c
> +        if (PyErr_Occurred())
I think this is a waste and isn't solving a problem that any has in the real world.

2018-02-21 01:51 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2018-03-26 14:11 UTC, serhiy-storchaka commented
In don't see how an exception can be set here in master.

But maybe this check is still needed in 3.6.

2018-03-26 14:11 UTC, closed without merging