bpo-30031: Improve queens demo
python/cpython pull request #1084
Opened 2017-04-11 13:21 UTC by PavloKapyshin

* made it use argparse
* made it use singular form of “solutions” if needed
* added empty lines according to PEP 8

2017-04-11 13:21 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-04-17 16:01 UTC, PavloKapyshin commented
Re-run the CLA check, please.

2017-04-17 16:34 UTC, louisom requested changes
Some small suggest, others LGTM.

2017-04-17 16:34 UTC, lulouie commented on Tools/demo/queens.py
> +        "side_size", default=N, type=int, nargs="?",
To make string quote consistency, using `'` will better than `"`

2017-04-17 16:34 UTC, lulouie commented on Tools/demo/queens.py
> +        "-n", "--silent", default=SILENT, action="store_true",
Is not intuitive to set `silent` to `-n`, I think `-s` is better than `-n`.

2017-04-17 16:34 UTC, lulouie commented on Tools/demo/queens.py
> +        "side_size", default=N, type=int, nargs="?",
I'll prefer to set `-n` here, since is a `N` queen problem.

2017-04-18 21:26 UTC, Mariatta commented
Closing this PR since the issue was rejected in the bug tracker.

2017-04-18 21:26 UTC, closed without merging