gh-42765 timeit.Timer Documentation Update
python/cpython pull request #108744
Opened 2023-09-01 02:50 UTC by richardhob

Update the `timeit` documentation based on discussion in issue #42765.          
                                                                                
Resolve Issue #42765                                                            
                                                                                
This issue discusses the documentation for the `timeit.Timer` class, as well as possible improvements. `elibendersky` provided a patch to update the  documentation, and `rurpy` improved on this in a post. This merge request  implements `rurpy`'s version of the `timeit.Timer` class documentation with some light edits.                                                                    
                                                                                
The goal of this documentation change is to better explain how to use `timeit.Timer`, what the input arguments are, and how the args are use to actually time the execution of the provided snippet.

2024-01-23 20:14 UTC, erlend-aasland commented
@richardhob, can you please split this up: create a PR with the low-hanging fruit first, and then, if possible, create one PR for rewording the class docs, and one for rewording the method docs.

Doc PRs that change multiple things at once are hard to review, and rarely get attention.

2025-09-23 18:13 UTC, StanFromIreland requested changes
Please remove unrelated changes and see Erlend's comment.

2025-09-23 18:13 UTC, StanFromIreland commented on Misc/NEWS.d/next/Library/2023-08-21-18-36-09.gh-issue-52769.PoTaac.rst
This is unrelated?

2025-09-23 18:13 UTC, StanFromIreland commented on Doc/library/timeit.rst
> -         collection` during the timing.  The advantage of this approach is that
Double spaces are fine, please don't do this.

2025-09-24 15:10 UTC, closed without merging

2025-09-24 15:11 UTC, StanFromIreland commented
That force push was broken (maybe you merged 3.14 in?) and resulted in a large number of review requests, please create a new PR.