Fix a typo in Lib/turtle.py
python/cpython pull request #108958
Opened 2023-09-05 19:52 UTC by dnd-qodqks

The word "Photoimage" seems a typo. This PR corrects the typo to "PhotoImage".

2023-09-19 09:52 UTC, corona10 commented on Misc/NEWS.d/next/Library/2023-09-06-06-06-43.gh-issue-108958.vG6m73.rst
> +The word "Photoimage" seems a typo. This PR corrects the typo to "PhotoImage".
Please remove NEWS.d, it is not necessary for simple typo.

2023-09-19 09:53 UTC, corona10 requested changes, later dismissed
See: https://github.com/python/cpython/pull/108958#discussion_r1329867344

2023-09-21 03:46 UTC, AA-Turner approved these changes
Seems this is a Tk ref: https://docs.python.org/3/library/tkinter.html#images

A

2023-09-22 15:55 UTC, Son-Dongwoo commented on Misc/NEWS.d/next/Library/2023-09-06-06-06-43.gh-issue-108958.vG6m73.rst
> +The word "Photoimage" seems a typo. This PR corrects the typo to "PhotoImage".
Yes, thank you

2023-09-22 16:03 UTC, dnd-qodqks commented
@AA-Turner Thanks for the fix. :+1:

2023-09-25 12:36 UTC, corona10 approved these changes

2023-09-25 12:37 UTC, merged

2023-09-26 09:15 UTC, dnd-qodqks commented
Thank you for the merge!