bpo-35389: platform.libc_ver() uses os.confstr()
python/cpython pull request #10891
Opened 2018-12-04 11:47 UTC by vstinner

platform.libc_ver() now uses os.confstr('CS_GNU_LIBC_VERSION') if
available.

Quick benchmark on Fedora 29:

python3 -m perf command ./python -S -c 'import platform; platform.libc_ver()'
94.9 ms +- 4.3 ms -> 33.2 ms +- 1.4 ms: 2.86x faster (-65%)

2018-12-04 12:16 UTC, jwilk commented on Lib/platform.py
> +    except (AttributeError, ValueError):
On some systems (IIRC using musl libc) `os.confstr('CS_GNU_LIBC_VERSION')` fails with `OSError`, so that should be caught too.

2018-12-04 13:13 UTC, vstinner commented on Lib/platform.py
> +    except (AttributeError, ValueError):
Oh, I didn't know. It's now fixed.

2018-12-04 20:35 UTC, vstinner commented on Misc/NEWS.d/next/Library/2018-12-04-12-46-05.bpo-35389.CTZ9iA.rst
> +available.
Maybe I should add that it's only used if the executable parameter is not set.

2018-12-05 01:30 UTC, vstinner commented
Travis CI failed because of https://bugs.python.org/issue35411 :-( I just fixed this issue, this PR should be rebase (or merged with master).

2018-12-05 01:41 UTC, vstinner commented
I squashed my commits and rebased my PR.

2018-12-05 07:57 UTC, serhiy-storchaka requested changes
The test overrides the existing test `test_libc_ver`.

2018-12-05 10:44 UTC, vstinner commented
I have made the requested changes; please review again.

2018-12-05 10:44 UTC, vstinner commented
> The test overrides the existing test test_libc_ver.

Oops, I missed these tests! It's now fixed.

2018-12-05 13:02 UTC, serhiy-storchaka approved these changes

2018-12-05 13:04 UTC, merged