gh-109375: Fix pdb alias command
python/cpython pull request #109376
Opened 2023-09-13 14:45 UTC by buermarc

Issue: https://github.com/python/cpython/issues/109375

An unkown alias without a given command should not register a new alias.

2023-09-13 17:18 UTC, gaogaotiantian requested changes

2023-09-13 17:18 UTC, gaogaotiantian commented on Lib/pdb.py
> +            self.error("Unkown alias. To create an alias see 'help alias'")
```suggestion
        if len(args) == 1:
            if args[0] in self.aliases:
                self.message("%s = %s" % (args[0], self.aliases[args[0]]))
            else:
                self.error(f"Unknown alias '{args[0]}'")
```

2023-09-13 17:18 UTC, gaogaotiantian commented on Lib/pdb.py
> +            self.error("Unkown alias. To create an alias see 'help alias'")
I modified this a bit. You are right that we should send an error in this case, a couple of notes for the modification:
1. I think it's clearer to separate cases with the length of args - whether this is a read or a write, so I restructured it a bit.
2. Referring to `help` is not a common pattern in `pdb`. I removed it and put the argument in the error message.
3. Fixed a typo.

2023-09-13 17:18 UTC, gaogaotiantian commented on Lib/test/test_pdb.py
> +    *** Unkown alias. To create an alias see 'help alias'
```suggestion
    *** Unkown alias 'pi'.
```

2023-09-14 11:59 UTC, buermarc commented
I included the proposed changes. There was a failing test, because of an additional '.' (`Unkown alias 'pi'.`). I fixed it and squashed the two commits created by Github. Should i squash all commits or is it common to just squash when merging?

2023-09-14 18:44 UTC, gaogaotiantian commented
You don't need to squash any commits on your feature branch. In fact, that is discouraged as it might make code review harder (to track the previous changes). The maintainers will squash all your commits when merging.

The code looks good to me. @iritkatriel

2023-09-14 18:45 UTC, gaogaotiantian approved these changes

2023-09-14 19:04 UTC, iritkatriel commented
@gaogaotiantian Is this a bugfix (should it be backported)?

2023-09-14 19:10 UTC, iritkatriel approved these changes

2023-09-14 19:12 UTC, iritkatriel commented on Misc/NEWS.d/next/Library/2023-09-13-17-22-44.gh-issue-109375.ijJHZ9.rst
> +The pdb alias builtin now prevents registering aliases without a command.
```suggestion
The :mod:`pdb` ``alias`` command now prevents registering aliases without arguments.
```

2023-09-14 19:13 UTC, iritkatriel commented
@buermarc thanks for the fix. I see thing is your first PR in this repo. Care you add your name to the ``Misc/ACKS `` file?

2023-09-14 19:25 UTC, buermarc commented
Thanks for the reviewes

> You don't need to squash any commits on your feature branch. In fact, that is discouraged as it might make code review harder (to track the previous changes). The maintainers will squash all your commits when merging.

That makes sense. Thanks for the info!

> @buermarc thanks for the fix. I see thing is your first PR in this repo. Care you add your name to the `Misc/ACKS ` file?

I added my name, and tried to follow the "rough" alphabetical order :)

2023-09-14 21:12 UTC, gaogaotiantian commented
> @gaogaotiantian Is this a bugfix (should it be backported)?

I think we should backport it. It prevents `pdb` from raising an error in some situation - so not only improving user's experience, but actually protecting `pdb`'s execution. Also it's not disruptive at all, very self-contained, easy to backport and very low risk.

2023-09-14 21:12 UTC, gaogaotiantian commented
> @buermarc thanks for the fix. I see thing is your first PR in this repo. Care you add your name to the `Misc/ACKS ` file?

Ha! I was not even in the list!

2023-09-14 21:28 UTC, iritkatriel commented
> > @buermarc thanks for the fix. I see thing is your first PR in this repo. Care you add your name to the `Misc/ACKS ` file?
> 
> Ha! I was not even in the list!

Add yourself in your next PR.

2023-09-14 21:31 UTC, merged

2023-09-14 21:31 UTC, miss-islington commented
Thanks @buermarc for the PR, and @iritkatriel for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11, 3.12.
🐍🍒⛏🤖