gh-57141: Add dircmp shallow option.
python/cpython pull request #109499
Opened 2023-09-16 20:17 UTC by aunzat

Add support for non shallow file comparison for filecmp.dircmp like there is for filecmp.cmp and filecmp.cmpfiles.

Based on (BPO) patch from @planet36. I have added unittests for the shallow options and
reorganized the tests somewhat. Maybe a "new in version" should be added to the documentation?

Co-authored-by: Steve Ward <planet36@gmail.com>

Issue: #57141

2023-09-16 22:05 UTC, CuriousLearner commented on Doc/library/filecmp.rst
> +   :func:`filecmp.cmp`.
```suggestion
   The :class:`dircmp` class compares files by doing *shallow* comparisons
   as described for :func:`filecmp.cmp` by default using the *shallow* 
   parameter.
```

2023-09-16 22:06 UTC, CuriousLearner commented on Misc/NEWS.d/next/Library/2023-07-12-14-52-04.gh-issue-57141.L2k8Xb.rst
> +:func:`filecmp.cmp`.
```suggestion
Add option for *non-shallow* comparisons to :class:`filecmp.dircmp` like
:func:`filecmp.cmp`. Original patch by Steven Ward. Enhanced by 
Tobias Rautenkranz
```

2023-09-16 22:07 UTC, CuriousLearner requested changes
Hi Tobias @aunzat 👋🏼 

Thanks for your contributions!

Seems like the test case `test_dircmp_shallow_same_file` is failing. Can you please take a look?

I have a few suggestions mentioned inline.

Since this is your first contribution, if you prefer, you may add your name to `Misc/ACKS` file.

2023-09-17 11:10 UTC, aunzat commented
@CuriousLearner, thanks for comments

> Seems like the test case `test_dircmp_shallow_same_file` is failing. Can you please take a look?

Fixed

> I have a few suggestions mentioned inline.

Perfect, I have updated it accordingly.

2024-03-04 16:47 UTC, encukou commented
> Maybe a "new in version" should be added to the documentation

For a new argument, there's `versionchanged` -- see the [devguide](https://devguide.python.org/documentation/markup/#paragraph-level-markup).
I've uptated the branch, added the directive, and tested locally; since I had the commit I pushed it here directly rather than add a suggestion.

2024-03-04 17:27 UTC, merged