bpo-30058: Fixed buffer overflow in select.kqueue.control().
python/cpython pull request #1095
Opened 2017-04-12 17:20 UTC by serhiy-storchaka

2017-04-13 11:20 UTC, zhangyangyu commented on Modules/selectmodule.c
> +        nchanges = PySequence_Fast_GET_SIZE(arg);
`PySequence_Fast_GET_SIZE` returns a Py_ssize_t. This may trigger a compile warning.

2017-04-13 12:05 UTC, serhiy-storchaka commented on Modules/selectmodule.c
> +        nchanges = PySequence_Fast_GET_SIZE(arg);
Good point!

2017-04-13 12:53 UTC, zhangyangyu commented on Modules/selectmodule.c
> +        if (PySequence_Fast_GET_SIZE(arg) > INT_MAX / sizeof(struct kevent)) {
`arg` should be `seq`, right?

I don't think we need to `/ sizeof(struct kevent)`. `> INT_MAX` is enough.

2017-04-13 16:13 UTC, serhiy-storchaka commented on Modules/selectmodule.c
> +        if (PySequence_Fast_GET_SIZE(arg) > INT_MAX / sizeof(struct kevent)) {
Done.

2017-04-14 02:59 UTC, zhangyangyu approved these changes
LGTM from code. But I can't even compile.

2017-04-16 13:11 UTC, louisom requested changes
just a nit typo

2017-04-16 13:11 UTC, lulouie commented on Lib/test/test_kqueue.py
> +        # chagelist must be an iterable
typo: `chagelist` -> `changelist`

2017-04-16 13:12 UTC, lulouie commented
@zhangyangyu why can't you compile? My env compile it well.

2017-04-16 14:39 UTC, zhangyangyu commented
@lulouie , the code is specialized for BSD. I only have access to Linux. Compiling it on Linux doesn't make any sense.

2017-04-16 14:47 UTC, lulouie commented
@zhangyangyu ah, It has compiled on Linux, but only the GNU part, not BSD part.

2017-04-16 16:26 UTC, serhiy-storchaka commented on Lib/test/test_kqueue.py
> +        # chagelist must be an iterable
Good catch @lulouie!

2017-10-12 19:17 UTC, merged

2017-10-12 19:17 UTC, miss-islington commented
Thanks @serhiy-storchaka for the PR 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2017-10-12 19:20 UTC, miss-islington commented
Sorry, @serhiy-storchaka, I could not cleanly backport this to `2.7` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker de072100775cc29e6cd93a75466cecbd1086f258 2.7
                            ```