gh-107583: Update Doc/howto/unicode.rst
python/cpython pull request #109501
Opened 2023-09-16 23:02 UTC by xzmeng

- Replace PEP 263 with [Encoding declarations](https://docs.python.org/3/reference/lexical_analysis.html#encoding-declarations) to avoid misleading
- Reorder paragraphs about encoding comment to put Emacs thing behind
- Mark the link about Python 2 as "For historical interest"

2024-01-17 18:40 UTC, serhiy-storchaka approved these changes

2024-01-18 19:31 UTC, malemburg requested changes

2024-01-18 19:31 UTC, malemburg commented on Doc/howto/unicode.rst
> +literals start with ``u``). (Notice: Python 2 is no longer supported, just keep it
Better: (Note: Python 2 is no longer supported. We just keep this reference for historic reasons.)

2024-01-18 19:31 UTC, malemburg commented on Doc/howto/unicode.rst
> +already mentioned.
Please keep the reference to PEP 263, since this explains how it all works.

2025-09-26 16:18 UTC, StanFromIreland commented on Doc/howto/unicode.rst
> +``-*- coding: latin-1 -*-`` in the comment. See :ref:`encodings` for detailed
```suggestion
``-*- coding: latin-1 -*-`` in the comment. See :ref:`encodings` for a detailed
```
Grammar nit

2025-09-26 16:18 UTC, StanFromIreland commented on Doc/howto/unicode.rst
> +here for historical interest.)
```suggestion
literals start with ``u``). (Note: Python 2 is no longer supported.
This reference is preserved for historic reasons.)
```
A slightly different suggestion to the above.

2026-09-10 20:08 UTC, StanFromIreland commented
Closing as stale, the requested changes were never made.

2026-09-10 20:08 UTC, closed without merging