GH-109190: Copyedit 3.12 What's New: asyncio
python/cpython pull request #109661
Opened 2023-09-21 16:22 UTC by AA-Turner

- Standardise Itamar's name

2023-09-21 20:44 UTC, itamaro requested changes, later dismissed
thanks for this @AA-Turner !
I have changed my name recently, so let's go with the current name :)

2023-09-21 20:44 UTC, itamaro commented on Doc/whatsnew/3.12.rst
> +  (Contributed by Jacob Bower & Itamar Ostricher in :gh:`102853`, :gh:`104140`, and :gh:`104138`)
```suggestion
  (Contributed by Jacob Bower & Itamar Oren in :gh:`102853`, :gh:`104140`, and :gh:`104138`)
```

2023-09-21 20:44 UTC, itamaro commented on Doc/whatsnew/3.12.rst
> +  (Contributed by Itamar Ostricher in :gh:`103793`.)
```suggestion
  (Contributed by Itamar Oren in :gh:`103793`.)
```

2023-09-22 12:54 UTC, AA-Turner commented
The other instances need updating, will do when back on a
computer.

A

2023-09-22 13:14 UTC, hugovk commented
Allow me to help :)

2023-09-22 13:32 UTC, AA-Turner reviewed
Thanks Hugo! (GH doesn't let me approve the new changes as it's my own PR)

A

2023-09-22 13:32 UTC, merged

2023-09-22 13:32 UTC, miss-islington commented
Thanks @AA-Turner for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.12.
🐍🍒⛏🤖