[3.11] gh-109634: Use :samp: role (GH-109635)
python/cpython pull request #109778
Opened 2023-09-23 06:49 UTC by serhiy-storchaka

(cherry picked from commit 92af0cc580051fd1129c7a86af2cbadeb2aa36dc)

2023-09-28 04:06 UTC, JacobCoffee requested changes
Found a couple of oopsies

2023-09-28 04:06 UTC, JacobCoffee commented on Doc/library/codecs.rst
> +|                    |         | :samp:`\\U{XXXXXXXX}``    |
```suggestion
|                    |         | :samp:`\\U{XXXXXXXX}`    |
```
An extra backtick here

2023-09-28 04:06 UTC, JacobCoffee commented on Doc/reference/lexical_analysis.rst
> +| :samp:`\\{ooo}`         | Character with octal value      | (2,4) |
Is this missing the `\`? - it just renders as `{ooo}` in the preview docs.
```suggestion
| :samp:`\{ooo}`         | Character with octal value      | (2,4) |
```

2023-09-28 04:06 UTC, JacobCoffee commented on Misc/NEWS.d/3.8.0a1.rst
> +covers the implications of using custom :samp:sys.std{xxx}` objects.
```suggestion
covers the implications of using custom :samp:`sys.std{xxx}` objects.
```

2023-09-28 04:08 UTC, JacobCoffee commented on Doc/reference/lexical_analysis.rst
> +| :samp:`\\{ooo}`         | Character with octal value      | (2,4) |
Prod:
![image](https://github.com/python/cpython/assets/45884264/c05a7a5b-a148-464a-a570-85be08a2a220)
Preview:
![image](https://github.com/python/cpython/assets/45884264/0e2f7424-961b-4bdf-bf72-0b7ca741939c)

2023-09-28 05:55 UTC, serhiy-storchaka commented
:man_facepalming: Good catch @JacobCoffee. Do you mind to create a PR for main branch?

2023-09-28 05:56 UTC, JacobCoffee commented
Would this be based off of this branch or just with the fixes found?

2023-09-28 06:09 UTC, serhiy-storchaka commented on Doc/library/codecs.rst
> +|                    |         | :samp:`\\U{XXXXXXXX}``    |
It should be replaced with a space, not removed, to preserve the table formatting.
```suggestion
|                    |         | :samp:`\\U{XXXXXXXX}`     |
```

2023-09-28 06:09 UTC, serhiy-storchaka commented on Doc/reference/lexical_analysis.rst
> +| :samp:`\\{ooo}`         | Character with octal value      | (2,4) |
No, it needs more backslashes, not less.
```suggestion
| :samp:`\\\\{ooo}`       | Character with octal value      | (2,4) |
```

2023-09-28 06:15 UTC, serhiy-storchaka commented
Since the original changes were already merged in main and 3.12, they only need fixes. Note my corrections of two of your suggestions.

2023-09-29 03:17 UTC, JacobCoffee commented
#110073 is ready for you @serhiy-storchaka

2023-09-29 06:09 UTC, JacobCoffee approved these changes

2023-09-29 06:39 UTC, merged