GH-109653: Defer import of ``importlib.metadata._adapters``
python/cpython pull request #109829
Opened 2023-09-25 12:23 UTC by AA-Turner

For a ~14% speed up. However, this introduces inline imports into ``.metadata``, which might be undesirable.

A

2023-09-26 06:45 UTC, AA-Turner commented
> How is timing benchmarked

```console
$ python -X importtime -Sc 'import importlib.metadata' 2> importlib_metadata.log
$ cat importlib_metadata.log
$ tuna importlib_metadata.log
```

The [tuna](https://github.com/nschloe/tuna) viewer is optional, often I just read the text log.

A

2023-09-26 06:47 UTC, AA-Turner commented
> Can you confirm how much of the speedup is achieved by each of the two changes?

I'll try and come back with some timings

A

2024-03-21 02:59 UTC, jaraco requested changes
Thanks hugovk for providing the benchmarks for reference.

I do think we still need comments for these deferred imports to indicate why they're deferred. Without comments or something else to protect them, the optimizations could get normalized away.

2024-03-21 03:06 UTC, jaraco approved these changes

2024-03-21 03:49 UTC, merged

2024-03-21 13:08 UTC, jaraco commented
Cherry-picked to python/importlib_metadata@6673723baa and python/importlib_resources@ca03a4df06.