gh-110014: Fix inconsistent struct definition in pycore_semaphore.h
python/cpython pull request #110030
Opened 2023-09-28 14:54 UTC by colesbury

The pycore_semaphore.h header is included by Python/lock.c and Python/parking_lot.c. The macro `_POSIX_SEMAPHORES` was not consistently defined across the two files (due to a missing include of `<unistd.h>`) leading to different struct definitions. The RHEL8 ppc64le LTO buildbot correctly warned due to this issue.

2023-09-28 14:54 UTC, colesbury commented
!buildbot ppc64le

2023-09-28 14:55 UTC, colesbury commented
!buildbot lto

2023-09-28 15:08 UTC, colesbury commented
1) I verified locally that `pycore_semaphore.h` now consistently defines `_PySemaphore` (by temporarily added `#warning`)
2) https://buildbot.python.org/all/#/builders/256/builds/1238 (ppc64, lto) does not have any warnings related to `pycore_semaphore.h`. It's not identical to the buildbot running on the main branch, but it's the closest configuration I could find for PRs.

2023-09-28 15:25 UTC, vstinner commented
> The regex 'ppc64le' did not match any buildbot builder.Is the requested builder in the list of stable builders?

Oh, maybe the search is case sensitive and you should use ``PPC64LE`` or ``PPC64LE RHEL8``.

2023-09-28 15:27 UTC, colesbury commented
!buildbot PPC64LE

2023-09-28 15:31 UTC, colesbury commented
Thanks!

2023-09-29 16:52 UTC, colesbury commented
@vstinner, would you please review this when you get a chance?

2023-09-30 10:39 UTC, vstinner requested changes
Oh wait. The problem is way wider than pycore_semaphore.h! _POSIX_THREADS and _POSIX_SEMAPHORES macros are checked in Python/pthread_thread.h, pycore_condvar.h. and pycore_pythread.h without explicitly including <unistd.h>.

I wrote a wider change to attempt to fix all cases: PR gh-110139.

2023-09-30 17:26 UTC, vstinner commented
I wrote a more complete fix: PR #110139. Thanks for working on fixing these warnings!

2023-09-30 17:26 UTC, closed without merging