Update ftplib.rst documentation
python/cpython pull request #11023
Opened 2018-12-07 12:34 UTC by pinguin999

# Update docs for FTP lib

The docs only showed how to download a file via FTP but not how to upload a file.

Now the docs have an example for download and upload files via ftp.

2018-12-07 12:34 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-03-19 15:52 UTC, remilapeyre requested changes

2019-03-19 15:52 UTC, remilapeyre commented on Doc/library/ftplib.rst
> +   >>> ftp.retrbinary('RETR README', open('README', 'wb').write)  # Download the file README
Hi @pinguin999, thanks for improving the documentation!

It seems to me that the file you open here is not closed before doing the upload next line. Shouldn't you close it before opening it again and reading from it?

Maybe we should use context managers here, after all, it probably isn't great to encourage beginners to keep their files open.

2019-09-11 10:22 UTC, JulienPalard commented
Hi @pinguin999, thanks for trying to enhance the documentation. IIRC this has already been proposed (can't find where though), and was refused because it make the example unrealistic (a user have a high chance not having the rights to write on ftp.debian.org).

I think the example is enough demoing the lib, it's short and readable, I don't think we need to add every ftplib function in it. And the `storbinary` is documented a few lines after.

2019-09-11 10:22 UTC, closed without merging