gh-110628: Add tests for PyLong C API
python/cpython pull request #110629
Opened 2023-10-10 13:00 UTC by serhiy-storchaka

2023-10-10 13:15 UTC, sobolevn commented on Modules/_testcapi/long.c
> +pylong_asssize_t(PyObject *module, PyObject *arg)
```suggestion
pylong_as_ssize_t(PyObject *module, PyObject *arg)
```

It is really hard to tell `_assize_t` and `_asssize_t` when reading

2023-10-10 13:15 UTC, sobolevn commented on Modules/_testcapi/long.c
> +pylong_assize_t(PyObject *module, PyObject *arg)
```suggestion
pylong_as_size_t(PyObject *module, PyObject *arg)
```

2023-10-10 19:55 UTC, erlend-aasland requested changes

2023-10-10 19:55 UTC, erlend-aasland commented on Modules/_testcapi/long.c
> +        // XXX 'end' is not always set.
What does `XXX` imply? Is it a FIXME or TODO comment? If it has no special meaning, I think it should be removed. If it has a special meaning, it should be expressed clearly.

2023-10-10 19:55 UTC, erlend-aasland commented on Lib/test/test_capi/test_long.py
> +        """Test PyLong_Check()"""
These docstrings do not add any information; they just repeat the test name with a slightly different text format. They also clutter the test output when running tests in verbose mode. Please do not pollute tests like this.

2023-10-10 20:07 UTC, vstinner commented on Lib/test/test_capi/test_long.py
> +
Maybe tests values around 0, like -0.0, +0.0, and `math.nextafter(0.0, 1.0)` (subnormal positive minimum)?

2023-10-10 20:07 UTC, vstinner commented on Lib/test/test_capi/test_long.py
> +        self.assertGreaterEqual(y, 0)
NULL can be greater than 0?

```suggestion
        self.assertEqual(y, 0)
```

2023-10-10 20:07 UTC, vstinner commented on Modules/_testcapi/long.c
> +        // XXX 'end' is not always set.
not good :-( can it be fixed?

2023-10-10 20:07 UTC, vstinner commented on Modules/_testcapi/long.c
> +    return Py_NewRef((PyObject *)value);
Wait, is it an object? It's just a raw pointer, no?

Maybe return PyLong_FromVoidPtr(value)?

2023-10-11 12:46 UTC, vstinner commented on Lib/test/test_capi/test_long.py
> +                self.assertEqual(fromdouble(value), int(value))
This test is now suspicious. What if int() executes exactly the same code path, PyLong_FromDouble()?

I would prefer to hardcode the expected result:

```
for value, expected in (
    (5.0, 5),
    ...
    (float_max, int(float_max)),
):
    ...
```

2023-10-11 19:56 UTC, serhiy-storchaka commented on Lib/test/test_capi/test_long.py
> +        """Test PyLong_Check()"""
Actually, some of them add information. For example  `test_long_aslong` tests both`PyLong_AsLong()` and `PyLong_FromLong()`, unlike most of other tests.

But I understand your pain. The right solution perhaps to add options to hide docstrings, or change the default report format, or output docstring only in `-vv` mode. But this is a different issue. I'll turn docstrings into comments.

2023-10-11 19:56 UTC, serhiy-storchaka commented on Lib/test/test_capi/test_long.py
> +
I do not think that they are interesting, but I'll add zeroes.

2023-10-11 19:56 UTC, serhiy-storchaka commented on Lib/test/test_capi/test_long.py
> +        self.assertGreaterEqual(y, 0)
Hmm. One part of me remember, that bitpattern of NULL is not always zeroes. But on other hand, a lot of code in CPython depends on this (starting from initializing pointers with `memset()`).

2023-10-11 19:56 UTC, serhiy-storchaka commented on Modules/_testcapi/long.c
> +        // XXX 'end' is not always set.
It means that that we cannot add `assert(end != UNINITIALIZED_PTR)` here. `end` is not set if `base` is incorrect, and maybe in case of memory allocation error. I am not sure what to do with this. It is not correct to set `end = str`, because the first character can be valid. Maybe set it to NULL? This is a different issue, and I am going to think about this later.

XXX means "Look! Something not good here."

2023-10-11 19:56 UTC, serhiy-storchaka commented on Modules/_testcapi/long.c
> +        // XXX 'end' is not always set.
Not in this issue. And it is not clear what fix may look like.

2023-10-11 19:56 UTC, serhiy-storchaka commented on Modules/_testcapi/long.c
> +    return Py_NewRef((PyObject *)value);
Yes, it is a raw pointer. But Python does not have pointers. So these tests only test pointers to Python objects (and NULL). With `PyLong_FromVoidPtr() and `PyLong_AsVoidPtr()` we can round trip object -> int -> object.

2023-10-11 19:56 UTC, serhiy-storchaka commented on Lib/test/test_capi/test_long.py
> +                self.assertEqual(fromdouble(value), int(value))
Right, it is the purpose. `PyLong_FromDouble()` works exactly as `int()` with float argument.

How does `int()` with float argument work is tested in other tests.

2023-10-14 05:53 UTC, merged

2023-10-14 05:54 UTC, miss-islington commented
Thanks @serhiy-storchaka for the PR 🌮🎉.. I'm working now to backport this PR to: 3.12.
🐍🍒⛏🤖

2023-10-14 05:54 UTC, miss-islington commented
Sorry, @serhiy-storchaka, I could not cleanly backport this to `3.12` due to a conflict.
Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
```
cherry_picker 9d40ebf1902812fad6aa85ede7b6f1fdff3c1291 3.12
```