deprecate asyncio.set_event_loop_policy
python/cpython pull request #110728
Opened 2023-10-11 15:54 UTC by graingert

2023-10-11 18:53 UTC, cjw296 reviewed
No objection to the unittest or AsyncMock changes!

2023-10-26 01:02 UTC, gvanrossum reviewed
Just a few nits, basically LG. That `tearDownModule()` pattern is annoying! :-)

I assume that deprecating `get_event_loop_policy()` will follow? Are there other APIs? I'm guessing we also want to avoid instantiating or subclassing the standard event loop policy classes (I expect this will turn up some significant uses of them).

Before we merge this we may need to bring this up on discuss.python.org (in the asyncio category) to see if there are significant objections to the proposed deprecation schedule.

2023-10-26 01:02 UTC, gvanrossum commented on Doc/library/asyncio-policy.rst
> +be removed in Python 3.15.
We should review the deprecation once we've reached that point:
```suggestion
be removed in Python 3.15 or later.
```

2023-10-26 01:02 UTC, gvanrossum commented on Lib/asyncio/events.py
> +                         "removed in Python {remove}.", remove=(3, 15))
Either "may be removed" or "3.15 or later"?

2023-10-26 01:02 UTC, gvanrossum commented on Lib/test/test_asyncio/test_events.py
> +            asyncio.set_event_loop_policy(policy)
`cm` unused?
```suggestion
        with self.assertWarns(DeprecationWarning):
            asyncio.set_event_loop_policy(policy)
```

2023-10-26 01:02 UTC, gvanrossum commented on Misc/NEWS.d/next/Library/2023-10-11-15-55-53.gh-issue-94597.qXo8Q4.rst
> +deprecate :func:`asyncio.set_event_loop_policy`
Misc/NEWS entries should be capitalized and punctuated properly (they are formatted as paragraphs ReST text somewhere).
```suggestion
Deprecate :func:`asyncio.set_event_loop_policy`.
```

2023-10-26 19:19 UTC, graingert commented
> Just a few nits, basically LG. That `tearDownModule()` pattern is annoying! :-)

I think we can start getting rid of tearDownModules using #110774 

> I assume that deprecating `get_event_loop_policy()` will follow? Are there other APIs? I'm guessing we also want to avoid instantiating or subclassing the standard event loop policy classes (I expect this will turn up some significant uses of them).

Yep currently that's a bit more complicated because get/set_event_loop calls get_event_loop_policy and afaik we don't want to make get_event_loop an alias of get_running_loop anymore

2023-10-27 17:03 UTC, willingc reviewed
Thanks for the PR. I've left a few questions for you.

2023-10-27 17:03 UTC, willingc commented on Lib/test/libregrtest/save_env.py
> +        support.set_event_loop_policy(policy)
Is line 99 still necessary?

2023-10-27 17:03 UTC, willingc commented on Doc/library/asyncio-policy.rst
> +be removed in Python 3.15.
Do we want to give a reason as to why the policy system is being deprecated?

2023-10-29 01:09 UTC, gvanrossum commented on Doc/library/asyncio-policy.rst
> +be removed in Python 3.15.
Good question. I don't think there's anyone among the (current or past) asyncio maintainers thinks the policy system was a good idea -- it's too complex with not enough benefits. But do we need to explain this in the docs? I don't believe we usually document the reason for a deprecation.

2023-10-29 19:28 UTC, hugovk commented
Please also mention the deprecation in What's New in Python 3.13.

Because it's to be removed in 3.15 or later it could be listed under either [Pending Removal in Python 3.15](https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-python-3-15) or [Pending Removal in Future Versions](https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-future-versions).

I suggest the former, as it's more likely to be noticed and action taken, and include the "3.15 or later" wording. We can update later if needed.

2023-10-31 16:27 UTC, graingert commented on Lib/test/libregrtest/save_env.py
>          asyncio = self.get_module('asyncio')
```suggestion
```

2023-10-31 16:28 UTC, graingert commented on Lib/test/libregrtest/save_env.py
> +        support.set_event_loop_policy(policy)
no, I've removed it

2023-10-31 16:28 UTC, graingert commented on Lib/asyncio/events.py
> +                         "removed in Python {remove}.", remove=(3, 15))
```suggestion
                         "{name!r} is deprecated as of Python 3.13 and will be "
                         "removed in Python {remove} or later.", remove=(3, 15))
```

2023-10-31 16:42 UTC, hugovk commented on Doc/whatsnew/3.13.rst
> +  rest of the asyncio policy system.
3.15 or later?

```suggestion
  rest of the asyncio policy system in Python 3.15 or later.
```

2023-10-31 16:46 UTC, graingert commented
> Before we merge this we may need to bring this up on discuss.python.org (in the asyncio category) to see if there are significant objections to the proposed deprecation schedule.

discuss post posted here: https://discuss.python.org/t/removing-the-asyncio-policy-system-asyncio-set-event-loop-policy-in-python-3-15/37553

2023-10-31 20:52 UTC, gvanrossum approved these changes
Okay, I'm happy with this. Let's wait a bit if anyone brings up substantial objections in the [Discourse thread](https://discuss.python.org/t/removing-the-asyncio-policy-system-asyncio-set-event-loop-policy-in-python-3-15/37553).

2023-10-31 23:36 UTC, willingc approved these changes
Bravo @graingert for simplifying. ✨

2023-11-01 13:14 UTC, kumaraditya303 requested changes
Please also add a notice under `asyncio` changes, most users like myself won't look under 3.15 removals for this change. Thanks

2023-11-01 13:40 UTC, graingert commented
> Please also add a notice under `asyncio` changes, most users like myself won't look under 3.15 removals for this change. Thanks

Can you link me to the location in the docs that you mean please?

2023-11-01 13:40 UTC, graingert commented
> Please also add a notice under `asyncio` changes, most users like myself won't look under 3.15 removals for this change. Thanks

Can you link me to the location in the docs that you mean please?

2023-11-01 13:59 UTC, kumaraditya303 commented
> Can you link me to the location in the docs that you mean please?

Add `asyncio` entry in https://docs.python.org/3.13/whatsnew/3.13.html#deprecated for `asyncio`

2023-11-01 16:07 UTC, hugovk commented
That sounds fine, then let's move it from the "Pending Removal in Python 3.15" section to this one.

2023-11-01 18:56 UTC, graingert commented
I have made the requested changes; please review again

2023-11-01 21:22 UTC, gvanrossum approved these changes
LGTM, but let's wait until the dust in the Discourse thread settles.

2024-09-12 03:35 UTC, 1st1 commented
Happy to review and hopefully merge this during the core sprint.

2024-12-25 08:05 UTC, closed without merging

2024-12-25 08:05 UTC, graingert commented
@kumaraditya303 is doing this now