gh-110745: feat: pathlib.Path.read_text should include a newline argument
python/cpython pull request #110880
Opened 2023-10-14 19:44 UTC by Okabe-Junya

2023-10-18 18:08 UTC, barneygale commented
Looking good! Could you also add a test in `Lib/test/test_pathlib.py`? Maybe have a look at `test_write_text_with_newlines` :)

2023-10-21 15:16 UTC, Okabe-Junya commented
Thank you for your kind review! I apologize for the delayed response.

As you suggested, I intend to add the appropriate tests. Please give me a moment.

2023-10-21 19:43 UTC, Okabe-Junya commented
Only the test on Windows is failing. I wonder why...

2023-10-24 02:27 UTC, Okabe-Junya commented
Implementing tests using os.linesep seems challenging. Especially on Windows, where the newline code is `\r\n`, covering this in test cases appears difficult.

Would it be appropriate to separate test cases for each OS?

2023-10-29 16:55 UTC, barneygale commented
Regarding `newline=None`, this should convert all newlines to `\n` on read, on all OSs, so your test shouldn't need to reference `os.linesep`. Maybe something like this?

```python
    def test_read_text_with_newlines(self):
        p = self.cls(BASE, 'fileA')
        p.write_bytes(b'abcde\r\nfghlk\n\rmnopq')
        self.assertEqual(p.read_text(newline=None),   'abcde\nfghlk\n\nmnopq')
        self.assertEqual(p.read_text(newline=''),     'abcde\r\nfghlk\n\rmnopq')
        self.assertEqual(p.read_text(newline='\r'),   'abcde\r\nfghlk\n\rmnopq')
        self.assertEqual(p.read_text(newline='\n'),   'abcde\r\nfghlk\n\rmnopq')
        self.assertEqual(p.read_text(newline='\r\n'), 'abcde\r\nfghlk\n\rmnopq')
```

2023-10-31 05:38 UTC, Okabe-Junya commented
@barneygale 

Thank you for your thoughtful comment!!

I've implemented tests based on your feedback, and they now pass!!

2023-11-02 11:10 UTC, rawwar commented
closes #110745

2023-11-21 03:22 UTC, barneygale requested changes
Sorry for my delayed feedback. Last thing to do is to fix the version number, and give yourself some credit in the changelog if you wish :)

2023-11-21 03:22 UTC, barneygale commented on Doc/library/pathlib.rst
> +   .. versionchanged:: 3.12
```suggestion
   .. versionchanged:: 3.13
```

2023-11-21 03:22 UTC, barneygale commented on Misc/NEWS.d/next/Library/2023-10-15-08-08-26.gh-issue-110745.mxEkh0.rst
> +Added *newline* parameter to ``pathlib.Path.read_text()``.
```suggestion
Added *newline* parameter to :meth:`pathlib.Path.read_text`.
Patch by Junya Okabe.
```

2023-11-21 04:53 UTC, Okabe-Junya commented
Thank you for your kind review!! (I might not have mentioned properly. I am sorry for that)

I accept your polite suggestion and am ready to merge this. Thank you.

2023-11-21 04:53 UTC, Okabe-Junya commented
I have made the requested changes; please review again

2023-11-21 22:29 UTC, barneygale approved these changes
Looks good, thank you very much!

2023-11-21 22:32 UTC, merged