Fix information about sequence indexes
python/cpython pull request #110903
Opened 2023-10-15 18:28 UTC by adorilson

The documentation says:

```These represent finite ordered sets indexed by non-negative numbers```

but indexes can be negative too. This PR fixed it and added some information about indexes.

2023-11-03 13:49 UTC, encukou commented
Thank you for your attention to detail.

I'd keep the opening statement about what sequences *are*, and only after that add that they can *also* be indexed using negative numbers. The next section then adds indexing by slices.
Would this wording work for you?

```rst
These represent finite ordered sets indexed by non-negative integers. The
built-in function :func:`len` returns the number of items of a sequence. When
the length of a sequence is *n*, the index set contains the numbers 0, 1,
..., *n*-1. Item *i* of sequence *a* is selected by ``a[i]``.

Sequences also support indexing with negative numbers: ``a[-1]`` selects
the last item, ``a[-2]`` selects the penultimate (next to last) item and so forth.
That is, ``seq[-n]`` selects the same item as ``seq[len(seq) - n]`` (for *n*
``>`` ``0``).
```

2023-11-04 16:22 UTC, adorilson commented
In general, it sounds good. However, it keeps the main problem for me: non-negative numbers in sequence definition. The text sounds auto-conflicted: first, we say non-negative numbers index the sequence, and after, we say negative numbers also index the sequence. It is weird.

Besides, the `integer numbers` version is more [PEP 3119](https://peps.python.org/pep-3119/#sequences) compliance. Or...

Did I understand wrong, and the negative numbers are not expected and assurance? Are there some built-in sequences, for example this case? If this is the case, maybe your second paragraph can start with this disclaimer `Some sequences also...`

2024-02-25 05:33 UTC, terryjreedy commented
Actually, some (not guaranteed) sequences are indexed by the hack/cleaver-device of interpreting `-n` as `len(seq)-n`, which must result in a non-negative int in the proper range.  So -len to -1 result in valid indexes of 0 to len-1.  I agree with Petr's suggestion except I might change ``seq[-n]`` selects the same item as ``seq[len(seq) - n]`` to ``seq[-n]`` is interpreted  as ``seq[len(seq) - n]``.  Or replace 'interpreted as' with 'converted to'.

2024-02-25 18:28 UTC, adorilson commented
I got the point.

I didn't realize the difference between the indexes and subscription operations.
Although the indexes are non-negative numbers, the subscription operation also works with negative numbers.

So, what do you think about erasing details about that and referencing subscription and slicing operations?
Subscription documentation takes care of negative numbers as well.

```
These represent finite ordered sets indexed by non-negative numbers. The
built-in function :func:`len` returns the number of items of a sequence. When
the length of a sequence is *n*, the index set contains the numbers 0,
1, 2, ..., *n*-1.

Sequences are instances of a :ref:`container class <sequence-types>`, so they
support the :ref:`subscription <subscriptions>` and :ref:`slicing <slicings>`
operations. Also, sequences are distinguished according to their mutability:
```

2024-03-25 15:05 UTC, adorilson commented
I have made the requested changes; please review again

2024-03-25 17:03 UTC, zware commented
Please be careful about rebasing.  In general it's simplest to avoid it altogether unless you're sure you can get it right, which usually means carefully doing an `--interactive` rebase onto `python/cpython:main` rather than your own main branch.  And never trust an automated rebase, it will be wrong :)

I have rebased your branch on `python/cpython:main` and force-pushed to your fork, please make sure to reset your local branch before doing anything else here.

2024-03-25 17:20 UTC, terryjreedy requested changes
This revised proposal is a regression that simply removes information, contrary to the expressed motivation of adding info.  I do not understand the reason at all.  Note that the rebase erased the original proposal, so I cannot comment on that.

Either abandon and close or revert these deletions and add the paragraph suggested by @encukou with my addition of 'Some' and maybe other touchups.

Or I can close this and make a new PR based on Petr's suggestion.

2024-03-25 17:24 UTC, terryjreedy commented
The original rebase made this PR unable to be merged without special admin intervetion because it added 4 people without signed CLAs to the list of people required to have them.  Zachary's 2nd rebase undid that while I was in the process of commenting.  Blind rebasing is really bad.  The rebase also seems to have erased the original proposed patch.

2024-03-25 18:04 UTC, terryjreedy requested changes
Reviewing this area of the Datamodel section further, I think it would be sufficient to add the following to the existing paragraph.
> Some sequences, including built-in sequences, interpret negative subscripts by adding the sequence length.  For example, ``a[-2]`` equals ``a[n-2]``, the second to last item of sequence ``a`` with length ``n``.

In the discussion of slicing, the existing sentence "This implies that the index set is renumbered so that it starts at 0."  is meaningless as Python indexes already start at 0.  (Is this sentence a fossil from pre-release Python with 1-based indexes?)  Replace with
> The comment above about negative indexes also applies to negative slice positions.

2024-03-25 19:56 UTC, adorilson commented
I have made the requested changes; please review again

@terryjreedy I reverted all my previous commits then I applied your last suggestion. Thank you.

2024-03-25 22:31 UTC, terryjreedy approved these changes

2024-03-25 22:34 UTC, merged

2024-03-25 22:42 UTC, terryjreedy commented
Both backports merged.