gh-110905: fix enum._is_private for triple underscore names
python/cpython pull request #110906
Opened 2023-10-15 18:55 UTC by eendebakpt

* Fix `enum._is_private` for triple underscore names
* Rewrite `_is_sunder` check in the same style as `_is_private`
* Remove unused variable `blanks`
* Update docstring

2023-10-16 16:19 UTC, ethanfurman requested changes
A couple changes and we're good to go!

2023-10-16 16:19 UTC, ethanfurman commented on Lib/enum.py
> +            and name[pat_len] != '_'
Just remove this line.
```suggestion
```

2023-10-16 16:19 UTC, ethanfurman commented on Lib/test/test_enum.py
>      private_names = '_MyEnum__private', '_MyEnum__still_private'
```suggestion
    private_names = '_MyEnum__private', '_MyEnum__still_private', '_MyEnum___triple_private'
```

2023-10-16 16:19 UTC, ethanfurman commented on Lib/test/test_enum.py
> +    random_names = 'okay', '_semi_private', '_weird__', '_MyEnum__', '___triple_underscore'
Move this up to the `private_names` line.
```suggestion
    random_names = 'okay', '_semi_private', '_weird__', '_MyEnum__',
```

2023-10-16 18:20 UTC, eendebakpt commented on Lib/test/test_enum.py
> +    random_names = 'okay', '_semi_private', '_weird__', '_MyEnum__',
```suggestion
    random_names = 'okay', '_semi_private', '_weird__', '_MyEnum__'
```

2023-10-16 18:27 UTC, ethanfurman approved these changes

2023-10-16 20:37 UTC, merged

2023-10-17 01:12 UTC, sunmy2019 commented
@ethanfurman shall we backport this?