DOC: emphasize the need to always call PySequence_Fast
python/cpython pull request #11140
Opened 2018-12-13 06:30 UTC by mattip

`PySequence_Fast()` should always be used (and the result checked) before any of the other `PySequence_Fast*` family of functions. As an implementation detail, CPython can circumvent this if `PyTuple_CheckExact()` passes, but that does not work on PyPy. 

xref numpy/numpy#12524

2018-12-13 10:35 UTC, serhiy-storchaka commented
Is not this a PyPy issue that `PySequence_Fast*` functions do not work with lists and tuples?

2018-12-13 11:16 UTC, mattip commented
The functions work for `ret` after calling `PyObject* ret = PySequence_Fast(o)`, on both PyPy and CPython, but the documentation was not clear that this is always necessary. Hopefully now it is clearer.

2018-12-14 04:12 UTC, eric-wieser commented
@serhiy-storchaka: I think the point is that requiring those functions to work on lists and tuples puts nasty lifetime constraints on pypy, which could be lifted simply by relaxing the documentation to saying _"`PySequence_Fast_ITEMS` is only defined on the result of `PySequence_Fast`"_.

2019-02-04 10:34 UTC, jdemeyer approved these changes

2019-06-07 04:20 UTC, serhiy-storchaka commented
I think this change needs more wide discussion. Please open an issue on the [bug tracker](https://bugs.python.org/) and ask the question on the [Python-Dev mailing list](https://mail.python.org/archives/list/python-dev@python.org/).

2019-09-11 10:40 UTC, JulienPalard commented
@mattip Hi, have you been able to open an issue on bugs.python.org about it as requested by Serhiy?

2019-09-11 12:11 UTC, mattip commented
@serhiy-storchaka what do you see as controversial? Perhaps you could suggest a phrasing that would not require such an extensive discussion for a documentation clarification?

2019-09-12 14:10 UTC, benjaminp requested changes

2019-09-12 14:10 UTC, benjaminp commented on Doc/c-api/sequence.rst
> +   Equivalent to :c:func:`PySequence_GetItem` but faster.
Not exactly. At the very least, it has a difference analogous to the one between `PySequence_GetItem` and `PySequence_GetItem`, where the "fast" form doesn't handle negative indexes.

2019-09-12 14:10 UTC, benjaminp commented on Doc/c-api/sequence.rst
> +   :c:func:`PySequence_Size` but faster.
I don't like to say these are equivalent, since `PySequence_Fast_GET_SIZE` has the assumption that `PySequence_Fast` has been called. The old sentence was clearer.

2019-09-12 14:10 UTC, benjaminp commented on Doc/c-api/sequence.rst
> +   raises :exc:`TypeError` with *m* as the message text.
I suggest only describing the abstract semantics (the first and last sentences) of this function in the first paragraph and moving the implementation details below (the middle sentence).

2019-09-12 14:10 UTC, benjaminp commented on Doc/c-api/sequence.rst
> +   This family of functions is labelled *Fast* since it can assume *o* is a
It would be clearer to say "The `PySequence_Fast_*` functions are thus named because they assume...".

2019-09-12 15:28 UTC, benjaminp commented on Doc/c-api/sequence.rst
> +   *o* is a :c:type:`PyTupleObject` or a :c:type:`PyListObject`, and accesses
`s/accesses/access/`

2019-09-12 15:28 UTC, benjaminp commented on Doc/c-api/sequence.rst
> +   The ``PySequence_Fast*`` functions are thus named because they can assume
remove `can`

2019-09-12 15:28 UTC, benjaminp commented on Doc/c-api/sequence.rst
> +   the type's data fields directly.
`s/type's/*o*'s/`

2019-09-12 15:28 UTC, benjaminp commented on Doc/c-api/sequence.rst
> +   raises :exc:`TypeError` with *m* as the message text.
This partially duplicates the first paragraph now.

2019-09-12 16:19 UTC, merged