bpo-35450: reflect in docs that venv module is not always creating a …
python/cpython pull request #11144
Opened 2018-12-13 18:24 UTC by mkkot

…copy of python binary

https://bugs.python.org/issue35450

2018-12-13 19:14 UTC, brettcannon requested changes

2018-12-13 19:14 UTC, brettcannon commented on Doc/using/venv-create.inc
> +containing a copy/symlink of the Python binary/binaries (as appropriate by the
```suggestion
containing a copy/symlink of the Python binary/binaries (as appropriate for the
```

2018-12-13 19:15 UTC, brettcannon commented
@mkkot only one minor grammatical change to make. Otherwise I'm just waiting for your CLA to be processed and then I can merge the change!

2018-12-14 19:45 UTC, mkkot commented
Sure, please merge. What about backporting, who is dealing with this?

2018-12-14 20:03 UTC, brettcannon commented
@mkkot our magical bots handle backports 😄  (that's what the labels actually trigger).

2018-12-14 20:04 UTC, brettcannon commented
@mkkot I can't merge until you either accept the suggested fix or click the checkbox to let maintainers modify your branch (I just tried and GitHub says I can't do it).

2018-12-14 20:08 UTC, mkkot commented
@brettcannon I resolved the conversation, hope now you can merge.

2018-12-14 20:24 UTC, brettcannon approved these changes

2018-12-14 20:28 UTC, merged

2018-12-14 20:35 UTC, brettcannon commented
@mkkot I actually wanted the suggested change to get merged, but it turned out I had the appropriate permissions to edit the file, so I just went ahead and did that.

Thanks for the PR!