Reusable ubuntu build with GIL disabled
python/cpython pull request #111452
Opened 2023-10-29 06:59 UTC by NCLI

2023-10-29 07:32 UTC, corona10 commented on .github/workflows/build.yml
> +          build_ubuntu_nogil,
```suggestion
          build_ubuntu_free_threaded,
```

2023-10-29 07:32 UTC, corona10 commented on .github/workflows/build.yml
> +            build_ubuntu_nogil,
```suggestion
            build_ubuntu_free_threaded,
```

2023-10-29 07:32 UTC, corona10 commented on .github/workflows/build.yml
> +    name: 'Ubuntu GIL disabled'
```suggestion
    name: 'Ubuntu'
```

2023-10-29 07:33 UTC, corona10 commented on .github/workflows/build.yml
> +  build_ubuntu_nogil:
```suggestion
  build_ubuntu_free_threaded:
```

2023-10-29 07:38 UTC, corona10 commented on .github/workflows/build.yml
> +    - build_ubuntu_nogil
```suggestion
    - build_ubuntu_free_threaded
```

2023-10-29 10:18 UTC, corona10 commented on .github/workflows/build.yml
> +    if: needs.check_source.outputs.run_tests == 'true'
We should check that the label is attached   or not.

2023-10-29 10:29 UTC, corona10 requested changes
Please skip the test if the label is not attached
https://github.com/python/cpython/pull/111452/files#r1375408558

2023-10-29 15:07 UTC, corona10 commented on .github/workflows/build.yml
> +    if: needs.check_source.outputs.run_tests == 'true'
```suggestion
    if: needs.check_source.outputs.run_tests == 'true' && contains(github.event.pull_request.labels.*.name, 'topic-free-threaded')
```

2023-10-29 15:09 UTC, corona10 approved these changes
Now it looks good to me
@hugovk @ezio-melotti  Can you please take a look?

2023-10-29 17:23 UTC, hugovk commented
I'll add the https://github.com/python/cpython/labels/topic-free-threaded label to check if it triggers.

2023-10-29 17:33 UTC, hugovk commented
The label would need to have been added before the _workflow_ runs, which means you need to add it when drafting the PR or do it very quickly.

Or we need to add triggers similar to this:

https://github.com/python/cpython/blob/fa35b9e89b2e207fc8bae9eb0284260d0d922e7a/.github/workflows/require-pr-label.yml#L3-L5

But that adds extra complexity because we don't want to re-trigger all the other CI jobs.

---

More to the point: do we really need to limit this via a label?

Should we always run it?

After all, we want to make sure there are no regressions for both the GIL and free-threaded builds, whether or not someone considers their PR to somehow related free-threaded.

2023-10-29 21:15 UTC, corona10 commented
> The label would need to have been added before the workflow runs, which means you need to add it when drafting the PR > or do it very quickly.
> 
> Or we need to add triggers similar to this:
> More to the point: do we really need to limit this via a label?
>  Should we always run it?

I know this issue, but `topiuc-free-thread` works are not a big portion of over all PRs so I think that it can be taken into account anyway at this moment. In the near future it can be run anyway once the `free-thread` version becomes stable but looks like not this moment. :)

2023-10-29 21:18 UTC, corona10 commented
> The label would need to have been added before the workflow runs, which means you need to add it when drafting the PR or do it very quickly.

And it's intended design at this moment, or we need to improve it at later

2023-10-29 21:50 UTC, corona10 commented
And simply re-open the PR will works if the person miss the timing of the labeling

2023-10-30 14:27 UTC, hugovk approved these changes
Thanks, let's merge this.

We can remove the label-handling later when we're all ready for it.

Let's also consider the YML file names later, once the Windows one is also done.

And at the same time we can see about naming the "build_x" bit (the third part in "Tests / OS / build_x") in a nicer and more consistent way:

![image](https://github.com/python/cpython/assets/1324225/6352dff4-80ea-44bc-aa1b-d97eb7bedc8f)

PS We'll need to backport all of these PRs to 3.11/3.12 -- but obviously not the free threaded part. And we can take care of that later too.

2023-10-30 14:28 UTC, merged

2023-10-30 14:44 UTC, NCLI commented
Thanks for the help @corona10 :-)