gh-111354: Simplify _PyGen_yf by moving some of its work to the compiler and frame state
python/cpython pull request #111648
Opened 2023-11-02 14:53 UTC by iritkatriel

This splits the SUSPENDED frame state into SUSPENDED and SUSPENDED_YIELD_FROM, adds an oparg to YIELD_VALUE to indicate whether it's in a yield-from or await (so it can set the state correctly). With this, `_PyGen_yf` has a lot less work to do.

2023-11-02 16:33 UTC, markshannon requested changes
I'd like to avoid the extra branch in `YIELD_VALUE`.
Other than that, looks good.

2023-11-02 16:33 UTC, markshannon commented on Python/bytecodes.c
> +            gen->gi_frame_state = oparg ? FRAME_SUSPENDED_YIELD_FROM : FRAME_SUSPENDED;
Can we make this unconditional?
Ideally `gen->gi_frame_state = oparg`, but that might require flipping the sign of the all the gen state constants.
`gen->gi_frame_state = oparg + K` would be OK.

2023-11-02 16:33 UTC, markshannon commented on Python/bytecodes.c
> +            gen->gi_frame_state = oparg ? FRAME_SUSPENDED_YIELD_FROM : FRAME_SUSPENDED;
Ditto

2023-11-02 17:54 UTC, iritkatriel commented
When you're done making the requested changes, leave the comment: I have made the requested changes; please review again.

2023-11-03 09:57 UTC, markshannon approved these changes
Looks good.

2023-11-03 10:01 UTC, merged