bpo-32810: Allow accessing the ags_gen and agt_gen attrs of async generators
python/cpython pull request #11166
Opened 2018-12-14 19:57 UTC by ZackerySpytz

2018-12-15 15:18 UTC, asvetlov requested changes
Looks very good, thanks!

Would you add a docs update to reflect new fields?

2018-12-15 15:31 UTC, 1st1 commented
Please don't merge this. I'm not sure i want them to be exposed.

2018-12-15 15:34 UTC, 1st1 requested changes
We need to consider this carefully. Exposing these fields pins the current implementation and might prevent us from evolving it. It's also unclear if it's possible to implement this in PyPy et al

2018-12-15 15:54 UTC, asvetlov commented
@1st1 thank you for sharing your worries.
I'll assign you to the PR.
You will decide, ok?

2020-01-12 13:32 UTC, csabella commented
@1st1, just wondering if there is any update for this idea?  Should the PR be closed so that the discussion can happen on the bug tracker first?  Thanks!

2020-04-15 17:17 UTC, vxgmichel commented
> We need to consider this carefully. Exposing these fields pins the current implementation and might prevent us from evolving it. It's also unclear if it's possible to implement this in PyPy et al

Another way of fixing the issue described in [bpo-32810](https://bugs.python.org/issue32810) without adding extra field names is to expose `async_generator.ag_*` as `async_generator_asend.cr_*` (and `async_generator_athrow.cr_*`), i.e:
- `async_generator_asend.cr_await` -> `async_generator_asend.ags_gen.ag_await`
- `async_generator_asend.cr_code` -> `async_generator_asend.ags_gen.ag_code`
- `async_generator_asend.cr_frame` -> `async_generator_asend.ags_gen.ag_frame`
- `async_generator_asend.cr_running` -> `async_generator_asend.ags_gen.ag_running`
- `async_generator_athrow.cr_await` -> `async_generator_athrow.agt_gen.ag_await`
- `async_generator_athrow.cr_code` -> `async_generator_athrow.agt_gen.ag_code`
- `async_generator_athrow.cr_frame` -> `async_generator_athrow.agt_gen.ag_frame`
- `async_generator_athrow.cr_running` -> `async_generator_athrow.agt_gen.ag_running`

Retrieving the stack can then be implemented by simply walking up the chain of coroutines using `cr_await` and `cr_frame`. This would work transparently whether the stack contains async generators or not.

2022-04-11 23:02 UTC, iritkatriel commented
https://bugs.python.org/issue32810 is closed. What is the status of this PR?

2024-01-05 15:13 UTC, erlend-aasland commented
I'll look into the build failures later; I messed up the merge.

2024-01-05 21:51 UTC, erlend-aasland commented
I fixed the merge conflicts, but the tests are failing all over the place. It looks to me the assumptions in the test in 6024d01ecc129e467b782624baa4eb46a1b8c037 from 2018 won't hold in 2023.

2024-01-10 01:19 UTC, gvanrossum commented
I  am just closing this. In 2018 @1st1 didn't like the idea of exposing these fields. Here we are 6 years later and the only reason we're back looking at this is that someone decided to audit the OP's PRs.

2024-01-10 01:19 UTC, closed without merging