gh-111956: Add thread-safe one-time initialization.
python/cpython pull request #111960
Opened 2023-11-10 15:31 UTC by colesbury

The one-time initialization (`_PyOnceFlag`) is used in two places:

 * `Python/Python-ast.c`
 * `Python/getargs.c`

2023-11-10 15:53 UTC, colesbury commented
@ericsnowcurrently, when you have some time, would you please look at this?

One question: I'm unsure of what `int` value should be used here to indicate an error or success. I have gone with `0=error` and `1=success` here because that requires fewer modifications to the use sites, which already use that convention. I am unsure if `-1=error`, `0=success` would be better.

2023-11-15 21:17 UTC, ericsnowcurrently requested changes
Aside from one small thing, LGTM.

2023-11-15 21:17 UTC, ericsnowcurrently commented on Python/getargs.c
> -    PyThread_acquire_lock(_PyRuntime.getargs.mutex, WAIT_LOCK);
This is the only place we use `_PyRuntime.getargs.mutex`, isn't it.  If so, we could remove it.

2023-11-15 21:43 UTC, ericsnowcurrently commented
> I'm unsure of what int value should be used here to indicate an error or success. I have gone with 0=error and 1=success here because that requires fewer modifications to the use sites, which already use that convention. I am unsure if -1=error, 0=success would be better.

The typical convention in the case of success vs. error is -1 for error and 0 for success.  The 0/1 convention is more for true/false situations.

2023-11-15 21:46 UTC, colesbury commented
@ericsnowcurrently that makes sense. I'll change it to -1=error, 0=success.

2023-11-15 22:37 UTC, colesbury commented
@ericsnowcurrently, I changed the code to use `-1=error` `0=success` and updated `asdl_c.py`/`Python-ast.c`. It ended up being a large change to that file, but fixed one bug where we ignored errors in `init_identifiers` due to a mismatch in return code assumptions.

2023-11-15 23:23 UTC, ericsnowcurrently approved these changes
LGTM

FWIW, I haven't combed through the asdl_c.py changes but would expect the test suite to catch an mistakes in there.  It's also a good sign that you caught the bug in `init_identifiers()`. 😄

2023-11-16 01:18 UTC, ericsnowcurrently commented
I'll merge this in the morning if no one beats me to it.

2023-11-16 19:19 UTC, merged