bpo-28929: Add to Misc/NEWS
python/cpython pull request #112
Opened 2017-02-15 05:09 UTC by Mariatta

Mention bpo-28929 in the Documentation section of:

- What's New in Python 3.7.0 alpha 1?
- What's New in Python 3.6.1 release candidate 1?
- What's New in Python 3.5.4 release candidate 1?

http://bugs.python.org/issue28929

2017-02-15 23:55 UTC, brettcannon requested changes
We typically don't worry about covering NEWS entries more than once in a single copy of the file since it's redundant information at that point; as long as someone reading the release notes in a release can see the news entry _somewhere_ then that's enough.

2017-02-15 23:55 UTC, brettcannon commented on Misc/NEWS
> +- bpo-28929: Link the documentation to its source file on GitHub
Missing a period.

2017-02-15 23:55 UTC, brettcannon commented on Misc/NEWS
> +- bpo-28929: Link the documentation to its source file on GitHub
This is unnecessary as the same bit of information is picked up in the 3.7 release notes.

2017-02-15 23:55 UTC, brettcannon commented on Misc/NEWS
> +What's New in Python 3.5.4 release candidate 1?
This is also unnecessary.

2017-02-16 02:58 UTC, Mariatta commented
Thanks @brettcannon :) 
I removed the unnecessary entries.

2017-02-16 02:59 UTC, Mariatta commented
I suppose it doesn't need backport then. But please re-add the labels if I'm mistaken.

2017-02-16 03:42 UTC, brettcannon commented
You can still backport into the appropriate sections, I'm just saying you don't need it more than once in the file at any one time.

And I'm now on vacation so I'll let someone else approve. 😀

2017-02-16 03:52 UTC, Mariatta commented
Ah ok I think I got it now 😅 Re-added the backport labels. 

Please enjoy your vacation!

2017-02-24 23:10 UTC, brettcannon approved these changes

2017-02-25 02:09 UTC, merged