gh-112071: Make `_random.Random` methods thread-safe in `--disable-gil` builds
python/cpython pull request #112128
Opened 2023-11-15 21:24 UTC by chgnrdv

Fixes #112071
Guard `_random.Random` methods with critical section API locks by using `@critical_section` AC directive

2023-11-15 21:40 UTC, colesbury approved these changes
Thanks @chgnrdv, this LGTM.

@rhettinger, would you be able to review this? This adds `@critical_section` Argument Clinic directives to the methods of `_random.Random`. In `--disable-gil` builds, this acquires/releases the per-object locks around the methods. They are no-ops in the default build.

2023-11-22 13:18 UTC, corona10 requested changes

2023-11-22 13:18 UTC, corona10 commented on Modules/_randommodule.c
> +#include "pycore_critical_section.h"
You don't need to add this header manually since the AC automatically adds it.
Please rebase the branch and rerun the `make clinic`

2023-11-23 19:41 UTC, rhettinger approved these changes

2023-11-28 03:06 UTC, corona10 approved these changes
LGTM (with my own push) cc @colesbury

2023-11-28 03:27 UTC, merged