Remove misleading sentence
python/cpython pull request #11216
Opened 2018-12-18 20:16 UTC by Hawk777

The sentence, “It inherits BufferedReader and BufferedWriter, and
further supports seek() and tell() functionality,” is misleading: it
suggests that BufferedRandom is special in that it is seekable, whereas
BufferedReader and BufferedWriter are not. However, this is not the
case: assuming the underlying raw stream is seekable (which is equally a
requirement of BufferedRandom), then BufferedReader and BufferedWriter
*are* seekable. Remove the misleading sentence.

2019-04-11 15:43 UTC, benjaminp requested changes
I think we still need to say something about `seek` & `tell` otherwise it's not clear what `BufferedRandom` is for at all unless you know what a "random" stream is. We could say `seek` and `tell` *must* be supported.

2019-04-12 04:51 UTC, Hawk777 commented
How about this? I have made the requested changes; please review again.

2019-04-12 15:50 UTC, merged

2019-04-12 15:50 UTC, miss-islington commented
Thanks @Hawk777 for the PR, and @benjaminp for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.7.
🐍🍒⛏🤖

2019-04-12 15:50 UTC, benjaminp commented
Thank you for the PR.