gh-108724: Use _PyTime_GetMonotonicClock() in parking_lot.c
python/cpython pull request #112222
Opened 2023-11-17 22:47 UTC by vstinner

Using a system clock causes issues when it's being updated by the system administrator, NTP, Daylight Saving Time, or anything else. Sadly, on Windows, the monotonic clock resolution is around 15.6 ms.

Example: https://github.com/python/cpython/issues/85876

2023-11-17 22:48 UTC, vstinner commented
@colesbury @ericsnowcurrently: Please don't use the system clock for locks. It causes too many issues. Using a monotonic clock is more reliable. Sadly, on Windows, the monotonic clock has a resolution of 15.6 ms.

2023-11-17 22:58 UTC, colesbury requested changes
We should use the monotonic clock when available, but this change isn't sufficient:

* `sem_timedwait` does not work with CLOCK_MONOTONIC. (Need `sem_clockwait` if available)
* `pthread_cond_t` needs to be initialized with the right attribute

2023-11-17 23:19 UTC, colesbury commented on Python/parking_lot.c
>          err = sem_timedwait(&sema->platform_sem, &ts);
Maybe:

```c
# ifdef HAVE_SEM_CLOCKWAIT
        _PyTime_t deadline = _PyDeadline_Init(timeout);
        _PyTime_AsTimespec_clamp(deadline, &ts);
        err = sem_clockwait(&sema->platform_sem, CLOCK_MONOTONIC, &ts);
# else
        _PyTime_t deadline = _PyTime_Add(_PyTime_GetSystemClock(), timeout);
        _PyTime_AsTimespec_clamp(deadline, &ts);
        err = sem_timedwait(&sema->platform_sem, &ts);
 #endif
```

2023-11-17 23:24 UTC, vstinner commented
Oh. I made a mechanical change to avoid _PyTime_GetSystemClock(). I didn't see that timestamps are passed to existing functions such as pthread_cond_timedwait(). I mark my PR as a draft for now and will try to update it to address Sam's review

2023-12-01 18:26 UTC, closed without merging

2023-12-01 18:26 UTC, vstinner commented
I don't have time to fix my PR right now. I may try again later ;-)

2023-12-01 18:53 UTC, colesbury commented
I wrote it up as an issue so that I don't forget about this and in case someone else wants to tackle it first.

https://github.com/python/cpython/issues/112606