GH-112498 Add heapremove and heapfix
python/cpython pull request #112550
Opened 2023-11-30 11:43 UTC by kristjanvalur

This is an alternative PR to #112497 which adds two functions, heapfix and heapremove. 
This is perhaps better, since the use cases are slightly similar.  heappop becomes a special case of heapremove, and
it corresponds to what golang does in https://pkg.go.dev/container/heap

2025-09-27 18:42 UTC, StanFromIreland requested changes
I think max heaps should have an equivalent API to avoid confusion.

2025-09-27 18:42 UTC, StanFromIreland commented on Doc/library/heapq.rst
> +   .. versionadded:: 3.13
Please change these to `next`

2025-09-27 18:42 UTC, StanFromIreland commented on Doc/library/heapq.rst
> +   If the _callable_ *key* is provided, it will be called for each item
This is restructured text, underscores will not work.

2025-10-09 14:14 UTC, kristjanvalur commented
this PR is two years old, not sure there is any interest in pursuing it.  It was at best lukewarm at the time.

2025-10-24 05:46 UTC, closed without merging