gh-112538: Add internal-only _PyThreadStateImpl "wrapper" for PyThreadState
python/cpython pull request #112560
Opened 2023-11-30 19:03 UTC by colesbury

Every PyThreadState instance is now actually a _PyThreadStateImpl. It is safe to cast from `PyThreadState*` to `_PyThreadStateImpl*` and back. The _PyThreadStateImpl will contain fields that we do not want to expose in the public C API.

* Issue: gh-112538

2023-11-30 19:05 UTC, colesbury commented
To keep the PR small, I haven't added any fields to `_PyThreadStateImpl`. In future PRs, I expect to add free-lists (in `Py_GIL_DISABLED` builds) that are currently per-interpreter.

cc @ericsnowcurrently

2023-12-06 15:05 UTC, colesbury commented
@vstinner, would you be able to review this please?

2023-12-06 23:32 UTC, ericsnowcurrently requested changes
This solution makes sense.  There are only a couple of minor things I'd suggest doing differently.

2023-12-06 23:32 UTC, ericsnowcurrently commented on Python/pystate.c
> +        tstate = &tstate->base.interp->_initial_thread;
\<unrelated to this PR\>

Weird.  Why are we assigning it if we already know its the right value?

2023-12-06 23:32 UTC, ericsnowcurrently commented on Include/internal/pycore_interp.h
> +} _PyThreadStateImpl;
I'd expect this to be in pycore_thread.h or pycore_tstate.h or something.

2023-12-06 23:32 UTC, ericsnowcurrently commented on Python/pystate.c
> +    init_threadstate(&tstate->base, interp, id, whence);
FWIW, I'd expect tstate to passed in as-is.

```c
static void
init_threadstate(_PyThreadStateImpl *_tstate,
                 PyInterpreterState *interp, uint64_t id, int whence)
{
    PyThreadState *tstate = (PyThreadState *)_tstate;
```

2023-12-07 00:20 UTC, colesbury commented on Python/pystate.c
> +        tstate = &tstate->base.interp->_initial_thread;
Hmm, yeah that looks like dead code.

2023-12-07 00:20 UTC, colesbury commented on Include/internal/pycore_interp.h
> +} _PyThreadStateImpl;
`pycore_pystate.h` seemed like the natural place to put it, but the include order doesn't work out: `pycore_pystate.h` -> `pycore_runtime.h` -> `pycore_interp.h`, but `PyInterpreterState` depends on the `_PyThreadStateImpl` definition.

(This wasn't a problem for `PyThreadState` because it's defined earlier in `cpython/pystate.h`.)

We could put it in it's own new header file. Would that be better?

2023-12-07 00:20 UTC, colesbury commented on Python/pystate.c
> +    init_threadstate(&tstate->base, interp, id, whence);
I've changed `init_threadstate` as suggested.

I left `add_threadstate` as-is because the `interp->threads.head` linked list is still typed as `PyThreadState*` and changing one or borth of `tstate` and `next` seemed like it would make things more verbose and less clear. Let me know if you would like me to change it. 
```
add_threadstate(PyInterpreterState *interp, PyThreadState *tstate, PyThreadState *next)
```

2023-12-07 01:17 UTC, ericsnowcurrently commented on Include/internal/pycore_interp.h
> +} _PyThreadStateImpl;
Yeah, that's why I was thinking of pycore_thread.h or pycore_tstate.h.

2023-12-07 01:17 UTC, ericsnowcurrently commented on Python/pystate.c
> +    init_threadstate(&tstate->base, interp, id, whence);
I think you did the right thing.

2023-12-07 18:23 UTC, colesbury commented on Include/internal/pycore_interp.h
> +} _PyThreadStateImpl;
I've moved it to `pycore_tstate.h`

2023-12-07 19:09 UTC, ericsnowcurrently approved these changes
LGTM

2023-12-07 19:11 UTC, merged

2023-12-07 19:12 UTC, ericsnowcurrently commented
Thanks, @colesbury!