gh-112779: Check 1-byte atomics in configure
python/cpython pull request #112819
Opened 2023-12-06 23:49 UTC by colesbury

2023-12-07 20:24 UTC, colesbury commented
See https://gcc.godbolt.org/z/rPbrns6P8:

```
_Py_atomic_add_int8:
        addi    sp,sp,-16
        li      a2,5
        andi    a1,a1,0xff
        sd      ra,8(sp)
        call    __atomic_fetch_add_1
        ld      ra,8(sp)
        slliw   a0,a0,24
        sraiw   a0,a0,24
        addi    sp,sp,16
        jr      ra
```

```
_Py_atomic_add_int64:
        mv      a5,a0
        fence iorw,ow; amoadd.d.aq a0,a1,0(a5)
        ret

```

2023-12-08 01:18 UTC, corona10 commented
I will take a look at this weekend

2023-12-08 10:01 UTC, erlend-aasland approved these changes
Looks good to me.

2023-12-08 14:51 UTC, corona10 requested changes
Overall, it looks good to me.
But would you like to leave a comment why 1-byte atomic checking and 8-byte atomic is checking is needed with compiler version issue?

In the future, we need to know why the check-ing was needed but without comment, it could be easily forgotten.

2023-12-08 16:06 UTC, corona10 approved these changes

2023-12-08 16:31 UTC, merged