bpo-35566: Add links to annotation glossary term
python/cpython pull request #11291
Opened 2018-12-23 01:25 UTC by csabella

https://bugs.python.org/issue35566

2018-12-23 02:31 UTC, rhettinger reviewed
The term annotation in pickletools used in a generic sense rather than the type-annotation sense, so the link is not applicable.

2018-12-23 02:33 UTC, rhettinger requested changes
The term annotation in pickletools used in a generic sense rather than the type-annotation sense, so the link is not applicable.

2018-12-23 18:07 UTC, csabella commented
I have made the requested changes; please review again

Thank you for pointing that out.  I wasn't sure of the usage in pickletools, but I guess I should have realized it wasn't related since the parm was added in 3.2, but typing in 3.5.

2018-12-24 05:08 UTC, rhettinger approved these changes

2018-12-24 05:09 UTC, merged

2018-12-24 05:09 UTC, miss-islington commented
Thanks @csabella for the PR, and @rhettinger for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖