Update webbrowser.py
python/cpython pull request #11327
Opened 2018-12-27 08:35 UTC by shangchihh

Chrome is my favorite web browser, and I want to use it in Windows. Why do not register this browser in the `register_standard_browsers` function? Isn't it "standard"?

2018-12-27 08:35 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-12-27 11:36 UTC, tirkarthi commented
Please open an issue at https://bugs.python.org since this is a non-trivial change. Searching along the lines of webbrowser, windows and Chrome I can find this to be a related issue at https://bugs.python.org/issue8232. Feel free to raise a new one if it's different from the issue.

Thanks

2018-12-27 13:38 UTC, eamanu commented
@tirkarthi  I think that is a good point to discuss. I just created the issue https://bugs.python.org/issue35593

2018-12-27 15:14 UTC, shangchihh commented
@eamanu Thanks.

2018-12-29 03:21 UTC, terryjreedy commented
I have forgotten what 'registering' does, but Chrome is now the most used browser.  It is already registered on Mac: `register("chrome", None, MacOSXOSAScript('chrome'))`.  This suggests to me tha

2018-12-29 14:01 UTC, eamanu commented
> As is, the patch will not register on unix. Should it?
I can prepare this. Or you consider better make this change here?

2019-01-10 00:06 UTC, zooba requested changes
Doesn't work as-is - see my comments on the associated bug.

2019-03-29 21:18 UTC, brettcannon commented
Thanks for the PR, but closing as the CLA has not been signed within the last month. If you do decide to sign the CLA we can re-open this PR.

2019-03-29 21:18 UTC, closed without merging