bpo-28097: IDLE: Add Previous/Next History to Shell menu
python/cpython pull request #11325
Opened 2018-12-26 20:15 UTC by csabella

The first commit adds the entries the menu and the second commit grays out the entries when the shell is initially opened.

Some observations:
* I thought about calling the menu items 'Previous Command' and 'Next Command' instead of using the word 'history'.
* When a shell is restarted, the history isn't cleared.
* Should there be a menu item to clear history on demand?
* The history is always cyclic unless someone edits their config file by hand.  Since it's not on configdialog to set it, I enable both menu entries whenever there is any history (since, when cyclic, there is always a Previous and Next entry).  I think enabling the menu entries when the cyclic flag is False would best be handled at the time cyclic is added the condigdialog.
* I added a new function to editor.py to update the state for the menu items.  Because of this, I changed the recently added code for enabling/disabling the Code Context menu item to use this new function.

2018-12-27 05:46 UTC, ZackerySpytz commented on Lib/idlelib/editor.py
> +        "Update state for menu item at index ."
I don't think there should be a space after "index" (same goes for the docstring of the recently-added `update_menu_label()` just above).

2018-12-27 15:50 UTC, csabella commented on Lib/idlelib/editor.py
> +        "Update state for menu item at index ."
Thanks for catching that!  :-)

2018-12-28 05:01 UTC, terryjreedy requested changes
The current line is part of the wraparound cycle, so the cycle is never empty and the short cuts always 'work' (rather than raising).  So the new menu items should also.  

Please move the typo fix and update_menu_state(), which we *will* need and its use in outwin to a new skip-news PR attached to issue 35555.

The result of both changes would be doc and mainmenu additions and the blurb.

2018-12-28 18:42 UTC, terryjreedy approved these changes

2018-12-28 20:11 UTC, merged

2018-12-28 20:11 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!