GH-113350: Changed the python docs 3.12.1 in logging HOWTO
python/cpython pull request #113424
Opened 2023-12-23 08:34 UTC by vaishnavi192

Fix #113350 - Basic logging tutorial: Confusing matrix and use of word "above"

This Pull Request changes the documentation of  `logging-cookbook.rst` and `logging.rst` from "above" word to required changes.

2023-12-23 10:41 UTC, serhiy-storchaka reviewed
Some lines are extra long. Please split them.

2023-12-23 11:59 UTC, hugovk commented on Doc/howto/logging-cookbook.rst
> +show messages of severity ``ERROR`` and only events of this level and higher severity will be tracked as well as ``INFO`` and
```suggestion
show messages of severity ``ERROR`` and higher, as well as ``INFO`` and
```

And please remove the trailing space at the end of the change in the other file.

2023-12-23 21:51 UTC, vsajip requested changes
I feel that my suggested wording is less clumsy than "this level and higher severity and above".

2023-12-23 21:51 UTC, vsajip commented on Doc/howto/logging-cookbook.rst
> +show messages of severity ``ERROR`` and only events of this level and higher severity will be tracked as well as ``INFO`` and
Would prefer the wording "only events of this severity and higher will  be tracked" here.

2023-12-23 21:51 UTC, vsajip commented on Doc/howto/logging.rst
> +The default level is ``WARNING``, which means that only events of this level and higher severity and above will be tracked,
Would prefer the wording "only events of this severity and higher will be tracked" here.

2023-12-26 11:54 UTC, vaishnavi192 commented
okay yeah! I will do changes today itself!   sorry for replying late my laptop got into some trouble.

2023-12-26 11:58 UTC, hugovk commented
Please could you also edit the PR title to be more descriptive?

2023-12-26 17:27 UTC, vaishnavi192 commented
I have made the requested changes; please review again

2023-12-26 18:36 UTC, hugovk commented
@vaishnavi192 Remember to `git push` your changes.

2023-12-27 08:03 UTC, hugovk commented
Closing as a duplicate if https://github.com/python/cpython/pull/113491.

2023-12-27 08:03 UTC, closed without merging

2023-12-27 10:54 UTC, vaishnavi192 commented
@hugovk just wanted to confirm the issue is solved right?

2023-12-27 10:58 UTC, hugovk commented
Yes, it's solved now, and the issue is closed: https://github.com/python/cpython/issues/113350

What happened:

* You made this first PR from your `main` branch
* You then made updates in another `documentation` branch and made a second PR

Next time, I recommend making a new branch, and a PR from that branch, and avoid making any changes directly to your `main`.

Thank you for your contribution!

2023-12-27 11:02 UTC, vaishnavi192 commented
Okay got it! Thank you @hugovk for being so welcoming to new contributors. It helps a lot!......Looking forward to contribute more in Python.😄