gh-58211 Add builtins callables tests
python/cpython pull request #113575
Opened 2023-12-29 20:43 UTC by adorilson

Although there was an inconclusive discussion in #58211, this PR adds tests to `__self__` in built-in callables as it work currently.

2024-01-01 15:25 UTC, AlexWaygood reviewed
This appears to me to go in the opposite direction to the consensus in #58211 -- the consensus seems to me to be that this is a misfeature that could only be confusing. That doesn't mean that we should necessarily bother changing the current behaviour unless it's actually causing a bug for somebody. But we should only add tests for things which are working in a desirable way currently -- we shouldn't cement undesirable behaviour by adding tests for it.

I'm therefore doubtful that this PR is a good idea. Instead, I think we should fix the documentation so that it is more vague about what the value of this attribute might be for builtin functions.

2024-01-01 18:57 UTC, adorilson commented
> we shouldn't cement undesirable behaviour by adding tests for it.

Yes, I agree. (Although I'm the PR author). The big problem is where desirable behaviour is defined.
I found a PEP concern about this but didn't find it. Do you know if it exists?

Furthermore, ignoring other necessary knowledge, I think of the `self` as the member's owner. So, thinking about the module as the built-in functions' owner was natural. 

> 
> I'm therefore doubtful that this PR is a good idea. Instead, as I suggested in [#113574 (comment)](https://github.com/python/cpython/pull/113574#issuecomment-1873004124), I think we should fix the documentation so that it is more vague about what the value of this attribute might be for builtin functions.

I don't know if this is a good idea. I guess not.

Maybe it is better to remove this attribute from the documentation. Seeing the [Terry's comment](https://github.com/python/cpython/issues/58211#issuecomment-1093570089), the bug is not only the `__self__` value but their own existence. In this sense, we already have been cementing undesirable behaviour.

2024-01-01 20:03 UTC, serhiy-storchaka commented
There is a code in `inspect` or `pydoc` to work around this "feature". There may be a third-party code or even code in the stdlib that depends on this feature. If we even change this in future, it is better to have explicit tests that will fail, so this change will not pass unnoticed as a side effect of other changes. We can make these tests running only on CPython, and add comments explaining this.

2024-01-01 20:53 UTC, adorilson commented
> If we even change this in future, it is better to have explicit tests that will fail, so this change will not pass unnoticed as a side effect of other changes. We can make these tests running only on CPython, and add comments explaining this.

Do you mean:

1. Considering this PR
2. Keeping in documentation `__self__ is set to None` (because it is the desirable behaviour)
3. Adding in documentation a `impl-detail` directive: Currently, CPython returns the module object where the built-in function is defined, but it can change in the future.

?

2024-01-02 09:56 UTC, serhiy-storchaka commented
I meant considering this PR.

2025-01-03 14:25 UTC, AlexWaygood requested changes
@adorilson, if you make @serhiy-storchaka's suggested changes, then we can consider merging this:

> We can make these tests running only on CPython, and add comments explaining this.

We have a `test.support.cpython_only` decorator for tests that are only meant to run if the implementation is CPython.

2025-03-16 17:57 UTC, adorilson commented
I have made the requested changes; please review again

I've added the `test.support.cpython_only`.

Regarding the comment explaining it, I put a 'See gh-58211' only. Is it enough?

2025-03-16 18:04 UTC, picnixz commented on Lib/test/test_funcattrs.py
> +    def test_builtin__self__(self):
```suggestion
    @support.cpython_only
    def test_builtin__self__(self):
        # See https://github.com/python/cpython/issues/58211.
```

2025-03-16 18:04 UTC, picnixz commented on Lib/test/test_funcattrs.py
> +        import builtins
Are those imports local for testing or can they be made global? btw, whether they are made global or not, can you order them? (import builtins before time)

2025-03-16 18:05 UTC, picnixz commented on Lib/test/test_funcattrs.py
> +    def test_builtin__self__(self):
If this is not sufficient, a summary of the discussion can be added (but not using docstrings as it would be present in case of failure).

2025-03-16 19:49 UTC, adorilson commented on Lib/test/test_funcattrs.py
> +        import builtins
They can be global. I only copied the style from the test before this new one.

2025-03-30 12:28 UTC, picnixz commented on Lib/test/test_funcattrs.py
> +        import builtins
Fine to keep them local but just for readability, I would swap the imports so that they are alphabetically sorted.

2025-04-10 10:35 UTC, skirpichev approved these changes

2025-04-10 10:54 UTC, serhiy-storchaka commented on Lib/test/test_funcattrs.py
> +        self.assertEqual(len.__self__, builtins)
Use more strict assertion `assertIs` where it is possible.

2025-04-10 10:54 UTC, serhiy-storchaka commented on Lib/test/test_funcattrs.py
> +        self.assertEqual(str.maketrans.__self__, None)
Use `assertIsNone` here.

2025-04-10 10:54 UTC, serhiy-storchaka commented on Lib/test/test_funcattrs.py
> +        self.assertEqual([1, 2, 3].append.__self__, [1, 2, 3])
Save the instance as a variable and use `assertIs`.

2025-04-10 10:54 UTC, serhiy-storchaka commented on Lib/test/test_funcattrs.py
> +
Add also a test for the `None` bound method, for example, `None.__repr__.__self__`.

2025-04-10 15:17 UTC, adorilson commented on Lib/test/test_funcattrs.py
> +        self.assertEqual(len.__self__, builtins)
I'll do that.

But concerning the imports, should I keep locally or put globally?

2025-04-10 15:41 UTC, serhiy-storchaka commented on Lib/test/test_funcattrs.py
> +        self.assertEqual(len.__self__, builtins)
Either is fine. Thanks.

2025-04-10 22:47 UTC, adorilson commented on Lib/test/test_funcattrs.py
> +
What if we test for all built-in constants? I've done that.

2025-04-10 22:48 UTC, adorilson commented
I have made the requested changes; please review again

2025-04-11 01:33 UTC, skirpichev approved these changes

2025-04-11 10:20 UTC, serhiy-storchaka commented on Lib/test/test_funcattrs.py
> +        self.assertIs(d.__repr__.__self__, d)
`None` is the only interesting case here, because `__self__` is `None` only for static methods and for bound methds of `None`.
```suggestion
        self.assertIsNone(None.__repr__.__self__)
```
All other tests are redundant.

2025-04-11 11:29 UTC, serhiy-storchaka approved these changes
LGTM.

2025-04-12 11:38 UTC, picnixz approved these changes

2025-04-12 12:02 UTC, merged