Allow passing PathLike arguments to SimpleHTTPRequestHandler
python/cpython pull request #11398
Opened 2019-01-02 00:03 UTC by maggyero

2019-01-02 09:36 UTC, tirkarthi commented
Please raise an issue in https://bugs.python.org for this PR to discuss this since it's a non-trivial change and would require tests.

2019-01-02 12:54 UTC, eamanu commented
This seems a interest. I open a issue https://bugs.python.org/issue35640 to discuss this @tirkarthi  @maggyero

2019-01-02 12:55 UTC, eamanu approved these changes
LGTM. @maggyero Maybe you will need some Exception control.

2019-03-15 21:55 UTC, JulienPalard commented
Hi @maggyero thanks for the PR!

Could you also provide a `.. versionchanged::` in the documentation to tell about it, and a test?

2019-03-17 00:25 UTC, maggyero commented
> Could you also provide a `.. versionchanged::` in the documentation to tell about it, and a test?

@JulienPalard Yes, done.

2019-03-17 01:40 UTC, maggyero commented
> Could you also provide a `.. versionchanged::` in the documentation to tell about it, and a test?

@JulienPalard Yes, done.

2019-06-14 15:17 UTC, maggyero commented
@JulienPalard Up.

2019-08-06 20:46 UTC, maggyero commented
@JulienPalard I have made the requested changes. Please review again.

2019-08-20 06:22 UTC, maggyero commented
@JulienPalard

2019-09-03 13:12 UTC, maggyero commented
@JulienPalard I have made the requested changes. Please review again.

2019-09-10 11:13 UTC, zware commented
@maggyero Could you add a NEWS entry for this change?

2019-09-10 14:01 UTC, maggyero commented
@zware Yes, done!

2019-09-11 10:40 UTC, zware requested changes
One last thing that I'll commit myself if GitHub lets me, otherwise LGTM.

2019-09-11 10:40 UTC, zware commented on Doc/library/http.server.rst
> +      .. versionchanged:: 3.7
```suggestion
      .. versionchanged:: 3.9
```

2019-09-11 10:50 UTC, zware commented on Doc/library/http.server.rst
> +      .. versionchanged:: 3.7
It looks like GitHub won't let me commit this myself :)

2019-09-11 12:36 UTC, maggyero commented on Doc/library/http.server.rst
> +      .. versionchanged:: 3.7
Done, thanks!

2019-09-11 12:37 UTC, maggyero commented
I have made the requested changes; please review again.

2019-09-11 12:44 UTC, zware approved these changes
LGTM!

2019-09-11 13:03 UTC, merged

2019-09-11 13:05 UTC, zware commented
Thanks for the patch, @maggyero!

2019-09-11 13:11 UTC, maggyero commented
Thanks for the review @zware!