Fix bpo-35641: IDLE: calltips not properly formatted for functions without doc-strings
python/cpython pull request #11415
Opened 2019-01-02 19:43 UTC by eamanu

bpo-35641: IDLE: calltips not properly formatted for functions without doc-strings

2019-01-02 19:52 UTC, taleinat requested changes
Other than my inline comment, two more things:

1. Add a test for this bug. It should fail without the fix and pass with the fix.
2. Add a NEWS entry. The easiest way to do so is to follow the "Details" link next to the failing "bedevere/news" check near the bottom of this page, which will lead you to the "blurb-it" tool.

2019-01-02 19:52 UTC, taleinat commented on Lib/idlelib/calltip.py
> +    print(lines)
This needs to be removed.

2019-01-02 19:53 UTC, remilapeyre requested changes
Thanks for your contribution!

When you write a commit message, make it more descriptive about what the commit does, it's very important when diving into git log, here are some tips about commit messages: https://devguide.python.org/pullrequest/#making-good-commits

You need to use `blurb add` or create manually an entry to `Misc/NEWS`.

Please add some test to your pull request :)

2019-01-02 19:53 UTC, remilapeyre commented on Lib/idlelib/calltip.py
> +    print(lines)
You forgot a debug statement.

2019-01-02 20:03 UTC, eamanu commented on Lib/idlelib/calltip.py
> +    print(lines)
holy .....  sorry!!!

2019-01-02 20:03 UTC, terryjreedy commented on Lib/idlelib/calltip.py
> +    print(lines)
```suggestion
```

2019-01-02 20:13 UTC, eamanu commented
Thanks for your comments. I will push tests

2019-01-02 20:15 UTC, terryjreedy commented on Lib/idlelib/calltip.py
> +    print(lines)
When I hit Commit suggestion, GitHub said "Not authorized to edit …"  even though I am, and did with pencil icon.  I gave them feedback.

2019-01-02 20:16 UTC, terryjreedy commented on Lib/idlelib/calltip.py
> +    print(lines)
I did it with pencil edit.

2019-01-02 20:21 UTC, terryjreedy requested changes
What tal said.  Add at least one test *and* a blurb file.  I will likely edit whatever you write before merging, so don't agonize over the wording.  But with a file, I can do so in the online pencil editor.

2019-01-03 06:07 UTC, terryjreedy approved these changes

2019-01-03 06:10 UTC, terryjreedy commented
Tal, since our change requests were identical, I will merge this when CI passes.

2019-01-03 07:47 UTC, merged

2019-01-03 07:48 UTC, miss-islington commented
Thanks @eamanu for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-01-03 10:08 UTC, miss-islington commented
Thanks @eamanu for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-01-03 10:08 UTC, miss-islington commented
Sorry, @eamanu and @terryjreedy, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker ab54b9a130c88f708077c2ef6c4963b632c132b3 3.7
                                ```

2019-01-03 10:12 UTC, miss-islington commented
Thanks @eamanu for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2019-01-03 10:12 UTC, miss-islington commented
Sorry, @eamanu and @terryjreedy, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker ab54b9a130c88f708077c2ef6c4963b632c132b3 3.7
                                ```

2019-01-03 11:16 UTC, taleinat commented
Sorry for the noise; both Terry and I added the "needs backport to 3.7", which caused the second backport attempt to fail.

2019-01-03 18:14 UTC, terryjreedy commented
Better than neither of us ;-).  Part of the problem was that the robots + GitHub were *really* slow in posting anything, so I removed and re-added the label after the backport has been done.

2019-01-09 15:38 UTC, terryjreedy commented
I just noticed that the blurb was put in the Library directory instead of the Idle directory.  #11479 moves it.