gh-114490: Add check for Mach-O linkage in Lib/platform.py
python/cpython pull request #114491
Opened 2024-01-23 15:56 UTC by aidenfoxivey

<https://github.com/python/cpython/issues/114490>

2024-01-23 15:57 UTC, aidenfoxivey commented
Could be wrong here, but this seems like a minor enough change that no news is needed.

2024-01-23 16:05 UTC, ronaldoussoren requested changes
The change itself LGTM.

I would prefer a news entry though, adding it is easy enough and does show users that something changed here.

2024-01-23 16:09 UTC, ronaldoussoren commented
BTW. Normally I'd ask for a test as well, but this function is mostly untested at the moment and adding a test for just the linkage on macOS feels wrong to me.

2024-01-23 16:26 UTC, aidenfoxivey commented
> The change itself LGTM.
> 
> I would prefer a news entry though, adding it is easy enough and does show users that something changed here.

Sounds good! I'll set it right up.

2024-01-23 16:26 UTC, aidenfoxivey commented
> BTW. Normally I'd ask for a test as well, but this function is mostly untested at the moment and adding a test for just the linkage on macOS feels wrong to me.

Oh, so it would be helpful to add some tests for this function?

2024-01-23 16:36 UTC, aidenfoxivey commented
I have made the requested changes; please review again

2024-01-23 18:47 UTC, ronaldoussoren commented
> > BTW. Normally I'd ask for a test as well, but this function is mostly untested at the moment and adding a test for just the linkage on macOS feels wrong to me.
> 
> Oh, so it would be helpful to add some tests for this function?

I'm personally not that bothered by not having tests for this function, but better test coverage can help avoiding regressions in the future.

AFAIK the only tests for this function are here:

https://github.com/python/cpython/blob/441affc9e7f419ef0b68f734505fa2f79fe653c7/Lib/test/test_platform.py#L78-L86

Tests will inherently have platform specifics in them, for other functions in `platform` the tests themselves are cross-platform by mocking functions used the test. For `platform.architecture` just mocking `_syscmd_file` should be good enough. This does require access to a number of platforms to collect data though.

2024-01-23 18:49 UTC, ronaldoussoren requested changes
The linting job found a formatting niggle in the news entry, see the suggested change below.

With that change the PR is good to go.

2024-01-23 18:49 UTC, ronaldoussoren commented on Misc/NEWS.d/next/macOS/2024-01-23-11-35-26.gh-issue-114490.FrQOQ0.rst
> +Add Mach-O linkage support for `platform.architecture()`
```suggestion
Add Mach-O linkage support for :func`platform.architecture()`
```

This fixes the error in the lint job

2024-01-23 19:17 UTC, aidenfoxivey commented
I have made the requested changes; please review again

2024-01-25 16:03 UTC, aisk commented on Misc/NEWS.d/next/macOS/2024-01-23-11-35-26.gh-issue-114490.FrQOQ0.rst
> +Add Mach-O linkage support for :func:`platform.architecture()`
```suggestion
Add Mach-O linkage support for :func:`platform.architecture()`.
```

2024-01-25 16:28 UTC, aidenfoxivey commented on Misc/NEWS.d/next/macOS/2024-01-23-11-35-26.gh-issue-114490.FrQOQ0.rst
> +Add Mach-O linkage support for :func:`platform.architecture()`
Awesome, thank you. :)

2024-01-26 19:54 UTC, ronaldoussoren approved these changes
LGTM

2024-01-26 20:36 UTC, merged

2024-01-26 20:37 UTC, ronaldoussoren commented
@aidenfoxivey, thanks for your PR!