bpo-35283: Add a _DummyThread.isAlive alias and a deprecated msg.
python/cpython pull request #11454
Opened 2019-01-07 08:18 UTC by corona10

2019-01-07 09:07 UTC, corona10 commented
@asvetlov

Hi, Can you take a look, please?

2019-01-07 13:00 UTC, eamanu approved these changes
LGTM

2019-01-07 13:00 UTC, eamanu commented on Lib/test/test_threading.py
> +        t.is_alive()
IMO if the name of test case is  `test_old_threading_api(self)` I think that `t.is_alive()` must be deleted because this is not a old api.

2019-01-07 15:21 UTC, corona10 commented
@eamanu Done thanks!

2019-01-16 11:02 UTC, corona10 commented
@vstinner Hi, Could you review this PR, please?

2019-01-16 11:43 UTC, vstinner reviewed
Please document the deprecation at https://docs.python.org/dev/whatsnew/3.8.html#deprecated : Doc/whatsnew/3.8.rst file.

Strange. I cannot see isAlive() is https://docs.python.org/dev/library/threading.html Should we document it... just to say that it's deprecated?

2019-01-16 11:43 UTC, vstinner commented on Lib/threading.py
> +        This instance method is deprecated, use is_alive() instead.
```suggestion
        This method is deprecated, use is_alive() instead.
```

2019-01-16 12:22 UTC, asvetlov commented
I believe `isAlive()` was removed from docs as a part of depreciation already.
Docs for Python 2.7 mentions the method but 3.5 doesn't.
I don't recall when the method dropped removed.
From my perspective, we don't need touching docs.

2019-01-16 12:22 UTC, asvetlov approved these changes

2019-01-16 13:49 UTC, corona10 commented
@asvetlov @vstinner 

Hi, Thank you for fast feedback!
I've updated the PR! Please take a look, please! Thanks!

2019-01-16 14:24 UTC, vstinner requested changes
test_threading.test_old_threading_api() currently fails with -Werror:

```
vstinner@apu$ ./python -W error -m test -v test_threading -m test_old_threading_api
ERROR: test_old_threading_api (test.test_threading.ThreadTests)
```

You have to move the isAlive() call inside something like:

```
with self.assertWarnsRegex(DeprecationWarning, 'should be'):
```

2019-01-16 15:09 UTC, corona10 commented
@vstinner 
I' ve updated the unit test code also support.start_threads API to use `is_alive` to prevent the same issue as you mentioned. (e.g test_threaded_import)

2019-01-17 03:40 UTC, corona10 commented
I have made the requested changes; please review again

2019-01-17 09:34 UTC, vstinner approved these changes
LGTM, but can you please enhance the documentation formatting as requested? So I can merge your change.

2019-01-17 09:34 UTC, vstinner commented on Doc/whatsnew/3.8.rst
> +* The :meth:`~isAlive()` method of :class:`threading.Thread` has been deprecated.
If you add "threading.Thread" to isAlive(), it's still displayed as "isAlive()" but the link can be clicked :-)

```suggestion
* The :meth:`~threading.Thread.isAlive()` method of :class:`threading.Thread` has been deprecated.
```

2019-01-17 09:34 UTC, vstinner commented on Doc/whatsnew/3.8.rst
> +
Please remove this empty line, so both setences can be rendered on the same line.

2019-01-17 09:34 UTC, vstinner commented on Misc/NEWS.d/next/Library/2019-01-07-17-17-16.bpo-35283.WClosC.rst
> +Add a deprecated warning for the threading.Thread.isAlive.
```suggestion
Add a deprecated warning for the :meth:`threading.Thread.isAlive` method.
```

2019-01-17 11:18 UTC, corona10 commented
@vstinner 
I 've enhanced the PR as your request! 
Thanks always

2019-01-17 12:14 UTC, merged

2019-01-17 12:14 UTC, vstinner commented
Thanks! I merged your PR.