gh-114494: Change logging docstring to bool for exec_info
python/cpython pull request #114558
Opened 2024-01-25 15:55 UTC by tristanpank

2024-01-25 17:18 UTC, sunmy2019 commented on Misc/NEWS.d/next/Documentation/2024-01-25-15-58-31.gh-issue-114494.sgtopX.rst
> +I updated the logging docstring to use bool instead of integer parameters for exec_info. Originally, it was written as exec_info=1 in 6 places, which I changed to exec_info=True.
Don't state what you have done. State what change is affecting the user.

Example:
Minor fixes for ``logging`` docstring.

2024-01-25 17:19 UTC, sunmy2019 commented
NEWS should state what you want the user to know, **not how you solved the problem.**

But this fix is too trivial so I am gonna let you skip this NEWS.

2024-01-25 17:20 UTC, sunmy2019 requested changes

2024-01-25 17:20 UTC, sunmy2019 commented on Misc/NEWS.d/next/Documentation/2024-01-25-15-58-31.gh-issue-114494.sgtopX.rst
> +I updated the logging docstring to use bool instead of integer parameters for exec_info. Originally, it was written as exec_info=1 in 6 places, which I changed to exec_info=True.
remove this NEWS

2024-01-26 12:06 UTC, serhiy-storchaka approved these changes

2024-01-26 19:40 UTC, vsajip approved these changes

2024-01-26 19:48 UTC, merged