gh-108303: Remove `Lib/test/sortperf.py`
python/cpython pull request #114687
Opened 2024-01-28 20:18 UTC by sobolevn

@corona10 what do you think about moving these case to `pyperformance`? Would it be benefitial?

2024-01-29 15:35 UTC, sobolevn commented
It was Guido 27 years ago: https://github.com/python/cpython/commits/main/Lib/test/sortperf.py

I think he agreed on moving it away in Discord's #python-dev channel.

2024-01-29 17:20 UTC, corona10 requested changes
IMO, the First thing we have to do is add the benchmark script, not remove the file.

2024-01-29 19:04 UTC, sobolevn commented
@corona10 ok, I will send a PR to pyperformance soon! 👍

2024-02-09 14:23 UTC, corona10 reviewed
Even if we just move the script into Tools/script 
IMO pyperf based script is more modernized way and easy to compare with improvement patch. WDYT?

2024-02-09 14:37 UTC, sobolevn commented
I agree with Guido: it is not really that useful as a benchmark (since it is a micro-benchmark). It is only interesting when working on `list.sort` directly. 

So, I think that we can move this file for now. If someone has a real use-case for `list.sort` benchmark in `pyperf`, they can recreate my existing closed PR.

2024-02-10 06:04 UTC, corona10 commented
> So, I think that we can move this file for now. If someone has a real use-case for list.sort benchmark in pyperf, they can recreate my existing closed PR.

Ah, I meant rewriting the benchmark script based on pyperf(you already did) and storing it Tools/script/
I also agree with Guido.

2024-02-10 09:28 UTC, sobolevn commented
@corona10 sure!

2024-02-11 12:28 UTC, corona10 commented
I will take a look at the PR by tomorrow :)

2024-02-12 12:49 UTC, corona10 requested changes
1. By default, all benchmark should be executed.
2. Benchmarks needs some tune up
```
.....................
list_sort: Mean +- std dev: 30.8 ms +- 0.4 ms
.....................
list_sort_ascending: Mean +- std dev: 1.76 ms +- 0.10 ms
```

Too slow :)

2024-02-12 12:49 UTC, corona10 commented on Tools/scripts/sortperf.py
> +    cmd.append(args.benchmark)
```suggestion
def add_cmdline_args(cmd: list[str], args) -> None:
    if args.benchmark:
        cmd.append(args.benchmark)
```

2024-02-12 12:49 UTC, corona10 commented on Tools/scripts/sortperf.py
> +        default="list_sort",
```suggestion
```

2024-02-12 12:49 UTC, corona10 commented on Tools/scripts/sortperf.py
> +    runner.bench_time_func(args.benchmark, benchmark.run)
```suggestion
    if args.benchmark:
        benchmarks = (args.benchmark,)
    else:
        benchmarks = sorted(BENCHMARKS)
    for bench in benchmarks:
        benchmark = Benchmark(bench, args.size, args.rng_seed)
        runner.bench_time_func(bench, benchmark.run)
```

2024-02-15 09:05 UTC, sobolevn commented
@corona10 I've merged your suggestions. Thank you!

I've also optimized the benchmark:

```
» time python Tools/scripts/sortperf.py  
.....................
list_sort: Mean +- std dev: 29.0 us +- 0.2 us
.....................
list_sort_ascending: Mean +- std dev: 28.9 us +- 0.4 us
.....................
list_sort_ascending_exchanged: Mean +- std dev: 29.2 us +- 0.4 us
.....................
list_sort_ascending_one_percent: Mean +- std dev: 29.5 us +- 0.2 us
.....................
list_sort_ascending_random: Mean +- std dev: 29.6 us +- 0.3 us
.....................
list_sort_descending: Mean +- std dev: 29.5 us +- 0.2 us
.....................
list_sort_duplicates: Mean +- std dev: 30.4 us +- 1.1 us
.....................
list_sort_equal: Mean +- std dev: 29.2 us +- 0.2 us
.....................
list_sort_worst_case: Mean +- std dev: 29.2 us +- 0.2 us
python Tools/scripts/sortperf.py  98.38s user 3.21s system 99% cpu 1:41.75 total
```

Is it good enough?

2024-02-17 12:55 UTC, corona10 approved these changes
LGTM

@sobolevn Feel free to merge the PR anytime!

2024-02-18 07:25 UTC, sobolevn commented
@corona10 Thank you! 🎉 


I think that we also need to backport this to 3.11 and 3.12
Do you agree?

2024-02-18 07:25 UTC, corona10 commented
Yeah go a head

2024-02-18 07:27 UTC, merged