gh-101100: Fix sphinx warnings in `library/enum.rst`
python/cpython pull request #114696
Opened 2024-01-29 06:37 UTC by sobolevn

Before:

```
/Users/sobolev/Desktop/cpython2/Doc/library/enum.rst:798: WARNING: py:attr reference target not found: Enum._name_
/Users/sobolev/Desktop/cpython2/Doc/library/enum.rst:799: WARNING: py:attr reference target not found: Enum._value_
/Users/sobolev/Desktop/cpython2/Doc/library/enum.rst:805: WARNING: py:attr reference target not found: Enum._order_
```

It renders just fine:
<img width="820" alt="Снимок экрана 2024-01-29 в 09 34 09" src="https://github.com/python/cpython/assets/4660275/718e0b85-47ce-45fc-9c20-cf63c70ded6c">

I though that I can possibly define these attributes in-place, but their rendering would be very strange this way. So, I went with a little duplication.

2024-01-31 16:26 UTC, hugovk commented
Technically looks okay, but let's check with @ethanfurman: if the whole point of `_order_` is for Python 2/3 consistency, do we need to keep that detail in the docs?

2024-02-08 22:08 UTC, ethanfurman requested changes
A minor change, then good to go!

2024-02-08 22:08 UTC, ethanfurman commented on Doc/library/enum.rst
> +      Used to ensure member order is consistent
```suggestion
      No longer used, kept for backward compatibility.
```

2024-02-08 22:08 UTC, ethanfurman commented on Doc/library/enum.rst
>    consistent (class attribute, removed during class creation)
```suggestion
- :attr:`~Enum._order_` -- no longer used, kept for backward
  compatibility (class attribute, removed during class creation)
```

2024-02-09 02:52 UTC, ethanfurman approved these changes

2024-02-09 06:40 UTC, merged

2024-02-09 10:17 UTC, sobolevn commented
I will send backports PRs later 👍