gh-114667: Support hexadecimal floating point literals
python/cpython pull request #114668
Opened 2024-01-28 05:19 UTC by skirpichev

This add hexadecimal floating point literals (IEEE 754-2008 §5.12.3) and support construction of floats from hexadecimal strings.  Note that the syntax is more permissive: everything that is currently accepted by the float.fromhex, but with a mandatory base specifier; it also allows grouping digits with underscores.

Examples:
```pycon
>>> 0x1.1p-1
0.53125
>>> float('0x1.1')
1.0625
>>> 0x1.1
1.0625
>>> 0x1.1_1_1
1.066650390625
```

Minor changes:
* Py_ISDIGIT/ISXDIGIT macros were transformed to functions

2024-04-02 07:00 UTC, skirpichev commented
Now it is ready for review.  The second commit should clear syntax incompatibility wrt access to public attributes on hexadecimal integer literals, e.g. ``0x1.to_bytes``.

One note for reviewers (also valid for #113805, but more relevant here): do we still support non-IEEE 754 platforms?  Build requirements [claims](https://docs.python.org/3.13/using/configure.html#build-requirements): "Support for [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) floating point numbers and [floating point Not-a-Number (NaN)](https://en.wikipedia.org/wiki/NaN#Floating_point)." is required.

The current pr has special case, using the system ``strtod()`` if ``_PY_SHORT_FLOAT_REPR == 0``.  This was tested locally on IEEE system.  But will this be tested by some CPython's build bot (hardly it's tested by regular GA checks)?  More generally, is there reasons (after 10+ years) to not use system's ``strtod()`` (in C locale) to do hard work?

2024-04-02 10:40 UTC, pablogsal requested changes
This needs a PEP accepted

2024-04-02 13:46 UTC, skirpichev commented
PEP Draft and pr were updated to match each other.   I'll convert this to a draft if this will touch some new files.

2024-12-12 08:22 UTC, skirpichev commented on Doc/library/functions.rst
> +   .. versionchanged:: 3.14
```suggestion
   .. versionchanged:: next
```

2024-12-12 08:22 UTC, skirpichev commented on Doc/reference/lexical_analysis.rst
> +.. versionchanged:: 3.14
```suggestion
.. versionchanged:: next
```

2025-04-12 10:09 UTC, closed without merging