gh-111968: Refactor _PyXXX_Fini to follow Eric's suggestion
python/cpython pull request #114899
Opened 2024-02-02 10:13 UTC by corona10

2024-02-02 10:39 UTC, corona10 commented
Address by @ericsnowcurrently 's and @colesbury 's review from https://github.com/python/cpython/issues/111968#issuecomment-1922247135

2024-02-02 18:07 UTC, colesbury reviewed
This looks good to me, although I'd probably name `PySlice_ClearCache` like the other freelist clearing functions for consistency.

2024-02-02 18:07 UTC, colesbury commented on Include/internal/pycore_gc.h
> +extern void _PySlice_ClearCache(_PyFreeListState *state, int is_finalization);
I would name this like the other functions `_PySlice_ClearFreeList`

2024-02-02 23:13 UTC, ericsnowcurrently requested changes
Thanks for doing this.  It mostly looks okay to me.  There are just a few small things I'd like you to consider.

2024-02-02 23:13 UTC, ericsnowcurrently commented on Python/pystate.c
> +_PyObject_ClearFreeLists(_PyFreeListState *state, int is_finalization)
FWIW, it seems odd to me that `_PyObject_ClearFreeLists()` is implemented in pystate.c.  I'd expect it in Objects/object.c.  It isn't critical, but consider moving it there.

2024-02-02 23:13 UTC, ericsnowcurrently commented on Python/pystate.c
>      _PyFreeListState *freelist_state = &((_PyThreadStateImpl*)tstate)->freelist_state;
```suggestion
    _PyFreeListState *freelist_state = _PyFreeListState_GET();
```

2024-02-02 23:13 UTC, ericsnowcurrently commented on Include/internal/pycore_gc.h
>  extern void _PyContext_ClearFreeList(_PyFreeListState *state, int is_finalization);
FWIW, I personally would put these function declarations in the respective type-specific header files, e.g. `_PyTuple_ClearFreeList()` in pycore_tuple.h.  That's the first place I'd think to look for a type-specific declaration like this.  The second place I'd look is pycore_freelist.h.  I would not think to look for it in pycore_gc.h.

2024-02-03 09:19 UTC, corona10 commented on Include/internal/pycore_freelist.h
> +extern void _PyObject_ClearFreeLists(_PyFreeListState *state, int is_finalization);
Since this API is not a domain-specific API, I located all ClearFreeList API into here :)

2024-02-03 09:51 UTC, corona10 commented
I have made the requested changes; please review again

2024-02-03 10:26 UTC, corona10 commented
As I commented before, we need some header cleanup, but I will do it as a separate PR since it affected a lot of codes, including `bytecodes.c`

2024-02-08 23:06 UTC, corona10 commented
@ericsnowcurrently gentle ping

2024-02-09 16:31 UTC, ericsnowcurrently approved these changes
LGTM

2024-02-10 00:57 UTC, merged