bpo-35045: Fix test_ssl.test_min_max_version()
python/cpython pull request #11508
Opened 2019-01-10 17:05 UTC by vstinner

test_ssl.test_min_max_version() no longer tests the default
minimum_version: it depends on the OpenSSL configuration, it is not
always equal to TLSVersion.MINIMUM_SUPPORTED.

2019-01-10 17:06 UTC, vstinner commented
cc @stratakis

2019-01-10 17:11 UTC, tiran requested changes
-1

Fedora's crypto policy modifies the settings. You have to disable the crypto policy for your test session.

2019-01-10 17:13 UTC, hroncok commented
can we change the environment variable as part of the tests instead?

2019-01-10 17:14 UTC, tiran commented
Yes, that's my plan. I'm working on a PR right now.

2019-01-10 17:41 UTC, hroncok commented
```python3
script = '''
import ssl
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
print(ctx.minimum_version)
'''

proc = subprocess.run([sys.executable, '-c', script],
                      capture_output=True,
                      text=True,
                      check=True,
                      env={**os.environ, 'OPENSSL_CONF': '/non-existing-file'})
assert proc.stdout.strip() == 'TLSVersion.MINIMUM_SUPPORTED'
```

2019-01-10 17:44 UTC, vstinner commented
11 lines of code just to test the default value of an OpenSSL constant, is it really worth it? Well, I rely on @tiran for ssl changes :-)

2019-01-15 12:39 UTC, vstinner commented
> Yes, that's my plan. I'm working on a PR right now.

If nobody comes with a better fix for this test on Fedora, I will merge this change at the end of the week.

Note: Even if I merge my change, it i will be trivial to revert my change later for a better solution ;-)

2019-01-15 13:08 UTC, hroncok commented
@vstinner IIRC there is another PR open by @tiran for this.

2019-01-15 14:00 UTC, vstinner commented
> @vstinner IIRC there is another PR open by @tiran for this.

Oh, I missed the PR #11510. Thanks.

2019-01-15 14:02 UTC, vstinner commented
I abandon my PR in favor of PR #11510 which is a better fix.

2019-01-15 14:02 UTC, closed without merging