bpo-35711: When asserting !PyErr_Occurred, output error before crashing
python/cpython pull request #11513
Opened 2019-01-10 20:59 UTC by sfreilich

It's better to crash than to silently swallow an error state. Aid debugging by outputting the unexpectedly-pending error before crashing.

2019-01-10 20:59 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-01-10 21:35 UTC, lisroach approved these changes
LGTM, please sign the CLA :)

2019-01-10 23:45 UTC, sfreilich commented
Signed. But the confirmation link doesn't confirm that yet. My bpo profile says "Contributor Form Received" and has my github name set correctly, so I guess that just hasn't propagated yet?

2019-01-11 10:39 UTC, vstinner requested changes
I concur with @serhiy-storchaka: if C extensions are written properly, this change only adds an overhead for no gain. I would prefer to restrict the check to debug mode.

2019-01-11 12:53 UTC, sfreilich commented
@vstinner: I'm confused by some of that. Not commenting on whether or not these asserts should be compiled in by default (outside of noting that it seems a little like the idea that you can avoid overhead by assuming that you're never in a situation where undefined behavior happens, a trade-off that is not without drawbacks), but these *particular* assertions seemed to be in by default. I think this change only adds overhead when the program is about to crash due to an assert failure.

If `PyErr_Print` is not the best choice for out putting some debugging information about the pending error before assert failing, what is the correct choice?

"If C extensions are written properly" is a big if. I'm writing this change for a reason, I spent a lot of time debugging a failure of this particular assert that would have been limited if it output more context.

2019-01-11 13:17 UTC, vstinner commented
By default, Python is compiled in release mode and removes all C assertions (``assert(...);``).

2019-01-11 19:47 UTC, sfreilich commented
That's not necessarily true for C++ extensions linking in that code, but I see your point. My objective wasn't to add additional work in circumstances where the assert is disabled. My point was that "!PyErr_Occurred() was false" and then a stack-trace for the assert isn't terribly useful for debugging in situations where the thing passed to `PyErr_SetString` might help figure out what's going on.

There are quite a few instances of `assert(!PyErr_Occurred())` like this. Some of them are conditioned on `Py_DEBUG` some are not. Should they all be? Is there something that could be used instead of (or in addition to) assert, since assert doesn't provide a way of adding additional error output?

2019-01-12 00:38 UTC, vstinner commented
If an assertion fails, faulthandler should dump the current Python stack. I
am not sure if faulthandler should be enabled or not to get the Python
traceback. In case of doubt, use -X dev (which enables faulthandler and
other debug checks) ;-)

I recently added _PyObject_ASSERT() which dumps a Python object on
assertion failure. If you enable tracemalloc, you also get the traceback
where the object has been allocated.

-- 
Night gathers, and now my watch begins. It shall not end until my death.

2019-01-14 16:46 UTC, sfreilich commented
Would it be reasonable for the sigabrt handler to print information about a pending error, if there is one?

```python
static PyObject *
faulthandler_sigabrt(PyObject *self, PyObject *args)
{
    faulthandler_suppress_crash_report();
    if (PyErr_Occurred()) {
        PyObject *exception, *v, *tb, *hook;
        PyErr_Fetch(&exception, &v, &tb);
        if (exception != NULL) {
            // Something minimal to print the exception (what exactly?)
        }
    }
    abort();
    Py_RETURN_NONE;
}
```

That would avoid losing useful debugging messages, while not doing additional work in normal situations.

2019-01-15 12:04 UTC, vstinner commented
> Would it be reasonable for the sigabrt handler to print information about a pending error, if there is one?

I modified _testcapi.raise_exception() to call this code:

```
    PyErr_SetString(PyExc_ValueError, "oops");
    Py_FatalError("something bad happened");
```

On the following example:

```
import _testcapi
def bug():
    _testcapi.raise_exception()
def func():
    bug()
func()
```

Python fails with exit code 134 and the following output (I tested on debug build, but release build should give the same output):

```
Fatal Python error: something bad happened
ValueError: oops

Current thread 0x00007f51a2c81740 (most recent call first):
  File "x.py", line 3 in bug
  File "x.py", line 5 in func
  File "x.py", line 6 in <module>
Aborted (core dumped)
```

_Py_FatalError_PrintExc() is responsible to dump the current exception. It uses the Python sys.stderr object, normalizes the exception which can allocate memory on the heap to instanciate the exception, and call PyErr_Display() which calls the complex function print_exception_recursive(), etc.

A signal handler must not allocate memory because it can be executed anytime, even during a current allocation on the heap and memory allocators are usually not reentrant. Writing an async-safe signal handler is very difficult.

You can easily write our own signal handler (in C) for SIGABRT which will call Py_FatalError() to dump the current exception with its traceback. But that can crash and we don't want to do that in Python.

I close the PR since we are far from the initial change and your request doesn't fit Python performance and stability requirements.

2019-01-15 12:04 UTC, closed without merging

2019-01-15 12:04 UTC, vstinner commented
cc @serhiy-storchaka: read my last comment FYI ;-)