gh-115285: Fix `test_dataclasses` with `-OO` mode
python/cpython pull request #115286
Opened 2024-02-11 09:26 UTC by sobolevn

After it passes with both modes:

```
» ./python.exe -OO Lib/test/test_dataclasses/__init__.py
............................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 236 tests in 0.230s

OK
```

```
» ./python.exe Lib/test/test_dataclasses/__init__.py    
............................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 236 tests in 0.229s

OK
```

2024-02-11 16:19 UTC, terryjreedy requested changes

2024-02-11 16:19 UTC, terryjreedy commented on Lib/test/test_dataclasses/__init__.py
> +            self.assertEqual(C.__doc__, "C(x: int)")
`test_docstring_one_field` below already tests that ""C(x:int)" replaces None.  If the replacement code is altered, that and the tests that follows are enough failures.  This test is about not replacing a non-None docstring and should just test that. So perhaps better just put the non-None docstring back when it is stripped by the command line option;
```suggestion
        if C.__doc__ == None:  # If stripped by a "-00" command line option.
            C.__doc__ = "Lorem ipsum"
        self.assertEqual(C.__doc__, "Lorem ipsum")
```
or even better, just condition the test on some docstring being present.
```suggestion
        if C.__doc__ != None:  # If not stripped by a "-00" command line option.
            self.assertEqual(C.__doc__, "Lorem ipsum")
```

2024-02-12 07:00 UTC, sobolevn commented
Agreed, I just skip the test right now when there are no docstrings.

2024-02-12 18:09 UTC, ericvsmith approved these changes
Looks good to me.

2024-02-12 18:30 UTC, sobolevn commented
Thanks everyone!

2024-02-12 18:31 UTC, merged