bpo-35726:QueueHandler formating affects other handlers
python/cpython pull request #11537
Opened 2019-01-12 17:37 UTC by Zheaoli

https://bugs.python.org/issue35726

2019-01-12 23:27 UTC, remilapeyre requested changes
Hi @Zheaoli, thanks for your contribution !

Tests for the `logging` module do not pass anymore, can you look into it?

2019-01-13 00:57 UTC, Zheaoli commented
@remilapeyre 
sorry about the fail.

I have already fixed the test error! This PR could be reviewed and merged right now.

2019-01-13 01:04 UTC, Zheaoli commented
this PR need backport to 3.0-3.7 and 2.7

2019-01-13 09:26 UTC, vsajip requested changes

2019-01-13 09:26 UTC, vsajip commented on Lib/logging/handlers.py
> +        record = copy.copy(record)
Add comment above added line: # bpo-35726: make copy of record to avoid affecting other handlers in the chain.

2019-01-13 09:26 UTC, vsajip commented on Misc/NEWS.d/next/Library/2019-01-13-01-33-00.bpo-35726.dasdas.rst
> +fix bpo-35726:
Remove this line and blank lines.

2019-01-13 09:26 UTC, vsajip commented on Misc/NEWS.d/next/Library/2019-01-13-01-33-00.bpo-35726.dasdas.rst
> +fix logging.QueueHandler will change the logging record's message
Change to: QueueHandler.prepare() now makes a copy of the record before modifying and enqueueing it, to avoid affecting other handlers in the chain.

2019-01-13 10:49 UTC, Zheaoli commented
I have made the requested changes; please review again

2019-01-14 03:16 UTC, Zheaoli commented
I have made the requested changes; please review again

2019-01-23 07:08 UTC, merged

2019-01-23 07:31 UTC, Zheaoli commented
@vsajip this PR need be back  to Python 3.5/3.6/3.7

2019-01-23 07:45 UTC, tirkarthi commented
3.5 and 3.6 are in security fixes only mode so this can be backported only to 3.7.

2019-01-23 07:49 UTC, Zheaoli commented
@tirkarthi Got it, thx

2019-01-23 09:22 UTC, tirkarthi commented
@Zheaoli @vsajip I am just curious if there is a test for this in `test_logging` or as a separate PR? I hope below script illustrates the issue.

```python
import queue
import logging
from logging import handlers

queue = queue.Queue(-1)

que_hdlr = handlers.QueueHandler(queue)
stream_hdlr = logging.StreamHandler()

logger = logging.getLogger(__name__)
queue_log_format = "Queue %(name)s -> %(levelname)s: %(message)s"
queue_formatter = logging.Formatter(queue_log_format)
stream_log_format = "Stream %(name)s -> %(levelname)s: %(message)s"
stream_formatter = logging.Formatter(stream_log_format)

stream_hdlr.setFormatter(stream_formatter)
que_hdlr.setFormatter(queue_formatter)

listener = handlers.QueueListener(queue, que_hdlr)
listener.start()

logger.setLevel(logging.WARNING)
logger.addHandler(que_hdlr)
logger.addHandler(stream_hdlr)

logger.exception("hello")
```

```shell
➜  cpython git:(master) ✗ python3.7 /tmp/foo.py
Stream __main__ -> ERROR: Queue __main__ -> ERROR: hello
NoneType: None
➜  cpython git:(master) ✗ ./python.exe /tmp/foo.py # patched master
Stream __main__ -> ERROR: hello
NoneType: None
```

2019-01-23 10:14 UTC, tirkarthi commented
I can raise a PR something along the lines of below if there is a confirmation that there are no tests for the current PR.

```python
@unittest.skipUnless(hasattr(logging.handlers, 'QueueListener'),
                     'logging.handlers.QueueListener required for this test')
def test_queue_listener_with_multiple_handlers(self):
    # Test that queue handler format doesn't affect other handler formats (bpo-35726).
    self.que_hdlr.setFormatter(self.root_formatter)
    self.que_logger.addHandler(self.root_hdlr)

    listener = logging.handlers.QueueListener(self.queue, self.que_hdlr)
    listener.start()
    self.que_logger.error("error")
    listener.stop()
    self.assertEqual(self.stream.getvalue().strip(), "que -> ERROR: error")
```

* Without patch

```
./python.exe -m unittest -v test.test_logging.QueueHandlerTest.test_queue_listener_with_multiple_handlers
test_queue_listener_with_multiple_handlers (test.test_logging.QueueHandlerTest) ... FAIL

======================================================================
FAIL: test_queue_listener_with_multiple_handlers (test.test_logging.QueueHandlerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karthikeyansingaravelan/stuff/python/cpython/Lib/test/test_logging.py", line 3519, in test_queue_listener_with_multiple_handlers
    self.assertEqual(self.stream.getvalue().strip(), "que -> ERROR: error")
AssertionError: 'que -> ERROR: que -> ERROR: error' != 'que -> ERROR: error'
- que -> ERROR: que -> ERROR: error
+ que -> ERROR: error


----------------------------------------------------------------------
Ran 1 test in 0.009s

FAILED (failures=1)
```

* With patch 

```
./python.exe -m unittest -v test.test_logging.QueueHandlerTest.test_queue_listener_with_multiple_handlers
test_queue_listener_with_multiple_handlers (test.test_logging.QueueHandlerTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
```

2019-04-07 11:57 UTC, miss-islington commented
Thanks @Zheaoli for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖