bpo-11822: Improve disassembly to show embedded code objects.
python/cpython pull request #1155
Opened 2017-04-15 14:21 UTC by serhiy-storchaka

2017-04-15 15:55 UTC, ncoghlan requested changes
Thanks for getting this RFE moving again!

I think there may be some usability and robustness problems with a simple all-or-nothing flag for the recursive behaviour, so I've posted that question back on the original issue: https://bugs.python.org/issue11822#msg291718

2017-04-15 15:55 UTC, ncoghlan commented on Lib/dis.py
> +                disassemble(x, file=file, recursive=True)
This has the potential to get very noisy if disassembling a whole module, so I've posted a design question back on the original issue: https://bugs.python.org/issue11822#msg291718

I'd prefer to keep that discussion on the issue tracker, so I won't duplicate it here.

2017-05-29 01:10 UTC, ncoghlan commented
As per the discussion at https://bugs.python.org/issue11822#msg291780, I still prefer the approach with the `depth` parameter, but amended so the default is `depth=None` to automatically render the entire tree.

2017-06-11 11:11 UTC, serhiy-storchaka commented
Closed in favor of #1844.

2017-06-11 11:11 UTC, closed without merging