gh-89480: Document the gdb helpers
python/cpython pull request #115657
Opened 2024-02-19 13:57 UTC by pablogsal

2024-02-19 15:59 UTC, encukou commented
Thank you! I'll update this for recent GDB, and then we can perhaps point the devguide to it.

To everyone else: Please don't add GitHub suggestions, they might be lost.

2024-02-19 16:59 UTC, encukou commented
I'm signing of for the day. Here's a first pass, I'll finish tomorrow.
It's safe to add suggestions now, if anyone wants to do that.

2024-02-20 12:29 UTC, encukou commented
Ready for review.

Diátaxis-wise, this leans toward being a *reference* rather than a *how-to guide*. I'm not sure how to quickly handle that -- the document assumes you know debugging with GDB, and only provides a few details.
IMO, adding it would be an improvement, and restructuring can be done later.

Once merged, the [devguide page](https://devguide.python.org/development-tools/gdb/) should be updated to point here, and retain only the parts specific to CPython core (`test_gdb` & tips).

2024-02-20 12:40 UTC, hugovk reviewed
Some typos found with https://github.com/codespell-project/codespell

2024-02-20 12:40 UTC, hugovk commented on Doc/howto/gdb_helpers.rst
> +   If the current C frame corrresponds to multiple Python frames, ``py-print``
```suggestion
   If the current C frame corresponds to multiple Python frames, ``py-print``
```

2024-02-20 12:40 UTC, hugovk commented on Doc/howto/gdb_helpers.rst
> +The extension comands complement GDB's built-in commands.
```suggestion
The extension commands complement GDB's built-in commands.
```

2024-02-20 12:40 UTC, hugovk commented on Doc/howto/gdb_helpers.rst
> +   If the current C frame corrresponds to multiple Python frames, locals from
```suggestion
   If the current C frame corresponds to multiple Python frames, locals from
```

2024-02-20 12:50 UTC, encukou commented on Doc/howto/gdb_helpers.rst
> +   If the current C frame corrresponds to multiple Python frames, locals from
Arrrr!

Thank you :)

2024-02-20 17:04 UTC, ezio-melotti reviewed
I just skimmed through it and left a few comments about the high-level structure of the document and its headers.

2024-02-20 17:04 UTC, ezio-melotti commented on Doc/howto/gdb_helpers.rst
> +We hereafter present two ways to overcome this limitation.
By looking at the ToC, it's not clear to me what these two ways are.

2024-02-20 17:04 UTC, ezio-melotti commented on Doc/howto/gdb_helpers.rst
> +Linux distros
This title is not very descriptive -- maybe
```suggestion
Installing debug information package on Linux
```
If this only works on Linux, you could just use:
```suggestion
Installing Python debug information package
```
and state in the first paragraph that these are only available on Linux.

2024-02-20 17:04 UTC, ezio-melotti commented on Doc/howto/gdb_helpers.rst
> +Python built from source
If this is a prerequisite, it should be listed above, and this section would just explain how to do it, with a title like:
```suggestion
Building Python from source
```

2024-02-20 17:04 UTC, ezio-melotti commented on Doc/howto/gdb_helpers.rst
> +   If you do not seee instructionns for your version of GDB, put this in your
```suggestion
   If you do not see instructions for your version of GDB, put this in your
```

2024-02-20 17:04 UTC, ezio-melotti commented on Doc/howto/gdb_helpers.rst
> +Debug build and Development mode
This title could also be more "action-oriented":
```suggestion
Building Python in "debug" and "development" mode
```
or
```suggestion
Enabling "debug" and "development" mode
```
This could also be a sub-section of the "Building Python from source" section above.  You wouldn't want to read that and build everything and then discover that you have to do it again with debug/dev mode enabled.

2024-02-20 17:04 UTC, ezio-melotti commented on Doc/howto/gdb_helpers.rst
> +Using the ``python-gdb`` extension
This seems to be the actual how-to.

You could also add a short introductory paragraph like "After installing the dependencies, you can now use the `python-gdb extension to ...".

2024-02-20 17:04 UTC, ezio-melotti commented on Doc/howto/gdb_helpers.rst
> +=====================·
```suggestion
=====================
```
This broke the formatting of the title -- maybe this is the second way mentioned in the first paragraph?

2024-02-20 20:17 UTC, willingc requested changes
Let's come up with a better title and address the introduction section that I mention in my comments. After that, I think this will be ready to merge from my vantage point.

I'm less concerned about where this falls diataxis-wise and more concerned that we have clarity of its purpose for the reader and for future disambiguation of the old-style HOWTOs.

2024-02-21 12:20 UTC, encukou commented on Doc/howto/gdb_helpers.rst
> +Debug build and Development mode
You do want both: for debugging *extensions* it's sometimes easier to use the production build.
And these are not specific to source builds.

2024-02-21 12:28 UTC, encukou commented on Doc/howto/gdb_helpers.rst
> +Using the ``python-gdb`` extension
The previous section tells you how to set things up, this tessl you how to use it :)

2024-02-21 12:30 UTC, encukou commented on Doc/howto/gdb_helpers.rst
> +We hereafter present two ways to overcome this limitation.
Right, there's only one way left in the document. (The other was for the 2010's.)
Thanks for the catch!

2024-02-21 12:32 UTC, encukou commented on Doc/howto/gdb_helpers.rst
> +Linux distros
Setting things up depends on how you got your Python. These are examples for two common cases: source builds, and Linux distros. (No Windows or Mac, you wouldn't typically use GDB there.)

2024-02-21 12:34 UTC, encukou commented on Doc/howto/gdb_helpers.rst
> +Python built from source
I'd keep Python itself is a prerequisite for the prerequisites. The guide doesn't tell you how to get it, but how to set things up for it.
Hopefully “Setup with Python built from source” is clearer.

2024-02-21 12:41 UTC, encukou commented
Thanks! Your perspectives are very helpful here; I'm too deep in :)
I want to move it forward, it doesn't really need to be quick. It's a deferred release blocker for 3.11, a few more months won't matter.

@willingc 
> guidance for the reader
>
>  -  who would find this content useful
>  -  when would they use gdb and specifically the python helper
>  -  what will they learn if they read the rest of the document

I thought the first section covers exactly these questions. When you have the time, could you please be more specific about how it should be written?

2024-02-21 17:23 UTC, willingc commented
@encukou I like the changes that you have made to the headings.

> I thought the first section covers exactly these questions. When you have the time, could you please be more specific about how it should be written?

I think it is being more explicit to the reader. I will leave an example in the comments here later today. Thanks!

2024-02-21 18:13 UTC, willingc commented
@encukou This is more along the lines of what I was thinking:
- high-level what
- why this is needed
- who would use this information
It takes most of the info that you wrote but breaks it into more logical chunks for a reader, such a scientist writing and debugging a C extension, who has not yet used the the Python extension with GDB.

```
This document explains how GDB and the Python extension, ``python-gdb.py``, can
be used together to debug CPython extensions and the CPython interpreter itself.

When debugging low-level problems such as crashes or deadlocks, a low-level debugger,
such as GDB, is useful to diagnose and correct the issue. By default, GDB (or any
of its front-ends) doesn't support high-level information specific to the CPython
interpreter.

The ``python-gdb.py`` extension adds CPython interpreter information to GDB. The
extension helps introspect a currently executing Python function. Given
a Python object represented by a standard PyObject * pointer, the extension surfaces
the type and value of the object.

Developers who are working on CPython extensions or tinkering with parts of CPython
that are written in C can use this document to learn how to use GDB with the
``python-gdb.py`` extension.

.. note::
    
   This document assumes that you are familiar with the basics of GDB and the
   CPython C API. It consolidates guidance from the CPython devguide
   and the Python wiki.
```

2024-02-21 18:15 UTC, willingc reviewed
See sample wording in my comment.

2024-02-21 18:15 UTC, willingc approved these changes

2024-02-23 09:53 UTC, encukou commented
Thank you for the concrete wording! I hope it will help future me write better introductions on my own :)

I edited your suggestion for technical details, and to highlight that this doesn't teach how to use GDB itself -- the guide (and the extension) are mainly useful for people who already use GDB.

I take your GitHub approval as a sign that you don't necessarily want to review again, so, I'll merge on Monday if there are no objections.

2024-02-23 16:13 UTC, merged

2024-02-23 16:13 UTC, encukou commented
Thank you!