gh-96471: Correct docs for queue shutdown raises
python/cpython pull request #115838
Opened 2024-02-23 02:08 UTC by EpicWink

* Remove "raises ShutDown" from `Queue.join()` and `Queue.task_done()` documentation (including doc-string)
* Clarify `Queue.shutdown()` behaviour (it doesn't raise itself, but causes other methods to raise)
* Add that `Queue.task_done()` raises `ValueError` after an immediate queue shutdown

Caused by: #104750

2024-02-23 02:47 UTC, gvanrossum reviewed
Thanks! Two nits and then I'll merge this. (I feel bad that I didn't catch this in review.)

2024-02-23 02:47 UTC, gvanrossum commented on Doc/library/queue.rst
> +   the queue, or after an immediate shutdown.
That's not entirely correct IIRC. Even after an immediate shutdown, if there are items still being processed, calling `task_done()` for those is allowed. Basically once a `get()` has returned an item, you can call `task_done()` for it (once) any time. Only `get()` and `put()` check the `self.is_shutdown` variable.

2024-02-23 02:47 UTC, gvanrossum commented on Lib/queue.py
>              self.is_shutdown = True
A few lines below is an unused `n_items = self._qsize()` line -- can you remove that too?

2024-02-23 22:39 UTC, gvanrossum reviewed
Please fix the nits I called out.

2024-02-23 22:39 UTC, gvanrossum requested changes
Please fix the nits I called out.

2024-02-25 04:48 UTC, EpicWink commented
I have made the requested changes; please review again

2024-02-25 16:30 UTC, gvanrossum commented on Doc/library/queue.rst
> +   :meth:`shutdown(immediate=True)` calls :meth:`task_done` for each remaining item
```suggestion
   ``shutdown(immediate=True)`` calls :meth:`task_done` for each remaining item
```

2024-02-25 16:30 UTC, gvanrossum approved these changes

2024-02-25 16:53 UTC, merged