pyinstaller added to docs, py2exe ref updated
python/cpython pull request #1158
Opened 2017-04-16 02:51 UTC by denfromufa

It is not clear why this FAQ item is written in addition to this document:

https://github.com/python/cpython/blob/909a6f626ff343937cd3f06fda996870e7890724/Doc/faq/programming.rst#how-can-i-create-a-stand-alone-binary-from-a-python-script

2017-04-16 02:51 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-04-16 03:06 UTC, kirbyfan64 commented on Doc/faq/windows.rst
> +distutils extensions that allows you to create console and GUI executables
PyInstaller isn't a distutils extension (and AFAIK doesn't even have anything to do with distutils).

2017-04-20 03:41 UTC, berkerpeksag commented
Thanks for the PR, but please open an issue on bugs.python.org. I agree that those two sections can be merged into one.

2017-06-26 04:27 UTC, denfromufa commented
added issue: http://bugs.python.org/issue30757

2017-06-26 12:47 UTC, briancurtin requested changes

2017-06-26 12:47 UTC, briancurtin commented on Doc/faq/windows.rst
> +https://pypi.python.org/pypi/py2exe/.
All three of these do the same or similar things but the grouping of the sentences reads oddly. Can we just simplify this to be more of a list? Something like...

```
The following packages can help with the creation of cross-platform console and GUI executables:
* http://cx-freeze.sourceforge.net/
* http://www.pyinstaller.org/

Additionally, http://www.py2exe.org/ exclusively supports Windows executables.
```

2017-07-19 18:33 UTC, denfromufa commented
@briancurtin @berkerpeksag please review

2017-07-22 02:13 UTC, berkerpeksag requested changes

2017-07-22 02:13 UTC, berkerpeksag commented on Doc/faq/windows.rst
> +The following 2 packages cx_Freeze and PyInstaller allow
I liked Brian's suggested wording more:

> The following packages can help with the creation of console and GUI executables:

2017-07-22 02:13 UTC, berkerpeksag commented on Doc/faq/windows.rst
> +* http://cx-freeze.sourceforge.net/
```rst
`cx_Freeze <http://cx-freeze.sourceforge.net/>`_
```

2017-07-22 02:13 UTC, berkerpeksag commented on Doc/faq/windows.rst
> +* http://www.pyinstaller.org/
PyInstaller can run on non-Windows platforms too. I think that the best we could do

* Move the content of this section to end of the "How can I create a stand-alone binary from a Python script?" section in `Doc/faq/programming.rst`
* In `Doc/faq/programming.rst`, change lines 75 and 76 to

  ```rst
  .. _faq-create-standalone-binary:

  How can I create a stand-alone binary from a Python script?
  -----------------------------------------------------------
  ```
* Remove

  ```rst
  Additionally, http://www.py2exe.org/ exclusively supports Windows
  executables.
  ```

  and add py2exe to the list:

  ```rst
  The following packages can help with the creation of console and GUI
  executables:

  * `cx_Freeze <http://cx-freeze.sourceforge.net/>`_ (Cross-platform)
  * `PyInstaller <http://www.pyinstaller.org/>`_ (Cross-platform)
  * `py2exe <http://www.py2exe.org/>`_ (Windows only)
  ```
* Then make the "How do I make an executable from a Python script?" section in this file a pointer to the "How can I create a stand-alone binary from a Python script?" section in `Doc/faq/programming.rst`:

  ```rst
  How do I make an executable from a Python script?
  -------------------------------------------------

  See :ref:`faq-create-standalone-binary` for a list of tools that can be
  used to make executables.
  ```

2017-07-22 02:13 UTC, berkerpeksag commented on Doc/faq/windows.rst
> +Additionally, http://www.py2exe.org/ exclusively supports Windows executables.
```rst
`py2exe <http://www.py2exe.org/>`_
```

2018-02-21 01:51 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2020-01-18 12:19 UTC, csabella commented
@denfromufa, please address the code reviews and resolve the merge conflicts.  Thank you!

2021-05-22 12:04 UTC, erlend-aasland commented
Due to the lack of response (pinged both here and on bpo), I've applied @berkerpeksag and @briancurtin's suggestions and opened #26309. Closing this in favour of the new PR.

2021-05-22 12:04 UTC, closed without merging