GH-116218 Docs; Add availability information for the 'resource' module
python/cpython pull request #116256
Opened 2024-03-03 01:04 UTC by Privat33r-dev

2024-03-08 08:55 UTC, ronaldoussoren requested changes
I've added some comments about the availability of a number of constants that have much wider availability than claimed by this PR.

I have not checked beyond macOS and FreeBSD, further resource is needed to update the availability statement. The constants I marked as being available on macOS and FreeBSD as well may well be available on all relevant unix-y platforms.

The symbols I marked as being part of the unix spec should IMHO not have availability information.

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
This constant is part of the unix standard and should be available on all platforms (given that this module is documented as available on unix platforms).

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
Likewise.

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
Likewise.

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
Likewise.

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
Likewise

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
Also available on (at least) macOS and FreeBSD, not mentioned in the unix spec.

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
Also available on (at least) macOS and FreeBSD, not mentioned in the unix spec.

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
Part of the unix spec, see above

2024-03-08 08:55 UTC, ronaldoussoren commented on Doc/library/resource.rst
> +   .. availability:: Linux >= 1.3.0
Part of the unix spec, see above.

2024-03-08 09:19 UTC, Privat33r-dev commented
Issues are addressed, thanks for the review.

2024-03-09 08:58 UTC, ronaldoussoren approved these changes
LGTM

2024-03-09 09:00 UTC, merged