Add documentation for exit() function
python/cpython pull request #11622
Opened 2019-01-19 17:46 UTC by vinayb21

2019-01-19 17:46 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-01-19 19:26 UTC, asottile commented on Lib/argparse.py
> +        if message is None then status is 0 else the status is 1
this part doesn't appear to be true:

```
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> parser.exit(0, 'hello world')
hello world
$ echo $?
0
```

2019-01-20 00:48 UTC, eamanu requested changes
IMO, the docstring improve are good. But I think that this PR has some things to correct:
* pep8
* A short title that briefly summarizes the functionality
* @asottile comments
*  look the other docstring formats.

Please sign CLA. I don't know if is necessary open a issue for this. I want to listen other opinions.

2019-01-20 18:02 UTC, pablogsal requested changes
Thank you for the PR! We can only continue the review when the CLA is signed.

In the meanwhile, please, add a NEWS entry using the `blurb` tool.

2019-01-20 18:02 UTC, pablogsal commented on Lib/argparse.py
> +
This docstring is missing a short description of what the exit function *does*.

2019-03-29 21:19 UTC, brettcannon commented
Thanks for the PR, but closing as the CLA has not been signed within the last month. If you do decide to sign the CLA we can re-open this PR.

2019-03-29 21:19 UTC, closed without merging