gh-116386: Fix format string "%ld" warning in `_xxinterpqueuesmodule`
python/cpython pull request #116387
Opened 2024-03-05 22:07 UTC by sobolevn

No warnings should be generate on GitHub. Locally this passes just fine.

2024-03-05 23:05 UTC, gvanrossum approved these changes
LGTM. No warnings on macOS.

2024-03-06 17:09 UTC, serhiy-storchaka reviewed
Would not be more natural to use the `%zd` format string?

And this looks like a completely different issue than the originally reported one.

2024-03-06 18:10 UTC, ericsnowcurrently requested changes

2024-03-06 18:10 UTC, ericsnowcurrently commented on Modules/_xxinterpqueuesmodule.c
> +                qid, (int64_t)queue->items.count);
As @serhiy-storchaka pointed out:

```C
        fprintf(stderr, "queue %" PRId64 " still holds %zd items\n",
                qid, queue->items.count);
```

2024-03-06 22:55 UTC, ericsnowcurrently approved these changes
LGTM

2024-03-07 06:44 UTC, merged

2024-03-07 06:44 UTC, sobolevn commented
Thanks for the help and reviews!

2024-03-07 16:25 UTC, ericsnowcurrently commented
Thanks for fixing this. 😄