bpo-29553 - Fixed ArgumentParses format_usage for mutually exclusive groups
python/cpython pull request #117
Opened 2017-02-15 10:31 UTC by andrewnester

Fix for https://bugs.python.org/issue29553

2017-02-19 14:16 UTC, berkerpeksag requested changes
I just did a quick review and the PR looks good in general, thank you. We also need an entry in `Misc/NEWS` (should be in "Library" section)

2017-02-19 14:16 UTC, berkerpeksag commented on Lib/test/test_argparse.py
> +        parser = ErrorRaisingArgumentParser(prog='PROG')
Is there a reason you can't use the existing test infrastructure? I think it's possible to convert these tests to follow the style of `TestMutuallyExclusiveOptionalAndPositional`: https://github.com/python/cpython/blob/82e38bd80113ecfc7aff2fb3edaf2802fe21c1fb/Lib/test/test_argparse.py#L2560

We can define a `get_parser()` method and use `usage_when_required` and `usage_when_not_required` to check output of `parser.format_help()`.

2017-02-19 17:29 UTC, andrewnester commented
@berkerpeksag thanks! just updated my PR.

2018-02-21 01:53 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2019-07-27 09:43 UTC, flavianh commented
Recreated at https://github.com/python/cpython/pull/14976

2019-08-22 22:02 UTC, aeros167 commented
Since this has not received a response from the author since the ``awaiting changes`` label was added on Feb 20, 2018 and was recreated at https://github.com/python/cpython/pull/14976, I'll close this PR.

2019-08-22 22:02 UTC, closed without merging