gh-117187: Fix XML tests for vanilla Expat <2.6.0
python/cpython pull request #117203
Opened 2024-03-24 23:08 UTC by hartwork

Please someone add labels…

- `needs backport to 3.8`
- `needs backport to 3.9`
- `needs backport to 3.10`
- `needs backport to 3.11`
- `needs backport to 3.12`

…for me. Thank you! :pray:

2024-03-25 00:58 UTC, gpshead requested changes
Running the full test suite `./configure --with-system-expat` (which uses 2.5.0) I see several more xml related test failures that this PR doesn't yet address. Some are obviously reparse related.  `./python -m test test_pyexpat test_sax test_xml_etree test_xml_etree_c`

The test_xml_etree* `XMLPullParserTest.test_simple_xml_chunk` ones may or may not be related but _probably_ are.

2024-03-25 14:40 UTC, serhiy-storchaka approved these changes
LGTM.

2024-03-25 21:36 UTC, hartwork commented
> Running the full test suite `./configure --with-system-expat` (which uses 2.5.0) I see several more xml related test failures that this PR doesn't yet address. Some are obviously reparse related. `./python -m test test_pyexpat test_sax test_xml_etree test_xml_etree_c`
> 
> The test_xml_etree* `XMLPullParserTest.test_simple_xml_chunk` ones may or may not be related but _probably_ are.

@gpshead I tried to reproduce it myself using your command…

> `./python -m test test_pyexpat test_sax test_xml_etree test_xml_etree_c`

… with (1) `=dev-libs/expat-2.5.0` on Gentoo and (2) Expat 2.5.0-2 on Debian trixie; all tests pass, no errors. Below is the adjusted `Dockerfile` (based on https://github.com/python/cpython/issues/117187#issuecomment-2016981929):

```Dockerfile
FROM debian:trixie
RUN apt-get update \
        && \
    apt-get install --yes --no-install-recommends -V \
            ca-certificates \
            build-essential \
            git \
            libexpat1-dev \
            pkg-config
# Was: RUN git clone --depth 1 https://github.com/python/cpython
RUN git clone --depth 1 --branch issue-117187-fix-xml-tests-for-vanilla-expat-2-5-0 https://github.com/hartwork/cpython
WORKDIR cpython
RUN git rev-parse HEAD
RUN ./configure --with-system-expat && make -j$(nproc)
# Was: RUN ./python -m test test_sax test_xml_etree
RUN ./python -m test test_pyexpat test_sax test_xml_etree test_xml_etree_c
```

Does the error still show up for you? Any ideas on how to reproduce it locally or in Docker?

2024-03-26 01:21 UTC, gpshead commented
Change that Dockerfile to use `FROM ubuntu:22.04` (and likely `ubuntu:23.10` as that's the actual distro I saw it on locally) and it shows the failures.  (surprising to me that `debian:trixie` and `debian:bookworm` do not)

2024-03-26 01:44 UTC, gpshead commented
Ahha, the difference here is one I wasn't expecting.  Debian does **not** have the CVS-2024-28757 change backported to its libexpat1 2.5.0-2 or 2.5.0-1 packages: https://metadata.ftp-master.debian.org/changelogs//main/e/expat/expat_2.5.0-2_changelog

Ubuntu ships libexpat1 2.5.0-2ubunutu0.1 which contains the 2.6.0 feature backported: https://changelogs.ubuntu.com/changelogs/pool/main/e/expat/expat_2.5.0-2ubuntu0.1/changelog

So this is the "other" case I had pondered coming up (backports).  Should we deal with it or should the distro?  _(oddly I don't see patches to Ubuntu's python3.x packages to deal with this, but I don't know how their internal package rebuild testing story)_

I'm fine accepting this PR as is for now as it fixes the larger problem of simply working when linked against more normal old versions.

2024-03-26 01:45 UTC, gpshead approved these changes

2024-03-26 01:48 UTC, merged

2024-03-26 22:57 UTC, hartwork commented
> So this is the "other" case I had pondered coming up (backports). Should we deal with it or should the distro?

Clear vote for case "the distro" from both a complexity and an ecosystem perspective, from me.

> I'm fine accepting this PR as is for now as it fixes the larger problem of simply working when linked against more normal old versions.

@gpshead thank you!