bpo-34886: Fix subprocess.run handling of exclusive arguments
python/cpython pull request #11727
Opened 2019-02-01 22:48 UTC by remilapeyre

I think we can skip news for this one.

2019-02-02 12:27 UTC, eamanu approved these changes
lgtm

2019-06-06 00:09 UTC, gpshead requested changes
Please use blurb or blurbit to add the following NEWS entry:

```
Fix an unintended ValueError from :func:`subprocess.run` when checking for
conflicting `input` and `stdin` or `capture_output` and `stdout` or `stderr` args
when they were explicitly provided but with `None` values within a passed in
`**kwargs` dict rather than as passed directly by name.
```

2019-06-08 14:07 UTC, remilapeyre commented
Hi @gpshead, thanks for the review! I have made the requested changes; please review again

2019-06-08 14:55 UTC, gpshead approved these changes

2019-06-08 14:56 UTC, merged

2019-06-08 14:56 UTC, miss-islington commented
Thanks @remilapeyre for the PR, and @gpshead for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-06-08 14:56 UTC, miss-islington commented
Thanks @remilapeyre for the PR, and @gpshead for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖