Allow WeakSet.discard and WeakSet.remove to accept non referenceable …
python/cpython pull request #1176
Opened 2017-04-19 05:19 UTC by donkopotamus

…values

Currently `WeakSet().discard([])` will raise a `TypeError` as we cannot take a weak reference to a list.

However, that means a list can never be in a `WeakSet`, so `WeakSet().discard([])` could instead be a no-op.  Similarly `WeakSet().remove([])` could be a KeyError.

2017-04-19 05:19 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-04-19 05:31 UTC, donkopotamus commented
Clearly the same argument can be made for the `pop` and `__delitem__` (and `__getitem__`?) methods in `WeakKeyDictionary` as well.  Its not in this patch currently though.

2017-04-19 06:02 UTC, serhiy-storchaka requested changes
I don't know whether this is a worth change, but if it is worth the patch needs tests and `Misc/NEWS` entry.

2017-04-19 06:02 UTC, serhiy-storchaka commented on Lib/_weakrefset.py
> +            return KeyError(item)
... `from None`

2017-04-19 06:12 UTC, donkopotamus commented on Lib/_weakrefset.py
> +            return KeyError(item)
Yes I've noticed the tests explicitly check that `discard` and `remove` raise for such types ... I'll patch those tests tomorrow (hopefully!).

(Also, that `return` should have been a `raise`, I've force pushed that so your change has gone outdated)

2018-02-02 22:05 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2019-08-22 06:03 UTC, rhettinger commented
I'm inclined to leave the code as-is. The current behavior is plausible enough in that it matches *set() * behavior:

```
>>> set().discard([])
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    set().discard([])
TypeError: unhashable type: 'list'
```

2019-08-22 06:03 UTC, closed without merging