bpo-27777: cgi.FieldStorage can't parse simple body with Cont…
python/cpython pull request #11764
Opened 2019-02-05 22:40 UTC by ar45

…ent-Length and no Content-Disposition

- If content length is present, read at most len bytes.
- When reading `read_lines_to_eof` use `read` instead of `readline`.
- Use `self.__write` even when content length is present and > 1000.

2019-02-05 22:40 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-06-02 07:09 UTC, auvipy requested changes
can you check the failures?

2019-06-02 23:35 UTC, ar45 commented
@auvipy I updated. passes now.

2019-06-03 05:59 UTC, ZackerySpytz commented on Misc/NEWS.d/next/Library/2019-02-05-16-57-27.bpo-27777.AKUxDR.rst
> +Fixes a bug in :mod:`cgi` when a request has a "Content-Length" header but
I think `FieldStorage` should be mentioned.

2020-04-08 08:43 UTC, GuillaumeDerval commented
The test added in PR #10771 does not pass with this PR:

```
    def test_content_length_no_content_disposition(self):
        body = b'{"test":123}'
        env = {
            'CONTENT_LENGTH': len(body),
            'REQUEST_METHOD': 'POST',
            'CONTENT_TYPE': 'application/json',
            'wsgi.input': BytesIO(body),
        }

        form = cgi.FieldStorage(fp=env['wsgi.input'], environ=env)
        self.assertEqual(form.file.read(), body.decode(form.encoding))
```

The tests fails with 

```
Traceback (most recent call last):
  File "/.../myfile.py", line 17, in test_content_length_no_content_disposition
    form = cgi.FieldStorage(fp=env['wsgi.input'], environ=env)
  File "/mypydistrib/cgi.py", line 474, in __init__
    self.read_single()
  File "/mypydistrib/cgi.py", line 665, in read_single
    self.read_content()
  File "/mypydistrib/cgi.py", line 687, in read_content
    self.__write(data)
  File "/mypydistrib/cgi.py", line 702, in __write
    if self.__file is not None:
  File "/mypydistrib/cgi.py", line 498, in __getattr__
    raise AttributeError(name)
AttributeError: _FieldStorage__file
```

The attr `self.__file` must be defined before calling `self.__write`. Adding `self.__file = self.file` to `read_content` fixes the issue:

```
    def read_content(self):
        if self.length > 1000:
            self.file = self.make_file()
        else:
            self.file = self.io_object()
        self.__file = self.file #line added here
```

2020-07-13 06:02 UTC, closed without merging

2020-07-13 06:07 UTC, ar45 commented
Superseded by #21457