gh-102247: http: support rfc9110 status codes
python/cpython pull request #117611
Opened 2024-04-07 19:33 UTC by mbeijen

rfc9110 obsoletes the earlier rfc 7231. This document also includes some status codes that were previously only used for WebDAV and assigns more generic names to these status codes.

ref: https://www.rfc-editor.org/rfc/rfc9110.html#name-changes-from-rfc-7231

- http.HTTPStatus.CONTENT_TOO_LARGE (413, previously REQUEST_ENTITY_TOO_LARGE)
- http.HTTPStatus.URI_TOO_LONG (414, previously REQUEST_URI_TOO_LONG)
- http.HTTPStatus.RANGE_NOT_SATISFYABLE (416, previously REQUEST_RANGE_NOT_SATISFYABLE)
- http.HTTPStatus.UNPROCESSABLE_CONTENT (422, previously UNPROCESSABLE_ENTITY)

The new constants are added to http.HTTPStatus and the old constants are preserved for backwards compatibility.

References in documentation to the obsoleted rfc 7231 are updated

An earlier attempt at implementing RFC 9110 status codes was made but was closed by the author without getting merged; see https://github.com/python/cpython/pull/102570

One problem with this PR (and the previous attempt) is that the unit test currently checks the enum order which now is different, and it's not obvious how to use `enum._test_simple_enum()` to make the test not fail.

The last time @corona10 asked @ethanfurman for advise but the PR was closed before this feedback was given. @ethanfurman is the enum 'mastermind' and has converted http.HTTPStatus into an enum, so indeed I would like to ask their advise here

2024-04-08 20:19 UTC, ethanfurman commented
The current mismatch error is due to a bug in the `_simple_enum` decorator.  Working on a fix.

2024-04-08 20:20 UTC, mbeijen commented
Great, thanks for the quick feedback!

2024-04-08 22:11 UTC, ethanfurman submitted a review, later dismissed
Looks like a mismatch in the new Range not Satisfiable member.  Once that's fixed and the `_simple_enum` decorator is fixed, this should be good to go.

2024-04-08 22:11 UTC, ethanfurman commented on Lib/http/__init__.py
>          'Requested Range Not Satisfiable',
```suggestion
        'Range Not Satisfiable',
```

2024-04-08 23:31 UTC, ethanfurman requested changes
Instead of respecifying the legacy entries, just assign the new entry.  I.e.:

    REQUESTED_RANGE_NOT_SATISFIABLE = RANGE_NOT_SATISFIABLE

2024-04-09 06:39 UTC, mbeijen commented
> Instead of respecifying the legacy entries, just assign the new entry. I.e.:
> 
> ```
> REQUESTED_RANGE_NOT_SATISFIABLE = RANGE_NOT_SATISFIABLE
> ```

I changed this as you suggested, but I wanted to point out that this changes the behaviour of the old constants slightly, the number in the resulting tuple is still the same, but the message now differs to the RFC 9110 version. I'm not fully sure this is desirable.

> Looks like a mismatch in the new Range not Satisfiable member. Once that's fixed and the `_simple_enum` decorator is fixed, this should be good to go.

Thanks, I fixed that and if I rebase on f931992f42607c1622be4102976fd6d1998f7cca the tests now pass. I'll wait for #117664 to be merged before I'l request review again

2024-04-09 13:37 UTC, ethanfurman commented
Because the `HTTPStatus` codes are `IntEnum`s, we cannot have different members with the same numerical value -- so fully specifying the legacy settings is useless, because, for example, the object that is `REQUESTED_RANGE_NOT_SATISFIABLE` will be thrown away, and the name will become an alias to `RANGE_NOT_SATISFIABLE`.

In other words, once the transformation to `IntEnum` is complete:

```python
>>> HTTPStatus.REQUESTED_RANGE_NOT_SATISFIABLE is HTTPStatus.RANGE_NOT_SATISFIABLE
True
```

2024-04-09 18:55 UTC, mbeijen commented
I have made the requested changes; please review again.

2024-04-12 21:47 UTC, ethanfurman approved these changes

2024-04-13 14:33 UTC, merged