GH-117881: fix athrow().throw()/asend().throw() concurrent access
python/cpython pull request #117882
Opened 2024-04-15 07:35 UTC by graingert

2024-04-15 07:37 UTC, graingert commented on Misc/NEWS.d/next/Core and Builtins/2024-04-15-07-37-09.gh-issue-117881.07H0wI.rst
> +prevent concurrect access to an async generator via athrow().throw() or asend().throw()
```suggestion
prevent concurrent access to an async generator via athrow().throw() or asend().throw()
```

2024-04-15 07:59 UTC, graingert commented on Objects/genobject.c
> +            o->ags_state = AWAITABLE_STATE_CLOSED;
this was set in `async_gen_athrow_send` but forgotten in `async_gen_asend_send`

2024-04-15 08:01 UTC, graingert commented on Objects/genobject.c
> +            o->ags_state = AWAITABLE_STATE_CLOSED;
https://github.com/python/cpython/blob/8418dcc5d3190a199d2236e99e30f2c146939e95/Objects/genobject.c#L2098-L2113

2024-04-15 08:04 UTC, graingert commented on Objects/genobject.c
>          return async_gen_unwrap_value(o->agt_gen, retval);
```suggestion
        retval = async_gen_unwrap_value(o->agt_gen, retval);
        if (retval == NULL) {
            o->agt_gen->ag_running_async = 0;
        }
        return retval;
```

2024-04-15 08:08 UTC, graingert commented on Objects/genobject.c
> +        o->ags_state = AWAITABLE_STATE_ITER;
```suggestion
        o->ags_state = AWAITABLE_STATE_ITER;
        o->ags_gen->ag_running_async = 1;
```

2024-04-15 08:08 UTC, graingert commented on Objects/genobject.c
> +        o->agt_state = AWAITABLE_STATE_ITER;
```suggestion
        o->agt_state = AWAITABLE_STATE_ITER;
        o->agt_gen->ag_running_async = 1;
```

2024-04-24 12:15 UTC, encukou reviewed
As in #117851: I'm not an expert in this area.
It makes sense to start the generator in send/throw.

What I don't get is the purpose of all the synchronization between `ags_state` and `ags_gen->ag_running_async`/`ags_gen->ag_closed`. What's the difference between what they represent? Should they go out of sync at some point?

2024-04-24 13:12 UTC, encukou commented
Is it a bug if they go out of sync?
If it is, and `ag_running_async` & `ag_closed` hold the necessary info, why have `ags_state` at all?

2024-04-24 13:20 UTC, graingert commented
this is where they go out of sync:

```python
import types
import itertools

@types.coroutine
def _async_yield(v):
    return (yield v)


async def agenfn():
    for i in itertools.count():
        await _async_yield(i)
    return
    yield

agen = agenfn()
gen = agen.__anext__()
print(f"{gen.send(None)=}")
print(f"{agen.ag_running=}")
gen.close()  # uh-oh, gen->ags_state is CLOSED
print(f"{agen.ag_running=}")  # but the async generator is still running
agen.aclose().send(None)  # and it's broken so we can't aclose it
```

2024-04-25 09:31 UTC, encukou approved these changes
The PR looks good to me. But, it would be great to have a more comprehensive way to find issues like this. I commented on the issue.

2024-04-25 09:51 UTC, hugovk requested changes, later dismissed

2024-04-25 09:51 UTC, hugovk commented on Lib/test/test_asyncgen.py
> +    def test_async_gen_asend_throw_concurrent_with_send(self):
[Ignore this review, I'm testing if Bedevere will run without needing approval.]

2024-04-25 17:55 UTC, hugovk commented
No need for me to review, I was only testing the bot earlier. 👍

2024-04-26 08:00 UTC, graingert commented on Objects/genobject.c
> +            o->ags_state = AWAITABLE_STATE_CLOSED;
probably could do with a test

2024-04-26 09:27 UTC, graingert commented on Objects/genobject.c
> +            o->ags_state = AWAITABLE_STATE_CLOSED;
test added in 1220aee3d7a1a8e72903abc815fdf96f31c5ce34

2024-04-26 09:28 UTC, graingert commented on Lib/test/test_asyncgen.py
> +            r"cannot reuse already awaited aclose\(\)/athrow\(\)"):
```suggestion
                r"cannot reuse already awaited aclose\(\)/athrow\(\)"):
```

2024-04-26 09:28 UTC, graingert commented on Lib/test/test_asyncgen.py
> -            del g
driveby: oops this wasn't running

2024-04-30 21:19 UTC, graingert commented
@encukou is there anything else I need to do on this? I'd like to start looking at fixing athrow().close() and asend().close() next

2024-05-01 06:43 UTC, encukou commented
No, sorry for the delay!

2024-05-01 06:44 UTC, merged