bpo-35922: Fix RobotFileParser when robot.txt is invalid
python/cpython pull request #11791
Opened 2019-02-08 16:05 UTC by remilapeyre

I don't think this change requires a news entry.

2019-06-02 07:21 UTC, auvipy approved these changes

2019-06-08 19:33 UTC, taleinat requested changes
In addition to testing with empty robots.txt content, it would be good to also test with:
1. one not referencing the given user-agent and without a default
2. one with a default or with the given user-agent, but which doesn't define `Crawl_delay` and `Request_rate`

2019-06-08 19:33 UTC, taleinat commented on Lib/test/test_robotparser.py
> +class InvalidFileTest(BaseRobotTest, unittest.TestCase):
This tests an empty file, which doesn't appear to be invalid from my reading. I suggest renaming to "EmptyFileTest".
```suggestion
class EmptyFileTest(BaseRobotTest, unittest.TestCase):
```

2019-06-08 19:33 UTC, taleinat commented on Lib/urllib/robotparser.py
Both `crawl_delay` and `request_rate` should return `None` explicitly if there is no applicable entry.

2019-06-09 16:49 UTC, remilapeyre commented
Thanks for the review @taleinat! I made all the changes you requested, let me know if you want me to make other updates.

I have made the requested changes; please review again

2019-06-09 19:24 UTC, taleinat requested changes
These changes are very well done, and they were done very quickly; nice!

Taking a deeper look at the structure of the existing tests, we would do better to build on the existing `BaseRequestRateTest`. Specifically, I think its `test_request_rate()` method should be changed to always check the crawl delay and request rate, so that setting them to `None` will check that `RobotFileParser` actually returns `None`.

Doing so should allow removing `NoDefaultUserAgentTest`, since that case will already be covered by the existing `CrawlDelayAndRequestRateTest`. `EmptyFileTest` should stay but not require any special logic, just define `robots_txt` to an empty stings. Similarly, `NoRequestRateAndCrawlDelayTest` could be written much more simply.

Let me know if you'd like to do this yourself or if you'd prefer me to make these changes myself.

2019-06-09 19:41 UTC, remilapeyre commented
Yeah, it will be better that way, I will push a new commit tomorrow.

2019-06-11 09:35 UTC, remilapeyre commented
Thanks @taleinat, I have made the requested changes; please review again

2019-06-11 10:48 UTC, taleinat commented on Lib/test/test_robotparser.py
> +class NoRequestRateAndCrawlDelayTest(BaseRobotTest, unittest.TestCase):
I believe this case is already covered by other tests, e.g. `RejectAllRobotsTest`.

2019-06-11 10:52 UTC, taleinat requested changes

2019-06-11 10:52 UTC, taleinat commented on Lib/test/test_robotparser.py
> +    crawl_delay = 3
These can simply be removed, since these are the same values as the base class.

2019-06-11 11:12 UTC, remilapeyre commented
Thanks @taleinat for the review, ISTM that I should add `    good = ['/foo']` to `EmptyFileTest` right?

2019-06-11 11:25 UTC, taleinat commented
> ISTM that I should add ` good = ['/foo']` to `EmptyFileTest` right?

Yes, that would be good.

2019-06-11 11:39 UTC, remilapeyre commented
Thanks @taleinat, I think it should be good now (How many mistakes can I make on a simple patch ;) ?)

I have made the requested changes; please review again

2019-06-11 15:38 UTC, taleinat commented
> I think it should be good now

I think so too! I'll make a final review later.

> Thanks @taleinat, I think it should be good now (How many mistakes can I make on a simple patch ;) ?)

Heh, the sky is the limit... But really, these aren't mistakes, this is the natural process for making changes: Most changes need at least a few iterations before they can go in. Additionally, in this particular case, I was working with this part of the codebase for the first time, so I was also learning as we went.

2019-06-12 06:24 UTC, taleinat commented
@remilapeyre, this does need a NEWS file, plus a few minor fixes. For some reason I can't push to this PR's branch, nor create a PR for this branch in your repo. Perhaps you've got some privacy settings set in a non-standard way?

If you'd rather leave things the way they are, I'll create a new PR and still make sure to give you credit for this work.

2019-06-12 09:24 UTC, remilapeyre commented
> Perhaps you've got some privacy settings set in a non-standard way?
The "Allow edits from maintainers." box is checked and I don't think I changed anything. I granted you rights on my fork, let me know if you're still blocked.

2019-06-12 09:54 UTC, taleinat commented
> 
> 
> > Perhaps you've got some privacy settings set in a non-standard way?
> 
> The "Allow edits from maintainers." box is checked and I don't think I changed anything. I granted you rights on my fork, let me know if you're still blocked.

Ah, sorry, the problem was on my side; fixed now!

2019-06-12 10:00 UTC, taleinat approved these changes

2019-06-12 10:08 UTC, miss-islington commented
@remilapeyre: Status check is done, and it's a failure ❌ .

2019-06-12 10:11 UTC, remilapeyre commented
Not sure what the status check is, @taleinat should I backport manually?

2019-06-12 10:13 UTC, miss-islington commented
@remilapeyre: Status check is done, and it's a failure ❌ .

2019-06-12 10:14 UTC, taleinat commented
> 
> 
> Not sure what the status check is, @taleinat should I backport manually?

No, please ignore those messages. They seem to be caused by a bug in Miss Islington.

2019-06-12 10:17 UTC, miss-islington commented
@remilapeyre: Status check is done, and it's a failure ❌ .

2019-06-12 10:21 UTC, taleinat commented
> 
> 
> > Not sure what the status check is, @taleinat should I backport manually?
> 
> No, please ignore those messages. They seem to be caused by a bug in Miss Islington.

Or maybe Miss Islington was just made aware of the failure earlier...

2019-06-12 10:23 UTC, ZackerySpytz commented
The commit message should use "robots.txt", not "robot.txt".

2019-06-12 15:04 UTC, berkerpeksag requested changes
Good catch! I just left very minor comments. Otherwise it looks good to me.

2019-06-12 15:04 UTC, berkerpeksag commented on Lib/urllib/robotparser.py
> +        else:
The `else` branch isn't needed:

```py
if self.default_entry:
    return self.default_entry.delay
return None
```

2019-06-12 15:04 UTC, berkerpeksag commented on Lib/urllib/robotparser.py
> +        else:
Same as above.

2019-06-12 15:04 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2019-06-11-19-34-29.bpo-35922.rxpzWr.rst
> +Fix :meth:`RobotFileParser.crawl_delay()` and
Nit: () can be removed. Sphinx will it add it automatically.

2019-06-12 15:04 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2019-06-11-19-34-29.bpo-35922.rxpzWr.rst
> +:meth:`RobotFileParser.request_rate()` to return ``None`` rather than
Nit: () can be removed. Sphinx will it add it automatically.

2019-06-12 15:04 UTC, berkerpeksag commented on Lib/test/test_robotparser.py
> +    robots_txt = ""
Nit: Please use single quotes.

2019-06-12 18:35 UTC, taleinat commented
I have made the requested changes; please review again.

2019-06-14 13:38 UTC, taleinat commented
@berkerpeksag, just awaiting your final okay, and I'll go about backporting this.

2019-06-15 10:29 UTC, berkerpeksag approved these changes
Good catch! Thank you for fixing this.

2019-06-16 06:48 UTC, merged

2019-06-16 06:49 UTC, miss-islington commented
Thanks @remilapeyre for the PR, and @taleinat for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖