bpo-21269: Provide args and kwargs attributes on mock call objects
python/cpython pull request #11807
Opened 2019-02-10 09:13 UTC by kakshay21

https://bugs.python.org/issue21269
This PR tries to add this functionlity
```
➜  cpython git:(fix-issue-21269) ✗ ./python.exe
Python 3.8.0a0 (heads/fix-issue-21269-dirty:2433a2ab70, Feb 10 2019, 14:24:54)
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest.mock import Mock
>>> m = Mock()
>>> m(1, a=23)
<Mock name='mock()' id='4552188368'>
>>> m.call_args
call(1, a=23)
>>> m.call_args.args     #after this patch
(1,)
>>> m.call_args.kwargs   #after this patch
{'a': 23}
>>> m.call_args_list[0].args    #after this patch
(1,)
>>> m.call_args_list[0].kwargs   #after this patch
{'a': 23}
```

2019-02-10 16:02 UTC, remilapeyre commented
Hi @kakshay21, this patch looks fine but you will need to add a test and add both attributes to `call` documentation.

2019-02-10 19:23 UTC, kakshay21 commented
@remilapeyre I've added tests and some documentation. Let me know if I've to add more.

2019-02-10 23:47 UTC, remilapeyre approved these changes
Thanks!

2019-02-15 10:19 UTC, kakshay21 commented
@remilapeyre any update on this?

2019-02-16 12:52 UTC, remilapeyre commented
Hi @kakshay21, the patch, tests and documentation looks fine to me, that's why I approved your pull request (please don't force push though next time as it makes all previous messages loose their context and your whole PR will get squash anyway).

A Python core developer will now make a final review (and may ask you other changes). There is very few of them and their attention can get stretched on many issues so it may take some time, don't worry about it.

2019-03-18 22:22 UTC, cjw296 commented on Misc/NEWS.d/next/Library/2019-02-10-16-49-16.bpo-21269.Fqi7VH.rst
> +objects. Contributed by Kumar Akshay.
This could be better worded as "Add args and kwards propery to mock call objects".

2019-03-18 22:22 UTC, cjw296 commented on Doc/library/unittest.mock.rst
> +        form of a tuple: the first member is ``args`` which will be any ordered
I'd prefer this to be "the first member, which can also be accessed through the ``args`` property", and likewise with kwargs below.

2019-03-20 10:28 UTC, kakshay21 commented
Thanks! @cjw296

2019-03-22 06:56 UTC, cjw296 requested changes

2019-03-22 06:56 UTC, cjw296 commented on Misc/NEWS.d/next/Library/2019-02-10-16-49-16.bpo-21269.Fqi7VH.rst
> +Add args and kwards propery to mock call objects. Contributed by Kumar Akshay.
Typos in `kwards` and `propery` need fixing. args and kwargs should likely be surrounded by double back ticks, as in the docs, as it looks line NEWS is ReST too.

2019-03-22 07:19 UTC, kakshay21 commented
I have made the requested changes; please review again

2019-03-22 07:47 UTC, cjw296 approved these changes

2019-03-22 08:10 UTC, merged

2019-03-22 08:10 UTC, miss-islington commented
Thanks @kakshay21 for the PR, and @cjw296 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-03-22 08:10 UTC, miss-islington commented
Sorry, @kakshay21 and @cjw296, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker b0df45e55dc8304bac0e3cad0225472b84190964 3.7
                                ```

2019-04-01 21:17 UTC, cjw296 commented
@tirkarthi / @mariocj89 - would either of you be able to tackle the backport? I've not used cherry-picker before and this is the first time @miss-islington hasn't succeeded in the merge (which makes me a little scared!)

2019-04-01 22:18 UTC, tirkarthi commented
This more seems like an enhancement/feature to me. Is it worth backporting to 3.7?

2019-04-02 06:51 UTC, cjw296 commented
@tirkarthi - good call, sorry, brain not fully working. Guess that means there's nothing to do here?

2019-04-02 07:00 UTC, tirkarthi commented
No problem, I think the "need backport to 3.7" label can be removed and the issue on tracker can be closed.