bpo-36942: Delegate on PyOS_FSPath when checking for __fspath__ in path_converter
python/cpython pull request #11831
Opened 2019-02-12 22:32 UTC by pablogsal

2019-02-12 22:37 UTC, ZackerySpytz commented
The issue number is wrong.

2019-02-12 22:38 UTC, ZackerySpytz commented on Modules/posixmodule.c
> +        if (res == NULL){
This doesn't comply with PEP 7.

2019-02-12 22:40 UTC, pablogsal commented on Modules/posixmodule.c
> +        if (res == NULL){
Fixed!

2019-02-17 06:42 UTC, serhiy-storchaka requested changes
I don't like this. It makes error messages for incorrect type of arguments worse.

Change only error messages for `__fspath__()` returning incorrect result.

2019-02-17 19:29 UTC, pablogsal commented
@serhiy-storchaka I have changed the approach to only correct messages for `__fspath__()` returning an incorrect result.

I have made the requested changes; please review again

2019-02-18 05:31 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +        if (PyUnicode_Check(o)) {
Move this up, before line 971 (using `res` instead of `o`).

2019-02-18 05:31 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +            Py_DECREF(o);
This line and the next one are not needed.

2019-02-18 05:31 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +            Py_DECREF(o);
Replace this line and the next one with just `Py_DECREF(res)`.

2019-02-18 05:31 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +        PyObject *res = NULL;
No need to initialize `res` and `func` with NULL.

2019-02-18 08:36 UTC, pablogsal commented
@serhiy-storchaka Thank you very much for the thorough review! I have addressed your feedback in 477daf8.

2019-02-18 09:13 UTC, serhiy-storchaka approved these changes

2019-02-18 09:14 UTC, serhiy-storchaka commented
I think this bugfix is forth a news entry.

2019-02-18 09:25 UTC, ambv approved these changes
Thanks for jumping on this so quickly, @pablogsal!

2019-02-18 09:38 UTC, eamanu commented on Modules/posixmodule.c
> +        Py_DECREF(o);
A little question, Why don't make `Py_DECREF(res);` too?

2019-02-18 09:40 UTC, serhiy-storchaka approved these changes

2019-02-18 10:46 UTC, merged

2019-02-18 10:46 UTC, miss-islington commented
Thanks @pablogsal for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖