bpo-34235: PyArg_ParseTupleAndKeywords: support required keyword arguments
python/cpython pull request #11834
Opened 2019-02-13 01:56 UTC by msullivan

This adds a `@` glyph to the PyArg_ParseTupleAndKeywords that
specifies that subsequent arguments are required keyword-only
arguments. It must appear after `|` and `$`, and allows functions to
take all four combinations of positional/named-only
v. required/optional arguments.

The restriction that `@` only appear after `|` and `$` have already
appeared is because it substantially simplifies the state machine and
because `$` already only works properly when `|` is specified (though
this is not *checked*).

2019-02-18 07:23 UTC, auvipy approved these changes

2019-02-18 23:58 UTC, vstinner commented
@serhiy-storchaka: Would you mind to review this PR?

2019-02-19 06:29 UTC, serhiy-storchaka commented
I want to try other options first.

2019-02-21 02:40 UTC, msullivan commented
I'm working on trying out some of the other options that Serhiy suggested, but have been busy

2022-12-07 19:23 UTC, iritkatriel requested changes
This has merge conflicts now, as well as an unresolved discussion.

2022-12-07 21:38 UTC, closed without merging