gh-118331: Don't raise an error if tuple allocation fails when clearing weakrefs
python/cpython pull request #118338
Opened 2024-04-26 23:30 UTC by mpage

It's not safe to raise an exception in `PyObject_ClearWeakRefs()` if one is not already set, since it may be called by `_Py_Dealloc()` and hit https://github.com/python/cpython/blob/5a90de0d4cbc151a6deea36a27eb81b192410e56/Objects/object.c#L2843-L2860

Additionally, make sure we clear the weakrefs even when tuple allocation fails.

This bug predates gh-111926. If it's getting tickled now, I suspect it's because we always allocate a tuple now when clearing weakrefs that have callbacks, so we're more likely to hit an allocation failure.

2024-04-27 04:39 UTC, Fidget-Spinner approved these changes

2024-04-27 08:50 UTC, hugovk commented
Thanks, this fixes gh-118331 for me.

2024-04-29 14:51 UTC, colesbury approved these changes
Thanks!

2024-04-29 15:03 UTC, colesbury requested changes

2024-04-29 15:03 UTC, colesbury commented on Objects/weakrefobject.c
> +        }
Hmm... I think this should instead be:

```suggestion
        PyErr_WriteUnraisable(NULL);
        PyErr_SetRaisedException(exc);
```

In other words, write the unraisable exception and then restore the previous active exception, if any.

I don't think we should chain exceptions. The assertion in `_Py_Dealloc` checks that the exception did not change, but as written we would end up changing the exception if there was previously an active one.

2024-04-29 15:03 UTC, colesbury commented on Objects/weakrefobject.c
> +        }
For an example of this pattern see _PyGen_Finalize:

https://github.com/python/cpython/blob/23d0371bb99b1df183c36883e256f82fdf6a4bea/Objects/genobject.c#L81-L89

2024-04-29 16:34 UTC, mpage commented
I have made the requested changes; please review again.

2024-04-29 16:38 UTC, colesbury approved these changes

2024-04-29 16:56 UTC, merged