gh-118473: Fix set_asyncgen_hooks not to allow partial setup
python/cpython pull request #118474
Opened 2024-05-01 13:05 UTC by youknowone

2024-05-01 18:24 UTC, gvanrossum commented
I am starting to review. Please do not force push any more -- you can add new commits, and we will squash them when we merge the code.

2024-05-01 18:41 UTC, gvanrossum requested changes
I'm sorry, I don't like how you separated the audit calls from the setter functions, since it's conceivable that other (internal) code might call them, and the changes should always be audited.

I think a better refactoring would be to save the current finalizer hook and if setting the firstiter hook fails, restore the original finalizer. It still makes sense of course to do both callable checks before making any of the setter calls.

(Note that in your current PR there is a possible scenario where the second audit hook fails, no setters are called, but the first audit hook has already been called.)

Also, CC @zooba.

2024-05-01 18:41 UTC, gvanrossum commented on Misc/NEWS.d/next/Core and Builtins/2024-05-01-22-43-54.gh-issue-118473.QIvq9R.rst
> +Fix set_asyncgen_hooks not to be partially set when raising TypeError
Please make this proper ReST markup with links to the code for `set_asyncgen_hooks` and `TypeError`, and end the sentence with a period. (I can help with the markup but consulting other news files should give ample examples.)

2024-05-02 03:02 UTC, youknowone commented
@gvanrossum Thank you for the guide!

I have made the requested changes; please review again

2024-05-07 00:02 UTC, gvanrossum approved these changes
Thanks! LGTM. I will merge this now, so it will make it into beta 1. Congrats!

2024-05-07 00:02 UTC, merged

2024-05-07 00:03 UTC, gvanrossum commented
@youknowone Do you think this should be backported to Python 3.12? It's a pure bugfix, so I think it could be.

2024-05-07 07:14 UTC, youknowone commented
@gvanrossum No opinion about it. I found this bug not by running code, but by watching CPython source code. It is hard to imagine real world code make a try-except block for `sys.set_asyncgen_hooks`.

2024-05-07 15:44 UTC, gvanrossum commented
Then let's not backport.