[3.12] gh-101137: Add `text/x-rst` to `mimetypes` (GH-118593)
python/cpython pull request #118599
Opened 2024-05-05 15:49 UTC by sobolevn

(cherry picked from commit 1511bc95c4bc95bd35599dc9c88111c9aac44c0d)

2024-05-05 16:28 UTC, jaraco requested changes
Let's hold off on merging this until there's a decision on https://github.com/python/cpython/pull/118594 (and only include this backport if markdown is backported and there's no objection to merging this one).

2024-11-10 08:14 UTC, hugovk commented
> Let's hold off on merging this until there's a decision on #118594 (and only include this backport if markdown is backported and there's no objection to merging this one).

That was merged, albeit with a post-merge objection: https://github.com/python/cpython/pull/118594#issuecomment-2271870657

Maybe close this backport?

2024-11-10 14:54 UTC, jaraco commented
> > Let's hold off on merging this until there's a decision on #118594 (and only include this backport if markdown is backported and there's no objection to merging this one).
> 
> That was merged, albeit with a post-merge objection: [#118594 (comment)](https://github.com/python/cpython/pull/118594#issuecomment-2271870657)
> 
> Maybe close this backport?

I wouldn't characterize that as a post-merge objection, more an objection about the process than the change itself. Since the markdown change was backported and not reverted, it seems prudent to also backport the rst change, as those two changes were symmetrical. I advocate to merge this change.

2024-11-10 14:54 UTC, jaraco approved these changes

2025-04-08 10:40 UTC, merged