gh-118868: logging QueueHandler fix passing of kwargs
python/cpython pull request #118869
Opened 2024-05-09 20:41 UTC by Kaundur

2024-05-09 21:16 UTC, nineteendo commented on Lib/test/test_logging.py
> +    def test_118868(self):
```suggestion
    # gh-118868: check if kwargs are passed to logging QueueHandler
    def test_kwargs_passing(self):
```

2024-05-11 20:21 UTC, dolfinus commented on Lib/logging/config.py
>          rhl = kwargs.get('respect_handler_level', False)
Shouldn't there be `.pop()` as well?

2024-05-13 16:23 UTC, Kaundur commented on Lib/logging/config.py
>          rhl = kwargs.get('respect_handler_level', False)
Yes you are correct, 'respect_handler_level' should have been included

2024-05-13 16:37 UTC, vsajip requested changes

2024-05-13 16:37 UTC, vsajip commented on Lib/logging/config.py
> +            rhl = False
```suggestion
        rhl = kwargs.pop('respect_handler_level', False)
```

2024-05-13 16:37 UTC, vsajip commented on Lib/logging/config.py
> +
Use the same approach as suggested above: 
```python
lklass = kwargs.pop('listener', logging.handlers.QueueListener)
handlers = kwargs.pop(`handlers`, [])
```

2024-05-13 17:23 UTC, Kaundur commented
I have made the requested changes; please review again

2024-06-04 11:38 UTC, vsajip approved these changes

2024-06-04 11:48 UTC, merged