Docs: fix typos in documentation
python/cpython pull request #118815
Opened 2024-05-09 04:09 UTC by xyb

2024-05-09 08:26 UTC, vsajip requested changes
The other changes look fine to me.

2024-05-09 08:26 UTC, vsajip commented on Doc/library/bz2.rst
> +    ... pulvinar a. Nam gravida euismod magna, non various justo tincidunt feugiat.
This is not a typo, it's Latin - you can leave it as is.

2024-05-09 08:26 UTC, vsajip commented on Doc/library/bz2.rst
> +    ... pulvinar a. Nam gravida euismod magna, non various justo tincidunt feugiat.
This is not a typo, it's Latin - you can leave it as is.

2024-05-09 18:42 UTC, Privat33r-dev requested changes
Please, revert the latin changes as suggested. Other changes are good, thank you for your contribution.

2024-05-09 18:42 UTC, Privat33r-dev commented on Doc/library/bz2.rst
> +    ... pulvinar a. Nam gravida euismod magna, non various justo tincidunt feugiat.
```suggestion
    ... pulvinar a. Nam gravida euismod magna, non varius justo tincidunt feugiat.
```

2024-05-09 18:42 UTC, Privat33r-dev commented on Doc/library/bz2.rst
> +    ... pulvinar a. Nam gravida euismod magna, non various justo tincidunt feugiat.
```suggestion
    ... pulvinar a. Nam gravida euismod magna, non varius justo tincidunt feugiat.
```

2024-05-10 03:34 UTC, xyb commented
@vsajip @Privat33r-dev Thank you for your advices. I have made the requested changes; please review again.

2024-05-10 07:57 UTC, Privat33r-dev approved these changes

2024-05-10 08:09 UTC, vsajip approved these changes

2024-05-10 08:11 UTC, merged