gh-118469: Add missing PEP-249 constructors
python/cpython pull request #118975
Opened 2024-05-12 17:57 UTC by firat-v

2024-05-12 20:41 UTC, kalebers approved these changes

2024-05-14 18:12 UTC, erlend-aasland requested changes
Thanks for the PR! I don't think we should expose implementation details; instead, try to (re)use the wording of PEP-249 (or adapt it to fit within the `sqlite3` docs).

2024-07-27 07:13 UTC, erlend-aasland commented
> Thanks for the PR! I don't think we should expose implementation details; instead, try to (re)use the wording of [PEP-249](https://peps.python.org/249) (or adapt it to fit within the `sqlite3` docs).

No response for more than two months. Applied the `pending` label.

2024-07-27 07:14 UTC, erlend-aasland commented
There is also a competing PR up:

- #122091

2025-06-26 14:26 UTC, firatv commented
I apologise for not being around for so long. I checked the preview, seems like everything is set. I assume I should close this PR. Thank you all for your time, attention and efforts. Also, sorry again.

2025-06-26 14:26 UTC, closed without merging