bpo-35899: Fix Enum handling of empty and weird strings
python/cpython pull request #11891
Opened 2019-02-16 07:06 UTC by bdbaraban

Co-authored-by: Maxwell <maxwellpxt@gmail.com>
Co-authored-by: Stéphane Wirtel <stephane@wirtel.be>

2019-02-18 08:03 UTC, matrixise approved these changes
LGTM

Thank you for your contribution.

2019-02-20 12:38 UTC, matrixise commented
@ethanfurman do you want to review/merge this PR?

Have a nice day,

2019-02-21 21:16 UTC, ethanfurman requested changes
Looking pretty good!  A couple more changes and this should be ready to go.

2019-02-21 21:16 UTC, ethanfurman commented on Lib/test/test_enum.py
> +        empty_abc = Enum('empty_abc', ('', 'B', 'C'))
This test should fail with a `ValueError` as empty strings for names are not allowed (include check in line 154 in enum.py).

2019-02-21 21:16 UTC, ethanfurman commented on Lib/test/test_enum.py
> +        weird_abc = Enum('weird_abc', ('!', 'B', 'C'))
Use non-latin letters and numbers for this check as those are supported, but exclamation points, etc., are not supported.

2019-02-23 00:10 UTC, bdbaraban commented
I have made the requested changes; please review again

Thank you, Ethan. I've updated both files accordingly.

2019-03-03 19:31 UTC, ethanfurman requested changes
One more minor change and this PR is good to go!  Nice work!

2019-03-03 19:31 UTC, ethanfurman commented on Misc/NEWS.d/next/Library/2019-02-16-07-11-02.bpo-35899.cjfn5a.rst
> +Enum has been fixed to correctly handle empty strings and strings with "weird" characters (ie. '!') without crashing. Original patch contributed by Maxwell. Assisted by Stéphane Wirtel.
Please change the exclamation point and weird characters comment to an alphanumeric unicode comment.

2019-03-03 22:00 UTC, ethanfurman approved these changes

2019-03-03 22:09 UTC, miss-islington commented
@bdbaraban: Status check is done, and it's a success ✅ .

2019-03-03 22:09 UTC, merged

2019-03-03 22:09 UTC, miss-islington commented
Thanks @bdbaraban for the PR 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖