bpo-35126: Fix a mistake in FAQ about converting number to string
python/cpython pull request #11911
Opened 2019-02-18 09:17 UTC by matrixise

2019-02-18 13:17 UTC, JulienPalard requested changes

2019-02-18 13:17 UTC, JulienPalard commented on Doc/faq/programming.rst
> +``division`` from :mod:`__future__` ::
I think you should not put a space before `::`.

By adding the space, the code bloc will still be properly introduced, but the `:` won't be rendered, and as you did not put a dot at the end of the sentense, I think you'd like the `:` to be rendered, so, so space before `::`.

2019-02-19 08:26 UTC, matrixise commented
@JulienPalard just updated, if you want to review.

2019-02-19 09:25 UTC, JulienPalard approved these changes
Thanks for the PR @matrixise :)

2019-02-19 09:26 UTC, merged