Use consistent case for HTTP header fields
python/cpython pull request #11924
Opened 2019-02-18 22:30 UTC by maggyero

Use consistent case for HTTP header fields, according to [RFC 7231](https://tools.ietf.org/html/rfc7231).

2019-02-19 08:23 UTC, JulienPalard requested changes
Hi and thanks for the PR @maggyero !

Tests are failing, I'll let you take a look at why. Anyway, beware of not breaking any backward compatibility here.

Have you checked in the git log why this capitalisation is used in the first place?

2019-02-19 08:32 UTC, maggyero commented
Salut @JulienPalard ! I updated my post to show the motivation behind this PR.
Yes tests are failing for 3 header fields: `User-Agent`, `Content-Length` and `Transfer-Encoding`.
For the 1st one I missed 3 location to update so I will do a new commit. For the others I am still investigating (it seems that the `str.capitalize` method in urllib is the culprit but I am not sure).

2019-02-19 09:06 UTC, JulienPalard commented
As @matrixise is highlighting in the issue, it may not be worth the effort: The spec also tells the headers are case insensitive.

So there may be debate: That's not because they're case insensitive that we should output an ugly mix of capitalization. 

But is it worth the work?

It would have been a simple commit fixing only documentation, OK let's fix it.

But touching unit test, and finding "subtle problems" doing so... may be not worth it.

2019-02-20 20:14 UTC, brettcannon commented
While I appreciate the work and enthusiasm to fix this, I agree with @matrixise and @JulienPalard  don't think the churn and risk of breaking code (as already shown by failing tests).

I think cleaning up the docs is fine, but code itself shouldn't be touched for this. Do you want to re-target this PR for just docs, @maggyero , or start a new PR?

2019-02-20 20:14 UTC, brettcannon requested changes
Changing code isn't worth the churn and risk of breaking code. Updating the PR to only target documentation would be great, though!

2019-02-23 15:37 UTC, maggyero commented
@JulienPalard @matrixise @brettcannon Problem solved, all tests are passing.

Here is what happened: at first I simply greped all capitalize-case string literals of RFC 7231 HTTP header fields in the entire CPython repository and converted them to title-case.

Example of capitalize-case (Python method `str.capitalize()`): "User-agent"
Example of title-case (Python method `str.title()`): "User-Agent"

But 18 tests were failing involving the "Content-Length", "Transfer-Encoding", "Proxy-Authorization" and "User-Agent" header fields:

* 5 in Lib/distutils/tests/test_register.py
* 12 in Lib/test/test_urllib2.py
* 1 in Lib/test/test_urllib2net.py

So I had to revert to capitalize-case the header fields of the following files:

* Lib/distutils/tests/test_register.py
* Lib/distutils/tests/test_upload.py
* Lib/test/test_urllib2.py
* Lib/test/test_urllib2net.py
* Lib/urllib/request.py

Then all tests were passing.

This was because the class `urllib.Request` normalize given header fields to capitalize-case before adding them to a request:

```
    def add_header(self, key, val):
        # useful for something like authentication
        self.headers[key.capitalize()] = val

    def add_unredirected_header(self, key, val):
        # will not be added to a redirected request
        self.unredirected_hdrs[key.capitalize()] = val
```

Apparently this is done for backwards compatibility, as stated in this docstring in Lib/test/test_urllib2.py:


```
    def test_request_headers_methods(self):
        """
        Note the case normalization of header names here, to
        .capitalize()-case.  This should be preserved for
        backwards-compatibility.  (In the HTTP case, normalization to
        .title()-case is done by urllib2 before sending headers to
        http.client).

        Note that e.g. r.has_header("spam-EggS") is currently False, and
        r.get_header("spam-EggS") returns None, but that could be changed in
        future.

        Method r.remove_header should remove items both from r.headers and
        r.unredirected_hdrs dictionaries
        """
        […]
```

And as stated, the class `urllib.AbstractHTTPHandler` normalize request header fields to title-case before adding them to a response:


```
    def do_open(self, http_class, req, **http_conn_args):
        """Return an HTTPResponse object for the request, using http_class.

        http_class must implement the HTTPConnection API from http.client.
        """
        host = req.host
        if not host:
            raise URLError('no host given')

        # will parse host:port
        h = http_class(host, timeout=req.timeout, **http_conn_args)
        h.set_debuglevel(self._debuglevel)

        headers = dict(req.unredirected_hdrs)
        headers.update({k: v for k, v in req.headers.items()
                        if k not in headers})

        # TODO(jhylton): Should this be redesigned to handle
        # persistent connections?

        # We want to make an HTTP/1.1 request, but the addinfourl
        # class isn't prepared to deal with a persistent connection.
        # It will try to read all remaining data from the socket,
        # which will block while the server waits for the next request.
        # So make sure the connection gets closed after the (only)
        # request.
        headers["Connection"] = "close"
        headers = {name.title(): val for name, val in headers.items()}
        […]
```

To sum up, Urllib requests uses capitalize-case normalization on header fields while Urllib *HTTP* responses uses title-case normalization. That is why the title-case normalization of header fields string literals that I applied on all the repository made some tests involving Urllib fail.

Now the reason why I applied this title-case normalization in the first place was to have a "Content-Type" header field instead of the inconsistent "Content-type" one in the HTTP responses generated by the class `http.server.SimpleHTTPRequestHandler`. So this PR might be overkill. I could have just updated the following 2 lines in Lib/http/server.py:

```
-           self.send_header("Content-type", ctype)
+           self.send_header("Content-Type", ctype)
```

```
-       self.send_header("Content-type", "text/html; charset=%s" % enc)
+       self.send_header("Content-Type", "text/html; charset=%s" % enc)
```

and optionally/or added this line (to make sure given header fields are always title-case normalized):

```
    def send_header(self, keyword, value):
        """Send a MIME header to the headers buffer."""
+       keyword = keyword.title()
        if self.request_version != 'HTTP/0.9':
            if not hasattr(self, '_headers_buffer'):
                self._headers_buffer = []
            self._headers_buffer.append(
                ("%s: %s\r\n" % (keyword, value)).encode('latin-1', 'strict'))

        if keyword.lower() == 'connection':
            if value.lower() == 'close':
                self.close_connection = True
            elif value.lower() == 'keep-alive':
                self.close_connection = False```

```

So if you still think that this PR might break some client code, we can keep only the 2 above corrected lines (`self.send_header`) in Lib/http/server.py (that way we don't touch any tests and are sure that client code will not break), and optionally/or add the 3rd line (`keyword = keyword.title()`). Let me know what you think, I am fine with both solutions.

2019-02-28 01:35 UTC, brettcannon commented
I'm still not comfortable changing any code (tests don't prove the absence of bugs, only that specific tests are passing).

2019-02-28 06:12 UTC, asvetlov commented
I agree with @brettcannon @JulienPalard and others: header names *don't need* to be title-cased.
They are case-insensitive by the RFC (https://tools.ietf.org/html/rfc7230#section-3.2 if you need an exact reference). 

Changing the code is not necessary, a change to make a regression is very high. At least we had that in aiohttp once or twice, despite the fact that aiohttp uses case-insensitive headers comparator. The problem was in case-sensitive (and obviously buggy) code on peer side.

I'm 100% ok with updating documentation though.

2019-03-03 11:13 UTC, maggyero commented
@JulienPalard @brettcannon @asvetlov Since HTTP headers have no defined case, HTTP clients (Web browsers, Curl, the  library `requests`) should be header case insensitive, which they are. So if some client code on top of them is header case sensitive, it actually _should_ break, so that it can be fixed.

I am not confortable with documenting that, contrary to the library `urllib` (more precisely the class `urllib.AbstractHTTPHandler`), the library `http` (more precisely the class `http.server.SimpleHTTPRequestHandler`) does not title-case normalize the HTTP headers in the HTTP responses that it generates, and that contrary to all other HTTP headers which are output in title-case, "Content-Type" is output in capitalize-case: "Content-type", but only in responses to GET and HEAD HTTP requests with a status code that is not a client or server error (4xx or 5xx). That would make no sense to Python users.

Let's at least correct this "Content-type" header in the class `http.server.SimpleHTTPRequestHandler` like suggested in the alternative solution. I don't mind about the other changes in this PR.

2019-03-05 01:33 UTC, brettcannon commented
@maggyero Then don't document this detail (when I said "update the docs" I meant make the case consistent so it looks nice).

I am now saying it for the last time: I am not comfortable changing this code just for the idea of completeness. If another core dev wants to dismiss my review then that's totally fine, but my view has not changed.

2019-03-05 13:12 UTC, maggyero commented
@brettcannon Okay as the majority is against this PR I will close it. Thank you for taking the time to review it.

2019-03-05 13:13 UTC, closed without merging

2019-03-05 21:55 UTC, brettcannon commented
@maggyero thanks for trying to get this through! I know it's always disappointing to not get one's PR committed, but hopefully you understand where we're coming from.