gh-115225: Raise error on unsupported ISO 8601 time strings
python/cpython pull request #119339
Opened 2024-05-21 18:44 UTC by benchatt

Some time strings that contain fractional hours or minutes are permitted by ISO 8601, but such strings are very unlikely to be intentional. The current parser does not parse such strings correctly or raise an error. This change raises a ValueError when hours or minutes contain a decimal mark.

2024-05-22 16:12 UTC, pganssle requested changes
This looks good to me, but can you add a test case?

2024-05-22 17:37 UTC, benchatt commented
I have made the requested changes; please review again

2024-05-22 21:21 UTC, pganssle approved these changes

2024-05-24 00:42 UTC, pganssle approved these changes
One last thing before merge is I realized that this patch doesn't credit you. Do you want to add yourself to the news fragment and the [ACKS file](https://github.com/python/cpython/blob/main/Misc/ACKS)?

Those are not required, but it's commonly done and good to give credit where credit is due. 😅

2024-05-24 00:42 UTC, pganssle commented on Misc/NEWS.d/next/Library/2024-05-21-19-10-30.gh-issue-115225.eRmfJH.rst
> +Raise error on certain technically valid but pathological ISO 8601 strings passed to :meth:`datetime.time.fromisoformat` that were previously parsed incorrectly.
If you want you can put (Patch by ...) with whatever name you are comfortable using here at the end of this file

2024-05-24 02:21 UTC, benchatt commented
Sure thing, I'm on a plane right now but I'll try to add those when I can

On Thu, May 23, 2024, 20:42 Paul Ganssle ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> One last thing before merge is I realized that this patch doesn't credit
> you. Do you want to add yourself to the news fragment and the ACKS file
> <https://github.com/python/cpython/blob/main/Misc/ACKS>?
>
> Those are not required, but it's commonly done and good to give credit
> where credit is due. 😅
> ------------------------------
>
> In Misc/NEWS.d/next/Library/2024-05-21-19-10-30.gh-issue-115225.eRmfJH.rst
> <https://github.com/python/cpython/pull/119339#discussion_r1612516963>:
>
> > @@ -0,0 +1 @@
> +Raise error on certain technically valid but pathological ISO 8601 strings passed to :meth:`datetime.time.fromisoformat` that were previously parsed incorrectly.
>
> If you want you can put (Patch by ...) with whatever name you are
> comfortable using here at the end of this file
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/python/cpython/pull/119339#pullrequestreview-2075364564>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB4PWEAVV54EXYJMLJDMMNDZD2EHBAVCNFSM6AAAAABICFM2M6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZVGM3DINJWGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-24 15:16 UTC, benchatt commented
> One last thing before merge is I realized that this patch doesn't credit you. Do you want to add yourself to the news fragment and the [ACKS file](https://github.com/python/cpython/blob/main/Misc/ACKS)?
> 
> Those are not required, but it's commonly done and good to give credit where credit is due. 😅

Alright, those are ready! Let me know if anything's out of sync or unusual and I'll fix it. Thanks again!

2024-05-26 22:53 UTC, benchatt commented
I have made the requested changes; please review again

2024-05-28 18:23 UTC, benchatt commented
@pganssle Not sure I was supposed to call on Bedevere again. Sorry about that!

2024-06-01 19:04 UTC, benchatt commented
Just would like to ping real quick one more time, sorry for the bother
@pganssle

On Sun, May 26, 2024, 15:54 bedevere-app[bot] ***@***.***>
wrote:

> Thanks for making the requested changes!
>
> @pganssle <https://github.com/pganssle>: please review the changes made
> to this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/python/cpython/pull/119339#issuecomment-2132422100>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB4PWEDJM2A7LTUBM6Z5GZLZEJRZNAVCNFSM6AAAAABICFM2M6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMZSGQZDEMJQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-05 17:34 UTC, pganssle approved these changes

2024-06-05 17:35 UTC, merged