Updated queue.py
python/cpython pull request #11938
Opened 2019-02-19 12:03 UTC by zahash

added __repr__() method to the PriorityQueue class and LifoQueue class

2019-02-19 12:03 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-02-19 15:57 UTC, remilapeyre commented
Hi @zahash, as the message says when opening a pull request on GitHub:

Thanks

>  for your contribution!
> Please read this comment in its entirety. It's quite important.
> 
> # Pull Request title
> 
> It should be in the following format:
> 
> ```
> bpo-NNNN: Summary of the changes made
> ```
> 
> Where: bpo-NNNN refers to the issue number in the https://bugs.python.org.
> 
> Most PRs will require an issue number. Trivial changes, like fixing a typo, do not need an issue.
> 


Please open a ticket on https://bugs.python.org. Your pull request will also need tests and a what's new entry before being reviewed.

2019-02-20 09:47 UTC, eamanu requested changes
please do the @remilapeyre  comments and you will need work on testcases

2019-02-20 09:57 UTC, zahash commented
This is my first pull request so I'm very new to this. Nevertheless, I will
make sure to apply all the necessary changes by Friday

On Wed, 20 Feb 2019, 3:17 pm Emmanuel Arias, <notifications@github.com>
wrote:

> *@eamanu* requested changes on this pull request.
>
> please do the @remilapeyre <https://github.com/remilapeyre> comments and
> you will need work on testcases
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/cpython/pull/11938#pullrequestreview-205661271>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AieqY0Ltfef-p5S17uaLVT9QxLRzrUtvks5vPRnNgaJpZM4bC0LM>
> .
>

2019-02-20 10:00 UTC, eamanu commented
> This is my first pull request so I'm very new to this. Nevertheless, I
> will
> make sure to apply all the necessary changes by Friday
Sure! Not problem!

2019-02-20 11:04 UTC, zahash commented
I just linked the CLA.
can someone please check if it is properly linked?

2019-02-20 12:08 UTC, matrixise commented
Hi @zahash 

1. Add a blurb entry
2. Fix the tests on Travis

3. I have an other PR: https://github.com/python/cpython/pull/11953 where you could check the code.

Have a nice day,

2019-02-20 12:15 UTC, zahash commented
Thank you so much, Stephane. This is actually my very first pull request
and I'm really excited about it.
It would be truly amazing if it gets merged/accepted.
I found this issue while I was working with the PriorityQueue class.

Since I'm new to this, I don't know about "blurb entry" and "fix Travis
tests".
Can you please help me with this?

2019-02-20 12:29 UTC, matrixise commented
Hi @zahash 

1. for the blurb entry
`blurb` is a tool that we use for the documentation of a PR, without that we can not accept a PR (excepted in some cases, Typo fix,...)

You should use `blurb` you can read [this article](https://discuss.python.org/t/blurb-it-is-now-available/528) from @Mariatta where she explains how to use `blurb_it` ([a web service](https://blurb-it.herokuapp.com/)) if you don't want to use the `blurb` tool (it's a CLI)

2. for the tests,
When you modify the code you have to check if the tests will continue to be executed in the future.
For that, you need to execute the tests with `./python -m test test_queue.py -v` in this case. For that, you have compile `python` on your computer

```
> ./configure --prefix=$PWD --with-pydebug`
> make -j 4
> ./python -m test test test_queue.py -v
```

Once you have finished these steps you will have tested your code and your patch.

In my PR, I have modified `Lib/queue.py` and `Lib/test/test_queue.py` and executed the tests.

but one thing, and maybe the most essential, you have to read the devguide
https://devguide.python.org, in this document we expain all the things to know for the contirbuting in Python.

Good luck.

2019-02-20 13:11 UTC, remilapeyre requested changes

2019-02-20 13:11 UTC, remilapeyre commented on Lib/queue.py
> +            return "PriorityQueue(" + str(self.queue[:max_length_to_display - 1]) + " ..... " + str(self.queue[-1]) + ")"
I think you could use the repr here `repr(self.queue[:max_length_to_display - 1])` and others

2019-02-20 13:11 UTC, remilapeyre commented on Lib/queue.py
> +        max_length_to_display = 20
There is a discussion on https://bugs.python.org/issue36049 on whether or not to have a short repr.

If it's decided to have a short repr, I don't think this need to be set as a variable, just write `if len(self.queue) > 20:`.

2019-02-20 13:11 UTC, remilapeyre commented on Lib/queue.py
> +            return "PriorityQueue(" + str(self.queue[:max_length_to_display - 1]) + " ..... " + str(self.queue[-1]) + ")"
`PriorityQueue` should also be `self.__class__.__name__`

2019-02-20 16:56 UTC, closed without merging