Handle `STORE_ATTR_WITH_HINT` in tier two
python/cpython pull request #119481
Opened 2024-05-23 22:07 UTC by brandtbucher

This way we can remove the version check in the optimizer, too!

2024-05-24 09:26 UTC, markshannon requested changes
I'm hoping to remove `STORE_ATTR_WITH_HINT` once almost all instance have inline values.
Until then, this seems like a worthwhile improvement.

One question and a couple of suggestions.

2024-05-24 09:26 UTC, markshannon commented on Include/internal/pycore_dict.h
> +PyAPI_FUNC(void)
Why does this symbol need to be exposed?
It isn't used by the JIT.

2024-05-24 09:26 UTC, markshannon commented on Python/bytecodes.c
>              PyTypeObject *tp = Py_TYPE(owner);
```suggestion
```

This is only used in the assert, AFAICT, so will generate a compiler warning for non-debug builds.

2024-05-24 09:26 UTC, markshannon commented on Python/bytecodes.c
>              assert(tp->tp_flags & Py_TPFLAGS_MANAGED_DICT);
```suggestion
            assert(Py_TYPE(owner)->tp_flags & Py_TPFLAGS_MANAGED_DICT);
```

2024-05-25 14:42 UTC, Fidget-Spinner approved these changes

2024-05-28 19:47 UTC, merged