Clarify the nature of the root logger in the `logging` documentation
python/cpython pull request #119440
Opened 2024-05-22 21:53 UTC by jkunimune

The way it's currently written, it's very confusing what the root logger's name is, because it's not explicitly stated anywhere (the how-to page says that its name "is printed as 'root'", which makes it sound like it's actually something else, but it's not it's just 'root'), and because it is stated that the logging hierarchy is based on period-separated names ("root" is the exception to this rule, and that exception isn't stated anywhere here).

2024-05-23 22:25 UTC, vsajip requested changes

2024-05-23 22:25 UTC, vsajip commented on Doc/library/logging.rst
> +descendants of ``foo``.  In addition, all loggers are descendants of ``root``.
```suggestion
descendants of ``foo``.  In addition, all loggers are descendants of the root logger.
```

2024-05-23 22:25 UTC, vsajip commented on Doc/library/logging.rst
> +   root logger of the hierarchy (equivalent to passing ``name='root'``). If specified, the name is
I don't especially want to encourage the idiom where you fetch the root logger using `name='root'`. For example, code Python 2 doesn't work like this, and while Python 2.x is EOL, there are still environments where it is used (and there might be other environments like Jython where this isn't the case). So I'd prefer to suggest `logging.getLogger()` as the default way of getting the root logger, while perhaps noting that `logging.getLogger('')` or `logging.getLogger(None)` also work for this.

2024-05-25 12:02 UTC, vsajip requested changes
Your response to my earlier comment is fine, but as we're in the area, I thought maybe we can add another suggestion about logger naming. What do you think?

2024-05-25 12:02 UTC, vsajip commented on Doc/library/logging.rst
>     Choice of these names is entirely up to the developer who is using logging.
```suggestion
   Choice of these names is entirely up to the developer who is using logging, though it is recommended that ``__name__`` be used unless you have a specific reason for not doing that, as mentioned in :ref:`logger-objects`.
```

2024-05-25 13:57 UTC, jkunimune commented
Sure, that works for me.  I have made the requested changes; please review again.

2024-05-28 10:30 UTC, vsajip approved these changes

2024-05-28 10:31 UTC, merged