bpo-20582: add link for manpage for flags on getnameinfo()
python/cpython pull request #11977
Opened 2019-02-21 13:56 UTC by eamanu

bpo-20582: add link for manpage for flags on getnameinfo()

This a minor documentation change. I think that the NEWS could be ignore here

2019-02-21 14:13 UTC, matrixise commented
@JulienPalard do we need a blurb entry for this issue? or add the `skip-news` label.

LGTM

2019-02-22 15:36 UTC, JulienPalard commented on Doc/library/socket.rst
> +   `manpage <http://man7.org/linux/man-pages/man3/getnameinfo.3.html>`_.
You could add the name of the manpage so people prefering to consult it locally can easily do.
```suggestion
   `getnameinfo manpage <http://man7.org/linux/man-pages/man3/getnameinfo.3.html>`_.
```

2019-02-22 18:31 UTC, eamanu commented
Ready @JulienPalard

2019-02-23 20:02 UTC, csabella commented
Please take a look at Serhiy's comment on the bug tracker.

2019-02-24 16:06 UTC, eamanu commented
oops!

2019-02-24 16:13 UTC, eamanu commented
Sorry everybody for the noise. I was wrong on the push. 

Thanks @csabella  I make the suggestion

2019-02-28 11:45 UTC, eamanu commented
ping @JulienPalard :-)

2019-04-02 18:00 UTC, brettcannon requested changes

2019-04-02 18:00 UTC, brettcannon commented on Doc/library/socket.rst
> +   For more information about *flags* you can consult on :manpage:`getnameinfo(3)`.
```suggestion
   For more information about *flags* you can consult :manpage:`getnameinfo(3)`.
```

2019-04-03 15:18 UTC, eamanu commented
I have made the requested changes; please review again

2019-04-11 21:13 UTC, brettcannon approved these changes

2019-04-11 21:13 UTC, merged

2019-04-11 21:13 UTC, brettcannon commented
Thanks!