bpo-36073: Raise ProgrammingError on recursive usage of cursors in sqlite converters
python/cpython pull request #11984
Opened 2019-02-22 07:48 UTC by sir-sigurd

2019-06-01 18:39 UTC, auvipy approved these changes

2019-06-01 18:40 UTC, auvipy approved these changes

2019-06-21 22:39 UTC, BoboTiG commented on Lib/sqlite3/test/regression.py
> +class ConverterProggrammingErrorTestCase(unittest.TestCase):
Small typo:
```suggestion
class ConverterProgrammingErrorTestCase(unittest.TestCase):
```

2019-06-21 22:40 UTC, BoboTiG commented
Thanks @sir-sigurd, I think a NEWs entry would be interesting, don't you?

2021-04-01 21:46 UTC, erlend-aasland commented
@sir-sigurd, can you rebase onto master?

2021-04-08 09:09 UTC, erlend-aasland requested changes

2021-04-08 09:09 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +        pysqlite_check_thread(cur->connection) && pysqlite_check_connection(cur->connection);
Please format these lines according to PEP 7.

2021-04-08 09:09 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +        PyErr_SetString(pysqlite_ProgrammingError, "Recursive use of cursors not allowed.");
Line is longer than 79 characters, ref. PEP 7.

2021-04-08 09:09 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +static int check_cursor_locked(pysqlite_Cursor* cur)
PEP 7

```suggestion
static int
check_cursor_locked(pysqlite_Cursor *cur)
```

2021-04-08 09:09 UTC, erlend-aasland commented on Misc/NEWS.d/next/Library/2019-06-22-11-01-45.bpo-36073.ED8mB9.rst
> +Raise ProgrammingError on recursive usage of cursors in sqlite converters.
Missing reST formatting and attribution.

```suggestion
Raise :exc:`~sqlite3.ProgrammingError` on recursive usage of cursors in
:mod:`sqlite3` converters. Patch by Sergey Fedoseev.
```

2021-04-08 09:09 UTC, erlend-aasland commented on Lib/sqlite3/test/regression.py
> +        unittest.makeSuite(ConverterProgrammingErrorTestCase),
This needs to be rebased onto master in order to fit in with the changes in the test suite.

2021-04-09 10:27 UTC, sir-sigurd commented
@erlend-aasland 
I'll try to rebase in the near future, though I almost do not remember anything about this.

2021-04-09 10:29 UTC, erlend-aasland commented
> I'll try to rebase in the near future, though I almost do not remember anything about this.

Thanks, there's no hurry :)

2021-06-16 16:23 UTC, erlend-aasland approved these changes
LGTM!

2021-06-16 16:27 UTC, erlend-aasland commented
@serhiy-storchaka would you mind reviewing this?

2021-11-17 04:17 UTC, sir-sigurd commented
Closed in favor of GH-29054.

2021-11-17 04:17 UTC, closed without merging