bpo-29524: Add Objects/call.c file
python/cpython pull request #12
Opened 2017-02-11 00:38 UTC by haypo

* Move all functions to call objects in a new Objects/call.c file.
* Rename fast_function() to _PyFunction_FastCallKeywords().
* Copy null_error() from Objects/abstract.c
* Inline type_error() in call.c to not have to copy it, it was only
  called once.
* Export _PyEval_EvalCodeWithName() since it is now called
  from call.c.

2017-02-11 07:55 UTC, methane requested changes

2017-02-11 07:55 UTC, methane commented on Python/ceval.c
> -*/
This comment block should be moved to `function_code_fastcall()`.

2017-02-11 13:48 UTC, haypo commented
Oh in fact it was a deliberate choice to remove the comment. Python 3.7 now
has a wide range of "fast call" functions which are designed for best
performance. Do you think that it's worth it to keep the comment?

2017-02-12 04:47 UTC, methane approved these changes
I just checked all code is moved as-is.
I agree the comment block is not so important.

2017-02-12 09:38 UTC, haypo commented
Thank you for the review.

2017-02-12 18:27 UTC, merged

2018-06-25 13:06 UTC, jdemeyer commented
Follow-up at #7909