bpo-29553 - Fixed ArgumentParses format_usage for mutually exclusive groups
python/cpython pull request #120
Opened 2017-02-15 14:21 UTC by andrewnester

Fix for https://bugs.python.org/issue29553
Alternative to https://github.com/python/cpython/pull/117 
This alternative advised by Christoph Stahl and Brian Curtin

2017-02-19 14:21 UTC, berkerpeksag requested changes
See https://github.com/python/cpython/pull/117#discussion_r101918576 about tests I left in #117.

2017-02-19 14:25 UTC, autumnsashes3 commented
No mother f***** is only reason I'm on here is because you m************
keep goddamn f****** with people in real life and in just like in real life
really get somebody killed real f****** quick

On Feb 19, 2017 6:21 AM, "Berker Peksag" <notifications@github.com> wrote:

> *@berkerpeksag* requested changes on this pull request.
>
> See #117 (comment)
> <https://github.com/python/cpython/pull/117#discussion_r101918576> about
> tests I left in #117 <https://github.com/python/cpython/pull/117>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/cpython/pull/120#pullrequestreview-22660718>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYpvdm51qKkgwev80pBJFaist5GxVHkfks5reE_mgaJpZM4MBxVS>
> .
>

2017-02-19 14:26 UTC, autumnsashes3 commented
I don't give two f**** what you guys have to do but fix it and I don't
f****** I hear another thing out of anybody ever the f*** again I swear to
God my niece and nephew get scared because they think somebody standing
outside doesn't matter what it is

On Feb 19, 2017 6:21 AM, "Berker Peksag" <notifications@github.com> wrote:

> *@berkerpeksag* requested changes on this pull request.
>
> See #117 (comment)
> <https://github.com/python/cpython/pull/117#discussion_r101918576> about
> tests I left in #117 <https://github.com/python/cpython/pull/117>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/cpython/pull/120#pullrequestreview-22660718>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYpvdm51qKkgwev80pBJFaist5GxVHkfks5reE_mgaJpZM4MBxVS>
> .
>

2017-02-19 14:27 UTC, autumnsashes3 commented
I mean what kind of f****** person puts human s*** and f****** nasty trash
f****** nasty garbage smelling s*** in somebody's vehicle somebody that
obviously wants to be tortured very long and very f****** painfully

On Feb 19, 2017 6:21 AM, "Berker Peksag" <notifications@github.com> wrote:

*@berkerpeksag* requested changes on this pull request.

See #117 (comment)
<https://github.com/python/cpython/pull/117#discussion_r101918576> about
tests I left in #117 <https://github.com/python/cpython/pull/117>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/python/cpython/pull/120#pullrequestreview-22660718>,
or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AYpvdm51qKkgwev80pBJFaist5GxVHkfks5reE_mgaJpZM4MBxVS>
.

2017-02-19 17:25 UTC, andrewnester commented
@berkerpeksag thanks! just updated my PR.

2017-02-22 13:39 UTC, andrewnester commented
@berkerpeksag any updates? :)

2017-02-22 13:55 UTC, zhangyangyu commented on Misc/NEWS
>    now emit DeprecationWarnings and have better descriptive messages.
We need an empty line here.

2017-02-22 13:57 UTC, andrewnester commented on Misc/NEWS
>    now emit DeprecationWarnings and have better descriptive messages.
@zhangyangyu updated, sorry! thanks!

2017-02-26 20:59 UTC, andrewnester commented
@berkerpeksag any updates on this one? :)

2017-03-12 08:57 UTC, andrewnester commented
@zhangyangyu @berkerpeksag any updates on this? :)

2018-02-21 01:53 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2019-08-31 00:13 UTC, berkerpeksag commented
Superseded by PR #14976.

2019-08-31 00:13 UTC, closed without merging