resolve sinpi name clash with libm (IEEE-754 violation)
python/cpython pull request #12027
Opened 2019-02-25 12:42 UTC by dimpase

the standard math library (libm) may follow IEEE-754 recommendation to
include an implementation of sinPi(), i.e. sinPi(x):=sin(pi*x).
And this triggers a name clash, found by FreeBSD developer
Steve Kargl, who worken on putting sinpi into libm used on FreeBSD
(it has to be named "sinpi", not "sinPi", cf. e.g.
https://en.cppreference.com/w/c/experimental/fpext4)

2019-02-25 12:42 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-02-25 13:49 UTC, dimpase commented
See https://bugs.python.org/issue36106 for the bug report.

2019-02-25 14:53 UTC, eamanu requested changes
Hi, sign the CLA please.

2019-02-25 14:53 UTC, eamanu commented
I put a comment on bpo.

2019-02-25 14:54 UTC, dimpase commented
> Hi, sign the CLA please.

I have done it, just takes a while to get through...

2019-02-25 15:14 UTC, serhiy-storchaka requested changes

2019-02-25 15:14 UTC, serhiy-storchaka commented on Misc/NEWS.d/next/Library/2019-02-25-13-21-43.bpo-36106.VuhEiQ.rst
> +Resolve potential name clash with libm's sinpi()
```suggestion
Resolve potential name clash with libm's sinpi(). Patch by Dmitrii Pasechnik.
```

2019-02-25 16:27 UTC, dimpase commented
A backport to 2.7 would be great, too.

2019-02-25 16:27 UTC, serhiy-storchaka approved these changes

2019-02-26 06:36 UTC, merged

2019-02-26 06:36 UTC, miss-islington commented
Thanks @dimpase for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.7.
🐍🍒⛏🤖

2019-02-26 06:36 UTC, miss-islington commented
Sorry, @dimpase and @serhiy-storchaka, I could not cleanly backport this to `2.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker f57cd8288dbe6aba99c057f37ad6d58f8db75350 2.7
                                ```

2019-02-26 06:38 UTC, serhiy-storchaka commented
Signing the CLA is not necessary for trivial changes.

2019-02-26 06:40 UTC, serhiy-storchaka commented
Thank you for your contribution @dimpase!

Unfortunately, our bot failed to backport this change to 2.7 automatically. Do you mind to backport it manually, if this is needed?

2019-02-26 08:56 UTC, koobs commented
For reference, we (FreeBSD) are tracking this downstream here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232792

2019-02-26 09:38 UTC, dimpase commented
> Unfortunately, our bot failed to backport this change to 2.7 automatically.

OK, sure. The problem is in unrelated to this patch changes to the file in question, which confuse cherry_picker. Working on it.

2019-02-26 09:42 UTC, dimpase commented
> Signing the CLA is not necessary for trivial changes.

according to https://check-python-cla.herokuapp.com/ I've signed the CLA - it's probably not automatically updated...