Improve error message on dbm.open
python/cpython pull request #12060
Opened 2019-02-26 22:50 UTC by rougeth

Improve error message when trying to open existing database that actually doesn't exist.

2019-03-05 13:42 UTC, rougeth commented
The forced-push was just to rebuild on Azure. It was falling for reasons not related to the changes.

2019-03-12 16:30 UTC, remilapeyre approved these changes

2019-04-02 21:10 UTC, brettcannon requested changes

2019-04-02 21:10 UTC, brettcannon commented on Lib/dbm/__init__.py
> +            raise error[0]("db file doesn't exist, "
```suggestion
            raise error[0]("db file doesn't exist; "
```

2019-04-02 21:11 UTC, brettcannon commented
@rougeth mind adding a news file? (And make sure to thank yourself!) You can use blurb-it -- found in the Details link for the bedevere/news CI check -- to add one easily.

2019-04-06 19:57 UTC, rougeth commented
I have made the requested changes; please review again.

2019-04-06 20:00 UTC, rougeth commented
@brettcannon I was looking into the other news entries, found a typo and fixed it, is that ok?

2019-04-26 22:53 UTC, brettcannon approved these changes

2019-04-26 22:54 UTC, brettcannon commented on Lib/dbm/__init__.py
> +                           "use 'c' or 'n' flag to open new db")
```suggestion
                           "use 'c' or 'n' flag to create a new db")
```

2019-04-26 22:54 UTC, brettcannon requested changes
One minor wording change.

2019-04-26 22:55 UTC, brettcannon commented
I would have committed the change myself but GH says I don't have permission to.

2019-04-26 23:10 UTC, rougeth commented
I have made the requested changes; please review again

2019-04-27 01:28 UTC, rougeth commented
@brettcannon I may have blocked PR changes from other people (don't know/remember why :) I believe now it's ok.

2019-04-29 23:23 UTC, merged

2019-04-29 23:23 UTC, brettcannon commented
Thanks!