gh-120784: Fix utc deprecation msg
python/cpython pull request #120791
Opened 2024-06-20 09:52 UTC by nineteendo

It's better to point to `datetime.timezone.utc` as `datetime.UTC` was only added in Python 3.11.
No need to suggest to make code backwards incompatible without a good reason.

2024-06-21 17:20 UTC, pganssle commented
I think I am -0 on this change. I chose the `datetime.UTC` wording deliberately because it advertises that the `datetime.UTC` singleton exists, which allows people to do things like `from datetime import UTC; datetime.now(UTC)` (which is the same number of characters as `datetime.utcnow()`, which some people care about).

I would not think that we should be so concerned with backwards compatibility, since this deprecation warning only even happens in Python 3.12+, and it's referring to a removal that won't take place for an indefinite amount of time in the future.

Evidently some people are indeed confused by this, though, so I dunno, maybe it's better on net to recommend the wordy version? :shrug:

2024-06-21 17:21 UTC, pganssle requested changes
As I mentioned, I'm not really in favor of merging this, but if we do end up merging it, it should probably get a news blurb.

2024-06-21 19:04 UTC, nineteendo commented
Ruff also mentions `datetime.timezone.utc` first: https://docs.astral.sh/ruff/rules/call-datetime-utcnow.
Would you prefer to mention both too?

2024-06-21 19:13 UTC, nineteendo commented
pganssle, I have made the requested changes; please review again.

2024-09-12 17:29 UTC, merwok commented
I agree with Paul, the warning is not wrong and this is not really a bug.

2024-09-12 17:29 UTC, closed without merging