gh-120882: Fix shutil.move to properly handle files opened by another process
python/cpython pull request #120883
Opened 2024-06-22 15:17 UTC by Saqibs575

# Bug report

### Bug description:

# Problem:
When attempting to move a file using shutil.move from one location to another, if the file is opened by another process (if file is opened in other python script using `open` function), shutil.move raises an error (`WinError 32: The process cannot access the file because it is being used by another process`). Despite this error, the file is still copied to the destination directory, which is unexpected behavior.

# Details:
The shutil.move function is designed to handle moving files or directories between locations. However, it does not check if the file is currently open by another process before attempting to move it. This results in an error being raised, but the file is still copied to destination regardless of the error condition.

# Solution:
To address this issue, I modified the shutil.move function to include an additional check for OSError with errno.EACCES (Permission Denied) in the exception handling block. This ensures that if the file cannot be moved due to being opened by another process, the operation is aborted cleanly without copying the file to maintain the integrity of the move function as well as file system.

Here is the modified part of the shutil.move function

```python
    except OSError as exc:
        if exc.errno == errno.EACCES:
            raise  # Propagate the PermissionError
     # Existing code
```

# Proposal:
I propose adding this error handling improvement to the shutil.move function in Python's standard library. This enhancement will make file operations more reliable in scenarios where files may be concurrently accessed by multiple processes

# Steps to Reproduce:

- Open a file (test.pdf) in any python script using `open` function in read mode.
- Attempt to move the file using shutil.move to another directory.
- Observe the WinError 32 exception and incorrect copying behavior.
- Close the file (To avoid memory leakage).

**NOTE:** Avoid to use context manager here for opening file to find the error.
You can also run the following script to get the error.

```python
import shutil

src = "C://Users//Desktop//Downloads//test.pdf" # Provide full file path of your system.
dst_dir = "D://Files" # Provide destination directory path.
f = open(src, "r")
try:
    shutil.move(src, dst_dir)
except Exception as e:
    print(e)
finally:
    f.close()
```

# Expected Behavior:

When shutil.move encounters a situation where the source file is open in another process (WinError 32), it should raise an exception and abort the operation without performing any partial file copying to the destination.

# Impact:

This issue affects users trying to use shutil.move to relocate files that are concurrently accessed by other processes. The proposed solution aims to improve the robustness and expected behavior of the function in such scenarios.

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

2024-06-22 17:21 UTC, barneygale commented
> When shutil.move encounters a situation where the source file is open in another process (WinError 32), it should raise an exception and abort the operation without performing any partial file copying to the destination.

Unfortunately we can't know that ahead of time, nor can we roll back the copy if we encounter an error while deleting. Users expect that `shutil.move()` deletes the original file (that's what differentiates it from `copy2()` / `copytree()`) which doesn't seem compatible with your suggestion to suppress `EACCES`.

2024-06-22 19:48 UTC, nineteendo commented on Lib/shutil.py
> +            raise
```suggestion
            raise
```

2024-06-22 19:57 UTC, nineteendo commented
It doesn't raise the correct error when moving a directory on Windows:

```pytb
======================================================================
ERROR: test_dont_move_dir_in_itself (test.test_shutil.TestMove.test_dont_move_dir_in_itself)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_shutil.py", line 2742, in test_dont_move_dir_in_itself
    self.assertRaises(shutil.Error, shutil.move, self.src_dir, dst)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 804, in assertRaises
    return context.handle('assertRaises', args, kwargs)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\unittest\case.py", line 238, in handle
    callable_obj(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\a\cpython\cpython\Lib\shutil.py", line 857, in move
    os.rename(src, real_dst)
    ~~~~~~~~~^^^^^^^^^^^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\cpython\\cpython\\build\\test_python_[833](https://github.com/python/cpython/actions/runs/9626446182/job/26552425077?pr=120883#step:6:834)6�\\tmpjagpnbs_' -> 'D:\\a\\cpython\\cpython\\build\\test_python_8336�\\tmpjagpnbs_\\bar'
```

Could you also add a test for the fix?

2024-06-24 17:43 UTC, vstinner requested changes
This change is wrong. You cannot simply ignore all OSErrors but EACCESS.

2024-06-24 22:57 UTC, eryksun commented
> It doesn't raise the correct error when moving a directory on Windows

Note that starting with Windows 11 22H2, this test case fails with `ERROR_INVALID_PARAMETER` (87), which maps to C `EINVAL`. So it actually didn't fail for me on Windows 11 23H2. It would have failed if it were implemented to move a directory into one of its subdirectories instead of directly into itself. In Windows 11, the latter still fails with `ERROR_ACCESS_DENIED` (5), which maps to C `EACCES`.

What's changed recently is that for a rename operation, the kernel's internal I/O manager function `IopOpenLinkOrRenameTarget()` was updated to open the destination directory using read, write, and delete sharing, whereas it used to open it with just read and write sharing. This change is documented in [\[MS-FSA\]: 2.1.5.15.11 FileRenameInformation](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fsa/87f86c9b-6c2a-4803-84b7-131a74a434fa) where it mentions opening `DestinationDirectory` with "`ShareAccess` equal to `FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE`".

With the old implementation, which dates back about 30 years, the internal `IopOpenLinkOrRenameTarget()` call would fail with a sharing violation, i.e. Windows error `ERROR_SHARING_VIOLATION` (32)[^1] because this second open of the directory didn't share delete access. Now in Windows 11 it succeeds in this case, and the rename operation ends up failing farther along in the device stack with `ERROR_INVALID_PARAMETER`. This behavior is currently undocumented in the `FileRenameInformation` protocol. I have to wonder whether it's an oversight. If it were intentional, I'd expect the error code to be `ERROR_ACCESS_DENIED`.

Note that trying to rename a directory into a subdirectory of itself (e.g. "spam" -> "spam\\eggs\\foo") still fails with `ERROR_ACCESS_DENIED`, as documented where the protocol discusses "[i]f `Open.File.FileType` is `DirectoryFile`, determine whether `Open.File` contains open files as specified in section 2.1.4.2...". In this case, there's at least one open file in the source directory tree -- the destination directory.

[^1]: For consistency and simplicity I'm using Windows error codes instead of the actual error status codes that are used in the NT API, such as `STATUS_SHARING_VIOLATION`, `STATUS_INVALID_PARAMETER`, and `STATUS_ACCESS_DENIED`.

2024-09-08 08:46 UTC, closed without merging