gh-120811: Fix reference leak upon `_PyContext_Exit` failure
python/cpython pull request #120812
Opened 2024-06-20 20:57 UTC by ZeroIntensity

- Issue: #120811

2024-06-20 21:01 UTC, Eclips4 approved these changes

2024-06-20 21:38 UTC, AraHaan commented
can this be backported to the 3.11 branch but require people who want the fix to manually compile themselves?

2024-06-21 03:55 UTC, Eclips4 commented
> can this be backported to the 3.11 branch but require people who want the fix to manually compile themselves as well?

Unfortunately, no. 3.11 branch accepts now only a security fixes.

2024-06-21 04:54 UTC, kumaraditya303 requested changes
Please add a news entry, it is a user facing bug not internal.

2024-06-21 14:33 UTC, ZeroIntensity commented
I have made the requested changes; please review again

2024-06-21 17:04 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2024-06-21-14-32-56.gh-issue-120811.eBmVTV.rst
> +Fix memory leak in ``contextvars.Context.run()``
```suggestion
Fix possible memory leak in :meth:`contextvars.Context.run`.
```

2024-06-21 17:05 UTC, kumaraditya303 approved these changes

2024-06-21 17:28 UTC, merged