Fix parameter name at dbm.gnu.open docs
python/cpython pull request #12095
Opened 2019-02-28 16:18 UTC by rougeth

There's a missing `s` in the `flags` parameter at the [docs](https://docs.python.org/3/library/dbm.html#dbm.gnu.open) for `dbm.gnu.open`.

Reference: https://github.com/python/cpython/blob/master/Modules/_gdbmmodule.c#L533

2019-03-14 11:07 UTC, remilapeyre commented
Hi @rougeth, thanks for taking the time to improve the documentation!

I think `dbm.ndbm.open` suffers from the same issue, can you fix it too?

2019-03-14 13:39 UTC, rougeth commented
Updated, thanks for reviewing @remilapeyre. This `flags` options is quite confusing, in `ndbm` it accepts only one flag at the time, doesn't make sense to be in plural.

Sorry of the force-pushed commits, wasn't getting the git name/email correctly configured.

2019-03-14 15:09 UTC, remilapeyre commented
You are right, the good thing is that it does not take keyword arguments:

```
>>> dbm.ndbm.open(filename='foo', flags='r', mode=438)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: open() takes no keyword arguments
>>>
```

so we can change the name of the argument without breaking current code.

I think we should fix the docstring for `dbm.ndbm.open` rather than changing the doc here.

2019-03-14 15:38 UTC, rougeth commented
@remilapeyre the issue is that in every other reference I could find about `ndbm` uses `flags` instead of `flag`, so I think we should implement the same interface.

2019-03-14 16:09 UTC, remilapeyre commented
Were those references in the documentation? Since there is no way to use keyword arguments with `dbm.ndbm.open` it would not change the interface.

2019-03-14 16:45 UTC, rougeth commented
No, not in Python documentation. What I meant was that our documentation would be different from every other place (considering a fast and superficial web search) that describes how to use `ndbm.open`.

If only the docstring is changed, there will be inconsistency between it and how the function was actually implement, is that something ok?

Either way, I think this goes a bit further than "a trivial change". I'm going to open an issue on bpo so that we can continue from there and I think this PR can go as it is. What do you think?

2019-03-14 23:41 UTC, remilapeyre commented
Hi @rougeth, you are right that this goes further than the initial change and opening a issue on bpo so people more knowledgeable can give the correct way forward is always a good idea.

Please do open a new bug report; if you want, you can rollback the change made on `dbm.ndbm.open` on this PR (really sorry about that) so we can get this documentation improvement merged and we will open a new PR with whatever the consensus on `dbm.ndbm.open` will be.

2019-03-15 00:05 UTC, rougeth commented
@remilapeyre nothing to be sorry about :) But I still think the last commit is valid tho. I'd prefer to go with the way it's now and if it's needed, we can change it again. Thanks for the help!

2019-03-16 20:26 UTC, rougeth commented
FYI: About the rename of `dbm.ndbm.open` argument from `flags` to `flag`: https://bugs.python.org/issue36322

2019-04-02 21:17 UTC, brettcannon requested changes
It looks like you're not only right about the incorrect name, but it also seems default values are missing.

2019-04-02 21:17 UTC, brettcannon commented on Doc/library/dbm.rst
> +.. function:: open(filename[, flags[, mode]])
Double-check me, but https://github.com/python/cpython/blob/master/Modules/_gdbmmodule.c#L553 seems to suggest this is actually even more accurate:
```suggestion
.. function:: open(filename[, flags="r"[, mode]])
```

2019-04-02 21:17 UTC, brettcannon commented on Doc/library/dbm.rst
> +.. function:: open(filename[, flags[, mode]])
Double-check me, but https://github.com/python/cpython/blob/master/Modules/_dbmmodule.c#L427 makes this even more accurate:
```suggestion
.. function:: open(filename[, flags="r"[, mode]])
```

2019-04-02 21:26 UTC, brettcannon commented
Closing as the parameters under question are positional-only and thus their names don't matter.

2019-04-02 21:26 UTC, closed without merging