bpo-33944: Add site.py debugging via PYTHODSITEDEBUG
python/cpython pull request #12107
Opened 2019-02-28 22:24 UTC by native-api

2019-03-02 09:36 UTC, methane commented on Lib/site.py
> +    pdb.set_trace()
```suggestion
    breakpoint()
```

2020-06-16 18:17 UTC, tiran requested changes
This PR piggybacks on BPO 33944. IMO it needs a separate BPO and a more thorough discussion.

2020-06-16 18:17 UTC, tiran commented on Lib/site.py
> +if os.environ.get("PYTHONSITEDEBUG", ""):
Any PYTHON env var must be ignored when ignore environment is set.

```suggestion
if not sys.flags.ignore_environment and os.environ.get("PYTHONSITEDEBUG"):
```

2020-06-16 18:17 UTC, tiran commented on Doc/using/cmdline.rst
> +   .. versionadded:: 3.8
```suggestion
   .. versionadded:: 3.10
```

2024-01-15 21:27 UTC, erlend-aasland commented
Closed as per https://github.com/python/cpython/pull/12107#pullrequestreview-431773752

2024-01-15 21:27 UTC, closed without merging