Fix typos in comments
python/cpython pull request #121074
Opened 2024-06-27 03:38 UTC by xyb

2024-06-27 19:13 UTC, Eclips4 approved these changes

2024-07-02 03:51 UTC, xyb commented
@vstinner Would you please approve this pr? Thanks.

2024-07-02 07:24 UTC, vstinner requested changes
Objects/mimalloc/ directory is a copy of https://github.com/microsoft/mimalloc/ : please fix the typos upstream.

2024-07-02 07:25 UTC, vstinner commented
See also: https://github.com/python/cpython/issues/113141

2024-07-02 07:25 UTC, closed without merging