bpo-26707: enable  plistlib to read UID keys
python/cpython pull request #12153
Opened 2019-03-04 01:24 UTC by Bigfootjon

Plistlib currently throws an exception when asked to decode a valid
.plist file that was generated by Apple's NSKeyedArchiver. Specifically,
this is caused by a byte 0x80 (signifying a UID) not being understood.

This fixes the problem by enabling the binary plist reader and writer
to read and write plistlib.UID objects.

2019-03-04 09:06 UTC, serhiy-storchaka requested changes
Add tests for the following UIDs (this will expose a bug in your code):

* from `2**8` to `2**16-1`
* from `2**16` to `2**32-1`
* from `2**32` to `2**63-1`
* from `2**63` to `2**64-1`
* larger than `2**64-1`
* `0`
* negative

Add tests for the *data* attribute of UID, for equality/inequality tests and hashing, for `repr(uid)`, for `operator.index(uid)`, and for pickling/unpickling and copying of UIDs.

Document the UID class. Add the `versionchanged` directives in the module documentation and a What's New entry.

Add your name into Misc/ACKS.

2019-03-04 17:02 UTC, serhiy-storchaka reviewed
Please add also a test for the `data` attribute.

2019-03-04 17:02 UTC, serhiy-storchaka commented on Lib/plistlib.py
>          return self.data == other.data
Add
```python
if not isinstance(self, UID):
    return NotImplemented
```
and add a test for equality check with non-UID.

2019-03-04 17:02 UTC, serhiy-storchaka commented on Lib/plistlib.py
> +            elif value.data < 1 << 63:
This is not needed.

2019-03-04 17:02 UTC, serhiy-storchaka commented on Lib/test/test_plistlib.py
> +        self.assertEqual(pickle.loads(pickle.dumps(UID(19))), UID(19))
Test with all supported protocols.

2019-03-04 19:12 UTC, Bigfootjon commented
I have made the requested changes; please review again

2019-03-05 07:30 UTC, serhiy-storchaka approved these changes

2019-03-14 01:51 UTC, Bigfootjon commented
Bump

2019-04-02 03:01 UTC, Bigfootjon commented
Bump

2019-04-25 17:37 UTC, brettcannon commented
@ronaldoussoren @ned-deily either of you want to take a look, or should @serhiy-storchaka go ahead and merge?

2019-04-25 18:10 UTC, ned-deily commented
@ronaldoussoren and @serhiy-storchaka are the current plistlib experts. In the bpo issue, @ronaldoussoren expressed doubts about adding this support.  @ronaldoussoren ?

2019-05-01 12:55 UTC, Bigfootjon commented
Ping @ronaldoussoren @serhiy-storchaka @ned-deily

2019-05-05 04:51 UTC, serhiy-storchaka commented
The PR LGTM, and I understand why this feature is needed. But I am not even a macOS user.

2019-05-06 16:52 UTC, brettcannon commented
I think if @ronaldoussoren doesn't respond in some capacity in the next week then we should merge based on the review from @serhiy-storchaka .

2019-05-15 19:56 UTC, Bigfootjon commented
Ping @ronaldoussoren @brettcannon @serhiy-storchaka

2019-05-15 20:14 UTC, merged

2019-05-15 20:16 UTC, serhiy-storchaka commented
Thank you for your contribution @Bigfootjon!