gh-121153: Change _PyLong_CompactValue() return type to int
python/cpython pull request #121536
Opened 2024-07-09 13:47 UTC by vstinner

2024-07-09 13:47 UTC, vstinner commented
cc @serhiy-storchaka @markshannon

2024-07-09 13:56 UTC, serhiy-storchaka commented on Include/cpython/longintrepr.h
>      Py_ssize_t sign;
```suggestion
    int sign;
```

2024-07-09 13:57 UTC, serhiy-storchaka requested changes
This is incomplete change. You need also to change the code that calls `_PyLong_CompactValue()` (and simplify it).

2024-07-10 13:42 UTC, vstinner commented
> You need also to change the code that calls _PyLong_CompactValue() (and simplify it).

Ok, I updated _PyLong_CompactValue() usage as well.

2024-07-10 13:47 UTC, vstinner reviewed
@serhiy-storchaka: It would be nice if you could review this change since I'm not sure if it's correct.

2024-07-10 14:07 UTC, serhiy-storchaka reviewed
You need to update also other code. Take #121154 and replace `Py_ssize_t` with `int`. Then remove dead code.

2024-07-10 14:07 UTC, serhiy-storchaka commented on Objects/longobject.c
> +#if SIZEOF_INT < SIZEOF_VOID_P
Remove this branch. It was wrong from beginning, and it is no longer needed.

2024-07-10 14:07 UTC, serhiy-storchaka commented on Objects/longobject.c
> +        x = (Py_uhash_t)_PyLong_CompactValue(v);
Since `Py_hash_t` != `int`:
```suggestion
        x = (Py_uhash_t)(Py_hash_t)_PyLong_CompactValue(v);
```

2024-07-10 14:07 UTC, serhiy-storchaka commented on Python/bltinmodule.c
> +                    (i_result >= 0 ? (1 - i_result) : (1 - i_result)))
This code does not make sense.

2024-07-11 11:56 UTC, vstinner commented on Python/bltinmodule.c
> +                    (i_result >= 0 ? (1 - i_result) : (1 - i_result)))
I don't understand this code.

2024-07-11 11:58 UTC, vstinner commented
> You need to update also other code. Take https://github.com/python/cpython/pull/121154 and replace Py_ssize_t with int. Then remove dead code.

I'm not sure that I'm not the right person to implement this change. Maybe you should create your own PR and I abandon this PR.

2024-07-11 19:19 UTC, serhiy-storchaka commented on Python/bltinmodule.c
> +                    (i_result >= 0 ? (1 - i_result) : (1 - i_result)))
This is an overflow check for `i_result += b`.

2024-07-12 11:26 UTC, vstinner commented
This PR changes PyUnstable_Long_CompactValue() return type. I documented that change.

If it's an issue, we can leave PyUnstable_Long_CompactValue() return type unchanged.

2024-07-12 16:00 UTC, serhiy-storchaka approved these changes
Yes, it needs also changing `PyUnstable_Long_CompactValue` which may be defined as an alias of `_PyLong_CompactValue`.

Technically, it now LGTM. But we should ask @markshannon what he thinks about changing the return type. Why it was `Py_ssize_t` at first place?

2024-07-13 17:35 UTC, vstinner commented
https://github.com/python/cpython/pull/121154 was merged instead.

2024-07-13 17:35 UTC, closed without merging