gh121528: Fix the process crash when load extension when it's compiled with low version of the python.
python/cpython pull request #121550
Opened 2024-07-09 19:15 UTC by Zheaoli

Fix #121528

2024-07-09 19:33 UTC, ZeroIntensity requested changes
Can confirm that this PR fixes #121528

2024-07-09 19:33 UTC, ZeroIntensity commented on Include/internal/pycore_object.h
> +    if (_PyType_HasFeature(typeobj, Py_TPFLAGS_HEAPTYPE) || _Py_IsImmortal(typeobj)){
This should follow [PEP 7](https://peps.python.org/pep-0007/). There should be a space between the end of the parens and `{`

2024-07-09 21:53 UTC, ZeroIntensity commented
@Eclips4 Can you add the 3.13 backport label?

2024-07-10 04:40 UTC, Eclips4 commented
cc @mgorny can you confirm that this patch fixes the issue?

2024-07-10 11:40 UTC, ZeroIntensity requested changes

2024-07-10 11:40 UTC, ZeroIntensity commented on Misc/NEWS.d/next/Core_and_Builtins/2024-07-10-03-13-19.gh-issue-121528._Bo7rw.rst
> +Fix the process crash when load extension when it's compiled with low
I think this should be reworded, it's not too clear to someone who's not familiar with the exact issue.

```suggestion
Fix crash when loading extension modules that are compiled with an older
```

2024-07-10 11:40 UTC, ZeroIntensity commented on Misc/NEWS.d/next/Core_and_Builtins/2024-07-10-03-13-19.gh-issue-121528._Bo7rw.rst
> +version of the python.
```suggestion
version of Python.
```

2024-07-10 12:11 UTC, Zheaoli commented
@ZeroIntensity Thanks for the tips!

2024-07-10 12:20 UTC, ZeroIntensity approved these changes
Thanks for the changes, LGTM.

2024-07-19 04:38 UTC, closed without merging