gh-121529: Document from_ parameter in _mboxMMDF methods
python/cpython pull request #121530
Opened 2024-07-09 11:16 UTC by sebbASF

* Issue: gh-121529

----
📚 Documentation preview 📚: https://cpython-previews--121530.org.readthedocs.build/

2024-07-09 18:44 UTC, ZeroIntensity requested changes
from_ should be italic, as `*from_*` in the file.

2024-07-09 19:19 UTC, ZeroIntensity requested changes
Thanks! "unix" is a proper noun, it should be capitalized.

2024-07-09 19:38 UTC, ZeroIntensity requested changes
Looks good to me, but I think `'From '` should use double quotes, as that's what's used in the docs already (see [here, for example](https://docs.python.org/3/library/mailbox.html#mailbox.mbox))

2024-07-09 19:38 UTC, ZeroIntensity commented
Sorry for not catching the second two changes in my initial review, that's my fault.

2024-07-09 20:26 UTC, ZeroIntensity approved these changes
LGTM, I'll leave nitpicking the rest to someone else.

2025-02-23 14:20 UTC, ZeroIntensity commented
@picnixz Here's an easy review in the backlog if you want to take a look. (This predates both of our triage memberships :laughing:.)

2025-02-23 14:21 UTC, picnixz commented
I was just writing the commit message :')

2025-02-23 14:26 UTC, picnixz commented
Actually, I've just observed that the documentation is not updating the paragraph for `MMDF` class, only the paragraph for `mailbox.mbox`. Can this also be done in this PR?

The commit title will be 

```
gh-121529: Document `from_` parameter of `mailbox.mbox and `mailbox.MMDF` methods (#121530)
```

The commit message will be 

```
In addition to documenting the `from_` parameter of the `mailbox.{mbox,MMDF}.get_file` methods,
we also document the `get_bytes` and `get_string` methods that were previously not documented.
```

2025-02-24 00:01 UTC, picnixz commented
I'll review it tomorrow and merge it if it's fine. Thanks for updating those docs btw

2025-02-24 17:57 UTC, picnixz commented on Doc/library/mailbox.rst
> +      Note: This method has an extra parameter (*from_*) compared with other classes.
I don't know if it's better to repeat the same note or just say something like "See XXX for the meaning of `from_`". It's fine to repeat it twice, one for `mbox` and one for `MMDF`, but for the methods just after, I think it's fine to mention the first documented method of the sub-section. WDYT?

2025-03-23 12:10 UTC, picnixz commented on Doc/library/mailbox.rst
> +      Note: This method has an extra parameter (*from_*) compared with other classes.
Let's keep the current wording.

2025-03-23 12:10 UTC, merged