gh-121583: Remove dependency from pystats.h to internal header file
python/cpython pull request #121587
Opened 2024-07-10 14:43 UTC by mdboom

This just uses a fixed number of slots for recording uops stats that is enforced to be big enough.

Alternatively, we could generate the correct number and put it in a public header, but that seems like overkill.

2024-07-10 15:16 UTC, ZeroIntensity requested changes
Should follow [PEP 7](https://peps.python.org/pep-0007/).

2024-07-10 15:16 UTC, ZeroIntensity commented on Include/cpython/pystats.h
> +    uint64_t error_in_opcode[PYSTATS_MAX_UOP_ID+1];
```suggestion
    uint64_t error_in_opcode[PYSTATS_MAX_UOP_ID + 1];
```

2024-07-10 15:16 UTC, ZeroIntensity commented on Include/cpython/pystats.h
> +    UOpStats opcode[PYSTATS_MAX_UOP_ID+1];
```suggestion
    UOpStats opcode[PYSTATS_MAX_UOP_ID + 1];
```

2024-07-10 15:34 UTC, ZeroIntensity approved these changes

2024-07-16 22:37 UTC, brandtbucher approved these changes
Thanks @mdboom! I'm going to go ahead and land this.

2024-07-16 22:38 UTC, merged