GH-121584: Toggle helper instead of nesting instances when using key bindings
python/cpython pull request #121668
Opened 2024-07-13 09:52 UTC by saucoide

Adds a flag to check if the helper is active, interrupting it instead of opening a new instance if so

This is to stop F1 from opening multiple instances of help you need to quit individually before returning to the repl, maybe the toggling part with the sigint is not needed, but I figured `paste_mode` behaves that way so maybe this can too?

2024-10-24 04:25 UTC, saucoide commented
@ambv i just saw that the toggle behavior for help is mentioned explicitly in the pep, any chance this will get merged or is that part going to be reworked anyway and better not to introduce more stuff?

2025-01-21 21:55 UTC, pablogsal commented on Lib/_pyrepl/commands.py
> +            signal.raise_signal(signal.SIGINT)
Hummm...I am worried by this. Why are we raising SIGINT here? This looks very error prone

2025-01-21 21:56 UTC, pablogsal requested changes
See the previous comment

2025-01-25 12:34 UTC, saucoide commented on Lib/_pyrepl/commands.py
> +            signal.raise_signal(signal.SIGINT)
I needed a way to get out of the help's input prompt here

```python
    def interact(self):
        self.output.write('\n')
        while True:
            try:
                request = self.getline('help> ')
                if not request: break
            except (KeyboardInterrupt, EOFError):
                break
            request = request.strip()

            # Make sure significant trailing quoting marks of literals don't
            # get deleted while cleaning input
            if (len(request) > 2 and request[0] == request[-1] in ("'", '"')
                    and request[0] not in request[1:-1]):
                request = request[1:-1]
            if request.lower() in ('q', 'quit', 'exit'): break
            if request == 'help':
                self.intro()
            else:
                self.help(request)

    def getline(self, prompt):
        """Read one line, using input() when appropriate."""
        if self.input is sys.stdin:
            return input(prompt)
        else:
            self.output.write(prompt)
            self.output.flush()
            return self.input.readline()
```

I've swapped it now for a `KeyboardInterrupt`, would that be ok? 

"I have made the requested changes; please review again"

2025-01-25 14:06 UTC, pablogsal commented on Lib/_pyrepl/commands.py
> +            signal.raise_signal(signal.SIGINT)
I do think this is the correct approach. Relying on signals for this is super error prone in my opinion. Not only that but testing this that way is going to be a nightmare taking into account how signals behave in different machines. Also if the user has handles already installed you will be executing that code which may have side effects that the user didn't trigger.

This probably requires some heavier changes but I don't think we want to deal with the chaos of control flow by signals. 

WDYT @ambv

2025-01-25 14:19 UTC, ambv commented on Lib/_pyrepl/commands.py
> +            signal.raise_signal(signal.SIGINT)
The newest version of the code doesn't `raise_signal` anymore but raises a regular exception with KeyboardInterrupt. This is a bit weird, but we already do this ourselves in `commands.ctrl_c`. That command is mapped to `\x03` in `reader` (used by the asyncio REPL) and in the `ExceptHookHandler` (used for `threading.excepthook` so that exceptions from threads created in the REPL format okay).

While in both cases the command works around the fact that there's no good way to interrupt input from another thread, the way we actually interrupt the input is by raising KeyboardInterrupt by hand in the command.

All I'm saying is that there's precedent. I would want to test this with the asyncio REPL.

2025-07-19 10:52 UTC, saucoide commented
bumping asking to take a look at this again, the latest version doesnt use signals anymore

_I have made the requested changes; please review again_

2025-12-21 12:34 UTC, saucoide commented
@pablogsal can you take a look at this again?

2026-04-07 15:14 UTC, johnslavik commented
Thanks for the PR!

See also https://github.com/python/cpython/issues/148191, where I am proposing removing the F1 key bind entirely.

2026-04-07 16:00 UTC, johnslavik commented
We're keeping F1. @saucoide, do you want to address the remaining issues or would you like me to take over the work on this? There's some conflicts with upstream, things have changed since.

We're not in a rush, we will rebase this onto https://github.com/python/cpython/pull/146584.

2026-04-12 11:57 UTC, saucoide commented
@johnslavik i don't think i'll have time anytime soon, would gladly take it but i'm a bit busy at the moment, so feel free to take over if you have the time :) thanks!

2026-04-14 09:41 UTC, johnslavik commented
Thank you for your work on this and the quick reply. I'll close it and open a new PR with a slightly different solution.

2026-04-14 09:41 UTC, closed without merging