gh-121650 : detect newlines in headers
python/cpython pull request #121812
Opened 2024-07-15 19:53 UTC by basbloemsaat

@encukou as promised, the fix for this issue.

This PR fixes both issues addressed in the issue, both the newlines at the end as well as the encoded newlines.

As this has security implication, it may need to be backported as well.

2024-07-15 21:27 UTC, ZeroIntensity requested changes
I wasn't able to confirm that this PR fixes #121650. The original reproducer still contains the embedded newline:

```py
from email import message_from_string
from email.policy import default

email_in = """\
To: incoming+tag@me.example.com
From: External Sender <sender@them.example.com>
Subject: Here's an =?UTF-8?Q?embedded_newline=0A?=
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

<html>
<head><title>An embeded newline</title></head>
<body>
  <p>I sent you an embedded newline in the subject. How do you like that?!</p>
</body>
</html>
"""

msg = message_from_string(email_in, policy=default)
msg = message_from_string(email_in, policy=default)
for header, value in msg.items():
    del msg[header]
    msg[header] = value
email_out = str(msg)
print(email_out)
```

2024-07-15 21:27 UTC, ZeroIntensity commented on Lib/email/policy.py
> +                         "or carriage return characters")
I would keep the formatting consistent:
```suggestion
                             "or carriage return characters")
```

2024-07-15 21:27 UTC, ZeroIntensity commented on Misc/NEWS.d/next/Library/2024-07-15-21-43-38.gh-issue-121650.A0FkCh.rst
> +Fixes newlines (and carriage returns) in email headers, both at the end of
```suggestion
Fixed newlines and carriage returns in :mod:`email` headers, both at the end of
```

2024-07-15 21:27 UTC, ZeroIntensity commented on Misc/NEWS.d/next/Library/2024-07-15-21-43-38.gh-issue-121650.A0FkCh.rst
FWIW, as a tiny nitpick, this is actually a fix to `EmailPolicy`, so that might be worth specifying.

2024-07-16 08:29 UTC, basbloemsaat commented on Misc/NEWS.d/next/Library/2024-07-15-21-43-38.gh-issue-121650.A0FkCh.rst
done, I think, please check

2024-07-16 08:31 UTC, basbloemsaat commented
> I wasn't able to confirm that this PR fixes #121650. The original reproducer still contains the embedded newline:
> ...

I missed headers that were parsed from a message, as in the example, updated the fix and the tests.

2024-07-16 13:44 UTC, ZeroIntensity approved these changes
Confirmed that this fixes #121650. I'm pretty sure this is a security fix (as you could previously inject email headers using this method), so this should need a backport all the way to 3.8

2024-07-16 15:26 UTC, encukou commented
@warsaw, @bitdancer, @maxking: as the [email experts](https://devguide.python.org/core-developers/experts/#stdlib), do you have any comments?

2024-07-16 15:27 UTC, encukou approved these changes, later dismissed
The fix looks good to me! Thank you for digging into it!

2024-07-19 16:09 UTC, encukou commented
I take back the review. There's more to this, unfortunately :(

Here's another reproducer:
```py
from email import message_from_string
from email.policy import default

email_in = """\
To: incoming+tag@me.example.com
From: External Sender <sender@them.example.com>  =?UTF-8?Q?embedded_newline=0A?=Smuggled-Data: Bad
Subject: foo <bar> Here's an
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

<html>
<head><title>An embeded newline</title></head>
<body>
  <p>I sent you an embedded newline in the subject. How do you like that?!</p>
</body>
</html>
"""

msg = message_from_string(email_in, policy=default)
print(msg)
for header, value in msg.items():
    del msg[header]
    msg[header] = value
email_out = str(msg)
print(email_out)
```

2024-07-19 17:13 UTC, basbloemsaat commented
> I take back the review. There's more to this, unfortunately :(

I'll look into this...

2024-07-19 22:14 UTC, basbloemsaat commented
@encukou I tried all header types. This eliminates all newlines. Two notes:

- date headers parse the date, and the offending code is eliminated that way
- the MIME-Version header doesn't decode the encoded newline, so it doesn't break the message. Improving the parsing of that header would mean rewriting the parsing code to do so, but I think that goes beyond the scope of this ticket.

2024-07-24 13:57 UTC, encukou commented
After reading up on the email module, I propose to fix the issue in a different part of the code: see #122233.

2024-08-01 13:54 UTC, encukou commented
Closing in favour of #122233.
Thank you for the work here, @basbloemsaat! And sorry that I “stole” the issue.

2024-08-01 13:54 UTC, closed without merging