gh-121874: Define audit-event open parameters consistently
python/cpython pull request #121883
Opened 2024-07-17 01:58 UTC by bmwiedemann

Define `audit-event` `open` parameters consistently to be the same as in
```
Doc/library/io.rst:   .. audit-event:: open path,mode,flags io.open
Doc/library/os.rst:   .. audit-event:: open path,mode,flags os.open
```
to avoid triggering a race-condition in Sphinx
that causes non-deterministic output.

See https://reproducible-builds.org/ for why this matters.

Fixes: #121874

This patch was done while working on reproducible builds for openSUSE, sponsored by the NLnet NGI0 fund.

2024-07-17 05:55 UTC, hugovk commented
`io.open` is an alias for `open` and both have a `file` parameter rather than `name`.

https://docs.python.org/3/library/functions.html#open says:


> `open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)`
> 
> ...
> 
> Raises an [auditing event](https://docs.python.org/3/library/sys.html#auditing) open with arguments `file`, `mode`, `flags`.

https://docs.python.org/3/library/io.html#io.open says:

> `io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)`
>
> ...
> 
> This function raises an [auditing event](https://docs.python.org/3/library/sys.html#auditing) open with arguments *path*, *mode* and *flags*. The *mode* and *flags* arguments may have been modified or inferred from the original call.

Should we change both to `file` rather than `path`? And write them all in [italics](https://devguide.python.org/documentation/markup/#quick-reference)?

2024-07-17 07:19 UTC, bmwiedemann commented
I tried that and found that `os.open` also needs to be adapted then, making the whole change more intrusive: https://github.com/bmwiedemann/cpython/pull/new/docrace2

2024-07-17 18:51 UTC, serhiy-storchaka requested changes
This is incorrect. The name of the parameter is `file`, not `path`.

2024-07-17 19:25 UTC, bmwiedemann commented
I have made the requested changes; please review again.

2024-07-18 06:01 UTC, serhiy-storchaka approved these changes
LGTM.

2024-07-18 10:05 UTC, merged