bpo-28814: Undeprecate inadvertantly deprecated inspect function.
python/cpython pull request #122
Opened 2017-02-15 16:54 UTC by Carreau

Nick Coghlan said on bpo-28814:

> inspect.getargvalues() and inspect.formatargvalues() were deprecated
> in Python 3.5 as part of implementing bpo-20438

> This is incorrect, as these are *frame* introspection related functions,
> not callable introspection ones. The documentation and implementation
> layout is confusing though, as they're interleaved with the callable
> introspection operation

So un-deprecate in the doc, and leave a note to ignore previous
deprecation notice.

2017-02-15 16:55 UTC, Carreau commented
> The documentation and implementation
> layout is confusing though, as they're interleaved with the callable
> introspection operation

I did not touch the code but I'll be happy to move these 2 functions into the "stack frame extraction" section of `inspect.py`

2017-02-18 04:43 UTC, ncoghlan commented on Doc/whatsnew/3.5.rst
> +  where inadvertantly marked as deprecated with with the release of Python 3.5.0
Accidentally doubled word here: s/with with/with/

2017-02-18 04:43 UTC, ncoghlan commented
Thanks! This mostly looks good to me, just one accidentally doubled word to fix before it can be merged.

2017-02-19 20:09 UTC, berkerpeksag requested changes

2017-02-19 20:09 UTC, berkerpeksag commented on Doc/library/inspect.rst
> +      This function was inadvertantly marked as deprecated in Python 3.5. Ignore
typo: inadvert*e*ntly

2017-02-19 20:09 UTC, berkerpeksag commented on Doc/library/inspect.rst
> +      This function was inadvertantly marked as deprecated in Python 3.5. Ignore
"Ignore previous deprecation notice." is superfluous and can be deleted in my opinion.

2017-02-19 20:09 UTC, berkerpeksag commented on Doc/whatsnew/3.5.rst
> +  Function :func:`~inspect.getargvalues` and :func:`~inspect.formatargvalues`
Function -> Functions

2017-02-19 20:09 UTC, berkerpeksag commented on Doc/whatsnew/3.5.rst
> +  Function :func:`~inspect.getargvalues` and :func:`~inspect.formatargvalues`
Indentation should use 3 or 4 spaces:

```rst
.. note::
   Functions [...]
```

2017-02-19 20:09 UTC, berkerpeksag commented on Doc/whatsnew/3.5.rst
> +  where inadvertantly marked as deprecated with with the release of Python 3.5.0
typo: inadvertantly -> inadvertently

2017-02-19 20:09 UTC, berkerpeksag commented on Doc/whatsnew/3.5.rst
> +  where inadvertantly marked as deprecated with with the release of Python 3.5.0
Please add a dot at the end of the sentence.

2017-02-19 20:09 UTC, berkerpeksag commented on Doc/whatsnew/3.5.rst
> +  Function :func:`~inspect.getargvalues` and :func:`~inspect.formatargvalues`
Or start with:

```rst
:func:`~inspect.getargvalues` and :func:`~inspect.formatargvalues` functions were inadvertently [...]
```

I'm not a native speaker so I hope @ncoghlan will chime in here :)

2017-02-20 23:35 UTC, Carreau commented
Thanks ! Comments addressed.

2017-02-21 07:39 UTC, berkerpeksag requested changes
Looks pretty good to me, just left two minor comments :)

2017-02-21 07:39 UTC, berkerpeksag commented on Doc/whatsnew/3.5.rst
> +   were inadvertently marked as deprecated with the release of Python 3.5.0
You forgot to end the sentence with a full stop :)

2017-02-21 07:39 UTC, berkerpeksag commented on Doc/whatsnew/3.5.rst
> +.. note::
Looking at this again, I think using a note directive is not needed in 3.5 whatsnew page.

2017-02-21 16:53 UTC, Carreau commented on Doc/whatsnew/3.5.rst
> +.. note::
Do you mean removing the `.. note::` altogether along with the text, or just demote the text to a plain paragraph ?

2017-02-21 19:23 UTC, berkerpeksag commented on Doc/whatsnew/3.5.rst
> +.. note::
Sorry, I wasn't clear in my earlier comment. I meant the latter one.

2017-02-22 03:03 UTC, Carreau commented on Doc/whatsnew/3.5.rst
> +.. note::
Ok, Done. And full stop added at the end.

2017-02-22 05:43 UTC, berkerpeksag approved these changes

2017-02-22 05:45 UTC, merged

2017-02-22 05:46 UTC, berkerpeksag commented
Thanks!

2017-02-22 18:23 UTC, Carreau commented
> Thanks!

Thanks as well.

2017-02-23 05:03 UTC, ncoghlan commented
@berkerpeksag Thanks, you picked up several things I missed :)