bpo-36216: Add check for characters in netloc that normalize to separators
python/cpython pull request #12201
Opened 2019-03-06 17:45 UTC by zooba

2019-03-06 18:07 UTC, tiran commented on Lib/urllib/parse.py
> +import unicodedata
Please load the module only when necessary. The unicodedata is a very large module and usually not loaded. The shared library is over 1 MB. 

```
>>> import urllib.parse, urllib.request
>>> import sys
>>> 'unicodedata' in sys.modules
False
```

2019-03-06 20:02 UTC, tiran requested changes
Please optimize ``import unicodedata``.

2019-03-06 20:03 UTC, tiran approved these changes

2019-03-06 20:03 UTC, tiran commented
sorry, GH didn't refresh.

2019-03-07 16:02 UTC, zooba commented
I'm removing the "needs backport" tags and will create the backports manually. In particular, the docs need to be slightly different for each version.

I'll probably also have to come back later and add the CVE reference once we're assigned one (if we want it in there).

2019-03-07 16:02 UTC, merged

2019-05-28 09:34 UTC, mcepl commented on Lib/urllib/parse.py
> +    _, _, netloc = netloc.rpartition('@') # anything to the left of '@' is okay
@zooba @tiran Could you tell me something about this line (it is now https://github.com/python/cpython/blob/master/Lib/urllib/parse.py#L405)? It seems to me that it exactly breaks the first example from https://bugs.python.org/issue36216:
```py
>>> u = "https://example.com\uFF03@bing.com"
>>> urlsplit(u).netloc.rpartition("@")[2]
bing.com
```