gh-120802: Providing more information on `__getitem__`.
python/cpython pull request #122178
Opened 2024-07-23 14:12 UTC by Alex-Wasowicz

2024-07-23 15:13 UTC, picnixz requested changes

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   Expressions like: ::
```suggestion
   Expressions like::
```

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   are translated into:. ::
```suggestion
   are translated into::
```

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   improper type.
```suggestion
   incorrect type.
```

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   improper type.
```suggestion
   with custom behaviour on indexing. The implementation is responsible for
   handling keys of inappropriate type, e.g., by raising a :exc:`TypeError`.
```

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> -      :keyword:`for` loops expect that an :exc:`IndexError` will be raised for
Where did this note disappear?

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   (set to :const:`None` is not considered missing), the :func:`reversed`
This is too verbose.

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +      __reversed__ = collections.abc.Sequence.__reversed__
I don't think this should be given.

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   (set to :const:`None` is not considered missing), the :func:`iter` built-in
Well... I would say that it is obvious that setting it to `None` is not considered as missing since... you would have it. Are there cases where setting something to `None` is actually considered to be missing?

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   :class:`collections.abc.Sequence`, ``__getitem__`` should also:.
```suggestion
   :class:`collections.abc.Sequence`, ``__getitem__`` should also:
```

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   3. For non-integer key that supports :func:`operator.index`, use that
Swap the wording (put "Use..." at the front).

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   2. For all integer keys outside of bounds ``-len(self) <= key < len(self)``,
This should not necessarily be the case. For instance, if you implement a list that reduces the index modulo its length.

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +      index as integer key.
It should probably raise a TypeError otherwise.

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   that is also a ``Sequence[Sequence]``:. ::
```suggestion
   that is also a ``Sequence[Sequence]`::
```

General tips: Don't use a period after a colon and use `::` to print a colon and consider the next indented block as a code-block (this is a Sphinx trick).

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   Second, there is expected behaviour for :term:`mapping` types:.
```suggestion
   Second, there is expected behaviour for :term:`mapping` types:
```

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   :ref:`types-genericalias` of :class:`collections.abc.Mapping`.
This paragraph is too compact for the reader. You should split the requirements from the static type checkers (which I'm not sure should be mentioned here at all).

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +   Lastly, here is an example of possible implementation for ``Matrix``,
When you say "first, second, lastly", it appears like you are describing requirements but all of them are actually unrelated to each other. You can just start your paragraphs normally like "For Sequence types, ...", "For mapping types,..." and use an Example section.

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +              return Matrix(self._rows_list[key])
You return is not covariant for subclasses here. Ideally, it should be `self.__class__(...)`.

2024-07-23 15:13 UTC, picnixz commented on Doc/reference/datamodel.rst
> +              return self._rows_list[key]
What would be `rows_list`? please provide a complete  example instead of a partial one.

2024-07-23 15:15 UTC, picnixz commented
There are various points that you could improve:

- Check the Sphinx syntax with colons (and do not put a period after a colon in general).
- Complete your example.
- Try to avoid compact paragraphs with requirements. Your bullet list was good for sequences, but for mappings everything was in compact form making it hard to read.
- I wouldn't say anything about type checkers in general, at least not in this section. Instead, you can just recommend inheriting from `collections.abc.Mapping` or `collections.abc.Sequence` in generla.

2025-01-15 11:18 UTC, Alex-Wasowicz commented
No point in keeping this open. I will try to make those changes in separate PR-s, with step by step commits.

2025-01-15 11:18 UTC, closed without merging