gh-83938: Stop incorrectly RFC 2047 encoding non-ASCII email addresses
python/cpython pull request #122540
Opened 2024-08-01 00:35 UTC by medmunds

This PR also fixes gh-122476, which is the same underlying issue.

Email generators had been incorrectly flattening non-ASCII email addresses to RFC 2047 encoded-word format, leaving them undeliverable. (RFC 2047 prohibits use of encoded-word in an addr-spec.) This change raises a ValueError when attempting to flatten an EmailMessage with a non-ASCII addr-spec and a policy with `utf8=False`. (Exception: If the non-ASCII address originated from parsing a message, it will be flattened as originally parsed, without error.)

Non-ASCII email addresses are supported when using a policy with `utf8=True` (such as email.policy.SMTPUTF8) under RFCs 6531 and 6532.

Non-ASCII email address domains (but not localparts) can also be used with non-SMTPUTF8 policies by encoding the domain as an IDNA A-label. (The email package does not perform this encoding, because it cannot know whether the caller wants IDNA 2003, IDNA 2008, or some other variant such as UTS-46.)

2024-08-01 01:08 UTC, medmunds commented
This is based on https://github.com/python/cpython/issues/81074#issuecomment-1093823543:

> we should probably be raising an error if the rendering policy does not have utf8=True and we don't have an "original source line" from parsing a message (which is the case here), rather than using the incorrect RFC2047 encoding.

Checking `part.token_type == 'addr-spec'` seemed like the simplest approach.

An alternative would be to introduce a new `NonASCIIDomainLiteralDefect` paralleling `NonASCIILocalPartDefect` and apply it in _header_value_parser.get_domain_literal(). And add `NonASCIIAddrSpecDefect` as a superclass of both. Then change _refold_parse_tree() to check `any(isinstance(d, NonASCIIAddrSpecDefect) for d in part.all_defects)` (and perhaps move it up with the other UnicodeEncodeError logic). (If we go this direction, PR #122477 will also need an update.)

Also, I *think* `charset == 'unknown-8bit'` is only possible in _refold_parse_tree() when the non-ASCII characters resulted from parsing an existing message: see the UndecodableBytesDefect logic just above the new code. (The added tests seem to confirm this.)

2024-08-01 01:58 UTC, medmunds commented
Fixes #83938

2025-03-31 21:27 UTC, bitdancer requested changes
Your analysis is solid and the fix looks great.  We'll need a follow on PR to have smtplib handle the new error, but that should be a trivial PR.

2025-03-31 21:27 UTC, bitdancer commented on Lib/test/test_email/test_generator.py
> +                    " '{}'".format(msg['To'].addresses[0].addr_spec)
I prefer to not require an exact wording for error messages.  I would write this:
```
expected_error = (
    "(?i)(?=.*non-ascii)(?=.*utf8.*True)"
    f"(?=.*{re.escape(msg['To'].addresses[0].addr_spec)})"
    )
```
to require only what I consider to be the essential parts of the message.

2025-03-31 21:27 UTC, bitdancer commented on Lib/email/_header_value_parser.py
> +                raise ValueError(
ValueError is correct, but we don't want smtplib caching *all* ValueErrors, so we're going to need a ValueError subclass here.  How about InvalidMailboxError?

This should probably be added to the generator and/or the policy docs.

2025-03-31 21:27 UTC, bitdancer commented on Misc/NEWS.d/next/Library/2024-07-31-17-22-10.gh-issue-83938.TtUa-c.rst
> +``utf8=False``.
This needs to mention the new error that will be raised.  Here is my suggestion:

The :mod:`email` module no longer incorrectly encodes non-ascii characters in email addresses using :rfc:2047 encoding.  Under a policy with `utf8=True` this means the addresses will be correctly passed through.  Under a policy with `utf8=False`, attempting to serialize a message with non-ASCII email addresses will now result in a :exc:`InvalidMailboxError`.

2025-04-01 20:09 UTC, medmunds commented on Lib/email/_header_value_parser.py
> +                raise ValueError(
I wasn't sure whether InvalidMailboxError should subclass MessageError or HeaderWriteError, but went with the more general MessageError.

2025-04-01 20:26 UTC, medmunds commented
I have made the requested changes; please review again

2025-05-18 21:25 UTC, bitdancer requested changes
Sorry it took me so long to get back to this.

2025-05-18 21:25 UTC, bitdancer commented on Lib/email/_header_value_parser.py
> +                    " '{}'".format(part)
Would f"Non-ASCII mailbox {str(part)!r} is invalid under current policy setting (utf8=False)" be clearer do you think?

2025-05-18 21:25 UTC, bitdancer commented on Misc/NEWS.d/next/Library/2024-07-31-17-23-06.gh-issue-122476.TtUa-c.rst
> +The :mod:`email` module no longer incorrectly encodes non-ASCII characters
Duplicate news item.

2025-05-26 23:23 UTC, medmunds commented on Misc/NEWS.d/next/Library/2024-07-31-17-23-06.gh-issue-122476.TtUa-c.rst
> +The :mod:`email` module no longer incorrectly encodes non-ASCII characters
I've updated the blurbs to address the two issues and offer specific advice for each.

If there's some incantation that allows a single news item to cover both, happy to change to that. (But I'm guessing that requires someone who's authorized to argue with the Bedevere bot, which I am not.)

2025-05-27 00:01 UTC, medmunds commented
> We'll need a follow on PR to have smtplib handle the new error, but that should be a trivial PR.

It looks like smtplib's send_message() already detects (some) non-ASCII mailboxes and if necessary, automatically clones a policy with `utf8=True` and requires SMTPUTF8. The cases handled by smtplib's current code should never get an InvalidMailboxError, so I'm not sure what would be needed.

There's a potential enhancement, but it's a (little) bit more involved. send_message()'s international detection doesn't check all address headers—e.g., an IDN reply-to would fool it. (And its `from_addr` and `to_addrs` params make it ignore the corresponding message headers.) That logic could be made more robust by serializing unconditionally with the message's own policy, and if that raises InvalidMailboxError (or already has utf8 True) falling into the SMTPUTF8-required code.

2025-05-27 00:02 UTC, medmunds commented
I have made the requested changes; please review again

2026-04-18 00:34 UTC, medmunds commented
🤖💩

2026-04-22 19:47 UTC, bitdancer approved these changes

2026-04-22 19:47 UTC, bitdancer commented on Misc/NEWS.d/next/Library/2024-07-31-17-23-06.gh-issue-122476.TtUa-c.rst
> +The :mod:`email` module no longer incorrectly encodes non-ASCII characters
Fair enough.  I don't know how to argue with the bot either, and as you point out the bugs are subtly different ;)

2026-04-22 21:49 UTC, bitdancer requested changes
Well, it turns out that this bug goes a bit deeper than apparent. `addr_spec` was already supposed to be prevented from being encoded, but the logic around as_ew_allowed is broken: it doesn't "look inside" the token it is encoded to make sure *all* of it can be encoded.  The fix in this PR also has its problems, as proven by the test failures after merge with main: want_encoding can be set when what is wanted is wrapping, rather than *needing* encoding.  Those should probably have been two separate flags...but at this point the folder is a bit of a patchwork mess.  (I plan to fix that...someday).

If we fix as_eq_allowed handling I think it will make those test failures go away, as well as simplifying the logic for raising the error, but it won't be certain until we try it.

There is another test failure as well, but I think that's not a bug, but rather a change in  behavior that the test needs to adapt to.  I haven't proven that yet, though :)

2026-04-23 18:23 UTC, bitdancer commented
Looking at the code more closely, it is supposed to already be handing this case.  The fact that it isn't indicates there's a bug there, and there were certainly missing tests.  I will poke at this.

2026-04-27 13:04 UTC, bitdancer commented
I've crafted a more complete fix for the bug.  If you could review it, @medmunds, that would be great.

Since I switched to using the existing HeaderWriteError, I'm wondering if we need the versionchanged at all at this point, if anyone has input on that.

2026-04-28 01:47 UTC, medmunds commented
> I've crafted a more complete fix for the bug. If you could review it, @medmunds, that would be great.

Sorry for the delay, I've been deep in some Django work. This and #122477 are both at the top of my list tomorrow.

2026-04-29 23:50 UTC, medmunds reviewed
@bitdancer this LGTM. I pushed a couple of fixes to the docs.

I'd be inclined to keep the versionchanged note. (Unless there's some style guide policy against that for bug fixes.) There seems to be a popular misconception—in many email libraries and systems—that any MIME header with non-ASCII chars can just be run through rfc2047. The versionchanged note makes it clear dropping rfc2047 here was a deliberate fix in Python's email package, and might help discourage future requests to add it back in.

2026-04-30 16:14 UTC, bitdancer approved these changes

2026-04-30 16:52 UTC, bitdancer commented
Since this is a bug fix that isn't going to get backported because of backward compatibility concerns, we'll keep the versionchanged.  We can always delete it if someone objects.

2026-04-30 16:58 UTC, bitdancer commented
It occurs to me that if it is worth a versionchanged there should also be a What's New entry.  Do you want to write one?

2026-04-30 17:42 UTC, medmunds commented
> It occurs to me that if it is worth a versionchanged there should also be a What's New entry. Do you want to write one?

Something like this? [edited]

```patch
Index: Doc/whatsnew/3.15.rst
<+>UTF-8
===================================================================
diff --git a/Doc/whatsnew/3.15.rst b/Doc/whatsnew/3.15.rst
--- a/Doc/whatsnew/3.15.rst	(revision 71636d347e37db41a11a21419137fd7eb3423f74)
+++ b/Doc/whatsnew/3.15.rst	(date 1777572899407)
@@ -914,6 +914,16 @@
   (Contributed by Eric Froemling in :gh:`149085`.)
 
 
+email
+-----
+
+* Email generators now raise an error when an :class:`.EmailMessage` cannot be
+  accurately flattened due to a non-ASCII email address (mailbox) in an address
+  header. :attr:`.EmailPolicy.utf8` offers options for supporting Email Address
+  Internationalization (EAI).
+  (Contributed by R David Murray and Mike Edmunds in :gh:`122540`.)
+
+
 functools
 ---------
 

```

[Edited: trying to capture the attention of users who might be affected and direct them to the docs that have complete details.]

2026-04-30 19:14 UTC, bitdancer commented
Yeah, that looks good.  Though I'd say "The documentation for...offers" just to make it clear that it isn't the policy option itself that provides the support.

2026-04-30 19:15 UTC, bitdancer commented
Although I guess technically it does...maybe your wording is correct.

2026-05-01 17:52 UTC, merged