bpo-36250: ignore ValueError from signal in non-main thread
python/cpython pull request #12251
Opened 2019-03-09 15:05 UTC by blueyed

2019-03-10 19:30 UTC, zware requested changes

2019-03-10 19:30 UTC, zware commented on Lib/pdb.py
> +                signal.signal(signal.SIGINT, pdb.Pdb._previous_sigint_handler)
```suggestion
                signal.signal(signal.SIGINT, Pdb._previous_sigint_handler)
```

2019-03-10 19:30 UTC, zware commented on Lib/pdb.py
> +                pdb.Pdb._previous_sigint_handler = None
```suggestion
                Pdb._previous_sigint_handler = None
```

2019-03-10 22:52 UTC, blueyed commented
I have made the requested changes; please review again.

2019-09-09 10:44 UTC, zware approved these changes

2019-09-09 10:45 UTC, merged

2019-09-09 10:46 UTC, miss-islington commented
Thanks @blueyed for the PR, and @zware for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-09-09 10:46 UTC, zware commented
Thanks for the patch, and sorry for the delay in my re-review!