gh-80222: Fix email address header folding with long quoted-string
python/cpython pull request #122753
Opened 2024-08-06 19:42 UTC by medmunds

Fixes #80222 (bpo-36041).

Email generators using email.policy.default could incorrectly omit the quote ('"') characters from a quoted-string during header refolding, leading to invalid address headers and enabling header spoofing. This change restores the quote characters on a bare-quoted-string as the header is refolded, and escapes backslash and quote chars in the string.

Fix is adapted from PR #12054.

[This fixes a #security-issue. PRST instructed me to handle the fix publicly.]

2024-10-29 19:45 UTC, medmunds commented
Requesting a review from @bitdancer (who probably knows the most about this code, and was actively involved in the discussion on the original report five years ago).

(See also PR #122754 which aims to fix a similar security issue with encoded-words.)

2025-01-07 13:25 UTC, encukou approved these changes
By my reading of the code & RFC, this is correct.
I'd appreciate an additional review from an email expert though.

2025-01-14 00:08 UTC, medmunds commented
Could someone add the topic-email label?

2025-01-18 19:50 UTC, bitdancer requested changes
Great work, thank you.  If I'd gotten that test you modified correct in the first place, this would have been fixed long ago.

2025-01-18 19:50 UTC, bitdancer commented on Lib/email/_header_value_parser.py
> +def escape_for_quotes(value):
Let's call this 'make_quoted_pairs'.  That aligns it a bit better with the RFC terminology.

2025-01-18 19:50 UTC, bitdancer commented on Lib/email/_header_value_parser.py
> +                # Restore the quotes and escape contents.
Let's go ahead and be wordy here: "To fold a quoted string we need to create a list of terminal tokens that will render the leading and trailing quotes and use quoted pairs in the value as appropriate"

2025-01-18 19:50 UTC, bitdancer commented on Lib/email/_header_value_parser.py
> +                    [dquote])
Note my XXX comment above the definition of "DOT".  That should get fixed someday.  To avoid the problem that comment addresses here, create two separate ValueTerminal instances.  it doesn't make any practical difference and is slightly less efficient, but it is more correct per the design of the parser and parse tree (that is, these are supposed to be 'unique quote marks'.  Since this is only getting used in the folder it shouldn't actually be a problem ever, but I'd like the code to be self consistent.

2025-01-18 19:50 UTC, bitdancer commented on Misc/NEWS.d/next/Security/2024-08-06-11-43-08.gh-issue-80222.wfR4BU.rst
> +spoofing via a carefully crafted display-name.
I'd like to be a bit more precise here: "Fix bug in the folding of quoted strings.  Previously when a quoted string was folded so that it spanned more than one line, the surrounding quotes and internal escapes would be omitted.  This could theoretically be used to spoof header lines using a carefully constructed quoted string if the resulting rendered email was transmitted or re-parsed."

2025-01-18 21:40 UTC, medmunds commented on Lib/email/_header_value_parser.py
> +                    [dquote])
I'd just been wondering about exactly that, and had missed the XXX comment.

2025-01-18 21:41 UTC, medmunds commented
I have made the requested changes; please review again.

@bitdancer thanks for the review!

2025-01-18 21:43 UTC, medmunds commented
@encukou and @bitdancer thanks for the reviews. Any chance you could also look at the related PR #122754, which fixes a similar problem in refolding rfc2047 encoded-words?

2025-01-18 22:26 UTC, bitdancer commented
Sure, I've added it to my list.  I'm finally back to contributing more actively after years away, but it may still take me a while to get to it ;)

2025-01-19 00:47 UTC, bitdancer approved these changes
LGTM

2025-01-19 00:50 UTC, merged

2025-08-14 21:11 UTC, serhiy-storchaka commented
Reminder about backporting. @medmunds @bitdancer

2025-08-15 10:06 UTC, encukou commented
GH-132371 is a backport of this pull request to the 3.9 branch.