gh-118926: Spill deferred references to stack in cases generator
python/cpython pull request #122748
Opened 2024-08-06 18:26 UTC by colesbury

This automatically spills the results from `_PyStackRef_FromPyObjectNew` to the in-memory stack so that the deferred references are visible to the GC before we make any possibly escaping call.

2024-08-06 19:03 UTC, colesbury commented
@markshannon, this is the spilling logic split out from:

* https://github.com/python/cpython/pull/121318

I've updated it to handle the changes to the stack from https://github.com/python/cpython/pull/122286. This required tracking output local variables in the stack before emitting tokens for a uop.

I've also moved the analysis to analyzer.py.

2024-08-07 13:41 UTC, markshannon requested changes
The stack shouldn't have "outputs" (or inputs) as it should model the state of the stack only.
The outputs (or inputs) are properties of the uops and instructions.

That can be fixed by passing the output variables to `flush_single_var` instead of caching them on the stack.

Note:
   I think the correct long term approach to handling stack spilling is to lazily spill when code escapes. But that involves considerably deeper analysis.
Although this PR doesn't do that, it doesn't prevent us from doing in future. So I am happy to merge it once the above issue is fixed.

2024-08-07 13:41 UTC, markshannon commented on Tools/cases_generator/analyzer.py
> +        if node.block.tokens[idx-1].kind != "EQUALS":
I think this is OK, as the first token should be the opening brace. Could you add a comment as to why this is safe.

2024-08-07 13:41 UTC, markshannon commented on Tools/cases_generator/stack.py
> +        self.outputs: list[Local] = []
The stack shouldn't have "outputs" (or inputs) as it should model the state of the stack.
The outputs (or inputs) are properties of the uops and instructions.

2024-08-07 13:41 UTC, markshannon commented on Tools/cases_generator/stack.py
> +    def flush_single_var(self, out: CWriter, var_name: str, cast_type: str = "uintptr_t", extract_bits: bool = False) -> None:
Rather than caching `outputs` on the stack,  can you pass `outputs` as a `list[StackItem]` argument?

2024-08-07 13:41 UTC, markshannon commented on Tools/cases_generator/optimizer_generator.py
> +        outputs: list[Local] = []
The optimizer generator doesn't need to track the state of locals, nor is the GC involved, so shouldn't change.

2024-08-07 14:20 UTC, colesbury commented on Tools/cases_generator/analyzer.py
> +        if node.block.tokens[idx-1].kind != "EQUALS":
I think that's right, but I'll add condition to ensure that `idx != 0` to make it explicit.

2024-08-07 14:59 UTC, colesbury commented on Tools/cases_generator/stack.py
> +        self.outputs: list[Local] = []
I've removed this

2024-08-07 15:00 UTC, colesbury commented on Tools/cases_generator/stack.py
> +    def flush_single_var(self, out: CWriter, var_name: str, cast_type: str = "uintptr_t", extract_bits: bool = False) -> None:
I added `outputs` as a `list[StackItem]`

2024-08-07 15:00 UTC, colesbury commented on Tools/cases_generator/optimizer_generator.py
> +        outputs: list[Local] = []
I've reverted the changes to `optimizer_generator.py`

2024-08-07 15:01 UTC, colesbury commented
@markshannon, would you please take another look at it.

I have made the requested changes; please review again

2024-08-07 15:49 UTC, markshannon approved these changes
Thanks for bearing with me on this one.

2024-08-07 17:23 UTC, merged