gh-122712: Guard against `__code__` reassignment in `CALL_ALLOC_AND_ENTER_INIT`
python/cpython pull request #122713
Opened 2024-08-06 00:09 UTC by mpage

Use function versions to guard against someone reassigning `__code__`.

2024-08-06 01:47 UTC, mpage commented
Failing hypothesis tests are a known issue: https://github.com/python/cpython/issues/122686

2024-08-06 02:20 UTC, mpage commented
JIT test failures look like unrelated issues with qemu:

```
ERROR:../../plugins/core.c:221:qemu_plugin_vcpu_init_hook: assertion failed: (success)
Bail out! ERROR:../../plugins/core.c:221:qemu_plugin_vcpu_init_hook: assertion failed: (success)
aarch64-binfmt-P: ./include/qemu/rcu.h:101: rcu_read_unlock: Assertion `p_rcu_reader->depth != 0' failed.
```

2024-08-07 23:43 UTC, mpage commented
@brandtbucher @markshannon - I've updated this to perform the necessary checks inline in `CALL_ALLOC_AND_ENTER_INIT` rather than use function versions. Would you please have a look?

2024-08-15 10:30 UTC, markshannon requested changes
This looks like the correct fix. Thanks.

I'd like the DEOPT test streamlined a bit, but it looks good otherwise.

2024-08-15 10:30 UTC, markshannon commented on Python/bytecodes.c
> +            DEOPT_IF(_Py_Specialize_CheckCode(code) != _Py_Specialize_Ok);
We want guards to be fast; just a few machine instructions if possible.
Even if the C compiler can inline and optimize it, I'd prefer the stripped down version:
```suggestion
            DEOPT_IF(code->co_flags & (CO_VARKEYWORDS | CO_VARARGS | CO_OPTIMIZED)) != CO_OPTIMIZED)
            DEOPT_IF(code->co_kwonlyargcount);
```

2024-08-15 15:39 UTC, brandtbucher approved these changes
Agreed with @markshannon's suggestion. Otherwise, looks good!

2024-08-20 18:58 UTC, mpage commented
Looks like this was fixed on main by gh-123140. The underlying issue is still present in 3.13, however. I'm going to close this and reassign gh-122712 to @markshannon for the fix on 3.13.

2024-08-20 22:14 UTC, mpage commented
Closing this since gh-123140 fixes it on main.

2024-08-21 12:18 UTC, markshannon commented
Sorry. I meant to merge this first, so we got the test before changing `CALL_ALLOC_AND_ENTER_INIT`. It appears I forgot.

Do you want to re-open this PR with just the test, or make a new one?

2024-08-21 15:33 UTC, ericsnowcurrently commented
```
======================================================================
FAIL: test_basic_multiple_interpreters_deleted_no_reset (test.test_import.SinglephaseInitTests.test_basic_multiple_interpreters_deleted_no_reset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildbot/Library/Developer/XCTestDevices/163B47BC-A1C1-4382-9772-4D79687530BB/data/Containers/Bundle/Application/FDBABAF6-E02D-45C5-A42C-5FCCA078C9B2/iOSTestbed.app/python/lib/python3.13/test/test_import/__init__.py", line 136, in wrapper
    func(self)
    ~~~~^^^^^^
  File "/Users/buildbot/Library/Developer/XCTestDevices/163B47BC-A1C1-4382-9772-4D79687530BB/data/Containers/Bundle/Application/FDBABAF6-E02D-45C5-A42C-5FCCA078C9B2/iOSTestbed.app/python/lib/python3.13/test/test_import/__init__.py", line 3031, in test_basic_multiple_interpreters_deleted_no_reset
    self.check_copied(loaded_interp1, base)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/buildbot/Library/Developer/XCTestDevices/163B47BC-A1C1-4382-9772-4D79687530BB/data/Containers/Bundle/Application/FDBABAF6-E02D-45C5-A42C-5FCCA078C9B2/iOSTestbed.app/python/lib/python3.13/test/test_import/__init__.py", line 2694, in check_copied
    self.assertNotEqual(snap.id, base.snapshot.id)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 4607884272 == 4607884272

----------------------------------------------------------------------
```

2024-08-21 15:34 UTC, ericsnowcurrently commented
Also, the failure is relative to the 3.13 backport: gh-123184.

2024-08-21 17:30 UTC, mpage commented
That failure seems like it should be unrelated to this change. I also haven't been able to reproduce it locally.

2024-08-21 17:42 UTC, mpage commented
@markshannon - No worries. Reopened this with just the test.

2024-08-22 07:38 UTC, merged