gh-122781: fix time format bug
python/cpython pull request #122829
Opened 2024-08-08 15:00 UTC by midnightstardust

Fixed it such that %z is now read as optional and can be an empty string.

2025-04-25 10:27 UTC, StanFromIreland commented on Misc/NEWS.d/next/Library/2024-08-08-15-29-34.gh-issue-122781.4gEwEt.rst
> +Make %z represent an optional UTC offset instead of mandating a UTC offset
Duplicate NEWS

2025-04-25 10:27 UTC, StanFromIreland requested changes
Please add tests and remove the duplicate NEWS entry.

2025-06-29 13:10 UTC, donbarbos commented
@StanFromIreland apparently you can now close this PR since the issue has been resolved

2025-06-29 14:10 UTC, closed without merging

2025-06-29 14:10 UTC, StanFromIreland commented
Thank you, yes this was fixed with #132922.