[3.12] gh-122695: Fix double-free when using `gc.get_referents` with a freed `_asyncio.FutureIter`
python/cpython pull request #122834
Opened 2024-08-08 18:25 UTC by ZeroIntensity

CC @vstinner, @douglas-raillard-arm

This is a (somewhat hacky) way to do it while keeping items in the freelist returned by `gc.get_referents`. The ideal solution would be to remove the traversal of the freelist all together, but that might be a breaking change (depending on how `lisa` relied on it).

* Issue: gh-122431

2024-08-08 18:27 UTC, vstinner requested changes
This change is wrong. A freelist is not storing objects but just raw memory.

module_traverse() should be modified to not visit the free list.

2024-08-08 18:31 UTC, ZeroIntensity commented
(Hit the wrong button when copy-pasting the `<gh-issue-number>` shindig, my bad!)

2024-08-08 18:40 UTC, colesbury commented
Do you want this in 3.13 as well?

2024-08-08 18:43 UTC, ZeroIntensity commented
> Do you want this in 3.13 as well?

Nope, this issue only occurs on 3.12.

2024-08-08 18:55 UTC, colesbury commented
3.13 has the same underlying bug: `module_traverse` visits the free list, and the test case you added hangs (forever?) on 3.13.

2024-08-08 18:56 UTC, ZeroIntensity commented
It's now just a removal of the traversal, as @vstinner suggested.

2024-08-08 18:57 UTC, ZeroIntensity commented
> 3.13 has the same underlying bug: `module_traverse` visits the free list, and the test case you added hangs (forever?) on 3.13.

It does? I thought we tried this on 3.13 already. I guess this does go in 3.13 then.

2024-08-08 18:59 UTC, colesbury commented
> I thought we tried this on 3.13 already

I think someone confused 3.13 with the main branch (future 3.14 release)

2024-08-08 19:00 UTC, ZeroIntensity commented
> > I thought we tried this on 3.13 already
> 
> I think someone confused 3.13 with the main branch (future 3.14 release)

Will make a PR for 3.13

2024-08-09 10:01 UTC, vstinner commented
The issue should be fixed in the 3.13 branch and then backported automatically to 3.12. I close this PR in favor of https://github.com/python/cpython/pull/122837

2024-08-09 10:01 UTC, closed without merging