gh-122928: Make thread state(tstate) pointer safe
python/cpython pull request #122929
Opened 2024-08-12 02:08 UTC by Wulian233

To prevent dangling pointer issues, adding a check for NULL ensures that invalid pointers are not dereferenced

2024-08-12 08:55 UTC, ZeroIntensity commented
I'm not totally sure this fix is necessary :(

A `NULL` check doesn't prevent any problems with dangling pointers, since they are non-`NULL`.

2024-08-12 08:57 UTC, ZeroIntensity commented on Python/pystate.c
> -        // XXX This isn't completely safe from daemon thraeds,
I would keep this comment, `tstate` could still be dangling in the sense that it's freed memory.

2024-08-12 08:59 UTC, Wulian233 commented
😧

2024-08-12 19:29 UTC, kumaraditya303 requested changes
Adding `NULL` pointer checks doesn't prevent dangling pointers.

2024-08-12 23:03 UTC, ZeroIntensity commented
It might be best to just this into an assertion `assert(tstate != NULL)`

2024-08-13 01:13 UTC, Wulian233 commented
Can I solve this by (code from https://github.com/python/cpython/blob/main/Python/_warnings.c#L45-L45)

```c
int
_PyThreadState_MustExit(PyThreadState *tstate)
{
    PyThreadState *current_tstate = _PyThreadState_GET();
    if (current_tstate == NULL) {
        (void)check_interp(NULL);
        return 1;
    }
    
    if (!check_interp(current_tstate->interp)) {
        return 1;
    }

   ...

```

2024-08-13 08:08 UTC, ZeroIntensity commented
No, `check_interp` just makes sure that it's non-NULL, not dangling. It's very difficult to safely detect if something is an invalid pointer at runtime, you should leave that to tools like `valgrind`. (FWIW, C doesn't support inline functions like in your snippet.)

2024-08-13 08:08 UTC, ZeroIntensity commented on Python/pystate.c
> +    }
Let's just make this an assertion.
```suggestion
    assert(tstate != NULL);
```

2024-08-13 11:47 UTC, Wulian233 commented
I see. Finally, let's use assert(tstate! = NULL) Thank you for your review

2024-08-13 11:48 UTC, Wulian233 commented on Python/pystate.c
>  // is used, the pointer is not deferenced.
I type a space when I revert the changes, hopefully not a big problem

2024-08-14 10:03 UTC, ZeroIntensity commented
FWIW, I think this should be a "skip news."
We are just enforcing a pre-condition, as @picnixz mentioned, users will not see these changes.

2024-08-14 11:01 UTC, picnixz commented on Misc/NEWS.d/next/Core_and_Builtins/2024-08-12-10-02-40.gh-issue-122928.e6_yVr.rst
> +Make thread state(tstate) pointer safe
No need for a NEWS entry. First, it's only guaranteed in debug builds, second, it was a pre-condition.

2024-08-14 11:17 UTC, Wulian233 commented
deleted

2024-08-14 12:56 UTC, ZeroIntensity approved these changes
Looks good, now we're just validating a precondition. @kumaraditya303, could you re-review?

2024-09-18 17:17 UTC, vstinner requested changes
This change is wrong. There are exactly 4 calls to this function. 1 in _threadmodule.c, 3 in ceval_gil.c. All code paths check that tstate is not NULL before calling _PyThreadState_MustExit().

Moreover, I don't understand which problem you are trying to solve here. Dangling pointers cannot be avoided by checking a pointer value (NULL or anything else).

2024-09-18 17:17 UTC, closed without merging

2024-09-18 17:22 UTC, ZeroIntensity commented
Yeah, this was originally conceived as a way to prevent dangling pointers, but there was some misunderstanding on the difference between a `NULL` and dangling pointer. It eventually just got turned into an assertion.