gh-123080: Additional ast optimizations
python/cpython pull request #123081
Opened 2024-08-16 19:09 UTC by wrongnull

With this pr certain expression templates produce less byte code and and do more folding in ```fold_compare``` function

2024-08-16 19:13 UTC, wrongnull commented
I guess there is no need to update news for this

2024-08-16 20:38 UTC, terryjreedy commented
I believe that changing bytecode requires News and What's New items.

2024-08-17 08:50 UTC, wrongnull commented
I'll convert it to draft so far because of tests segfaults. Also I'll wait until https://github.com/python/cpython/pull/122667 will be merged

2024-08-18 15:16 UTC, wrongnull commented
For now, everything works fine and all the previous optimizations are preserved. I'll wait for tests of ast optimizations to be merged.

2024-08-19 19:07 UTC, pablogsal commented on Python/ast_opt.c
> +            if (PyErr_ExceptionMatches(PyExc_KeyboardInterrupt)) {
There is no need to match against `PyExc_KeyboardInterrupt` here. Just treat this like a regular error and bubble up

2024-08-19 19:08 UTC, pablogsal commented on Python/ast_opt.c
> +                PyObject_GC_UnTrack(newval);
Why are you calling directly these GC functions? Just call a normal `Py_DECREF` when you are done with it

2024-08-19 19:08 UTC, pablogsal commented on Python/ast_opt.c
> +                PyObject_GC_UnTrack(newval);
Same as https://github.com/python/cpython/pull/123081/files#r1722232517

2024-08-19 19:08 UTC, pablogsal commented on Python/ast_opt.c
> +        if (arg->kind == Set_kind)
PEP 7: Add braces

2024-08-19 19:08 UTC, pablogsal commented on Python/ast_opt.c
> +            Py_SETREF(newval, PyFrozenSet_New(newval));
`PyFrozenSet_New` can fail, you need to check for errors and handle the failure

2024-08-19 19:09 UTC, pablogsal commented on Python/ast_opt.c
> +            if (has_starred(list_elts))
PEP 7: add braces

2024-08-19 19:12 UTC, pablogsal commented on Python/ast_opt.c
> +        if ((node->v.Compare.left->v.Constant.value) == (arg->v.Constant.value))
PEP 7: Add braces

2024-08-19 19:13 UTC, pablogsal commented on Python/ast_opt.c
> +    //lhs_const = node->v.Compare.left->v.Constant.value;
Why is this commented out?

2024-08-19 19:20 UTC, pablogsal requested changes
Left some comments

2024-08-19 20:12 UTC, wrongnull commented on Python/ast_opt.c
> +    //lhs_const = node->v.Compare.left->v.Constant.value;
Sorry I leave it by accident

2024-08-20 04:59 UTC, Eclips4 commented on Python/ast_opt.c
> +                PyObject_GC_Del(newval);
```suggestion
                Py_DECREF(newval);
```

2024-08-20 04:59 UTC, Eclips4 commented on Python/ast_opt.c
> +            Py_SETREF(newval, PyFrozenSet_New(newval));
This line was copied from `fold_iter`. So, `fold_iter` has the same issue (no error handling for NULL values on calls to `PyFrozenSet_New`). Do you think it's OK to address this issue in this PR?

2024-08-20 11:03 UTC, pablogsal commented
> Do you think it's OK to address this issue in this PR?

I prefer to do that separately because we want to back port it. I will take care of that

2024-08-21 04:03 UTC, closed without merging