gh-123142: Fix too wide source locations in tracebacks of exceptions from broken iterables in comprehensions
python/cpython pull request #123173
Opened 2024-08-20 11:31 UTC by iritkatriel

2024-08-21 12:24 UTC, markshannon requested changes
The code change looks good.
At least `class Iter` and maybe some more of the tests could be shared

2024-08-21 12:24 UTC, markshannon commented on Lib/test/test_dictcomps.py
> +        class Iter:
This appears in all three tests. Perhaps move it to test_support?

2024-08-21 12:24 UTC, markshannon commented on Lib/test/test_dictcomps.py
> +                {(x, x) for x in Iter(next_raises=True)}
This is a set comprehension
```suggestion
                {x:x for x in Iter(next_raises=True)}
```

2024-08-21 15:50 UTC, iritkatriel commented
I have made the requested changes; please review again.

2024-08-21 16:01 UTC, markshannon approved these changes
Looks good.

The code in the three `with self.subTest(func)` blocks look the same/very similar. I think they could be factored out, but that might just end up obscuring the intent. It's up to you if you want to factor it further.

2024-08-21 18:12 UTC, merged

2024-08-26 18:37 UTC, 15r10nk commented
@iritkatriel might it be that this fix changed the source range for exceptions in `__init__` and `__next__` but not for exceptions in `__iter__`.

```python
class Foo:
    def __iter__(self):
        assert False

a = [x for x in Foo()]
```

output (Python 3.13.0rc1+):
```python
Traceback (most recent call last):
  File "/home/frank/projects/cpython/codi.py", line 5, in <module>
    a = [x for x in Foo()]
        ^^^^^^^^^^^^^^^^^^
  File "/home/frank/projects/cpython/codi.py", line 3, in __iter__
    assert False
           ^^^^^
AssertionError
```

This is the example from the issue and I'm a little confused as to whether it was just forgotten or if I'm missing something here.

2024-08-27 23:09 UTC, iritkatriel commented
> This is the example from the issue and I'm a little confused as to whether it was just forgotten or if I'm missing something here.

So it seems. The test doesn't check for this too. Thanks for reporting, I'll fix.