[WIP] bpo-36287:  Ignoring optional field.
python/cpython pull request #12328
Opened 2019-03-14 14:35 UTC by eamanu

To avoid unnecessary verbose this PR add and `if` to know
if the field to return is not None

https://bugs.python.org/issue36287

2019-03-15 20:59 UTC, matrixise requested changes

2019-03-15 20:59 UTC, matrixise commented on Lib/ast.py
> +                ('%s=%s' % field for field in fields if field[1] !='None')
need a space after the operator `!=`

2019-03-16 03:42 UTC, eamanu commented on Lib/ast.py
> +                ('%s=%s' % field for field in fields if field[1] !='None')
Ready! thanks!

2019-03-26 19:03 UTC, brettcannon commented
Why is this a WIP? If this truly isn't ready to be considered for review then please close the PR.

2019-03-26 20:01 UTC, eamanu commented
Hi @brettcannon. I will close it now. I am working on this Issue, but you are right, when I have the "final" PR I will open it again.

2019-03-26 20:01 UTC, closed without merging