gh-67041: Allow to distinguish between empty and not defined URI components
python/cpython pull request #123305
Opened 2024-08-25 07:41 UTC by serhiy-storchaka

Changes in the `urllib.parse` module:
    
* Add option _allow_none_ in `urlparse()`, `urlsplit()` and `urldefrag()`. If it is true, represent not defined components as None instead of an empty string.
* Add option _keep_empty_ in `urlunparse()` and `urlunsplit()`. If it is true, keep empty non-None components in the resulting string.
* Add option _keep_empty_ in the `geturl()` method of `DefragResult`, `SplitResult`, `ParseResult` and the corresponding bytes counterparts.

2024-12-05 11:12 UTC, serhiy-storchaka commented
I am sorry, I forget to copy the `_keep_empty` attribute in copying/encoding/decoding methods. Now the PR is ready for review.

@orsenthil, @barneygale, could you please make a review?

2025-11-17 02:11 UTC, merwok commented
I think that `allow_none` is not the correct name: this is not about allowing nones in the input (like how `allow_fragments` allows fragment in the input), but about controlling the data returned.

Possible alternatives:
- `use_none` (short)
- `missing_as_none`
- `use_none_for_empty`

2025-11-17 09:09 UTC, serhiy-storchaka commented
Maybe `missing_as_empty`? In future the behavior will be changed to use None for missing by default.

2025-11-17 14:24 UTC, merwok commented
I think it should be `missing_as_empty_string` (short for _return missing values as empty strings_), which is long!

To change the default in the future, do you plan on adding a warning first?
I could see many projects not paying attention to the new param and getting surprised (or silent bugs) a few years after.

2025-11-17 14:34 UTC, serhiy-storchaka commented
> To change the default in the future, do you plan on adding a warning first?

On one hand, a warning will inform everyone about the change (it should be a FutureWarning). You will have to pass explicit True or False to silence it and get your behavior. This how we normally do. On other hand, the warning will unnecessary disturb those who are fine with any behavior. We will discuss this when the time come.

2025-11-17 14:39 UTC, serhiy-storchaka commented
> I think it should be `missing_as_empty_string` (short for _return missing values as empty strings_), which is long!

Currently, missing and empty component are not distinguishable. This parameter will allow to distinguish them. This PR adds also the `keeps_empty` parameter. So, "empty" refers not only to string, but to component. `missing_component_as_empty_component`, or simply `missing_as_empty`. Will it work?

2025-11-17 19:24 UTC, merwok commented
Ah your’re right, there is _empty component_ and _empty string_.

`missing_as_none` is good!

2025-11-17 19:27 UTC, merwok commented on Doc/library/urllib.parse.rst
> +   This allows to restore the URL that was parsed with option
```suggestion
   This allows rebuilding a URL that was parsed with option
```

2025-11-19 03:08 UTC, orsenthil requested changes, later dismissed

2025-11-19 03:08 UTC, orsenthil commented on Doc/library/urllib.parse.rst
> +.. function:: urlparse(urlstring, scheme=None, allow_fragments=True, *, missing_as_none=False)
I am really sorry, that I am contributing so late; but "missing_as_none=False" is confusing and not intuitive at all to me.

Pretty sure, others who have not participated are going to feel the same.


The function signature and term is not giving a signal on what it is meant to be. 

Are you open to new name?

2025-11-19 03:12 UTC, orsenthil commented on Doc/library/urllib.parse.rst
> +.. function:: urlparse(urlstring, scheme=None, allow_fragments=True, *, missing_as_none=False)
I am adding @gpshead, as one of the active developers in this area, to get his opinion too.

2025-11-19 06:01 UTC, gpshead reviewed
overall I like this, comments are all about how to explain it in the docs.

2025-11-19 06:01 UTC, gpshead commented on Doc/library/urllib.parse.rst
> +.. function:: urlparse(urlstring, scheme=None, allow_fragments=True, *, missing_as_none=False)
I'm fine with this name.  Admittedly I have spent too much time in the past wrangling problems in this library, but the reason it still works for me despite that is that it is a common concept: do you represent the absence of a value distinctly from the base zero/empty version of that type or not?  That is what None is for.  and *missing_as_none* is at least explicit in name to indicate that some values may be None.  I'm not going to call it _pretty_ but it is "understandable enough" for me.  I can't come up with anything that'd be meaningfully better rather than just alternately-understandable.

2025-11-19 06:01 UTC, gpshead commented on Doc/library/urllib.parse.rst
> +   By default, *keep_empty* is true if *parts* is the result of the
It is easy to miss this "footnote" about keep_empty not being a simple False default.  I think the function signature above should be more clear that it has a non-trivial default value when not explicitly specified.  something awkward with a fake descriptive name but indicative that people should read further for details keep_empty=_FALSE_UNLESS_PARTS_IS_A_URLSPLIT_RESULT or similar perhaps?

2025-11-19 06:01 UTC, gpshead commented on Doc/library/urllib.parse.rst
> +   By default, *keep_empty* is true if *parts* is the result of the
same comment as above.  make it obvious from the function signature that the default depends on the type of parts.

2025-11-19 08:28 UTC, serhiy-storchaka reviewed
Thank you for your attention.

I would like to take this opportunity to discuss a certain design issue. To make this change more user friendly, we need to keep the status of `missing_as_none` in the result of `urlsplit()` and others. So the user will not need to specify `keep_empty=True` each time they use `missing_as_none=True`, and change their code again in future. There are two ways to do this:

1. Return different subclasses of `SplitResult` (and of other 5 classes). This approach already was used to differentiate string/bytes results. This will add 12 new classes.
2. Add a (hidden) boolean attribute to instances of `SplitResult` (and of other 5 classes).

In both cases there are some issues with copying, pickling, etc, which will be resolved in different ways. In distant future, after flipping the default behavior and deprecating and removing the current behavior (if we completely remove it), we may return to the current state of 6 named tuple classes.

What approach do you prefer?

2025-11-19 08:28 UTC, serhiy-storchaka commented on Doc/library/urllib.parse.rst
> +.. function:: urlparse(urlstring, scheme=None, allow_fragments=True, *, missing_as_none=False)
What are your thoughts about `missing_as_empty` with the opposite semantic? In future, None will be returned for not defined components by default, and you will need to specify `missing_as_none=False` or `missing_as_empty=True` to restore the current behavior.

2025-11-19 08:28 UTC, serhiy-storchaka commented on Doc/library/urllib.parse.rst
> +   By default, *keep_empty* is true if *parts* is the result of the
Pydoc will output `urlunparse(components, *, keep_empty=['not specified'])`. Is it fine, or you need more descriptive name?

2025-11-19 18:10 UTC, merwok commented on Doc/library/urllib.parse.rst
> +.. function:: urlparse(urlstring, scheme=None, allow_fragments=True, *, missing_as_none=False)
I think that name should really be `missing_as_empty_string` at least (we can’t say just “empty”), meaning _missing parts returned as empty strings_.

What about `use_none=False` which is short and doesn’t try to be self-explanatory, so people need to read the docs?

2026-01-06 16:40 UTC, merwok commented on Doc/library/urllib.parse.rst
> +   By default, *keep_empty* is true if *parts* is the result of the
I think gps is requesting the signature in this doc file to be more explicit, not pydoc output.

2026-01-06 16:41 UTC, merwok commented on Lib/urllib/parse.py
> +    '_SplitResultBase', 'scheme netloc path query fragment')):
Avoid visually aligning lines that are not part of the same logical block:
```suggestion
        '_SplitResultBase', 'scheme netloc path query fragment')):
```

2026-01-06 16:41 UTC, merwok commented on Lib/urllib/parse.py
> +    '_ParseResultBase', 'scheme netloc path params query fragment')):
```suggestion
        '_ParseResultBase', 'scheme netloc path params query fragment')):
```

2026-01-06 16:42 UTC, merwok commented on Lib/urllib/parse.py
> +        return urlunsplit(self)
```
geturl = urlunsplit
```

?

2026-01-06 16:56 UTC, serhiy-storchaka commented on Doc/library/urllib.parse.rst
> +   By default, *keep_empty* is true if *parts* is the result of the
I changed also the signature in this doc file. See above. It no longer contains `keep_empty=False`.

2026-01-06 16:56 UTC, serhiy-storchaka commented on Lib/urllib/parse.py
> +        return urlunsplit(self)
`urlunsplit()` has the `keep_empty` parameter, `geturl()` does not.

This code was not changed.

2026-01-21 01:34 UTC, orsenthil commented on Lib/urllib/parse.py
> +                 for x in args)
```suggestion
    return tuple(x.decode(encoding, errors) if x else ('' if x is not None else x)
                 for x in args)
```

2026-01-21 01:38 UTC, orsenthil commented
Hello @serhiy-storchaka ,

This PR looks good to me. This is an important change to the behavior of the urlparse, and improves the behavior with less ambiguity, and I believe should be helpful to users.

Regarding your design question

> Add a (hidden) boolean attribute to instances of SplitResult (and of other 5 classes).


The above option looks better to me - like, how the current PR does.


Are you waiting for anything else for merging this PR? I am approving this so that this can be merged.

2026-01-21 01:38 UTC, orsenthil approved these changes
LGTM.

I made an optional code suggestion for improving readability.

2026-01-21 07:32 UTC, serhiy-storchaka commented on Lib/urllib/parse.py
> +                 for x in args)
I understand your confusion, but chained ternary operator is idiomatic code in C and Python and does not need parentheses (unlike to PHP).

Maybe splitting it on several line will help readability?

2026-01-21 18:54 UTC, orsenthil commented on Lib/urllib/parse.py
> +                 for x in args)
That's fine. I suggested it merely for better readability. Keeping it same is fine! Once I parsed it in my mind properly, I read it again totally fine.

2026-01-22 00:59 UTC, orsenthil commented
Looks like we maintain a patch for the iOS build which is failing to apply with this PR. 
```
  export PATH=/Users/runner/work/cpython/cpython/Apple/iOS/Resources/bin:/Users/runner/work/cpython/cpython/cross-build/arm64-apple-ios-simulator/prefix:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
  > make -j 3
  arm64-apple-ios-simulator-clang -c -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -mios-version-min=13.0   -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I../../Include/internal -I../../Include/internal/mimalloc -IObjects -IInclude -IPython -I. -I../../Include    -DPy_BUILD_CORE -o Programs/python.o ../../Programs/python.c
  arm64-apple-ios-simulator-clang -c -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -mios-version-min=13.0   -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I../../Include/internal -I../../Include/internal/mimalloc -IObjects -IInclude -IPython -I. -I../../Include    -DPy_BUILD_CORE -o Parser/token.o ../../Parser/token.c
  1 out of 1 hunks failed while patching 'Lib/test/test_urlparse.py'
```

2026-01-22 01:50 UTC, orsenthil commented
This file https://github.com/python/cpython/blob/main/Mac/Resources/app-store-compliance.patch (a meta-patch) needs to be updated for the new behavior (returning None instead of '') for it apply cleanly.

2026-01-22 04:55 UTC, orsenthil commented
This file https://github.com/python/cpython/blob/main/Mac/Resources/app-store-compliance.patch should be updated with this content.

```suggestion
diff --git a/Mac/Resources/app-store-compliance.patch b/Mac/Resources/app-store-compliance.patch
index f4b7decc01c..e5d1e7da866 100644
--- a/Mac/Resources/app-store-compliance.patch
+++ b/Mac/Resources/app-store-compliance.patch
@@ -1,21 +1,21 @@
 diff --git a/Lib/test/test_urlparse.py b/Lib/test/test_urlparse.py
-index d6c83a75c1c..19ed4e01091 100644
+index 49a292df934..e1669a0c9b2 100644
 --- a/Lib/test/test_urlparse.py
 +++ b/Lib/test/test_urlparse.py
-@@ -237,11 +237,6 @@ def test_roundtrips(self):
-               '','',''),
+@@ -282,11 +282,6 @@ def test_qs(self, orig, expect):
+               None,None,None),
               ('git+ssh', 'git@github.com','/user/project.git',
-               '', '')),
+               None, None)),
 -            ('itms-services://?action=download-manifest&url=https://example.com/app',
--             ('itms-services', '', '', '',
--              'action=download-manifest&url=https://example.com/app', ''),
+-             ('itms-services', '', '', None,
+-              'action=download-manifest&url=https://example.com/app', None),
 -             ('itms-services', '', '',
--              'action=download-manifest&url=https://example.com/app', '')),
+-              'action=download-manifest&url=https://example.com/app', None)),
              ('+scheme:path/to/file',
-              ('', '', '+scheme:path/to/file', '', '', ''),
-              ('', '', '+scheme:path/to/file', '', '')),
+              (None, None, '+scheme:path/to/file', None, None, None),
+              (None, None, '+scheme:path/to/file', None, None)),
 diff --git a/Lib/urllib/parse.py b/Lib/urllib/parse.py
-index 8f724f907d4..148caf742c9 100644
+index e917f8b61bb..8575172573f 100644
 --- a/Lib/urllib/parse.py
 +++ b/Lib/urllib/parse.py
 @@ -59,7 +59,7 @@
 ```
 
 And patch application is successful.
 
 ```
$patch -p1 < Mac/Resources/app-store-compliance.patch
patching file 'Lib/test/test_urlparse.py'
patching file 'Lib/urllib/parse.py'
```

And 
```
 ./python.exe Lib/test/test_urlparse.py -v
```

was successful with this change.

2026-01-22 11:09 UTC, serhiy-storchaka commented
Thank you @orsenthil. I was confused by this failure. The original issue is interesting: #120522.

2026-01-22 12:29 UTC, merged