bpo-36292:  Properly decref operands on failed bitwise operations
python/cpython pull request #12333
Opened 2019-03-14 15:48 UTC by stratakis

2019-03-14 16:00 UTC, vstinner requested changes
You are modiying deadcode, it doesn't deserve a NEWS entry :-)

2019-03-14 16:00 UTC, vstinner commented on Objects/longobject.c
>          PyErr_BadArgument();
This is deadcode: long_bitwise() is a private function only called with '&', '^' or '|'. So I would prefer to use "Py_UNREACHABLE();" here.

2019-03-14 16:00 UTC, vstinner commented on Objects/longobject.c
>          PyErr_BadArgument();
Ditto: use "Py_UNREACHABLE();" instead. No need to both with references. It's deadcode.

2019-03-15 18:56 UTC, terryjreedy commented
The news entry was deleted and `Py_UNREACHABLE()` used instead.  I don't know if our convention is to add the somewhat redundant `/* Unreachable code */`.  Either way, this seems ready to merge.

2019-03-18 13:31 UTC, vstinner requested changes

2019-03-18 13:31 UTC, vstinner commented on Objects/longobject.c
> +        /* Unreachable code */
I concur with @terryjreedy: the comment (here and above) is redudant, please remove it.

2019-03-18 16:41 UTC, vstinner approved these changes

2019-03-18 16:47 UTC, serhiy-storchaka approved these changes

2019-03-18 17:59 UTC, merged