Document that logging registers shutdown as an exit handler
python/cpython pull request #12378
Opened 2019-03-17 15:33 UTC by andresdelfino

Before reading the code from the module I had added the atexit.register(logging.shutdown) line to my own code, unnecessarily. I think it could be documented.

2019-03-17 18:07 UTC, tirkarthi commented
cc: @vsajip

2019-03-17 19:00 UTC, vsajip requested changes

2019-03-17 19:00 UTC, vsajip commented on Doc/library/logging.rst
> +   When then logging module is imported, it registers this function as an exit
"When then" should be "when the"

2019-03-17 21:47 UTC, andresdelfino commented on Doc/library/logging.rst
> +   When then logging module is imported, it registers this function as an exit
Sorry :sweat_smile: Done!

2019-03-17 21:47 UTC, andresdelfino commented
I have made the requested changes; please review again

2019-03-26 00:20 UTC, andresdelfino commented
Hi, @vsajip could you review the changes made? :)

2019-03-26 05:42 UTC, merged