[3.13] gh-121039: add Floats/ComplexesAreIdenticalMixin to test.support.testcase (GH-121071)
python/cpython pull request #123840
Opened 2024-09-08 15:08 UTC by skirpichev

(cherry picked from commit 8ef8354ef15e00d484ac2ded9442b789c24b11e0)

2024-09-08 16:29 UTC, serhiy-storchaka approved these changes

2024-09-08 16:35 UTC, serhiy-storchaka requested changes

2024-09-08 16:35 UTC, serhiy-storchaka commented on Lib/test/test_ctypes/test_numbers.py
> +class NumberTestCase(unittest.TestCase, ComplexesAreIdenticalMixin):
Wait, is it used?

2024-09-08 17:19 UTC, skirpichev commented
I have made the requested changes; please review again.

2024-09-08 17:25 UTC, serhiy-storchaka approved these changes

2024-09-11 12:07 UTC, vstinner approved these changes
LGTM. It can wait for 3.13.1.

2024-09-11 12:49 UTC, skirpichev commented
Depend on https://github.com/python/cpython/pull/123938

2024-09-30 01:27 UTC, merged