gh-123843: Remove broken links to the Zope DateTimeWiki
python/cpython pull request #123846
Opened 2024-09-08 19:03 UTC by AA-Turner

As an alternative to #123844.

cc: @otkd @Eclips4 

A

2024-09-08 19:40 UTC, Eclips4 commented
If we're talking about "Are these links really useful anymore?" I would say "No, let's remove them".

So I'm in favor of removing them.

2024-09-08 19:45 UTC, otkd requested changes
Minor change for clarity and resolved link

2024-09-08 19:45 UTC, otkd commented on Lib/datetime.py
> +"""Concrete date/time and related types.
```suggestion
"""Specific date/time and related types.
```

2024-09-08 19:45 UTC, otkd commented on Lib/datetime.py
> +See http://www.iana.org/time-zones/repository/tz-link.html for
```suggestion
See https://data.iana.org/time-zones/tz-link.html for
```
Replaced with resolved link

2024-09-08 20:20 UTC, otkd approved these changes
Thanks!

2024-09-09 02:28 UTC, terryjreedy commented
Looks good; nothing to add.

2024-09-09 02:39 UTC, merged