bpo-36345: Deprecate Tools/scripts/serve.py in favour of the HTTP server
python/cpython pull request #12408
Opened 2019-03-18 14:14 UTC by matrixise

2019-03-18 14:16 UTC, matrixise commented
@JulienPalard here is the PR

2019-03-18 15:47 UTC, vstinner requested changes
https://bugs.python.org/issue36345#msg338247

2019-03-23 00:50 UTC, matrixise commented
I have made the requested changes; please review again

2019-03-23 02:04 UTC, vstinner commented
https://bugs.python.org/issue36345#msg338637

2019-03-23 11:35 UTC, matrixise commented
I have made the requested changes; please review again

2019-03-23 11:36 UTC, matrixise commented
I added this PR https://github.com/python/cpython/pull/12511

2019-03-24 12:24 UTC, matrixise commented
@vstinner I have updated this PR with your remark (modify the makefile first). this is the part-0 for this issue.

The part-2 is #12511 (sorry, I don't rename the branch)
The part-1 will arrive after you have approved the part-0.

I have made the requested changes; please review again

Thank you

2019-03-24 22:13 UTC, vstinner commented on Misc/NEWS.d/next/Documentation/2019-03-18-15-11-24.bpo-36345.aRmIHE.rst
> +Use :mod:`http.server` with ``-d`` parameter instead of
What does "use http.server"? You should mention "make server" somewhere.

2019-03-25 19:55 UTC, matrixise commented
Hi @vstinner thank you for your review

I have made the requested changes; please review again

2019-03-26 12:25 UTC, vstinner commented
Please squash your commits into a single commit and update the PR title and description. It became very unclear what is the purpose of this change, because of its long history.

2024-11-18 14:58 UTC, hugovk commented
`make serve` has since been replaced with `make htmllive`, which uses https://github.com/sphinx-doc/sphinx-autobuild:

* `make serve` was removed in https://github.com/python/cpython/issues/80510.
* `make htmllive` was added in https://github.com/python/cpython/pull/111900.

2024-11-18 14:58 UTC, closed without merging