gh-90996: Fixed the issue that the xmlrpc module throws a ProtocolError which may leak the password
python/cpython pull request #124051
Opened 2024-09-13 13:00 UTC by rruuaanng

…ay cause password leakage

Fixed the security issue mentioned in https://github.com/python/cpython/issues/90996, could be leaked password due to a `ProtocolError` thrown

2024-09-13 13:40 UTC, Wulian233 reviewed
Thanks your PR, but there has two FAILURES:

Docs

Error: new NEWS nits:

/home/runner/work/cpython/cpython/build/NEWS:129: WARNING: py:meth reference target not found: xmlrpc.client.Transport.single_request [ref.meth]
Process completed with exit code 255.

Tests:
test_fail_no_info (test.test_xmlrpc.FailingServerTestCase.test_fail_no_info) ... ERROR
test_fail_with_info (test.test_xmlrpc.FailingServerTestCase.test_fail_with_info) ... ERROR

1 test failed again:
    test_xmlrpc

== Tests result: FAILURE then FAILURE ==

2024-09-13 13:40 UTC, Wulian233 commented on Misc/NEWS.d/next/Library/2024-09-13-20-48-05.gh-issue-90996.MPGcGC.rst
> +in the :mod:`xmlrpc.client`
```suggestion
Fixed a potential password leak in the :meth:`Transport.single_request`
where passwords could be exposed in a ``ProtocolError`` exception, raised by
the :mod:`xmlrpc.client`.
```

2024-09-13 13:41 UTC, Wulian233 commented
Add security label?

2024-09-14 08:25 UTC, Wulian233 commented
After the change, the current document test still fails. Can you modify the test to match the newer code? Thanks

https://github.com/python/cpython/actions/runs/10859924577/job/30139890135

2024-09-14 11:02 UTC, rruuaanng commented
> After the change, the current document test still fails. Can you modify the test to match the newer code? Thanks
> 
> https://github.com/python/cpython/actions/runs/10859924577/job/30139890135

Okay， I'm ready change

2024-09-15 20:30 UTC, Eclips4 reviewed
Please add a test case for this.

2024-09-16 00:59 UTC, rruuaanng commented
> Please add a test case for this.

I'm working on it, but it's really hard to find.

2024-09-16 01:52 UTC, rruuaanng commented
I'm helpless. I don't know much about unittest and I don't know where to modify it.

2024-09-16 02:36 UTC, rruuaanng commented
> Please add a test case for this.

Oh, `test_fail_no_info` of `test_xmlrpc.py` confuses me.

2024-09-16 04:16 UTC, rruuaanng commented
I wrote a simple test, but it fails.
```
    def test_throw_protocol(self):
        try:
            raise xmlrpclib.ProtocolError('hello')
        except (xmlrpclib.ProtocolError) as e:
            print(e)
            self.assertTrue(True)
```

2024-09-16 07:11 UTC, Wulian233 requested changes
Lint

2024-09-16 07:11 UTC, Wulian233 commented on Misc/NEWS.d/next/Library/2024-09-13-20-48-05.gh-issue-90996.MPGcGC.rst
> +could lead to password leaks.
```suggestion
Fixed a security issue where a ``ProtocolError`` raised by
:meth:`Transport.send_request`` in the :mod:`xmlrpc.client` could lead
to password leaks.
```

2024-09-16 08:58 UTC, rruuaanng commented
> Lint

I need to modify test_fail_on_info, but I don't know where to start.

2024-09-16 10:37 UTC, closed without merging