bpo-31199: configure fails if libasan is not installed when --with-address-sanitizer is enabled
python/cpython pull request #12433
Opened 2019-03-19 11:19 UTC by matrixise

2019-03-19 11:20 UTC, matrixise commented
Just to be sure, I have modified the `configure.ac` file but I don't know if I need to run `autoconf` or `autoreconf` for the update of `configure`

2019-03-19 12:35 UTC, pmatos commented
@matrixise thanks for the pr. I am the bug reporter. Will give this a try.

2019-03-19 12:43 UTC, pmatos commented
OK - LGTM

2019-03-19 14:23 UTC, matrixise commented
@Yhg1s In the devguide, I saw you are the expert for the `configure.ac` file, please when you have time, could you check this PR? Thank you.

2019-03-23 00:14 UTC, matrixise commented
@vstinner or @ned-deily what do you think about this PR?

2019-03-25 01:39 UTC, ned-deily requested changes
The test is too platform-specific.  For one, it fails on current macOS systems with the default `clang` even though the address sanitizer is available.  (Apple no long ships any `gcc` as part of their developer tools.) Relevant output from `config.log`:
```

configure:10043: checking for --with-address-sanitizer
configure:10049: result: yes
configure:10065: checking for malloc in -lasan
configure:10090: clang -o conftest   -fsanitize=address  conftest.c -lasan  -ldl  >&5
conftest.c:102:6: warning: incompatible redeclaration of library function 'malloc' [-Wincompatible-library-redeclaration]
char malloc ();
     ^
conftest.c:102:6: note: 'malloc' is a builtin with type 'void *(unsigned long)'
1 warning generated.
ld: library not found for -lasan
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:10090: $? = 1

```

If a test is really needed here, perhaps a better approach would be to try to compile, link, and run a skeletal program using `AC_RUN_IFELSE`.  There are examples of its use elsewhere in `configure.ac`.

2019-03-25 20:04 UTC, matrixise commented
@ned-deily thank you, I will check on my MBP and I will come back with a feedback in maximum 3 days.

2019-05-31 11:30 UTC, csabella commented
@matrixise, friendly reminder of your last comment.  🙂

2020-05-23 16:53 UTC, csabella commented
@matrixise ping

2026-05-05 17:30 UTC, StanFromIreland commented
Closing as stale, the requested changes have not been applied in seven years.

2026-05-05 17:30 UTC, closed without merging