bpo-36309: Raise a PendingDeprecationWarning when calling tempfile.mktemp()
python/cpython pull request #12437
Opened 2019-03-19 13:43 UTC by matrixise

2019-03-19 14:51 UTC, pablogsal requested changes
The CI is failing because `multiprocessing.connection` is still using `mktemp`. Did we already settle on how we want to handle this? I don't see anything on the issue

2019-03-19 15:22 UTC, matrixise commented
@pablogsal this is a WIP PR for the issue and the discussion on python-dev@python.org

2019-03-19 15:29 UTC, pablogsal commented
Ok, I will mark it as "DO-NOT-MERGE" for now, then.

2019-03-24 05:57 UTC, matrixise commented
I close this PR, waiting for the decision of the thread on Python-dev https://mail.python.org/pipermail/python-dev/2019-March/156721.html

2019-03-24 05:57 UTC, closed without merging