gh-120144: Make it possible to use `sys.monitoring` for bdb and make it default for pdb
python/cpython pull request #124533
Opened 2024-09-25 18:43 UTC by gaogaotiantian

This is the most conservative attempt ever to utilize `sys.monitoring` in `bdb` and `pdb`.

Highlights:

* **Full backward compatibility** - no changes to `test_pdb` and `test_bdb` at all with the new backend
* `bdb` will still default to `sys.settrace`, which keeps all the old behavior. Users can opt-in to the new `sys.monitoring` backend, and the interface is still the same, even for `trace_dispatch` (that's how `test_bdb` passes).
* New additional and optional interfaces in `bdb` where user can disable certain events to improve the peformance.
* `pdb` uses the `monitoring` backend and no noticable difference I can observe at this point.

Solution:

Basically, I mimiced the behavior of `sys.settrace` with `sys.monitoring` to keep the old behavior as much as possible. But I had the chance to use the new API of `sys.monitoring` to disable certain events.

Performance:

It's not as impressive as the original proposal, but for the following code:

```python
import time
def f(x):
    # Set breakpoint here
    x *= 2
    return x + 1

def test():
    start_time = time.time()
    for i in range(1000):
        for j in range(1000):
            j + i
    cost = time.time() - start_time
    print(cost)
    f(0)

test()
```

On my laptop, without debugger, it takes 0.025s. With the new pdb attached (`b f` then `c`), it takes 0.036s (40% overhead), and with Python 3.12 pdb, it takes 1.04s(4100%+ overhead). The performance improvement is significant to say at least.

And this is simply with the line event disabling, there is a lot of potential to disable events like `PY_START` when we know it's not needed (for recursive calls). We can make the debugger **much much faster**.

And as you can tell from the diff, the actual changes to `pdb` is minimal - just change `sys.settrace(tracefunc)` to `self.start_trace(tracefunc)` and `sys.settrace(None)` to `self.stop_trace()`. That's what the debugger developers need to do to onboard.

If we want to make even more conservative, we can use `settrace` as default backend for `pdb.Pdb` which devs might inherit from and keep all the old behavior. And instantiate our own `pdb.Pdb` on inline breakpoints or cli with the new backend.

2024-09-25 18:45 UTC, gaogaotiantian commented
And of course we need documentation updates, I will do it later when the feature is accepted and the interface is decided.

2024-09-28 06:22 UTC, terryjreedy commented
Its after midnight so will test much later today.  If all ok using default, will patch IDLE to pass 'monitoring'.

2024-09-29 06:53 UTC, terryjreedy commented
Ran fine with default.  Not fine with `backend='monitoring'`.
Usually, when I start debugger, stack should one line with `bdb.run()`.  Running a file should top line under that.  I think showing bdb.run is an error, but this is what to compare to.  With monitoring, there is initially nothing in stack window.  Running a file results in 17 lines from threading, idlelib, and bdb.  I have to hit 'go' to get to bdb.run + first line.  After that, over and step seem to work, but 'go' freezes debugger.

2024-09-29 21:10 UTC, gaogaotiantian commented
Right - the most important thing is `IDLE` can simply keep working as it is, but it's also a very important example to test the new mechanism.

I think at least part of the issue is multi-threading. For `sys.settrace`, it only sets trace on current thread, but `sys.monitoring` sets events on all threads. That should answer some of the questions. I can patch this PR for thread check and maybe you can take a look after the fix.

2024-10-16 23:30 UTC, gaogaotiantian commented
Hi @terryjreedy , I "fixed" the multi-threading issue. Well by "fixed" I meant making it the same behavior as before. Let me know if you have some time to test it out :)

2024-10-17 00:01 UTC, gaogaotiantian commented
With `clear_tool_id`, I can easily change the events line `LINE` to local, and that gives me the full speed! The code example runs with basically 0 overhead now.

2025-01-17 12:24 UTC, pyscripter commented
> It's not as impressive as the original proposal, but for the following code:
> 
> ```python
> import time
> def f(x):
>     # Set breakpoint here
>     x *= 2
>     return x + 1
> 
> def test():
>     start_time = time.time()
>     for i in range(1000):
>         for j in range(1000):
>             j + i
>     cost = time.time() - start_time
>     print(cost)
>     f(0)
> 
> test()
> ```
> 
> On my laptop, without debugger, it takes 0.025s. With the new pdb attached (`b f` then `c`), it takes **the same amount of time**, and with Python 3.12 pdb, it takes 1.04s(4100%+ overhead). The performance improvement is significant to say at least.

The improvement you see here is entirely due to the changes in break_anywhere(self, frame): introduced in python 3.14.  If you try with the released alpha versions of 3.14 you get similar results to yours.

I have tried you new bdb code in different cases and, unfortunately, I did not see any improvements.  Quite the opposite!

2025-01-17 15:32 UTC, gaogaotiantian commented
> The improvement you see here is entirely due to the changes in break_anywhere(self, frame): introduced in python 3.14.

#124553 was merged after this PR so that's not possible (I did it btw).

But yes, for this specific case, the changes to `break_anywhere` will give the same result, and that's good.

What case did you try for this implementation? Like I mentioned, this is not the perfect solution, the major problem is solves is when a line event is triggered multiple times. So, for the same code, if you put a breakpoint at `print(cost)`, it should show the similar diff, and `break_anywhere` change won't affect it.

When you say `quite the opposite`, do you mean it's actually significant slower than the original solution? Do you have any examples?

2025-01-17 16:41 UTC, pyscripter commented
> So, for the same code, if you put a breakpoint at `print(cost)`, it should show the similar diff, and `break_anywhere` change won't affect it.

Yes it does!  Massive improvement in this case!

> the major problem is solves is when a line event is triggered multiple times

Could you please elaborate on how this is achieved?

> When you say `quite the opposite`, do you mean it's actually significant slower than the original solution? Do you have any examples?

One script I saw degradation of performance was the following:

```python
import threading
from timeit import timeit

class A(object):
    def __init__(self):
        self.value = 1

class B(A):
    @staticmethod
    def create_property(name):
        return property(
            lambda self: getattr(self.srg, name),
            lambda self, v: setattr(self.srg, name, v),
        )
    value = create_property.__func__("value")

    def __init__(self):
        self.srg = __import__("threading").local()
        self.value = 2
        super().__init__()

b1 = B()
b2 = B()

print(timeit("b1.value = 4; c = b1.value", number=100000, globals=globals()))
print(timeit("b1.v = 4; c = b1.v", number=100000, globals=globals()))
```

With a breakpoint in the last line, the monitoring-based Bdb takes 4 times as much time to reach it.

But let me add some more details about how I am testing.  I am using a Bdb-based debugger in [PyScripter](https://github.com/pyscripter/pyscripter), which is adapted for multi-treaded debugging.   I am not using your modified bdb.py directly. Instead I created a subclass of Bdb integrating your code (see fastbdb.zip).   Since, I wanted to back port your code to python 12 and 13, I replaced clear_tool_id with a custom function.  Finally, since I am using the code for multi-threaded debugging, I have removed the changes in 99ea70c2189201b6a49dc8f9673032f062c9272b.
[fastbdb.zip](https://github.com/user-attachments/files/18457347/fastbdb.zip)

2025-01-17 17:00 UTC, gaogaotiantian commented
Okay that's a completely different story. Unfortunately this is the CPython PR so I can't fully solve issues for your debugger, but I have some potential theories.

`sys.monitoring`, unlike `sys.settrace`, will be triggered on all threads. If you mentioned multi-thread, that could be the problem. Are you using 4 threads when you say it's 4x slower?

`clear_tool_id` is also critical in this case, because local events will not be disabled automatically when you free the tool id. I don't know if your implementation of that is correct.

So, if you can reproduce the performance issue on pdb from this branch, I can investigate more into it. If you are experiencing issues on a debugger that's based on a customized version of this bdb, I'm afriad you are on your own because it's highly possible that the issue is caused by your customization (otherwise you should be able to repro it with pure pdb).

2025-01-17 17:11 UTC, pyscripter commented
I am testing on python 3.14 and I am using the following clear_tool_id

```python
        def clear_tool_id(tool_id):
            import sys
            if sys.version_info >= (3,14):
                sys.monitoring.clear_tool_id(tool_id)
            else:
                for event in sys.monitoring.events.__dict__.values():
                    if isinstance(event, int) and event:  # Ensure it's an event constant
                        sys.monitoring.register_callback(tool_id, event, None)
```
So, no difference here.

> `sys.monitoring`, unlike `sys.settrace`, will be triggered on all threads. If you mentioned multi-thread, that could be the problem. Are you using 4 threads when you say it's 4x slower?

No.   There is just one thread and it works exactly like your code.  PyScripter allows  you to debug multi-threaded python code, but for single-threaded scripts it works exactly like Bdb. 

And I am not asking you to solve my problems.  I reported one script where monitoring degrades debugging performance. Why don't you try it on your side?

2025-01-17 17:43 UTC, gaogaotiantian commented
```
gaogaotiantian@DESKTOP-I8L3RCK:~/programs/mycpython$ ./python -m pdb example.py 
> /home/gaogaotiantian/programs/mycpython/example.py(1)<module>()
-> from timeit import timeit
(Pdb) b 26
Breakpoint 1 at /home/gaogaotiantian/programs/mycpython/example.py:26
(Pdb) c
0.6028096990003178
0.0015645000003132736
> /home/gaogaotiantian/programs/mycpython/example.py(26)<module>()
-> pass
(Pdb) 
gaogaotiantian@DESKTOP-I8L3RCK:~/programs/mycpython$ ./python -m pdb example.py 
> /home/gaogaotiantian/programs/mycpython/example.py(1)<module>()
-> from timeit import timeit
(Pdb) b 26
Breakpoint 1 at /home/gaogaotiantian/programs/mycpython/example.py:26
(Pdb) c
0.4884036080002261
0.004922300000544055
> /home/gaogaotiantian/programs/mycpython/example.py(26)<module>()
-> pass
```

Former is monitoring and latter is settrace. Let me know if you have different results. Again, not results from pyscripter, please only send results of pdb monitoring vs pdb settrace. (And you can use the latest PR which merged in the 3.14 changes).

2025-01-17 18:40 UTC, pyscripter commented
Using the attached script  I get

```
using settrace
time1=  0.318285699991975
+++ <test> 26 <module> : print("time2= ", timeit("b1.v = 4; c = b1.v", number=100000, globals=globals()))
time2=  0.003290199994808063

using monitoring
time1=  0.3893818999931682
+++ <test> 26 <module> : print("time2= ", timeit("b1.v = 4; c = b1.v", number=100000, globals=globals()))
time2=  0.0014353000151459128
```
So monitoring is about 25% slower in this example.   Consistent with your results.

[testfastdbd.zip](https://github.com/user-attachments/files/18458518/testfastdbd.zip)

2025-01-17 19:18 UTC, gaogaotiantian commented
Yes, the callback is actually slower because we have checks. However, `pdb` could support multi thread in the future which will turn this into a positive.

Performance of a debugger is important, but 25% overhead is not unacceptable (it's a debugger, so overhead is expected). It's about a tradeoff between how much we gain on more common cases vs how much we lose on others.

Eliminating repeating line events is a big gain and we can polish the performance in the future. I think we can actually get much better with the ability to disable events. This is just a start.

2025-01-17 19:21 UTC, pyscripter commented
Thanks! And by the way, I found why I got the large performance hit in my earlier tests.  It looks good.

2025-01-18 14:36 UTC, pyscripter commented
@gaogaotiantian  I would like to mention that using bdb for multi-threaded debugging, even as it stands today is quite straightforward.  What it takes is:
- store fields like botframe, retrunframe, stopframe etc. in thread local storage
- patch threading.Thread to enable tracing and send notifications on thread start and stop
I am doing this in PyScripter.

2025-01-18 16:02 UTC, gaogaotiantian commented
Well it's definitely out of the scope of this PR, but from a debugger's view, there are a lot of things to consider, more than "how to trigger a callback on an arbitrary thread". For example, will other threads be halted while a thread is being debugged? If so, how? Otherwise, what if they are printing stuff? How to switch between threads? I believe some of the issues were discussed in an issue specifically for the matter. I do think there are solutions, but I don't think it'll be trivial. For now that's an item on todo list :)

2025-01-18 16:13 UTC, pyscripter commented
> Well it's definitely out of the scope of this PR

Of course

I was talking about Bdb.   All Bdb is doing is allowing descendent classes to call user_line, user_call etc.  The multi-threaded bdb would just add one more say user_thread to notify about thread start and finish. How these are implemented it depends on the debugger UI.

The difficult bit is to think through how for example Pdb would handle multiple threats.  In an IDE context it would work like Visual Studio works.   In PyScripter the debugger displays the running threads and their state and the user can step over any thread, examine the locals, issue commands in the context of the selected frame, resume any thread or all of them etc.

![image](https://github.com/user-attachments/assets/5bab41e9-bda7-4943-8115-93701d317ed7)

2025-01-18 17:03 UTC, pyscripter commented
By the way I am in awe by the [sys.monitoring.DISABLE](https://docs.python.org/3/library/sys.monitoring.html#sys.monitoring.DISABLE) magic.  which appears to work on a per line (code location basis).

Your little test:
```python
import time

def test():
    start_time = time.time()
    for i in range(1000):
        for j in range(1000):
            j + i
    cost = time.time() - start_time
    print("Elapsed time: ", cost)
    f(0)

def f(x):
    # Set breakpoint here
    x *= 2
    return x + 1

test()
```

results in just  a few calls to dispatch_line

```
using monitoring
dispatch_line:  2
dispatch_line:  4
dispatch_line:  13
dispatch_line:  18
+++ call test None
dispatch_line:  5
dispatch_line:  6
dispatch_line:  7
dispatch_line:  8
dispatch_line:  7
dispatch_line:  6
dispatch_line:  9
dispatch_line:  10
Elapsed time:  0.00011396408081054688
dispatch_line:  11
+++ <test> 11 test : f(0)
```

Fantastic!

2025-01-20 18:14 UTC, pyscripter commented
@gaogaotiantian Any chance of provide an option to enable the tracing of other threads?

2025-01-20 19:22 UTC, gaogaotiantian commented
Like I said, it's on the todo-list. For CPython, it's not simply implement it and go - we need to consider other potential impacts. We need to make sure all other stuff works well with the changes. If `bdb` supports multi-thread, it would be natural for `pdb` to support at least some features. It won't be a super quick patch.

Also this PR is not even approved at this point. We can discuss features based on this PR after it got merged.

2025-01-20 19:30 UTC, pyscripter commented
Maybe I did not make myself clear.  I did not ask for full mutli-threaded support in this PR.   Just an option like this::

```python
    def callback_wrapper(func):
        import functools

        @functools.wraps(func)
        def wrapper(self, *args):
            if self.single_thread and (self._tracing_thread != threading.current_thread()):
                return
            try:
```

2025-01-20 22:27 UTC, gaogaotiantian commented
Yes, I'm aware what you are asking for - that's not a trivial feature. It's a small change code wise, but it brings multi-thread support to bdb and that's a promise. For now, I'm only focused on how to merge this PR, with as less difference to the existing implementation as possible.

2025-01-29 15:37 UTC, pyscripter commented
I found a bug in the code.

If a breakpoint has a condition or ignore > 0 and bdb.effective returns (None, None) the code line is disabled and the breakpoint is not triggered when it should.

Example:
```python
def main():
    sum = 0
    for i in range(1000):
        sum = sum + i
    print(sum)

if __name__ == '__main__':
    main()
```
If you set a conditional breakpoint in line 4, with a condition "sum > 0" or "i==100", the breakpoint will never fire.  Same is you set the ignore property of the breakpoint to a value > 0.

2025-02-08 23:39 UTC, gaogaotiantian commented
You are right, this is a bug. Fixed with regression tests.

2025-02-18 17:04 UTC, markshannon requested changes
Looks good. I have a few questions and comments.

Treating `DEFAULT_BACKEND` as a class variable is a bit surprising, as `ALL_CAPS` are usually constants.
Maybe add a classmethod to `Pdb` for setting the default?

2025-02-18 17:04 UTC, markshannon commented on Lib/bdb.py
> +    def jump_callback(self, frame, code, inst_offset, dest_offset):
I'm surprised this is necessary.
What line events does the `line_callback` method miss?

2025-02-18 17:04 UTC, markshannon commented on Lib/bdb.py
> +        else:
Maybe raise an exception if `backend != "settrace"`?

2025-02-18 17:04 UTC, markshannon commented on Lib/bdb.py
> +        if self.backend == 'monitoring':
```suggestion
        if self.monitoring_tracer:
```
Avoids the magic strings constant

2025-02-18 17:04 UTC, markshannon commented on Lib/bdb.py
> +        if self.backend == 'monitoring':
Likewise

2025-02-18 17:04 UTC, markshannon commented on Lib/bdb.py
> +                if self.backend == 'monitoring':
```suggestion
                if self.monitoring_tracer:
```

2025-02-18 17:04 UTC, markshannon commented on Lib/pdb.py
> +                 nosigint=False, readrc=True, mode=None, backend=None):
~`backend=Pdb.DEFAULT_BACKEND` to avoid the need for the conditional expression on the next line.~

That wouldn't work because `DEFAULT_BACKEND` is not a constant.

2025-02-18 17:04 UTC, markshannon commented on Lib/test/test_pdb.py
> +def test_pdb_breakpoint_ignore_and_condition():
Is this test for a behavior change, or was it just untested before?

2025-02-18 17:26 UTC, gaogaotiantian commented on Lib/bdb.py
> +    def jump_callback(self, frame, code, inst_offset, dest_offset):
I don't know if it's necessary. I basically copied the logic from `sys.settrace()` and this is what it does. Deleting it does not affect the test, but the test suite of pdb is not the most thorough one. If we are confident, we can probably remove the one for `sys.settrace()` and here.

2025-02-18 17:27 UTC, gaogaotiantian commented on Lib/test/test_pdb.py
> +def test_pdb_breakpoint_ignore_and_condition():
This is untested and a regression from one initial implementation. I fixed the implementation and added an extra test for it.

2025-02-18 17:28 UTC, gaogaotiantian commented
I can change the `DEFAULT_BACKEND` thing. Do you think it should be a class-level variable or a module-level one like `multiprocessing`? For either one I can add utility functions for users to change it.

2025-02-19 09:31 UTC, markshannon commented on Lib/bdb.py
> +    def jump_callback(self, frame, code, inst_offset, dest_offset):
> the test suite of pdb is not the most thorough one.

The tests for `sys.monitoring` and `sys.settrace` are a lot more thorough. If line events were missing I think those would catch them. Also coverage.py relies on these events and it has lots of tests.
If there is some obscure case that isn't handled, we should be fixing that in `sys.monitoring` anyway, not here.

2025-02-19 09:34 UTC, markshannon commented
> I can change the `DEFAULT_BACKEND` thing. Do you think it should be a class-level variable or a module-level one like `multiprocessing`? For either one I can add utility functions for users to change it.

I think a module-level one. The interface to pdb is the module. The `Pdb` class is mostly for extensions.

2025-02-19 21:29 UTC, gaogaotiantian commented on Lib/bdb.py
> +    def jump_callback(self, frame, code, inst_offset, dest_offset):
`sys.settrace` uses `JUMP` event from `sys.monitoring` to trigger a `line` event - I simply copied the logic. If I remember correctly, this is for the line event in loops? The jump back of for loops does not trigger a line event for `sys.monitoring`, and we need to keep the backward compatibility for `sys.settrace` so we need to add in the `JUMP` event?

https://github.com/python/cpython/blob/73801864d866c76ae26a120b9db9de21b08f8b50/Python/legacy_tracing.c#L350-L352

2025-02-19 22:38 UTC, gaogaotiantian commented
I added the module level util for default backends. I also added the docs (with my best effort) and the whatsnew entry. This is a full package that needs review now :)

2025-02-21 17:06 UTC, markshannon commented on Lib/bdb.py
> +    def jump_callback(self, frame, code, inst_offset, dest_offset):
I remember now.

This is for backward jumps within the same line.
`sys.settrace` generates a "line" event for these, but `sys.monitoring` does not generate a `LINE` event, as there is no change in line.

2025-02-21 17:10 UTC, markshannon approved these changes
@terryjreedy are you OK with this being merged?

2025-02-27 17:17 UTC, gaogaotiantian commented
@terryjreedy friendly ping. Do you have other comments for this change? IDLE can use settrace version bdb now and we can work together to see if we can move it to monitoring in the future. We also have a few months before 3.14 release so time is on our side.

2025-03-06 21:17 UTC, pyscripter commented
I found another bug. Consider the following code:

```python
for i in range(10):
    j = i ** 2
    print(j)
```

- Start with a breakpoint in line 3.  
- When the breakpoint is hit, delete this breakpoint and add a breakpoint at line 2.  
- Continue execution.  The second breakpoint is not respected, and execution continues to the end.

2025-03-07 02:07 UTC, gaogaotiantian commented
Thanks for filing the bug. The events should be restarted after every user interaction. I forgot the one after `user_line`. Fixed and added a regression test.

2025-03-17 02:42 UTC, gaogaotiantian commented
As Terry is busy, I will merge this soon if no one objects. I don't expect this change to break anything (except for pdb maybe).

2025-03-17 08:12 UTC, terryjreedy commented
I ran IDLE debugger with updated main, a PR branch, and after adding `backend='monitoring' to the `super.__int__()` on line 34 of idlelib/debugger.py.  (IDLE debugger never calls sys.settrace.)  All seemed to run the same.  I saw none of the problems I reported in https://github.com/python/cpython/pull/124533#issuecomment-2381135288 last September.  So fine with me to merge.  When you do, I will make a PR with separate blurb to modify idlelib.debugger on main.  Can the backend be changed on the fly?

2025-03-17 22:33 UTC, gaogaotiantian commented
Thank you @terryjreedy for testing it out. I don't think you can change the backend while the debugging is working. It should be fine to change it before it starts tracing or after it's done. I'm glad the current version just works for IDLE - that's the original goal anyway.

2025-03-17 22:34 UTC, merged