Handle the case when sys.argv is not set
python/cpython pull request #12463
Opened 2019-03-20 08:43 UTC by uellue

I encountered a situation where `sys.argv` wasn't set when using Python as an embedded interpreter. The proposed update will avoid an AttributeError in that case. If `sys.argv` is set, it should not change behavior.

There's discussions related to correct behavior in this case: 
https://bugs.python.org/issue32573

Is this proposed update to spawn.py the correct fix, or should the embedded case be handled differently, somehow?

2019-03-20 08:43 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-05-13 15:34 UTC, vstinner requested changes
In Python 3.8, sys.argv always exist: https://bugs.python.org/issue32573#msg342342

2019-05-23 12:22 UTC, uellue commented
Would it make sense to include the workaround and/or setting `sys.argv` in Python 3.7, or will it only be updated in 3.8?

2019-05-24 16:25 UTC, vstinner commented
> Would it make sense to include the workaround and/or setting sys.argv in Python 3.7, or will it only be updated in 3.8?

I'm working on a whole PEP for Python 3.8: https://www.python.org/dev/peps/pep-0587/

For Python 3.7, I'm not sure that it's ok to change the behavior, but I just wrote: PR #13553.

2019-12-14 01:14 UTC, csabella commented
This was fixed as of 3.8 and [won't be backported to earlier releases](https://bugs.python.org/issue32573#msg344329).

2019-12-14 01:14 UTC, closed without merging