bpo36366: Return None on stopping unstarted patch object
python/cpython pull request #12472
Opened 2019-03-20 12:17 UTC by tirkarthi

Return None on stopping unstarted patch object instead of raising `RuntimeError` making `patch.stop` call idempotent.

2019-03-20 19:26 UTC, eamanu approved these changes

2019-03-27 19:09 UTC, brettcannon requested changes
Some minor naming and grammar stuff, otherwise LGTM!

2019-03-27 19:09 UTC, brettcannon commented on Lib/unittest/test/testmock/testpatch.py
> +        # bpo-36366: calling stop without start will return None
```suggestion
        # bpo-36366: calling stop without start will return None.
```

2019-03-27 19:09 UTC, brettcannon commented on Lib/unittest/test/testmock/testpatch.py
> +        # bpo-36366: calling stop on an already stopped patch will return None
```suggestion
        # bpo-36366: calling stop on an already stopped patch will return None.
```

2019-03-27 19:09 UTC, brettcannon commented on Lib/unittest/test/testmock/testpatch.py
> +    def test_stop_double_stop(self):
```suggestion
    def test_stop_idempotent(self):
```

2019-03-28 00:06 UTC, tirkarthi commented
Travis has some problems https://www.traviscistatus.com

2019-03-28 02:44 UTC, tirkarthi commented
I have made the requested changes; please review again.

2019-03-28 21:08 UTC, brettcannon approved these changes

2019-03-28 21:08 UTC, merged

2019-03-29 00:03 UTC, tirkarthi commented
Thanks Brett :)