bpo-36375: PEP 499 implementation: "python -m foo" binds the main module as both __main__ and foo in sys.modules
python/cpython pull request #12490
Opened 2019-03-22 02:27 UTC by cameron-simpson

This contains documentation updates, `runpy.py` implementation, two unit tests and a fix for `Lib/pdb.py` to accomodate new aliasing of `__main__ `as the module's canonical name.

A run of "make test" on my El Capitan Mac here now shows the following failures:

    test_c_locale_coercion test_smtpnet test_ssl test_urllib
    test_urllib2 test_urllib2net test_xmlrpc

Of these:

  test_c_locale_coercion appears to be due to differences between my OS release and presumably more modern Darwin releases: various "utf-8" vs "ascii" mismatches in the output.

  text_xmlrpc seems to run forever, here

  the other tests fail for network based reasons.

WRT to a run against the master branch, the failure set is the same.

I cannot reproduce the hashlib based failures seen by Travis on my earlier PR. It will be interesting to see what Travis says now.

2019-03-24 11:30 UTC, ncoghlan requested changes
Just adding a blocking review to ensure the PR isn't merged until after the PEP has been reviewed.

2019-03-24 11:37 UTC, ncoghlan commented on Lib/pdb.py
> +        __main__ = types.ModuleType(module_name, 'New __main__ module for pdb.')
This won't interact correctly with the interpreter's `-i` switch, as that always drops you into the *original* `__main__` namespace, even if it's been rebound in `sys.modules` by the application code.

2019-03-24 11:49 UTC, ncoghlan commented
@cameron-simpson This is looking pretty good, but there are still some backwards compatibility risks that we're going to have to investigate before the PEP can be approved.

I'm officially the design & implementation reviewer for this PEP now, so I added the two key questions/concerns that I'm currently aware of to a new section: https://github.com/python/peps/pull/946

2022-09-06 11:44 UTC, erlend-aasland commented
Closing this, as the linked issue has been closed.

2022-09-06 11:44 UTC, closed without merging