gh-125260: gzip: let compress mtime default to 0
python/cpython pull request #125261
Opened 2024-10-10 13:23 UTC by bmwiedemann

this follows GNU gzip, which defaults to
store 0 as mtime for compressing stdin, where no file mtime is involved

This makes gzip.compress(str) output deterministic by default and greatly helps reproducible builds.

2024-10-10 13:58 UTC, ZeroIntensity commented
This needs a NEWS entry, as this is a user-facing error. Also, could you add a test for this?

2024-10-10 14:08 UTC, AA-Turner requested changes

2024-10-10 14:08 UTC, AA-Turner commented on Doc/library/gzip.rst
> +      The *mtime* parameter now defaults to 0 for reproducible output
```suggestion
   .. versionchanged:: 3.14
      The *mtime* parameter now defaults to 0 for reproducible output.
```

2024-10-10 14:08 UTC, AA-Turner commented on Lib/gzip.py
>      """
Your fork is significantly out-of-date, this changed in 2021. Once you merge that in, the docstring should be updated.


![image](https://github.com/user-attachments/assets/fb97bf7b-6715-4c10-a7e8-81b19b5f6b9f)

2024-10-10 16:51 UTC, bmwiedemann commented
I have rebased it onto main now. I had probably based it off the old master branch.

I would appreciate some help with the NEWS and test. I only saw Misc/NEWS.d/3.13.0a1.rst but nothing for 3.14 yet.

2024-10-10 16:53 UTC, AA-Turner commented
You can use [blurb it](https://blurb-it.herokuapp.com/)

A

2024-10-10 16:56 UTC, AA-Turner commented
@ZeroIntensity I'm not sure about backport labels here as the function works as intended (so this is a feature) -- what was your rationale?

2024-10-10 17:18 UTC, ZeroIntensity commented
Hmm, is this a feature? The original issue was marked as a bug, so I thought it would be backportable.

2024-10-10 17:21 UTC, AA-Turner commented
It was opened with the bug template, hence the bug label, but it's a judgement call as to 'bug' or 'feature'. Personally I would be hesitant to backport, but others may have different opinions.

A

2024-10-10 17:22 UTC, ZeroIntensity commented
I think that's right, I'll update the labels. My bad!

2024-10-11 05:20 UTC, bmwiedemann commented
I have made the requested changes; please review again

2024-10-11 06:08 UTC, nineteendo commented on Lib/gzip.py
> +def compress(data, compresslevel=_COMPRESS_LEVEL_BEST, *, mtime=0):
```suggestion

def compress(data, compresslevel=_COMPRESS_LEVEL_BEST, *, mtime=0):
```

2024-10-11 11:10 UTC, ZeroIntensity approved these changes
LGTM

2024-10-11 14:17 UTC, mcepl approved these changes
Yes, that looks like a great idea!

2024-10-11 14:48 UTC, mcepl commented
> It was opened with the bug template, hence the bug label, but it's a judgement call as to 'bug' or 'feature'. Personally I would be hesitant to backport, but others may have different opinions.

Reason why Bernhard would like to consider it as a bug (and thus backport it) is that it breaks reproducible builds.

2024-10-11 14:58 UTC, nineteendo commented
As AA-Turner said, "the function works as intended (so this is a feature)" and thus not a bug. Only bugs can be backported.

2024-10-11 16:32 UTC, AA-Turner commented
@bmwiedemann please don't force-push, as it makes PRs harder to review. See [the devguide](https://devguide.python.org/getting-started/pull-request-lifecycle/#quick-guide) for similar guidance. We squash-merge all commits.

2024-10-11 16:42 UTC, AA-Turner reviewed
I've had to leave a couple of comments as diffs rather than suggestions due to limitations in the GH review interface -- sorry.

A

2024-10-11 16:42 UTC, AA-Turner commented on Lib/test/test_gzip.py
> +                    self.assertEqual(nocompress, nocompressnomtime)
It feels odd to have this test inside `test_compress_correct_level` rather than `test_compress_mtime`. Perhaps we could add a new `test_compress_mtime_default` that tests `mtime=0` and `mtime=None` (the latter case isn't currently tested, as far as I can see). 

`mtime=None` could test that `f.mtime` is e.g. `self.assertGreater(f.mtime, time.time()-1000)`

2024-10-11 16:42 UTC, AA-Turner commented on Lib/gzip.py
> +def compress(data, compresslevel=_COMPRESS_LEVEL_BEST, *, mtime=0):
Please change the docstring as follows:

```diff
-    mtime can be used to set the modification time. The modification time is
-    set to the current time by default.
+    mtime can be used to set the modification time.
+    The modification time is set to 0 by default, for reproducibility.

2024-10-11 16:42 UTC, AA-Turner commented on Doc/library/gzip.rst
>     Compress the *data*, returning a :class:`bytes` object containing
Please make the following change to the third line:
```diff
    Compress the *data*, returning a :class:`bytes` object containing
    the compressed data.  *compresslevel* and *mtime* have the same meaning as in
-   the :class:`GzipFile` constructor above.
+   the :class:`GzipFile` constructor above, 
+   but *mtime* defaults to 0 for reproducible output.
```

2024-10-11 16:42 UTC, AA-Turner commented on Doc/library/gzip.rst
> +      The *mtime* parameter now defaults to 0 for reproducible output.
```suggestion
   .. versionchanged:: 3.14
      The *mtime* parameter now defaults to 0 for reproducible output.
      For the previous behaviour of using the current time,
      pass ``None`` to *mtime*.
```

2024-10-11 17:57 UTC, bmwiedemann commented on Lib/test/test_gzip.py
> +                    self.assertEqual(nocompress, nocompressnomtime)
I made a somewhat cleaner version. Feel free to add on top of that.

2024-10-12 00:02 UTC, AA-Turner commented on Lib/test/test_gzip.py
> +        self.assertNotEqual(datac, datac3)
```suggestion
        datac3 = gzip.compress(data1, mtime=None)
        self.assertNotEqual(datac, datac3)
        with gzip.GzipFile(fileobj=io.BytesIO(datac3), mode="rb") as f:
        	f.read(1) # to set mtime attribute
            self.assertGreater(f.mtime, 1)  
```

2024-10-12 00:23 UTC, AA-Turner approved these changes
Thanks!

A

2024-10-12 00:23 UTC, AA-Turner commented on Misc/NEWS.d/next/Library/2024-10-11-04-04-38.gh-issue-125260.PeZ0Mb.rst
> +The :func:`gzip.compress` *mtime* parameter now defaults to 0 for reproducible output.
Add credits for yourself (feel free to remove me if you'd prefer, I only helped with tests/docs)
```suggestion
The :func:`gzip.compress` *mtime* parameter now defaults to 0 for reproducible output.
Patch by Bernhard M. Wiedemann and Adam Turner.
```

2024-10-12 17:18 UTC, merged

2024-10-12 17:19 UTC, AA-Turner commented
Thanks @bmwiedemann!

A