gh-125234: Integrated `NULL` check in `PyInitConfig_Free()`
python/cpython pull request #125266
Opened 2024-10-10 14:24 UTC by rruuaanng

```
PyInitConfig *config = NULL;
// some code
if (error_occurred) {
    goto Error;
}
config = PyInitConfig_Create();
if (config == NULL) {
    goto Error;
}
// some other code
if (error_occurred) {
    goto Error;
}
// more code
Error:
// release resources
PyInitConfig_Free(config);
// release resources

```

2024-10-10 18:02 UTC, ZeroIntensity approved these changes
LGTM

2024-10-10 18:04 UTC, ZeroIntensity commented
This implementation looks fine, but the point of the original issue was to simplify things. Should that be done with this PR as well?

2024-10-10 18:24 UTC, serhiy-storchaka reviewed
Since this is a public C API change, it should be documented. Add a `versionchanged` directive and the What's New entry.

I am going also to get an approve of the C API Workgroup.

2024-10-10 19:00 UTC, ZeroIntensity commented
This is already in "What's New" under PEP 741, I think.

2024-10-10 19:03 UTC, serhiy-storchaka commented
Ah, it is new in 3.14. Then nothing of this is needed.

2024-10-10 19:04 UTC, ZeroIntensity commented
Yeah. In fact, do we even need a NEWS entry for changes to unreleased features?

2024-10-10 19:05 UTC, serhiy-storchaka commented
A NEWS entry is not needed.

2024-10-10 23:57 UTC, rruuaanng commented
> A NEWS entry is not needed

Maybe I can remove it.

2024-10-11 08:02 UTC, kumaraditya303 approved these changes

2024-10-14 12:40 UTC, erlend-aasland requested changes
Please add a test, for example in the `testcapi` extension module.

2024-10-15 00:41 UTC, rruuaanng commented
It's exist in `_testembed.c`.
https://github.com/python/cpython/blob/8d42e2d915c3096e7eac1c649751d1da567bb7c3/Programs/_testembed.c#L1898

2024-10-15 01:01 UTC, ZeroIntensity commented
Yeah, but not with calling with `NULL`. Could you just add a `PyInitConfig_Free(NULL)` right next to it?

2024-10-15 01:06 UTC, rruuaanng commented
I have made change, Please reviewer.

2024-10-15 01:07 UTC, ZeroIntensity approved these changes
I wonder if GitHub will let me approve a second time.

2024-10-15 01:07 UTC, ZeroIntensity commented
Oh, it worked!

2024-10-15 01:08 UTC, rruuaanng commented
Maybe, I have made the corresponding changes (I hope).

2024-10-15 01:09 UTC, rruuaanng commented
Maybe we should remove `change requests`.

2024-10-15 01:11 UTC, ZeroIntensity commented
You didn't trigger the bot. I think saying `I didn't expect the Spanish Inquisition` should work too 😉

2024-10-15 01:16 UTC, rruuaanng commented
Oh, This is really interesting! Hope this works🙂

2024-10-15 01:24 UTC, ZeroIntensity commented
(You have to say it, the bot ignores comments from people other than the author.)

2024-10-15 01:26 UTC, rruuaanng commented
I didn't expect the Spanish Inquisition

2024-10-15 01:27 UTC, rruuaanng commented
OMG, It's success!!

2024-10-15 07:50 UTC, erlend-aasland commented
@rruuaanng: every time you make a comment on an issue or a PR, all subscribed parties receives a notification, or even an email. Please be respectful of others time and don't use GitHub as a forum. We have [Discourse](https://discuss.python.org) for that functionality.

2024-10-15 07:52 UTC, erlend-aasland commented on Python/initconfig.c
> +    /* PyInitConfig_Free(NULL) has no effect */
```suggestion
```

2024-10-15 07:58 UTC, erlend-aasland requested changes
Please also update the docs. Look to `PyMem_Free` and `PyMem_RawFree` for inspiration.

2024-10-15 09:20 UTC, erlend-aasland approved these changes

2024-10-15 09:21 UTC, merged

2024-10-15 10:52 UTC, ZeroIntensity commented
> every time you make a comment on an issue or a PR, all subscribed parties receives a notification, or even an email. Please be respectful of others time and don't use GitHub as a forum.

Yeah, I was a little guilty of this too in this case, sorry :(

In general, what's the procedure for walking someone through the PR process if they're having difficulties?

2024-10-15 11:22 UTC, erlend-aasland commented
> Yeah, I was a little guilty of this too in this case, sorry :(
> 
> In general, what's the procedure for walking someone through the PR process if they're having difficulties?

No worries, you're both fine. If I notice such a pattern on a PR, I explicitly make a remark and remind the participants of this effect. Using reactions, like thumbs-up, is often sufficient. Also, thinking twice about how often we demand the attention of others may be helpful.