bpo-18576: Add test.support.script_helper documentation
python/cpython pull request #1252
Opened 2017-04-22 06:18 UTC by lulouie

Based on `bobcatfist`'s patch, addressed on Martin request and some minor change.

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +   variables *env_vars*, asserting that run succeeds (return code is zero).
“asserting that _the_ run” reads smoother to me and would be consistent with __failure_ below

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +across various script exection or command line interface tests, such as creating
exection → execution

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +   stdout and stderr of the failed process.
The assertion failed, but saying the process failed is confusing. Maybe just drop _failed_. (Unless this last fragment refers to the tuple return value.) I would rewrite as something like

If the exit status is zero, the function raises an :exc:`` `AssertionError` ``, which includes the `*stdout*` and `*stderr*` from the interpreter. Otherwise, the function returns an (`*exit status*`, `*stdout*`, `*stderr*`) tuple.

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +   Runs a Python subprocess with the given arguments and returns the
Maybe change _Runs_ to _Spawns_ or _Starts_, to avoid implying it waits for the interpreter to exit.

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +.. function:: assert_python_failure(*args, **env_vars)
This parallels _assert_python_ok_. Maybe it would be easier to understand if they were documented together. E.g.

.. function:: assert_python_ok(*args, **env_vars)
> > assert_python_failure(*args, **env_args)
> 
> Runs the interpreter . . ., asserting that the run succeeds (exit status is zero) or fails (nonzero).

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +   Runs the given Popen process until completion and return stdout.
return → returns, to agree with _Runs_ (though I admit this error is just copied from the doc string)

Since this is decoupled from the implementation, it may be worth clarifying that this does not send a signal (_kill_ implies signalling to me), but that it does close the input pipe.

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +   directly as the name of created file with no extension.
of _the_ created file

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +   Would create an archive in the current directory called ``example.zip``
Lowercase _would_; it’s not the start of a sentence

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +   The *depth* argument controls how many deeply nested the package is.
. . . controls how deeply nested the package is.

or

. . . controls how many packages the submodule is nested inside.

2017-04-22 23:42 UTC, vadmium commented on Doc/library/test.rst
> +   suitable named compiled bytecode files rather than the original source
doubled _the_

Do you mean _suitably-named_?

2017-04-23 01:50 UTC, lulouie commented on Doc/library/test.rst
> +across various script exection or command line interface tests, such as creating
fixed

2017-04-23 01:50 UTC, lulouie commented on Doc/library/test.rst
> +   variables *env_vars*, asserting that run succeeds (return code is zero).
fixed

2017-04-23 01:50 UTC, lulouie commented on Doc/library/test.rst
> +.. function:: assert_python_failure(*args, **env_vars)
I merged these two, and the below paragraph, too.

2017-04-23 01:50 UTC, lulouie commented on Doc/library/test.rst
> +   Runs a Python subprocess with the given arguments and returns the
change to *Spawns*

2017-04-23 01:50 UTC, lulouie commented on Doc/library/test.rst
> +   Runs the given Popen process until completion and return stdout.
done.

2017-04-23 01:50 UTC, lulouie commented on Doc/library/test.rst
> +   Would create an archive in the current directory called ``example.zip``
fixed

2017-04-23 01:51 UTC, lulouie commented on Doc/library/test.rst
> +   The *depth* argument controls how many deeply nested the package is.
change to "controls how deeply nested the package is*

2017-04-23 01:51 UTC, lulouie commented on Doc/library/test.rst
> +   suitable named compiled bytecode files rather than the original source
fixed

2017-05-11 05:50 UTC, DimitrisJim requested changes

2017-05-11 05:50 UTC, DimitrisJim commented on Doc/library/test.rst
> +   stderr as a `_PythonRunResult`.
It returns a tuple containing the `_PythonRunResult` and the command executed (`cmd_line`).

2017-05-11 05:50 UTC, DimitrisJim commented on Doc/library/test.rst
> +   *stderr*) tuple.
these both return a `_PythonRunResult` namedtuple as obtained from `run_python_until_end`

2018-09-11 01:26 UTC, gpshead commented
Please sync the branch with the latest doc version in github and consider DimitrisJim's comments.

2018-11-04 10:28 UTC, matrixise commented
Hi @louisom 

Thank you for your contribution.

Since the commit 988fb28 some functions have been documented, I propose to you to update your code with the new documentation and submit it again.

Thank you.

2019-03-26 18:54 UTC, brettcannon commented
@louisom did you want to update this to resolve the merge conflict before I review it?

2019-09-09 16:26 UTC, JulienPalard commented
All those functions has now been documented. Thanks for the pull request in any cases!

2019-09-09 16:26 UTC, closed without merging