gh-85935: Excplicitly document the case nargs=0 in argparse
python/cpython pull request #125302
Opened 2024-10-11 07:44 UTC by serhiy-storchaka

2024-10-11 22:18 UTC, savannahostrowski requested changes
Two minor comments for conciseness, but otherwise, LGTM.

2024-10-11 22:18 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +Only actions that consume command-line arguments (such as ``'store'``,
```suggestion
Only actions that consume command-line arguments (e.g. as ``'store'``,
```

2024-10-11 22:18 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +Actions that do not consume command-line arguments (such as
```suggestion
Actions that do not consume command-line arguments (e.g.
```

2024-10-12 11:34 UTC, serhiy-storchaka commented on Doc/library/argparse.rst
> +Only actions that consume command-line arguments (such as ``'store'``,
I think "as" was redundant.
```suggestion
Only actions that consume command-line arguments (e.g. ``'store'``,
```

2024-10-12 11:53 UTC, merged