gh-109861: Fix a doctest in ``Lib/_pydecimal.py`` which was failing when running its doctests directly.
python/cpython pull request #125479
Opened 2024-10-14 19:28 UTC by mbyrnepr2

gh-109861: Fix a doctest in ``Lib/_pydecimal.py`` which was failing when run directly on the module via the command:
``./python.exe -m doctest Lib/_pydecimal.py``.

2024-10-15 01:22 UTC, skirpichev requested changes
I think we should stick with your solution for ``_pydecimal.py``.  It's more local.

2024-10-15 08:49 UTC, skirpichev approved these changes

2026-01-28 01:17 UTC, skirpichev commented
CC @picnixz

2026-01-28 01:24 UTC, tim-one approved these changes
Looks good!

2026-01-28 01:52 UTC, picnixz approved these changes

2026-08-06 14:49 UTC, merged