gh-125665: Replace turtledemo docstring with correct file name
python/cpython pull request #125691
Opened 2024-10-18 11:41 UTC by Wulian233

During the test I found a new bug, the `space` does not make `sorting_animate.py`
Exit normally and see the video. should be presse the EXIT button

https://github.com/user-attachments/assets/75a9e4fc-9313-4805-8099-39f615616ae7

2024-10-20 17:20 UTC, terryjreedy commented
About the side issue of sorting_animate.py:  The normal way to stop within the demo framework is the red STOP button, and this works (but see below).  The spacebar bit is for when one runs sorting_animate directly, as with `f:\dev\3x>python -m turtledemo.sorting_animate`.  Spacebar *does* work then.  Perhaps other demos should stop with spacebar when run directly.  Maybe some do?  Perhaps demo should know if run directly or in framework.  Anyway, another issue.  The 'but' above is that both STOP and spacebar raise Terminator when pressed while the animation is going, as opposed to when waiting for input (`i`, etc.).

2024-10-20 18:06 UTC, terryjreedy requested changes

2024-10-20 18:06 UTC, terryjreedy commented on Lib/turtledemo/colormixer.py
> +       turtledemo/colormixer.py
I would like all of these 3-line headers condensed to 

```suggestion
"""turtledemo/colormixer.py
```
This directory is the turtledemo suite and saying this twice is redundant.

2024-10-20 18:06 UTC, terryjreedy commented on Lib/turtledemo/sorting_animate.py
> -    onkey(bye, "space")
Let's leave code changes to a separate PR.  See https://github.com/python/cpython/pull/125691#issuecomment-2425136335 for this issue.

2024-10-20 18:06 UTC, terryjreedy commented on Lib/turtledemo/chaos.py
> +2009-06-24
I think remove this.  Each example was written by somebody.

2024-10-20 18:06 UTC, terryjreedy commented on Doc/library/turtle.rst
> +- Two example scripts :file:`nim.py` and :file:`round_dance.py`
I think this turtledemo item can be deleted.  Both examples are listed in the table above.

The 2.6 section should be deleted and I doubt this section is current.  'Added' notes should follow the item added, not collected together like this.  But these are turtle doc, not a turtledemo concern.

2024-10-20 18:06 UTC, terryjreedy commented on Lib/turtledemo/forest.py
> +https://homepage.univie.ac.at/erich.neuwirth/
Remove this link (German).  It has nothing to do with with the Logo program.  Anyone wanting to know about him should do a normal search.

2024-10-20 18:16 UTC, terryjreedy commented
As explained in https://github.com/python/cpython/issues/118673#issuecomment-2419980443, backports will have merge conflicts, like #123457 did.  So fixing more than the 3 header lines now is likely a good idea.  I believe that if you have the diff in a file, you can just add `#!/usr/bin/env python3\n` above `""".*suite:\n` and `"""turtledemo.*\n` lines (this latter after my requested change).  Then apply in 3.13 PR branch.  But I don't currently know all the details (I'm not a git expert).  We would have to check all examples in 3.13 to make sure they have the same exact `#!` line.

2024-10-20 18:20 UTC, terryjreedy commented
I decided to skip news as there is no reason I can think of that anyone should be hinted to possibly read the revised docstring.

2024-10-21 12:00 UTC, Wulian233 commented
> As explained in [#118673 (comment)](https://github.com/python/cpython/issues/118673#issuecomment-2419980443), backports will have merge conflicts, like #123457 did. So fixing more than the 3 header lines now is likely a good idea. I believe that if you have the diff in a file, you can just add above and lines (this latter after my requested change). Then apply in 3.13 PR branch. But I don't currently know all the details (I'm not a git expert).`#!/usr/bin/env python3\n``""".*suite:\n``"""turtledemo.*\n`
> 
> EDIT: Cancel this: "We would have to check all examples in 3.13 to make sure they have the same exact line. " As far as I can see, the turtledemo lines removed from main by https://github.com/python/cpython/pull/119658/files are all the same. Some non-turtledemo files had a space after .`#!``#!`

Sorry I didn't understand what should I do :( . Do I need to open another PR of 3.13/3.12 to resolve the conflict after merge? The above suggestion has been resolved, thanks

2024-10-22 03:57 UTC, terryjreedy commented on Lib/turtledemo/colormixer.py
> +       turtledemo/colormixer.py
This is not resolved because it was done only for colormixer, not all files.  Please let me (and other coredevs) decide if our comments are resolved.

2024-10-22 04:00 UTC, terryjreedy commented on Lib/turtledemo/sorting_animate.py
> -    onkey(bye, "space")
Code changes are moved to #125763 and its PR.

2024-10-22 04:01 UTC, terryjreedy commented on Doc/library/turtle.rst
> +- Two example scripts :file:`nim.py` and :file:`round_dance.py`
The two lines were deleted.

2024-10-22 04:07 UTC, terryjreedy commented on Lib/turtledemo/forest.py
> +https://homepage.univie.ac.at/erich.neuwirth/
I meant to only remove the quoted weblink, not the credit line "The example ... written by Erich Neuwirth."  Please restore it.

2024-10-22 04:40 UTC, terryjreedy commented
I unresolved comments 1 and 5 (though gh falsely still claims outdated).  Fix 5 first.

I believe 1 can be done with sed, which comes with Git for Windows.  Start menu => Git => Git Bash starts a Linux-like terminal that recognizes sed (stream editor) commands.  I used it several years ago after finding and reading a sed manual.  I will do so if need be.  (It might be easier to first undo the change to clock.py in the local branch version -- I don't know if sed on multiple files stops on error or merely reports and continues with the next one.)

When I merge to main, I will try backporting to be sure that the merge conflict for clock.py was due to (or remains after) changing the docstring rather than only resulting from deleting the coding line.  Assuming the backport fails, the first step will be to switch to a 3.13 branch (or workspace) and copy the new main turtledemo files into the turtledemo directory of a 3.13 PR branch.  I may ask other core developers if we need to add back the #! line.  If so, sed would be easiest.  I will let you try if you wish or refresh my sed-fu.

2024-10-22 11:50 UTC, Wulian233 commented on Lib/turtledemo/colormixer.py
> +       turtledemo/colormixer.py
Thanks for informing, I'll be aware of that in the future

2024-10-23 06:32 UTC, terryjreedy commented
Looks good as of my last comments.  Tomorrow I will recheck.  Since there is likely to be a backport problem, I will also expand comments to see if I want to make any further changes now before merging.

2024-10-23 15:07 UTC, terryjreedy commented on Lib/turtledemo/chaos.py
> +A demonstration of chaos
```suggestion
A demonstration of chaos.
```

2024-10-23 15:15 UTC, terryjreedy commented on Lib/turtledemo/forest.py
> +https://homepage.univie.ac.at/erich.neuwirth/
Done.

2024-10-23 15:18 UTC, terryjreedy commented
I added periods to 3 files.  Any further changes past line 3 will backport properly.

2024-10-23 15:19 UTC, terryjreedy approved these changes

2024-10-23 20:29 UTC, merged

2024-10-23 21:55 UTC, terryjreedy commented
Of the 19 examples, 13 have shebang lines an have the executable mode bit; the other 6 have neither.  Using cherry_picker showed that the 13 have merge conflicts because of the shebang lines.  I think we should leave shebang line presence and file mode alone.  I am thinking about how to be best do this while changing the docstring.

2024-10-23 23:51 UTC, terryjreedy commented
Thank you for the main PR. I can think of 3 backport approaches, and all seem more trouble than the result is worth.  I am now inclined to skip backports, close the issue, and move on to other isssues.

2024-10-24 10:33 UTC, Wulian233 commented
If you'd like, I can create a manual target of 3.13  `[3.13] 
gh-xxx: `, which may also resolve potential conflicts in the future (I'm not sure if the bug with the space exit https://github.com/python/cpython/issues/125763 after the fix has any conflicts)

2024-10-24 17:07 UTC, terryjreedy commented
At least part of the reason that shebang/mode changes were not backported was compatibility considerations (https://peps.python.org/pep-0387/). ([IDLE exception](https://peps.python.org/pep-0434/). ) As I said above, "we should leave shebang line presence and file mode alone".  This multiplies the time needed for a [3.13] backport by at least 2.  If you produce one ready-to-merge for fun/instruction, I will merge it, but I prefer to work on other issues.