gh-125590: Allow FrameLocalsProxy to delete and pop keys from extra locals
python/cpython pull request #125616
Opened 2024-10-16 20:31 UTC by gaogaotiantian

It's okay for us to pop/delete the keys that were added to `f_locals` manually, just ban the real fast variables.
@ncoghlan not sure if there's any documentation that needs to be changed.

I also changed the exception from `TypeError` to `KeyError` to match what `dict` generates.

2024-10-16 21:37 UTC, gaogaotiantian commented
@terryjreedy the only tests failed were Idle on MacOS-13, which is a bit weird. I can imagine changing `f_locals` impacts Idle, but only on a specific platform? Do you have any idea why the test failed? I looked at the error messages and they do not quite make sense to me.

2024-10-17 01:01 UTC, ZeroIntensity commented on Objects/frameobject.c
> +    PyObject* result = NULL;
PEP 7--not blaming you though, I like this style better :)
```suggestion
    PyObject *result = NULL;
```

2024-10-17 01:01 UTC, ZeroIntensity commented on Objects/frameobject.c
> +            PyErr_Format(PyExc_KeyError, "'%R'", key);
A tiny optimization to consider (though, it's more complex--feel free to reject this):
```suggestion
            PyObject *repr = PyObject_Repr(key);
            if (repr == NULL) {
                return NULL;
            }
            PyErr_SetObject(PyExc_KeyError, repr);
```

2024-10-17 01:01 UTC, ZeroIntensity commented on Lib/test/test_frame.py
> +            d.pop('non_exist')
Consider adding a test with `assertRaisesRegex` to make sure that the contents of the `KeyError` is correct.

2024-10-17 01:08 UTC, gaogaotiantian commented on Objects/frameobject.c
> +            PyErr_Format(PyExc_KeyError, "'%R'", key);
I just realized I could've used `_PyErr_SetKeyError(key)` like `dictobject.c`. I'll switch to that.

2024-10-17 01:09 UTC, ZeroIntensity commented on Objects/frameobject.c
> +            PyErr_Format(PyExc_KeyError, "'%R'", key);
Oh, that sounds better. I wasn't aware of that, TIL!

2024-10-17 01:32 UTC, gaogaotiantian commented on Objects/frameobject.c
> +            PyErr_Format(PyExc_KeyError, "'%R'", key);
So I switched to `_PyErr_SetKeyError(key)` when the key does not exist. However, for local variables cases, I think `RuntimeError` would fit better. One important reason was `KeyError` actually expects the "key" to be the explanation string, and giving a reason is a bit weird. Also in this case we have the key, we just can't remove it, so `RuntimeError` might be better.

2024-10-17 06:05 UTC, terryjreedy commented
MacOS versions after 10 have various odd interactions with tkinter and python.  Without a saved reference to the now-overwritten failing test, I cannot comment other than to note the following:
```
Searching 'locals()' in C:\Programs\Python314\Lib\idlelib\*.py ...
C:\Programs\Python314\Lib\idlelib\debugger.py: 248:             self.show_locals()
C:\Programs\Python314\Lib\idlelib\debugger_r.py: 214:             return self._get_f_locals()
```
The first call must result in the second, which I have no memory of.  There is no direct test of either function.  I'm glad you found better code that worked on major systems

2024-10-17 08:12 UTC, markshannon commented
I think this needs backporting to 3.13, as that's the version mentioned in the issue

2024-10-17 08:21 UTC, markshannon requested changes
The exception types need changing from `RuntimeError` to `KeyError`.
Otherwise, looks good.

2024-10-17 08:21 UTC, markshannon commented on Objects/frameobject.c
> +            PyErr_SetString(PyExc_RuntimeError, "cannot remove local variables from FrameLocalsProxy");
I think this should be a `KeyError`. 
Users will expect mapping types to raise a `KeyError`. https://docs.python.org/3/library/stdtypes.html#mapping-types-dict

2024-10-17 08:21 UTC, markshannon commented on Objects/frameobject.c
> +        PyErr_SetString(PyExc_RuntimeError, "cannot remove local variables from FrameLocalsProxy");
Ditto

2024-10-17 08:29 UTC, markshannon commented
FTR, from the PR, the potential additions to PEP 667 would be:

```
   def __delitem__(self, name):
        if name in co._name_to_offset_mapping:
             raise KeyError(f"Cannot delete local variable '{name}'")
        del self._extra_locals[name]

    def pop(self, name, default):
        if name in co._name_to_offset_mapping:
             raise KeyError(f"Cannot delete local variable '{name}'")
        return self._extra_locals.pop(name, default)
```

I think this is what we want.
Although maybe instead of `k = KeyError(f"Cannot delete local variable '{name}'")`, we could do this:
```Py
    k = KeyError(name)
    k.add_note("Cannot delete local variable")
```

2024-10-17 15:45 UTC, gaogaotiantian commented
From the [documentation](https://docs.python.org/3/library/exceptions.html#KeyError), it explains `KeyError` as

> Raised when a mapping (dictionary) key is not found in the set of existing keys.

I think there's a distinctive difference here. The key is in the mapping, we can even read it, `key in mapping == True`. We fail the operation because we don't allow deleting this key, not the key does not exist. I think a `RuntimeError` would fit better in this case.

2024-10-18 09:15 UTC, markshannon commented
I appreciate `KeyError` is not ideal.

I guess the question is do we want:
```Py
try:
    del f.f_locals["local_name"]
except KeyError:
    ...
```
to handle the exception or not?

If not, then I think `ValueError` is better than `RuntimeError`.

> 
> exception ValueError
> Raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as [IndexError](https://docs.python.org/3/library/exceptions.html#IndexError).
> 
> 

Other than that, the PR looks ready to merge.

2024-10-18 21:40 UTC, gaogaotiantian commented
> I guess the question is do we want:
> 
> ```python
> try:
>     del f.f_locals["local_name"]
> except KeyError:
>     ...
> ```
> 
> to handle the exception or not?

I think we need two separate exceptions because I don't know what they would do in the `except` block here. Trying to remove a real local variable is very different than trying to remove an artificial variable. Even for a try ... except block, I think those should be separate cases.

2024-10-19 14:42 UTC, ncoghlan commented
I also agree `ValueError` makes sense. 

For https://github.com/python/peps/pull/3845, I've described this with prose rather than the equivalent Python code:

> Extra keys (which do not correspond to local variables on the underlying
frame) may be removed as usual with ``del`` statements or the ``pop()``
method.
>
> Using ``del``, or the ``pop()`` method, to remove keys that correspond to local
variables on the underlying frame is NOT supported, and attempting to do so
will raise ``ValueError``.
>
> Local variables can only be set to ``None`` (or some other value) via the proxy,
they cannot be unbound completely.

(and then linked back to this PR and the associated bug report from the "Implementation Notes" section)

For the main docs, looking at https://docs.python.org/dev/reference/datamodel.html#frame-objects there's nothing that currently goes into that level of detail. I'll file a separate docs issue suggesting adding a 4th subsection there that talks more about the write-through proxy behaviour.

2024-10-19 14:43 UTC, ncoghlan approved these changes

2024-10-21 10:37 UTC, markshannon commented
Ok, let's go with ValueError.

2024-10-21 10:40 UTC, markshannon approved these changes
Thanks

2024-10-21 15:43 UTC, merged