gh-125746: Remove deprecated `zipimport.zipimporter.load_module`
python/cpython pull request #125748
Opened 2024-10-20 05:03 UTC by Wulian233

Remove deprecated method `zipimport.zipimporter.load_module`. It had previously raised a :exc:`DeprecationWarning` since Python 3.10. Use `zipimport.zipimporter.exec_module` instead.

2024-10-20 06:47 UTC, Wulian233 commented
I removed a few lines of code related to load_module for the test, but the test failed. The error message does not seem to be related to the removed code from the surface, but it is indeed caused by this. Does anyone know why this is happening? What should I do?

2024-10-20 07:00 UTC, rruuaanng commented
I also encountered this problem, but I don't know why it happened. I opened an issue.

2024-10-20 15:00 UTC, ZeroIntensity requested changes
I would like to postpone this until 3.15. Please update the PR to move the `load_module` deprecation to `pending-removal-in-3.15`

2024-10-20 22:36 UTC, Wulian233 commented
You're right, when I did this pr, my vscode (the latest Python extension) didn't prompt exec_module either. I will edit the pending-removal-in-3.15.rst and Lib/zipimport.py to remove the entries for pending-removal-in-future.rst

2024-10-21 11:48 UTC, ZeroIntensity approved these changes
Thank you! LGTM.

2024-10-21 16:19 UTC, brettcannon requested changes

2024-10-21 16:19 UTC, brettcannon commented on Lib/zipimport.py
> +               "removal in Python 3.15; use exec_module() instead")
We should probably update this to use `warnings._deprecated()`.

https://github.com/python/cpython/blob/5b7a872b26a9ba6c93d7c2109559a82d1c1612de/Lib/warnings.py#L650-L668

2024-10-21 22:53 UTC, Wulian233 commented
I have made the requested changes; please review again

2024-10-22 15:57 UTC, brettcannon approved these changes

2024-10-22 15:58 UTC, brettcannon approved these changes

2024-10-22 15:58 UTC, brettcannon commented on Doc/deprecations/pending-removal-in-3.15.rst
> +* :meth:`~zipimport.zipimporter.load_module` have been deprecated since
```suggestion
* :meth:`~zipimport.zipimporter.load_module` has been deprecated since
```

2024-10-27 08:14 UTC, Wulian233 commented
Can we ready to merge?
ping~ @brettcannon

2024-10-31 22:41 UTC, Wulian233 commented
There was a test failure here, it seems that zipimport.zipimport was used, but the PR did not make any other changes

2024-11-10 15:18 UTC, picnixz reviewed
Can you check if there is a `deprecated-removed` directive to update in the corresponding docs entry?

2024-11-10 15:18 UTC, picnixz commented on Doc/deprecations/pending-removal-in-3.15.rst
> +  Python 3.10. Use :meth:`~zipimport.zipimporter.exec_module` instead.
```suggestion
  * :meth:`~zipimport.zipimporter.load_module` has been deprecated since
    Python 3.10. Use :meth:`~zipimport.zipimporter.exec_module` instead.
```

2024-11-10 15:18 UTC, picnixz commented on Lib/zipimport.py
> +                         remove=(3, 15))
```suggestion
        import warnings
        warnings._deprecated("zipimport.zipimporter.load_module",
                             f"{warnings._DEPRECATED_MSG}; "
                             "use zipimport.zipimporter.exec_module() instead",
                             remove=(3, 15))
```

2024-11-10 15:18 UTC, picnixz commented on Lib/zipimport.py
> +import warnings  # For warnings
```suggestion
```

2024-11-10 15:18 UTC, picnixz commented on Misc/NEWS.d/next/Library/2024-10-20-13-01-05.gh-issue-125746.wDLTay.rst
> +time to 3.15. Use :meth:`~zipimport.zipimporter.exec_module` instead.
```suggestion
Delay deprecated :meth:`zipimport.zipimporter.load_module` removal
time to 3.15. Use :meth:`zipimport.zipimporter.exec_module` instead.
```

We want fully-qualified names since seeing `load_module` or `exec_module` only may be confusing in the full CHANGELOG entry since there is no "zipimport" section here.

2024-11-11 11:35 UTC, Wulian233 commented
Applied code review suggestions

2024-11-17 02:25 UTC, Wulian233 commented
@brettcannon Can we merge this? It should be fine now, thank you!

2024-11-17 02:29 UTC, rruuaanng commented
@Wulian233 Be patient, everyone has their own job :)

2024-11-17 05:12 UTC, ZeroIntensity commented
Eh, IMO it's fine to remind someone to merge if the PR hasn't had any additional reviewers

2025-02-11 20:18 UTC, Wulian233 commented
A few months later: A similar PR for the delayed removal of `exec_module` in `importlib` https://github.com/python/cpython/pull/129855 was just merged and backported. Is this PR still needed?

2025-02-11 20:52 UTC, tomasr8 commented
> Is this PR still needed?

It is, this one updates `zipimport`, while the other one was for `importlib`.

2025-02-11 23:36 UTC, brettcannon approved these changes

2025-02-11 23:59 UTC, merged

2025-02-12 00:16 UTC, brettcannon commented
Sorry for the delay! Got swamped and this fell off my radar thinking I was waiting on something for the PR.