gh-84545: Clarify the 'extend' action documentation in argparse
python/cpython pull request #125870
Opened 2024-10-23 08:55 UTC by serhiy-storchaka

* Issue: gh-84545

----
📚 Documentation preview 📚: https://cpython-previews--125870.org.readthedocs.build/

2024-10-23 08:56 UTC, serhiy-storchaka commented
@savannahostrowski, could you, as a native speaker, please look at these changes?

2024-10-23 23:03 UTC, savannahostrowski requested changes
Sounds good - just a couple of tweaks!

2024-10-23 23:03 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +  Example usage::
```suggestion
* ``'extend'`` - This stores a list and appends each item from the multi-value
  argument list to it.
  The ``'extend'`` action is typically used with the nargs_ keyword argument
  value ``'+'`` or ``'*'``.
  Note that when nargs_ is ``None`` (the default) or ``'?'``, each
  character of the argument string will be appended to the list.
  Example usage::
```

2024-10-23 23:03 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +  Example usage::
Should we also move this phrase up or better integrate it into the intro paragraph before listing the actions available?

> Only actions that consume command-line arguments (e.g. ``'store'``,
``'append'`` or ``'extend'``) can be used with positional arguments.

IMO, it seems a little disjoint at the bottom of the section now.

2024-10-23 23:55 UTC, serhiy-storchaka commented on Doc/library/argparse.rst
> +  Example usage::
As for "the list"/"it" -- in descriptions of 'append' and 'append_const' they repeat "the list". Is it okay to have such difference, or "the list" should be replaced with "it" in other places too? Or there wass a reason to repeat "the list"?

> IMO, it seems a little disjoint at the bottom of the section now.

How do you suggest to move and change it? It is not at the bottom at the section -- there is a lot of text and examples after it. It is not disjoined -- it immediately follows the list of actions. Did you mean something other?

2024-10-24 23:22 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +  Example usage::
> As for "the list"/"it" -- in descriptions of 'append' and 'append_const' they repeat "the list". Is it okay to have such difference, or "the list" should be replaced with "it" in other places too? Or there wass a reason to repeat "the list"?

It reads a bit redundant to me, but we can keep it for consistency.

> How do you suggest to move and change it? It is not at the bottom at the section -- there is a lot of text and examples after it. It is not disjoined -- it immediately follows the list of actions. Did you mean something other?

Thinking about this more, I think it's fine as you have it now. I considered whether it'd be worth having this as a pre-amble before introducing the actions, but I'm not sure I love it either. You can disregard this for now  😄 !

2024-10-25 08:15 UTC, serhiy-storchaka commented
Thank you for your review @savannahostrowski. My English is very bad and I appreciate any help.

2024-10-25 08:41 UTC, merged