Fixed capital letters missing and missing .
python/cpython pull request #12584
Opened 2019-03-27 10:46 UTC by Seluj78

No `bpo` for minor doc fix

2019-03-27 10:50 UTC, eamanu approved these changes
Lgtm

2019-03-27 12:27 UTC, Seluj78 commented
cc @birkenfeld

2019-03-27 12:51 UTC, csabella commented
I can understand why this is lower case; it is using the `New in version 3.1:` part as the beginning of the sentence.  However, it may be better to make this more of a complete sentence in itself, such as ``Added under the name``.

There is another lower case example under the `Deprecated Alias` section:
``Deprecated since version 3.1: the fail* aliases listed in the second column.``

That one would probably should have the `the` capitalized.

2019-03-27 14:13 UTC, eamanu commented
@csabella  mmm yes ... sound good that you say, but on the line 1005 on the versionchanged ```Renamed to :meth:`assertRaisesRegex`.```  start with capital.

2019-03-27 14:31 UTC, Seluj78 commented
Done @csabella

2019-03-27 19:01 UTC, brettcannon requested changes
If the sentences are going to be edited then they should be made into complete sentences.

2019-03-27 19:01 UTC, brettcannon commented on Doc/library/unittest.rst
> +         Under the name ``assertRegexpMatches``.
```suggestion
         Added under the name ``assertRegexpMatches``.
```

2019-03-27 19:01 UTC, brettcannon commented on Doc/library/unittest.rst
> +         The assert* aliases listed in the third column.
```suggestion
         The assert* aliases listed in the third column have been deprecated.
```

2019-03-27 19:01 UTC, brettcannon commented on Doc/library/unittest.rst
> +         The ``assertNotRegexpMatches`` name in favor of :meth:`.assertNotRegex`.
```suggestion
         The ``assertNotRegexpMatches`` name is deprecated in favor of :meth:`.assertNotRegex`.
```

2019-03-27 19:01 UTC, brettcannon commented on Doc/library/unittest.rst
> +         The fail* aliases listed in the second column.
```suggestion
         The fail* aliases listed in the second column have been deprecated.
```

2019-03-28 07:27 UTC, Seluj78 commented
I have made the requested changes; please review again

2019-03-28 21:06 UTC, brettcannon approved these changes

2019-03-28 21:06 UTC, merged

2019-03-28 21:06 UTC, miss-islington commented
Thanks @Seluj78 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖