GH-125868: Fix STORE_ATTR_WITH_HINT specialization
python/cpython pull request #125876
Opened 2024-10-23 13:11 UTC by markshannon

Simple fix, but challenging to test.

Also fixes a minor bug I found in `dis.dis(show_caches=True)` while investigating the issue.

2024-10-23 22:51 UTC, hroncok commented
This fixes https://github.com/cython/cython/issues/6426

2024-10-24 08:57 UTC, iritkatriel approved these changes

2024-10-24 09:14 UTC, hroncok requested changes
The versions in NEWS are off by one.

2024-10-24 09:14 UTC, hroncok commented on Misc/NEWS.d/next/Core_and_Builtins/2024-10-23-14-05-47.gh-issue-125868.uLfXYB.rst
> +It was possible in 3.14.a0 only for attribute lookup to give the wrong
```suggestion
It was possible in 3.14.0a1 only for attribute lookup to give the wrong
```

2024-10-24 09:14 UTC, hroncok commented on Misc/NEWS.d/next/Core_and_Builtins/2024-10-23-14-05-47.gh-issue-125868.uLfXYB.rst
> +circumstances. This is fixed in 3.14.a1.
```suggestion
circumstances. This is fixed in 3.14.0a2.
```

2024-10-24 10:57 UTC, merged