bpo-31341: remove more SGI IRIX-specific codes
python/cpython pull request #12587
Opened 2019-03-27 14:33 UTC by yan12125

To make work on curses-related modules simpler https://bugs.python.org/issue28190

2019-09-11 14:10 UTC, benjaminp requested changes
This looks mostly good but needs a rebase.

2019-09-11 14:10 UTC, benjaminp commented on Modules/_cursesmodule.c
> +#if defined(HAVE_TERM_H)
Can you change this to `#ifdef`?

2019-09-11 14:10 UTC, benjaminp commented on Modules/posixmodule.c
> +#if defined(HAVE_DEV_PTC)
Change to `ifdef`.

2019-09-15 02:57 UTC, yan12125 commented
I have made the requested changes; please review again.

As a side note, the merge conflict was due to additions for VxWorks (https://github.com/python/cpython/pull/12118/files#diff-a6f29e907cbb5fffd44d453bcd7b77d5R232).

2021-02-20 12:38 UTC, yan12125 commented
Most IRIX-specific codes are removed in https://github.com/python/cpython/pull/23023, while there are still references to IRIX-specific macros `sgi` and `__sgi`. I rebased this pull request to only remove remaining macros.

2021-11-12 08:51 UTC, yan12125 commented
Rebased for recent cleanups in Include/Python.h (https://bugs.python.org/issue45434)

2022-03-14 06:01 UTC, yan12125 commented
Seems no sign of further reviewing, closing.

2022-03-14 06:01 UTC, closed without merging