bpo-31904: fix signalmodule issue in VxWorks
python/cpython pull request #12670
Opened 2019-04-03 02:33 UTC by yuesun1

The type of sig_atomic_t is 'unsigned char' in VxWorks, so it can't be assigned to -1, so in the signalmodule.c. I set the data type of fd in struct 'wakeup' to 'int' for VxWorks.

More and full support on modules for VxWorks will continuously be added by the coming PRs.
VxWorks is a product developed and owned by Wind River. For VxWorks introduction or more details, go to https://www.windriver.com/products/vxworks/
Wind River will have a dedicated engineering team to contribute to the support as maintainers.
We already have a working buildbot worker internally, but has not bound to master. We will check the process for the buildbot, then add it.

2019-04-09 12:45 UTC, jdemeyer requested changes
The `fd` member is clearly meant to be a file descriptor, which is of type `int` (as specified by POSIX). So the old code is unconditionally wrong: you should use `int` on all systems, not just VxWorks. This happened to work because `sig_atomic_t` is `int` on almost all systems.

2019-04-10 05:51 UTC, jdemeyer commented on Misc/NEWS.d/next/Library/2019-04-03-10-14-36.bpo-31904.xd3b78.rst
> +fix VxWorks signalmodule issue
I'd rather frame this as a general bug-fix and not a VxWorks-specific issue.

2019-04-10 06:03 UTC, jdemeyer commented
Now that you're correctly using `int`, reading/writing it may no longer be atomic. So you should use the atomic macros to access it (there are plenty of examples in `signalmodule.c` doing that).

2019-04-10 06:38 UTC, yuesun1 commented
Thanks for your comment, now the fd is not atomic, do you mean I also still use _Py_atomic_load() or _Py_atomic_store() to read/write it ?

Thanks very much

2019-04-17 10:25 UTC, vstinner commented
Please open a separated issue for this change.

2019-04-17 12:13 UTC, jdemeyer commented
> Thanks for your comment, now the fd is not atomic, do you mean I also still use _Py_atomic_load() or _Py_atomic_store() to read/write it ?

Yes, I think so. You'll find many uses of these functions in `signalmodule.c`.

2019-05-21 10:48 UTC, vstinner commented
The easiest way to fix VxWorks but not impact other operating systems if to modify your PR as, pseudo-code:

```
#ifdef <VxWorks>
int ...
#else
sig_atomic_t ...
#endif
```

2019-05-21 11:02 UTC, jdemeyer commented
The existing code is unconditionally wrong: it's a file descriptor, which is of type `int`.

2019-05-21 11:18 UTC, vstinner commented
> The existing code is unconditionally wrong: it's a file descriptor, which is of type int.

I already asked "Please open a separated issue for this change." but nobody did that.

2019-05-21 11:46 UTC, jdemeyer commented
> I already asked "Please open a separated issue for this change." but nobody did that.

I know but that doesn't imply that the existing code is correct. It only means that nobody cares enough to open an issue.

2019-05-21 11:57 UTC, vstinner commented
> It only means that nobody cares enough to open an issue.

In case of doubt, I'm ok to leave the code unchanged: that's the safest option. That's the principle of https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence To remove the fence, someone must first investigate why it's there.

This issue is about VxWorks. I disagre that adding VxWorks support would change the code on other platforms.

2020-11-30 08:35 UTC, vstinner commented
Let's continue the work on PR #23391.

2020-11-30 08:35 UTC, closed without merging