gh-126775: make linecache.checkcache threadsafe and GC re-entrency safe
python/cpython pull request #126776
Opened 2024-11-13 10:43 UTC by graingert

* Issue: gh-126775

2024-11-19 01:43 UTC, bswck commented on Misc/NEWS.d/next/Library/2024-11-13-10-44-25.gh-issue-126775.a3ubjh.rst
> +make :func:`linecache.checkcache` threadsafe and GC re-entrency safe
```suggestion
Make :func:`linecache.checkcache` thread safe and GC re-entrancy safe.
```

2024-12-04 09:48 UTC, cfbolz requested changes

2024-12-04 09:48 UTC, cfbolz commented on Lib/linecache.py
> +        filenames = cache.copy().keys()
I would add a comment here why the copy is necessary. Apart from that it looks good to me.

2024-12-04 09:52 UTC, graingert commented on Lib/linecache.py
> +        filenames = cache.copy().keys()
```suggestion
        # get keys atomically
        filenames = cache.copy().keys()
```

2024-12-04 09:53 UTC, graingert commented
I have made the requested changes; please review again

2024-12-05 07:23 UTC, cfbolz approved these changes

2024-12-10 07:40 UTC, merged