gh-126400: Add TCP socket timeout to SysLogHandler to prevent blocking
python/cpython pull request #126716
Opened 2024-11-12 07:05 UTC by hodamarr

Issue #126400.
branch name - fix-issue-126400

### Summary
In the current implementation of the `SysLogHandler` class from the `logging.handlers` module, if the specified address does not respond or is unreachable, the `createSocket` method may block indefinitely in case of using TCP socket (based on stream). This is problematic because there is no way to set a socket timeout during the connection's creation without overriding the entire `createSocket` method.

### Changes
1. Added a `timeout` parameter to the `SysLogHandler.__init__` method, allowing users to specify a timeout for the socket connection.
2. Updated the `createSocket` method to apply the `timeout` to the socket if provided.

This change allows users to prevent indefinite blocking on socket creation, enabling more robust error handling when the SysLog server is unresponsive.

### Example Usage
With this update, users can now create a `SysLogHandler` with a timeout as follows:

```python
import logging
from logging.handlers import SysLogHandler

# Create a SysLogHandler with a 5-second timeout
handler = SysLogHandler(address=('localhost', 514), timeout=5)
```

2024-11-12 08:04 UTC, vsajip commented
Thank you for the PR. Would you mind updating the documentation, adding a NEWS entry using the `blurb` tool and signing the CLA? Thanks again.

2024-11-12 15:55 UTC, hodamarr commented
Hi @vsajip, added

2024-11-12 20:37 UTC, vsajip commented
Thanks for those. You don't feel comfortable updating the docs?

2024-11-12 20:47 UTC, hodamarr commented
@vsajip Oh, I thought you meant only the blurb. I'll update the documentation as well

2024-11-13 09:13 UTC, vsajip commented
> This is the first time that I'm contributing to open source

Hopefully the first of many contributions! As it's an API change, it needs the documentation updating so users will know about the new parameter.

2024-11-13 10:06 UTC, asvetlov commented on Misc/NEWS.d/next/Library/2024-11-12-15-55-14.gh-issue-126400.ztsnx5.rst
> +Added a timeout parameter to logging.handlers.SysLogHandler class to control the TCP socket timeout and prevent process blocking when the Syslog server is unreachable; this improves resilience when w
```suggestion
Added a timeout parameter to :class:`logging.handlers.SysLogHandler` class to control the TCP socket timeout and prevent process blocking when the Syslog server is unreachable; this improves resilience when working with unresponsive Syslog servers. 

```

2024-11-13 10:11 UTC, asvetlov requested changes
Please update file `./Doc/library/logging.handlers.rst` to mention added `timeout` parameter.

Take a look at`socktype` argument for inspiration.

2025-01-19 10:17 UTC, vsajip commented on Doc/library/logging.handlers.rst
> +   .. versionchanged:: 3.x
```suggestion
   .. versionchanged:: 3.14
```

2025-01-29 13:51 UTC, vsajip commented
The docs build is failing with some unrelated error in processing the Misc/NEWS entries, same happens locally. I've fixed the sphinx lint error and missing blurb in this PR. Not sure what the docs build problem is.

2025-01-29 19:36 UTC, vsajip commented
Somewhere, perhaps during a force-push, the original blurb got lost. I added a new one (a bit shorter) and everything now seems to be building correctly. I had to update a couple of unrelated blurb files, seemingly because they wrongly had `gh:` instead of `gh-issue:` in places (perhaps a change to blurb caused the build failures).

2025-01-29 19:36 UTC, vsajip approved these changes

2025-01-29 19:37 UTC, merged