gh-126911: Update credits output (Trivial Change)
python/cpython pull request #126913
Opened 2024-11-16 22:03 UTC by StanFromIreland

Trivial change updating name of Python Foundation.

2024-11-16 22:36 UTC, hugovk commented
Thanks for the suggestion, but I don't think we should erase their contribution and credit because they had dot com in their name, and the corresponding website is no longer up.

BeOpen.com also has history relating to licensing:

https://docs.python.org/3/license.html

> Trivial change updating name of Python Foundation.

See the history page above, the PSF isn't the same as BeOpen.com with a new name.

2024-11-16 23:00 UTC, StanFromIreland commented
@hugovk 

My mistake I have updated my commit to include BeOpen.

2024-11-17 22:44 UTC, terryjreedy requested changes
Approve with 2 tweaks.

2024-11-17 22:44 UTC, terryjreedy commented on Misc/NEWS.d/next/Windows/2024-11-16-22-08-41.gh-issue-126911.HchCZZ.rst
> +Updated credits command output
```suggestion
Update credits command output.
```

2024-11-17 22:44 UTC, terryjreedy commented on Lib/site.py
>      for supporting Python development.  See www.python.org for more information.""")
Reflow to 80 columns.
```suggestion
    Thanks to CWI, CNRI, BeOpen, Zope Corporation, the Python Software
    Foundation, and a cast of thousands  for supporting Python
    development.  See www.python.org for more information.""")
```

2024-11-17 22:44 UTC, terryjreedy approved these changes

2024-11-17 23:06 UTC, terryjreedy commented
Hugo: I am not sure whether changing 'BeOpen.com' to 'BeOpen' is proper or whether '.com' is part of the name, as opposes to url.  Even if '.com' was part of the name, the fact that 'BeOpen.com' in the browser resolves to now unrelated 'beopen.com' suggest that deleteing '.com' is a good idea.  I am letting you decide and merge.

Stan: the commit message one adds is intended to be put above, not below, the boilerplate comment.  Much easier to edit when above.

2024-11-18 11:49 UTC, encukou commented on Lib/site.py
> +    Foundation, and a cast of thousands  for supporting Python
```suggestion
    Foundation, and a cast of thousands for supporting Python
```

2024-11-18 12:02 UTC, hugovk approved these changes
As far as I can tell, "BeOpen.com" was the full name. It was from the dotcom bubble days, and they've long been out of business (as is visible from the new owners of the domain).

We should keep "BeOpen.com" for the [copyright](https://docs.python.org/3/copyright.html) and [licence](https://docs.python.org/3/license.html), but I thinks it's fine to use a shorter version here in the REPL credits.

2024-11-18 15:29 UTC, hugovk commented
@StanFromIreland Tip for next time, we prefer not to rebase branches and force push in this repo, thanks!

2024-11-18 15:29 UTC, merged