gh-127036: Update `importlib.util._LazyModule.__getattribute__` to special-case requests for `__spec__`.
python/cpython pull request #127038
Opened 2024-11-19 21:10 UTC by Sachaa-Thanasius

Allow `importlib.util._LazyModule` to special-case its `__spec__` attribute so that when the regular import machinery requests that attribute, it doesn't trigger the full module load.

2024-11-19 21:28 UTC, Sachaa-Thanasius commented
A few things I'm unsure of:
- Is this is worthy of a news fragment?
- What kind of tests would suffice? I can imagine adding two along the lines of `test_spec_passthrough_without_load` and `test_e2e_same_module` in `Lib/test/test_importlib/test_lazy.py`, but I'm not confident in that, so I'd appreciate any guidance.

2025-08-18 17:25 UTC, brettcannon commented
> * Is this worthy of a news fragment?

I think so since it changes the semantics and someone may have been relying on it.



> * What kind of tests would suffice?

I think what you already have in the PR suffices as it verifies things are working.

2025-08-18 17:25 UTC, brettcannon commented
And apologies for taking so long to get to this PR!

2025-08-18 17:26 UTC, brettcannon approved these changes

2025-08-18 17:26 UTC, brettcannon commented
FYI my approval is still gated on a news entry thanks to CI checking for it.

2025-08-18 17:39 UTC, Sachaa-Thanasius commented
Cheers! Looking at this with fresh eyes, the semantic change definitely warrants more than just a code change.

In addition to the news entry, I'll attempt to tweak the `LazyLoader` docs and `LazyLoader.exec_module` comment to mention the `__spec__` special case, since both currently specify that _any_ attribute access triggers the load. Hope that's fine.

2025-08-19 17:55 UTC, brettcannon commented
> Hope that's fine.

Sounds great!

2025-09-09 19:54 UTC, brettcannon requested changes
This needs at least a news entry and doc changes.

2025-11-21 00:02 UTC, brettcannon commented
@Sachaa-Thanasius do you think you want to continue to work on this and address the review comments?

2025-12-19 18:26 UTC, brettcannon commented
@Sachaa-Thanasius if you end up wanting to pick up this PR later just let me know, but otherwise I'm closing this PR due to lack of activity.

2025-12-19 18:26 UTC, closed without merging

2025-12-19 18:31 UTC, Sachaa-Thanasius commented
Apologies, life was distracting. Still is. Also, I had second thoughts on the scope of this (e.g. maybe we actually want to return a copy of the spec, since it's mutable; maybe there are other import-related attributes we want to exclude like `__path__`; and so on).

I'll come back to this when I'm in a better headspace (or maybe someone will beat me to it :D).