gh-127385: Add latest F_DUPFD_QUERY constants to fcntl module
python/cpython pull request #127386
Opened 2024-11-29 05:13 UTC by rruuaanng

By the way
```
if (PyModule_AddIntMacro(m, LOCK_NB)) return -1;
```
is packaged to be consistent with the approach in `socketmodule.c`. Like this
```
#define ADD_INT_MACRO(MOD, INT) do {                    \
    if (PyModule_AddIntConstant(MOD, #INT, INT) < 0) {  \
        goto error;                                     \
    }                                                   \
} while (0)
```

2024-11-29 06:19 UTC, ZeroIntensity requested changes, later dismissed
This PR is trying to do too many things. I don't really see the need for the switch to a new macro, but if we do end up doing that, it should be in another PR. Please revert that and keep this focused on the one new macro.

2024-11-29 06:23 UTC, rruuaanng commented
@ZeroIntensity
I think you are right. Can you help me convert it into a draft? I'm mobile now.

2024-11-29 08:08 UTC, erlend-aasland approved these changes

2024-11-29 08:11 UTC, erlend-aasland commented
> This PR is trying to do too many things. I don't really see the need for the switch to a new macro, but if we do end up doing that, it should be in another PR. Please revert that and keep this focused on the one new macro.

@rruuaanng, please take Peter's words into account for future contributions. That piece of advice is also spelled out in the devguide.

2024-11-29 08:14 UTC, rruuaanng commented
> > This PR is trying to do too many things. I don't really see the need for the switch to a new macro, but if we do end up doing that, it should be in another PR. Please revert that and keep this focused on the one new macro.
> 
> 
> 
> @rruuaanng, please take Peter's words into account for future contributions. That piece of advice is also spelled out in the devguide.

Yes, So I've completed his suggestion. I almost forgot it in the process :)

2024-11-29 16:16 UTC, ZeroIntensity approved these changes
Thank you :)

2024-11-30 09:11 UTC, rruuaanng commented
Hold on, I need to add a document for fcntl, and I found the addition log in the existing documentation. And I confirmed that there is no corresponding document for my other PR

2024-12-03 22:40 UTC, erlend-aasland commented on Misc/NEWS.d/next/Library/2024-11-29-13-06-52.gh-issue-127385.PErcyB.rst
> +Add the ``F_DUPFD_QUERY`` macro constants to the :mod:`fcntl`.
```suggestion
Add the ``F_DUPFD_QUERY`` constant to the :mod:`fcntl` module.
```

2024-12-03 22:40 UTC, erlend-aasland commented on Doc/library/fcntl.rst
> +.. versionchanged:: 3.14
```suggestion
.. versionchanged:: next
```

2025-04-24 21:06 UTC, serhiy-storchaka approved these changes
LGTM.

2025-04-24 21:06 UTC, merged