gh-127411: Fix invalid conversion of load of TLBC array when compiled in C++
python/cpython pull request #127466
Opened 2024-12-01 06:54 UTC by mpage

Cast the load of the thread-local bytecode array.

2024-12-01 06:58 UTC, mpage commented
I was able to reproduce the issue installing scipy and verified that running `pip install -U --pre --no-build-isolation  git+https://github.com/scipy/scipy` in a venv built with this PR succeeds.

2024-12-01 13:06 UTC, Fidget-Spinner approved these changes

2024-12-01 22:26 UTC, clin1234 requested changes
A `_Py_STATIC_CAST` is more suitable, no?

2024-12-02 12:50 UTC, clin1234 approved these changes

2024-12-02 13:57 UTC, ZeroIntensity commented on Include/internal/pycore_code.h
> +    return _Py_STATIC_CAST(_PyCodeArray *,
I thought about `_Py_STATIC_CAST` when I mentioned it in the issue, but the [precedent](https://github.com/search?q=repo%3Apython%2Fcpython%20_Py_STATIC_CAST&type=code) is to not use it for objects.

2024-12-02 14:53 UTC, colesbury approved these changes

2024-12-02 18:13 UTC, merged