gh-127434: Fix iOS `xcrun --sdk` clang/ar scripts to allow arguments with spaces
python/cpython pull request #127575
Opened 2024-12-03 18:27 UTC by FeodorFitsner

This PR fixes scripts `iOS/Resources/bin` directory to allow arguments with spaces.

Related issue: #127434

2024-12-03 18:29 UTC, FeodorFitsner commented
cc @freakboy3742

2024-12-03 22:58 UTC, freakboy3742 requested changes
Thanks for the contribution - the code changes look fine; from a process perspective, all changes to Python [require a NEWS entry](https://devguide.python.org/core-developers/committing/#how-to-add-a-news-entry). Bevedere has provided a link to an online tool that can be used to add one, or you can set up the `blurb` tool in your own environment.

2024-12-04 23:02 UTC, freakboy3742 commented on Misc/NEWS.d/next/Core_and_Builtins/2024-12-04-09-52-08.gh-issue-127434.RjkGT_.rst
> +with spaces.
```suggestion
The iOS compiler shims can now accept arguments with spaces.
```

2024-12-05 00:34 UTC, freakboy3742 approved these changes
Thanks for the fix!

2024-12-05 00:35 UTC, freakboy3742 commented
!buildbot iOS

2024-12-05 00:50 UTC, freakboy3742 commented
I'm just waiting on an iOS buildbot job to 100% confirm that this works; for some reason, the buildbots doesn't seem to be starting jobs at present...

2024-12-05 03:00 UTC, merged

2024-12-05 05:54 UTC, freakboy3742 commented
The Fedora build failure seems to be a transient network failure, not related to this PR.