better __init__.py explanation in tutorial
python/cpython pull request #12763
Opened 2019-04-10 11:52 UTC by methane

ref: https://python.zulipchat.com/#narrow/stream/116633-documentation/topic/English.20question

2019-04-10 17:38 UTC, auvipy approved these changes

2019-04-10 19:46 UTC, brettcannon requested changes

2019-04-10 19:46 UTC, brettcannon commented on Doc/tutorial/modules.rst
> +such as ``string``, unintentionally hide valid modules that occur later
```suggestion
such as ``string``, unintentionally hiding valid modules that occur later
```

2019-04-11 06:10 UTC, merged

2019-04-11 06:10 UTC, miss-islington commented
Thanks @methane for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖