GH-126367: Fix urllib.request.url2pathname() colon handling in URLs on Windows
python/cpython pull request #127752
Opened 2024-12-09 03:59 UTC by samtstephens

2024-12-09 09:23 UTC, nineteendo commented on Lib/nturl2path.py
> +    if not '|' in url or ('|' in url and not (
Can this not be simplified? I had a hard time understanding the code:

```python
url = url.replace(':', '|', 1)
if not '|' in url or ('|' in url and not (
    url.startswith('|') # error case
    or '/|' in url      # error case
    or (len(url) > 2 and url[0] == '/' and url[1].isalpha() and url[2] == '|')
)):
```

2024-12-10 00:26 UTC, barneygale requested changes
Thanks for taking a look at this

It's perhaps worth taking a step back to think about what we're aiming to do here, and why Windows drive paths need special handling.

The simplest way to create a `file:` URI is to prepend `file:` to a path, so:

- `foo/bar.txt` becomes `file:foo/bar.txt`
- `/etc/hosts` becomes `file:/etc/hosts`

For conformance with [RFC 1738](https://www.rfc-editor.org/rfc/rfc1738), folks began adding an empty authority section for absolute paths, so:

- `/etc/hosts` becomes `file:///etc/hosts`

This works nicely on POSIX because absolute paths must start with a slash, just like the *path* component of URLs.

But what about Windows? A path like `C:/foo` can't be directly mapped to a URL path component because it doesn't start with a slash. The solution folks came up with: just add a slash prefix!

- `C:/foo` becomes `file:///C:/foo`

Our task in this PR is to undo that operation. We need to:

- Detect when a URL's *path* component begins with a slash and then a Windows drive, like `/A:/foo/bar` or `/B|/doo`
  - Remove the leading slash if so
- If second character is `|`, convert it to `:`

As far as detecting a Windows drives goes, I suggest having a look at the implementation of `os.path.splitroot()` or `os.path.isabs()` in `ntpath.py`:

https://github.com/python/cpython/blob/5c89adf385aaaca97c2ee9074f8b1fda0f57ad26/Lib/ntpath.py#L80-L95

We don't need to check whether the drive letter is alphabetic IMHO. It's probably sufficient to check that 3rd character in the URL path is a colon or a pipe.

2024-12-10 00:40 UTC, barneygale commented
Don't worry about breaking the following test case - there's no reason for `url2pathname()` to be stricter about Windows drives than functions in `ntpath.py`. It would be good if `url2pathname()` didn't raise `OSError` at all.

https://github.com/python/cpython/blob/5c89adf385aaaca97c2ee9074f8b1fda0f57ad26/Lib/test/test_urllib.py#L1498-L1499

2024-12-10 00:47 UTC, barneygale commented
All this code smells funny and should be binned IMO:

https://github.com/python/cpython/blob/5c89adf385aaaca97c2ee9074f8b1fda0f57ad26/Lib/nturl2path.py#L28-L40

2024-12-10 01:12 UTC, samtstephens commented
Hi, thank you for the detailed response, I really appreciate it!! We will look into these changes and we'll see if we can come up with a better solution. I can definitely say we felt a bit out of our depth, not having a lot of in-depth knowledge with how the files _should_ look, so this background is appreciated.

2024-12-10 19:11 UTC, barneygale commented
You didn't pick the easiest issue to work on to be honest :sweat_smile: file URIs are a bit of a dark art...

2025-02-05 23:51 UTC, barneygale commented
Hey @samtstephens, is there anything I can do to help with this? Ta

2025-03-18 23:38 UTC, barneygale commented
Closing this PR as the bug has been fixed elsewhere. Thanks all the same for taking a look!

2025-03-18 23:38 UTC, closed without merging