lib/logging: Set handlers as set instead of list
python/cpython pull request #127826
Opened 2024-12-11 14:01 UTC by adityagesh

Handlers is currently initialized as empty list. The operation most per formed is __contains__. Set performs faster for this and ordering of handler is not a concern. Hence replace the list initialization with set.

2024-12-11 15:39 UTC, ZeroIntensity requested changes
Sorry, this is a breaking change. `handler` is documented as a list: https://docs.python.org/3/library/logging.html#logging.Logger.handlers

2024-12-11 17:50 UTC, vsajip commented
As pointed out, a breaking change.

> Set performs faster for this

Did you do any benchmarks with realistic scenarios? Even if a set is faster, how much difference does it really make? I'm minded to close this.

2024-12-11 18:29 UTC, ZeroIntensity commented
If it's a *really* significant speedup (which I doubt it is), then in theory we could deprecate `handlers` for a new attribute, and then just reflect changes to it for compatibility. I'm speculating though, and I'd definitely like to see some benchmarks before doing that.

2024-12-12 03:30 UTC, adityagesh commented
I don't have benchmark at the moment. I'll close this for now.

2024-12-12 03:30 UTC, closed without merging