itemgetter add dict example
python/cpython pull request #1280
Opened 2017-04-25 06:48 UTC by twz915

The document says that `operator.itemgetter` using the operand’s `__getitem__()` method. However, it is difficult to understand for a newbie.
One example is better than thousands of words.

2017-04-25 06:48 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-04-25 07:04 UTC, louisom requested changes

2017-04-25 07:04 UTC, lulouie commented on Doc/library/operator.rst
> +      >>> itemgetter('name')({'name': 'tu', 'age': 18})
I think this shouldn't put here, this code block is for explaining `Lists, tuples, and strings accept an index or a slice:`, not `Dictionaries accept any hashable value`.

If we want to add a new example for dictionaries, it should make a new code block above this one.

2017-04-25 10:05 UTC, serhiy-storchaka commented
I think existing words are enough for explaining `operator.itemgetter`. Open an issue on the bug tracker for discussion.

2017-04-25 10:55 UTC, bitdancer commented on Doc/library/operator.rst
> +      >>> itemgetter('name')({'name': 'tu', 'age': 18})
Actually, this makes the example exactly parallel the paragraph it follows, showing the dictionary example first, then the index, and then the slice, in the order they are mentioned in the text.  Breaking the paragraph up with the example would not improve the flow, in my opinion.  The fact that dictionary is in a separate sentence doesn't that much, I think.

2017-07-20 21:45 UTC, haypo commented
@twz915: Hi, would you mind to open a bug on bugs.python.org and sign the CLA please? Otherwise, we will be unable to accept your contribution and will have to close your PR :-(

2017-07-24 23:16 UTC, terryjreedy commented
I think that this qualifies at the upper edge of trivial, so that no issue or CLA is needed.
Brett, do we have a specific rule on number of characters or words?
That mean this is also at the upper edge of what does not need a Misc/ACK entry.

2017-07-24 23:18 UTC, terryjreedy approved these changes
I agree with Bitdancer that this fits nicely at the proposed location.  The itemgetter concept is not initially trivial and I think that this helps a bit.  If not for other opinions, I would merge it.

2017-07-25 00:24 UTC, twz915 commented
@terryjreedy That's why I added the snippet. I think it is a good example to help users to understand `itemgetter` and `list's List[x] or dict's Dict[x] behavior` better.

2017-07-25 00:31 UTC, twz915 commented
@haypo I don't think this is a bug, and add the example is just used to contribute a better understanding.

2017-07-25 00:42 UTC, terryjreedy commented
@twz915 Some people say 'bug' when they really mean 'issue'.  The issues on the site include enhancement requests and performance improvements.  The site could have been called 'issues/python/org' or 'tracker/python/org', but someone named it 'bugs/python/org'.

2017-07-25 00:57 UTC, terryjreedy commented
The other interpretation is that a 'bug' is a report of something that 'bugs' the person who opens the issue.  You were 'bugged' by the absence of a mapping example.  Once an issue is open, we carefully classify it as about (bad) behavior, enhancement, performance, security, or something else.

2017-07-25 01:22 UTC, haypo commented
Sorry, I requested an issue before reading the PR. I read your PR, I agree that no issue is required here.

2018-04-13 01:33 UTC, merged

2018-04-13 01:36 UTC, ned-deily commented
Since this is such a trivial change, I have merged it.  Thanks, @twz915, for your contribution.  Please fill out the [contributor form](https://www.python.org/psf/contrib/contrib-form/) for any future contributions.