gh-115514: Fix incomplete writes after close in asyncio._SelectorSocketTransport
python/cpython pull request #128037
Opened 2024-12-17 16:44 UTC by Tasssadar

Change introduced in gh-106503 cause the transport to miss writes scheduled after it is closed.

Issue: https://github.com/python/cpython/issues/115514

* Issue: gh-115514

2025-01-10 18:09 UTC, ZeroIntensity reviewed
Thanks for contributing! Some high-level triage comments, and then otherwise LGTM.

2025-01-10 18:09 UTC, ZeroIntensity commented on Misc/NEWS.d/next/Library/2024-12-17-16-48-02.gh-issue-115514.1yOJ7T.rst
> +Breaking change introduced in gh-106503, released in 3.12.0.
```suggestion
Fix exceptions and incomplete writes after :class:`!asyncio._SelectorTransport`
is closed before writes are completed.
```

2025-01-10 18:09 UTC, ZeroIntensity commented on Lib/test/test_asyncio/test_selector_events.py
> +        # If the transport is closed while:
```suggestion
        # gh-115514: If the transport is closed while:
```

2025-01-10 18:09 UTC, ZeroIntensity commented on Lib/asyncio/selector_events.py
> +        finally:
It's a good idea to add a comment explaining why we need this (and link the issue number as well).

2025-01-10 18:22 UTC, kumaraditya303 requested changes

2025-01-10 18:22 UTC, kumaraditya303 commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
handlers should not be run manually, please change test to not rely on it

Also I think this test should really be in ssl tests not here

2025-01-13 07:13 UTC, Tasssadar commented on Lib/asyncio/selector_events.py
> +        finally:
You mean the try/finally? It calls user-supplied callback internally, I'm just doing the same thing the parent `SelectorTransport` is: https://github.com/python/cpython/blob/d0ecbdd838034c1f061e9b4e9b54a900141458c3/Lib/asyncio/selector_events.py#L904-L916 

Do you think I should write a comment here about that?

2025-01-13 07:22 UTC, Tasssadar commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
Hi, could you please suggest on how to do that? The `TestLoop` used here does not process the writers when it is ran, so for example `self.loop.run_until_complete(asyncio.sleep(0))` does not work.

> Also I think this test should really be in ssl tests not here

I don't think so, this is behavior of the SocketTransport, SSL just happens to be the one prevalent user that relies on this behavior.

There already [happens to be a more real-world-like test in SSL](https://github.com/python/cpython/blob/8a433b683fecafe1cb04469a301df2b4618167d0/Lib/test/test_asyncio/test_ssl.py#L1310-L1432) that almost triggers the bad path here, but I would somehow have to make `socket.send` not consume the whole `data` to actually trigger this bug. IMHO its nicer to have the more artificial test here that is easier to understand and triggers the bugged path reliably.

2025-01-13 12:51 UTC, kumaraditya303 commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
> There already [happens to be a more real-world-like test in SSL](https://github.com/python/cpython/blob/8a433b683fecafe1cb04469a301df2b4618167d0/Lib/test/test_asyncio/test_ssl.py#L1310-L1432) that almost triggers the bad path here, but I would somehow have to make socket.send not consume the whole data to actually trigger this bug. IMHO its nicer to have the more artificial test here that is easier to understand and triggers the bugged path reliably.

You can use mock for `socket.send` to trigger the bug right? That would be a more realistic test than this one

2025-01-13 13:37 UTC, Tasssadar commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
I don't think so, the socket still needs to work because it sends data through it. I can shove this there however, artificially limit the socket buffer size which triggers the problem on my computer.

I'm not convinced this is really better, but I can do that in addition to/instead of the mock-based test.


```diff --git a/Lib/test/test_asyncio/test_ssl.py b/Lib/test/test_asyncio/test_ssl.py
index 125a6c35793..b694b4d38db 100644
--- a/Lib/test/test_asyncio/test_ssl.py
+++ b/Lib/test/test_asyncio/test_ssl.py
@@ -12,6 +12,7 @@
 import tempfile
 import threading
 import time
+import unittest.mock
 import weakref
 import unittest

@@ -1410,10 +1411,22 @@ async def client(addr):
             except (BrokenPipeError, ConnectionResetError):
                 pass

-            await future
+            socket_transport = writer.transport._ssl_protocol._transport

-            writer.close()
-            await self.wait_closed(writer)
+            def _shrink_sock_buffer(data):
+                if socket_transport._read_ready_cb is None:
+                    socket_transport._sock.setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF, 1)
+                return unittest.mock.DEFAULT
+
+            with unittest.mock.patch.object(
+                socket_transport, "write",
+                wraps=socket_transport.write,
+                side_effect=_shrink_sock_buffer
+            ):
+                await future
+
+                writer.close()
+                await self.wait_closed(writer)

         def run(meth):
             def wrapper(sock):
```

2025-01-17 18:55 UTC, kumaraditya303 commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
I think limiting the buffer with `SO_SNDBUF` makes sense, you can perhaps access the socket using `get_extra_info` method as well instead of private attrs.

2025-01-20 07:16 UTC, Tasssadar commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
Added in latest commit. Still kept the original mocked test I added - the interaction from `SSLProtocol` is really hard to track down, and this benefits from having a more straightforward illustration of what is expected from SocketTransport, even if it is all mocks.

2025-01-20 11:37 UTC, kumaraditya303 requested changes

2025-01-20 11:37 UTC, kumaraditya303 commented on Lib/test/test_asyncio/test_ssl.py
> +            # Make sure _SelectorSocketTransport enters the delayed write
You shouldn't modify existing tests, instead add a new one based on the previous one.

2025-01-20 12:07 UTC, Tasssadar commented on Lib/test/test_asyncio/test_ssl.py
> +            # Make sure _SelectorSocketTransport enters the delayed write
Right, done.

2025-01-27 12:54 UTC, Tasssadar commented
I have made the requested changes; please review again

2025-01-31 17:29 UTC, kumaraditya303 commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
The test isn't failing for me even if I remove your fix in ssl test

2025-01-31 23:26 UTC, Tasssadar commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
On what platform, and what exactly are you changing? On MacOS, with while on my branch, I only have to roll back the fix like this to make both new tests fail:
```diff
diff --git a/Lib/asyncio/selector_events.py b/Lib/asyncio/selector_events.py
index 22147451fa7..60bef420331 100644
--- a/Lib/asyncio/selector_events.py
+++ b/Lib/asyncio/selector_events.py
@@ -1188,7 +1188,7 @@ def _call_connection_lost(self, exc):
         try:
             super()._call_connection_lost(exc)
         finally:
-            self._write_ready = None
+            #self._write_ready = None
             if self._empty_waiter is not None:
                 self._empty_waiter.set_exception(
                     ConnectionError("Connection is closed by peer"))
@@ -1206,6 +1206,7 @@ def _reset_empty_waiter(self):

     def close(self):
         self._read_ready_cb = None
+        self._write_ready = None
         super().close()
```

2025-02-01 00:10 UTC, Tasssadar commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.writers[7]._run()
Okay, it's fixed now - problem was that on Linux, the minimum write buffer size is 1024, and it can only be set before the socket is connected anyway.

I switched it to use a wrapper class that fakes the full buffer by only writing half the data.

On linux, the ssl test was also not deterministic, it was not sending enough data and they actually got through before `close` call most of the time, so I doubled the size and now I can reliably trigger the bug with them on both Linux and MacOS.

2025-02-02 14:08 UTC, kumaraditya303 approved these changes

2025-02-02 15:11 UTC, merged

2025-03-06 18:24 UTC, aelamran commented
```
 Traceback (most recent call last):
  File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/client.py", line 616, in execute_command
    return await conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/client.py", line 589, in _send_command_parse_response
    await conn.send_command(*args)
  File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/connection.py", line 505, in send_command
    await self.send_packed_command(
  File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/connection.py", line 480, in send_packed_command
    self._writer.writelines(command)
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 349, in writelines
    self._transport.writelines(data)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1182, in writelines
    self._write_ready()
TypeError: 'NoneType' object is not callable 
```

was this fixed in python 3.12.9 ? I have the feeling I am still experiencing the issue in high concurrency scenario with redis client

2025-03-07 06:27 UTC, Tasssadar commented
Yes, this was fixed in 3.12.9. Your stack trace is different though, this looks like more like "writing after close" scenario rather than bug in Python.

2025-07-25 10:31 UTC, EsmeraldaYS commented
> ```
>  Traceback (most recent call last):
>   File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/client.py", line 616, in execute_command
>     return await conn.retry.call_with_retry(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
>     return await do()
>            ^^^^^^^^^^
>   File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/client.py", line 589, in _send_command_parse_response
>     await conn.send_command(*args)
>   File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/connection.py", line 505, in send_command
>     await self.send_packed_command(
>   File "/opt/venv/lib/python3.12/site-packages/redis/asyncio/connection.py", line 480, in send_packed_command
>     self._writer.writelines(command)
>   File "/usr/local/lib/python3.12/asyncio/streams.py", line 349, in writelines
>     self._transport.writelines(data)
>   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1182, in writelines
>     self._write_ready()
> TypeError: 'NoneType' object is not callable 
> ```
> 
> was this fixed in python 3.12.9 ? I have the feeling I am still experiencing the issue in high concurrency scenario with redis client这个问题在 python 3.12.9 中修复了吗？我感觉在使用 redis 客户端进行高并发场景时，这个问题仍然存在。

was this fixed

2025-07-25 13:14 UTC, ZeroIntensity commented
That would be https://github.com/redis/redis-py/issues/3546, not a CPython problem.