gh-109959: attempt to fix hypothesis tests for `test_glob`
python/cpython pull request #128255
Opened 2024-12-25 11:13 UTC by picnixz

Just trying to see if this approach would work or not. Tests are likely to be flaky but I want at least to isolate the failure if possible...

2024-12-26 09:16 UTC, picnixz commented
I've rerun lots of times the hypothesis workflow and didn't encounter issues but I really don't know if this is meaningful. @barneygale WDYT?

2024-12-28 21:59 UTC, barneygale commented
I know I speculated that this area of code could be related, but on reflection I think it's very unlikely. Given the behaviour Alyssa analysed, if this code were related, then _only_ a bug in `itertools.chain()` could explain it, and why would such a bug show up only here? I think the issue must elsewhere in `glob.py`.

2024-12-28 22:24 UTC, picnixz commented
What's also really weird is that I'm locally never seeing this failure. I don't know if this may be something related to the machine the hypothesis tests are actually running.

2025-01-11 00:33 UTC, picnixz commented
After Victor's investigation, it appears to be an OS issue itself. I'm going to close this one as I don't think I can come up with a good fix (though, is it possible to rerun it automatically if it failed, perhaps with a few exponential backoff strategy to avoid a busy host due to other tests running?)

2025-01-14 08:17 UTC, vstinner requested changes
The root issue is in the Linux kernel: https://github.com/python/cpython/issues/109959#issuecomment-2577524847

I don't think that changing iglob() is going to work around the issue.

2025-01-14 09:10 UTC, closed without merging

2025-01-14 09:10 UTC, picnixz commented
Ok so nothing I can do except skipping the test as we discussed on Discord. Closing in favor of https://github.com/python/cpython/pull/128812 then.