Trivial: Fix typo in Py_DECREF comment
python/cpython pull request #128387
Opened 2024-12-31 23:12 UTC by jkrejcha

`Py_DECREF`'s comment incorrectly references `_Py_IncRef` which isn't used by decref. Both functions don't accept NULL but only `_Py_DecRef` is relevant

```c
// Similar to Py_IncRef() and Py_DecRef() but the argument must be non-NULL.
// Private functions used by Py_INCREF() and Py_DECREF().
PyAPI_FUNC(void) _Py_IncRef(PyObject *);
PyAPI_FUNC(void) _Py_DecRef(PyObject *);
```

2025-01-01 16:14 UTC, StanFromIreland requested changes
Why change a comment that is wrong to one that is also wrong?

This is explained in a previous comment in the file:
`If it may be NULL, use Py_XINCREF/Py_XDECREF instead.`

I think this comment should be completely changed or removed.

2025-01-01 17:35 UTC, picnixz commented
The comment is more for internal purposes and implementation details explaining why we are using `_Py_DecRef` instead of `Py_DecRef` and for compatibility reasons.

The caller is not meant to pass `NULL` when using `Py_DECREF` at all, but the implementation may appear to allow it (at least until Python 3.10).

2025-01-02 00:27 UTC, jkrejcha commented
Indeed the compatibility reason appears to be the case. `Py_DecRef` (notably not `Py_DECREF`) appears to just be a thin wrapper around `Py_XDECREF`.

2025-02-08 11:39 UTC, picnixz approved these changes

2025-02-08 11:40 UTC, picnixz commented
@vstinner I plan to merge this one without a commit message and the title as the commit title.

If you however think it's not needed, we can also close this PR (strictly speaking, the comment is also correct but weird considering the implementation and was likely a C/C error).

2025-02-17 17:10 UTC, vstinner approved these changes
LGTM. I confirm that I made a stupid copy/paste mistake here.

2025-02-25 10:10 UTC, merged

2025-02-25 10:41 UTC, vstinner commented
I don't think that it's worth it to backport such change.