bpo-30202 : Update test.test_importlib.test_abc to test find_spec()
python/cpython pull request #12847
Opened 2019-04-15 19:02 UTC by nanjekyejoannah

I have added a test for find_spec() in test.test_importlib.test_abc and also made some other tests use find_spec instead of find_module().

I may have not looked at all possible areas to use find_spec(), so please let me know in the reviews for this PR.

2019-04-27 19:50 UTC, auvipy approved these changes

2019-05-29 00:34 UTC, nanjekyejoannah commented
ping @brettcannon for any thoughts on this PR.

2019-05-30 22:23 UTC, brettcannon commented
@nanjekyejoannah it's in my review queue, I just need to actually start clearing my review queue. 😉 I do promise to eventually get to this, I just can't promise when (but hopefully in the next week or two).

2019-05-31 00:43 UTC, nanjekyejoannah commented
@brettcannon got it :) , thanks!

2019-05-31 22:34 UTC, brettcannon requested changes
Overall looks good, but you inadvertently removed all tests of the `DeprecationWarning` for `find_module()`. 😄 Could you add an explicit test for that?

2019-05-31 22:34 UTC, brettcannon commented on Lib/test/test_importlib/test_abc.py
> +    def test_find_spec(self):
Is nearly mimics `test_spec` with the changes you made beyond passing an explicit target. Probably worth changing the names of both test methods to more clearly define what's being tested.

2019-06-06 17:31 UTC, nanjekyejoannah commented
I have made the requested changes; please review again.

2019-06-21 18:16 UTC, brettcannon approved these changes

2019-06-21 18:17 UTC, merged

2019-06-21 18:17 UTC, brettcannon commented
Thanks!

2019-06-21 20:07 UTC, nanjekyejoannah commented
@brettcannon, I can close the issue now I guess?

2019-06-21 23:01 UTC, brettcannon commented
@nanjekyejoannah I closed it. I usually do it the next time I go through my b.p.o notifications and see the commit message.