[3.6] bpo-29960 _random.Random corrupted on exception in setstate(). …
python/cpython pull request #1287
Opened 2017-04-26 02:35 UTC by Mariatta

…(GH-1019).

(cherry picked from commit 9616a82e7802241a4b74cf7ae38d43c37bf66e48)

2017-04-26 06:43 UTC, serhiy-storchaka requested changes

2017-04-26 06:43 UTC, serhiy-storchaka commented on Misc/NEWS
> +- bpo-29960: Preserve generator state when _random.Random.setstate()
Wrong section. Should be in 3.6.2 rather than 3.6.1.

2017-05-27 04:32 UTC, Mariatta commented on Misc/NEWS
> +- bpo-29960: Preserve generator state when _random.Random.setstate()
Thanks. Moved to 3.6.2

2017-05-27 05:13 UTC, serhiy-storchaka approved these changes

2017-05-27 14:20 UTC, merged