bpo-14817: add tests to extend_path
python/cpython pull request #12871
Opened 2019-04-18 03:14 UTC by Windsooon

Actually, there are some tests for extend_path already (see https://github.com/python/cpython/blob/master/Lib/test/test_pkgutil.py#L235). I add some tests for it anyway. However, I didn't test every line of the code in the extend_path function.

2019-05-01 09:57 UTC, auvipy approved these changes

2019-07-09 13:27 UTC, nanjekyejoannah commented
cc @ericvsmith

2023-02-05 18:40 UTC, arhadthedev commented
Would anybody mind to review and possibly merge this PR?

2023-03-20 21:46 UTC, furkanonder approved these changes

2023-04-09 17:26 UTC, arhadthedev commented
@vsajip, @brettcannon, could you review and possibly merge this PR, please? (as the ones who committed into `Lib/test/test_pkgutil.py` more than once last ten years and still active)

2023-04-12 18:29 UTC, brettcannon commented
I'm rather swamped right now, so it might be a while (especially since I want to deprecate the entire `pkgutil` module eventually 😁).

2023-06-09 22:28 UTC, brettcannon requested changes
The tests have some misleading names and they are not cleaning up after themselves appropriately.

2023-06-09 22:28 UTC, brettcannon commented on Lib/test/test_pkgutil.py
> +        # path should be list instead of string
Comments should be complete sentences.

2023-06-09 22:28 UTC, brettcannon commented on Lib/test/test_pkgutil.py
> +    def test_parent_package_raise_key_error(self):
```suggestion
    def test_parent_package_raises_key_error(self):
```

2023-06-09 22:28 UTC, brettcannon commented on Lib/test/test_pkgutil.py
> +    def test_parent_package_raise_key_error(self):
There's nothing here making sure `KeyError` is raised, so the name of the test is confusing.

2023-06-09 22:28 UTC, brettcannon commented on Lib/test/test_pkgutil.py
> +    def test_parent_package_raise_attr_error(self):
The name doesn't match what seems to be tested.

2023-06-09 22:28 UTC, brettcannon commented on Lib/test/test_pkgutil.py
> +        self.dirname = tempfile.mkdtemp()
There's no cleanup of the temporary directory.

2023-06-09 22:28 UTC, brettcannon commented on Lib/test/test_pkgutil.py
> +        f.close()
Use a context manager and write a comment in the file as to the purpose of the file existing.

2023-06-09 22:28 UTC, brettcannon commented on Lib/test/test_pkgutil.py
> +        import foo
This will leave `sys.modules` dirty from this test. Use the helper functions in `test.support` to make sure this method cleans up after itself.

2024-05-18 21:14 UTC, nineteendo commented
Do we close this or do we remove the pending label? It's been almost 100 days.

2024-05-19 22:53 UTC, ericvsmith commented
Closing due to inactivity.

2024-05-19 22:53 UTC, closed without merging