[3.5] bpo-29960 _random.Random corrupted on exception in setstate(). …
python/cpython pull request #1288
Opened 2017-04-26 02:38 UTC by Mariatta

…(GH-1019).

(cherry picked from commit 9616a82e7802241a4b74cf7ae38d43c37bf66e48)

2017-04-26 04:04 UTC, serhiy-storchaka requested changes

2017-04-26 04:04 UTC, serhiy-storchaka commented on Modules/_randommodule.c
> +    uint32_t new_state[N];
Use `PY_UINT32_T` rather than `uint32_t`.

2017-04-26 04:04 UTC, serhiy-storchaka commented on Modules/_randommodule.c
> +        new_state[i] = (uint32_t)element;
Use `PY_UINT32_T` rather than `uint32_t`.

2017-05-27 04:47 UTC, Mariatta commented on Modules/_randommodule.c
> +    uint32_t new_state[N];
Updated.

2017-05-27 05:16 UTC, serhiy-storchaka approved these changes

2017-05-27 14:19 UTC, merged