[2.7] bpo-29960 _random.Random corrupted on exception in setstate(). …
python/cpython pull request #1289
Opened 2017-04-26 02:40 UTC by Mariatta

…(GH-1019).

(cherry picked from commit 9616a82e7802241a4b74cf7ae38d43c37bf66e48)

2017-04-26 02:42 UTC, Mariatta commented
@serhiy-storchaka Can you please check if I backported this correctly? There was a conflict in _randommodule.c which I have to resolve manually. Just making sure if everything is still in order.
Thanks :)

2017-04-26 03:54 UTC, serhiy-storchaka requested changes

2017-04-26 03:54 UTC, serhiy-storchaka commented on Modules/_randommodule.c
> +    uint32_t new_state[N];
`uint32_t` is C99. Use `unsigned long` instead.

2017-04-26 03:54 UTC, serhiy-storchaka commented on Modules/_randommodule.c
> +        new_state[i] = (uint32_t)element;
Leave the 2.7 code at the right hand of assignment.

2017-05-13 20:15 UTC, serhiy-storchaka commented
Why you have removed the `cherry-pick for 2.7` label @brettcannon?

2017-05-13 20:30 UTC, brettcannon commented
@serhiy-storchaka there's an email to python-committers about it, but the label was removed from GitHub entirely so I didn't specifically remove it  just for this PR.

2017-05-27 05:05 UTC, Mariatta commented on Modules/_randommodule.c
> +    uint32_t new_state[N];
Thanks, changed to `unsigned long`.

2017-05-27 05:05 UTC, Mariatta commented on Modules/_randommodule.c
> +        new_state[i] = (uint32_t)element;
Changed.

2017-05-27 05:18 UTC, serhiy-storchaka approved these changes

2017-05-27 14:19 UTC, merged