bpo-30166: Import command-line parsing modules only when needed.
python/cpython pull request #1293
Opened 2017-04-26 08:36 UTC by serhiy-storchaka

2017-04-26 08:42 UTC, berkerpeksag approved these changes
I'm not familiar with IDLE, but rest of the PR looks good to me. Just left a comment about code styling.

Thanks!

2017-04-26 08:42 UTC, berkerpeksag commented on Lib/code.py
> +    import argparse
Style nit: You may want to add a new line after `import argparse` like the other cases.

2017-04-26 09:09 UTC, serhiy-storchaka commented on Lib/code.py
> +    import argparse
This is a thing that compelled me to hesitate. Some usages of argparse have an empty line after imports, some doesn't have (and the majority doesn't have). I added a new line if the following code is large or separated on sections by empty lines, and didn't add it if the following code is short and dense, as in this case.

2017-04-26 09:10 UTC, serhiy-storchaka commented
I left reviewing IDLE on @terryjreedy.

2017-04-27 02:51 UTC, terryjreedy requested changes
Moving imports not needed in the main body is consistent with what I did in Fall 2015.  It is also how I introduced a bug.  So I checked that os can be moved in profile.py and verified the changes in idlelib/pyshell.py.  (They will be helpful if I ever move main() to a different module.)  The one requested change is obviously not crucial.

2017-04-27 02:51 UTC, terryjreedy commented on Lib/idlelib/pyshell.py
> +import idlelib
Move this also to __main__.  'idlelib' by itself is never used in main body of module.

2017-04-27 02:51 UTC, terryjreedy commented on Lib/profile.py
> -import os
def trace_dispatch (line 184 in 3.6.1) is preceded by an apparently out-of-date comment
    # Heavily optimized dispatch routine for os.times() timer
That os.times is no longer used is why the os import can be moved.
self.timer is now  time.process time

2017-05-04 05:17 UTC, merged

2017-05-04 06:12 UTC, terryjreedy commented
I will backport the idlelib.pyshell part

2017-07-25 08:56 UTC, ibanezz1999 reviewed
Bahasa indonesia

2017-07-25 17:55 UTC, terryjreedy commented
@ibanezz1999 Please explain your comment.  This was merged months ago and any additional changes will be a new patch.