bpo-24758: Improve the error msg for unittest.mock.Mock()'s unsafe mode
python/cpython pull request #12991
Opened 2019-04-28 05:59 UTC by ZackerySpytz

2019-04-28 06:41 UTC, tirkarthi commented on Lib/unittest/mock.py
> +                raise AttributeError("Attributes cannot start with 'assert'")
`startswith` checks both "assert" and "assret" so hardcoding "assert" might lead to confusing error message when the attribute starts with assret instead. Perhaps change this to "Attributes cannot start with 'assert' or 'assret'" ?

```
./python.exe
Python 3.8.0a3+ (heads/master:55d035113d, Apr 28 2019, 01:37:48)
[Clang 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest import mock
>>> mock.Mock().assret_mock_call
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karthikeyansingaravelan/stuff/python/cpython/Lib/unittest/mock.py", line 598, in __getattr__
    raise AttributeError("Attributes cannot start with 'assert'")
AttributeError: Attributes cannot start with 'assert'
```

2019-05-06 14:49 UTC, kushaldas requested changes
`"Attributes cannot start with 'assert' or 'assret'"` is a better error message in this. Also, please check for the right error message in `test_mock_unsafe` as we are checking the assertion there.

2019-05-06 16:31 UTC, ZackerySpytz commented
Thank you, @kushaldas.

I have made the requested changes; please review again.

2019-05-06 16:36 UTC, tirkarthi approved these changes
LGTM. The attribute can start with assert or assret in unsafe mode but adding it to error message looks intrusive to me and this seems like a good improvement.

Thank you for the PR.

2019-05-08 17:32 UTC, kushaldas approved these changes
This looks good now, thank you for the PR. Approved.

2019-05-08 17:32 UTC, merged