remove duplicate definition from pickletools
python/cpython pull request #1301
Opened 2017-04-26 14:42 UTC by JelleZijlstra

There's another almost identical definition of bytes1 above this one.

The only difference is a minor one in the docstring: the first one has
"the number of bytes in the string" and the second one has just "the
number of bytes". I like the first wording better so I kept it.

2017-04-26 14:44 UTC, JelleZijlstra commented
I think this qualifies as "trivial" but I don't have the rights to add that label.

2017-04-26 15:39 UTC, berkerpeksag commented
Unfortunately, this is a code cleanup so we at least need to ping pickle maintainers on bugs.p.o. Sometimes there might be a valid or historical reason for this kind of code duplication.

2017-04-26 15:49 UTC, JelleZijlstra commented
OK, I'll open an issue.

2017-04-26 15:51 UTC, tim-one commented
I'm the original pickletools author, and the change looks good to me.  The "bytes" type didn't exist at the time, so this code was added later.   The current duplication obviously serves no purpose, and was certainly a mistake.  I don't understand how the new git workflow works yet else I'd do something tangible to get this patch applied ;-)

2017-04-26 16:34 UTC, serhiy-storchaka requested changes
The variant without " in the string" is more correct and consistent with bytes4 and bytes8.

2017-04-27 16:03 UTC, serhiy-storchaka approved these changes

2017-04-27 16:05 UTC, merged