BPO-34861: better cProfile CLI defaults: sort by time, restrict to top 20
python/cpython pull request #13083
Opened 2019-05-04 18:07 UTC by andreasvc

adds option -n to restrict to top n lines (defaults to 20 for CLI)
set default of -s to sort by time (instead of unsorted)
"python3 -m cProfile foo.py" directly usable.

2019-05-04 18:07 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-06-10 12:18 UTC, mangrisano reviewed
Hi, thank you for the pull request and for the patience. I've left a couple of comments about the changes.
Just a question: did yo test it? If didn't, please provide it. Thank you. 
Furthermore, the Doc and perhaps the docstring should be improved adding the parameter and explaining what it does.

I'm not a core-dev, so feel free to don't follow my tips.

2019-06-10 12:18 UTC, mangrisano commented on Lib/cProfile.py
> +        numresults=None):
Please, indent `numresults` under `statement`.

2019-06-10 12:18 UTC, mangrisano commented on Lib/cProfile.py
> +                options.numresults)
Please, indent `options.numresults` under `code`.

2019-06-10 12:18 UTC, mangrisano commented on Lib/profile.py
> +        numresults=None):
The same for this row. :)

2019-06-10 12:18 UTC, mangrisano commented on Lib/profile.py
> +                options.numresults)
Indent `options.numresults` under `code`.

2022-07-17 21:31 UTC, hauntsaninja reviewed
Note that #31929 made the default sort order cumtime. Any interest in merging main and picking this back up?

2023-02-09 07:59 UTC, hauntsaninja requested changes
Requesting changes as per above

2026-05-03 16:55 UTC, StanFromIreland commented
Hello! I'm sorry but I'm closing this PR as it is stale, has requested changes, and has not signed the CLA.

2026-05-03 16:55 UTC, closed without merging