bpo-20092. Use __index__ in constructors of int, float and complex.
python/cpython pull request #13108
Opened 2019-05-06 14:30 UTC by serhiy-storchaka

Constructors of `int`, `float` and `complex` will now fall back to `__index__` if corresponding special methods `__int__`, `__float__` and `__complex__` are not defined.

2019-05-06 15:02 UTC, remilapeyre commented
I'm not sure `PyLong_AsDouble` will always raise an exception for the conversion from `int` to `float` like Steven D'Aprano showed in https://mail.python.org/pipermail/python-dev/2019-March/156687.html.

Here the example given by Steven D'Aprano:

```
>>> class Test:
...     def __index__(self):
...             return 2**64 + 1
... 
>>> 2**64 + 1 == int(float(Test()))
False
```

2019-05-07 11:11 UTC, serhiy-storchaka commented
Yes, converting integers to float is not always reversible.
```
>>> 2**64 + 1 == int(float(2**64 + 1))
False
```
This is expected behavior.

2019-05-16 14:54 UTC, jdemeyer commented
For `__index__`, I prefer the idea of #13106: that will work in all cases where `__int__` is used, not only in those 4 particular constructors.

2019-05-31 08:49 UTC, serhiy-storchaka commented
The only cases where `__int__` is used are those particular constructors.

2019-06-01 19:02 UTC, mdickinson commented on Doc/library/functions.rst
> +   it returns ``x.__index__()``.  If *x* defines :meth:`__trunc__`,
There's some question about what the right order should be here, but I agree that it makes sense to try `__index__` before `__trunc__` here.

2019-06-01 19:09 UTC, mdickinson commented on Objects/floatobject.c
> +                return -1;
Super-nitpick: I'd prefer `return -1.0;` (leaving the return-type conversion implicit feels odd to me), but I see that we're returning plain-old `1` in the other branch, so I guess this is fine.

2019-06-01 19:13 UTC, mdickinson approved these changes
LGTM: code looks good, and I agree that this is a desirable change.

The one fly in the ointment is that `index` can return something that's not an exact int, which means that there's now another code-path by which `int` can return something that's not of exact type `int`. 

```
>>> class A:
...     def __index__(self): return True
... 
>>> int(A())
<stdin>:1: DeprecationWarning: __index__ returned non-int (type bool).  The ability to return an instance of a strict subclass of int is deprecated, and may be removed in a future version of Python.
1
```

I'd love to finally turn that `DeprecationWarning` into an error, but fear we've run out of time for that for 3.8, and we may want to wait for 3.9 anyway to make sure that everyone's had a chance to react to that warning. (Do you remember which version it got introduced in?)

2019-06-01 19:14 UTC, mdickinson commented
Ah, sorry; apparently we _are_ converting to exact int already. (Yay!)

2019-06-01 19:26 UTC, mdickinson commented
Hmm: bug found during manual testing:
```
ython 3.8.0a4+ (remotes/serhiy-storchaka/convert-index-to-number:5f980e9716, Jun  1 2019, 19:59:) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class A:
...     def __index__(self): return 2**1024
... 
>>> float(A())
OverflowError: int too large to convert to float

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'float'> returned a result with an error set
```

2019-06-01 19:35 UTC, mdickinson commented on Objects/abstract.c
> +        double val = PyLong_AsDouble(res);
Missing an error check here.

2019-06-01 19:36 UTC, mdickinson requested changes
Updating my approval to "request changes": there's a missing error check in `PyNumber_Float`.

2019-06-01 20:28 UTC, mdickinson approved these changes

2019-06-01 21:05 UTC, merged