bpo-34682: Wording and grammatical changes to the doc(https://docs.python.org/3)
python/cpython pull request #13120
Opened 2019-05-06 17:32 UTC by divyag9

2019-05-06 17:32 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-05-06 17:57 UTC, ericvsmith requested changes
Other than my comments, this looks good. Thanks!

2019-05-06 17:57 UTC, ericvsmith commented on Doc/reference/expressions.rst
> -   executed yield expression.  When a generator function is resumed with a
I think the original "a" is correct here, although I realize there's some wiggle room.

2019-05-06 17:57 UTC, ericvsmith commented on Doc/reference/expressions.rst
> +is y`` is true if and only if *x* and *y* are the same object.  Object's identity
And same here: "An object's identity ..."

2019-05-06 17:57 UTC, ericvsmith commented on Doc/reference/expressions.rst
> +The operators :keyword:`is` and :keyword:`is not` test for object's identity: ``x
I would make this "test for an object's identity" (adding "an").

2019-05-06 18:10 UTC, divyag9 commented
I have made the requested changes; please review again

2019-05-06 18:13 UTC, ericvsmith approved these changes
Looks good. Thanks!

2019-05-13 13:05 UTC, merged

2019-05-13 13:05 UTC, miss-islington commented
Thanks @divyag9 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-05-13 13:09 UTC, csabella commented
@divyag9 Congratulations on getting your PR merged!  :tada: :tada:

2019-05-14 02:33 UTC, divyag9 commented
> @divyag9 Congratulations on getting your PR merged! 🎉 🎉

Thanks Cheryl! Thanks for all your help