Makefile: fix Issue36464 (parallel build race problem)
python/cpython pull request #13186
Opened 2019-05-08 09:01 UTC by sandy-lcq

This issue reproduces on python2 and python3

When using make -j with the 'install' target, it's possible for altbininstall
(which normally creates BINDIR) and libainstall (which doesn't, though it
installs python-config there) to race, resulting in a failure due to
attempting to install python-config into a nonexistent BINDIR. Ensure it also
exists in the libainstall target.

Signed-off-by: Changqing Li <changqing.li@windriver.com>

2019-05-08 09:01 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-05-08 09:18 UTC, sandy-lcq commented
I have signed the CLA, and receive the confirm mail,  I don't know why CLA still not recognized.

2019-05-31 16:28 UTC, auvipy requested changes
try to fix the builds

2019-11-21 21:40 UTC, rossburton commented
The build failure logs are no longer available.  Can the CI be made to run again?

2020-05-29 09:59 UTC, csabella commented
Closing and reopening to rerun the builds.

2021-05-16 23:57 UTC, iritkatriel commented
This was fixed in https://bugs.python.org/issue16866

2021-05-16 23:57 UTC, closed without merging