bpo-12800: 'tarfile.StreamError: seeking backwards is not allowed' when extract symlink
python/cpython pull request #13217
Opened 2019-05-09 09:55 UTC by websurfer5

Extracting a symlink from a tarball using the tarfile
module in stream mode ('r|') fails with an exception when a file
or symlink of the same name already exists. The fix is to remove
the existing file or symlink before extraction. Tests are included.

2019-05-13 13:13 UTC, auvipy approved these changes

2020-05-13 15:17 UTC, catlee commented
Is there a way I can help get this landed? I just ran into this today and wasted a lot of time trying to figure out why my tar file opened in streaming mode was trying to seek backwards.

2020-05-17 14:03 UTC, JulienPalard requested changes
The idea of removing the file / symlink before creating the symlink looks good to me, GNU tar behave the same way.

Please note that GNU tar also removes an empty directory if it exists (but keeps a non-empty directory, and give an error), we may want to copy this too?

2020-05-17 14:03 UTC, JulienPalard commented on Lib/test/test_tarfile.py
> +        tmpdir = support.temp_cwd('overwrite_symlink')
temp_cwd is a context manager, please use it in a with statement (also you're not using the variable at all which is strange).

2020-05-17 14:03 UTC, JulienPalard commented on Lib/test/test_tarfile.py
> +                pass
If using a temporary directory for your test (temp_cwd in a context manager for example), you should not need this at all.

2020-06-19 02:16 UTC, catlee commented
I've submitted a new PR with the suggested changes: https://github.com/python/cpython/pull/20972

I have made the requested changes; please review again.

2020-09-19 15:46 UTC, taleinat commented
Thanks for the PR, @websurfer5, but I'm closing this in favor of PR GH-21409, which restores the original fix for this issue which was lost in a bad merge.

2020-09-19 15:46 UTC, closed without merging