bpo-36865: allow 'rt' mode in FileInput
python/cpython pull request #13221
Opened 2019-05-09 17:23 UTC by natgaertner

The FileInput class (https://github.com/python/cpython/blob/master/Lib/fileinput.py) delegates to the open function, gzip, or bz2. Each of these delegates supports the 'rt' mode flag, so FileInput can probably support it as well.

This might clear up some confusion as in https://bugs.python.org/issue5758, which, in accordance with the FileInput docs, assumes all files opened with the 'r' flag will be opened in text mode. For gzip and bz2 this is not the case, they will be opened in binary 'rb' mode.

This pull request adds the 'rt' mode to the allowed modes, expands the unit test for FileInput to test opening with all allowed modes, and makes the documentation in FileInput about the behavior of the 'r' flag more accurate.

2019-05-09 17:23 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-05-31 16:31 UTC, auvipy requested changes
please re base

2019-06-06 16:36 UTC, natgaertner commented
@auvipy I rebased, but that appears to have made it so I can't see your suggested changes? I apologize, I may have misunderstood the github workflow for rebasing pull requests. Would it be possible to make your suggestions again? Sorry for the hassle.

2021-04-08 01:35 UTC, methane commented
As I said in b.p.o., we should open compressed files for "r" mode.
So no need to add 't' mode.

2021-04-08 01:35 UTC, closed without merging