bpo-27805: Allow opening /dev/std{out,err} in append mode
python/cpython pull request #13254
Opened 2019-05-11 21:50 UTC by ZackerySpytz

For example, `open('/dev/stdout', 'a')` will no longer raise an `OSError`.

2019-05-13 13:11 UTC, auvipy approved these changes

2019-09-27 03:39 UTC, benjaminp commented on Modules/_io/fileio.c
>          PyObject *pos = portable_lseek(self, NULL, 2);
Wouldn't it be simpler to check for `ESPIPE` in `portable_lseek`. (Perhaps you need to add a parameter?)

2019-10-05 00:27 UTC, benjaminp requested changes
(dropping from my queue because of my question)

2019-11-12 22:52 UTC, benjaminp commented
Closing because GH-17112 was merged instead. Thank you for the PR, though.

2019-11-12 22:52 UTC, closed without merging