Remove workaround for defaults in namedtuple now that we have the defaults parameter
python/cpython pull request #13263
Opened 2019-05-12 12:55 UTC by andresdelfino

The intention is to prevent the previous more verbose style now that a more fitting solution has been implemented.

2019-05-20 16:58 UTC, remilapeyre approved these changes
Thanks !

2019-05-20 21:40 UTC, csabella requested changes
Can you also remove one of the blank lines so that only one is left?  Thanks.

2019-05-20 21:42 UTC, csabella commented
Although I can see some value in leaving this example (that is, the creation of a Factory namedtuple), the intent of the example was to show the use of defaults, so I agree it should be removed.

2019-05-20 23:37 UTC, andresdelfino commented
> Can you also remove one of the blank lines so that only one is left? Thanks.

Sure, sorry about that.

2019-05-20 23:37 UTC, andresdelfino commented
I have made the requested changes; please review again

2019-05-21 00:51 UTC, csabella approved these changes

2019-05-21 00:52 UTC, merged

2019-05-21 00:53 UTC, csabella commented
@andresdelfino Thank you for the contribution.  I'm going to just apply this to 3.8 and leave the example in for 3.7 when `defaults` was added.