bpo-36927: Update the docstring of the traceback.format_tb() function.
python/cpython pull request #13359
Opened 2019-05-16 13:36 UTC by mangrisano

The request of the issue-36927 regards of making more verbiage the docstring of traceback.format_tb() because actually isn't clear which values the function returns.

https://bugs.python.org/issue36927

2019-05-16 16:30 UTC, Carreau commented
I'm not a core-dev, but it looks like you have many intermediate commits that are unrelated and don't appear in the final diff. 

You may want to consider an interactive rebase or a cherry-pick ?

2019-05-16 17:52 UTC, mangrisano commented
You're right. I'm trying to figure it out.

2019-05-16 18:48 UTC, Carreau commented
```
git rebase -i origin/master
... delete all the commits you don't want (dd in vim)
... esc :wq # to save and quit
git push # maybe with --force
```
![xx](https://user-images.githubusercontent.com/335567/57879098-83d22100-77d0-11e9-9e81-dec43573214e.gif)

2019-05-16 18:53 UTC, mangrisano commented
> ```
> git rebase -i origin/master
> ... delete all the commits you don't want (dd in vim)
> ... esc :wq # to save and quit
> git push # maybe with --force
> ```
> 
> 
> ![xx](https://user-images.githubusercontent.com/335567/57879098-83d22100-77d0-11e9-9e81-dec43573214e.gif)

Is it ok now?

2019-05-16 19:04 UTC, Carreau commented
You did force-push, but you don't appear to have removed the intermediate commits.

2019-05-16 19:08 UTC, mangrisano commented
If I run `git rebase -i origin/master` in my local branch, I have only the last commit, the good one. What am I suppose to do? Thank you for your support.

2019-05-16 19:11 UTC, Carreau commented
Hum that is weird. 

what about `git rebase -i bfba8c373e362d48d4ee0e0cf55b8d9c169344ae` ?

2019-05-16 19:16 UTC, mangrisano commented
With your last command I had the same your output with all the commits that I have to remove. I removed them, I pushed and I think nothing is changed :D Do you confirm that?

2019-05-16 19:21 UTC, Carreau commented
Fine now, I only see one commit on github. Maybe the UI took some time to react and your first try worked:-)

2019-05-16 19:21 UTC, Carreau commented
Good job ! Rebase are not easy in git !

2019-05-16 19:26 UTC, mangrisano commented
Good job to you. I've just follow your suggestions to fix it.
Now I have a question: Do I need to do a rebase and remove unnecessary commits everytime I push something?

2019-05-16 19:34 UTC, Carreau commented
> Do I need to do a rebase and remove unnecessary commits everytime I push something?

Not always; it is a question of keeping history clean from unrelated changes, also depends on the projects. Here you had a small change and it had something like ~16 commits including many merges. 

Before you rebase the history was looking like so (trimming down the commit descriptions): 

```
* 3906e54b52 (HEAD, origin/pr/13359) Update the docstring of traceback.format_tb() function
*   3c9eb15eb6 Merge branch 'master' of https://github.com/mangrisano/cpython
|\
| * 4a919297d0 Remove _config.yml
| *   9d0c78f1aa Merge branch 'master' of https://github.com/mangrisano/cpython
| |\
| | *   125278d038 Merge branch 'master' of https://github.com/mangrisano/cpython
| | |\
| | | *   a0c7d7ae4c Merge branch 'master' of https://github.com/mangrisano/cpython
| | | |\
| | | | *   a2e57a412e Merge branch 'master' of https://github.com/mangrisano/cpython
| | | | |\
| | | | | *   2cb757f795 Merge branch 'master' of https://github.com/mangrisano/cpython
| | | | | |\
| | | | | | * 671a258845 Set theme jekyll-theme-hacker
| | | | | * | ee138b9c60 Set theme jekyll-theme-hacker
| | | | * | | 2d31dcd8d3 Set theme jekyll-theme-hacker
| | | * | | | 86f1df8917 Set theme jekyll-theme-hacker
| | * | | | | 81654a8472 Set theme jekyll-theme-hacker
| * | | | | | 1b2dd326de Set theme jekyll-theme-hacker
| |/ / / / /
* | | | | | 836b366a53 Remove _config.yml
* | | | | | ec56a762ee Set theme jekyll-theme-hacker
|/ / / / /
* | | | | bfba8c373e bpo-36748: optimize TextIOWrapper.write() for ASCII string (GH-13002)
```

and now
```
* commit 5a087031bad323a3c8a8bffbac2ae8052c47ea6a (HEAD, origin/pr/13359)
| Author: Michele Angrisano <michele.angrisano@gmail.com>
| Date:   Thu May 16 20:49:12 2019 +0200
|
|     Update the docstring of traceback.format_tb() function
|
* commit bfba8c373e362d48d4ee0e0cf55b8d9c169344ae
| Author: Inada Naoki <songofacandy@gmail.com>
| Date:   Thu May 16 15:03:20 2019 +0900
|
|     bpo-36748: optimize TextIOWrapper.write() for ASCII string (GH-13002)
|
```

Looks nicer right ?

2019-05-16 19:41 UTC, mangrisano commented
Now looks great. Thank you.
PS: Which command did your run to obtain that output? git log?

2019-05-16 20:15 UTC, Carreau commented
`git log --graph`, and the first one with the extra `--oneline` option

2019-05-16 20:24 UTC, mangrisano commented
If I run `git log --graph` in the branch I obtain the same your last output. If I run it in the master, I obtain the first one, with all that useless commits. This suggests to me that the next time I will have the same problem, isn't it?

2019-05-16 20:32 UTC, Carreau commented
You might; it depends on how you work. Usually to submit a patch I'll create a branch, `reset --hard origin/master`, and work from there. 

`reset --hard`  is a bit dangerous as it is one of the rare operation in git that can't be undone – or at least relatively difficult to undo. Anyway do not worry about that for now; it will make sens at some point.

2019-05-16 20:49 UTC, mangrisano commented
Ok. Thanks a lot again for supporting me step by step. I've really appreciated it.

2019-05-17 19:55 UTC, Carreau approved these changes

2019-06-13 19:38 UTC, ezio-melotti commented
I think it would be better to explain what the function does first, then mention the equivalent snippet.
There are also 3 other function with an unhelpful documentation like `format_tb()`: `format_stack`,`print_exc`, `print_last`.  I think those should be fixed as well.

2019-06-23 11:59 UTC, mangrisano commented
I have made the requested changes; please review again.

2019-09-01 11:14 UTC, mangrisano commented
/cc @ezio-melotti

2021-01-15 20:04 UTC, iritkatriel requested changes
I don't think it's a good idea to copy-paste paragraphs of documentation, for the same reasons that we don't copy-paste code.  "A is a shorthard for B" is both precise and concise, and sends you straight to where the information you are looking for can be found.

Furthermore, the bpo issue was about docstrings and not the rst file (I think it's a bad idea for the docstrings as well, but even more so for the online documentation, which people might want to read through).

2022-07-08 13:26 UTC, iritkatriel commented
Closing as there was no followup to my change request.

2022-07-08 13:26 UTC, closed without merging