bpo-18911: using xmlcharrefreplace when open a file
python/cpython pull request #13352
Opened 2019-05-16 03:11 UTC by Windsooon

See https://bugs.python.org/issue18911

2019-05-31 10:43 UTC, auvipy approved these changes

2019-05-31 10:59 UTC, scoder requested changes
We should not recommend using the replacement method. See my comment in the ticket.

2019-06-01 03:52 UTC, Windsooon commented
@scoder I updated the PR base on your review and suggestions.

2019-06-01 06:31 UTC, scoder approved these changes

2019-06-01 06:33 UTC, merged

2019-06-01 06:38 UTC, miss-islington commented
Thanks @Windsooon for the PR, and @scoder for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-06-01 06:38 UTC, miss-islington commented
I'm having trouble backporting to `3.7`. Reason: '`Error 110 while writing to socket. Connection timed out.`'. Please retry by removing and re-adding the `needs backport to 3.7` label.

2019-06-01 06:39 UTC, miss-islington commented
Thanks @Windsooon for the PR, and @scoder for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-06-01 06:59 UTC, scoder commented
Thanks @Windsooon!