bpo-36770: add feature for shutil.make_archive
python/cpython pull request #13447
Opened 2019-05-20 16:26 UTC by OwenChia

https://bugs.python.org/issue36770

Add support for different ZIP compression method.

if you just want to use different zip compression method, no need to rewrite entire _make_zipfile function.

e.g.
```python
>>> shutil.make_archive('archive', 'zip_lzma', '/path/to/whatever')
```

2019-05-20 16:26 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-05-21 06:45 UTC, matrixise requested changes
Thank you for your contribution,
Please, could you check the blurb entry?

2019-05-21 06:45 UTC, matrixise commented on Misc/NEWS.d/next/Library/2019-05-20-17-01-31.bpo-36770.SanQsw.rst
> +Add support for different ZIP compression method in shutil.make_archive.
Use the ReST roles, example :+1: 
```
Add support for different ZIP compression methods in :func:`shutil.make_archive`
```

2019-05-22 08:47 UTC, OwenChia commented
I have made the requested changes; please review again.

Also, I use `git push --force` to update, am I doing it right?

2020-03-05 15:09 UTC, akuchling requested changes
I think the code changes look fine; they're very tidily done, and will report a ValueError when a bad value of 'compress' is provided. Thanks!

The missing pieces are:

*  the tests in `Lib/test/test_shutil.py` don't exercise the new functionality. It looks like the tests currently invoke each of the differently-compressed tar file formats, so it should try each of the zipfile formats as well.

* The docstring for make_archive() isn't updated by the patch to list the new possible values, and neither is the documentation of the function in `Doc/library/shutil.rst`.

2025-04-07 10:29 UTC, closed without merging