bpo-37004: Documented asymmetry of string arguments in difflib.SequenceMatcher for ratio method
python/cpython pull request #13482
Opened 2019-05-22 02:21 UTC by sweeneyde

2019-05-22 02:21 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-05-22 03:03 UTC, tim-one requested changes
I like the idea!  But want some changes, as spelled out in comments.  Thanks!

2019-05-22 03:03 UTC, tim-one commented on Doc/library/difflib.rst
> +         respect to the order of the arguments. For instance::
No need to scream "not", and more accurate to say it may not be symmetric.  But rather than the high-falutin' "symmetric", I'd prefer plain language.  So, e.g.,

> Caution: The result of a :meth:`ratio` call may depend on the order of the arguments.  For instance::

2019-05-22 03:03 UTC, tim-one commented on Doc/library/difflib.rst
> +            0.4444444444444444
Long floating-point values distract from the point.  Suggest using the words "diet" and "tide" instead.  With "diet" first, the ratio is 0.5; with "tide" first, it's 0.25.

2019-05-22 03:14 UTC, sweeneyde commented
I have made the requested changes; please review again.

2019-05-22 03:36 UTC, tim-one approved these changes

2019-05-22 04:22 UTC, tirkarthi commented on Doc/library/difflib.rst
> +
```suggestion

```

Please remove the trailing space in this line causing CI error.

2019-08-07 01:21 UTC, sweeneyde commented
What is the process for getting this PR merged?

2019-08-07 02:46 UTC, tim-one commented
Thanks for speaking up!  While the change is fine by me, I'm not familiar enough with current workflow to finish it.  So I just posted a message to the python-dev mailing list, asking for someone else to proceed:

https://mail.python.org/archives/list/python-dev@python.org/thread/TFTQCJ7IZNCE3XUWEC4IVHPXBDZIKVEI/

I bet they'll ask that you add your name to the `Misc/ACKS` file.

2019-08-07 04:37 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Base branch was modified. Review and try the merge again.`.

2019-08-07 04:37 UTC, merged

2019-08-07 04:37 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Base branch was modified. Review and try the merge again.`.

2019-08-07 04:37 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Base branch was modified. Review and try the merge again.`.

2019-08-07 04:37 UTC, miss-islington commented
Thanks @sweeneyde for the PR 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7, 3.8.
🐍🍒⛏🤖

2019-08-07 15:42 UTC, terryjreedy commented
@tim-one The backports have to be 1. approved by a coredev, after briefly checking that done correctly, in which case the bot will merge if and when CI passes, or 2. directly merged by human, after CI passes.  I did the latter for 3.8 and 3.7.

2019-08-07 16:09 UTC, tim-one commented
Thanks, Terry!  I was just going to kill them, to avoid screwing things up worse ☹️ 

While you're here, do you understand what the earlier

> Sorry, I can't merge this PR. Reason: Base branch was modified. Review and try the merge again..   

messages were trying to communicate?

And, when you did the merges, do you understand what the

 > Please replace # with GH- in the commit message next time. Thanks!

messages were trying to say?  I've seen the latter message every time I've "squashed & merged" anything, and still have no idea what it's talking about (I didn't use "#" in the commit messages).

2019-08-07 20:12 UTC, terryjreedy commented
1. Good thing you left them alone.  They were fine.  If closed, new backport labels here would have been needed.  I open this and took a look at them because your fairly detailed explanation of what you did omitted mention of approving the backports.

2. Once CI for a patch to master passes, changes to master can create merge conflicts.  When so, Github adds a temporary message to the CI detail box.  (It is now shrunken, with a [View Details] button.)  One can resolved them by editing files with conflict markers either with Github's  online editor or with any editor on one's working machine, followed by a push of the edited branch.

When you added the Automerge label, our backport/merge bot, Miss Islington gets involved.  I resume its message paraphrases what I said above.  But I am puzzled because there is no listed merge-resolution commit.  Perhaps there was a spurious conflict that disappeared, perhaps github retried with a different and more successful merge strategy, perhaps there was just a timing issue.  Automerge is fairly recent, and I don't use it for changes to master because it hides the human who made the decision, and I often decide to merge after a final review.

3. The title at the top of this page has the PR number, here #13482, at the end, in gray.  It cannot be edited.  When one presses the green [Merge] button, github adds the number in ()s, such as (#13482) in black, and editable.  We are supposed to remember to change '#' to 'GH-', because #13482 could also refer to a tracker (bpo) number.  Automerge does that.  (What I don't like about automerge for original PRs is that it hides who triggered the merge.)

The same change is requested for backport numbers on backport merges (although there is discussion that they should maybe be deleted instead, or maybe the original PR #).  I forgot.

A coredev approving a backport is equivalent to an automerge label.  Then the change is automatic.  I could have used that instead.  I have not checked yet whether the label is available.

2019-08-07 21:31 UTC, tim-one commented
Thanks again, Terry.  Ya, I assumed the "can't merge this PR" messages were complaining about a merge conflict, but didn't see any evidence of such.  Plus there were _three_ such messages, two of which _followed_ the bot saying it merged the commit into master.

So then I thought "OK, 3 complaints, but nothing fishy about master, but I added 3 backport labels so it must be complaining about them".  But no sign of merge conflicts in those either.

For the rest, sounds like I'll avoid automerge in the future.  It's hard enough trying to guess the consequences of what I explicitly do :wink:.