bpo-28787: Fix out of tree --with-dtrace builds
python/cpython pull request #135
Opened 2017-02-16 14:04 UTC by stratakis

Issue reported at: https://bugs.python.org/issue28787

This was observed after DTrace and Systemtap support was introduced for Python 3.6.0: https://bugs.python.org/issue21590

2017-05-05 16:13 UTC, vstinner requested changes
It seems to be your first contribution, please add yourself to Misc/ACKS ;-)

2017-05-05 16:13 UTC, haypo commented on Makefile.pre.in
> +	@$(MKDIR_P) Include
Please remove @, I like to see what is done.

2017-05-05 16:24 UTC, haypo commented
Please rebase also your change.

2017-05-10 15:08 UTC, vstinner approved these changes

2017-05-10 15:08 UTC, merged

2017-05-10 15:12 UTC, haypo commented
I merged your change, thanks @stratakis. Would you mind to backport the change? Only 3.6 is needed according to http://bugs.python.org/issue28787

I used the following commands. Without the change, make fails. With the fix, make works as expected.

```
cd $HOME
rm -rf build_cpython/
mkdir build_cpython/
cd build_cpython/
~/prog/python/master/configure --with-pydebug --with-dtrace
make
```

2017-05-10 15:13 UTC, stratakis commented
Thanks @haypo . I have already backported the change at #1519 .