bpo-36686: Improve the documentation of the std* params in loop.subprocess_exec
python/cpython pull request #13586
Opened 2019-05-26 19:16 UTC by sbstp

https://bugs.python.org/issue36686

2019-05-26 21:29 UTC, asvetlov requested changes
The PR is for documentation update, that's nice.
`base_events.py` in `subprocess_exec` and `subprocess_shell` explicitly forbids non-default `universal_newlines`, `shell` and `bufsize`.
It would be nice if `text`, `encoding` and `errors` arguments are explicitly forbidden too by code

2019-05-26 21:29 UTC, asvetlov commented on Doc/library/asyncio-eventloop.rst
> +     The ``asyncio`` subprocess API does not yet support decoding the streams
Let's not make assumptions the future in docs.
I mean `subprocess API does not yet support` should be replaced with just `subprocess API does not support`.
I'm open for discussion about text mode support though, please create a separate ussue for that.

2019-05-26 23:27 UTC, sbstp commented
> It would be nice if `text`, `encoding` and `errors` arguments are explicitly forbidden too by code

I don't mind writing the code for that, but it seems like there's a chance it will cause breakage if some programs used those params.

2019-05-27 12:54 UTC, 1st1 approved these changes

2019-05-27 12:54 UTC, 1st1 commented
Please use `blurb` to generate a NEWS entry.

2019-05-27 21:44 UTC, asvetlov requested changes
Almost perfect! Please fix last nits

2019-05-27 21:44 UTC, asvetlov commented on Lib/asyncio/base_events.py
> +        if encoding or errors or text:
Please split this `if` into three separate checks. It makes error messages more specific.

2019-05-27 21:44 UTC, asvetlov commented on Lib/asyncio/base_events.py
> +        if encoding or errors or text:
The same

2019-05-27 22:33 UTC, sbstp commented
I have made the requested changes; please review again. :)

2019-05-27 23:02 UTC, asvetlov commented on Lib/asyncio/base_events.py
> +        if encoding:
```suggestion
        if encoding is not None:
```

2019-05-27 23:02 UTC, asvetlov commented on Lib/asyncio/base_events.py
> +        if errors:
```suggestion
        if errors is not None:
```

2019-05-27 23:02 UTC, asvetlov commented on Lib/asyncio/base_events.py
> +        if encoding:
```suggestion
        if encoding is not None:
```

2019-05-27 23:02 UTC, asvetlov commented on Lib/asyncio/base_events.py
> +        if errors:
```suggestion
        if errors is not None:
```

2019-05-27 23:08 UTC, asvetlov requested changes
Please use suggested strict checks to distinguish, e.g. empty string from `None`.
I know that empty string for `errors` is invalid currently but still...

2019-05-27 23:36 UTC, asvetlov approved these changes
Thanks!

2019-05-27 23:51 UTC, miss-islington commented
@sbstp: Status check is done, and it's a success ✅ .

2019-05-27 23:51 UTC, merged

2019-05-28 00:13 UTC, sbstp commented
Thanks for being patient with me!