bpo-37077: Add native thread ID (TID) to threading.Thread objects for AIX
python/cpython pull request #13624
Opened 2019-05-28 13:24 UTC by aixtools

This is the followup PR for issue36084 (now closed so new bpo number)

(And I miss-pasted Add in the commit message (became dd, sigh).

2019-05-28 19:54 UTC, aixtools commented
@jaketesler - Hi, and thanks in advance. Many thanks for offering to be "tagged"!

This seems straight forward - and I hope complete (docs updated). (also thanks to @ncoghlan iirc who pointed at thread_self() - the "kernel" routine versus the posix thread *_self routine!

2019-05-29 07:02 UTC, tiran submitted a review, later dismissed
-1

As you already said, pthread_self does not return the TID, https://linux.die.net/man/3/pthread_self

> The thread ID returned by pthread_self() is not the same thing as the kernel thread ID returned by a call to gettid(2).

I'd rather not provide the feature at all than to provide an implementation that does not match with other implementations.

2019-05-29 07:45 UTC, aixtools commented
> 
> 
> -1
> 
> As you already said, pthread_self does not return the TID, https://linux.die.net/man/3/pthread_self
> 
> > The thread ID returned by pthread_self() is not the same thing as the kernel thread ID returned by a call to gettid(2).
> 
> I'd rather not provide the feature at all than to provide an implementation that does not match with other implementations.

And I did not use pthread_self() - I used thread_self() - also a routine that has been around for years.

A short example - with also the verification from "ps" that the value returned by thread_self is - indeed - the KERNEL tid and not the POSIX_tid.

```
root@x066:[/data/prj/aixtools/tests/posix]./thread_self
thread_self: pid:7602402 tid:12779547 ptid:1
[1] + Stopped (SIGTSTP)        ./thread_self
root@x066:[/data/prj/aixtools/tests/posix]ps -p 7602402 -mo THREAD
    USER     PID    PPID       TID ST  CP PRI SC    WCHAN        F     TT BND COMMAND
    root 7602402 7209084         - T    0  60  1 f1000a040034adb0   200011  pts/0   - ./thread_self
       -       -       -  12779547 T    0  60  1 f1000a040034adb0   410400      -   - -
root@x066:[/data/prj/aixtools/tests/posix]cat thread_self.c
#include <pthread.h>
#include <sys/thread.h>
#include <stdio.h>

main()
{
        pid_t pid;
        tid_t tid;
        pthread_t ptid;

        pid = getpid();
        tid = thread_self();
        ptid = pthread_self();

        fprintf(stderr,"thread_self: pid:%d tid:%d ptid:%d\n", pid, tid, ptid);
        sleep(300);     /* give time to run ps -mo THREAD */
}

```

So, not understanding the GIT process - you requested a change - but I do not see anything to change. Other than perhaps my comment where I thanked 'someone' for pointing out the issue BEFORE I submitted anything. 

Regards,
Michael

2019-05-29 14:31 UTC, jaketesler commented
This may provide some clarity – https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.basetrf2/thread_self.htm

2019-06-09 05:38 UTC, ncoghlan commented
@aixtools @encukou has cleared out the review that was based on misreading the update. It's likely worth adding a comment to the new AIX code, referencing the link that @jaketesler's provided.

Do you have any thoughts on how we might be able to properly test this change? The existing native thread ID code doesn't appear to have any obvious tests either, so I wouldn't consider that a merge blocker, but it would still be nice if we could add that missing test coverage while folks have eyes on the code anyway.

2019-06-09 16:06 UTC, aixtools commented
On 09/06/2019 07:38, Nick Coghlan wrote:
> @aixtools @encukou has cleared out the review that was based on misreading the update. It's likely worth adding a comment to the new AIX code, referencing the link that @jaketesler's provided.
>
> Do you have any thoughts on how we might be able to properly test this change? The existing native thread ID code doesn't appear to have any obvious tests either, so I wouldn't consider that a merge blocker, but it would still be nice if we could add that missing test coverage while folks have eyes on the code anyway.
>
With all mails coming from "Nicole Trudeau", sometime hard to know who
is saying what.

a) I have no issue with adding a reference to
https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.basetrf2/thread_self.htm,
but I wonder why to make an exception for the AIX bit.

I had replied directly to "whoever" had made the review - that I had
found the same comment in a book (white books I called them back then)
on AIX 4.1 documentation from June 1995).

I'll bow to your wisdom - but it feels funny giving AIX "special
attention". iirc, the other platforms do not have any link re: their
documentation.


b) as to how to verify the the difference between "pthread"_tid() -
whatever it name and "kernel"_tid() - for AIX I can only come up with
something (that would work on AIX, do not know how to implement it on
other platforms) is to verify the current PID is the "owner" of the TID
would be to call, and parse a command such as "ps -p $PID -mo tid".

ps -p $PID # fairly common"

-o tid # I expect to be 'common' as well

-m (on AIX stands for multi-line),

An example - not as root, so it works for all:

ps -p $$ -mo tid
      TID
        -
 22937633

So, while it could be used "as proof" - I think it would need to be a
separate PR/issue - as it will require "platform" input for all platforms.

As a footnote - I would not mind learning how to expand a test (even if
only for AIX) to make this comparison - as long as you know, in advance,
the basic approach I would take.

Regards,

Michael

2019-06-12 08:58 UTC, aixtools commented
Someone will need to send me better instructions on how to rebase. Locally it only showed the difference from master - this does not look 'rebased' at all.

The real changes are the same 4 files - and the same sort of changes - as were made for OpenBSD - bpo-37087, PR 13654

2019-06-12 09:07 UTC, encukou commented
> Someone will need to send me better instructions on how to rebase.

Which instructions were you using?
What you did here is a rebase *followed by a merge*.

2019-06-12 09:08 UTC, skrah commented
Why do you need to rebase?  I'm usually fine with `git pull https://github.com/python/cpython/ master` **after committing my local changes**, which then merges `master` into the local branch.

2019-06-12 09:12 UTC, encukou commented
> Why do you need to rebase?

The surrounding code changed.

2019-06-12 09:19 UTC, asvetlov commented
@aixtools your PR has 234 commits from which about 4 are yours, others are the result of false merge/rebase.
I personally usually use `git merge upstream/master` when working on PR because we squash all PR's commits before merging into master anyway -- but other people can have different preferences.

2019-06-12 09:28 UTC, aixtools commented
@encukou - besides reading the git manual I also reviewed https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase. 

It looked - fine - from my forks perspective, or is that local copy - but when I pushed it here it seems to sees it only as a merge. Perhaps I need to add a --force flag - which I have never used to date - to make it all look 'cleaner'.

This is not my day job - and although I generally like git - it still gets the better of me - frequently.
I hope the real content is clear - the 4 files I had merge conflicts are the same files that we both updated to add this function - 

michael@x071:[/data/prj/python/git/python3-3.8]vi Doc/library/_thread.rst Doc/library/threading.rst Include/pythread.h Python/thread_pthread.h

I do not want to clutter this with my steps. I am saving the screen output, and if someone will be kind enough to explain where I went wrong I, hopefully, will not get caught like this again.

2019-06-12 09:35 UTC, skrah commented
> The surrounding code changed.

I guess technically you're correct but the point is that one does not have to call `git rebase` explicitly, fixing conflicts is part of the merge.

2019-06-12 09:41 UTC, asvetlov commented
Try `git merge master` or `git  merge upstream/master` depending on where `https://github.com/python/cpython` repo is present in your fork.
It can eliminate all foreign commits for your PR.

2019-06-12 09:56 UTC, aixtools commented
> I guess technically you're correct but the point is that one does not have to call `git rebase` explicitly, fixing conflicts is part of the merge.

As I said - not my day job - and when someone writes - elsewhere - that a "PR needs rebase" I made, the (wrong?) assumption - that that is the expected flow. In this case it would have been much easier to do it all manually. 

Big Sigh. There will be a next time and I'll probably feel forced to close the "old" PR and start a new one.  :( I do not like "messy".

> Try `git merge master` or `git merge upstream/master` depending on where `https://github.com/python/cpython` repo is present in your fork.
> It can eliminate all foreign commits for your PR.

So, I need to work from a combined setup - as I cannot commit/push to cpython.

My normal workflow is:
cd cypthon-master
git checkout master
git fetch cpython
git pull cpython master
git push --all aixtools # update my fork

And then switch to a clone of my fork
git fetch aixtools
git pull aixtools master
... # create branch bpo-XXXXX-tag, etc..
git commit -m"message"
git push --set-upstream aixtools bpo-XXXXX-tag

If I would add cpython as an additional upstream - can I "rebase" from it, and then push to my fork (as I cannot push to cpython) - and the foreign commits are eliminated?

2019-06-12 10:33 UTC, asvetlov commented
I use the so-called triangular workflow: https://github.blog/2015-07-29-git-2-5-including-multiple-worktrees-and-triangular-workflows/

I have a fork of cpython project here: https://github.com/asvetlov/cpython
My `cpython/.git/config` looks like:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "upstream"]
	url = git@github.com:python/cpython.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "master"]
	remote = upstream
	merge = refs/heads/master
[remote "origin"]
	url = git@github.com:asvetlov/cpython.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "3.7"]
	remote = upstream
	merge = refs/heads/3.7
[branch "dangling-threads-in-watcher"]
	remote = origin
	merge = refs/heads/dangling-threads-in-watcher
```

So my local master is `upstream/master` but my working branches are `origin/feature-branch`.
To sync my feature branch with upstream master I do:
```
cd cpython
git checkout master
git pull
git checkout feature-branch
git merge master
git push -u origin feature-branch
```
Thus my clone has all my work but my master is `https://github.com/python/cpython.git`

I hope it helps you

2019-06-12 11:36 UTC, aixtools commented
Thanks. I'll do something similar - it has to be better than what I am doing now. :)

2019-06-12 11:55 UTC, aixtools commented
So, do I need to (try to) clean this up, or close the PR, and create a new one that is based on current master? Or will the process be able to proceed? I do not wish to make extra work for someone else (e.g., clean up actions).

2019-06-12 12:14 UTC, methane commented
I think Github will fix this automatically.
I saw similar trouble sometime.  They are fixed automatically after several hours.

2019-06-12 12:53 UTC, asvetlov commented
Whatever works for you.
Usually, we don't close existing PR to keep conversation history.
You can create a new clear branch, apply your 4 pull requests (by making patch file or cherry-picking) and force-push the new local branch to this existing github-side branch without closing the PR.

2019-06-12 14:01 UTC, aixtools commented
I'll try the cherry-pick, at least look at it, and force a new PR.

2019-06-12 14:33 UTC, aixtools commented
This looks cleaner. Thanks for the suggestions.

2019-06-12 20:31 UTC, asvetlov requested changes
Cool!
Please resolve conflicts.
This is a job for PR author, not a merger.

A patch for NetBSD was landed before AIX :)

2019-06-13 10:12 UTC, aixtools commented
So, I get to learn - again - if I have mastered the "rebase" process :)

2019-06-13 10:16 UTC, methane commented
No need to learn "rebase".  Just use "merge".
In our workflow, "rebase" does not have any merit.  It only cause troubles like this.

2019-06-13 10:29 UTC, ericvsmith commented
But https://devguide.python.org/gitbootcamp/#syncing-with-upstream recommends rebase if you have local changes. Or maybe I misunderstand the use case here.

2019-06-13 10:41 UTC, methane commented
> But https://devguide.python.org/gitbootcamp/#syncing-with-upstream recommends rebase if you have local changes. Or maybe I misunderstand the use case here.

I think it is just an preference of the document author, not official recommendation.

2019-06-13 10:50 UTC, skrah commented
> But https://devguide.python.org/gitbootcamp/#syncing-with-upstream recommends rebase if you have local changes. Or maybe I misunderstand the use case here.

Yes, it looks a bit like a recommendation.  FWIW, I recently had this conversation with a highly advanced git user, and his opinion was to merge master into the PR for all projects that squash merges, because the alternative is too complex for PRs that are open for a long time.

2019-06-13 10:54 UTC, aixtools commented
OK - third time is the charm they say.

Question: line 358 of  Doc/library/threading.rst: the OpenBSD PR change this line. I am following the line from the original PR. So which is correct?

OpenBSD PR with:  .. availability:: Require :func:`get_native_id` function.

Or "original model": .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX.

If OpenBSD is correct, I'll update the PR again.

I have made the requested changes; please review again.

@methane,  @ericvsmith and @skrah - thanks for the extra info.

FYI - elsewhere I was told to use "rebase" - and I finally (think I) understand why the operation is named 'rebase' - and it looks nice on my repository - but horrible here (i.e., where it cam from). @asvetlov gave a very helpful "list" that is working nicely for me now.

I have made the requested changes; please review again.

2019-06-13 10:58 UTC, methane commented
> Yes, it looks a bit like a recommendation. FWIW, I recently had this conversation with a highly advanced git user, and his opinion was to merge master into the PR for all projects that squash merges, because the alternative is too complex for PRs that are open for a long time.

I agree with him.  While I use rebase often (especially for branches before sending pull request), it requires high git knowledge.  Additionally, it requires `-f` option when `git push`.  It is dangerous for new git users too.
I think "git rebase" shouldn't be recommended for new users.

2019-06-13 11:05 UTC, aixtools commented
I am thinking the "rebase" - read "merge" should be written up in the devguide. I tried reading up on it yesterday and this morning - and my head hurts - how to make it simple.

What I think has been vital for me was seeing how to merge from "upstream". I thought I had to maintain my fork at 100% - so I had a separate directory for "maintaining" the fork and then did all my cloneing, merge, pull, etc. from my fork rather than from "upstream".

I suppose when in a team using git - rather than "solo" (aka wannabe 'member') getting advice and direction in how to use git effectively is more efficient than googling through multiple opinions written up as tutorials.

:) so happy this "merge" went smoothly.

2019-06-13 12:32 UTC, methane commented
I sent pull request to stop recommend "rebase": python/devguide#496

2019-06-13 13:30 UTC, asvetlov requested changes

2019-06-13 13:30 UTC, asvetlov commented on Misc/NEWS.d/next/Core and Builtins/2019-05-28-11-47-44.bpo-37077.S1h0Fc.rst
> +Add native thread ID (TID) for AIX
```suggestion
:func:`threading.get_native_id` now also supports AIX.
```

2019-06-13 13:30 UTC, asvetlov commented on Doc/library/threading.rst
> +      .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX.
```suggestion
      .. availability:: Require :func:`get_native_id` function.
```
Please keep the text from master.
@vstinner approved the change for NetBSD, I think we don't have to change it again (and fix doc in two places once next implementation will be added).

2019-06-13 13:33 UTC, jaketesler commented on Doc/library/threading.rst
> +      .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX.
“Require” or “Requires”?

2019-06-13 13:39 UTC, asvetlov commented on Doc/library/threading.rst
> +      .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX.
grepping python doc provides the only similarity from `os.rst`: 
```
.. availability:: Unix, Windows.  :func:`spawnlp`, :func:`spawnlpe`, :func:`spawnvp`
```
Also doesn't look perfect.

I don't know, I'm not a native speaker. Ok with any decision.

2019-06-13 13:43 UTC, jaketesler commented on Doc/library/threading.rst
> +      .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX.
I’d suggest “Requires.” Maybe this will set a good precedent. ¯\_(ツ)_/¯

2019-06-13 13:46 UTC, asvetlov commented on Doc/library/threading.rst
> +      .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX.
Updated suggestion

2019-06-13 19:47 UTC, aixtools commented
I have made the requested changes; please review again.

2019-06-13 20:12 UTC, vstinner approved these changes
LGTM.

2019-06-13 22:34 UTC, asvetlov approved these changes

2019-06-13 22:34 UTC, merged

2019-06-13 22:34 UTC, miss-islington commented
Thanks @aixtools for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!