bpo-35246: fix support for path-like args in asyncio subprocess
python/cpython pull request #13628
Opened 2019-05-28 15:27 UTC by lilydjwg

Drop isinstance checks from create_subprocess_exec function and let
subprocess module do them.

https://bugs.python.org/issue35246

2019-05-28 15:27 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-05-28 15:45 UTC, asvetlov requested changes

2019-05-28 15:45 UTC, asvetlov commented on Lib/test/test_asyncio/test_subprocess.py
> +        self.loop.run_until_complete(execute())
please add `self.assertIsNone(loop.run_until_complete(...))` check to emphasize that we checked that the test passed correctly.

2019-05-28 15:45 UTC, asvetlov commented on Lib/test/test_asyncio/test_subprocess.py
> +            from pathlib import Path
Move the import to the top of the module.
Use `import pathlib` form and `pathlib.Path` for consistency.

2019-05-28 16:11 UTC, lilydjwg commented
I have made the requested changes; please review again.

BTW the Windows CI errors should be resolved by #5914.

2019-05-28 17:06 UTC, asvetlov approved these changes

2019-05-28 17:07 UTC, asvetlov requested changes
Please take a look on failed test on Windows: https://ci.appveyor.com/project/python/cpython/builds/24869318

2019-05-28 17:20 UTC, asvetlov commented
Sorry, didn't read your last message.

Let's postpone merging for a while.
If #5914 will be merged soon you'll do sync with the master and I'll merge.
Otherwise we have to add tests skipping or `expectedFailure()` on Windows

2019-05-28 19:47 UTC, serhiy-storchaka commented on Lib/test/test_asyncio/test_subprocess.py
> +                pathlib.Path(sys.executable), '-c', 'pass')
If we test for the support of the path protocol it is better to use `test.support.FakePath` instead of `pathlib.Path`.

2019-05-28 20:48 UTC, asvetlov requested changes
#5914 has been merged.
Please sync with master and address @serhiy-storchaka suggestion about `test.support.FakePath`.
Rebase is not necessary, `git merge master` is enough. We squash all commits on merging anyway.

2019-05-29 06:28 UTC, lilydjwg commented
I have made the requested changes; please review again.

2019-05-29 06:50 UTC, asvetlov approved these changes
Well done!

2019-05-29 06:51 UTC, merged