[3.6] Doc: Add an optional obsolete header. (GH-13638).
python/cpython pull request #13657
Opened 2019-05-29 16:49 UTC by JulienPalard

(cherry picked from commit 46ed90dd014010703c7a3b2a61c4927644fa8210)

Co-authored-by: Julien Palard <julien@palard.fr>

2019-05-30 14:00 UTC, JulienPalard commented
@ned-deily Hi Ned, would you please merge this, if you like it? See screenshot here: https://github.com/python/cpython/pull/13638

2019-05-30 16:30 UTC, ned-deily requested changes
Are you also planning to add `outdated` to `conf.py`?

2019-05-30 16:30 UTC, ned-deily commented on Doc/tools/templates/layout.html
> +    <a href="/3/{{ pagename }}{{ file_suffix }}">{% trans %} Python documentation for the last stable release {% endtrans %}</a>.
Suggest using "most recent" or "current" rather than "last" to avoid ambiguity ("most recent" vs "final").

2019-06-02 19:01 UTC, JulienPalard commented
> Are you also planning to add `outdated` to `conf.py`?

I think I'll add it thrue docsbuild-scripts, not via the file, so for future releases I won't have to commit the boolean to conf.py.

2019-06-15 13:54 UTC, JulienPalard commented
I have made the requested changes; please review again.

2019-06-15 18:22 UTC, ned-deily approved these changes
LGTM, thanks!

2019-06-15 18:25 UTC, merged