bpo-36373:Deprecate explicit loop parameter in all public asyncio APIs
python/cpython pull request #13670
Opened 2019-05-30 00:50 UTC by eamanu

This PR deprecate explicit loop parameters in all public asyncio APIs

This issues is split to be easier to review.

First step: tasks.py

2019-05-30 02:20 UTC, Carreau approved these changes

2019-05-30 03:15 UTC, tirkarthi reviewed
Please handle `DeprecationWarning` in the tests. Running with `-Werror` would give test failures due to warnings.

2019-05-30 10:50 UTC, asvetlov requested changes
Agree with @tirkarthi 
`./python -Werror -m test` should pass
You can find the following command useful in development:
`./python -Werror -m test -v test_asyncio"

2019-06-05 10:57 UTC, asvetlov requested changes
Please run the PR with `./python -Werror -m test --check-env-changed -v test_asyncio` and make sure that the test run is succeded.

2019-06-05 10:57 UTC, asvetlov commented on Lib/asyncio/tasks.py
> +        if loop:
This check is redundant: `asyncio.gather()` always passes `loop` to internal `_GatheringFuture` constructor.

2019-06-05 13:47 UTC, asvetlov commented on Lib/asyncio/tasks.py
> +            warnings.warn("The loop argument is deprecated since Python 3.8, "
`Task` is called with explicit `loop` by `loop.create_task()` method, please drop the check

2019-09-12 12:41 UTC, closed without merging