Remove unused imports found by pyflakes
python/cpython pull request #137
Opened 2017-02-16 14:21 UTC by haypo

Make also minor PEP8 coding style fixes on modified imports.

2017-02-16 15:18 UTC, orsenthil approved these changes

2017-02-16 15:57 UTC, serhiy-storchaka requested changes
Please open an issue on the tracker. This is enough large change.

2017-02-16 15:57 UTC, serhiy-storchaka commented on Lib/tkinter/test/test_tkinter/test_widgets.py
> -    setUpModule)
setUpModule should be imported in the module namespace!

2017-02-16 15:57 UTC, serhiy-storchaka commented on Lib/tkinter/test/test_ttk/test_widgets.py
> -    setUpModule)
Same as above.

2017-02-16 15:57 UTC, serhiy-storchaka commented on Lib/unittest/__main__.py
> -from .main import main, TestProgram
This looks suspicious. Are you sure that TestProgram is not needed?

2017-02-16 15:57 UTC, serhiy-storchaka commented on Lib/idlelib/idle_test/test_searchbase.py
> +from tkinter import Tk, Frame  ##, BooleanVar, StringVar
Why BooleanVar and StringVar are commented out?

2017-02-16 16:44 UTC, haypo commented on Lib/unittest/__main__.py
> -from .main import main, TestProgram
Lib/unittest/main.py ends with "main = TestProgram". And TestProgram is not used in Lib/unittest/__main__.py.

2017-02-16 16:45 UTC, haypo commented on Lib/idlelib/idle_test/test_searchbase.py
> +from tkinter import Tk, Frame  ##, BooleanVar, StringVar
They are used in commented code a few lines below. I don't want to remove this commented code, since I don't know this file.

2017-02-16 18:56 UTC, orsenthil commented
Here was my basis for approval. The change is an automated one using pyflakes and our unit-tests are successful. I could not spot anything critical after looking at the diff. ( That is, if things would have broken by removal of top-level imports, then we should have seen when the module was invoked).

2017-02-17 23:35 UTC, warsaw commented
Gosh I'd love to enable flake8 on the stdlib, since it often causes my eyes to bleed red when I open a py file from the stdlib.  But I suppose that will just cause unnecessary code churn.  It's still nice to clean things up when you can, like unused imports.

2017-02-18 00:37 UTC, haypo commented
2017-02-18 0:35 GMT+01:00 Barry Warsaw <notifications@github.com>:
> Gosh I'd love to enable flake8 on the stdlib, since it often causes my eyes to bleed red when I open a py file from the stdlib. But I suppose that will just cause unnecessary code churn. It's still nice to clean things up when you can, like unused imports.

Technically, it's possible, but you should expect a lot of "# noqa" to
ignore warnings when pyflakes is not smart enough to understand
"Python magic". For example, even with my patch, there are still tons
of "unused import" warnings.

2017-03-27 13:08 UTC, haypo commented on Lib/tkinter/test/test_tkinter/test_widgets.py
> -    setUpModule)
fixed

2017-03-27 13:08 UTC, haypo commented on Lib/tkinter/test/test_ttk/test_widgets.py
> -    setUpModule)
fixed

2017-03-27 13:11 UTC, haypo commented
I rebased my patch and removed the two changes removing setUpModule() :-)

2017-03-27 13:12 UTC, haypo commented
@serhiy-storchaka: "Please open an issue on the tracker. This is enough large change."

I don't see the value added by creating an issue, but ok, I created http://bugs.python.org/issue29919 :-)

2017-03-27 14:03 UTC, serhiy-storchaka approved these changes

2017-03-27 14:05 UTC, merged

2017-03-27 14:05 UTC, haypo commented
Thanks for the reviews!