minor: Bugfix in configure script's print statement
python/cpython pull request #13818
Opened 2019-06-04 17:39 UTC by jeffguy

2019-06-04 17:39 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-06-04 17:54 UTC, jeffguy commented
I've now signed the CLA, but not sure how to re-trigger the-knights-who-say-ni

2019-06-13 08:21 UTC, jdemeyer requested changes
`configure` is auto-generated by autoconf starting from `configure.ac`. It should never be edited manually.

2019-09-13 13:06 UTC, matrixise commented
Thank you but this PR is not related to Python itself but to the autoconf tool. I close the PR.

2019-09-13 13:06 UTC, closed without merging