bpo-19903: Change to inspect.signature for calltips
python/cpython pull request #1382
Opened 2017-05-02 10:28 UTC by lulouie

This commit change the get_argspec from using inspect.getfullargspec
to inspect.signature. It will improve the tip message for use.

Also, if object is not callable, now will return this message for
user, not blank tips. If the methods has an invalid method signature,
it will also return message to user.

2017-05-02 12:03 UTC, serhiy-storchaka commented on Lib/idlelib/calltips.py
> +    except AttributeError:
Could you left this change for separate issue?

2017-05-02 12:03 UTC, serhiy-storchaka commented on Lib/idlelib/calltips.py
> +            if argspec.startswith("(self,"):
What if the first parameter have a different name?

2017-05-02 14:39 UTC, lulouie commented on Lib/idlelib/calltips.py
> +            if argspec.startswith("(self,"):
Yes, you are right. I'll still need to figure out how it does different from `getfullargspec`

2017-05-03 04:08 UTC, lulouie commented on Lib/idlelib/calltips.py
> +            if argspec.startswith("(self,"):
Find out that `signature` will deal correctly with MethodType, but will not handle `__init__` correctly.
Fix the condition of trim first param.

2017-05-03 04:08 UTC, lulouie commented
@serhiy-storchaka @terryjreedy Also add the test for first param not `self` test.

2017-05-03 04:12 UTC, lulouie commented on Lib/idlelib/idle_test/test_calltips.py
> -                                      (C.m2, "(**kwds)"), (c.m2, "(**kwds)"),):
Remove invalid method signature, move to `test_invalid_method_signature`

2017-05-03 04:12 UTC, lulouie commented on Lib/idlelib/idle_test/test_calltips.py
> +        self.assertEqual(signature(Test()), mtip)
This test borrow from `test_signature`

2017-05-03 04:12 UTC, lulouie commented on Lib/idlelib/idle_test/test_calltips.py
> +            def __call__(oui, a, b, c):
Add corner case for first param not `self`

2017-05-03 04:13 UTC, lulouie commented on Lib/idlelib/idle_test/test_calltips.py
> +
PEP8

2017-05-04 07:14 UTC, terryjreedy commented on Lib/idlelib/calltips.py
>      if isinstance(fob, (types.FunctionType, types.MethodType)):
Remove and dedent block.

2017-05-04 07:14 UTC, terryjreedy commented on Lib/idlelib/calltips.py
> +        except ValueError:
Must get and test error message.

2017-05-04 07:17 UTC, terryjreedy commented on Lib/idlelib/calltips.py
> +            argspec = "This function has an invalid method signature"
Add _invalid_signature to global defs before function so can access for testing without repeating string.

2017-05-04 07:18 UTC, terryjreedy commented on Lib/idlelib/calltips.py
> +        except ValueError:
Condition return on error message

2017-05-04 07:19 UTC, terryjreedy commented on Lib/idlelib/calltips.py
>          if (isinstance(ob, (type, types.MethodType)) or
Add argspec != '' to later revised condition

2017-05-04 07:22 UTC, terryjreedy requested changes
See msg292964 on issue for explanations and comment on what test addition is needed.

2017-05-04 17:45 UTC, terryjreedy commented on Lib/idlelib/calltips.py
> -    elif isinstance(ob_call, types.MethodType):
Why these removals? This should be justified by discussion/examples on the issue first.

2017-05-04 17:45 UTC, terryjreedy commented on Lib/idlelib/calltips.py
> +b"""calltips.py - An IDLE Extension to Jog Your Memory
??? Docstrings are not bytes.

2017-05-04 17:57 UTC, terryjreedy commented on Lib/idlelib/calltips.py
> -        fob = ob.__init__
Why remove this?  It worked before.  Does signature() do this automatically?  Such a change should be explained on the issue with examples, both for Python and C coded classed.  And yes, I wish I had added comments here or in test file or, by reference, an issue, when I revised this and and added test file.

2017-05-04 18:00 UTC, terryjreedy commented on Lib/idlelib/calltips.py
> +        argspec = ''
Why? '/' is used in legitimate signatures, and appear, I believe, in the docs.

2017-05-05 03:56 UTC, lulouie commented on Lib/idlelib/calltips.py
> +b"""calltips.py - An IDLE Extension to Jog Your Memory
A typo..., I'm using trackpoint on laptop, sometime when scrolling down, it will unexpectedly
pressing "b"

2017-05-05 04:03 UTC, lulouie commented on Lib/idlelib/calltips.py
> -        fob = ob.__init__
As you said on msg, this will automatically done by `signature`.

2017-05-05 07:05 UTC, lulouie commented on Lib/idlelib/calltips.py
> +        argspec = ''
I'll use your method in [msg293008](http://bugs.python.org/issue19903#msg293008)

2017-07-24 19:02 UTC, terryjreedy commented
Replaced by #2822 with new account name.

2017-08-02 21:41 UTC, terryjreedy commented
Edit by others being turned off seems to be resolved for now.

2017-08-02 21:41 UTC, closed without merging