bpo-37173: Show passed class in inspect.getfile error
python/cpython pull request #13861
Opened 2019-06-06 11:08 UTC by flying-sheep

Currently, inspect.getfile(str) will report nonsense:

>>> inspect.getfile(str)
TypeError: <module 'builtins' (built-in)> is a built-in class

This fixes that

2019-06-06 12:49 UTC, mangrisano approved these changes

2019-06-06 12:58 UTC, flying-sheep commented
I think we can skip the news entry on this tiny fix

2019-06-06 13:02 UTC, asvetlov requested changes
I don't follow how the variable renaming can fix anything.
Please provide a test

2019-06-06 13:29 UTC, flying-sheep commented
May I convince you to look again instead? It’s 4 lines of very simple code…

1. We go into the branch when `object` is a class
2. `object` gets reassigned to the class’ module
3. An error gets thrown, with the message talking about the class.

 I simply introduce a new variable instead of reassigning `object`, so it stays assigned to the class and the error message is correct.

2019-06-08 02:35 UTC, terryjreedy commented
I agree that the change appears to be is correct, as explained.  See the end below.

In general, bpo issues get blurbs.  A bugfix like this needs a blurb so that anyone who has run into it will see that it is fixed.  We are not starved for news space. "The exception message for inspect.getfile(<built-in class>) now correctly reports the class rather than module builtins.

test_inspect needs 3 new methods added after test_getfile:
```
    def test_getfile_builtin_module(self):
        with self.assertRaises(TypeError) as e:
            inspect.getfile(sys)
        self.assertTrue(str(e.exception).startswith('<module'))

    def test_getfile_builtin_class(self):
        with self.assertRaises(TypeError) as e:
            inspect.getfile(int)
        self.assertTrue(str(e.exception).startswith('<class'))

    def test_getfile_builtin_function_or_method(self):
        with self.assertRaises(TypeError) as e:
            inspect.getfile(abs)
        self.assertIn('expected, got', str(e.exception))
        with self.assertRaises(TypeError) as e:
            inspect.getfile(list.append)
        self.assertIn('expected, got', str(e.exception))
```
Note that test_getfile_builtin_class current fails because the message currently starts with '<module'.  The patch should make it pass.

2019-06-08 10:27 UTC, flying-sheep commented
OK, I was opposed to just add a test for the thing I fixed (basically as a regression test), but proposing that the whole thing ought to be tested makes sense to me. I’ll add both news and tests

2019-06-08 11:40 UTC, flying-sheep commented
@asvetlov OK, done

2019-06-08 12:05 UTC, asvetlov approved these changes
lgtm

2019-06-08 12:05 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Base branch was modified. Review and try the merge again.`.

2019-06-08 12:05 UTC, merged

2019-06-08 12:05 UTC, miss-islington commented
Thanks @flying-sheep for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-06-08 12:09 UTC, flying-sheep commented
Great! Thank you for the tests @terryjreedy

2019-06-08 15:02 UTC, miss-islington commented
Thanks @flying-sheep for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-06-08 15:05 UTC, terryjreedy commented
@flying-sheep Our general policy is to add an initially failing test, to prevent a regression, for every bugfix.