bpo-37221: Add PyCode_NewEx to be used internally and set PyCode_New as a compatibility wrapper
python/cpython pull request #13959
Opened 2019-06-11 01:48 UTC by pablogsal

2019-06-11 21:53 UTC, vstinner commented
I would prefer to call the new function PyCode_NewWithPosArgs() rather than PyCode_NewEx().

2019-06-11 22:03 UTC, vstinner commented
Would it make sense to wait to merge this PR just before next beta2, and also synchronize with Cython to make sure that Cython will be compatibl with Python 3.8 beta2, soon after beta2 is released?

2019-06-11 22:03 UTC, pablogsal commented
I renamed the new function to `PyCode_NewWithPosOnlyArgs`

2019-06-11 22:05 UTC, pablogsal commented
> Would it make sense to wait to merge this PR just before next beta2, and also synchronize with Cython to make sure that Cython will be compatible with Python 3.8 beta2, soon after beta2 is released?

We can merge and backport it and it will be released before in beta2, right? I will do the PR for Cython right away. They can chose to merge it when they think is better.

2019-06-11 22:12 UTC, vstinner commented on Doc/c-api/code.rst
> +.. c:function:: PyCodeObject* PyCode_NewWithPosOnlyArgs(int argcount, int posonlyargcount, int kwonlyargcount, int nlocals, int stacksize, int flags, PyObject *code, PyObject *consts, PyObject *names
I suggest to move it *after* PyCode_New().

2019-06-11 22:12 UTC, vstinner commented on Doc/c-api/code.rst
>     version since the definition of the bytecode changes often.
I suggest to write a simpler doc, like:

Similar to :c:func:`PyCode_New`, but with an extra "posonlyargcount" for positonal-only arguments.

2019-06-11 22:12 UTC, vstinner commented on Doc/whatsnew/3.8.rst
> +  reasons and will set the number os positional only parameters to 0.
I'm not sure about making PyCode_NewWithPosOnlyArgs the preferred way. PyCode_New() is fine for most use cases, no?

2019-06-11 22:12 UTC, vstinner commented on Objects/codeobject.c
> +PyCode_New(int argcount, int kwonlyargcount,
nitpick: *here* i suggest to declare PyCode_New *after* PyCode_NewWithPosOnlyArgs declaration.

2019-06-11 22:27 UTC, vstinner requested changes

2019-06-11 22:27 UTC, vstinner commented on Doc/c-api/code.rst
>     .. audit-event:: code.__new__ "code filename name argcount posonlyargcount kwonlyargcount nlocals stacksize flags"
I suggest to remove the audit event here, it's already documented in PyCode_New().

2019-06-11 22:27 UTC, vstinner commented on Doc/c-api/code.rst
> +   .. audit-event:: code.__new__ "code filename name argcount kwonlyargcount nlocals stacksize flags"
That's wrong, it's really `   .. audit-event:: code.__new__ "code filename name argcount posonlyargcount kwonlyargcount nlocals stacksize flags"` in practice (with pos only).

2019-06-11 22:27 UTC, vstinner commented on Doc/whatsnew/3.8.rst
> +  code objects like :c:func:`PyCode_New`, but with an extra "posonlyargcount"
nitpick: `*posonlyargcount*` formatting

2019-06-11 22:27 UTC, vstinner commented on Include/code.h
> +/* For backwards compatibility after adding posonlyargcount */
IMHO this comment can be removed. There is no **need** to deprecate anything so far.

2019-06-11 22:27 UTC, vstinner commented on Misc/NEWS.d/next/C API/2019-06-11-02-50-38.bpo-37221.4tClQT.rst
> +reasons and will set the number os positional only parameters to 0.
I'm not sure that it's needed to deprecate/prefer anything so far. Just mention that you add the function, no?

2019-06-11 22:34 UTC, vstinner approved these changes
LGTM, but I would prefer a second review. @methane, @serhiy-storchaka, @ncoghlan, @encukou, anyone?

2019-06-11 22:34 UTC, vstinner commented on Include/code.h
> +
unrelated change

2019-06-11 22:34 UTC, vstinner commented on Doc/whatsnew/3.8.rst
> +  argument for indicating the number of positonal-only arguments.
extra argument or extra parameter?

2019-06-11 22:34 UTC, vstinner commented on Misc/NEWS.d/next/C API/2019-06-11-02-50-38.bpo-37221.4tClQT.rst
> +
you might remove empty lines :)))

2019-06-12 04:49 UTC, scoder commented
> Would it make sense to wait to merge this PR just before next beta2

Yes, please. Otherwise, we will loose a month of CI time during which Cython cannot adapt (because the CPython API version does not change before the release) and during which users cannot properly test with the unreleased CPython master because Cython does not work on it any more.

2019-06-12 06:02 UTC, serhiy-storchaka reviewed
Please add a What's New entry.

2019-06-12 06:05 UTC, serhiy-storchaka commented
Would be nice if Cython release a new version which will use a special case only for Python `== 3.8b1`, not for `>= 3.8b1`.

2019-06-12 08:32 UTC, pablogsal commented
@serhiy-storchaka There is already a what's new entry. Do you mean something extra or something different?

2019-06-12 10:19 UTC, serhiy-storchaka commented
Sorry, I missed it.

2019-06-15 14:55 UTC, ncoghlan approved these changes
Thanks @pablogsal

2019-06-15 15:03 UTC, ncoghlan commented
@serhiy-storchaka The issue for Cython is that the 3.8 dev branch is currently still mostly advertising itself as 3.8b1: https://github.com/python/cpython/blob/3.8/Include/patchlevel.h

@ambv Could we do something a little odd here, and change the branch version string to be "3.8b2-" and bump the release serial to "2" before the actual release? That way the change could be merged, and Cython would be able to correctly detect it as being a different build from 3.8b1.

2019-06-16 17:00 UTC, scoder commented
> change the branch version string

Note that the dependency is in the generated C code and based on PY_VERSION_HEX, which cannot easily be modified in this way.

2019-06-21 14:53 UTC, ncoghlan commented
@scoder I've posted a PR at https://github.com/cython/cython/pull/3009 which adds a check directly for the new PyCode_NewWithPosOnlyArgs symbol, which should let Cython reliably detect versions where the incompatible API change has been reverted, even before the Python 3.8.0b2 version bump.

If that's acceptable on the Cython side, then the only blocker to merging this on the CPython side would be fixing the merge conflict in What's New.

2019-06-24 18:19 UTC, scoder approved these changes

2019-06-25 01:51 UTC, pablogsal commented
I have rebased to fix the merge conflicts.

2019-06-25 13:59 UTC, ambv commented
> @ambv Could we do something a little odd here, and change the branch version string to be "3.8b2-" and bump the release serial to "2" before the actual release?

Sorry, missed the notification on this one. I'd rather not, let's just merge this shortly before beta2, say: Friday.

2019-06-26 09:09 UTC, encukou commented
I read that as an invitation for anyone to hit the green button on Friday. Let us know if you want to do the merge yourself.

2019-07-01 10:35 UTC, merged

2019-07-01 10:36 UTC, miss-islington commented
Thanks @pablogsal for the PR, and @encukou for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-07-01 17:51 UTC, scoder commented
FYI, Cython 0.29.11 has been released with the necessary change for beta-2.

2019-07-01 18:05 UTC, vstinner commented
> FYI, Cython 0.29.11 has been released with the necessary change for beta-2.

That's great! Thank you.