bpo-37285: setup.py: avoid joining the SDKROOT twice
python/cpython pull request #14095
Opened 2019-06-14 18:30 UTC by mistydemeo

Fixes https://bugs.python.org/issue37285.

2019-06-14 18:30 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-07-14 10:50 UTC, ronaldoussoren requested changes
The same code is present in the 3.x branches as well, and should therefore be fixed there as well.

2019-07-14 10:50 UTC, ronaldoussoren commented on setup.py
> +                or (path.startswith('/Library/') and not path.startswith(sysroot)) )
It is not immediately clear why "and not ..." is necessary. Please add a comment that explains this.

2019-10-19 10:01 UTC, ned-deily commented
Thanks for the PR!  As explained on the bug tracker issue, the problems seen that your PR corrects have been fixed in PR #14256 and PR #14257.  These fixes are released in 2.7.17.

2019-10-19 10:01 UTC, closed without merging