bpo-35224: Reverse evaluation order of key: value in dict comprehensions
python/cpython pull request #14139
Opened 2019-06-17 03:39 UTC by joernheissler

… as proposed in PEP 572; key is now evaluated before value.

2019-06-17 03:39 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-06-17 03:44 UTC, joernheissler commented
> If you have recently signed the CLA, please wait at least one business day
> before our records are updated.

I signed it just before submitting the PR.

2019-06-17 03:47 UTC, gvanrossum commented
I like this -- very minimalist. Would you be so kind as to fill out the CLA and add a news item?

2019-06-18 09:42 UTC, methane commented
Would you update the document of MAP_ADD in `Doc/library/dis.rst`?

2019-06-21 20:50 UTC, gvanrossum requested changes
@joernheissler Please update the MAP_ADD docs as requested by Inada-san. Then I'll approve it and it will go into beta 2.

2019-06-22 07:16 UTC, joernheissler commented
I have made the requested changes; please review again.
Thanks for the hints!

2019-06-22 14:40 UTC, gvanrossum approved these changes

2019-06-22 14:40 UTC, merged

2019-06-22 14:41 UTC, gvanrossum commented
Thanks for helping out making the code conform to the PEP!

2019-06-22 19:27 UTC, joernheissler commented
For the Buildbot failure, refer to https://bugs.python.org/issue35224; msg346287, msg346292 and following.

2019-06-22 22:16 UTC, miss-islington commented
Thanks @joernheissler for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖