bpo-1025395: Fix email.utils.parseaddr to handle multiple hops
python/cpython pull request #142
Opened 2017-02-17 19:05 UTC by ioanatia

This fixes a very old [issue](https://bugs.python.org/issue1025395) with `email.utils.parseaddr`.
Right now `email.utils.parseaddr` will fail to parse the input correctly when the address contains a route with multiple hops. However it does not have an issue with single hop routes.

[RFC5322](https://www.ietf.org/rfc/rfc5322.txt) states that including route hops is obsolete and that the route part should be ignored (Section 4.4). It also states that this syntax is valid and it must be accepted and parsed (Section 4).

2017-02-17 19:05 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/22867185/d3aedcf8-f137-11e6-8469-d5f7861a1073.png)
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
4. If you just signed the CLA, please **wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-09-06 17:05 UTC, thehesiod commented
there's another issue I listed in http://bugs.python.org/issue1025395 where comments are not parsed correctly:
```
>>> AddrlistClass('John Smith <john.smith(comment)@example.org>').getdomain()
'JohnSmith'
```

mind taking a crack at that in this PR as well?

2017-11-07 21:08 UTC, ioanatia commented
Hey folks! I was wondering why my PR keeps failing, even though I did a rebase a couple of days ago! Can someone elucidate what might be going on here, please? From what I'm noticing, the Travis job has a different config than other jobs, so I'm kinda confused about why is that. Thanks a lot!

2017-11-07 21:19 UTC, brettcannon commented
It's totally fine to just do a merge if that's easier since we will do a squash commit in the end. I've restarted the Travis job just in case it was a weird fluke, though.

2017-12-08 14:55 UTC, ioanatia commented
Rebasing the branch on latest master does not fix it.
It seems to be that the travis build is not even run my latest commit, but on a random one https://github.com/python/cpython/commit/de1d4fcf48525331fea603101d8d54896e0861b9 .
On the other hand, the appveyor build seems fine.

2017-12-08 19:29 UTC, brettcannon commented
Maybe try doing a merge instead of a rebase? We've had issues in the past of Travis only grabbing the last 50 commits so that can lead to issues with older PRs.

2018-05-16 01:10 UTC, Mariatta requested changes
Please see my review: https://github.com/python/cpython/pull/142#issuecomment-389252659

2018-05-16 19:05 UTC, closed without merging