bpo-36888: Increase timeout in test_parent_process
python/cpython pull request #14286
Opened 2019-06-21 13:46 UTC by pierreglaser

Attempt to fix the buildbot failures reported in the original bpo issue.

We (@tomMoral and I) suspect that the `AssertionError` comes from the child process and the grand-child processes taking more than 5 seconds to get up and running, making the following calls to `rconn.poll(timeout=5)` return `False`. 

The proposed fix here is therefore to give more time for the child processes to start by increasing the timeout in the `rconn.poll` calls.

We also increase the life-span of the child process to make sure the it is not dead when the grand-child process starts executing.

cc @vstinner :)

2019-06-21 14:05 UTC, tomMoral commented
I agree this looks like an issue due to timeout that are too short. This PR should fix this.

2019-06-21 20:38 UTC, vstinner requested changes
test_parent_process() seems to be designed around time. That's a very weird synchronization primitation, it's not reliable at all. Can't you use another more reliable synchronization primitive? Something like https://docs.python.org/dev/library/multiprocessing.html#multiprocessing.Event?

cc @pablogsal

2019-06-25 14:37 UTC, tomMoral commented
The synchronization here does not rely on time bu is done thru the `multiprocessing.Pipe` object which is used as a communication channel. The timeout are only here to safeguard against hanged interpreters. Using `mp.Event` would lead to very similar code, as to avoid frozen interpreters, we would need to rely on `Event.wait` with non-zero timeout, which would be equivalent to the `poll` with non-zero timeout.

2019-06-25 20:43 UTC, vstinner approved these changes

2019-06-25 20:44 UTC, merged

2019-06-25 20:44 UTC, miss-islington commented
Thanks @pierreglaser for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖