bpo-37302: Add an "onerror" callback parameter to the tempfile.TemporaryDirectory member functions
python/cpython pull request #14292
Opened 2019-06-21 18:28 UTC by websurfer5

This PR adds an "onerror" callback parameter to the tempfile.TemporaryDirectory() member functions so that the caller can perform special handling for directory items that it can't automatically delete.  The caller created the undeletable directory entries, so it is reasonable to believe the caller may know how to unmake what they made.

The provided test cases create a filesystem image and mount it within the temporary directory to force an error in the underlying shutil.rmtree() call during cleanup that triggers calls to the new onerror parameters.  The test cases are provided for macOS because Windows and Linux require special user privileges to create and/or mount/unmount a filesystem image.  This method was chosen to simulate the cleanup problems described in bpo-36422.

I am open to suggestions on how to force errors on those systems or in a portable manner.  The usual trick of changing directory entry permissions won't work because tempfile.TemporaryDirectory() has heuristics to handle that case.

2019-06-22 21:15 UTC, mangrisano approved these changes

2023-04-04 16:45 UTC, iritkatriel requested changes
See recent changes to rmtree's onerror arg: https://github.com/python/cpython/pull/102829

2024-01-05 09:48 UTC, erlend-aasland commented
@websurfer5 could you please resolve the conflicts and update the PR?

2024-01-15 19:06 UTC, erlend-aasland commented
The feature request was rejected by @giampaolo in https://github.com/python/cpython/issues/80603#issuecomment-1093819196. Closing.

2024-01-15 19:06 UTC, closed without merging