bpo-20181: Convert the readline module to the Argument Clinic
python/cpython pull request #14326
Opened 2019-06-23 19:03 UTC by ZackerySpytz

2020-07-10 19:54 UTC, serhiy-storchaka requested changes

2020-07-10 19:54 UTC, serhiy-storchaka commented on Modules/readline.c
> +set the maximal number of lines which will be written to the history file.
```suggestion
Set the maximal number of lines which will be written to the history file.
```

2020-07-10 19:54 UTC, serhiy-storchaka commented on Modules/readline.c
> +history truncation.
```suggestion
A negative length is used to inhibit history truncation.
```

2020-07-10 19:54 UTC, serhiy-storchaka commented on Modules/readline.c
> +return the maximum number of lines that will be written to the history file.
```suggestion
Return the maximum number of lines that will be written to the history file.
```

2020-07-10 19:54 UTC, serhiy-storchaka commented on Modules/readline.c
> +get the beginning index of the completion scope
```suggestion
Get the beginning index of the completion scope.
```

2020-07-11 12:58 UTC, ZackerySpytz commented
I have made the requested changes; please review again.

2020-07-11 14:05 UTC, serhiy-storchaka requested changes

2020-07-11 14:05 UTC, serhiy-storchaka commented on Modules/readline.c
> +get the ending index of the completion scope
Please fix also other docstrings.
```suggestion
Get the ending index of the completion scope.
```

2020-07-11 14:05 UTC, serhiy-storchaka commented on Modules/readline.c
> +Returns current completer function.
Maybe use "get" for uniformity with other functions?

At least "return" is more preferable than "returns".

2020-07-12 16:00 UTC, serhiy-storchaka approved these changes

2020-07-12 16:00 UTC, serhiy-storchaka commented
:+1:

2020-07-12 16:01 UTC, merged