bpo-37382: check for debug info before testing GDB
python/cpython pull request #14331
Opened 2019-06-24 08:53 UTC by jdemeyer

2019-06-24 09:25 UTC, jdemeyer commented
CC @encukou

2019-06-26 08:54 UTC, jdemeyer commented
Bugfix, so should be backported to all earlier versions.

2019-06-26 11:07 UTC, vstinner requested changes
The tests should be skipped if Python is optimized: see the issue.

2019-06-26 14:19 UTC, jdemeyer commented
So how would you suggest to fix bpo-37382?

2019-06-26 14:37 UTC, vstinner commented
https://bugs.python.org/issue37382 is not a bug.

2019-06-26 14:41 UTC, jdemeyer commented
At least part of it is a bug: `test_gdb` fails when compiling CPython with `-O0 -g0`.

But the real issue for me is that `test_gdb` is not run by default. This PR addresses that.

2020-02-11 13:22 UTC, vstinner reviewed
Please don't backport this change to Python 3.8 :-) test_gdb is giving me too many headaches :-) For example, it fails if Python is built with -Os.

2020-02-11 13:22 UTC, vstinner commented on Lib/test/support/__init__.py
> +            final_opt = opt
Why not just returning True here? (and "return False" outside the loop)

2020-02-11 13:22 UTC, vstinner commented on Lib/test/support/__init__.py
> +    return final_opt == '-g'
Why do you reject "-ggdb"? I heard that it's even better than "-g".

2020-02-11 13:22 UTC, vstinner commented on Doc/library/test.rst
> +   Return ``True`` if Python was built with ``-g``.
Add ".. versionadded:: 3.9".

2024-01-15 17:06 UTC, encukou commented
Sorry for missing the ping back in 2019.
This PR has been superseded by [#110026](https://github.com/python/cpython/pull/110026/files#diff-65a7e7fedffb3771932da22df1aa9c74f8ec3781ed33775db45ac011be17e8a0) (and others). 
The current settings probably skip more than they need to, so the issue might still be relevant -- but a PR for that should now skip fewer tests rather than more.

2024-01-15 17:06 UTC, closed without merging