mapping.rst: PyMapping_Check(list) returns 1
python/cpython pull request #144
Opened 2017-02-17 21:50 UTC by jbarlow83

As discussed below, in Python 3, PyMapping_Check(list) returns 1. This behavior is justified by a developer as consistent with Python 3's internals. It is however surprising to C-API users (speaking from experience) and because it deviates from collections.abc.Mapping.

I think it is better to be vague than describe the implementation details.

https://mail.python.org/pipermail/python-dev/2009-May/089445.html

2017-02-17 21:50 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/22867185/d3aedcf8-f137-11e6-8469-d5f7861a1073.png)
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
4. If you just signed the CLA, please **wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-18 09:16 UTC, serhiy-storchaka requested changes

2017-02-18 09:16 UTC, serhiy-storchaka commented on Doc/c-api/mapping.rst
> +   function always succeeds. This is not exactly equivalent to ``collections.abc.Mapping``.
Use double space after sentence-ending period. The line is too long, wrap it at column 79. Make collections.abc.Mapping a reference.

2017-02-24 13:04 UTC, grapherd commented
Should the commit rebase into one commit?

2017-02-24 20:01 UTC, jbarlow83 commented
@grapherd The PR can be accepted as a squash merge in one click that will have the same effect as manually squashing it.

2017-02-27 20:09 UTC, jbarlow83 commented
Squashed

2017-03-06 06:10 UTC, Mariatta commented
I think this looks good now. @serhiy-storchaka would you like to take another look? I can do the backports.
Thanks :)

2017-03-06 07:12 UTC, rhettinger commented
No backports please.

2017-03-06 07:52 UTC, serhiy-storchaka commented
This is just the documentation fix. I think it should be backported.

But proposed wording doesn't LGTM. See my comment on the tracker.

2017-03-10 21:46 UTC, jbarlow83 commented
On [bpo](https://bugs.python.org/issue5945) serhiy-storchaka wrote:
>Proposed wording doesn't looks much informative to me. Maybe just say that PyMapping_Check() also returns 1 for sequences that support slicing? And recommend `PyMapping_Check() && !PySequence_Check()` for true mapping test?

There is no recommendation to use `PyMapping_Check() && !PySequence_Check()` in that thread. In fact developers [recommend against](https://bugs.python.org/issue5945#msg87752) both PyMapping_Check and PySequence_Check as well:

>(Author: Benjamin Peterson) Personally, I think PyMapping_Check and PySequence_Check should be deprecated and removed. Like their Python counterparts, operator.isMappingType() and operation.isSequenceType(), they are unreliable at best in the face of not LBYL and abcs

So I think it is appropriate to keep the proposed wording since it steers users to ABC checks and away from these APIs. If there is a change perhaps it should be explicitly "not recommended" in the documentation.

2018-02-21 01:53 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2018-02-23 01:11 UTC, jbarlow83 commented
I have made the requested changes; please review again.

Given that several core developers suggested or concurred with deprecating this API (Benjamin Peterson, GvR, Raymond Hettinger) I marked it not recommended as an alternative to officially deprecating.

No other core developers concur with the suggestion to use ``PyMapping_Check() && !PySequence_Check()``, one of the requested changes. It appears that this will not always work. Instead I recommend ``PyObject_IsInstance`` which steers the API user toward a modern API.

2018-05-21 04:47 UTC, willingc reviewed
@jbarlow83 Thanks for the PR and the changes. To keep this PR from further languishing, I suppose it may be most efficient to update the wording to incorporate @serhiy-storchaka's suggestion.

2018-05-21 04:47 UTC, willingc commented on Doc/c-api/mapping.rst
> +   protocol, and ``0`` otherwise.  This function always succeeds.  The C-API
I recommend using @serhiy-storchaka's suggested wording to move this PR forward.

~~The C-API mapping protocol is not equivalent to :class:`collections.abc.Mapping`, and also returns ``1`` for sequences that support slicing.  Use :c:func::`PyObject_IsInstance` instead.~~

`PyMapping_Check() also returns 1 for sequences that support slicing.`

2018-05-21 05:01 UTC, jbarlow83 commented
@willingc Done

2018-05-21 05:02 UTC, willingc commented
Thanks @jbarlow83 for the quick response.

@serhiy-storchaka This looks good to me now. If you have no further changes, I recommend merging. Thanks.

2018-05-21 05:02 UTC, willingc approved these changes

2018-06-04 10:34 UTC, ilevkivskyi commented
Superseded by https://github.com/python/cpython/pull/7029

2018-06-04 10:34 UTC, closed without merging