Update __main__.rst
python/cpython pull request #14487
Opened 2019-06-30 17:16 UTC by maggyero

This PR will apply the following changes on the [``__main__``](https://docs.python.org/3.7/library/__main__.html) documentation:

- correct the phrase "run as script" by "run from the file system" (as used in the [``runpy``](https://docs.python.org/3/library/runpy.html) documentation) since "run as script" does not mean the intended `python foo.py` but `python -m foo` (cf. [PEP 338](https://www.python.org/dev/peps/pep-0338/));
- replace the phrase "run with ``-m``" by "run from the module namespace" (as used in the [``runpy``](https://docs.python.org/3/library/runpy.html) documentation) since the module can be equivalently run with ``runpy.run_module('foo')`` from code instead of `python -m foo` from the command line;
- correct the place of the block comment and make it [PEP 8](https://www.python.org/dev/peps/pep-0008/#comments)-compliant (initial capital, ending period).

2019-06-30 18:35 UTC, mangrisano approved these changes
LGTM.

2019-08-07 06:33 UTC, maggyero commented
@Mariatta If you have some time, could you also review this one?

2019-08-20 06:23 UTC, maggyero commented
@Mariatta If you have some time, could you also review this one?

2019-09-03 13:14 UTC, maggyero commented
@Mariatta If you have some time, could you review this PR?

2019-10-15 06:26 UTC, maggyero commented
Hi @Mariatta. If you have some time, could you review this PR?

2020-01-25 13:43 UTC, csabella commented
@maggyero, please open a bug tracker ticket for this.  That will provide the chance for more people to see the change and comment on it.  Thanks!

2020-01-25 14:01 UTC, maggyero commented
Done @csabella.

2020-01-31 20:05 UTC, terryjreedy requested changes
To me, at least the first two changes in the description are wrong.  See the issue for discussion.

2020-09-16 21:18 UTC, maggyero commented
I have made the requested changes; please review again.

2020-09-17 02:27 UTC, terryjreedy commented
Remove trailing whitespace with patchcheck, as mentioned in devguide.

2020-09-17 02:37 UTC, terryjreedy commented
@stevendaprano Changes were made in response to your review on the issue.

2020-09-17 08:37 UTC, maggyero commented
@terryjreedy

> Remove trailing whitespace with patchcheck, as mentioned in devguide.

Done.

2021-08-24 12:37 UTC, ambv commented
Closing in favor of GH-26883.

2021-08-24 12:37 UTC, closed without merging