bpo-37451: remove redundant code in _testcapimodule.c
python/cpython pull request #14483
Opened 2019-06-30 09:14 UTC by shihai1991

2019-06-30 18:45 UTC, mangrisano commented
Hi. Thank you for the pull request. I'm not an expert, therefore, would you mind telling me why that is redundant? Just for learning. Thank you :)

2019-07-01 08:58 UTC, jdemeyer requested changes
I don't see why this code should be removed. It seems to be used for testing that `PyUnicode_FromWideChar` can deal with NULL-terminated and non-NULL-terminated buffers.

So at least, this PR needs better justification.

2019-07-01 11:58 UTC, shihai1991 commented
> I don't see why this code should be removed. It seems to be used for testing that `PyUnicode_FromWideChar` can deal with NULL-terminated and non-NULL-terminated buffers.
> 
> So at least, this PR needs better justification.

2019-07-01 12:33 UTC, shihai1991 commented
> I don't see why this code should be removed. It seems to be used for testing that `PyUnicode_FromWideChar` can deal with NULL-terminated and non-NULL-terminated buffers.
> 
> So at least, this PR needs better justification.

Jeroen, thanks for review.

`PyUnicode_FromWideChar` can return two kind of values of three scenarios:
1) `widechar_size + 1` if buffer is NULL or buflen > widechar_size + 1
    1.1 buffer is NULL can not happen in `PyUnicode_FromWideChar` because it have been judged in 
          https://github.com/python/cpython/blob/master/Modules/_testcapimodule.c#L1852
    1.2 buflen > widechar_size + 1 is judged in _testcapimodule.c is ok.
2) `buflen`
     2.1 the latest return value is buflen  or size(buflen==size) because of 
           https://github.com/python/cpython/blob/master/Objects/unicodeobject.c#L3164.

So I think the else statement in _testcapimodule.c is redundant.

2019-07-01 12:37 UTC, shihai1991 commented
> Hi. Thank you for the pull request. I'm not an expert, therefore, would you mind telling me why that is redundant? Just for learning. Thank you :)

Hi, Michele. Discussing process over result ;). I have answered downstairs.

2019-07-01 12:43 UTC, shihai1991 commented
> I don't see why this code should be removed. It seems to be used for testing that `PyUnicode_FromWideChar` can deal with NULL-terminated and non-NULL-terminated buffers.
> 
> So at least, this PR needs better justification.

2019-07-08 13:15 UTC, jdemeyer reviewed
OK, I see what you mean now. But given that it took me a while to understand why your PR was correct, I'm not convinced that we should merge it as-is.

2019-07-08 17:59 UTC, shihai1991 commented
> OK, I see what you mean now. But given that it took me a while to understand why your PR was correct, I'm not convinced that we should merge it as-is.

it's a small change and don't effect any functions, if core teams think it is not necessary, pls help me close this PR.
Don't waste too much time on it ;)

2019-07-20 10:01 UTC, zhangyangyu commented
Thanks for the contribution and I could understand your logic. It actually is from my point of view but it's quite tiny and doesn't affect anything so I think it's not necessary to change it.

2019-07-20 10:01 UTC, closed without merging