bpo-37459: importlib docs improperly reference get_resource_loader()
python/cpython pull request #14568
Opened 2019-07-03 03:23 UTC by aldwinaldwin

2019-07-03 04:40 UTC, aeros approved these changes
Approved, verified that this is the only reference to ``get_resource_loader(fullname)`` across the cpython repository. Based on the described functionality, ``get_resource_reader()`` seems to be the appropriate replacement.

2019-07-03 18:54 UTC, warsaw commented on Doc/library/importlib.rst
> +    provide a method called ``get_resource_reader()`` which
Please restore the `fullname` argument here.

2019-07-03 18:55 UTC, warsaw requested changes
Thanks for the fix; one change is needed.

2019-07-04 00:57 UTC, warsaw approved these changes
Thanks!

2019-07-04 00:58 UTC, merged

2019-07-04 00:58 UTC, miss-islington commented
Thanks @aldwinaldwin for the PR, and @warsaw for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-07-04 06:54 UTC, aeros167 commented
@warsaw Good catch, I should've searched the repository for ``get_resource_reader()`` to make sure, I had assumed that method was only using a ``self`` arg. Line 272 of ``zimimport.py clearly shows otherwise: ``def get_resource_reader(self, fullname):``. I definitely need to learn to scrutinize everything in order to provide more constructive reviews. My apologies.

2019-07-05 19:08 UTC, warsaw commented
No worries @aeros167 !  Thanks for helping out!