bpo-37482: Fix email address name with encoded words and special chars
python/cpython pull request #14561
Opened 2019-07-02 18:51 UTC by bsiem

Special characters in email address header display names are normally
put within double quotes. However, encoded words (=?charset?x?...?=) are
not allowed withing double quotes. When the header contains a word with
special characters and another word that must be encoded, the first one
must also be encoded.

In the next example, the display name in the From header is quoted and
therefore the comma is allowed; in the To header, the comma is not
within quotes and not encoded, which is not allowed and therefore
rejected by some mail servers.

From: "Foo Bar, France" <foo@example.com>
To: Foo Bar, =?utf-8?q?Espa=C3=B1a?= <foo@example.com>

2019-07-02 18:51 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-08-17 02:59 UTC, maxking requested changes
Thanks for the PR, it looks good to me. 

I have a very tiny nit, but otherwise I think we can merge this.

2019-08-17 02:59 UTC, maxking commented on Misc/NEWS.d/next/Library/2019-07-09-11-20-21.bpo-37482.auzvev.rst
> +Fixed email address display name with both encoded words and special chars.
nit:
```suggestion
Fix serialization of display name in orignator or destination address fields with both encoded words and special chars.
```

2019-08-17 08:51 UTC, bsiem commented
I have made the requested changes; please review again

2019-08-21 23:00 UTC, maxking approved these changes

2019-08-21 23:00 UTC, merged

2019-08-21 23:00 UTC, miss-islington commented
Thanks @bsiem for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-08-21 23:00 UTC, miss-islington commented
Sorry @bsiem, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker df0c21ff46c5c37b6913828ef8c7651f523432f8 3.8
                                ```