Doc: Fix missing negation.
python/cpython pull request #14640
Opened 2019-07-07 21:34 UTC by JulienPalard

Reported by Hug Capella on docs@.

2019-07-08 04:07 UTC, aeros requested changes
As a minor phrasing improvement suggestion, I would recommend changing it from:

> ...  If the :const:`LOCALE` flag is used, matches characters considered alphanumeric in the current locale and the underscore.

to:
> ...  If the :const:`LOCALE` flag is used, matches characters which are considered alphanumeric in the current locale and the underscore.

2019-07-09 02:21 UTC, eamanu approved these changes
LGTM

2019-07-12 17:37 UTC, JulienPalard commented
@aeros167 So you mean you're suggestion is to change:

> If the	:const:`LOCALE` flag is
   used, matches characters neither considered alphanumeric in the current locale
   nor the underscore.

to:

> If the	:const:`LOCALE` flag is
   used, matches characters which are neither considered alphanumeric in the current locale
   nor the underscore.

?

2019-07-12 18:48 UTC, aeros167 commented
@JulienPalard I'll submit the actual suggestion instead of just leaving it as a comment so it's easier to see

2019-07-12 18:53 UTC, aeros requested changes

2019-07-12 18:53 UTC, aeros167 commented on Doc/library/re.rst
> +   used, matches characters neither considered alphanumeric in the current locale
```suggestion
   used, matches characters which are neither alphanumeric in the current locale
```
Also removed "considered", unnecessary filler word in this case.

2019-09-11 15:33 UTC, matrixise approved these changes
Thank you for your contribution

2019-09-11 15:55 UTC, miss-islington commented
@JulienPalard: Status check is done, and it's a success ✅ .

2019-09-11 15:55 UTC, merged

2019-09-11 15:55 UTC, miss-islington commented
Thanks @JulienPalard for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖