bpo-25433: Streamline whitespace definitions
python/cpython pull request #14753
Opened 2019-07-13 15:51 UTC by rompe

According to bpo-25433, knowledge about whitespace should be implemented only once and documented only once.
This PR should fulfil both aspects.

2019-07-13 15:51 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-07-14 05:14 UTC, aeros requested changes
@rompe Welcome and thanks for the contribution!

I would advise closing this PR and splitting it into multiple smaller ones. This usually helps to expedite the review process and to better isolate any build related errors from the integration tests. 

The point of failure for travis is occurring on line 1870 of `bytearrayobject.c`, relating to the auto-generated argument clinic comments. I'm not particularly experienced with using them, so I would recommend checking out the [relevant documentation on it](https://docs.python.org/3/howto/clinic.html#basic-concepts-and-usage) if you haven't already.

From a first glance, it also looks like there might be some other whitespace issues, particularly in `glossary.rst`. Many of these can be resolved through the use of `patchcheck`. For more information on using it, see the [devguide](https://devguide.python.org/pullrequest/?highlight=pull%20request#patchcheck). If that does not auto-correct the spacing issues for you, the integration tests should be able to specify the problematic lines. 

On future PRs, I would also advise using the `Create draft pull request` feature. This allows you to let the integration tests to run without opening the PR, so that you can try to troubleshoot the issues. Optimally, the majority of the troubleshooting is done locally with `patchcheck` and the [automated tests](https://devguide.python.org/runtests/#runtests), but this provides final confirmation across multiple platforms. Once the integration tests are passing (or if you are unable to a solution for the test failures), you can select `Ready for review`, which will change the PR's status to `Open`. This is not at all required, but it can be quite helpful for both the author and any reviewers.

2019-07-14 08:15 UTC, rompe commented
@aeros167 thanks a million for your feedback. I will rework as requested and split code and documentation parts into separate pull requests.

(I was under the impression that one bgo issue should equal to one pull request, and I have to admit that I don't understand `patchcheck` yet. Time for some homework.)

2019-07-14 08:15 UTC, closed without merging

2019-07-14 18:27 UTC, aeros167 commented
>I was under the impression that one bgo issue should equal to one pull request, and I have to admit that I don't understand patchcheck yet.

No problem, the docs are quite extensive and we certainly don't expect anyone to know everything. Especially on their first PR to the repository. The process is quite involved and frequently not intuitive.

2019-07-14 19:15 UTC, rompe commented
OTOH I have to say that in fact everything is very well documented and I just need more time and practice to absorb it. For everything else Petr has been very helpful at the Europython sprint today, so I think the pull requests should be fine now.