bpo-25433: Streamline whitespace documentation
python/cpython pull request #14775
Opened 2019-07-14 11:58 UTC by rompe

Add a "whitespace" definition to the glossary and link to it from every documentation regarding whitespae.

As requested in bpo-25433, whitespace should be explained only once and all other places should point to this documentation instead of either explaining the term themselves or just stating "whitespace" without an explanation.

2019-07-14 11:58 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-09-11 07:53 UTC, matrixise commented
Thank you @rompe for your contribution but could you fix the conflict with `Doc/library/stdtypes.rst` ?

2019-09-11 08:08 UTC, matrixise requested changes
Please, rebase with master and fix the conflicts.

2019-11-21 02:18 UTC, csabella commented
@rompe, please resolve the merge conflicts.  Thanks!

2019-12-01 18:52 UTC, csabella commented
This PR has been languishing while waiting for the merge conflicts to be resolved.  I'm going to close this for now to allow someone else to pick it up.  If the original author wishes to come back to it, then it can be reopened at that time.  Thank you!

2019-12-01 18:52 UTC, closed without merging