bpo-19180: Updated reference for RFC 1750 and RFC 3280
python/cpython pull request #148
Opened 2017-02-18 08:57 UTC by chkumar246

* RFC 1750 has been been obsoleted by RFC 4086.
* RFC 3280 has been obsoleted by RFC 5280.
* RFC 4366 has been obsoleted by RFC 6066.

2017-02-18 08:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/22867185/d3aedcf8-f137-11e6-8469-d5f7861a1073.png)
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
4. If you just signed the CLA, please **wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-22 03:11 UTC, Carreau approved these changes
For the little effect my review can have, I approve, and comment made by OP are correct. 

> RFC 4366 has been obsoleted by RFC 6066.

If another reviewer is wondering, this one is already cited a couple of lines after the end the diff.

2017-02-27 09:41 UTC, chkumar246 commented
Thanks for the review. Any thing more to add to this patch?

2017-03-11 06:01 UTC, chkumar246 commented
@Carreau @serhiy-storchaka anything more i can improve to this patch?

2017-03-11 19:13 UTC, Mariatta approved these changes

2017-04-04 05:37 UTC, orsenthil commented
@serhiy-storchaka  - shall we move forward with this? The change looks good to me. These  are `See Also` links which informative guidance ( like introduction to SSL/TLS from Apache site in the same list). Removing the obsolete RFC and mentioning the correct ones seems to be right thing to do.

2017-04-04 05:37 UTC, orsenthil submitted a review, later dismissed

2017-04-04 06:20 UTC, serhiy-storchaka commented
RFC references should be updated only if the ssl module actually supports new RFCs and is not sticked to obsolete RFCs. I'm not a SSL expert and don't know if it is. @tiran is an expert.

There are also other references to obsolete RFCs in `ssl.rst` and `_ssl.c`. Shouldn't they be updated too?

2017-04-04 06:48 UTC, tiran requested changes
Please update inline references, too.

Also please add RFC 6125 and link it from match_hostname.

2017-04-04 06:48 UTC, tiran commented on Doc/library/ssl.rst
> -   `RFC 1750: Randomness Recommendations for Security <https://www.ietf.org/rfc/rfc1750>`_
This RFC is referenced in the documentation of ```RAND_add```. You need to update both occurrences.

2017-04-04 06:48 UTC, tiran commented on Doc/library/ssl.rst
> +   `RFC 5280: Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile <http://datatracker.ietf.org/doc/rfc5280/>`_
5280 is correct. Please update documentation of ```SSLSocket.getpeercert```, too.

2017-04-04 06:48 UTC, tiran commented on Doc/library/ssl.rst
> -   `RFC 4366: Transport Layer Security (TLS) Extensions <https://www.ietf.org/rfc/rfc4366>`_
RFC 6066 is the successor to 4366. Please update documentation of HAS_SNI.

2017-05-27 05:40 UTC, ncoghlan commented
@chkumar246 Thanks for the initial work on this at the PyCon Pune sprints. Do you think you may be able to find time to follow up on @tiran's feedback, or would you prefer that someone else pick up the change and finish up those final details?

2017-05-28 05:03 UTC, ncoghlan commented
Added the sprint label, as this PR was submitted at the PyCon Pune 2017 core development sprint.

2017-06-02 12:57 UTC, chkumar246 commented
Sorry for the late reply, I will update the PR soon.

2017-06-03 06:01 UTC, chkumar246 commented on Doc/library/ssl.rst
> -   `RFC 1750: Randomness Recommendations for Security <https://www.ietf.org/rfc/rfc1750>`_
Done.

2017-06-03 06:01 UTC, chkumar246 commented on Doc/library/ssl.rst
> -   `RFC 4366: Transport Layer Security (TLS) Extensions <https://www.ietf.org/rfc/rfc4366>`_
Done

2017-06-03 06:01 UTC, chkumar246 commented on Doc/library/ssl.rst
> +   `RFC 5280: Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile <http://datatracker.ietf.org/doc/rfc5280/>`_
Done

2017-06-03 06:02 UTC, chkumar246 commented
@ncoghlan @tiran Thanks for the review. I have resolved the comments, please have a look.

2017-06-09 07:35 UTC, tiran approved these changes

2017-06-09 09:08 UTC, matrixise commented
Just add the url https://bugs.python.org/issue19180

2017-06-09 09:43 UTC, merged

2017-06-09 09:45 UTC, matrixise commented
thanks @ncoghlan

2017-06-09 11:59 UTC, ncoghlan commented
Backport: https://github.com/python/cpython/pull/2023