fix-issue-37640
python/cpython pull request #14877
Opened 2019-07-21 09:22 UTC by peternguyen93

2019-07-21 09:22 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2019-07-22 09:47 UTC, tirkarthi commented
Please change the PR title to be of the format `bpo-NNNN: Description of the fix` where NNNN is the issue number to make sure the PR is linked to the issue. This PR would require tests and a NEWS entry. Given that the fix is applied on master branch I am not sure if the code to detect to be above python 3.6 is needed.

2019-07-22 10:39 UTC, ericvsmith commented
@tirkarthi: This code doesn't need a version test. The stdlib always only runs on the version it's shipped with. Agreed about needing tests and NEWS.

2019-08-20 06:24 UTC, peternguyen93 commented
Hi everyone, this issue should be fixing because a lot of CTF tools are based on it if it upgrades to python 3

2019-08-20 11:34 UTC, ericvsmith requested changes
You need to add tests and a Misc/NEWS entry (using blurb).

2019-08-20 11:34 UTC, ericvsmith commented on Lib/telnetlib.py
> +
Please remove the version tests. This code only needs to run on Python 3.

2019-09-11 08:16 UTC, matrixise requested changes
Thank you for your contribution but
1. Sign the CLA
2. Remove the test and simplify the code.

Thank you

2019-09-11 08:16 UTC, matrixise commented on Lib/telnetlib.py
> +                            if is_py_3:
just 
```python
sys.stdout.buffer.write(text)
```

2019-09-11 08:16 UTC, matrixise commented on Lib/telnetlib.py
> +                if is_py_3:
ditto

2019-12-13 02:25 UTC, csabella commented
@peternguyen93, just another reminder to sign the CLA and address the code review.  Without that, we'll have to close your PR.  Thanks!

2020-01-05 22:42 UTC, csabella commented
I'm going to close this pull request as the author has not signed the CLA after more than one request to do so.  Once the CLA is signed, this can be reopened.  Thank you.

2020-01-05 22:42 UTC, closed without merging