Remove unnecessary tuples, lists, sets, and dicts
python/cpython pull request #1489
Opened 2017-05-07 12:57 UTC by jdufresne

* Replaced list(<generator expression>) with list comprehension
* Replaced dict(<generator expression>) with dict comprehension
* Replaced set(<generator expression>) with set comprehension
* Replaced builtin func(<list comprehension>) with func(<generator
  expression>) when supported (e.g. any(), all(), tuple(), min(), &
  max())

2017-05-07 12:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-05-07 17:32 UTC, rhettinger requested changes

2017-05-07 17:32 UTC, rhettinger commented on Lib/_weakrefset.py
> +        return self.data < {ref(item) for item in other}
Let's use:  set(map(ref, other)) for all of these.

2017-05-07 17:32 UTC, rhettinger commented on Lib/distutils/msvc9compiler.py
> +    interesting = {"include", "lib", "libpath", "path"}
Yes to this one.  Set literals are always a win.

2017-05-07 17:32 UTC, rhettinger commented on Lib/inspect.py
> +    metamro = tuple(cls for cls in metamro if cls not in (type, object))
Yes, this one is fine.

2017-05-07 17:32 UTC, rhettinger commented on Lib/ntpath.py
> +            isabs, = {p[:1] == sep for d, p in drivesplits}
This code smells bad (both the original and revision).  Can this be replaced with any(...).

2017-05-07 17:32 UTC, rhettinger commented on Lib/optparse.py
> +                return tuple(self.check_value(opt, v) for v in value)
This looks like a reasonable change, but optparse is essentially defunct so we should leave it alone.

2017-05-07 17:32 UTC, rhettinger commented on Lib/pstats.py
> +                new_callers[func] = tuple(i[0] + i[1] for i in
Yes, this is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/pstats.py
> +                                          zip(caller, new_callers[func]))
If the line isn't too long, this is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/sqlite3/dbapi2.py
> +sqlite_version_info = tuple(int(x) for x in sqlite_version.split("."))
The suggest change is a minor improvement, but this code is very old and is probably best left untouched.

2017-05-07 17:32 UTC, rhettinger commented on Lib/symtable.py
> +        return tuple(ident for ident in self.get_identifiers()
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/tkinter/filedialog.py
> +            result = tuple(getattr(r, "string", r) for r in result)
This is a file I prefer not to touch.  Otherwise the change itself seems reasonable.

2017-05-07 17:32 UTC, rhettinger commented on Lib/tokenize.py
> +    result = {''}
This is okay.  Set literals are almost always the right thing to do.  My only misgiving is that the new code looks like an ascii emoticon.

2017-05-07 17:32 UTC, rhettinger commented on Lib/traceback.py
> +        self.locals = {k: repr(v) for k, v in locals.items()} if locals else None
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/turtle.py
> +        return tuple(c * self._colormode/255 for c in cl)
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/turtle.py
> +        return tuple((t11*x + t12*y, t21*x + t22*y) for (x, y) in polygon)
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/turtle.py
> +        keys = sorted(x for x in docsdict.keys()
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/turtledemo/wikipedia.py
> +    while any(t.undobufferentries() for t in s.turtles()):
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/urllib/request.py
> +                self.reduce_uri(u, default_port) for u in uri)
This is okay

2017-05-07 17:32 UTC, rhettinger commented on Lib/urllib/request.py
> +        headers.update({k: v for k, v in req.headers.items() if k not in headers})
update() can accept an iterable of tuples, so change this to:
headers.update((k, v) for k, v in req.headers.items() if k not in headers)

2017-05-07 17:32 UTC, rhettinger commented on Lib/urllib/request.py
> +        headers = {name.title(): val for name, val in headers.items()}
This is okay.  Sometimes the dict() form is clearer about its intention but in this case the colon form for the key/value is clearer than the (key, value) form.

2017-05-07 17:32 UTC, rhettinger commented on Mac/BuildScript/build-installer.py
> +    return tuple(int(n) for n in getVersion().split('.', 2))
This would be okay but it is in a file that we usually avoid touching.

2017-05-07 17:32 UTC, rhettinger commented on Tools/gdb/libpython.py
> +                       for i in safe_range(int_from_int(self.field('ob_size'))))
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Tools/scripts/byext.py
> +        colwidth["ext"] = max(len(ext) for ext in exts)
This is okay but I like max(map(len, exts)) better

2017-05-07 17:32 UTC, rhettinger commented on Tools/unicode/makeunicodedata.py
> +    print(len([n for n in names if n is not None]), "distinct names")
This is okay

2017-05-07 17:32 UTC, rhettinger commented on Lib/_compat_pickle.py
> +REVERSE_IMPORT_MAPPING = {v: k for k, v in IMPORT_MAPPING.items()}
Lets skip this module.

2017-05-07 17:32 UTC, rhettinger commented on Lib/_pydecimal.py
> +            self.traps = {s: int(s in traps) for s in _signals + traps}
Let's skip this module.

2017-05-07 17:32 UTC, rhettinger commented on Lib/argparse.py
> +            invocation_length = max(len(s) for s in invocations)
Let's skip this module.  I think Bethard would like this to be compatible across as many versions as possible or at least to keep the code in-sync as much as possible.

2017-05-07 17:32 UTC, rhettinger commented on Lib/ast.py
> +            return tuple(_convert(v) for v in node.elts)
In all of these cases, I prefer the original for clarity and inter-line parallelism

2017-05-07 17:32 UTC, rhettinger commented on Lib/cgi.py
> +        return list({item.name for item in self.list})
Let's skip this one.  I think the original is clearer about its intention.

2017-05-07 17:32 UTC, rhettinger commented on Lib/cmd.py
> +        topics = {a[5:] for a in self.get_names()
Skip this one.  The original is clearer about its intentions.

2017-05-07 17:32 UTC, rhettinger commented on Lib/concurrent/futures/_base.py
> +        finished = {
Let's skip all of these.  This module is delicate (harder to test minor changes) and the original code is marginally a bit clearer.

2017-05-07 17:32 UTC, rhettinger commented on Lib/distutils/cygwinccompiler.py
> +    return tuple(_find_exe_version(cmd) for cmd in commands)
This change would be okay but it is in a module I prefer not to touch.

2017-05-07 17:32 UTC, rhettinger commented on Lib/email/headerregistry.py
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/idlelib/multicall.py
> +        substates = list({state & x for x in states})
Skip this one.  I think the original is clearer.

2017-05-07 17:32 UTC, rhettinger commented on Lib/idlelib/multicall.py
> +                   for name in _modifiers[number]}
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/idlelib/multicall.py
> +               for name in _types[number]}
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/lib2to3/main.py
> +    unwanted_fixes = {fixer_pkg + ".fix_" + fix for fix in options.nofix}
Skip this.  I prefer the original for clarity and for parallelism with the previous line.

2017-05-07 17:32 UTC, rhettinger commented on Lib/logging/config.py
> +        kwargs = {k: config[k] for k in config if valid_ident(k)}
This should use the iterable-of-pairs form instead of creating an intermediate dictionary:
dict((k, config[k]) for k in config if valid_ident(k))

2017-05-07 17:32 UTC, rhettinger commented on Lib/logging/config.py
> +        kwargs = {k: config[k] for k in config if valid_ident(k)}
Same comment here:
dict((k, config[k]) for k in config if valid_ident(k)).
The proposed change also reads well but I'm not sure whether Vinay would want dict comps in this module.

2017-05-07 17:32 UTC, rhettinger commented on Lib/multiprocessing/context.py
> +DefaultContext.__all__ = [x for x in dir(DefaultContext) if x[0] != '_']
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/multiprocessing/forkserver.py
> +                data = {x: y for x, y in data.items() if x in desired_keys}
I'm ambivalent about this one.

2017-05-07 17:32 UTC, rhettinger commented on Lib/multiprocessing/sharedctypes.py
> +            d = {name: make_property(name) for name in names}
This is okay.

2017-05-07 17:32 UTC, rhettinger commented on Lib/ntpath.py
> +        if len({d for d, p in drivesplits}) != 1:
I prefer the original for clarity.

2017-05-07 17:32 UTC, rhettinger commented on Lib/pathlib.py
> +        {chr(x) for x in range(ord('a'), ord('z') + 1)} |
This should be simplified to set('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')
or if string is already imported to set(string.ascii_letters)

2017-05-07 17:32 UTC, rhettinger commented on Lib/posixpath.py
> +            isabs, = {p[:1] == sep for p in paths}
This code smells bad.  Is there a better way to express what it is trying to do?

2017-05-07 17:32 UTC, rhettinger commented on Lib/signal.py
> +        return {_int_to_enum(x, Signals) for x in sigs_set}
Skip this, I prefer the original.

2017-05-07 17:32 UTC, rhettinger commented on Lib/signal.py
> +        return {_int_to_enum(x, Signals) for x in sigs}
Skip this. I prefer the original.

2017-05-07 17:32 UTC, rhettinger commented on Lib/urllib/request.py
> +                      if k.lower() not in CONTENT_HEADERS}
I'm ambivalent about this one.

2017-05-07 17:32 UTC, rhettinger commented on Tools/msi/csv_to_wxs.py
> +    assert len(files) == len({make_id(f[1]) for f in files}), "Duplicate file IDs exist"
Skip this.  The original is clearer and the fix is one we usually don't touch unless we have to.

2017-05-07 17:32 UTC, rhettinger commented on Tools/ssl/make_ssl_data.py
> +    new_code_nums = {(libcode, num)
Skip this.  I prefer the original and the file is one I prefer not to touch.

2017-05-07 17:32 UTC, rhettinger commented on Tools/stringbench/stringbench.py
> +_format_dict_bytes = {bytes_from_str(k): bytes_from_str(v) for k, v in _format_dict.items()}
I prefer not to touch a benchmark file lest it cause comparability issues.

2017-05-07 17:32 UTC, rhettinger commented on setup.py
> +        ext_map = {ext.name: i for i, ext in enumerate(extensions)}
Skip this.  I prefer not to touch anything in setup.py.

2017-05-07 17:32 UTC, rhettinger commented on setup.py
> +        longest = max((len(e.name) for e in self.extensions), default=0)
Skip

2017-05-07 17:32 UTC, rhettinger commented on setup.py
> +            longest = max(longest, max(len(name) for name in all_failed))
Skip

2017-05-07 17:32 UTC, rhettinger commented on setup.py
> +                    sqlite_version_tuple = tuple(int(x) for x in sqlite_version.split("."))
Ambivalent.

2017-05-12 20:48 UTC, terryjreedy requested changes
I keep idlelib 3.6 and 3.7 in sync as much as possible.  
Please remove all Lib/idlelib/multicall.py changes from this PR and optionally (and preferably) make the 2 approved changes in a separate PR that can be backported easily.

2017-05-12 20:48 UTC, terryjreedy commented on Lib/idlelib/multicall.py
> +                   for name in _modifiers[number]}
I prefer the change as easier to read and likely faster.  Ditto for the other dict(list) to dict comp change in this file.

2017-05-12 20:48 UTC, terryjreedy commented on Lib/idlelib/multicall.py
> +        substates = list({state & x for x in states})
Agreed

2017-05-13 15:11 UTC, jdufresne commented on Lib/posixpath.py
> +            isabs, = {p[:1] == sep for p in paths}
Perhaps. However, my intention with this change was to avoid logic changes. I'll revert `posixpath.py` and `ntpath.py` for now.

2017-05-13 15:12 UTC, jdufresne commented
Thanks for the reviews! I believe I have addressed all feedback comments. If I missed or misunderstood any of the previous comments, please let me know.

2017-05-15 08:15 UTC, rhettinger approved these changes

2017-05-18 14:35 UTC, merged

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/email/headerregistry.py
The original variant, with list comprehension, is faster than the variant with a generator. The difference is up to 2 times for simple tests.

I would keep the original code.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/inspect.py
> +    metamro = tuple(cls for cls in metamro if cls not in (type, object))
I would keep the original code.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/logging/config.py
> +        kwargs = dict((k, config[k]) for k in config if valid_ident(k))
I would use a dict comprehension.

And the same for other change in this file.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/pstats.py
> +                new_callers[func] = tuple(i[0] + i[1] for i in zip(caller, new_callers[func]))
I would keep the original code.

Maybe unpack a tuple:
```
tuple([i + j for i, j in zip(caller, new_callers[func])])
```

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/symtable.py
> +        return tuple(ident for ident in self.get_identifiers()
I would keep the original code.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/turtle.py
> +        return tuple(c * self._colormode/255 for c in cl)
I would keep the original code.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/turtle.py
> +        return tuple((t11*x + t12*y, t21*x + t22*y) for (x, y) in polygon)
I would keep the original code.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/turtle.py
> +        keys = sorted(x for x in docsdict.keys()
`.keys()` can be removed. Iterate just `docsdict`.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/urllib/request.py
> +                self.reduce_uri(u, default_port) for u in uri)
I would keep the original code.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Lib/urllib/request.py
> +        headers.update((k, v) for k, v in req.headers.items() if k not in headers)
This changes the semantic. Updated `headers` is used in the generator expression. I don't know whether this is good.

I would use a dict comprehesion.

2017-05-18 15:07 UTC, serhiy-storchaka commented on Tools/gdb/libpython.py
> +                       for i in safe_range(int_from_int(self.field('ob_size'))))
I would keep the original code.