bpo-27470: fix documentation for -3 commandline option not warning wh…
python/cpython pull request #150
Opened 2017-02-18 09:35 UTC by Ghost-script

…en incompatibilities can't be detected using static code analysis

2017-02-18 09:35 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-22 03:26 UTC, Carreau approved these changes

2017-02-22 05:42 UTC, berkerpeksag requested changes

2017-02-22 05:42 UTC, berkerpeksag commented on Doc/using/cmdline.rst
> +   .. note::
I don't think a note directive is needed here. You can say something like

```rst
See :doc:`howto/pyporting` for more details.
```

I haven't checked whether :doc:\`howto/pyporting\` works or not so please build the docs locally and test it.

2017-02-22 18:48 UTC, Ghost-script commented on Doc/using/cmdline.rst
> +   .. note::
@berkerpeksag thanks for pointing out, fixed it.

2017-08-04 01:49 UTC, Mariatta approved these changes

2017-08-04 02:00 UTC, merged

2017-08-04 02:02 UTC, Mariatta commented
@berkerpeksag's review has been addressed.
I also tested locally that :doc:`howto/pyporting` works.

Thanks for the PR, @Ghost-script 🌮