bpo-30306: release arguments of contextmanager
python/cpython pull request #1500
Opened 2017-05-08 14:18 UTC by tecki

The arguments of a function which was declared as a contextmanager
are stored inside the context manager, and thus are kept alive.

This is a possible unnecessary memory leak.

This fixes the problem and adds a test for it. Look at the test to see an example of the problem.

2017-05-08 15:08 UTC, rhettinger commented
Does this change cause problems for recreate_cm?

```
    def _recreate_cm(self):
        # _GCM instances are one-shot context managers, so the
        # CM must be recreated each time a decorated function is
        # called
        return self.__class__(self.func, self.args, self.kwds)
```

2017-05-08 15:36 UTC, tecki commented
it shouldn't make problems for recreation. At the line you are showing the context manager has not yet been called, so the arguments have not yet been deleted. And once the context manager is actually `__enter__`d it cannot be recreated anymore (it's his "father" that gets recreated).

At least the tests still run, and there are tests for recreating context managers.

2017-05-09 02:24 UTC, ncoghlan commented
Nice catch, and it makes me pleased I decided exposing `_recreate_cm` as a public API would be a bad idea (otherwise it wouldn't really be feasible to change the current behaviour).

To address Raymond's concern, I think a more self-explanatory way of implementing the change would be to explicitly *not save* the arguments in the cases where we know `_recreate_cm` isn't going to be called on the instance (i.e. those created by the `self.__class__` call in `_recreate_cm`).

Suggested setup for that aspect:

* Add a `allow_recreation=True` keyword-only parameter to `GeneratorContextManagerBase.__init__`
* Make setting `self.[func, args, kwds]` conditional on that parameter being set (otherwise set them to None)
* Add a `allow_recreation=False` argument to the `self.__class__` call in `_recreate_cm`

And then make clearing the settings in `__enter__` conditional on `self.func != None`, with an explanatory note that when the instance is used directly as a context manager,  we don't need to keep the arguments for `_recreate_cm` around, so we release them ASAP.

(I'll add some more background and discussion about this on https://bugs.python.org/issue30306 so we have a record of the discussion)

2017-05-09 05:37 UTC, ncoghlan requested changes
The request for changes here relates mainly to the structural changes described above, but there's also a minor typo in the new test's helper function name.

2017-05-09 05:37 UTC, ncoghlan commented on Lib/test/test_contextlib.py
> +        def whohoo(a, b):
s/whohoo/woohoo/ (Yes, it's just a silly name for a throwaway function, but we may as well spell it correctly and consistently)

2017-05-09 08:05 UTC, tecki commented
I looked at the code more carefully and realized that it is unnecessarily complex. The recreation of the context manager is actually not necessary at all. All we need is to recreate the generator. This can be much more easily done directly in `__enter__`.

One might notice that I prefixed the variables in `_GeneratorContextBase` with double underscores. This is to show the world that their use is really confined to just those 25 lines of class code.

2017-05-09 10:24 UTC, ncoghlan commented
The generator is created eagerly so that argument/parameter mismatches get reported at the right spot (i.e. when the context manager is created, not when it first gets used). Please don't change that (but feel free to add a comment explaining why it is written that way).

2017-05-10 06:31 UTC, tecki commented
I changed the implementation to create the generator eagerly as proposed, and added test for it.

I think the proposed implementation is pretty clear by now.

2017-05-10 07:24 UTC, ncoghlan commented
While I haven't tested it, I'm pretty sure the revised implementation of the ContextDecorator support is going to have problems when applied to a recursive function - without an entire new inner CM being created for each call, the __exit__ invocations won't be properly independent.

It isn't possible to provide that independence implicitly in `__enter__`, as the interpreter has already saved its reference to the bound `__exit__` method by the time that runs.

If I'm right, that does suggest there's a missing test case for that scenario, though - the current test case just covers reuse without covering recursion.

2017-05-10 11:28 UTC, tecki commented
So I undid my additional changes, going back to my originally proposed two lines, plus tests added for all the cases that @ncoghlan mentioned.

2018-01-28 03:58 UTC, ncoghlan approved these changes

2018-01-28 04:14 UTC, ncoghlan commented
Branch editing is disabled, so I'll skip the NEWS entry for now, and add it in a follow-up commit.

2018-01-28 04:17 UTC, merged

2018-01-28 04:21 UTC, ncoghlan commented
NEWS entry PR: https://github.com/python/cpython/pull/5374