bpo-19692: Rename Py_SAFE_DOWNCAST to _Py_DOWNCAST
python/cpython pull request #15090
Opened 2019-08-03 07:31 UTC by shihai1991

2019-08-03 07:40 UTC, shihai1991 commented
cc @pitrou

2019-08-10 19:18 UTC, CuriousLearner reviewed
Not very sure if renaming this would be a good idea and what impact it can have. 🤷‍♂ 

But I'd like to see the discussion on bug tracker regarding this. Overall the changes look okay to me.

2019-08-11 10:22 UTC, shihai1991 commented
> Not very sure if renaming this would be a good idea and what impact it can have. 
> 
> But I'd like to see the discussion on bug tracker regarding this. Overall the changes look okay to me.

Thanks for review, Sanyam. Waiting enough discussion :)

2019-09-16 08:05 UTC, vstinner requested changes
You cannot remove Py_SAFE_DOWNCAST() macro which is part of the Python stable C ABI.

2019-09-16 17:03 UTC, shihai1991 commented
> Py_SAFE_DOWNCAST

Hi, victor.
Make sure I understand: adding `#define _Py_DOWNCAST(VALUE, WIDE, NARROW) Py_SAFE_DOWNCAST(VALUE, WIDE, NARROW)` for backwards compatibility and using `_Py_DOWNCAST` to repalce `Py_SAFE_DOWNCAST` inside.

ps: docs need updated too.

2019-09-16 19:26 UTC, vstinner commented
You PR says:

> Rename :meth:`Py_SAFE_DOWNCAST` to :meth:`_Py_DOWNCAST`

So it removes Py_SAFE_DOWNCAST() macro. Compilation of any C extension using Py_SAFE_DOWNCAST() will fail with this change.

> Make sure I understand: adding #define _Py_DOWNCAST(VALUE, WIDE, NARROW) Py_SAFE_DOWNCAST(VALUE, WIDE, NARROW) for backwards compatibility and using _Py_DOWNCAST to repalce Py_SAFE_DOWNCAST inside.

That would be an option.

2019-09-17 11:50 UTC, shihai1991 commented
> You PR says:
> 
> > Rename :meth:`Py_SAFE_DOWNCAST` to :meth:`_Py_DOWNCAST`
> 
> So it removes Py_SAFE_DOWNCAST() macro. Compilation of any C extension using Py_SAFE_DOWNCAST() will fail with this change.
> 
> > Make sure I understand: adding #define _Py_DOWNCAST(VALUE, WIDE, NARROW) Py_SAFE_DOWNCAST(VALUE, WIDE, NARROW) for backwards compatibility and using _Py_DOWNCAST to repalce Py_SAFE_DOWNCAST inside.
> 
> That would be an option.

Thanks, victor. I add an alias of `Py_SAFE_DOWNCAST ` and update the news.

2019-09-17 12:02 UTC, shihai1991 commented
Ops,  catching an typo erro incidentally: https://github.com/python/cpython/pull/16230

2019-09-17 13:18 UTC, shihai1991 commented
I have made the requested changes; please review again

2020-10-26 06:32 UTC, methane commented
I'm +0. Removed me from reviewers.

2025-01-28 08:59 UTC, erlend-aasland commented
Closing, as the linked issue is closed.

2025-01-28 08:59 UTC, closed without merging