bpo-37750: Add doc of PyBuffer_FromContiguous
python/cpython pull request #15091
Opened 2019-08-03 08:58 UTC by shihai1991

2019-08-14 15:53 UTC, shihai1991 commented
cc @pitrou @benjaminp

2019-09-11 11:11 UTC, matrixise requested changes
Thank you for your contribution but I have some remarks, could you fix them?

Thank you

2019-09-11 11:11 UTC, matrixise commented on Doc/c-api/buffer.rst
> +.. c:function:: int PyBuffer_FromContiguous(void *view, Py_buffer *buf, Py_ssize_t len, char fort)
Please, the description of the parameters is wrong
```c
int PyBuffer_FromContinuous(Py_buffer *view, void *buf, Py_ssize_t len, char fort);
```

2019-09-11 16:03 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@voidspace

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


## CLA Missing

Our records indicate the following people have not signed the CLA:

@mrkn

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-09-11 16:08 UTC, closed without merging

2019-09-11 16:09 UTC, shihai1991 commented
sorry, wrong rebase operation.