bpo-15786: Fix autocomletetion box mouse behavior
python/cpython pull request #1517
Opened 2017-05-09 13:15 UTC by lulouie

2017-05-10 03:53 UTC, lulouie commented
@terryjreedy This fixed the MacOS freeze and double click disappear problem, please help to take a review

2017-05-11 05:19 UTC, terryjreedy requested changes
Trivial formatting change.
Does not solve issue on Windows.

2017-05-11 05:19 UTC, terryjreedy commented on Lib/idlelib/autocomplete_w.py
> +            if self.widget == self.widget.focus_get() or not self.widget.focus_get():
2nd if is equivalent to 'and', and line is too long.  This works and conforms to PEP8.
        if (self.is_active() and
                (self.widget == self.widget.focus_get()
                or not self.widget.focus_get())):
            self.hide_window()

2017-05-11 05:19 UTC, terryjreedy commented on Lib/idlelib/autocomplete_w.py
> +        # This will be trigger when focus on widget or autocompletewindow
Make proper docstring, which I believe 
"Hide autocomplete list if it exists and does not have focus."

2017-05-11 07:49 UTC, lulouie commented
I must admire your work in IDLE, terry. Tk has bunch of cross-platform holes. On windows it can't work is because somehow winconfig will be trigger multiple time (just like a infinity loop), and let Tk can't respond to Double-ButtonRelease.

The fix will unbind winconfig_event when we are in the windows platform to prevent this problem.

2017-05-25 09:51 UTC, louisom commented
Close this issue and transfer to #1811

2017-05-25 09:51 UTC, closed without merging