bpo-16011 explicitly document the behaviour of in operator
python/cpython pull request #152
Opened 2017-02-18 09:53 UTC by aktech

2017-02-18 09:53 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-18 09:58 UTC, tiran approved these changes

2017-02-18 11:05 UTC, autumnsashes3 commented
![screenshot_20161218-075501](https://cloud.githubusercontent.com/assets/25849718/23092780/1f36f202-f587-11e6-9d34-11b94101c9a5.jpg)

2017-02-21 13:58 UTC, aktech commented
@tiran @ncoghlan @Mariatta  Can we Merge this now, as CLA is signed?

2017-02-22 02:05 UTC, berkerpeksag requested changes

2017-02-22 02:05 UTC, berkerpeksag commented on Doc/reference/expressions.rst
> +``in`` operator coerces the result returned by :meth:`__contains__` to a boolean,
This sentence should be ended with a full stop. Or if you used comma intentionally, "Hence" shouldn't begin with an uppercase letter "H".

2017-02-22 02:05 UTC, berkerpeksag commented on Doc/reference/expressions.rst
> +Hence ``x in y`` is true if and only if ``y.__contains__(x)`` is true.
Perhaps changing the example to `bool(y.__contains__(x))` would make the whole paragraph clearer?

2017-02-22 04:30 UTC, methane commented
I feel proposed sentence is unnecessary long.  How about this?

```
For user-defined classes which define the :meth:`__contains__` method, ``x in y``
behaves like ``bool(y.__contains__(x))``.
```

2017-02-22 04:59 UTC, zhangyangyu commented on Doc/reference/expressions.rst
> +Hence ``x in y`` is true if and only if ``y.__contains__(x)`` is true.
+1. Otherwise I don't see the difference with the original one.

2017-02-22 13:56 UTC, aktech commented
I have put the full stop before `Hence [..]`.
For ``bool(y.__contains__(x))`` quoting **R. David Murray** (https://bugs.python.org/issue16011) here:

> "coerce to boolean" is better than "apply bool", because the code may not in fact be using the bool function to do it.

2017-02-22 14:20 UTC, zhangyangyu approved these changes

2017-02-26 15:20 UTC, aktech commented
Can we merge this now?

2017-02-27 16:51 UTC, bitdancer commented
You know what, reading this change side by side with the original, I think I'd instead favor making it:

  For user-defined classes which define the :meth:`__contains__` method, ``x in y`` returns ``True`` if ``y.__contains__(x)`` returns a true value, and ``False`` otherwise.

Throughout the section, we should then change 'true' to ``True`` anywhere the result of the in operator is being discussed.

2017-03-03 08:28 UTC, aktech commented
@bitdancer does that looks good now?

2017-03-03 15:13 UTC, bitdancer commented
Yes, but we should also change 'true' to ``True`` in the rest of that section where the result of 'in' is being referenced.

2017-03-03 18:42 UTC, aktech commented
> Yes, but we should also change 'true' to True in the rest of that section where the result of 'in' is being referenced.

Yes, Indeed. I have changed that now.

2017-03-11 08:04 UTC, aktech commented
@bitdancer Is this good to go now?

2017-03-15 01:00 UTC, bitdancer commented on Doc/reference/expressions.rst
> +y`` returns ``True`` if ``y.__contains__(x)`` returns a ``True`` value, and
The second ``True`` here should be just true.

2017-03-19 11:32 UTC, aktech commented
@bitdancer Can we merge this now?

2017-03-19 15:38 UTC, bitdancer commented
Not until the Travis check passes.  I don't know what's wrong with that or how to get it fixed, unfortunately.

2017-03-27 06:01 UTC, aktech commented
> Not until the Travis check passes. I don't know what's wrong with that or how to get it fixed, unfortunately.

@ncoghlan Can you help me with this? Need to restart the travis build for this PR.

2017-03-28 03:34 UTC, ncoghlan commented
@aktech Since there isn't even a "Details" link, I can't trigger a rebuild from the Travis side of things, but you should be able to push an empty commit to the PR branch as described in http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit/31694534#31694534

Since we use the squash-and-merge workflow, that won't show up in the eventual commit history.

2017-03-28 05:14 UTC, Mariatta commented
Maybe try rebasing with upstream/master and push again?

2017-03-28 11:53 UTC, aktech commented
Thanks @Mariatta @ncoghlan, all tests passed.

2017-03-28 14:13 UTC, merged

2017-03-28 14:15 UTC, bitdancer commented
I think this should be backported to 2.7 as well, but I don't see a label for that.

2017-03-28 14:15 UTC, bitdancer commented
Nevermind, I just didn't realize I needed to scroll the list to find it.

2017-03-28 14:24 UTC, Mariatta commented
Thanks @aktech for your first contribution to CPython :tada:
Thanks @bitdancer for the merge. I can backport this to 3.6, 3.5, and 2.7.

2017-03-28 16:23 UTC, aktech commented
Thanks everyone for helping in improving this!

2017-05-28 05:07 UTC, ncoghlan commented
Added the sprint label, as this PR was submitted at the PyCon Pune 2017 core development sprint.

2017-09-13 17:18 UTC, miss-islington commented
Thanks @aktech for the PR, and @bitdancer for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7.
🐍🍒⛏🤖

2017-09-13 17:18 UTC, miss-islington commented
Sorry, @aktech and @bitdancer, I could not cleanly backport this to `2.7` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.