Fix typos mostly in comments, docs and test names
python/cpython pull request #15209
Opened 2019-08-11 13:52 UTC by minho42

Found some more typos in various files.

2019-08-27 01:50 UTC, epicfaace requested changes

2019-08-27 01:50 UTC, epicfaace commented on Doc/library/importlib.rst
>     representation being used, so ``/foo/bar/baz.py`` with an *optimization* of
```suggestion
   representation is used, so ``/foo/bar/baz.py`` with an *optimization* of
```

2019-08-27 01:50 UTC, epicfaace commented on Lib/test/test_winreg.py
> +    def test_inexistent_remote_registry(self):
```suggestion
    def test_nonexistent_remote_registry(self):
```

2019-08-27 01:50 UTC, epicfaace commented on Lib/unittest/test/testmock/testpatch.py
> +    def test_patch_propagrates_exc_on_exit(self):
```suggestion
    def test_patch_propagates_exc_on_exit(self):
```

2019-08-30 15:51 UTC, minho42 commented on Doc/library/importlib.rst
>     representation being used, so ``/foo/bar/baz.py`` with an *optimization* of
Thanks for the suggestions @epicfaace,
"Any other value’s string representation being used, so..."
This line is not very clear to me. I think there should be "If" at the beginning as well.
Anyway, I would like to leave this as is if possible, and get the typo bits merged first.

2019-08-30 19:22 UTC, terryjreedy commented on Doc/library/importlib.rst
>     representation being used, so ``/foo/bar/baz.py`` with an *optimization* of
Accept the suggestion as 'being' is effectively a typo.  With that change, the sentence is coherent, even if not optimal, whereas it it not now.

2019-08-30 19:25 UTC, terryjreedy commented
I am going to make and backport the idlelib changes, revert here, and then review.

2019-08-30 20:16 UTC, terryjreedy approved these changes
All changes look correct and non-controversial.  I checked that the only code change (LOADLIBARYEX to LOADLIBRARYEX) was complete and consistent.

2019-08-30 20:16 UTC, terryjreedy commented on Modules/expat/loadlibrary.c
> +  pLoadLibraryEx = (LOADLIBRARYEX_FN) GetProcAddress(hKernel32, LOADLIBRARYEX);
I verified with recursive grep that these are the only four instances of LOADLIBARYEX in any .c file or any .py file in lib or tools.  Note that the spelling is LOADLIBRARYEX_FN (with 2nd R) on line 51.

2019-08-30 20:21 UTC, merged

2019-08-30 20:21 UTC, miss-islington commented
Thanks @minho42 for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-08-30 20:26 UTC, miss-islington commented
Thanks @minho42 for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-08-30 20:26 UTC, miss-islington commented
Sorry, @minho42 and @terryjreedy, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 39d87b54715197ca9dcb6902bb43461c0ed701a2 3.7
                                ```

2019-08-30 20:35 UTC, terryjreedy commented
I expected the 3.8 backport to fail; good thing I tried it anyway.
If you or anyone makes a 3.7 backport PR, I think the LOADLIBARYEX fix should be skipped in case people have used it in their code.  They should not be surprised until they try 3.8.

2019-08-31 02:49 UTC, minho42 commented
Thank you @terryjreedy