bpo-37826: Document exception chaining in Python tutorial for errors.
python/cpython pull request #15243
Opened 2019-08-13 01:27 UTC by maxking

2019-08-13 01:35 UTC, maxking commented
I am going to add a skip-news label since this is a Documentation only change.

2019-08-14 20:36 UTC, warsaw requested changes

2019-08-14 20:36 UTC, warsaw commented on Doc/tutorial/errors.rst
> +The :keyword:`raise` statement allows an optional :keyword:`from` which allows
Maybe the second "allows" could be "enables"?

2019-08-14 20:36 UTC, warsaw commented on Doc/tutorial/errors.rst
> +inside an exception handler or :keyword:`finally` section. Although, it can be
That last sentence isn't a full sentence.  How about:

> Exception chaining can be disabled by using the ``from None`` idiom:

2019-08-14 21:06 UTC, maxking commented
I have made the requested changes; please review again.

2019-08-14 21:11 UTC, warsaw approved these changes

2019-08-14 21:11 UTC, merged