bpo-19820: Updated documentation for inspect module: some module attributes were…
python/cpython pull request #15359
Opened 2019-08-21 12:23 UTC by MichaelAnckaert

Updated documentation for inspect module: some module attributes were missing

2019-08-21 12:28 UTC, eamanu commented on Doc/library/inspect.rst
> +| module    | __name_           | name of the module        |
it would be great if it is order:
```
__cached__
__doc__
__file__
. . . 
```
Just an opinion :-)

2019-08-23 18:35 UTC, epicfaace requested changes

2019-08-23 18:35 UTC, epicfaace commented on Doc/library/inspect.rst
> +|           |                   | module/package            |
Can you lowercase the description in the __package__ row and __loader__ row so that capitalization is consistent?

2019-09-11 13:49 UTC, ericsnowcurrently requested changes
Mostly LGTM

Please add an entry for `__spec__`.

2019-09-11 13:49 UTC, ericsnowcurrently commented on Doc/library/inspect.rst
> +| module    | __name_           | name of the module        |
```suggestion
| module    | __name__           | name of the module        |
```

2019-09-11 13:49 UTC, ericsnowcurrently commented on Doc/library/inspect.rst
> +|           |                   | version is/should be      |
There isn't any "should be".  Either it's stored there or `__cached__` isn't set.

2019-09-11 13:49 UTC, ericsnowcurrently commented on Doc/library/inspect.rst
> +|           |                   | version is/should be      |
This should go below `__file__`.

2020-01-25 23:59 UTC, csabella commented
@MichaelAnckaert, please address the code reviews.  Thank you!

2020-05-25 13:36 UTC, MichaelAnckaert commented
I have made the requested changes; please review again

2021-07-21 23:40 UTC, rhyn0 requested changes
I think `name` is still missing an underscore on the tail end and that is why this hasn't been merged
https://github.com/python/cpython/pull/15359#discussion_r323249839

2021-09-03 14:08 UTC, MichaelAnckaert commented
Updated PR with requested changes.

2022-05-08 21:39 UTC, JelleZijlstra commented
We're still missing `__spec__` which @ericsnowcurrently asked for.

2022-08-27 11:39 UTC, DarshitSolanki04 commented
If it is possible, I would like to help. Since I am learning, it would be a pleasant experience for me.

2022-08-27 11:50 UTC, DarshitSolanki04 commented
If it is possible, I would like to help. Since I am learning, it would be a great learning opportunity for me.

2022-08-29 14:46 UTC, DarshitSolanki04 commented
If it is possible, I would like to help. I might need a little guidance to know what text to be written exactly.

2022-09-26 03:05 UTC, slateny commented
@MichaelAnckaert Are you still interested in giving this PR a quick update?

2022-10-02 22:56 UTC, slateny commented
I'll start on a separate PR here and close this when that's open, let me know if you'd like to continue this PR.

2022-10-09 03:54 UTC, slateny commented
See #98116

2022-10-09 03:54 UTC, closed without merging