Fix typo and remove redundant fix type.
python/cpython pull request #15402
Opened 2019-08-22 21:42 UTC by GeeTransit

2019-08-23 02:17 UTC, eamanu approved these changes

2019-08-23 03:50 UTC, aeros requested changes
Thanks for the PR @GeeTransit.

I agree with the typo correction, but it should still be mentioned that this change involves the IDLE.

2019-08-23 03:50 UTC, aeros167 commented on Misc/NEWS.d/next/IDLE/2019-08-04-17-10-01.bpo-36419.TJZqOc.rst
> +Refactor autocomplete and improve testing.
```suggestion
Refactor IDLE autocomplete and improve testing.
```

2019-08-23 04:16 UTC, GeeTransit commented on Misc/NEWS.d/next/IDLE/2019-08-04-17-10-01.bpo-36419.TJZqOc.rst
> +Refactor autocomplete and improve testing.
Yup, this sounds good too!

2019-08-23 05:04 UTC, aeros approved these changes
Thanks for making the recommended changes.

2019-08-23 08:38 UTC, raulcd approved these changes

2019-08-24 17:01 UTC, merged

2019-08-24 17:01 UTC, miss-islington commented
Thanks @GeeTransit for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-08-24 17:44 UTC, miss-islington commented
Thanks @GeeTransit for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-08-24 17:44 UTC, miss-islington commented
Thanks @GeeTransit for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-08-24 18:11 UTC, terryjreedy commented
I mis-hit the merge button while editing the title, such that Miss I. could not report success here.  I reverted and will make a new PR.