bpo-15542: Documentation incorrectly suggests __init__ called after direct  __new__ call
python/cpython pull request #15478
Opened 2019-08-24 23:19 UTC by nanjekyejoannah

C-Authored by : Aaron.Staley

Clarify data model documentation.

cc @cjerdonek

2019-08-24 23:20 UTC, nanjekyejoannah commented
@willingc , help me apply the skip news entry on this PR.

2019-08-25 04:41 UTC, rhettinger requested changes

2019-08-25 04:41 UTC, rhettinger commented on Doc/reference/datamodel.rst
> +   instance of *cls*, then the new instance’s :meth:`__init__` method will be
Substitute "instance or subclass of cls" for "instance of cls"

2019-08-25 18:13 UTC, nanjekyejoannah commented
I have made the requested changes; please review again .

2019-08-25 23:02 UTC, willingc approved these changes
Looks as if the requested changes are applied. Thanks @nanjekyejoannah and Raymond.

2019-08-26 06:52 UTC, rhettinger approved these changes

2019-08-26 06:53 UTC, merged

2019-08-26 06:53 UTC, miss-islington commented
Thanks @nanjekyejoannah for the PR, and @rhettinger for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖