bpo-34769: Restore instantiation Windows IOCP event loop from non-main thread
python/cpython pull request #15492
Opened 2019-08-25 15:12 UTC by asvetlov

2019-08-25 22:36 UTC, aeros requested changes
Thanks for the PR @asvetlov, I think this PR is more extensive than the initial one I created (https://github.com/python/cpython/pull/15477, just included the bug fix), so I closed mine.

I have a few minor suggestions:

2019-08-25 22:36 UTC, aeros commented on Lib/test/test_asyncio/test_windows_events.py
> +        self.assertTrue(finished)
Good idea with regards to adding tests to ensure that further optimizations/changes don't accidentally recreate the bug.

2019-08-25 22:36 UTC, aeros commented on Misc/NEWS.d/next/Library/2019-08-25-18-07-48.bpo-34679.HECzL7.rst
> +Restore instantiation Windows IOCP event loop from non-main thread.
Minor grammar nit:
```suggestion
Restores instantiation of Windows IOCP event loops from the non-main thread.
```

I was also thinking that it might be helpful to add brief entry to the [glossary](https://docs.python.org/3.8/glossary.html) for IOCP. Readers unfamiliar with async terminology might not be aware of what the acronym stands for or what it's referring to. This could be done in a separately, in another PR.

```
Input/output completion ports. IOCP is an API used for handling
concurrent asynchronous IO operations by associating each port
object with a variable number of sockets or file descriptors.
```

If we add this in to master and backport it to 3.8 in a separate PR, I can later edit the "What's New" for 3.8 to link to the glossary term with a sphinx role: ``` :term:`IOCP` ```. Let me know what you think.

2019-08-25 22:36 UTC, aeros167 commented on Lib/asyncio/proactor_events.py
> +            # wakeup fd can be installed from main thread only
Minor clarification/nit: 

```suggestion
            # wakeup fd can only be installed to a file descriptor from the main thread
```

2019-08-25 23:44 UTC, gvanrossum approved these changes
Please change the news file per suggestion from @aeros167 (I wasn't able to commit it).

2019-08-26 09:37 UTC, asvetlov commented on Misc/NEWS.d/next/Library/2019-08-25-18-07-48.bpo-34679.HECzL7.rst
> +Restore instantiation Windows IOCP event loop from non-main thread.
I agree that adding IOCP to glossary makes sense in general. 
Sorry, don't want to do it here just for change note. The note has a high chance of dropping from release note: there is no python stable release where the regression is present, only 3.8 betas. Maybe I'm wrong, release notes editor should decide.
Anyway, adding IOCP term requires its usage in asyncio docs, not only news record. That's why the term requires a separate PR.

2019-08-26 09:38 UTC, asvetlov commented
@gvanrossum @aeros167 thanks the review.
All notes are fixed.

2019-08-26 09:51 UTC, merged

2019-08-26 09:51 UTC, miss-islington commented
Thanks @asvetlov for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-08-27 00:58 UTC, aeros commented on Misc/NEWS.d/next/Library/2019-08-25-18-07-48.bpo-34679.HECzL7.rst
> +Restore instantiation Windows IOCP event loop from non-main thread.
>I agree that adding IOCP to glossary makes sense in general.

> Sorry, don't want to do it here just for change note. The note has a high chance of dropping from release note: there is no python stable release where the regression is present, only 3.8 betas. 

@asvetlov Sounds good, that's why I was thinking of adding the term in a separate PR. I seem to recall the term being used in the docs a couple of times. From a preliminary search of the repository using the one on GitHub, the term comes up around 6 times throughout various areas of asyncio not including news entries (including in code comments and as part of ``IocpProactor``). When I get around to opening the PR for it I'll probably include git grep results for a more thorough count of its usage.