bpo-30076: Rename the BUILD_{TUPLE,MAP}_UNPACK_WITH_CALL opcodes
python/cpython pull request #15513
Opened 2019-08-26 10:24 UTC by ZackerySpytz

2019-08-26 12:29 UTC, serhiy-storchaka commented on Lib/importlib/_bootstrap_external.py
> +MAGIC_NUMBER = (3421).to_bytes(2, 'little') + b'\r\n'
No magic number update is needed. The bytecode itself will not be changed, just human names of some opcodes.

2019-08-26 12:29 UTC, serhiy-storchaka commented on Lib/test/test_dis.py
> +            if opname in ('BUILD_VAR_KEYWORD', 'BUILD_VAR_POSITIONAL'):
Remove it at all. This workaround no longer needed.

2019-08-26 15:22 UTC, ZackerySpytz commented on Lib/importlib/_bootstrap_external.py
> +MAGIC_NUMBER = (3421).to_bytes(2, 'little') + b'\r\n'
Hmm, I see.

2019-08-26 16:02 UTC, serhiy-storchaka approved these changes

2019-09-03 11:03 UTC, ncoghlan requested changes
The general update here looks good, but I think I made a mistake in my naming suggestion back in 2017 (short version: I now think the new opcodes should be `BUILD_ARG_*` rather than `BUILD_VAR_*`, see the BPO issue for the details).

2020-01-16 09:47 UTC, csabella commented
@ZackerySpytz, please address the code review.  Thanks!

2021-10-20 15:53 UTC, closed without merging