bpo-37798: Fix _statistics module doc
python/cpython pull request #15546
Opened 2019-08-27 08:58 UTC by corona10

2019-08-27 09:00 UTC, corona10 commented
@rhettinger 
I found my mistake. Module doc should be updated. Please take a look.
Backport patch needed which affected by https://github.com/python/cpython/pull/15266

2019-09-03 01:46 UTC, corona10 commented
@rhettinger ping

2019-09-03 08:40 UTC, taleinat requested changes

2019-09-03 08:40 UTC, taleinat commented on Modules/_statisticsmodule.c
> +"statistics accelerator\n");
```suggestion
"Accelerators for the statistics module.\n");
```

2019-09-03 08:40 UTC, taleinat commented on Misc/NEWS.d/next/Library/2019-08-27-17-56-51.bpo-37998.Blh9So.rst
> +Fix _statistics module doc. Patch by Dong-hee Na.
I don't think a NEWS entry is need for a small fix to an unreleased change.

2019-09-03 08:57 UTC, corona10 commented
@taleinat Thank you for the review. I've updated the PR :)

2019-09-03 09:20 UTC, taleinat commented
@corona10, great!

FYI, in the future, if you include "I have made the requested changes; please review again" in your comment, our Bedevere bot will understand, change the status labels accordingly and mention the relevant core devs.

2019-09-03 09:21 UTC, taleinat approved these changes
LGTM

2019-09-03 09:21 UTC, merged

2019-09-03 09:21 UTC, miss-islington commented
Thanks @corona10 for the PR, and @taleinat for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖