bpo-37964: add F_GETPATH command in fcntl module
python/cpython pull request #15550
Opened 2019-08-27 15:54 UTC by vinay0410

2019-08-28 01:54 UTC, benjaminp requested changes
Please also a `.. versionchanged` directive about it to `Doc/library/fcntl.rst`.

2019-08-28 04:17 UTC, vinay0410 commented
I have made the requested changes; please review again
I have also added a test, testing this command/flag on macos.

2019-08-29 01:37 UTC, benjaminp approved these changes

2019-08-29 01:50 UTC, miss-islington commented
@vinay0410: Status check is done, and it's a failure ❌ .

2019-08-29 01:50 UTC, miss-islington commented
@vinay0410: Status check is done, and it's a failure ❌ .

2019-08-29 01:55 UTC, miss-islington commented
@vinay0410: Status check is done, and it's a failure ❌ .

2019-08-29 01:56 UTC, miss-islington commented
@vinay0410: Status check is done, and it's a success ✅ .

2019-08-29 01:56 UTC, merged