bpo-23878: Remove the key parameter of _Py_FindEnvConfigValue()
python/cpython pull request #15555
Opened 2019-08-27 21:38 UTC by ZackerySpytz

Suggested by @vstinner in GH-15424.

https://bugs.python.org/issue23878

2019-08-28 22:01 UTC, vstinner commented on Python/pathconfig.c
>  /* Search for a prefix value in an environment file (pyvenv.cfg).
It doesn't search "for a prefix". It searchs for the the line "home=<path>" and return `<path>`. It tolerates whitespaces around "=".

2019-08-28 22:02 UTC, vstinner commented
IMO it's fine to reuse https://bugs.python.org/issue23878 for this cleanup change. It gives more context about this change, than no bpo number.

2019-09-09 14:33 UTC, zooba requested changes
If we're going to remove the key argument, we should also rename the function to reflect that it only finds `home` somehow.

Personally, I see no benefit here, and we may as well leave it alone. But if others think it's cleaner to have `_Py_FindEnvConfigHomeValue` instead of specifying `L"home"` in the call, I'm not going to fight it.

2020-02-04 12:20 UTC, csabella commented
@ZackerySpytz, please resolve the merge conflicts and address the code review.  If this change is no longer relevant, please close the PR.  Thanks!

2020-05-23 00:33 UTC, csabella commented
@ZackerySpytz ping

2021-07-30 14:00 UTC, iritkatriel commented
https://bugs.python.org/issue23878 is closed. What is that status of this PR?

2021-08-04 14:21 UTC, vstinner commented
This PR is still relevant, but it's outdated. @ZackerySpytz: can you please rebase it on the main branch? Or create a new PR.

2022-04-14 11:42 UTC, kumaraditya303 commented
Closing as it is outdated and bpo is closed, if required a new PR can be opened or this can reopened.

2022-04-14 11:42 UTC, closed without merging