Improve message for openssl lookup
python/cpython pull request #15556
Opened 2019-08-27 23:54 UTC by vhquang

This is a re-open from #15082 , in which one of my reviewers suggested it go on `master`. It is a cosmetic change on the display message, so I don't think any issue number is needed.

Rationale for the change:
> I was trying to test the pre-release 3.8b3, and since I have multiple installation of OpenSSL, having this improved message with more specific on which type of OpenSSL header would be needed, will definitely make my hunt go easier.

It is still my first PR to Python, so kindly let me know if anything else that I can improve.

2019-08-28 02:21 UTC, brandtbucher approved these changes

2019-08-28 11:42 UTC, tiran requested changes
The configure file is auto-generated from configure.ac and m4 macro files. You cannot modify the generated output. It will be overwritten the next time the configure script is regeerated.

The OpenSSL detection code uses https://www.gnu.org/software/autoconf-archive/ax_check_openssl.html . Please take this up to the author of the m4 macro for ax_check_openssl. I don't want to deviate from upstream sources.

2019-08-29 02:22 UTC, vhquang commented
I didn't know the configure script is generated by `autoconf-archive/ax_check_openssl.m4`. I agree let take this upstream.
Thanks Christian and Brandt for the pointers!

2019-08-29 02:23 UTC, vhquang commented
Bring the change to `autoconf-archive` instead of here.

2019-08-29 02:23 UTC, closed without merging

2019-09-01 15:55 UTC, vhquang commented
@tiran Just to close the loop, the change we discussed is merged upstream. Do I need to do anything in CPython so we will pick up the change? If so, can you give me few pointers?