bpo-23674:  Clarify ambiguities in super() docs
python/cpython pull request #15564
Opened 2019-08-28 17:56 UTC by rhettinger

https://bugs.python.org/issue23674

2019-08-28 22:12 UTC, geryogam requested changes
Thank you @rhettinger, finally you did it before me. Here are a few change suggestions.

2019-08-28 22:12 UTC, maggyero commented on Doc/library/functions.rst
>     class of *type*.  This is useful for accessing inherited methods that have
```suggestion
    class of *object-or-type*.  This is useful for accessing inherited methods that have
```

2019-08-28 22:12 UTC, maggyero commented on Doc/library/functions.rst
>     The :attr:`~class.__mro__` attribute of the *type* lists the method
```suggestion
```

2019-08-28 22:12 UTC, maggyero commented on Doc/library/functions.rst
>     resolution search order used by both :func:`getattr` and :func:`super`.  The
```suggestion
    The :attr:`~class.__mro__`
```

2019-08-28 23:27 UTC, rhettinger commented on Doc/library/functions.rst
>     class of *type*.  This is useful for accessing inherited methods that have
I believe *type* is correct.

2019-08-28 23:28 UTC, rhettinger commented on Doc/library/functions.rst
>     The :attr:`~class.__mro__` attribute of the *type* lists the method
This one should be ``object-or-type``

2019-08-28 23:29 UTC, rhettinger commented on Doc/library/functions.rst
>     resolution search order used by both :func:`getattr` and :func:`super`.  The
I prefer the wording that references both *getattr* and *super*.  Those two are deeply related.

2019-08-29 06:29 UTC, maggyero commented on Doc/library/functions.rst
>     class of *type*.  This is useful for accessing inherited methods that have
Sorry my bad, _type_ is indeed correct here.

2019-08-29 06:42 UTC, maggyero commented on Doc/library/functions.rst
>     The :attr:`~class.__mro__` attribute of the *type* lists the method
Exactly.

2019-08-29 07:44 UTC, merged

2019-08-29 07:44 UTC, miss-islington commented
Thanks @rhettinger for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-08-29 07:54 UTC, miss-islington commented
Thanks @rhettinger for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖