bpo-30353 Fix pass by value for structs on 64-bit Cygwin/MinGW
python/cpython pull request #1559
Opened 2017-05-12 16:27 UTC by embray

Fixes bpo-30353 by making additional stack allocations for structs and copying the struct data (as libffi would do otherwise).

2017-05-19 09:39 UTC, embray commented
Per [discussion](https://bugs.python.org/issue30353#msg293600) on [bpo-30353](https://bugs.python.org/issue30353), I've updated this to apply the same workaround for builds on arm64, which has a similar bug in libffi ([bpo-29804](https://bugs.python.org/issue29804)).

2017-05-20 11:50 UTC, vsajip requested changes

2017-05-20 11:50 UTC, vsajip commented on Modules/_ctypes/callproc.c
> +        if (pa->ffi_type->type == FFI_TYPE_STRUCT) {
Is this definitely the correct test? Similar code to fix bpo-29565 uses a test of the type's size being greater than 8 bytes. Have you tested with structs both under and over this size limit?

2017-05-20 11:50 UTC, vsajip commented on Modules/_ctypes/callproc.c
> +        void *tmp;
Any reason this declaration can't be inside the `if` block? It's only ever used in that block.

2017-05-22 09:25 UTC, embray commented on Modules/_ctypes/callproc.c
> +        void *tmp;
I'm not sure what you mean.  It is inside the if block.

2017-05-22 09:29 UTC, embray commented on Modules/_ctypes/callproc.c
> +        if (pa->ffi_type->type == FFI_TYPE_STRUCT) {
Oh, I didn't see that issue--interesting.  I might be able to adapt the existing fix there to this issue as well.

As to whether or not it impacts just structs or any value > 8 bytes I'm not sure off the top of my head anymore.  I'll have to double-check.

2017-05-22 11:14 UTC, vsajip commented on Modules/_ctypes/callproc.c
> +        void *tmp;
By my reading, it's inside the `#if` block, but not inside the `if (pa->ffi_type->type == FFI_TYPE_STRUCT) {` block.

2017-05-22 12:18 UTC, embray commented on Modules/_ctypes/callproc.c
> +        void *tmp;
You you meant the actual if statement.  I don't mind moving it, but I don't see what difference it makes--it generates the exact same assembly either way.

2017-05-22 16:50 UTC, vsajip commented on Modules/_ctypes/callproc.c
> +        void *tmp;
Just a little tidier. The reference (`tmp`) stays in the scope in which it's used.

2017-05-23 08:59 UTC, embray commented on Modules/_ctypes/callproc.c
> +        void *tmp;
I don't really agree--I find variable declarations in an if statement pretty ugly, but I can't disagree it at least limits it scope (even if it's ultimately irrelevant).  Maybe I'll change it if/when there are other more substantive changes to make.

2017-05-23 09:34 UTC, embray commented on Modules/_ctypes/callproc.c
> +        if (pa->ffi_type->type == FFI_TYPE_STRUCT) {
@vsajip Okay, I think you're right here--the issue is basically the same as the old libffi_msvc code that's backported into ctypes--my changes actually cause a segfault if a small (<=8 bytes) struct is passed by value, so I should add a test for that.

2017-05-23 09:37 UTC, embray commented on Modules/_ctypes/callproc.c
> +        void *tmp;
Sorry, I think my last comment came off as disrespectful--to be clear I have no problem with changing this later (I just meant I won't bother making a separate commit for it).

2017-05-23 09:41 UTC, embray commented on Modules/_ctypes/callproc.c
> +        if (pa->ffi_type->type == FFI_TYPE_STRUCT) {
Oops, I should say, it doesn't cause a segfault (that was just a minor typo on my part). But regardless the fix is not needed for smaller structs which are, as expected, passed by value in registers.

2017-05-23 10:21 UTC, embray commented on Modules/_ctypes/callproc.c
> +        if (pa->ffi_type->type == FFI_TYPE_STRUCT) {
I should correct myself again--actually it is needed for smaller structs if they are not register-aligned.

2017-05-23 10:49 UTC, vsajip commented on Modules/_ctypes/callproc.c
> +        void *tmp;
No offence taken :smile:

> I find variable declarations in an if statement pretty ugly

As far as I know, it's considered good practice for declarations to be limited to the scope of the blocks where they're used, as long as the version of C in use permits it. There's nothing special about an `if` block here - one would do the same for `for`, `while`, `do` etc.

> I won't bother making a separate commit for it

I wouldn't worry too much about that; commits are cheap and would normally be squashed on merge, anyway.

2017-05-23 14:28 UTC, embray commented
Okay, I reworked this a bit.  I realized while figuring out that was going on that smaller structs that *do* fit in a register were actually not working properly (and I added a test for this).  This is because libffi is currently pretty dumb about how it treats arguments.  It only looks at the argument size, and if it's not 1, 2, 4, or 8 bytes it assumes the argument is a pointer and it puts that pointer on its stack.  However, for structs of size 1/2/4/8 bytes the existing behavior (before my earlier fix) was correct because it libffi is passed the pointer to the struct value, and it treats this (e.g. for an 8 byte struct) as a uint64 pointer which it dereferences and copies the value.

2017-05-24 08:17 UTC, embray commented
Looks like the Windows build on appveyor died for seemingly unrelated reasons.

2017-06-07 17:42 UTC, merged

2017-06-08 07:42 UTC, embray commented
Thanks!

2017-06-12 16:03 UTC, stratakis commented
@embray would you be able to create a PR for the 3.6 branch?

2017-06-12 20:20 UTC, vsajip commented
There's no need, the way to do it is to cherry-pick that commit to the 3.6 branch - I'll look at it soon.

2018-03-01 21:09 UTC, miss-islington commented
Thanks @embray for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6.
🐍🍒⛏🤖