bpo-22702: Improves documentation for str.join method
python/cpython pull request #156
Opened 2017-02-18 11:12 UTC by CuriousLearner

Fixes issue http://bugs.python.org/issue22702

2017-02-18 11:12 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-18 17:08 UTC, DimitrisJim commented
Hi @CuriousLearner! The original text seems fine to me, why do you think this change is warranted?

2017-02-18 17:26 UTC, CuriousLearner commented
Hi @DimitrisJim !

As in the issue Raymond & others mentioned that at least the usage of repeated `iterable` word should be removed. Moreover, in general to make the docstring less verbose, this change is suggested.

Is there something else wanted in this PR?

2017-02-18 17:34 UTC, DimitrisJim commented
Yes the double use of iterable is odd here, my view is that that is the only thing needing change. 

"separated by the string ``str`` provided in this method" seems more confusing to me than the original sentence, though.

2017-02-19 10:12 UTC, CuriousLearner commented
Sure, I've done the changes as suggested.

2017-02-20 16:51 UTC, CuriousLearner commented
CLA is signed and now visible in my account.

cc @ncoghlan

2017-02-22 10:26 UTC, zhangyangyu commented on Doc/library/stdtypes.rst
> +   :term:`iterable`. A :exc:`TypeError` will be raised if there are
IMHO \*iterable* should be left, referring the parameter.

2017-03-01 16:45 UTC, wm75 commented
I don't think anything should be changed here. The double iterable is much less disturbing when formatted as html.

2017-03-01 17:42 UTC, marco-buttu requested changes
IMO it should be just  "in *iterable* " and not "in the :term:`iterable`, as it is in the rest of the file when referring to the parameter *iterable*. Furthermore, you should apply the same modification to the `bytearray.join()` description, and add a second whitespace after the dot, before "A :exc:`TypeError`.

2017-04-09 09:58 UTC, ncoghlan commented
@CuriousLearner Sorry for the delayed review, but I'm inclined to agree with @marco-buttu here - the iterable to drop is the term reference, rather than the parameter name.

See http://bugs.python.org/issue22702#msg291366 for further discussion.

2017-04-12 15:48 UTC, CuriousLearner commented
Hi @marco-buttu & @ncoghlan !

I've made the changes according to earlier review. Please review :)

2017-04-13 09:22 UTC, marco-buttu requested changes
Just a minor change.  The rest LGTM.

2017-04-13 09:22 UTC, marco-buttu commented on Doc/library/stdtypes.rst
> +   *iterable*, including :class:`bytes` objects. The separator between
Could you please add an extra whitespace after the period?  I mean, two whitespaces between `objects.` and `The separator`.

2017-04-13 16:29 UTC, CuriousLearner commented
Hi @marco-buttu ! I've updated the patch. Can you please take a look?

2017-04-13 20:40 UTC, marco-buttu approved these changes
Thank you, ok to me :-)

2017-05-10 10:28 UTC, berkerpeksag commented on Doc/library/stdtypes.rst
> +   binary data sequences in the *iterable*.  A :exc:`TypeError` will be
You dropped "the" before \*iterable\* in str.join() documentation, but kept it here. Is there a reason to keep it here?

2017-05-10 10:40 UTC, CuriousLearner commented on Doc/library/stdtypes.rst
> +   binary data sequences in the *iterable*.  A :exc:`TypeError` will be
@berkerpeksag  I don't remember any specific reason for that. Should I include `the` in `str.join()` documentation?

2017-05-10 10:52 UTC, berkerpeksag commented on Doc/library/stdtypes.rst
> +   binary data sequences in the *iterable*.  A :exc:`TypeError` will be
I'm not a native speaker so I'll defer the decision to @ncoghlan :)

2017-05-10 11:17 UTC, ncoghlan commented on Doc/library/stdtypes.rst
> +   binary data sequences in the *iterable*.  A :exc:`TypeError` will be
We want to drop it - "*iterable*" refers specifically to the method parameter rather than the general term, so it doesn't need "the" in front of it.

2017-05-10 11:30 UTC, CuriousLearner commented on Doc/library/stdtypes.rst
> +   binary data sequences in the *iterable*.  A :exc:`TypeError` will be
@ncoghlan @berkerpeksag I've fixed it.

Is there something else needed for this PR?

2017-05-27 05:44 UTC, merged

2017-05-28 05:06 UTC, ncoghlan commented
Added the sprint label, as this PR was submitted at the PyCon Pune 2017 core development sprint.