bpo-36409: Remove old plistlib API deprecated in 3.4
python/cpython pull request #15615
Opened 2019-08-30 17:51 UTC by Bigfootjon

Also cleanup the documentation

2019-09-04 12:37 UTC, ronaldoussoren requested changes
The patch looks good to me, except for one minor issue.

2019-09-04 12:37 UTC, ronaldoussoren commented on Doc/whatsnew/3.9.rst
> +
Please also mention that the "use_builtin_types" parameter was removed.

2019-09-04 14:53 UTC, ronaldoussoren commented on Doc/whatsnew/3.9.rst
> +
Thanks.

2019-09-04 14:58 UTC, ronaldoussoren requested changes
Just one more nit to pick... 

I will merge once this is changed and the CI passes.

2019-09-04 14:58 UTC, ronaldoussoren commented on Doc/whatsnew/3.9.rst
> +  functions. Additionally, the `use_builtin_types` parameter was removed,
There is a CI failure due to the way `use_buitin_types` is written.  Please use double backticks.

2019-09-04 16:59 UTC, Bigfootjon commented
Thank you for the quick turnaround and tips @ronaldoussoren, I appreciate the help!

I have made the requested changes; please review again

2019-09-05 08:10 UTC, ronaldoussoren approved these changes
Patch looks good to me.

2019-09-05 08:11 UTC, merged

2019-09-05 08:12 UTC, ronaldoussoren commented
@Bigfootjon Thanks for your patch!

2020-10-31 10:00 UTC, justvanrossum commented
It appears the removal of the `use_builtin_types` argument to `load()` was not preceded by a deprecation phase. That makes this a rather hard breaking change. See for example github.com/unified-font-object/ufoNormalizer/issues/73 and downstream issues.