bpo-36876: Make some static string literal arrays constant.
python/cpython pull request #15760
Opened 2019-09-09 11:30 UTC by ericsnowcurrently

This gives us guarantees about immutability.

2019-09-09 12:29 UTC, 1st1 approved these changes

2019-09-09 12:31 UTC, pganssle requested changes
Looks good overall, a few formatting nits around whitespace I found.

2019-09-09 12:31 UTC, pganssle commented on Modules/_datetimemodule.c
> +                                "tzinfo", "fold", NULL};
I think this got mis-aligned.

```suggestion
                                 "tzinfo", "fold", NULL};
```

2019-09-09 12:31 UTC, pganssle commented on Modules/_decimal/_decimal.c
> +    static const char *kwlist[] = {"context", NULL};                            \
```suggestion
    static const char *kwlist[] = {"context", NULL};                      \
```

2019-09-09 12:31 UTC, pganssle commented on Modules/_decimal/_decimal.c
> +    static const char *kwlist[] = {"context", NULL};                 \
```suggestion
    static const char *kwlist[] = {"context", NULL};           \
```

2019-09-09 12:31 UTC, pganssle commented on Modules/_decimal/_decimal.c
> +    static const char *kwlist[] = {"other", "context", NULL};          \
Few other alignment issues like the ones above - probably best to align the newline escapes as above.

2019-09-09 12:33 UTC, pganssle commented on Modules/_multiprocessing/semaphore.c
>                               NULL};
```suggestion
                                   NULL};
```

I think this is the right number of spaces to re-align this...

2019-09-09 12:36 UTC, pganssle requested changes
Here are all the alignment issues I found. Hopefully the "suggestions" are the right number of spaces.

2019-09-09 12:36 UTC, pganssle commented on Modules/mmapmodule.c
> +    static const char *keywords[] = { "fileno", "length",
Next two lines are also misaligned.

2019-09-09 12:36 UTC, pganssle commented on Modules/posixmodule.c
>                                  "offset", "count",
Alignment here again.

2019-09-09 12:36 UTC, pganssle commented on Modules/posixmodule.c
> +    static const char *keywords[] = {"out", "in",
Alignment again.

2019-09-09 12:36 UTC, pganssle commented on Modules/selectmodule.c
>                               "data", "udata", NULL};
```suggestion
                                   "data", "udata", NULL};
```

2019-09-09 12:36 UTC, pganssle commented on Python/_warnings.c
>                                  "module", "registry", "module_globals",
Alignment here again.

2019-09-10 06:22 UTC, serhiy-storchaka commented
Changing `char *kwlist[]` to `const char *kwlist[]` is incompatible change, because `PyArg_ParseTupleAndKeywords()` takes `char **` which is not compatible with `const char **`. The compiler should raise warnings or even errors about this. If not this this change would be made years ago.

It is possible to change the API, but it is long a complex process. It is a separate issue.

Adding consts in `Python/Python-ast.c` may be good, but this file is generated. You should modify the generating script.

2019-09-10 07:34 UTC, serhiy-storchaka commented
Note also that you can add two `const`s in `static char *something[]`: `static const char * const something[]`. One for C-strings, and other for an array.

See #15824 for changes in `Python/Python-ast.c`.

2019-09-10 15:46 UTC, ericsnowcurrently commented
Hmm, this won't work out.

2019-09-10 15:46 UTC, closed without merging

2021-02-24 10:52 UTC, georgthegreat commented
At the time there is a bunch of forgotten const / const_cast / `(char**)` c-style casts everywhere in `PyArg_ParseTupleAndKeywords` invocations.

The list includes the following pip packages (but definitely not limited to):

* [brotli](https://github.com/google/brotli/blob/63be8a99401992075c23e99f7c84de1c653e39e2/python/_brotli.cc#L462)
* [rapidjson](https://github.com/python-rapidjson/python-rapidjson/blob/dd69a997b8174be7f933cdd37853a97fe26b1e9e/rapidjson.cpp#L1542)
* [annoy](https://github.com/spotify/annoy/blob/be83fbae5760074e2de084c2d1fdc6e572b0fbaa/src/annoymodule.cc#L147)

Is there any way to continue working on the issue?

2021-02-25 11:36 UTC, georgthegreat commented
@serhiy-storchaka, could you, please, elaborate on

> It is possible to change the API, but it is long a complex process. It is a separate issue.)

At the time the lack of const causes problems i. e. when compiling in [MSVC standard conformance](https://docs.microsoft.com/ru-ru/cpp/build/reference/permissive-standards-conformance?view=msvc-160) mode (which is default for `/std:c++latest` / `/std:c++20`).