bpo-37499: Test various C calling conventions
python/cpython pull request #15776
Opened 2019-09-09 13:07 UTC by encukou

Add functions with various calling conventions to `_testcapi`, expose them as module-level functions, bound methods, class methods, and static methods, and test calling them and introspecting them through GDB.

2019-09-09 13:08 UTC, encukou commented
I started this on a train, and never got to finishing it up. Unfortunately it duplicates work in GH-14795.

2019-09-09 15:48 UTC, pganssle requested changes

2019-09-09 15:48 UTC, pganssle commented on Lib/test/test_call.py
> +class TestCallingConventionsFunction(TestCallingConventions):
Unnecessary?

2019-09-09 15:48 UTC, pganssle commented on Lib/test/test_call.py
> +@cpython_only
May not need this, PyPy has `cpyext` and supports the C API.

2019-09-09 16:15 UTC, encukou commented
I have made the requested changes; please review again.

2019-09-09 16:51 UTC, encukou commented
The `Function "meth_noargs" not defined.` warnings on stderr aren't easy to get rid of (without masking other warnings by redirecting stderr): See the [comment in get_stack_trace](https://github.com/python/cpython/blob/master/Lib/test/test_gdb.py#L156)

2019-09-10 10:50 UTC, pganssle approved these changes
This looks good to me, I think we can go ahead and merge.

@encukou Let me know if you have any problems with the changes I pushed in d8a28ab29e668e5d66824fdaec5bc59cf914e6a7.

Also, I had to rebase this against master to resolve a merge conflict, so you'll need to do a force pull or something equivalent if you want to push more commits.

2019-09-10 10:51 UTC, encukou commented on Lib/test/test_gdb.py
> +                        import _testcapi  # (not always needed)
```suggestion
                        import _testcapi
```

2019-09-10 11:03 UTC, miss-islington commented
@encukou: Status check is done, and it's a failure ❌ .

2019-09-10 11:15 UTC, miss-islington commented
@encukou: Status check is done, and it's a failure ❌ .

2019-09-10 11:21 UTC, miss-islington commented
@encukou: Status check is done, and it's a success ✅ .

2019-09-10 11:21 UTC, merged