bpo-38073: Make pwd module PEP 384 compatible
python/cpython pull request #15790
Opened 2019-09-09 15:16 UTC by DinoV

Makes the pwd module PEP-384 compatible

2019-09-09 15:37 UTC, matrixise requested changes

2019-09-09 15:37 UTC, matrixise commented on Misc/NEWS.d/next/Core and Builtins/2019-09-09-15-17-58.bpo-38073.ZoKYOU.rst
> +pwd module is now PEP-384 compatible
```
`:mod:`pwd` is :pep:`384` compatible
```

2019-09-09 15:37 UTC, matrixise commented on Modules/pwdmodule.c
> +  PyTypeObject *StructPwdType;
indent of 4?

2019-09-09 15:37 UTC, matrixise commented on Modules/pwdmodule.c
> +    if (state->StructPwdType == NULL)
```c
if (state->StructPwdType == NULL) {
    return NULL
}
```

2019-09-10 09:00 UTC, DinoV commented
I have made the requested changes; please review again.

2019-09-10 11:23 UTC, tiran approved these changes
LGTM, thanks!

2019-09-10 11:27 UTC, tiran requested changes

2019-09-10 11:27 UTC, tiran commented on Misc/NEWS.d/next/Core and Builtins/2019-09-09-15-17-58.bpo-38073.ZoKYOU.rst
> +`:mod:`pwd` is :pep:`384` compatible
sphinx doesn't like the reference here, please change the text to ``Make pwd extension module PEP-384 compatible``

2019-09-10 12:44 UTC, tiran approved these changes

2019-09-10 12:59 UTC, miss-islington commented
@DinoV: Status check is done, and it's a success ✅ .

2019-09-10 12:59 UTC, merged