bpo32972: Document IsolatedAsyncioTestCase of unittest.async_case module
python/cpython pull request #15878
Opened 2019-09-10 15:49 UTC by tirkarthi

* Document `unittest.async_case.IsolatedAsyncioTestCase` API
* Add a simple example with respect to order of evaluation of setup and teardown calls.

2019-09-10 18:22 UTC, asvetlov approved these changes
Looks good, thank you.

Please fix a couple notes

2019-09-10 18:22 UTC, asvetlov commented on Doc/library/unittest.rst
> +.. class:: async_case.IsolatedAsyncioTestCase(methodName='runTest')
The class is exported on the package level, e.g. `unittest.IsolatedAsyncioTestCase` works.
Please drop `async_case` prefix

2019-09-10 18:22 UTC, asvetlov commented on Doc/library/unittest.rst
> +      from unittest.async_case import IsolatedAsyncioTestCase
Drop `async_case` here

2019-09-10 18:22 UTC, asvetlov commented on Misc/NEWS.d/3.8.0b1.rst
> +Implement ``unittest.async_case.IsolatedAsyncioTestCase`` to help testing asyncio-based code.
```suggestion
Implement ``unittest.IsolatedAsyncioTestCase`` to help testing asyncio-based code.
```

2019-09-10 18:23 UTC, asvetlov requested changes
import paths should be fixed before the merge

2019-09-11 09:39 UTC, tirkarthi commented
Thanks Andrew, I didn't know about the import. It makes it more clean and user doesn't need to know about async_case module too. I have fixed the imports as per comments. I think this feature also deserves a better attention so I have added it to the What's new document under unittest section with a simple example. Thoughts?

2019-09-11 09:43 UTC, asvetlov commented
> I think this feature also deserves a better attention so I have added it to the What's new document under unittest section with a simple example. Thoughts?

Excellent idea! Please do

2019-09-11 09:44 UTC, tirkarthi commented
Sure, added at https://github.com/python/cpython/pull/15878/files#diff-77c703d9a958f6a4b0dc2f692b3fd5b3R1114 . Please review the wording and example.

2019-09-11 10:12 UTC, asvetlov reviewed
The example is fine. Please address my last comments.

2019-09-11 10:12 UTC, asvetlov commented on Doc/whatsnew/3.8.rst
> +            self.connection = await ExpensiveConnection()
```suggestion
            self.connection = await AsyncConnection()
```
Async is not necessary expensive :)

2019-09-11 10:12 UTC, asvetlov commented on Doc/library/unittest.rst
> +              self._async_connection = await ExpensiveAsyncConnection()
```suggestion
              self._async_connection = await AsyncConnection()
```

2019-09-11 10:12 UTC, asvetlov commented on Doc/library/unittest.rst
> +              response = await self._async_connection.get("https://example.com")
```suggestion
              events.append("test_response")
              response = await self._async_connection.get("https://example.com")
```

2019-09-11 10:12 UTC, asvetlov commented on Doc/library/unittest.rst
> +              response = self._sync_connection.get("https://example.com")
Please drop sync connection example.
These lines are correct but blow the example.

2019-09-11 10:12 UTC, asvetlov commented on Doc/library/unittest.rst
> +      test = Test("test_response")
Please avoid the usage of API that most users don't know. At least I've learned how to instantiate test-case years after starting to write unit tests; tests discovery works just fine for newbies.

I'd like to have something like "After running the test `events` contains `["setUp", "asyncSetUp", "test_response", "asyncTearDown", "tearDown", "cleanup"]`" sequence.

Does it make sense?

2019-09-11 10:28 UTC, tirkarthi commented
Thanks Andrew, I have reworded `ExpensiveAsyncConnection` to `AsyncConnection` . I have removed the sync_connection example and moved the events assertion out to docs with a statement as suggested.

Yes, test discovery works better and friendly. I must admit I copied the test from async_case as example which was the reason and I just learned about TestCase instantiation while writing this example :) Your suggestion is better and changed it to test discovery.

2019-09-11 10:31 UTC, asvetlov approved these changes
Perfect!

2019-09-11 10:32 UTC, asvetlov commented on Doc/library/unittest.rst
> +              self._sync_connection = ExpensiveSyncConnection()
Drop this line please

2019-09-11 10:32 UTC, asvetlov commented on Doc/library/unittest.rst
> +              self._sync_connection.close()
and this one

2019-09-11 10:33 UTC, asvetlov requested changes
there are two extra lines in example that should be dropped

2019-09-11 10:35 UTC, asvetlov approved these changes
Thank you very much!
Done well

2019-09-11 10:35 UTC, tirkarthi commented
Ah sorry, I removed the connection example and overlooked the setup and teardown which is not used. Thanks.

2019-09-11 10:45 UTC, tirkarthi commented
Thank you very much Andrew for all the guidance :)

2019-09-11 11:02 UTC, miss-islington commented
@tirkarthi: Status check is done, and it's a success ✅ .

2019-09-11 11:02 UTC, merged

2019-09-11 11:02 UTC, miss-islington commented
Thanks @tirkarthi for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖