bpo-38113: Update the Python-ast.c generator to PEP384
python/cpython pull request #15957
Opened 2019-09-11 14:06 UTC by DinoV

Summary: This mostly migrates Python-ast.c to PEP384 and removes all statics from the whole file. This modifies the generator itself that generates the Python-ast.c.  It leaves in the usage of _PyObject_LookupAttr even though it's not fully PEP384 compatible (this could always be shimmed in by anyone who needs it).

2019-09-11 14:31 UTC, ericsnowcurrently approved these changes
LGTM

2019-09-11 15:26 UTC, tiran requested changes

2019-09-11 15:26 UTC, tiran commented on Parser/asdl_c.py
> +                      f"astmodulestate_global->{t.name}_type);", 1)
You cannot use f-strings here. Some platforms like old Ubuntu have python3 3.5 or older. Travis CI is failing with a SyntaxError.

2019-09-11 17:16 UTC, merged

2019-09-13 04:07 UTC, eduardo-elizondo commented on Parser/asdl_c.py
> +        self.emit("((PyTypeObject*)state->AST_type)->tp_dictoffset = offsetof(AST_object, dict);", 1)
This is still accessing the dict offset, we need to remove this by letting the type system handle it