bpo-25324: copy tok_name before changing it
python/cpython pull request #1608
Opened 2017-05-16 15:44 UTC by albertjan

Saw this open bug report, and since I was looking at tokenize.py anyway. I figured I address it. 

This may catch people off guard though because they may be relying on `tok_name` containing `ENCODING`, `COMMENT` and `NL`. 🤷‍♂️

2017-05-16 15:44 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-05-16 16:24 UTC, serhiy-storchaka commented on Lib/test/test_tokenize.py
> +                     open as tokenize_open, Untokenizer, tok_name as tokenize_tok_name)
Too long line.

2017-05-16 20:54 UTC, haypo commented on Lib/test/test_tokenize.py
> +                         tokenize_tok_name[ENCODING])
I would prefer to import the tokenize module and write tokenize.tok_name.

I know that this file uses "from tokenize import ..." but this pattern is unusual in the Python test suite.

2017-05-16 21:04 UTC, vstinner requested changes
I'm not sure that it's the right way to fix the issue: see http://bugs.python.org/issue25324 discussion. I also have comments on the change itself, but I will want until we agree on the way to fix the issue before reviewing the change.

2017-05-16 21:44 UTC, brettcannon commented
Due to a new release of Sphinx, we had to fix the documentation to build on Travis again. Please do a merge to get these changes to help get Travis passing on your PR.

2017-05-25 11:13 UTC, vstinner requested changes

2017-05-25 11:13 UTC, haypo commented on Lib/token.py
> +COMMENT = 56
Please don't change ERRORTOKEN value.

2017-05-25 11:13 UTC, haypo commented on Include/token.h
> +/* These aren't used by the c tokenizer but are needed for tokenize.py */
Niypick: replace c with C.

2017-05-25 11:13 UTC, haypo commented on Lib/token.py
> +COMMENT = 56
Please copy token.h comment here.

2017-05-30 09:28 UTC, albertjan commented
Updated the PR. comments are now copied from token.h to token.py automatically. And I moved ERRORTOKEN back to where it was.

2017-05-30 11:00 UTC, vstinner reviewed
LGTM, but I added a new (last I hope) serie of nitpicking comments :-p

2017-05-30 11:00 UTC, haypo commented on Lib/test/test_tokenize.py
> -
This change is not PEP 8 compliant :-)

2017-05-30 11:00 UTC, haypo commented on Lib/token.py
> +        "^\s*/\*\s*(.+)\s*\*/\s*$",
This string emits:

```
<stdin>:1: DeprecationWarning: invalid escape sequence \s
```

I suggest to always use raw strings for regular expressions.

2017-05-30 11:00 UTC, haypo commented on Lib/token.py
> +            tokens[prev_val] = {'token': name}          # reverse so we can sort them...
I would prefer to use val here, but set prev_val after the tokens assignement. Here we use the current value, not the previous value.

2017-05-30 11:00 UTC, haypo commented on Lib/token.py
> +            if comment_match and prev_val:
"prev_val is not None" to support prev_val == 0 (ENDMARKER = 0).

2017-05-30 11:00 UTC, haypo commented on Lib/token.py
> +                val = comment_match.group(1)
nitpick: i suggest to rename the variable "comment".

2017-05-30 11:00 UTC, haypo commented on Lib/token.py
>      for val in keys:
nitpick: I suggest to rename "val" to "key" to be more consistent.

2017-05-30 11:48 UTC, albertjan commented
This should address your comments. Thanks for taking the time to review my PR.

2017-05-30 11:53 UTC, vstinner approved these changes
LGTM. I will merge the change once tests pass.

2017-05-30 12:08 UTC, serhiy-storchaka commented
Please wait with merging. I'm finishing my patch for generating `token.h` from `token.py`.

2017-05-30 12:09 UTC, haypo commented
> Please wait with merging. I'm finishing my patch for generating token.h from token.py.

Wait? Do you expect conflicts?

2017-05-30 12:14 UTC, serhiy-storchaka commented
Yes, conflicts, and maybe this will lead to redesigning both patches.

2017-05-31 08:24 UTC, haypo commented on Misc/NEWS
> +  ``NL`` AND ``ENCODING``. This way the tokens and tok_names in token.py
and: lower case

in token.py: in the token module

import tokenize.py: import the tokenize module.

2017-05-31 08:42 UTC, albertjan commented
Should I do a merge or a rebase to resolve the conflicts?

2017-05-31 08:55 UTC, haypo commented
> Should I do a merge or a rebase to resolve the conflicts?

As you want.

2017-05-31 10:16 UTC, serhiy-storchaka submitted a review, later dismissed

2017-05-31 10:16 UTC, serhiy-storchaka commented on Misc/NEWS
> +- bpo-25324: Tokens needed for parsing in python moved to C. ``COMMENT``,
Python: title case.

2017-05-31 10:16 UTC, serhiy-storchaka commented on Doc/library/token.rst
> +      Added :data:`COMMENT`, :data:`NL` and :data:`ENCODING`. To bring
Isn't a period is redundant here?

2017-05-31 10:16 UTC, serhiy-storchaka commented on Doc/library/token.rst
> +      tokenize.py. These tokens aren't used by the C tokenizer.
tokenize.py -> the :mod:\`tokenize\` module

2017-05-31 14:00 UTC, merged

2017-05-31 14:00 UTC, vstinner commented
LGTM. Thanks @albertjan!

2017-06-24 22:05 UTC, ammaraskar commented
Hey @albertjan, did you manually edit token.py for this change? As part of my pr here for testing the round tripping of https://github.com/python/cpython/pull/681, it looks like your commit eats up the last token if its followed by a comment.

i.e currently the file generated by token.py looks something like this
```python
ATEQUAL = 50
RARROW = 51
# Don't forget to update the table _PyParser_TokenNames in tokenizer.c!
OP = 53
AWAIT = 54
ASYNC = 55
# These aren't used by the C tokenizer but are needed for tokenize.py
COMMENT = 57
NL = 58
ENCODING = 59
```

whereas the original token.py looks like
```python
ATEQUAL = 50
RARROW = 51
ELLIPSIS = 52
# Don't forget to update the table _PyParser_TokenNames in tokenizer.c!
OP = 53
AWAIT = 54
ASYNC = 55
ERRORTOKEN = 56
# These aren't used by the C tokenizer but are needed for tokenize.py
COMMENT = 57
NL = 58
ENCODING = 59
```

Notice how `ERRORTOKEN` and `ELLIPSIS` haven't been added in the auto generated file. I'll fix it as part of my PR but just wondering if you manually edited the file.

2017-06-24 22:11 UTC, ammaraskar commented
Nevermind @albertjan, looks like the issue I described here was caused by a merge issue. Thanks anyway :)