https://bugs.python.org/issue38165
python/cpython pull request #16126
Opened 2019-09-13 17:53 UTC by evgeniymischuk

freezes when loading a program on imports because user rights are insufficient
python installed on c:/ and requires administrator rights
when run program from not root user

2019-09-13 18:15 UTC, eduardo-elizondo requested changes
All the builds are failing. Please look at the failing builds and re-submit your change

2019-09-13 22:37 UTC, aeros reviewed
Thanks for the PR @evgeniymischuk. Please adjust the title of the PR according the standard conventions. The format is: ``bpo-<issue_number>: <summary_of_PR>``. This allows the PR to be directly linked to the bpo issue. If you haven't already, I would highly recommend reading through the [devguide's quick reference page](https://devguide.python.org/#quick-reference). 

Travis CI is currently failing because of a error in ``test.test_tempfile.TestMkstempInner``, specifically for the tests ``test_collision_with_existing_directory`` and ``test_collision_with_existing_file ``. Both failures are occurring during the handling of ``FileNotExistsError``. Here's the relevant traceback, for debugging purposes:
![image](https://user-images.githubusercontent.com/44193521/64898252-6c0e8a80-d654-11e9-95a4-d619364ab669.png)

I didn't include the other one since they both contained the same exact traceback. Essentially, when the ``FileExistsError`` is being raised, there is no suitable replacement name found for the temporary file created during the tests. I would recommend trying to address this issue first.

Before you update this PR with a new batch of commits, you should [run the tests locally](https://devguide.python.org/runtests/#running) to ensure everything is passing. The CI can still potentially fail if the tests are not passing in other environments, but this will help to rule out the majority of issues.

2019-09-13 22:52 UTC, aeros167 commented
For now, I am adding a ``DO-NOT-MERGE`` label since there are issues to resolve with the PR. Once the problems have been addressed, either someone else can remove the label, or you can @mention me to take a look at the PR again.

2019-09-13 22:56 UTC, aeros167 commented on Lib/tempfile.py
> -    for seq in range(TMP_MAX):
Why is this being removed? This block is supposed to continue trying to create the file until the maximum number of tries are reached ``TMP_MAX``.

2019-09-13 22:58 UTC, aeros167 commented on Lib/tempfile.py
> +        raise FileExistsError(_errno.EEXIST, "No usable temporary file name found")
When the exception occurs, this block is supposed try *resolving* the exception, not just raising it.

2019-09-13 22:59 UTC, aeros167 commented on Lib/tempfile.py
> +        raise PermissionError(_errno.EACCES, "No permission to create temp file")
See my [other comment](https://github.com/python/cpython/pull/16126/files#r324393420).

2019-09-16 18:51 UTC, matrixise commented
Hi @aeros167 

Thank you for your review and your time, but I think we can close this PR and the associated issues.

2019-09-16 18:51 UTC, closed without merging

2019-09-16 20:23 UTC, aeros167 commented
> Hi @aeros167
Thank you for your review and your time, but I think we can close this PR and the associated issues.

No problem, I think they could be closed as well.