bpo-17258: use sha256 instead of md5 within multiprocessing.connection
python/cpython pull request #16264
Opened 2019-09-18 16:17 UTC by stratakis

Within multiprocessing.connection, deliver_challenge() and
answer_challenge() use hmac for a challenge/response, however
hmac implicitly defaults to using MD5, which fails under FIPS
mode. Hardcode the digest value to sha256.

This PR is adapted from the patch provided at bpo-17258 and pulled from https://github.com/encukou/cpython/commit/b819ca654873ea36144ce1cb6f8c422a6d2f5d7d

2019-09-18 16:17 UTC, stratakis commented
cc @tiran

2019-09-19 05:14 UTC, matrixise approved these changes

2019-09-19 11:18 UTC, tiran requested changes
I would prefer a more flexible solution that allows us to change algorithms more easily in the future and perhaps allows different auth mechanisms than HMAC challenge and response.

2019-12-05 15:41 UTC, encukou commented
> I would prefer a more flexible solution that allows us to change algorithms more easily in the future 

As fas as I can see, changing the algorithm would mean setting `HMAC_DIGEST_NAME` to a new value. That sounds very easy.
What am I missing?

> and perhaps allows different auth mechanisms than HMAC challenge and response.

I don't see how this PR is blocking someone from working on that.

2019-12-05 16:16 UTC, tiran commented
The change breaks backward compatibility. multiprocessing supports distributed computing across multiple machines and works with multiple Python versions. With the change a controller with Python 3.9 would no longer be able to talk to a 3.8 server or the other way around.

2020-02-27 15:58 UTC, stratakis commented
@tiran What would you propose to move this forward, essentially moving away from md5? Any approaches that would make sense? Something like implementing a client-server handshake negotiation to agree on a hash?

2020-06-18 13:44 UTC, stratakis commented
Closing this. Superseded by #20380

2020-06-18 13:44 UTC, closed without merging