Doc: errors tutorial improvements
python/cpython pull request #16269
Opened 2019-09-19 00:52 UTC by adorilson

Improvements:

- Improvements in how try clause works section
  This suggestion is because the execution continues after *except*, not after *try* but before *except*. I guess this form more clear.

- Surrounding some keywords with *...*
  For uniformity the highlighted terms  

- Adjust the number of chars per line to 80

2019-09-19 03:27 UTC, aeros requested changes
Thanks for the PR @adorilson.

Regarding the usage of asterisks, they are typically reserved for argument names, so I do not support the idea of using *try clause* or *except clause*. If anything, the emphasis should only surround "try" or "except". Additionally, it should be using either the Spinx ``keyword`` role or inline code blocks. The Sphinx roles provide a specific functional purpose of linking to the documentation, so they are more beneficial when appropriately used.

Sphinx role example:
```
:keyword:`try` clause
```
Code block example:
```
``try`` clause
```
Also, while we typically require that any PRs changing or adding documentation fit within the 80 character line width limit for reST, it is discouraged to change an existing section solely for the purpose of fixing the wrapping, as this can add unnecessary clutter to the commit logs.

2019-09-19 03:27 UTC, aeros commented on Doc/tutorial/errors.rst
> +* If an exception occurs during execution of the *try clause*, the rest of the
Example of where the Sphinx role or code blocks should be used.
```suggestion
* If an exception occurs during execution of the :keyword:`try` clause, the rest of the
```

2019-09-19 03:27 UTC, aeros167 commented on Doc/tutorial/errors.rst
>    clause is skipped.  Then if its type matches the exception named after the
This is not part of the PR, but this minor grammar fix should be made anyways. Wouldn't be worth it's own PR.
```suggestion
   clause is skipped.  Then, if its type matches the exception named after the
```

2019-09-19 03:27 UTC, aeros167 commented on Doc/tutorial/errors.rst
> +  continues after the *try/except* block.
Try/except is an appropriate name for the block, but it is not a literal keyword in the code.
```suggestion
  continues after the try/except block.
```

2019-09-20 01:26 UTC, aeros167 commented on Doc/tutorial/errors.rst
> +   clause is skipped.  Then, if its type matches the exception named after the
This extra space is likely causing the doc build failures. 
```suggestion
  clause is skipped.  Then, if its type matches the exception named after the
```

2021-01-23 23:16 UTC, adorilson commented
Hi, folks.

What exactly I need to do here?

2021-01-31 06:06 UTC, aeros approved these changes
Sorry for the delay, LGTM. (For clarification, I did not have commit privileges when I last left a review)

2021-01-31 06:07 UTC, merged