bpo-38216, bpo-36274: Allow subclasses to override validation and encoding behavior
python/cpython pull request #16321
Opened 2019-09-21 08:55 UTC by jaraco

This patch introduces a new semi-private hook for subclasses to override the validation and encoding behavior in `http.client.HTTPConnection.putrequest`, allowing select clients to customize the behavior and implement invalid requests as was possible prior to the patch in bpo-30458 (for control characters) and prior to Python 3.0 (for encoding).

2019-09-21 14:08 UTC, tirkarthi commented
So the fix would be that projects like cherrypy can override this private function to make sure crlf is not validated? I understand it's a private hook but not sure how it could be documented if some other project stumbles upon this and wants to bypass the validation. IIRC, the original discussion was about introducing a parameter to turn off validation in putrequest but was given up due to introducing a new parameter in a maintenance release.

2019-09-21 14:38 UTC, jaraco commented
> So the fix would be that projects like cherrypy can override this private function to make sure crlf is not validated?

Essentially, yes. I specifically wanted to avoid adding a parameter due to the public exposure that brings (documentation, explanation, additional interfaces). Almost no clients are going to want to override this behavior. Those that do will very likely trace the code to this place and see that the behavior can be overridden. The tests enforce that contract so it isn't accidentally removed, but otherwise it's tucked away with little documentation. Anyone asking about it may refer to the tests for examples of how it might be used.

2019-09-22 20:47 UTC, webknjaz commented on Lib/test/test_httplib.py
> +                        url):
This little hanging thing looks weird. Maybe do smth like
```python
pattern = client._contains_disallowed_url_pchar_re
if match := pattern.search(url):
```

2019-09-22 20:48 UTC, webknjaz approved these changes

2019-09-25 23:18 UTC, zooba commented on Lib/test/test_httplib.py
> +                        url):
Or just ignore the line length _guideline_ for this one case.

2019-09-27 05:23 UTC, gpshead commented on Lib/test/test_httplib.py
> +                        url):
it's fine as is.  using `m` as the name instead of `match` would've been my suggestion. ;)

2019-09-27 05:30 UTC, gpshead requested changes

2019-09-27 05:30 UTC, gpshead commented on Lib/test/test_httplib.py
> +                return url.encode('utf-8')
Rather than requiring people to override the entire def _prepare_path method just to change the encoding it allows (which, as this example shows, means copy and pasting the first part of the implementation), how about making a `._prepare_path_encoding` attribute to the class that could be overridden.  it'd default to `'ascii'` but you would set it to `'utf-8'` in this subclass.  instead of overriding the method.

2019-09-27 05:30 UTC, gpshead commented on Lib/http/client.py
>          # Non-ASCII characters should have been eliminated earlier
We can get rid of this comment now.  it was referring to the `.encode('ascii')` that is no longer below.

2019-09-27 05:34 UTC, gpshead requested changes
also, please use blurb to add a NEWS entry for this change.

2019-09-27 22:08 UTC, gpshead commented
I'm looking into addressing my suggested changes now so that this can go in.

2019-09-27 22:12 UTC, jaraco commented
I'll look at this later this evening.

2019-09-27 22:14 UTC, jaraco commented on Lib/test/test_httplib.py
> +                return url.encode('utf-8')
I considered this, but the proposed change that inspired this change wished to change the invocation of `encode('ascii')` to `encode('ascii', errors='surrogateescape')`, so that seemed like enough of a signal that one might wish to override the encoding process entirely.

2019-09-27 22:14 UTC, jaraco commented on Lib/test/test_httplib.py
> +                return url.encode('utf-8')
Does it still make sense to use `self._prepare_path_encoding` so it's easier to override if that's what someone wants?

2019-09-27 22:28 UTC, gpshead commented on Lib/test/test_httplib.py
> +                return url.encode('utf-8')
i suppose _prepare_path_encoding could be its own method in that case.  I wanted to avoid people needing to duplicate the control characters check for this situation.

2019-09-27 22:35 UTC, gpshead approved these changes

2019-09-27 22:37 UTC, gpshead commented
Waiting on the CI results here.  I don't anticipate problems.  Please take a look and let me know what you think.  I want to get this in over the weekend.

2019-09-28 01:34 UTC, jaraco commented
This approach looks acceptable to me. I'm still not super-happy with it (not your changes in particular, just the problem); I hate how the _prepare_path and _encode_prepared_path are entangled. I took a stab at a slightly less aggressive approach that once again separates the concerns of _prepare_path and _encode_prepared_path in [this branch](https://github.com/jaraco/cpython/tree/feature/38216-putrequest-hooks-separate) (currently one commit ahead of this PR). @gpshead, if you have time or energy, would you comment on that approach? Otherwise, we can move forward with this approach.

2019-09-28 03:37 UTC, gpshead commented
i'm inclined to go forward with your new PR #16448

2019-09-28 06:38 UTC, ned-deily commented
> i'm inclined to go forward with your new PR #16448 
Me, too.

2019-09-28 12:32 UTC, closed without merging