closes bpo-38174: Update vendored expat library to 2.2.8.
python/cpython pull request #16346
Opened 2019-09-24 04:03 UTC by benjaminp

Fixes CVE-2019-15903. See full changelog at https://github.com/libexpat/libexpat/blob/R_2_2_8/expat/Changes.

2019-09-24 10:16 UTC, vstinner requested changes
Using my https://github.com/vstinner/misc/blob/master/cpython/cpython_rebuild_expat_dir.sh script (modify TAG= at the first line to put: TAG=R_2_2_8), I get a very similar result, except that my script also removed Modules/expat/loadlibrary.c. loadlibrary.c has been removed from libexpat: https://github.com/libexpat/libexpat/commit/5d34a708e752ccea53fc6f97bf7a14933587d8b9

"replace loadlibrary.c and RtlGenRandom call with rand_s() on windows"

2019-09-25 06:14 UTC, benjaminp commented
I have made the requested changes; please review again.

On Tue, Sep 24, 2019, at 03:18, Victor Stinner wrote:
> *@vstinner* requested changes on this pull request.
> 
> Using my 
> https://github.com/vstinner/misc/blob/master/cpython/cpython_rebuild_expat_dir.sh script (modify TAG= at the first line to put: TAG=R_2_2_8), I get a very similar result, except that my script also removed Modules/expat/loadlibrary.c. loadlibrary.c has been removed from libexpat: libexpat/libexpat@5d34a70 <https://github.com/libexpat/libexpat/commit/5d34a708e752ccea53fc6f97bf7a14933587d8b9>
> 
> "replace loadlibrary.c and RtlGenRandom call with rand_s() on windows"
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/python/cpython/pull/16346?email_source=notifications&email_token=AABVSTSGWWLMHIEESA2U6JDQLHSNTA5CNFSM4IZ2KYIKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCFWGI4I#pullrequestreview-292316273>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AABVSTVTJVMOFVGL6FHT7ELQLHSNTANCNFSM4IZ2KYIA>.
>

2019-09-25 11:15 UTC, vstinner approved these changes
LGTM, thanks.

2019-09-26 04:33 UTC, merged

2019-09-26 04:34 UTC, miss-islington commented
Thanks @benjaminp for the PR 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6, 3.7, 3.8.
🐍🍒⛏🤖

2019-09-26 04:34 UTC, miss-islington commented
I'm having trouble backporting to `3.8`. Reason: '`Error 110 while writing to socket. Connection timed out.`'. Please retry by removing and re-adding the `needs backport to 3.8` label.

2019-09-26 04:34 UTC, miss-islington commented
Sorry, @benjaminp, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 52b940803860e37bcc3f6096b2d24e7c20a0e807 3.7
                                ```

2019-09-26 04:34 UTC, miss-islington commented
Sorry @benjaminp, I had trouble checking out the `3.6` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 52b940803860e37bcc3f6096b2d24e7c20a0e807 3.6
                                ```

2019-09-26 04:34 UTC, miss-islington commented
Sorry, @benjaminp, I could not cleanly backport this to `2.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 52b940803860e37bcc3f6096b2d24e7c20a0e807 2.7
                                ```

2019-09-26 04:35 UTC, miss-islington commented
Thanks @benjaminp for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-09-26 04:35 UTC, miss-islington commented
Sorry @benjaminp, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 52b940803860e37bcc3f6096b2d24e7c20a0e807 3.8
                                ```