bpo-38279: use of easier to understand syntax
python/cpython pull request #16398
Opened 2019-09-25 17:46 UTC by BMaxV

The suggested changes mostly deal with my troubles to understand how long a process "lives" in code, how and when they stop.

The first change is putting the processes in a list, after creating and starting them in separate lines. Should be easier to read.

It was unclear to me, why iter(input.get,"stop") and putting "stop" to the task queue would stop a process. Also after reading up on iter(), it should pass "stop" anyway when input.get() wouldn't work. After removing the last "stop" putting loop, it didn't do that though. So I don't get how that works. Since it's an example I don't think it's too much to ask for it to be obvious. Or more "obvious" anway.

So I replaced that for ... iter(...) with a while that just gets stuff basically the same way, and terminates processes explicitly.

This is safe, as far as I understand it, because the for i in range(len(tasks2)) done_queue.get() will always wait until all tasks are done, because of the defaults for queue.get().

2019-09-25 17:46 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@BMaxV

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-09-25 17:50 UTC, BMaxV commented
Ah. I will sign the thing when I have the time. :)

2019-09-28 01:29 UTC, terryjreedy commented
Signing takes about 5 minutes.  It is a potential waste of time for us to review until you do.

2019-09-28 08:05 UTC, BMaxV commented
Ok I signed the thing and got the confirmation via mail.

2019-10-13 19:14 UTC, BMaxV commented
Yo. It's been nearly three weeks. Should I do something else than signing the thing?

2019-10-13 21:39 UTC, terryjreedy commented
I manually removed the Unsigned tag and the bot confirmed the signing.  Davin or Antoine can review it now.

2019-11-02 16:38 UTC, pitrou requested changes
Some comments here:
* the changes don't follow PEP 8 (whitespace around operators and assignments)
* sending a "STOP" string to gracefully shutdown a worker process is not the same as brutally killing it by calling `terminate()`; I believe that showcasing how to gracefully end a worker process is more useful to the reader (killing processes is easy but can risk losing data by cancelling critical operations)
* while two-argument `iter` is not very common, it's not that difficult to understand and it is expected that people trying to use `multiprocessing` primitives are able to use the documentation to find the meaning of a built-in function (!)

So, while I understand the intent of making an example simpler to approach, in the end it's not obvious that this PR is actually useful.

2019-11-02 16:40 UTC, pitrou commented
By the way, sorry for the delay in reviewing this. However, I'm going to close this PR as I don't believe any of the proposed changes are actually desirable. Feel free to open another PR and/or bug entry if you believe other changes may be useful.

2019-11-02 16:40 UTC, closed without merging

2019-11-03 09:25 UTC, BMaxV commented
@pitrou Let me get this straight:

You criticse my PR, to improve documentation, based on functionality that's not documented, even though the page that should document it, is the very same I'm trying to improve?

>sending a "STOP" string to gracefully shutdown a worker process

There is no advice on the doc page to do this, or that it works or how it works.

Then completely without any discussion, you just decide the doc page is perfect and changes are not desirable and you close the issue?