bpo-37404: Raising value error if an SSLSocket is passed to asyncio functions
python/cpython pull request #16457
Opened 2019-09-28 10:29 UTC by idomic

2019-09-28 10:36 UTC, idomic commented
Adding @taleinat as a reviewer

2019-09-28 17:51 UTC, taleinat commented
I'm not very familiar with asyncio, but it seems to me that in these cases the code should raise an exception rather than emit a warning. A `TypeError` exception would be appropriate.

2019-09-28 18:39 UTC, 1st1 commented
Agree with @taleinat, a `TypeError` is better than a warning.

2019-09-29 13:23 UTC, asvetlov commented
Agree as well.
The code doesn't work with incorrect socket type anyway, using a strict exception is correct in this case.

2019-09-29 15:27 UTC, idomic commented
> Agree as well.
> The code doesn't work with incorrect socket type anyway, using a strict exception is correct in this case.

Hi all, would fix it to throw a TypeError exception, I was following the thread in bpo - there was a discussion about sending a warning first instead of just throwing an exception without any notice first.

Will commit a new version soon!

2019-10-01 13:18 UTC, idomic commented
Commited the new version: raising TypeError instead of a warning.

2019-12-01 19:43 UTC, idomic commented
@taleinat Maybe we can push this one as well? (been pending 2 months)

2019-12-01 20:44 UTC, taleinat requested changes

2019-12-01 20:44 UTC, taleinat commented on Lib/asyncio/selector_events.py
> +            raise TypeError("Socket cannot be of type SSLSocket instance")
"of type SSLSocket instance" is strange. This should say either "of type SSLSocket" or "an SSLSocket instance".

(below as well)

2019-12-01 20:46 UTC, taleinat commented
@idomic 

> @taleinat Maybe we can push this one as well? (been pending 2 months)

Sorry for letting this languish, that's definitely on me! Thanks for the reminder.

For this, we'll also need to add a NEWS entry. You can use [blurb-it](https://blurb-it.herokuapp.com/) to do so easily in the browser, or install locally with `pip install blurb` and run `blurb add`.

2019-12-02 08:40 UTC, taleinat approved these changes
LGTM

2019-12-02 08:41 UTC, taleinat commented
@1st1, @asvetlov, care for a quick review before I merge this?

2019-12-07 11:52 UTC, merged

2019-12-07 11:52 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Base branch was modified. Review and try the merge again.`.

2019-12-07 11:52 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Base branch was modified. Review and try the merge again.`.

2019-12-07 11:52 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Base branch was modified. Review and try the merge again.`.

2019-12-07 11:52 UTC, miss-islington commented
Thanks @idomic for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-12-07 11:52 UTC, asvetlov approved these changes

2019-12-07 11:52 UTC, miss-islington commented
Sorry @idomic, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 892f9e0777f262d366d4747a54c33a1c15a49da6 3.8
                                ```

2019-12-07 11:52 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Pull Request is not mergeable`.