bpo-34344 Fixed AbstractEventLoopPolicy.get_event_loop docstrings
python/cpython pull request #16463
Opened 2019-09-28 14:42 UTC by idomic

2019-09-29 06:23 UTC, brandtbucher requested changes
Thanks @idomic, and welcome to CPython!

This change looks good, but I think it was made in the wrong place. This new docstring should be moved to the `get_event_loop` method on **line 632** of this same file. The current docstring for line 580 is perfectly fine as-is.

Besides that, I've got a couple of formatting fixes that should be incorporated. See below:

2019-09-29 06:23 UTC, brandtbucher commented on Lib/asyncio/events.py
> +        """ Get the event loop for the current context.
No leading space here:

```suggestion
        """Get the event loop for the current context.
```

2019-09-29 06:23 UTC, brandtbucher commented on Lib/asyncio/events.py
> +            Returns an instance of EventLoop or raises an exception.
No hanging indent here:

```suggestion
        Returns an instance of EventLoop or raises an exception.
```

2019-09-29 06:23 UTC, brandtbucher commented on Lib/asyncio/events.py
> +       """
Bad indent here:

```suggestion
        """
```

2019-10-01 13:10 UTC, idomic commented
Thanks @brandtbucher for the warm welcome and the detailed comments.
I've removed the past change and fixed the remarks on the docstring at line 632.

2019-10-01 13:21 UTC, brandtbucher commented on Lib/asyncio/events.py
> +           Returns an instance of EventLoop or raises an exception.
Looks good @idomic! One more tiny formatting fix (hanging indent):

```suggestion
        Returns an instance of EventLoop or raises an exception.
```

2019-10-01 13:31 UTC, brandtbucher approved these changes

2019-10-01 16:00 UTC, 1st1 commented on Lib/asyncio/events.py
> +        Returns an instance of EventLoop or raises an exception.
Need a newline before "Returns".  See https://www.python.org/dev/peps/pep-0257/ for the reference.

2019-10-03 21:08 UTC, 1st1 approved these changes

2019-10-03 21:08 UTC, merged

2019-10-03 21:08 UTC, miss-islington commented
Thanks @idomic for the PR, and @1st1 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-10-03 21:40 UTC, brandtbucher commented
Congrats on your first PR @idomic!