bpo-30398: Add a docstring for re.error.
python/cpython pull request #1647
Opened 2017-05-18 09:48 UTC by serhiy-storchaka

2017-05-19 21:13 UTC, terryjreedy requested changes
It is nice to have this documented.  Main question is when it can be raised.

2017-05-19 21:13 UTC, terryjreedy commented on Lib/sre_constants.py
> +    '''Exception raised for invalid regular expressions.
If this is only raised during compilation, then
"Exception raised while compiling invalid regular expressions.

2017-05-19 21:13 UTC, terryjreedy commented on Lib/sre_constants.py
> +    pos: The index of pattern where compilation failed
'in' instead of 'of' sounds better to me.
If this is also raised during matching, what would this be?

2017-05-19 21:13 UTC, terryjreedy commented on Lib/sre_constants.py
> +    colno: The column corresponding to pos
'source line' and 'source column'?

2017-05-22 06:50 UTC, serhiy-storchaka commented on Lib/sre_constants.py
> +    '''Exception raised for invalid regular expressions.
It is also raised by `Pattern.sub()` and `Match.expand()` when the replacement string contains invalid group reference. E.g. `re.compile(r'\w').sub(r'\1', 'a')`, `re.match(r'\w', 'a').expand(r'\1')`. Technically it is raised not during compilation, but immediately after it from user's point of view.

2017-05-22 06:50 UTC, serhiy-storchaka commented on Lib/sre_constants.py
> +    pos: The index of pattern where compilation failed
The wording is copied from the module documentation (see [bpo-22578](https://bugs.python.org/issue22578)). Should it be updated too?

Attributes `pattern`, `pos`, `lineno` and `colno` can be `None` if it is hard to determine the point of failure.

2017-05-22 07:25 UTC, serhiy-storchaka commented on Lib/sre_constants.py
> +    pos: The index of pattern where compilation failed
The `re` module documentation is copied from the `json` module documentation, which was copied from the `simplejson` documentation. If change the wording it makes sense to change it consistently in all these places.

2017-05-26 01:17 UTC, terryjreedy commented on Lib/sre_constants.py
> +    pos: The index of pattern where compilation failed
Leave 'of' alone then.  My comment on 'of' to 'in' was about a 60% change - 40% leave alone  judgment.  But your previous comment reveals that failure can occur during matching (which is the re equivalent of execution).    Source lineno and colno are only relevant when failure *is* during matching.

2017-05-27 13:12 UTC, merged