bpo-38341: Add SMTPNotSupportedError in the exports of smtplib
python/cpython pull request #16525
Opened 2019-10-01 20:52 UTC by rockwelln

Pretty simple add in the __all__ variable, the missing exception SMTPNotSupportedError

2019-10-01 20:52 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@rockwelln

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-10-01 20:58 UTC, brandtbucher commented
Thanks for your time @rockwelln, and welcome to CPython! 😎

This looks like a good change. Can you also [create a NEWS entry](https://blurb-it.herokuapp.com/), since this changes `smtplib`'s exported names?

2019-10-01 20:59 UTC, brandtbucher requested changes
This looks like a good change. Can you also [create a NEWS entry](https://blurb-it.herokuapp.com/), since this changes `smtplib`'s exported names?

Just something simple, like:

```rst
Added :exc:`smtplib.SMTPNotSupportedError` to ``__all__`` in :mod:`smtplib`.
```

2019-10-01 21:09 UTC, rockwelln commented
Thank you @brandtbucher  :-), I posted the news.
Don't hesitate if I missed something, it's the first time I propose a change in CPython.

2019-10-01 21:22 UTC, brandtbucher commented on Misc/NEWS.d/next/Library/2019-10-01-21-06-18.bpo-38341.uqwgU_.rst
> +Add SMTPNotSupportedError in the smtplib exported names.
Looks good. This can be a bit richer, though:

```suggestion
Add :exc:`smtplib.SMTPNotSupportedError` to the :mod:`smtplib` exported names.
```

2019-10-01 21:24 UTC, brandtbucher approved these changes

2019-10-01 21:27 UTC, brandtbucher commented
Awesome. I assume you’ve seen the bot’s message about the CLA?

2019-10-01 21:33 UTC, rockwelln commented
thanks!
about the CLA, I signed it few minutes ago, it should be ok now.

2019-10-05 00:30 UTC, maxking approved these changes
Thanks for working on this @rockwelln 

Since this is a public API (https://docs.python.org/3/library/smtplib.html?highlight=smtplib#smtplib.SMTPNotSupportedError) it should be exported.

2019-10-05 00:30 UTC, merged

2019-10-05 00:31 UTC, miss-islington commented
Thanks @rockwelln for the PR, and @maxking for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-10-05 00:31 UTC, miss-islington commented
Sorry @rockwelln and @maxking, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 3faf826e5879536d2272f1a51c58965a16827f81 3.8
                                ```

2019-10-05 00:44 UTC, brandtbucher commented
Congrats on your first CPython contribution @rockwelln! :champagne:

Looking forward to seeing more from you in the future.

2019-10-06 14:46 UTC, rockwelln commented
thank you very much @brandtbucher for your support. this first experience was a pleasure.
I'd be happy to contribute again.

2019-10-11 20:42 UTC, miss-islington commented
Thanks @rockwelln for the PR, and @maxking for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-10-11 20:43 UTC, ned-deily commented
(The 3.8 autobackport failed for some reason originally, manually restarted it.)