bpo-NNNN: syslog: fixed making default "ident" from sys.argv[0]
python/cpython pull request #16557
Opened 2019-10-03 11:38 UTC by vaclavbartos

The default value of "ident" parameter should be sys.argv[0] with leading path
components stripped, but it contained the last slash, i.e. '/program' instead
of 'program'.

The BPO issue number will be filled in soon...

2019-10-03 11:38 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@vaclavbartos

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-10-03 16:01 UTC, brandtbucher commented
Thanks for your time @vaclavbartos, and welcome to CPython! 😎

This looks like a good change. I assume you’ve already seen the bot’s message about the CLA?

2019-10-03 17:07 UTC, brandtbucher requested changes
Even though this is a fairly trivial fix, I still think you should [make a NEWS entry](https://blurb-it.herokuapp.com), since it changes logging output. Just something simple, like:

```rst
Fixed an issue where ``ident`` could include a leading path separator when :func:`syslog.openlog` was called without arguments.
```

And while a regression test or two are always good to include, it looks like this module has almost no test coverage currently due to platform issues. So, *probably* not necessary in this case.

2019-10-04 09:59 UTC, vaclavbartos commented
OK, I added the News entry. I signed the CLA yesterday and it's checked now.

Regarding tests - as you noted, it would be quite difficult to implement them, since there is currently no other way to read `ident` than to emit a syslog message, read it from a syslog file and parse `ident` from it - which is highly platfrom dependent.

2019-10-04 15:36 UTC, brandtbucher commented
This module doesn't have any experts with GitHub accounts, and hasn't had any real changes in almost a decade. Given that this is a fairly trivial change, perhaps another core dev could look at it?

CC @vstinner

2019-10-23 03:31 UTC, gvanrossum approved these changes
Yeah, this looks good. I agree that this looks like a mis-translation of the original code, apparently introduced in revision d63a3b8beb4a0841cb59fb3515347ccaab34b733.

2019-10-23 03:32 UTC, gvanrossum commented
Should we backport this to 3.8? Then the behavior would be different in 3.8.1 than in 3.8.0.

2019-10-23 04:24 UTC, brandtbucher commented
Even though it's a bug fix, I'm leaning "no". Logging output shouldn't change between minor versions, and I don't know of anyone who sees this as a must-have.

It's just another reason 3.9 will be better than 3.8.

2020-01-14 16:18 UTC, brandtbucher commented
Going through some of my old reviews and saw that this was still unmerged. @gvanrossum, is this waiting for anything?

2020-01-14 17:57 UTC, merged

2020-01-14 17:57 UTC, gvanrossum commented
Sorry! It should be merged now.

2020-01-14 17:58 UTC, brandtbucher commented
Congrats on your first CPython contribution @vaclavbartos! :champagne:

Looking forward to seeing more from you in the future.