bpo-30400: Fix race condition in shutil.copyfile()
python/cpython pull request #1659
Opened 2017-05-18 20:42 UTC by pkmoore

This PR is currently not passing all tests.  I believe this is caused by the mock file objects not operating correctly with os.stat() and os.fstat().

2017-06-12 19:14 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-07-11 14:46 UTC, vstinner requested changes
Hum. I'm not sure that the approach is reliable. Why not using os.fstat() on the open src and dst files?

2018-08-14 05:16 UTC, pkmoore commented
I have made the requested changes; please review again

As discussed on the bug tracker, this PR now opens the source and destination early and uses file descriptors in order to avoid a race condition where the file being copied is replaced at some point during copyfile's execution.  I've just added a missing test so the modifications should have good test coverage.

Thanks,
Preston

2020-01-25 20:06 UTC, csabella commented
@pkmoore, please resolve the merge conflicts.  Thanks!

2020-06-12 12:11 UTC, csabella commented
@pkmoore please resolve the merge conflicts.  Thanks!

2022-07-24 09:12 UTC, erlend-aasland commented
Closing this PR as the concerns have not been addressed, and the PR has been stale for years.

2022-07-24 09:12 UTC, closed without merging

2025-07-19 10:34 UTC, abadger commented
@pkmoore are you still interested in this?  I would be willing to pick it up and care for it until someone merges it but if I want to credit you and use your code as a basis, you wuold need to sign the CLA.  If you're not interested, I will reimplement it from the discussion here and in the issue.

2025-07-19 12:34 UTC, abadger commented
@pkmoore ah, I found that you have signed the cla in the past by looking at bugs.python.org.  I can continue your work in a new PR but let me know if you want to take it over.