bpo-38384: Fix a possible assertion failure in _pickle
python/cpython pull request #16606
Opened 2019-10-06 13:41 UTC by ZackerySpytz

In _Unpickler_SetInputStream(), _PyObject_LookupAttrId() is called
three times in a row without any error handling.  If an exception
occurs during the first or second call, _PyObject_LookupAttrId()
will be called with a live exception.

2019-10-06 16:36 UTC, serhiy-storchaka requested changes
Please add a test.

2019-10-21 06:44 UTC, serhiy-storchaka commented
Minimal reproducer (but you can add `readline` and `readinto`):
```python
class F:
    @property
    def read(self):
        1/0

import pickle
pickle.load(F())
```

2019-11-13 22:47 UTC, taleinat commented
@ZackerySpytz Ping?

2019-11-22 23:12 UTC, taleinat commented
Hi @ZackerySpytz! This is looking good!

Make sure to also add a NEWS entry (you can use [blurb-it](https://blurb-it.herokuapp.com/)).

2021-10-19 11:36 UTC, serhiy-storchaka commented on Lib/test/pickletester.py
> +    def test_load_read_exception(self):
`readinto` will not be tested if `read` raises an error. You need six tests for classes which do not have one of these attributes or raise error for it but have other two attributes.

2021-10-19 11:36 UTC, serhiy-storchaka commented on Modules/_pickle.c
> +    if (_PyObject_LookupAttrId(file, &PyId_readinto, &self->readinto) <= 0) {
`readinto` is optional now.

Ifs for `read` and `readline` can be merged.

2022-12-22 11:06 UTC, bumper-furkan-onder approved these changes

2022-12-22 12:19 UTC, furkanonder approved these changes

2022-12-22 12:19 UTC, furkanonder commented
LGTM. @serhiy-storchaka

2022-12-22 12:53 UTC, serhiy-storchaka reviewed
LGTM.

Please add few more test cases:

* no `read`, no `readline`
* `read = bad_property`, no `readline`
* `readline = bad_property`, no `read`

2023-12-01 12:35 UTC, serhiy-storchaka commented
Sorry, I forget to merge this PR at its time, so the original issue was fixed in #105667.

But the tests may still be useful.

2023-12-01 12:37 UTC, serhiy-storchaka approved these changes

2023-12-01 13:36 UTC, merged