bpo-38471: Fix _ProactorDatagramTransport close() behaviour
python/cpython pull request #16779
Opened 2019-10-14 14:01 UTC by primal100

Fixes an issue where if the _ProactorDatagramTransport close method is called while there is data in the write buffer, the data is not sent and connection_lost is not called. Behaviour now matches _SelectorDatagramTransport.

2019-10-14 14:01 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@primal100

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-10-14 17:45 UTC, asvetlov commented
NEWs entry is required: https://devguide.python.org/committing/#what-s-new-and-news-entries

2019-10-19 09:48 UTC, primal100 commented
The news entry was added

2019-10-19 10:12 UTC, asvetlov requested changes

2019-10-19 10:12 UTC, asvetlov commented on Doc/whatsnew/3.8.rst
> -Prerelease users should be aware that this document is currently in
This change is not related to the issue

2019-10-19 10:12 UTC, asvetlov commented on Doc/whatsnew/3.8.rst
> +Running ``python -m asyncio`` launches a natively async REPL.  This allows rapid
The same

2019-10-19 10:12 UTC, asvetlov commented on Lib/test/support/__init__.py
> +        os.chdir(os.path.realpath(path))
Why this update is needed?

2019-10-20 12:05 UTC, primal100 commented
Github is showing three commits that aren't mine this pull request. I have no idea why or how to fix it, so will just start over with a new fork and pull request.

2019-10-20 13:02 UTC, asvetlov commented
You can force-push (`git push -f`) here without recreating the PR

2019-10-20 13:33 UTC, closed without merging