bpo-38480: resource.setrusage() should raise PermissionError
python/cpython pull request #16804
Opened 2019-10-15 16:11 UTC by giampaolo

See: https://bugs.python.org/issue38480

2019-10-19 11:27 UTC, zhangyangyu requested changes
The whatsnew and changelog are wrong. It's `ValueError` and `setrlimit`. And the document of `setrlimit` should also be updated. Currently it says: raises ValueError if a process tries to raise its hard limit. I think we need a versionchanged in 3.9 documents when a not super user do this PermissionError is raised.

2019-10-26 04:07 UTC, pppery commented on Doc/whatsnew/3.9.rst
> +  :exc:`KeyError` if the user doesn't have privileges.
```suggestion
  :exc:`ValueError` if the user doesn't have privileges.
```

2020-01-26 01:26 UTC, csabella commented
@giampaolo, please take a look at the code review.  Thanks!

2020-01-26 21:43 UTC, giampaolo commented
@zhangyangyu could you please take one last look?

2020-02-06 02:50 UTC, zhangyangyu approved these changes

2020-02-06 02:53 UTC, zhangyangyu requested changes

2020-02-06 02:53 UTC, zhangyangyu commented on Misc/NEWS.d/next/Library/2019-10-16-00-07-21.bpo-38480.Fe6PqI.rst
> +resource.setrusage() now raises PermissionError instead of KeyError  if the
it's `setrlimit`

2023-08-12 06:56 UTC, closed without merging