bpo-33604: Raise TypeError on missing hmac arg.
python/cpython pull request #16805
Opened 2019-10-15 16:38 UTC by gpshead

Also updates the documentation to clarify the situation surrounding
the digestmod parameter that is required despite its position in the
argument list as of 3.8.0 as well as removing old python2 era
references to "binary strings".

We indavertently had this raise ValueError in 3.8.0 for the missing
arg.  This is not considered an API change as no reasonable code would
be catching this missing argument error in order to handle it.

2019-10-15 16:44 UTC, Carreau approved these changes

2019-10-15 16:46 UTC, tiran requested changes
The digestmod name must be a string or callable.

2019-10-15 16:46 UTC, tiran commented on Doc/library/hmac.rst
> +.. function:: new(key, msg=None, digestmod=b'')
digestmod is either a string or a callable, not bytes.

2019-10-15 16:58 UTC, gpshead commented
I have made the requested changes; please review again.

2019-10-15 18:04 UTC, tirkarthi commented
Does changing exception type between 3.8.0 and 3.8.1 needs a versionchanged directive note in doc or is NEWS entry sufficient for these cases?

2019-10-15 20:47 UTC, tiran approved these changes

2019-10-15 20:58 UTC, gpshead commented
I'm not adding a versionchanged because the exception type when an argument was missing doesn't really count as a meaningful logic part of the API.  Nobody would be likely to ever call this, looking for that exception, and doing something else.  arguments can be made in favor of both TypeError and ValueError, but TypeError is a bit more consistent with the _intent_ so moving it to that seems better.

2019-10-18 03:30 UTC, merged

2019-10-18 03:30 UTC, miss-islington commented
Thanks @gpshead for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖