bpo-30245: possible overflow when organize struct.pack_into error message
python/cpython pull request #1682
Opened 2017-05-20 15:25 UTC by johanliu

I just try to extend the huge sum from signed long to unsigned long in order to print it without showing overflowed effect. 

I suppose it works as expected since you can't make a buffer which size is larger than sys.maxsize. so as before, it make sense.

2017-05-20 15:25 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-05-20 15:36 UTC, serhiy-storchaka requested changes

2017-05-20 15:36 UTC, serhiy-storchaka commented on Modules/_struct.c
> +
Please remove these empty lines. They look distracting.

2017-05-20 15:36 UTC, serhiy-storchaka commented on Lib/test/test_struct.py
> +            " \(actual buffer size is 10\)"
Use raw string literals. Compiling `"\("` emits a deprecation warning.

You also could use classic string formatting, string's format() method, or f-string expression for composing this string.

2017-05-20 15:41 UTC, serhiy-storchaka commented on Misc/ACKS
> +Yuan Liu
Names are sorted in roughly alphabetical order. Thus your name should be about letter L or Y (don't know what of names is a surname).

2017-05-20 16:31 UTC, zhangyangyu approved these changes

2017-05-20 17:08 UTC, serhiy-storchaka approved these changes

2017-05-27 14:30 UTC, Mariatta commented
@johanliu Your PR looks good. Have you signed the CLA? We can't accept the PR until it is signed.
Thank you.

2017-05-27 16:20 UTC, johanliu commented
Hi, I have already signed the CLA but seems like the procedure not finished yet. It takes one week after I submit the application. What should I do right now on this issue? Thank you.

2017年5月27日 +0800 22:30 Mariatta <notifications@github.com>，写道：

@johanliu<https://github.com/johanliu> Your PR looks good. Have you signed the CLA? We can't accept the PR until it is signed.
Thank you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/python/cpython/pull/1682#issuecomment-304455664>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAzzSNWDfVWbkRL2gLgw1BvBtNyMJ8XZks5r-DOagaJpZM4NhU-t>.

2017-06-01 21:53 UTC, Mariatta commented
Thanks @johanliu Looks like your CLA form has been received.
If you can resolve the conflict then I think this PR is ready for merge.

2017-06-02 06:33 UTC, merged