Clarify, for BaseHTTPRequestHandler, that path includes query
python/cpython pull request #16884
Opened 2019-10-22 09:38 UTC by drj11

A minor improvement to the documentation for BaseHTTPRequestHandler in the `http.server` library.
Pointing that the `path` attribute also includes the `query` part, when present.

2019-10-22 14:41 UTC, eamanu approved these changes

2019-10-30 09:32 UTC, drj11 commented
Can someone please add `skip label` and `skip news`? Thanks!

2020-01-11 20:56 UTC, orsenthil requested changes
The content looks good to me. Please make sure to format it at 80 column wrap for better readability.

2020-05-28 23:04 UTC, csabella commented
@drj11, please make the requested changes.  Thanks!

2021-04-25 16:40 UTC, orsenthil commented
Superseded by https://github.com/python/cpython/pull/25597

2021-04-25 16:40 UTC, closed without merging