Add support for extended attributes on FreeBSD
python/cpython pull request #1690
Opened 2017-05-21 03:47 UTC by worr

Extended attributes are supported on FreeBSD, but have
a different API than on Linux. This implements a compatibility
layer so that the same set of python functions map to the
equivalent FreeBSD functions.

This is the patch for issue: https://bugs.python.org/issue12978

2017-05-21 03:47 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-05-21 05:23 UTC, worr commented
I've updated my bpo account to point at my github account, so hopefully that clears up the CLA issue.

2018-05-16 07:45 UTC, grimreaper approved these changes

2022-11-29 19:31 UTC, iritkatriel requested changes
This has merge conflicts now.

2023-04-29 18:43 UTC, arhadthedev commented
Superseded by gh-103994.

2023-04-29 18:43 UTC, closed without merging