bpo-38565: add new cache_parameters method for lru_cache
python/cpython pull request #16916
Opened 2019-10-24 08:10 UTC by Zheaoli

https://bugs.python.org/issue38565

2019-10-29 05:32 UTC, rhettinger requested changes

2019-10-29 05:32 UTC, rhettinger commented on Lib/functools.py
> +        return {"maxsize": maxsize, "typed": typed}
NIt:  Please use single quotes, the same as used by ``dict.__repr__()``

2019-10-29 05:32 UTC, rhettinger commented on Lib/functools.py
> +        return {"maxsize": maxsize, "typed": typed}
Also move the function to just after *cache_clear()*.

2019-10-29 05:32 UTC, rhettinger commented on Lib/test/test_functools.py
> +    def test_lru_cache_parameters(self):
Add a blank line before the *def*.

2019-10-29 05:32 UTC, rhettinger commented on Lib/test/test_functools.py
> +        f = self.module.lru_cache(2)(f)
Let's use the decorator notation to create the example.  Also, make the example use `maxsize=1000` and `typed=True`.

2019-10-29 05:32 UTC, rhettinger commented on Misc/NEWS.d/next/Library/2019-10-24-08-10-30.bpo-38565.SWSUst.rst
> +add new cache_parameters method for lru_cache
``Add new cache_parameters() method for functools.lru_cache() to better support pickling.

2019-10-29 05:32 UTC, rhettinger commented on Modules/_functoolsmodule.c
> +    PyObject *cache_parameters =  PyDict_New();
Need to test whether *cache_parameters* is *NULL*.

2019-10-29 05:32 UTC, rhettinger commented on Modules/_functoolsmodule.c
> +    PyDict_SetItemString(cache_parameters, "maxsize", PyLong_FromSsize_t(self->maxsize));
There are also two possible failure points that need to be tested here as well.

2019-10-29 05:32 UTC, rhettinger commented on Modules/_functoolsmodule.c
> +    PyDict_SetItemString(cache_parameters, "typed", self->typed == 0 ? Py_False : Py_True);
1.  Drop the test for zero, putting the positive case first: ``self->typed ? Py_True : Py_False)``
2. Test the result of *PyDict_SetItemString()* to see if it failed.

2019-10-29 05:32 UTC, rhettinger commented on Modules/_functoolsmodule.c
> +    {"cache_parameters", (PyCFunction)lru_cache_cache_parameters, METH_NOARGS},
Move this down one, just after the *cache_clear* entry.

2019-11-09 01:40 UTC, Zheaoli commented
ping @rhettinger

2019-11-12 06:22 UTC, rhettinger approved these changes

2019-11-12 07:30 UTC, merged