bpo-4630: A cursor blink option for IDLE
python/cpython pull request #16960
Opened 2019-10-28 10:51 UTC by ZackerySpytz

Add an option to toggle IDLE's cursor blink.

Co-Authored-By: Guilherme Polo <ggpolo@gmail.com>
Co-Authored-By: Roger Serwy <roger.serwy@gmail.com>

2019-10-31 03:42 UTC, terryjreedy requested changes
Thank you *very* much for converting this overdue, overlooked patch.  I realize that adjusting the 9-year-old code to the highly revised configdialog was very much *not* 'cut and paste'.

AFAICT, the code works and changes properly persist between sessions.

After the revisions, a new test should be added to test_configdialog.  I expect to write but you can try if you want.

I want this merged in November for the December releases, so ping if I let this go more than a week after revision.

2019-10-31 03:42 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +        frame_cursor_blink_default = Frame(frame_editor, borderwidth=0)
```suggestion
        frame_cursor_blink = Frame(frame_window, borderwidth=0)
```

2019-10-31 03:42 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +                frame_cursor_blink_default: Frame
1. Remove 'default' from comment lines and all code lines, including pack and tracer lines.
The line_number stuff is not an example to follow (I will change it also in a separate PR).

2. Move comment lines to frame_window, as this applies to Shell, Editor, and Output windows.
I want to try putting this just after win_size.

3. Move code similarly.

2019-10-31 03:42 UTC, terryjreedy commented on Lib/idlelib/editor.py
> +            self.text.config(insertofftime=0)
```suggestion
            self.text['insertofftime'] = 0
```

2019-10-31 03:42 UTC, terryjreedy commented on Lib/idlelib/editor.py
> +        self.text._insertofftime = self.text['insertofftime']
The attribute should be attached to self, not the tk text, as with other instance attributes.
```suggestion
        self.blink_off_time = self.text['insertofftime']
```
Corresponding change is suggested below.

The NMT tkinter 8.5 manual says that this is 300, but the tcl/tk 8.6 reference does not give a default, so grabbing the initial time seems safest for matching blinks on a particular system.

This set of new lines belongs further down the file, perhaps following 
`        self.set_notabs_indentwidth()`

2019-10-31 03:42 UTC, terryjreedy commented on Lib/idlelib/editor.py
> +            self.text.config(insertofftime=self.text._insertofftime)
```suggestion
            self.text['insertofftime'] = self.blink_off_time
```
I prefer the pythonic option getting/setting.

2019-11-01 21:26 UTC, ZackerySpytz commented
Thank you, @terryjreedy, for the thorough review. I believe I have addressed all of
your comments.

I was unsure if the `cursor-blink` config option in `config-main.def` should be moved.

I have made the requested changes; please review again.

2019-11-08 21:35 UTC, ZackerySpytz commented
@terryjreedy Ping.

2019-11-13 05:56 UTC, terryjreedy approved these changes
As I noted on the issue, the original news item was not true, but the reduced claim is.  Storing insertofftime on idleConf will make a 2nd patch much easier.

The new update_cursor_blink was tested manually, though a unittest should be added.

2019-11-13 07:13 UTC, merged

2019-11-13 07:15 UTC, miss-islington commented
Thanks @ZackerySpytz for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-11-13 07:15 UTC, miss-islington commented
Thanks @ZackerySpytz for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖