bpo-38316: describe co_stacksize a little bit better
python/cpython pull request #16983
Opened 2019-10-29 10:02 UTC by isidentical

2019-10-29 16:39 UTC, ammaraskar commented on Doc/reference/datamodel.rst
> +      largest size, stack will ever grow to (after certain operations);
Let's get rid of the comma here: "is the largest size the stack will ever grow to"

and maybe reword "after certain operations" to "due to certain instructions" or maybe even omit that part.

2019-11-15 18:47 UTC, ammaraskar commented
hmm, now that I think about this more. I think more appropriate wording would be:

> `co_stacksize` is the largest size the stack will grow to when executing the function;

2019-11-15 22:20 UTC, isidentical commented
@ammaraskar can you check it now?

2019-11-15 22:21 UTC, ammaraskar approved these changes
LGTM with final suggestion

2019-11-15 22:21 UTC, ammaraskar commented on Doc/reference/datamodel.rst
> +      largest size stack will ever grow to when executing the function;
```suggestion
      largest size the stack will ever grow to when executing the function;
```

2019-11-15 23:19 UTC, ammaraskar commented
@vstinner Would you mind taking a look at this?

2019-12-14 14:51 UTC, vstinner requested changes
Objects/frameobject.c allocates an array of `code->co_stacksize + code->co_nlocals + ncells + nfrees` items. The array size doesn't chagne during the execution of the function, it's not like x86 machine mode which manipulates the stack pointer (SP) register and use PUSH/POP.

> :attr:`co_stacksize` is the required stack size (including local variables)

So this definition sounds wrong to me.

Instead, I suggest this definition:

```
:attr:`co_stacksize` is the required stack size
```

=> just remove `(including local variables)`.

2019-12-15 06:41 UTC, isidentical commented
I have made the requested changes; please review again

2019-12-15 22:02 UTC, merged

2019-12-15 22:03 UTC, miss-islington commented
Thanks @isidentical for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-12-15 22:03 UTC, miss-islington commented
Thanks @isidentical for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-12-15 22:03 UTC, miss-islington commented
Sorry, @isidentical and @vstinner, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker d587272fe3b0fcad2f23a490e76f9f82ca7d64ef 3.7
                                ```

2019-12-15 22:03 UTC, miss-islington commented
Sorry @isidentical and @vstinner, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker d587272fe3b0fcad2f23a490e76f9f82ca7d64ef 3.8
                                ```

2019-12-15 22:04 UTC, vstinner commented
@isidentical: The automated backport to 3.7 and 3.8 failed. Can you please try to manually backport these changes? Use " cherry_picker d587272fe3b0fcad2f23a490e76f9f82ca7d64ef 3.8" or "git cherry-pick -x d587272fe3b0fcad2f23a490e76f9f82ca7d64ef".

2019-12-18 20:45 UTC, vstinner commented
Ping @isidentical, tell me if you prefer that I do the backport.

2019-12-19 14:06 UTC, isidentical commented
Thanks for the ping @vstinner, I totally forgot backports. Sending them right away