Make default value immutable
python/cpython pull request #17007
Opened 2019-10-31 01:35 UTC by EFanZh

Better to use immutable default values.

2019-10-31 01:35 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@EFanZh

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-10-31 05:47 UTC, brandtbucher commented
Thanks for your time @EFanZh, and welcome to CPython! :sunglasses:

2019-10-31 05:55 UTC, brandtbucher requested changes
This looks good to me. However, given that it does touch a user-facing interface (albeit trivially), this probably needs [a bugs.python.org issue](https://bugs.python.org) and [a NEWS entry](https://blurb-it.herokuapp.com).

For the NEWS entry, something fairly simple like this should be fine:

```rst
Replaced a mutable default argument in the constructor for :class:`urllib.request.Request` with :const:`None`.
```

2019-10-31 16:29 UTC, brandtbucher approved these changes

2019-10-31 16:30 UTC, brandtbucher commented
CC @orsenthil

2019-11-11 12:01 UTC, tirkarthi commented
The PR can be closed since the linked bug is also closed as not a bug.

2019-11-11 19:19 UTC, orsenthil commented
https://bugs.python.org/issue38654 lists the reason for not accepting this patch. 
Thanks for your contribution, @EFanZh

2019-11-11 19:19 UTC, closed without merging