doc(http.client): fix link for requests package
python/cpython pull request #17006
Opened 2019-10-30 21:16 UTC by simon04

2019-10-30 21:16 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@simon04

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-10-30 22:14 UTC, brandtbucher approved these changes
Thanks for your time @simon04, and welcome to CPython! :sunglasses:

Looks good to me.

2019-10-30 22:15 UTC, Mariatta commented on Doc/library/http.client.rst
> +    The `Requests package <https://requests.kennethreitz.org/>`_
```suggestion
    The `Requests package <https://requests.readthedocs.io/en/master/>`_
```

2019-10-30 22:15 UTC, Mariatta requested changes
Thanks for the fix, however the right url is https://requests.readthedocs.io/en/master/

2019-10-31 06:59 UTC, simon04 commented
I have made the requested changes; please review again

2019-10-31 11:58 UTC, Mariatta approved these changes

2019-10-31 12:01 UTC, merged

2019-10-31 12:02 UTC, miss-islington commented
Thanks @simon04 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-10-31 12:02 UTC, miss-islington commented
Thanks @simon04 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-10-31 14:58 UTC, brandtbucher commented
Congrats on your first CPython contribution @simon04! :champagne:

Looking forward to seeing more from you in the future.