bpo-38693: Use f-strings instead of str.format() within importlib
python/cpython pull request #17058
Opened 2019-11-05 06:23 UTC by gpshead

This is a small performance improvement, especially for one or two hot
places such as `_handle_fromlist()` that are called a lot and the
`str.format()` method was being used just to join two strings with a `'.'`.

Otherwise it is merely a readability improvement.

This could be backported to 3.8 as it does not change any logic.

I kept `_ERR_MSG` as an attribute in `importlib._bootstrap` and `imp`
as I wasn't sure if there were other things in the world that might
refer to those.  They're private and could go away in 3.9 but should
not within 3.8 just in case.

2019-11-05 14:39 UTC, ericvsmith reviewed
I think this is generally a good idea, and all of the changes look correct.

However, I'm not sure I'd remove the use of _ERR_MSG, since it is used outside of this file. Either that, or remove it in Lib/imp.py, too (the only other place it's used).

I'm also not sure what value is added by _ERR_MSG_PREFIX. It doesn't seem to be used anywhere. I'd just roll it into _ERR_MSG, if it's being kept.

2019-11-05 20:41 UTC, brettcannon commented
`_ERR_MSG` was actually created specifically because there have been numerous instances where that sentence has been formatted differently across the code base (with or without a period, capitalized or not, wording, etc.). I think `_ERR_MSG_PREFIX` was created because it was used from `import.c`.

2019-11-05 20:41 UTC, brettcannon requested changes
Need to decide what the ultimate fate of `_ERR_MSG` is.

2020-01-25 13:32 UTC, csabella commented
@gpshead, please take a look at the review comments.  Thanks!

2021-05-26 19:58 UTC, jaraco approved these changes

2022-05-17 16:40 UTC, ambv commented
This missed the boat for inclusion in Python 3.9 which accepts security fixes only as of today.

2022-10-06 22:23 UTC, gpshead commented
> I'm not sure I'd remove the use of _ERR_MSG, since it is used outside of this file. Either that, or remove it in Lib/imp.py, too (the only other place it's used).

I left `_ERR_MSG` and `_ERR_MSG_PREFIX` in place as they could be used by others. The code now uses the latter within its own f-string.

PTAL

2022-10-06 22:29 UTC, ericvsmith reviewed
Other than the tiny nit I mentioned, LGTM.

2022-10-06 22:29 UTC, ericvsmith commented on Lib/importlib/_bootstrap.py
> +        message = (f'import of {name} halted; None in sys.modules')
The parens here can be deleted; it looks like they were previously used for the multi-line string.

2022-10-06 22:47 UTC, ericvsmith approved these changes

2022-10-06 23:43 UTC, merged