[2.7] Fix typos in multiple `.rst` files (GH-1668)
python/cpython pull request #1707
Opened 2017-05-21 23:40 UTC by delirious-lettuce

I fixed many of the same typos as in my previous PR #1668 . There were fewer typos overall in the `2.7` docs (at least of the same words as the other PR).

2017-05-21 23:40 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-05-22 06:03 UTC, serhiy-storchaka requested changes

2017-05-22 06:03 UTC, serhiy-storchaka commented on Modules/zlib/configure
> +# update Makefile with the configure results
Please revert the change in this file.

2017-05-22 16:15 UTC, delirious-lettuce commented on Modules/zlib/configure
> +# update Makefile with the configure results
@serhiy-storchaka ,

My mistake, should now be fixed below.

2017-05-22 16:21 UTC, serhiy-storchaka approved these changes

2017-05-22 17:16 UTC, merged