bpo-38771
python/cpython pull request #17108
Opened 2019-11-11 22:42 UTC by jonathan-scholbach

2019-11-11 22:43 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@jonathan-scholbach

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-11-12 00:06 UTC, rhettinger requested changes

2019-11-12 00:06 UTC, rhettinger commented on Doc/library/collections.rst
> +        command_line_args = {k: v for k, v in vars(namespace).items() if v is not None}
I think reads better without the space before *v*.

2019-11-12 00:49 UTC, merged

2019-11-12 00:49 UTC, miss-islington commented
Thanks @jonathan-scholbach for the PR, and @rhettinger for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖