Update _threadmodule.c
python/cpython pull request #17116
Opened 2019-11-12 10:02 UTC by toywei

cpuNum>1 ,rlock_count<0

2019-11-12 17:20 UTC, brandtbucher commented
Thanks for the PR @toywei!

Since these changes touch live code, though, this should have [a BPO issue](https://bugs.python.org) and [a NEWS entry](https://blurb-it.herokuapp.com).

2019-11-12 17:21 UTC, brandtbucher requested changes
I'm a bit confused. Do you have a specific bug you can show us that's fixed by this?

2019-11-12 17:21 UTC, brandtbucher commented on Modules/_threadmodule.c
> +    if (self->rlock_count <= 0 || self->rlock_owner != tid) {
`rlock_count` is an `unsigned long` here, so I can't see why this change would be necessary.

2020-01-11 00:17 UTC, csabella commented
I'm going to close this as the code review and the request for a bpo ticket hasn't been addressed.  This can be reopened if the original author is interested in addressing the review.  Thank you!

2020-01-11 00:17 UTC, closed without merging