bpo-38741: Definition of multiple ']' in header configparser
python/cpython pull request #17129
Opened 2019-11-12 18:47 UTC by jsnklln

I've changed up the regex for finding section headers.
I don't know if this covers every case but it covers
all the cases I could come up with.  The docs don't really
call out if ] should be allowed in section headers but
I can't think of any reason it shouldn't be.

This change keeps the existing failure if you try and
define a section with no name, like [].

2019-11-12 20:23 UTC, brandtbucher commented
Thanks @jsnklln!

2019-11-12 20:23 UTC, brandtbucher requested changes
The patch itself looks good, but I don't know enough about this module to decide if this behavior is technically correct or not. @ambv, thoughts?

Also, this probably needs a test or two. Can you include them in `test_configparser.py`?

2019-11-12 20:47 UTC, jsnklln commented
@brandtbucher adding some tests sounds like fun.  I'm totally open to opinions on how to best handle it.

2019-11-13 08:19 UTC, mark99i commented
its is a my commit! 
https://github.com/python/cpython/pull/17086/commits/46751c6fbce254425a7c3b2e824fc15a3a825630
or was it not customary to point to the source?

2019-11-13 14:49 UTC, jsnklln commented
@mark99i I didn't realize we were working on the same bug.  There's not a PR on the bug tracker and I'm pretty sure I pulled from changes master yesterday but I hay not have. 

One note.  Using .* allows [] to be considered valid where with the previous version it threw an exception.  ConfigParser doesn't allow definitions without a section, I'm pretty sure that's still true, so I don't know where those would go if they were allowed.

2019-11-13 15:59 UTC, jsnklln commented
@mark99i I didn't realize we were working on the same bug.  There's not a PR on the bug tracker and I'm pretty sure I pulled from changes master yesterday but I hay not have. 

One note.  Using .* allows [] to be considered valid where with the previous version it threw an exception.  ConfigParser doesn't allow definitions without a section, I'm pretty sure that's still true, so I don't know where those would go if they were allowed.

2019-11-13 16:25 UTC, jsnklln commented
@brandtbucher tests have been pushed.

2019-11-13 21:15 UTC, brandtbucher approved these changes
Thanks @jsnklln! I recommended that #17086 be closed in favor of this, since it contains tests and handles the empty case.

2019-11-13 22:02 UTC, jsnklln commented
@brandtbucher thanks.  @mark99i sorry we got our wires crossed up, I'll gladly split the credit.

2019-12-04 02:59 UTC, jsnklln commented
@brandtbucher is this waiting on something to be merged?  Not being pushy just want to make sure I've got all my t's dotted.

2020-07-17 17:02 UTC, brandtbucher commented
Closing and reopening to trigger CI.

2020-07-17 17:40 UTC, brandtbucher commented
@ambv This patch is simple and looks fine to me. Do you mind clearing up whether or not it is correct to allow `]` in header names? If so, it can probably be merged.

2021-07-13 13:54 UTC, merged

2021-07-13 13:54 UTC, miss-islington commented
Thanks @jsnklln for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖