bpo-37838: get_type_hints for wrapped functions with forward reference
python/cpython pull request #17126
Opened 2019-11-12 15:19 UTC by benedwards14

2019-11-12 17:55 UTC, brandtbucher requested changes
This looks like a good change to me! Just a few comments below to fix CI and clean things up.

2019-11-12 17:55 UTC, brandtbucher commented on Lib/test/ann_module.py
> +    return wraps(func)(wrapper)
I think the tests are failing because of this missing newline:

```suggestion
    return wraps(func)(wrapper)

```

2019-11-12 17:55 UTC, brandtbucher commented on Lib/test/ann_module.py
> +    def wrapper(*args, **kwargs):
Any reason why this doesn't use `wraps` as a decorator?

```suggestion
    @wraps(func)
    def wrapper(*args, **kwargs):
```

2019-11-12 17:55 UTC, brandtbucher commented on Lib/test/test_typing.py
> +    def func(a: 'ForRefExample'):
Minor, but maybe just name this argument `self` for cleanliness?

```suggestion
    def func(self: 'ForRefExample'):
```

2019-11-12 17:55 UTC, brandtbucher commented on Lib/test/test_typing.py
> +    def nested(a: 'ForRefExample'):
See above:

```suggestion
    def nested(self: 'ForRefExample'):
```

2019-11-12 17:55 UTC, brandtbucher commented on Lib/test/test_typing.py
> +        expects = {'a': ForRefExample}
See above:

```suggestion
        expects = {'self': ForRefExample}
```

2019-11-12 17:58 UTC, brandtbucher commented
Thanks for the PR @benedwards14!

This one should also have [a NEWS entry](https://blurb-it.herokuapp.com). Just something simple, like:

```rst
:meth:`typing.get_type_hints` properly handles functions decorated with :meth:`functors.wraps`. 
```

2019-11-21 11:40 UTC, benedwards14 commented
Hey @brandtbucher, thanks for the review. Here a re the markups.

2019-11-21 14:31 UTC, brandtbucher requested changes
Looks good! Just a couple of remaining style nitpicks:

2019-11-21 14:31 UTC, brandtbucher commented on Lib/test/test_typing.py
> +class ForRefExample():
No parentheses here, and 2 blank lines between top-level definitions:

```suggestion

class ForRefExample:
```

2019-11-21 14:31 UTC, brandtbucher commented on Lib/test/test_typing.py
> +        self.assertEqual(gth(ForRefExample.nested), expects)
Two blank lines between top-level definitions:

```suggestion
        self.assertEqual(gth(ForRefExample.nested), expects)

```

2019-11-21 14:31 UTC, brandtbucher commented on Lib/test/test_typing.py
> +        pass
Two blank lines between top-level definitions:

```suggestion
        pass

```

2019-11-21 16:33 UTC, brandtbucher requested changes
Sorry, one last typo I spotted. Then good!

2019-11-21 16:33 UTC, brandtbucher commented on Misc/NEWS.d/next/Library/2019-11-21-11-39-17.bpo-37838.lRFcEC.rst
> +:meth:`typing.get_type_hints` properly handles functions decorated with :meth:`functors.wraps`.
Autocorrect. 🙄

```suggestion
:meth:`typing.get_type_hints` properly handles functions decorated with :meth:`functools.wraps`.
```

2019-11-21 17:18 UTC, brandtbucher commented
@ilevkivskyi

2019-11-21 17:22 UTC, ilevkivskyi approved these changes
Looks good, thanks!

2019-11-21 17:23 UTC, ilevkivskyi commented
(Added backport labels since this is a bugfix.)

2019-11-21 17:24 UTC, merged

2019-11-21 17:25 UTC, miss-islington commented
Thanks @benedwards14 for the PR, and @ilevkivskyi for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖