Reuse identifier of PREDICT macros as PREDICT_ID
python/cpython pull request #17155
Opened 2019-11-14 16:51 UTC by deiuch

_Trivial change_

In function `_PyEval_EvalFrameDefault`, macros `PREDICT` and `PREDICTED` use the same identifier creation scheme, which may be shared between them, reducing code repetition, and do ensure that the same identifier is generated.

2019-11-14 18:17 UTC, brandtbucher commented
Thanks for your time @deiuch, and welcome to CPython!

2019-11-14 18:21 UTC, brandtbucher requested changes
I don't think we need a third macro. In your changes, `PREDICTED` and `PREDICT_ID` are aliases, right?

So why not just replace the two occurrences of `PRED_##op` in the definition of `PREDICT` with `PREDICTED(op)`?

2019-11-14 18:25 UTC, deiuch commented
> I don't think we need a third macro. In your changes, `PREDICTED` and `PREDICT_ID` are aliases, right?
> 
> So why not just replace the two occurrences of `PRED_##op` in the definition of `PREDICT` with `PREDICTED(op)`?

They are a bit different constructs. `PREDICTED` is a label statement, which is intended for use as a "landing pad" of `goto`'s that address prediction of the given operator. There is a trailing colon character :)

2019-11-14 18:47 UTC, brandtbucher approved these changes
Ah, I missed the colon. This looks good, then!

2020-02-21 08:45 UTC, taleinat approved these changes
Indeed, looks good. I'll wait for input from someone with more experience with this C code though.

2020-02-21 09:14 UTC, pitrou approved these changes
+1, thank you.

2020-02-21 09:17 UTC, pitrou commented
Opcode prediction is disabled on gcc / clang builds and enabled on MSVC, so both cases should be exercised by CI. Merging.

2020-02-21 09:17 UTC, merged

2020-02-21 10:34 UTC, serhiy-storchaka commented
It reduced readability of the code to me. I need now to search the definition of a new macro when I read definitions of PREDICT and PREDICTED, and it is not easy with my conditions.

2020-02-21 10:46 UTC, deiuch commented
@serhiy-storchaka, you mean it is now harder to read with your IDE?

2020-02-21 14:13 UTC, serhiy-storchaka commented
I do not use IDE.

2020-02-21 15:11 UTC, brandtbucher commented
Congrats on your first CPython contribution, @deiuch! :champagne:

Looking forward to seeing more from you in the future.