Allow translating argument error messages
python/cpython pull request #17169
Opened 2019-11-15 11:56 UTC by DjMorgul

2019-11-15 11:56 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@DjMorgul

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-11-15 16:44 UTC, brandtbucher commented
Thanks for your time @DjMorgul, and welcome to CPython! :sunglasses:

I assume that you've seen the bot's message about the CLA?

2019-11-15 16:55 UTC, brandtbucher requested changes
I don't think this is necessary... we don't internationalize any other exception messages in this file.

If this exception is raised during parsing, it is printed by calling `ArgumentParser.error`, which performs this step already (see the last line of the file).

It would be great if you could open [a BPO issue](https://bugs.python.org) for discussion.

2019-11-17 12:33 UTC, DjMorgul commented
This message isn't used (only?) in exceptions... it's a message that is given to the console, to notify the user when she didn't provide correct parameters. For example:

```
$ python3 ./drt.py -l
Uso: ./drt.py [-h] [-l LONG_MIN] [-L LONG_MAX] [-v] [-V]
              entrada.json [salida.tok]
./drt.py: error: argument -l/--min-length: se esperaba un parámetro
```

These are console messages localized into Spanish. The "error:" part is translatable, but it's the same word in Spanish than in English. The "argument" part is what isn't translatable, and it's taken from this "exception".

I confirmed that my proposed patch, translating that particular string, allows giving a fully localized console output to the user in Spanish, such as:

`./drt.py: error: parámetro -l/--min-length: se esperaba un parámetro`

2019-11-18 15:28 UTC, taleinat commented
@DjMorgul, the place to discuss this is on our issue tracker. Please [create an issue on bugs.python.org](https://bugs.python.org/issue?@template=item), as suggested above by @brandtbucher.

2020-01-25 13:41 UTC, csabella commented
@DjMorgul, did you have a chance to open an issue on the bug tracker as requested by @taleinat?  If so, please update the PR title with the format `bpo-xxxxx:` for the tracker number.  Thanks!

2020-01-27 14:01 UTC, DjMorgul commented
I just created the issue on bugs.python.org, and I updated the title of this pull request accordingly.

2022-05-05 04:25 UTC, rhettinger approved these changes

2022-05-05 04:27 UTC, rhettinger approved these changes

2022-05-05 05:32 UTC, merged