bpo-25532: Protect against infinite loops in inspect.unwrap()
python/cpython pull request #1717
Opened 2017-05-22 12:16 UTC by takluyver

Some objects, such as `unittest.mock.call`, generate a new similar object every time you access `obj.__wrapped__`. This isn't caught by the memoise loop protection, because each object has a different ID. So a call like `inspect.getsourcelines(unittest.mock.call)` goes into an infinite loop, using ever more memory as it creates new objects.

This implements @ncoghlan's suggestion in [issue 22532](http://bugs.python.org/issue25532): if we've unwrapped something `sys.getrecursionlimit()` times, assume it's an infinite chain and give up. Things like `getsourcelines()` will fail, but an exception is better than using up all the memory.

IPython's inspection machinery already has a similar check, with an arbitrary limit of 100 unwraps. That returns the original object if the limit is exceeded, rather than throwing an error.
https://github.com/ipython/ipython/blob/6.0.0/IPython/core/oinspect.py#L279

2017-05-22 13:38 UTC, ncoghlan commented
+1 from me, so this just needs a Misc/NEWS entry noting the fix.

2017-05-22 14:12 UTC, takluyver commented
Added a NEWS entry :-)

2017-05-22 14:42 UTC, ncoghlan commented
Hah, that'll teach me to review patches late at night - I missed a more important omission, which is to add a test case that triggers the new check :)

2017-05-22 14:44 UTC, takluyver commented
I take it you don't want the test to use `unittest.mock` and go into an infinite loop if this is ever broken? ;-)

2017-05-22 16:31 UTC, takluyver commented
How does that test look?

2017-05-22 18:23 UTC, 1st1 requested changes

2017-05-22 18:23 UTC, 1st1 commented on Lib/inspect.py
>      memo = {id(f)} # Memoise by id to tolerate non-hashable objects
While we are here: we should switch to use a dictionary `{id(o): o}`. The same approach that `deepcopy` uses to ensure that objects stay alive long enough.

2017-05-22 19:12 UTC, takluyver commented on Lib/inspect.py
>      memo = {id(f)} # Memoise by id to tolerate non-hashable objects
Done.

2017-05-22 19:47 UTC, pppery commented
Why can't you use `len(memo)` instead of creating a seperate `unwrap_count` variable?

2017-05-22 20:00 UTC, 1st1 commented
+1 to the `len(memo)` idea.

2017-05-23 03:27 UTC, merged

2017-05-23 03:30 UTC, ncoghlan commented
Thanks for the patch @takluyver, and thanks for the suggested improvements @1st1 and @pppery :)

2017-09-07 00:25 UTC, miss-islington commented
🐍🍒⛏🤖 Thanks @takluyver for the PR, and @ncoghlan for merging it 🌮🎉.I'm working now to backport this PR to: 3.6.

2017-09-07 00:25 UTC, miss-islington commented
Sorry, @takluyver and @ncoghlan, I could not cleanly backport this to `3.6` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.