bpo-25866: Minor cleanups to "sequence" in docs
python/cpython pull request #17177
Opened 2019-11-15 20:02 UTC by alclarks

Hi, this is a pull request for my patch for BPO issue 25866.

2019-11-15 20:19 UTC, brandtbucher commented
Thanks @alclarks! I've recommended that #17175 be closed in favor of this PR.

2019-11-15 20:34 UTC, brandtbucher requested changes
A bit of minor cleanup, but otherwise this looks good:

2019-11-15 20:34 UTC, brandtbucher commented on Doc/reference/datamodel.rst
> +  of the iterator's values. However, the *__slots__* variable will be an empty
```suggestion
  of the iterator's values. However, the *__slots__* attribute will be an empty
```

2019-11-15 20:34 UTC, brandtbucher commented on Doc/reference/datamodel.rst
> +through the container; for mappings, :meth:`__iter__` should return an iterator
Minor, but in my opinion it helps the sentence read better.

```suggestion
through the container; for mappings, :meth:`__iter__` should iterate
```

2019-11-15 20:59 UTC, alclarks commented
Thanks for the review @brandtbucher, does this one require a news entry?

2019-11-15 22:32 UTC, brandtbucher commented
Do you think so? If not, I can add the label.

2019-11-15 23:43 UTC, alclarks commented
Because it's entirely documentation and not documenting any new feature I don't think the news would be useful - but I'm happy to add one if you think it's a big enough change to warrant some news :)

2019-11-15 23:47 UTC, brandtbucher commented
Agreed... I think your judgement is correct here.

2019-11-15 23:49 UTC, brandtbucher commented
CC @rhettinger

2019-11-17 22:00 UTC, merged

2019-11-17 22:00 UTC, miss-islington commented
Thanks @alclarks for the PR, and @rhettinger for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-11-17 22:01 UTC, miss-islington commented
Thanks @alclarks for the PR, and @rhettinger for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-11-18 00:04 UTC, brandtbucher commented
Congrats on your first CPython contribution @alclarks! :champagne:

Looking forward to seeing more from you in the future.

2019-11-18 10:20 UTC, alclarks commented
Thanks @brandtbucher and @rhettinger for the review and merge!