bpo-38821: Fix crash in argparse when using gettext
python/cpython pull request #17192
Opened 2019-11-16 17:52 UTC by federicobond

2019-11-16 17:52 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@federicobond

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-11-16 18:35 UTC, brandtbucher commented
Thanks for your time, and welcome to CPython @federicobond!

I assume that you've seen the bot's message about the CLA?

2019-11-16 23:10 UTC, federicobond commented
Hi there @brandtbucher, yes. Waiting for the CLA to get accepted! Should I include a changelog in the PR?

2019-11-16 23:16 UTC, brandtbucher commented
Yes please! You can do so easily [here](https://blurb-it.herokuapp.com).

2019-11-16 23:28 UTC, federicobond commented
Done! I was not feeling particularly inspired writing the news entry, so feel free to suggest changes.

2019-11-17 06:19 UTC, rhettinger commented
Please add a test.

2019-11-17 06:52 UTC, federicobond commented
I could not find any existing test exercising locale support in argparse. What would this test assert?

2019-11-18 15:14 UTC, taleinat commented
> I could not find any existing test exercising locale support in argparse. What would this test assert?

I suggest test various possible values for nargs, including all of the special ones, when using gettext.

2019-11-18 22:07 UTC, federicobond commented
I think adding those tests would be a great idea but none of them would fail prior to this change, so I am not sure we should bundle them together.

A proper regression test for this change needs to load a custom catalog, bind it to the global domain, etc.

2019-11-19 01:38 UTC, brandtbucher requested changes
Just a bit of clarification on the NEWS entry:

2019-11-19 01:38 UTC, brandtbucher commented on Misc/NEWS.d/next/Library/2019-11-16-23-26-25.bpo-38821.-albNN.rst
> +Fix crash in argparse when using gettext.
```suggestion
Fix unhandled exceptions in :mod:`argparse` when internationalizing error some messages.
```

2019-11-19 08:30 UTC, taleinat commented
> A proper regression test for this change needs to load a custom catalog, bind it to the global domain, etc.

We could also monkey-patch `argparse._` and `argparse.ngettext` using `unittest.mock.patch`, which should be simpler to set up.

That being said, this is an obvious fix and we have no existing tests for this, so I realize demanding that you add such tests is rather unfair. Let me know whether you'd like to try, and I'll take care of things even if you don't.

2019-11-19 16:59 UTC, federicobond commented
@taleinat sure, I can do that. Do you think those tests should accompany this PR or should I open a new one? I would rather submit another PR so we can discuss them separately and not stall this changeset, but whatever works best for the maintainers is good for me.

2019-11-20 08:39 UTC, taleinat commented
@federicobond, yes, let's go with a separate issue and PR for adding such tests.

2019-11-20 08:43 UTC, taleinat commented on Misc/NEWS.d/next/Library/2019-11-16-23-26-25.bpo-38821.-albNN.rst
> +Fix unhandled exceptions in :mod:`argparse` when internationalizing some error messages.
```suggestion
Fix unhandled exceptions in :mod:`argparse` when internationalizing error messages for arguments with ``nargs`` set to special (non-integer) values.  Patch by Federico Bond.
```

2019-11-20 13:26 UTC, taleinat approved these changes

2019-11-20 13:29 UTC, merged

2019-11-20 13:29 UTC, miss-islington commented
Thanks @federicobond for the PR, and @taleinat for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-11-20 13:29 UTC, miss-islington commented
I'm having trouble backporting to `3.8`. Reason: '`Error 110 while writing to socket. Connection timed out.`'. Please retry by removing and re-adding the `needs backport to 3.8` label.

2019-11-20 13:29 UTC, miss-islington commented
Thanks @federicobond for the PR, and @taleinat for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-11-20 16:11 UTC, brandtbucher commented
Congrats on your first CPython contribution @federicobond! :champagne:

Looking forward to seeing more from you in the future.

2019-11-20 18:29 UTC, federicobond commented
Thank you @brandtbucher & co! I can see that you have all put a lot of effort into making this a pleasurable experience, definitely makes me want to contribute again 🎉