Added missing coma after end of list in subprocess.rst
python/cpython pull request #17217
Opened 2019-11-18 07:06 UTC by Seluj78

2019-11-18 10:41 UTC, Seluj78 reviewed
I'm dumb sometimes

2019-11-18 10:41 UTC, Seluj78 commented on Doc/library/subprocess.rst
> +**Source code:** :sourc:`Lib/subprocess.py`
```suggestion
**Source code:** :source:`Lib/subprocess.py`
```

2019-11-18 16:46 UTC, brandtbucher requested changes

2019-11-18 16:46 UTC, brandtbucher commented on Doc/library/subprocess.rst
> +      ``executable``, ``args``, ``cwd`` and ``env``. The value for ``args``
```suggestion
      ``executable``, ``args``, ``cwd``, and ``env``. The value for ``args``
```

2019-11-19 00:53 UTC, brandtbucher approved these changes

2019-11-19 12:14 UTC, csabella approved these changes

2019-11-19 12:14 UTC, merged

2019-11-19 12:14 UTC, miss-islington commented
Thanks @Seluj78 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-11-19 12:14 UTC, miss-islington commented
Sorry @Seluj78, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker f25875af425a3480e557aaedf49c3bb867bcbd5d 3.8
                                ```