Be more specific about the `.so` gitignore patterns
python/cpython pull request #17328
Opened 2019-11-21 20:48 UTC by asottile

In #15823 the pattern was changed from `libpython*.so*` to `*.so*` which
matches a bit too greedily for some packagers.  For instance this trips up
`debian/README.source`.  A more specific pattern fixes this issue.

2019-11-21 20:49 UTC, asottile commented
CC @zware @gnprice

2019-11-23 01:54 UTC, eamanu requested changes
I don't know if separate the entry on .gitignore is a good idea.

`*.so*` work fine for `*.so*` files

2019-11-23 02:02 UTC, asottile commented
> I don't know if separate the entry on .gitignore is a good idea.
> 
> `*.so*` work fine for `*.so*` files

@eamanu  please see the linked discussion -- thanks!

2019-11-27 04:54 UTC, zware approved these changes

2019-11-27 04:54 UTC, merged

2019-11-27 04:54 UTC, miss-islington commented
Thanks @asottile for the PR, and @zware for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2019-11-27 04:54 UTC, miss-islington commented
Sorry @asottile and @zware, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 1ef4c32c8d4f374adfea599f033fa61254bf951d 3.8
                                ```