bpo-27873: Update docstring for multiprocessing.Pool.map
python/cpython pull request #17367
Opened 2019-11-24 14:05 UTC by aisk

Co-authored-by: @naught101 .

This PR is transpered from https://bugs.python.org/issue27873

2019-11-24 14:05 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@aisk

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-11-24 14:18 UTC, aisk commented
@aeros

2019-11-24 15:24 UTC, corona10 commented
@aisk 

Thanks for the contribution to CPython project :)
Glad to meet you again on Github. 
Would you like to sign up for the CLA, please?

2019-11-24 15:30 UTC, corona10 reviewed
@berkerpeksag 
Dear core developers,

@aisk is the first time contributor to this project.
This PR looks good to me except the CLA is not done yet.

Please take a look @aisk PR kindly.

Thank you for understanding :)

2019-11-24 16:05 UTC, aisk commented
@corona10 Hi thanks for your welcome! Happy to see you again!

The CLA is signed,  and I think it's taking time to complete? The bot said it's taking a work day usually.

2019-11-24 16:17 UTC, corona10 commented
> The CLA is signed, and I think it's taking time to complete? The bot said it's taking a workday usually.

Yes, it is expected to take some time. Let's wait until then. :)
I request the final review to the core developer.

If you need my help please ping me any time 

Thanks for your contribution!

2019-11-24 16:22 UTC, aisk commented
:smiley: Thank you again!

2019-11-24 21:19 UTC, aeros requested changes
Thanks for the PR @aisk and welcome!

I approve the general goal of the PR, but I would recommend a slight change in wording:

```
      A parallel equivalent of the built-in function :func:`map`. It blocks
      until the result is ready.

      Unlike :func:`map`, this method supports only one *iterable*
      argument. For functions that require multiple arguments, see
      :meth:`starmap`.
```

(Note: adjusted the word wrapping because it exceeded 80 chars per line with the changes I recommended)

2019-11-26 05:23 UTC, aisk commented
Updated, and the CLA check is passed.

2019-11-26 08:12 UTC, aeros approved these changes
Thanks for making the recommended changes @aisk, LGTM.

2019-11-26 13:35 UTC, corona10 approved these changes
lgtm

2019-11-26 14:35 UTC, corona10 commented
Dear @rhettinger 

This PR is the @aisk 's first time contributing to this project.
Can you please take a look at this PR as the core developer?
Triagers reviewed it already, only left is the core developer's decision. :)
Thank you for your understanding.

2019-11-26 22:55 UTC, rhettinger commented
Sorry, I'm going to recommend rejecting this edit as being unnecesary.  The argument signature already shows that only one iterable is accepted.

AFAICT, no one has ever been confused by the current docs.  There has been interest in changing the signature to accommodate multiple inputs, but that is a different matter than whether the current docs are accurate.

2019-11-27 05:08 UTC, aisk commented
@rhettinger Hi I'm fine with this, and have another question. If we change the signature to allow it accept multiple iterable as input,  how to compat with old codes? Some developer could call this with chunksize withoud keyword argument like `pool.map(func, iterable, 10)`.

Can we just check the chunksize's type and make it compatible? or mark it as a breaking change?

2019-11-27 05:55 UTC, aeros commented
@rhettinger 
> Sorry, I'm going to recommend rejecting this edit as being unnecesary. The argument signature already shows that only one iterable is accepted.

While there's already a mention of `pool.map()` only accepting one iterable, I think it's helpful to briefly mention and link to `pool.starmap()` as an alternative if more than one is needed. @berkerpeksag suggested mentioning this in the bpo issue, which seems to be the primary purpose of the PR:

> I think we can add a note for starmap() in the following sentence:
> > [...] (it supports only one iterable argument though).

Perhaps the PR be edited to leave the existing "supports only one iterable" part intact, and modify it only slightly to mention `pool.starmap()` (which is more along the lines of @berkerpeksag's suggestion):

```
      A parallel equivalent of the :func:`map` built-in function (it supports only
      one *iterable* argument though, for multiple iterables see :meth:`starmap`).
      It blocks until the result is ready.
```

Also, it might be helpful to obtain additional input on this from @pitrou, since he's an active [expert/maintainer](https://devguide.python.org/experts/#stdlib) for the multiprocessing module.

2019-11-27 09:07 UTC, closed without merging

2019-11-27 11:59 UTC, pitrou commented
I'd be in favour of @aeros' proposed change. Feel free to open a new PR :-)

2019-11-27 19:33 UTC, aeros commented
@pitrou 
> I'd be in favour of @aeros' proposed change. Feel free to open a new PR :-)

Awesome, sounds good. (:

@aisk Let me know if you'd like to open a PR with the above recommended changes (or simply open it and @ mention me).

2019-11-28 03:29 UTC, aisk commented
@aeros ok, I'll try it later this day, thanks!