bpo-37347: Require SQLite 3.7.3+
python/cpython pull request #17413
Opened 2019-11-28 15:42 UTC by sir-sigurd

[#14268](https://github.com/python/cpython/pull/14268/files#diff-2eeaed663bd0d25b7e608891384b7298R1351) makes `sqlite3` module require SQLite 3.7.2+ because it's using `sqlite3_create_function_v2()`, but actually it was added in [SQLite 3.7.3](https://sqlite.org/changes.html#version_3_7_3).

This PR:
* updates `setup.py` to require SQLite 3.7.3+
* removes unneeded code that was required for support of older SQLite versions
* explicitly states required SQLite version in doc of `sqlite3` module

2019-12-09 10:45 UTC, ned-deily commented
Thanks for the PR but, as bpo-37347 is closed and was focused on a specific problem, you should open a separate issue to propose dropping support for SQLite versions prior to 3.7.3 and move this PR to it.

2019-12-11 01:10 UTC, berkerpeksag requested changes
I agree with Ned that removing pre 3.7.3 code from sqlite3 needs its own issue.

2019-12-11 01:10 UTC, berkerpeksag commented on Doc/library/sqlite3.rst
> +   This module requires SQLite 3.7.3+.
I think this information can be incorporated into the following paragraph:

```rst
The sqlite3 module was written by Gerhard Häring.  It provides a SQL interface
compliant with the DB-API 2.0 specification described by :pep:`249`.
```

2020-01-25 13:50 UTC, csabella commented
@sir-sigurd please address the review comments.  If the new bug tracker issue has already been created, please mention it in this PR and close this one.  Thanks!

2020-05-22 22:11 UTC, csabella commented
@sir-sigurd, ping

2020-07-06 18:31 UTC, sir-sigurd commented
Closing in favor of https://github.com/python/cpython/pull/20909.

2020-07-06 18:31 UTC, closed without merging