38952: support new Python3 IPv4Address and IPv6Address
python/cpython pull request #17434
Opened 2019-12-02 01:08 UTC by vegerot

Add support for new Python3 IPv4Address and IPv6Address inet types.  This is tested and forwards and backwards compatible with different host types.

2019-12-02 01:08 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@vegerot

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-12-02 01:14 UTC, vegerot commented
Notes:
I have signed the CLI, but the [check yourself](https://check-python-cla.herokuapp.com/) link says otherwise.  

I did put an issue # in the title.

2019-12-03 02:01 UTC, aeros commented
@vegerot
>  I have signed the CLI, but the check yourself link says otherwise.

It usually takes around 24-48 hours before the CLI status is updated on GitHub, I'd recommend periodically using the `check yourself` link to manually refresh the status.

If it's been more than 48 hours since you submitted the CLA, you can reach out to the PSF at either:

1) contributors@python.org
2) psf@python.org

2020-06-06 21:12 UTC, remilapeyre requested changes
Hi @vegerot, thanks for fixing this! Can you please:

- change the title of the pull request to "bpo-35019: support IPAddress in asyncio.start_server()"
- Add a test for this change
- Add a [blurb](https://devguide.python.org/committing/#what-s-new-and-news-entries), you can add one by using https://blurb-it.herokuapp.com/
- Add a `.. versionchanged::` note in `Doc/library/asyncio-stream.rst` to document this change
- Add your name to `Misc/ACKS`

?

Thanks!

2020-06-10 01:34 UTC, vegerot commented
@remilapeyre thank you!  It's done.  Let me know how I can make this PR better!

2020-06-10 04:24 UTC, terryjreedy commented
Look at why the tests failed.  test_base_events.py has trailing whitespace somewhere.  Run patchcheck or edit with IDLE and Format => Strip Trailing Whitespace.  Check for blank lines at the end.

2020-06-10 07:06 UTC, remilapeyre requested changes

2020-06-10 07:06 UTC, remilapeyre commented on Misc/ACKS
> +Max Coplan 🤘
```suggestion
Max Coplan
```

I appreciate your enthusiasm but let's keep the name consistent with the rest of the file ;)

2020-06-10 07:06 UTC, remilapeyre commented on Doc/library/asyncio-stream.rst
> +   .. versionadded:: 3.9
```suggestion
   .. versionadded:: 3.10
```

2020-06-10 07:06 UTC, remilapeyre commented on Doc/library/asyncio-stream.rst
> +   .. versionadded:: 3.9
```suggestion
   .. versionadded:: 3.10
```

2020-06-10 07:06 UTC, remilapeyre commented on Misc/NEWS.d/next/Library/2020-06-10-01-33-27.bpo-35019.dwhOOO.rst
> +support IPAddress in asyncio.start_server()
```suggestion
Added support for IPAddress in asyncio.start_server()
```

2020-06-10 18:30 UTC, ericvsmith commented on Lib/asyncio/base_events.py
> +    host = str(host)
I'd like to see a comment here along the lines of: "Even though we're calling str() on host (so we'll convert arbitrary objects to str), we're restricting it to a valid IP address later when calling socket.inet_pton()." I say this because I first looked at this line I thought "uh oh, now we'll accept Paths and file objects and generators and everything else". But since we later call inet_pton, there's nothing to worry about.

2020-06-11 17:27 UTC, vegerot commented
@ericvsmith thanks for reviewing my PR so in depth

2020-06-11 23:03 UTC, aeros commented
@vegerot Please try to avoid force-pushing to the branch after opening the PR, as it messes with the reviews and makes it more difficult to look over the relevant commit history. See the [devguide](https://devguide.python.org/pullrequest/#submitting) for details.

2020-06-11 23:04 UTC, vegerot commented
My bad.  I will look over that now.  I messed up my fast-forward and ended up with thousands of commits in this PR

2020-06-11 23:24 UTC, aeros commented
> My bad. I will look over that now. I messed up my fast-forward and ended up with thousands of commits in this PR

I've certainly done that before (when I first started contributing). My recommendation is to use `git pull upstream master --ff-only` for keeping the local master branch up to date, and using the following for updating branches that have local commits:

```
git checkout some-branch
git fetch upstream
git merge upstream/master
git push origin some-branch
```

See the [git bootcamp section of the devguide](https://devguide.python.org/gitbootcamp/#syncing-with-upstream) for details.

2020-06-11 23:40 UTC, aeros commented
@asvetlov [mentioned](https://bugs.python.org/issue35019#msg327999) taking a more generalized approach in the original bpo issue:

> I mean if we implement something like PathLike [1] but for IP addresses to socket module and teach all socket APIs to accept IPLike objects along with str -- no asyncio change is required.

Do you still have the same thoughts on the issue Andrew, or should we consider a more simplified approach? I would certainly prefer something like an IPLike approach so we don't have to make changes in future and current asyncio APIs that accept IP addresses, but if that's going to be significantly far away, it may be worthwhile to consider the convenience benefits for just the high-level parts of asyncio (such as `asyncio.create_server()`).

2020-06-13 02:52 UTC, vegerot commented
@aeros 
Looking through the dev guide, very helpful.  I agree tackling this in a way that doesn't require changes to asyncio would be great.  But as a one-line change, no reason we couldn't do both.  But I would also be interested in working on another method too 🙂

2021-04-06 20:25 UTC, vegerot commented
Any update on this?

2022-12-08 08:30 UTC, kumaraditya303 commented
Closing as won't fix as discussed on issue.

2022-12-08 08:30 UTC, closed without merging

2022-12-13 06:49 UTC, vegerot commented
> Closing as won't fix as discussed on issue.

Where is the issue?

2022-12-13 06:49 UTC, vegerot commented
> Closing as won't fix as discussed on issue.

@kumaraditya303 Where is the issue?

2022-12-13 07:00 UTC, kumaraditya303 commented
> Where is the issue?


https://github.com/python/cpython/issues/79200