bpo-36470: Allow dataclasses.replace() to work InitVar with default values
python/cpython pull request #17441
Opened 2019-12-02 20:17 UTC by PCManticore

If a dataclass contain an InitVar, that InitVar must be specified in the call to replace(), unless it has a default value, in which case replace() should not raise a `ValueError` if the value was not specified in the call to replace(). 

https://bugs.python.org/issue36470

2019-12-08 12:26 UTC, ericvsmith requested changes

2019-12-08 12:26 UTC, ericvsmith commented on Misc/NEWS.d/next/Library/2019-12-02-21-03-41.bpo-36470.Gy9Sff.rst
> +Allow dataclasses.replace() to work InitVar with default values
Can you make this a single paragraph? Maybe something simpler like "Fix dataclasses with InitVars and replace(). Patch by Claudiu Popa."

2019-12-08 12:26 UTC, ericvsmith commented on Lib/test/test_dataclasses.py
> +    def test_initvar_with_default_value(self):
I find this test extremely confusing. I think most of the tests should be of the form `self.assertEqual(replace(c, y=4), C(1, 2, 3))`. In other words, all of the fields should be tested.

2019-12-08 12:26 UTC, ericvsmith commented on Lib/test/test_dataclasses.py
> +        print('replacing')
Remove the `print()` statement.

2019-12-08 12:38 UTC, PCManticore commented
Hi @ericvsmith 

Thank you for the review! Sorry about that `print`, should have double checked before sending it in.

I have made the requested changes; please review again.

2020-05-21 17:18 UTC, closed without merging

2021-01-29 15:08 UTC, anthrotype commented
I see https://bugs.python.org/issue36470 is still open. Why was this PR closed without a merge?
The issue makes using dataclasses.replace impossible with InitVars that have default values (which I believe is quite common).
Please consider reopening this, thank you

2021-01-29 15:42 UTC, ericvsmith commented
I don't know why it was closed. I'll try and take a look at the bpo.

2021-03-31 13:39 UTC, cadiv commented
any news on this? I just hit this issue myself and wound up here