bpo-9883: writexml on a DocumentFragment acts on children
python/cpython pull request #1745
Opened 2017-05-23 00:30 UTC by arp11

Adds writexml method as well as a test to make sure it works. Since there was no attribute previously, the only behavior change is if a client introspects the available attributes on this node type specifically. There seems to be no other test coverage for writexml whatsoever.

2017-05-23 00:30 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-07-30 08:59 UTC, BoboTiG requested changes
Hello,

Thank you for the patch. I locally checked and it is working fine.
Could you update the PR to include the news file as well?

2018-07-30 08:59 UTC, BoboTiG commented on Lib/test/test_minidom.py
> +        self.assertEquals(written.getvalue(), ' foo: bar: bat:')
Use `self.assertEqual()` (without the trailing `s`).

2018-07-30 09:02 UTC, BoboTiG requested changes

2018-07-30 09:02 UTC, BoboTiG commented on Lib/test/test_minidom.py
> +        dom, orig, c1, c2, c3, frag = self._create_fragment_test_nodes()
You could delete unused vars by using `dom, *_, frag = ...`.

2019-04-03 04:28 UTC, freddrake commented
I'm not sure why this has languished so long, but I don't remember reading the patch when I first saw bpo-9883 (though it was present).

@arp11: Are you willing to update the patch to resolve the conflicts, even though this has aged a bit?

2019-05-30 19:22 UTC, csabella commented
It looks like @arp11 is no longer active therefore I'm going to close this pull request.

2019-05-30 19:23 UTC, closed without merging