bpo-38994: Implement __class_getitem__ for PathLike
python/cpython pull request #17498
Opened 2019-12-07 16:04 UTC by isidentical

2019-12-08 14:13 UTC, asvetlov requested changes
Adding `__class_getitem__` to `os.PathLike` only is not enough for using, e.g. `pathlib.Path[str]` in runtime.

`pathlib.PurePath` should be modified in this way as well.

2019-12-08 18:42 UTC, isidentical commented
@asvetlov I have made the requested changes; please review again

2019-12-08 20:30 UTC, asvetlov approved these changes

2019-12-08 20:31 UTC, merged

2019-12-08 20:31 UTC, asvetlov commented
Awesome, thanks!

2019-12-09 18:53 UTC, brettcannon commented on Misc/NEWS.d/next/Library/2019-12-07-18-58-44.bpo-38994.IJYhz_.rst
> +Implement ``__class_getitem__`` for ``os.PathLike``, ``pathlib.Path``
This news item is slightly misleading as the change was made to `pathlib.PurePath`, not `pathlib.Path`.

2019-12-09 18:53 UTC, brettcannon commented on Misc/NEWS.d/next/Library/2019-12-07-18-58-44.bpo-38994.IJYhz_.rst
> +Implement ``__class_getitem__`` for ``os.PathLike``, ``pathlib.Path``
And @isidentical forgot to give himself credit for the change. :)

2019-12-09 18:54 UTC, brettcannon commented
Any reason not to document this?

2019-12-09 19:30 UTC, isidentical commented
It is kind of irrelevant I wrote a simple script to analyze typeshed and I think i found other classes with missing class getitems. Should I open an issue per class or just open one and fix all of them in one PR (I can tweak the comment change @brettcannon said in that PR). It is like 6-7 lines per class so i dont think it would make review harder.

2019-12-10 01:14 UTC, brettcannon commented
@isidentical individual is always easier to review, but if it's too much work you can try doing it in a single PR.

2019-12-10 11:15 UTC, asvetlov commented
@isidentical would you make a follow-up PR for fixing @brettcannon notes?

2019-12-10 12:16 UTC, isidentical commented
Yes

On Tue, Dec 10, 2019, 2:15 PM Andrew Svetlov <notifications@github.com>
wrote:

> @isidentical <https://github.com/isidentical> would you make a follow-up
> PR for fixing @brettcannon <https://github.com/brettcannon> notes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/cpython/pull/17498?email_source=notifications&email_token=ALJKHQN2UMJNZNTHPSU4J2DQX525FA5CNFSM4JXO3CS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGO4CAI#issuecomment-563986689>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALJKHQJAUGZFTMH57Q6EPHDQX525FANCNFSM4JXO3CSQ>
> .
>