bpo-38091: Import deadlock detection causes deadlock
python/cpython pull request #17518
Opened 2019-12-09 10:27 UTC by arigo

2019-12-21 20:01 UTC, pitrou commented
The fix here is more of a hack. A proper fix could be something like the below. At least it fixes the reproducer posted by @rlamy . Is there a real-world reproducer you can test it on?

```diff
diff --git a/Lib/importlib/_bootstrap.py b/Lib/importlib/_bootstrap.py
index 8de0e9ee79..7b2bfefdec 100644
--- a/Lib/importlib/_bootstrap.py
+++ b/Lib/importlib/_bootstrap.py
@@ -71,9 +71,20 @@ class _ModuleLock:
             lock = _blocking_on.get(tid)
             if lock is None:
                 return False
-            tid = lock.owner
-            if tid == me:
+            owner_tid = lock.owner
+            if owner_tid == tid:
+                # Lock owner is temporarily blocking on a lock it
+                # already owns.  This means it's not actually blocking.
+                # (this can happen at the beginning of acquire() below
+                #  -- see bpo 38091)
+                return False
+            if owner_tid == me:
+                # Lock owner is blocking on a lock we own, but we're blocking
+                # on the lock it owns => deadlock.
                 return True
+            # Move along the chain and find out whether the owner is blocking
+            # on another lock.
+            tid = owner_tid
 
     def acquire(self):
         """
```

2019-12-22 17:29 UTC, arigo commented
Maybe a safer way to think about it would be to ask ourselves when has_deadlock() is really supposed to return True.  I think it means to return True if the chain ``_blocking_on[_blocking_on[...[tid]...]]`` eventually reaches the value ``me``, and False in all other cases.  You are fixing one such case by detecting when the chain enters a fixpoint, i.e. a loop of length 1.  I'm not convinced that longer loops are impossible; maybe we should also detect them and return False in these cases.  Something like that (untested code):

```
     def has_deadlock(self):
         # Deadlock avoidance for concurrent circular imports.
         me = _thread.get_ident()
         tid = self.owner
+        seen = set()
         while True:
             lock = _blocking_on.get(tid)
             if lock is None:
                 return False
             tid = lock.owner
             if tid == me:
                 return True
+            if tid in seen:
+                # bpo 38091: the chain of tid's we encounter here
+                # eventually leads to a fixpoint or a cycle, but
+                # does not reach 'me'.  This means we would not
+                # actually deadlock.  This can happen if other
+                # threads are at the beginning of acquire() below.
+                return False    
+            seen.add(tid)
```

2019-12-22 17:38 UTC, pitrou commented
@arigo Yes, that fix would probably work. Perhaps @rlamy can check :-)

2019-12-23 18:43 UTC, rlamy commented
I think that this should fix the issue. It caused some intermittent test failures in PyPy, so I guess we should just merge the change there and monitor the CI results.

2020-01-01 21:46 UTC, pitrou commented
@rlamy Did you test this fix on PyPy?

2020-01-22 23:46 UTC, brettcannon requested changes
Marking as rejected until we here back from PyPy that the proposed fix in the PR discussion worked for them.

2020-01-23 09:39 UTC, arigo commented
I have made the requested changes; please review again

2020-01-23 09:40 UTC, arigo commented
I have updated the PR to include the test from https://bugs.python.org/issue38091 , which fails (deadlocks) without the fix and passes with the fix.

2020-02-08 00:07 UTC, brettcannon approved these changes

2020-02-08 00:09 UTC, brettcannon requested changes
`importlib.h` wasn't regenerated and included in this PR. I believe that can be done with `make regen-all` (or something like that).

2020-02-08 00:10 UTC, brettcannon commented
The change looks good, but `importlib.h` updates accidentally got left out. There is also no news entry (you can use https://blurb-it.herokuapp.com/ to do that).

2020-02-08 00:10 UTC, brettcannon commented
BTW I'm assuming the test failures are due to `importlib.h` not getting updated in the PR.

2020-02-14 23:21 UTC, arigo commented
I have made the requested changes; please review again

2020-03-03 01:16 UTC, brettcannon commented on Lib/test/test_import/__init__.py
> +        # has_deadlock(); the logic was itself sometimes deadlocking
```suggestion
        # has_deadlock(); the logic was itself sometimes deadlocking.
```

2020-03-03 01:17 UTC, brettcannon approved these changes

2020-03-03 01:19 UTC, brettcannon commented on Misc/NEWS.d/next/Core and Builtins/2020-02-14-23-10-07.bpo-38091.pwR0K7.rst
> +The import logic has got code to detect deadlock. This code was faulty. It occasionally caused deadlocks to occur.
```suggestion
Tweak import deadlock detection code to not deadlock itself.
```

2020-03-03 01:31 UTC, miss-islington commented
@arigo: Status check is done, and it's a failure ❌ .

2020-03-03 01:37 UTC, miss-islington commented
@arigo: Status check is done, and it's a success ✅ .

2020-03-03 01:37 UTC, merged

2020-03-03 01:37 UTC, miss-islington commented
Thanks @arigo for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2020-03-03 01:37 UTC, miss-islington commented
Sorry, @arigo, I could not cleanly backport this to `3.8` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 6daa37fd42c5d5300172728e8b4de74fe0b319fc 3.8
                                ```

2020-03-03 01:37 UTC, miss-islington commented
Sorry @arigo, I had trouble checking out the `3.7` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 6daa37fd42c5d5300172728e8b4de74fe0b319fc 3.7
                                ```

2020-03-03 18:23 UTC, brettcannon commented
@arigo any interest in manually backporting this to 3.8 and 3.7? (Chances are it's `importlib.h`.)

2020-03-05 18:10 UTC, arigo commented
My git-fu is very limited (in general and on github).  Do you expect two other pull requests for the 3.7 and 3.8 branches?

2020-03-05 20:55 UTC, brettcannon commented
@arigo yep, but don't worry about it too much. I can try to get around to it eventually myself.