bpo-39031: Include elif keyword when producing lineno/col-offset info for if_stmt
python/cpython pull request #17582
Opened 2019-12-12 20:21 UTC by lysnikolaou

2019-12-12 20:59 UTC, pablogsal commented
Hi there 😉 Can you add a NEWS entry?

2019-12-12 21:03 UTC, pablogsal requested changes
Can you also add a `elif` case to the `exec_test` list and regenerate the test data (check the end of the file for instructions)?

2019-12-12 21:07 UTC, pablogsal commented on Misc/NEWS.d/next/Core and Builtins/2019-12-12-21-05-43.bpo-39031.imlCYZ.rst
> +When parsing an elif node, lineno and col_offset of the node now point to the elif keyword and not to its condition.
```suggestion
When parsing an elif node, lineno and col_offset of the node now point to the elif keyword and not to its condition, making it consistent with the `if` node.
```

2019-12-12 21:20 UTC, lysnikolaou commented
Thanks a lot for the review @pablogsal! I have made the requested changes; please review again.

2019-12-12 21:23 UTC, pablogsal approved these changes
Thanks for the patch @lysnikolaou! I will backport this to `3.8` and `3.7` once the CI finish.

2019-12-12 21:38 UTC, miss-islington commented
@lysnikolaou: Status check is done, and it's a failure ❌ .

2019-12-12 21:40 UTC, miss-islington commented
@lysnikolaou: Status check is done, and it's a success ✅ .

2019-12-12 21:40 UTC, merged

2019-12-12 21:40 UTC, miss-islington commented
Thanks @lysnikolaou for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2019-12-12 21:40 UTC, miss-islington commented
Sorry, @lysnikolaou, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 025a602af7ee284d8db6955c26016f3f27d35536 3.7
                                ```

2019-12-13 00:56 UTC, miss-islington commented
Thanks @lysnikolaou for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-12-13 00:56 UTC, miss-islington commented
I'm having trouble backporting to `3.8`. Reason: '`Error 110 while writing to socket. Connection timed out.`'. Please retry by removing and re-adding the `needs backport to 3.8` label.

2019-12-13 01:59 UTC, miss-islington commented
Thanks @lysnikolaou for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-12-13 01:59 UTC, miss-islington commented
Sorry @lysnikolaou, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 025a602af7ee284d8db6955c26016f3f27d35536 3.8
                                ```

2019-12-13 14:03 UTC, miss-islington commented
Thanks @lysnikolaou for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2019-12-13 17:15 UTC, lysnikolaou commented
@pablogsal I just found out that I kind of messed this up and one more change is needed. What is the right course of action here? Open a new PR for the additional change?

2019-12-13 17:28 UTC, pablogsal commented
> Open a new PR for the additional change?

Yes, also explain in the issue what is missing

2020-01-08 19:40 UTC, asottile commented
@pablogsal In the past these usually don't get backported to already-released versions as they break static analysis tools (I just hit an error due to this patch when upgrading from 3.8.0 to 3.8.1!)

2020-01-08 20:30 UTC, pablogsal commented
> @pablogsal In the past these usually don't get backported to already-released versions as they break static analysis tools (I just hit an error due to this patch when upgrading from 3.8.0 to 3.8.1+!)

@asottile Apologies for the inconvenience :S. In this case I backported it because I considered this a bugfix but I can see how this can be inconvenient for static analysers. 

Although static analysers would break anyway with a new major release I will make sure to take this into account for further similar situations so we don't cause breakage for minor releases.

2020-01-08 20:45 UTC, asottile commented
> > @pablogsal In the past these usually don't get backported to already-released versions as they break static analysis tools (I just hit an error due to this patch when upgrading from 3.8.0 to 3.8.1+!)
> 
> @asottile Apologies for the inconvenience :S. In this case I backported it because I considered this a bugfix but I can see how this can be inconvenient for static analysers.
> 
> Although static analysers would break anyway with a new major release I will make sure to take this into account for further similar situations so we don't cause breakage for minor releases.

yep makes sense, in major versions breakage is ~kinda expected -- but having conditions for `< (3, 8, 1)` is pretty unfortunate

oh actually it appears this isn't released in 3.8.1 so it would be part of 3.8.2?  should we revert instead?

2020-01-08 20:51 UTC, pablogsal commented
>oh actually it appears this isn't released in 3.8.1 so it would be part of 3.8.2? should we revert instead?

Unless I am mistaken, the fixes for issue39031 are in 3.8.1 because we are relying on that for developing pegen.

2020-01-08 20:52 UTC, asottile commented
> > oh actually it appears this isn't released in 3.8.1 so it would be part of 3.8.2? should we revert instead?
> 
> Unless I am mistaken, the fixes for issue39031 are in 3.8.1 because we are relying on that for developing pegen.

ah yep they are -- false alarm.  I'm bad at reading `git log` :laughing:

2020-01-08 20:53 UTC, pablogsal commented
Notice that this fixes are also on the latest 3.7.x :(

2020-01-08 20:53 UTC, asottile commented
ugh that's even messier :(

2020-01-08 20:59 UTC, pablogsal commented
@asottile But notice this is not unique of this issue, for example https://bugs.python.org/issue38535 also changes ast colum offsets and line numbers and was backported (for example, is in 3.7.6).

2020-01-08 21:04 UTC, asottile commented
[bpo-16806](https://bugs.python.org/issue16806) was not for instance -- and there was a change to the tokenizer in a patch version which pretty badly broke pyflakes + pycodestyle but I'm having a difficult time finding it (it involved `ENDMARKER` and files not ending in newlines)

ideally we'd document this somewhere and be more consistent :man_shrugging: