bpo-28886: Move deprecated abc module decorators to separate section …
python/cpython pull request #176
Opened 2017-02-19 15:04 UTC by harshul1610

…in docs
[bpo-28886]
this PR solves the above issue.

As per the message logs, it is good to add the deprecated decorators to the separate section in
https://docs.python.org/3.7/library/abc.html

2017-02-19 15:04 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-19 15:19 UTC, DimitrisJim requested changes

2017-02-19 15:19 UTC, DimitrisJim commented on Doc/library/abc.rst
> +
Please fix the small typo: "support" -> "supports the"

2017-02-19 15:21 UTC, DimitrisJim commented
In addition to the typo, it might be a good idea to describe how their non-abstract counterparts can now simply be applied with `@abstractmethod`, instead of adding a sentence to each class about how this is the case.

2017-02-20 04:58 UTC, harshul1610 commented
I see. Let me fix this.

2017-02-20 08:56 UTC, harshul1610 commented
@DimitrisJim if we see https://docs.python.org/3.7/library/abc.html

it currently describes how the non-abstract counterparts can be applied with `@abstractmethod` . Do we actually need the separate section? We just need to organize it a little bit. May be, adding the Deprecation line as quoted

> Deprecated since version 3.3: It is now possible to use classmethod with abstractmethod(), making this decorator redundant.

just after the decorator heading can make it more understandable rather than making a separate section. We can add few more lines about how the non-abstract counterparts are working.

correct me, if I am wrong anywhere?

2017-03-27 07:46 UTC, methane approved these changes

2017-03-27 07:50 UTC, methane submitted a review, later dismissed
In [bpo-28886](http://bugs.python.org/issue28886),  @ncoghlan said:

> Then that section can *start* with the information on simply applying the builtin decorators on top of the abc.abstractproperty() decorator, before moving on to document the available subclasses.

How about adding one example on the top of the section, and remove three "This special case is deprecated,..."?

2018-02-21 01:51 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2018-02-21 04:30 UTC, merged

2018-02-21 04:30 UTC, miss-islington commented
Thanks @harshul1610 for the PR, and @methane for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖