bpo-38870: Remove dead code related with argument unparsing
python/cpython pull request #17613
Opened 2019-12-15 12:25 UTC by isidentical

It looks like there are no ways this code to fall down `first = False` block. Because of this statement;
https://github.com/python/cpython/blob/94d2c8df1a7657015a2fcdb4c4d43392f91f8348/Lib/ast.py#L1187-L1189

2019-12-15 22:22 UTC, pablogsal requested changes

2019-12-15 22:22 UTC, pablogsal commented on Misc/NEWS.d/next/Library/2019-12-15-15-22-04.bpo-38870.YHJpq5.rst
> +Remove dead code from ``ast._Unparser`` related with argument unparsing.
Please, remove the NEWS entry. There is no user-facing change here :)

2019-12-16 05:04 UTC, isidentical commented
I have made the requested changes; please review again

2019-12-16 05:14 UTC, isidentical commented
I have made the requested changes; please review again

2019-12-16 12:23 UTC, pablogsal commented
I don't understand what you mean, that branch can certainly be hyrft:

```
ast.unparse(ast.parse("def f(*x): pass"))
```

2019-12-16 12:25 UTC, pablogsal commented
Disregard my latest message,  I was looking at the wrong branch! :joy:

2019-12-16 12:26 UTC, merged

2019-12-16 12:27 UTC, pablogsal commented
Thanks for the PR! :tada: