PyDEBUG builds don't support the limited ABI
python/cpython pull request #1766
Opened 2017-05-23 18:12 UTC by stefanor

[Issue 28401](https://bugs.python.org/issue28401): Don't attempt to import the stable API extensions, they are not supported in PyDEBUG builds (which don't implement that ABI).

2017-05-23 18:12 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-05-23 18:15 UTC, stefanor commented
> this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings

That was it.

2017-05-25 21:56 UTC, brettcannon approved these changes

2018-07-13 20:58 UTC, brettcannon commented
@stefanor sorry, this simply fell through the cracks. Could you add a NEWS entry file?

2018-07-20 23:24 UTC, brettcannon requested changes
Please add a news entry.

2018-11-03 17:44 UTC, stefanor commented
Rebased (so that blurb was supported) and added a NEWS entry.

2018-11-16 23:37 UTC, brettcannon approved these changes

2018-11-16 23:52 UTC, miss-islington commented
@stefanor: Status check is done, and it's a success ✅ .

2018-11-16 23:52 UTC, merged