issue31711: On SSLObject.write method, added assert that data has content.
python/cpython pull request #17671
Opened 2019-12-20 11:34 UTC by choyos

This avoid to rise ssl.SSLEOFError on petition that has no content on response.

2019-12-20 11:34 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@choyos

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-12-22 12:06 UTC, raulcd commented
Hi,
Thanks for your contribution. Why would you want to obscure this returning an emtpy string. To me raising an Exception sounds like the approach we should maintain. Can you elaborate more on the case of why this behaviour has to change?
Thanks
Raúl

2019-12-23 18:03 UTC, tiran requested changes

2019-12-23 18:03 UTC, tiran commented on Lib/ssl.py
> +        if data != b'':
``if data:``

2019-12-23 18:03 UTC, tiran commented on Lib/ssl.py
> +            return ""
``write`` returns the number of bytes sent. The function should either return ``0`` or fail with a more useful exception.

2019-12-23 18:27 UTC, joernheissler commented
> To me raising an Exception sounds like the approach we should maintain. Can you elaborate more on the case of why this behaviour has to change?

See https://bugs.python.org/issue31711 for some discussion. Currently, the behaviour is undefined, i.e. instead of an exception something else may happen. Some code change is required to achieve defined behaviour, whichever that is.

I prefer a noop.

2019-12-24 00:33 UTC, slingamn commented
Previous PR implementing no-op behavior: https://github.com/python/cpython/pull/7559

2020-01-09 10:18 UTC, choyos commented
Sorry about the delay. I have made the requested changes as suggested by @tiran.
Also, I have looked #7559 indicated by @slingamn. Both solutions seem fine for me, but I think this change is less critical if the C function is used on other points, avoiding regressions. 
If there was another solution to this problem, it would also be fine for me, but it needs to be solved.

2020-01-25 19:48 UTC, csabella commented
@choyos, the bot could not find a signed CLA for you.  Please take a look at the instructions above for setting that up.

2021-04-19 03:59 UTC, tiran commented
Thanks to PEP 644 the issue will be fixed in 3.10 by using SSL_read_ex and SSL_write_ex() functions. I couldn't use the functions earlier because Python had to support older OpenSSL versions and LibreSSL. https://github.com/python/cpython/pull/25468

2021-04-19 03:59 UTC, closed without merging