Fix potential deadlock in logging
python/cpython pull request #17689
Opened 2019-12-24 01:12 UTC by DerekTBrown

2019-12-24 01:12 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@DerekTBrown

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2019-12-26 01:13 UTC, DerekTBrown commented
I just signed CLA.

2019-12-31 12:36 UTC, csabella commented
Hi @DerekTBrown, thank you for your contribution and for helping to improve CPython.  Please open an issue on bugs.python.org and update the title of the PR with the ticket number.  Trivial changes are for things like one word spelling changes and anything more than that should have a bug ticket.  Thank you!

2020-01-02 20:25 UTC, DerekTBrown commented
Thanks @csabella! I filed a BPO and created a news entry as well.

2020-01-02 22:24 UTC, bharel commented
Why not just nest a finally? Might be a tiny bit more nested but it'll be faster and more readable I believe

2020-01-05 12:25 UTC, gareth-rees commented on Lib/logging/__init__.py
> +    def _isEnabledForNoCache(self, level):
Method needs a docstring.

2020-01-05 12:25 UTC, gareth-rees commented on Lib/logging/__init__.py
> +            self._cache[level] = self._isEnabledForNoCache(level)
The old version of the code locked the call to `self.getEffectiveLevel` against the update of the cache. The new version does not. This introduces a race condition:

1. Thread A consults the cache and gets a `KeyError`
2. Thread B also consults the cache and gets a `KeyError`
3. Thread A acquires the lock, reads the effective level, which is 1, and releases the lock
4. Thread C changes the effective level to 2
5. Thread B acquires the lock, reads the effective level, which is 2, and releases the lock
6. Thread B updates the cache to 2
7. Thread A updates the cache to 1

So now the effective level is 2 but the cached value is 1. This couldn't happen previously.

(Maybe this is harmless, I am not an expert on multi-threaded logging.)

2020-01-06 19:47 UTC, vsajip requested changes
I would also prefer to not add the extra method but handle with a nested `try`, while ensuring that Gareth Rees' comment is also addressed.

2020-01-06 22:58 UTC, DerekTBrown commented
I have made the requested changes; please review again. Given comments, I made a simpler change and just wrapped setting the level in a `try...finally` block.

2020-01-07 16:38 UTC, vsajip approved these changes

2020-01-07 16:40 UTC, merged

2020-01-07 16:41 UTC, miss-islington commented
Thanks @DerekTBrown for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-01-07 16:41 UTC, miss-islington commented
Thanks @DerekTBrown for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖