bpo28754: AC on bisect.
python/cpython pull request #177
Opened 2017-02-19 16:19 UTC by JulienPalard

2017-02-20 06:34 UTC, methane reviewed
LGTM.
But please wait approval from expert.
(@rhettinger is listed on http://cpython-devguide.readthedocs.io/experts.html)

2017-02-23 13:10 UTC, serhiy-storchaka requested changes

2017-02-23 13:10 UTC, serhiy-storchaka commented on Modules/_bisectmodule.c
> +ssize_t_converter(PyObject *obj, void *ptr)
ssize_t_converter is not used for parsing arguments. It is used only in optional_ssize_t_converter. Wouldn't be better to inline it?

2017-02-23 13:10 UTC, serhiy-storchaka commented on Modules/_bisectmodule.c
> +    lo: Py_ssize_t(c_default='0') = 0
`c_default='0'` is redundant.

2017-02-23 13:10 UTC, serhiy-storchaka commented on Modules/_bisectmodule.c
> +bisect.bisect_right
You can use the return converter for simplifying the code.
```
bisect.bisect_right -> Py_ssize_t
```

The body of `bisect_bisect_right_impl()` would be just:
```
return internal_bisect_right(a, x, lo, hi);
```

2017-02-23 13:10 UTC, serhiy-storchaka commented on Lib/test/test_bisect.py
> +            self.assertEqual(func(data, elem, 0, -1),
This doesn't check that passing `-1` and `None` is the same as not specifying the hi argument. Compare results with `func(data, elem)`.

2017-04-05 05:42 UTC, rhettinger commented
I don't want the pure python API to change at all.  It is a long standing API and there is nothing wrong with it.  Also, passing it -1 here as a special value makes real code less readable.  Further, the change slightly slows down the case where high is specified.  In a high performance building block module, we shouldn't add in unnecessary checks.

2018-02-21 01:51 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2018-03-24 18:10 UTC, closed without merging