bpo-15795: Preserve permissions on UNIX (based/like) systems
python/cpython pull request #17790
Opened 2020-01-01 23:41 UTC by sharkwouter

The reasoning behind this is that the unzip command (Info-ZIP) on pretty much every unix system will preserve the permissions by default.
The Info-ZIP unzip command is shipped with all currently supported versions of:
- MacOS
- OpenBSD and NetBSD
- Probably every manjor Linux distribution
Here is a list: https://pkgs.org/download/unzip

In this pull request the permissions are only preserved if a zip file is extracted on a posix system and the zipfile was made on a UNIX system. Permissions are also set for directories.

2020-01-01 23:41 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@sharkwouter

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-03-03 14:13 UTC, sharkwouter commented
I've added a news message, now all tests pass. Please let me know if this change will be considered and if any changes are needed.

2020-07-22 13:16 UTC, sharkwouter commented
Does it usually take over half a year for a PR to be reviewed? Did I not follow the standard procedure for PRs?

2020-10-16 12:37 UTC, Makishima commented
Is there any chance that the pull request will be accepted? I'm a bit tired of using workaround every time I need unzip something on linux.

2020-10-16 12:41 UTC, sharkwouter commented
@Makishima I would suggest you use the unzip command with subprocess instead. There are more issues with the zipfile library than just the permissions. It also breaks symlinks for instance.

2021-04-14 17:50 UTC, woodruffw commented
Not a reviewer, but I took a quick look at this patch and it looks correct to me (checks the provenance of the member and only applies the permission if applicable). There's still the problem of this all being woefully underspecified, but it's consistent with what ZIP libraries in the wild do (namely Info-ZIP and libzip). 

Any chance for another review on this?

2021-10-23 14:32 UTC, nanjekyejoannah requested changes
I share and will reecho Eric's sentiments, can you please add some unit tests that exercise your changes?

2022-04-22 01:40 UTC, clopez commented
Related: https://github.com/python/cpython/pull/15401

2022-04-22 12:37 UTC, closed without merging