bpo-39223: Support slices in constant folding
python/cpython pull request #17838
Opened 2020-01-05 15:57 UTC by isidentical

2020-01-05 17:29 UTC, pablogsal requested changes

2020-01-05 17:29 UTC, pablogsal commented on Python/ast_opt.c
> +        key = PySlice_New(GET_CONSTANT(slice->v.Slice.lower),
You are leaking this value if we go this code path

2020-01-05 17:51 UTC, isidentical commented
I have made the requested changes; please review again

2020-01-06 04:29 UTC, isidentical commented
Closing as Issue rejected.

2020-01-06 04:29 UTC, closed without merging