bpo-39267: Fix dict's __missing__ documentation
python/cpython pull request #17911
Opened 2020-01-09 00:12 UTC by bharel

According to the mailing list discussion, fixed dict's documentation to account for get() not calling __missing__ and moved __missing__ from the data model to dict as it's a dict-only method and not part of the Mapping ABC.

2020-02-21 10:43 UTC, bharel commented
bump

2020-05-24 11:31 UTC, terryjreedy requested changes
My first thought is that the entry should stay where it is, though something may need to be added somewhere.  Special method should not have to be part of an ABC to be documented in the special methods doc.  This section long predated ABCs.  I will have to look at the linked discussion when I have more time.  So I don't know what change, if any, to suggest at the moment.

2020-05-24 14:03 UTC, bharel commented
> Special method should not have to be part of an ABC to be documented in the special methods doc.

Thing is, I'm not implying any opinion on whether it should be there or not.
What I I'm saying, is that it should be consistent.

At the moment, you have `__reduce__` in pickle's docs, `__subclasshook__` in abc's docs, and other dunders at their appropriate or relevant places. You don't have all dunders in the same location, apart from those relevant to all objects and classes.

Continuing with that logic, `__missing__` should probably be in dict's docs, as that's the only location where it's relevant. Otherwise the documentation is inconsistent.

Furthermore - it's specifically `dict.__missing__`, not `object.__missing__`. The docs are misleading in the current state. (Discussion @ mailing list) 

As a side note, the PR changes `dict.get` documentation as well.

2022-12-10 03:03 UTC, slateny commented
Per Guido on the mailing list, maybe @rhettinger can suggest something (seeing that you reviewed/merged https://github.com/python/cpython/pull/17910 as well).

2024-03-01 17:56 UTC, merwok commented on Doc/library/stdtypes.rst
> +      Not implemented by default. Called by :class:`dict`\ .\ :meth:`__getitem__`
```suggestion
      Not implemented by default. Called by :meth:`dict.__getitem__`
```

2024-03-01 17:57 UTC, merwok commented
I agree about not moving the entry.
Other magic methods are also documented as `object.__iter__` and so on.  In this context it means «some object», not «the object type». Improving that would be a separate issue.

2026-05-05 17:35 UTC, StanFromIreland commented
Closing as stale, the requested changes have not been applied in six years.

2026-05-05 17:35 UTC, closed without merging