nntplib.NNTP/NNTP_SSL refactoring
python/cpython pull request #17939
Opened 2020-01-10 16:44 UTC by corona10

2020-01-10 16:48 UTC, vstinner commented
> This PR is only refactoring work, so I skip the news and issue.

I prefer to always attach a bpo to get more context. This change is connected to: https://bugs.python.org/issue39259

2020-01-10 16:56 UTC, vstinner requested changes
Hum, you changed how _NNTPBase. With this change, I'm not sure that it's still relevant to have _NNTPBase *and* NNTP. What do you think of merging _NNTPBase and NNTP into NNTP? The most tricky part is to merge the two `__init__()` methods. Maybe just move NNTP code at the end of _NNTPBase.__init__().

2020-01-10 16:56 UTC, vstinner commented on Lib/nntplib.py
> +            raise ValueError('Non-blocking socket (timeout=0) is not supported')
This is unrelated, please revert it.

2020-01-10 16:57 UTC, corona10 commented on Lib/nntplib.py
> +            raise ValueError('Non-blocking socket (timeout=0) is not supported')
Oops Thanks for letting me know

2020-01-10 17:03 UTC, corona10 commented
@vstinner  Yes, that's reasonable. I will update this PR with merging 2 classes.

2020-01-10 17:24 UTC, corona10 commented
@vstinner 
https://github.com/python/cpython/blob/2e6a8efa837410327b593dc83c57492253b1201e/Lib/test/test_nntplib.py#L424

Hmm... _NNTPBase is also used for testing server code.
IMHO, if we merge _NNTPBase and NNTP, the work looks pretty large.
How about creating a separate issue for this (e.g remove _NNTPBase)?

2020-01-10 23:06 UTC, vstinner commented on Lib/nntplib.py
> +            self.sock = super()._create_socket(timeout)
In NNTP, the method only creates a socket, it doesn't assign self.sock. Please replace `self.sock` with `sock`.

2020-01-10 23:06 UTC, vstinner commented
> Hmm... _NNTPBase is also used for testing server code.
> IMHO, if we merge _NNTPBase and NNTP, the work looks pretty large.
> How about creating a separate issue for this (e.g remove _NNTPBase)?

Ok.

2020-01-11 04:20 UTC, corona10 commented
@vstinner  Updated!

> Ok.

I will create a new issue for this :)

2020-01-11 15:07 UTC, merged

2020-01-11 16:13 UTC, corona10 commented
https://bugs.python.org/issue39305 is created :)