bpo-39259: nntplib.NNTP/NNTP_SSL now reject timeout = 0
python/cpython pull request #17936
Opened 2020-01-10 14:28 UTC by corona10

2020-01-10 14:48 UTC, vstinner requested changes
This refactoring is interesting. I merged your other change to reject timeout=0, you should now rebase this PR.

Currently, this PR is a refactoring **and** rejects timeout=0. I prefer to have one commit per change.

2020-01-10 14:48 UTC, vstinner commented on Lib/nntplib.py
> +        return socket.create_connection((self.host, self.port), timeout)
You should move `sys.audit("nntplib.connect", self, host, port)` here :-)

2020-01-10 14:48 UTC, vstinner commented on Lib/nntplib.py
> +            self.sock = NNTP._create_socket(self, timeout)
```suggestion
            self.sock = super()._create_socket(timeout)
```

2020-01-10 14:48 UTC, vstinner commented on Lib/nntplib.py
> +            NNTP.__init__(self, host, port, user, password, readermode,
```suggestion
            super().__init__(host, port, user, password, readermode,
```

2020-01-10 14:48 UTC, vstinner commented on Lib/nntplib.py
> +            self.sock = _encrypt_on(self.sock, self.ssl_context, self.host)
`try: ... except: self.sock.close() raise` is needed here.

2020-01-10 15:52 UTC, corona10 reviewed
I have made the requested changes; please review again

Thanks for the review 👍 
- I 've separated commits :)
- Also, applied feedback from code reviews, Thank you very much!

2020-01-10 16:28 UTC, vstinner commented
You should now rebase your PR on master, since I merged your other PR.

2020-01-10 16:30 UTC, corona10 commented
@vstinner 
Hmm.. I already rebase this PR.

```git

commit 38bdc38ff90fb058ae80a78ca0ecf0096f4e616c (HEAD -> bpo-39259-nntplib, corona10/bpo-39259-nntplib)
Author: Dong-hee Na <donghee.na92@gmail.com>
Date:   Sat Jan 11 00:37:14 2020 +0900

    bpo-39259: Update

commit 0aa665bb0980f81d13480c45ac534235c4d5315a
Author: Dong-hee Na <donghee.na92@gmail.com>
Date:   Sat Jan 11 00:33:02 2020 +0900

    bbpo-39259: nntplib.NNTP/NNTP_SSL now reject timeout = 0

commit 02b3045015efb1bbb9dbb314fc2217378d4c6b32
Author: Dong-hee Na <donghee.na92@gmail.com>
Date:   Fri Jan 10 23:27:45 2020 +0900

    bpo-39259: nntplib.NNTP/NNTP_SSL refactoring

commit c39b52f1527868c7ada9385669c38edf98858921 (origin/master)
Author: Dong-hee Na <donghee.na92@gmail.com>
Date:   Fri Jan 10 23:34:05 2020 +0900

    bpo-39259: poplib now rejects timeout = 0 (GH-17912)
```

2020-01-10 16:39 UTC, vstinner requested changes
Ooooh, now I get it :-) I merged a PR to modify poplib, but this is a PR for nntplib :-D

Please split your PR to extract the _create_socket() refactoring. I would like to first have a PR for the refactoring, and *then* have a PR to reject timeout=0. Having a single PR for two changes makes review harder. In Python, we always squash multiple commits into a single commit on merge.

2020-01-10 16:47 UTC, corona10 commented
@vstinner 
Thanks for the guide.
I 've opened a new PR https://github.com/python/cpython/pull/17939 for the refactoring work.

2020-01-10 16:50 UTC, corona10 commented
So this PR should be reviewed after #17939 is merged.

2020-01-11 15:08 UTC, vstinner commented
I merged your PR #17939. You can now rebase this one on top of it (master branch).

2020-01-11 16:12 UTC, corona10 commented
> I merged your PR #17939. You can now rebase this one on top of it (master branch).

Thanks! I 've rebased the PR :)

2020-01-11 17:39 UTC, merged

2020-01-11 17:39 UTC, vstinner commented
Thanks to the refactoring, it was way easier to review this PR. It's now merged, thanks!