bpo-39273: Expose BUTTON5_* constants in the curses module if available
python/cpython pull request #17996
Opened 2020-01-14 06:45 UTC by ZackerySpytz

2020-10-13 17:20 UTC, lisroach approved these changes
LGTM

2020-10-14 09:11 UTC, serhiy-storchaka requested changes

2020-10-14 09:11 UTC, serhiy-storchaka commented on Modules/_cursesmodule.c
> +#if NCURSES_MOUSE_VERSION > 1
`NCURSES_MOUSE_VERSION` is a ncurses specific constant. It is not defined on other implementations. Add a check that it is defined.

2020-10-14 16:43 UTC, serhiy-storchaka approved these changes

2020-10-14 16:45 UTC, serhiy-storchaka reviewed
Please update the documentation.

2021-01-06 09:49 UTC, serhiy-storchaka requested changes
Please update `Doc/library/curses.rst` and `Doc/whatsnew/3.10.rst`.

2021-01-14 03:55 UTC, ZackerySpytz commented
I have made the requested changes; please review again.

2021-01-14 09:39 UTC, serhiy-storchaka approved these changes
:+1:

2021-01-14 09:40 UTC, merged