bpo-18819: tarfile: only set device fields for device files
python/cpython pull request #18080
Opened 2020-01-20 18:08 UTC by wchargin

The GNU docs describe the `devmajor` and `devminor` fields of the tar
header struct only in the context of character and block special files,
suggesting that in other cases they are not populated. Typical utilities
behave accordingly; this patch teaches `tarfile` to do the same.

Test Plan:
No tests added because none appear to exist for this module. Manually
verified that this enables output that is bit-for-bit compatible with
GNU tar. In particular, this program now passes on my Ubuntu 16.04,
whereas it failed before this patch:

```python
import os
import subprocess
import tarfile
import tempfile

filename = "important_data"
contents = b"The quick brown fox jumps over the lazy dog"

with tempfile.TemporaryDirectory() as tmpdir:
    os.chdir(tmpdir)
    with open(filename, "wb") as outfile:
        outfile.write(contents)
    with tarfile.open("py.tar", "x", format=tarfile.GNU_FORMAT) as outfile:
        outfile.add(filename)
    subprocess.check_call(["tar", "cf", "gnu.tar", filename])
    subprocess.check_call(["shasum", "-a", "256", "py.tar", "gnu.tar"])
    subprocess.check_call(["cmp", "-b", "py.tar", "gnu.tar"])
```

(The exact hashes depend on the calling user and current time but should
always be the same across both output archives.)

wchargin-branch: tarfile-limit-device-headers

2020-01-22 02:12 UTC, ethanfurman commented
The code looks good.  Question, though:  why use both `cmp` and `shasum`?  If `cmp` passes aren't the files identical?

Also, the tests for `tarfile` are in `Lib/test/test_tarfile.py`.  A quick perusal suggests that `MemberReadTest` might be a good place for your test above (appropriately modified, of course).  Feel free to suggest a different class in that file, though.

2020-01-22 02:18 UTC, ethanfurman requested changes
This looks good.  Add your test and we should be ready to commit.

2020-01-22 02:22 UTC, wchargin reviewed
> Question, though: why use both `cmp` and `shasum`? If `cmp` passes aren't the files identical?

Yes; I had the `shasum` just as a sanity check that the files weren’t
empty, but you’re right that the `cmp` is certainly sufficient. I’ll go
ahead and remove this from the description to avoid confusion.

> Also, the tests for `tarfile` are in `Lib/test/test_tarfile.py`.

Great, thanks. Not sure how I missed this.

> Add your test and we should be ready to commit.

Will add a test to `test_tarfile.py`, probably more like the existing
tests in that file than like the end-to-end test in the description
(which would only work on systems with GNU `tar` installed).

Thanks for the speedy review! I’ll add a test and get back to you.

2020-01-22 06:25 UTC, wchargin commented
I’ve put the test in a new test class because it needs to run only in
the uncompressed case (or, we’d need special handling to decompress the
compressed archives, but I don’t see any benefit to doing that).

I have made the requested changes; please review again.

2020-01-23 02:32 UTC, ethanfurman requested changes
Looking good.  Nice tests.

Please add yourself to Misc/ACKS and we should be good to go.  (Sorry for not noticing that earlier.)

2020-01-23 04:19 UTC, wchargin commented
Done; thanks!

I have made the requested changes; please review again.

2020-01-23 04:23 UTC, ethanfurman approved these changes

2020-01-24 04:14 UTC, wchargin commented
I’m not sure how to interpret the coverage check failure. As far as
I can tell, this PR doesn’t add any uncovered lines or branches. Each
file in the Codecov “diff” has positive coverage delta, but the
“coverage changes” tab shows 363 files, almost all unrelated.

@ethanfurman, is there any action that I should take here?

2020-02-12 19:56 UTC, merged

2020-02-12 19:57 UTC, wchargin commented
Awesome; thanks for merging, and thanks for your help on this PR! :-)