bpo-29435: Allow is_tarfile to take a filelike obj
python/cpython pull request #18090
Opened 2020-01-20 23:42 UTC by woodruffw

This makes `tarfile.is_tarfile` behave similarly to `zipfile.is_zipfile`: instead of just a string or path-like, the single positional argument can also be a file or file-like.

Ref: https://bugs.python.org/issue29435

2020-01-20 23:42 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@woodruffw

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-01-21 07:50 UTC, tirkarthi commented
This will need a test similar to one in `test_zipfile` and also update to docs that the argument could be a file like object with a versionchanged directive like `is_zipfile` docs.

2020-01-22 00:50 UTC, woodruffw commented
> This will need a test similar to one in `test_zipfile` and also update to docs that the argument could be a file like object with a versionchanged directive like `is_zipfile` docs.

Thanks, will do.

2020-01-22 02:18 UTC, woodruffw commented
Okay, added tests (for all `is_tarfile` cases, not just files and file-likes) and updated the docs.

2020-01-22 14:04 UTC, ethanfurman requested changes
Looking good.

A couple minor changes to the docs text are needed.

Please add yourself to the `Misc/ACKS` file.

2020-01-22 14:04 UTC, ethanfurman commented on Doc/library/tarfile.rst
> +   module can read. *name* may be a file or file-like object too.
Change last sentence to:
<pre>
*name* may be a :class:`str`, file, or file-like object.
</pre>

2020-01-22 14:04 UTC, ethanfurman commented on Lib/tarfile.py
> +       The name argument may be a file or file-like object.
Change last sentence to:
<pre>
'name' should be a string, file, or file-like object.
</pre>

2020-01-23 00:23 UTC, woodruffw commented
I have made the requested changes; please review again!

2020-01-23 02:22 UTC, ethanfurman approved these changes

2020-01-23 02:24 UTC, merged