Change six instances of "an" to "a"
python/cpython pull request #1814
Opened 2017-05-25 13:02 UTC by kms70847

"An ModuleNotFoundError" appears several times in this document, likely because in the previous version it used to be "An ImportError".
"An path" also appears.
These instances of "an" should be "a" instead.

2017-05-25 13:02 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-05-25 14:37 UTC, kms70847 commented
Initially I wasn't sure whether "an `__path__`" ought to be changed to "a `__path__`", since one might conceivably pronounce it as "an underscore underscore path underscore underscore", but a quick grep through my slightly outdated local copy indicates that the underscores are conventionally not pronounced:
```

c:\Programming\Python 3.5\source\Python-3.5.1\Doc>grep -rsi "a ``__" *
c-api/object.rst:   A generic implementation for the getter of a ``__dict__`` descriptor. It
c-api/object.rst:   A generic implementation for the setter of a ``__dict__`` descriptor. This
faq/programming.rst:the compiled code should be created in a ``__pycache__`` subdirectory of the
faq/programming.rst:has the ability (permissions, free space, etc...) to create a ``__pycache__``
faq/programming.rst:This will write the ``.pyc`` to a ``__pycache__`` subdirectory in the same
howto/pyporting.rst:an object defines a ``__truediv__`` method but not ``__floordiv__`` then your
library/codeop.rst:   text containing a ``__future__`` statement, the instance 'remembers' and
library/doctest.rst:* Define a ``__test__`` dictionary mapping from regression test topics to
library/functools.rst:   automatically adds a ``__wrapped__`` attribute to the wrapper that refers to
library/functools.rst:      function, even if that function defined a ``__wrapped__`` attribute.
library/idle.rst:an Editor window which are not via ``__main__`` and :data:`sys.modules` will
library/inspect.rst:   chain has a ``__signature__`` attribute defined.
library/plistlib.rst:      Dict values in the result have a ``__getattr__`` method that defers
library/plistlib.rst:      Dict values in the result have a ``__getattr__`` method that defers
library/runpy.rst:      Added ability to execute packages by looking for a ``__main__`` submodule.
library/runpy.rst:   compiled bytecode file or a valid sys.path entry containing a ``__main__``
library/zipapp.rst:   Write a ``__main__.py`` file to the archive that executes *mainfn*.  The
library/zipapp.rst:   contain a ``__main__.py`` file, as otherwise the resulting archive
library/zipapp.rst:Python has been able to execute zip files which contain a ``__main__.py`` file
library/zipapp.rst:simply has to be a standard zip file containing a ``__main__.py`` file which
reference/datamodel.rst:is prepared. If the metaclass has a ``__prepare__`` attribute, it is called
reference/import.rst:module.  Specifically, any module that contains a ``__path__`` attribute is
reference/import.rst:   Non-package modules should not have a ``__path__`` attribute.
reference/import.rst: * If the module has a ``__spec__`` attribute, the information in the spec
reference/import.rst: * If the module has a ``__file__`` attribute, this is used as part of the
reference/import.rst: * If the module has no ``__file__`` but does have a ``__loader__`` that is not
using/cmdline.rst:      Supply the package name to run a ``__main__`` submodule.
using/cmdline.rst:   containing a ``__main__.py`` file, or a zipfile containing a
whatsnew/2.6.rst:Python 2.6 has a ``__future__`` import that removes ``print`` as language
whatsnew/2.6.rst:There's also a ``__future__`` import that causes all string literals
whatsnew/3.1.rst:  a ``__main__`` submodule when a package name is supplied.
whatsnew/3.3.rst:Another change is that all modules have a ``__loader__`` attribute, storing the
whatsnew/3.4.rst:* Frozen modules no longer define a ``__file__`` attribute. It's semantically
whatsnew/3.5.rst:Without a ``__future__`` import, a :exc:`PendingDeprecationWarning` will be
whatsnew/3.5.rst:the files, including a ``__main__.py`` file, into a directory ``myapp``

c:\Programming\Python 3.5\source\Python-3.5.1\Doc>grep -rsi "an ``__" *
library/contextlib.rst:It is occasionally desirable to catch exceptions from an ``__enter__``
library/contextlib.rst:Cleaning up in an ``__enter__`` implementation
reference/import.rst:By definition, if a module has an ``__path__`` attribute, it is a package,
whatsnew/2.1.rst:  is used, by defining an ``__all__`` attribute containing a list of names that
whatsnew/3.4.rst:* The :class:`int` constructor now accepts any object that has an ``__index__``
```

Besides path, all of the other "an"s here precede a name starting with a vowel.

2017-05-25 22:34 UTC, brettcannon commented
@kms70847 is this purposefully only against 3.6 and not master? Is master fixed for this?

2017-05-26 19:21 UTC, Mariatta commented
The changes here should be applied to `master` too.
@kms70847 please make your PR against `master` branch. Once it's merged, it can be backported to 3.6. 
Thanks.

2017-05-27 00:20 UTC, vadmium commented
This looks okay to me.

The ModuleNotFoundError change was introduced with commit 46f97b8. For bonus points, the problem with _an_ could also be fixed in a comment in “test.test_importlib.import_.test_fromlist.HandlingFromlist.test_module_from_package_triggers_ModuleNotFoundError”.

2017-05-27 19:33 UTC, brettcannon commented
I tried changing the base to `master` through the web UI, but then it suddenly picked up all of the changes between `3.6` and `master` so that didn't work.

2017-05-29 22:35 UTC, Mariatta requested changes
Please make the change against master branch.

2017-05-30 15:46 UTC, kms70847 commented
I have created a new pull request with identical changes except it's on the master branch: https://github.com/python/cpython/pull/1862

I could not quite figure out how to change the branch without creating a new PR. I apologize if this is an inconvenience.

2017-05-30 15:46 UTC, closed without merging