bpo-39435: Fix docs for pickle.loads
python/cpython pull request #18160
Opened 2020-01-24 05:19 UTC by hauntsaninja

2020-01-24 05:19 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@hauntsaninja

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-01-24 05:50 UTC, hauntsaninja commented
Hello, it's my first time contributing to CPython!

Apologies if something is incorrect. `make patchcheck` complained about not having updating `Misc/ACKS`, although this is a trivial change, so sort of confused about that. Hopefully it'll recognise my CLA signature soon :-)

2020-01-24 19:29 UTC, pitrou commented
Thanks for contributing this. However, I don't think there is anything to fix. The argument is positional only (hence the `/` after it), so its name is purely indicative. Here, `bytes_object` points to the kind of object that is accepted. By renaming it to `data`, that information is removed.

2020-01-24 19:30 UTC, pitrou commented
I'm rejecting this PR.

2020-01-25 02:28 UTC, hauntsaninja commented
Hello @pitrou , thanks for reviewing! 
I don't see a `/` for positional-only, all I see is a `*` for the remaining arguments being keyword-only. Note that the asterisk is escaped with a backslash in the `.rst` which could be a possible source of confusion?
As far as I can tell, the argument is not positional-only in pickle.rst on master (`.. function:: loads(bytes_object, \*, fix_imports=True, encoding="ASCII", errors="strict", buffers=None)`), the documentation at https://docs.python.org/3/library/pickle.html#pickle.loads or the behaviour at runtime:
```
>>> sys.version
'3.7.6 (default, Dec 30 2019, 19:38:26) \n[Clang 11.0.0 (clang-1100.0.33.16)]'
>>> inspect.signature(pickle.loads)
<Signature (data, *, fix_imports=True, encoding='ASCII', errors='strict')>
```

If you feel `bytes_object` is a better name than `data`, maybe we could actually document the argument as positional-only, and leave the fact that it is positional-or-keyword as undocumented.

2020-01-25 09:22 UTC, pitrou commented
Hi @hauntsaninja, you're right, it seems I confused the `\` with a `/`. Sorry for that, and I'm reopening the PR.

2020-04-30 02:36 UTC, hauntsaninja commented
Gentle bump :-)

2020-05-01 10:53 UTC, pitrou requested changes
Thank you. Just one comment.

2020-05-01 10:53 UTC, pitrou commented on Doc/library/pickle.rst
> +   *data* of an object.
Ok, but then you should mention that *data* has to be a bytes-like object.

2020-05-01 17:40 UTC, hauntsaninja commented
I have made the requested changes; please review again

2020-05-01 19:45 UTC, pitrou approved these changes

2020-05-01 19:46 UTC, merged

2020-05-01 19:46 UTC, miss-islington commented
Thanks @hauntsaninja for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2020-05-01 19:46 UTC, miss-islington commented
Sorry @hauntsaninja, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 289842ae820f99908d3a345f1f3b6d4e5b4b97fc 3.8
                                ```

2020-05-01 19:46 UTC, pitrou commented
Thank you @hauntsaninja !

2020-05-01 19:46 UTC, miss-islington commented
Sorry, @hauntsaninja, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 289842ae820f99908d3a345f1f3b6d4e5b4b97fc 3.7
                                ```