Stripped whitespace before parsing the docstring in the Lib.unittest.…
python/cpython pull request #18175
Opened 2020-01-25 01:33 UTC by scirelli

# Pull Request title
Removed whitespace from Testcase shortDescription
https://bugs.python.org/msg360666

```
bpo-39450: Stripped whitespace before parsing the docstring in the Lib.unittest.case.TestCase:shortDescription() return.
```

2020-01-25 01:33 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@scirelli

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-01-25 21:14 UTC, scirelli commented
Well I signed the license agreement it twice now... still not finding me.

2020-01-25 23:37 UTC, csabella commented
It may take a few days for the status to be updated.

2020-01-29 01:10 UTC, scirelli commented
Not sure what to do. I signed it twice.

2020-01-30 08:39 UTC, cjw296 requested changes
Please add additional test(s) to verify the behaviour you seek, they should be added around here:
https://github.com/python/cpython/blob/master/Lib/unittest/test/test_case.py#L588-L611

2020-02-01 18:32 UTC, scirelli commented
Test added

2020-02-02 16:23 UTC, cjw296 requested changes
Please make sure lines are, at most, 79 cars wide.
After that, you need to add a news item as indicated by the bot.

2020-02-03 07:03 UTC, cjw296 approved these changes

2020-02-03 07:06 UTC, merged

2020-02-03 07:07 UTC, miss-islington commented
Thanks @scirelli for the PR, and @cjw296 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-02-03 07:07 UTC, miss-islington commented
Thanks @scirelli for the PR, and @cjw296 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-02-03 08:02 UTC, miss-islington commented
Thanks @scirelli for the PR, and @cjw296 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖