fix typo
python/cpython pull request #18209
Opened 2020-01-27 18:57 UTC by Bonifacio2

2020-01-27 18:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Bonifacio2

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-01-28 14:47 UTC, cjw296 commented on Doc/reference/import.rst
> +:term:`portion` the path entry finder sets "loader" on the spec to
This should be a comma, not a space.

2020-01-28 17:14 UTC, brandtbucher requested changes
Thanks for your time @Bonifacio2, and welcome to CPython! :sunglasses:

I assume that you've seen the bot's message about the CLA?

2020-01-28 17:14 UTC, brandtbucher commented on Doc/reference/import.rst
> +:term:`portion` the path entry finder sets "loader" on the spec to
Agreed, this should be a comma:

```suggestion
:term:`portion`, the path entry finder sets "loader" on the spec to
```

2020-01-28 18:32 UTC, Bonifacio2 commented
> Thanks for your time @Bonifacio2, and welcome to CPython! 😎
> 
> I assume that you've seen the bot's message about the CLA?

Yes, I saw it. I already created my b.p.o account, set the github account, signed the agreement, received my certificate, but https://check-python-cla.herokuapp.com/ still says I haven't signed the CLA.

2020-01-28 18:38 UTC, brandtbucher commented
Okay, I'd give it a business day or two then before it's marked as received. It's my understanding that they're processed manually by a human that the PSF.

2020-01-28 18:45 UTC, Mariatta approved these changes
Thanks!

2020-01-28 18:50 UTC, Bonifacio2 commented
Hello, @Mariatta . Should I open the backport PRs for the 3.7 and 3.8 branches now or should I wait for this to be merged?

2020-01-28 18:51 UTC, brandtbucher commented
The bot will open them automatically. Your work here is done!

2020-01-28 19:10 UTC, cjw296 commented
@Mariatta - where can I find out what the `automerge` tag does? How come I appear to be able to merge this PR even though CLA is still not signed?

2020-01-29 17:44 UTC, Mariatta commented
@cjw296 The PR will be automatically merged by @miss-islington if all of the following are true:
- PR has automerge label
- PR has CLA signed label
- PR has awaiting merge label (has been reviewed and approved by a core dev)
- all checks and tests in the PR have passed
- PR does not have DO NOT MERGE label

Additionally, automerge takes care of replacing the "#NNNN" into "GH-NNNN" in the commit message.
Automerge also uses the PR description and PR body as the commit message. This is helpful in case of multiple commits in PR. 

Through GitHub web UI, the only restriction it has is that you must have commit right, and that all checks pass. Core dev can use their own judgement and bypass the CLA check if they see fit.  In the past, some of us would bypass CLA check if it is simple typo fixes. Personally for me though, I rather have CLA always signed, and let the bot do the merging.

Hope this helps.

2020-01-29 18:23 UTC, cjw296 commented
perfect, thankyou!

2020-01-30 02:23 UTC, merged

2020-01-30 02:23 UTC, miss-islington commented
Thanks @Bonifacio2 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2020-01-30 02:35 UTC, brandtbucher commented
Congrats on your first CPython contribution @Bonifacio2! :champagne:

Looking forward to seeing more from you in the future.