bpo-39487: Merge duplicated _Py_IDENTIFIER identifiers in C code
python/cpython pull request #18254
Opened 2020-01-29 14:56 UTC by shihai1991

2020-01-29 20:13 UTC, brettcannon approved these changes

2020-01-29 20:15 UTC, brettcannon requested changes

2020-01-29 20:15 UTC, brettcannon commented on Python/import.c
>      _Py_IDENTIFIER(__spec__);
```suggestion
```

2020-01-29 22:43 UTC, ncoghlan commented
We can't make this change, as it means the statics get initialised before the Python interpreter has been initialised, and won't be reinitialised if the interpreter is destroyed and recreated.

2020-01-29 22:52 UTC, ncoghlan commented
My apologies, my comment above was based on an outdated understanding of how the identifier structs get initialised (it's the usage that initialises them, not the declaration).

That means this is a useful refactoring to help identify blockers to full subinterpreter support.

2020-01-30 10:15 UTC, shihai1991 commented
I have made the requested changes; please review again

2020-01-30 23:18 UTC, brettcannon approved these changes

2020-01-30 23:20 UTC, merged

2020-01-30 23:20 UTC, brettcannon commented
Thanks, @shihai1991 !