bpo-39492: Fix a reference cycle between reducer_override and a Pickler instance
python/cpython pull request #18266
Opened 2020-01-30 01:13 UTC by pierreglaser

This also needs a backport to 3.8

2020-01-31 09:39 UTC, pierreglaser commented
@pitrou if you want to take a look.

2020-02-01 19:24 UTC, pitrou requested changes
Thank you for noticing and for the fix.

2020-02-01 19:24 UTC, pitrou commented on Modules/_pickle.c
> +    Py_CLEAR(self->reducer_override);
You should add a comment explaining why this is necessary.

2020-02-01 19:24 UTC, pitrou commented on Lib/test/pickletester.py
> +                _ = weakref.ref(f, lambda obj: collect.set())
This is complicated. You could simply do this:
```python
wr = weakref.ref(f)

# ...
del p
del f
self.assertIsNone(wr())
```

2020-02-01 19:24 UTC, pitrou commented on Lib/test/pickletester.py
> +    def test_reducer_override_no_reference_cycle(self):
You should mark this test CPython-only, as it relies on reference counting. Use the `@support.cpython_only` decorator.

2020-02-01 19:24 UTC, pitrou commented on Modules/_pickle.c
> +    }
To make this less clumsy:
```c

static int
dump(PicklerObject *self, PyObject *obj)
{
    int status = -1;
    // ...

    if (save(self, obj, 0) < 0 ||
        _Pickler_Write(self, &stop_op, 1) < 0 ||
        _Pickler_CommitFrame(self) < 0)
        goto error;

    // Success
    status = 0;

  error:
    self->framing = 0;
    Py_CLEAR(self->reducer_override);
    return status;
}
```

2020-02-02 18:41 UTC, pitrou approved these changes

2020-02-02 18:55 UTC, miss-islington commented
@pierreglaser: Status check is done, and it's a success ✅ .

2020-02-02 18:55 UTC, merged

2020-02-02 18:55 UTC, miss-islington commented
Thanks @pierreglaser for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-02-02 19:32 UTC, miss-islington commented
Thanks @pierreglaser for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2020-02-02 19:32 UTC, miss-islington commented
I'm having trouble backporting to `3.8`. Reason: '`Error 110 while writing to socket. Connection timed out.`'. Please retry by removing and re-adding the `needs backport to 3.8` label.

2020-02-02 19:33 UTC, miss-islington commented
Thanks @pierreglaser for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-02-03 06:01 UTC, miss-islington commented
Sorry, @pierreglaser, I could not cleanly backport this to `3.8` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 0f2f35e15f9fbee44ce042b724348419d8136bc5 3.8
                                ```

2020-02-03 06:01 UTC, miss-islington commented
Sorry @pierreglaser, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 0f2f35e15f9fbee44ce042b724348419d8136bc5 3.8
                                ```

2020-02-04 11:05 UTC, pierreglaser commented
I'm confused by the bot: was this PR well backported to 3.8? cc @pitrou

2020-02-04 11:25 UTC, pitrou commented
It was, but I had to do it manually because the bot failed for some reason.