bpo-39495: Remove default value from C impl of TreeBuilder.start
python/cpython pull request #18275
Opened 2020-01-30 06:49 UTC by hauntsaninja

2020-02-01 08:36 UTC, corona10 requested changes

2020-02-01 08:36 UTC, corona10 commented on Misc/NEWS.d/next/Library/2020-01-30-07-02-02.bpo-39495.8LsIRN.rst
> +Remove default value from ``attrs`` parameter of ``xml.etree.ElementTree.TreeBuilder.start`` for consistency between Python and C implementations.
```suggestion
Remove default value from *attrs* parameter of :meth:`xml.etree.ElementTree.TreeBuilder.start` for consistency between Python and C implementations.
```

2020-02-01 10:06 UTC, serhiy-storchaka commented
Thank you for your PR @hauntsaninja.

I prefer to remove also the support of None as a value of `attrib` in `treebuilder_handle_start`. According to the documentation `attrib` is a dict, and a dict is always passed to custom `TreeBuilder.start()`.

`treebuilder_handle_start` is called from two places: the implementation of `TreeBuilder.start()` and `expat_start_handler`. In the latter case None is passed for optimization, to avoid creation of an empty dictionary. We can use NULL instead of None for this optimization.

2020-02-01 10:16 UTC, serhiy-storchaka commented
Or you can just use `object(subclass_of='&PyDict_Type')` for `attrs`.

2020-02-02 04:04 UTC, hauntsaninja commented
Thanks Dong-hee and Serhiy! Don't know much about argument clinic converters, that's a neat fix.

2020-02-02 08:33 UTC, corona10 requested changes
Looks good.
I'd like to add unit tests for this change.
You can add in these files.
- https://github.com/python/cpython/blob/master/Lib/test/test_xml_etree.py
- https://github.com/python/cpython/blob/master/Lib/test/test_xml_etree_c.py

2020-02-11 01:45 UTC, hauntsaninja commented
Thanks, sorry for the delay, done. It seems test_xml_etree_c.py automatically runs all tests in test_xml_etree.py, so I only added a test for the latter.

2020-03-01 11:25 UTC, corona10 approved these changes

2020-03-01 11:25 UTC, corona10 commented
@serhiy-storchaka Can you please take a look?

2020-03-01 15:11 UTC, serhiy-storchaka commented on Lib/test/test_xml_etree.py
> +        self.assertRaises(TypeError, ET.TreeBuilder().start, "tag", None)
Please add also a test for `start()` with a single argument.

2020-03-02 06:32 UTC, serhiy-storchaka approved these changes

2020-03-02 06:33 UTC, merged