bpo-39509: Update HTTP status code to follow IANA
python/cpython pull request #18294
Opened 2020-01-31 15:14 UTC by corona10

2020-02-09 12:02 UTC, BoboTiG requested changes
Thank you for the patch @corona10 :+1:

2020-02-09 12:02 UTC, BoboTiG commented on Misc/NEWS.d/next/Library/2020-02-01-00-03-06.bpo-39509.-YxUSf.rst
> +:class:`http.HTTPStatus` Patch by Dong-hee Na.
Small improvement (missing 's' and dot):
> HTTP status codes ``103 EARLY_HINTS`` and ``425 TOO_EARLY`` are added
to :class:`http.HTTPStatus`. Patch by Dong-hee Na.

2020-02-09 12:02 UTC, BoboTiG commented on Doc/whatsnew/3.9.rst
> +HTTP status code ``103 EARLY_HINTS`` and ``425 TOO_EARLY`` are added to
```suggestion
HTTP status codes ``103 EARLY_HINTS`` and ``425 TOO_EARLY`` are added to
```

2020-02-09 13:34 UTC, corona10 commented
@BoboTiG  Thanks for the review, I 've update the PR :)

2020-02-09 13:35 UTC, corona10 commented
@rhettinger @vadmium Can you please take a look?

2020-02-09 15:19 UTC, BoboTiG approved these changes

2020-02-22 06:33 UTC, vadmium commented
Looks okay to me

2020-02-22 08:35 UTC, corona10 commented
@vadmium 

If you don't mind, can we merge this PR?, I don't have merge permission :)

2020-02-28 03:57 UTC, vadmium commented
Sorry, I don't really have the time or motivation to merge anything these days. Hopefully you can find someone else.

2020-02-28 06:26 UTC, corona10 commented
@vstinner Can you please take a look at this?

2020-03-02 16:20 UTC, vstinner commented
cc @JulienPalard @matrixise

2020-03-14 14:09 UTC, serhiy-storchaka approved these changes

2020-03-14 14:12 UTC, merged