bpo-39534: Clarify return in finally
python/cpython pull request #18324
Opened 2020-02-03 08:23 UTC by JulienPalard

2020-02-03 12:06 UTC, csabella commented
The new wording looks good.  The only suggestion I would make is to remove the links from some of the keywords, like they are in the paragraph above this one.  It may not be necessary to have every `return` be clickable, for example.

2020-02-03 16:40 UTC, JulienPalard commented
@csabella Removed a few links, good idea, too much blue don't help the readability (kept only one link per keyword on the whole list).

2020-02-04 10:26 UTC, Pritesh-Inexture requested changes
If a finally clause includes a return statement, then **always** the expression after the return in finally will be returned. However, if try or except also has a return statement, in such a case the expression after that return statement **will be evaluated but not returned**. Also, the expression in try is always evaluated **before** the expression in finally.

I think this is how someone new to python can understand what will exactly happen in this case. @JulienPalard.

2020-02-06 16:43 UTC, JulienPalard commented
Looks a bit too heavy for me, we're in a tutorial, not in `datamodel/`.

2020-02-06 22:08 UTC, csabella commented
I agree with Julien.  After reading this section of the tutorial, I think it's good that the bullet points highlight how the try/except/finally work together at a high level so that the reader can understand the general behavior, but I don't think it's necessary to go into it in more detail.  Once the reader moves beyond the tutorial into the other docs, they will gain any deeper level of understanding when they need it.

2020-02-06 22:08 UTC, csabella approved these changes

2020-02-06 22:16 UTC, merged

2020-02-06 22:16 UTC, miss-islington commented
Thanks @JulienPalard for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2020-02-06 22:16 UTC, miss-islington commented
I'm having trouble backporting to `3.8`. Reason: '`Error 110 while writing to socket. Connection timed out.`'. Please retry by removing and re-adding the `needs backport to 3.8` label.

2020-02-06 22:17 UTC, miss-islington commented
Thanks @JulienPalard for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-02-06 22:17 UTC, miss-islington commented
Thanks @JulienPalard for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖