bpo-29988: Only check evalbreaker after calls and on backwards egdes.
python/cpython pull request #18334
Opened 2020-02-03 17:04 UTC by markshannon

Makes sure that `__exit__` or `__aexit__` is called in (async) with statements, by not handling interrupts during set up of the with block.

We want to make sure that interrupts are always handled eventually, and ideally that they are handled promptly.
Checking `eval_breaker` on backward edges ensures that they are always handled eventually.
Checking after every explicit call ensures that they are handled promptly in most cases.

2020-03-15 22:18 UTC, gpshead commented
Basically this moves the check for eval breaker to a select few points instead of being more frequent.

Any idea what negative consequences this could have?

Generally things like "what code pattern now prevents a ^C from raising a KeyboardInterrupt in a timely fashion" are how I anticipate this kind of change to manifest.

2020-03-15 22:21 UTC, gpshead approved these changes
Overall I _believe_ this is good, though I would like other reviewer eyeballs on it than just mine.

2020-06-28 07:01 UTC, ncoghlan requested changes
This needs test cases to make sure that it's actually solving the problem its aiming to solve.
The draft ones I wrote at the 2017 core dev sprints can be found at https://github.com/ncoghlan/cpython/pull/2/files (writing these test cases was the original reason we added per-opcode tracing support to the eval loop)

2020-06-28 07:09 UTC, ncoghlan commented
Like @gpshead, this approach looks promising to me in principle - I like it a *lot* better than what I tried back in 2017. Removing the `DISPATCH`/`FAST_DISPATCH` distinction is also a nice bonus (effectively the opcodes that call the eval breaker are now the only ones not using fast dispatch).

So if we're super lucky, the test cases from my old branch will "just work" with this new code. And if they still don't pass, well, that's important to know as well :)

2020-07-09 09:19 UTC, markshannon commented
@ncoghlan
Adding tests only ensures that https://bugs.python.org/issue29988 doesn't manifest itself under some circumstances.
However, we know PR fixes the problem, because there can be no interrupt between the call to `__enter__` and the exception handler being installed.
Having said that, a regression test is a good idea.
I've just had a look at your test. The one thing that I don't like is that it uses `f_trace_opcodes`, which exists purely to test for https://bugs.python.org/issue29988.
I'd like to remove  `f_trace_opcodes` as its behaviour is undefined, because the sequence of bytecodes generated for any Python code is not defined. 
Any ideas on how to test it without using `f_trace_opcodes`?

I've not tested your branch as https://github.com/ncoghlan/cpython/pull/2/files has some unrelated changes to `ceval.c` so won't rebase cleanly onto this branch.

2020-11-21 09:39 UTC, gpshead commented
@ncoghlan any thoughts on markshannon's question above?

2021-01-25 14:59 UTC, markshannon commented
@ncoghlan?

2021-01-27 14:13 UTC, ncoghlan commented
I added f_trace_opcodes specifically to enable the injection of exceptions after an arbitrary number of opcodes. The intended usage is the way I used it in the bpo-29988 test case: inject an exception after every bytecode offset and ensure they're all handled "as expected".

I didn't want to require a special build for the testing, nor rely on an undocumented feature, so we went ahead and published it, even though we didn't manage to fix the original bug report.

If we knew of another way to test this kind of thing, we wouldn't have needed to add f_trace_opcodes :)

2021-03-24 17:55 UTC, markshannon commented
I think this has sat around for long enough, time to merge.

2021-03-24 17:56 UTC, merged