bpo-39548: Fix handling of 'WWW-Authenticate' header for Digest Auth
python/cpython pull request #18338
Opened 2020-02-03 23:50 UTC by sbalousek

- The 'qop' value in the 'WWW-Authenticate' header is optional. The
   presence of 'qop' in the header should be checked before its value
   is parsed with 'split'.

Signed-off-by: Stephen Balousek <stephen@balousek.net>

2020-02-03 23:50 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@sbalousek

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-02-04 22:15 UTC, sbalousek commented
Hi!
I apologize in advance for missing any procedural steps here.  This is my first merge request, and although I read the developer documentation, there's a lot of it!
Please let me know what I am missing!
- Steve

2020-02-06 12:15 UTC, csabella commented
Hi Steve!  Welcome and thank you for the contribution to CPython.  You've done a great job navigating your first PR here.  :-)  The `bedevere/news` status is red because most changes require a News entry.  This allows users to see what has changed from one version to the next.  Code coverage is also red, but you changed the lines around, but didn't add new logic, so I'm not sure why it's unhappy.  Typically, if you introduce new logic, you need to also add tests to cover it.

2020-02-06 12:43 UTC, sbalousek commented
Thanks @csabella, for the warm welcome. I figured out how to add a News item, but I am also unsure why the code coverage test results changed. I can try adding new test cases for the 'WWW-Authenticate' header if you like. My guess is that it will take me a little while to figure the test subsystem out.

This change request is all about fixing the changes made for `bpo-38686`, but I can certainly see the value of adding tests for this part of the library.

2020-02-06 13:09 UTC, sbalousek commented
Also, how does this change get backported to versions 3.8 and 3.7? Is that automatic or something I need to initiate?

2020-02-06 16:55 UTC, brandtbucher commented
Thanks for your time, and welcome to CPython @sbalousek! :sunglasses:

Sorry about the late review, I've been tied up with a couple of other things. I've tagged this for backporting, as you suggested.

2020-02-06 17:00 UTC, brandtbucher requested changes
Looks great! We don't have many tests in this area (and coverage is passing), so this is probably good as-is. Just one small change to the NEWS entry:

2020-02-06 17:00 UTC, brandtbucher commented on Misc/NEWS.d/next/Library/2020-02-06-05-33-52.bpo-39548.DF4FFe.rst
> +Fix handling of 'WWW-Authenticate' header when the optional 'qop' parameter
This can be a bit richer:

```suggestion
Fix handling of header in :class:`urllib.request.AbstractDigestAuthHandler` when the optional ``qop`` parameter
```

2020-02-06 17:02 UTC, sbalousek commented on Misc/NEWS.d/next/Library/2020-02-06-05-33-52.bpo-39548.DF4FFe.rst
> +Fix handling of 'WWW-Authenticate' header when the optional 'qop' parameter
Much better. Thank you, Brandt!

2020-02-06 18:26 UTC, brandtbucher approved these changes
Looks good now! CC @orsenthil.

2020-02-13 08:15 UTC, PypeBros commented
good catch.

2020-02-29 12:52 UTC, orsenthil approved these changes
LGTM. Thank you! :)

2020-02-29 20:31 UTC, merged

2020-02-29 20:32 UTC, miss-islington commented
Thanks @sbalousek for the PR, and @orsenthil for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2020-02-29 20:32 UTC, miss-islington commented
I'm having trouble backporting to `3.8`. Reason: '`Error 110 while writing to socket. Connection timed out.`'. Please retry by removing and re-adding the `needs backport to 3.8` label.

2020-02-29 20:46 UTC, miss-islington commented
Thanks @sbalousek for the PR, and @orsenthil for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖