bpo-39549: reprlib.Repr uses a “fillvalue” attribute
python/cpython pull request #18343
Opened 2020-02-04 02:16 UTC by fish2000

Whereas the code for `reprlib.Repr` had previously used a hardcoded
string value of `'...'`, this PR updates it to use of a “fillvalue”
attribute, whose value defaults to `'...'` and can be reset in either
individual `reprlib.Repr` instances or in subclasses thereof.

A new assert has been added to `test_reprlib.py` to verify the new
attributes’ functionality.

2020-02-05 22:40 UTC, eamanu reviewed
Hi, 

I think setting a variable could be confused in the sense that is more quickly see
the '...' than "self.fillvalue". But is a personal point of view.

Despite of this  could be a good improve to if we want to avoid 'hardcoded' things.

2020-02-06 14:50 UTC, rhettinger commented
Why not pass the fillvalue into \__init__?

2020-02-07 16:19 UTC, fish2000 commented
@rhettinger I would be happy to do that – I only set it up this way to match the existing manner of setting attributes on `reprlib.Repr` instances. Shall I go ahead and change it to use an argument?

2021-09-19 18:47 UTC, rhettinger requested changes
Please update the main documentation as well:  Doc/library/reprlib.rst

Include a *versionchanged* directive.

2021-09-22 16:57 UTC, rhettinger commented
Hmm, the force push didn't work out well.  Was trying to add this only:

```

diff --git a/Doc/library/reprlib.rst b/Doc/library/reprlib.rst
index dbe2a7182a..9e1873d582 100644
--- a/Doc/library/reprlib.rst
+++ b/Doc/library/reprlib.rst
@@ -75,6 +75,14 @@ size limits for the representations of different object types,  and methods
 which format specific object types.


+.. attribute:: Repr.fillvalue
+
+   This string is displayed for recursive references. It defaults to
+   ``...``.
+
+   .. versionadded:: 3.11
+
+
 .. attribute:: Repr.maxlevel

    Depth limit on the creation of recursive representations.  The default is ``6``


```

2021-09-22 20:44 UTC, rhettinger approved these changes

2021-09-22 20:45 UTC, merged

2021-09-22 20:46 UTC, rhettinger commented
Thanks Zach.

2021-09-25 22:32 UTC, fish2000 commented
🎉🎉🎉