bpo-30499: Remove a deprecated note about sets.
python/cpython pull request #1848
Opened 2017-05-28 21:34 UTC by JulienPalard

Found that this note is refering to code that has been dropped in 51ced7afe72d861b46f069d757f2787f13253d32.

2017-05-29 03:49 UTC, rhettinger commented on Doc/library/stdtypes.rst
> +   :meth:`discard` methods may be a set.
While correct, this leaves the mechanism as a mystery.   There should probably be a sentence saying that a new temporary frozenset is built from *elem*.  That would be a minor implementation detail except for the O(n) conversion cost.

2017-05-29 03:50 UTC, rhettinger requested changes
Add a note indicating that a temporary frozenset is built to support the search.

2017-06-01 02:07 UTC, Mariatta approved these changes

2017-06-01 03:25 UTC, rhettinger approved these changes

2017-06-01 14:02 UTC, merged

2017-06-01 14:14 UTC, Mariatta commented
Thanks for the PR @JulienPalard 🎉

2017-06-01 14:24 UTC, JulienPalard commented
Thanks for the merge in all relevant branches @Mariatta