bpo-39479:Add math.lcm() function: Least Common Multiple
python/cpython pull request #18547
Opened 2020-02-18 12:29 UTC by ananthan-123

2020-02-18 12:33 UTC, ananthan-123 commented
This PR is created due to some problems caused in the repository.
#18328

2020-02-18 14:49 UTC, ananthan-123 commented
It is showing an error 

1 test failed:
    test_importlib

2020-02-18 15:04 UTC, mdickinson commented
> This PR is created due to some problems caused in the repository.

I recommend that you investigate Git branching: instead of making all your commits on the master branch of your fork, create a dedicated branch for the work you're doing, and make the pull request from that. Apart from anything else, that will enable you to work on multiple independent issues at once, in different branches of your fork.

2020-02-18 15:32 UTC, ananthan-123 commented
Thanks for the information.
can you tell me what is the problem in the code?

2020-02-18 16:06 UTC, ananthan-123 commented
======================================================================
FAIL: test_case_insensitivity (test.test_importlib.extension.test_case_sensitivity.Frozen_ExtensionModuleCaseSensitivityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/runners/2.164.0/work/cpython/cpython/Lib/test/test_importlib/extension/test_case_sensitivity.py", line 36, in test_case_insensitivity
    self.assertTrue(hasattr(loader, 'load_module'))
AssertionError: False is not true

======================================================================
FAIL: test_case_insensitivity (test.test_importlib.extension.test_case_sensitivity.Source_ExtensionModuleCaseSensitivityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/runners/2.164.0/work/cpython/cpython/Lib/test/test_importlib/extension/test_case_sensitivity.py", line 36, in test_case_insensitivity
    self.assertTrue(hasattr(loader, 'load_module'))
AssertionError: False is not true

======================================================================
FAIL: test_insensitive (test.test_importlib.source.test_case_sensitivity.Frozen_CaseSensitivityTestPEP302)
----------------------------------------------------------------------
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/runners/2.164.0/work/cpython/cpython/Lib/test/test_importlib/source/test_case_sensitivity.py", line 57, in test_insensitive
    self.assertIsNotNone(insensitive)
AssertionError: unexpectedly None

2020-02-18 16:06 UTC, ananthan-123 commented
Above is the error showing.

2020-02-18 18:41 UTC, mdickinson commented on Doc/library/math.rst
> +   .. versionadded:: 3.5
3.9

2020-02-18 18:44 UTC, mdickinson commented on Lib/test/test_math.py
> +                  576559230871654959816130551884856912003141446781646602790216406874):
I don't think there's any real need to use such a huge number here. Pick something else?

2020-02-18 18:46 UTC, mdickinson commented on Misc/ACKS
> +Ananthakrishnan
Please maintain the rough alphabetical order.

2020-02-18 18:47 UTC, mdickinson commented on Misc/NEWS.d/next/Library/2020-02-18-12-37-16.bpo-39479.j3UcCq.rst
> +Add :func:`math.lcm` function: Least Common Multiple.
It doesn't matter that much, since this is only a news entry, but why the capitalization? This wasn't there in your original, approved PR.

2020-02-18 18:50 UTC, mdickinson requested changes
I've left a few comments.

The macOS failures are unrelated, and are described in https://bugs.python.org/issue38691. Once #18553 is merged, you should be able to merge origin/master into your branch to get the CI to pass.

2020-02-19 09:54 UTC, ananthan-123 commented
I have made the requested changes; please review again

2020-02-19 11:32 UTC, mdickinson commented
@ananthan-123: 

> I have made the requested changes

Not quite. :-) Please could you address my comment about alphabetical order in `Misc/ACKS`?

2020-02-19 11:32 UTC, mdickinson requested changes
There's still one unaddressed comment from the last change request.

2020-02-19 13:51 UTC, ananthan-123 commented
I have made the requested changes; please review again

2020-02-19 14:23 UTC, mdickinson commented
@ananthan-123 Please can you investigate the failure on Travis CI? I think you may need to re-run `make clinic` locally and push the changes that result from that. It would also be worth merging the upstream master into this branch if you haven't already done so.

(As a general rule, it's good to try to get all the CI checks passing before asking for review.)

2020-02-19 17:42 UTC, ananthan-123 commented
Hurray!The test is **passed**

2020-02-19 17:43 UTC, ananthan-123 commented
I have made the requested changes; please review again

2020-02-19 18:21 UTC, mdickinson approved these changes
LGTM

2020-02-19 18:21 UTC, merged