bpo-39737: Speed up list.__eq__
python/cpython pull request #18638
Opened 2020-02-24 04:57 UTC by sweeneyde

2020-02-25 15:12 UTC, corona10 requested changes
Without objective indicators of performance improvements, news of performance improvements may not be appropriate.
Nevertheless, for the code cleansing, I think this PR is acceptable.

2020-02-25 15:12 UTC, corona10 commented on Misc/NEWS.d/next/Core and Builtins/2020-02-24-04-59-34.bpo-39737.467YHt.rst
> +Sped up list comparison operators by about 6%.
Sped/Speed

2020-02-25 15:12 UTC, corona10 commented on Objects/listobject.c
> +        int k;
IMHO, there is no reason to declare `k` on this line.
Please rollback it :)

2020-02-25 15:12 UTC, corona10 commented on Objects/listobject.c
> +        k = PyObject_RichCompareBool(vitem, witem, Py_EQ);
`int k = PyObject_RichCompareBool(vitem, witem, Py_EQ);`might be enough

2020-02-25 15:13 UTC, corona10 commented on Misc/NEWS.d/next/Core and Builtins/2020-02-24-04-59-34.bpo-39737.467YHt.rst
> +Sped up list comparison operators by about 6%.
But please read my comment :)

2020-02-26 01:19 UTC, corona10 requested changes

2020-02-26 01:19 UTC, corona10 commented on Misc/NEWS.d/next/Core and Builtins/2020-02-25-19-21-00.bpo-39737.CaeXi4.rst
> +Remove code repitition in list_richcompare.
We don't add news for this case :)

2020-02-26 01:38 UTC, methane approved these changes

2020-02-26 02:08 UTC, corona10 approved these changes

2020-02-26 06:58 UTC, serhiy-storchaka approved these changes

2020-02-26 07:00 UTC, merged

2020-03-02 16:35 UTC, vstinner commented
>  code repitition

Is it a play on words?