bpo-37970: Added documentation fixes
python/cpython pull request #18631
Opened 2020-02-23 23:20 UTC by idomic

# bpo-37970: Added documentation fixes

# [X.Y] bpo-37970: Added documentation fixes (GH-NNNN)

2020-03-01 16:53 UTC, idomic commented
Tagging @taleinat

2020-03-12 19:58 UTC, taleinat requested changes
The fix here is good and important.

However, this does not address the central issue brought up in bpo-37970, regarding this line of the docs being misleading, since the parts of the netloc are available as additional attributes on the returned named-tuple object:

> The components are not broken up in smaller parts (for example, the network location is a single string)

2020-03-15 14:12 UTC, idomic commented
> The fix here is good and important.
> 
> However, this does not address the central issue brought up in [bpo-37970](https://bugs.python.org/issue37970), regarding this line of the docs being misleading, since the parts of the netloc are available as additional attributes on the returned named-tuple object:
> 
> > The components are not broken up in smaller parts (for example, the network location is a single string)

You're right, don't know why I missed this part, fixed for both urlsplit and parse.

2020-03-15 14:13 UTC, idomic commented
I have made the requested changes; please review again

2020-03-18 21:33 UTC, taleinat requested changes
I think this change to the documentation is still not clear enough. Writing "The components are broken up into smaller parts (for example, ...)" is confusing, since for example the query is not broken down into its parts.

What really happens is that the parts as described in the beginning are used as-is for the named-tuple fields. Additionally, only the netloc is broken down into username, password, hostname, and port, and those are added as additional attributes on the returned object. Further, these extra attributes are *only accessible by name*, but not by index - they are not technically part of the named-tuple's fields.

We need to convey this clearly and concisely, which needs some more thought. The currently suggested wording doesn't achieve this.

2020-03-22 21:36 UTC, idomic commented
@taleinat I've changed one description, once we'll decide on the format I'll clone for the other function

2020-05-17 19:43 UTC, idomic commented
@taleinat ping on that

2020-05-19 10:43 UTC, taleinat commented
Apologies for the delay, @idomic.

What you've written is better, I like the direction :)

I suggest omitting the first sentence, which I find redundant, changing the order of the sentences, and changing "expanded" to "decoded":

> The delimiters as shown above
   are not part of the result, except for a leading slash in the *path* component, which is
   retained if present.
>
> Additionally, the netloc item is broken down into: username, password, hostname, and port. These are added as additional attributes of the returned object.
>
> % escapes are not decoded.
>
> For example: ...

What do you think?

2020-05-24 22:02 UTC, idomic commented
@taleinat Agree, I like the decoded change, and the first paragraph.
What do you think about:

Additionally, the netloc property is broken down into these additional attributes in the returned object: username, password, hostname, and port.

2020-05-25 06:43 UTC, taleinat commented
@idomic, looks good, just replace "in the returned object" with "added to the returned object".

2020-05-25 14:34 UTC, taleinat approved these changes

2020-05-25 14:35 UTC, taleinat requested changes
I almost forgot! Please use a similar doc-string for `urlsplit()`.

2020-05-26 20:10 UTC, taleinat commented
@idomic, please review the documentation you suggest here for `urlsplit()` more thoroughly: It contains wrong information (it returns a 5-tuple, not a 6-tuple) and much duplication.

Please use the new wording to replace the parallel existing wording further in its documentation.

2020-05-26 20:11 UTC, taleinat requested changes
@idomic, please review the `urlsplit()` docs as currently suggested by this PR much more thoroughly.

2020-06-05 12:44 UTC, idomic commented
> @idomic, please review the `urlsplit()` docs as currently suggested by this PR much more thoroughly.

@taleinat I think I've added the missing descriptions and changed it to fit to url split. Also tried to remove redundant text.

2020-06-05 12:44 UTC, idomic commented
I have made the requested changes; please review again

2020-06-20 20:19 UTC, idomic commented
@taleinat Added the urlsplit() let me know what you think

2020-06-23 08:11 UTC, taleinat requested changes
Two small comments.

Also, please make sure to wrap the lines at 80 characters, in keeping with (the style guide)[https://devguide.python.org/documenting/#style-guide].

2020-06-23 08:11 UTC, taleinat commented on Doc/library/urllib.parse.rst
> +   Similar to :func:`urlparse`, witout splitting the URL parameters.
Typo: "witout" -> "without"

2020-06-23 08:11 UTC, taleinat commented on Doc/library/urllib.parse.rst
> +   separate the path segments and parameters.
I suggest keeping these lines together with the first line ("This is similar..."), like it was before.

2020-06-27 18:07 UTC, idomic commented on Doc/library/urllib.parse.rst
> +   Similar to :func:`urlparse`, witout splitting the URL parameters.
Fixed

2020-06-28 11:20 UTC, taleinat submitted a review, later dismissed

2020-06-28 11:20 UTC, taleinat commented on Doc/library/urllib.parse.rst
> +   the returned object: username, password, hostname, and port.
This part of the urlparse docs is still not wrapped to 79 characters.

2020-06-28 14:24 UTC, idomic commented
I have made the requested changes; please review again

2024-07-14 10:30 UTC, tuukkamustonen reviewed
Looking into this years old PR.

The function docstrings were adjusted in https://github.com/python/cpython/pull/16458. What remains are updates to the reference docs (this PR).

As I see it, the author has done all the fixes requested.

Added a few comments/suggestions. But in general, it looks good to me.

Maybe @zware @taleinat @encukou could have a look? @idomic you still around to potentiall adjust?

(Looking into this as part of EuroPython 2024 sprint - I'm just a user, not maintainer, fyi.)

2024-07-14 10:30 UTC, mtvx commented on Doc/library/urllib.parse.rst
> +   and port.
Same comment as above, for formatting the fields.

2024-07-14 10:30 UTC, tuukkamustonen commented on Doc/library/urllib.parse.rst
> +   This function returns a 5-item :term:`named tuple`::
The paragraph here feels a bit confusing to the reader. Could it be rephrased a little bit and an example given:

```
The function is similar to :func:`urlparse`, but does not split the parameters from the
URL. This is useful, if the given :attr:`url` follows the alternative URL syntax that allows parameters
per path segment (e.g. `http://hostname/path;arg=value/bar`, see :rfc:`2396`).
In that case, the path segments and parameters need to be separated with a separate function.

The function returns a 5-item :term:`named tuple`::
```

I'd also like to see an explicit mention there, that the "separate function" referenced there is _not_ provided in the stdlib. Now it just leaves the reader dry on that ("okay, which function???").

On the other hand, RFC 2396 (from 1998) has been obsoleted by [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) (in 2005), and the latter no longer has the query-params-per-path-segment format in the spec (https://stackoverflow.com/a/6548553/165629).

I wonder how useful it is to reference a spec which is no longer valid and which (probably few people) use. Could the paragraph be lifted altogether?

Then again, it makes perfect sense to explain _why_ there is `urlparse` and `urlsplit`, when/if the only difference is parsing the parameters vs not (I wonder what _is_ the reasoning that remains, it doesn't do real harm to try parse the `?` query parameters when they don't exist).

2024-07-14 10:30 UTC, tuukkamustonen commented on Doc/library/urllib.parse.rst
> +   port.
The same information is given in the below table, so I'm not sure how necessary this paragraph is?

I don't see harm in having it, though.

The field names should be formatted, though:

```
   Additionally, the netloc property is broken down into these additional
   attributes added to the returned object: :attr:`username`, :attr:`password`, :attr:`hostname`,
   and :attr:`port`.
```

2024-11-01 22:51 UTC, willingc reviewed
Let's reboot this PR and move into a mergeable state.

2024-11-01 22:51 UTC, willingc commented on Doc/library/urllib.parse.rst
> +   % escapes are not decoded.
```suggestion
```

2024-11-01 22:51 UTC, willingc commented on Doc/library/urllib.parse.rst
> +   This function returns a 5-item :term:`named tuple`::
```suggestion
   This function returns a 5-item :term:`named tuple`::
```

2025-01-26 09:48 UTC, StanFromIreland commented
Hello, the original creator has not been active for quite some time. I can open a PR for #82151 myself if @idomic doesn't mind.

2026-07-07 19:05 UTC, cmaloney commented
Thanks for the PR @idomic! Continuation of this work got merged in https://github.com/python/cpython/pull/152985

2026-07-07 19:05 UTC, closed without merging