bpo-39769: Fix compileall ddir for subpkgs.
python/cpython pull request #18676
Opened 2020-02-27 08:47 UTC by gpshead

Fixes `compileall.compile_dir()`'s `ddir` parameter and `compileall` command
line flag `-d` to no longer write the wrong pathname to the generated
pyc file for submodules beneath the root of the directory tree being
compiled.  This fixes a regression introduced with Python 3.5.

2020-02-27 08:49 UTC, gpshead commented
while i marked this as needing a backport... it'll never be automatic.  This fix was easy to make as I could use the new features introduced by PR 16102 to implement it.  I'm not sure it is worth it, nobody noticed for _four_ releases.  Easiest to just let 3.9 get this.

2020-02-27 21:44 UTC, Yhg1s requested changes

2020-02-27 21:44 UTC, Yhg1s commented on Lib/compileall.py
> +                invalidation_mode=None, *, stripdir=None,
This feels like a superfluous change... also, the choice of which parameters are keyword-only seems a bit arbitrary?

2020-02-27 21:44 UTC, Yhg1s commented on Lib/compileall.py
> +    if ddir:
What if ddir is an empty string?

2020-02-27 21:44 UTC, Yhg1s commented on Lib/test/test_compileall.py
> +        assert mods
This should use an assert method, because the testsuite does get run with -O.

2020-02-27 21:44 UTC, Yhg1s commented on Lib/test/test_compileall.py
> +                str(err, encoding=sys.getdefaultencoding())
os.fsdecode(err)

2020-02-28 05:33 UTC, gpshead commented on Lib/compileall.py
> +                invalidation_mode=None, *, stripdir=None,
The previous change from #16012 added the following three parameters for 3.9, there is no reason not to make them keyword only. That is the only way they'll be used.  Doing it to the other parameters would make sense but would be an incompatible API change so I'm not going there.

2020-02-28 05:57 UTC, gpshead commented
I have made the requested changes; please review again.

2020-02-29 00:34 UTC, Yhg1s approved these changes

2020-02-29 01:28 UTC, merged

2020-02-29 01:28 UTC, miss-islington commented
Thanks @gpshead for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-02-29 01:28 UTC, miss-islington commented
Sorry @gpshead, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 02673352b5db6ca4d3dc804965facbedfe66425d 3.8
                                ```