bpo-28577: Special case added to IPv4Network hosts for /32 networks
python/cpython pull request #18757
Opened 2020-03-02 23:49 UTC by JamoBox

Calling hosts() on a /32 IPv4Network now returns a list containing the IPv4Address instead of an empty list.

2020-03-03 18:01 UTC, ethanfurman requested changes
According to Travis there is a file with whitespace issues, and some problem with the docs.

Otherwise, it looks good to me!

2020-03-03 20:04 UTC, JamoBox commented
I have made the requested changes; please review again

2020-03-03 21:42 UTC, ethanfurman approved these changes
Looks good!

I'll give it a couple days in case somebody else want to chime in.  Feel free to ping me early next week if this PR is still open.

2020-03-09 21:52 UTC, JamoBox commented
> Looks good!
> 
> I'll give it a couple days in case somebody else want to chime in. Feel free to ping me early next week if this PR is still open.

No updates on here or on [BPO](https://bugs.python.org/issue28577) - do we want to leave it open a bit longer or are you happy to sign off on it?

2020-03-09 22:33 UTC, merged

2020-03-09 22:35 UTC, miss-islington commented
Thanks @JamoBox for the PR, and @ethanfurman for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6.
🐍🍒⛏🤖

2020-03-09 22:35 UTC, miss-islington commented
Thanks @JamoBox for the PR, and @ethanfurman for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-03-09 22:35 UTC, miss-islington commented
Sorry, @JamoBox and @ethanfurman, I could not cleanly backport this to `3.6` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 8e9c47a947954c997d4b725f4551d50a1d896722 3.6
                                ```

2020-03-09 22:35 UTC, miss-islington commented
Sorry @JamoBox and @ethanfurman, I had trouble checking out the `3.7` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 8e9c47a947954c997d4b725f4551d50a1d896722 3.7
                                ```

2020-03-09 22:42 UTC, ethanfurman commented
Will need to do the backports after the RCs are published.

2021-04-12 09:11 UTC, mathieui commented
Hi there, sorry for the noise; it looks like the backports did not happen, did they?

2021-04-22 20:05 UTC, JamoBox commented
> Hi there, sorry for the noise; it looks like the backports did not happen, did they?

Yep, totally forgot about these - PRs are in for 3.6, 3.7 and 3.8 now. Thanks!