Add daemon keyword to Timer class constructor
python/cpython pull request #1878
Opened 2017-05-31 01:36 UTC by awolokita

Currently in order to have daemonic Timer objects one must instantiate the class, set daemonic status through the property (Timer.daemon=True), and then start the Timer. It would be nice to have the ability to set the daemonic status of the Timer class during instantiation, similar to what is possible with the Thread superclass.

2017-05-31 01:36 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-05-31 02:41 UTC, mlouielu commented
Hi @awolokita, thanks for this contribution. For non-trivial enhancement, you should first go to b.p.o: http://bugs.python.org to open a new issue, then post the PR to GitHub. Also, you will need to signed the CLA (please refer here for how to do: http://cpython-devguide.readthedocs.io/pullrequest.html#licensing)

After doing this, you will need to change your PR's title to the b.p.o issue number, for example: `bpo-55123: Add daemon keyword...`

2017-05-31 02:58 UTC, awolokita commented
Hi @mlouielu, thanks for your feedback.I have opened the issue + changed the PR title, as well as signed the CLA.
Andre.

2017-05-31 03:02 UTC, mlouielu commented
@awolokita For CLA not signed badge, you will need to wait until Member removes the badge and then bedevere will re-check again.

For your patch, I think it will also need to update `Doc/library/threading.rst`, too.

2017-05-31 03:24 UTC, awolokita commented
@mlouielu Thank you. I have updated `Doc/library/threading.rst` to reflect changes.

2019-04-16 15:11 UTC, pitrou requested changes
On the principle, I think this change isn't very useful (the `threading.Timer` class is rarely the right answer for scheduling tasks in the future). However, it also seems harmless.

This PR lacks:
* some unit tests in `Lib/test/test_threading.py`
* a Misc/NEWS entry describing the change. You can generate it using [blurb](https://pypi.org/project/blurb/).

2019-04-16 15:11 UTC, pitrou commented on Doc/library/threading.rst
>     .. versionchanged:: 3.3
You need to add a `versionchanged` entry for the new constructor argument.

2019-11-16 01:49 UTC, csabella commented
@awolokita, please address the code review requesting unit tests and a news entry.  Thanks!

2020-01-12 13:38 UTC, csabella commented
It appears that this pull request has been abandoned, so I'm going to close it.  It can be reopened or a new pull request can be created to address the issue.  Thank you!

2020-01-12 13:38 UTC, closed without merging