bpo-30521: IDLE: Add navigate bar and replace current goto dialog
python/cpython pull request #1884
Opened 2017-05-31 08:03 UTC by mlouielu

2017-06-05 19:35 UTC, terryjreedy commented on Lib/idlelib/editor.py
> +        from idlelib.singlebar import NavigateBar
You named the file navigatebar

2017-06-05 19:38 UTC, terryjreedy requested changes
As I will explain on the issue, I do not like the concept and am inclined to reject this.

+ a bar with no title is confusing.

2018-02-02 22:04 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2022-06-29 19:24 UTC, erlend-aasland commented
> As I will explain on the issue, I do not like the concept and am inclined to reject this.

@terryjreedy, is this still your stance? If so, I'd like to mark this as pending close.
@mlouielu, are you still interested in pushing these changes?

2022-07-01 03:04 UTC, terryjreedy commented
I will try my alternate plan first (see issue), and even that is low priority.  (I believe I have not heard from Louie since Sept. 2017.)

2022-07-01 03:04 UTC, closed without merging