bpo-39702: Add the documentation for Assignment Expressions (PEP 572).
python/cpython pull request #18851
Opened 2020-03-08 13:28 UTC by shankarj67

https://bugs.python.org/issue39868

2020-03-08 17:41 UTC, brandtbucher commented
Thanks for your time @shankarj67, and welcome to CPython! :sunglasses:

I'll review this in a bit. Adding "skip news" since the one for #18793 is fine here as well.

Also, can you change the PR title to reference "bpo-39868" instead of "bpo-39702"?

2020-03-08 17:54 UTC, brandtbucher requested changes
This is good, thanks!

It's a bit longer than I think it needs to be, though (see similar sections, which are quite brief and have no subheadings). I also don't *think* we need examples of code *without* assignment expressions, since we're not trying to sell the syntax (like the PEP), just explaining it!

Before we get to grammar, etc., I've identified three chunks that can probably be removed, for the reasons above.

2020-03-08 17:54 UTC, brandtbucher commented on Doc/reference/expressions.rst
> +
```suggestion
```

2020-03-08 17:54 UTC, brandtbucher commented on Doc/reference/expressions.rst
> +**Using assignment expression**
```suggestion
```

2020-03-08 17:54 UTC, brandtbucher commented on Doc/reference/expressions.rst
> +**Using assignment expression**
```suggestion
```

2020-03-08 18:42 UTC, shankarj67 commented on Doc/reference/expressions.rst
> +**Using assignment expression**
I have added the commit.

2020-03-10 15:48 UTC, brandtbucher requested changes
I've added some suggestions (mostly grammar and style):

2020-03-10 15:48 UTC, brandtbucher commented on Doc/reference/expressions.rst
We typically add `versionadded` directives for new features:

```suggestion

.. versionadded:: 3.8

```

2020-03-10 15:48 UTC, brandtbucher commented on Doc/reference/expressions.rst
> +chunk from the file.
I was a bit confused by the original wording... something like this is clearer to me:

```suggestion
Or, when processing a file stream in chunks:
```

2020-03-10 15:48 UTC, brandtbucher commented on Doc/reference/expressions.rst
> +   if (matching := pattern.search(data)):
No need for parentheses here:

```suggestion
   if matching := pattern.search(data):
```

2020-03-10 15:48 UTC, brandtbucher commented on Doc/reference/expressions.rst
> +One common use case is when handling the matched data in regular expression
Grammar:

```suggestion
One common use case is when handling matched regular expressions:
```

2020-03-10 15:48 UTC, brandtbucher commented on Doc/reference/expressions.rst
> +
I personally don't think this needs to include the history or motivation... just the behavior. We can reuse the above grammar for the explanation, too!

```suggestion
An assignment expression (sometimes also called a "named expression" or
"walrus") assigns an :token:`expression` to an :token:`identifier`, while also
returning the value of the :token:`expression`. 
```

2020-03-10 17:05 UTC, shankarj67 commented
Thank you for the suggestion. I have added the new commit.

2020-03-10 17:31 UTC, brandtbucher commented on Doc/reference/expressions.rst
> +One common use case is when handling matched regular expression:
Thanks! One more tiny fix:

```suggestion
One common use case is when handling matched regular expressions:
```

2020-03-10 17:47 UTC, shankarj67 commented on Doc/reference/expressions.rst
> +One common use case is when handling matched regular expression:
done

2020-03-10 18:12 UTC, brandtbucher approved these changes

2020-07-17 17:00 UTC, brandtbucher commented
Closing and reopening to trigger CI.

2020-07-25 20:58 UTC, gvanrossum approved these changes
This looks fine to me. Is it waiting for anything?

2020-07-25 23:15 UTC, brandtbucher commented
Just a merge! ;)

2020-07-25 23:33 UTC, merged

2020-07-25 23:33 UTC, miss-islington commented
Thanks @shankarj67 for the PR, and @gvanrossum for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖