bpo-30532: email.policy.SMTP.fold() mangles long headers
python/cpython pull request #1892
Opened 2017-05-31 22:52 UTC by jhillacre

Pull request for http://bugs.python.org/issue30532

2017-06-01 01:49 UTC, zvyn commented on Lib/email/_header_value_parser.py
>                  # avoid infinite recursion.
Looks good to me! You could remove the repeated comment from line 340 while you are here.

2017-06-01 02:17 UTC, jhillacre commented
@zvyn OK, got it in 3d07dc5.

2017-06-05 20:10 UTC, jhillacre commented
Rebased from master so the windows build passes and gives the PR the ✔️.

2017-06-05 20:13 UTC, jhillacre commented
Is there anything I need to do to keep the PR moving?

2017-06-26 01:19 UTC, bitdancer requested changes
One small change, and we need a NEWS entry (which should now use the 'blurb' mechanism, see the recent updates to the devguide).

2017-06-26 01:19 UTC, bitdancer commented on Lib/email/_header_value_parser.py
> +                folded.stickyspace = ws
It looks like this was a case of me "fixing" the code, and missing one spot (for which there obviously wasn't a test).  To make this code match other other instances of this logic, you should put an str call around ws.

2017-06-26 17:38 UTC, jhillacre commented
@bitdancer, Added your requested changes in ec63c3c and 29f92f0.

Should I be rebasing this pull request to a single commit with the message of `bpo-30532: Fix email header value parser dropping folding white space in certain cases.`?

2017-06-26 21:37 UTC, bitdancer approved these changes

2017-06-26 21:41 UTC, merged

2017-06-26 21:43 UTC, bitdancer commented
Nope, it gets squashed during merge.  Now it needs backport to 3.6, and I think 3.5 is still open for backports.  You can do that (see devguide), or someone else will, since it isn't (yet) automated.

2017-07-05 20:15 UTC, jhillacre commented
added backport PRs #2591 #2592