bpo-39689: Do not use native packing for format "?" with standard size
python/cpython pull request #18969
Opened 2020-03-12 20:30 UTC by skrah

2020-03-12 20:41 UTC, skrah commented
This implements the current documentation somewhat pedantically:

```
The '?' conversion code corresponds to the _Bool type defined by C99. If this type is not available, it is simulated using a char. In standard mode, it is always represented by one byte.
```

We always have `C99` now, so native mode always uses `_Bool`.  When compiling with
`  -fsanitize=bool`, this should (and does) fail:

```python
>>> from struct import *
>>> unpack("?", b"\x02")
/home/stefan/cpython/Modules/_struct.c:487:12: runtime error: load of value 2, which is not a valid value for type '_Bool'
(False,)
```

This, however, should pass (and does after this patch):

```python
>>> 
unpack("<?", b"\x02")
(True,)
```

2020-03-17 15:13 UTC, encukou requested changes
The docs currently say:

> For the '?' format character, the return value is either True or False. When packing, the truth value of the argument object is used. Either 0 or 1 in the native or standard bool representation will be packed, and any non-zero value will be True when unpacking.

So, if we do want change that and expose UB to Python, the docs need to change. IMO, this will need a news entry as well.

The docs also currently talk about the characters `@=<>!` only affecting byte order, size, and alignment. Will that need to be expanded?

2020-03-24 12:58 UTC, encukou approved these changes

2020-03-24 13:01 UTC, merged

2020-03-25 13:31 UTC, miss-islington commented
Thanks @skrah for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-03-25 13:31 UTC, miss-islington commented
Thanks @skrah for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖