bpo-39879: update language reference to specify that dict is insertion-ordered.
python/cpython pull request #19027
Opened 2020-03-16 08:59 UTC by furkanonder

2020-03-16 09:08 UTC, hakancelikdev approved these changes

2020-03-16 09:16 UTC, hakancelikdev approved these changes

2020-03-16 09:38 UTC, isidentical reviewed
Looks great

2020-03-16 09:38 UTC, isidentical commented on Doc/reference/datamodel.rst
> +         Dictionary order is guaranteed to be insertion order. Note that updating a key
I feel like something is missing here, please ignore if this is the common usage (I'm not a native speaker). 
```suggestion
         The dictionary order is guaranteed to be the same as the insertion order. Note that updating a key
```

2020-03-16 09:38 UTC, isidentical commented on Doc/reference/datamodel.rst
> +         This behavior was an implementation detail of CPython from 3.6.
I think you should split this into its own version changed tag.

2020-03-17 22:02 UTC, zware requested changes
See also my comment on the issue.

2020-03-17 22:02 UTC, zware commented on Doc/reference/datamodel.rst
> +         The dictionary order is guaranteed to be the same as the insertion order. Note that updating a key
Please wrap lines at 80 characters, as [mentioned in the devguide](https://devguide.python.org/documenting/#use-of-whitespace).

2020-03-17 22:02 UTC, zware commented on Doc/reference/datamodel.rst
> +         This behavior was an implementation detail of CPython from 3.6.
I think this is fine being just a note in this block.

2020-03-17 23:15 UTC, furkanonder commented on Doc/reference/datamodel.rst
> +         The dictionary order is guaranteed to be the same as the insertion order. Note that updating a key
It's fixed.

2020-03-18 07:23 UTC, closed without merging

2020-03-26 20:01 UTC, furkanonder commented
It was combined with another pr. =>  https://github.com/python/cpython/pull/19006