bpo-40016: Clarify flag case in `re` module
python/cpython pull request #19078
Opened 2020-03-19 17:42 UTC by cool-RR

2020-03-21 23:58 UTC, terryjreedy requested changes
See issue.

2020-03-21 23:58 UTC, terryjreedy commented on Lib/re.py
> +               to the matching logic (details below).
I gave a different replacement on the issue and added more above the flag list.

2020-03-21 23:58 UTC, terryjreedy commented on Misc/NEWS.d/next/Library/2020-03-19-19-40-27.bpo-40016.JWtxqJ.rst
> +Replace misleading uppercase flags in documentation
This is wrong.  The uppercase module constants are used for call arguments.  
```suggestion
In re docstring, clarify the relationship between inline and argument compile flags.
```

2020-03-22 18:55 UTC, cool-RR commented
I didn't expect the Spanish Inquisition

2020-03-25 03:14 UTC, terryjreedy approved these changes
Looks good.  The maxOS failure details were not available, so let us see what happens with retest.  Otherwise, I think this ready to merge.
---
Added: The new Docs/Docs failure makes no sense.  Git fetch failed and runner received a shutdown signal.  Failed again on re-run.  This patch does not touch the regular doc.  Even if this text includes blurbs, the change since the previous run should not cause a failure.

2020-03-25 03:42 UTC, terryjreedy commented
@vstinner @pablogsal The Docs/Docs test is failing tonight with a git fetch failure.  The only 'doc change' is the news item.  Do either of you know what is going on?  May I merge anyway?

2020-03-25 18:44 UTC, merged

2020-03-25 18:44 UTC, miss-islington commented
Thanks @cool-RR for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖

2020-03-25 18:46 UTC, terryjreedy commented
The Travis checks passed, but this was not reported back here.