bpo-39966: Fix wrapped objects exception mockunittest
python/cpython pull request #19102
Opened 2020-03-21 12:53 UTC by amiremohamadi

the wrapped value of magic methods will be used **when present** or falls back to the default value.

2020-03-25 14:15 UTC, brandtbucher requested changes
Thanks @amiremohamadi, this looks good.

I just think we can simplify the tests and clean up the NEWS entry a bit:

2020-03-25 14:15 UTC, brandtbucher commented on Lib/unittest/test/testmock/testmock.py
> +        self.assertEqual(bool(obj1), False)
```suggestion
        self.assertFalse(klass1())
```

2020-03-25 14:15 UTC, brandtbucher commented on Lib/unittest/test/testmock/testmock.py
> +        self.assertEqual(bool(obj2), True)
```suggestion
        self.assertTrue(klass2())
```

2020-03-25 14:15 UTC, brandtbucher commented on Misc/NEWS.d/next/Library/2020-03-21-17-16-51.bpo-39966.3cRQmc.rst
> +object.
```suggestion
:mod:`unittest.mock` objects return a suitable default value when a magic
method is not defined on the mocked object.
```

2020-03-25 14:16 UTC, brandtbucher commented
The CI failure is a separate bug, and can be ignored.

2020-03-25 16:39 UTC, brandtbucher approved these changes
Awesome, thanks!

2020-08-06 16:12 UTC, tirkarthi commented
Closing this as the change was reverted. Please refer to the bug for discussion.

2020-08-06 16:12 UTC, closed without merging