bpo-40052: Fix alignment issue in PyVectorcall_Function()
python/cpython pull request #19133
Opened 2020-03-24 06:59 UTC by cryptomilk

```
In file included from /usr/include/python3.8/Python.h:147:
In file included from /usr/include/python3.8/abstract.h:837:
/usr/include/python3.8/cpython/abstract.h:91:11: error: cast from 'char *' to 'vectorcallfunc *'
(aka 'struct _object *(**)(struct _object *, struct _object *const *, unsigned long, struct _object *)')
increases required alignment from 1 to 8 [-Werror,-Wcast-align]

    ptr = (vectorcallfunc*)(((char *)callable) + offset);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

2020-03-24 06:59 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@cryptomilk

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-03-24 07:07 UTC, cryptomilk commented
I've added my github username to my account on bugs.python.org and signed the CA. However I think it might take some time till the system gets the update.

2020-04-18 18:10 UTC, pitrou requested changes

2020-04-18 18:10 UTC, pitrou commented on Include/cpython/abstract.h
> +    return *vc.ptr;
I don't think this is better. The correct, idiomatic solution is something like:
```c
    vectorcallfunc *ptr;
    memcpy(ptr, (char *) callable + offset, sizeof(ptr));
    return *ptr;
```

2020-04-18 18:10 UTC, pitrou commented on Objects/call.c
> +    vectorcallfunc func = *vc.ptr;
Same comment here.

2020-04-18 18:11 UTC, pitrou commented on Include/cpython/abstract.h
> +    return *vc.ptr;
(also, note that any decent compiler will optimize the memcpy call away)

2020-04-20 12:36 UTC, vstinner commented
In my experience, memcpy() is good solution for such problem.

2020-12-29 16:44 UTC, encukou commented
I've made a PR with the suggested `memcpy` at https://github.com/python/cpython/pull/23999

2020-12-29 17:17 UTC, pitrou commented
Closing in favour of #23999.

2020-12-29 17:17 UTC, closed without merging