bpo-39734: Deprecate the readinto() fallback path in _pickle.c
python/cpython pull request #19237
Opened 2020-03-30 22:10 UTC by ZackerySpytz

2020-03-30 22:11 UTC, ZackerySpytz commented
I think the warning message could be better.
This PR still needs a news entry (if it is accepted).

2020-04-18 10:53 UTC, pitrou submitted a review, later dismissed
Thank you for doing this. It looks good on the principle.

2020-04-18 10:53 UTC, pitrou commented on Lib/test/pickletester.py
> +        with warnings.catch_warnings():
It would be better to use `with self.assertWarns(DeprecationWarning)` here.

2022-11-09 14:05 UTC, iritkatriel commented on Lib/test/pickletester.py
> +            self._check_multiple_unpicklings(MinimalIO, seekable=False)
```suggestion
        with self.assertWarns(DeprecationWarning):
            self._check_multiple_unpicklings(MinimalIO, seekable=False)
```

2022-11-09 15:02 UTC, iritkatriel requested changes
With the change the test fails for the Python version unpickler: 

```
======================================================================
FAIL: test_multiple_unpicklings_minimal (test.test_pickle.PyPicklerUnpicklerObjectTests.test_multiple_unpicklings_minimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython/Lib/test/pickletester.py", line 3710, in test_multiple_unpicklings_minimal
    with self.assertWarns(DeprecationWarning):
AssertionError: DeprecationWarning not triggered
```

2026-05-05 17:37 UTC, StanFromIreland commented
Closing as stale, the requested changes have not been applied in four years.

2026-05-05 17:37 UTC, closed without merging