bpo-40148 Add PurePath.with_stem()
python/cpython pull request #19295
Opened 2020-04-02 01:31 UTC by timhoffm

Similar to `PurePath.with_name()` and `PurePath.with_suffix()` there should be a `PurePath.with_stem()`.

A common use case would be appending something before the suffix:
`path.with_stem(path.stem + '_v2')`

As of now this must be written more cumbersome as:
`path.with_name(path.stem + '_v2' + path.suffix)`

While the implementation is just a slight modification of `with_name`, I still think it's justified to add this method:

- It states the intent much cleaner than meddling `with_name()` and `suffix` manually together.
- From an API symmetry/completeness point of view, this is missing in the set of methods for modifying filenames.

https://bugs.python.org/issue40148

2020-04-16 22:53 UTC, pitrou reviewed
This looks generally good to me, just one question.

2020-04-16 22:53 UTC, pitrou commented on Doc/library/pathlib.rst
> +      >>> p.with_name('lib')
Surely you mean `with_stem` here?

2020-04-16 23:53 UTC, timhoffm commented on Doc/library/pathlib.rst
> +      >>> p.with_name('lib')
Yes, of course. Thanks. Fixed.

2020-04-17 18:16 UTC, pitrou requested changes
Looks like there is a final typo. Also, can you add a NEWS entry. You can do so either on the Web using [blurb-it](https://blurb-it.herokuapp.com/), or from the command line using [blurb](https://pypi.org/project/blurb/).

2020-04-17 18:16 UTC, pitrou commented on Doc/library/pathlib.rst
> +      >>> p.with_step('lib')
"stem" not "step"

2020-04-19 15:25 UTC, timhoffm commented
I have made the requested changes; please review again.

2020-04-19 15:29 UTC, pitrou approved these changes

2020-04-19 15:29 UTC, merged