Truncating file if opened in append mode.
python/cpython pull request #19337
Opened 2020-04-03 16:06 UTC by mzr

Related issue https://bugs.python.org/issue40105.

Implemented a test for this behaviour.

If we just `truncate`, then test fail for `Unseekable` file types. In current implementation that type of files cannot be opened in 'a' mode anyway, se we probably could make a check like that.

2020-04-03 16:06 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@mzr

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-09-26 10:00 UTC, taleinat requested changes
This looks good! Just a couple of minor comments regarding the test.

2020-09-26 10:00 UTC, taleinat commented on Lib/test/test_zipfile.py
> +        self.assertEqual(original_zip_size, os.path.getsize(TESTFN) + 1)
Testing for the precise size is too restrictive IMO. It would be better to just test that the size was reduced. That would also allow keeping the existing comments.

2020-09-26 10:00 UTC, taleinat commented on Lib/test/test_zipfile.py
> +        one_byte_shorter_comment =  original_comment[:-1]
IMO extracting these to variables makes the test code harder to understand rather than easier. I suggest undoing this change.

2020-09-28 16:20 UTC, mzr commented
I have made the requested changes; please review again.

2020-09-28 18:24 UTC, taleinat approved these changes
Looks good!

2020-09-28 18:53 UTC, merged

2020-09-28 18:53 UTC, miss-islington commented
Thanks @mzr for the PR, and @taleinat for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2020-09-28 19:56 UTC, miss-islington commented
Thanks @mzr for the PR, and @taleinat for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖