bpo-40192: Use thread_cputime for time.thread_time to improve resolution
python/cpython pull request #19381
Opened 2020-04-05 01:19 UTC by isidentical

2020-05-15 14:25 UTC, vstinner requested changes

2020-05-15 14:25 UTC, vstinner commented on Modules/timemodule.c
>  }
Please add a newline for readability.

2020-05-15 14:25 UTC, vstinner commented on Modules/timemodule.c
> +    thread_cputime_t tc;
Please add a comment explaining why thread_cputime() is preferred over standard clock_gettime(CLOCK_THREAD_CPUTIME_ID). Add "bpo-40192: " prefix, to add a reference to the issue.

2020-05-15 14:25 UTC, vstinner commented on Modules/timemodule.c
> +    *tp = _PyTime_FromNanoseconds(tc.stime);
That's wrong: you must return stime+utime, https://bugs.python.org/issue40192#msg368947

2020-05-15 15:37 UTC, vstinner commented on Modules/timemodule.c
> +    resolution of clock_gettime(CLOCK_THREAD_CPUTIME_ID) */
typo: preferred

```suggestion
    /* bpo-40192: On AIX, thread_cputime() is preferred: it has nanosecond
       resolution, whereas clock_gettime(CLOCK_THREAD_CPUTIME_ID)
       has a resolution of 10 ms. */
```

2020-05-15 15:37 UTC, vstinner commented on Doc/whatsnew/3.9.rst
> +``thread_cputime`` on AIX. (Contributed by Batuhan Taskaya in :issue:`40192`)
Oh, I proposed a different text, but it seems like my comment is lost :-( I propose:

```
On AIX, :func:`~time.thread_time` is now implemented with ``thread_cputime()``
which has nanosecond resolution, than than
``clock_gettime(CLOCK_THREAD_CPUTIME_ID)`` which has a resolution of 10 ms.
(Contributed by Batuhan Taskaya in :issue:`40192`)
```

Use the same text in the NEWS entry, but replace "(Contributed by Batuhan Taskaya in :issue:`40192`)" with "Patch by Batuhan Taskaya.".

2020-05-15 16:16 UTC, isidentical commented
I have made the requested changes; please review again

2020-05-15 16:17 UTC, isidentical commented
I have made the requested changes; please review again

2020-05-16 09:39 UTC, merged

2020-05-16 09:39 UTC, vstinner commented
Merged, thanks @isidentical!

2020-05-16 10:03 UTC, isidentical commented
Thank you for the review @vstinner!