Updated regex in pattern for finding cookie (rfc2616)
python/cpython pull request #19393
Opened 2020-04-06 16:04 UTC by lpopil

Updated regex for special case for "expires" attr in pattern for finding cookie if day of week is specified in deprecated format(rfc2616).

According to https://tools.ietf.org/html/rfc2616#section-3.3.1, clients and servers that parse the date value MUST accept all three formats (for compatibility with HTTP/1.0).
But current regular expression not match date in following format:
      Sunday, 06-Nov-94 08:49:37 GMT
      Sunday, 06-Nov-94 08:49:37 GMT

2020-04-06 16:04 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@lpopil

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-09-26 11:50 UTC, taleinat commented
I've confirmed that without this PR, the existing regular expression `_CookiePattern` doesn't properly recognize the string `'expires = Sunday, 06-Nov-94 08:49:37 GMT'`, and that this PR does indeed fix that.

2020-09-26 11:53 UTC, taleinat requested changes
Thanks for working on this!

This PR will needs new tests checking that this parsing works as expected on several examples of "expires" dates.

Also, this PR doesn't add support for the third date format described in RFC 2616 section 3.3.1, the "ANSI C's asctime() format", for example: `Sun Nov  6 08:49:37 1994`.

2022-04-19 10:50 UTC, AlexWaygood commented
Changes were requested by a core dev around a year and half ago, but have not been made. I am therefore closing this PR.

@lpopil, if you're still interested in working on this issue, feel free to open a new PR. Alternatively, ping me, and I'll happily reopen the PR. Thanks! 🙂

2022-04-19 10:50 UTC, closed without merging