bpo:19468 delete unnecessary modul control statement
python/cpython pull request #19424
Opened 2020-04-07 23:33 UTC by furkanonder

2020-04-08 02:02 UTC, eamanu approved these changes
LGTM

2020-04-08 02:05 UTC, eamanu commented
IMO news could be skipped.

2020-05-01 16:02 UTC, ericsnowcurrently approved these changes
LGTM

I expect there could possibly be some deep corner cases (via `_bootstrap._find_spec()` and `_bootstrap._exec()` that would change behavior here, but find it highly unlikely that, if such cases even exist, anyone relies on them. :smile:

2020-05-27 21:57 UTC, furkanonder commented
@brettcannon

2020-05-28 18:59 UTC, brettcannon commented
LGTM, although I think a news entry is still appropriate.

2020-05-28 19:00 UTC, brettcannon requested changes
Needs a news entry as it changes the semantics of the function.

2020-06-01 19:49 UTC, brettcannon commented
@furkanonder please read the instructions from the bot on how to signal you're ready for another review.

2020-06-01 19:57 UTC, furkanonder commented
> @furkanonder please read the instructions from the bot on how to signal you're ready for another review.

Sorry, I missed it. I have made the requested changes; please review again :)

2020-06-05 18:01 UTC, brettcannon commented on Misc/NEWS.d/next/Core and Builtins/2020-05-30-23-18-35.bpo-19468.S-TA7p.rst
> +Delete unnecessary instance check in importlib.reload().
```suggestion
Delete unnecessary instance check in importlib.reload().
Patch by Furkan Önder.
```

2020-06-05 18:02 UTC, brettcannon approved these changes

2020-06-05 19:56 UTC, miss-islington commented
@furkanonder: Status check is done, and it's a success ✅ .

2020-06-05 19:56 UTC, merged