bpo-40232: Update functions to use _PyThread_at_fork_reinit
python/cpython pull request #19450
Opened 2020-04-09 16:59 UTC by corona10

2020-04-09 18:08 UTC, corona10 commented
@vstinner Please take a look :)

2020-04-14 00:19 UTC, vstinner requested changes

2020-04-14 00:19 UTC, vstinner commented on Python/ceval.c
>      pending->lock = PyThread_allocate_lock();
With _PyThread_at_fork_reinit() call, ``pending->lock = PyThread_allocate_lock()`` is no longer needed!

2020-04-14 00:19 UTC, vstinner commented on Python/pystate.c
> +#ifdef HAVE_FORK
_PyRuntimeState_ReInitThreads() is only called by PyOS_AfterFork_Child(): so only if HAVE_FORK is defined.

I suggest to only defined _PyRuntimeState_ReInitThreads() if HAVE_FORK is defined. Said differently, put the whole function into #ifdef HAVE_FORK ... #endif. Here and where it's prototype in the header file (pycore_runtime.h).

Same remark for _PyImport_ReInitLock() and _PyEval_ReInitThreads().

2020-04-14 14:53 UTC, corona10 commented
I have made the requested changes; please review again

2020-04-14 15:08 UTC, vstinner commented on Include/internal/pycore_ceval.h
>      struct pyruntimestate *runtime);
I don't think that this function must be exported. Please make it private with:

```suggestion
extern void _PyEval_ReInitThreads(struct pyruntimestate *runtime);
```

2020-04-14 15:08 UTC, vstinner commented on Python/pystate.c
> +    if (_PyThread_at_fork_reinit(&runtime->interpreters.mutex) < 0) {
I suggest to add 3 local variables to store _PyThread_at_fork_reinit() result and only check the result after `PyMem_SetAllocator(PYMEM_DOMAIN_RAW, &old_alloc);` call. Just to limit code between the two PyMem calls.

2020-04-14 15:08 UTC, vstinner commented on Python/ceval.c
> +
nitpick: remove this empty line. Same remark for the 2 other functions :-p

2020-04-14 16:03 UTC, vstinner approved these changes
LGTM. You can merge it. Thanks, the updated code now looks better! It's good to no longer define the 3 functions on Windows where they make no sense.

2020-04-14 16:16 UTC, merged