bpo-40273: Reversible mappingproxy
python/cpython pull request #19513
Opened 2020-04-14 15:56 UTC by ZackerySpytz

2020-04-14 15:57 UTC, ZackerySpytz commented
The tests are based on `test_reversed()` in test_dict.py.

2020-04-14 16:05 UTC, brandtbucher requested changes
Looks good! One tiny suggestion for the test:

2020-04-14 16:05 UTC, brandtbucher commented on Lib/test/test_types.py
> +        r = reversed(self.mappingproxy(d))
I think creating the proxy *before* deleting the element makes sure that this is indeed an updating view:

```suggestion
        mp = self.mappingproxy(d)
        del d['foo']
        r = reversed(mp)
```

2020-04-14 16:12 UTC, brandtbucher commented
This should probably also get docs, similar to the ones for `dict`:

```rst
.. describe:: reversed(proxy)

   Return a reversed iterator over the keys of the underlying mapping.

   .. versionadded:: 3.9
```

2020-04-14 20:07 UTC, rhettinger commented on Misc/NEWS.d/next/Library/2020-04-14-09-54-35.bpo-40273.IN73Ks.rst
> +:class:`types.MappingProxyType` is now reversible.
This needs at versionchanged note in the main docs as well.

2020-05-06 17:34 UTC, brandtbucher approved these changes
Looks good, thanks!

2020-05-08 05:25 UTC, merged