bpo-32494: Add gdbm.count()
python/cpython pull request #19569
Opened 2020-04-17 14:30 UTC by ZackerySpytz

gdbm_count() was added in GDBM 1.11.

2020-04-18 10:33 UTC, pitrou requested changes
Thank you. This looks mostly good, just one comment.

2020-04-18 10:33 UTC, pitrou commented on Modules/_gdbmmodule.c
> +    if (gdbm_count(self->di_dbm, &count) == -1) {
Need to set `errno = 0` before this.

2020-04-18 10:36 UTC, corona10 reviewed
@ZackerySpytz  @pitrou 

Can we just replace the logic of `dbm_length` to use  `gdbm_count` when the version is available?

https://github.com/python/cpython/blob/1b55b65638254aa78b005fbf0b71fb02499f1852/Modules/_gdbmmodule.c#L98

if possible, we don't have to export a new method.

2020-05-01 12:16 UTC, pitrou commented
Superseded by PR #19814. Closing.

2020-05-01 12:16 UTC, closed without merging