bpo-40383: Reprs of subclasses of weakref now contain actual type name
python/cpython pull request #19707
Opened 2020-04-25 03:12 UTC by OhBonsai

Reprs of subclasses of weakref now contain actual type name

2020-04-25 08:39 UTC, corona10 requested changes

2020-04-25 08:39 UTC, corona10 commented on Objects/weakrefobject.c
> +                                    _PyType_Name(Py_TYPE(self)));
```suggestion
                                    _PyType_Name(Py_TYPE(self)), self);
```

2020-04-25 08:42 UTC, corona10 requested changes
Thanks for the contribution, you might add NEWS.d for this PR.
https://devguide.python.org/committing/#what-s-new-and-news-entries

And @serhiy-storchaka will decide that this PR would be accepted.

2020-04-25 09:47 UTC, OhBonsai commented
I have made the requested changes; please review again

@serhiy-storchaka

2020-04-25 11:38 UTC, OhBonsai commented
Thank you for reminding me. I See

2020-04-27 15:32 UTC, corona10 approved these changes
I am okay with the change, but let's wait @serhiy-storchaka 's review!

2020-04-29 10:34 UTC, OhBonsai commented
> I am okay with the change, but let's wait @serhiy-storchaka 's review!
Haha, This's my first time contributing to c project... Almost first time contributing to open source project, Thank you for you replay and review

2020-06-12 10:02 UTC, OhBonsai commented
@serhiy-storchaka TBR plz 😄

2020-07-16 13:21 UTC, OhBonsai commented
@serhiy-storchaka Please take a look in your free time, thanks~

2021-06-27 10:31 UTC, corona10 requested changes

2021-06-27 10:31 UTC, corona10 commented on Objects/weakrefobject.c
> +
```suggestion
```

2021-06-27 10:31 UTC, corona10 commented on Objects/weakrefobject.c
> +                name);
dedent please

2021-06-27 10:31 UTC, corona10 commented on Objects/weakrefobject.c
> +                obj);
dedent please

2024-01-05 09:54 UTC, erlend-aasland commented
@OhBonsai, can you please resolve the merge conflicts and update the PR?

2026-05-03 17:01 UTC, StanFromIreland commented
Hello! I'm sorry but I'm closing this PR as it is stale and has requested changes that have not been addressed in quite some time.

2026-05-03 17:01 UTC, closed without merging