bpo-27867: Add a porting guide for PySlice_GetIndicesEx().
python/cpython pull request #1973
Opened 2017-06-06 17:41 UTC by serhiy-storchaka

2017-06-09 13:49 UTC, marco-buttu commented on Doc/c-api/slice.rst
> +      This function considered not safe for resizable sequences.  Replace its invocation ::
Is there a typo?  Maybe *is considered*?  Also there is a whitespace before `::`.  I do not know if it is intentional, considering you apply the  `::` without a whitespace in the sentence below

2017-06-09 14:47 UTC, serhiy-storchaka commented on Doc/c-api/slice.rst
> +      This function considered not safe for resizable sequences.  Replace its invocation ::
Thank you. Yes, this is a typo. A whitespace before `::` is intentional.

2017-09-21 15:07 UTC, cryvate requested changes
The manual change looks good to me (could improve still), the what's new blurb is a tad confusing.

2017-09-21 15:07 UTC, cryvate commented on Doc/c-api/slice.rst
> +      This function is considered not safe for resizable sequences.  Replace its invocation ::
I thought about "is considered not" v.s. "is not considered" for a while, but actually the former/current version as its semantics seem more appropriate

2017-09-21 15:07 UTC, cryvate commented on Doc/c-api/slice.rst
> +      with using functions :c:func:`PySlice_Unpack` and :c:func:`PySlice_AdjustIndices`::
You want to link to these functions here? It makes the sentence a bit of a roller coaster. 

Could it be possible to move the "using ..." to after the code block? so:

with

if (Py [...]

using functions :c: ...

2017-09-21 15:07 UTC, cryvate commented on Doc/c-api/slice.rst
> +      with using functions :c:func:`PySlice_Unpack` and :c:func:`PySlice_AdjustIndices`::
Or restructure it, so that the whole block is

"This function is considered not safe for resizable sequences. Its invocation should be replaced by a combination of :c:... and :c:... where

if (PySlice_Get[...]

is replaced by

if (PySlice_Unpack..."

2017-09-21 15:07 UTC, cryvate commented on Doc/whatsnew/3.7.rst
> +* Function :c:func:`PySlice_GetIndicesEx` is considered not safe for
"Function" -> "The function"

2017-09-21 15:07 UTC, cryvate commented on Doc/whatsnew/3.7.rst
> +  if the slice indices are not instances of :class:`int`, but objects that
"[...] instances of :class:`int`" seems like an unended thoought. The double but in a row ("but if ..", "but objects") is quite confusing. Consider splitting into 2 or more sentences?

2017-09-21 19:10 UTC, serhiy-storchaka commented on Doc/c-api/slice.rst
> +      with using functions :c:func:`PySlice_Unpack` and :c:func:`PySlice_AdjustIndices`::
Thank you, I'll restructure it.

2017-09-21 19:12 UTC, serhiy-storchaka commented
Thank you @cryvate for your review.

2017-09-23 12:33 UTC, cryvate commented
No problem @serhiy-storchaka . Really like what you've changed it to.

2017-10-04 07:56 UTC, dalcinl commented on Doc/c-api/slice.rst
> +         if (PySlice_Unpack(slice, length, &start, &stop, &step) < 0) {
Remove `length` from argument list.

2017-10-08 09:53 UTC, merged