bpo-40409: Updates urlsplit scheme validation logic
python/cpython pull request #19741
Opened 2020-04-27 20:21 UTC by sgg

https://bugs.python.org/issue40409

* Checks that the first character of a scheme is a letter.
* Uses frozensets for scheme char validation instead of a string as the
  use of a string led to linear scanning when parsing
* Adds a unit test

Assuming this change is appropriate it should be easy to backport to older
versions of Python.

It is worth noting that this *does not* attempt to fix any other potential
parsing issues. While testing I did notice that `urlsplit` returns "paths"
that do not look valid at a glance both before AND after this change
(e.g. `+git+ssh:///+git+ssh://git@github.com/user/project.git"`).

2020-04-27 20:21 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@sgg

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-06-13 14:48 UTC, jacobtylerwalls commented
Hi @sgg, thanks for this. Strolled by because I was also working in `urllib.parse` recently. I bet you could increase the likelihood of getting a core review by creating a NEWS entry, since this is a behavior change. I found [blurb](https://devguide.python.org/?highlight=blurb#quick-reference) very easy to use for this purpose.

2022-05-16 11:34 UTC, thedrow requested changes

2022-05-16 11:34 UTC, thedrow commented on Lib/test/test_urlparse.py
> +            self.assertEqual(split_url.scheme, "")
I think these cases should raise a ValueError instead.

2022-11-27 19:38 UTC, iritkatriel requested changes
This has a merge conflict now. Also missing a news file, and there are unanswered review comments.

2024-04-28 05:06 UTC, vadmium commented
Probably close this since commit 439b9cfaf430 looks like it does the same thing

2026-05-05 17:37 UTC, StanFromIreland commented
Closing as stale, the requested changes have not been applied in four years.

2026-05-05 17:37 UTC, closed without merging