bpo-40394 - difflib.SequenceMatched.find_longest_match default args
python/cpython pull request #19742
Opened 2020-04-27 21:52 UTC by lrjball

Added default args to find_longest_match, as well as related tests

2020-04-27 21:52 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@lrjball

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-04-27 21:56 UTC, lrjball commented
CLA signed :+1:

2020-04-28 00:55 UTC, tim-one requested changes
Looks good so far!  Needs more stuff:

- Add your name to `Misc/ACKS`
- Docs need to be updated to match, and with a `versionchanged` note.
- Needs a `NEWS` entry.

2020-04-28 00:55 UTC, tim-one commented on Lib/test/test_difflib.py
> +        self.assertEqual(match.size, 6)
Would be good to also test a mix of explicit and default args.  For example, like this test, but with `alo=2` and `bhi=6`.

2020-04-28 19:09 UTC, lrjball commented
I've made these updates, thanks. Worth mentioning as well that `None` is a valid param for `ahi` and `bhi` now, but will not work for `alo` and `blo` which still error if they aren't ints. Not sure if that should be documented anywhere or if it is fine how it is. 

I have made the requested changes; please review again

2020-04-29 00:06 UTC, tim-one requested changes
Nice!  I made one more code suggestion, which you should be able to commit directly from the comment.  Or argue about it, but I don't suggest that :wink:

2020-04-29 00:06 UTC, tim-one commented on Lib/difflib.py
> +        bhi = len(b) if bhi is None else bhi
```suggestion
        if ahi is None:
            ahi = len(a)
        if bhi is None:
            bhi = len(b)
```
It's a small point, but this is easier to follow the suggested way - which is the way similar defaults are resolved throughout the code base.  The "extra" lines don't matter at all.  What does matter is that it's visually obvious at once that "`is None`" is the _only_ thing going on.

2020-04-29 00:08 UTC, tim-one commented
> `None` is a valid param for `ahi` and `bhi` now, but will not work for `alo` and `blo` which still error if they aren't ints. Not sure if that should be documented anywhere or if it is fine how it is.

It's fine.  Nobody is going to pass an explicit `None` for any of these, and nothing in the docs or function signature suggest that passing `None` for `alo` or `blo` would make any sense.

2020-04-29 10:08 UTC, lrjball commented
Thanks for the suggestion, I have added it in.

I have made the requested changes; please review again

2020-04-30 03:41 UTC, tim-one approved these changes
All good - thank you, Lewis!  I'll merge this now :smiley:

2020-04-30 03:42 UTC, merged