bpo-29587: Enable implicit exception chaining with gen.throw()
python/cpython pull request #19823
Opened 2020-04-30 21:43 UTC by cjerdonek

This is a new version of PR #19811 to sort out the buildbot failures.

It enables implicit exception chaining when calling `generator.throw(exc)` by setting `exc.__context__`.

2020-04-30 22:08 UTC, 1st1 commented on Objects/genobject.c
> +        _PyErr_ChainExceptions(gen->gi_exc_state.exc_type, gen->gi_exc_state.exc_value, gen->gi_exc_state.exc_traceback);
You must wrap lines at 79 characters.

2020-04-30 22:13 UTC, vstinner requested changes
test_unittest still crash on this PR. I tested on Linux (Fedora 32).

```
$ make clean
$ make
$ ./python -m test -v test_unittest 
(...)
test_patch_nested_autospec_repr (unittest.test.testmock.testpatch.PatchTest) ... ok
test_patch_object_keyword_args (unittest.test.testmock.testpatch.PatchTest) ... ok
test_patch_object_with_spec_as_boolean (unittest.test.testmock.testpatch.PatchTest) ... ok
test_patch_orderdict (unittest.test.testmock.testpatch.PatchTest) ... ok
test_patch_propagates_exc_on_exit (unittest.test.testmock.testpatch.PatchTest) ... Fatal Python error: Segmentation fault

Current thread 0x00007f886bd1c740 (most recent call first):
  File "/home/vstinner/python/master/Lib/unittest/mock.py", line 1524 in __exit__
  File "/home/vstinner/python/master/Lib/unittest/test/testmock/testpatch.py", line 1673 in __exit__
  File "/home/vstinner/python/master/Lib/contextlib.py", line 498 in __exit__
  File "/home/vstinner/python/master/Lib/unittest/mock.py", line 1323 in decoration_helper
  File "/home/vstinner/python/master/Lib/contextlib.py", line 135 in __exit__
  File "/home/vstinner/python/master/Lib/unittest/mock.py", line 1337 in patched
  File "/home/vstinner/python/master/Lib/unittest/case.py", line 201 in handle
  File "/home/vstinner/python/master/Lib/unittest/case.py", line 733 in assertRaises
  File "/home/vstinner/python/master/Lib/unittest/test/testmock/testpatch.py", line 1692 in test_patch_propagates_exc_on_exit
(...)
```

2020-04-30 22:26 UTC, cjerdonek commented
Is there a way to mark this PR as "don't merge" for now? This is the same PR as before, so it has the same issue. The Azure CI job seems not to be running, which is what exhibited the failure before.

> test_unittest still crash on this PR. I tested on Linux (Fedora 32).

Yes, this is the same failure as before. Everything passes locally on my Mac, so it will take me more time to look into this.

2020-04-30 22:51 UTC, vstinner commented
> Is there a way to mark this PR as "don't merge" for now?

Hum, I wasn't sure, so I did the 3 tricks that I know:

* Add "do no merge label"
* Add "[WIP]" in the PR title
* Convert the PR as a draft

It seems like only the conversion to a draft technically prevents someone to merge the PR my mistake.

2020-04-30 22:52 UTC, cjerdonek commented
Looks like that will cover it. ;)

2020-05-01 08:42 UTC, cjerdonek commented
Okay, I believe my latest changes fix the buildbot failures from before.

Also, for future reference, below is a script I came up with that isolates the behavior difference between Mac and Fedora, with my prior version of the PR:

```python
import re
import sys
import traceback


def f():
    exc, exc_value, tb = sys.exc_info()
    print(f'CLEARING FRAME: {tb.tb_frame!r}')
    tb.tb_frame.clear()

def g():
    # Uncommenting this line caused the tb_frame.clear() line above
    # to crash on Fedora 32, but not on a Mac.
    data = re.compile('xxx')

    try:
        yield
    except Exception:
        f()

gen = g()
gen.send(None)
gen.throw(ValueError)
```

Maybe this suggests an issue elsewhere in Python's code base.

Should this PR also get a What's New?

2020-05-01 08:43 UTC, cjerdonek commented on Objects/genobject.c
> +        _PyErr_ChainExceptions(gen->gi_exc_state.exc_type, gen->gi_exc_state.exc_value, gen->gi_exc_state.exc_traceback);
Done.

2020-05-01 08:47 UTC, cjerdonek commented
I have made the requested changes; please review again.

2020-05-01 12:45 UTC, vstinner approved these changes
LGTM. "./python -m test -j0 -r" does no longer crash on my Fedora.

I understood that passing NULL value to _PyErr_ChainExceptions() created the bug? Maybe add an assertion to prevent the situation to happen again?

2020-05-01 13:33 UTC, cjerdonek commented
Thank you.

Regarding an assertion, the thing is that it looks like `_PyErr_ChainExceptions()` is designed to accept a `NULL` value. So maybe in the future it can be made to work. (That's why I added an `XXX` comment.) So I wouldn't want to add an assertion making it seem like it always has to be like that. It could just something about how things are set up right now that was causing the crash.

Would you still like me to add an assertion and/or perhaps a code comment explaining this possibility?

2020-05-02 01:14 UTC, merged

2020-05-03 07:41 UTC, cjerdonek commented
For future reference, I was able to remove the NULL check in a later PR (#19877): https://github.com/python/cpython/commit/21893fbb74e8fde2931fbed9b511e2a41362b1ab