Fix for issue bpo-30566
python/cpython pull request #1986
Opened 2017-06-07 16:18 UTC by vikhegde

A bug in the punycode codec raises an IndexError when we attempt to decode the string "xn--w&". The fix is straightforward and obvious one-liner. Bug number:  bpo-30566

2017-06-07 17:03 UTC, zware commented
Could you add a test for this?

2017-06-07 18:48 UTC, vikhegde commented
I have added a test case to the punycode Test-suite.

2017-11-01 10:12 UTC, berkerpeksag requested changes
Please also add a NEWS file. See https://devguide.python.org/committing/#what-s-new-and-news-entries for details.

2017-11-01 10:12 UTC, berkerpeksag commented on Lib/test/test_codecs.py
> +        for byt, exception in punycode_decode_exceptions:
I'd rename `byt` to `puny`.

2017-11-01 10:12 UTC, berkerpeksag commented on Lib/test/test_codecs.py
> +punycode_decode_exceptions = [
I'd rename this to `invalid_punycode_testcases`.

2017-11-01 10:12 UTC, berkerpeksag commented on Lib/test/test_codecs.py
> +    # Make sure punycode codec raises the right kind of exception
Style nit: We can drop this comment.

2017-11-01 10:12 UTC, berkerpeksag commented on Lib/test/test_codecs.py
> +            with self.assertRaises(exception):
We couls use `self.subTest()` to make test failure messages clearer.

2019-01-10 16:06 UTC, vstinner commented
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

2019-09-11 10:41 UTC, zware commented
@vikhegde Would you like to move this forward by implementing @berkerpeksag's suggestions?

2020-01-12 13:57 UTC, csabella commented
This pull request seems to have been abandoned, so I'm going to close it.  It can reopened if the original author is interested in working on it again or a new pull request can be created to replace it.  Thank you!

2020-01-12 13:57 UTC, closed without merging