bpo-40426: Revert reporting of invalid string prefixes
python/cpython pull request #19888
Opened 2020-05-03 20:30 UTC by lysnikolaou

Due to backwards compatibility concerns, that keywords immediately
followed by a string without whitespace between them
(like in `bg="#d00" if clear else"#fca"`) will fail to parse,
PR19476 has to be reverted.

2020-05-03 20:43 UTC, gvanrossum approved these changes

2020-05-03 20:45 UTC, gvanrossum requested changes
Please also delete the NEWS item of the reverted change (Misc/NEWS.d/next/Core and Builtins/2020-04-11-17-52-03.bpo-40246.vXPze5.rst).

2020-05-03 21:00 UTC, lysnikolaou commented
Can't find the news file. There is not file with `bpo-40246` on master according to Github and to my local clone.

2020-05-03 22:11 UTC, hroncok commented
That news file has already been merged to the changelog when 3.9.0a6 was released. I think this should explicitly add a new entry about the revert.

2020-05-03 23:31 UTC, hroncok commented on Misc/NEWS.d/next/Core and Builtins/2020-05-03-23-28-11.bpo-40246.c1D7x8.rst
> +Reporting a specialised error message for invalid string prefixes, which was introduced in #19888, is being reverted due to backwards compatibility concerns for strings that immediately follow a rese
19888 is this one

2020-05-03 23:36 UTC, lysnikolaou commented on Misc/NEWS.d/next/Core and Builtins/2020-05-03-23-28-11.bpo-40246.c1D7x8.rst
> +Reporting a specialised error message for invalid string prefixes, which was introduced in #19888, is being reverted due to backwards compatibility concerns for strings that immediately follow a rese
Whoops. Thanks for the catch!

2020-05-03 23:38 UTC, lysnikolaou commented
I have made the requested changes; please review again

2020-05-04 00:21 UTC, pablogsal commented on Misc/NEWS.d/next/Core and Builtins/2020-05-03-23-28-11.bpo-40246.c1D7x8.rst
> +Reporting a specialised error message for invalid string prefixes, which was introduced in GH-19476, is being reverted due to backwards compatibility concerns for strings that immediately follow a re
Please, mention the bpo number instead of the PR number (GH-19476)

2020-05-04 00:22 UTC, pablogsal commented on Misc/NEWS.d/next/Core and Builtins/2020-05-03-23-28-11.bpo-40246.c1D7x8.rst
> +Reporting a specialised error message for invalid string prefixes, which was introduced in GH-19476, is being reverted due to backwards compatibility concerns for strings that immediately follow a re
```suggestion
Reporting a specialised error message for invalid string prefixes, which was introduced in GH-19476, is being reverted due to backwards compatibility concerns for strings that immediately follow a reserved keyword without whitespace between them, making constructs like `bg="#d00" if clear else"#fca"` invalid.
```

2020-05-04 04:31 UTC, gvanrossum commented on Misc/NEWS.d/next/Core and Builtins/2020-05-03-23-28-11.bpo-40246.c1D7x8.rst
> +Reporting a specialised error message for invalid string prefixes, which was introduced in GH-19476, is being reverted due to backwards compatibility concerns for strings that immediately follow a re
Honestly I like @lysnikolaou's version better.

2020-05-04 04:31 UTC, gvanrossum approved these changes

2020-05-04 10:23 UTC, pablogsal commented on Misc/NEWS.d/next/Core and Builtins/2020-05-03-23-28-11.bpo-40246.c1D7x8.rst
> +Reporting a specialised error message for invalid string prefixes, which was introduced in GH-19476, is being reverted due to backwards compatibility concerns for strings that immediately follow a re
Fair enough, let's skip my suggestion then.

2020-05-04 10:46 UTC, hroncok commented
I've backported this PR t Fedora's build of 3.9.0a6 and I still see:

```
  File "/usr/lib/python3.9/site-packages/dnf/comps.py", line 111
    return'.'.join(lcl)
         ^
SyntaxError: invalid string prefix
```

I will double check the patch was actually applied.

2020-05-04 10:51 UTC, hroncok commented
It was a cache issue, it used an older, unpatched build. Sorry for the noise.

In fact, this PR makes the problem go away, as ecpected.

2020-05-04 10:52 UTC, lysnikolaou commented
No `SyntaxError` when building this branch locally.

```
╰─ ./python.exe
Python 3.9.0a6+ (heads/master-dirty:64224a4727, May  3 2020, 23:23:39)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def f():
...     return'.'.join(lcl)
...
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
NameError: name 'lcl' is not defined
```

2020-05-04 11:02 UTC, pablogsal commented on Misc/NEWS.d/next/Core and Builtins/2020-05-03-23-28-11.bpo-40246.c1D7x8.rst
> +Reporting a specialised error message for invalid string prefixes, which was introduced in GH-19476, is being reverted due to backwards compatibility concerns for strings that immediately follow a re
```suggestion
Reporting a specialised error message for invalid string prefixes, which was introduced in :issue:`40246`, is being reverted due to backwards compatibility concerns for strings that immediately follow a reserved keyword without whitespace between them. Constructs like `bg="#d00" if clear else"#fca"` were failing to parse, which is not an acceptable breakage on such short notice.
```

2020-05-04 11:12 UTC, pablogsal approved these changes

2020-05-04 11:32 UTC, merged