bpo-13097: fix segfault in ctypes callback invocation
python/cpython pull request #19914
Opened 2020-05-05 05:06 UTC by swgillespie

The ctypes module allocates arguments on the stack in
`ctypes_callproc` using alloca, which is problematic
when large numbers of parameters are passed. Instead
of crashing, this commit raises an ArgumentError if
more than 1024 parameters are passed.

2020-05-05 05:06 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@swgillespie

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-05-06 16:41 UTC, vstinner requested changes
Hum. This approach makes sense.

But. There is another way. If `sizeof(struct argument) * argcount` is larger than 4 KB, we can allocate memory on the heap, instead of using alloca().

2020-05-06 16:41 UTC, vstinner commented on Lib/ctypes/test/test_callbacks.py
> +            return (1, "abc", None)
```suggestion
        def func(*args):
            return len(args)
```

2020-05-06 16:41 UTC, vstinner commented on Lib/ctypes/test/test_callbacks.py
> +        nargs = 2 ** 20
```suggestion
        CTYPES_MAX_ARGCOUNT = 1024
```

2020-05-06 16:41 UTC, vstinner commented on Lib/ctypes/test/test_callbacks.py
> +            cb(*(1,) * nargs)
```suggestion
        args1 = (None,) * CTYPES_MAX_ARGCOUNT
        self.assertEqual(cb(*args1), CTYPES_MAX_ARGCOUNT)
        
        args2 = (None,) * (CTYPES_MAX_ARGCOUNT + 1)
        with self.assertRaises(ArgumentError):
            cb(*args2)
```

2020-05-06 16:41 UTC, vstinner commented on Modules/_ctypes/callproc.c
> +        PyErr_SetString(PyExc_ArgError, "too many arguments");
```suggestion
        PyErr_Format(PyExc_ArgError, "too many arguments (%zi), maximum is %i",
                     argcount, CTYPES_MAX_ARGCOUNT);
```

2020-05-06 16:41 UTC, vstinner commented on Modules/_ctypes/callproc.c
> + * Max number of arguments _ctypes_callproc will accept.
Please add "bpo-13097: " and explain that the limit is for alloca() call in _ctypes_callproc().

2020-05-06 17:34 UTC, swgillespie commented
Thanks for the review!

> But. There is another way. If sizeof(struct argument) * argcount is larger than 4 KB, we can allocate memory on the heap, instead of using alloca().

It's true, but I also don't think there's ever a legitimate reason for a callback to have this many arguments. There's some additional complexity involved when freeing the argument buffer in this case, since we'd need to only free it when `argcount` is greater than the limit. I'm happy to do that, but I personally didn't think the complexity was worth it for such a niche use case.

2020-05-06 17:43 UTC, swgillespie commented
I have made the requested changes; please review again

2020-05-22 19:05 UTC, swgillespie commented
Is this PR OK to merge? @vstinner

2020-05-27 15:20 UTC, vstinner approved these changes
LGTM.

I tried to rewrite _ctypes_callproc() to use PyMem_Malloc() instead of alloca(), but it's quite complicated. There are 3 arrays with a length of argcount items: args, avalues, atypes. Moreover, resbuf is also allocated with alloca(). When using PyMem_Malloc(), error handling is much more complicated.

I also tried to restrict the overall usage of stack memory to 4096 bytes (size of one page on x86), but users would be surprised by CTYPES_MAX_ARGCOUNT value.

I would say that raising an exception is better than crashing for a lot of arguments. If someone is blocked by this new limitation, in that case we can revisit the PyMem_Malloc() idea.

2020-05-27 15:22 UTC, merged

2020-05-27 15:22 UTC, miss-islington commented
Thanks @swgillespie for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖

2020-05-27 15:23 UTC, miss-islington commented
Thanks @swgillespie for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2020-05-27 15:23 UTC, miss-islington commented
Thanks @swgillespie for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖