bpo-40516: Silence GCC 9 warnings on MacOS Catalina
python/cpython pull request #19925
Opened 2020-05-05 13:35 UTC by remilapeyre

2020-05-05 13:43 UTC, corona10 reviewed
I don't think that this is good way to fix it.

2020-05-05 13:46 UTC, remilapeyre commented
> I don't think that this is good way to fix it.

I'm not sure what to do here. Is GCC 9 on Catalina supposed to be supported? I tried it because I'm having issues with debug symbols with the latest version of clang and GDB but should I just build gcc 10?

2020-05-05 13:47 UTC, corona10 requested changes
See the similar discussion about this issue.
https://github.com/python/cpython/pull/13306#issuecomment-618239942

2020-05-06 01:25 UTC, ned-deily commented
My question is do we know if these are legitimate warnings?  If so, does the current Apple-provided clang  give them in an otherwise identical build environment and configure options?  If not, why not :) ?  Also does gcc 10 report the same errors?  Do these errors show up in other BSD-based systems, like FreeBSD?   BTW @remilapeyre. you mentioned problems using gdb with clang.  Have you tried clang's native debugger, lldb?

2020-05-06 12:12 UTC, remilapeyre commented
Hi, thanks for your feedback, I had not found https://github.com/python/cpython/pull/13306 sorry about that. 

For more context about this issue, I'm usually using clang and lldb but I'm currently trying to diagnose a segmentation fault during SSL handshakes. To understand what's going on I would like to use the gdb support (https://devguide.python.org/gdb/). Using gdb on a binary built with clang used to work well but broke recently, I opened an issue at https://sourceware.org/bugzilla/show_bug.cgi?id=25850.

I would actually be quite happy to continue using lldb as using gdb on MacOS is cumbersome since a certificate needs to be generated and gdb needs to signed with it but as as I know there is no way to get the same integration with the debugger.

> My question is do we know if these are legitimate warnings? If so, does the current Apple-provided clang give them in an otherwise identical build environment and configure options? If not, why not :) ? Do these errors show up in other BSD-based systems, like FreeBSD?

The one in posix is specific to a quirk of MacOS 10.13, maybe clang knows about it? I did not check if the one in nis is present on BSD.

> Also does gcc 10 report the same errors?

I did not try as I did not know it existed, it does not appear at https://gcc.gnu.org/releases.html.

My main goal here is to be able to use https://devguide.python.org/gdb/ on MacOS, I see multiple way to do that:

- build with GCC 9 and the gdb support
- build with GCC 10 and the gdb support
- create the equivalent `python-gdb.py` for lldb so that I can avoid using GCC and GDB

Maybe the the third one is the best as a Python / LLDB could be useful to others?

2020-10-17 20:42 UTC, taleinat commented
Ping, @ned-deily, @corona10?

2020-10-19 20:52 UTC, ned-deily commented
> Ping, @ned-deily, @corona10?

I don't have further suggestions as it's not really my area of expertise.  Perhaps @ronaldoussoren might.

2020-10-22 14:47 UTC, remilapeyre commented
For what it's worth I started working on a `python-lldb.py` script that would make it possible to use the same commands available in GDB. I don't have experience with the Python bindings of LLDB so it's taking me quite some time but I already have some commands working.

2020-10-23 09:35 UTC, ronaldoussoren requested changes
Are the nismodule.c warnings also present on Linux systems with GCC 9? If so, adding warning suppression seems like a sane thing to do.

2020-10-23 09:35 UTC, ronaldoussoren commented on Modules/nismodule.c
> +    #pragma GCC diagnostic ignored "-Wcast-function-type"
This needs a preprocessor guard to ensure the pragma is only used with compatible compilers.

2020-10-23 09:35 UTC, ronaldoussoren commented on Modules/nismodule.c
> +    #pragma GCC diagnostic pop
Likewise

2020-10-23 09:35 UTC, ronaldoussoren commented on Modules/posixmodule.c
>       * This is for Mac OS X 10.3, which doesn't have lchown.
PR #22855  will fix the warnings in posixmodule.c (as a side effect of more interesting changes).

2022-04-11 21:16 UTC, hugovk commented
Note the nis module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

2022-04-12 09:32 UTC, AlexWaygood commented
This PR has been "awaiting changes" for over a year, and now has a merge conflict. I am therefore closing this PR.

@remilapeyre, if you're still interested in working on this issue, feel free to ping me and I'll happily reopen the PR. However, do note that the `nis` module is now deprecated, as @hugovk says, so it will probably be low priority for the core dev team to review.

2022-04-12 09:32 UTC, closed without merging