Revert "bpo-36543: Remove the xml.etree.cElementTree module."
python/cpython pull request #19920
Opened 2020-05-05 11:51 UTC by serhiy-storchaka

Reverts python/cpython#19108

2020-05-05 11:55 UTC, scoder commented
Thanks Serhiy. Was there a News entry and docs update that went with the removal? Those would then need to be reverted as well.

2020-05-05 12:20 UTC, scoder approved these changes

2020-05-15 17:43 UTC, tiran requested changes
I'd still prefer to land my PR #19921 and mark the module for removal in 3.10.

2020-05-15 17:43 UTC, tiran commented on Misc/NEWS.d/3.9.0a1.rst
> -ElementTree.getiterator() and the xml.etree.cElementTree module.
Don't remove news entries from published releases. For users, packagers and distributions it's important to know how the Python has changed between alpha releases.

2020-05-15 18:34 UTC, serhiy-storchaka commented
I messed this PR. Recreated as #20117.

2020-05-15 18:34 UTC, closed without merging