bpo-40544: Set the validate field in logging Formatter with fileConfig
python/cpython pull request #19991
Opened 2020-05-08 08:07 UTC by mirii1994

https://bugs.python.org/issue40544
This PR fixes python 3.8 bug that caused because of the add of the `validate` param (default: True) in `logging.Formatter`, it causing it to throws ValueError exception if the `format` param is not one of the 3 styles.
There was no way to set `validate` field when using `logging.config.fileConfig`, which breaks the code to users who want to upgrade to 3.8.

2020-05-08 08:07 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@mirii1994

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-05-10 06:38 UTC, vsajip commented
Are you using a custom style which is not one of the three supported styles? If so, perhaps `dictConfig` should be used instead. I would prefer to encourage people to move over to `dictConfig` as it supports configuring more of the logging API. The `fileConfig` usage should be for legacy applications only.

2020-05-10 13:27 UTC, mirii1994 commented
@vsajip Thanks for the quick response. It is a custom style. I know I can use dictConfig, but I do think that allowing the usage of `fileConfig` will solve a lot of trouble for people who are upgrading to 3.8.

2020-07-11 21:26 UTC, vsajip commented on Lib/logging/config.py
> +            vld = False
I suggest this be simplified to `vld = (vldstr != "False")`.

2020-07-11 21:27 UTC, vsajip requested changes
Possibly a test could also be added for various values in the configuration.

2020-07-11 21:28 UTC, vsajip requested changes
I clicked on "Request changes", but for some reason the status has remained at "Awaiting review" ...

OK, it's changed now to "awaiting changes".

2020-07-12 16:17 UTC, mirii1994 commented
@vsajip  I have made the requested changes; please review again

2020-07-12 22:00 UTC, vsajip requested changes
How about adding tests?

2022-06-25 22:28 UTC, iritkatriel commented
This PR seems to have been abandoned by the OP. Shall we close it?

2022-06-26 16:53 UTC, vsajip commented
> This PR seems to have been abandoned by the OP. Shall we close it?

Yes, I'll do that.

2022-06-26 16:53 UTC, closed without merging