Rename README to README.rst and enhance formatting
python/cpython pull request #2
Opened 2017-02-10 22:41 UTC by haypo

2017-02-10 22:49 UTC, haypo commented
README.rst is recognized by GitHub which will render the README as reStructured text (nice!), instead of plain text.

Example with my tiny project https://github.com/haypo/perf which has a README.rst file.

2017-02-10 22:50 UTC, haypo commented
I checked if the "README" file was referenced directly somewhere: I only found Makefile.pre.in.

2017-02-10 22:52 UTC, zware commented
This could use some additional formatting enhancement, such as changing things like `"./configure --help"` to

```
``./configure --help``
```

Also, links can be turned into linked text rather than written out URLs.

2017-02-10 23:09 UTC, haypo commented
@zware: I hesitated, but ok: I made these changes.

I also added a link to the python-ideas mailing list, and I updated the Release Schedule to the Python 3.7 PEP.

2017-02-11 00:31 UTC, merwok commented on README.rst
> +See `PEP 537 <https://www.python.org/dev/peps/pep-0537/>`_ for Python 3.7
Basic reST supports :pep:'537' (replace quotes with backticks because lol markdown)

2017-02-11 00:55 UTC, haypo commented on README.rst
> +See `PEP 537 <https://www.python.org/dev/peps/pep-0537/>`_ for Python 3.7
I tried locally using rst2html tool. Sadly, this tool uses the old HTTP link, whereas www.python.org moved to HTTPS. I prefer to use HTTPS.

2017-02-11 01:08 UTC, zware requested changes
A couple of minor things, but mostly looks good!

2017-02-11 01:08 UTC, zware commented on README.rst
>  On Windows, see PCbuild/readme.txt.
We could link to the actual file (https://github.com/python/cpython/blob/master/PCbuild/readme.txt).

2017-02-11 01:08 UTC, zware commented on README.rst
>  welcome, preferably in unified diff format.  Please use the issue tracker:
This whole section can use updating:

```
Bug reports are welcome!  You can use the `issue tracker
<https://bugs.python.org>`_ to report bugs, and/or submit pull requests `on
Github <https://github.com/python/cpython>`_.

You can also follow development discussion on the `python-dev mailing list
<https://mail.python.org/mailman/listinfo/python-dev/>`_.
```

2017-02-11 01:08 UTC, zware commented on README.rst
> +See `PEP 537 <https://www.python.org/dev/peps/pep-0537/>`_ for Python 3.7
We should see which one Github uses, if either :)

2017-02-11 01:10 UTC, haypo commented on README.rst
>  On Windows, see PCbuild/readme.txt.
Such change are out of the scope of my initial change. I suggest to make more enhancements in a second change.

2017-02-11 01:10 UTC, haypo commented on README.rst
>  welcome, preferably in unified diff format.  Please use the issue tracker:
Ditto.

2017-02-11 01:12 UTC, dstufft commented on README.rst
> +See `PEP 537 <https://www.python.org/dev/peps/pep-0537/>`_ for Python 3.7
https://github.com/github/markup/blob/cf74e842dfd082d8001417c1bb94edd2ae06d61b/lib/github/commands/rest2html AFAIK

2017-02-11 01:15 UTC, haypo commented
Ok, it seems like Eric and Zach want :pep:`537`: so I made this change.

But I prefer to restrict this change to converting README to README.rst and fix/enhance reST syntax. If you want to more general update/enhancements of README, I suggest to work on a new change based on mine.

2017-02-11 01:16 UTC, zware approved these changes
Fair enough :)

2017-02-11 01:21 UTC, merged

2017-02-11 02:03 UTC, haypo commented
And the winner is .... http://www.python.org/dev/peps/pep-0537 => HTTP link. But since each change now requires a PR, I'm not interested to write a PR just to replace HTTP with HTTPS :-p

2017-02-11 02:28 UTC, zware commented
I'd recommend to report that as a bug to Github :).  It is at least redirected to https automatically.

2017-02-12 21:14 UTC, merwok commented on README.rst
> +See `PEP 537 <https://www.python.org/dev/peps/pep-0537/>`_ for Python 3.7
Damn!  docutils predates universal HTTPS.

2017-02-25 19:28 UTC, Mariatta commented
Do we want to backport this to 3.5 and 2.7?

2017-02-25 20:13 UTC, haypo commented
This change causes issues with Windows installer, check with Steve Dower
(sorry I don't recall the bpo number).

2017-02-25 21:11 UTC, Mariatta commented
Thanks @haypo . I saw the messages in http://bugs.python.org/issue29579. Seems like we won't be backporting readme changes to 3.5 and 2.7.
I'll remove the labels.

2023-10-11 08:52 UTC, miss-islington commented
Thanks @Mariatta for the PR 🌮🎉.. I'm working now to backport this PR to: 3.12.
🐍🍒⛏🤖

2023-10-11 08:52 UTC, miss-islington commented
Sorry, @Mariatta, I could not cleanly backport this to `3.12` due to a conflict.
Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
```
cherry_picker e699b1b7c60b648693cff9a370ab50bff373baeb 3.12
```