[doc] Update MacPython version
python/cpython pull request #20023
Opened 2020-05-10 14:45 UTC by andresdelfino

2020-05-19 14:34 UTC, tirkarthi commented
cc: @ned-deily

2020-05-21 08:04 UTC, ned-deily requested changes

2020-05-21 08:04 UTC, ned-deily commented on Doc/using/mac.rst
> -The "Build Applet" tool that is placed in the MacPython 3.6 folder is fine for
Thanks for catching this.  The Build Applet tool does not exist anymore.  So this whole paragraph should simply be deleted.

2020-05-21 11:58 UTC, andresdelfino commented
I didn't expect the Spanish Inquisition!

2020-05-21 22:42 UTC, ned-deily approved these changes
Thanks for the update and catching the other reference.

2020-05-21 22:45 UTC, merged

2020-05-21 22:45 UTC, miss-islington commented
Thanks @andresdelfino for the PR, and @ned-deily for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8, 3.9.
🐍🍒⛏🤖