bpo-38872: Document exec symbol for codeop.compile_command
python/cpython pull request #20047
Opened 2020-05-12 00:45 UTC by nanjekyejoannah

Original author :  Андрей Беньковский, abenkovskii@gmail.com .

2020-05-14 20:57 UTC, nanjekyejoannah reviewed
Requesting a look at this from @berkerpeksag

2020-05-14 21:52 UTC, berkerpeksag requested changes
This looks good to me, thanks! I just left two comments where we can drop some words just to make the docs more brief.

2020-05-14 21:52 UTC, berkerpeksag commented on Doc/library/code.rst
> +   grammar start symbol, which should be either ``'single'`` (the default), ``'eval'``
I'd suggest dropping the "either" here.

2020-05-14 21:52 UTC, berkerpeksag commented on Doc/library/codeop.rst
> +   cause :exc:`ValueError` to  be raised. If *symbol* is ``'single'`` and *source*
The sentence starting with "If symbol is 'single' [...]" can also be dropped. I think these values are already documented at https://docs.python.org/3/library/functions.html#compile so we can keep these docs brief.

2020-05-14 21:54 UTC, berkerpeksag commented
Also, do you think it's worth to backport this to 3.7 and 3.8?

2020-05-14 23:38 UTC, nanjekyejoannah commented
> Also, do you think it's worth to backport this to 3.7 and 3.8?

yeah this SGTM.

2020-05-15 00:37 UTC, berkerpeksag approved these changes
LGTM, nice work, thanks!

2020-05-15 00:59 UTC, merged

2020-05-15 00:59 UTC, miss-islington commented
Thanks @nanjekyejoannah for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖