Update mimetypes.py
python/cpython pull request #20042
Opened 2020-05-11 23:13 UTC by schwabm

Could you update the types to include the newer version of hdf... hdf5 with .h5 file extension?
See 'Recommendations' section for mime types from the HDF group here:  https://www.hdfgroup.org/2018/06/citations-for-hdf-data-and-software/

2020-05-11 23:13 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@schwabm

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-05-14 14:41 UTC, tirkarthi commented
This would require an issue in https://bugs.python.org .

2020-05-14 15:04 UTC, schwabm commented
> This would require an issue in https://bugs.python.org .

created an issue.

2020-05-18 16:24 UTC, schwabm commented
Any idea if or when this might finish review and be merged?

2020-05-18 17:22 UTC, remilapeyre requested changes
Hi @schwbm, the change looks correct, thanks for your contribution!

Can you change the title of this Pull Request to "bpo-40626: Support HDF5 in mimetypes"?

A core developer will review your PR and will either merge it or ask for some changes. This can take some time as there is a lot of work going on in Python but they will get there. There is not need for merging quickly anyway, it only needs to be done before the next release of Python.

2020-05-18 17:22 UTC, remilapeyre commented
This change will also require a NEWS entry (https://devguide.python.org/committing/#what-s-new-and-news-entries), you can add one by using https://blurb-it.herokuapp.com/

2020-05-18 17:32 UTC, schwabm commented
I’ve updated the title and posted a news blurb.

Thanks!


From: Rémi Lapeyre <notifications@github.com>
Reply-To: python/cpython <reply@reply.github.com>
Date: Monday, May 18, 2020 at 11:22 AM
To: python/cpython <cpython@noreply.github.com>
Cc: "schwabm@nsidc.org" <schwabm@nsidc.org>, Mention <mention@noreply.github.com>
Subject: Re: [python/cpython] Update mimetypes.py (#20042)


@remilapeyre requested changes on this pull request.

Hi @schwbm, the change looks correct, thanks for your contribution!

Can you change the title of this Pull Request to "bpo-40626<https://bugs.python.org/issue40626>: Support HDF5 in mimetypes"?

A core developer will review your PR and will either merge it or ask for some changes. This can take some time as there is a lot of work going on in Python but they will get there. There is not need for merging quickly anyway, it only needs to be done before the next release of Python.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/python/cpython/pull/20042#pullrequestreview-413793978>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHZ2PRUM3N36XARKCZMS7ULRSFVGXANCNFSM4M6KQ74Q>.

2020-05-18 18:14 UTC, remilapeyre approved these changes
Thanks for making the changes!

2020-05-18 18:14 UTC, remilapeyre commented on Misc/NEWS.d/next/Library/2020-05-18-17-29-30.bpo-40626.NeZufF.rst
> +Add h5 file extension as MIME Type application/x-hdf5, as per HDF Group recommendation for HDF5 formatted data files.
```suggestion
Add h5 file extension as MIME Type application/x-hdf5, as per HDF Group recommendation for HDF5 formatted data files. Path contributed by Mark SCHWAB.
```

You can also add an entry at https://github.com/python/cpython/blob/master/Misc/ACKS

2020-06-11 18:54 UTC, akuchling approved these changes

2020-06-11 19:04 UTC, merged

2020-06-11 19:04 UTC, miss-islington commented
Thanks @schwabm for the PR, and @akuchling for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!