bpo-30605: Fix compiling binary regexs with BytesWarnings enabled.
python/cpython pull request #2016
Opened 2017-06-09 01:02 UTC by rowillia

Running our unit tests with `-bb` enabled triggered this failure.

2017-06-09 01:21 UTC, jmphilli commented
+1

2017-06-09 06:09 UTC, serhiy-storchaka requested changes
Add a test for bytes pattern, a Misc/NEWS entry, and your name in Misc/ACKS.

2017-06-09 06:09 UTC, serhiy-storchaka commented on Lib/test/test_re.py
> +            "Flags not at the start of the expression '%s'" % p
Just use `%r`.

And add a test for bytes pattern `b'A(?i)'`.

2017-06-09 07:05 UTC, rowillia commented on Lib/test/test_re.py
> +            "Flags not at the start of the expression '%s'" % p
Done

2017-06-09 07:05 UTC, rowillia commented
Thanks for your feedback @serhiy-storchaka !  Addressed your comments.

2017-06-09 07:25 UTC, serhiy-storchaka requested changes

2017-06-09 07:25 UTC, serhiy-storchaka commented on Misc/ACKS
> +Roy Willams
Typo.

2017-06-09 07:25 UTC, serhiy-storchaka commented on Misc/NEWS
> +  bytes instance.
Add "Patch by Roy Williams."

"... when compiling a  bytes instance with misplaced inline modifier." Or something like.

And usually new entries are added at the begin of a section, so they are listed in the reversed chronological order.

2017-06-10 00:02 UTC, rowillia commented
Thanks again @serhiy-storchaka for taking a look.  I promise usually I spell my own name correctly 😆 !

2017-06-10 04:41 UTC, serhiy-storchaka approved these changes

2017-06-10 05:01 UTC, merged

2017-06-10 05:02 UTC, serhiy-storchaka commented
Thank you for your contribution @rowillia. Do you mind to backport this fix to 3.6?

2017-06-12 21:55 UTC, rowillia commented
Sounds good to me @serhiy-storchaka, thanks for your help landing this.