Revert "move a dot outside double quotes"
python/cpython pull request #20175
Opened 2020-05-18 12:17 UTC by deronnax

As seen in #20007, contrary to what one would expect, in American English, dots go into quotes.
see https://www.thepunctuationguide.com/quotation-marks.html.

Reverts python/cpython#20007

2020-05-18 13:16 UTC, pganssle commented
I think it's basically controversial how to do this, I like @zware's suggestion to reword the question so as to obviate the need to take a stance on this, I think:

> Date and time objects may be categorized as "aware" or "naive" depending on whether or not they include timezone information.

both solves the problem and improves the reader's comprehension, so I call it a win-win.

2020-05-18 13:16 UTC, pganssle requested changes
Rather than revert, let's adopt @zware's suggestion.

2020-05-18 19:56 UTC, JulienPalard commented
I concour with @pganssle, using a workaround will save everybody the time to understand why the dot is here (allowing the brain to focus on what is said by the doc, which is good).

2020-05-21 15:41 UTC, deronnax commented
here you go

2020-05-21 17:52 UTC, zware approved these changes

2020-05-21 20:23 UTC, pganssle approved these changes

2020-05-21 20:26 UTC, merged

2020-05-21 20:26 UTC, miss-islington commented
Thanks @deronnax for the PR, and @pganssle for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖

2020-05-21 20:26 UTC, pganssle commented
Thanks @deronnax et al!