bpo-29607: Fix stack_effect computation for CALL_FUNCTION_EX
python/cpython pull request #202
Opened 2017-02-20 19:54 UTC by MatthieuDartiailh

2017-02-20 19:54 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-21 12:29 UTC, methane approved these changes

2017-02-21 12:35 UTC, methane requested changes
Could you add an entry to `Misc/NEWS` ?

It might be like this:

```
Core and Builtins
-----------------

- bpo-29607: Fix stack effect computation for CALL_FUNCTION_EX opcode.
```

2017-02-21 12:56 UTC, methane approved these changes

2017-02-21 13:06 UTC, serhiy-storchaka commented on Misc/NEWS
> +- bpo-29607: Fix stack_effect computation for CALL_FUNCTION_EX
Please add "Patch by <yourname>."

2017-02-21 13:14 UTC, serhiy-storchaka commented on Misc/NEWS
> +  Patch by Matthieu Dartiailh
Add a period at the end of the entry.

2017-02-21 13:24 UTC, serhiy-storchaka approved these changes

2017-02-21 13:25 UTC, merged

2017-02-21 15:04 UTC, methane commented
@MatthieuDartiailh I'm sorry, but I missed "CLA not signed" label.
Could you sign CLA?  Or have you already signed and waiting it's reviewed?

2017-02-21 15:14 UTC, MatthieuDartiailh commented
It is waiting to be reviewed.

2017-02-21 15:56 UTC, serhiy-storchaka commented
I think signing CLA is not required for such trivial change. Since the bug was reported anyone could write the patch.

But if Matthieu wants to continue his contributing, signing CLA is required.