bpo-40707: Document that Popen.communicate sets the returncode attribute
python/cpython pull request #20283
Opened 2020-05-21 07:53 UTC by gareth-rees

This pull request fixes [issue 40707](https://bugs.python.org/issue40707) by documenting that the `subprocess.Popen.communicate()` method sets the `returncode` attribute.

2020-05-21 09:00 UTC, remilapeyre approved these changes
Thanks for improving the docs @gareth-rees!

2020-05-21 09:00 UTC, remilapeyre commented on Doc/library/subprocess.rst
> +   until end-of-file is reached.  Wait for process to terminate.  Set
```suggestion
   until end-of-file is reached.  Wait for process to terminate and set
```

2020-05-21 11:38 UTC, gareth-rees commented on Doc/library/subprocess.rst
> +   until end-of-file is reached.  Wait for process to terminate.  Set
Suggestion seems fine — go ahead.

2020-05-21 11:50 UTC, remilapeyre commented on Doc/library/subprocess.rst
> +   until end-of-file is reached.  Wait for process to terminate.  Set
I think you should an "Apply suggestion" button you can use or you will need to push a new commit to apply it.

2020-05-21 11:50 UTC, remilapeyre commented on Doc/library/subprocess.rst
> +   until end-of-file is reached.  Wait for process to terminate.  Set
I think you should an "Apply suggestion" button you can use or you will need to push a new commit to apply it.

2020-06-24 01:28 UTC, terryjreedy requested changes

2020-06-24 01:28 UTC, terryjreedy commented on Doc/library/subprocess.rst
> +   until end-of-file is reached.  Wait for process to terminate and set
```suggestion
   until end-of-file is reached.  Wait for process to terminate and set the
```

2020-06-24 01:29 UTC, terryjreedy approved these changes

2020-06-24 03:12 UTC, merged

2020-06-24 03:12 UTC, miss-islington commented
Thanks @gareth-rees for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖