bpo-34689: Prevent sysconfig._parse_makefile from expanding $${variables}
python/cpython pull request #20439
Opened 2020-05-26 21:20 UTC by lepaperwan

As described in [bpo-34689](https://www.bugs.python.org/issue34689), sysconfig._parse_makefile recognizes `$${variable}` as a variable to expand in the second half of the `_parse_makefile` function.
This pull-request aims to fix that by splitting strings on `$$` before looking for variables in them and restoring the `$$` in values that require more processing.
There is no change to the documentation as this is a bug-fix.

https://bugs.python.org/issue34689

Supersedes #9362

2020-06-05 20:14 UTC, ZackerySpytz commented on Lib/sysconfig.py
> +                    value = value[:offset + m.start()] + item.replace('$', '$$') + after
Please limit lines to 79 characters.

2020-06-05 20:14 UTC, ZackerySpytz commented on Misc/NEWS.d/next/Library/2018-09-17-19-11-17.bpo-34689.RtyOE3.rst
> +Split strings prior to parsing in :func:`sysconfig._parse_makefile` so it
`sysconfig._parse_makefile` is not a documented function, so I don't think the `func` role should be used here.

2024-02-28 17:06 UTC, serhiy-storchaka requested changes
`Lib/sysconfig.py` was turned into package. Could you please resolve conflicts?

2025-10-10 05:27 UTC, FFY00 commented
Closing as superseded by GH-136166.

2025-10-10 05:27 UTC, closed without merging