Expose X509_V_FLAG_PARTIAL_CHAIN ssl flag
python/cpython pull request #20463
Opened 2020-05-27 19:57 UTC by l0x-c0d3z

This short PR exposes an openssl flag that  wasn't exposed. I've also updated to doc to reflect the change. It's heavily inspired by 990fcaac3c428569697f62a80fd95ab4d4b93151.

2020-05-27 19:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@l0x-c0d3z, @vbr-cts

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-05-28 12:19 UTC, l0x-c0d3z commented
I've signed the CLA.

2020-06-02 19:14 UTC, ZackerySpytz reviewed
Please open an issue on bugs.python.org. Also, this change should have a news entry.

2020-06-02 19:14 UTC, ZackerySpytz commented on Doc/library/ssl.rst
> +  .. versionadded::3.8.4
```suggestion
   .. versionadded:: 3.10
```
It should be `3.10`. Also, there should be a space after the `::`.

2020-06-02 19:25 UTC, l0x-c0d3z commented
Bug report created at https://bugs.python.org/issue40849
What would be to proper place to add the NEWS entry ?

2020-06-02 19:40 UTC, l0x-c0d3z commented
Added myself to ACKS to make patchcheck happy.

2020-06-03 08:41 UTC, tiran commented
@l0x-c0d3z We still don't have your contributor agreement in the database. It's possible that it was not assigned to your GH account correctly.

2020-07-20 11:53 UTC, csabella commented
@l0x-c0d3z, please see the previous comments about signing the CLA.  Without a signed CLA, this PR will be closed.  Thank you.

2020-09-21 13:05 UTC, csabella commented
The [tool](https://check-python-cla.herokuapp.com/) for checking the CLA shows that it is signed, so we'll need to see why the bot keeps flagging it as not signed.

2021-04-18 06:44 UTC, tiran requested changes
The bot does not recognize your CLA. Could you please verify that you used the correct GH account and that the email address from your commit matches GH settings?

2021-04-19 10:44 UTC, l0x-c0d3z commented
Ok, rewrote the commit history to change the emails, and the knights have now given their blessing.

I have made the requested changes; please review again

2021-04-19 11:51 UTC, tiran approved these changes
Thanks!

Knight Bedevere is picky.

2021-04-19 11:51 UTC, merged