bpo-40807: Show warnings once from codeop._maybe_compile
python/cpython pull request #20486
Opened 2020-05-28 13:57 UTC by csabella

2020-05-30 05:24 UTC, terryjreedy requested changes
After writing the comments, did some more experiments with the REPL that suggest the need for different or maybe just additional changes somewhere (here?  code.II?, IDLE?).  I will report on the issue tomorrow.   Consider these for now.

2020-05-30 05:24 UTC, terryjreedy commented on Lib/codeop.py
> +        # Capture warnings only on the first call to avoid duplication.
```suggestion
        # Allow warnings only on the first call to avoid duplication.
```
but see alternative.

2020-05-30 05:24 UTC, terryjreedy commented on Lib/codeop.py
> +        # Capture warnings only on the first call to avoid duplication.
```suggestion
```
plus suggestion below.

2020-05-30 05:24 UTC, terryjreedy commented on Lib/codeop.py
> +        with warnings.catch_warnings():
Alternative: wrap both compiles with one context manager, preceded by
```
# Suppress warnings after the first compile to avoid duplication.
```
(This is too much for a 'Suggested change' box.)

2020-05-30 09:32 UTC, csabella commented
I have made the requested changes; please review again.

2020-05-30 17:46 UTC, csabella commented on Lib/codeop.py
> +        with warnings.catch_warnings():
Thanks for the suggestion.  Done.

2020-05-30 17:47 UTC, csabella commented on Lib/codeop.py
> +        # Capture warnings only on the first call to avoid duplication.
Done

2020-05-30 17:47 UTC, csabella commented on Lib/codeop.py
> +        # Capture warnings only on the first call to avoid duplication.
I went with the alternative of moving the comment to the ignored warnings.

2020-06-04 20:19 UTC, terryjreedy approved these changes

2020-06-04 20:21 UTC, terryjreedy commented
I am adding the News entry and will merge when possible, and then finish the IDLE fix that requires this.

2020-06-04 23:40 UTC, merged

2020-06-04 23:40 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8, 3.9.
🐍🍒⛏🤖

2020-06-05 03:01 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-06-05 03:01 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-06-05 03:06 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-06-05 03:06 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-06-05 03:22 UTC, terryjreedy commented
@Mariatta Backport are mostly not working for the last hour.
And when it did once, the PR number and link did not appear.  I found the backport of #20646 by trying #20647.

2020-06-05 10:12 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-06-05 10:12 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-06-06 08:06 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-06-06 08:06 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-06-06 09:23 UTC, terryjreedy commented
> Failed tests: test_asyncio (test_cancel_make_subprocess_transport_exec)
Ignore. Known prone to intermittent failure.  In this case, a time-out.

2020-08-12 11:12 UTC, vstinner commented
It seems like this change introduced a regression, would you mind to have a look at https://bugs.python.org/issue41520 ?

cc @csabella