bpo-40820: Add change version for Mock Call `args` and `kwargs` properties
python/cpython pull request #20519
Opened 2020-05-29 18:15 UTC by gobisa

2020-05-29 18:16 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@gobisa

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-05-29 18:59 UTC, remilapeyre requested changes
Hi @gobisa, thanks for taking the time to improve the documentation!

2020-05-29 18:59 UTC, remilapeyre commented on Doc/library/unittest.mock.rst
> +          positional args and keyword args within a ``Call`` object tuple.
```suggestion
          positional args and keyword args within a ``Call`` object.
```

2020-05-29 18:59 UTC, remilapeyre commented on Misc/NEWS.d/next/Documentation/2020-05-29-18-35-18.bpo-40820.SY-wL0.rst
> +Add missing change version for ``args`` and ``kwargs`` mock call objects. Contributed by Andrew Gobis.
Document changes don't need a NEWS entry as they don't change the behaviour of Python but you should add your name to `Misc/ACKS`.

2020-05-29 19:12 UTC, remilapeyre approved these changes
👍

2020-05-29 19:51 UTC, gobisa commented
Should this change also be made to the 3.8 and 3.9 branches?

2020-06-11 14:03 UTC, gobisa commented
> I think it should, please sign the CLA as @the-knights-who-say-ni said :)

2020-06-21 00:22 UTC, remilapeyre commented
> > I think it should, please sign the CLA as @the-knights-who-say-ni said :)
> 
> Will do, but this is out of my control for now.

What do you mean exactly?

2020-07-18 13:20 UTC, tirkarthi commented
Closing this in favor of https://github.com/python/cpython/pull/21525. Sorry.

2020-07-18 13:20 UTC, closed without merging