bpo-40823: Use loadTestsFromTestCase() iso. makeSuite() in sqlite3 tests
python/cpython pull request #20538
Opened 2020-05-30 11:43 UTC by erlend-aasland

2021-01-06 00:33 UTC, berkerpeksag requested changes
I don't have a strong objection to this, but if we are going to drop `Check` prefix, I'd prefer using `test_*` instead of `test*`.

2021-01-06 00:35 UTC, erlend-aasland commented
> I don't have a strong objection to this, but if we are going to drop `Check` prefix, I'd prefer using `test_*` instead of `test*`.

No problem. I'll rebase onto master and fix the naming.

2021-01-06 19:43 UTC, erlend-aasland commented on Lib/sqlite3/test/types.py
> +    def test_cursor_description_ctes_multiple_columns(self):
```suggestion
    def test_cursor_description_cte_multiple_columns(self):
```

@berkerpeksag: ctes => cte?

2021-01-06 19:46 UTC, erlend-aasland commented
PTAL, @berkerpeksag. Rebased onto master with snake case method naming. IMHO, it looks really nice now.

2021-01-06 19:47 UTC, erlend-aasland commented
I have made the requested changes; please review again

2021-01-06 21:01 UTC, berkerpeksag commented on Lib/sqlite3/test/types.py
> +    def test_cursor_description_ctes_multiple_columns(self):
CTE sounds good to me.

2021-01-06 21:04 UTC, berkerpeksag requested changes

2021-01-06 21:04 UTC, berkerpeksag commented on Lib/sqlite3/test/userfunctions.py
> +
Nitpick: I'd drop the extra newline here.

2021-01-06 21:04 UTC, berkerpeksag commented on Misc/NEWS.d/next/Tests/2020-05-30-13-39-22.bpo-40823.yB7K5w.rst
> +Use :meth:`unittest.TestLoader().loadTestsFromTestCase` iso.
Nitpick: I'd prefer using the long form of iso here.

2021-01-06 21:04 UTC, berkerpeksag commented on Misc/NEWS.d/next/Tests/2020-05-30-13-39-22.bpo-40823.yB7K5w.rst
> +:meth:`unittest.makeSuite` in :mod:`sqlite3` tests.
Nitpick: Please add "Patch by Your Name."

2021-01-06 21:24 UTC, erlend-aasland commented
I have made the requested changes; please review again

2021-01-06 21:29 UTC, erlend-aasland commented
GitHub messed up the encoding again! See commit fd4f651. I must remember no to use the suggestion feature for these files.  We should normalise the encoding:

```
$ file Lib/sqlite3/test/*.py
Lib/sqlite3/test/__init__.py:      empty
Lib/sqlite3/test/backup.py:        Python script text executable, ASCII text
Lib/sqlite3/test/dbapi.py:         Python script text executable, ISO-8859 text
Lib/sqlite3/test/dump.py:          Python script text executable, ASCII text
Lib/sqlite3/test/factory.py:       Python script text executable, ISO-8859 text
Lib/sqlite3/test/hooks.py:         Python script text executable, ISO-8859 text
Lib/sqlite3/test/regression.py:    Python script text executable, ISO-8859 text
Lib/sqlite3/test/transactions.py:  Python script text executable, ISO-8859 text
Lib/sqlite3/test/types.py:         Python script text executable, UTF-8 Unicode text
Lib/sqlite3/test/userfunctions.py: Python script text executable, UTF-8 Unicode text
```

2021-01-06 21:32 UTC, erlend-aasland commented
We converted Lib/sqlite3/test/userfunctions.py to UTF-8 in #20448. I'd say we fix the rest right away. Agreed, @berkerpeksag?

2021-01-06 22:05 UTC, berkerpeksag commented
> The same thing happened in #20448, and we ended up just converting Lib/sqlite3/test/userfunctions.py to UTF-8 in the same PR. I'd say we convert the rest right away. Agreed, @berkerpeksag?

I failed to see what's wrong here and #20448 has lots of comments. Why do you want to convert encodings of these files?

2021-01-06 22:15 UTC, erlend-aasland commented
> I failed to see what's wrong here and #20448 has lots of comments. Why do you want to convert encodings of these files?

Commit fd4f651 was auto-generated by GitHub from the "suggestion" I set up in https://github.com/python/cpython/pull/20538#discussion_r552926126. As you notice from the diff, GitHub silently converted the file from ISO-8859 encoding to UTF-8 encoding (ignoring the `#-*- coding: iso-8859-1 -*-` header), in addition to applying the "suggestion" I set up. Over at #20448 the same thing happened; Victor Stinner set up a "suggestion", which I applied, and then GitHub silently converted Lib/sqlite3/test/userfunctions.py from ISO-8859 to UTF-8. Instead of reverting the encoding change GitHub made, we decided to remove the `#-*- coding: iso-8859-1 -*-` header instead, since GitHub obviously dislikes ISO-8859.

2021-01-06 23:03 UTC, berkerpeksag commented
Ah, I see now, thanks for the explanation! Personally, I prefer reverting the commit generated by GitHub and apply the suggested change manually. I don't like when companies try to impose their own practices (it doesn't mean they are bad practices) on a perfectly fine piece of code :)

2021-01-06 23:23 UTC, erlend-aasland commented
… or we can revert the encoding change and create an issue for normalising the encodings.

> Ah, I see now, thanks for the explanation! Personally, I prefer reverting the commit generated by GitHub and apply the suggested change manually. I don't like when companies try to impose their own practices (it doesn't mean they are bad practices) on a perfectly fine piece of code :)

No problem. I'll open an issue for normalising the file encodings. Consistence FTW :)

2021-01-06 23:32 UTC, erlend-aasland commented
Reverted in f93a63b1cd6cb9c9dd6ddbe6700fc1ce3f84862a. PTAL, @berkerpeksag

2021-01-07 00:04 UTC, berkerpeksag approved these changes
LGTM!

2021-01-07 00:05 UTC, merged