Updated code example for asyncio.gather
python/cpython pull request #20604
Opened 2020-06-03 10:54 UTC by josephernest

The previous example did not fully showcase the interest of using gather.

Here the example showcases "the result is an aggregate list of returned values".

As suggested by @ned-deily on https://github.com/python/cpython/pull/20581, I move the pull request here instead of 3.7 branch.

2020-06-03 10:54 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@josephernest

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-06-03 21:55 UTC, aeros requested changes
In general, I'm in favor of the suggestion to display the current number, as I think it does better demonstrate the behavior of `asyncio.gather()`. Although I would simplify it to just `print(f"Task {name}: Compute factorial({number}), current={i}...")`.

But, I disagree with assigning a variable to the result and printing it at the end; I personally don't think that would add anything of real value to the example or help the reader further understand how `asyncio.gather()` works.

Any thoughts @1st1?

2020-06-03 22:05 UTC, josephernest commented
@aeros In the current example, the function `async def factorial` does not return anything, it's a bit a shame because one major feature of `gather` is to be able to get the results of the function as a list, as explained in:

> If all awaitables are completed successfully, the result is an aggregate list of returned values. The order of result values corresponds to the order of awaitables in aws.

The example should really showcase this ^ ; if not, I find the example not really specific or complete, in comparison to other asyncio functions.

How would you showcase this main feature of gather in an example @aeros?

2020-06-03 23:37 UTC, aeros commented
> How would you showcase this main feature of gather in an example @aeros?

My opinion is that the main benefit of the example is showing how `asyncio.gather()` is used to concurrently execute awaitables, as that's the part which is likely to be more difficult to mentally visualize for someone less familiar with concurrent and/or async programming. In general, the examples are not intended to showcase every component of a feature. In the case of the return behavior, I find the documentation's explanation to be very clear and for additional reinforcement in the example to not be necessary.

But that's just my perspective on the matter, @1st1 or @asvetlov might have other thoughts.

2021-05-14 06:04 UTC, orsenthil commented
This example really demonstrates

> If all awaitables are completed successfully, the result is an aggregate list of returned values. The order of result values corresponds to the order of awaitables in aws.

listed in the documentation. 

This also shows concurrent execution of the tasks, using variables. 

So, +1 to clarity provided by these examples. Given that this PR is a documentation enhancement, I propose to merge it, and if current experts feel a mistake, a comment to correct, or request for revert should be fine. Although, as a user and developer, I personally see this as an improvement.

2021-05-14 06:04 UTC, orsenthil approved these changes

2021-05-14 06:05 UTC, orsenthil commented
For Kyle's comment.

> But, I disagree with assigning a variable to the result and printing it at the end; 

I thought about this, I agree that it demonstrates this property explicitly.

> If all awaitables are completed successfully, the result is an aggregate list of returned values. The order of result values corresponds to the order of awaitables in aws.

2021-05-14 06:06 UTC, merged

2021-05-14 06:06 UTC, miss-islington commented
Thanks @josephernest for the PR, and @orsenthil for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.9.
🐍🍒⛏🤖