bpo-40643:  Improve doctrings for datetime parsing methods
python/cpython pull request #20677
Opened 2020-06-06 13:07 UTC by SimiCode

2020-09-25 19:49 UTC, taleinat requested changes
I have a few comments, but the main thing missing here is also updating the doc-strings of the C versions of these methods.

2020-09-25 19:49 UTC, taleinat commented on Lib/datetime.py
> +        """strftime(fmt) -> date_string
The "input -> output" style of doc-strings is only used in functions and class-methods in this module, but not for normal (instance) methods. I don't see that it adds anything in this case (and the others changed by this PR).

2020-09-25 19:49 UTC, taleinat commented on Lib/datetime.py
> +            format: representation of date_string using format codes.
1. The argument is named "fmt".
2. The "Args:" style is different from that currently used in these classes, and adds little in this case with just one argument.
3. I'm not sure "representation of date_string using format codes" would be clear to someone who hadn't seen this before. It seems to me that an example would be very helpful here.

2020-09-25 19:49 UTC, taleinat commented on Lib/datetime.py
> +            date_string: String representation of the date
IMHO these final two lines don't actually add any information.

2020-09-25 19:49 UTC, taleinat commented on Lib/datetime.py
> +                %p  Locale's equivalent of either AM or PM.
Copied from `time.strftime()`, I see. This is very nice!

Perhaps here we should omit the codes referring to hours, minutes and seconds?

Also, where would one find more detailed info and the full list of format codes available? Perhaps consider a reference as to where more detailed information may be found, though I'm not sure what that should be. For `time.strftime()` we have: "Other codes may be available on your platform. See documentation for the C library strftime function."

2020-09-25 20:02 UTC, taleinat commented
Also, since the datetime class currently inherits the strftime() method from the date class, it might be worth adding datetime.strftime() which simply calls the parent class's method, just to override the misleading doc-string.

And I forgot to mention, thanks for working on this, it certainly would have been helpful to me many times, and I'm sure for millions of others as well!

2020-10-20 20:45 UTC, pganssle commented
> Also, since the datetime class currently inherits the strftime() method from the date class, it might be worth adding datetime.strftime() which simply calls the parent class's method, just to override the misleading doc-string.

I wish there were a way to do this without the additional unnecessary stack frame, but I can't find a good one. ☹

2020-10-21 09:36 UTC, taleinat commented
> > Also, since the datetime class currently inherits the strftime() method from the date class, it might be worth adding datetime.strftime() which simply calls the parent class's method, just to override the misleading doc-string.
> 
> I wish there were a way to do this without the additional unnecessary stack frame, but I can't find a good one. frowning_face

I was thinking the exact same thing! But I can't think of a way that wouldn't be a messy hack.

2020-10-22 09:04 UTC, taleinat commented
> Maybe making `__doc__` a property/descriptor?

Ack, that doesn't seem to be supported on functions/methods :(

2020-10-22 09:06 UTC, taleinat commented
> I wish there were a way to do this without the additional unnecessary stack frame, but I can't find a good one. frowning_face

Looking at this again, the `.strftime()` implementation is far from optimized, and the overhead of another method call would be negligible. I'm +1 for wrapping it for better doc-strings.

2020-10-22 09:15 UTC, taleinat commented
However, for the `datetime` class from the `_datetime` module, which is rather optimized and most often the one used, the doc-string can be overridden without adding an extra function call, by explicitly adding the function to `datetime_methods[]` with a custom doc-string.

2020-10-22 09:17 UTC, taleinat commented
@SimiCode, I realize that several months have passed since you created this PR. Would you be interested and able to follow this up?

2022-01-20 22:04 UTC, taleinat commented
Since it's been months and @SimiCode hasn't responded, I've gone ahead and made the changes myself.

I even found a simple way to to get a nice doc-string for `datetime.strftime()` without an extra stack frame :)

@pganssle, it would be great to get your :eyes: on this!

2022-05-18 14:54 UTC, MaxwellDupre approved these changes
Ran 960 tests in 10.773s
OK (skipped=28)
Looks ok.

2023-04-24 21:06 UTC, pganssle requested changes

2023-04-24 21:06 UTC, pganssle commented on Lib/datetime.py
> +        """Convert to a string in the given format via time.strftime().
I think these aren't supposed to be `time.strftime()`, I think we want to directly reference `` :manpage:`strftime(3)` ``. Or at least `strftime(3)` (I guess these docstrings aren't destined for Sphinx, so probably just `strftime(3)` is most appropriate)

2023-04-24 21:06 UTC, pganssle commented on Modules/_datetimemodule.c
> +         "Convert to a string in the given format via time.strftime().\n\n"
Same here as well.

2025-09-15 16:33 UTC, StanFromIreland commented
Thanks for your contribution, however, this has been superseded by https://github.com/python/cpython/pull/138559.

2025-09-15 16:33 UTC, closed without merging