bpo-40944: email.message.EmailMessage address parser fix
python/cpython pull request #20790
Opened 2020-06-10 19:12 UTC by qs

email.message.EmailMessage address parser fails to handle 'example@' assuming that `value` parameter is not empty. Fixed in several places.

https://bugs.python.org/issue40944

2020-06-12 13:02 UTC, csabella commented
@qs, please sign the CLA as requested by the bot in a previous message.  Thank you!

2020-06-12 13:52 UTC, qs commented
@csabella yes, I did, my username https://bugs.python.org/user34926 However, the online check shows I haven't signed.

2020-06-12 14:16 UTC, csabella commented
@qs Thanks!  Let's give it a few days and then we'll check it again.

2024-04-16 18:45 UTC, serhiy-storchaka requested changes
Could you please add tests?

2024-04-17 09:34 UTC, serhiy-storchaka reviewed
LGTM.

2024-04-17 09:34 UTC, serhiy-storchaka commented on Misc/NEWS.d/next/Core and Builtins/2020-06-10-19-24-17.bpo-40943.vjiiN_.rst
> +Fix email.message.EmailMessage address parser handling empty domain e.g. ``"example@"``.
It should be in the Library section.

2024-04-17 09:34 UTC, serhiy-storchaka commented on Lib/email/_header_value_parser.py
> +            "expected name-addr but but found '{}'".format(value))
It seems that this check is redundant, this function is never called with empty value. But let's leave it just in case.

2024-04-17 09:35 UTC, serhiy-storchaka approved these changes

2024-04-17 09:43 UTC, serhiy-storchaka commented
Thank you for your contribution @qs. I do not know whether you are active now, so I added tests myself, and also fixed similar errors in several other place.

2024-04-17 10:14 UTC, merged

2025-11-26 00:05 UTC, medmunds commented
Fixed #85116. [bpo-40944 == GH-85116. GitHub won't autoconnect patches to issues via bpo ids.]