bpo-27729: Give a better error msg when a file path is too long on Windows
python/cpython pull request #20844
Opened 2020-06-12 21:30 UTC by ZackerySpytz

2020-06-12 21:35 UTC, ZackerySpytz commented
It would be good to add a test for `open('')`.

2020-06-12 21:36 UTC, ZackerySpytz commented
It would be nice to add a test for the error message when passing an empty string to `open()`.

2020-06-12 21:37 UTC, ZackerySpytz commented
It would be nice to add a test that checks the error message when an empty string is passed to `open()`.

2020-10-19 22:36 UTC, zooba commented on Modules/_io/fileio.c
> +                    PyExc_OSError, _doserrno, nameobj);
What does the error look like in the path too long case with this change? Would it be more helpful if we checked the error code and used our own message?

2023-11-24 21:47 UTC, iritkatriel requested changes
This has a merge conflict now, as well as an unanswered review.

2026-08-02 20:29 UTC, StanFromIreland commented
Closing as stale, changes haven't been made.

2026-08-02 20:29 UTC, closed without merging