doctest: use `super()` instead of `pdb.Pdb`
python/cpython pull request #20952
Opened 2020-06-17 20:29 UTC by blueyed

This makes a difference / is necessary when using a customized /
replaced `pdb.Pdb`.

2020-06-17 21:59 UTC, pablogsal commented
Please, open first an issue in bugs.python.org

2020-06-17 23:23 UTC, eamanu requested changes
Agree with @pablogsal, please open an issue on b.p.o

2020-06-19 09:45 UTC, blueyed commented
Ok, closing for now then.

2020-06-19 09:45 UTC, closed without merging

2020-06-19 10:39 UTC, pablogsal commented
> Ok, closing for now then.

Hummmm.....you don't need to close the PR, you just need to open a bug in  bugs.python.org first and then link it against this PR