bpo-41048: mimetypes should read the rule file using UTF-8, not the locale encoding
python/cpython pull request #20998
Opened 2020-06-20 09:56 UTC by srinivasreddy

2020-06-20 13:11 UTC, corona10 requested changes
@srinivasreddy 

Thanks for the contribution,
Please add the NEWS.d by using blurb :)

guide: https://devguide.python.org/committing/#what-s-new-and-news-entries

2020-06-20 14:14 UTC, srinivasreddy commented
@corona10 Done

2020-06-20 15:00 UTC, serhiy-storchaka requested changes
Please add tests.

2020-06-20 15:00 UTC, serhiy-storchaka commented on Misc/NEWS.d/next/Library/2020-06-20-10-16-57.bpo-41048.hEXB-B.rst
> +"read_mime_types" function reads the rule file using UTF-8 encoding, not the locale encoding.
```suggestion
:func:`mimetypes.read_mime_types` function reads the rule file using UTF-8 encoding, not the locale encoding.
```

2020-06-21 09:32 UTC, serhiy-storchaka commented on Lib/test/test_mimetypes.py
> +            file.write_text(data)
`write_text()` uses the locale encoding by default. Either specify the encoding or use `write_bytes()`.

2020-06-21 09:32 UTC, serhiy-storchaka commented on Lib/test/test_mimetypes.py
> +            self.addCleanup(setattr, _bootlocale, 'getpreferredencoding', getpreferredencoding)
`_bootlocale.getpreferredencoding` should be a function.

I suggest to use `test.support.swap_attr()`. It is easier and safer.
```
with support.swap_attr(_bootlocale, 'getpreferredencoding', lambda do_setlocale=True: 'ASCII'):
    mime_dict = mimetypes.read_mime_types(file)
eq(mime_dict[".Français"], "application/no-mans-land")
```

2020-06-21 10:31 UTC, srinivasreddy commented
@serhiy-storchaka done. Thanks a lot

2020-06-21 11:32 UTC, serhiy-storchaka approved these changes

2020-06-29 08:34 UTC, serhiy-storchaka approved these changes

2020-06-29 08:36 UTC, merged

2020-06-29 08:36 UTC, miss-islington commented
Thanks @srinivasreddy for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8, 3.9.
🐍🍒⛏🤖

2020-06-29 08:37 UTC, miss-islington commented
Sorry, @srinivasreddy and @serhiy-storchaka, I could not cleanly backport this to `3.7` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 7f569c9bc0079906012b3034d30fe8abc742e7fc 3.7
                                ```