bpo-34154: Improve tkinter widget docstrings
python/cpython pull request #21118
Opened 2020-06-24 14:47 UTC by ZackerySpytz

Co-Authored-By: Noah Haasis <haasis_noah@yahoo.de>

2020-06-24 14:50 UTC, ZackerySpytz commented
This PR addresses the issues that were found in the old PR.

2020-06-25 02:19 UTC, terryjreedy requested changes
I checked the lists against https://www.tcl.tk/man/tcl8.6/TkCmd/contents.htm.  I assumed 'bg' and 'fg' are valid even when not listed there.
Serhiy, do you want to separately review, or should I merge after corrections.

2020-06-25 02:19 UTC, terryjreedy commented on Lib/tkinter/__init__.py
> +        invcmd, justify, readonlybackground, relief, selectbackground,
The tk docs do not list 'invcmd' but do list 'vcmd'.  So I will presume without conrary evidence that this is either missing from the tk doc or is added by tkinter.

2020-06-25 02:19 UTC, terryjreedy commented on Lib/tkinter/__init__.py
> +            background, bitmap, borderwidth, compound,
tk docs include bg, even though they do not for many of widgets above.
```suggestion
            background, bg, bitmap, borderwidth, compound,
```

2020-06-25 02:19 UTC, terryjreedy commented on Lib/tkinter/__init__.py
> +            background, blockcursor, borderwidth,
The list of standard options was correct.  The 6 additions
blockcursor, endline (spelled correctly), inactiveselectbackground, insertunfocused, startline, tabstyle,
 should be moved to WIDGET-SPECIFIC OPTIONS

2020-06-25 02:19 UTC, terryjreedy commented on Lib/tkinter/__init__.py
> +            orient, proxybackground, proxyborderwidth,
height and width were misplaced as standard. They and the 3 new proxy... options should be moved down.

2020-12-25 21:30 UTC, serhiy-storchaka commented on Lib/tkinter/__init__.py
> +        invcmd, justify, readonlybackground, relief, selectbackground,
`invcmd` is an alias of `invalidcommand` and `vcmd` is an alias of `validatecommand`.

2026-07-10 18:40 UTC, serhiy-storchaka commented
Thanks @ZackerySpytz and @noahhaasis.

The tkinter docstring option lists were since completed in gh-78335 by #152485; the current docstrings already cover everything this PR adds, with correct spellings and `Tk 9.1+` annotations. Closing as superseded.

2026-07-10 18:40 UTC, closed without merging