bpo-41195: Add getter for Openssl security level
python/cpython pull request #21282
Opened 2020-07-02 13:10 UTC by matthewhughes934

Add an accessor under SSLContext.security_level as a wrapper around
SSL_CTX_get_security_level, see:
https://www.openssl.org/docs/manmaster/man3/SSL_CTX_get_security_level.html

------
This is my first time contributing, so please pull me up on all the things I missed or did incorrectly.

2020-07-02 13:10 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@matthewhughes934

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-07-02 13:24 UTC, tiran commented
Thanks! You need to do three things:

* sign the CLA
* add a news entry. You can either use [blurb-it](https://github.com/python/blurb_it) bot or the blurb tool
* update documentation Doc/library/ssl.rst including ``versionadded``

2020-07-02 14:11 UTC, matthewhughes934 commented
Thanks tiran,

> sign the CLA

Done, from what I understand it's now just a waiting game for it to be picked up by the system
 
> add a news entry. You can either use [blurb-it](https://github.com/python/blurb_it) bot or the blurb tool
> update documentation Doc/library/ssl.rst including `versionadded`

Thanks, added these too.

2020-07-05 14:52 UTC, tiran requested changes
Good work!

I have two small requests for documentation.

2020-07-05 14:52 UTC, tiran commented on Doc/library/ssl.rst
> +      Only available with OpenSSL >= 1.1.0
```suggestion
   .. availability:: OpenSSL 1.1.0 or newer
```

2020-07-05 14:52 UTC, tiran commented on Doc/library/ssl.rst
> +   The current security level for the context. This attribute is read-only.
Please mention that the security level is an integer and link to https://www.openssl.org/docs/manmaster/man3/SSL_CTX_get_security_level.html

2020-07-05 17:17 UTC, matthewhughes934 commented
Thanks for the suggestions, I have made the requested changes; please review again

2020-07-05 18:56 UTC, tiran approved these changes
LGTM, thanks a lot!

2020-07-06 15:45 UTC, matthewhughes934 commented
Not sure what's holding up the Travis check; it looks like the job for the latest commit passed ok. Hopefully it will just sort itself out in time.

2020-07-09 09:21 UTC, matthewhughes934 commented
@tiran Thanks again for helping with my first contribution!

I'm a bit worried the Travis check here might be stuck, the build looks to have run successfully in a reasonable time, but the status on Github has not been updated for some days now. Is there some way to force this to update/refresh?

2020-07-17 08:37 UTC, matthewhughes934 commented
:thinking: I might try closing and reopening to see if that gets Travis going again.

2020-07-17 08:59 UTC, miss-islington commented
@matthewhughes934: Status check is done, and it's a success ✅ .

2020-07-17 08:59 UTC, merged