bpo-41197: Async magic methods in contextlib.closing
python/cpython pull request #21285
Opened 2020-07-02 18:23 UTC by uburuntu

# Async magic methods in contextlib.closing

I think `__aenter__` and `__aexit__` methods should be added to `contextlib.closing`, so that we can use `contextlib.closing` in async code too.

For example:

```python3
class SomeAPI:
    ...

    async def request(self):
        pass

    async def close(self):
        await self.session.close()
        

async with closing(SomeAPI()) as api:
    response = await api.request()
    print(response)
```

Also these methods can be moved to another class (like `asyncclosing` along the lines of `asynccontextmanager`).

2020-07-02 18:23 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@uburuntu

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-08-08 05:41 UTC, ZackerySpytz commented on Lib/test/test_contextlib_async.py
> +from contextlib import asynccontextmanager, closing, AbstractAsyncContextManager, AsyncExitStack
Please limit modified lines to 79 characters to follow PEP 8.

2020-08-08 05:41 UTC, ZackerySpytz commented on Misc/NEWS.d/next/Library/2020-07-02-22-00-21.bpo-41197.zE6sX-.rst
> +Added `__aenter__` and `__aexit__` methods to :class:`contextlib.closing`,
```suggestion
Added ``__aenter__`` and ``__aexit__`` methods to :class:`contextlib.closing`,
```
Please use double backquotes around `__aenter__` and `__aexit__`.

2020-08-11 00:56 UTC, 1st1 commented on Lib/contextlib.py
> +        await self.thing.close()
Should be `aclose()`

2020-08-11 00:57 UTC, 1st1 requested changes
+1, but the closing method should be `aclose()`

2020-08-11 11:44 UTC, uburuntu commented
Thanks for the review.

I have made the requested changes; please review again.

2021-09-29 11:46 UTC, njsmith commented
I think this and #21545 accidentally raced with each other to solve the same problem, and #21545 won the race; its `aclosing` helper will be shipped in 3.10 next week. (Also having a separate `aclosing` does seem slightly better than overloading `closing` to call two different methods depending on context, IMO.) So unfortunately there may not be anything left to do with this except, well... closing it. It sucks when this kind of thing happens, but not much to be done :-(

2021-10-03 13:41 UTC, uburuntu commented
@njsmith, thanks for the clarification.

It's depressing, but that's okay. Good luck 🚀

2021-10-03 13:41 UTC, closed without merging