bpo-17805: Simple Documentation fix
python/cpython pull request #21291
Opened 2020-07-03 11:31 UTC by Volker-Weissmann

Just a simple documentation fix: apply_async and map_async return a "multiprocessing.pool.AsyncResult Object", not a "result object".

2020-07-03 11:31 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Volker-Weissmann

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-07-03 11:41 UTC, remilapeyre requested changes
Hi @Volker-Weissmann, thanks for improving the documentation!

While it is not always required for simple documentation changes, the CLA will be needed if you want to contribute more significant changes to Python in the future so please follow the advice of @the-knights-who-say-ni to sign it :-)

Also, the documentation wraps the lines at 80 characters, can you please update your PR so that it's consistent with the rest of the file?

2020-07-03 11:57 UTC, Volker-Weissmann commented
I signed the CLA a few minutes ago and added a line break.

2020-07-03 11:59 UTC, remilapeyre commented
Thanks, also bpo-17805 is not exactly related to this change. As it is a simple documentation change, a bpo entry may not be required but we should not use another one that is not strictly this issue. I think you can just change the title of the PR to something like "Add link in multiprocessing documentation".

2020-07-03 12:01 UTC, remilapeyre approved these changes
Thanks!

2020-07-20 11:26 UTC, csabella approved these changes
LGTM.  Thank you for the contribution!

2020-07-20 11:26 UTC, merged

2020-07-20 11:26 UTC, miss-islington commented
Thanks @Volker-Weissmann for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖