Implementing issue-41202
python/cpython pull request #21295
Opened 2020-07-03 15:04 UTC by tomaszdrozdz

bpo-41202: Allow to provide custom exception handler to asyncio.run()

2020-07-03 15:04 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@tomaszdrozdz

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-07-03 15:08 UTC, remilapeyre requested changes
Hi @tomaszdrozdz thanks for improving Python!

For this change to be accepted you will need to had some tests and update the documentation.

This will also require a [NEWS entry](https://devguide.python.org/committing/#what-s-new-and-news-entries), you can add one by using https://blurb-it.herokuapp.com/

2020-07-03 15:13 UTC, remilapeyre commented
Also, can you please update the title of the PR to "bpo-41202: Allow to provide custom exception handler to asyncio.run()"?

No need to open a new PR for that, you can do so by using the "Edit" button at the top of the page near the PR title.

2020-07-06 21:48 UTC, 1st1 requested changes
Thanks for submitting a PR!

That said I'm -1 on the change as I explained in the issue. Blocking the PR for now.

2020-07-07 14:25 UTC, tomaszdrozdz commented
Thanks for reply.  
But I have some doubts.  
I have put them in isue comment.

2020-07-13 11:20 UTC, closed without merging

2020-07-13 11:21 UTC, tomaszdrozdz commented
Changes not wanted. Won't improve.