bpo-30639: Lazily compute repr for error
python/cpython pull request #2132
Opened 2017-06-12 15:42 UTC by takluyver

If the `TypeError` is caught and handled by calling code, there's no need to compute the object's repr for the error message - the repr may take a long time (real case encountered in IPython & Jedi), or it may throw another error.

If the error results in a traceback, it will still compute the repr and produce the message as before.

I think this defensiveness is worthwhile for `inspect` functions because, by design, we're calling them with arbitrary objects which might be badly behaved, and expecting them to be useful nonetheless.

An alternative fix would be to use `object.__repr__()` to always get the plain `<foo object at 0x123abc...>` representation.

2017-06-14 16:03 UTC, marco-buttu requested changes
A part of the newline that should be removed, the rest LGTM

2017-06-14 16:03 UTC, marco-buttu commented on Lib/inspect.py
> +
This new line should be removed.

2017-06-14 16:30 UTC, marco-buttu requested changes

2017-06-14 16:30 UTC, marco-buttu commented on Lib/inspect.py
> +                        type(object).__name__))
I am sorry I did not tell you in the previous message, but I realized just now.  You should align the `type(object).__name__` to `'function'`.

2017-06-14 16:38 UTC, marco-buttu approved these changes

2017-06-20 14:42 UTC, takluyver commented
Can I prevail on anyone to merge this? @serhiy-storchaka , I implemented the change you suggested on the issue.

2017-06-20 15:21 UTC, serhiy-storchaka approved these changes

2017-10-24 10:47 UTC, serhiy-storchaka commented
Could you please take a look on this change @1st1?

2017-10-24 10:56 UTC, 1st1 requested changes
Please add a NEWS entry using blurb.

2017-10-24 10:56 UTC, 1st1 commented on Lib/inspect.py
> +                    type(object).__name__))
Could you please change the error message to "module, class, method, function, traceback, frame, or code object was expected, got {}".

2017-10-24 12:12 UTC, takluyver commented
I have made the requested changes; please review again

2017-10-24 12:42 UTC, 1st1 approved these changes

2017-10-24 12:42 UTC, merged

2017-10-24 12:43 UTC, 1st1 commented
Merged. Thanks a lot!