bpo-39184: Fix incorrect return value in `msvcrt_get_osfhandle_impl`
python/cpython pull request #21322
Opened 2020-07-04 22:24 UTC by gousaiyang

As per #18580, `msvcrt_get_osfhandle_impl` should also return -1 instead of `NULL` when `PySys_Audit` fails.

2021-04-21 23:54 UTC, gousaiyang commented
Hi @zooba, could you review this PR if you have time? This PR seems necessary to correct a mistake I made previously.

2022-10-07 21:24 UTC, nanjekyejoannah reviewed
Dont we need any tests for this change?

2022-10-10 16:58 UTC, zooba approved these changes

2022-10-10 17:01 UTC, zooba commented
If we had failure tests for all APIs with audit hooks, then I'd insist upon it. But we don't, and this only would've been caught by having broad testing (100+ new tests).

It's worth creating an issue for adding that set of tests. They ought to be fairly quick as well (though some will require e.g. making a real network connection, and most will require starting a new Python process for each API), but I think we can take this fix without adding all that.

2022-12-21 10:43 UTC, kumaraditya303 requested changes
The CLA needs to be signed.

2023-01-09 17:45 UTC, zooba commented on PC/msvcrtmodule.c
> +        return -1;
```suggestion
        return (void*)-1;
```

2023-03-06 23:13 UTC, zooba commented
Nothing heard from the OP, but also it doesn't seem to be necessary. This function call checks for any error, without looking at the return value.

2023-03-06 23:13 UTC, closed without merging