Add make key lru cache
python/cpython pull request #21353
Opened 2020-07-06 16:52 UTC by Itayazolay

bpo-41220: added additional make_key argument to lru_cache

I'd like to add optional argument to lru_cache.
This argument is a user given function that will replace the default behaviour of creating a key from the args/kwds of the function.

for example:

def my_make_key(my_list):
  return my_list[0]

@lru_cache(128, make_key=my_make_key)
def cached_func(my_list):
  return sum(my_list)

This will creating a cached function that accepts immutable.
Also, It will allow user to add custom functions from knowledge about the expected function input, without the need to create custom classes and/or overriding __hash__

2020-07-06 17:45 UTC, bharel requested changes
Make sure to Py_Clear make_key on tp_clear.
Make sure you update the docs in C (see lru_cache_doc).
Make sure you update the news with blurb.

2020-07-06 17:45 UTC, bharel commented on Modules/_functoolsmodule.c
> +    obj->make_key = make_key;
Will segfault. Py_INCREF the make_key func.

2020-07-06 17:50 UTC, bharel commented on Modules/_functoolsmodule.c
> +
If `typed` is passed and make_key exists, flow should be identical to the .py implementation.

2020-07-08 11:15 UTC, bharel requested changes

2020-07-08 11:15 UTC, bharel commented on Modules/_functoolsmodule.c
> +    if (obj->key != NULL)
no need to check for NULL

2020-07-08 11:15 UTC, bharel commented on Modules/_functoolsmodule.c
> +    if (key != NULL)
Py_XINCREF, no need for NULL check

2020-07-08 11:15 UTC, bharel commented on Modules/_functoolsmodule.c
> +   if (self->key != NULL)
No need to check for NULL

2020-07-08 11:15 UTC, bharel commented on Modules/_functoolsmodule.c
> +    //if (self->key != NULL)
commented?

2020-07-08 11:15 UTC, bharel commented on Modules/_functoolsmodule.c
> +        if (key && typed){
No need to check key again

2020-07-09 08:12 UTC, bharel requested changes
Awesome 👍

You're welcome to add yourself on MISC/ACKS.
Other than that, LGTM technical wise.
Conceptual wise, waiting for bpo decision.

2020-07-09 08:12 UTC, bharel commented on Lib/functools.py
> +    provided, arguments of the function doesn't have to be hashable.
Grammar fix: 'don't need to be hashable'

2020-07-09 08:12 UTC, bharel commented on Lib/functools.py
> +    make_key = key           # a user defined function of to make key from args.
`make_key = _make_key if key is None else key`

2020-07-09 08:12 UTC, bharel commented on Lib/functools.py
> +            if make_key:
Remove key checks

2020-07-09 08:12 UTC, bharel commented on Lib/functools.py
> +            if make_key:
Remove key checks

2020-07-09 09:48 UTC, Itayazolay commented on Lib/functools.py
> +    make_key = key           # a user defined function of to make key from args.
I wanted to do that, the problem is that _make_key also accepts `typed` as argument.
I think I'll use partial here.

2020-07-10 10:07 UTC, Itayazolay commented
@bharel  Thanks for your CR (and mental support), really appreciate it 😄 
I found a way to remove the `if key...`. I would like to do it also for the C implementation. 
Do you have an idea of how (or if I should)?

2020-07-10 10:35 UTC, bharel approved these changes

2020-07-10 10:36 UTC, bharel approved these changes

2020-07-10 10:41 UTC, bharel commented
> @bharel Thanks for your CR (and mental support), really appreciate it 😄
> I found a way to remove the `if key...`. I would like to do it also for the C implementation.
> Do you have an idea of how (or if I should)?

The only way to maybe do it is by converting the existing implementation to funcproc or vectorcall.
The amount of saving you'll receive is close to 0, so I don't think you should do it. Keep it simple here :-)

2020-07-18 02:13 UTC, rhettinger commented
Closing this for the reasons listed in the BPO.

@bharel Thank for doing a review.  I think we need to have some way to forestall working out the small details before we even decide when the idea itself is acceptable, even in its most perfect form.

2020-07-18 02:13 UTC, closed without merging