bpo-41205: Document Decimal power 0 to the 0
python/cpython pull request #21386
Opened 2020-07-08 04:21 UTC by srinivasreddy

2020-07-08 16:20 UTC, mdickinson requested changes
LGTM. One nitpicky request to remove the extra blank lines introduced in this PR, and one suggested minor wording change.

2020-07-08 16:20 UTC, mdickinson commented on Doc/library/decimal.rst
> +
Nitpick: please remove the extra blank lines here.

2020-07-08 16:20 UTC, mdickinson commented on Doc/library/decimal.rst
> +      in the Python version. Also note that ``Decimal(0) ** Decimal(0)`` results in
I'd suggest dropping the "Also note that" words; I don't think they add value.
```suggestion
      in the Python version. ``Decimal(0) ** Decimal(0)`` results in
```

2020-07-08 16:58 UTC, srinivasreddy commented
@mdickinson   ✅ . Thanks.

2020-07-08 19:03 UTC, mdickinson approved these changes
Thanks for the updates! LGTM. I'll leave this open for a bit in case @skrah or @rhettinger wants to comment.

2020-07-08 21:03 UTC, skrah approved these changes

2020-07-08 21:04 UTC, skrah commented
Looks good, thanks!

2020-07-12 05:12 UTC, rhettinger requested changes

2020-07-12 05:12 UTC, rhettinger commented on Doc/library/decimal.rst
> +      in the Python version. ``Decimal(0) ** Decimal(0)`` results in
Please add a blank line so this gets its own paragraph.

2020-07-13 03:51 UTC, srinivasreddy commented
@rhettinger  Done Raymond. Thanks!!!

2020-07-19 11:03 UTC, skrah commented
@rhettinger's comment has been addressed, so I think we can merge.

2020-07-19 11:03 UTC, merged

2020-07-19 11:03 UTC, miss-islington commented
Thanks @srinivasreddy for the PR, and @skrah for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖