bpo-41073: PyType_GetSlot() could accept static types.
python/cpython pull request #21395
Opened 2020-07-08 14:09 UTC by shihai1991

2020-07-08 15:42 UTC, shihai1991 commented
@vstinner @encukou pls take a look if you have free time, thanks.

2020-07-08 16:04 UTC, encukou requested changes
This will not work with static types. Try adding some tests, and look at how `PyHeapTypeObject` is different from `PyTypeObject`. You should see why.
Sadly I don't have time right now to go into detail, but I'll be happy to add more later. Let me know if you get stuck.

2020-07-08 16:04 UTC, encukou commented on Include/typeslots.h
> +#endif
These should *not* be part of the limited API. See `Py_bf_getbuffer` above for how to exclude them.

2020-07-09 11:26 UTC, shihai1991 commented on Include/typeslots.h
> +#endif
ok, I will update it.

2020-07-09 11:30 UTC, shihai1991 commented
> This will not work with static types. Try adding some tests, and look at how `PyHeapTypeObject` is different from `PyTypeObject`. You should see why.
> Sadly I don't have time right now to go into detail, but I'll be happy to add more later. Let me know if you get stuck.

Copy that, Let me try it.

2020-07-09 13:00 UTC, shihai1991 commented on Include/typeslots.h
> +#endif
Looks like we juse need define it and it don't need to be excluded, no?

2020-07-11 16:30 UTC, shihai1991 commented on Include/typeslots.h
> +#endif
Hi, petr. I create a test module(_testgettypeslots) to see the blocks, but I am not get stuck,: https://github.com/shihai1991/cpython/pull/18

Do we need add some `special` test cases?

2020-08-20 17:07 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Akuli

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-08-20 17:09 UTC, closed without merging

2020-08-20 17:24 UTC, shihai1991 commented
Sorry for my terrible PR~

2020-08-20 17:25 UTC, shihai1991 commented on Include/typeslots.h
> +#endif
Hi, petr. Due to my stupied rebase operation, I decide to create a new PR: #21931

2020-08-21 01:23 UTC, methane commented
"rebase" creates this type of trouble sometime. You can use "merge" instead.
See https://discuss.python.org/t/info-rebase-origin-master-push-f-workflow-corrupts-pull-request-rarely/2558 for detail.

2020-08-21 03:02 UTC, shihai1991 commented
> "rebase" creates this type of trouble sometime. You can use "merge" instead.
> See https://discuss.python.org/t/info-rebase-origin-master-push-f-workflow-corrupts-pull-request-rarely/2558 for detail.

Thanks a million, Inada. It's very useful to me. I haven't found some useful info in google and not sure `git merge` is a good way to reslove this problem before, Lol~

2020-08-21 08:14 UTC, Akuli commented
You might like [git lola](http://blog.kfish.org/2010/04/git-lola.html). I use it a **lot** and I probably couldn't use git without it. It displays your git history as a nice tree that very clearly shows what's going on with branches and merges.