inspect: BlockFinder: handle nested parens with decorators
python/cpython pull request #21425
Opened 2020-07-09 22:17 UTC by blueyed

Fixes:
```
import inspect

def deco(*args, **kwargs):
    def wrapped(f):
        return f
    return wrapped

@deco((lambda: True), (lambda: False))
def func():
    pass

print(inspect.getsource(func))
```

Without this patch it would only print:

> @deco((lambda: True), (lambda: False))

TODO:

- [ ] test
- [ ] bpo issue (?)
- [ ] blurb

2020-07-10 10:14 UTC, kk456852 approved these changes

2020-07-10 19:50 UTC, Deco commented
@blueyed You called?

2022-02-28 05:15 UTC, ahopkins commented
Still an issue in need of merge. I opened a similar PR before finding this one.

https://github.com/python/cpython/pull/31605

2022-12-06 22:52 UTC, iritkatriel requested changes
This PR needs a unit test and news item.

2022-12-07 17:03 UTC, AlexWaygood commented
@carljm, am I correct in thinking this has been superseded by #99654?

2022-12-07 17:04 UTC, carljm commented
Yep, superseded.

2022-12-07 17:04 UTC, closed without merging