Fixed a few leaks
python/cpython pull request #2142
Opened 2017-06-12 23:54 UTC by tiagofilipesilva

This commit fixes a few memory leaks in /PC/bdist_wininst/install.c

2017-06-13 06:56 UTC, serhiy-storchaka reviewed
There are other leaks in this code.

2017-06-13 06:56 UTC, serhiy-storchaka commented on PC/bdist_wininst/install.c
> +            if (!lines) {
The memory pointed by the old value of `lines` is leaked if `realloc()` returns NULL.

And seems `lines` is leaked in the code below.

2018-03-26 09:47 UTC, serhiy-storchaka requested changes
Please fix a leak in `realloc()`.

2019-01-10 16:06 UTC, vstinner commented
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

2019-05-11 03:01 UTC, csabella commented
@serhiy-storchaka, it appears that the original creator of this pull request has abandoned the issue.  Since this concerns refleaks, should this PR be closed a new one opened to address the problems?  Thanks.

2019-05-13 09:05 UTC, vstinner commented
> @serhiy-storchaka, it appears that the original creator of this pull request has abandoned the issue. Since this concerns refleaks, should this PR be closed a new one opened to address the problems? Thanks.

The author signed the CLA. You should try to find someone else to recreate this PR and fix the issue identified by @serhiy-storchaka.

2019-05-13 11:58 UTC, closed without merging

2019-05-13 11:58 UTC, csabella commented
Created bpo-36901 for this pull request.