bpo-41045: Add documentation for f-string's self documenting expressions
python/cpython pull request #21464
Opened 2020-07-13 15:25 UTC by rishi93

Missing documentation describing the = specifier for f-strings has been added

2020-07-13 15:28 UTC, ericvsmith requested changes

2020-07-13 15:28 UTC, ericvsmith commented on Doc/reference/lexical_analysis.rst
> +F-strings can also help with "printf-style" debugging.
I think this needs to at least describe the feature. See my 2 points in bpo-41045 for what I think needs to be included.

2020-07-13 18:57 UTC, rishi93 commented
I have made the requested changes; please review again

2020-07-13 20:30 UTC, ericvsmith reviewed
I think this still needs some polishing, but I'm not very good at writing documentation. Hopefully someone else will respond with some suggestions.

2020-07-14 17:06 UTC, amaajemyfren reviewed
I think the line
```reSt
replacement_field: "{" `f_expression` ["!" `conversion`] [":" `format_spec`] "}"
```
Should be changed to 
```reSt
replacement_field: "{" `f_expression` ["="] ["!" `conversion`] [":" `format_spec`] "}"
```

2020-07-14 17:28 UTC, amaajemyfren commented on Doc/reference/lexical_analysis.rst
> +F-strings can also help with "printf-style" debugging.
Hey @rishi93,

Would you consider adding that this is new from version 3.8?

2020-07-14 17:51 UTC, amaajemyfren commented on Doc/reference/lexical_analysis.rst
> +expression. You can use the repr() with the !r format specifier
Hey @rishi93,

I think ```!r``` is a conversion not a format specifier.

2020-07-14 21:01 UTC, amaajemyfren commented
Hey @rishi93 and @ericvsmith,

I have done [this](https://github.com/amaajemyfren/cpython/blob/proposal_issue41045/Doc/reference/lexical_analysis.rst) file and would like to hear your view of it. I was thinking of doing a PR of it but wanted your opinions first.

2020-07-20 07:24 UTC, rishi93 commented
@amaajemyfren, I will close this PR, you can open a new PR with your changes. Thank you for your effort.

2020-07-20 07:24 UTC, closed without merging