bpo-41373: IDLE: Fix saving files loaded with no newlines or mixed newlines
python/cpython pull request #21597
Opened 2020-07-23 06:02 UTC by serhiy-storchaka

2020-07-23 08:16 UTC, terryjreedy requested changes
I would like to make two changes other than the one in the comment below.

1. Line 140 'Will utf-8 decode'.  Replace with encoding might be unknown rather than wrong.

2. UnicodeDecodeError on 152 can now only come from the 2nd read in 144-9.

Add to this PR? Separate PR for this issue?  Separate issue?

2020-07-23 08:16 UTC, terryjreedy commented on Lib/idlelib/iomenu.py
> +            eol_convention = os.linesep  # default
line 124 above is identical, except it sets eol_convention as a class attribute.  The class attribute is used in fixnewlines (the only usage) for new files created in IDLE.  Rather than duplicate the default, I would rather only set the instance attribute when it might not be the default.
```
if isinstance(eol_convention, str):
    self.eol_convention = eol_convention  # Line 172 below.
else:
    # If .... None.
    # If ... tuple.
    if eol_convention is not None:
        # Message box as below.
```

2020-07-23 11:24 UTC, serhiy-storchaka commented on Lib/idlelib/iomenu.py
> +            eol_convention = os.linesep  # default
When you call `loadfile()` for the same edit window second time, `eol_convention` will be set to the EOL convention in previously opened file,

2020-07-23 11:26 UTC, serhiy-storchaka commented
> Add to this PR? Separate PR for this issue? Separate issue?

I did not fully understand you, but I think it is a separate issue.

2020-07-24 00:36 UTC, terryjreedy commented on Lib/idlelib/iomenu.py
> +            eol_convention = os.linesep  # default
At present, I don't think loadfile() is ever called more than once for an edit window.    Which means that the later line deleting current content is a no-op.  But I would like to add a 'reload' function, such an when one want to restart editing, or a file is changed externally.  So I agree with leaving loadfile as is, ready for such an addition.

However, the line changing eol_convention from None/tuple to string must be moved after the test for it being tuple (not None).  As it is, editing a blank file brings up a spurious mixed endings message.  I will change this and add a blurb.

2020-07-24 05:46 UTC, serhiy-storchaka commented on Lib/idlelib/iomenu.py
> +            eol_convention = os.linesep  # default
Good catch!

AFAIK loadfile() is called for the same edit window when you pick a recent file from menu.

2020-07-24 11:32 UTC, eamanu approved these changes
LGTM

2020-07-24 21:35 UTC, terryjreedy approved these changes

2020-07-24 22:06 UTC, terryjreedy commented
I will leave other changes to another issue after adding tests in a followup PR.  I tested this change after the line was moved by loading and saving both a blank file and one with different endings, and reloading the result of the latter and checking that it only had default endings.  I added blurb and will merge when CI done.

2020-07-24 22:31 UTC, terryjreedy commented on Lib/idlelib/iomenu.py
> +            eol_convention = os.linesep  # default
Recent files not already being edited are loaded in a new window, leaving current windows alone.  Asking for a file already loaded switches to its window.  What I would like to add is a popup offering to discard changes and reload.

2020-07-25 03:21 UTC, merged

2020-07-25 03:21 UTC, miss-islington commented
Thanks @serhiy-storchaka for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖

2020-07-26 07:23 UTC, serhiy-storchaka commented
Thank you for adding blurb Terry.