bpo-41400: Remove references to nonexisting __ne__ methods
python/cpython pull request #21628
Opened 2020-07-26 10:19 UTC by serhiy-storchaka

2020-07-28 04:49 UTC, rhettinger commented
I prefer the tables as-is.  The \__ne__ method does exist; it has just been moved farther along the \__mro__.  From a user's point of view, the method still flows automatically from the abstract methods.

2020-07-28 06:36 UTC, serhiy-storchaka commented
There are several methods which "exist" because they are inherited from the `object` class.
```
>>> sorted(set(object.__dict__) - set(collections.abc.Mapping.__dict__))
['__class__', '__delattr__', '__dir__', '__format__', '__ge__', '__getattribute__', '__gt__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```
But there are no `__lt__`, `__reduce__` or `__format__` in the table.

I now think that it would be better to keep `__ne__` in the table, but change the code (bpo-41416).

2022-01-29 22:36 UTC, hugovk commented
> I now think that it would be better to keep `__ne__` in the table, but change the code ([bpo-41416](https://bugs.python.org/issue41416)).

@serhiy-storchaka So shall we close this PR (and bpo-41400) in favour of doing bpo-41416 instead?

2022-01-30 06:22 UTC, rhettinger approved these changes

2022-11-07 14:02 UTC, iritkatriel requested changes
This has merge conflicts.

2026-07-04 08:07 UTC, serhiy-storchaka commented
Closing along with gh-85572, which was closed as not planned (the current documentation was judged fine as is).

2026-07-04 08:07 UTC, closed without merging