bpo-41455: Fix docs according to sources and devguide
python/cpython pull request #21703
Opened 2020-08-02 08:36 UTC by P-Alban

I've noticed that python docs differ from devguide (https://github.com/python/devguide/blob/master/garbage_collector.rst#collecting-the-oldest-generation)
and source code (https://github.com/python/cpython/blob/master/Modules/gcmodule.c#L1409). 

So, I decided to fix python docs according to those sources. This is my first contribution, so any critic is welcome.

2020-08-02 08:36 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@P-Alban

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-08-02 15:10 UTC, remilapeyre requested changes
Hi @P-Alban, welcome to contributing to Python 🎉 !

As @the-knights-who-say-ni said, you will need to sign the CLA before this change can be merged. Please follow the instructions in his message to do so.

Also in the documentation the lines are wrapped at the 80-th column. Can you please update your pull request so that lines are wrapped accordingly and match the style of the rest of the file?

2020-08-02 15:20 UTC, P-Alban commented
> Hi @P-Alban, welcome to contributing to Python 🎉 !
> 
> As @the-knights-who-say-ni said, you will need to sign the CLA before this change can be merged. Please follow the instructions in his message to do so.
> 
> Also in the documentation the lines are wrapped at the 80-th column. Can you please update your pull request so that lines are wrapped accordingly and match the style of the rest of the file?

Yeah, I've already signed CLA, but as it says, I should wait one business day for confirmation. 
I'll fix my MR right now, thanks.

2020-08-07 23:41 UTC, pablogsal requested changes
I think this may be too verbose for the documentation. In my opinion, we don't need to explain here *why* this is (maybe provide a link to the devguide) we just need to say that it happens.

2020-08-08 13:19 UTC, P-Alban commented
I have made the requested changes; please review again

2020-08-08 18:30 UTC, pablogsal commented on Doc/library/gc.rst
> +   see `Collecting the oldest generation <https://devguide.python.org/garbage_collector/#collecting-the-oldest-generation>`_ for more information.
```suggestion
   With the third generation, things are a bit more complicated, 
   see `Collecting the oldest generation <https://devguide.python.org/garbage_collector/#collecting-the-oldest-generation>`_ for more information.
```

2020-08-08 18:31 UTC, pablogsal approved these changes

2020-08-08 18:37 UTC, pablogsal commented on Doc/library/gc.rst
> +   see `Collecting the oldest generation <https://devguide.python.org/garbage_collector/#collecting-the-oldest-generation>`_ for more information.
```suggestion
   examined, then generation ``1`` is examined as well.
   With the third generation, things are a bit more complicated,
   see `Collecting the oldest generation <https://devguide.python.org/garbage_collector/#collecting-the-oldest-generation>`_ for more information.
```

2020-08-08 18:48 UTC, merged

2020-08-08 18:48 UTC, miss-islington commented
Thanks @P-Alban for the PR, and @pablogsal for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8, 3.9.
🐍🍒⛏🤖

2020-08-08 18:48 UTC, pablogsal commented
Thanks for the PR @P-Alban !