bpo-41472: webbrowser: Use $XDG_CURRENT_DESKTOP to check desktop
python/cpython pull request #21731
Opened 2020-08-04 13:35 UTC by 3v1n0

Usage of $GNOME_DESKTOP_SESSION_ID env variable is deprecated since
GNOME 3.30.0 [1], so should not be used, while the standard
XDG_CURRENT_DESKTOP should be instead preferred.

[1] https://gitlab.gnome.org/GNOME/gnome-session/-/commit/00e0e6226371d53f65

2020-08-04 13:35 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@3v1n0

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2024-02-27 19:14 UTC, serhiy-storchaka requested changes
LGTM, but please resolve conflict and add a NEWS entry.

2024-02-27 20:15 UTC, 3v1n0 commented
I have made the requested changes; please review again

2024-03-02 12:23 UTC, serhiy-storchaka approved these changes
LGTM.

2024-03-02 12:48 UTC, merged