bpo-30662: fixed OrderedDict.__init__ docstring re PEP 468
python/cpython pull request #2179
Opened 2017-06-14 05:01 UTC by jonathaneunice

As of Python 3.6, [PEP 468](https://www.python.org/dev/peps/pep-0468/), kwarg order is no longer arbitrary, but stable wrt to the order of args stated in source code. OrderedDict's docstring should be clear about that, not describe the situation that obtained in Python 3.5 and prior.

2017-06-14 13:51 UTC, jonathaneunice commented
Would be happy with it simply saying "Initialize an ordered dictionary.  The signature is the same as regular dictionaries." I.e., just truncating it so not actively wrong wrt PEP 468. But it's a big change in semantic guarantees, so a bit more explantation might be warranted.

Pending further review, have tightened comment wording and made sure the C implementation has an equivalent comment. (Thanks to Serhiy Storchaka suggestion on bugs.python.org)

2017-06-14 14:02 UTC, jonathaneunice commented
Have just reviewed the collections docs (`Doc/library/collections.rst`). They seem quite up-to-date re PEP 468. No changes seem needed there.

2017-06-14 15:35 UTC, marco-buttu commented on Lib/collections/__init__.py
> +        regular dictionaries. As of Python 3.6, keyword argument insertion
There should be an extra whitespace aftere the period.

2017-06-14 15:35 UTC, marco-buttu commented on Lib/collections/__init__.py
> +        order is stable. (PEP 468)
IMHO *preserved* is more meaningful than *stable*.

2017-06-14 15:35 UTC, marco-buttu commented on Objects/odictobject.c
> +        regular dictionaries. As of Python 3.6, keyword argument insertion\n\
The same as in the previous comment: extra whitespace after period, *preserved* instead of *stable*.

2017-06-14 19:12 UTC, jonathaneunice commented on Objects/odictobject.c
> +        regular dictionaries. As of Python 3.6, keyword argument insertion\n\
@marco-buttu Thank you. Wording and post-period spacing updated.

2017-06-14 21:18 UTC, brettcannon requested changes

2017-06-14 21:18 UTC, brettcannon commented on Lib/collections/__init__.py
> +        regular dictionaries.  As of Python 3.6, keyword argument insertion
Don't mention Python 3.6 or PEP 468 as that's the past and just how things are in Python 3.7 which this docstring is for. Same goes for the other docstring change.

2017-06-14 22:17 UTC, jonathaneunice commented on Lib/collections/__init__.py
> +        regular dictionaries.  As of Python 3.6, keyword argument insertion
Should I mention that keyword order is preserved? Or just drop that altogether and fall back to the compatibility claim alone?

2017-06-15 00:30 UTC, ericsnowcurrently commented on Lib/collections/__init__.py
> +        regular dictionaries.  As of Python 3.6, keyword argument insertion
How about something like "regular dictionaries.  Keyword argument order is preserved."

2017-06-15 04:29 UTC, rhettinger approved these changes

2017-06-16 15:40 UTC, jonathaneunice reviewed
Short, crisp notation of order preservation seems workable consensus.

2017-06-16 15:40 UTC, jonathaneunice commented on Lib/collections/__init__.py
> +        regular dictionaries.  As of Python 3.6, keyword argument insertion
@ericsnowcurrently Agreed. That's exactly the current proposal.

2017-06-16 17:11 UTC, brettcannon approved these changes

2017-09-05 23:23 UTC, merged