bpo-30565: Remove PEP 538 warnings
python/cpython pull request #2186
Opened 2017-06-14 14:25 UTC by haypo

Writing warnings to stderr causes many test failures and the warning
cannot be disabled.

2017-06-14 22:50 UTC, haypo commented
@ncoghlan: So Nick, what do you think? :-)

2017-06-14 23:35 UTC, haypo commented
I don't understand the AppVeyor failure :-( I'm not sure that it's related to my PR.

```
======================================================================
FAIL: test_s_option (test.test_site.HelperFunctionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cpython\lib\test\test_site.py", line 188, in test_s_option
    self.assertIn(usersite, sys.path)
AssertionError: 'C:\\Users\\appveyor\\AppData\\Roaming\\Python\\Python37\\site-packages' not found in ['', 'C:\\projects\\cpython\\PCbuild\\win32\\python37.zip', 'C:\\projects\\cpython\\DLLs', 'C:\\projects\\cpython\\lib', 'C:\\projects\\cpython\\PCbuild\\win32', 'C:\\projects\\cpython', 'C:\\projects\\cpython\\lib\\site-packages']
```

2017-06-15 01:50 UTC, ncoghlan commented
I'm fine with making the stderr warnings opt-in at runtime via `PYTHONCOERCECLOCALE=warn`, but I'm not a fan of removing them entirely.

With the off-by-default runtime switch, you could still remove the compile time option, though.

2017-06-17 04:34 UTC, ncoghlan requested changes
I'm not a fan of this approach, so I'll put together an alternative PR that instead adds `PYTHONCOERCECLOCALE=warn` as a runtime guard for both the successful coercion warning and *for* the coercion-failed-or-was-not-attempted warning, while remove the build time option.

2017-06-17 06:43 UTC, ncoghlan commented
Competing proposal: https://github.com/python/cpython/pull/2260

2017-06-17 14:54 UTC, ncoghlan commented
@haypo  +1'ed #2260, so closing this in favour of that PR.

2017-06-17 14:54 UTC, closed without merging

2017-06-17 22:30 UTC, haypo commented
Le 17 juin 2017 16:54, "Nick Coghlan" <notifications@github.com> a écrit :

@haypo <https://github.com/haypo> +1'ed #2260
<https://github.com/python/cpython/pull/2260>, so closing this in favour of
that PR.

I prefer my PR, but I have no strong preference. I just want to see a quick
fix for freebsd buildbots :-)

For buildbots, another option is to disable the pep in configure on freebsd
:-)