bpo12806: Add argparse FlexiHelpFormatter
python/cpython pull request #22129
Opened 2020-09-07 13:35 UTC by davesteele

This adds the FlexiHelpFormatter class to argparse.

It supports wrapping text, while preserving paragraphs. Bullet lists are supported.

There are a number of differences, relative to the latest patch in the issue report:
  - single line feeds in a paragraph are allowed
  - the code is refactored to avoid duplication
  - test failure fixes (mostly whitespace)

Tests and documentation are included.

2021-05-27 09:10 UTC, lastthyme approved these changes

2025-12-14 19:49 UTC, savannahostrowski requested changes
Hey there - I just saw this has been opened for awhile but I think this is a great formatter addition. I have a couple of comment but I've played around with this quite a bit and it looks pretty solid!

2025-12-14 19:49 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +.. versionadded:: 3.13
```suggestion
.. versionadded:: 3.15
```

2025-12-14 19:49 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +           FlexiHelpFormatter
I don't think that FlexiHelpFormatter is descriptive enough. I'd suggest something like:
```suggestion
           ParagraphHelpFormatter
```

2025-12-14 19:49 UTC, savannahostrowski commented on Lib/argparse.py
> +        return "\n".join(lines)
```suggestion
        lines = self._para_reformat(text, width - len(indent))
        return "\n".join(indent + line for line in lines)
```

As is, this eats any form of indentation that the user might have specified, which I think we want to preserve.

2025-12-14 19:49 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +:class:`FlexiHelpFormatter` wraps description and help text like the default
We should also make it more clear that consecutive non-blank lines at the same indentation without supported bullet markers are merged into one paragraph. Users should add blank lines if they want to preserve formatting.

2025-12-14 19:49 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +single non-whitespace character followed by a "."::
```suggestion
formatter, while preserving paragraphs and supporting bulleted lists. Bullet
list items are recognized by markers such as "*", "-", "+", or ">" characters, or 
by alphanumeric sequences followed by "." or ")" (e.g. 1., a), iv.)::
```

2025-12-14 19:49 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +   usage: PROG [-h] option
```suggestion
   usage: PROG [-h] argument
```

2025-12-14 19:49 UTC, savannahostrowski commented on Doc/library/argparse.rst
> +   optional arguments:
```suggestion
   options:
```

2025-12-19 18:18 UTC, davesteele commented on Doc/library/argparse.rst
> +           FlexiHelpFormatter
Changed to ParagraphHelpFormatter in 2b30019d.

2025-12-19 18:38 UTC, davesteele commented
I have made the requested changes; please review again.

2025-12-20 05:56 UTC, davesteele commented on Doc/library/argparse.rst
> +:class:`FlexiHelpFormatter` wraps description and help text like the default
Addressed in ec6d2d78d.

2025-12-20 05:58 UTC, davesteele commented on Doc/library/argparse.rst
> +single non-whitespace character followed by a "."::
Sorry, I nuked the last part of your change. I thought it was mine, and has trouble reading it.

2025-12-20 06:00 UTC, davesteele commented on Doc/library/argparse.rst
> +   optional arguments:
Commit f64e966b.

2025-12-20 06:00 UTC, davesteele commented on Doc/library/argparse.rst
> +.. versionadded:: 3.13
Commit 8e207548d4.

2025-12-20 06:01 UTC, davesteele commented on Lib/argparse.py
> +        return "\n".join(lines)
Commit 2a53ad49b3.

2025-12-20 06:02 UTC, davesteele commented on Doc/library/argparse.rst
> +   usage: PROG [-h] option
Commit ae7c70f43bb.

2026-05-07 03:37 UTC, davesteele commented
I've "resolved" issues I believe to be addressed in an effort to facilitate progress.

2026-05-09 21:35 UTC, savannahostrowski commented
Thanks for the patience on this, and for picking it back up earlier this year.

After spending more time thinking about this, I don't think a fifth formatter class is the right addition. The direction I'd like to keep argparse in is "good enough for basic CLIs". There are a lot of richer CLI libraries on PyPI now, and growing argparse's surface area makes it harder to maintain and harder to evolve.

There's also a specific concern I have that this PR surfaces which is around composability. The existing four formatters don't compose, so a user who wants paragraphs and defaults still ends up needing to write a multi-inheritance subclass. Adding `ParagraphHelpFormatter` extends that pattern without solving the problem the user actually has, and once it's in the stdlib, it's part of the API forever, which constrains any future redesign aimed at fixing composability.

Meanwhile, [`argparse-formatter`](https://pypi.org/project/argparse-formatter/), which you maintain, already serves the users who need this today, and can iterate in ways the stdlib can't. Given that, I'm going to decline this and close the PR.

2026-05-09 21:35 UTC, closed without merging

2026-05-11 02:31 UTC, davesteele commented
> Meanwhile, [argparse-formatter](https://pypi.org/project/argparse-formatter/), which you maintain, already serves the users who need this today, and can iterate in ways the stdlib can't.

Adoption of argparse-formatter is significantly hindered by the reticence of some people to face the possible risk disclosed in the README:

> Note that ParagraphHelpFormatter is implemented by overriding two private methods in the default argparse formatter, and that the internals of that class are not considered part of the argparse API. There is therefore a (vanishingly) small risk that the code may break with a future standard library release.

That is why I've been supporting this submission for 6 1/2 years.