bpo-41734: refactor b32{encode,decode} tests
python/cpython pull request #22122
Opened 2020-09-06 19:34 UTC by FFY00

Matching b32hex{encode,decode}.

Signed-off-by: Filipe Laíns <lains@archlinux.org>

2020-09-06 19:34 UTC, FFY00 commented
cc @pganssle

2020-09-08 21:04 UTC, pganssle requested changes
I'm +1 on this, but I think it should _probably_ have a news entry, even though it only affects the tests, in case it breaks something for downstream redistributors for some reason.

Given that there's a [tests](https://docs.python.org/3/whatsnew/changelog.html#tests) section to the Changelog, I think we may as well err on the side of caution here.

2020-09-08 21:04 UTC, pganssle commented on Lib/test/test_base64.py
> +        test_cases = [
I feel like we've had this conversation before and I must have been convinced otherwise, but I can't help but think that this _might_ be a bit easier to read as some variation on this:

```python
test_cases = [
    (to_decode, expected, casefold)
    for casefold in [True, False]
    for to_decode, expected in [
    # to_decode, expected
    (b'',         b'')
    (b'AA======', b'\x00'),
    (b'ME======', b'a'),
    (b'MFRA====', b'ab'),
    (b'MFRGG===', b'abc'),
    (b'MFRGGZA=', b'abcd'),
    (b'MFRGGZDF', b'abcde'),
]] + [
    # to_decode, expected, casefold
    (b'me======', b'a',     True),
    (b'mfra====', b'ab',    True),
    (b'mfrgg===', b'abc',   True),
    (b'mfrggza=', b'abcd',  True),
    (b'mfrggzdf', b'abcde', True),
]
```

Downsides: It's got a control structure in it, and the final version of it isn't fully "spelled out".

Upsides: The test cases that are tested with both `casefold=True` and `casefold=False` are much more clearly delineated from the ones that are only tested with `casefold=True`, and the test cases aren't repeated.

I'm on the fence so I'll defer to the author in case anyone else feels strongly about it.

2020-09-08 21:07 UTC, FFY00 commented on Lib/test/test_base64.py
> +        test_cases = [
I can make that change, sure.

2020-09-08 21:08 UTC, FFY00 commented
Before putting any more work into this, can we discuss it in BPO as @serhiy-storchaka marked it as rejected?

2020-09-11 18:32 UTC, merwok commented on Lib/test/test_base64.py
> +        test_cases = [
Personally I find the less logic in tests, the better.  Flat list of cases is the easiest to read and change.  I even like the alignment of entries which I strongly dislike in regular code! :slightly_smiling_face:

2024-11-17 09:00 UTC, FFY00 commented
Yeah, closing this.

2024-11-17 09:00 UTC, closed without merging