bpo-30674: IDLE: add docstrings to grep.py
python/cpython pull request #2213
Opened 2017-06-15 12:29 UTC by csabella

2017-06-15 12:56 UTC, mlouielu requested changes
Thanks for the PR, some small point should be changed.

2017-06-15 12:56 UTC, mlouielu commented on Lib/idlelib/grep.py
> +    "Search Dialog for Find in Files."
`"""Search dialog for find in files."""`

2017-06-15 12:56 UTC, mlouielu commented on Lib/idlelib/grep.py
> +        """Create Search Dialog for searching for a phrase in the file system.
`"""Create search dialog for ...`

2017-06-15 12:56 UTC, mlouielu commented on Lib/idlelib/grep.py
> +        "Make dialog visible on top of others and ready to use."
`"""Make dialog visible .... """`

2017-06-15 12:56 UTC, mlouielu commented on Lib/idlelib/grep.py
> +        "Create base entry widgets and add widget for search path."
`"""Create base entry .... path."""`

2017-06-15 12:56 UTC, mlouielu commented on Lib/idlelib/grep.py
> +        "Add check button to recurse down subdirectories."
`"""Add check button ....subdirectories."""`

2017-06-15 12:56 UTC, mlouielu commented on Lib/idlelib/grep.py
> +        "Create base command buttons and add button for search."
`"""Create base command .... for search."""`

2017-06-15 12:56 UTC, mlouielu commented on Lib/idlelib/grep.py
> +            return None
`return` will return `None`.  So you don't need to explicit `return None`

2017-06-15 12:56 UTC, mlouielu commented on Lib/idlelib/grep.py
> +        "Close the dialog."
`"""Close the dialog."""`

2017-06-15 12:57 UTC, mlouielu commented
I also create a picture for the import relationship for IDLE.  you can saw it here:
![](https://i.imgur.com/1WZwakQ.png)

2017-06-15 17:31 UTC, csabella commented
Terry had changed my """ quotes on a previous PR to just " when the docstring was only one line.  I was following his convention with these changes.

2017-06-16 07:05 UTC, terryjreedy requested changes

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +    "Search Dialog for Find in Files."
The menu item is 'Find in Files', but I agree it is not obvious and awkward if one does not notice.  "Find in Files" is already in file docstring.  How about "Dialog for searching multiple files."?

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +"""Grep dialog for Find in File functionality.
'Files', plural

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +        io: IOBinding with default path to search.
'iomenu.IOBinding instance'

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +        """Create Search Dialog for searching for a phrase in the file system.
agreed

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +        "Make dialog visible on top of others and ready to use."
No. Single double quote is allowed and preferred by me.  Common in stdlib.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +
Don't need new paragraph here.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +            return None
"Either all return statements in a function should return an expression, or none of them should."  So if any must (return an expression), all must, but if all return None, then none must, so None can be omitted but must be omitted everywhere.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +            return None
Leave this at it was also.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +        "Close the dialog."
No.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +                   % hits) if hits else "No hits.")
I believe this was technically correct as it was, but it looks better with the extra space.  But I don't really like it either way (and I wrote it in this form).  In 3.6+, we can do
```
            print(f"Hits found: {hits}\n"
                  f"(Hint: right-click to open locations.)"
                  if hits else "No hits.")
            # or with 79 char lines
            print(f"Hits found: {hits}\n(Hint: right-click to open locations.)"
                  if hits else "No hits.")
```
I like both of these better, so choose one.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +        SearchDialogBase.close(self, event)
Good catch.  Maybe these were once different.  Now, just delete GrepDialog.close and inherit SearchDialogBase.close.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +        "Create base entry widgets and add widget for search path."
See above.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +        "Add check button to recurse down subdirectories."
Ditto.

2017-06-16 07:05 UTC, terryjreedy commented on Lib/idlelib/grep.py
> +        return None
" If any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None "  So if no return statement return an expression, no explicit return is needed at the end.  In other words, this function was within the rules and should be left as it was.

2017-06-16 11:40 UTC, csabella commented on Lib/idlelib/grep.py
> +        SearchDialogBase.close(self, event)
Thanks!

2017-06-16 11:41 UTC, csabella commented on Lib/idlelib/grep.py
> +                   % hits) if hits else "No hits.")
Changed.  I also changed the other string formatting lines to use f strings.

2017-06-16 11:42 UTC, csabella commented on Lib/idlelib/grep.py
> +        return None
Got it.  Thanks.

2017-06-16 11:45 UTC, csabella commented
@mlouielu  @terryjreedy    Thanks for the reviews.  I added an additional note to default_command to mention that the search dialog is closed when the search begins.

One other question -- when I run this, the dialog box always opens way on the bottom of my screen.  Has anyone requested a change to this before?  Or would it be worth mentioning on idle-dev?

2017-06-16 12:40 UTC, mlouielu commented
@csabella I think your question should also post it on b.p.o. Since here is to discuss about code review. I didn't get this on macOS, the dialog show off at the left top side of the screen.

2017-06-27 06:41 UTC, merged