bpo-41776: Revise example of "continue" in the tutorial documentation
python/cpython pull request #22234
Opened 2020-09-13 23:15 UTC by neerajsamtani

2020-09-13 23:15 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@neerajsamtani

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-09-14 01:19 UTC, ericvsmith requested changes

2020-09-14 01:19 UTC, ericvsmith commented on Doc/tutorial/controlflow.rst
>      Found a number 3
The output needs to be changed, too: "Found an odd number 3", etc.

2020-09-14 08:22 UTC, neerajsamtani commented
I have made the requested changes; please review again

2020-09-14 11:25 UTC, ericvsmith reviewed
This looks good. As soon as the CLA is signed, I'll merge it.

2020-09-15 08:29 UTC, neerajsamtani commented
@ericvsmith notifying you that the CLA has been signed so you can now merge it. Thanks

2020-09-15 13:39 UTC, merged

2020-09-15 13:39 UTC, miss-islington commented
Thanks @neerajsamtani for the PR, and @ericvsmith for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖

2020-09-15 13:39 UTC, ericvsmith commented
Thanks!