bpo-25739: Add PAYLOAD_TOO_LARGE / URI_TOO_LONG to http.HTTPStatus
python/cpython pull request #22295
Opened 2020-09-18 05:51 UTC by ZackerySpytz

2022-01-24 03:19 UTC, JelleZijlstra approved these changes

2022-01-24 03:59 UTC, JelleZijlstra commented
This fails tests now, presumably because an enum was added and the new codes need to be adapted to it.

2022-11-27 19:15 UTC, iritkatriel requested changes
Tests are failing.

2026-08-11 20:41 UTC, serhiy-storchaka commented
This was implemented in #117611, with the RFC 9110 names: 413 is now `CONTENT_TOO_LARGE` and 414 is `URI_TOO_LONG`, and the old names are kept as aliases. RFC 9110 renamed 413 from "Payload Too Large" to "Content Too Large", so `PAYLOAD_TOO_LARGE` is no longer the current name. Thank you anyway.

2026-08-11 20:41 UTC, closed without merging