bpo-29614: Rename and reimplement DictReader.
python/cpython pull request #223
Opened 2017-02-21 20:43 UTC by foxfluff

Rename and modify current implementation of DictReader to TableReader that offers non-destructive behavior for csv documents with duplicate fieldname values.

Create new class DictReader as a child to TableReader, allowing for backwards compatibility.

2017-02-21 20:43 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
2. **Wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-21 21:19 UTC, briancurtin requested changes

2017-02-21 21:19 UTC, briancurtin commented on Lib/csv.py
> +class DictReader(TableReader):
There would need to be a DeprecationWarning raised at some point here.

2017-02-21 21:24 UTC, foxfluff commented on Lib/csv.py
> +        d = tuple(zip(self.fieldnames, row))
Tests failed due to using tuple instead of list (as line 127 will attempt to write to what is now non-mutable)
Needs to be changed to list(zip...)

2017-02-21 22:02 UTC, foxfluff commented on Lib/csv.py
> +class DictReader(TableReader):
Would a DeprecationWarning be appropriate here? as this ideally would not affect the behavior of DictReader, and would instead just add the "new" functionality of TableReader.

2017-02-22 05:07 UTC, methane requested changes
No doc and test for TableReader.

But agreement about adding TableReader is required in bugs.python.org before it.

2017-02-22 11:29 UTC, vstinner requested changes
You just cannot remove a public class: https://docs.python.org/dev/library/csv.html#csv.DictReader

2017-02-23 02:48 UTC, foxfluff commented
Closing as rejected.

2017-02-23 02:48 UTC, closed without merging