shutil.rmtree: call onerror with correct function
python/cpython pull request #22585
Opened 2020-10-07 10:12 UTC by nijel

The onerror is supposed to be called with failed function, but in this case lstat is wrongly used instead of open.

Not sure if this needs bug or not...

2020-10-07 10:12 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@nijel

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-10-09 03:35 UTC, tirkarthi commented
I guess this needs a bug. cc: @serhiy-storchaka

2020-10-12 12:54 UTC, nijel commented
I've just created https://bugs.python.org/issue42014

2020-10-14 09:56 UTC, hynek approved these changes, later dismissed
Yeah, looks like a copy pasta.

2020-11-10 13:01 UTC, hynek requested changes
The fix is correct, but it needs a news blurb. Please use https://blurb-it.herokuapp.com/ to fix it, thanks!

2020-11-10 15:41 UTC, nijel commented
I have made the requested changes; please review again

2020-11-10 16:05 UTC, hynek approved these changes

2020-11-10 16:06 UTC, merged

2020-11-10 16:06 UTC, miss-islington commented
Thanks @nijel for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖

2020-11-10 16:06 UTC, hynek commented
Thank you for cleaning up my mess and sorry for the delays!