Docs: improve equivalence expression for chained comparison
python/cpython pull request #22589
Opened 2020-10-07 18:14 UTC by spazm

Add grouping parenthesis around the informal equivalence expression to make it clear that it is evaluated as a single expression.

`x < y < z` parses as a single expression, so while it is equivalent to x < y and y < z in isolation, it is different when used in an expression with `not`.  
`not` has a higher precedence than `and`.  We don't see this with `or` as it has a lower precedence than `and`.  (See the next section on Boolean Expressions)

+ `not x < y < z` == `not (x < y < z)`
+ `not x < y and y < z` != `not (x < y and y < z)`

```
>>> import ast
>>> ast.dump(ast.parse('not x<y<z')) == ast.dump(ast.parse('not(x < y <z)'))
True

>>> ast.dump(ast.parse('not x < y and y < z')) == ast.dump(ast.parse('(not x < y) and y < z'))
True

>>> ast.dump(ast.parse('not x < y and y < z')) == ast.dump(ast.parse('not (x < y and y < z)'))
False
```

2020-10-07 18:14 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@spazm

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-02-03 20:11 UTC, MaxwellDupre requested changes
Its usual to have an issue opened in https://bugs.python.org/
I suggest just copying the text from you conversation.

2022-02-19 16:22 UTC, hugovk commented
> Its usual to have an issue opened in https://bugs.python.org/ I suggest just copying the text from you conversation.

For documentation changes, we can generally skip an issue and news file. I've added the appropriate labels. 👍

2022-02-19 17:09 UTC, hugovk commented
> Add grouping parenthesis around the informal equivalence expression to make it clear that it is evaluated as a single expression.
> 
> `x < y < z` parses as a single expression, so while it is equivalent to x < y and y < z in isolation, it is different when used in an expression with `not`. `not` has a higher precedence than `and`. 

Sure, however we don't have `not` here, so parentheses are arguably redundant here, and for example, some IDEs will recommend removing them. 

Thanks for the PR, but I'm not sure the addition necessarily helps with clarity in this case.

2022-11-14 08:11 UTC, hauntsaninja commented
Thanks, but +1 to hugovk here

2022-11-14 08:11 UTC, closed without merging