bpo-41845: Move PyObject_GenericGetDict() back into the limited API
python/cpython pull request #22646
Opened 2020-10-11 11:09 UTC by ZackerySpytz

It was moved out of the limited API in
7d95e4072169911b228c9e42367afb5f17fd3db0.

2020-10-11 14:31 UTC, alex reviewed
You need to add this to `PC/python3dll.c` as well

2020-10-11 14:45 UTC, alex approved these changes
LGTM, but waiting for a windows reviewer.

2020-10-19 21:35 UTC, zooba requested changes

2020-10-19 21:35 UTC, zooba commented on Include/dictobject.h
> +#if !defined(Py_LIMITED_API) || Py_LIMITED_API+0 >= 0x03030000
```suggestion
#if !defined(Py_LIMITED_API) || Py_LIMITED_API+0 >= 0x030A0000
```

Unfortunately, we can't backport this change, so we need to set the minimum version to 3.10.

2020-10-19 21:35 UTC, zooba commented on Misc/NEWS.d/next/C API/2020-10-11-05-05-53.bpo-41845.ZFvuQM.rst
> +:c:func:`PyObject_GenericGetDict` is available again in the limited API.
```suggestion
:c:func:`PyObject_GenericGetDict` is available again in the limited API when targeted 3.10 or later.
```

2020-10-19 21:52 UTC, ZackerySpytz commented
I have made the requested changes; please review again.

2020-10-19 22:11 UTC, zooba approved these changes

2020-10-19 22:18 UTC, alex approved these changes

2020-10-19 22:47 UTC, merged