bpo-42036:Fixed unchecked return in Modules/posixmodule.c
python/cpython pull request #22696
Opened 2020-10-14 15:42 UTC by monocle-ai

**Instance 1**
File : `Modules/posixmodule.c` 
Enclosing Function : `os_times_impl`
Function : `GetProcessTimes@20` 
https://github.com/siva-msft/cpython/blob/582aaf19e8b94a70c1f96792197770d604ba0fdf/Modules/posixmodule.c#L8505
**Issue in**: _user, kernel_

**Code extract**:

```cpp
    FILETIME create, exit, kernel, user;
    HANDLE hProc;
    hProc = GetCurrentProcess();
    GetProcessTimes(hProc, &create, &exit, &kernel, &user); <------ HERE
    /* The fields of a FILETIME structure are the hi and lo part
       of a 64-bit value expressed in 100 nanosecond units.
```

**How can I fix it?** 
Correct reference usage found in `Modules/timemodule.c` at line `1133`.
https://github.com/siva-msft/cpython/blob/582aaf19e8b94a70c1f96792197770d604ba0fdf/Modules/timemodule.c#L1133
**Code extract**:

```cpp
    BOOL ok;

    process = GetCurrentProcess();
    ok = GetProcessTimes(process, &creation_time, &exit_time, <------ HERE
                         &kernel_time, &user_time);
    if (!ok) {
```

---
**Instance 2**
File : `Modules/posixmodule.c` 
Enclosing Function : `posixmodule_exec`
Function : `dir_fd_converter` 
https://github.com/siva-msft/cpython/blob/582aaf19e8b94a70c1f96792197770d604ba0fdf/Modules/posixmodule.c#L15060
**Issue in**: _ignored_

**Code extract**:

```cpp
    fd_specified("", -1);
    follow_symlinks_specified("", 1);
    dir_fd_and_follow_symlinks_invalid("chmod", DEFAULT_DIR_FD, 1);
    dir_fd_converter(Py_None, &ignored); <------ HERE
    dir_fd_unavailable(Py_None, &ignored);
    }
```

**How can I fix it?** 
Correct reference usage found in `Modules/posixmodule.c` at line `1258`.
https://github.com/siva-msft/cpython/blob/582aaf19e8b94a70c1f96792197770d604ba0fdf/Modules/posixmodule.c#L1258
**Code extract**:

```cpp
dir_fd_unavailable(PyObject *o, void *p)
{
    int dir_fd;
    if (!dir_fd_converter(o, &dir_fd)) <------ HERE
        return 0;
    if (dir_fd != DEFAULT_DIR_FD) {
```

2020-10-14 15:42 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@monocle-ai

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-10-29 12:29 UTC, sweeneyde commented on Modules/posixmodule.c
> +       return 0;
According to [PEP 7](https://www.python.org/dev/peps/pep-0007/#code-lay-out), all new code should use braces.

2020-11-03 23:17 UTC, monocle-ai commented on Modules/posixmodule.c
> +       return 0;
Done

2021-10-09 19:11 UTC, serhiy-storchaka requested changes

2021-10-09 19:11 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +    if(!dir_fd_converter(Py_None, &ignored))
It never fails.

2021-10-09 19:11 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +        return -1;
It is not even compiled.
```suggestion
        return NULL;
```

2022-04-04 00:09 UTC, closed without merging