[3.5] bpo-29887: Test normalization now fails if download fails (GH-905)
python/cpython pull request #2272
Opened 2017-06-19 03:31 UTC by Mariatta

* test_normalization fails if download fails

bpo-29887. The test is still skipped if "-u urlfetch" option is not
passed to regrtest (python3 -m test -u urlfetch test_normalization).

* Fix ResourceWarning in test_normalization

bpo-29887: Fix ResourceWarning in test_normalization if tests are
interrupted by CTRL+c.
(cherry picked from commit 722a3af092b94983aa26f5e591fb1b45e2c2a0ff)

2017-06-19 11:23 UTC, haypo commented
Strange, Travis CI failed on an unrelated test:

```
======================================================================

FAIL: test_write_filtered_python_package (test.test_zipfile.PyZipFileTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/python/cpython/Lib/test/test_zipfile.py", line 811, in test_write_filtered_python_package

    self.assertTrue('SyntaxError' not in reportStr)

AssertionError: False is not true
```

2017-06-19 14:08 UTC, vstinner requested changes
You must also cherry-pick d13d54748d3a7db023d9db37223ea7d40bb8f8e3: see my PR #2275.

2017-06-20 04:04 UTC, Mariatta commented
Thanks @haypo :) I cherry-picked d13d54748d3a7db023d9db37223ea7d40bb8f8e3. 
Since f-strings don't work in this branch, I used `%s` to format the string.

2017-06-20 06:31 UTC, vstinner approved these changes

2017-06-20 06:31 UTC, merged

2017-06-20 06:31 UTC, haypo commented
Thanks for the backport @Mariatta !