bpo-25684: ttk.OptionMenu radiobuttons aren't unique between instance…
python/cpython pull request #2276
Opened 2017-06-19 13:02 UTC by csabella

…s of OptionMenu

Solution based on workaround by Bryan Oakley at https://stackoverflow.com/questions/33831289/ttk-optionmenu-displaying-check-mark-on-all-menus

to set the `variable` attribute of the OptionMenu when the radiobuttons are added.

2017-07-16 16:45 UTC, serhiy-storchaka requested changes

2017-07-16 16:45 UTC, serhiy-storchaka commented on Lib/tkinter/test/test_ttk/test_extensions.py
> +        # check that radiobuttons are unique across instances (bpo25684)
Could you please move this test into separate method?

2017-07-16 16:49 UTC, serhiy-storchaka commented
Please add an entry in `Misc/NEWS.d/next/Library/` and move the test into separate method.

2017-07-17 15:47 UTC, csabella commented
@serhiy-storchaka   Thank you for the review.  I've made the requested changes.  It was the first time I've added a NEWS entry though, so hopefully I used blurb correctly.

2017-07-29 18:18 UTC, terryjreedy approved these changes
When this is merged and backported, I will try to remember to add a note to the S.O. question. 

Cheryl, this would be a good issue for learning to use cherry_picker.  I believe you can install into the same venv as you used for coverage and blurb.

2017-07-29 18:18 UTC, terryjreedy commented on Lib/tkinter/test/test_ttk/test_extensions.py
> +        del textvar2, optmenu_radiobutton_name, optmenu2_radiobutton_name
Not needed. del just unbinds the local names.  This happens anyway when the function exits.

2017-07-29 18:18 UTC, terryjreedy commented on Lib/tkinter/test/test_ttk/test_extensions.py
> +        optmenu2_radiobutton_name = optmenu2['menu'].entrycget(0, 'variable')
I presume that this is actually the tk name of the StringVar that has the selected value.
If so, `optmenu_stringvar_name` would seem clearer.  With the bug fixed, the name should be 'PY_VAR####' instead of the current ttk default `'::selectedButton'`.

2017-07-29 18:18 UTC, terryjreedy commented on Lib/tkinter/test/test_ttk/test_extensions.py
> +                         items[2])
I cannot find any doc for `globalgetvar` other than its use in the Variable subclass `get` methods. It appear to be a _tkinter function that gets the value of a Variable from its name.

2017-07-29 18:20 UTC, terryjreedy commented
Although I approved, I also suggested a change.  The last commit satisfies Serhiy request.

2017-07-29 18:30 UTC, terryjreedy commented
The release candidate for the final bugfix release of 3.5, 3.5.4, is out.  Since this is not a security issue, I believe it should not be backported to 3.5

2017-07-30 12:06 UTC, csabella commented on Lib/tkinter/test/test_ttk/test_extensions.py
> +        del textvar2, optmenu_radiobutton_name, optmenu2_radiobutton_name
Thanks.  For some reason, even though they were local, I thought that the Tk variables had to be explicitly deleted for refleaks.  But, it's probably just when it's in setUp.

2017-07-30 12:11 UTC, csabella commented on Lib/tkinter/test/test_ttk/test_extensions.py
> +                         items[2])
I had a lot of trouble with this when I was trying to create the test.  I had even asked for help on core_workflow.  But, after looking through the other tests in this suite, I saw that `globalgetvar` gave me what I wanted.  I ran the test over the old code and it failed (which was good - failed on the old and passed on the new) and I also looked at the values in debug and this was exactly what I needed.  I don't know if there was any other way to get that information.

2017-07-30 12:15 UTC, csabella commented
Terry,

Yes, I can use cherry_picker to backport this once it's merged.  Thanks!

2017-07-31 09:27 UTC, serhiy-storchaka approved these changes

2017-07-31 09:30 UTC, merged

2017-07-31 09:32 UTC, serhiy-storchaka commented
Thank you @csabella! When you will backport this PR to 3.6 and 2.7 don't forgot to add your name in `Misc/ACKS`.