Allow dependabot to check GitHub actions daily
python/cpython pull request #22787
Opened 2020-10-19 21:57 UTC by jlosito

This allows dependabot to check GitHub actions which this project uses and submit PRs automatically with version bumps.

I did not submit a bug because I thought this was a trivial change and this PR does not necessarily add functionality or fix anything.

Here's reference to the dependabot configs.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot

2020-10-19 21:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@jlosito

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-10-20 19:06 UTC, Mariatta requested changes
Thanks. I think daily update is way too noisy for CPython. Can you change it to monthly?

2020-10-20 19:06 UTC, Mariatta commented on .github/dependabot.yml
> +      interval: "daily"
Can this be done monthly?

2020-10-22 15:59 UTC, jlosito commented
I have made the requested changes; please review again

2020-10-23 21:04 UTC, Mariatta approved these changes
Thanks!

2020-10-23 21:06 UTC, merged

2020-10-23 21:06 UTC, Mariatta commented
Thanks for your first contribution to CPython! 🌮

2020-10-24 16:49 UTC, Mariatta commented
I'm curious whether dependabot checks for the configuration on the other branches, or is it only for the main branch. I was thinking perhaps we should backport this change to 3.9 and 3.8, so at least we don't need to manually trigger backports to future dependabot PRs.

2020-10-24 19:27 UTC, hugovk commented
It should be possible using the `target_branch` option:

https://dependabot.com/docs/config-file/#target_branch

In one of my repos, I have dependabot configured for `master`, and also for this PR's branch: https://github.com/hugovk/pypistats/pull/88

(I'm waiting for httpx to reach 1.0, and dependabot is updating dependencies to check it still passes CI in the meanwhile. It's been useful as the httpx mocker library has been out of sync a couple of times.)

I don't have config files for that repo yet, it's using config from the UI. The only difference between the two configs is there's a target branch set for the PR's branch.