bpo-26131: deprecate the use of load_module()
python/cpython pull request #22905
Opened 2020-10-23 00:33 UTC by brettcannon

Deprecating the use of `load_module()` requires two parts:

1. The actual `load_module()` implementations are deprecated.
2. Use of `load_module()` as a fallback for `exec_module()` trigger an `ImportWarning`.

This makes sure that either direct use of the method or indirect use by the import system raises _some_ warning.

The method itself has been documented as deprecated since Python 3.6 and has been superceded by exec_module().

2020-10-23 00:52 UTC, warsaw requested changes
One suggestion.  There are also test failures.

2020-10-23 00:52 UTC, warsaw commented on Lib/importlib/_bootstrap.py
> +    # It is assumed that all callers have warned about using load_module()
"...have been..."?

2020-10-23 18:14 UTC, brettcannon commented
I have made the requested changes; please review again

2020-10-28 19:48 UTC, brettcannon commented
This is going to require implementing `exec_module()` for `zipimport`.

2020-10-28 19:48 UTC, closed without merging