bpo-42151: don't set specified_attributes=1 in pure Python ElementTree
python/cpython pull request #22987
Opened 2020-10-26 16:01 UTC by obfusk

See https://bugs.python.org/issue42151

2020-10-26 16:01 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@obfusk

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-10-26 16:25 UTC, scoder commented
Thanks for your contribution. The patch looks good to me.
Please add a News entry and send in a signed CLA form.

2020-10-26 17:03 UTC, obfusk commented
> Please add a News entry

Done.

> and send in a signed CLA form.

Already on its way :)

2020-11-20 10:58 UTC, mattip commented
Thanks @obfusk this solved the issue in PyPy.

2021-02-23 15:50 UTC, corona10 commented on Lib/test/test_xml_etree.py
> +        # Test default attribute values; See BPO 42151.
```suggestion
        # Test default attribute values; See bpo-42151.
```

2021-02-24 01:07 UTC, corona10 requested changes

2021-02-24 01:07 UTC, corona10 commented on Misc/NEWS.d/next/Library/2020-10-26-18-01-09.bpo-42151.et5f7s.rst
> +Make the pure Python implementation of `xml.etree.ElementTree` behave the
`[2] ../Misc/NEWS.d/next/Library/2020-10-26-18-01-09.bpo-42151.et5f7s.rst:1: default role used``

Documentation build is failed

2021-02-24 01:47 UTC, obfusk commented
I have made the requested changes; please review again

2021-02-24 02:25 UTC, corona10 approved these changes

2021-02-24 02:25 UTC, merged