bpo-30616: Functional API of enum allows to create empty enums.
python/cpython pull request #2304
Opened 2017-06-20 16:17 UTC by corona10

bpo-30616: Functional API of enum allows to create empty enums.

2017-06-20 22:51 UTC, corona10 commented
@ethanfurman Can you take a look?

2017-06-21 01:51 UTC, ethanfurman requested changes
Overall it looks good.  Please add one more test for:

    Thing = enum.Enum('Thing', [])

2017-06-21 03:52 UTC, corona10 commented
@ethanfurman Updated! Need to backport for 3.6?

2017-06-21 16:13 UTC, ethanfurman approved these changes
Excellent. Thank you.

2017-06-21 16:52 UTC, merged

2017-06-24 16:35 UTC, ethanfurman commented
Add 3.5 backport label since 3.5 is still open to bug fixes.