trivial - made FLASH_DELAY configure for all styles.
python/cpython pull request #2306
Opened 2017-06-20 21:46 UTC by wohlganger

added highlight both parens option.
added name to acks file.

2017-06-21 09:12 UTC, mlouielu commented
I think this isn't trivial, you will need to first add the issue on bugs.python.org. Nosy @terryjreedy for this is a IDLE PR.

2017-06-21 13:24 UTC, wohlganger commented
Added to bugs.python.org . ID# 30723

2017-06-27 16:42 UTC, wohlganger commented
Minor change committed to fix conflict with bpo-29910.

2017-06-27 22:57 UTC, terryjreedy requested changes
I made comments about the initial PR on bpo-30723 and made desired changes myself.  Still need news.

2017-06-27 23:12 UTC, terryjreedy approved these changes

2017-06-28 02:36 UTC, merged