bpo-38413: Improve documentation of sqlite3 module
python/cpython pull request #23159
Opened 2020-11-05 02:00 UTC by greatvovan

This removes an outdated section in the documentation and slightly improves wording and formatting.

See https://bugs.python.org/issue38413

2020-11-05 02:07 UTC, dimaqq approved these changes

2020-11-05 02:15 UTC, greatvovan commented
Sorry, I am new to this repo, how can I assign "skip news" label?

2020-11-05 04:04 UTC, dimaqq commented
> Sorry, I am new to this repo, how can I assign "skip news" label?

AFAIK, someone has to do that for you.

2020-12-16 01:12 UTC, dimaqq commented
> This PR is stale because it has been open for 30 days with no activity. Remove stale label or comment or this will be closed in 5 days

No, it's not!

2020-12-16 04:01 UTC, greatvovan commented
I am the author. Is anything else required from me? Any concerns?

2020-12-18 23:25 UTC, greatvovan commented
Anybody? @berkerpeksag, it shows you as code owner... Is there anything that needs to be fixed?

2020-12-30 01:08 UTC, greatvovan commented
@willingc please help.

2021-01-05 00:54 UTC, willingc commented
@greatvovan I've been offline for a few weeks. I'll add this to my queue for review. Thanks for your patience.

2021-01-05 02:53 UTC, berkerpeksag requested changes

2021-01-05 02:53 UTC, berkerpeksag commented on Doc/library/sqlite3.rst
> +   ``-–enable-loadable-sqlite-extensions`` option in ``PYTHON_CONFIGURE_OPTS``.
AFAIK `PYTHON_CONFIGURE_OPTS` is specific to pyvenv. The old sentence was correct. `configure` is the script mentioned in the [build instructions](https://github.com/python/cpython#build-instructions). Please revert it.

Also, we don't usually accept PRs with random formatting changes.

2021-01-05 17:09 UTC, greatvovan commented
Thanks @berkerpeksag, I reverted to mentioning `configure` script and added the link you provided. I insist that the original sentence is bad as it gives no hints to the topic 90% of Python developers will not ever touch.

Please also note that the main issue here is removing a paragraph that is inconsistent with other article sections (see BPO), it is not a "random formatting change".

2021-01-05 18:23 UTC, berkerpeksag commented
> Thanks @berkerpeksag, I reverted to mentioning configure script and added the link you provided. I insist that the original sentence is bad as it gives no hints to the topic 90% of Python developers will not ever touch.

%90 of Python developers will never have to pass that specific configuration option and the rest of them will understand what that sentence means.

> Please also note that the main issue here is removing a paragraph that is inconsistent with other article sections (see BPO), it is not a "random formatting change".

The part I commented about is a random formatting change. The BPO issue is about removing an outdated section in the sqlite3 documentation which I agree with and I can merge a PR that specifically removes that section.

2021-01-05 21:02 UTC, greatvovan commented
@berkerpeksag the phrase

> you must pass "something" to configure

is not even a syntactically correct phrase in English as "configure" is a verb, and only something noun-like is applicable here. This is not a random formatting change either.

I am not sure I am getting your point... Aren't you agree that this change improves documentation? Or you want me to create another BPO for that? Sorry, I am not very active contributor here.

2021-01-05 21:59 UTC, willingc commented
Let's do this... Remove the agreed upon section. For the last sentence, you both have valid points. Improving the wording slightly seems the best approach. Something similar to:

```
To get loadable extension support, you must pass ``--enable-loadable-sqlite-extensions`` to the `configure <https://github.com/python/cpython#build-instructions>`_ script.
```

2021-01-05 22:32 UTC, greatvovan commented
I think it worths to mention that Python must be rebuilt (recompiled) as just running the script will do nothing.

2021-01-05 23:36 UTC, berkerpeksag commented
Let me try again. You are trying to make two separate changes in a single PR:

1. *Removing an outdated section in the documentation*. This is completely fine and I'd be happy to merge such PR.
2. *Making random formatting and wording changes on a completely unrelated sentence explaining something you don't fully understand.* This is not okay for the following reasons:
   - We prefer doing one change (this can be a new feature, bug fix, documentation changes) per BPO issue. bpo-38413 is about removing an outdated section. You cannot include another change. It's a bad practice. If you found something else while working on bpo-38413, the best practice is opening a new BPO issue or a PR (for example, if you found a typo, you can just submit a separate PR without creating a BPO issue)
   - The change you are trying to *insist* on including is incorrect and the old sentence hasn't been caused any confusion for the past decade. So I'm not going to change it just because someone who initially proposed replacing `configure` with pyenv's `PYTHON_CONFIGURE_OPTS` said so.
   - It's okay to not know about a very niche feature. We all learn something new all the time. However, it's not okay to keep pushing for it when someone else said "no your change is incorrect, please revert to the old version."

2021-01-06 00:06 UTC, berkerpeksag approved these changes
LGTM, thank you!

2021-01-06 00:18 UTC, merged

2021-01-06 00:18 UTC, miss-islington commented
Thanks @greatvovan for the PR, and @berkerpeksag for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖

2021-01-06 00:18 UTC, miss-islington commented
Sorry @greatvovan and @berkerpeksag, I had trouble checking out the `3.9` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker f9949f82e17c88609adb53eff3a7d5cd63a645bd 3.9
                                ```

2021-01-06 00:20 UTC, berkerpeksag commented
@greatvovan do you have time to submit a backport PR for 3.9? I can help you if you don't want to use `cherry_picker`.

2021-01-06 00:26 UTC, greatvovan commented
- I admitted that I was incorrect in my initial change. With your help it was fixed, this is why we have review process of pull requests. I am still not getting what is wrong with the second version and why you are still saying I don't understand something two times in one post.
- I got your point about creating a separate BPO/PR for other unrelated issues and am actually agree that this is better, but in this case I believe it's easier to just inform your counterpart about best practices for the future and proceed. Due to such kind of bureaucracy you have 1.5K of open pull requests.
- You have no data to state that "the old sentence hasn't been caused any confusion for the past decade". Not everyone who finds a confusing phrase runs submitting a change. Questions about enabling sqlite extensions can be found on StackOverflow and in other places, so it is indeed calls confusion.
- I reverted the original sentence. You just left the Python documentation with this ugly phrase:

> you must pass --enable-loadable-sqlite-extensions to configure

My congratulations.

2021-01-06 00:28 UTC, greatvovan commented
> do you have time to submit a backport PR for 3.9?

Yes, I do have time, but your help is appreciated (links, recommendations). Isn't it just a PR to another branch with the same change?

2021-01-06 00:46 UTC, berkerpeksag commented
> Isn't it just a PR to another branch with the same change?

Yes, you basically do:

```sh
$ git checkout -b backport-to-3.9 3.9
$ git cherry-pick -x f9949f82e17c88609adb53eff3a7d5cd63a645bd 
```

And add `[3.9]` prefix to PR title when submitting it. You can copy and paste the title of GH-24134 and replace 3.8 with 3.9.

2021-01-06 19:27 UTC, greatvovan commented
@berkerpeksag #24145