Clarify that Set._from_iterable is not required to be a classmethod.
python/cpython pull request #23272
Opened 2020-11-13 22:13 UTC by rickeylev

In the implementation, `_from_iterable` is only used via `self`, and
requiring `_from_iterable` to be a classmethod makes it of little
value to subclasses with different constructor signatures.

2020-11-13 22:13 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@rickeylev

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-11-15 20:21 UTC, rhettinger requested changes

2020-11-15 20:21 UTC, rhettinger commented on Doc/library/collections.abc.rst
> +   That assumption is factored-out to an internal method called
This line should be left as-is.  It documents the method as given.

2020-11-15 20:21 UTC, rhettinger commented on Doc/library/collections.abc.rst
> +   to construct new instances from an iterable argument.
Let's change this to "with a classmethod or regular method ..."

Also, add test to verify that it works with a regular method.

2020-11-17 03:48 UTC, rickeylev commented
I have made the requested changes; please review again

2020-11-21 19:56 UTC, merged

2020-11-21 19:56 UTC, miss-islington commented
Thanks @rickeylev for the PR, and @rhettinger for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖