Updated obsolete references for RFC 3548 to RFC 4648
python/cpython pull request #2336
Opened 2017-06-23 01:13 UTC by paulehoffman

Updating just the documentation for base64 library. The RFC that was reference was obsolete. The description of both the old and new RFCs was incorrect in saying that they allowed optional changes; the proposed new wording makes this clear without deprecating the option.

2017-06-23 01:13 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-06-23 01:15 UTC, paulehoffman commented
I signed the CLA earlier today, so I'm not sure why the bot didn't find it.

2017-06-24 06:22 UTC, lf- commented
Your indent on line 133 appears to have offended the CI bot for some reason.

2017-06-26 15:06 UTC, reschke commented on Lib/base64.py
> +# Modified 30-Dec-2003 by Barry Warsaw to add full RFC 4648 support
...that appears to be an incorrect change, rewriting history...

2017-06-26 16:31 UTC, paulehoffman commented on Lib/base64.py
> +# Modified 30-Dec-2003 by Barry Warsaw to add full RFC 4648 support
Good call. I have reverted that in d585264.

2018-03-26 09:36 UTC, serhiy-storchaka requested changes
Please open an issue on the [bug tracker](https://bugs.python.org/) for discussion.

We should check that the module supports the new RFC, not just update the number.

2019-04-10 13:20 UTC, csabella commented
@paulehoffman Thank you for the suggested change and for the PR!  If you've opened a bug tracker ticket per @serhiy-storchaka's review, please update the PR title with the bpo number and remove the `trivial` comment.  If you haven't yet opened a ticket, please do so in order for review of this PR to proceed.  Thanks!

2019-04-22 18:35 UTC, paulehoffman commented
I have made the requested changes; please review again

2019-09-12 23:58 UTC, pganssle commented on Doc/library/base64.rst
> +   ``None``, so that 0 and 1 are not allowed in the input. Note that :rfc:`4648`
Is this true? Looks to me like the relevant language is present on [page 5](https://tools.ietf.org/html/rfc4648#page-5) of RFC 4648. The wording is a little different from [RFC 3548](https://tools.ietf.org/html/rfc3548#page-3) but the gist seems to be the same.

2019-09-12 23:59 UTC, pganssle commented on Doc/library/base64.rst
> +   ``None``, so that 0 and 1 are not allowed in the input. Note that :rfc:`4648`
This change is also not mentioned in the [Changes since RFC 3548 section](https://tools.ietf.org/html/rfc4648#page-15). I think we can leave the original wording on these pages and just update the number.

2020-01-25 13:14 UTC, csabella commented
@paulehoffman, please address the code review and resolve the merge conflicts.  Thanks!

2020-08-10 19:05 UTC, pganssle commented
This PR is quite old, but the blocker is now fixed. @paulehoffman do you mind rebasing it against master and addressing [this comment](https://github.com/python/cpython/pull/2336#pullrequestreview-287761922)?

2021-05-03 21:29 UTC, closed without merging