bpo-42423: Accept single base class in PyType_FromModuleAndSpec()
python/cpython pull request #23441
Opened 2020-11-21 10:34 UTC by serhiy-storchaka

2020-11-21 11:33 UTC, tiran requested changes

2020-11-21 11:33 UTC, tiran commented on Modules/_hashopenssl.c
> +        &EVPXOFtype_spec, state->EVPtype
```suggestion
        &EVPXOFtype_spec, (PyObject *)state->EVPtype
```

2020-11-21 11:33 UTC, tiran commented on Objects/structseq.c
> +    type = (PyTypeObject *)PyType_FromSpecWithBases(&spec, &PyTuple_Type);
```suggestion
    type = (PyTypeObject *)PyType_FromSpecWithBases(&spec, (PyObject *)(&PyTuple_Type));
```

2020-11-21 12:46 UTC, encukou commented on Doc/whatsnew/3.10.rst
> +  functions now accept ``NULL`` as the ``tp_doc`` slot.
Please don't change the other entry.

2020-11-21 12:54 UTC, serhiy-storchaka commented
I have made the requested changes; please review again.

2020-11-21 13:58 UTC, tiran approved these changes

2020-11-22 11:25 UTC, merged

2020-11-24 13:38 UTC, encukou commented
Thank you!