bpo-42299: Remove formatter module
python/cpython pull request #23476
Opened 2020-11-23 14:46 UTC by corona10

2020-11-24 13:37 UTC, vstinner commented on Doc/whatsnew/3.10.rst
> +  Since the 2.7 is end of the life, we decide to remove ``formatter`` module.
Maybe use the passive form:

```suggestion
  Since the 2.7 is end of the life, it has been decided to remove the ``formatter`` module.
```

2020-11-24 13:37 UTC, vstinner commented on Misc/NEWS.d/next/Library/2020-11-23-23-42-08.bpo-42299.Fdn4Wf.rst
> +Removed the ``formatter`` module, which was deprecated in 3.4.
```suggestion
Removed the ``formatter`` module, which was deprecated in Python 3.4.
```

2020-11-24 13:37 UTC, vstinner commented on Misc/NEWS.d/next/Library/2020-11-23-23-42-08.bpo-42299.Fdn4Wf.rst
> +(Contributed by Dong-hee Na and and Terry J. Reedy in :issue:`33955`.)
```suggestion
Patch by Dong-hee Na and and Terry J. Reedy.
```

The bpo number is part of the NEWS entry and will be generated in the Changelog: https://docs.python.org/dev/whatsnew/changelog.html#changelog

2020-11-24 13:58 UTC, vstinner commented on Misc/NEWS.d/next/Library/2020-11-23-23-42-08.bpo-42299.Fdn4Wf.rst
> +Removed the ``formatter`` module, which was deprecated in 3.4.
You may also add (here, but maybe also in the What's New entry) that the module had no test!

2020-11-24 14:47 UTC, corona10 reviewed
@vstinner Can you please take a look?

2020-11-24 17:28 UTC, vstinner commented on Doc/whatsnew/3.10.rst
> +* Removed the ``formatter`` module, which was deprecated in Python 3.4.
```suggestion
* Removed the ``formatter`` module, which was deprecated in Python 3.4 and was not tested.
```

Same remarks for the NEWS entry.

2020-11-24 17:28 UTC, vstinner commented on Doc/whatsnew/3.10.rst
> +  but we decided to delay such removals until after Python 2.7 EOL.
```suggestion
  but it has been decided to delay such removals until after Python 2.7 EOL.
```

2020-11-24 17:29 UTC, vstinner approved these changes
LGTM. I'm fine with removing the module. I just left minor remarks on the documentation, you're free to ignore them.

2020-11-24 17:50 UTC, terryjreedy commented on Doc/whatsnew/3.10.rst
> +  but we decided to delay such removals until after Python 2.7 EOL.
```suggestion
  but it was decided to delay such removals until after Python 2.7 EOL.
```

2020-11-24 20:43 UTC, terryjreedy reviewed
LGTM.  I simply don't know if anything else is needed.

2020-11-24 20:43 UTC, terryjreedy commented on Doc/whatsnew/3.10.rst
> +  (Contributed by Dong-hee Na and Terry J. Reedy in :issue:`42299`.)
Putting the comments (including 1 I deleted) together and adding a bit, including what to do and removing duplication, I suggest the following entry.  I discussed 'obsolete' and remedy a bit on the issue.  We don't need to repeat that 2.7 EOL has happened.
```suggestion
* Removed the ``formatter`` module, which was deprecated in Python 3.4.
  It is somewhat obsolete, little used, and not tested.  It was originally
  scheduled to be removed in Python 3.6, but such removals were delayed until
  after Python 2.7 EOL.  Existing users should copy whatever classes they use
  into their code.  (Contributed by Dong-hee Na and Terry J. Reedy in
  :issue:`42299`.)
```

2020-11-24 20:45 UTC, terryjreedy requested changes
See suggested change, which applies to news also.

2020-11-25 11:10 UTC, vstinner approved these changes
LGTM. Thanks @terryjreedy for the way better documentation than what I wrote :-) It's good to write down the full rationale, otherwise people get angry when they see that we remove modules on purpose.

2020-11-25 12:54 UTC, corona10 commented
@vstinner @terryjreedy 
Thanks Victor,
I will merge this PR after CI is passed ;)

2020-11-25 13:17 UTC, merged

2020-11-25 18:04 UTC, terryjreedy commented
Victor, I was inspired to add a 'solution' by your sentence from issue 39352: "I'm no longer sure that it's a good idea to remove a module from the stdlib without providing a solution for the few people relying on it." In this case, I am convinced that copying is a better solution than putting the module on PyPI.