Issue #29176: Use tmpfile() in curses module
python/cpython pull request #235
Opened 2017-02-22 10:37 UTC by tiran

The curses module used mkstemp() + fopen() to create a temporary file in
/tmp. The /tmp directory does not exist on Android. The tmpfile()
function simplifies the task a lot. It creates a temporary file in a
correct directory, takes care of cleanup and returns FILE*.

tmpfile is supported on all platforms (C89, POSIX 2001, Android,
Windows).

https://bugs.python.org/issue29176

Signed-off-by: Christian Heimes <christian@python.org>

2017-02-22 10:58 UTC, vstinner reviewed
Oh, I missed your PR and wrote exactly the same :-)

https://github.com/python/cpython/pull/237

2017-02-22 10:58 UTC, haypo commented on Modules/_cursesmodule.c
>      if (fp != NULL)
the if can now be removed

2017-02-22 10:58 UTC, haypo commented on Modules/_cursesmodule.c
>      FILE *fp = NULL;
= NULL can be removed

Same remarks for the other function.

2017-02-22 11:23 UTC, vstinner approved these changes

2017-02-22 11:25 UTC, vstinner requested changes
Oh, I missed "Issue #29176: Use tmpfile() in curses module " in the commit message.

Please replace "Issue #29176" with "bpo-29176".

Moreover, I don't think that the bugs.python.org URL is needed in the commit message.

2017-02-22 12:05 UTC, serhiy-storchaka commented on Modules/_cursesmodule.c
> +        PyErr_SetFromErrno(PyExc_IOError);
Can be OSError.

2017-02-22 12:08 UTC, serhiy-storchaka commented
I think an entry in Misc/NEWS is required.

2017-02-22 12:15 UTC, haypo commented
> I think an entry in Misc/NEWS is required.

From an user point of view, there is no change, except of Android support.

Last days, I'm trying to avoid touching Misc/NEWS, because it's even more a mess because of how pull requests work :-(

2017-03-02 10:08 UTC, vstinner approved these changes

2017-03-02 10:09 UTC, merged