bpo-42485: [Doc] Link to PEP 617 from full grammar specification
python/cpython pull request #23532
Opened 2020-11-27 16:07 UTC by SnoopJeDi

Now that CPython uses the new PEG parser, it would be helpful to include a reference to the guiding PEP (617) on the docs page (https://docs.python.org/3/reference/grammar.html) that gives the grammar.

https://bugs.python.org/issue42485

2020-11-27 16:07 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@SnoopJeDi

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-11-27 18:57 UTC, pablogsal commented
Thanks for the PR @SnoopJeDi.

Could you follow these instructions (https://github.com/python/cpython/pull/23532#issuecomment-734900015) to sign up the CLA so I can review and merge the PR?  :)

2020-11-27 20:25 UTC, jgerityneurala commented
> 
> 
> Thanks for the PR @SnoopJeDi.
> 
> Could you follow these instructions ([#23532 (comment)](https://github.com/python/cpython/pull/23532#issuecomment-734900015)) to sign up the CLA so I can review and merge the PR? :)

I've signed the CLA and received a copy by email, so I assume we're waiting on the bot to take notice of this. Will check back tomorrow!

2020-11-27 20:27 UTC, SnoopJeDi commented
> 
> 
> Thanks for the PR @SnoopJeDi.
> 
> Could you follow these instructions ([#23532 (comment)](https://github.com/python/cpython/pull/23532#issuecomment-734900015)) to sign up the CLA so I can review and merge the PR? :)

I've signed the CLA and received a copy by email, so I assume we're waiting on the bot to take notice of this. Will check back tomorrow! (apologies if you received two notifications about this, I accidentally replied with another account at first)

2020-11-27 22:04 UTC, lysnikolaou requested changes
Thanks a lot for your contribution, @SnoopJeDi! We've got a custom `pep` rst directive, which should be used to link to PEPs.

2020-11-27 22:04 UTC, lysnikolaou commented on Doc/reference/grammar.rst
> +details on the grammar's syntax.
```suggestion
:pep:`617` for more details on the grammar's syntax.
```

2020-11-28 12:37 UTC, terryjreedy commented
I expect that our office manager took today off in addition to Thanksgiving yesterday.  So I expect no CLA link until Monday.

2020-11-28 16:11 UTC, SnoopJeDi commented
Cheers for the review and the directive. 

I have made the requested changes; please review again

2020-11-30 19:08 UTC, pablogsal approved these changes

2020-11-30 19:08 UTC, merged

2020-11-30 19:08 UTC, pablogsal commented
Thanks for the PR @SnoopJeDi !