bpo-42487: don't call __getitem__ of underlying maps in ChainMap.__iter__
python/cpython pull request #23534
Opened 2020-11-28 01:00 UTC by ap--

See: https://bugs.python.org/issue42487

2020-11-28 01:00 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@ap--

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-11-28 01:27 UTC, rhettinger requested changes

2020-11-28 01:27 UTC, rhettinger commented on Lib/collections/__init__.py
> +            d.update(dict.fromkeys(mapping))    # reuses stored hash values if possible
*dict.fromkeys()* keeps the keys but loses the values.

2020-11-28 01:33 UTC, rhettinger requested changes
Please add tests and a blurb entry for Misc/NEWS.  Also, please get the CLA signed.

2020-11-28 03:37 UTC, ap-- commented
Hi @rhettinger,
I added a test and the news blurb and signed the CLA (though it states on bpo it make take up to few days to register...)

Thanks for the quick review and feedback :)

Cheers,
Andreas

2020-11-28 09:02 UTC, serhiy-storchaka approved these changes
LGTM.

2020-11-28 18:41 UTC, rhettinger approved these changes

2020-11-30 16:34 UTC, merged

2020-11-30 16:34 UTC, miss-islington commented
Thanks @ap-- for the PR, and @rhettinger for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!