bpo-42536: Track recycled zip result tuples
python/cpython pull request #23623
Opened 2020-12-03 04:32 UTC by brandtbucher

2020-12-03 09:31 UTC, vstinner commented on Lib/test/test_builtin.py
> +            gc.disable()
Is it needed to disable the GC?

2020-12-03 09:31 UTC, vstinner commented on Lib/test/test_builtin.py
> +            gc.collect()
Please explain that this GC collection untracks the internal "result" tuple of the zip object.

2020-12-03 09:31 UTC, vstinner commented on Lib/test/test_builtin.py
> +            self.assertTrue(gc.is_tracked(next(z)))
This test checks for an implementation details, I suggest to decorate the test with `@support.cpython_only`.

2020-12-03 09:31 UTC, vstinner commented on Lib/test/test_builtin.py
> +    def test_zip_result_gc(self):
Please add a comment mentioning bpo-42536 and explain the purpose of the test.

2020-12-03 09:31 UTC, vstinner commented on Misc/NEWS.d/next/Core and Builtins/2020-12-02-20-23-31.bpo-42536.Kx3ZOu.rst
> +Fix an issue where :func:`zip` may create untracked reference cyles. Patch
Hum, it's unclear to me that the fix involved an internal tuple which is not tracked by the garbage collector. I suggest something like:

":func:`zip` now ensures that its internal tuple is always tracked by the garbage collector to be able to break reference cycle. Previously, the internal tuple was sometimes untracked by a garbage collection."

The reality is even more complex, it's an old version of the tuple which is untracked, a version which cannot be part of a reference cycle: a tuple only containing None values. But after the tuple is untracked, the tuple is modified in place (yeah, modifying an immutable object ;-)) and the new tuple can be involved in a reference cycle...

But I don't think that we should elaborate too much in the NEWS entry. People can look into the bpo for details ;-)

2020-12-03 09:31 UTC, vstinner commented on Python/bltinmodule.c
> +        // untracked. Since we're recycling it, make sure it's tracked again:
Since this issue is quite tricky, I suggest to add a reference to `bpo-42536: `.

2020-12-03 16:32 UTC, brandtbucher commented on Lib/test/test_builtin.py
> +            gc.disable()
Ah, nice catch.

2020-12-03 20:01 UTC, pablogsal requested changes, later dismissed
Thanks @brandtbucher for giving this a go. I think that there is a better approach here: force the result to be tracked on the visiting function. This has the advantage of adding only an overhead when the GC calls the visiting function over the zip object as opposed to pay per call to `next()`. To be clear, this is what I mean:

```diff
 a/Python/bltinmodule.c b/Python/bltinmodule.c
index a73b8cb320..b05239c037 100644
--- a/Python/bltinmodule.c
+++ b/Python/bltinmodule.c
@@ -2604,6 +2604,9 @@ static int
 zip_traverse(zipobject *lz, visitproc visit, void *arg)
 {
     Py_VISIT(lz->ittuple);
+    if (!_PyObject_GC_IS_TRACKED(lz->result)) {
+        _PyObject_GC_TRACK(Zz->result);
+    }
     Py_VISIT(lz->result);
     return 0;
 }
```

2020-12-03 20:15 UTC, pablogsal commented
The only reason I think we should consider doing this on the visiting function is due to these results:

https://bugs.python.org/msg382365

2020-12-03 22:20 UTC, brandtbucher commented
Thanks Pablo. See my thoughts here:

https://bugs.python.org/msg382455

If that doesn't worry you at all, I'm fine moving this to the traverse function.

2020-12-03 22:23 UTC, brandtbucher commented
Oh, wait. I see now that GitHub says you "dismissed" your review. I'm not sure what that means... are we in agreement here to keep this as-is?

2020-12-03 23:34 UTC, pablogsal commented
> Oh, wait. I see now that GitHub says you "dismissed" your "stale review". I'm not sure what that means... are we in agreement here to keep this as-is?

Sorry, I comented it here: https://bugs.python.org/msg382458. I think that unless we see a horrendous performance regression, I prefer this approach that `tp_traverse`.

2020-12-04 04:08 UTC, rhettinger approved these changes

2020-12-04 04:47 UTC, methane approved these changes

2020-12-04 08:17 UTC, serhiy-storchaka approved these changes

2020-12-04 11:21 UTC, vstinner commented on Lib/test/test_dict.py
> +        i = iter({None: []}.items())
nitpick: i suggest to rename the variable to "it", I dislike names of a single letter ;-) Same remark for other tests.

2020-12-04 11:21 UTC, vstinner commented on Lib/test/test_itertools.py
> +    def test_permutations_result_gc(self):
Can you please make the two tests closer in the file?

2020-12-04 11:24 UTC, vstinner approved these changes
LGTM, but I left some minor coding style remarks (you're free to ignore them).

I also suggest you to copy your NEWS entry as the commit message.

2020-12-04 11:24 UTC, vstinner commented on Misc/NEWS.d/next/Core and Builtins/2020-12-02-20-23-31.bpo-42536.Kx3ZOu.rst
> +Bucher.
You may give the list. Copy from your PR description (I didn't check if it's complete):

```
    collections.OrderedDict.items
    dict.items
    enumerate
    functools.reduce
    itertools.product
    itertools.combinations
    itertools.combinations_with_replacement
    itertools.permutations
    itertools.zip_longest
    zip
```

2020-12-04 22:09 UTC, pablogsal approved these changes
:rocket:

2020-12-04 22:15 UTC, vstinner approved these changes
LGTM. Thanks for the latest round of updates ;-)

2020-12-05 03:45 UTC, merged

2020-12-05 03:46 UTC, miss-islington commented
Thanks @brandtbucher for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖

2020-12-05 03:46 UTC, miss-islington commented
Sorry, @brandtbucher, I could not cleanly backport this to `3.9` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 226a012d1cd61f42ecd3056c554922f359a1a35d 3.9
                                ```

2020-12-05 03:46 UTC, miss-islington commented
Sorry @brandtbucher, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 226a012d1cd61f42ecd3056c554922f359a1a35d 3.8
                                ```