typo-ish: improved comment that indicates state of Barrier
python/cpython pull request #23755
Opened 2020-12-13 20:29 UTC by cpriyank

removed extra comma in comment that indicates state of a `Barrier` as it was confusing and breaking the flow while reading. Also added missing space after `#` that began the comment

2020-12-13 20:29 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@cpriyank

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-02-11 10:25 UTC, serverwentdown approved these changes
LGTM, erroneous extra comma in code comment.

2021-05-11 15:06 UTC, eamanu requested changes
I'm not sure about a new commit for only for this change.

We can take in advantage some other bugs to fix this.

Also @cpriyank don't forget sign the CLA.

2021-09-29 13:23 UTC, ambv commented on Lib/threading.py
> +        self._state = 0 # 0 filling, 1 draining, -1 resetting, -2 broken
```suggestion
        self._state = 0  # 0 filling, 1 draining, -1 resetting, -2 broken
```

2021-09-29 13:42 UTC, ambv commented
Closing in favor of GH-28623.

2021-09-29 13:42 UTC, closed without merging