Fixed typo in itertools documentation
python/cpython pull request #23816
Opened 2020-12-17 08:50 UTC by Casper-Smet

# Fixed typo in itertools documentation

As I was perusing the documentation for itertools.product, I noticed a small typo in the last sentence:

``` Accordingly, it only useful with finite inputs.```

This pull request simply adds the word "is" in order to make this sentence grammatically correct:

``` Accordingly, it is only useful with finite inputs.```

--------------------------------------------------------
I also added my name to the misc/ACKS file, per the contribution guidelines.

2020-12-17 08:50 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Casper-Smet

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2020-12-17 08:59 UTC, Casper-Smet commented
I have now signed the CLA and signed up to b.p.o., my sincere apologies for not doing this earlier.

2020-12-18 18:11 UTC, rhettinger approved these changes

2020-12-19 04:28 UTC, merged

2020-12-19 04:31 UTC, fochoao requested changes
It is useful for finite inputs.