[doc] Add versionadded for Symbol.is_annotated
python/cpython pull request #23861
Opened 2020-12-19 21:44 UTC by andresdelfino

2020-12-20 07:52 UTC, Fidget-Spinner approved these changes

2020-12-29 12:38 UTC, serhiy-storchaka requested changes

2020-12-29 12:38 UTC, serhiy-storchaka commented on Doc/library/symtable.rst
> +      .. versionadded:: 3.10
It was added in 3.6.
```suggestion
      .. versionadded:: 3.6
```

2020-12-29 12:54 UTC, andresdelfino commented
I have made the requested changes; please review again

2020-12-29 13:31 UTC, serhiy-storchaka approved these changes

2020-12-29 13:32 UTC, merged

2020-12-29 13:32 UTC, miss-islington commented
Thanks @andresdelfino for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖

2020-12-29 13:32 UTC, miss-islington commented
Sorry, @andresdelfino and @serhiy-storchaka, I could not cleanly backport this to `3.9` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 2edfc86f69d8a74f4821974678f664ff94a9dc22 3.9
                                ```

2020-12-29 13:32 UTC, miss-islington commented
Sorry @andresdelfino and @serhiy-storchaka, I had trouble checking out the `3.8` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 2edfc86f69d8a74f4821974678f664ff94a9dc22 3.8
                                ```