bpo-42367: Restore os.makedirs() ability to apply *mode* recursively
python/cpython pull request #23901
Opened 2020-12-22 23:58 UTC by ZackerySpytz

Allow os.makedirs() to apply the *mode* argument to any intermediate
directories that are created.

2021-01-22 10:42 UTC, ZackerySpytz commented
It is not stale.

2021-07-08 23:47 UTC, chimosky commented
@ZackerySpytz is there any workaround for this at the moment as you stated in [#42367](https://bugs.python.org/issue42367) that umask can't be used to control the intermediate directory creation permissions.

2022-02-12 12:49 UTC, MaxwellDupre requested changes
The target introduced is not 3.10 but 3.11.
Could you make the appropriate 'rst' changes please?

2025-08-30 19:47 UTC, ZackerySpytz reviewed
Hello, @gpshead. I see that you have made some changes to this PR. I have pointed out some lines in the changes you have made that we should modify.

We should also make sure that the lines in the new pathlib code are limited to a maximum of 79 characters (for PEP 8 compliance).

2025-08-30 19:47 UTC, ZackerySpytz commented on Doc/library/os.rst
> +   newly-created intermediate-level directories. Otherwise, intermediate
```suggestion
   newly-created, intermediate-level directories. Otherwise, intermediate
```

2025-08-30 19:47 UTC, ZackerySpytz commented on Doc/library/pathlib.rst
> +   newly-created intermediate-level directories when *parents* is true.
```suggestion
   newly-created, intermediate-level directories when *parents* is true.
```

2025-08-30 19:47 UTC, ZackerySpytz commented on Doc/library/pathlib.rst
> +.. method:: Path.mkdir(mode=0o777, parents=False, exist_ok=False, *, parent_mode=None)
``parent_mode`` should be placed on a new line (like in ``os.rst``).

2026-05-18 18:15 UTC, gpshead commented
replaced by https://github.com/python/cpython/pull/150011

2026-05-18 18:15 UTC, closed without merging