bpo-27200: fix configparser, copyreg and ctypes doctests
python/cpython pull request #240
Opened 2017-02-22 20:54 UTC by marco-buttu

This PR patially fixes bpo-27200. Partially and not completely, because I followed the suggestion of @ezio-melotti to split the patch in several patches. According to @rhettinger I applyed minimal changes, skipping some tests instead of using `sorted()`. I just want to point out that the two `<BLANKLINE>` and the `testsetup` dicrective will not appear in the output.

2017-02-27 14:31 UTC, berkerpeksag requested changes

2017-02-27 14:31 UTC, berkerpeksag commented on Doc/library/configparser.rst
> +    import configparser
Indentation should use three spaces here.

2017-02-27 14:31 UTC, berkerpeksag commented on Doc/library/ctypes.rst
> +.. doctest::
I find your version much clearer, +1. However, I don't see much point converting this to a doctest. I'd say remove `.. doctest::` and keep the rest of the changes.

2017-02-27 14:37 UTC, marco-buttu commented on Doc/library/configparser.rst
> +    import configparser
Thanks, you are right

2017-02-27 15:21 UTC, marco-buttu commented on Doc/library/ctypes.rst
> +.. doctest::
I removed the doctest directive. However, there is one point for taking it: in some editors, if you use the `::` before the example you enable the syntax hightligh for the example, but the example will not be doctested. If you use just the `:`, you lose the syntax highligh but the example will be doctested. If you eventually use the `doctest` directive, you have both syntax highlight and doctest.

2017-02-27 15:27 UTC, berkerpeksag commented on Doc/library/ctypes.rst
> +.. doctest::
Well, I didn't mentioned it because I assumed you are going to change "[...] each time:" to "[...] each time::" :)

2017-02-27 18:13 UTC, marco-buttu commented on Doc/library/ctypes.rst
> +.. doctest::
@berkerpeksag, it was "[...] each time:" from the beginning, I did not change it. Do you still want to change it anyway? Sorry for all these questions :/

2017-02-27 18:15 UTC, berkerpeksag commented on Doc/library/ctypes.rst
> +.. doctest::
Yes, please change it to "[...] each time::".

2017-02-27 18:36 UTC, marco-buttu commented on Doc/library/ctypes.rst
> +.. doctest::
Ok, done. Thank you! :-)

2017-03-02 10:00 UTC, ezio-melotti approved these changes

2017-03-02 11:02 UTC, berkerpeksag approved these changes

2017-03-02 11:02 UTC, merged