bpo-42811: Update importlib.utils.resolve_name docs
python/cpython pull request #24100
Opened 2021-01-04 20:10 UTC by Fongeme

I believe there is not much to add.

2021-01-04 20:10 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@Fongeme

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-01-06 00:06 UTC, brettcannon requested changes

2021-01-06 00:06 UTC, brettcannon commented on Doc/library/importlib.rst
> +   ``importlib.util.resolve_name('sys', __spec__)`` without doing a
```suggestion
   ``importlib.util.resolve_name('sys', __spec__.parent)`` without doing a
```

2021-01-06 00:06 UTC, brettcannon commented on Misc/NEWS.d/next/Documentation/2021-01-04-22-14-22.bpo-42811.HY2beA.rst
> +__package__
```suggestion
Updated importlib.utils.resolve_name() doc to use __spec__.parent
instead of __package__. (Thanks Yair Frid.)
```

2021-01-06 09:50 UTC, Fongeme commented
I have made the requested changes; please review again

2021-01-06 17:42 UTC, brettcannon approved these changes

2021-01-06 17:42 UTC, merged

2021-01-06 17:42 UTC, miss-islington commented
Thanks @Fongeme for the PR 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9.
🐍🍒⛏🤖

2021-01-06 17:42 UTC, miss-islington commented
Sorry @Fongeme, I had trouble checking out the `3.9` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker ff8458b918050168acda1ad6d079f52b8effa821 3.9
                                ```