bpo-42833: make digest algorithms case insensitive
python/cpython pull request #24122
Opened 2021-01-05 16:00 UTC by tardyp

as per https://tools.ietf.org/html/rfc3230#section-4.1.1
digest names shall be case insensitive

2021-01-05 16:00 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@tardyp

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-01-05 16:05 UTC, tiran requested changes
Please use ``SHA`` for testing and wrap the new test function with ``requires_hashdigest("sha1")`` decorator from ``test.support`` package.

2021-01-05 16:11 UTC, tardyp commented
I have made the requested changes; please review again

2021-01-06 13:45 UTC, tardyp commented
@tiran I signed the CLA and fixed the tests. It should be ready to go. thx!

2021-04-07 14:40 UTC, tardyp commented
anything I need to do?

2021-04-07 14:40 UTC, tardyp commented
@tiran ping

2021-04-07 14:43 UTC, tiran requested changes
Could you please add a ``versionchanged`` entry to documentation?

2021-05-27 09:09 UTC, lastthyme approved these changes

2021-08-08 19:34 UTC, ElWeroRanchero approved these changes
Yes

2026-05-05 17:40 UTC, StanFromIreland commented
Closing as stale, the requested changes have not been applied in several years.

2026-05-05 17:40 UTC, closed without merging