Fix for shoutdown process error with python 3.4 and pyqt/PySide
python/cpython pull request #2413
Opened 2017-06-26 16:17 UTC by tucuentafalsa

This is a fix for an error that it is happend when shutdown manager process with a frozen app.
   https://github.com/pyinstaller/pyinstaller/issues/1937

2017-06-26 16:17 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-06-27 15:38 UTC, eryksun commented
This has nothing to do with bpo-1754 (WindowsError messages are not properly encoded). Please reference the correct issue.

2017-06-27 16:19 UTC, alfonnews commented
I think that I reference the correct issue.
Please correct me if it is not

https://github.com/cython/cython/issues/1754

2017-06-27 16:26 UTC, eryksun commented
You created an issue on Cython's issue tracker instead of CPython's issue tracker at bugs.python.org.

2017-06-29 07:59 UTC, alfonnews commented
Ok, Thanks. I fix them.

2017-07-11 12:50 UTC, larryhastings commented
This PR is not targeting the 3.4 branch; it's targeting master.

Python 3.4 is in "security fixes only" mode.  Since this is not a "security fix", it will not be accepted into the 3.4 branch.  Please either change the description so it doesn't mention 3.4, or close the PR.

2017-07-22 19:24 UTC, larryhastings commented
If there are no changes to this issue in two weeks, I will close it.

2017-07-24 22:54 UTC, terryjreedy requested changes
I think this should be closed.

2017-07-24 22:54 UTC, terryjreedy commented on Lib/multiprocessing/process.py
> +            if sys.platform.startswith('win') and sys.version_info[:2] == (3, 4):
The version check makes this useless in any other version.

2017-07-24 22:54 UTC, terryjreedy commented on Lib/multiprocessing/process.py
> +import imp
Deprecated in 3.4.  A patch using deprecated modules will not be accepted.

2017-07-24 22:54 UTC, terryjreedy commented on Lib/multiprocessing/process.py
> +                    sys.stderr.flush()
The fact that one frozen module crashes from the flushes does not mean that all frozen modules will or that suppressing flushes will not harm other frozen modules.  The fact that other frozen modules do run on various versions of Python suggest that the problem is with the particular frozen module.  This suggests to me that the patch is in general wrong and should be rejected now.

2017-07-28 17:36 UTC, larryhastings commented
Ouch.  Yeah, this code is awful and would never be merged.

@alfonnews: in the future, if you're interested in contributing to CPython, you should know that we have very high code quality standards.  Your PR here is a "band-aid"; it doesn't fix the problem (whatever it is), it merely works around it.  To be honest I still have no idea what problem you're solving.  And the comments by @terryjreedy are all spot on.

2017-07-28 17:36 UTC, closed without merging

2017-11-10 13:06 UTC, alfonnews commented
I agree, in any case sorry for the inconvenience.
My intention was to expose the concrete problem and a casuistic that solves it, not as a final solution but as a starting point to detect the underlying problem and its correct solution.
I understand that it is not the right way for this. Thanks for corrections and suggestions