bpo-24464: Call sqlite3.enable_shared_cache() from deprecation wrapper
python/cpython pull request #24170
Opened 2021-01-08 18:33 UTC by erlend-aasland

2021-01-08 18:34 UTC, erlend-aasland commented
Thanks for spotting this, @mrluanma.

2021-01-08 18:35 UTC, erlend-aasland commented
@berkerpeksag or @serhiy-storchaka, can one of you review and apply this? #skipnews

2021-01-08 18:36 UTC, erlend-aasland commented
Regression caused by #24008

2021-01-08 20:49 UTC, erlend-aasland commented
Fixed macOS tests. Ready for review, @berkerpeksag / @serhiy-storchaka

2021-01-08 23:30 UTC, berkerpeksag requested changes

2021-01-08 23:30 UTC, berkerpeksag commented on Lib/sqlite3/test/dbapi.py
> +                    self.assertEqual(sys.platform, 'darwin')
I'd rather skip the test here if OperationalError was caused by:

> This method is disabled on MacOS X 10.7 and iOS version 5.0 and will always return SQLITE_MISUSE.

2021-01-08 23:30 UTC, berkerpeksag commented on Lib/sqlite3/test/dbapi.py
> +                    self.assertEqual(sys.platform, 'darwin')
Also, third-party links tend to change so I'd prefer explaining why we are doing this in a comment instead of just linking to SQLite docs.

2021-01-09 09:03 UTC, erlend-aasland commented
I have made the requested changes; please review again

2021-01-09 11:01 UTC, berkerpeksag approved these changes

2021-01-09 11:25 UTC, merged

2021-01-09 11:26 UTC, berkerpeksag commented
Thank you.