bpo-42766 Fixed 2 bugs in urllib.request.HTTPPasswordMgr.is_suburi and added some tests for it
python/cpython pull request #24181
Opened 2021-01-09 20:31 UTC by Fongeme

I kinda ran out of time, i suspect more testing is due.
I patched is_suburi to fit the doc string, because a certain test failed for me:

`assertFalse(is_suburi(reduce_uri('http://example.com/sub_dir/sub_dir'), reduce_uri('http://example.com/sub_dir')))`

This issue was not yet triaged but i suspect we have more problems with this function, i might free up more time for tests later this week :)

2021-07-06 17:02 UTC, taleinat commented
Closing and re-opening to restart a stuck CI check.

2021-07-06 21:13 UTC, terryjreedy commented
The Pipelines failure is a single repeated test_asyncio failure in one of the 5 sets of tests.  It can be ignored.

2021-07-06 22:19 UTC, terryjreedy requested changes
A failing example should have been added to each of the two PRs and a clear determination made if the second is a duplicate of the first or not.

2021-07-06 22:19 UTC, terryjreedy commented on Lib/urllib/request.py
> +        """Check if test is below base in a URI tree (inclusive)
What does 'inclusive' mean here?

2021-07-06 22:19 UTC, terryjreedy commented on Lib/test/test_urllib2.py
> +        self.assertFalse(is_suburi(reduce_uri('http://example.com/sub_dir_diff'), reduce_uri('http://exmaple.com/sub_dir_second_diff')))
A line break and abbreviation are needed to keep within 80 chars.
```suggestion
        true = self.assertTrue
        false = self.assertFalse
        true(is_suburi(reduce_uri('http://example.com'),
                       reduce_uri('http://example.com/sub_dir')))
        true(is_suburi(reduce_uri('http://example.com/sub_dir'),
                       reduce_uri('http://example.com/sub_dir/sub_dir')))
        false(is_suburi(reduce_uri('http://example.com/sub_dir/sub_dir'),
                        reduce_uri('http://example.com/sub_dir')))
        false(is_suburi(reduce_uri('http://example.com/second_dir'),
                        reduce_uri('http://example.com/first_dir/second_dir')))
        false(is_suburi(reduce_uri('http://example.com/sub_dir'),
                        reduce_uri('http://example.com/sub')))
        false(is_suburi(reduce_uri('http://example.com/sub_dir'),
                        reduce_uri('http://exmaple.com/sub_dir_diff')))
        false(is_suburi(reduce_uri('http://example.com/sub_dir_diff'),
                        reduce_uri('http://exmaple.com/sub_dir_second_diff')))
```
I think that the last two tests are redundant.

2021-07-07 05:49 UTC, Fongeme commented on Lib/urllib/request.py
> +        """Check if test is below base in a URI tree (inclusive)
e.g, is_suburi(base, base) is True

2021-07-07 05:50 UTC, Fongeme commented on Lib/urllib/request.py
> +        """Check if test is below base in a URI tree (inclusive)
Should i rephrase?

2021-07-07 05:58 UTC, Fongeme commented on Lib/urllib/request.py
> +        """Check if test is below base in a URI tree (inclusive)
If we look at is_suburi as an ordering function, this is weak ordering

2021-07-07 11:41 UTC, terryjreedy commented on Lib/urllib/request.py
> +        """Check if test is below base in a URI tree (inclusive)
Would 'test equal or below base' be accurate?  I know what partial order is, not 'weak order'.

2021-07-12 06:46 UTC, Fongeme commented on Lib/urllib/request.py
> +        """Check if test is below base in a URI tree (inclusive)
Yes, i meant partial ordering
```suggestion
        """Check if test is equal or below base in a URI tree
```

2021-07-12 06:46 UTC, Fongeme commented
I have made the requested changes; please review again

2022-02-21 05:01 UTC, akulakov commented on Lib/test/test_urllib2.py
> +        true(is_suburi(reduce_uri('http://example.com'),
It would be easier to understand the logic tested if there was a blank line between each subtest.

2022-02-21 05:02 UTC, akulakov commented on Lib/urllib/request.py
> +        if base[0] != test[0] or len(test[1]) < len(base[1]):
The test cases pass even if this change is not included. Are you sure it's needed?

2022-02-21 05:02 UTC, akulakov commented on Misc/NEWS.d/next/Library/2021-01-09-22-36-01.bpo-42766.6ybdUr.rst
> +Fixed 2 bugs in urllib.request.HTTPPasswordMgr.is_suburi, added some tests
It would be useful to shortly describe the 2 bugs being fixed.

2022-02-21 14:14 UTC, akulakov commented
It looks like this is being fixed in https://github.com/python/cpython/pull/31353

2022-02-25 12:11 UTC, serhiy-storchaka commented
This PR was good in general, but this issue has been solved in #31353.

Few minor issues with this PR:
1. Using `posixpath.commonpath()` may look more general, supporting patches with duplicated slashes, but actually it is not, because they'll do not pass test `len(common) == len(base[1])`.
2. Private function `is_suburi()` is used in tests. #31353 tests use only public API.

It would be easy to address these comments, but an alternate PR was already written. In any case thank you. See for your future PRs.

2022-02-25 12:11 UTC, closed without merging