Make dyld search work with SYSTEM_VERSION_COMPAT=1
python/cpython pull request #24324
Opened 2021-01-25 09:28 UTC by isuruf

In macOS Big Sur, if the executable was compiled with `MACOSX_DEPLOYMENT_TARGET=10.15`
or below, then SYSTEM_VERSION_COMPAT=1 is the default which means that Big Sur
reports itself as 10.16 which means that `__builtin_available(macOS 11.0)` will not be triggered.

This can be observed by using the python 3.9.1 universal2 installer and using it on
x86_64 Big Sur or with Rossetta 2 on arm64 Big Sur. (Not an issue with native arm64
as that part is compiled with `MACOSX_DEPLOYMENT_TARGET=11.0`)

cc @ronaldoussoren

2021-01-25 09:29 UTC, isuruf commented
Original issue is that the following returned None.
`SYSTEM_VERSION_COMPAT=1 arch -x86_64 /usr/local/bin/python3 -c "from ctypes.util import find_library; print(find_library('AppKit'))"`

2021-01-28 03:59 UTC, ned-deily commented
Thank you for the PR. Please open an issue for this on [bugs.python.org](https://bugs.python.org) and add the issue number to the PR as described in the [Python Developers Guide](https://devguide.python.org/pullrequest/#quick-guide).

2021-01-28 12:13 UTC, ronaldoussoren commented
Is there documentation how this works? In particular, documentation that shed a light on what will happen once macOS 12 is released.

There are other checks for macOS 11 using __builtin_available, and there may be similar checks for macOS 12 later on. I wonder how that will work ``SYSTEM_VERSION_COMPAT=1``.

2021-01-28 14:02 UTC, isuruf commented
I don't know. I only saw https://eclecticlight.co/2020/08/13/macos-version-numbering-isnt-so-simple/

Consider the following program A,
```
int main() {
  if (__builtin_available(11.0)) {
    return 1;
  } else {
    return 0;
  }
}
```
and program B,
```
int main() {
  if (__builtin_available(10.16)) {
    return 1;
  } else {
    return 0;
  }
}
```

compile A with `clang -arch x86_64 -mmacosx-version-min=11.0` and run it, it will return 1.
compile A with `clang -arch x86_64 -mmacosx-version-min=10.9` and run it, it will return 0.
compile B with `clang -arch x86_64 -mmacosx-version-min=11.0` and run it, it will return 1.
compile B with `clang -arch x86_64 -mmacosx-version-min=10.9` and run it, it will return 1.

For macOS 12, I have no idea how it will work. (probably, it'll be 10.17, but that's pure speculation on my part)

2021-02-01 04:53 UTC, ned-deily commented
See [my comment](https://bugs.python.org/issue43052#msg386055) about this on the bug tracker.

2021-03-04 02:53 UTC, ned-deily requested changes
It hasn't been established yet that this change is needed. See the discussion here on the PR and on the bug tracker. Without further justification, I would suggest we close the PR.

2022-02-01 15:25 UTC, ronaldoussoren commented
> It hasn't been established yet that this change is needed. See the discussion here on the PR and on the bug tracker. Without further justification, I would suggest we close the PR.

I agree. This *only* affects users running with "SYSTEM_VERSION_COMPAT" set in the environment, ``find_library`` works correctly otherwise.

2022-02-01 15:25 UTC, closed without merging