bpo-43125: Fix: return expected type (str), not original value (bytes)
python/cpython pull request #24476
Opened 2021-02-07 18:40 UTC by gst

All in title.

the utility function `Lib/email/base64mime.py::body_encode` :

```
def body_encode(s, maxlinelen=76, eol=NL):
```

returns its given input if this ones evaluates to False. This is bad. given the expected input is bytes but the expected output is str. ( `return EMPTYSTRING.join(encvec)` ). 

The fix looks obvious: return an empty string instead of the original object (whatever type it might be).

2021-02-09 10:52 UTC, gst commented
@matrixise 

my first PR ! :) 

what's next ?

2021-02-22 00:56 UTC, corona10 approved these changes
lgtm
but @serhiy-storchaka Can you please take a look also?

2021-02-22 01:00 UTC, corona10 commented on Misc/NEWS.d/next/Library/2021-02-07-19-13-30.bpo-43125.AqNoMa.rst
> +Fix: return expected type (str), not original value (bytes) in Lib/email/base64mime.py
```suggestion
Return empty string if base64mime.body_encode receive empty bytes
```

2021-02-22 01:00 UTC, corona10 commented on Lib/test/test_email/test_email.py
> +        eq(base64mime.body_encode(b''), '')  # empty bytes ? empty string !
```suggestion
        eq(base64mime.body_encode(b''), '') # bpo-43125
```

2021-03-03 16:23 UTC, gst commented
@corona10 @serhiy-storchaka 

I made the changes. what's next step ?

2021-03-08 13:44 UTC, matrixise requested changes

2021-03-08 13:44 UTC, matrixise commented on Lib/test/test_email/test_email.py
> +        eq(base64mime.body_encode(b''), '')  # bpo-43125
You don't need to add `# bpo-43125`

2021-03-08 13:51 UTC, gst commented on Lib/test/test_email/test_email.py
> +        eq(base64mime.body_encode(b''), '')  # bpo-43125
fixed.

2021-03-10 12:38 UTC, gst commented
I have made the requested changes; please review again

2021-03-19 10:43 UTC, gst commented
@matrixise @corona10  ?

2021-03-30 08:36 UTC, corona10 approved these changes
lgtm

2021-03-30 08:37 UTC, merged