bpo-36859: use sqlite3_stmt_readonly() to detect DML statements
python/cpython pull request #24492
Opened 2021-02-09 14:38 UTC by erlend-aasland

2021-02-09 14:39 UTC, erlend-aasland commented
Cherry-picked from #13216 and rebased onto master.

cc. @berkerpeksag @coleifer @serhiy-storchaka

2021-03-02 09:09 UTC, erlend-aasland commented on Modules/_sqlite/statement.c
> +                      PyOS_strnicmp(p, "vacuum", 6));
I don't think we need all of those.

- `sqlite3_stmt_readonly()` with `ALTER` statement returns `0`
- `sqlite3_stmt_readonly()` with `VACUUM` statement returns `0`
- `sqlite3_stmt_readonly()` with `ANALYZE` statement returns `0`
- `sqlite3_stmt_readonly()` with `DROP` statement returns `0`
- `sqlite3_stmt_readonly()` with `CREATE` statement that actually creates a new item returns `0`
- `sqlite3_stmt_readonly()` with `CREATE` statement that resolves to a no-op returns `1`

2022-04-04 11:05 UTC, MaxwellDupre requested changes
Ran 18 tests in 0.481s
OK
Other Sqlite tests also passed. Looks ok.
Need to add to Docs, not just NEWS otherwise users will not be aware.

2022-06-27 08:01 UTC, erlend-aasland commented
I'm not sure this is the correct way to address to the problems in the linked issue. Closing.

2022-06-27 08:01 UTC, closed without merging