[DOC] Add missing value returned by methods on cookiejar
python/cpython pull request #24522
Opened 2021-02-13 00:00 UTC by eamanu

Documentation say that return something but don't specific with what
value is return, and that can be confuse. This patch add that information.

2021-02-14 20:28 UTC, eamanu commented
Re open to know if the tests pass

2021-07-07 13:25 UTC, akulakov requested changes
Thanks!, - this is a good change that makes return value much clearer. Requesting a small change because 'whether' would not be gramatically correct to leave in with this change.

2021-07-07 13:25 UTC, akulakov commented on Doc/library/http.cookiejar.rst
> +   Return ``True`` whether *domain* is on the blocklist for setting or receiving
```suggestion
   Return ``True`` if *domain* is on the blocklist for setting or receiving
```

2021-07-07 13:25 UTC, akulakov commented on Doc/library/http.cookiejar.rst
> +   Return ``True`` whether *domain* is not on the allowlist for setting or receiving
```suggestion
   Return ``True`` if *domain* is not on the allowlist for setting or receiving
```

2021-07-07 15:52 UTC, eamanu commented
Thanks @akulakov

2021-11-15 22:43 UTC, willingc approved these changes

2021-11-15 22:44 UTC, merged