bpo-43353: Document that logging.getLevelName() accepts string representation of logging level.
python/cpython pull request #24693
Opened 2021-03-01 21:37 UTC by felixxm

bpo-43353

2021-03-07 09:14 UTC, vsajip requested changes

2021-03-07 09:14 UTC, vsajip commented on Lib/logging/__init__.py
>      Otherwise, the string "Level %s" % level is returned.
Suggest changing this to "If no matching numeric or string value is passed inm the string 'Level %s' % level is returned."

2021-03-07 09:14 UTC, vsajip commented on Doc/library/logging.rst
> +   Otherwise, the string 'Level %s' % level is returned.
Suggest changing this to "If no matching numeric or string value is passed inm the string 'Level %s' % level is returned."

2021-03-07 09:28 UTC, felixxm commented
@vsajip Thanks for the review :+1: 

I have made the requested changes; please review again.

2021-03-08 11:15 UTC, vsajip approved these changes

2021-03-08 11:16 UTC, merged

2021-03-08 11:16 UTC, miss-islington commented
@felixxm: Status check is done, and it's a success ✅ .

2021-03-08 11:16 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `Pull Request is not mergeable`.