bpo-43362: Fix bad free in py_sha3_new_impl function
python/cpython pull request #24702
Opened 2021-03-02 02:52 UTC by alexhenrie

Initializing `buf.obj` to `NULL` earlier in the function prevents the possibility of `PyBuffer_Release` being called on an invalid object.

2021-03-03 18:08 UTC, auvipy requested changes
can you check function declaration isn’t a prototype [-Wstrict-prototypes]? also doesn't this need some change in tests?

2021-04-17 21:18 UTC, tiran commented
Please rebase the PR and provide a blurb (news entry).

2021-04-17 21:18 UTC, tiran requested changes
Please rebase the PR and provide a blurb (news entry).

2021-04-17 22:58 UTC, tiran commented
I have found another potential problem and opened https://github.com/python/cpython/pull/25463. You are mentioned as co-author. Thanks for your assistance!

2021-04-17 22:58 UTC, closed without merging

2021-05-06 02:40 UTC, alexhenrie commented
@tiran Thank you!