bpo-43381: Add frozen module co_lines() test
python/cpython pull request #24712
Opened 2021-03-03 01:01 UTC by nascheme

2021-03-03 07:48 UTC, nascheme commented
This PR will fail until `__hello__` frozen module is re-generated, e.g. PR #24714.

2021-07-05 16:08 UTC, akulakov commented on Lib/test/test_frozen.py
> +        # Invalid marshalled data in frozen.c could case the interpreter to
case/cause

2021-07-05 16:16 UTC, akulakov commented on Lib/test/test_frozen.py
> +    @impl_detail('code object line table', cpython=True)
a small nitpick: cpython arg is not needed and other uses of @impl_detail in tests leave it out (with just one exception).

2022-11-27 21:21 UTC, iritkatriel requested changes
This has merge conflicts now.

2022-11-28 21:15 UTC, nascheme commented
This PR seems obsolete now since Eric Snow added some tests to `test_frozen` (e.g. gh-28664).  Closing it and the issue.

2022-11-28 21:15 UTC, closed without merging