bpo-42128: Implement AST validation for Pattern Matching
python/cpython pull request #24771
Opened 2021-03-06 10:52 UTC by isidentical

2021-05-16 17:48 UTC, brandtbucher reviewed
Hi @isidentical!

I think I missed this in the beta-freeze scramble. Any plans to update it for the new AST?

2021-05-16 17:51 UTC, isidentical commented
> I think I missed this in the beta-freeze scramble. Any plans to update it for the new AST?

I might take a look at it in the upcoming weeks though I don't think I would have enough capacity to catch up with beta 2 (9 days from now). If you have time, I could give access to my fork if not I'll try to make it ready for beta 3.

2021-05-16 18:27 UTC, brandtbucher commented
Beta 3 is fine!

2021-06-12 17:45 UTC, isidentical commented
Hey @brandtbucher! I've updated the PR with the new AST form, sorry it took a bit long. I didn't have much free time after the AST layout change, and needed to catch up with the new nodes first. Just ported all the missing pieces, there are still some bugs that I can see (for example some of the old parts of the validator code just quit when error happens, but doesn't decrement the recursion limit. Since I didn't touch those and the patch was already big I just skipped them now, might fix later) but nothing too big. Please let me know any missing stuff that I should handle.

2021-06-30 21:13 UTC, brandtbucher requested changes
Thanks, this looks really good! I just have a few comments:

2021-06-30 21:13 UTC, brandtbucher commented on Lib/test/test_ast.py
> +                            body = [ast.Expr(ast.Constant(...))]
Took me a sec to see what was happening here. Maybe clearer as `ast.Pass()`?
```suggestion
                            body = [ast.Pass()]
```

2021-06-30 21:13 UTC, brandtbucher commented on Lib/test/test_ast.py
> +        ),
This looks the exact same as the pattern above, right?

```suggestion
```

2021-06-30 21:13 UTC, brandtbucher commented on Python/ast.c
> +        }
I don't think these braces are needed, right?

```suggestion
        case Constant_kind:
            /* Ellipsis and immutable sequences are not allowed.
               For True, False and None, MatchSingleton() should
               be used */
            if (!validate_expr(state, exp, Load)) {
                return 0;
            }
            PyObject *literal = exp->v.Constant.value;
            if (PyLong_CheckExact(literal) || PyFloat_CheckExact(literal) ||
                PyBytes_CheckExact(literal) || PyComplex_CheckExact(literal) ||
                PyUnicode_CheckExact(literal)) {
                return 1;
            }
            PyErr_SetString(PyExc_ValueError,
                            "unexpected constant inside of a literal pattern");
            return 0;
```

2021-06-30 21:13 UTC, brandtbucher commented on Python/ast.c
>                  return 0;
```suggestion
                ret = 0;
                break;
```

2021-06-30 21:13 UTC, brandtbucher commented on Python/ast.c
> +        case MatchMapping_kind: {
These braces aren't needed either, right?

```suggestion
        case MatchMapping_kind:
```

2021-06-30 21:13 UTC, brandtbucher commented on Python/ast.c
> +        }
See above.

```suggestion
```

2021-06-30 21:13 UTC, brandtbucher commented on Python/ast.c
> +                } else {
```suggestion
                }
                else if (cls->kind == Attribute_kind) {
                    cls = cls->v.Attribute.value;
                    continue;
                }
                else {
```

2021-06-30 21:13 UTC, brandtbucher commented on Python/ast.c
>                  return 0;
```suggestion
                ret = 0;
                break;
```

2021-06-30 21:13 UTC, brandtbucher commented on Python/ast.c
>                  return 0;
```suggestion
                ret = 0;
                break;
```

2021-06-30 21:20 UTC, brandtbucher commented
> Just ported all the missing pieces, there are still some bugs that I can see (for example some of the old parts of the validator code just quit when error happens, but doesn't decrement the recursion limit. Since I didn't touch those and the patch was already big I just skipped them now, might fix later) but nothing too big.

Sorry, didn't see this. Feel free to ignore those suggestions, then!

I can find time to go back over those and fix the `"_"` name validation issue sometime if you're too busy. Just let me know.

2021-07-08 19:48 UTC, isidentical commented
> I can find time to go back over those and fix the "_" name validation issue sometime if you're too busy. Just let me know.

What do you mean by the `_` validation (example case would be welcome)? By the way feel free to apply style suggestions by yourself since it is quite hard to deal with that sort of diffs in GitHub interface :(

2021-07-28 17:13 UTC, brandtbucher commented
> What do you mean by the `_` validation (example case would be welcome)?

Patterns like `MatchMapping(..., rest="_")`, `MatchStar("_")`, and `MatchAs(..., name="_")` should be rejected, but aren't.

Also, `MatchStar` is allowed as a top-level pattern, but shouldn't be. I'll just merge this and fix those, the remaining recursion depth bugs, and remove some outdated comments in a new PR today (it will be easier to backport to 3.10 that way).

2021-07-28 17:14 UTC, merged

2021-07-28 17:17 UTC, brandtbucher commented
Thanks again! Sorry I kept dropping the ball on this, haha.