bpo-43429: mmap.size() now returns the size on Unix for anonymous memory
python/cpython pull request #24781
Opened 2021-03-07 23:33 UTC by ZackerySpytz

Previously, the size would be returned on Windows and an OSError would
be raised on Unix.

2023-05-12 17:07 UTC, furkanonder requested changes
LGTM. @ZackerySpytz Could you resolve the conflicts?

2023-05-12 17:53 UTC, arhadthedev commented
Marking as <kbd>needs backport to 3.11</kbd> because the parent issue is marked as https://github.com/python/cpython/labels/type-bug.

2023-05-12 18:44 UTC, furkanonder approved these changes

2023-05-14 12:28 UTC, iritkatriel commented on Doc/library/mmap.rst
> +
If this is going to be backported to 3.11 then versionchanged should be 3.11.

2025-08-29 09:50 UTC, serhiy-storchaka commented
@ZackerySpytz, could you please update your PR to 3.15? It should take into account `trackfd`, as in #138198.

2025-09-02 16:38 UTC, vstinner commented
I'm not sure that @ZackerySpytz is still active. Maybe a new PR should be written?

2025-09-02 20:24 UTC, merged

2025-09-02 20:44 UTC, ZackerySpytz reviewed
Hello, @serhiy-storchaka. We must modify some of the changes you have made to this PR.

2025-09-02 20:44 UTC, ZackerySpytz commented on Doc/library/mmap.rst
> +      For anonymous mapping, return its size.
```suggestion
      For an anonymous mapping, return its size.
```

2025-09-02 20:44 UTC, ZackerySpytz commented on Doc/library/mmap.rst
> +         Supports anonymous mapping on Unix.
```suggestion
         Anonymous mappings are now supported on Unix.
```

2025-09-02 20:44 UTC, ZackerySpytz commented on Misc/NEWS.d/next/Library/2021-03-07-16-31-36.bpo-43429.Koa0mf.rst
> +Raise :exc:`ValueError` instead of :exc:`OSError` with ``trackfd=False``.
```suggestion
would be raised on Unix. :exc:`ValueError` is now raised instead of
:exc:`OSError` with ``trackfd=False``.
```

2025-09-02 20:54 UTC, AA-Turner commented
@ZackerySpytz this has been merged, please would you open a new PR?

2025-09-02 20:59 UTC, ZackerySpytz commented
I'm well aware that this PR has been merged, thank you very much.

2025-09-04 10:43 UTC, ZackerySpytz commented
@serhiy-storchaka I have created GH-138494.