bpo-26506: hex() documentation: mention "%x" % int
python/cpython pull request #2479
Opened 2017-06-28 16:54 UTC by sharanry

Refs:
[http://bugs.python.org/issue26506](http://bugs.python.org/issue26506)

2017-06-28 16:54 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-06-28 19:40 UTC, haypo commented on Doc/library/functions.rst
> +      >>> format(num, '#b'), format(num, 'b')
I suggest to remove the num variable and just write 14 directly, to simplify examples (and easier to copy/paste).

2017-06-28 19:40 UTC, haypo commented on Doc/library/functions.rst
> +   also :func:`format` for more information.
I suggest to move the "See also..." sentence *after* the examples.

2017-06-28 19:40 UTC, haypo commented on Doc/library/functions.rst
> +   also :func:`format` for more information.
Ditto, move "See also ..." above.

2017-06-28 19:40 UTC, haypo commented on Doc/library/functions.rst
> +      >>> num=255
Ditto: replace num by its value (and remove num).

2017-06-28 19:41 UTC, haypo commented
"Original patch by Manvi B", hum, please put this string in the commit message (use "git commit --amend" for example to edit the commit message), and include the email: manvishab77@gmail.com.

2017-06-28 19:41 UTC, vstinner requested changes
(Please make suggested changes.)

2017-06-28 20:49 UTC, Mariatta commented
Regarding the commit message, the core developer who merge this PR can manually type it in after they press the "Squash and merge" button :)

2017-06-28 21:21 UTC, haypo commented on Doc/library/functions.rst
> +      func:`format` for more information.
This line is strange...  I suggest to put "See also ..." sentence after the following ">>> ..." examples.

2017-06-28 21:31 UTC, sharanry commented
@haypo I have made the changes you asked. Please review them.

2017-06-29 07:18 UTC, haypo commented on Doc/library/functions.rst
> +   See also :
I don't understand why :func:`format` is splitted in two lines. I expect an error when building the doc. Please don't split this statement into two lines.

2017-06-29 07:23 UTC, vstinner requested changes

2017-06-29 07:23 UTC, haypo commented on Doc/library/functions.rst
> +      func:`format` for more information.
Please move "See also .." after the example.

2017-06-29 07:23 UTC, haypo commented on Doc/library/functions.rst
> +   more information.
Same here. I already asked you to do that :-(

2017-06-29 07:49 UTC, sharanry commented on Doc/library/functions.rst
> +   See also :
I don't understand what you are saying. Could you please be more specific?

2017-06-29 07:51 UTC, haypo commented on Doc/library/functions.rst
> +   See also :
You have ":" on line 102 and "func:`format`" on line 103. The documentation uses the Sphinx format. I don't think that your syntax is valid. Please write ":func:`format`" on the same line.

2017-06-29 07:57 UTC, sharanry commented on Doc/library/functions.rst
> +   See also :
Never mind i understood what you are saying. Thanks!

2017-06-29 08:06 UTC, vstinner approved these changes

2017-06-29 08:07 UTC, haypo commented
@Mariatta: Would you mind to take a look to confirm that the doc change is fine. I don't know if we can "merge" the two "See also ..." sentence of the hex() doc. I don't know if t's worth it. Maybe just put them in the same paragraph?

2017-06-29 13:33 UTC, kushaldas commented
I think we should ask the original author if she wants to submit the PR.

2017-06-29 19:41 UTC, manvi77 commented
I am the original contributor. I will look into it again and can submit the PR.

2017-06-30 17:12 UTC, Mariatta commented
> I think we should ask the original author if she wants to submit the PR.

I agree. I've just updated the Dev guide with guidance and protocol for converting the patches to PR:
https://devguide.python.org/pullrequest/#converting-an-existing-patch-from-the-b-p-o-to-github

> I am the original contributor. I will look into it again and can submit the PR.

Please do.

2017-07-01 03:09 UTC, vadmium commented on Doc/library/functions.rst
> +   See also :func:`int` for converting a hexadecimal string to an integer using a base of 16.
_Hexadecimal_ and _base of 16_ seems redundant

2017-07-01 03:09 UTC, vadmium commented on Doc/library/functions.rst
> +   If you want to convert an integer number to uppercase or lowercase hexadecimal
. . . to _an_ uppercase or lowercase . . .

2017-07-01 07:15 UTC, manvi77 commented on Doc/library/functions.rst
> +   See also :func:`int` for converting a hexadecimal string to an integer using a base of 16.
yes, removing it.

2017-07-01 09:30 UTC, manvi77 commented on Doc/library/functions.rst
> +   See also :func:`int` for converting a hexadecimal string to an integer using a base of 16.
What I meant is an integer using base of 16, for eg., int('0xff', 16). If it is redundant, I can remove it.

2017-07-06 22:37 UTC, Mariatta commented
Thanks for the PR @sharanry 
However, I accepted PR #2525 from the original author. So I will close this.
I hope you'll continue working on another issue in the bug tracker and submit a different PR.
Thanks.

2017-07-06 22:37 UTC, closed without merging