bpo-43132: Add tests for find_in_strong_cache() bug in _zoneinfo
python/cpython pull request #24829
Opened 2021-03-11 22:56 UTC by ZackerySpytz

Co-Authored-By: Paul Ganssle <p.ganssle@gmail.com>

2025-06-29 16:51 UTC, StanFromIreland commented
Serhy, since you merged https://github.com/python/cpython/pull/24450, maybe you can review the tests?

2025-07-01 14:55 UTC, merged

2025-07-01 15:07 UTC, pganssle requested changes

2025-07-01 15:07 UTC, pganssle commented on Lib/test/test_zoneinfo/test_zoneinfo.py
> +    def test_clear_cache_refleak(self):
Apparently I wrote this function 4 years ago, but coming back to it now it is opaque as heck, so we should probably describe what this test is about.

```suggestion
    def test_clear_cache_refleak(self):
        # bpo-43132: The portion of the C implementation of ZoneInfo that
        # ejects specific keys from the strong cache (i.e. the LRU cache) was
        # leaking references if comparing to the key object failed; because the
        # strong cache is not currently implemented for subclasses, this test
        # only really applies to the C implementation of the ZoneInfo class.
```

2025-07-01 15:07 UTC, pganssle commented on Lib/test/test_zoneinfo/test_zoneinfo.py
> +            # Note: This is try/except rather than assertRaises because
I realize that I wrote this function, but it kind of bothers me that this can silently become a no-op (and in fact this is silently a no-op for all subclasses `ZoneInfo`). I think that the only way around it is fairly annoying if we want to allow tests to run in parallel, which is that we would need to acquire a lock around anything that deals with the cache.

2025-07-01 15:07 UTC, pganssle commented on Lib/test/test_zoneinfo/test_zoneinfo.py
> +        self.klass(key)
To increase the chance that this actually works:

```suggestion
        self.klass.clear_cache(only_keys="America/Los_Angeles")
        self.klass(key)
```

2025-07-01 15:07 UTC, pganssle commented on Lib/test/test_zoneinfo/test_zoneinfo.py
> +    def test_clear_cache_refleak(self):
We may also want to skip this test if `self.klass` is not exactly the C implementation of `ZoneInfo`, since otherwise it's a no-op.

2025-07-01 15:08 UTC, pganssle commented
Oof, missed the window for this by 12 minutes.

2025-07-01 16:13 UTC, serhiy-storchaka commented
Sorry, the PR was already on auto-merge.