bpo-24766: doc= argument to subclasses of property not handled correctly
python/cpython pull request #2487
Opened 2017-06-29 08:46 UTC by embray

Here's a PR for a small fix I've had languishing for it looks like a couple years now.  Do I need to add a blurb as well?

2017-06-29 23:13 UTC, ethanfurman approved these changes

2017-09-16 14:24 UTC, mscuthbert commented
should this have "awaiting merge" as a tag?

2017-10-06 09:37 UTC, embray commented
I don't know. I guess?

2017-10-07 20:15 UTC, serhiy-storchaka requested changes

2017-10-07 20:15 UTC, serhiy-storchaka commented on Objects/descrobject.c
> +            Py_DECREF(get_doc);
`get_doc` is NULL here, isn't?

2017-10-07 20:15 UTC, serhiy-storchaka commented on Objects/descrobject.c
> +                                      self->prop_doc);
`self->prop_doc` can be NULL.

2018-10-09 15:03 UTC, embray commented on Objects/descrobject.c
> +            Py_DECREF(get_doc);
Yes, the decref is no good here.

2018-10-09 15:18 UTC, embray commented
Forgot about this for a ah, long time.
Rebased on latest master and addressed Serhiy's review comments.

2018-10-09 15:46 UTC, serhiy-storchaka commented
```
>>> class NoDoc:
...     @property
...     def __doc__(self):
...         raise AttributeError
... 
>>> class PropertySub(property):
...     """This is a subclass of property"""
... 
>>> property(NoDoc()).__doc__
>>> PropertySub(NoDoc()).__doc__
'This is a subclass of property'
```

2018-10-09 15:54 UTC, embray commented
I see...  is there a test for this (bizarre) case?  Perhaps there should be?

2018-10-09 15:57 UTC, embray commented
In fact, I'm not really sure what you're suggesting be done here.

2018-10-09 16:01 UTC, serhiy-storchaka commented
I suggest that the `property` subclass should be consistent with `property`, i.e. return None.

There is no test for this case, and I suggest to add one.

2018-10-09 16:03 UTC, embray commented
I agree, though this appears to be a different issue.  Your case is broken the same way with or without this patch and is not the same as the specific issue that this is fixing.  Though I don't mind fixing both as long as I'm monkeying around in there...

2018-10-12 11:36 UTC, serhiy-storchaka commented
It looks just as a corner case of the original. I think it should be fixed in this PR.

2020-01-25 23:41 UTC, csabella commented
@embray, please address Serhiy's last comment and also resolve the merge conflict.  Thank you!

2020-01-28 13:40 UTC, embray commented
@csabella Rebased, and addressed @serhiy-storchaka's corner case, which I agree was related.

2020-08-04 12:44 UTC, embray commented
Rebased again; @serhiy-storchaka's change request is implemented.

2022-04-15 14:09 UTC, embray commented
Looks like it needs a minor rebase yet again.  But there's no other reason not to move forward on this minor bug fix, I think.

2023-12-15 13:08 UTC, serhiy-storchaka approved these changes

2023-12-16 19:34 UTC, terryjreedy commented
@embray Please click the button in  https://github.com/python/cpython/pull/2487#issuecomment-1857848446  to re-sign the CLA with your current GH email.  It is needed to merge here.

2024-06-10 08:55 UTC, merged