Fix bug in netrc.__repr__()
python/cpython pull request #2491
Opened 2017-06-29 19:09 UTC by Bezier89

2017-06-29 19:09 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-08-03 07:41 UTC, methane requested changes

2017-08-03 07:41 UTC, methane commented on Lib/netrc.py
> +            rep = rep + "machine "+ host + "\n\tlogin " + str(attrs[0]) + "\n"
```
rep += f"machine {host}\n\tlogin {attrs[0]}\n"
```

2017-08-03 07:41 UTC, methane commented on Lib/netrc.py
> +            rep = rep + "\tpassword " + str(attrs[2]) + "\n"
```
    rep += f"\taccount {attrs[1]}\n"
rep += f"\tpassword {attrs[2]}\n"
```

2017-08-03 12:35 UTC, Bezier89 commented on Lib/netrc.py
> +            rep = rep + "machine "+ host + "\n\tlogin " + str(attrs[0]) + "\n"
Done

2017-08-03 12:35 UTC, Bezier89 commented on Lib/netrc.py
> +            rep = rep + "\tpassword " + str(attrs[2]) + "\n"
Done

2017-09-15 19:33 UTC, Bezier89 commented
@methane, I updated this to use f-strings. Is there anything else that needs to be done for this to be merged?

2017-09-16 11:56 UTC, methane commented
Sorry for delay.
Would you add NEWS file and test?

2017-09-16 12:03 UTC, methane commented
See https://devguide.python.org/committing/#what-s-new-and-news-entries for how to create NEWS entry file.

2017-09-29 19:49 UTC, Bezier89 commented
@methane This is done. Let me know if it looks good!

2017-09-30 07:08 UTC, methane approved these changes

2017-09-30 07:10 UTC, merged

2017-09-30 07:11 UTC, methane commented
Thanks.

2017-11-02 17:38 UTC, sloria commented
Will this fix be backported to python 2.7? The issue exists there as well.

2017-11-03 00:40 UTC, miss-islington commented
Thanks @Bezier89 for the PR, and @methane for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6.
🐍🍒⛏🤖

2017-11-03 00:50 UTC, methane commented
@sloria Will and will not.
This pull request need modify to backport to 2.7, since it using f-string.
If you create pull request for 2.7, please mention me.  I'll see it.

2017-11-03 03:03 UTC, sloria commented
I needed this fix, so I released a library that addresses this issue (and also adds write functionality): https://github.com/sloria/tinynetrc .

I can't make any promises, but if I get some time, I'll look into backporting to 2.7.

2017-11-04 12:43 UTC, sloria commented
@methane OK, I've made a PR for 2.7: https://github.com/python/cpython/pull/4276