[WIP] bpo-9566: Fixed some _ssl module warnings
python/cpython pull request #2495
Opened 2017-06-29 21:53 UTC by segevfiner

Split from https://github.com/python/cpython/pull/2492 on request by @haypo 

The following remain:
* `..\Modules\_ssl.c(2947): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data`
  The Py_buffer can *theoretically* be larger... But I'm not sure that the protocol even supports that...
  Should this be casted away or fixed some other way?
* `..\Modules\_ssl.c(4158): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data`
  Someone can *theoretically* pass a buffer big enough... But I doubt such a buffer is going to be written at once...
  Should this be casted away...?

2017-06-30 07:32 UTC, vstinner requested changes

2017-06-30 07:32 UTC, haypo commented on Modules/_ssl.c
> +    len = (int)strlen(buf);
buf is 512 bytes long and always ends with a null byte, so the downcast is safe.

2017-06-30 07:32 UTC, haypo commented on Modules/_ssl.c
> +    avail = (int)BIO_ctrl_pending(self->bio);
I dislike this downcast. I would prefer to use a larger integer type.

https://linux.die.net/man/3/bio_ctrl_pending says that the return type is size_t, it's unsigned. We may have to check < PY_SSIZE_T_MAX before downcasting to Py_ssize_t.

2017-06-30 07:35 UTC, haypo commented
>     ..\Modules\_ssl.c(2947): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
>     The Py_buffer can theoretically be larger... But I'm not sure that the protocol even supports that...
>     Should this be casted away or fixed some other way?

_ssl__SSLContext__set_alpn_protocols_impl(). You must check for overflow manually: "if (len > INT_MAX) raise an exception;".

>     ..\Modules\_ssl.c(4158): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
>     Someone can theoretically pass a buffer big enough...

_ssl_MemoryBIO_write_impl(): you cannot, there is "if (b->len > INT_MAX) { ... }" a few lines before, so the downcast is safe. Make it explicit with a "(int)" cast.

2017-06-30 08:46 UTC, segevfiner commented on Modules/_ssl.c
> +    avail = (int)BIO_ctrl_pending(self->bio);
`BIO_read` takes an `int` so we can only really only read as much as an `int` can hold without calling `BIO_read` in a loop. I replaced this with a `Py_MIN` which will make us read up to `INT_MAX`.

2017-06-30 08:49 UTC, segevfiner commented
@haypo 

> _ssl__SSLContext__set_alpn_protocols_impl(). You must check for overflow manually: "if (len > INT_MAX) raise an exception;".

`PySSLContext.alpn_protocols_len` was actually an `int` while it is treated as an `unsigned int` everywhere, so I changed it for correctness.

2017-07-26 15:56 UTC, zooba approved these changes

2017-07-26 15:56 UTC, zooba commented on Modules/_ssl.c
> +    len = (int)strlen(buf);
Right, and by explicitly stating that we are intentionally downcasting, someone who is reading the code can recognize that without having to do the flow analysis themselves. (Also, the compiler will recognize it too, and stop showing a warning.)

2017-07-26 22:19 UTC, zooba commented
The changes requested by @haypo have been made, so I'm merging.

2017-07-26 22:19 UTC, merged