Clarify glob logic a bit
python/cpython pull request #25028
Opened 2021-03-26 16:28 UTC by encukou

This was flagged by a static analyzer as "possible copy-paste error"
(dirname vs. pathname), and it did take me a bit more time than
necessary to understand why this code is correct.
Mentioning the os.path.split behavior this relies on in a comment
should make it clearer.

Code is changed to work on `pathname` to make it clear that
we're checking the same thing as in the preceding branch.
In this case it is the same as `dirname`, except for a trailing
slash which is irrelevant for `_isdir`.

2021-08-18 01:23 UTC, nightlark approved these changes

2021-08-18 01:31 UTC, nightlark commented
I'm very new to looking at the Python codebase and trying to understand what is going -- if I came across this function I'd find it easier to understand what is happening with these changes.

The comment about `patterns ending with a slash` also makes more sense by using `pathname` in the comparison rather than `dirname`.

2022-01-10 10:05 UTC, erlend-aasland commented
The PR title does not reflect the actual change; in addition to clarifying the glob logic, you're also changing parts of the logic. I believe this [does not qualify](https://devguide.python.org/triaging/?highlight=skip%20issue#github-labels-for-prs) for the _skip issue_ label, even though the change in logic is probably trivial and correct.

2022-01-10 10:12 UTC, serhiy-storchaka requested changes
Please add a test. It should fail with unpatched code and pass successfully with patched code.

Add a NEWS entry.

And please open an issue on the bug tracker for discussion.

2022-01-10 17:51 UTC, nightlark commented
> Please add a test. It should fail with unpatched code and pass successfully with patched code.

@serhiy-storchaka this request has me a bit puzzled -- if I'm understanding the changed code correctly the functionality should be identical to what it was before, meaning you're asking for the impossible by wanting a test that fails with the unpatched code.

Unless you're seeing a corner case that this change has fixed, shouldn't it be that any tests using this function should all pass with both the unpatched code and patched code to demonstrate that no regression has taken place?

2022-01-18 20:27 UTC, serhiy-storchaka commented
If there is no difference, we do not need this change.

There is as risk of introducing a regression. I am not sure that `os.stat('dirname/')` works on all platforms. It may fail on some rare platforms for which we do not have buildbots.

2022-01-18 20:27 UTC, closed without merging

2022-01-18 20:48 UTC, nightlark commented
> There is as risk of introducing a regression. I am not sure that `os.stat('dirname/')` works on all platforms. It may fail on some rare platforms for which we do not have buildbots.

By that same logic, we also can't be sure `os.stat('dirname')` works on all platforms. Worse would be if some rare platforms only like a trailing slash, and others never want the trailing slash -- which makes it impossible to know which . What are some rare platforms you'd want tested that don't have buildbots?

2022-01-21 07:52 UTC, serhiy-storchaka commented
If I remember correctly, on some commercial Unix either stat() or open() did not work with a path ending with a slash. Even if I misremembered, there is no need of changing a working code.