bpo-43640: Add warnings to ssl.PROTOCOL_TLSv1 and ssl.PROTOCOL_TLSv1_1
python/cpython pull request #25040
Opened 2021-03-27 15:44 UTC by illia-v

TLS 1.0 and TLS 1.1 have recently been deprecated.
https://datatracker.ietf.org/doc/rfc8996/

2021-03-27 15:49 UTC, tiran requested changes
I don't like to litter documentation with warnings. Warnings should be use sparsely. Otherwise users start to just ignore warnings. Could you please update the *Security considerations* section instead?

2021-03-27 15:52 UTC, tiran commented
Thanks, instead of adding warnings to PROTOCOL_TLSv1, PROTOCOL_TLSv1_1, OP_NO_TLSv1, OP_NO_TLSv1_1, TLSv1, and TLSv1_1, let's rather document problematic version in the security consideration block.

I'll soon post a new PEP based on the RFC, too.

2021-03-27 16:21 UTC, illia-v commented
> I don't like to litter documentation with warnings. Warnings should be use sparsely. Otherwise users start to just ignore warnings. Could you please update the _Security considerations_ section instead?

Fair enough.

Do you think it will suffice to change "SSL versions 2 and 3 are considered insecure" to "SSL versions 2 and 3, TLS 1.0, and TLS 1.1 are considered insecure" in the beginning of [this section](https://docs.python.org/3.10/library/ssl.html#protocol-versions)?

Also, should we leave the old warnings of `PROTOCOL_SSLv2` and `PROTOCOL_SSLv3`?

2021-03-27 16:22 UTC, illia-v commented
> I'll soon post a new PEP based on the RFC, too.

Are you going to disable TLS 1.0 and 1.1 by default?

2021-03-27 16:55 UTC, tiran commented
> Also, should we leave the old warnings of PROTOCOL_SSLv2 and PROTOCOL_SSLv3?

Good point! Please consolidate the old warnings, too.

2022-12-10 21:40 UTC, slateny commented on Doc/library/ssl.rst
>  use.  If you want maximum compatibility between clients and servers, it is
If https://datatracker.ietf.org/doc/rfc8996/ is authoritative, maybe adding it as a source would be useful?

2024-07-31 17:29 UTC, closed without merging