bpo-43433: Reattach query parameters after parsing URI
python/cpython pull request #25045
Opened 2021-03-27 21:46 UTC by Rosuav

Reinstate pre-3.9 behaviour where query parameters would be carried through in the path component.

2021-03-27 23:57 UTC, terryjreedy commented
According to Chris A., this patch fixes a regression introduced by 9c4c459, authored by Dong-he Na and merged by Serhiy for bpo-43614.

2021-03-28 08:43 UTC, serhiy-storchaka requested changes
Should not fragment be added too?

Also the code is not equivalent to the past code if path is empty. I do not know what is better, but all this should be tested.

Please add tests and NEWS entry.

2021-03-28 09:26 UTC, Rosuav commented
I'm not the one to analyze this as I don't actually use xmlrpc. Will ping the person with the original concern via python-list.

2021-03-28 17:27 UTC, kynan commented
The ["new" behavior] breaks the [DokuWiki XMLRPC interface](https://www.dokuwiki.org/devel:xmlrpc) (which is using the query string for authentication). I maintain a [client package for DokuWiki](https://github.com/kynan/dokuwikixmlrpc) which is broken by the behavior change addressed in this PR (kynan/dokuwikixmlrpc#8).

My opinion:
* Adding fragment is not hugely important but I can see no harm in including it to maintain full backwards compatibility with previous behavior. I can't see a legitimate reason for including a fragment in an XMLRPC server URI, but there's bound to be someone who depends on it :)
* The ["new" behavior] of implicitly using `/RPC2` as the path if empty is confusing and I expect will break existing users. I think users generally expect a hostname with and without trailing `/` to behave the same way. Also note that the path `/RPC2` in the [spec](http://xmlrpc.com/spec.md) is just an example and has *no* significance. Using it as a default in the first place was a misreading of the spec IMO. Restoring the previous behavior of using `/RPC2` as the default only if *both* path and query string are empty would be preferred. Ideally there would be no default, but I expect there are users depending on this also...

cc @Aluriak who originally reported this (to me and python-list).

Anything I can help with to move this along?

["new" behavior]: https://github.com/python/cpython/blob/3.9/Lib/xmlrpc/client.py#L1424

2021-03-28 17:32 UTC, kynan requested changes
I suggest also restoring the previous behavior where `/RPC2` is only used as the default if neither path nor query string are set. I'm indifferent on also adding fragment.

2021-03-28 17:32 UTC, kynan commented on Lib/xmlrpc/client.py
>          self.__handler = p.path or "/RPC2"
```suggestion
        self.__handler = p.path
```

2021-03-28 17:32 UTC, kynan commented on Lib/xmlrpc/client.py
```suggestion
        if not self.__handler:
            self.__handler = "/RPC2"

```

2021-03-29 12:18 UTC, corona10 requested changes
I am also the same with @serhiy-storchaka about testing and NEWS.d
we need to add the test code to check `self.__handler` value.

2021-03-29 12:40 UTC, vstinner reviewed
I prefer PR #25057 which reuses urlunsplit() and adds tests.

2021-03-29 12:57 UTC, Rosuav commented
Yep, I also like that PR.

2021-03-29 20:35 UTC, vstinner commented
PR #25057 was merged instead.

2021-03-29 20:35 UTC, closed without merging