bpo-34932: Add socket.TCP_KEEPIDLE support to macOS
python/cpython pull request #25079
Opened 2021-03-29 21:08 UTC by ShaneHarvey

This change add socket.TCP_KEEPIDLE support to macOS.

https://bugs.python.org/issue34932

2021-03-30 14:44 UTC, corona10 requested changes
Please update Doc/library/socket.rst first and I don't prefer to add TCP_KEEPALIVE as alias.

2021-03-30 14:44 UTC, corona10 commented on Modules/socketmodule.c
> +    PyModule_AddIntConstant(m, "TCP_KEEPIDLE", TCP_KEEPALIVE);
```suggestion
    PyModule_AddIntMacro(m, TCP_KEEPALIVE);;
```

2021-03-30 14:44 UTC, corona10 commented on Modules/socketmodule.c
> +#elif defined(__APPLE__) && defined(TCP_KEEPALIVE)
```suggestion
#if defined(TCP_KEEPALIVE)
```

2021-04-21 18:44 UTC, ShaneHarvey commented
After reading https://bugs.python.org/issue32394 to figure out why TestMSWindowsTCPFlags exists, I discovered that TCP_KEEPALIVE is undocumented on Windows: 
- https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-tcp-socket-options

Since we don't know what version of windows introduced this flag we cannot add it on Windows.

I've updated the code to only add TCP_KEEPALIVE on macOS (when it exists).

2021-04-21 18:44 UTC, ShaneHarvey commented
I have made the requested changes; please review again.

2021-06-02 19:17 UTC, ShaneHarvey commented
ping @corona10

2021-07-14 22:33 UTC, ShaneHarvey commented
Rebased on to main.

2021-07-14 22:36 UTC, ShaneHarvey commented
@corona10 @pablogsal I'm not sure what's holding up the review on this PR but I'm hoping it can be merged and backported to 3.10 similar to https://github.com/python/cpython/pull/25992.

2021-07-14 22:49 UTC, pablogsal approved these changes

2021-07-14 22:53 UTC, merged

2021-07-14 22:53 UTC, miss-islington commented
Thanks @ShaneHarvey for the PR, and @pablogsal for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖

2021-07-14 23:01 UTC, ShaneHarvey commented
Thanks all!

2021-07-14 23:02 UTC, pablogsal commented
Thanks for your contribution!