bpo-43749: Ensure current exe is copied when using venv on windows
python/cpython pull request #25216
Opened 2021-04-06 14:02 UTC by inorton

2021-04-07 20:26 UTC, vsajip requested changes
You can remove the NEWS file, as I've added the `skip-news` label to this PR.

2021-05-15 19:38 UTC, inorton commented
I have made the requested changes; please review again

2021-05-19 09:37 UTC, vsajip approved these changes

2021-05-19 09:37 UTC, merged

2021-12-10 17:26 UTC, miss-islington commented
Thanks @inorton for the PR 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2021-12-10 17:26 UTC, miss-islington commented
Thanks @inorton for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖