bpo-30794: added kill() method to multiprocessing.Process
python/cpython pull request #2528
Opened 2017-07-01 20:43 UTC by vmsp

kill() is the same as terminate() but sends SIGKILL instead of SIGTERM. On Windows it's the same as terminate() and wasn't tested. I'd appreciate if someone could try it.

2017-07-01 20:43 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-07-04 13:37 UTC, vmsp commented
I signed the CLA. Please re-run the check. Thanks!

2017-07-04 18:48 UTC, pitrou requested changes
Thank you for posting this!
Two things are missing from this PR:
* a documentation addition in `Doc/library/multiprocessing.rst`
* a NEWS entry, which you can create using the [blurb tool](https://pypi.org/project/blurb/) (see "blurb add")

2017-07-04 18:48 UTC, pitrou commented on Lib/test/_test_multiprocessing.py
> +    def test_kill(self):
It looks like this is duplicating most of `test_terminate`. Perhaps those two methods could use a shared helper?

2017-07-18 15:15 UTC, pitrou commented on Doc/library/multiprocessing.rst
> +   .. method:: kill()
Since this is a new method, you need a `versionadded` marker a well (see above the `sentinel` attribute for an example).

2017-07-18 15:17 UTC, pitrou commented
Sorry for the detail, there's one last nit :-) If you don't have time, just say so, I can add it myself.

2017-07-18 15:25 UTC, pitrou approved these changes

2017-07-18 15:26 UTC, vmsp commented
No problem! Hope it's alright now.

2017-07-18 15:34 UTC, pitrou commented
It is. I'm merging now. Thank you for making this!

2017-07-18 15:34 UTC, merged