bpo-30835: email: Fix AttributeError when parsing invalid Content-Tra…
python/cpython pull request #2544
Opened 2017-07-03 13:50 UTC by ajdlinux

…nsfer-Encoding

Parsing an email containing a multipart Content-Type, along with a
Content-Transfer-Encoding containing an invalid (non-ASCII-decodable) byte
will fail. email.feedparser.FeedParser._parsegen() gets the header and
attempts to convert it to lowercase before comparing it with the accepted
encodings, but as the header contains an invalid byte, it's returned as a
Header object rather than a str.

Cast the Content-Transfer-Encoding header to a str to avoid this.

Found using the AFL fuzzer.

Reported-by: Daniel Axtens <dja@axtens.net>
Signed-off-by: Andrew Donnellan <andrew@donnellan.id.au>

2017-07-03 13:50 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-07-05 17:14 UTC, bitdancer reviewed
Needs a test.

2017-07-18 02:48 UTC, pslacerda commented
I couldn't reproduce the bug feeding the following email to FeedParser:

    From: Nathaniel Borenstein <nsb@bellcore.com>
    To:  Ned Freed <ned@innosoft.com>
    Subject: Sample message
    MIME-Version: 1.0
    Content-Transfer-Encoding: öther
    Content-type: multipart/mixed; boundary="simple
    boundary"
    
    This is the preamble.  It is to be ignored, though it
    is a handy place for mail composers to include an
    explanatory note to non-MIME compliant readers.
    --simple boundary
    
    This is implicitly typed plain ASCII text.
    It does NOT end with a linebreak.
    --simple boundary
    Content-type: text/plain; charset=us-ascii
    
    This is explicitly typed plain ASCII text.
    It DOES end with a linebreak.
    
    --simple boundary--
    This is the epilogue.  It is also to be ignored.

2017-07-18 03:10 UTC, ajdlinux commented
@bitdancer I've been working on a test and will push one soon

2018-12-06 09:36 UTC, serhiy-storchaka requested changes
Please add tests.

2019-01-10 16:00 UTC, vstinner commented
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

2019-05-21 01:03 UTC, csabella commented
@ajdlinux, please address the code review comments to add tests.  Thanks!

2019-05-22 22:37 UTC, maxking commented
This has been pending requested changes for a while now, I will probably pick it up and add tests so that the bugfix can go in.

2019-06-04 18:01 UTC, warsaw commented
Closed in favor of #13598

2019-06-04 18:01 UTC, closed without merging