bpo-42737: Mention PEP 563 in doc for annotated assignment
python/cpython pull request #25511
Opened 2021-04-21 23:06 UTC by gousaiyang

Currently, the [documentation for variable annotations](https://docs.python.org/3/reference/simple_stmts.html#annotated-assignment-statements) does not mention PEP 563 at all. This PR tries to improve this.

Note: this is describing the situation when #23952 is not applied, so that this PR can be easily backported to earlier versions of Python. We may need to either update #23952 itself or create a new PR to update the doc to demonstrate that annotations for complex targets will no longer be evaluated when PEP 563 is enabled.

2021-04-22 08:08 UTC, isidentical commented
Please hold this PR until #23952 is resolved first.

2021-04-25 03:00 UTC, isidentical commented
@gousaiyang could you please update the PR with the new changes (if necessary)

2021-04-25 04:48 UTC, gousaiyang commented
I think it might be better to merge this PR and create a separate one to document the changes in #23952, since the changes in this PR applies to (and thus can be backported) all Python versions down to 3.7, while changes in #23952 is for 3.10 only. If those changes are mixed in one PR, would that be harder to backport?

2022-04-02 23:11 UTC, JelleZijlstra commented on Doc/reference/simple_stmts.rst
> +(i.e. :pep:`563` is enabled), the annotations are stored as string values in
Ideally we should link to the documentation for the `__future__` statement, not to the PEP directly. A PEP is a change proposal, not live documentation.

2022-04-02 23:11 UTC, JelleZijlstra commented on Doc/reference/simple_stmts.rst
> +that is a dictionary mapping from variable names (mangled if private) to the
```suggestion
that is a dictionary mapping from variable names (mangled if private) to
```
Reads better without the article

2022-04-02 23:11 UTC, JelleZijlstra commented on Doc/reference/simple_stmts.rst
> +in class or module scope (regardless of whether :pep:`563` is enabled), but not
Really? That seems like a bug.

2023-01-04 05:09 UTC, hauntsaninja requested changes
Could you address Jelle's review? The claim is false, e.g. you don't see any print out when running
```
from __future__ import annotations
import sys

def f():
    print("!!!")

x: f()
print(sys.modules[__name__].__annotations__)
```

2025-04-06 20:22 UTC, hauntsaninja commented
Closing because of requested feedback, merge conflict, CLA, etc

2025-04-06 20:22 UTC, closed without merging