bpo-43882 Remove the newline, and tab early. From query and fragments.
python/cpython pull request #25853
Opened 2021-05-03 14:08 UTC by orsenthil

Based on the review comment https://github.com/python/cpython/pull/25726#pullrequestreview-649803605

Moving the fix for removing newline and tabs early to include both query strings and fragments, (Entire URL).

2021-05-03 17:51 UTC, gpshead requested changes

2021-05-03 17:51 UTC, gpshead commented on Lib/test/test_urlparse.py
> +        scheme = "ht\ntp"
this doesn't appear to be used.  what is this section of the test doing?

2021-05-03 17:51 UTC, gpshead commented on Lib/test/test_urlparse.py
> +        url = "http\t://www.python.org/java\nscript:\talert('msg\r\n')/?query\n=\tsomething#frag\nment"
i suggest also adding a \r in the middle of the netloc for good measure.  `www.python\r.org` perhaps?

2021-05-03 18:52 UTC, gpshead approved these changes

2021-05-03 18:53 UTC, gpshead commented
fwiw this PR is against 3.9.  i assume you'll "backport to main and 3.10" once those aren't actively being release branched and renamed?

2021-05-03 19:08 UTC, orsenthil commented
>  i assume you'll "backport to main and 3.10" once those aren't actively being release branched and renamed?

Yes, exactly. I wanted to time window to be utilized for 3.9 and 3.8.
I will port it to rest of the active branches immediately.

2021-05-03 19:08 UTC, merged

2021-07-02 23:57 UTC, adamjstewart commented on Lib/urllib/parse.py
> +        scheme = scheme.replace(b, "")
According to the [typeshed](https://github.com/python/typeshed/blob/master/stdlib/urllib/parse.pyi#L126), the `scheme` argument to `urlparse` is `Optional`. However, with this change, a value of `None` will result in an error like:
```
AttributeError: 'NoneType' object has no attribute 'replace'
```
I'm not sure whether the typeshed is wrong or if this line should be guarded with `if scheme is not None`, but we should definitely fix one or the other and perhaps improve the documentation on this option.

Thanks to @branchvincent for doing the digging and reporting this issue to me.