bpo-44077: Expose IP_RECVTOS in the socket module
python/cpython pull request #25992
Opened 2021-05-08 15:23 UTC by gsauthof

https://bugs.python.org/issue44077

https://bugs.python.org/issue44077

2021-05-08 15:23 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@gsauthof

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-05-13 17:00 UTC, corona10 requested changes
Please update Docs and NEWS

For your help: https://github.com/python/cpython/pull/24946/files and https://docs.python.org/3/library/socket.html?highlight=socket#socket.SOMAXCONN

2021-05-13 20:13 UTC, gsauthof commented
I have made the requested changes; please review again.

2021-05-14 22:14 UTC, terryjreedy commented
@pablogsal Pablo, unless you are willing for this new constant to be backported to 3.10.0b2 (or b3 if it misses b2), the What's new entry should go in the currently non-existent What's new in 3.11.  Do you plan to add it soon?  I am not going to ask a new contributor to do so.

Georg, the 'new in' entry may need to be changed depending on Pablo's answer.

@corona10 Is this something you might merge, or do we need to find a socket person (I am not)?

2021-05-15 05:26 UTC, corona10 commented
@terryjreedy 
I think that if this PR is merged, this changed only affects 3.11

2021-05-15 05:29 UTC, corona10 commented
> Is this something you might merge, or do we need to find a socket person

I often observe that this kind of constants adding was accepted.
But getting opinions from socket experts looks great.

2021-05-15 05:30 UTC, corona10 requested changes

2021-05-15 05:30 UTC, corona10 commented on Doc/library/socket.rst
> +   .. versionchanged:: 3.10
```suggestion
   .. versionchanged:: 3.11
```

2021-05-15 05:38 UTC, corona10 commented
@terryjreedy 
FYI, I did not decide to merge this PR or not. Before accepting this PR we should investigate the use cases of `IP_RECVTOS`.
And if the socket expert exists, we can get a review from the expert.

2021-05-15 09:21 UTC, gsauthof commented
I have made the requested changes; please review again.

2021-06-20 19:41 UTC, pablogsal commented
> @pablogsal Pablo, are you willing for this new constant to be backported to 3.10.0b2 ?

Sorry for the late response, This has flown under my radar :(

I am ok including this constant, as it is contained enough

2021-06-20 20:08 UTC, merged

2021-06-20 20:08 UTC, miss-islington commented
Thanks @gsauthof for the PR, and @pablogsal for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖