bpo-43109: Use /usr/bin/ar on macOS for LTO builds
python/cpython pull request #25999
Opened 2021-05-09 00:09 UTC by xrisk

2021-05-09 18:06 UTC, matrixise requested changes

2021-05-09 18:06 UTC, matrixise commented on configure.ac
> +        # /usr/bin/ar on macOS works fine in place of llvm-ar
Here, you will just override the LLVM_AR variable, then the previous value was computed. You have to use a `else`.

Other question, could you check that `/usr/bin/ar` exists...

@ned-deily what's your opinion?

2021-05-09 19:19 UTC, ned-deily commented
Thanks for the PR, @xrisk, and the heads up, @matrixise.  I will review and test this PR soon.

2021-05-10 04:04 UTC, matrixise reviewed
Thank you for your modifications, now, we have to wait for a review of @ned-deily

2021-05-10 20:45 UTC, vstinner commented
cc @serge-sans-paille

2021-05-25 10:58 UTC, vstinner commented
PR #26341 was merged instead.

2021-05-25 10:58 UTC, closed without merging