bpo-29455: Mention coverage.py in trace module documentation
python/cpython pull request #261
Opened 2017-02-23 21:05 UTC by marco-buttu

This pull request fixes [bpo-29455](https://bugs.python.org/issue29455).

2017-02-25 00:07 UTC, Carreau commented on Doc/library/trace.rst
> +.. seealso:: `Coverage.py <https://coverage.readthedocs.io/>`_, which is one
Looking at the rest of the documentation is seem like most `.. seealso::` are alone on their lines with the paragraph on the next one.

2017-02-25 12:22 UTC, marco-buttu commented on Doc/library/trace.rst
> +.. seealso:: `Coverage.py <https://coverage.readthedocs.io/>`_, which is one
Thanks @Carreau. I also changed the markup to [reST list](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-seealso).

2017-02-27 14:48 UTC, berkerpeksag requested changes

2017-02-27 14:48 UTC, berkerpeksag commented on Doc/library/trace.rst
> +      A popular third-party coverage tools that provides very nice HTML
tools -> tool?

2017-02-27 14:48 UTC, berkerpeksag commented on Doc/library/trace.rst
> +      A popular third-party coverage tools that provides very nice HTML
"very nice" can be dropped.

2017-02-27 14:48 UTC, berkerpeksag commented on Doc/library/trace.rst
> +      output along with advanced features such as branch coverage.
advanced -> more advanced?

2017-02-27 15:15 UTC, berkerpeksag approved these changes
LGTM, thanks! The issue is assigned to @brettcannon so I won't merge this.

2017-03-03 20:42 UTC, merged