bpo-30790: fix proxy works uncorrectly if registry value end with a semicolon
python/cpython pull request #2611
Opened 2017-07-07 01:30 UTC by Cordius

The function proxy_bypass_registry will return 1 if registry value end
with a semicolon because a NULL string will be contained in the variable
proxyOverride while using proxyOverride.split(';'). And therefore, our
proxy will never work correctly.

2019-06-02 14:37 UTC, auvipy approved these changes

2020-05-29 09:47 UTC, csabella commented
@Cordius, please take a look at the comments on the bug tracker issue.

2022-12-07 19:51 UTC, iritkatriel requested changes
As was mentioned on the issue, a change like this requires a unit test that reproduces the bug being fixed.

2024-04-10 14:23 UTC, encukou commented
With no response for years, I'll close the PR.

2024-04-10 14:23 UTC, closed without merging