Print readline version information when running test suite
python/cpython pull request #2618
Opened 2017-07-07 10:48 UTC by berkerpeksag

2017-07-07 12:01 UTC, nirs reviewed
:+1:

2017-07-07 12:02 UTC, haypo commented
I would prefer to dump the curses version in test_readline, as done by test_tcl or test_gdb in verbose mode. When a test fails on buildbots, the test is run again in verbose mode.

2017-07-07 12:07 UTC, haypo commented
I prefer to not make regrtest header too big.

2017-07-07 12:24 UTC, berkerpeksag commented
Why would we want to print curses version in test_readline? Unless I'm missing something, curses doesn't have anything to do with bpo-29854.

tcl and gdb are much less common dependencies than readline. readline is probably available on all Unix platforms and I think it makes sense to easily see which version is installed on the host.

> I prefer to not make regrtest header too big.

Sorry, I don't have time for this kind of bikeshedding. We don't design a production level GUI for end users and it's already hard to read outputs of regrest and Buildbot. I prefer not to spend too much time to find which version of readline installed at http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/908/steps/test/logs/stdio Plus, that header has already prints less useful information so I don't think two additional lines would set the world on fire :)

2017-07-07 12:56 UTC, haypo commented
> Why would we want to print curses version in test_readline? Unless I'm missing something, curses doesn't have anything to do with bpo-29854.

Oh sorry, I'm always confused between readline and curses, they are the same thing for me, sorry :-)

By the way, you should mention bpo-29854 in your PR title. It helps later to get the rationale of a change ;-)

> tcl and gdb are much less common dependencies than readline. readline is probably available on all Unix platforms and I think it makes sense to easily see which version is installed on the host.

Another issue with importing readline early is that importing a module has side effect, especially readline. See for example http://bugs.python.org/issue19884 and TestReadline.test_init(): this test still fails on our RHEL buildbot, so importing readline still have an annoying side effect of writing a string into stdout.

I would prefer to limit imports at regrtest startup, to make it more deterministic.


> I prefer not to spend too much time to find which version of readline installed at http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/908/steps/test/logs/stdio

Would you mind to review my PR #2619? When it will be merged, I can retrieve the libreadline version for you and put it in the issue.

2017-07-07 14:03 UTC, haypo commented
We discuss this PR on IRC with @berkerpeksag. If imports are done are done in subprocess to prevent side effects, I'm ok to get such change merged ;-)

2017-07-07 14:05 UTC, haypo commented on Lib/test/libregrtest/main.py
> +        if readline is not None:
this line just can be an "else:" no?

2017-07-07 14:05 UTC, haypo commented on Lib/test/libregrtest/main.py
> +        except ImportError:
Maybe use sys.exit(1) to not try to decode empty stdout in the parent process.

2017-07-07 14:05 UTC, haypo commented on Lib/test/libregrtest/main.py
> +        rl_version_cmd = """if 1:
You may put the textwrap.dedent() directly here. But do you need "if 1:" in that case?

2017-07-07 14:06 UTC, haypo commented on Lib/test/libregrtest/main.py
> +                print(f"== readline implementation: {rl_implementation}")
can you please write both info on a single line?

2017-07-07 14:08 UTC, nirs commented on Lib/test/libregrtest/main.py
> +        """
It is very hard to read this code like this. The other program that you run should be indented differently from the other code.

Also the code to return the info should be in separate function, and here we can just print the values.

2017-07-07 14:11 UTC, berkerpeksag commented on Lib/test/libregrtest/main.py
> +        rl_version_cmd = """if 1:
Do you mean

```py
rl_version_cmd = textwrap.dedent("""
...
""")
```

?

And, you're right, we don't need `if 1:`, thanks!

2017-07-07 14:12 UTC, berkerpeksag commented on Lib/test/libregrtest/main.py
> +        except ImportError:
Good point!

2017-07-07 14:16 UTC, berkerpeksag commented on Lib/test/libregrtest/main.py
> +                print(f"== readline implementation: {rl_implementation}")
Sure, what do you thing about the following format?:

```
== readline: 0x0602 (GNU readline)
```

2017-07-07 14:17 UTC, haypo commented on Lib/test/libregrtest/main.py
> +                print(f"== readline implementation: {rl_implementation}")
I like it. Maybe just add version somewhere? "== readline: version 0x0602 (GNU readline)"

2017-07-07 14:18 UTC, berkerpeksag commented on Lib/test/libregrtest/main.py
> +                print(f"== readline implementation: {rl_implementation}")
Done:

```
== readline: version 0x0602 (GNU readline)
```

Thanks!

2017-07-07 14:37 UTC, berkerpeksag commented on Lib/test/libregrtest/main.py
> +        """
So what you're suggesting is similar to the following snippet, right?

```py
rl_version_cmd = """
def get_rl_info():
    # all code is here
    return version, implementation
version, implementation = get_rl_info()
print(version)
print(implementation)
"""
```

2017-07-07 14:51 UTC, berkerpeksag commented on Lib/test/libregrtest/main.py
> +        """
Or:

```py
rl_version_cmd = """
def get_rl_info():
    # all code is here
    return version, implementation
version, implementation = get_rl_info()
print("== readline: version {version} ({implementation})")
"""
```

2017-07-07 14:59 UTC, berkerpeksag commented
I've addressed all review comments (and hopefully I got @nirs' comment right) Thanks!

2017-07-07 16:40 UTC, nirs requested changes

2017-07-07 16:40 UTC, nirs commented on Lib/test/libregrtest/main.py
>              else:
We can remove the try/else/exit, just import readline:

    import readline

If import fails, we exit with exit code 1 anyway, no special code needed.

2017-07-07 16:40 UTC, nirs commented on Lib/test/libregrtest/main.py
> +        rl_version_cmd = textwrap.dedent("""
The extra indent make this much more clear, thanks!

2017-07-07 16:40 UTC, nirs commented on Lib/test/libregrtest/main.py
> +                    is_editline = readline.__doc__ and "libedit" in readline.__doc__
This is now the third place using this horrible __doc__ check. I think we should eliminate this, now, or at least leave a todo and clean up later. Ideally we should have exactly one is_editline() function in cpython.

2017-07-07 16:40 UTC, nirs commented on Lib/test/libregrtest/main.py
> +                rl_version, rl_implementation = get_rl_info()
I think we should print the same values ptinted now in test_readline.setupModule

2017-07-08 15:33 UTC, nirs commented on Lib/test/libregrtest/main.py
> +        """
More like:

````python
    def readline_info():
        script = """
import json
import readline
is_editline = readline.__doc__ and "libedit" in readline.__doc__
info = {"version": readline._READLINE_VERSION,
           "implementation": "editline" if is_editline else "GNU readline"}
print(json.dumps(info))
"""
        c = subprocess.run([sys.executable, "-c", script],
                                        stdout=subprocess.PIPE,
                                        stderr=subprocess.PIPE)
        if c.returncode == 0:
            return json.loads(c.stdout.decode())
```

And use readline_info() in display_header(), or in any other context as needed.

2017-08-11 22:29 UTC, berkerpeksag commented
Superseded by bpo-30871 and PR #3027.

2017-08-11 22:29 UTC, closed without merging

2017-08-15 02:12 UTC, asottile commented
@berkerpeksag  do you mean #3075?

2017-08-15 03:57 UTC, berkerpeksag commented
@asottile yes that's what I meant! :) Good catch, thanks.