bpo-41963: document that ConfigParser strips off comments
python/cpython pull request #26197
Opened 2021-05-17 19:59 UTC by jugmac00

... when reading a configuration file.

2021-05-17 20:50 UTC, lgfunderburk commented
Reviewing

2021-05-17 21:05 UTC, lgfunderburk requested changes
Slight wording change on `configparser.py`

_Please note that comments get stripped off **on** reading_ 

change to 

_Please note that comments get stripped off **when** reading_

2021-05-17 21:15 UTC, lgfunderburk requested changes
Testing review functionality. Sorry for duplicates.

2021-05-17 21:15 UTC, lgfunderburk commented on Lib/configparser.py
> +        section names. Please note that comments get stripped off on reading.
**Please note that comments get stripped off when reading configuration files.**

2021-05-17 21:26 UTC, lgfunderburk requested changes
Slight grammar change and consistency on what is being read.

2021-05-17 21:26 UTC, lgfunderburk commented on Lib/configparser.py
> +        section names. Please note that comments get stripped off on reading.
```suggestion
        section names. Please note that comments get stripped off when reading configuration files.
```

2021-05-17 21:26 UTC, jugmac00 commented on Lib/configparser.py
> +        section names. Please note that comments get stripped off on reading.
Thank you!

2021-05-17 21:27 UTC, lgfunderburk commented on Lib/configparser.py
> +        section names. Please note that comments get stripped off on reading.
Thank YOU! :)

2021-05-17 21:29 UTC, lgfunderburk approved these changes
Approving changes.

2021-05-18 16:11 UTC, merged

2021-05-18 16:11 UTC, miss-islington commented
Thanks @jugmac00 for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.9.
🐍🍒⛏🤖

2021-05-18 16:11 UTC, miss-islington commented
Sorry @jugmac00 and @ambv, I had trouble checking out the `3.10` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 02ee8191263848f8c8999f72286148946b83e5c9 3.10
                                ```