bpo-44166: Make IndexError messages for lists more informative
python/cpython pull request #26207
Opened 2021-05-18 07:40 UTC by miguendes

2021-05-18 08:38 UTC, pablogsal requested changes
This is a nice Idea. One thing I'm concerned about is that this removed the optimization for creating the string of index errors. As we are dynamically creating the strings now it means that code that raises index error but catches it later will be slower. 

We need to run some benchmarks to be sure that we are not going to introduce a big regression.

2021-05-18 09:03 UTC, Fidget-Spinner reviewed
I just have a few minor suggestions below. Apart from what Pablo said, the rest of the code LGTM.

2021-05-18 09:03 UTC, Fidget-Spinner commented on Objects/listobject.c
> +                 "%s index out of range, the len is %zd so index must be in -%zd..%zd, got %zd",
Wording:
```suggestion
                 "%s index out of range, the length is %zd so index must be between -%zd..%zd, got %zd",
```

2021-05-18 09:03 UTC, Fidget-Spinner commented on Objects/listobject.c
> +        i -= len;
formatting: PEP 7 needs brackets on new code
```suggestion
    if (i < 0) {
        i -= len;
    }
```

2021-05-18 09:04 UTC, Fidget-Spinner commented
BTW CI is failing because GitHub actions has some issues right now https://www.githubstatus.com/history. I doubt it's due to the code.

2021-05-18 20:23 UTC, miguendes commented
> This is a nice Idea. One thing I'm concerned about is that this removed the optimization for creating the string of index errors. As we are dynamically creating the strings now it means that code that raises index error but catches it later will be slower.
> 
> We need to run some benchmarks to be sure that we are not going to introduce a big regression.

Thanks for your input @pablogsal !

I ran some benchmarks. And indeed this new change is slower, the optimised version is around 1.82x faster.

```bash
$ ./python bench_index_error.py -o new.json
.....................
index_error: Mean +- std dev: 676 ns +- 13 ns

$ ./python bench_index_error.py -o old.json
.....................
index_error: Mean +- std dev: 372 ns +- 5 ns

$ ./python -m pyperf compare_to new.json old.json
Mean +- std dev: [new] 676 ns +- 13 ns -> [old] 372 ns +- 5 ns: 1.82x faster
```

Here's the code I used to benchmark it: https://gist.github.com/miguendes/99d7d57c9d48bf121ce7a30b190009bb

I fully understand the performance hit and it's a shame we cannot make the user experience better for this use case :(. Especially because this would be aligned with the new improvements we've done for SyntaxErrors. Even though we can't compare them in terms of performance.

Out of curiosity, how much slower should it be to be considered a big regression? 

Also, is the EAFP style mentioned by @serhiy-storchaka so common that this change would be a no-go? 
I was assuming that even if we catch these exceptions, this kind of event wouldn't happen so frequently, but I might be wrong.

Is there anything I can do to make it faster?

2021-05-18 21:36 UTC, pablogsal commented
> Out of curiosity, how much slower should it be to be considered a big regression?

It depends, but generally more than 4-5 % starts to raise concerns.

> Also, is the EAFP style mentioned by @serhiy-storchaka so common that this change would be a no-go?

Yep, is not the most common code, but is important enough to make this approach at least probably a no-go.

I have some ideas on how to implement this with no performance cost, but I need to finish something first before I can explain it in detail.

2021-12-06 03:57 UTC, rhettinger commented
As stated on the tracker, we've decided to leave the code as-is.

Thank you for submitting a PR.

2021-12-06 03:57 UTC, closed without merging