bpo-44184: Fix subtype_dealloc() for freed type
python/cpython pull request #26274
Opened 2021-05-20 23:46 UTC by vstinner

Fix a crash at Python exit when a deallocator function removes the
last strong reference to a heap type.

Don't read type memory after calling basedealloc() since
basedealloc() can deallocate the type and free its memory.

2021-05-20 23:46 UTC, vstinner commented
cc @pablogsal @erlend-aasland

2021-05-20 23:50 UTC, erlend-aasland approved these changes

2021-05-21 00:06 UTC, pablogsal requested changes, later dismissed
This fix makes no sense to me, if what you say in the comment was actually the root cause, we would be seeing this under vallgrind or the address sanitizer and I could not reproduce it

2021-05-21 00:19 UTC, pablogsal commented
This is enough to crash it:

```
mport ast
import builtins
import sys
import os

tree = ast.parse("pass")

class Cycle:
    def __del__(self):
        log("Cycle.__del__")
a = Cycle()
b = Cycle()
a.b = b
b.a = a
a.ast = tree

# Put the cycle somewhere to survive until the *last* GC collection
def callback(*args):
    pass
callback.a = a
os.register_at_fork(after_in_child=callback)

print("exit")
``` 

can we maybe add a test based on this?

2021-05-21 00:25 UTC, pablogsal commented
Diff with the test:

```diff
diff --git a/Lib/test/test_gc.py b/Lib/test/test_gc.py
index ee4fe49a57..807e95d987 100644
--- a/Lib/test/test_gc.py
+++ b/Lib/test/test_gc.py
@@ -722,6 +722,28 @@ def __del__(self):
         rc, out, err = assert_python_ok('-c', code)
         self.assertEqual(out.strip(), b'__del__ called')

+    def test_gc_heap_type_at_shutdown(self):
+        # Create a reference cycle through the __main__ module and check
+        # it gets collected at interpreter shutdown.
+        code = """if 1:
+            import ast
+            import builtins
+            import sys
+            import os
+
+            tree = ast.parse("pass")
+            x = [tree]
+            x.append(x)
+
+            # Put the cycle somewhere to survive until the *last* GC collection
+            def callback(*args):
+                pass
+            callback.a = x
+            os.register_at_fork(after_in_child=callback)
+            """
+        rc, out, err = assert_python_ok('-c', code)
+        self.assertEqual(out.strip(), b'__del__ called')
+
     def test_gc_ordinary_module_at_shutdown(self):
         # Same as above, but with a non-__main__ module.
         with temp_dir() as script_dir:
```

2021-05-21 00:27 UTC, vstinner commented
I would prefer to not rely directly on os.register_at_fork() to ensure that the object will survive until the last GC collection. I would prefer an abstraction function in the test.support module. I will try to add a test.

2021-05-21 07:43 UTC, erlend-aasland commented
I can reproduce the bug on macOS using the address sanitiser. The patch also fixes the buildbot problems on https://github.com/python/cpython/pull/24203#issuecomment-845025674

2021-05-21 16:17 UTC, vstinner commented
@pablogsal: I added an unit test, would you mind to review the updated PR?

I was too lazy to add an abstraction. Since the test is in test_gc, IMO it's ok. First, I wanted to add the test to test_ast.

2021-05-21 16:36 UTC, vstinner commented
Ah, register_at_fork() is not available on Windows. I modified my test to use codecs.register() instead.

You can test manually that the unit test fails as expected with this change:

```
diff --git a/Objects/typeobject.c b/Objects/typeobject.c
index af99ab79d1..acbedc64e6 100644
--- a/Objects/typeobject.c
+++ b/Objects/typeobject.c
@@ -5,6 +5,7 @@
 #include "pycore_compile.h"       // _Py_Mangle()
 #include "pycore_initconfig.h"
 #include "pycore_moduleobject.h"  // _PyModule_GetDef()
+#include "pycore_pymem.h"  // _PyModule_GetDef()
 #include "pycore_object.h"
 #include "pycore_pyerrors.h"
 #include "pycore_pystate.h"       // _PyThreadState_GET()
@@ -1459,6 +1460,7 @@ subtype_dealloc(PyObject *self)
        our type from a HEAPTYPE to a non-HEAPTYPE, so be careful about
        reference counting. Only decref if the base type is not already a heap
        allocated type. Otherwise, basedealloc should have decref'd it already */
+    assert(!_PyMem_IsPtrFreed(type->tp_name));
     if (type_needs_decref) {
         Py_DECREF(type);
     }
```

2021-05-21 17:14 UTC, erlend-aasland approved these changes
Looks good to me!

2021-05-21 17:19 UTC, merged

2021-05-21 17:20 UTC, miss-islington commented
Thanks @vstinner for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖

2021-05-21 17:20 UTC, vstinner commented
Thanks for reviews @pablogsal and @erlend-aasland!

2021-07-15 22:42 UTC, miss-islington commented
Thanks @vstinner for the PR 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖