Check callback is callable in PyWeakref_NewRef
python/cpython pull request #26273
Opened 2021-05-20 20:08 UTC by tekknolagi

The documentation says that `PyWeakref_NewRef` should raise a
`TypeError` if the callback is not callable, None, or NULL, but the code
does not reflect the documentation. This PR fixes that.

2021-05-20 20:41 UTC, tekknolagi commented
Tests failing seem entirely unrelated

2021-11-09 08:29 UTC, tekknolagi commented
bump? :)

2022-03-24 18:25 UTC, MaxwellDupre approved these changes
Runs ok on my Ubuntu.

2022-12-06 23:20 UTC, iritkatriel requested changes
This has merge conflicts now.

2022-12-17 07:30 UTC, kumaraditya303 commented on Misc/NEWS.d/next/C API/2019-03-09-00-10-25.bpo-36203.yKKWd3.rst
> +Amend PyWeakref_New to raise a TypeError if the callback given is not NULL, None, or a callable object. The documentation previously falsely claimed this check occurred.
```suggestion
Amend :c:func:`PyWeakref_New` to raise :exc:`TypeError` if the *callback* given is not NULL, None, or a callable object. The documentation previously falsely claimed this check occurred.

```

2026-04-09 14:25 UTC, tekknolagi commented
I regrettably have no time to work on this. Please feel free to take over or close as appropriate.

2026-06-10 10:40 UTC, serhiy-storchaka commented
Superseded by #151145.

2026-06-10 10:40 UTC, closed without merging