update: fix ImportError in hypotheses
python/cpython pull request #26324
Opened 2021-05-24 00:02 UTC by luizoti

2021-05-24 00:02 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@luizoti

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-05-30 01:47 UTC, eamanu requested changes
Please sign CLA and write the pr title in the form `bpo.NNNN: ....`

2021-05-30 01:47 UTC, eamanu commented on Lib/asyncio/events.py
> +        if self._when < other._when:
We're sure that always other is TimeHandle?

2021-05-30 01:47 UTC, eamanu commented on Lib/asyncio/events.py
> +        path is a str, representing a file systsem path to bind the
typo

2021-05-30 01:47 UTC, eamanu commented on Lib/asyncio/events.py
> +                isinstance(threading.current_thread(), threading._MainThread)):
I dind't check deeply but, the intention of the original code is check fi current_thread() is the same object of main_thread(). Why are you change it?

2021-05-30 21:19 UTC, luizoti commented
@eamanu, now it's correct?

2021-06-02 21:20 UTC, domdfcoding commented
I don't see how most of the changes relate to the original issue?

2021-06-09 20:26 UTC, eamanu commented
@domdfcoding you're right, This PR/issue it's a little  confuse (for me)

2021-07-08 08:05 UTC, luizoti commented
I hadn't noticed the 'hypotheses', the truth is, 'in some situations'

2021-07-08 08:08 UTC, luizoti commented
I'm going to test this out during the day, and I'm going to try to give the.  correct follow-up to PR.

2021-07-08 20:04 UTC, luizoti commented
I performed more tests, initially this correction took effect, but it seems that it was just a mistake, at this moment the problem continues, I will close this PR and if I can actually find a correction I will submit it again.

2021-07-08 20:04 UTC, closed without merging