[2.7] bpo-29854: Backport for 2.7
python/cpython pull request #2637
Opened 2017-07-08 23:28 UTC by nirs

Tested on Fedora 25, FreeBSD 10.3, FreeBSD 11.0.

On OS X 10.11.6, python 2.7 builds without readline since configure fail to find rl_resize_terminal in -lreadline, so I could not test it.

@berkerpeksag, @haypo please review.

2017-07-09 10:49 UTC, berkerpeksag commented
> On OS X 10.11.6, python 2.7 builds without readline since configure fail to find rl_resize_terminal in -lreadline, so I could not test it.

That's a bit weird. I think it should build fine since all of the usages of rl_resize_terminal covered by the HAVE_RL_RESIZE_TERMINAL check. See [this](https://github.com/nirs/cpython/blob/0c393206563d18e2d15aeb5c9720b6b2a48e3470/Modules/readline.c#L1036-L1042) for an example. Could you post a little bit more information here?

2017-07-10 11:05 UTC, nirs commented
The issue is this check in setup.py:

```python
if host_platform == 'darwin':
    os_release = int(os.uname()[2].split('.')[0])
    dep_target = sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET')
    if (dep_target and
            (tuple(int(n) for n in dep_target.split('.')[0:2])
                < (10, 5) ) ): 
        os_release = 8
    if os_release < 9: 
        # MacOSX 10.4 has a broken readline. Don't try to build
        # the readline module unless the user has installed a fixed
        # readline package
        if find_file('readline/rlconf.h', inc_dirs, []) is None:
            do_readline = False```
```

When configuring 2.7, we MACOSX_DEPLOYMENT_TARGET is "10.4", and readline is 
disabled. When configuring master/3.6/3.5, we get "10.11", so readline is not disabled.

MACOSX_DEPLOYMENT_TARGET Identifies the earliest OS X version the product is to
run on. So with 2.7 we try to build a version that runs on any OS X version down to 10.4,
and in master/3.x we build only for the current version. I did not find why this happens.

This is also reproducible on travis OS X build, see:
https://travis-ci.org/python/cpython/jobs/251594769

```
Python build finished, but the necessary bits to build these modules were not found:
_bsddb             dl                 imageop         
linuxaudiodev      ossaudiodev        readline        
spwd               sunaudiodev                        
```

I think we need to open a separate issue for this, this is not related to this fix, since readline
is not built by default on OS X.

2017-07-10 11:42 UTC, vstinner requested changes
The backport lacks the test_readline change, and please use better PR title.

2017-07-10 14:52 UTC, berkerpeksag commented
> I think we need to open a separate issue for this, this is not related to this fix, since readline
> is not built by default on OS X.

Agreed, could you create a new issue on bugs.p.o?

2017-07-10 15:07 UTC, nirs commented
@haypo, the title is hopefully better now.

2017-07-10 16:32 UTC, haypo commented
>  [2.7] bpo-29854: Backport fix for 2.7 (without the test) #2637 

Sorry, but this title is still not good. I would prefer "[2.7] bpo-29854: Fix segfault in call_readline()".

Why not backporting the unit test?

2017-07-10 17:23 UTC, nirs commented
@haypo, the test depends on run_pty(), not available in 2.7, and it depends on the selectors module. Too much work for one test.

2017-07-10 20:44 UTC, vstinner approved these changes
LGTM.

It's ok to not backport the test.

2017-07-10 20:45 UTC, haypo commented
@berkerpeksag: What do you think?

2017-07-10 21:05 UTC, berkerpeksag approved these changes

2017-07-10 21:06 UTC, merged

2017-07-10 21:07 UTC, berkerpeksag commented
> @berkerpeksag: What do you think?

Agreed. I just merge the PR. Thank you all!