[3.5] bpo-30814: Add a test for concurrent relative import. (GH-2580).
python/cpython pull request #2645
Opened 2017-07-10 14:21 UTC by serhiy-storchaka

(cherry picked from commit b4baacee1adc06edbe30ac7574d17a8cd168e2e0)

2017-07-10 15:02 UTC, vstinner requested changes
Hum, the test fails on my Windows VM:

AttributeError: module 'package' has no attribute 'submodule'

If I modify the test to only run 1 loop iteration, the test pass, but fail if run again... It fails randomly.

Please don't add such test to 3.5 yet :-)

2017-07-10 15:03 UTC, haypo commented
Hum, I forgot to explain how I tested: I downloaded this PR in my 3.5 checkout of CPython on Windows, and ran the test using "python -m test -m test_concurrency -v test_import".

2017-07-10 15:13 UTC, serhiy-storchaka commented
Thanks for testing on Windows @haypo. Now we know that the bug exposed in bpo-30891 exists on 3.5.

2017-07-22 19:29 UTC, larryhastings commented
Just a reminder: I expect to tag 3.5.4rc1 in eleven or twelve hours.  If this is a *bugfix* (not a *security* fix), and it isn't merged by then, it will probably never be merged into 3.5.

2017-07-27 10:20 UTC, serhiy-storchaka commented
Since Victor's fix was not backported, the test can't be added.

2017-07-27 10:20 UTC, closed without merging

2017-07-27 10:24 UTC, haypo commented
Yeah, I agree that it's too late in the 3.5 cycle (moving to security-only fixes) for work on such old importlib bug.