csv readers take iterables as well as iterators
python/cpython pull request #2653
Opened 2017-07-11 00:36 UTC by graingert

2017-07-11 00:36 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-07-11 00:36 UTC, graingert commented
See https://github.com/python/cpython/blob/3.6/Modules/_csv.c#L1564-L1569

2017-07-14 01:50 UTC, bitdancer requested changes

2017-07-14 01:50 UTC, bitdancer commented on Doc/library/csv.rst
> +   is called when its :meth:`!__iter__` method is called --- :term:`file objects
I would suggest instead changing the original with the following minimal change:
   `...can be any iterable object whose iterator returns a string each time its...`

2017-07-14 01:50 UTC, bitdancer commented
I don't think this is completely trivial, so you should open an issue for it.

2017-07-14 23:07 UTC, vadmium commented on Doc/library/csv.rst
> +   The number of lines read from the source iterable. This is not the same as the
Why change this? If there is only one iterator involved, the original would be more precise.

2017-07-15 03:58 UTC, bitdancer commented on Doc/library/csv.rst
> +   The number of lines read from the source iterable. This is not the same as the
That's a good point, iterator is more correct here.

2018-02-02 22:04 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2018-02-02 22:10 UTC, graingert commented
Sadly I am unable to honestly say that

I have made the requested changes; please review again.

2018-02-02 22:10 UTC, graingert commented
However it was requested that I make an 'issue' first

2019-03-22 18:21 UTC, brettcannon commented
Closing as the CLA has not been signed within the last month.

2019-03-22 18:21 UTC, closed without merging