bpo-30781: IDLE: configdialog - switch to ttk widgets
python/cpython pull request #2654
Opened 2017-07-11 00:46 UTC by csabella

First set of commits for converting constants to string literals.

2017-07-11 03:44 UTC, mlouielu commented
Maybe I'm not on the date, does this a new policy to changed tkinter constant to string?

2017-07-11 11:41 UTC, csabella commented
On the last file that was converted to use ttk widgets, I also changed the constants to literal strings at the same time because Terry prefers the literal strings.  I was applying the same steps here.

2017-07-11 23:44 UTC, csabella commented
The latest commit converts to ttk widgets.  Some comments about the changes:
1.  In order to show the color changes for the themes, I needed to use a frame background.  The only way to do this in ttk is with a style, but I tried to minimize the impact of adding Style.
2.  The `Checkbutton` no longer has an `indicatoron` option, so they look a lot different on the extensions tab.
3.  I didn't convert `Scale` because the ttk version didn't have a `tickinterval`.  I believe this is being changed anyway, so I left it as is for now.

2017-07-28 22:48 UTC, terryjreedy commented
I am thinking that having NORMAL and DISABLED stand out is ok.  Don't change though yet.
The change of from .config to subscripting created conflicts.  We may introduce others before we get to this.

2017-07-28 23:54 UTC, csabella commented
Yes, I had been keeping up with resolving the conflicts, but haven't done it in a few days, since the restructuring to the classes got the momentum.  Once you're ready for this, I'll just do it all then.

2017-08-25 05:23 UTC, terryjreedy requested changes
For the ttk issue, I want a minimal patch that only does what is needed to make the switch, or to be consistent about state ('disabled' instead of DISABLED with '!disabled', and 'normal').  I noted most but perhaps not all of these.

   I believe everything other that the one note in the tests is needed.  For configdialog, 80% is extraneous, so I presume it would be easier to start fresh.

I definitely want to switch to True, False, and widget['option'] = value, but in a separate style issue, at least after disposing of existing patches.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/idle_test/test_configdialog.py
> +        eq(d.custom_theme_on.state(), (DISABLED,))
Make this 'disabled' to be consistent with '!disabled'.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> -                     HORIZONTAL, VERTICAL, ANCHOR, ACTIVE, END)
Leave these imports.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +        text['state'] = 'disabled'
Keep

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +                self.custom_theme_on.state(('disabled',))
Keep.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +            self.button_delete_custom.state(('!disabled',))
Keep block.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +            self.bg_on.state(('!disabled',))
Keep block.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +            self.custom_theme_on.state(('disabled',))
Keep.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +                command=self.get_new_keys, state='disabled')
Keep.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +                self.custom_keyset_on.state(('disabled',))
Keep.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +            self.button_delete_custom_keys.state(('!disabled',))
Keep block.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +        self.button_new_keys.state(('!disabled',))
Keep.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +            self.custom_keyset_on.state(('disabled',))
Keep.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +                frame_helplist_buttons, text='Edit', state='disabled',
Keep.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +                frame_helplist_buttons, text='Remove', state='disabled',
Keep.

2017-08-25 05:23 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
> +                self.button_helplist_remove.state(('disabled',))
Keep.

2017-08-25 14:30 UTC, csabella commented
I didn't expect the Spanish Inquisition!

2017-08-25 18:45 UTC, terryjreedy requested changes
Pending a 'human test', looks good.

In title of existing news blurb,  Misc/NEWS.d/next/IDLE/2017-07-28-18-59-06.bpo-30781.ud5m18.rst, change 'Notebook' to 'widgets'.  Add 'Patches by Terry Jan Reedy and Cheryl Sabella.

2017-08-25 18:45 UTC, terryjreedy commented on Lib/idlelib/configdialog.py
>  import tkinter.messagebox as tkMessageBox
I want to change these in a subsequent 'style' patch, either with other style changes for this file or a separate patch for all files.  Probably
```
from tkinter import colorchooser
from tkinter import messagebox
import tkinter.font as tkfont
```
I think `tkfont` may be necessary to not conflict with local `font` names.  Will check with grep first.

2017-08-25 19:21 UTC, csabella commented
I didn't expect the Spanish Inquisition!

2017-08-25 19:43 UTC, terryjreedy approved these changes

2017-08-26 18:26 UTC, merged