bpo-28879 : add date if missing in smtplib.send_message
python/cpython pull request #2655
Opened 2017-07-11 02:14 UTC by lafe3402

Hi I've tried to change the patch submitted on bpo-28879 to be on a github PR.

It's my first time contributing through PR, please let me know what I did wrong.

Regards,
Eric Lafontaine

2017-07-11 02:14 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-07-11 02:20 UTC, lafe3402 commented
oh wow... this is really a nice setup you've got running there!  I see that some check failed for some trailing whitespace in my files... 

Unfortunatly, I seems to be unable to look at the log anymore :S.

Anyway, how could I see it again?

2017-07-11 02:22 UTC, lafe3402 commented
Ok got to find how to see it again.  Now to understand what "trailing whitespace" is supposed to be for python and for... C (but I didn't touch the C part...)

2017-07-11 02:41 UTC, Mariatta commented
The clue is at this line in travis log: (https://travis-ci.org/python/cpython/jobs/252242241#L494)

```
library/smtplib.rst:499: trailing whitespace
```

There is an extra space after the word `no` in line 499 of `smtplib.rst`.
The space should be removed.

2017-07-11 07:38 UTC, mlouielu requested changes
Hello, welcome to CPython community, thanks for contributing with CPython, and here is some coding style issue with PEP8 that can be fixed in your PR!

2017-07-11 07:38 UTC, mlouielu commented on Lib/test/test_smtplib.py
> +
This only need two blankline to spacing class and class

2017-07-11 07:38 UTC, mlouielu commented on Lib/smtplib.py
> +
This only need one blankline.

2017-07-11 12:06 UTC, lafe3402 commented
I've followed the recommandation (thanks @Mariatta @mlouielu ).  How can I re-trigger the CI now that the commit seems to be in the PR?

2017-07-11 12:11 UTC, mlouielu commented
@lafe3402 CI will automatically re-trigger when you push your commit to GitHub. 

Also, I would recommend you to read this article: [How to write a git commit message](https://chris.beams.io/posts/git-commit/). This article is very useful that it tells how to write a good commit message. For example, your second commit message would be much better to changed to `Addressed somebody's comment' or `Fix coding style blankline`.

2017-07-11 13:37 UTC, lafe3402 commented
yeah... I though that I would have to make another PR request... so I've put what I've done in the subsection of the commit (it's in the expand the commit message if you expand it...).

Thanks a lot for the feedback :) you're really pro-active on the comment and I appreciate that.

Anything else I could do to ease the process?

Regards,
Eric Lafontaine

2017-07-12 12:16 UTC, mlouielu commented on Lib/smtplib.py
> +        if msg.get('Date',None) is None:
Here missing a whitespace after the `,`.

2017-07-12 12:18 UTC, mlouielu commented on Lib/test/test_smtplib.py
> +        smtp.send_message(m)
Maybe we can mock up the `email.utils.formatdate()` to ensure we have the same result to tests.

2017-07-12 12:18 UTC, mlouielu commented on Lib/test/test_smtplib.py
> +        current_moment = email.utils.formatdate()
see above to mock this up.

2017-07-13 13:08 UTC, lafe3402 commented on Lib/test/test_smtplib.py
> +        current_moment = email.utils.formatdate()
Thanks for the review :) I'll work on it tonight, my wife won't be home so I'll have nothing better to do :).

I'm not sure what you mean though on the "mock this up" but I guess you mean to use @mock(email.utils.formatdate) ?

I'll have to read to remember how to do it correctly if it's what you meant.

2017-07-20 17:52 UTC, lafe3402 commented
I'm sorry about this last re-commit, I can't run the test right now so I'm using the CI :$.

2017-07-21 02:15 UTC, mlouielu commented
@lafe3402 I can't pass the unittest on my laptop, too. You will need to check about the failed problem.

2017-08-03 21:16 UTC, lafe3402 commented
@mlouielu , thanks for your patience, I had trouble finding some free time.

2017-08-11 12:37 UTC, lafe3402 commented
Hi @mlouielu,

Would you have some feedback?  Just curious to see if there's something better I could've had done.

Regards,

2017-10-19 18:00 UTC, lafe3402 commented
@mlouielu @bitdancer,

Could you let me know what to do to accelerate the closure of this ticket?

2017-10-19 19:35 UTC, bitdancer commented
Find me some free time somewhere?  I'm sorry, I just don't have the cycles to look at this, nor will I any time soon :( :(

2017-11-20 19:00 UTC, lafe3402 commented
@bitdancer, Anything I could do to help you?  

I've been re-reading my question and I just don't want it to be misinterpreted as a "I want my request to get in!" kind of request.  I'm genuinely trying to help you guys.  I love python and I would love to contribute more.  

Also, David, are you the only one who can approve?  If yes, should I learn email modules and try to alleviate some of the pain?  

Again, sorry for asking here, but I would like more meat on how to contribute or how to learn what I need to contribute XD.

Regards,
Eric Lafontaine

2018-01-13 20:38 UTC, lafe3402 commented
Should I make a file in news.d ?

2018-01-13 22:31 UTC, lafe3402 commented
closing to re-open on a rebased project

2018-01-13 22:31 UTC, closed without merging