bpo-44339: Fix math.pow corner case to comply with IEEE 754
python/cpython pull request #26606
Opened 2021-06-08 17:04 UTC by mdickinson

This PR changes the behaviour of `math.pow(0.0, -math.inf)` and `math.pow(-0.0, -math.inf)` to return positive infinity instead of raising `ValueError`. This makes `math.pow` consistent with the built-in `pow` (and the `**` operator) for this particular special case, and brings the `math.pow` special-case handling into compliance with IEEE 754.

Before:
```python
Python 3.11.0a0 (heads/main:257e400a19, Jun  8 2021, 18:00:50) [Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import math
>>> math.pow(0.0, -math.inf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
>>> math.pow(-0.0, -math.inf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
```

After:
```python
Python 3.11.0a0 (heads/fix-float-pow-ieee-754-corner-case:1be10ea32f, Jun  8 2021, 17:43:05) [Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import math
>>> math.pow(0.0, -math.inf)
inf
>>> math.pow(-0.0, -math.inf)
inf
```

2021-06-08 17:05 UTC, mdickinson commented on Lib/test/ieee754.txt
> -
Accidental change; will revert.

2021-06-08 17:07 UTC, mdickinson commented on Lib/test/ieee754.txt
> -
Done.

2021-06-09 13:19 UTC, erlend-aasland approved these changes

2021-06-09 23:45 UTC, corona10 requested changes

2021-06-09 23:45 UTC, corona10 commented on Lib/test/test_math.py
> +        self.assertEqual(math.pow(0., NINF), INF)
For the consistent result check, 
I would like to suggest adding below tests

````python
self.assertEqual(math.pow(0., NINF), 0. ** NINF)
self.assertEqual(math.pow(-0., NINF), (-0.) ** NINF)
````

2021-06-10 05:56 UTC, corona10 commented on Lib/test/test_math.py
> +        self.assertEqual(math.pow(0., NINF), INF)
Ah, I read the following comment.
https://github.com/python/cpython/blob/40a928429d7f3951c0a593f39d1b26f7e02a7529/Lib/test/test_math.py#L1330

Please ignore my comment.

2021-06-10 05:56 UTC, corona10 approved these changes

2021-06-12 09:23 UTC, merged