bpo-44369: Improve syntax error for wrongly closed strings
python/cpython pull request #26633
Opened 2021-06-09 22:05 UTC by pablogsal

2021-06-10 00:19 UTC, akulakov commented on Grammar/python.gram
> +        "invalid syntax. Is this supposed to be part of the string?") }
Possibly slightly better phrasing "Is this intended to be..."

2021-06-14 17:06 UTC, erlend-aasland commented on Grammar/python.gram
> +        "invalid syntax. Is this supposed to be part of the string?") }
+1, @akulakov.

2021-10-08 20:36 UTC, pablogsal commented
Ok, I think this is ready :) @isidentical @lysnikolaou

2021-10-09 06:29 UTC, erlend-aasland approved these changes
LGTM :)

2021-10-09 06:42 UTC, isidentical approved these changes

2021-10-09 09:36 UTC, lysnikolaou approved these changes
Yup!

2022-11-23 23:53 UTC, iritkatriel requested changes, later dismissed
This has merge conflicts now.

2024-03-25 13:14 UTC, encukou commented
I've rebased. This looks like a nice improvement.

I did need to modify an additional test, though -- see 36758b8b04648d424709bb4592946627eb54499a. That looks like an improvement, but I'm not sure how it's related to this change.

2025-02-13 01:30 UTC, merged