bpo-44408 imaplib, handle extra blank response line
python/cpython pull request #26701
Opened 2021-06-13 05:35 UTC by jrlevine

Some (buggy) IMAP servers add an extra blank line after a literal value. This ignores the blank line.
MacOS mail and T'bird can deal with the blank line so it seems to be a somewhat common server bug.

2021-06-13 05:35 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@jrlevine

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2024-02-27 13:35 UTC, serhiy-storchaka requested changes
Please add tests and a news entry.

2024-02-27 13:36 UTC, serhiy-storchaka commented
Oh, and the PR should be against the `main` branch.

2024-10-23 22:43 UTC, zware commented
This, like GH-26709, also looks like a reasonable change, but also needs to be recreated against `main`.

2024-10-23 22:43 UTC, closed without merging