Fix typo in ssl deprecation warning message
python/cpython pull request #26754
Opened 2021-06-16 12:57 UTC by j178

`ssl.SSL_NO_TLS` should be `ssl.OP_NO_TLS`.

2021-06-16 12:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@j178

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-06-16 13:02 UTC, tiran approved these changes

2021-06-16 13:48 UTC, tiran requested changes
Please update ``test_openssl111_deprecations`` test case and sign the contribute agreement.

2021-06-17 01:23 UTC, j178 commented
Updated test

2021-06-17 09:39 UTC, tiran approved these changes

2021-06-17 09:39 UTC, merged

2021-06-17 09:39 UTC, miss-islington commented
Thanks @j178 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖