bpo-40928: notify users of osx malloc warnings
python/cpython pull request #26783
Opened 2021-06-18 12:10 UTC by jdevries3133

This is a bandaid to help people save time debugging this non-bug. I don't think this solution is very strong; I'm just hoping to move the discussion forward on the bpo, and hoping for a hint on how to suppress these warnings all together or come up with some other optimal solution.

I applied the function in test_decimal because that test consistently generates these malloc warnings on my system.

2021-06-18 14:01 UTC, jdevries3133 commented
This is one of two potential fixes I've provided for bpo-40928. The other fix, #26786, gets more to the root of the problem. This is more of a simple band-aid.

2021-08-02 17:16 UTC, ambv requested changes
This is a safe change to introduce regardless of what we do with the root cause.

2021-08-02 17:16 UTC, ambv commented on Lib/test/support/__init__.py
> +    detail = ('test_decimal may generate "malloc can\'t allocate region"\n'
Extract `test_decimal` to a function argument called "test_name".

2021-08-02 17:16 UTC, ambv commented on Lib/test/support/__init__.py
> +    """Assure user that loud errors generated by OS X libc's malloc are
There is no "OS X", change all such usage to "macOS" instead.

2021-08-02 19:42 UTC, jdevries3133 commented
@ambv Ok, your suggested changes were incorporated in 4859c7ef7526d4a0d5745c780de8a85ce8d2ff12. Thanks!

2021-08-02 19:43 UTC, jdevries3133 commented
I have made the requested changes; please review again

2021-08-06 12:50 UTC, merged

2021-08-06 12:51 UTC, miss-islington commented
Thanks @jdevries3133 for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖

2021-08-06 12:51 UTC, miss-islington commented
Thanks @jdevries3133 for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2021-08-06 12:51 UTC, miss-islington commented
Sorry @jdevries3133 and @ambv, I had trouble checking out the `3.9` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 15d3c14df32a35ac69898a7852115722e30d7857 3.9
                                ```

2021-08-06 12:51 UTC, miss-islington commented
Thanks @jdevries3133 for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖

2021-08-06 12:51 UTC, miss-islington commented
Sorry, @jdevries3133 and @ambv, I could not cleanly backport this to `3.9` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 15d3c14df32a35ac69898a7852115722e30d7857 3.9
                                ```