trivial: Fix warning in _json.c due to char being unsigned on some platforms
python/cpython pull request #2684
Opened 2017-07-12 17:16 UTC by segevfiner

From buildbots:
```
/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Modules/_json.c: In function ‘scanner_new’:
/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Modules/_json.c:1212:5: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if (s->strict < 0)
     ^
```

I didn't test this.

2017-07-12 17:46 UTC, serhiy-storchaka requested changes

2017-07-12 17:46 UTC, serhiy-storchaka commented on Modules/_json.c
> +    int strict;
`T_BOOL` below requires a field of type `char`.

2017-07-12 18:00 UTC, serhiy-storchaka commented
I think you could just use `signed char`.

2017-07-12 19:48 UTC, segevfiner commented
I just hope this doesn't end up triggering a signed/unsigned mismatch warning 😛

![Bug Toggle GIF](https://media.giphy.com/media/11ZSwQNWba4YF2/giphy.gif)

2017-07-13 05:49 UTC, serhiy-storchaka approved these changes

2017-07-13 05:52 UTC, merged