bpo-42369: Fix thread safety of zipfile._SharedFile.tell
python/cpython pull request #26974
Opened 2021-06-30 19:02 UTC by kevinmehall

The `_SharedFile` tracks its own virtual position into the file as `self._pos` and updates it after reading or seeking. `tell()` should return this position instead of calling into the underlying file object, since if multiple `_SharedFile` instances are being used concurrently on the same file, another one may have moved the real file position. Additionally, calling into the underlying `tell` may expose thread safety issues in the underlying file object because it was called without taking the lock.

Prior to this fix, the test case in https://bugs.python.org/issue42369#msg381212 reliably caused a `zipfile.BadZipFile: Bad CRC-32 for file 'file1'` in less than a second; with this fix I have not seen this error.

2021-07-13 04:19 UTC, ain-soph commented
Nice! This could certainly help me solve the issue in machine learning when I want to load data from a zip file.  
Hope its priority gets higher.

2022-03-19 19:22 UTC, serhiy-storchaka approved these changes

2022-03-19 19:27 UTC, serhiy-storchaka requested changes
LGTM, but please add a NEWS file.

2022-03-19 20:29 UTC, kevinmehall commented
I have made the requested changes; please review again

(hopefully got the rst formatting right)

2022-03-20 14:25 UTC, serhiy-storchaka approved these changes

2022-03-20 14:26 UTC, merged

2022-03-20 14:26 UTC, miss-islington commented
Thanks @kevinmehall for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖

2022-03-20 14:26 UTC, miss-islington commented
Thanks @kevinmehall for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖

2022-03-20 14:27 UTC, serhiy-storchaka commented
Thank you @kevinmehall.