bpo-44666: Use default encoding as fallback for compile_file
python/cpython pull request #27236
Opened 2021-07-19 10:53 UTC by stefanhoelzl

When sys.stdout.encoding is None compile_file will fall back to
sys.getdefaultencoding to encode/decode error messages.

2021-07-21 09:15 UTC, BoboTiG requested changes
Thank you for the patch. Could you also add a NEWs entry please?

2021-07-21 09:15 UTC, BoboTiG commented on Lib/compileall.py
> +                    else sys.getdefaultencoding()
That could be rewritten to:
```suggestion
                encoding = sys.stdout.encoding or sys.getdefaultencoding()
```

2021-07-21 10:46 UTC, stefanhoelzl commented
Thanks for the review.

> Thank you for the patch. Could you also add a NEWs entry please?
done

2021-07-21 15:10 UTC, BoboTiG commented on Misc/NEWS.d/next/Library/2021-07-21-10-43-22.bpo-44666.CEThkv.rst
> +fixed issue in :func:`compileall.compile_file` when ``sys.stdout`` is redirected
```suggestion
Fixed issue in :func:`compileall.compile_file` when ``sys.stdout`` is redirected.
Patch by Stefan Hölzl.
```

2021-07-21 15:11 UTC, BoboTiG approved these changes

2021-07-22 20:41 UTC, BoboTiG approved these changes
👍 Thank you @stefanhoelzl.

2021-07-30 16:38 UTC, merged

2021-07-30 16:38 UTC, miss-islington commented
Thanks @stefanhoelzl for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.9.
🐍🍒⛏🤖