Improve binary portability between MacOS versions
python/cpython pull request #27251
Opened 2021-07-20 01:00 UTC by bergkvist

# Improve binary portability between MacOS versions
When compiling CPython using a MacOS Catalina build server, it won't work as expected when trying to run it on MacOS Big Sur. In particular, `ctypes.util.find_library(name)` will always return None. This PR fixes that issue.

## Background

Checking if a shared library exists on MacOS Big Sur is no longer possible by looking at the file system. Instead, Apple recommends the use of dlopen to check if a shared library exists:

### [MacOS Big Sur 11.0.1 changenotes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes)
> *New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)*

### _dyld_shared_cache_contains_path and build time requirements
The current solution (introduced in https://github.com/python/cpython/pull/22855) to make find_library work on MacOS Big Sur does not use dlopen, but rather _dyld_shared_cache_contains_path from `#include <mach-io/dyld>`. This function/symbol is only available on MacOS Big Sur, meaning it will only be included if you compile CPython on MacOS Big Sur.

In other words, if we compile CPython on MacOS Catalina, and move the binary to MacOS Big Sur, `from _ctypes import _dyld_shared_cache_contains_path` will raise an ImportError - and find_library will not work, always returning None.
```diff
# ctypes/macholib/dyld.py
# ...

+try:
+    from _ctypes import _dyld_shared_cache_contains_path
+except ImportError:
+    def _dyld_shared_cache_contains_path(*args):
+        raise NotImplementedError

# ...

def dyld_find(name, executable_path=None, env=None):
    """
    Find a library or framework using dyld semantics
    """
    for path in dyld_image_suffix_search(chain(
                dyld_override_search(name, env),
                dyld_executable_path_search(name, executable_path),
                dyld_default_search(name, env),
            ), env):

        if os.path.isfile(path):
            return path
+        try:
+            if _dyld_shared_cache_contains_path(path):
+                return path
+        except NotImplementedError:
+            pass
# ...
```

## Method/Verification
If we instead use dlopen to check for library existence (as recommended by Apple in the release notes), we don't depend on any symbols that are only available on MacOS Big Sur. That means we can compile on an older version of MacOS, copy the binaries over - and find_library will work as expected.

To test that this works, I've set up 2 virtual machines using [OSX-KVM](https://github.com/kholia/OSX-KVM) on a Manjaro Linux host:
- Catalina (*OS: macOS Catalina 10.15.7 19H15 x86_64, Kernel 19.6.0*)
- Big Sur (*OS: macOS 11.4 20F71 x86_64, Kernel: 20.5.0*)

Files are copied between the 2 virtual machines using rsync:
```sh
#!/usr/bin/env bash
rm -rf "./local"
if [ "$1" = "BigSur" ]; then
	echo "Pulling from Catalina... (/usr/local/ -> ./local)"
	rsync -a -e "ssh -p 2222" tobias@localhost:/usr/local .
	echo "Pushing to BigSur... (./local/ -> /usr/local)"
	rsync -a -e "ssh -p 3222" ./local/* tobias@localhost:/usr/local/
else
	echo "Pulling from BigSur... (/usr/local/ -> ./local)"
	rsync -a -e "ssh -p 3222" tobias@localhost:/usr/local .
	echo "Pushing to Catalina... (./local/ -> /usr/local)"
	rsync -a -e "ssh -p 2222" ./local/* tobias@localhost:/usr/local/
fi
echo "Done!"
```

### Checks
- Compile on **Manjaro Linux**, run test suite on **Manjaro Linux**, install and call `find_library('c')`
- Compile on **Catalina**, run test suite, install and call `find_library('c')`
- Compile on **Big Sur**, run test suite, install and call `find_library('c')`
- Compile on **Catalina** and install, copy `/usr/local/*` over to **BigSur**, and call `find_library('c')`
- Compile on **Big Sur** and install, copy `/usr/local/*` over to **Catalina**, and call `find_library('c')`

## Results
### Before this change:
:heavy_check_mark: Compile on **Manjaro Linux**, run test suite on **Manjaro Linux**, install and call `find_library('c')`
```
Python 3.11.0a0 (heads/main-dirty:635bfe8162, Jul 19 2021, 17:11:32) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; print(find_library('c'))
libc.so.6
```
:heavy_check_mark: Compile on **Catalina**, run test suite on **Catalina**, install and call `find_library('c')`
```
Python 3.11.0a0 (heads/main:635bfe8162, Jul 19 2021, 08:09:05) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; print(find_library('c'))
/usr/lib/libc.dylib
```

:heavy_check_mark: Compile on **Big Sur**, run test suite on **Big Sur**, install and call `find_library('c')`
```
Python 3.11.0a0 (heads/main:635bfe8162, Jul 19 2021, 08:28:48) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; print(find_library('c'))
/usr/lib/libc.dylib
```
:x: Compile on **Catalina** and install, copy `/usr/local/*` over to **BigSur**, and call `find_library('c')`
```
Python 3.11.0a0 (heads/main:635bfe8162, Jul 19 2021, 08:09:05) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; print(find_library('c'))
None
```

:x: Compile on **Big Sur** and install, copy `/usr/local/*` over to **Catalina**, and call `find_library('c')`
```
Python 3.11.0a0 (heads/main:635bfe8162, Jul 19 2021, 08:28:48) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; print(find_library('c'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/usr/local/lib/python3.11/lib-dynload/_ctypes.cpython-311-darwin.so, 2): Symbol not found: __dyld_shared_cache_contains_path
  Referenced from: /usr/local/lib/python3.11/lib-dynload/_ctypes.cpython-311-darwin.so (which was built for Mac OS X 11.4)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.11/lib-dynload/_ctypes.cpython-311-darwin.so
```

### After this change:
:heavy_check_mark: Compile on **Manjaro Linux**, run test suite on **Manjaro Linux**, install and call `find_library('c')`
```
Python 3.11.0a0 (heads/main-dirty:635bfe8162, Jul 19 2021, 17:11:32) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; print(find_library('c'))
libc.so.6
```
:heavy_check_mark: Compile on **Catalina**, run test suite, install and call `find_library('c')`
```
Python 3.11.0a0 (heads/macos-ctypes-find-library:0858c0c9ff, Jul 19 2021, 17:52:24) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; print(find_library('c'))
/usr/lib/libc.dylib
```
:heavy_check_mark: Compile on **Big Sur**, run test suite, install and call `find_library('c')`
```
Python 3.11.0a0 (heads/macos-ctypes-find-library:0858c0c9ff, Jul 19 2021, 17:54:12) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; print(find_library('c'))
/usr/lib/libc.dylib
```
:heavy_check_mark: Com [...]

2021-07-20 01:00 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@bergkvist

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-07-20 23:15 UTC, bergkvist commented
Since this PR suggests changes to code that was merged in #22855, I'd love a review from @ronaldoussoren
This might also be relevant to @ned-deily, @serhiy-storchaka, @vstinner - since you guys were involved with that PR.

2021-07-25 19:28 UTC, erlend-aasland reviewed
I'll leave the technical review to Ronald, but I've left some remarks regarding code style (PEP 7).

BTW, did you read the discussion in GH-21241 regarding `_dyld_shared_cache_contains_path`?

2021-07-25 19:28 UTC, erlend-aasland commented on Misc/NEWS.d/next/macOS/2021-07-20-22-27-01.bpo-44689.mmT_xH.rst
> +You no longer need to compile Python on the same version of MacOS that you will be running it on (Catalina vs Big Sur) in order for ctypes.util.find_library to work.
Nitpick:
- MacOS => macOS
- Use reST markup

```suggestion
You no longer need to compile Python on the same version of macOS that you
will be running it on (Catalina vs Big Sur) in order for
:meth:`ctypes.util.find_library` to work.
```

2021-07-25 19:28 UTC, erlend-aasland commented on Modules/_ctypes/callproc.c
> +    void* handle;
C99 is now accepted, so please use intermingled declaration and move this down to line 1458:

```c
    void *handle = dlopen(name_str, RTLD_LAZY);
```

2021-07-25 19:28 UTC, erlend-aasland commented on Modules/_ctypes/callproc.c
> +        return NULL;
PEP 7: _"All new C code requires braces"_

This also applies when modifying existing code, so I'd add braces for those `if`'s.

2021-07-25 19:28 UTC, erlend-aasland commented on Modules/_ctypes/callproc.c
> +    } else {
```suggestion
    }
    else {
```

2021-07-26 01:28 UTC, bergkvist commented
Thanks a lot for the feedback @erlend-aasland - and for linking the discussion about _dyld_shared_cache_contains_path. Do you know if there a VSCode plugin for checking or auto-formatting C code according to PEP 7?

I discussed a bit with Ronald on [the issue linked to this PR](https://bugs.python.org/issue44689), and he made me realize that using dlopen to check for library existence is not a good idea because it can have side effects. A shared library can execute arbitrary code when opened with dlopen. This is why _dyld_shared_cache_contains_path is currently being used instead.

Instead of checking for _dyld_shared_cache_contains_path at compile time - it is possible to resolve it at run-time (dynamic loading) - and provide a fallback function which always returns false if the symbol does not exist. Then it won't matter whether the compilation happened on Catalina or Big Sur. I'll make an attempt at implementing this over the next few days.

2021-07-27 23:15 UTC, erlend-aasland commented
> Do you know if there a VSCode plugin for checking or auto-formatting C code according to PEP 7?

Sorry, I do not; I don't use VSCode, I use Vim.

2021-08-02 13:15 UTC, yaitskov commented
I would like to see this merged too, because having custom build of cpython in nix is a bit pain - some functions are private and has to be copy-pasted.

2021-08-04 23:57 UTC, ned-deily requested changes
Thanks for the updated PR.  Please see my recent detailed response on the bug tracker issue for comments that apply to this version.

2021-08-06 11:20 UTC, bergkvist commented
I have made the requested changes; please review again

2021-08-07 09:05 UTC, ronaldoussoren approved these changes
The PR looks good to me, from staring at the code.  I have not yet tried building on an older macOS version and running tests on Big Sur.

2021-08-07 10:34 UTC, ned-deily commented
I will review and test it next week.

2021-08-30 06:25 UTC, ned-deily approved these changes

2021-08-30 06:55 UTC, merged

2021-08-30 06:55 UTC, miss-islington commented
Thanks @bergkvist for the PR, and @ned-deily for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8, 3.9, 3.10.
🐍🍒⛏🤖