bpo-30935: update get_event_loop docs
python/cpython pull request #2731
Opened 2017-07-16 07:49 UTC by daxlab

2017-07-16 10:10 UTC, cjerdonek commented on Doc/library/asyncio-eventloops.rst
> +      Get the event loop for the current coroutine.
You want to say this not in the documentation of the interface, but in the documentation of the default policy.

Also, in the bpo issue I suggested adding a "Changed in 3.6" directive, but I don't see that here.

2017-07-16 10:58 UTC, daxlab commented on Doc/library/asyncio-eventloops.rst
> +      Get the event loop for the current coroutine.
Isn't it already [there](https://github.com/python/cpython/blob/master/Doc/whatsnew/3.6.rst#L821) ?

2017-07-16 16:02 UTC, cjerdonek commented on Doc/library/asyncio-eventloops.rst
> +      Get the event loop for the current coroutine.
In "What's New," yes, but not in the asyncio section of the docs.

2017-07-16 16:08 UTC, cjerdonek commented on Doc/library/asyncio-eventloops.rst
> +      Get the event loop for the current coroutine.
See the documentation of [`AbstractEventLoop.run_forever()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.run_forever) for an example. In this case, it says, "Changed in version 3.5.1."

2017-09-10 14:27 UTC, Mariatta requested changes
Please add the "Changed in 3.6" directive as suggested by @cjerdonek

2017-10-01 09:27 UTC, daxlab commented
I didn't expect the Spanish Inquisition!

2017-10-01 20:19 UTC, cjerdonek requested changes
This still doesn't update the [`get_event_loop()`](https://docs.python.org/3/library/asyncio-eventloops.html#asyncio.AbstractEventLoopPolicy.get_event_loop) docs as I said in the original bpo issue and in my previous review comment.

2017-10-19 17:52 UTC, 1st1 commented
Please update the docstring of `get_event_loop()`

2018-02-22 23:20 UTC, csabella commented
@daxlab  There were some additional changes requested since your last commit.  Would you be able to take a look at those?  Thanks!

2018-05-29 16:27 UTC, 1st1 approved these changes

2018-05-29 18:37 UTC, merged