bpo-72378: fixed log truncation on logging shutdown
python/cpython pull request #27310
Opened 2021-07-23 16:36 UTC by akulakov

2021-07-25 07:22 UTC, vsajip requested changes
Generally looks OK, but I would suggest the following changes:

* `_closed = True` is done in `Handler.close()`, and so there is a reliance that `FileHandler.close()` will call the superclass' `close()`. Of course it does, and there is a comment there about bpo-19523 and avoiding a handler leak, but I would add under that something  like
  ```
  # See also bpo-42378: we also rely on
  # self._closed being set to True there
  ```
* As you've added `next_rec()` to `BaseFileTest`, it can be removed from `RotatingFileHandlerTest`, which inherits from `BaseFileTest`.
* And, of course, add the documentation update and NEWS entry, as you've mentioned on the issue,

Thanks!

2021-07-25 12:48 UTC, akulakov commented
@vsajip Thanks for the review! 
I pushed an update per comments, PTAL..

2021-07-25 19:39 UTC, vsajip requested changes
Just minor changes suggested to the documentation part. Thanks!

2021-07-25 19:39 UTC, vsajip commented on Doc/library/logging.handlers.rst
> +      mode is 'w', record will not be emitted (see :issue:`42378`).
I would change "file mode" to "the file mode" and "record" to "the record".

2021-07-25 19:56 UTC, akulakov commented
@vsajip fixed the docs per comment..

2021-07-25 20:07 UTC, vsajip approved these changes

2021-07-25 20:17 UTC, miss-islington commented
@akulakov: Status check is done, and it's a success ✅ .

2021-07-25 20:17 UTC, merged

2021-07-25 22:55 UTC, akulakov commented
thanks @vsajip !

2022-01-07 21:52 UTC, miss-islington commented
Thanks @akulakov for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖