Remove 404 Page link
python/cpython pull request #27320
Opened 2021-07-24 08:04 UTC by rohitnishad613

https://mail.python.org/mailman/listinfo/python-porting this link is broken and return 404 error. So i just removed it.
Also, this page is about proting code so i linked out to my own python converter tool. (Its not a paid tool)

2021-07-24 08:04 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@rohitnishad613

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-07-26 15:10 UTC, rohitnishad613 commented
I signed PSF CA but added...
Is there anything wrong?

2021-07-28 21:01 UTC, Mariatta commented
@rohitnishad613 You also need to create the b.p.o account, and then put in your GitHub username in the b.p.o profile.

2021-07-28 21:09 UTC, Mariatta commented
So python-porting mailing list used to exist but it was retired a couple years ago.
See the thread about it here: https://mail.python.org/archives/list/python-dev@python.org/thread/6436V5ATEGKUGRQU5ONV27PUL2O4TMR4/

The archive is still accessible at  https://mail.python.org/pipermail/python-porting/
I would simply replace the link with this one, instead of recommending a third-party tool.

2021-07-28 21:12 UTC, Mariatta requested changes
I prefer we link to the archived mailing list instead of linking to a third party tool.

2021-07-28 21:12 UTC, Mariatta commented on Doc/howto/pyporting.rst
> +   For help with porting, you can use this python-converter-tool_.
```suggestion
   For help with porting, you can view the archived python-porting_ mailing list.
```

2021-07-28 21:12 UTC, Mariatta commented on Doc/howto/pyporting.rst
> +.. _python-converter-tool: https://360techexplorer.com/tools/python-2-to-3-converter/
```suggestion
.. _python-porting: https://mail.python.org/pipermail/python-porting/
```

2021-07-29 03:40 UTC, rohitnishad613 commented
I have made the requested changes; please review again.

Plus, I have a question I made a web tool "Python 2 to 3 converter" I think that tool is worth linking so, can I link it here?

2021-08-04 18:53 UTC, merged

2021-08-04 18:54 UTC, miss-islington commented
Thanks @rohitnishad613 for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.9.
🐍🍒⛏🤖