bpo-30938: Add pdb command to show user-owned variables
python/cpython pull request #2732
Opened 2017-07-16 11:30 UTC by FrontSide

Add debugger commands "who" and "whos" - similar to the
ones from ipython - to list the names of user-owned variables (who)
and user-owned variable names together with the variable type
and the assigned value.

Manually tested.

Example:
```
>>> import pdb 
>>> x = 1 
>>> y = {'key': 'value'}
>>> pdb.set_trace()
(Pdb) who
x       y 
(Pdb) whos
Variable        Type    Data/Info
------------------------------  
x               int     1   
y               dict    {'key': 'value'}
```

2017-07-16 11:30 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-07-16 11:36 UTC, FrontSide commented
Just added my GitHub username to my bugs.python.org profile there.

2019-02-15 21:35 UTC, blueyed commented
Interesting!
Please add tests for it.

2020-08-20 11:56 UTC, iritkatriel commented
David, this has been open for a while. Are you planning to work on the tests? If not I wouldn't mind trying.

2020-08-20 13:29 UTC, FrontSide commented
Go for it @iritkatriel. Would love to see this getting merged : )

2020-09-01 23:36 UTC, iritkatriel commented
I have some changes to your code in https://github.com/iritkatriel/cpython/tree/whos (I'm not sure how to make a PR into this branch. Also, this branch needs to be rebased). 

The changes are (1) refactor out the bit that creates the user vars list. (2) I changed the code that iterates over them in whos so that globals are correctly shadowed by locals.

For whos, I think there is a lot more work to do to make it render neatly when the values are large.

I started writing a unit test for who, but got into a problem where I think it picked up a lot of names from the unit test module.

2022-02-22 18:14 UTC, MaxwellDupre requested changes
Nice addition, but I would expect a NEWS entry and a change to the docs so that user are aware.

2022-06-21 21:31 UTC, iritkatriel commented
Closing since this was abandoned by the OP.

2022-06-21 21:31 UTC, closed without merging