bpo-26184: import.rst: Add versionchanged note
python/cpython pull request #277
Opened 2017-02-24 20:08 UTC by Mariatta

Add versionchanged note indicating that an ImportError is raised when exec_module() is defined, but create_module() is not.

http://bugs.python.org/issue26184

2017-02-24 20:13 UTC, Carreau approved these changes

2017-02-24 22:33 UTC, marco-buttu requested changes
Hi @Mariatta , it LGTM, but I would like you to add just a minor change, not directly related with this PR. In the first `versionadded` of the [Loaders](https://docs.python.org/3/reference/import.html#loaders) section, we do not have any markup for `create_module()`:

```
.. versionadded:: 3.4
   The create_module() method of loaders.
```

It should be:

```
.. versionadded:: 3.4
   The :meth:`~importlib.abc.Loader.create_module`  method of loaders.
```

Thank you very much

2017-02-25 00:06 UTC, Mariatta commented
Thanks for the review, @Carreau and @marco-buttu .

@marco-buttu, the change that you requested will require backport to 3.5 and 3.6 branches, whereas this PR will only be backported to 3.6.

I will make that change as a separate PR from this.

2017-02-25 11:24 UTC, marco-buttu commented
@Mariatta I opened a [bpo-29648](http://bugs.python.org/issue29648) issue for the missing reference to `create_module()`. I am making the PR.

2017-02-25 11:25 UTC, marco-buttu approved these changes

2017-02-26 15:36 UTC, merged

2017-02-26 17:26 UTC, berkerpeksag commented on Doc/reference/import.rst
> +   ``create_module`` is not.
I guess create_module should create_module() here since the latter form is also used in the first versionchanged note.

2017-02-26 21:09 UTC, Mariatta commented on Doc/reference/import.rst
> +   ``create_module`` is not.
Thanks for catching this, @berkerpeksag! I fixed it in GH-325