bpo-24955: Fix webbrowser broken on Mac OS X when using the BROWSER variable
python/cpython pull request #27751
Opened 2021-08-13 01:45 UTC by hudelgado

Fixes an issue with webbrowser by removing unused __init__ method.

https://bugs.python.org/issue24955

co-authored-by: Simon Conseil <sconseil>

2021-08-17 16:47 UTC, corona10 requested changes
Please add the NEWS.d for this change
See: https://devguide.python.org/#quick-reference (How to use blurb tool)

2021-08-17 16:49 UTC, corona10 requested changes
https://bugs.python.org/issue42255#msg380293

Since @ronaldoussoren wants to deprecate and remove it.
It looks like to good to change the PR

2021-09-08 17:31 UTC, ambv commented
@hudelgado, we'll need this refactored on the current state of webbrowser.py which deprecated the `MacOSX` class.

2022-04-04 12:44 UTC, kittydoor commented
I understand that it is sometimes not so simple, but as a user I've stumbled on this bug over multiple years and had to dig in really deep to figure out what even the real issue is for the errors I was having (finally ending up here). I feel like it might have been more pragmatic to merge and release this fix asap, and only after focus on deprecation with the proper notices as per procedure.

2023-12-20 09:04 UTC, ronaldoussoren commented
Closing this PR because it is no longer necessary, main branch is already updated as is 3.11.

2023-12-20 09:04 UTC, closed without merging