bpo-44903: Removed othergui.rst and list of GUI frameworks
python/cpython pull request #27762
Opened 2021-08-13 18:48 UTC by quantumgc

In their places I've added links to the python wiki [page on GUI frameworks](https://wiki.python.org/moin/GuiProgramming).

2021-08-13 19:28 UTC, zware requested changes
Overall, I'd say this is going in the right direction and about 90% there :)

2021-08-13 19:28 UTC, zware commented on Doc/faq/gui.rst
>  ========================================================
Nit: shorten the underline to match the heading:

```suggestion
===================================
```

2021-08-13 19:28 UTC, zware commented on Doc/faq/gui.rst
> -Mac OS X, Windows, and Unix platforms.
We should keep a mention of Tkinter here, since it's included with Python.

2021-08-13 19:28 UTC, zware commented on Doc/library/tk.rst
> +<https://wiki.python.org/moin/GuiProgramming>`_.
It looks like most of the change here is just reflowing the text, which makes it harder to review.  Could you please revert the reflow?

2021-08-13 20:10 UTC, quantumgc commented
I've reverted the reflow and shortened the underline. I kept the original paragraph on tkinter, just moving it upwards and slightly changing the paragraph which mentions the alternatives.

2021-08-17 09:00 UTC, merged

2021-08-17 09:01 UTC, miss-islington commented
Thanks @quantumgc for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖

2021-08-17 09:01 UTC, miss-islington commented
Sorry @quantumgc and @ambv, I had trouble checking out the `3.10` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 6a358bb9482f7595b858ea7b800cbe66f0de5fa1 3.10
                                ```

2021-08-17 09:02 UTC, miss-islington commented
Thanks @quantumgc for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖