bpo-44888: Add ssl.OP_LEGACY_SERVER_CONNECT
python/cpython pull request #27776
Opened 2021-08-16 03:58 UTC by xtkoba

Required for making OpenSSL 3.0.0 behave like 1.1.1.

2021-08-16 03:58 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@xtkoba

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-08-16 04:09 UTC, xtkoba commented
See also https://github.com/openssl/openssl/issues/16278

2021-08-17 12:51 UTC, ambv commented
Please add a NEWS entry.

2021-08-17 12:52 UTC, tiran commented
Please also add documentation update and a test case.

2021-08-18 11:20 UTC, tiran requested changes

2021-08-18 11:20 UTC, tiran commented on Doc/library/ssl.rst
> +   only.
Please add ``This option is only available with OpenSSL 3.0.0 and later.``.

2021-08-18 11:20 UTC, tiran commented on Lib/test/test_ssl.py
> +OP_LEGACY_SERVER_CONNECT = getattr(ssl, "OP_LEGACY_SERVER_CONNECT", 0)
This does neither verify that the option exists nor that it works as expected. Please include a full test case that performs a network connection with the option set on the server context.

2021-08-18 16:14 UTC, xtkoba commented
I have made the requested changes; please review again.

Note that the connection test would really require an "unpatched" server, which I didn't come up with how to prepare.

2021-09-15 18:39 UTC, closed without merging

2022-02-04 16:49 UTC, tiran commented
The changeset has not been merged and the flag is not available. @xtkoba closed the PR.

2022-03-28 11:00 UTC, hjmallon commented
Note to self/others, I was able to work around by manually setting the numeric value.

```python
ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
ctx.options |= 0x4
```