bpo-41379 Clarification on options needed for indentation
python/cpython pull request #27830
Opened 2021-08-19 11:41 UTC by TheHippiez

Added comment about empty_lines_in_values=False to the example .ini file.

2021-08-19 11:41 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@TheHippiez

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-03-10 10:20 UTC, MaxwellDupre approved these changes
Looks ok.

2022-04-03 23:06 UTC, JelleZijlstra requested changes
When I tried this on main I found that the string fails to parse regardless of the value of the `empty_lines_in_values` parameter to the ConfigParser constructor.

However, it works when setting `allow_no_value=True`:

```
In [14]: config = configparser.ConfigParser(allow_no_value=True)

In [15]: config.read_string(s)

In [16]: config.sections()
Out[16]: 
['Simple Values',
 'All Values Are Strings',
 'Multiline Values',
 'No Values',
 'You can use comments',
 'Sections Can Be Indented']
```

(`s` is this example)

Also, a comment deep in the example code isn't very discoverable. We should mention the required option in the "For example:" header instead.

2022-04-11 22:08 UTC, iritkatriel commented
Closing as [issue41379](https://bugs.python.org/issue41379) was rejected.

2022-04-11 22:30 UTC, TheHippiez commented
It was not rejected, it needed changes. Why was this closed?

2022-04-11 22:44 UTC, iritkatriel commented
https://bugs.python.org/issue41379 was closed as "not a bug".

2022-04-11 22:56 UTC, JelleZijlstra commented
I do think there should be a clarification to say that the example needs `allow_no_value=True` (see my comment above).

2022-04-11 23:14 UTC, iritkatriel commented
> I do think there should be a clarification to say that the example needs `allow_no_value=True` (see my comment above).

Ok, I've reopened the issue at https://github.com/python/cpython/issues/85551.

2022-10-11 06:57 UTC, TheHippiez commented
I'm unsure what your saying right now.

Op wo 9 mrt. 2022 18:11 schreef Mike cm ***@***.***>:

> See:
>
> ConfigParser Objects
> class configparser.ConfigParser(defaults=None, dict_type=dict,
> allow_no_value=False, delimiters=('=', ':'), comment_prefixes=('#', ';'),
> inline_comment_prefixes=None, strict=True, *empty_lines_in_values=True*,
> ...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/python/cpython/pull/27830#issuecomment-1063159042>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEB44SRWY3BXFZTR4ZPQJDLU7DLUZANCNFSM5COBGDOQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-11 12:58 UTC, AA-Turner commented
This PR would need to be retargeted and brought up to date, currently it is against the `3.9` branch.

A

2022-12-06 08:07 UTC, slateny commented
@TheHippiez Would you be interested in addressing the comments and reopening the PR?

2022-12-06 11:24 UTC, TheHippiez commented
@slateny Yes! I'll get on it this evening.

2022-12-06 23:08 UTC, TheHippiez commented
@JelleZijlstra You are correct, the example code will not work without `allow_now_value=True`. This does not solve the original issue ( with the docs ) as mentioned in the bug tracker. Consider the following .ini file:

[section]
a = 0.3

    [subsection]
    b = 123
    
There are 2 sections here, one is indented. This should be possible according to the documentation, but it doesn't work unless you specify empty_lines_in_values =False. 

Do you want me to address both issues in this commit?

2024-08-09 12:44 UTC, hugovk commented
I'm closing this PR because it should target `main` and not `3.11`.

A new PR is needed, because changing this PR's base branch will end up pinging dozens of core devs in the `CODEOWNERS` file.

@TheHippiez Would you like to open a new PR for `main`?

@JelleZijlstra Please can you also check @TheHippiez's question for you at https://github.com/python/cpython/pull/27830#issuecomment-1340134725?

Thanks all!

2024-08-09 12:44 UTC, closed without merging