bpo30977: define uuid.UUID.__slots__ to save memory
python/cpython pull request #2785
Opened 2017-07-20 17:15 UTC by wbolster

2017-09-15 11:20 UTC, tiran approved these changes
Looks sensible to me. What do you think, @warsaw ?

2017-09-27 18:58 UTC, amannijhawan commented
Will this get backported to 2.7.x?

2017-09-27 19:13 UTC, wbolster commented
hi, author here. is there anything i can do to help  move this pr forward?

2017-09-28 07:06 UTC, serhiy-storchaka requested changes
This change breaks pickle. See my comments on the tracker.

2017-09-28 13:37 UTC, vstinner approved these changes
LGTM, but please add a test in test_exceptions() to make sure that is_safe attribute cannot be modified, near the "badtype(lambda: setattr(u, 'int', i))" test.

2017-09-28 13:37 UTC, haypo commented on Lib/uuid.py
> +        super().__setattr__('is_safe', is_safe)
I suggest to use object.__setattr__(self, 'int', int).

2017-09-28 13:38 UTC, haypo commented
@serhiy-storchaka: "This change breaks pickle. See my comments on the tracker."

Oh, I missed this comment. It should be fixed.

Please rebase also your change.

2018-09-06 07:03 UTC, taleinat commented
Since this has lingered for a long time with no word from the original author, I've gone ahead and implemented appropriate pickle/unpickle logic. I've created a new PR (#9078) since this one is old and has merge conflicts.

I suggest closing this.

2018-09-06 08:23 UTC, closed without merging

2018-09-06 12:00 UTC, wbolster commented
thanks all, especially @taleinat for finishing my first attempt!