bpo-42064: Offset arguments for PyObject_Vectorcall in the _sqlite module
python/cpython pull request #27931
Opened 2021-08-24 14:04 UTC by encukou

This weird mechanism allows e.g. methods to be called efficiently by providing space for a "self" argument; see [PY_VECTORCALL_ARGUMENTS_OFFSET docs](https://docs.python.org/3/c-api/call.html#c.PY_VECTORCALL_ARGUMENTS_OFFSET).

2021-08-24 15:27 UTC, corona10 commented
Out of curiosity, How efficient? is there any benchmark?

2021-08-24 16:01 UTC, encukou commented
> Out of curiosity, How efficient? is there any benchmark?

I'm not aware of one, but the docs say this is *encouraged* :)

2021-08-24 16:46 UTC, shihai1991 commented on Modules/_sqlite/cursor.c
> +    PyObject *args[] = { NULL, operation, };
nitpick: note `Borrowed ref`  in here too?

2021-08-24 17:00 UTC, erlend-aasland commented
LGTM. This makes sense for the collation callback, but I can't see how the calls in `new_statement_cache` and `get_statement_from_cache` will ever benefit from this. OTOH, it won't hurt to use the encouraged calling convention :)

2021-08-24 17:01 UTC, erlend-aasland requested changes

2021-08-24 17:01 UTC, erlend-aasland commented on Modules/_sqlite/connection.c
> +        lru_cache, args + 1, 1 | PY_VECTORCALL_ARGUMENTS_OFFSET, NULL);
Could you please break lines according to PEP 7? I'm striving to keep all `sqlite3` changes PEP 7 compliant :)
Ditto for the other calls.

2021-08-24 17:05 UTC, erlend-aasland commented on Modules/_sqlite/connection.c
> +        lru_cache, args + 1, 1 | PY_VECTORCALL_ARGUMENTS_OFFSET, NULL);
That is, either:

```suggestion
    PyObject *inner = PyObject_Vectorcall(lru_cache, args + 1,
                                          1 | PY_VECTORCALL_ARGUMENTS_OFFSET,
                                          NULL);
```

or:

```suggestion
    size_t nargs = 1 | PY_VECTORCALL_ARGUMENTS_OFFSET;
    PyObject *inner = PyObject_Vectorcall(lru_cache, args + 1, nargs, NULL);
```

2021-08-31 12:04 UTC, erlend-aasland approved these changes

2021-08-31 12:34 UTC, merged

2021-08-31 12:34 UTC, encukou commented
Thanks for the reviews!