bpo-45115: Enable optimiaztions on Windows debug build
python/cpython pull request #28181
Opened 2021-09-06 15:25 UTC by vstinner

On Windows, enable compiler optimizations on the debug build to make
tests run faster and to reduce the stack memory usage, especially
with static inline functions used in Python public header files.

The Windows GitHub Actions now build Python in debug mode to catch
more bugs.

2021-09-06 15:34 UTC, vstinner commented
>  bpo-45115: Enable optimiaztions on Windows debug build #28181 

Ooops, there is a typo in the commit message. It can be fixed when the PR is merged.

2021-09-06 15:36 UTC, vstinner commented
I modified my PR #28128 to see if enabling compiler optimizations fix test_exceptions when Py_TYPE() macro is converted to a static inline function.

2021-09-06 15:49 UTC, vstinner commented
[Reference] Timing of a **release** build (**with** optimizations), from PR #28180:

* Windows x86: Total duration: **9 min 39 sec** (test_asyncio.test_sendfile_close_peer_in_the_middle_of_receiving() re-run)
* Windows x64: Total duration: **9 min 9 sec**

[With this PR] GitHub Action jobs with Python built in **debug** mode **with** optimizations:

* Windows x86: Total duration: **13 min 23 sec**.
* Windows x64: Total duration: **10 min 30 sec** (test_asyncio.test_sendfile_close_peer_in_the_middle_of_receiving() re-run).


Currently, the slowest job is the Address Sanitizer. IMO as soon as the Windows jobs are faster than the Address Sanitizer job, the little slowdown of this PR on GitHub Action is accepted. And it's way better to test Python on Windows in debug mode!

cc @pablogsal @ambv @corona10 @zware @zooba

2021-09-06 16:12 UTC, vstinner commented
Building Python in debug mode **does fix** test_exceptions crash when Py_TYPE() macro is converted to a static inline function:
* https://bugs.python.org/issue44348
* https://github.com/python/cpython/pull/28128

2021-09-06 16:49 UTC, zooba requested changes
Blocking this PR explicitly until we've had the discussion on the issue tracker.

2021-09-06 16:58 UTC, vstinner commented
> Blocking this PR explicitly until we've had the discussion on the issue tracker.

Ok, I convert this PR to a draft to prevent merging it by mistake.

2021-09-07 13:47 UTC, vstinner commented
I rejected my issue: https://bugs.python.org/issue45115#msg401273

2021-09-07 13:47 UTC, closed without merging