bpo-30940: fix docs for round if second arg is None
python/cpython pull request #2824
Opened 2017-07-23 12:54 UTC by daxlab

2017-07-23 13:14 UTC, serhiy-storchaka commented on Doc/library/functions.rst
> +   negative).  The return value is an integer if *ndigits* is omitted or *None*.
Format `None` with fixed-width font instead of italic.

2017-07-23 13:15 UTC, serhiy-storchaka requested changes
Needed to update the docstring too.

The signature of the function can be written as
```
round(number, ndigits=None)
```

2017-07-23 13:24 UTC, mdickinson approved these changes
LGTM. Thanks for doing this!

2017-07-23 13:33 UTC, serhiy-storchaka commented
Please update the docstring.

And what is more correct
```
if *ndigits* is omitted or is ``None``
```
(as in the first paragraph) or
```
if *ndigits* is omitted or ``None``
```
(as in the second paragraph)? Or both are correct?

2017-07-23 14:21 UTC, daxlab commented
`if *ndigits* is omitted or ``None`` ` looks correct.

2017-07-23 15:12 UTC, serhiy-storchaka commented on Python/bltinmodule.c
>  This returns an int when called with one argument, otherwise the\n\
"if ndigits is omitted or None"

2017-07-23 16:00 UTC, mdickinson commented
About

> if *ndigits* is omitted or is ``None``

versus

> if *ndigits* is omitted or ``None``

I think either is fine. To my eyes, the first looks a bit clearer, but also a bit more pedantic.

2017-07-24 05:36 UTC, daxlab commented
@serhiy-storchaka docs updated.

2017-08-27 16:18 UTC, daxlab commented
@serhiy-storchaka plz review.

2017-08-27 17:09 UTC, serhiy-storchaka approved these changes

2017-08-27 17:11 UTC, serhiy-storchaka commented
The current changes LGTM, but see a discussion on the tracker. Perhaps the documentation needs additional clarification.

2018-06-08 20:25 UTC, closed without merging