Remove hostflags from PySSLContext
python/cpython pull request #28602
Opened 2021-09-28 12:07 UTC by ramikg

The `PySSLContext` struct in `Modules/_ssl.c` mentions that "OpenSSL has no API to get hostflags from X509_VERIFY_PARAM* struct. We have to maintain our own copy".
Since OpenSSL 1.1.0i added the function `X509_VERIFY_PARAM_get_hostflags`, this statement is no longer true.
Because Python 3.10 requires OpenSSL 1.1.1 ([PEP 644](https://www.python.org/dev/peps/pep-0644/)), we no longer have to maintain a copy of the host flags.

This PR removes the `hostflags` member from the `PySSLContext` struct.

Notes:

* This PR also amends a minor typo in the `ssl` module docs, correctly specifying that [bpo43522](https://bugs.python.org/issue43522) was fixed in OpenSSL 1.1.1l (and not 1.1.1k as in the docs).
* No bpo because this is a trivial PR.

2021-10-07 08:47 UTC, ramikg commented
Mentioning @tiran as the author of bpo-31399, which added the `hostflags` member.

2021-10-07 09:20 UTC, tiran requested changes
bpo-43669 is closed. This PR needs a new ticket.

2024-10-26 13:21 UTC, ramikg commented
@tiran
I have made the requested changes; please review again.

2025-04-18 22:26 UTC, gpshead approved these changes

2025-04-18 22:27 UTC, merged