bpo-9285: Adding profile decorator, context manager to cProfile/profile
python/cpython pull request #287
Opened 2017-02-25 07:40 UTC by grapherd

This patch is base on Giampaolo Rodola works. It is a workaround
that change the assertion of trace_dispatch_return, somehow the
context manager will make a bad return, workaround skip this
special case and let it go.

2017-04-05 05:34 UTC, rhettinger commented
At first glance, this seems like a reasonable improvement.  Nick, what do you think about it and the the code from the combined decorate/contextmanager?

2017-04-05 06:13 UTC, ncoghlan requested changes
The basic concept seems sound to me, but the class level implementation needs to make a clearer choice between:

- having a separate `runblock()` method, which is more consistent with `run()`, `runctx()` and `runcall()`, but will be slower at runtime
- implementing context management support natively on the `Profile` classes in each module, and either not having a `runcontext()` method at all, or just having it return `self`

2017-04-05 06:13 UTC, ncoghlan commented on Lib/cProfile.py
> +        self.enable()
Native context management support on `Profile` would be redundant with the new `runblock()` method, so I'd suggest removing this.

That would also restore API consistency between `profile.Profile` and `cProfile.Profile`.

Alternatively (and this would be a more efficient implementation):

- have both classes implement native context management support (returning `self` from `__enter__`)
- inherit from `contextlib.ContextDecorator` to enable use as a function decorator
- remove the `runblock()` method as redundant (but keep the module level functions)

2017-04-05 06:27 UTC, ncoghlan commented
Regarding the assertion failure: before accepting the PR, I'd prefer to see a separate patch that added a test case that triggered the assertion error *without* any changes to the profile or cProfile module, and then made the minimal fixes needed to the assertion to get that case to pass.

My assumption is that the assertion become subtly incorrect back when with statements were first introduced (since they interact with the frame stack slightly differently from the way try/finally statements do), but I'd be wary of proceeding without an explicit test case to check that using the existing API.

2017-04-20 07:09 UTC, lulouie commented on Lib/cProfile.py
> +        self.enable()
I prefer the alternative way, so `cProfile` and `profile` become this:

```python
import cProfile
import profile

with cProfile.Profile():
    pass

with profile.Profile():
    pass

@cProfile.Profile()
def foo():
    pass

@profile.Profile():
def foo():
    pass
```

2017-04-20 14:21 UTC, lulouie commented on Lib/cProfile.py
> +        self.enable()
@ncoghlan also, should these __enter__ add the print option? or add like __init__ with print option.

2018-02-21 01:51 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2020-01-20 18:00 UTC, csabella commented
This change is from an unknown repository and this GitHub account is no longer active.  I'm going to close this PR so that another one could be opened to replace it.

2020-01-20 18:00 UTC, closed without merging