Add warning note about mimetypes.add_type ext argument format
python/cpython pull request #2871
Opened 2017-07-25 19:41 UTC by OddBloke

This addresses the documentation of the issue described in bpo-31040,
but not the underlying issue.

2017-07-25 19:41 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-07-25 19:43 UTC, OddBloke commented
(I signed the CLA just before submitting this PR, so that should be cleared up fairly soon.)

2019-09-13 13:12 UTC, JulienPalard requested changes

2019-09-13 13:12 UTC, JulienPalard commented on Doc/library/mimetypes.rst
> +        The *ext* argument should start with a dot ("``.``") for the
Please also explicitly tell it can be empty, see b.p.o.

2020-01-12 13:43 UTC, csabella commented
@OddBloke, please address the code review comments from @JulienPalard.  Thanks!

2020-05-28 22:59 UTC, csabella commented
@OddBloke ping

2022-05-08 21:21 UTC, JelleZijlstra commented
Closing as it's been almost two years since the requested change.

2022-05-08 21:21 UTC, closed without merging