bpo-45369: Remove libressl support
python/cpython pull request #28728
Opened 2021-10-05 04:57 UTC by ramikg

Python 3.10 drops support for LibreSSL (as per [PEP 644](https://www.python.org/dev/peps/pep-0644/)), but there are still a few workarounds & mentions of LibreSSL in the source code.

The related PR cleans the code of any LibreSSL workarounds or mentions.

2021-10-05 08:23 UTC, tiran requested changes
Thanks for your PR.

Python 3.10 didn't actively drop support for LibreSSL. For a lack of better wording, we *passively* removed compatibility with forks that don't provide OpenSSL 1.1.1 API. I still like to keep some code so we can re-add LibreSSL support later.

2021-10-05 08:23 UTC, tiran commented on Lib/test/test_ssl.py
> -            s.startswith((openssl_ver, libressl_ver)),
Please leave this check.

2021-10-05 08:23 UTC, tiran commented on Misc/NEWS.d/next/Core and Builtins/2021-10-05-05-00-16.bpo-45369.tluk_X.rst
> +Remove LibreSSL support as per PEP 644.
Your wording is a bit strong. Python will support LibreSSL again as soon as it becomes API compatible with OpenSSL 1.1.1.

```suggestion
Remove LibreSSL workarounds as per :pep`644`.
```

2021-10-05 08:23 UTC, tiran commented on Tools/ssl/multissltests.py
> -"""Run Python tests against multiple installations of OpenSSL and LibreSSL
Please leave this test helper unmodified. The LibreSSL code will be useful as soon as LibreSSL becomes API compatible with OpenSSL 1.1.1.

2021-10-07 08:43 UTC, tiran reviewed
Thanks for the quick fix!

2022-07-19 18:40 UTC, dhewg commented
> For a lack of better wording, we _passively_ removed compatibility with forks that don't provide OpenSSL 1.1.1 API. I still like to keep some code so we can re-add LibreSSL support later.

Some time has passed, and I guess [this patch](https://github.com/gentoo/libressl/blob/master/dev-lang/python/files/python-3.10.3-libressl.patch) sort of reflects the state of Python v3.10 with LibreSSL v3.5.
It looks like the [next version](https://github.com/openbsd/src/commit/28494c8705b190e170b73f24b26932751c07da84) will support `SSL_CTX_get_security_level` too.
What's left then are those four hash functions, which probably won't be added [anytime](https://github.com/libressl-portable/portable/issues/199) [soon](https://github.com/libressl-portable/portable/issues/455).

Does that change anything for Python w.r.t. LibreSSL support?

2022-07-19 18:49 UTC, dhewg commented
Of course I stumble upon [this](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.11.rst#hashlib) just after posting.
That sounds like it can solve the issue about the missing hashing functions?

2022-07-19 19:15 UTC, tiran commented
It is unlikely that we will officially support LibreSSL. Even if LibreSSL would become feature compatible with OpenSSL, we just don't have to resources to test and verify that Python works correctly with LibreSSL.

Is LibreSSL still relevant? AFAIK only OpenBSD uses it. All Linux distros have dropped support for LibreSSL, even [Gentoo](https://www.gentoo.org/support/news-items/2021-01-05-libressl-support-discontinued.html). FreeBSD uses OpenSSL and NetBSD seems to prefer OpenSSL as well (they have OpenSSL 1.1.1n and LibreSSL 2.7.4 from 2018).

2022-12-30 09:07 UTC, dhewg commented
For the record: Python 3.10.7 builds with LibreSSL 3.7.0 without any further patches.

2023-04-09 08:42 UTC, arhadthedev commented
If no deliberate removal of LibreSSL calls is planned, should we keep this PR and its parent issue open?

2023-04-16 21:40 UTC, orbea commented
> All Linux distros have dropped support for LibreSSL, even [Gentoo](https://www.gentoo.org/support/news-items/2021-01-05-libressl-support-discontinued.html).

It is still possible to use it on Gentoo with the overlay. https://github.com/gentoo/libressl

2024-01-05 10:08 UTC, erlend-aasland commented
@ramikg, can you resolve the conflicts and update the PR?

2024-01-05 18:35 UTC, ramikg commented
> @ramikg, can you resolve the conflicts and update the PR?

Sure, done.

2024-01-06 19:22 UTC, gpshead requested changes
This PR should not remove `RAND_egd`, that is something OpenSSL provides.

2024-01-06 20:16 UTC, ramikg commented
> This PR should not remove `RAND_egd`, that is something OpenSSL provides.

True. I've brought it back, and reworded the comment to be relevant to [OpenSSL](https://github.com/openssl/openssl/blob/5963aa8c196d7c5a940a979299a07418527932af/crypto/rand/rand_egd.c#L20).  
I've kept the `try` clause so that OpenSSL builds with `OPENSSL_NO_EGD` won't break.

(By the way, `RAND_egd` has already been _mostly_ removed from CPython, as I've mentioned [here](https://github.com/python/cpython/pull/25453#issuecomment-1453763157). Also, I didn't expect the Spanish Inquisition.)

2024-01-06 20:21 UTC, ramikg commented
I didn't expect the Spanish Inquisition

2024-01-06 20:22 UTC, ramikg commented
I have made the requested changes; please review again

2024-01-06 23:04 UTC, gpshead approved these changes

2024-01-06 23:25 UTC, merged