bpo-29410: Use SipHash13 instead of SipHash24.
python/cpython pull request #28752
Opened 2021-10-06 05:08 UTC by methane

2021-10-07 07:23 UTC, erlend-aasland commented on Lib/test/test_hash.py
> +        'siphash': [
`test_hash` aborts with `KeyError: 'siphash13'`

```suggestion
        'siphash13': [
```

Alternatively, change `test_hash` to look for `siphash` instead. (Probably a better solution.)

2021-10-07 09:08 UTC, vstinner commented on configure.ac
> +                           [select hash algorithm for use in Python/pyhash.c (default is SipHash)]),
Please update https://docs.python.org/dev/using/configure.html#cmdoption-with-hash-algorithm and add a "versionchanged" markup there to mention the change.

Moreover, please mention this build change in What's New in Python 3.11.

2021-10-07 09:09 UTC, vstinner commented on configure.ac
> +                           [select hash algorithm for use in Python/pyhash.c (default is SipHash)]),
Currently, it's called "siphash24". Why not calling the new one "siphash13"? I'm fine with "siphash", I'm just curious.

2021-10-07 09:18 UTC, tiran requested changes
The removal of SipHash-2-4 should go through regular deprecation cycle.
I recommend that you keep ``Py_HASH_SIPHASH24``, add a new constant for ``Py_HASH_SIPHASH13``, and add deprecation for ``Py_HASH_SIPHASH24``.

2021-10-07 09:46 UTC, methane commented
> add deprecation for `Py_HASH_SIPHASH24`.

How to add deprecation to undocumented macro? Comment in header is enough?

2021-10-07 10:12 UTC, tiran commented on Include/pyhash.h
> + * The values for Py_HASH_SIPHASH13 and Py_HASH_FNV are hard-coded in the
```suggestion
 * The values for Py_HASH_* are hard-coded in the
```

2021-10-07 10:12 UTC, tiran commented on Include/pyhash.h
>  #define Py_HASH_FNV 2
```suggestion
#define Py_HASH_SIPHASH24 1  /* deprecated */
#define Py_HASH_FNV 2
#define Py_HASH_SIPHASH13 3
```

2021-10-07 10:12 UTC, tiran commented on Lib/test/test_hash.py
>          'fnv': [
Please keep the siphash24 test vectors

2021-10-07 10:12 UTC, tiran commented on configure.ac
> +   SipHash13: 1, FNV: 2, externally defined: 0])
```suggestion
   SipHash24: 1, FNV: 2, SipHash13: 3, externally defined: 0])
```

2021-10-07 10:12 UTC, tiran commented on configure.ac
> +            AS_HELP_STRING([--with-hash-algorithm=@<:@fnv|siphash13@:>@],
```suggestion
            AS_HELP_STRING([--with-hash-algorithm=@<:@fnv|siphash13|siphash24@:>@],
```

2021-10-07 10:12 UTC, tiran commented on configure.ac
> +        AC_DEFINE(Py_HASH_ALGORITHM, 1)
```suggestion
        AC_DEFINE(Py_HASH_ALGORITHM, 3)
```

2021-10-08 05:46 UTC, methane commented on Lib/test/test_hash.py
> +        'siphash13': [
Created by this code. https://gist.github.com/methane/5bb59a0563a025994e49fac509b49bf9

2021-10-08 08:06 UTC, tiran requested changes
Excellent, almost there! I have two minor and one major suggestion for the PR.

2021-10-08 08:06 UTC, tiran commented on Python/pyhash.c
> +    return siphash13(key, 0, src, src_sz);
I'm not sure that it's a good idea to change the keyed hash format. PEP 552 kinda implies that PYC format uses SipHash-2-4. This change breaks backwards compatibility of public API ``importlib.util.source_hash``. The output of ``source_hash()`` on 3.11 would no longer be compatible with Python 3.10 and older releases.

@benjaminp @brettcannon What do you think?

2021-10-08 08:06 UTC, tiran commented on Include/pyhash.h
> + * - SIPHASH only works on platforms that don't require aligned memory for integers.
Is the statement about aligned memory still correct? I think this was fixed in bpo-28055. Commit 1e2ec8a996daec65d8d5a3d43b66a9909c6d0653 added ``memcpy()`` but did not update the comment.

2021-10-08 08:06 UTC, tiran commented on Doc/whatsnew/3.11.rst
> +* ``siphash13`` is added as a new internal hash algorithm for strings, and the default
Small nit pick: Your change affects str, bytes, and a couple of other places like memoryview, regular expressions, and datetime objects.

2021-10-08 08:51 UTC, methane commented on Doc/whatsnew/3.11.rst
> +* ``siphash13`` is added as a new internal hash algorithm for strings, and the default
I used the word "strings" because I don't have a better word to represent it. Any suggestion?

Configure script and https://docs.python.org/3/using/configure.html#security-options uses: "hash algorithm for use in Python/pyhash.c".

2021-10-08 08:56 UTC, methane commented on Python/pyhash.c
> +    return siphash13(key, 0, src, src_sz);
> This change breaks backwards compatibility of public API importlib.util.source_hash.

If "breaks backward compatibility" means changing hash value, incrementing MAGIC number is also backward incompatible.

I changed this hash function because speeding up hash validation may increase startup time when hash validation is used.

2021-10-08 09:09 UTC, tiran commented on Doc/whatsnew/3.11.rst
> +* ``siphash13`` is added as a new internal hash algorithm for strings, and the default
I would mention why we made it the default and that str and bytes are affected. Perhaps something like

> ``siphash13`` is added as a new internal hashing algorithms. It's has similar security properties as ``siphash24`` but it is slightly faster for long inputs. ``str``, ``bytes``, and some other types now use it as default algorithm for ``hash()``

2021-10-08 09:09 UTC, tiran commented on Python/pyhash.c
> +    return siphash13(key, 0, src, src_sz);
Good point!

May I suggest that we either wait for feedback from Brett and Benjamin or move the change into a separate BPO? This change may need an update of PEP 552, too.

2021-10-08 13:40 UTC, benjaminp commented on Python/pyhash.c
> +    return siphash13(key, 0, src, src_sz);
No application I'm aware of would care about this changing. `importlib.util.source_hash` just exists to have the same result as what the importlib system would compute.

2021-10-09 08:52 UTC, tiran commented on Python/pyhash.c
> +    return siphash13(key, 0, src, src_sz);
Thanks for the feedback, Benjamin!

2021-10-09 08:56 UTC, tiran commented on Doc/whatsnew/3.11.rst
> +  (Contributed by Inada Naoki in :issue:`29410`.)
```suggestion
* ``siphash13`` is added as a new internal hashing algorithms. It's has similar security
  properties as ``siphash24`` but it is slightly faster for long inputs. ``str``, ``bytes``,
  and some other types now use it as default algorithm for ``hash()``. :pep:`552`
  hash-based pyc files now use ``siphash13``, too.
  (Contributed by Inada Naoki in :issue:`29410`.)
```

2021-10-10 08:29 UTC, merged