Fix typos in the Lib directory
python/cpython pull request #28775
Opened 2021-10-06 20:27 UTC by cclauss

Like #28744 but for the Lib directory.

[skip issue] Opening a related issue is pending python/psf-infra-meta#130

codespell --ignore-words-list=aline,alo,ans,asend,atleast,ba,bloc,browseable,cant,crasher,crashers,commen,datas,datea,doesnot,donn,ende,filetest,filetests,fiter,fo,hda,hel,hellow,henc,hist,infinit,inout,interruptable,invokations,ist,ket,lable,larg,leapyear,mye,nams,nd,ned,nin,notmutch,nwe,oder,oll,parm,raison,responsable,seh,simeple,squirl,spawnve,sur,tbe,te,teh,tey,thow,timere,tre,trough,tthe,ue,upto,wile,wont --skip="*.decTest,*.txt,*.types" Lib

2021-10-06 21:01 UTC, terryjreedy requested changes
I checked everything, not just idlelib, and all the changes look correct.  I checked a few with the handy web search bar.  One other check will be sufficient.

The requested change is to change 'gui' to 'GUI' in a line with another correction.

If whoever merges this does not backport to both 3.10 and 3.9, please let me know as I want at least the idlelib changes backported and will do so if necessary.

2021-10-06 21:01 UTC, terryjreedy commented on Lib/email/errors.py
> +    """Header has unparsable or invalid date"""
A couple of places list 'parseable' as an 'alternate spelling' for 'parsable', implying that the latter is preferred.  I am OK with the change.

2021-10-06 21:01 UTC, terryjreedy commented on Lib/idlelib/idle_test/mock_tk.py
> +    only gui calls in a method, this replacement makes the method gui-free,
These are my errors.  GUI is standard for this acronym and I now use it.
```suggestion
    only GUI calls in a method, this replacement makes the method GUI-free,
```

2021-10-06 21:01 UTC, terryjreedy commented on Lib/lib2to3/fixes/fix_metaclass.py
> +    # !%@#! one-liners have no suite node, we have to fake one up
I checked this and '-' is needed.

2021-10-06 21:14 UTC, cclauss commented on Lib/email/errors.py
> +    """Header has unparsable or invalid date"""
https://pypi.org/project/codespell tends to prefer 🇺🇸spellings over 🇬🇧 spellings so that may explain some choices.

2021-10-06 21:18 UTC, ericvsmith requested changes
Except for the one small change I suggest, these all look good to me.

2021-10-06 21:18 UTC, ericvsmith commented on Lib/test/test_time.py
> +        # on all platform.  This will make sure that no other exception
I think this should be "make mktime return an error on all platforms": "error" -> "an error", and "platform" -> "platforms".

2021-10-06 21:32 UTC, ericvsmith approved these changes
Looks good to me.

2021-10-06 23:12 UTC, gpshead approved these changes

2021-10-06 23:13 UTC, merged

2021-10-06 23:13 UTC, miss-islington commented
Sorry, @cclauss and @gpshead, I could not cleanly backport this to `3.10` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 745c9d9dfc1ad6fdfdf1d07420c6273ff67fa5be 3.10
                                ```

2021-10-06 23:13 UTC, miss-islington commented
Sorry @cclauss and @gpshead, I had trouble checking out the `3.9` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 745c9d9dfc1ad6fdfdf1d07420c6273ff67fa5be 3.9
                                ```

2021-10-10 15:09 UTC, cjerdonek commented on Lib/asyncio/unix_events.py
> +        # abstract base classes requires it
requires -> require?

2021-10-10 15:10 UTC, cjerdonek commented on Lib/tkinter/test/test_ttk/test_widgets.py
> +        # verify that the tab gets read at its previous position
Was this supposed to be "re-added"?

2021-10-20 02:20 UTC, gpshead commented on Lib/tkinter/test/test_ttk/test_widgets.py
> +        # verify that the tab gets read at its previous position
PR 29079 out to address these.  thanks for noticing!