bpo-45405: Prevent ``internal configure error`` when running ``configure``  with recent versions of non-Apple clang.
python/cpython pull request #28845
Opened 2021-10-10 01:36 UTC by debohman

[bpo-45405](https://bugs.python.org/issue45405): Change the configure logic to function properly on darwin when the compiler outputs a platform triplet for option --print-multiarch.

https://bugs.python.org/issue45405

2021-10-10 01:36 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@debohman

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-10-10 07:38 UTC, corona10 requested changes
You may need to regenerate the `configure` file also.
https://devguide.python.org/setup/#regenerate-configure

2021-10-10 15:42 UTC, ned-deily commented
> You may need to regenerate the `configure` file also.
> https://devguide.python.org/setup/#regenerate-configure

We discussed this on the bpo issue. I'll take care of regenerating it.

2021-10-13 00:07 UTC, ned-deily approved these changes

2021-10-13 00:10 UTC, merged