bpo-45447: Add syntax highlighting for `.pyi` files in IDLE
python/cpython pull request #28950
Opened 2021-10-14 16:10 UTC by AlexWaygood

This commit adds syntax highlighting for `.pyi` files in IDLE.
It also adds an option to open Python stub files in the "File-open" dialogue,
and an option to save a file as a `.pyi` file in the "File-save" dialogue.

https://bugs.python.org/issue45447

2021-10-15 10:15 UTC, E-Paine commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
What's the reasoning for using `is_python_source` above and `is_python_extension` here?

2021-10-15 10:15 UTC, E-Paine commented on Lib/idlelib/util.py
> +def is_python_extension(extension, is_valid=PYTHON_EXTENSIONS.__contains__):
Do we need the `is_valid` argument? I'd also prefer if we just passed the frozen set to that argument and the next line was just `extension in is_valid`, since I'm not a fan of accessing the dunder method in this way.

2021-10-15 10:15 UTC, E-Paine commented on Lib/idlelib/idle_test/test_util.py
> +        self.assertIn('.pyw', util.PYTHON_EXTENSIONS)
It may make sense to test via the `is_python_extension` method instead.

2021-10-15 10:15 UTC, E-Paine commented on Misc/NEWS.d/next/IDLE/2021-10-14-16-55-03.bpo-45447.FhiH5P.rst
> +and will apply syntax highlighting accordingly. Patch by Alex Waygood.
```suggestion
IDLE now applies syntax highlighting to `.pyi` files. Patch by Alex Waygood.
```

2021-10-15 10:15 UTC, E-Paine commented on Lib/idlelib/util.py
> +    * warning stuff (ditto).
```suggestion
    * warning stuff (pyshell, run).
```
Make it explicit, so this line doesn't need to be changed when the point above is completed.

2021-10-15 10:35 UTC, AlexWaygood commented on Lib/idlelib/util.py
> +def is_python_extension(extension, is_valid=PYTHON_EXTENSIONS.__contains__):
It's not necessary, no -- I just thought it would make it slightly more performant to load the method at function-definition time. But I agree it's a little quirky; I'll take it out.

2021-10-15 11:34 UTC, AlexWaygood commented on Lib/idlelib/idle_test/test_util.py
> +        self.assertIn('.pyw', util.PYTHON_EXTENSIONS)
I've just rewritten the tests fairly extensively :)

2021-10-15 11:46 UTC, AlexWaygood commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
I think I was just trying to stick as closely to the existing source code as possible. `is_python_source`  will return `True` if the filepath points to a directory, and there's no logic like that in `listchildren` currently. Would it be better to use `is_python_source` instead of `is_python_extension` here, do you think?

2021-10-15 11:48 UTC, AlexWaygood commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
The reason I used `is_python_source` in `IsExpandable()` was because that was the guidance Terry gave me in the BPO issue.

2021-10-15 12:05 UTC, E-Paine commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
@terryjreedy I think it would make sense to use `is_python_extension` here. Your opinion?

2021-10-16 09:34 UTC, E-Paine commented on Lib/idlelib/idle_test/test_util.py
> +        self.assertIn('.pyw', util.PYTHON_EXTENSIONS)
LGTM

2021-12-06 16:03 UTC, E-Paine commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
Ping @terryjreedy

2021-12-06 18:51 UTC, AlexWaygood commented
@terryjreedy, would this be easier to review if I split it into several smaller PRs? I'm happy to do so.

2022-01-16 04:00 UTC, terryjreedy requested changes
Besides inline comments, add file requested on issue.

2022-01-16 04:00 UTC, terryjreedy commented on Lib/idlelib/util.py
> +PYTHON_EXTENSIONS = frozenset({'.py', '.pyw', '.pyi'})
```suggestion
PYTHON_EXTENSIONS = frozenset(('.py', '.pyw', '.pyi'))
```
For why, consider
```
>>> dis('frozenset((1,2,3))')
  1           0 LOAD_NAME                0 (frozenset)
              2 LOAD_CONST               0 ((1, 2, 3))
              4 CALL_FUNCTION            1
              6 RETURN_VALUE
>>> dis('frozenset({1,2,3})')
  1           0 LOAD_NAME                0 (frozenset)
              2 BUILD_SET                0
              4 LOAD_CONST               0 (frozenset({1, 2, 3}))
              6 SET_UPDATE               1
              8 CALL_FUNCTION            1
             10 RETURN_VALUE
>>> dis('{1,2,3}')
```

2022-01-16 04:00 UTC, terryjreedy commented on Lib/idlelib/idle_test/test_browser.py
> +"Test browser, coverage 81%."
I don't believe this.  IDLE coverage requires a customized .coveragerc file, as discussed either in README or idle_test/README (and in an open issue that should be finished).  I will recheck all these numbers.

2022-01-16 04:00 UTC, terryjreedy commented on Lib/idlelib/idle_test/test_util.py
> +class ExtensionTest(unittest.TestCase):
I will condense the extension tests.

2022-01-16 04:00 UTC, terryjreedy commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
ispythonsource is intended to include python files without .py? extension but starting with (re) '#!.*python'.  I need to review the usage of list children to see what I think its logic should be.  I may decide to leave moving .ispythonsource out of this issue (see issue), but have not done so yet.

2022-01-16 04:00 UTC, terryjreedy commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
If I cannot or do not decide soon, PR could be reduced to .pyi addition.

2022-01-16 14:04 UTC, AlexWaygood commented on Lib/idlelib/idle_test/test_browser.py
> +"Test browser, coverage 81%."
OK. Would you like me to take out those changes for now?

2022-01-24 05:53 UTC, terryjreedy commented
1. Manual test: are you sure that stub users will prefer a separate entry to load stub files?
2. I should look at IDLE doc for possible revision.
3. Please update branch after updating main: 'git merge origin/main' or whatever.  (Good to do this before every uploaded commit(s).
4. Change 'example.py' to 'example_stub.py' and add 'example_noext' (no extension) with #! line and 'normal' function.
5. For me, updated coverage module is not working with updated main.  (Submitted report.)  Leave alone for now.

2022-01-25 08:27 UTC, AlexWaygood commented
Thanks Terry!

---

> 1. Manual test: are you sure that stub users will prefer a separate entry to load stub files?

On second thought, I agree; I've changed it so that it's included with the other Python filetypes.

> 2. I should look at IDLE doc for possible revision.

I had a look, but couldn't see anywhere obvious where I might insert a mention about this change. I've had a go at adding an entry to "What's New in 3.11", though.

> 3. Please update branch after updating main: 'git merge origin/main' or whatever. (Good to do this before every uploaded commit(s).

Done.

> 4. Change 'example.py' to 'example_stub.py' and add 'example_noext' (no extension) with #! line and 'normal' function.

Done.

> 5. For me, updated coverage module is not working with updated main. (Submitted report.) Leave alone for now.

I've reverted all changes to coverage statistics.

---

I think I have made the requested changes; please review again.

2022-02-06 06:55 UTC, terryjreedy reviewed
Alex, I am editing the changes, so leave alone for now.

2022-02-06 06:55 UTC, terryjreedy commented on Lib/idlelib/browser.py
> +            file_open(self.file)
For no-extension files, IsExpandable requires that the file be open.  It make no sense to test that a file exists after is has been opened.  Nor to close and reopen after the uneeded test.  Testing no-extension files should be separate.

2022-02-06 06:55 UTC, terryjreedy commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
See comment for OnDoubleClick.  I will edit files and currently intend to leave no-ext files alone for now.

2022-02-11 04:48 UTC, terryjreedy commented on Lib/idlelib/browser.py
> +        if not is_python_extension(os.path.normcase(ext)):
pathbrowser only lists package subdirectories and .py files.  Without this being changed, the proposed changes to this file have no effect.  So I will revert all changes here.  We can open a new issue to change pathbrowser.py and browser.py together  to browse and open at least all source files with extension. The new issue can refer to Waygood's last commit as a starting point.

I will also remove is_python_source from the new util.py and revert move of the changes in editor.py, just changing the original ispythonsource function to include the new extension list that includes .pyi.  Same comment about Waygood's changes being a possible starting point for a followup.  The new test_util will be reduced.

2022-02-11 04:53 UTC, terryjreedy commented
Pathbrowser (pathbrowser.py) only lists package subdirectories and .py files.  Without this being changed, the proposed changes to browser.py have no effect.  I am reverting them.  There is also no need to move ispythonsource to util, so I am reverting that also and will instead edit to include .pyi files.  Corresponding tests can be deleted.

We can open a new issue to change pathbrowser.py and browser.py in sync so pathbrower will show and possibly open at least all source files with extension. The new issue can refer to Waygood's last commit as a starting point.

2022-02-11 06:31 UTC, terryjreedy commented
I think that this is now ready to merge.  In manual testing all of py, .pyw, .pyi, and '' files can be opened and are syntax-highlighted.

2022-02-11 06:31 UTC, terryjreedy approved these changes

2022-02-11 08:14 UTC, AlexWaygood commented
> I think that this is now ready to merge. In manual testing all of py, .pyw, .pyi, and '' files can be opened and are syntax-highlighted.

Thanks for all your help, Terry. Let me know if there's anything else you'd like me to do!

2022-02-11 08:59 UTC, terryjreedy commented
Reread the diff.  Try the open on your system if different from Windows.

2022-02-13 00:04 UTC, merged

2022-02-13 00:04 UTC, miss-islington commented
Thanks @AlexWaygood for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖

2022-02-13 00:05 UTC, miss-islington commented
Sorry, @AlexWaygood and @terryjreedy, I could not cleanly backport this to `3.10` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 50cf4991c49e19f917305dd7b9c71085c11edddb 3.10
                                ```

2022-02-13 15:18 UTC, AlexWaygood commented
Thanks for all the time you spent reviewing this, @terryjreedy! Hugely appreciate it.