bpo-31040: Reject undotted extensions in mimetypes.add_type
python/cpython pull request #2895
Opened 2017-07-26 15:06 UTC by OddBloke

Extensions that don't start with a dot will never be found by
methods/functions that act on the registry, so we should stop users from
mistakenly adding them.

2017-07-26 15:33 UTC, OddBloke commented
I've opened this now to get feedback on whether this is an appropriate change to make. Does it need a warning first, before it becomes the default behaviour?

(At a minimum, I would expect to need to add to documentation.)

2019-09-10 11:33 UTC, JulienPalard commented
As said in https://bugs.python.org/issue31040, please use `startswith` instead of find.

There is one case where it works without a dot:
```
>>> mimetypes.add_type('empty', '')
>>> mimetypes.guess_type('')
('empty', None)
```

And someone may have used it to distinguish emptyness verses not type not found. What I propose:

Emit a warning in case the ext is empty, else ValueError in case the type does not start with a dot, to ensure we're not breaking any code.

2019-09-10 11:34 UTC, JulienPalard requested changes

2019-09-10 11:34 UTC, JulienPalard commented on Lib/mimetypes.py
> +        if ext.find('.') != 0:
```suggestion
        if not ext.startswith('.'):
```

2019-09-10 13:53 UTC, OddBloke commented
I have made the requested changes; please review again.

2019-09-13 13:16 UTC, JulienPalard submitted a review, later dismissed

2019-09-13 13:16 UTC, JulienPalard commented on Lib/mimetypes.py
> +            warnings.warn('Empty extension specified')
As told on b.p.o, I found this morning a place prooving the empty ext is usefull, so I think now we should just let people use the empty type as a default fallback.
So maybe a ```if ext and not ext.startswith("."):``` then, and tell in the ValueError that it either should start with dot or be empty?

2024-11-06 16:54 UTC, hugovk requested changes, later dismissed
Some nits, but also the tests need updating to match the implementation change in [`f0c1bf7` (#2895)](https://github.com/python/cpython/pull/2895/commits/f0c1bf701e559aeee1bcd34a17087b609bc7facd).

2024-11-06 16:54 UTC, hugovk commented on Lib/test/test_mimetypes.py
> +        self.assertEqual('testing/type', mime_type)
Nit: asserts are usually written with test output first, expected result second:

```suggestion
        self.assertEqual(mime_type, None)
        mimetypes.add_type('testing/type', '.myext')
        mime_type, _ = mimetypes.guess_type('test.myext')
        self.assertEqual(mime_type, 'testing/type')
```

2024-11-06 16:54 UTC, hugovk commented on Lib/test/test_mimetypes.py
> +        self.assertEqual('Empty extension specified', str(warning.message))
```suggestion
        self.assertEqual(len(wlog), 1)
        warning = wlog[0]
        self.assertEqual(str(warning.message), 'Empty extension specified')
```

2024-11-06 16:54 UTC, hugovk commented on Misc/NEWS.d/next/Library/2019-09-10-09-28-52.bpo-31040.VyAJS9.rst
> +Reject undotted extensions in mimetypes.add_type.
Link to method:
```suggestion
Reject undotted extensions in :meth:`MimeTypes.add_type`.
```

2024-11-06 16:54 UTC, hugovk commented on Lib/test/test_mimetypes.py
> +    def test_add_type_with_empty_extension_emits_warning(self):
This test needs updating: there should be no warning for an empty extension.

2024-11-06 16:54 UTC, hugovk commented on Lib/test/test_mimetypes.py
> +    def test_add_type_with_undotted_extension_raises_exception(self):
This test can be updated to check the warning message for an undotted extension.

2025-01-03 17:05 UTC, encukou commented
IMO, this is a backwards-incompatible change and should be deprecated with a warning, and documented. (For example, if `add_type` is fed from a data file, this PR can change a relatively harmless data-entry error into a hard failure. Or someone could use `types_map` directly.)

2025-01-08 15:13 UTC, hugovk commented
Thanks, please see https://github.com/python/cpython/pull/128638 to deprecate it first, and I've marked this as a draft until it's ready for merge.

2026-05-09 17:47 UTC, StanFromIreland commented
> Thanks, please see https://github.com/python/cpython/pull/128638 to deprecate it first, and I've marked this as a draft until it's ready for merge.

It was deprecated and scheduled for 3.16, so it's time!

2026-05-09 18:27 UTC, StanFromIreland commented on Doc/library/mimetypes.rst
This should have the same "Valid extensions start with a '.' or are empty." note IMO, but it wasn't updated before?

2026-05-12 15:31 UTC, StanFromIreland commented
Completed in https://github.com/python/cpython/pull/149721.

2026-05-12 15:31 UTC, closed without merging