bpo-45442: Add deactivate step to venv tutorial.
python/cpython pull request #28981
Opened 2021-10-15 15:11 UTC by ShivnarenSrinivasan

@vsajip Sorry for the trouble—made a [fairly significant] git error in the previous PR.

Have edited the patch as you had said in #28959.

https://bugs.python.org/issue45442

Automerge-Triggered-By: GH:vsajip

2021-10-15 15:54 UTC, vsajip requested changes
There is still a build error which needs resolving. Did you build it locally and get a warning?

2021-10-15 21:23 UTC, vsajip commented
> Didn't know how to, so I had not built it—sorry.

As you can see, even a seemingly trivial change can lead to problems. Always build and test locally before submitting a PR.

2021-10-15 21:24 UTC, vsajip approved these changes

2021-10-15 21:24 UTC, merged

2021-10-16 09:35 UTC, ShivnarenSrinivasan commented
> > Didn't know how to, so I had not built it—sorry.
> 
> As you can see, even a seemingly trivial change can lead to problems. Always build and test locally before submitting a PR.

Understood
I'll be sure to do that going forward.