bpo-45506: Normalize _PyPathConfig.stdlib_dir when calculated.
python/cpython pull request #29040
Opened 2021-10-18 21:00 UTC by ericsnowcurrently

The recently added `PyConfig.stdlib_dir` was being set with ".." entries.  When `__file__` was added for from modules this caused a problem on out-of-tree builds.  This PR fixes that by normalizing "stdlib_dir" when it is calculated in getpath.c.

https://bugs.python.org/issue45506

2021-10-18 21:56 UTC, gpshead requested changes
`./python -m test.regrtest test_embed -v` still fails in an out of tree build for me with this change.  As does test_gdb.  Both appear to be having trouble importing `encodings`?  Others such as test_importlib no longer fail.

2021-10-18 22:23 UTC, warsaw requested changes
Even with this PR, `test_embed` and `test_unittest` still fail.

2021-10-18 22:23 UTC, warsaw commented on Modules/getpath.c
> +// This is similar to canonicalize() is PC/getpathp.c.
s/is/in

2021-10-19 01:03 UTC, ericsnowcurrently commented
With that latest commit I got all the tests to pass in an out-of-tree build.

2021-10-19 01:37 UTC, gpshead requested changes

2021-10-19 01:37 UTC, gpshead commented on Modules/getpath.c
> +    assert(orig[wcslen(orig)-1] != L'.');
This should either be an actual error or properly handled. What prevents a path with a trailing '.' from ever getting in here?

2021-10-19 01:37 UTC, gpshead commented on Modules/getpath.c
> +            assert(dots <= 2);
you have a couple `assert(dots <= 2)` in here, but I don't think those should exist. "..." is a perfectly valid file or directory name.  _(not that people should ever do that or that we expect any debug build folks to do that)_.  we just want this code to stop caring about the name once dots >= 3.  which this if else if for 2 and 1 will do already.  (same for the assert below)

2021-10-19 01:37 UTC, gpshead commented on Modules/getpath.c
> +/* Remove navigation elements such as "." and "..". */
What about "//"?  multiple SEPs in a row should turn into a single SEP.
It looks like these values come from outside of the process without any limits on what they contain, our code needs to be ready for things it doesn't like.

2021-10-19 01:37 UTC, gpshead commented on Modules/getpath.c
> +// This is similar to canonicalize() is PC/getpathp.c.
"in"

2021-10-19 01:37 UTC, gpshead commented on Modules/getpath.c
> +normalize(const wchar_t *orig, wchar_t *buf, const size_t buf_len)
it's really annoying that we have to implement this ourselves.  `realpath(orig, NULL)` would be good.. but only works on `char *` and does the additional symlink resolution along the way (which may or may not be bad depending on your point of view).

I tried whipping up an alternate implementation of this as a state machine that handles all of the cases. my unittest of it reveals bugs which i'm sure i could fix, but for reference it is ~125 lines. I'll hold off on posting and suggesting a different version for now. I think you'll wind up with a similar amount of logic here.  it'll be more a question of which seems more maintainable.

This function's kind of logic is something that deserves directed C/C++ level unittests which we tend to not do well in the CPython tree. :/

2021-10-19 14:48 UTC, ericsnowcurrently commented on Modules/getpath.c
> +    assert(orig[wcslen(orig)-1] != L'.');
The case is unlikely but, yeah, not impossible.  I'll take care of it.

2021-10-19 14:57 UTC, ericsnowcurrently commented on Modules/getpath.c
> +            assert(dots <= 2);
It should be impossible for `dots` to reach 3.  The assert is there to make sure.  That said, thanks to your comment here I did notice that I'm letting `dots` go past 2 further on.  I'll fix that.

2021-10-19 14:58 UTC, ericsnowcurrently commented on Modules/getpath.c
> +/* Remove navigation elements such as "." and "..". */
I thought about `//` but figured I'd punt on it for now.  However, I don't mind handling it here.  It won't be much of a change.

2021-10-19 15:02 UTC, ericsnowcurrently commented on Modules/getpath.c
> +normalize(const wchar_t *orig, wchar_t *buf, const size_t buf_len)
> it's really annoying that we have to implement this ourselves.

+1

> I tried whipping up an alternate implementation

FWIW, my only objective here is to fix out-of-tree builds.  I'm not attached to the solution and don't mind at all if we do something else entirely.

> This function's kind of logic is something that deserves directed C/C++ level unittests

+1

I'll see if I can add some.

2021-10-19 20:12 UTC, ericsnowcurrently commented on Modules/getpath.c
> +    assert(orig[wcslen(orig)-1] != L'.');
fixed

2021-10-19 20:12 UTC, ericsnowcurrently commented on Modules/getpath.c
> +/* Remove navigation elements such as "." and "..". */
fixed

2021-10-19 20:13 UTC, ericsnowcurrently commented on Modules/getpath.c
> +normalize(const wchar_t *orig, wchar_t *buf, const size_t buf_len)
I've added tests.

2021-10-19 22:14 UTC, ericsnowcurrently commented
Hmm, this PR isn't updating with changes I've pushed to my branch...

2021-10-22 23:02 UTC, gpshead approved these changes
I believe this one is good.  test_embed still fails for me using this branch but I think there was another PR you already merged that addressed that.

2021-10-22 23:03 UTC, gpshead commented on Modules/getpath.c
> +normalize(const wchar_t *orig, wchar_t *buf, const size_t buf_len)
I added a few more test cases and fixed a bug that turned up.  nice refactoring BTW!

2021-10-22 23:20 UTC, merged