bpo-45587: Distinguish title and description arguments from **kwargs in add_argument_group methods
python/cpython pull request #29192
Opened 2021-10-23 13:23 UTC by jb2170

Hi, this adds clarity to the `add_argument_group` method within the `argparse` module by separating the important `title` and `description` keyword arguments from the other `**kwargs`.

The method signature has been changed from
`add_argument_group(self, *args, **kwargs)` to
`add_argument_group(self, title=None, description=None, **kwargs)`

Observe that `*args` has been removed; it was never used. This is a backwards compatible change as any code that uses eg `parser.add_argument_group('myTitle', 'myDescription')` will fill out the first two correct keyword arguments, which was already the existing behaviour.

The documentation has been made consistent to these changes.

https://bugs.python.org/issue45587

2021-11-20 22:38 UTC, SelfAdjointOperator commented
Bump

2022-04-19 19:15 UTC, MaxwellDupre approved these changes
Ran 1672 tests in 9.180s
OK
Docs looks ok too.

2022-05-03 06:13 UTC, rhettinger approved these changes

2022-11-06 18:48 UTC, iritkatriel commented
Updated branch to kick off a new test run.

@rhettinger You approved this back in May. Any reason not to merge it?

2022-11-25 22:53 UTC, iritkatriel requested changes
The docs build failed:

Error: ../Misc/NEWS.d/next/Library/2021-10-23-14-08-59.bpo-45587.1-DdhN.rst:2: default role used (hint: for inline literals, use double backticks) (default-role)

2022-11-26 22:24 UTC, SelfAdjointOperator commented
Docs issue fixed. sphinx-lint all good

I have made the requested changes; please review again

2023-01-13 19:48 UTC, SelfAdjointOperator commented
Rebased. Can we get this merged and closed? It's been open nearly 450 days and I've noticed maintainers merging other PRs, why not this one? It's useful!

I have made the requested changes; please review again

2023-04-23 16:17 UTC, jb2170 commented
Closed due to inactivity

2023-04-23 16:17 UTC, closed without merging