bpo-37658: Actually return result in race condition
python/cpython pull request #29202
Opened 2021-10-24 15:43 UTC by Dreamsorcerer

Splitting this out from #28149 to ease review.

The original test written for this issue is bogus and fails to reproduce the bug report. I've replaced it with a test that reproduces the error, and have actually fixed the problem reported.

https://bugs.python.org/issue37658

2021-10-24 16:09 UTC, Dreamsorcerer commented on Lib/test/test_asyncio/test_tasks.py
> -    def test_wait_for_raises_timeout_error_if_returned_during_cancellation(self):
This test literally tests that we don't return a value when it has completed successfully...

I can't see any reason for this test, the issue linked to the PR does not mention anything that warrants this test existing: https://bugs.python.org/issue40607

So, as far as I can tell, this test should be binned and the behaviour should be as defined in the above changes.

2021-10-25 19:49 UTC, Dreamsorcerer commented on Lib/test/test_asyncio/test_tasks.py
> +            with contextlib.suppress(asyncio.CancelledError):
Initially I just emulated the race condition in the bug report, but because it's a race condition, it seems that the test occasionally failed due to actually hitting the timeout.

Instead, I've just suppressed the cancellation, which makes the behaviour 100% reproducible.

2021-11-28 11:04 UTC, asvetlov requested changes
The PR is correct.

Please add a NEWS entry.

2021-11-28 16:07 UTC, Dreamsorcerer commented
I couldn't run the `blurb add` command that seemed to be suggested, but I think that's right.

I have made the requested changes; please review again

2021-11-29 08:12 UTC, asvetlov approved these changes

2021-11-29 08:12 UTC, asvetlov commented
Thanks!

2021-11-29 08:12 UTC, merged

2021-11-29 08:13 UTC, miss-islington commented
Thanks @Dreamsorcerer for the PR, and @asvetlov for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖

2021-12-07 00:53 UTC, aaliddell commented on Lib/test/test_asyncio/test_tasks.py
> +            with contextlib.suppress(asyncio.CancelledError):
This is not an equivalent test. As I understand, the whole point of that test was to inject the cancellation at the exact point to cause the race on the return to ‘await waiter’ once fut is done. The new test is not checking this race at all but instead checking that a cancellation ignoring task can skip the timeout.

2021-12-07 10:00 UTC, Dreamsorcerer commented on Lib/test/test_asyncio/test_tasks.py
> +            with contextlib.suppress(asyncio.CancelledError):
It's not an equivalent test, because the previous test is completely wrong. It does not emulate a race condition, and it does not reproduce the issue in the bug report.

I wrote a test which actually reproduces the race condition as given in the bug report, and the issue was not fixed. As mentioned above, I had to use this suppress cancellation trick to make the test reproducible (it will still run things in the same order as the race condition), the original test worked correctly everytime I ran it, but failed in one of the CI runs, and we can't have flaky tests.

2021-12-07 10:11 UTC, Dreamsorcerer commented on Lib/test/test_asyncio/test_tasks.py
> +            with contextlib.suppress(asyncio.CancelledError):
You can see the old version which was timing dependent in the commit history:
https://github.com/python/cpython/pull/29202/commits/169294e95f8f373317d048bcd89ab3516352314f