bpo-45335: Add note to `sqlite3` docs about "timestamp" converter
python/cpython pull request #29200
Opened 2021-10-24 13:01 UTC by iafisher

See https://discuss.python.org/t/fixing-sqlite-timestamp-converter-to-handle-utc-offsets/10985 for further discussion of this issue.

https://bugs.python.org/issue45335

2021-10-28 19:45 UTC, ambv requested changes

2021-10-28 19:45 UTC, ambv commented on Doc/library/sqlite3.rst
> +.. warning::
We avoid using warnings in documentation. Instead we describe behavior using [affirmative tone](https://devguide.python.org/documenting/#affirmative-tone).

2021-10-28 19:45 UTC, ambv commented on Doc/library/sqlite3.rst
> +   returns a naive :class:`datetime.datetime` object, so if you read a timestamp
Outside of tutorials and howtos, we avoid addressing the reader as "you", instead using a style where the "you" is implied. Instead of saying:

> If you want X, do Y.

simply say:

> To achieve X, do Y.

2021-10-28 19:45 UTC, ambv commented on Doc/library/sqlite3.rst
> +   If you need to preserve UTC offsets in timestamps, then either leave
Similarly, instead of `if..then` just say "To preserve... either... or". This way you avoid the explicit "you".

2021-10-28 19:50 UTC, erlend-aasland commented on Doc/library/sqlite3.rst
> +   returns a naive :class:`datetime.datetime` object, so if you read a timestamp
Actually, I'd drop that part of the sentence. The first part already says that UTC offsets are ignored; no need to exemplify it. How about something like this:

```
    The "timestamp" converter ignores UTC offsets in the database and always 
    returns a naive :class:`datetime.datetime` object. To preserve UTC offsets
    in timestamps, either leave converters disabled, or register offset-aware
    converters with :func:`register_converter`.
```

2021-10-28 21:26 UTC, erlend-aasland approved these changes
LGTM. Thanks!

2021-10-29 20:17 UTC, merged

2021-10-29 20:17 UTC, miss-islington commented
Thanks @iafisher for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!