bpo-45639: Add webp and avif image formats to mimetypes
python/cpython pull request #29259
Opened 2021-10-28 02:35 UTC by kixorz

Modern image types webp and avif are not recognized by the mimetypes module.

Problem: Many tools are written in Python and running on macOS. Good example is the AWS CLI. Running commands like "s3 sync" will save files with .webp and .avif extensions with incorrect "binary/octet-stream" Content-Type to S3. This creates additional problems with serving these resources over HTTP.

The webp and avif image types are supported by most browsers:
https://caniuse.com/#feat=webp
https://caniuse.com/#feat=avif

While webp is fully supported and largely used, it is not officially registered with IANA.

Avif is currently less popular, but it is fully registered with IANA.
https://www.iana.org/assignments/media-types/media-types.xhtml

Please consider the attached GitHub PR as a fix to these MIME Content-Type issues.

https://bugs.python.org/issue45639

#89802

2021-10-30 17:27 UTC, merwok commented
wepb is already added in #23034 (and with proper alpha sorting in the list)

2021-10-31 01:42 UTC, kixorz commented
I saw the other PR, but it's not merged yet. The addition in the commit in this PR is sorted by mime type as requested in comment in the file.

2022-02-01 18:49 UTC, MaxwellDupre requested changes
Agreed these are not new and should be added but could you add to test Lib/test/test_mimetypes.py please?

2022-02-01 18:50 UTC, kixorz commented
Thank you. I'll add the test.

2022-02-01 19:01 UTC, merwok commented
On second thoughts, one ticket and one PR to add both types is fine.

2022-02-01 19:25 UTC, kixorz commented
I added the test.

2022-02-02 02:48 UTC, merwok commented
Can you add a news note on this model: https://github.com/python/cpython/pull/24917/files#diff-068155607fe32979f71408456e0f3163740897c21e6b6da80c45ec59cc660424

You can use https://blurb-it.herokuapp.com/ or `pip install blurb` locally

2022-02-02 03:03 UTC, TeamSpen210 commented
If `webp` is nonstandard, shouldn't it go in the non-strict dict instead?

2022-02-02 04:52 UTC, kixorz commented
I think I added the news entry. Thanks for the guidance.

2022-05-03 17:11 UTC, JelleZijlstra requested changes
Thanks, and sorry this was left hanging for so long! We still have a few days until the 3.11 feature freeze, and I'd love to get this in.

A few small things:
- You'll need to resign the CLA with our new process
- As @TeamSpen210 says, webp is nonstandard and should be in the `common_types` list.
- The docs build is failing because the blurb is missing a trailing newline.

2022-05-03 17:54 UTC, kixorz commented
I have made the requested changes; please review again.

2022-05-03 18:11 UTC, JelleZijlstra approved these changes

2022-05-03 18:19 UTC, JelleZijlstra commented
@kixorz thanks for the change! The tests are failing now, I think webp needs to move elsewhere in the test suite because it's not recognized by default.

2022-05-03 19:16 UTC, kixorz commented
I believe I fixed the tests.

2022-05-03 19:18 UTC, JelleZijlstra commented on Lib/test/test_mimetypes.py
> +        eq(self.db.guess_type('foo.xul', strict=True), (None, None))
This is duplicated
```suggestion
```

2022-05-03 19:21 UTC, kixorz commented
Thanks for checking it. Sorry, I missed it. Should be fine now.

2022-05-03 19:26 UTC, JelleZijlstra approved these changes

2022-05-03 21:17 UTC, merged

2022-05-04 03:24 UTC, kixorz commented
Thanks for merging my changes!