Change `%S` -> `%ls` in `swprintf` in `_testembed.c`
python/cpython pull request #29341
Opened 2021-10-31 08:35 UTC by sobolevn

Refs https://github.com/python/cpython/pull/29307

2021-10-31 08:41 UTC, sobolevn commented
Man: https://man7.org/linux/man-pages/man3/swprintf.3.html

2021-10-31 08:44 UTC, serhiy-storchaka approved these changes

2021-10-31 08:48 UTC, Fidget-Spinner approved these changes
I hope I understand the MSVC docs properly.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-160#size-prefixes-for-printf-and-wprintf-format-type-specifiers

2021-10-31 08:57 UTC, serhiy-storchaka requested changes
`%ls` is not applicable here.

One possible solutions is to use `%S` on Windows and `%s` on Linux (it should be tested). Or maybe there is a portable way.

2021-10-31 08:59 UTC, Fidget-Spinner requested changes
Following Serhiy's suggestion

2021-10-31 08:59 UTC, Fidget-Spinner commented on Programs/_testembed.c
> +    else if (swprintf(optval, 100, L"frozen_modules=%ls", rawval) < 0) {
```suggestion
    else if (swprintf(optval, 100,
#if defined(_MSC_VER)
        L"frozen_modules=%S",
#else
        L"frozen_modules=%s",
#endif
        rawval) < 0) {
```

2021-10-31 09:13 UTC, serhiy-storchaka commented
You can also use `Py_DecodeLocale()` as in other tests.

2021-10-31 13:21 UTC, serhiy-storchaka commented on Programs/_testembed.c
> +    wchar_t *frozen = Py_DecodeLocale(envvar, NULL);
If you are going to use `Py_DecodeLocale()`, you need to check its result for failure, and free the dynamic allocated memory after use. You should also add a special case for `getenv()` returning NULL.

@Fidget-Spinner's suggestion is much simpler.

2021-10-31 13:44 UTC, serhiy-storchaka approved these changes

2021-10-31 13:44 UTC, serhiy-storchaka approved these changes

2021-10-31 13:51 UTC, Fidget-Spinner approved these changes

2021-10-31 16:44 UTC, sobolevn commented
Thank you @serhiy-storchaka  and @Fidget-Spinner for your help! I am coming from Rust background and C is very hard for me! (no borrow checker 😬, you have to remember to deallocate memory!)

But, I will do my best to get used to it 🙂

2021-11-01 12:11 UTC, merged

2021-11-01 12:12 UTC, Fidget-Spinner commented
@sobolevn glad to help. Your comment also reminded me I should seriously try out Rust one day :). I still suck at it.

2021-11-01 14:16 UTC, sobolevn commented
@Fidget-Spinner you can take a look at `RustPython` project: https://github.com/RustPython/RustPython
I really like it! This was a project that motivated me to contribute to CPython.