bpo-45759: Better error messages for non-matching 'elif'/'else' state…
python/cpython pull request #29481
Opened 2021-11-09 00:05 UTC by thatbirdguythatuknownot

…ments

2021-11-09 09:36 UTC, pablogsal requested changes
Thanks for your PR! We need to think about this a bit more because I am not fully sure if this error is common enough to justify the extra complexity.

2021-11-09 09:36 UTC, pablogsal commented on Grammar/python.gram
> +    | &'elif' nomatch_elif
Unfortunately I'm not convinced about this, all of these should be in an "invalid_" rule and never inlined in the correct rule.

2021-11-09 09:36 UTC, pablogsal commented on Grammar/python.gram
> +nomatch_elif:
See my previous comment

2021-11-09 09:36 UTC, pablogsal commented on Grammar/python.gram
> +    | 'elif' named_expression ':' (NEWLINE INDENT statements | simple_stmts) a='else' {
I an not particularly convinced that the message is generic regarding the match ('if'/'while'/'for'/'except')

2021-11-09 09:38 UTC, pablogsal commented on Grammar/python.gram
> +    | 'if' named_expression ':' (NEWLINE INDENT statements | simple_stmts) a='elif' {
You can probably merge this two

2021-11-10 00:24 UTC, thatbirdguythatuknownot commented
Sorry for the many 'Fix conflicts' commits, I was trying to fix the `Parser/parser.c` conflict.

2021-11-10 02:54 UTC, thatbirdguythatuknownot commented
I have made the requested changes; please review again.

2021-11-10 10:36 UTC, closed without merging

2021-11-10 10:36 UTC, thatbirdguythatuknownot commented
Moved to another pull request with same title.