Fix issue 30987
python/cpython pull request #2956
Opened 2017-07-31 04:29 UTC by pylessard

This Pull Request add the support of CAN ISO-TP address extensions in `getsockaddrarg`.
It also defines constants required to create the socket as well as set/get options as defined in the [can-isotp](https://github.com/hartkopp/can-isotp) loadable kernel module readily available in the linux community.

In order to build Python with support of CAN_ISOTP, one must make `can-isotp/include/uapi/` available to the compiler include path before running `./configure`.

2017-07-31 04:29 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-07-31 11:51 UTC, pylessard commented
It look like the failing test on Travis CI are not related to this Pull Request. The main branch has the same failing tests.

2017-08-01 16:07 UTC, pylessard commented
After second thoughts, only the `getsockaddress` interface should be included in Python.
The constant in [can-isotp](https://github.com/hartkopp/can-isotp) should com from a third party module.
Will do the change and reopen the pull request

2017-08-03 04:16 UTC, pylessard commented
Pull request is re-open. All dependencies over the third aprty project have been removed.
getsockname also supports ISOTP now.

2017-08-26 13:52 UTC, tiran requested changes
Thanks for your contribution. Your patch looks mostly fine, good work! I added notes for some style nit picks and a missing ``ifdef`` check.

2017-08-26 13:52 UTC, tiran commented on Modules/socketmodule.c
> +    PyModule_AddIntMacro(m, CAN_ISOTP);
This needs a ``#ifdef CAN_ISOTP``.

2017-08-26 13:52 UTC, tiran commented on Modules/socketmodule.c
> +#if defined(CAN_ISOTP)
``#ifdef CAN_ISOTP``

2017-08-26 13:52 UTC, tiran commented on Modules/socketmodule.c
> +#if defined(AF_CAN)
Please use ifdef for simple checks: ``#ifdef AF_CAN``

2017-08-26 13:52 UTC, tiran commented on Lib/test/test_socket.py
> +                addr = (self.interface,0x123,0x456)
Style nit pick: ``addr = self.interface, 0x123, 0x456``

2017-08-26 13:52 UTC, tiran commented on Lib/test/test_socket.py
> +                                   s.bind, ('x' * 1024,1,2))
Please use

```
with self.assertRaisesRegex(OSError, 'interface name too long'):
    s.bind(('x' * 1024, 1, 2))
```
to make it more readable.

2017-08-26 20:08 UTC, pylessard commented
I didn't expect the Spanish Inquisition!

2017-08-27 20:47 UTC, tiran commented
Your PR is still missing a space after comma in ``test_socket.py``, https://github.com/python/cpython/pull/2956/commits/280141c99b81411cd000bb61391a9c39935901c6#diff-30065f853d7944a19b3e17b55db67733 . Let's follow PEP 8 for new code.

2017-08-27 20:58 UTC, pylessard commented
Changes done sir!

2017-08-28 08:32 UTC, tiran approved these changes
perfect! 🥇

2017-08-28 08:32 UTC, merged