bpo-45512: Simplify manage isolation level
python/cpython pull request #29562
Opened 2021-11-15 13:10 UTC by corona10

2021-11-15 13:11 UTC, corona10 commented
@erlend-aasland Can you please take a look?

2021-11-15 13:32 UTC, corona10 commented
````

0:00:00 load avg: 1.52 Run tests sequentially
0:00:00 load avg: 1.52 [1/1] test_sqlite3
beginning 6 repetitions
123456
......

== Tests result: SUCCESS ==

1 test OK.

Total duration: 4.3 sec
Tests result: SUCCESS
````

2021-11-15 14:12 UTC, erlend-aasland requested changes
I like this change! However, I think we can improve it further :) See my comments; let me know what you think.

2021-11-15 14:12 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +        rc = sqlite3_prepare_v2(self->db, "BEGIN ", -1, &statement, NULL);
Hm, you will never reach this branch. I suggest to add an `assert(self->isolation_level != NULL)` at the start of the function and remove this `if..else` instead.

2021-11-15 14:12 UTC, erlend-aasland commented on Modules/_sqlite/connection.c
> +    "EXCLUSIVE",
Should we move this static array into `get_isolation_level` while we're at it? Something like this:

```
static const char *
get_isolation_level(const char *level)
{
    static const char *const allowed_levels[] = {
        ...
    };
    ...
}
```

I will make the connection between this function and the array clearer.

2021-11-15 14:12 UTC, erlend-aasland commented on Modules/_sqlite/connection.c
> +        const char *level = get_isolation_level(isolation_level);
Now that there is no "isolation level to begin statement" conversion happening here, I find the `get_isolation_level` name a bit strange. I would prefer to rename `get_isolation_level` to `validate_isolation_level` and make it return 0 on success and -1 on error.

Another thing: it would be super nice to add a custom AC converter that could handle this conversion. That would mean that `__init__` was given a completely valid `const char *isolation_level`, and we could just place it in `self->isolation_level` without _any_ fuzz! It would make `__init__` even simpler.

2021-11-15 14:12 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +        char begin_stmt[80] = {0, };
IMO, 80 chars is too much overshoot. Max `strlen` is 15.

```suggestion
        char begin_stmt[16] = {0, };
        assert((strlen(self->isolation_level) + 1) >
               (sizeof(begin_stmt) - strlen(self->isolation_level)));
```

2021-11-15 14:12 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +        strcat(begin_stmt, self->isolation_level);
```suggestion
        (void)strcpy(begin_stmt, "BEGIN ");
        (void)strcat(begin_stmt, self->isolation_level);
```

2021-11-15 14:12 UTC, erlend-aasland commented on Modules/_sqlite/connection.h
> +    const char* isolation_level;
```suggestion
    const char *isolation_level;
```

2021-11-15 14:39 UTC, corona10 commented on Modules/_sqlite/connection.c
> +        const char *level = get_isolation_level(isolation_level);
> it would be super nice to add a custom AC converter that could handle this conversion.

I will left this part for you :)

2021-11-15 15:11 UTC, erlend-aasland commented on Modules/_sqlite/connection.c
> +        const char *level = get_isolation_level(isolation_level);
I'm on it ;) I can submit a PR for it after this has landed. I don't think I can modify your PR.

2021-11-15 17:17 UTC, erlend-aasland approved these changes
LGTM (with small nitpick comment; you can ignore it if you want). I'll add the AC converter in a new PR :)

2021-11-15 17:17 UTC, erlend-aasland commented on Modules/_sqlite/connection.c
> +    static const char * const allowed_levels[] = {
```suggestion
    static const char *const allowed_levels[] = {
```

2021-11-15 17:31 UTC, erlend-aasland commented
(See my DM on Discord before merging)

2021-11-15 19:01 UTC, erlend-aasland commented on Modules/_sqlite/connection.c
> +        const char *level = get_isolation_level(isolation_level);
>  I would prefer to rename get_isolation_level to validate_isolation_level and make it return 0 on success and -1 on error.

I withdraw this suggestion. We need to revert this particular change; we need to be sure that the pointer is valid as long as the connection object is alive.

2021-11-16 08:33 UTC, corona10 commented
@erlend-aasland 
````
>>> import sqlite3
>>> cx = sqlite3.connect(":memory:", isolation_level="DEFERRED")
>>> cx.isolation_level
'DEFERRED'
>>> cx.isolation_level
'DEFERRED'
>>> cx.isolation_level = "immediate"
>>> cx.isolation_level
'IMMEDIATE'
>>>
````

2021-11-16 09:31 UTC, erlend-aasland requested changes

2021-11-16 09:31 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +    (void)strcat(begin_stmt, self->isolation_level);
```suggestion
    char begin_stmt[16] = "BEGIN ";
    (void)strncat(begin_stmt, self->isolation_level, 9);
```

2021-11-16 10:22 UTC, corona10 commented on Modules/_sqlite/cursor.c
> +    (void)strcat(begin_stmt, self->isolation_level);
@erlend-aasland 
Why 15 not strlen(self->isolation_level) ?

2021-11-16 10:35 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +    (void)strcat(begin_stmt, self->isolation_level);
Because `strncat` will copy at most `n` bytes and then append a null terminator (thus never copying more than `n` + 1 bytes), so `strncat` will _never_ overflow the `begin_stmt` buffer.

`strlen` with an arbitrary value _may_ overflow that buffer, so `strlen(self->isolation_level) + strlen("BEGIN ")` _must not_ exceed 15. If we chose to keep `strcat`, we must at least `assert` for that condition.

At this point in time, the current code is of course technically safe, because we _know_ what the set of allowed input values is. _But_ that may change in the future (though it probably won't). Also, I consider it good practise to always make sure we avoid buffer overflows, even for trivial things like this :)

2021-11-16 11:20 UTC, erlend-aasland approved these changes

2021-11-16 11:51 UTC, erlend-aasland requested changes

2021-11-16 11:51 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +    assert(len <= 9);
`strlen` is only needed for `assert`, so we can wrap it in `#if Py_DEBUG`:

```suggestion
#ifdef Py_DEBUG
    size_t len = strlen(self->isolation_level);
    assert(len <= 9);
#endif
```

2021-11-16 13:34 UTC, erlend-aasland approved these changes
LGTM. Let's pull in the tests before landing.

2021-11-16 17:19 UTC, erlend-aasland commented
FYI, you need to merge in `main`, now that GH-28227 has landed.

2021-11-17 10:02 UTC, corona10 commented
@erlend-aasland 
I check this PR with https://github.com/python/cpython/pull/29576 and it works as expected :)

2021-11-17 10:12 UTC, erlend-aasland approved these changes
Great, LGTM!

2021-11-17 12:47 UTC, merged

2021-11-17 13:36 UTC, erlend-aasland commented on Modules/_sqlite/connection.c
> +        const char *level = get_isolation_level(isolation_level);
> I'm on it ;) I can submit a PR for it after this has landed. I don't think I can modify your PR.

FTR: I opened GH-29593