bpo-45874: Handle empty query string correctly in urllib.parse.parse_qsl
python/cpython pull request #29716
Opened 2021-11-22 22:39 UTC by sattlerc

2021-11-22 22:39 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@sattlerc

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-11-28 21:36 UTC, nickgaya commented on Lib/urllib/parse.py
> +    if qs:
Might be more readable to do:
```
if not qs:
    return r
```

2021-11-28 23:04 UTC, sattlerc commented on Lib/urllib/parse.py
> +    if qs:
This might be even more readable:
```python
query_args = qs.split(separator) if qs else []
for name_value in query_args:
    [...]
```

2021-12-02 08:42 UTC, asvetlov requested changes
Please add a new entry

2021-12-02 10:58 UTC, sattlerc commented
I have made the requested changes; please review again.

2021-12-09 12:59 UTC, asvetlov approved these changes

2021-12-12 08:41 UTC, merged

2021-12-12 08:41 UTC, asvetlov commented
Thanks!