pydoc html: parse https links
python/cpython pull request #2975
Opened 2017-08-01 11:00 UTC by python273

2017-08-01 11:00 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-08-02 11:09 UTC, python273 commented
> Contributor Form Received | Yes on: 2017-08-01.00:00:00

![parrot](http://cultofthepartyparrot.com/parrots/parrot.gif)

2017-11-25 18:51 UTC, Mariatta commented
Thanks for the PR. I think this change requires an issue in the b.p.o, a News entry and tests.

2018-03-26 09:33 UTC, serhiy-storchaka requested changes
Please open an issue on the [bug tracker](https://bugs.python.org/) for discussion.

2019-04-10 13:24 UTC, csabella commented
@python273 Thank you for the suggested change and for the PR!  If you've opened a bug tracker ticket per @serhiy-storchaka's review, please update the PR title with the bpo number.  If you haven't yet opened a ticket, please do so in order for review of this PR to proceed.  Also, please make the changes suggested by @Mariatta.  Thanks!

2019-05-13 04:06 UTC, csabella commented
I am closing this issue.  Feel free to re-open once the concerns have been addressed.

2019-05-13 04:06 UTC, closed without merging