bpo-38619: Update the documention for UUID.hex
python/cpython pull request #29830
Opened 2021-11-29 05:48 UTC by 180909

https://bugs.python.org/issue38619

2021-12-20 08:14 UTC, kumaraditya303 requested changes

2021-12-20 08:14 UTC, kumaraditya303 commented on Doc/library/uuid.rst
> +   The UUID as a 32-character hexadecimal string, and it's always lowercase.
```suggestion
   The UUID as a 32-character lowercase hexadecimal string.
```

2021-12-21 10:10 UTC, kumaraditya303 approved these changes

2022-01-12 13:28 UTC, hugovk approved these changes

2022-02-14 18:55 UTC, Mariatta approved these changes

2022-02-14 18:58 UTC, merged

2022-02-14 18:58 UTC, miss-islington commented
Thanks @180909 for the PR, and @Mariatta for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖