bpo-24301: Do not fail when gzip files have trailing garbage
python/cpython pull request #29847
Opened 2021-11-29 15:28 UTC by rhpvorderman

Apparently the `gzip` command line utility and several others display the same behaviour. Python failing here is unexpected.

The code was adapted so that trailing garbage emits a warning (just like the gzip cli). The first member is still checked for a correct magic number.

2022-02-27 12:36 UTC, MaxwellDupre requested changes
Could you add to docs, please?
I think its important users know what to expect. Does't need much, similar to what you have in NEWS.

2022-03-08 10:49 UTC, rhpvorderman commented
@MaxwellDupre I added some `..versionchanged` notes. Is that what you had in mind?

2025-10-20 08:56 UTC, jonathanunderwood commented
Is there any chance of moving this one forward?

2025-12-01 08:12 UTC, rhpvorderman commented
If the changes as is are deemed OK I am prepared to port them to the newest python version and resolve the conclicts.

2026-05-20 12:28 UTC, serhiy-storchaka commented
I understand the need of such feature, but ignoring error (or simple emitting a warning) is a wrong solution. We need to design more general solution which would work with all kind of errors with arbitrary buffered files.

2026-05-20 12:28 UTC, closed without merging

2026-05-20 13:18 UTC, rhpvorderman commented
I just checked the spec: https://www.rfc-editor.org/rfc/rfc1952

> The members simply appear one after another in the file,
      with no additional information before, between, or after them.

So I am fully onboard with dropping this.