bpo-31109: Convert zipimport to argument clinic
python/cpython pull request #2990
Opened 2017-08-02 19:06 UTC by jarondl

Convert the zipimport module to argument clinic. Mostly
straight-forward, had to rename a few argument names.

2017-08-03 07:16 UTC, serhiy-storchaka commented on Modules/zipimport.c
> +    archivepath: object(converter="PyUnicode_FSDecoder")
Why not use just the name "path"?

2017-08-03 07:16 UTC, serhiy-storchaka commented on Modules/zipimport.c
> +    fullname: unicode
The arguments of this method (and many other methods) were positional-only. Converting to Argument Clinic shouldn't change the behavior.

2017-08-03 14:26 UTC, jarondl commented on Modules/zipimport.c
> +    fullname: unicode
Actually *all* the methods here were positional-only. But this change is backwards compatible and logical. See for example http://bugs.python.org/issue20294#msg208444
Why should we force positional-only? Your patch in bpo-25711 to convert `zipimport` to Python would also have the same effect.

2017-08-03 14:29 UTC, jarondl commented on Modules/zipimport.c
> +    archivepath: object(converter="PyUnicode_FSDecoder")
Do you mean `path:` or `archivepath as path:`? 
Sure I can do the latter, but what's the benefit? It was more straight forward to rename the variable to match the signature

2017-08-03 14:31 UTC, jarondl commented on Modules/zipimport.c
> +    fullname: unicode
Do you prefer to keep Argument Clinic conversion separate from behavioral changes? Then we can add trailing `/`s to the argument lists and remove them in a separate PR.

2017-08-03 18:42 UTC, brettcannon commented on Modules/zipimport.c
> +    fullname: unicode
Yeah, we prefer to not change semantics while doing an Argument Clinic conversion (we have run into issues in the past when doing both at the same time).

2017-08-03 19:24 UTC, jarondl commented on Modules/zipimport.c
> +    fullname: unicode
OK, done, now they are positional only. Thank you both for reviewing.

2017-08-09 18:40 UTC, brettcannon requested changes

2017-08-09 18:40 UTC, brettcannon commented on Modules/zipimport.c
> +    archivepath: object(converter="PyUnicode_FSDecoder")
The benefit of not renaming is the patch is much easier to review that way. As it stands it's much harder for us to check the accuracy of the changes due to so many lines being flagged as changed compared to just reviewing the Argument Clinic changes which is what this PR is specifically targeting.

2017-08-10 16:56 UTC, jarondl commented on Modules/zipimport.c
> +    archivepath: object(converter="PyUnicode_FSDecoder")
Done.

2017-08-10 19:57 UTC, brettcannon requested changes
Three really minor formatting tweaks necessary and then I think this will be ready to go!

2017-08-10 19:57 UTC, brettcannon commented on Modules/zipimport.c
> +'ZipImportError is raised if 'archivepath' doesn't point to a valid Zip
Looks like there is a stray `'` at the start of this sentence.

2017-08-10 19:57 UTC, brettcannon commented on Modules/zipimport.c
> +The 'archive' attribute of zipimporter objects contains the name of the
"zipimporter objects" -> "the zipimporter object".

2017-08-10 19:57 UTC, brettcannon commented on Modules/zipimport.c
> +'fullname' must be the
Premature line break.

2017-08-10 21:55 UTC, brettcannon approved these changes
@serhiy-storchaka did you have any other feedback or can I merge this?

2017-08-17 00:45 UTC, jarondl commented
@serhiy-storchaka and @brettcannon , is there anything else I can do to have this merged?
In any case I want to say thank you both for the reviews.

2017-08-17 19:08 UTC, brettcannon commented
Since it looks like @serhiy-storchaka has nothing to add would you mind adding a news entry? See https://devguide.python.org/committing/#what-s-new-and-news-entries on how to do that. Once that's file in I can touch it up as necessary and then merge this!

2017-08-17 19:09 UTC, brettcannon requested changes
Please add a news entry.

2017-08-18 00:35 UTC, jarondl commented
Blimey, I didn't expect the Spanish Inquisition!

2017-08-18 18:26 UTC, brettcannon approved these changes
Once Travis goes green I'll merge!

2017-08-18 18:41 UTC, merged

2017-08-18 18:41 UTC, brettcannon commented
Thanks for the work, @jarondl !