bpo-45976: Remove unhelpful locals in Random._randbelow()
python/cpython pull request #29911
Opened 2021-12-04 02:22 UTC by onethreeseven

_randbelow_with_getrandbits() calls getrandbits() at most twice on average, so
the local reference never pays for itself.  Speeds up randrange(), shuffle(),
and sample().

_randbelow_without_getrandbits() gets a similar change for similar reasons.

2021-12-04 02:22 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@onethreeseven

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-12-04 04:24 UTC, rhettinger commented
Please sign the CLA and continue to update this PR.

I'll review it again when Python 3.11 is more mature, so we can have reliable before/after timings.

2021-12-04 04:38 UTC, onethreeseven commented
I think I've done what is necessary to sign the CLA and will check back on it in a few days.

2022-02-10 20:14 UTC, MaxwellDupre requested changes
I had to significantly hack the randbelow_timing.py to get it to work but still not right especially the function MainWithoutGetrandbits (random = self.random?). Hence, could you post a working test file? And possibly add a test?

2022-02-10 20:35 UTC, onethreeseven commented
I would also note that if you find `random = self.random` unusual, your issue is with [the current standard library](https://github.com/python/cpython/blob/main/Lib/random.py#L251), not with me.  But that kind of optimization is the entire thrust of the PR.

2022-02-13 15:02 UTC, rhettinger commented
Marking this as closed.  For the average case, it is mildly beneficial but only on some builds. For the multiple rejection case it is detrimental. I prefer to minimize the cost of the unhappy case.

2022-02-13 15:02 UTC, closed without merging