bpo-45711: Do not push/pop traceback on stack as part of exc_info
python/cpython pull request #29968
Opened 2021-12-07 17:47 UTC by iritkatriel

2021-12-07 17:48 UTC, iritkatriel commented
Marked as draft because I still need to update the opcodes documentation

2021-12-07 17:49 UTC, iritkatriel commented on Python/ceval.c
> +                exc_info->exc_traceback = PyException_GetTraceback(exc_info->exc_value);
The next step is to remove exc_traceback from exc_info and then this will not be here.

2021-12-07 18:23 UTC, iritkatriel commented
This clashes with the except* branch, and I'd rather merge that one first and update this one.

2021-12-08 11:31 UTC, markshannon commented
> This clashes with the except* branch, and I'd rather merge that one first and update this one.

I would rather merge this first.
Apart from the trivial conflict in dis.rst this seems ready to merge. The except* branch is not.

2021-12-08 11:39 UTC, iritkatriel commented
> > This clashes with the except* branch, and I'd rather merge that one first and update this one.
> 
> I would rather merge this first. Apart from the trivial conflict in dis.rst this seems ready to merge. The except* branch is not.

We won't see a speedup for this because of the get_exc_traceback calls. We should remove them before measuring, and probably merge the whole thing together.

2021-12-08 11:49 UTC, iritkatriel commented
> We won't see a speedup for this because of the get_exc_traceback calls. We should remove them before measuring, and probably merge the whole thing together.

And that requires PR 29922.

2021-12-08 11:55 UTC, arhadthedev requested changes
Spacing between tokens is strange.

2021-12-08 11:55 UTC, arhadthedev commented on Python/compile.c
> +            return -1 -2 * PY_EXC_INFO_STACK_SIZE;
```suggestion
            return -1 - 2 * PY_EXC_INFO_STACK_SIZE;
```

or even

```suggestion
            return -(1 + 2 * PY_EXC_INFO_STACK_SIZE);
```

2021-12-08 11:55 UTC, arhadthedev commented on Python/ceval.c
> +            PyObject *lasti = PEEK(PY_EXC_INFO_STACK_SIZE+1);
```suggestion
            PyObject *lasti = PEEK(PY_EXC_INFO_STACK_SIZE + 1);
```

2021-12-08 11:55 UTC, arhadthedev commented on Python/ceval.c
> +                PyObject *lasti = PEEK(oparg+PY_EXC_INFO_STACK_SIZE);
```suggestion
                PyObject *lasti = PEEK(oparg + PY_EXC_INFO_STACK_SIZE);
```

2021-12-15 18:37 UTC, iritkatriel commented
Superseded by https://github.com/python/cpython/pull/30122

2021-12-15 18:37 UTC, closed without merging