Docs: Add note regarding "reversed" flag in heapq.merge
python/cpython pull request #300
Opened 2017-02-25 21:57 UTC by AdamNiederer

The docs for `heapq.merge` are a little ambiguous. Iterables passed
into heapq.merge with the reversed flag enabled must be sorted from
largest to smallest to achieve the desired sorting affect, but the
previous paragraph states that they should be sorted from smallest
to largest.

2017-02-25 21:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/). The "bugs.python.org username" requested by the form is the "Login name" field in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/23276970/d14a380c-f9d1-11e6-883d-e13b6b211239.png)
2. **Wait at least one US business day** and then check the "Contributor form received entry under "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-03-03 17:47 UTC, Carreau commented
Thanks Adam, I believe the core dev expect all Pull-Requests to be backed by an issue on http://bugs.python.org/ you might have to create one and link it from here. 

+1 otherwise.

2017-03-05 05:02 UTC, rhettinger commented
I would think this would be obvious and it has never been a source of confusion.  But I don't mind the additional wording.

2017-03-05 05:04 UTC, rhettinger requested changes
"To achieve similar behavior to" -> "To achieve behavior similar  to"

2017-03-05 16:53 UTC, rhettinger approved these changes

2017-03-05 16:56 UTC, merged