bpo-45855: Replaced deprecated `PyImport_ImportModuleNoBlock` with PyIm…
python/cpython pull request #30046
Opened 2021-12-11 08:38 UTC by kumaraditya303

…port_ImportModule

2021-12-11 09:10 UTC, kumaraditya303 commented
cc @asvetlov

2021-12-11 09:54 UTC, arhadthedev requested changes

2021-12-11 09:54 UTC, arhadthedev commented on Misc/NEWS.d/next/C API/2021-12-11-08-41-36.bpo-45855.Lq2_gR.rst
> +Replaced deprecated :c:func:`PyImport_ImportModuleNoBlock` with :c:func:`PyImport_ImportModule`. Patch by Kumar Aditya.
Such a wording may create an impression that the whole Python (C API included) makes a replacement.

```suggestion
Built-in Python modules stopped using deprecated :c:func:`PyImport_ImportModuleNoBlock` in favor of :c:func:`PyImport_ImportModule`. Patch by Kumar Aditya.
```

2021-12-11 12:43 UTC, tiran approved these changes
Thanks, LGTM! 

PyImport_ImportModuleNoBlock is basically an alias for PyImport_ImportModule nowadays.

```
PyObject *
PyImport_ImportModuleNoBlock(const char *name)
{
    return PyImport_ImportModule(name);
}
```

2021-12-12 08:44 UTC, asvetlov approved these changes

2021-12-12 08:45 UTC, merged

2021-12-12 08:45 UTC, asvetlov commented
Thanks!