bpo-45997: Fix asyncio.Semaphore waiters order
python/cpython pull request #30052
Opened 2021-12-11 14:42 UTC by hyzyla

Allow other Semaphore waiters to acquire lock after releasing by current coroutine by skipping one event loop iteration. If everything is OK for Semaphore, I can add the same logic to other asyncio synchronization primitives

2021-12-11 14:42 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@hyzyla

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-12-14 09:52 UTC, asvetlov requested changes
The PR adds unconditional sleep even if the waiting is not needed (the context was switched already).
I think we need an alternative implementation based on future object waiting.

2022-01-18 07:28 UTC, taleinat commented
@hyzyla, are you interested in continuing to work on this PR following @asvetlov's comment?

(If so, we will need to to sign the CLA.)

2022-01-19 20:11 UTC, hyzyla commented
I would like to return to PR in few weeks, I have idea where I will create Future, then will put it to loop via call_soon and in the end in acquire method waiting for that Future

2022-01-20 22:18 UTC, taleinat commented
Alright @hyzyla, looking forward to what you'll come up with!

2022-03-15 17:52 UTC, asvetlov commented
https://github.com/python/cpython/pull/31910 is an alternative fix

2022-03-22 19:45 UTC, asvetlov commented
Thanks for the PR!
Fixed by #31910

2022-03-22 19:45 UTC, closed without merging