bpo-46053: Fix OSS audio support on NetBSD
python/cpython pull request #30065
Opened 2021-12-11 23:17 UTC by 0-wiz-0

2021-12-13 08:39 UTC, tiran requested changes

2021-12-13 08:39 UTC, tiran commented on configure.ac
> +esac
We keep feature checks and module definitions separate. Between ``LIBNSL`` and ``LIBSQLITE3`` looks like a nice spot. We also prefer m4 macros for new code:

```
AS_CASE([$ac_sys_system],
  [NetBSD*], [OSSAUDIODEV_LIBS="-lossaudio"],
  [OSSAUDIODEV_LIBS=""]
)
```

2021-12-13 08:52 UTC, 0-wiz-0 commented
Thanks for the suggestions!

I have made the requested changes; please review again

2022-01-21 09:10 UTC, 0-wiz-0 commented
@serhiy-storchaka You were so kind to review my other NetBSD pull requests, can you please check this one as well?

2022-01-21 17:41 UTC, serhiy-storchaka reviewed
I am not experienced with autotools. Should not AC_CHECK_LIB be used here?

2022-01-21 18:03 UTC, 0-wiz-0 commented
AFAIK only NetBSD provides libossaudio, and all versions of it (but definitely all supported versions) provide the library. That's why I thought it'd be easier just to add it this way.

2022-02-03 09:31 UTC, serhiy-storchaka commented on Misc/NEWS.d/next/Core and Builtins/2021-12-12-00-15-53.bpo-46053.tnok-6.rst
> +Fix OSS audio support on NetBSD
It should be in the "Library" section, not in "Core and Builtins". And please add a sentence-ending period.

Otherwise LGTM.

2022-02-06 12:01 UTC, 0-wiz-0 commented
Thanks for the review, @serhiy-storchaka 
I've made the requested changes.

2022-02-06 12:04 UTC, serhiy-storchaka approved these changes

2022-04-12 06:05 UTC, hugovk commented
Note the ossaudiodev module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

2022-04-12 14:19 UTC, AlexWaygood commented
> Note the ossaudiodev module is deprecated in 3.11 and set for removal in 3.13.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and #91217.

There is also now a merge conflict (I don't know how large the merge conflict is).

2022-04-12 14:44 UTC, hugovk commented
Here's the conflict:
```diff
diff --cc configure.ac
index 7d194f263e,6a460cd94c..0000000000
--- a/configure.ac
+++ b/configure.ac
@@@ -6409,8 -6789,8 +6795,13 @@@ PY_STDLIB_MOD([_socket]
  dnl platform specific extensions
  PY_STDLIB_MOD([grp], [], [test "$ac_cv_func_getgrgid" = yes -o "$ac_cv_func_getgrgid_r" = yes])
  PY_STDLIB_MOD([ossaudiodev],
++<<<<<<< HEAD
 +  [], [test "$ac_cv_header_linux_soundcard_h" = yes -o "$ac_cv_header_sys_soundcard_h" = yes],
 +  [], [$OSSAUDIODEV_LIBS])
++=======
+   [], [test "$ac_cv_header_linux_soundcard_h" = yes -o "$ac_cv_header_sys_soundcard_h" = yes])
+ PY_STDLIB_MOD([pwd], [], [test "$ac_cv_func_getpwuid" = yes -o "$ac_cv_func_getpwuid_r" = yes])
++>>>>>>> upstream/main
  PY_STDLIB_MOD([resource], [], [test "$ac_cv_header_sys_resource_h" = yes])
  PY_STDLIB_MOD([_scproxy],
    [test "$ac_sys_system" = "Darwin"], [],
```

2022-04-15 22:21 UTC, 0-wiz-0 commented
Some more years will pass before this code is really removed from python, so I'd like to see this merged.

I tried fixing the merge conflict on the ossaudio branch but my git-foo left me, the merged commits are now on

https://github.com/0-wiz-0/cpython/tree/ossaudio-v2

instead (but it's straightforward - on main, a line was added that is in the context of the change I made, the context just needs to be adapted).

2022-04-16 12:22 UTC, hugovk commented
If https://github.com/0-wiz-0/cpython/tree/ossaudio-v2 has what you want to merge, two options:

* Create a new PR from that branch, close this

* Reset this branch to that one, and force push to replace this:

```sh
# Start from this branch
git checkout ossaudio

# Replace the contents of this branch with ossaudio-v2
git reset --hard ossaudio-v2

# Now because we've rewritten the history of this branch, 
# we need to force push it
git push --force
```

2022-04-18 08:02 UTC, 0-wiz-0 commented
Thanks for the instructions, @hugovk ! I've just force-pushed to the ossaudio branch.

2022-04-18 08:46 UTC, AlexWaygood commented
@serhiy-storchaka, you previously approved this PR — reckon it can now be merged? :)

2022-04-18 09:12 UTC, merged

2022-04-18 09:16 UTC, serhiy-storchaka commented
I think that it is worth to to continue to fix bugs in deprecated modules. Especially if the solution is already ready.

Requests for new features will be rejected of course.

2022-04-18 09:19 UTC, 0-wiz-0 commented
Thank you for merging this, @serhiy-storchaka !

2022-04-20 10:47 UTC, miss-islington commented
Thanks @0-wiz-0 for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖

2022-04-20 10:47 UTC, miss-islington commented
Thanks @0-wiz-0 for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖

2022-04-20 10:47 UTC, miss-islington commented
Sorry, @0-wiz-0 and @serhiy-storchaka, I could not cleanly backport this to `3.9` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 2e7e3c4c109928870c1e33d8af36b78e92895594 3.9
                                ```

2022-04-20 10:47 UTC, miss-islington commented
Sorry @0-wiz-0 and @serhiy-storchaka, I had trouble checking out the `3.10` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 2e7e3c4c109928870c1e33d8af36b78e92895594 3.10
                                ```

2022-04-20 10:49 UTC, serhiy-storchaka commented
@0-wiz-0 do you think it is a good idea of backporting this change?

2022-04-20 10:55 UTC, 0-wiz-0 commented
@serhiy-storchaka if it's easy, I'd appreciate it (I think it should be easy) but if you don't want to spend the time on this, I understand and it's fine with me.

2022-04-20 11:01 UTC, serhiy-storchaka commented
I mean, do you want to spent your time on this? :wink:  I'll approve it immediately.

It is okay if you do not do it. I can make the backport myself, although I am not enough motivated to test it on NetBSD.

2022-07-30 19:14 UTC, 0-wiz-0 commented
Hi @serhiy-storchaka ! Sorry it tooks so long, but I've finally tried cherry_picker. The problem was that 3.10 and earlier still have the ossaudio module support in setup.py instead of configure.ac.
The pull request for 3.10 is here:
https://github.com/python/cpython/pull/95477
works on NetBSD

If this is fine, can we use that patch to merge to 3.9? I think that should apply more easily to 3.9.
Thanks.

2022-07-30 19:17 UTC, AlexWaygood commented
> If this is fine, can we use that patch to merge to 3.9?

3.9 is now in security-only mode; only security-related patches are backported to 3.9 these days.

2022-07-30 19:18 UTC, 0-wiz-0 commented
@AlexWaygood Oh, that's fine then. Thanks for the information.