Fix ipaddress.ip_network TypeErrors
python/cpython pull request #30087
Opened 2021-12-13 12:12 UTC by bharel

Minor fix - IPv4Network accepts a tuple.

If you send a tuple to ip_network instead, it throws a TypeError while attempting to format the ValueError message.

Fixed all 3 `%` formats.

Skip NEWS + Skip issue please.

2021-12-14 09:46 UTC, asvetlov requested changes
Please use f-strings here, they make code much easier to read.

2021-12-14 15:40 UTC, Fidget-Spinner requested changes
> If you send a tuple to ip_network instead, it throws a TypeError while attempting to format the ValueError message.
> Skip NEWS + Skip issue please.

That's a bug and there should be a bugs.python.org issue created for it please. Also anything that is user-facing needs a news entry. Thank you.

2021-12-20 23:25 UTC, bharel commented
I have made the requested changes; please review again

2021-12-23 09:25 UTC, kumaraditya303 approved these changes

2022-01-08 20:01 UTC, taleinat approved these changes
LGTM.

@asvetlov, @Fidget-Spinner, want another look before this goes in?

2022-01-12 13:33 UTC, Fidget-Spinner approved these changes
@taleinat sorry for the delay, I missed this notification.

This LGTM too. Thank you for addressing our reviews.

2022-01-21 05:34 UTC, iritkatriel commented
We need a test for this.

2022-05-03 12:14 UTC, JelleZijlstra commented
I merged #30642 which does the same thing, but with tests. Thanks for your contribution!

2022-05-03 12:14 UTC, closed without merging