bpo-46080: Fix crash when argparse.BooleanOptionalAction is used with default=argparse.SUPPRESS and help specified
python/cpython pull request #30111
Opened 2021-12-15 06:35 UTC by felixfontein

When `argparse.BooleanOptionalAction` is used with `default=argparse.SUPPRESS` and `help` specified, help text composition currently crashes. This PR fixes that by also checking whether `default is not SUPPRESS` before appending `%(default)s` to `help`.

Fixes https://bugs.python.org/issue46080.

2021-12-15 06:35 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@felixfontein

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-01-08 19:55 UTC, taleinat requested changes
Looks good to me, but I suggest some minor changes to the NEWS entry.

2022-01-08 19:55 UTC, taleinat commented on Misc/NEWS.d/next/Library/2021-12-15-06-29-00.bpo-46080.AuQpLt.rst
> +No longer crashes on help text composition if :class:`argparse.BooleanOptionalAction`'s default is ``argparse.SUPPRESS`` and ``help`` is specified.
```suggestion
Fix exception in argparse help text generation if a
:class:`argparse.BooleanOptionalAction` argument's default is
``argparse.SUPPRESS`` and it has ``help`` specified.  Patch by Felix Fontain.
```

2022-01-08 20:41 UTC, felixfontein commented on Misc/NEWS.d/next/Library/2021-12-15-06-29-00.bpo-46080.AuQpLt.rst
> +No longer crashes on help text composition if :class:`argparse.BooleanOptionalAction`'s default is ``argparse.SUPPRESS`` and ``help`` is specified.
That sounds much better, thanks!

2022-01-20 22:10 UTC, taleinat approved these changes

2022-01-20 22:48 UTC, merged

2022-01-20 22:48 UTC, miss-islington commented
Thanks @felixfontein for the PR, and @taleinat for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖

2022-01-21 04:57 UTC, felixfontein commented
@taleinat thanks for reviewing and merging this!