bpo-46103: Fix inspect.getmembers call the instance __bases__ attribute which ma…
python/cpython pull request #30147
Opened 2021-12-16 15:46 UTC by hongweipeng

…y cause exception

2021-12-17 14:40 UTC, sobolevn commented on Misc/NEWS.d/next/Library/2021-12-16-23-42-54.bpo-46103.LMnZAN.rst
> +Fix :func:`inspect.getmembers` will call the instance __bases__ attribute
nit

```suggestion
Fix :func:`inspect.getmembers` will call the instance ``__bases__`` attribute
```

2021-12-18 01:21 UTC, ethanfurman approved these changes
I'm fine with merging as-is, but would appreciate having the already-incorrect comment fixed.

2021-12-18 01:21 UTC, ethanfurman commented on Lib/inspect.py
> +        # :dd any DynamicClassAttributes to the list of names if object is a class;
Please also fix the `:dd` to `add`.  Thanks.  :-)

2021-12-19 09:13 UTC, kumaraditya303 requested changes

2021-12-19 09:13 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2021-12-16-23-42-54.bpo-46103.LMnZAN.rst
> +Fix :func:`inspect.getmembers` will call the instance ``__bases__`` attribute
```suggestion
Fix :func:`inspect.getmembers` will call the instance :attr:`__bases__` attribute
```

2021-12-24 08:16 UTC, hongweipeng commented
@ethanfurman I have made the requested changes; please review again.

2022-01-23 12:38 UTC, raghavthind2005 approved these changes

2022-01-23 17:36 UTC, ethanfurman approved these changes

2022-01-23 17:40 UTC, merged