bpo-43424: Deprecate `webbrowser.MacOSXOSAScript._name` attribute
python/cpython pull request #30241
Opened 2021-12-23 11:41 UTC by sobolevn

Changes:
- Now all `BaseBrowser` subtypes have the same interface
- I've also covered `name` in the docs, since original issue was about it

Looks like `MacOSXOSAScript` is not tested, so I didn't add any tests except local manual check:

```python
Python 3.11.0a3+ (heads/main-dirty:71ef0b4c2b, Dec 23 2021, 12:38:09) [Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import webbrowser
>>> a = webbrowser.get()
>>> a.name
'default'
>>> a._name
<stdin>:1: DeprecationWarning: MacOSXOSAScript._name is deprecated in 3.11 use MacOSXOSAScript.name instead.
'default'
>>> a.open('https://python.org')
True
```

2021-12-29 13:49 UTC, corona10 requested changes
https://github.com/python/cpython/blob/77195cd44b2506cda88a3cfc98918526068b1d46/Lib/test/test_webbrowser.py#L307

We can now remove this skip section with this change.

2021-12-29 16:59 UTC, sobolevn commented
@corona10 thank you! I've removed `AttributeError` from the list of allowed exceptions.
Because, I belive that `webbrowser.Error` can still happen on some platforms. 

To make bot happy:
I have made the requested changes; please review again.

2021-12-30 01:30 UTC, corona10 approved these changes

2021-12-30 01:30 UTC, merged

2021-12-30 08:35 UTC, sobolevn commented
@corona10 thank you! 👍