bpo-46186: replace `io.IncrementalNewlineDecoder` with non incremental newline decoders
python/cpython pull request #30276
Opened 2021-12-27 18:02 UTC by guoci

2022-02-05 19:29 UTC, MaxwellDupre reviewed
The issue had comments:
...can you give an example where it fails? Is it possible to write a unit test demonstrating that the current behaviour is wrong?
Can give more info please? I cant see a clear use case.

2022-02-05 19:31 UTC, guoci commented
The old code has an incorrect usage of `io.IncrementalNewlineDecoder`. Since the `decode` method is called only once, is it the final call and needs the `final=True` argument as documented in https://docs.python.org/dev/library/codecs.html#codecs.IncrementalDecoder.decode

It happens that in those cases, the results are correct in spite of the incorrect usage.

2025-10-31 22:50 UTC, brettcannon requested changes
I think the news entry can be a bit more descriptive, but otherwise LGTM!

2025-10-31 22:50 UTC, brettcannon commented on Misc/NEWS.d/next/Core_and_Builtins/2025-10-31-14-03-42.gh-issue-90344.gvZigO.rst
> +Replace :class:`io.IncrementalNewlineDecoder` with non incremental newline decoders in codebase.
```suggestion
Replace :class:`io.IncrementalNewlineDecoder` with non incremental newline decoders in codebase where :meth:`io.IncrementalNewlineDecoder.decode()` was being called once.
```

2025-10-31 23:07 UTC, guoci commented
I have made the requested changes; please review again

2025-10-31 23:12 UTC, brettcannon approved these changes

2025-11-07 15:03 UTC, guoci commented
The tests are failing due to the news item.
`/home/runner/work/cpython/cpython/Doc/build/NEWS:212: WARNING: py:meth reference target not found: io.IncrementalNewlineDecoder.decode [ref.meth]`

2025-11-14 19:14 UTC, guoci commented
@brettcannon is that ok now?

2025-11-14 23:46 UTC, brettcannon commented
> @brettcannon is that ok now?

Sorry, had a sick toddler the past week, so I haven't had time to look at your changes. But I'm going to look now.

2025-11-14 23:46 UTC, brettcannon approved these changes

2025-11-15 00:13 UTC, merged

2025-11-15 00:16 UTC, brettcannon commented
Thanks, @guoci !