bpo-22859: deprecating unittest.TestProgram.usageExit
python/cpython pull request #30293
Opened 2021-12-29 19:34 UTC by carlosdamazio

2022-01-24 04:46 UTC, JelleZijlstra requested changes
As mentioned on the PR, I would suggest making it raise DeprecationWarning first.

2022-01-29 12:51 UTC, carlosdamazio commented
@JelleZijlstra Done, `usageExit` is marked as being deprecated and will be removed in 3.13.

2022-01-29 13:19 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2021-12-29-19-37-49.bpo-22859.AixHW7.rst
> +`unittest.TestProgram.usageExit` is marked deprecated, to be removed in 3.13.
```suggestion
:meth:`~unittest.TestProgram.usageExit` is marked deprecated, to be removed in 3.13.
```

2022-01-29 13:19 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2021-12-29-19-37-49.bpo-22859.AixHW7.rst
> +`unittest.TestProgram.usageExit` is marked deprecated, to be removed in 3.13.
This will fix the docs CI.

2022-01-29 13:28 UTC, carlosdamazio commented
Thank you @kumaraditya303 for fixing the news entry.

2022-02-17 03:24 UTC, JelleZijlstra commented on Lib/unittest/main.py
> +                      " removed in 3.13", DeprecationWarning)
```suggestion
        warnings.warn("TestProgram.usageExit() is deprecated and will be"
                      " removed in Python 3.13", DeprecationWarning)
```

2022-03-16 11:23 UTC, kumaraditya303 approved these changes

2022-03-17 02:40 UTC, JelleZijlstra approved these changes

2022-03-17 02:41 UTC, merged