Allow filename mismatch in local and central directories in zipfile.py
python/cpython pull request #3035
Opened 2017-08-09 09:25 UTC by zyxtarmo

During malware research I bumped int problem with my Python based file analyzer: miscreants are modifying ZIP file header parts so, that python based automated analysis tools are unable to process the contents but intended clients are able to open the files with end-user applications and extract the possibly malicious contents. Proposed patch makes it possible to process the ZIP files even if such conditions occur. Default behavior remains the same (raise BadZipFile exception).

2017-08-09 09:25 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-01-30 06:49 UTC, gpshead commented
This looks useful and I have sympathy with people dissecting malware. A few things:

(1) Can you file an issue on https://bugs.python.org/ for this and rename the PR to bpo-NNNN: description so our automation picks up on that and associates the two?
(2) sync your branch and fix conflicts.
(3) add a NEWS entry per https://devguide.python.org/committing/#what-s-new-and-news-entries
(4) update Doc/library/zipfile.rst to document the new parameter.

2018-03-26 09:31 UTC, serhiy-storchaka requested changes
Please open an issue on the [bug tracker](https://bugs.python.org/) for discussion.

2019-05-19 01:20 UTC, csabella commented
@zyxtarmo, please address the previous code reviews from @gpshead and @serhiy-storchaka.  Thanks!

2020-01-13 22:53 UTC, csabella commented
I'm going to close this as there hasn't been any response to the code review.  It can reopened or a new pull request can be created to continue with the change.  Thank you!

2020-01-13 22:53 UTC, closed without merging