bpo-1635741: port _ctypes extension module to multiphase initialization
python/cpython pull request #30525
Opened 2022-01-11 03:54 UTC by kumaraditya303

2022-01-11 11:29 UTC, kumaraditya303 commented
cc @vstinner

2022-01-11 16:04 UTC, shihai1991 commented on Modules/_ctypes/_ctypes.c
> +    {Py_mod_exec, _ctypes_mod_exec},
I am just curious about those codes in `_ctypes_mod_exec`, do we need judge the attr manually?
```
_unpickle = PyObject_GetAttrString(mod, "_unpickle");
    if (_unpickle == NULL) {
        return -1;
    }
```

2022-01-11 16:37 UTC, vstinner requested changes
You should not convert an extension to the multi-phase init API until all static types defined by the extension are defined as heap types.

See _ctypes_add_types(): there are *many* types defined as static types. Just one example: PyCArg_Type.

2022-01-11 19:20 UTC, erlend-aasland commented
> You should not convert an extension to the multi-phase init API until all static types defined by the extension are defined as heap types.

True; but sadly, converting static types to heap types has been put on hold by the SC. The good news is that work is in progress to resolve the "deadlock", so we can continue applying PEP 489 and PEP 630 to the standard library 😃 

See [SC communications as of February 2021](https://github.com/python/steering-council/blob/1d85eefdc5861a096c3859e9990dbc8527c5973b/updates/2021-02-steering-council-update.md):

_"The Steering Council discussed the ongoing work on porting types in the standard library to heap-types and the subinterpreter-related changes. It was decided that through Pablo, the Steering Council will ask the core developers driving those changes to create an informational PEP and not to make any more changes in this area after beta 1, as per our general policy."_

2022-01-12 00:08 UTC, vstinner commented
> ask the core developers driving those changes to create an informational PEP

Eric is working on a PEP: https://github.com/python/peps/pull/2212

Not sure if it fulfill SC requirements to convert more static types to heap types.

2022-01-12 04:07 UTC, kumaraditya303 commented
IIUC converting static types to heap types is a different issue https://bugs.python.org/issue40077 which is not I am tackling in this PR, also itertools module also creates many static types but still uses multiphase initialization https://github.com/python/cpython/blob/be578e0c063dad1dbb273f86d5bc77e4e6f14583/Modules/itertoolsmodule.c#L4907 so how is _ctypes different ?

2022-01-12 06:33 UTC, erlend-aasland commented
It is subinterpreter related. Also, we first convert global state to module state, _then_ apply multi-phase init, as Victor already pointed out.

Some modules have been converted to multi-phase init prematurely. That does not alter the status quo, or set a precedent.

2022-01-13 14:35 UTC, corona10 commented
FYI, Please read https://github.com/vstinner/talks/blob/main/2021-PyconUS/subinterpreters.pdf how we've converted modules :)

2022-01-13 14:36 UTC, corona10 requested changes
Same as Victor

2022-01-14 11:17 UTC, closed without merging

2022-01-28 08:12 UTC, erlend-aasland commented
FYI: https://github.com/python/steering-council/issues/99

2022-06-27 13:24 UTC, erlend-aasland commented
FYI, PEP-687 was just [accepted](https://discuss.python.org/t/pep-687-isolating-modules-in-the-standard-library/14824/4?u=erlendaasland).