bpo-46353: Fix "pydoc -k" when a module fails to load
python/cpython pull request #30557
Opened 2022-01-12 13:04 UTC by dlax

The 'spec' value, here coming from pkgutil._get_spec(), may be None
because <importer>.find_module() may return None. We account for this in
pydoc's ModuleScanner and skip such modules scan.

2022-01-17 13:48 UTC, sobolevn reviewed
Thank you! Is there any good way to test this?

2022-01-17 14:50 UTC, dlax commented
> Is there any good way to test this?

That did not appear easy at first sight. That's typically something that a type checker would catch.
If a test is needed, I can have a second look though.

2022-02-26 11:36 UTC, MaxwellDupre requested changes
Could you add a test please?

2026-05-11 10:39 UTC, sobolevn commented
Feel free to reopen if we find a way to test this.

2026-05-11 10:39 UTC, closed without merging