bpo-46445: cover multiple inheritance of `TypedDict` in `test_typing`
python/cpython pull request #30719
Opened 2022-01-20 15:53 UTC by sobolevn

CC @corona10 as my mentor.

2022-01-20 15:55 UTC, sobolevn commented on Lib/test/test_typing.py
> -from typing import NewType
This is not related, but it was unused and I felt like there's no need to create a separate PR for this. If required, I can revert this change.

2022-01-21 00:52 UTC, JelleZijlstra requested changes

2022-01-21 00:52 UTC, JelleZijlstra commented on Lib/test/test_typing.py
> +        class ChildWithInlineAndOptional(Untotal, Inline):
Could you also test a case where the child has total=False but at least one of the parents doesn't? In that case only the parent's key should be required.

2022-01-21 18:19 UTC, JelleZijlstra approved these changes

2022-01-21 21:23 UTC, gvanrossum commented
Should I merge or wait?

2022-01-21 21:32 UTC, JelleZijlstra approved these changes

2022-01-21 21:32 UTC, JelleZijlstra commented
I think it's ready to merge.

2022-01-21 21:38 UTC, merged

2022-01-21 21:38 UTC, miss-islington commented
Thanks @sobolevn for the PR, and @gvanrossum for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖

2022-01-21 21:38 UTC, miss-islington commented
Sorry, @sobolevn and @gvanrossum, I could not cleanly backport this to `3.9` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 65b88d5e01c845c0cfa3ff61bc8b2faec8f67a57 3.9
                                ```