bpo-46425: fix direct invocation of `asyncio` tests
python/cpython pull request #30725
Opened 2022-01-20 18:24 UTC by sobolevn

Right now some tests in `test_asyncio` are suitable to be executed directly as `python Lib/test/test_asyncio/test_X.py` and some are only executable with `-m test` or `-m Lib/test/test_asyncio`.

- Supports all styles: https://github.com/python/cpython/blob/c02e860ee79f29905be6fca997c96bb1a404bb32/Lib/test/test_asyncio/test_asyncio_waitfor.py#L60-L61
- Does not support direct invocation: https://github.com/python/cpython/blob/c02e860ee79f29905be6fca997c96bb1a404bb32/Lib/test/test_asyncio/test_context.py#L33-L34

This does not look good to me.

So, I've fixed several tests modules in `test_asyncio` when invoked directly as `python module_name.py`

There were two major problems:
- relative imports
- missing `unittest.main()` call

The best way to illustrate this problem is to show `Lib/test/test_asyncio/test_runners.py`:

Step 1. No changes.

```
» ./python.exe Lib/test/test_asyncio/test_runners.py
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_asyncio/test_runners.py", line 5, in <module>
    from . import utils as test_utils
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: attempted relative import with no known parent package
```

Step 2. Fixed relative import.

```
» ./python.exe Lib/test/test_asyncio/test_runners.py

```

(nothing happens)

Step 3. With `unottest.main()`:

```
» ./python.exe Lib/test/test_asyncio/test_runners.py
........
----------------------------------------------------------------------
Ran 8 tests in 0.018s

OK

```

CC @corona10 as my mentor.

2022-01-21 00:53 UTC, JelleZijlstra approved these changes

2022-01-22 08:51 UTC, kumaraditya303 requested changes
Is there a reason that you run tests like scripts?

2022-01-22 09:33 UTC, sobolevn commented
> Is there a reason that you run tests like scripts?

I just click "Run file" in my IDE, it is the easiest thing to do when testing something.
And since it is supported by `if __name__ == '__main__': unittest.main()`, I think others might do the same / similar thing.

2022-01-22 11:05 UTC, asvetlov approved these changes
Historically `unittest.main()` was added on demand during unit tests debugging.
Thanks for spreading it everywhere.

2022-01-22 11:06 UTC, merged

2022-01-22 11:06 UTC, miss-islington commented
Thanks @sobolevn for the PR, and @asvetlov for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖