bpo-26669: Fix nan input error in pytime.c
python/cpython pull request #3085
Opened 2017-08-13 22:00 UTC by sn0wle0pard

* Make value error massage for nan value
Previously, did not show or show errors for different platforms.
* Add test case for nan value

2017-08-13 22:00 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-08-15 21:24 UTC, wkschwartz commented on Python/pytime.c
> +            PyErr_SetString(PyExc_ValueError, "Invalid Value");
Might be helpful for the error message specifically to mention that the value is NaN.

2017-08-29 21:31 UTC, pitrou commented
@haypo, do you have any comments about this?

2017-08-31 07:31 UTC, vstinner requested changes

2017-08-31 07:31 UTC, haypo commented on Lib/test/test_time.py
> +        self.assertRaises(ValueError, time.ctime, float("nan"))
Ok for "functional" tests", but I also would like to see unit tests on the following _testcapi functions:

* pytime_object_to_time_t
* pytime_object_to_timeval
* pytime_object_to_timespec
* PyTime_FromSeconds
* PyTime_FromSecondsObject
* PyTime_AsSecondsDouble

See CPyTimeTestCase in test_time.py.

2017-08-31 10:28 UTC, pitrou commented
Hmm... Did @warsaw [hack the bot](https://github.com/python/cpython/pull/3085#issuecomment-326214637)?

2017-09-04 17:44 UTC, haypo commented
@sn0wle0pard: Would you mind to add requested unit tests? Otherwise, I might try to modify your PR to add them myself?

2017-09-06 02:13 UTC, sn0wle0pard commented
@haypo I'll add test case as soon as possible.

2017-09-07 13:22 UTC, sn0wle0pard commented
@haypo I tested the following code in `_check_rounding`.
```python
# test nan
for time_rnd, _ in ROUNDING_MODES:
    with self.assertRaises(ValueError):
        pytime_converter(float('nan'), time_rnd)
``` 
Here are the results:
```
Python/pytime.c:116: _PyTime_DoubleToDenominator: Assertion `0.0 <= floatpart && floatpart < denominator' failed.
```
...so I tested one by one.
`pytime_object_to_time_t`: pass
`pytime_object_to_timeval`: error, pytime.c:116
`pytime_object_to_timespec`: error, pytime.c:116

`PyTime_FromSeconds`: error `TypeError: integer argument expected, got float` (does not pass time_rnd)
`PyTime_AsSecondsDouble`: error `PyTime_FromSecondsObject` (does not pass time_rnd)

And
`PyTime_FromSecondsObject`: does not raise error

`_PyTime_FromSecondsObject` call `_PyTime_FromObject` and `_PyTime_FromObject` has same logic at `_PyTime_ObjectToTime_t` (check float but do not check nan)
So I changed `_PyTime_FromObject`  and passed test for `_PyTime_FromSecondsObject`.

If the result is the same as expected, I will replace the passed test code with the changed `_PyTime_FromSecondsObject`..

2017-09-08 05:35 UTC, sn0wle0pard commented
pytime_object_to_timeval also has same error on macOS sierra

2017-09-08 06:22 UTC, sn0wle0pard commented
oh... in case NaN numerator is zero. i add some code for numerator zero. the it pass test case

2017-09-08 23:04 UTC, vstinner approved these changes

2017-09-08 23:05 UTC, haypo commented
Ok, it now LGTM!

2017-09-08 23:05 UTC, merged

2017-09-08 23:05 UTC, miss-islington commented
🐍🍒⛏🤖 Thanks @sn0wle0pard for the PR, and @haypo for merging it 🌮🎉.I'm working now to backport this PR to: 3.6.