bpo-46571: improve `typing.no_type_check` to skip foreign objects
python/cpython pull request #31042
Opened 2022-02-01 08:29 UTC by sobolevn

There are several changes:
1. We now don't explicitly check for any base / sub types, because new name check covers it
2. I've also checked that `no_type_check` do not modify foreign functions. It was the same as with `type`s
3. I've also covered `except TypeError` in `no_type_check` with a simple test case, it was not covered at all
4. I also felt like adding `lambda` test is a good idea: because `lambda` is a bit of both in class bodies: a function and an assignment

Are there any other cases we want to cover?

2022-02-01 21:37 UTC, AlexWaygood commented
Here's a slightly evil corner case that this doesn't account for:

If I have a module `test_typing.py`, like so:

```python
# test_typing.py
class A:
    class AA:
        foo: int
```

Then, observe the following behaviour:

```python
>>> from typing import get_type_hints, no_type_check
>>> import test_typing
>>> get_type_hints(test_typing.A.AA)
{'foo': <class 'int'>}
>>> @no_type_check
... class A:
...     AA = typing_test.A.AA
... 
...     
>>> get_type_hints(typing_test.A.AA)
{}
```

We might be able to get around this by looking at the `__module__` attribute.

2022-02-01 21:45 UTC, AlexWaygood commented on Lib/test/test_typing.py
> +            some.__no_type_check__
```suggestion
            some.__no_type_check__
            
        self.assertEqual(
            get_type_hints(some), 
            {'args': <class 'int'>, 'return': <class 'int'>}
        )
```

2022-02-02 02:19 UTC, JelleZijlstra requested changes

2022-02-02 02:19 UTC, JelleZijlstra commented on Lib/test/test_typing.py
> +            some_class = classmethod(some)
I don't know if we care, but it looks like `@no_type_check` wouldn't propagate to classmethods defined inside the class.

2022-02-02 02:19 UTC, JelleZijlstra commented on Lib/typing.py
> +            if (hasattr(obj, '__qualname__')
This isn't enough if the module is also different. (I think Alex brought that up already.)

2022-02-02 10:57 UTC, sobolevn commented
@AlexWaygood good one! Very evil! 

I've addressed this.

@JelleZijlstra I agree that we should also fix `classmethod` / `staticmethod` problem. Because we declare to support all methods, not just instance methods.

The problem is that `types.MethodType` does not support attribute assignment:

```python
>>> class Some:
...     @staticmethod
...     def st(x: int) -> int: ...
...     @classmethod
...     def cl(cls, y: int) -> int: ...

>>> Some.st.__no_type_check__ = True

>>> Some.cl.__no_type_check__ = True
AttributeError: 'method' object has no attribute '__no_type_check__'
```

Ideas?

Moreover, `@property` is also not supported:

```python
from typing import no_type_check

@no_type_check
class Some:
    @property
    def p(self, arg: int) -> int: ...

print(Some.p.__no_type_check__)
# AttributeError: 'property' object has no attribute '__no_type_check__'
```

But, I think that `@property` requires some more discussion.

2022-02-02 11:03 UTC, AlexWaygood commented
> @AlexWaygood good one! Very evil!
> 
> I've addressed this.

Doesn't look like you've pushed anything -- did you mean to? :)

2022-02-02 11:04 UTC, sobolevn commented
> Doesn't look like you've pushed anything -- did you mean to? :)

Not yet, I am still fighting `classmethod` 🙂

2022-02-02 11:07 UTC, sobolevn commented
Probably 

```python
if isinstance(obj, types.MethodType):
                obj.__func__.__no_type_check__ = True
```

is the way to go 🤔 

Will write some more tests to be sure.

2022-02-17 04:43 UTC, JelleZijlstra approved these changes
Looks good.

Do you think this should be backported? I'm leaning no as it's a behavior change and nobody directly complained about the old behavior (looks like you found it while reviewing typing test coverage).

2022-02-17 05:20 UTC, gvanrossum approved these changes
Agreed, a backport doesn't seem asked for.

2022-02-19 01:53 UTC, merged