Fix ElementTree.write XML prolog for encoding 'utf-8-sig'
python/cpython pull request #31043
Opened 2022-02-01 09:29 UTC by pepr

When ElementTree object is to be written to the file, and when BOM
is needed, the 'utf-8-sig' can be used for the purpose.
However, the XML prolog then looks like...

<?xml version='1.0' encoding='utf-8-sig'?>

... and that encoding in the prolog makes no sense. Therefore,
the utf-8-sig is changed to utf-8 for the purpose.

2022-02-01 09:29 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@pepr

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-02-01 09:44 UTC, pepr commented
Hello all,

To explain the problems with my login name. This is my first pull request related to cpython. I am using `pepr` as GitHub user name; however, I am using `prikryl` in Python bug tracker. The later one is older, and I had already posted 4 cases in the past. If anything else is needed for accepting the pull request, let me know, pleas.

The pull request is simple, and I have tried it on my local computer.

Have a nice day,
Petr

2022-02-02 16:27 UTC, corona10 requested changes
Please add the NEW.d for behavior changing

2022-02-02 20:08 UTC, pepr commented
@corona10: Sorry, I am new in this workflow. What does it mean the "add the NEW.d for behavior changing"? Is it expected from me?

2022-02-02 20:19 UTC, scoder commented
Thanks. You need to include a NEWS entry to describe the change.
https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python

Also, this needs a test. See the ElementTree tests under Lib/test/ There are already some that deal with encodings and the XML prologue.

2026-08-12 19:27 UTC, serhiy-storchaka approved these changes
Added tests and NEWS. Moved normalization so that the XML declaration is not written when xml_declaration is None (but BOM is). LGTM now.

2026-08-13 05:50 UTC, merged