bpo-46648: test_urllib2.test_issue16464() uses httpbin.org
python/cpython pull request #31146
Opened 2022-02-05 18:01 UTC by vstinner

The test_issue16464() test of test_urllib2 now uses
"http://httpbin.org/post" URL instead of "http://www.example.com/".

2022-02-05 18:02 UTC, vstinner commented
cc @corona10 @ambv

2022-02-05 19:35 UTC, tiran requested changes
Please use a different, more reliable service. The git repo and container image of the service hasn't been maintained in years.

2022-02-05 22:04 UTC, vstinner commented
> Please use a different, more reliable service. The git repo and container image of the service hasn't been maintained in years.

test_urllib2 is failing on all buildbots right now because example.com is no longer reliable. Do you have a better suggestion?

I'm not aware of any pythontest.net URL supporting POST.

Either we switch to any other URL or the test should be skipped. Most buildbots are failing.

2022-02-06 02:19 UTC, orsenthil commented
Hi @vstinner, I am with @tiran here. If possible m we should use pythontest . I think, it supports simple post.

If blocked by external resources, we can skip the test. BTW test_urllib2net is supposed to depend on external sources. The test_urllib2 should have mocks.

2022-02-06 14:09 UTC, closed without merging

2022-02-06 14:09 UTC, vstinner commented
I merged my PR #31161 instead (skip the test).