bpo-40479: Fix undefined behavior in Modules/_hashopenssl.c
python/cpython pull request #31153
Opened 2022-02-06 03:17 UTC by ZackerySpytz

va_end() must be called before returning.

2022-02-06 03:20 UTC, ZackerySpytz commented
This is a skip news PR.

The `va_start()` calls could be moved next to `PyErr_FormatV()`.

2022-02-06 09:54 UTC, tiran approved these changes
good catch!

2022-02-06 09:56 UTC, tiran requested changes
Please add a news entry. The problematic code is in releases 3.9.10 and 3.10.2.

2022-02-07 07:35 UTC, ZackerySpytz commented
I have made the requested changes; please review again.

2022-02-07 07:40 UTC, tiran approved these changes
Thank you!

2022-02-07 07:40 UTC, merged

2022-02-07 07:40 UTC, miss-islington commented
Thanks @ZackerySpytz for the PR 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖