shutil Lib enabling sendfile on solaris systems as it supports
python/cpython pull request #31165
Opened 2022-02-06 15:51 UTC by devnexen

copy between file descriptors.

2022-02-13 05:31 UTC, JelleZijlstra requested changes
How should this be tested?

From looking at test_shutil, it seems like it should run sendfile-based tests on Solaris automatically, but we don't run Solaris in normal CI. Perhaps we need to trigger the buildbots.

2022-02-13 05:31 UTC, JelleZijlstra commented on Lib/shutil.py
> +_USE_CP_SENDFILE = hasattr(os, "sendfile") and (sys.platform.startswith("linux") or sys.platform.startswith("sunos"))
```suggestion
_USE_CP_SENDFILE = hasattr(os, "sendfile") and sys.platform.startswith(("linux", "sunos"))
```

2022-02-13 05:31 UTC, JelleZijlstra commented on Misc/NEWS.d/next/Library/2022-02-06-15-53-30.bpo-46658.oRp0C-.rst
> +Enabling ``os.sendfile`` on shlib on Solaris based systems.
```suggestion
Enable use of :func:`os.sendfile` in :mod:`shutil` on Solaris.
```

2024-09-19 14:25 UTC, encukou commented
Closing in favour of #23893.

2024-09-19 14:25 UTC, closed without merging