[3.10] bpo-46433: _PyType_GetModuleByDef: handle static types in MRO (GH-30696)
python/cpython pull request #31262
Opened 2022-02-10 16:37 UTC by encukou

(cherry picked from commit 0ef08530124c5ca13a9394f4ac18bee8e6c66409)

https://bugs.python.org/issue46433

2022-02-10 17:11 UTC, vstinner approved these changes
LGTM.

There was just a minor change between while and for in the main branch, but with this change, 3.10 and main use "for", so it's better!

2022-02-10 23:04 UTC, erlend-aasland requested changes

2022-02-10 23:04 UTC, erlend-aasland commented on Objects/typeobject.c
>      Py_ssize_t i = 0;
You can remove this line, since the loop index is now inlined.

2022-02-10 23:18 UTC, vstinner commented on Objects/typeobject.c
>      Py_ssize_t i = 0;
Oh, I didn't see the warning: ``unused variable ‘i’ [-Wunused-variable]``.

2022-02-11 11:03 UTC, erlend-aasland approved these changes
Thanks, lgtm

2022-02-11 11:25 UTC, merged

2022-02-11 11:25 UTC, encukou commented
Thanks for the review!