[doc] Add a note in howto/logging.rst about "do not log to root logger in libraries"
python/cpython pull request #31271
Opened 2022-02-11 07:11 UTC by ppwwyyxx

Inside the `Configuring Logging for a Library` section, there is already a note here for library developers about "do not add handlers to library's loggers".
In similar spirit, I'm adding a note above it about "do not use root logger". This might sound obvious but I believe this antipattern happen more frequently than the existing note.

Please let me know if this looks reasonable. Thanks!

2022-02-11 07:11 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@ppwwyyxx

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-02-11 09:03 UTC, GBeauregard commented on Doc/howto/logging.rst
> +   name, such as `__name__`. This can avoid writing to the a logger that's used
Typo here "This can avoid writing to **the a** logger that's used"

2022-02-13 04:20 UTC, JelleZijlstra commented on Doc/howto/logging.rst
> +   name, such as `__name__`. This can avoid writing to the a logger that's used
```suggestion
   name, such as your library's ``__name__``. This can avoid writing to a logger that's used 
```

2022-02-13 22:16 UTC, ppwwyyxx commented
Addressed comments.

2022-02-13 22:25 UTC, JelleZijlstra approved these changes

2022-02-26 08:49 UTC, vsajip requested changes

2022-02-26 08:49 UTC, vsajip commented on Doc/howto/logging.rst
> +   identifiable name, such as your library's ``__name__``. This can avoid
change

> library's ``__name__``. This can avoid writing to a logger that's used by other libraries or the application,
   which will make it difficult for the application developer to configure
   handlers.

to

the ``__name__`` for your library's top-level package or module. Logging to the root logger will make it difficult or impossible for the application developer to configure the logging verbosity of your library as they wish.

2022-02-26 09:04 UTC, ppwwyyxx commented
Thanks, I have made the requested changes; please review again.

2022-02-26 09:54 UTC, vsajip approved these changes

2022-02-26 18:29 UTC, merged