replace `self` param with more appropriate `cls` in classmethods
python/cpython pull request #31402
Opened 2022-02-18 02:47 UTC by cmyui

No worries if this is nitpicky & denied, just noticed while reading through the code & thought I'd PR a fix.

named correctly in other places such as https://github.com/python/cpython/blob/main/Lib/_collections_abc.py#L622

2022-02-18 06:16 UTC, corona10 requested changes, later dismissed
Please add the news by using blurb
https://pypi.org/project/blurb/

2022-02-18 06:19 UTC, corona10 commented
And please sign up the CLA first :)

2022-02-19 20:50 UTC, serhiy-storchaka commented
No NEWS is need for such kind of changes.

Actually, it would be distracting, because the change does not have any user visible effect.

2022-02-19 20:57 UTC, serhiy-storchaka approved these changes

2022-02-20 12:29 UTC, asvetlov approved these changes

2022-02-20 12:30 UTC, asvetlov commented
Let's merge fast; the PR is ready.

2022-02-20 12:31 UTC, merged

2022-02-20 12:31 UTC, miss-islington commented
Thanks @cmyui for the PR, and @asvetlov for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖

2022-02-20 12:31 UTC, miss-islington commented
Sorry @cmyui and @asvetlov, I had trouble checking out the `3.10` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker a3fcca4af1cb418dc802feb75100ecc1a286afaa 3.10
                                ```