bpo-21761: Clarified __file__/__cached__ in import reference
python/cpython pull request #31565
Opened 2022-02-25 06:39 UTC by slateny

2022-02-28 16:30 UTC, Vidhyavinu reviewed
I feel "-the spec instructs the loader" can be started as a new sentence. Rest looks good. 
@ericsnowcurrently : are you ok with this?

2022-03-01 01:18 UTC, slateny commented
> I feel "-the spec instructs the loader" can be started as a new sentence. Rest looks good. @ericsnowcurrently : are you ok with this?

Separating the phrase into a new sentence felt a bit abrupt so I connected it to the previous sentence instead, but that's a preference thing and I'm open to changing it back if the others concur.

2022-03-04 17:38 UTC, ericsnowcurrently requested changes
Thanks for working on this, @slateny!  I've made some recommendations for you to consider.

Also, in [bpo-21761](https://bugs.python.org/issue21761#msg220578) I said, "The entire section should have a clear note that loaders are not meant to rely a module's import-related attributes."  This PR should include the addition of such a note.

2022-03-04 17:38 UTC, ericsnowcurrently commented on Doc/reference/import.rst
> +   appropriate.
I'd recommend reframing that a little, drop the reference to the import system, and reduce the churn.  Here's how I'd do it:

```rst
   set. However, that scenario is quite atypical. Ultimately, the
   loader is what makes use of the module spec provided by the finder
   (from which ``__file__`` and ``__cached__`` are derived).  So
   if a loader can load from a cached module but otherwise does not load
   from a file, that atypical scenario may be appropriate.
```

Here's the diff for that:

```diff
    set. However, that scenario is quite atypical. Ultimately, the
-   loader is what makes use of ``__file__`` and/or ``__cached__``. So
+   loader is what makes use of the module spec provided by the finder
+   (from which ``__file__`` and ``__cached__`` are derived).  So
    if a loader can load from a cached module but otherwise does not load
```

(Sorry if https://bugs.python.org/issue21761#msg407885 let you astray!)

2022-03-04 17:38 UTC, ericsnowcurrently commented on Doc/reference/import.rst
> +   appropriate.
FWIW, I recommend also updating the previous paragraph to have the same shift away from actively setting module attributes.  Something like this:

```rst
   If ``__file__`` is set then the ``__cached__`` attribute might also
   be set,  which is the path to any compiled version of
   the code (e.g. byte-compiled file). The file does not need to exist
   to set this attribute; the path can simply point to where the
   compiled file would exist (see :pep:`3147`).
```

the diff:

```diff
-   If ``__file__`` is set, it may also be appropriate to set the
-   ``__cached__`` attribute which is the path to any compiled version of
+   If ``__file__`` is set then the ``__cached__`` attribute might also
+   be set,  which is the path to any compiled version of
    the code (e.g. byte-compiled file). The file does not need to exist
```

2022-03-04 17:38 UTC, ericsnowcurrently commented on Doc/reference/import.rst
>     It is also appropriate to set ``__cached__`` when ``__file__`` is not
Let's slightly shift the wording away from actively setting the module attribute:

```suggestion
   Note that ``__cached__`` may be set even when ``__file__`` is not
```

2022-03-05 09:41 UTC, slateny commented on Doc/reference/import.rst
>     It is also appropriate to set ``__cached__`` when ``__file__`` is not
I've applied the change, though instead of saying 'even when' I made it 'even if' as the latter gives the impression of being less likely.

2022-03-05 09:43 UTC, slateny commented
I have made the requested changes; please review again

2022-04-26 18:55 UTC, brettcannon approved these changes

2022-04-26 19:12 UTC, miss-islington commented
@slateny: Status check is done, and it's a success ✅ .

2022-04-26 19:12 UTC, merged

2022-04-26 21:07 UTC, brettcannon commented
Thanks!