bpo-31203: Added constant socket.IP_PKTINFO
python/cpython pull request #3161
Opened 2017-08-20 16:31 UTC by AllesCoolAllesBestens

After this patch, `print(socket.IP_PKTINFO)` returns `8` as defined in http://elixir.free-electrons.com/linux/v4.12.8/source/include/uapi/linux/in.h#L96

2017-09-07 04:51 UTC, tiran commented
Your patch is missing a news entry. Please use the ``blurb`` tool to generate it, https://pypi.python.org/pypi/blurb

2017-09-07 04:52 UTC, tiran requested changes
blurb is missing.

2020-01-25 23:45 UTC, csabella commented
@AllesCoolAllesBestens, please take a look at the review request here and the comment on the bug tracker issue.  Thank you!

2020-04-11 00:42 UTC, alimcmaster1 commented
Looks like this is stale - @csabella are we good to close?

2020-05-23 15:53 UTC, csabella commented
@alimcmaster1, thanks for the ping.  Yes, I'm going to close this due to inactivity.  It can be reopened if the original author is interested in working on it or a new PR can be created to replace it.  If a new PR is created and uses the original change, please give credit to @AllesCoolAllesBestens in the pull request message.  Thanks!

2020-05-23 15:53 UTC, closed without merging