bpo-46889 Add compile flag for math support for sqlite3 on macos
python/cpython pull request #31635
Opened 2022-03-01 15:19 UTC by lyinch

Adds support for sqlite3 math functions on macos: https://bugs.python.org/issue46889

2022-03-01 20:25 UTC, ned-deily requested changes

2022-03-01 20:25 UTC, ned-deily commented on Mac/BuildScript/build-installer.py
> +                            '-DSQLITE_ENABLE_MATH_FUNCTIONS'
Please add a trailing space like in the previous lines in case we need to add another option in the future.

2022-03-01 21:19 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@lyinch

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-03-01 21:28 UTC, lyinch commented
Not sure if this is required but I didn't see a CI/CD pipeline for macos 12.1 aarch64 so I ran the tests offline:

```
== Tests result: SUCCESS ==

408 tests OK.

24 tests skipped:
    test_curses test_dbm_gnu test_devpoll test_epoll test_gdb
    test_ioctl test_msilib test_multiprocessing_fork test_ossaudiodev
    test_smtpnet test_socketserver test_spwd test_ssl test_startfile
    test_tix test_tk test_ttk_guionly test_urllib2net test_urllibnet
    test_winconsoleio test_winreg test_winsound test_xmlrpc_net
    test_zipfile64

Total duration: 2 min 37 sec
Tests result: SUCCESS
```

2022-03-01 21:36 UTC, ned-deily commented
Thanks for the test, but you do understand that this change will only affect the building of macOS installer packages like those released on python.org. Regular builds, including CI ones, use whatever libsqlite3 is available, by default the one provided by Apple in macOS or possibly one provided by a third-party distributor like MacPorts or Homebrew. In the meantime, we do need you to fill out the contributor agreement as noted above.

2022-03-02 17:20 UTC, ned-deily commented
See @erlend-aasland's comment on the bpo issue: this option is enabled by default on Unix builds and so the math functions are already present with current python.org macOS installers. But thanks for your contribution!

2022-03-02 17:20 UTC, closed without merging