bpo- 31245: Asyncio unix socket datagram
python/cpython pull request #3164
Opened 2017-08-21 14:11 UTC by ovv

2017-08-22 23:17 UTC, haypo commented on Lib/asyncio/unix_events.py
> +                    raise OSError(errno.EADDRINUSE, msg) from None
Please chain the exception.

2017-08-22 23:17 UTC, haypo commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop.assert_reader(7, tr._read_ready)
Please use self.sock_fd

2017-08-22 23:17 UTC, haypo commented on Lib/asyncio/selector_events.py
> +            return
Are you sure about the semantics? Can't you use send ("") as a cheap ping for example?

I suggest to remove this test.

2017-08-22 23:17 UTC, haypo commented on Lib/test/test_asyncio/test_selector_events.py
> +        self.loop._add_writer(7, transport._send_ready)
Again, use self.sock_fd

2017-08-22 23:17 UTC, haypo commented on Lib/test/test_asyncio/test_unix_events.py
> +                                        'Address.*is already in use'):
I would prefer to check the error code rather than the message.

2017-08-22 23:17 UTC, haypo commented on Misc/NEWS.d/next/Library/2017-08-22-11-05-35.bpo-31245.AniZuz.rst
> +Added `create_unix_datagram_connection` and `create_unix_datagram_server` to
Please mention asyncio. Maybe "asyncio: ...".

2017-08-23 11:41 UTC, ovv commented on Lib/asyncio/unix_events.py
> +                    raise OSError(errno.EADDRINUSE, msg) from None
This was made to improve the error message by including the address that failed the bind. I'm not sure chaining the exception will provide more information on the error.

2017-08-23 11:57 UTC, ovv commented on Lib/test/test_asyncio/test_unix_events.py
> +                                        'Address.*is already in use'):
I will check both. So we make sure the error message is also correctly rewritten

2017-08-23 13:20 UTC, ovv commented on Lib/asyncio/selector_events.py
> +            return
It seems to be working without the check. I wonder if it's also not necessary for the `SelectorDatagramTransport`

2017-08-24 01:15 UTC, njsmith commented on Lib/asyncio/selector_events.py
> +            return
That's correct – on a datagram socket, sending a packet with empty payload is totally legal, and is different from sending no packet at all.

2017-08-24 01:16 UTC, njsmith commented
This is a *ton* of new code (mostly copy/pasted?) for what's basically just... changing one constant. At the very least can't you share `DatagramProtocol` and most of the test code?

2017-08-24 01:26 UTC, 1st1 commented
> This is a ton of new code (mostly copy/pasted?) for what's basically just... changing one constant. At the very least can't you share DatagramProtocol and most of the test code?

+1. This should be refactored, and I wouldn't expect to see a patch that's longer than +- 50 lines of code.  Also, please don't merge without my final review.

2017-08-24 07:46 UTC, ovv commented
Thanks for the feedback. I'll try to refactor to shorten the patch.

Concerning the protocol I'm not sure on the direction to take. I could use the `DatagramProtocol`, but in my opinion it doesn't make much sense to pass the `addr` to `datagram_received` for a unix socket.

2017-08-24 14:30 UTC, ovv commented
Well it appears I had some misconception about how unix datagram socket works. 

I think this patch is much more reasonable. Sorry for the mess it was previously.

2017-10-19 17:46 UTC, 1st1 commented on Lib/asyncio/base_events.py
> +                        assert isinstance(addr, str)
Make it a proper exception -- `TypeError` in this case.

2017-10-19 17:47 UTC, 1st1 requested changes
Please resolve one remaining nit.  Otherwise LGTM

2017-10-30 09:14 UTC, ovv commented
I have made the requested changes; please review again

2017-10-30 09:54 UTC, asvetlov approved these changes

2017-10-30 13:42 UTC, 1st1 approved these changes

2017-10-30 13:43 UTC, merged

2017-10-30 13:43 UTC, 1st1 commented
Thanks!