bpo-46937: convert remaining functions to AC in _weakref
python/cpython pull request #31705
Opened 2022-03-06 08:51 UTC by kumaraditya303

2022-03-06 09:09 UTC, arhadthedev commented on Modules/_weakref.c
> +proxy when 'object' is about to be finalized."
```suggestion
proxy when 'object' is about to be finalized.
```

2022-03-06 15:45 UTC, corona10 requested changes

2022-03-06 15:45 UTC, corona10 commented on Modules/_weakref.c
> +    callback: object = None
```suggestion
    callback: object(c_default="NULL") = None
```

2022-03-07 08:00 UTC, kumaraditya303 commented
I have made the requested changes; please review again

2022-03-07 09:57 UTC, corona10 approved these changes

2022-03-07 09:57 UTC, merged