bpo-46933: Make pwd module optional
python/cpython pull request #31700
Opened 2022-03-05 20:58 UTC by tiran

2022-03-05 23:36 UTC, erlend-aasland commented
Hm, for some reason, `configure` now decides _not_ to build `pwd` on my Mac, thus breaking `posixpath.expanduser` for my username:

```bash
$ python3.11
Python 3.11.0a5 (v3.11.0a5:c4e4b91557, Feb  3 2022, 14:54:01) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import posixpath
>>> posixpath.expanduser("~erlendaasland")
'/Users/erlendaasland'
>>> ^D
$ ./python.exe                 
Python 3.11.0a5+ (heads/no-pwd-dirty:a6ca976941, Mar  6 2022, 00:31:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import posixpath
>>> posixpath.expanduser("~erlendaasland")
'~erlendaasland'
>>> ^D
```

`getpwuid` and `getpwuid_r` are both available, so I don't see why.

```bash
$ grep getpwuid config.cache
ac_cv_func_getpwuid=${ac_cv_func_getpwuid=yes}
ac_cv_func_getpwuid_r=${ac_cv_func_getpwuid_r=yes}
```

2022-03-05 23:40 UTC, erlend-aasland commented
Aaaah, I see it!

https://github.com/python/cpython/blob/6927632492cbad86a250aa006c1847e03b03e70b/configure.ac#L6465-L6466

https://github.com/python/cpython/blob/6927632492cbad86a250aa006c1847e03b03e70b/configure.ac#L6378

2022-03-05 23:52 UTC, erlend-aasland requested changes
We need to use `m4_foreach_w` (or `m4_map_args_w`) in `PY_STDLIB_MOD` and `PY_STDLIB_MOD_SIMPLE` when checking `py_stdlib_not_available` for unavailable modules. There may be a more elegant solution.

2022-03-06 11:39 UTC, tiran commented
> We need to use `m4_foreach_w` (or `m4_map_args_w`) in `PY_STDLIB_MOD` and `PY_STDLIB_MOD_SIMPLE` when checking `py_stdlib_not_available` for unavailable modules. There may be a more elegant solution.

I tried ``m4_set_add_all`` but it didn't work like I hoped. The m4 set functions seem to get evaluated during autoconf. We need to evaluate them when ``configure`` is running.

2022-03-06 13:12 UTC, erlend-aasland commented
> The m4 set functions seem to get evaluated during autoconf. We need to evaluate them when configure is running.

Yeah, I tried some experiments with the m4 wrappers yesterday, but they didn't work out.

2022-03-06 14:23 UTC, tiran commented
> Yeah, I tried some experiments with the m4 wrappers yesterday, but they didn't work out.

We may have to restructure the test. I have a working solution, will clean it up and push it later today.

2022-03-06 19:58 UTC, erlend-aasland approved these changes
Yep, this approach works swell. Tested on my mac; all good. I left some comments nits; do with them as you please :)

2022-03-06 19:58 UTC, erlend-aasland commented on configure.ac
> +dnl sets MODULE_$NAME based on $PY_STDLIB_MOD_SET_NA, ENABLED-TEST,
Comment nit. Something like this, or reword :)

```suggestion
dnl sets MODULE_$NAME based on PY_STDLIB_MOD_SET_NA(), ENABLED-TEST,
```

2022-03-06 19:58 UTC, erlend-aasland commented on configure.ac
> +dnl    n/a: $NAME in $PY_STDLIB_MOD_SET_NA (not available on platform)
More comment nit.

```suggestion
dnl    n/a: marked unavailable on platform by PY_STDLIB_MOD_SET_NA()
```

2022-03-06 19:58 UTC, erlend-aasland commented on configure.ac
> +dnl Always enable unless the module is listed in PY_STDLIB_MOD_SET_NA
```suggestion
dnl Always enable unless the module is disabled by PY_STDLIB_MOD_SET_NA
```

2022-03-07 12:36 UTC, merged