use FASTCALL calling convention in generator.throw
python/cpython pull request #31723
Opened 2022-03-07 11:01 UTC by kumaraditya303

2022-03-07 12:16 UTC, corona10 commented
@kumaraditya303 Can you provide the benchmark?

2022-03-07 12:20 UTC, kumaraditya303 commented
> @kumaraditya303 Can you provide the benchmark?

Yup, I'm working on a benchmark but my machine is not very stable, if you can come up with something that would be great.

2022-03-07 16:19 UTC, arhadthedev commented
If a vararg method looks like `throw(typ[,val[,tb]])`, can it be remolded as `throw(typ, val=None, tb=None)`?

2022-03-09 12:24 UTC, corona10 requested changes

2022-03-09 12:24 UTC, corona10 commented on Misc/NEWS.d/next/Core and Builtins/2022-03-08-10-50-42.bpo-46944.cnaIK3.rst
> +Speed up throwing exception in generator by 20%. Patch by Kumar Aditya.
```suggestion
Update .generator.throw to use FASTCALL calling convention Patch by Kumar Aditya.
```

Performance gains may be relative results depending on the environment. I prefer neutral comments.

2022-03-09 12:24 UTC, corona10 commented on Misc/NEWS.d/next/Core and Builtins/2022-03-08-10-50-42.bpo-46944.cnaIK3.rst
> +Speed up throwing exception in generator by 20%. Patch by Kumar Aditya.
Performance gains may be relative results depending on the environment. I prefer neutral comments.
```suggestion
Update :meth:`generator.throw` to use :const:`METH_FASTCALL calling convention  Patch by Kumar Aditya.
```

2022-03-11 11:22 UTC, kumaraditya303 commented
@markshannon I have added a news item, ready for your review. Thanks

2022-03-11 13:03 UTC, corona10 approved these changes

2022-03-11 14:36 UTC, markshannon commented
Looks good

2022-03-11 14:37 UTC, merged