Docstring: replace pysqlite with sqlite3
python/cpython pull request #31758
Opened 2022-03-08 10:11 UTC by erlend-aasland

Replace two instances of "pysqlite" with "sqlite3" in sqlite3 docstrings.
Also reword the same docstring with "does nothing" to "is a no-op" to align them with the docs.

2022-03-08 10:12 UTC, erlend-aasland commented
@JelleZijlstra: I believe this is one of the rare cases where _skip issue_ can be applied. Please shout out if you disagree.

2022-03-08 10:19 UTC, kumaraditya303 requested changes

2022-03-08 10:19 UTC, kumaraditya303 commented on Modules/_sqlite/cursor.c
> +Required by DB-API. Is a no-op in sqlite3.
```suggestion
Required by DB-API, is a no-op in sqlite3.
```

2022-03-08 10:19 UTC, kumaraditya303 commented on Modules/_sqlite/cursor.c
> +Required by DB-API. Is a no-op in sqlite3.
```suggestion
Required by DB-API, is a no-op in sqlite3.
```

2022-03-08 10:22 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +Required by DB-API. Is a no-op in sqlite3.
I'm not so sure about this. Using semi-colon would be more appropriate. Note also the OP:

_Also reword the same docstring with "does nothing" to "is a no-op" to align them with the docs._

The docs currently use a period, not a comma. If we expand this change, we should also change the docs. For now, I think keeping the period is fine.

2022-03-08 15:45 UTC, JelleZijlstra commented on Modules/_sqlite/cursor.c
> +Required by DB-API. Is a no-op in sqlite3.
Any reason not to keep the "Does nothing" wording? I think "does nothing" is slightly better because "no-op" is jargon.

2022-03-08 16:27 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +Required by DB-API. Is a no-op in sqlite3.
It was to align the docstrings with the docs. I'm fine with reverting that part of the PR.

2022-03-08 17:15 UTC, JelleZijlstra commented on Modules/_sqlite/cursor.c
> +Required by DB-API. Is a no-op in sqlite3.
OK, let's change it back to "does nothing" then. I don't think this is important enough to change everywhere, but it's better to stick to the more widely understood form.

2022-03-08 19:29 UTC, erlend-aasland commented on Modules/_sqlite/cursor.c
> +Required by DB-API. Is a no-op in sqlite3.
Do you mind if I align the docs with the docstrings in this PR? (Only for these two methods.)

2022-03-08 19:40 UTC, JelleZijlstra commented on Modules/_sqlite/cursor.c
> +Required by DB-API. Is a no-op in sqlite3.
Sure, let's do that

2022-03-08 19:45 UTC, erlend-aasland commented
We could backport this.

2022-03-08 19:58 UTC, JelleZijlstra approved these changes
Agree. @gvanrossum planning to merge this minor sqlite change

2022-03-08 20:08 UTC, gvanrossum approved these changes

2022-03-09 02:45 UTC, merged

2022-03-09 02:45 UTC, miss-islington commented
Thanks @erlend-aasland for the PR, and @JelleZijlstra for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖

2022-03-09 02:46 UTC, miss-islington commented
Sorry, @erlend-aasland and @JelleZijlstra, I could not cleanly backport this to `3.10` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker b33a1ae703338e09dc0af5fbfd8ffa01d3ff75da 3.10
                                ```

2022-03-09 02:46 UTC, miss-islington commented
Sorry @erlend-aasland and @JelleZijlstra, I had trouble checking out the `3.9` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker b33a1ae703338e09dc0af5fbfd8ffa01d3ff75da 3.9
                                ```

2022-03-09 02:47 UTC, JelleZijlstra commented
I'll backport