bpo-43923: Allow NamedTuple multiple inheritance
python/cpython pull request #31779
Opened 2022-03-09 04:16 UTC by juliusgeo

https://bugs.python.org/issue43923

This is a fix-forward PR (partial revert of [bpo-40185](https://bugs.python.org/issue40185)).

2022-03-10 02:29 UTC, JelleZijlstra requested changes
This looks like it's still mostly a revert, which I don't think is the right approach since it ends up losing a bunch of past improvements. Try to make the minimal change necessary to make things work.

2022-03-10 02:29 UTC, JelleZijlstra commented on Lib/typing.py
> +    nm_tpl = collections.namedtuple(name, [n for n, t in types])
`collections.namedtuple` now supports `default=` directly, so we should use that

2022-03-10 02:29 UTC, JelleZijlstra commented on Lib/typing.py
> +    msg = "NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type"
You're missing the improved error message from the existing code

2022-03-10 02:29 UTC, JelleZijlstra commented on Lib/typing.py
> +        nm_tpl._field_defaults = defaults_dict
No need to restore this old attribute

2022-03-10 16:31 UTC, JelleZijlstra commented
Note there's an alternative PR from Serhyi: #31781.

2022-03-10 16:42 UTC, AlexWaygood commented
> Note there's an alternative PR from Serhiy: #31781.

I still like Serhiy's more. In particular, I think it's best to keep `NamedTuple` a function, rather than a class. Given what inheriting from `NamedTuple` actually does (dynamically create a new _tuple_ subclass), I think it makes much more sense for it to be a function.

2022-10-06 00:13 UTC, JelleZijlstra commented
We merged #92027 to allow generic namedtuples. I don't think we want more general multiple inheritance. Thanks for your PR though!

2022-10-06 00:13 UTC, closed without merging