bpo-46841: Add a `_Py_SET_OPCODE` macro
python/cpython pull request #31780
Opened 2022-03-09 04:54 UTC by brandtbucher

Now that we don't modify opargs anymore, this is a cleaner (and slighly more efficient) way of performing this common move.

2022-03-09 05:22 UTC, sweeneyde commented on Include/cpython/code.h
> +#define _Py_SET_OPCODE(word, opcode) (((uint8_t *)&(word))[0] = (opcode))
Wouldn't this do the wrong thing on big-endian systems?

2022-03-09 05:49 UTC, sweeneyde commented on Include/cpython/code.h
> +#define _Py_SET_OPCODE(word, opcode) (((uint8_t *)&(word))[0] = (opcode))
My bad! I didn't see the ifdefs directly above.

2022-03-09 11:31 UTC, markshannon requested changes
The C compiler is allowed to assume that for `uint8_t *p1`, `_Py_CODEUNIT *p2`, `p1` and `p2` don't alias. If you add the special `char *` cast, then it cannot make that (in this case false) assumption.

2022-03-09 11:31 UTC, markshannon commented on Include/cpython/code.h
> +#define _Py_SET_OPCODE(word, opcode) (((uint8_t *)&(word))[0] = (opcode))
You'll need a `(char *)` in here to stop the compiler making a dubious aliasing decision.
`(((uint8_t *)((char *)word))[0] = (opcode))`

2022-03-09 11:31 UTC, markshannon commented
LGTM, apart from the missing cast.

2022-03-09 15:20 UTC, brandtbucher commented on Include/cpython/code.h
> +#define _Py_SET_OPCODE(word, opcode) (((uint8_t *)&(word))[0] = (opcode))
Interesting. I had assumed that `uint8_t` and `unsigned char` were completely equivalent on platforms where `CHAR_BIT` is `8`, but indeed it seems that’s not actually true.

Would just changing `uint8_t` to `unsigned char` here be sufficient? I find that a bit more readable than the proposed double-cast, if they're equivalent.

2022-03-09 15:35 UTC, markshannon commented on Include/cpython/code.h
> +#define _Py_SET_OPCODE(word, opcode) (((uint8_t *)&(word))[0] = (opcode))
I'm not sure, so unless you want to bury yourself in the C spec, let's play it safe and use the double cast.

2022-03-09 15:36 UTC, markshannon commented on Include/cpython/code.h
> +#define _Py_SET_OPCODE(word, opcode) (((uint8_t *)&(word))[0] = (opcode))
Feel free to add a comment for the benefit of those not aware of C's weird aliasing rules.

2022-03-12 00:07 UTC, brandtbucher commented on Include/cpython/code.h
> +#define _Py_SET_OPCODE(word, opcode) (((uint8_t *)&(word))[0] = (opcode))
Looks like `unsigned char *` is [indeed legal here](https://gist.github.com/jibsen/da6be27cde4d526ee564), so I'll use that. Thanks for catching this.

2022-03-12 00:31 UTC, merged