Fix codeop.compile_command docstring
python/cpython pull request #3179
Opened 2017-08-22 10:58 UTC by abenkovskii

codeop.compile_command actually accepts symbol="exec" too

2017-08-22 10:58 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-09-20 17:48 UTC, merwok commented
Hello!  I can’t review right now, but wanted to say you might get more attention by opening a new doc bug instead of recycling an old ticket that’s already closed.

2017-11-09 22:08 UTC, berkerpeksag requested changes
I agree with Éric. @abenkovskii could you please open a new issue? bpo-737999 was closed 14 years ago so it would be better to discuss your ptahc in a new issue.

Also, we don't need a NEWS entry for this.

2019-01-10 16:01 UTC, vstinner commented
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

2019-09-10 12:34 UTC, JulienPalard commented
@abenkovskii I agree with Berker, could you please open a new issue and remove the NEWS entry?

2019-11-20 01:57 UTC, csabella commented
Closing as there hasn't been any response to multiple requests for a bug report to be opened.  Please feel free to re-open this PR or create a new one to address the existing comments.  Thanks!

2019-11-20 01:57 UTC, closed without merging

2019-11-20 16:00 UTC, merwok commented
@csabella Would you mind creating a doc ticket for this?

2019-11-21 01:14 UTC, csabella commented
Created issue 38872.