gh-89928: Fix integer conversion of device numbers.
python/cpython pull request #31794
Opened 2022-03-10 14:51 UTC by serhiy-storchaka

Fix os.major(), os.minor() and os.makedev().
Support device numbers larger than 2**63-1.
Support non-existent device number (NODEV).

https://bugs.python.org/issue45767

* Issue: gh-89928

2022-11-27 19:29 UTC, iritkatriel requested changes, later dismissed
This has merge conflicts now.

2023-12-17 09:33 UTC, serhiy-storchaka commented
!buildbot freebsd

2023-12-17 10:18 UTC, serhiy-storchaka commented
I have made the requested changes; please review again.

2023-12-28 11:37 UTC, serhiy-storchaka commented
!buildbot bsd

2024-05-24 09:04 UTC, vstinner commented on Modules/posixmodule.c
> +#ifdef NODEV
Can you add a helper function to convert an "unsigned int" device number to a Python object? os.minor() uses the same code.

2024-05-24 09:04 UTC, vstinner commented on Misc/NEWS.d/next/Library/2022-03-10-16-47-57.bpo-45767.ywmyo1.rst
> +non-existent device number.
```suggestion
non-existent device number (`NODEV`).
```

2024-05-24 09:05 UTC, vstinner commented
I closed https://github.com/python/cpython/pull/113080 as a duplicate of this PR.

2024-05-24 12:04 UTC, vstinner approved these changes
LGTM. Thanks for the update.

2024-06-02 22:11 UTC, vstinner commented
@serhiy-storchaka: Do you want to merge this PR?

2024-06-03 11:23 UTC, serhiy-storchaka commented on Lib/test/test_posix.py
> +            NODEV = -1
I am going to expose `posix.NODEV`, but this is a different issue.

2024-06-04 16:36 UTC, merged

2024-06-04 17:10 UTC, vstinner commented
Thanks for the fix @serhiy-storchaka!

2025-09-02 02:19 UTC, kraj commented on Lib/test/test_posix.py
> +            NODEV = -1
FWIW, musl is another C library implementation on Linux ( like glibc ) which does not provide NODEV, so relying on platform to provide this definition may not be true always.