Document random module changes in 3.11 What's new
python/cpython pull request #31818
Opened 2022-03-11 13:19 UTC by hrnciar

2022-03-17 15:20 UTC, hugovk requested changes

2022-03-17 15:20 UTC, hugovk commented on Doc/whatsnew/3.11.rst
> +* The *population* parameter of :func: `random.sample` must be a sequence.
This should fix the docs build:

```suggestion
* The *population* parameter of :func:`random.sample` must be a sequence.
```

2022-03-17 16:04 UTC, serhiy-storchaka submitted a review, later dismissed
It is not a correct place for this note because it is not a new feature. From user's point of view it is a breaking change which can break a code that worked before (even if it issued deprecation warnings). It should be documented in sections "Porting to Python 3.11", subsection "Changes in the Python API" or in section "Removed" (different changes may be in different sections).

2022-03-24 13:19 UTC, vstinner commented
@serhiy-storchaka:
> It should be documented in sections "Porting to Python 3.11"

Done: @hrnciar moved the What's New entry to Porting to Python 3.11 > Changes in the Python API.

2022-03-24 13:22 UTC, serhiy-storchaka approved these changes

2022-03-24 13:22 UTC, merged

2022-03-24 13:46 UTC, vstinner reviewed
Post-merge review (@serhiy-storchaka was faster than me :-)): LGTM! This change properly describes https://bugs.python.org/issue40465 changes.

2022-03-24 14:03 UTC, serhiy-storchaka commented
BTW it was first time I used GitHub client for Android.