Improve some deprecations in the importlib
python/cpython pull request #32
Opened 2017-02-12 00:22 UTC by Carreau

Add the python version since the functionality is deprecated,
and raise a couple of deprecation warnings in a few places.

Theses functions are marked as deprecated in the documentation, but
especially in existing codebase, programmers tends to not re-check
whether functions are deprecated. So trigger the warning when possible.

It's also more probable that a developer will drop deprecated
functionality if we immediately give them information about
replacement API, and not have them to go find it in the documentation.

Include deprecation information in DocString as well, as many tools pull
documentation from there and not from docs.python.org.

2017-02-12 02:54 UTC, fgregg commented on Lib/importlib/abc.py
> +                      "3.4 in favor of MetaPatFinder.find_spec "
typo here s/MetaPatFinder/MetaPathFinder/

2017-02-12 19:46 UTC, Carreau commented on Lib/importlib/abc.py
> +                      "3.4 in favor of MetaPatFinder.find_spec "
Oops indeed, thanks.

2017-02-15 19:31 UTC, brettcannon requested changes
Could you add tests to make sure the warnings are being raised?

2017-02-15 19:31 UTC, brettcannon commented on Lib/importlib/abc.py
> +        Deprecated since Python 3.4 in favor of find_spec (available since 3.4)
This line is somewhat redundant since the deprecation is mentioned in the previous paragraph. Maybe just add the version it was deprecated in above?

2017-02-15 19:31 UTC, brettcannon commented on Lib/importlib/abc.py
> +        Deprecated since Python 3.4 in favor of find_spec (available since 3.4)
The deprecation is mentioned in the above paragraph, so if you would like to add the version info just toss in up there.

2017-02-15 19:31 UTC, brettcannon commented on Lib/importlib/abc.py
> +                      "3.4 in favor of MetaPathFinder.find_spec "
Please add `()` after `find_spec`.

2017-02-15 19:31 UTC, brettcannon commented on Lib/importlib/abc.py
> +                      "3.4 in favor of PathEntryFinder.find_spec "
Please add`()` as appropriate.

2017-02-15 22:45 UTC, Carreau commented
All comments should be addressed.

2017-02-15 23:23 UTC, brettcannon approved these changes

2017-02-15 23:25 UTC, brettcannon commented
Thanks! Please add entries in Misc/NEWS and one in What's New in the "deprecated" section and this will be ready to be merged!

2017-02-16 02:00 UTC, merged

2017-02-16 02:00 UTC, brettcannon commented
Thanks!

2017-02-16 02:05 UTC, Carreau commented
Thanks !