bpo-32642: add support for path-like objects in sys.path
python/cpython pull request #32118
Opened 2022-03-25 19:51 UTC by noamcohen97

The sys.path did only accept `str` or `bytes` object. This change
makes `os.PathLike` object to be accepted as well.

2022-03-25 19:51 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@noamcohen97

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-04-25 16:10 UTC, MaxwellDupre commented
Could you add a test please? The existing test doesn't exercise the code changes.

2022-07-19 18:47 UTC, graingert commented on Lib/test/test_importlib/test_pkg_import.py
> +        self.test_dir = pathlib.Path(tempfile.mkdtemp())
this removes the test for str on sys.path

2022-07-19 18:48 UTC, graingert requested changes

2022-07-19 18:48 UTC, graingert commented on Lib/importlib/_bootstrap_external.py
> +                # bytes, str and path-like objects will pass fspath
you need to add a test for bytes on `sys.path`, and test it with the other import systems. Note these tests fail with a BytesWarning

2022-07-19 18:49 UTC, graingert commented on Lib/importlib/_bootstrap_external.py
> +                # bytes, str and path-like objects will pass fspath
cc @brettcannon

2022-07-19 18:50 UTC, graingert commented
cc @jaraco re: https://github.com/python/importlib_metadata/issues/372

2022-07-19 19:51 UTC, graingert commented
@noamcohen97 the issue for this was closed - https://github.com/python/cpython/issues/76823#event-6892103552 you should raise the request for python-dev

2022-07-19 20:52 UTC, erlend-aasland commented
> @noamcohen97 the issue for this was closed - [#76823 (comment)] [...]

Suggesting then to close this PR.

2022-07-20 05:36 UTC, closed without merging