bpo-47129: Add more informative messages to f-string syntax errors
python/cpython pull request #32127
Opened 2022-03-26 15:09 UTC by macgors

2022-03-26 15:09 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@macgors

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


We also demand... [A SHRUBBERY!](https://www.youtube.com/watch?v=zIV4poUZAQo)


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-03-26 18:15 UTC, lysnikolaou approved these changes
Thanks @macgors for the PR. LGTM! Please sign the CLA, so we can merge it.

2022-03-26 18:49 UTC, macgors commented
> Thanks @macgors for the PR. LGTM! Please sign the CLA, so we can merge it.

Already signed it, waiting for it to be review/accepted, should come within 1 US business day.

2022-03-28 14:58 UTC, ericvsmith requested changes
Otherwise, this looks ready to merge. Thanks!

2022-03-28 14:58 UTC, ericvsmith commented on Parser/string_parser.c
> +        } else {
I know this is a nit, but could you remove the else clause, and move the next two statements out one level? When reviewing code it's more obvious that all code paths have the "return NULL" in them.

2022-03-28 17:35 UTC, macgors commented
No problem, @ericvsmith. I have made the requested changes; please review again.

2022-03-28 18:57 UTC, ericvsmith approved these changes

2022-03-28 19:24 UTC, lysnikolaou approved these changes

2022-03-28 21:08 UTC, merged