bpo-27929: resolve names only for AF_INET/AF_INET6 with asyncio
python/cpython pull request #32131
Opened 2022-03-26 18:17 UTC by vincentbernat

For other families, it may not make sense to resolve names. For
example, with AF_BLUETOOTH, there is no name resolution and attempting
to do so will trigger a "ai_family not supported".

The bug report contains an example:

```python
import asyncio
import socket
sock = socket.socket(family=socket.AF_BLUETOOTH,
                     type=socket.SOCK_STREAM,
                     proto=socket.BTPROTO_RFCOMM)
sock.setblocking(False)
addr = "00:12:34:56:78:99"
loop = asyncio.get_event_loop()
loop.run_until_complete(loop.sock_connect(sock, (addr, 1)))
```

https://bugs.python.org/issue27929

2022-03-26 18:17 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@vincentbernat

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-03-27 16:02 UTC, asvetlov requested changes
1. Please add NEWS entry (https://devguide.python.org/#quick-reference point 8)
2. Python can be compiled without IPv6 support, `socket.AF_INET6` is not available. Please use `base_events._HAS_IPv6`.

2022-03-28 19:40 UTC, asvetlov commented on Misc/NEWS.d/next/Library/2022-03-28-13-35-50.bpo-27929.j5mAmV.rst
> +like ``AF_BLUETOOTH`` and ``AF_UNIX``.
```suggestion
Fix :meth:`asyncio.loop.sock_connect` to only resolve names for :const:`socket.AF_INET` or
:const:`socketAF_INET6` families. Resolution may not make sense for other families,
like :const:`socket.AF_BLUETOOTH` and :const:`AF_UNIX`.
```

2022-03-28 21:49 UTC, asvetlov approved these changes

2022-03-28 21:50 UTC, merged

2022-03-28 21:50 UTC, miss-islington commented
Thanks @vincentbernat for the PR, and @asvetlov for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9, 3.10.
🐍🍒⛏🤖

2022-03-28 21:50 UTC, asvetlov commented
Thanks!