Fix ZeroMQSocketListener and ZeroMQSocketHandler examples
python/cpython pull request #3229
Opened 2017-08-28 18:43 UTC by pablogsal

This PR fixes two documentation issues regarding the `ZeroMQSocketListener` and `ZeroMQSocketHandler` examples in [the Logging Cookbook](https://docs.python.org/3/howto/logging-cookbook.html#subclassing-queuehandler-a-zeromq-example):

- The first issue is that in the '__init__' method for the 'ZeroMQSocketListener' the base class '__init__' is never called and therefore the internal variables are not correctly initialized. This leads to an empty 'handlers' attribute and a undefined 'queue' attribute.

- The second issue is that `zmq.Socket.send` and `zmq.Socket.setsockopt` only admits bytecode variables and therefore it fails in Python3 when using plain strings. The fix is to use `zmq.Socket.send_string`and `mq.Socket.setsockopt_string' instead.

2017-08-28 18:43 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-09-07 03:15 UTC, tiran requested changes
Thanks for your contribution, @pablogsal 

- [ ] Please add a News entry with the ``blurb`` tool
- [ ] Instead of ``json.dumps`` + ``send_string()``, how about ``send_json()`` instead? https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Socket.send_json

2017-09-07 19:50 UTC, pablogsal commented
I didn't expect the Spanish Inquisition!

2017-09-07 20:52 UTC, tiran approved these changes
Thanks, good work 🥇

2017-09-07 20:53 UTC, merged

2017-09-07 20:53 UTC, miss-islington commented
🐍🍒⛏🤖 Thanks @pablogsal for the PR, and @tiran for merging it 🌮🎉.I'm working now to backport this PR to: 3.6.