Remove white bar
python/cpython pull request #32363
Opened 2022-04-06 13:57 UTC by BA-24

I noticed there was a white bar to the left in my IDLE, it stuck out like a soar thumb since I have a custom dark theme. This was not an issue with earlier versions.

Changing this line of code solves this issue and leaves the color choices up to the user.

There's some jargon about pull requests that's supposed to go here but I don't think that's necessary since it's such a miniscule issue/change

2022-04-06 13:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@BA-24

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2022-04-11 00:11 UTC, terryjreedy requested changes
This only affects the shell sidebar, which is the subject of bpo-45451.

On my Windows with dark theme, I prefer the change.  But change needs evaluation on light and dark themes on all 3 major OSes.  Will ask OP of issue for opinion.

2022-04-11 00:11 UTC, terryjreedy commented on Lib/idlelib/sidebar.py
> +        self.canvas.grid(row=1, column=0, sticky=tk.NSEW, padx=0, pady=0)
Padding defaults to 0; remove defaulted options.
```suggestion
        self.canvas.grid(row=1, column=0, sticky=tk.NSEW)
```

2022-04-11 00:16 UTC, terryjreedy approved these changes

2022-04-11 00:28 UTC, terryjreedy commented
@ambv This should be linked to the new GH issue when available.  I overwrote the proposed change and will add blurb before merging.

2022-05-17 16:32 UTC, ambv commented
This missed the boat for inclusion in Python 3.9 which accepts security fixes only as of today.

2022-05-17 20:46 UTC, terryjreedy commented
I don't believe that this is needed for 3.9.  It is certainly more of an issue for 3.10+.

There is a new CI button that *requires* CLA be signed, even for something trivial that should not require it.  Adding a possibly false CLA signed label does not seem to fix that.  If no signature, any workaround other than making a new PR myself?

2022-05-18 05:02 UTC, BA-24 commented
> I don't believe that this is needed for 3.9. It is certainly more of an issue for 3.10+.
> 
> There is a new CI button that _requires_ CLA be signed, even for something trivial that should not require it. Adding a possibly false CLA signed label does not seem to fix that. If no signature, any workaround other than making a new PR myself?

This is my first issue I've created so I messed that part up. Upon realization, I signed the agreement but to the wrong account so I decided to just make a new issue on 

> 

That's my bad. I messed up the CLA thing, and, long story short, I ended up making a new identical issue on the bugs.python.org thing that can be found [here](https://bugs.python.org/issue47242)

2022-06-23 18:50 UTC, BA-24 commented
> 

Should be signed now

2022-10-31 22:30 UTC, BA-24 commented
Hey, just updated to 3.11, is this getting merged or will I have to keep modifying the file manually?

2022-11-25 11:23 UTC, iritkatriel commented
> Hey, just updated to 3.11, is this getting merged or will I have to keep modifying the file manually?

CI is failing because the news item is missing.

2022-11-25 15:12 UTC, terryjreedy commented
I am still planning to look at this soon.

2023-01-02 14:45 UTC, BA-24 commented
> > Hey, just updated to 3.11, is this getting merged or will I have to keep modifying the file manually?
> 
> CI is failing because the news item is missing.

As far as I'm concerned it's a typo and does not need a news entry.

2024-03-13 17:42 UTC, BA-24 commented
Hey, just updated to 3.12 and it seems this change still hasn't gone through. Updates?

2025-02-04 17:08 UTC, StanFromIreland commented
> I am still planning to look at this soon. (2022)

@terryjreedy Just a little reminder :) Is it possible for you to run all the actions (I do not have the permissions to do this) so we can see the current state of the PR?

2025-02-05 20:39 UTC, StanFromIreland approved these changes
@terryjreedy you asked for previews on major oss, here is Linux.

<details>
<summary>Classic</summary>

![image](https://github.com/user-attachments/assets/bb1c9456-0146-48f9-ac92-061aff4497f1)

</details>

<details>
<summary>Dark</summary>

![image](https://github.com/user-attachments/assets/59605a04-2d30-4356-8c54-2eff61d6ed1f)


</details>

2025-02-05 20:58 UTC, BA-24 commented
> @terryjreedy you asked for previews on major oss, here is Linux.

I think this looks great!

2026-09-15 16:53 UTC, merged