Fix bug in RobotFileParser().parse()
python/cpython pull request #3259
Opened 2017-09-01 09:39 UTC by gvx

The req_rate assigned to the new entry was a new namedtuple type,
rather than an instance of that type.

Credits to eesmith for finding this bug:
https://news.ycombinator.com/item?id=15136961

2017-09-01 09:39 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-09-01 16:21 UTC, rhettinger commented
See the comments on the tracker entry: http://bugs.python.org/issue31325

2017-09-11 02:45 UTC, rhettinger requested changes

2017-09-11 02:45 UTC, rhettinger commented on Lib/urllib/robotparser.py
> +
Please change from "req_rate" to "RequestRate", afterall this is a class.

2017-09-11 02:46 UTC, rhettinger commented
Add please add tests, a documentation patch, and a news blurb.

2017-11-09 00:38 UTC, berkerpeksag commented
@gvx do you have some time to address Raymond's comments at https://bugs.python.org/issue31325#msg301134 If not, I can do that this weekend.

2017-11-23 19:24 UTC, berkerpeksag commented
Superseded by PR #4529.

2017-11-23 19:24 UTC, closed without merging