bpo-29026: Clarify documentation of time.time
python/cpython pull request #34
Opened 2017-02-12 02:41 UTC by appeltel

Clarify the documentation of time.time by more
precisely defining what is meant by "seconds since
the epoch" on most platforms. Additionally explain
how gmtime and localtime may be used to extract
calendar components and convert to a more common
date format.

@haypo 

https://bugs.python.org/issue29026

2017-02-12 09:40 UTC, vstinner approved these changes

2017-02-12 09:42 UTC, haypo commented
Thank you for the new doc. It contains more info on timezone (UTC) and leap seconds (excluded).

2017-02-13 10:13 UTC, vstinner requested changes
Sorry, I saw a few more minor issues.

2017-02-13 10:13 UTC, haypo commented on Doc/library/time.rst
> +   `Unix time <https://en.wikipedia.org/wiki/Unix_time>`_.
IMHO it's worth it to repeat here:

To find out what the epoch is on a given platform, look at ``gmtime(0)``.

2017-02-13 10:13 UTC, haypo commented on Doc/library/time.rst
> +   Return the time in seconds since the epoch as a floating point
You should add a link on the "epoch" word to its definition.

2017-02-13 10:19 UTC, berkerpeksag commented on Doc/library/time.rst
> +  To find out what the epoch is on a given platform, look at ``gmtime(0)``.
I assume `gmtime(0)` is `time.gmtime(0)` here. If I'm correct, we can use this as an opportunity to make it clearer.

2017-02-13 10:19 UTC, berkerpeksag commented on Doc/library/time.rst
> +  `leap seconds <https://en.wikipedia.org/wiki/Leap_second>`_.
I'd say add

```rst
.. `leap seconds`: https://en.wikipedia.org/wiki/Leap_second
```

and use 

```rst
`leap-seconds`_
```

everytime you need the Wikipedia article.

(I might the syntax got wrong so please try first :))

2017-02-14 03:00 UTC, appeltel commented on Doc/library/time.rst
> +   Return the time in seconds since the epoch as a floating point
Added link in d387bf7

2017-02-14 03:00 UTC, appeltel commented on Doc/library/time.rst
> +   `Unix time <https://en.wikipedia.org/wiki/Unix_time>`_.
Repeated in d387bf7

2017-02-14 03:02 UTC, appeltel commented on Doc/library/time.rst
> +  To find out what the epoch is on a given platform, look at ``gmtime(0)``.
I changed it to `time.gmtime(0)` where it first appears in d387bf7. However, when the statement is repeated in the documentation of `time.time`, I retain `gmtime(0)` as this appears to be the convention used in all the function docs for the module.

2017-02-14 03:02 UTC, appeltel commented on Doc/library/time.rst
> +  `leap seconds <https://en.wikipedia.org/wiki/Leap_second>`_.
Added in d387bf7, also changed one other mention of leap seconds to link.

2017-02-14 04:19 UTC, appeltel commented on Doc/library/time.rst
> +  `leap seconds <https://en.wikipedia.org/wiki/Leap_second>`_.
Whoops, failed to add to amended commit before push - added that other mention in 263a4f4

2017-02-14 04:20 UTC, appeltel commented on Doc/library/time.rst
> +  To find out what the epoch is on a given platform, look at ``gmtime(0)``.
Oops, failed to amend commit before pushing, I fixed to use doc conventions in 263a4f4

2017-02-16 02:57 UTC, methane approved these changes

2017-02-16 10:00 UTC, vstinner approved these changes

2017-02-16 10:00 UTC, merged

2017-02-16 10:01 UTC, haypo commented
Thanks! I merged the PR.