Inside docker container from non root user raises KeyError
python/cpython pull request #3403
Opened 2017-09-06 23:43 UTC by Cinerar

When i try to run youtube-dl inside docker container from non root user i recieve this error:

failed to import the site module traceback (most recent call last): file "/usr/lib/python3.6/site.py", line 544, in main() file "/usr/lib/python3.6/site.py", line 530, in main known_paths = addusersitepackages(known_paths) file "/usr/lib/python3.6/site.py", line 282, in addusersitepackages user_site = getusersitepackages() file "/usr/lib/python3.6/site.py", line 258, in getusersitepackages user_base = getuserbase() # this will also set user_base file "/usr/lib/python3.6/site.py", line 248, in getuserbase user_base = get_config_var('userbase') file "/usr/lib/python3.6/sysconfig.py", line 601, in get_config_var return get_config_vars().get(name) file "/usr/lib/python3.6/sysconfig.py", line 558, in get_config_vars _config_vars['userbase'] = _getuserbase() file "/usr/lib/python3.6/sysconfig.py", line 205, in _getuserbase return joinuser("~", ".local") file "/usr/lib/python3.6/sysconfig.py", line 184, in joinuser return os.path.expanduser(os.path.join(*args)) file "/usr/lib/python3.6/posixpath.py", line 247, in expanduser userhome = pwd.getpwuid(os.getuid()).pw_dir keyerror: 'getpwuid(): uid not found: 1000'

I believe this problem is described here:
http://blog.dscpl.com.au/2015/12/unknown-user-when-running-docker.html

this simple fix make it work again

2017-09-06 23:43 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-09-16 00:39 UTC, merwok commented
Hello!  Could you search at https://bugs.python.org/ to make sure this is not already a known bug?

2018-12-04 15:44 UTC, gaborbernat commented
Is this ready for merge then?

2018-12-05 10:38 UTC, asvetlov requested changes
I believe a test for new functionality and news record is required.
Mentioning in docs the added feature is also makes sense

2018-12-05 12:59 UTC, vstinner commented
I wrote PR #10919 which has much more comments, more tests and a NEWS entry. I close this PR.

Thanks @Cinerar for your contribution!

2018-12-05 12:59 UTC, closed without merging