Updates PCBuild/readme.txt
python/cpython pull request #3418
Opened 2017-09-07 03:32 UTC by zooba

Updates the PCBuild/readme.txt file for simpler install steps and new info.

2017-09-07 04:24 UTC, zware requested changes
Two minor things, otherwise looks good.

2017-09-07 04:24 UTC, zware commented on PCbuild/readme.txt
> +_sqlite3
This is listed below.

2017-09-07 04:24 UTC, zware commented on PCbuild/readme.txt
> -Microsoft Visual C++ 2015 (MSVC 14.0) of any edition.  The specific
There's another mention of VS2015 on line 4.

2017-09-07 16:44 UTC, zooba commented
I didn't expect the Spanish Inquisition!

2017-09-08 03:10 UTC, merged

2017-09-08 03:30 UTC, zware commented
I forgot to look at this again earlier, but the changes do look good.