bpo-31307: Allow use of bytes object as a single argument in ConfigParser.read
python/cpython pull request #3420
Opened 2017-09-07 12:06 UTC by vxgmichel

Fix issue [bpo-31307](http://bugs.python.org/issue31307) and [bpo-29627](http://bugs.python.org/issue29627).

2017-09-16 00:55 UTC, merwok approved these changes

2017-10-31 06:41 UTC, berkerpeksag requested changes

2017-10-31 06:41 UTC, berkerpeksag commented on Lib/test/test_configparser.py
> +        # check when passing an existing bytestring path
`test_read_returns_file_list` is already too long, could you move it a separate test case?

2017-10-31 06:41 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2017-09-07-12-50-28.bpo-31307.AVBiNY.rst
> +Allow use of bytes objects for arguments to configparser.ConfigParser.read.
Please add "Patch by Vincent Michel.".

2017-10-31 06:41 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2017-09-07-12-50-28.bpo-31307.AVBiNY.rst
> +Allow use of bytes objects for arguments to configparser.ConfigParser.read.
:meth:\`configparser.ConfigParser.read\`

2017-11-02 12:43 UTC, vxgmichel commented
@berkerpeksag Thanks for the review. I have made the requested changes; please review again.

2017-11-02 12:44 UTC, berkerpeksag approved these changes

2017-11-02 12:47 UTC, merged

2017-11-02 12:47 UTC, berkerpeksag commented
Thanks!

2017-11-02 17:32 UTC, ambv commented
Thanks! ✨ 🍰 ✨