Fix socket leaks
python/cpython pull request #351
Opened 2017-02-27 21:11 UTC by J0l-lnny

The close method moved to finally block, so closing a socket will occur even in case of exception

2017-02-27 21:11 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/23276970/d14a380c-f9d1-11e6-883d-e13b6b211239.png)
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/). The "bugs.python.org username " requested by the form is the "Login name" field under "Your Details".
4. If you just signed the CLA, please **wait at least one US business day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-28 19:06 UTC, J0l-lnny commented
I'm signed the CLA

2017-03-02 10:42 UTC, vstinner reviewed
"with conn:" cannot be used?

2017-03-02 10:44 UTC, haypo commented
Oh, ignore my comment, I missed the Python version (2.7): in Python 2.7, socket.socket doesn't support the context manager protocol :-(

2017-03-02 10:49 UTC, vstinner requested changes
retrbinary(), retrlines() and storelines() at least have the same bug, no? Can you please fix similar bugs in other functions?

2017-03-02 17:43 UTC, J0l-lnny commented
Ok, I did

2017-03-02 17:50 UTC, vstinner approved these changes

2017-03-04 15:07 UTC, Mariatta commented
Should there be an issue in the bug tracker for this?

Also, I'm applying the `cherry-pick for 2.7`  label here to make it more obvious that this is for 2.7 branch :)

2017-04-02 13:23 UTC, serhiy-storchaka commented on Lib/ftplib.py
> +                fp.close()
Can `fp.close()` fail? If yes, `conn` will be not closed.

2017-04-02 13:23 UTC, serhiy-storchaka commented
You can use `contextlib.closing()`.

2017-04-03 09:41 UTC, haypo commented on Lib/ftplib.py
> +                fp.close()
The file is in read mode, I don't see why fp.close() would fail.

2017-04-03 09:54 UTC, vstinner reviewed
LGTM, but I prefer to wait for @serhiy-storchaka for retrlines().

2017-04-03 09:54 UTC, haypo commented on Lib/ftplib.py
> +                fp.close()
An alternative is to use two try/finally: conn and then fp. It would avoid "fp = None" as well. Do you think that it's worth it @serhiy-storchaka ?

2017-04-03 09:58 UTC, serhiy-storchaka commented on Lib/ftplib.py
> +                fp.close()
`KeyboardInterrupt` ;-)

2017-04-03 10:21 UTC, serhiy-storchaka approved these changes
LGTM. I think we can ignore very small issue in `retrlines()` in 2.7. I just remembered of alternatives for the case if you missed them.

2017-04-03 11:06 UTC, merged

2017-04-03 11:06 UTC, haypo commented
Thank you @J0l-lnny for your fix! I merged your PR.

2017-04-03 11:14 UTC, haypo commented
@serhiy-storchaka: "LGTM. I think we can ignore very small issue in retrlines() in 2.7."

Right, thank you for your review. If someone wants to handle the most complex corner cases, I suggest to focus on the master branch. Right now, the master branch uses a "nested" with which isn't ideal since it doesn't handle exceptions in creating fp fails (or is interrupted by CTRL+c or whatever):

Extract of ftplib.py in the master branch:

```
    def retrlines(self, cmd, callback = None):
        ...
        with self.transfercmd(cmd) as conn, \
                 conn.makefile('r', encoding=self.encoding) as fp:
        ...
```

At least, it ensures that conn and fp are closed properly, right?

2017-04-03 15:52 UTC, serhiy-storchaka commented
What is wrong with a nested with? The resources management in the master branch looks correct to me.

2017-04-03 15:58 UTC, haypo commented
> What is wrong with a nested with? The resources management in the master branch looks correct to me.

If makefile() raises an exception, conn is not closed. Well, in fact I'm not sure, that's why I was asking :-)

2017-04-03 16:06 UTC, serhiy-storchaka commented
It is properly closed.

```
with a, b:
        ...
```
is just a syntax sugar for
```
with a:
    with b:
        ...
```
You perhaps missed with deprecated and removed
```
with contextlib.nested(a, b):
        ...
```

2017-04-03 16:17 UTC, haypo commented
> (...) is just a syntax sugar for "with a: with b: ..."

Ok! master is fine in that case ;-) Thanks for the confirmation.

Note: By "nested", I really mean "with expr1 as a, expr2 as b: ...".