bpo-9303: Migrate sqlite3 module to _v2 API to enhance performance
python/cpython pull request #359
Opened 2017-02-28 20:39 UTC by palaviv

Use the _v2 API when possible.

2017-02-28 21:46 UTC, berkerpeksag reviewed
I think we can also avoid calling `sqlite3_reset` in `_pysqlite_seterror` if the v2 API is available.

2017-02-28 21:50 UTC, berkerpeksag commented
I haven't checked yet, but I also think that the check for `SQLITE_SCHEMA` can also be eliminated if the v2 API is available: https://github.com/python/cpython/blob/c92e6047bde01bcb846ad1fcf4126d3001e30f4b/Modules/_sqlite/cursor.c#L553

2017-02-28 22:11 UTC, berkerpeksag commented on Modules/_sqlite/connection.c
> +                         SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, NULL);
Style nitpick: `FOO|BAR` is more common than `FOO | BAR` in sqlite3 code base.

2017-02-28 22:14 UTC, berkerpeksag commented on Modules/_sqlite/connection.c
> +    rc = sqlite3_open_v2(database, &self->db,
I think that there is an opportunity to simplify this whole `SQLITE_OPEN_URI` and `HAVE_SQLITE3_OPEN_V2` dance.

2017-03-01 19:41 UTC, palaviv commented
> I think we can also avoid calling sqlite3_reset in _pysqlite_seterror if the v2 API is available.
done

> I haven't checked yet, but I also think that the check for SQLITE_SCHEMA can also be eliminated if the v2 API is available: https://github.com/python/cpython/blob/c92e6047bde01bcb846ad1fcf4126d3001e30f4b/Modules/_sqlite/cursor.c#L553

I don't think we should do this because we can get `SQLITE_SCHEMA` if `SQLITE_MAX_SCHEMA_RETRY` tries to recompile will pass.

2017-03-02 11:36 UTC, berkerpeksag reviewed
This looks pretty good to me. We just need an entry in `Misc/NEWS` (please add "Patch by Aviv Palivoda." too)

2017-03-02 11:36 UTC, berkerpeksag commented on Modules/_sqlite/util.c
> +
Nitpick: Please remove extra empty line.

2017-03-02 11:36 UTC, berkerpeksag commented on Modules/_sqlite/connection.c
> +       same as sqlite3_open_v2(filename, db, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, NULL)*/
Nitpick: `FOO|BAR` syntax instead of `FOO | BAR`.

Also, finish the line with a full stop and space:

```c
/* [...] NULL). */
```

2017-03-02 12:08 UTC, berkerpeksag commented
> I don't think we should do this because we can get SQLITE_SCHEMA if SQLITE_MAX_SCHEMA_RETRY tries to recompile will pass.

Right, we can still get `SQLITE_SCHEMA` from `sqlite3_step()` (in legacy API we need to call `sqlite3_reset()` to get it), but in this case `rc` is the return value of `sqlite3_reset()`. The latter call is not needed when we have the new API since `sqlite3_step()` calls `sqlite3_reset()` for us.

2017-03-02 18:51 UTC, palaviv commented on Modules/_sqlite/connection.c
> +       same as sqlite3_open_v2(filename, db, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, NULL)*/
done

2017-03-02 18:51 UTC, palaviv commented on Modules/_sqlite/util.c
> +
done

2017-03-02 18:52 UTC, palaviv commented
I have removed the reset but I left the recompile because we should recompile before calling sqlite3_step again.

2017-03-02 18:58 UTC, serhiy-storchaka approved these changes

2017-03-02 22:17 UTC, berkerpeksag commented on Modules/_sqlite/util.c
> +#if SQLITE_VERSION_NUMBER >= 3003009
Shouldn't `>=` be `<` here?

2017-03-03 07:04 UTC, serhiy-storchaka commented on Modules/_sqlite/util.c
> +#if SQLITE_VERSION_NUMBER >= 3003009
Good catch!

2017-03-03 07:05 UTC, serhiy-storchaka requested changes
Fix an error found by @berkerpeksag.

2017-03-03 08:14 UTC, palaviv commented on Modules/_sqlite/util.c
> +#if SQLITE_VERSION_NUMBER >= 3003009
Fixed

2017-03-03 10:32 UTC, berkerpeksag approved these changes
Thanks, Aviv! I will wait for Serhiy's approval and merge this.

2017-03-03 10:38 UTC, serhiy-storchaka approved these changes

2017-03-03 10:58 UTC, merged