bpo-31465: allow _PyType_Lookup() to raise exceptions
python/cpython pull request #3616
Opened 2017-09-16 11:55 UTC by scoder

This is based off #3279, the first commits are the same, because they touch the same code. FIrst new commit is 6c61028, right after the merge of "master". 6c61028 is a related bug fix, an unchecked error case.

Probably needs new tests that exercise the error conditions.

2018-07-29 11:41 UTC, markshannon commented
Two minor points.
I would prefer a new function, rather than modifying the signature of `_PyType_Lookup`.
Also, I think it is the conventional to return error codes directly and objects via the pointer, not the other way around. So `int _PyType_Lookup(type, name, *result)` not `PyObject *_PyType_Lookup(type, name, *error)`

2018-07-29 11:58 UTC, scoder commented
Sounds good to me. Will change it when I get to it, unless it proves controversial in the meantime.

2022-02-24 20:26 UTC, MaxwellDupre reviewed
Too many test fails:
`Test suite interrupted by signal SIGINT.

4 tests omitted:
    test_multiprocessing_fork test_multiprocessing_forkserver
    test_multiprocessing_spawn test_poplib

376 tests OK.

16 tests failed:
    test_asyncio test_dbm test_float test_ftplib test_httplib
    test_idle test_imaplib test_logging test_nntplib test_ossaudiodev
    test_shutil test_ssl test_tk test_ttk_guionly
    test_urllib2_localnet test_xmlrpc_net

9 tests skipped:
    test_devpoll test_kqueue test_msilib test_nis test_startfile
    test_winconsoleio test_winreg test_winsound test_zipfile64

Total duration: 13 min 49 sec
Tests result: FAILURE`
cpython on  _pt_lookup_exc [$?] via 🐍 v3.11.0a3+ took 13m48s 

Also, in typeobject.c line 739 shows:
`/* FIXME: unclear if we must update the slots even on errors or not */`

Need to have this cleared up before accepting PR. Get consensus from core dev(s).

2022-05-01 07:01 UTC, rhettinger approved these changes

2022-11-25 11:12 UTC, iritkatriel requested changes
This has merge conflicts now.

2023-05-11 15:05 UTC, furkanonder commented
@scoder Could you resolve the conflicts?

2026-02-13 09:40 UTC, encukou commented
I don't think it's worth it to keep this open; the codebase has diverged too much; .

If we agree on the design -- (see the issue), I'd be happy to redo the change.

2026-02-13 09:40 UTC, closed without merging