bpo-31351: Fix RC 0 in ensurepip when pip fails
python/cpython pull request #3626
Opened 2017-09-17 12:14 UTC by iafilatov

ensurepip discards pip's return code which leads to broken venvs. Make sure EC is propagated to that scripts that run ensurepip in a separate process (e.g. `python -m ensurepip`) can detect failure.
https://bugs.python.org/issue31351

I decided to keep the return value of the public version of `bootstrap()` unmodified although I'm not sure it's correct because it leaves no way to check if pip has succeeded or not (and I doubt there's a lot of code that relies on `bootstrap()` returning `None`).

2017-09-17 12:14 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-09-21 00:33 UTC, ncoghlan requested changes
This looks good to me. Just one additional change needed, which is to mention the command line return value with a corresponding `.. versionchanged: 3.7.0` note in https://docs.python.org/3/library/ensurepip.html#command-line-interface

2017-09-21 00:35 UTC, ncoghlan commented
As far as the return value of `ensurepip.bootstrap()` goes, I agree it makes sense to pursue the command-line-only fix first, and then consider changing the Python API in a follow-up patch (since we may decide we want to indicate bootstrap errors with an exception instead of a return value)

2017-09-21 08:49 UTC, iafilatov commented
I didn't expect the Spanish Inquisition!

2017-09-21 10:06 UTC, ncoghlan approved these changes

2017-09-21 10:07 UTC, merged

2017-09-21 10:07 UTC, miss-islington commented
Thanks @iafilatov for the PR, and @ncoghlan for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6.
🐍🍒⛏🤖

2017-09-24 13:49 UTC, miss-islington commented
Thanks @iafilatov for the PR, and @ncoghlan for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7.
🐍🍒⛏🤖

2017-09-24 13:50 UTC, miss-islington commented
Sorry, @iafilatov and @ncoghlan, I could not cleanly backport this to `2.7` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker 9adda0cdf89432386b7a04444a6199b580d287a1 2.7
                            ```