Update stdtypes.rst
python/cpython pull request #3642
Opened 2017-09-18 09:10 UTC by kgashok

Added behaviour of `find` when `substring` is `""`.

!!! If this is a backport PR (PR made against branches other than `master`),
please ensure that the PR title is in the following format:

[X.Y] <title from the original PR> GH-NNNN

Where: [X.Y] is the branch name, for example [3.6]

GH-NNNN refers to the PR number from `master`.

PLEASE: Remove this headline!!!

2017-09-21 15:11 UTC, raulcd commented
Hi @kgashok ,

Build is failing as this is not true:
```$ python3.6
Python 3.6.2 (default, Aug 23 2017, 13:37:24) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 'abc'.find('')
0
```

2017-09-21 15:16 UTC, tiran requested changes
Thanks for your contribution.

Your PR has multiple issues:

* Title of the ticket is not recognized by our bot. You need to add a colon after the bpo number: ``bpo-31504: Update stdtypes.rst``
* Doc tests are failing. You added extra line.
* As @raulcd already pointed out, the patch is wrong.

2017-09-21 16:05 UTC, merwok commented on Doc/library/stdtypes.rst
> +      a value that is equal to ``len(str)``.
I think the text should explain why.  As shows in the bpo-24243 ticket, people may be surprised by this behaviour if they don’t understand how it derives from Python’s notion of string slices.  If you know that `'' in 'abc'` is true + the doc of str.find says it returns the highest index of the found substring, then this is not a surprise.  I am not sure that mentioning `len` only here will help people make sense of it.

2017-09-21 16:06 UTC, merwok commented on Doc/library/stdtypes.rst
> +      a value that is equal to ``len(str)``.
Notation note: let’s write code like `len(s)`, not `len(str)`.

2018-03-26 15:02 UTC, serhiy-storchaka commented
Closed because tests failed, the added claim is not true, and the author is not active for a half of year.

2018-03-26 15:02 UTC, closed without merging