bpo-29688: Document Path.absolute
python/cpython pull request #384
Opened 2017-03-01 17:38 UTC by DimitrisJim

2017-03-01 18:10 UTC, marco-buttu requested changes
LGTM. You should just make the code markup on `'.'` (\`\`'.'\`\`) and `'..'` (\`\`'..'\`\`), as in the rest of the doc.

2017-03-01 18:57 UTC, DimitrisJim commented
Good catch, changed it. Thanks, Marco!

2017-03-01 19:04 UTC, marco-buttu approved these changes

2017-03-01 19:07 UTC, brettcannon requested changes

2017-03-01 19:07 UTC, brettcannon commented on Doc/library/pathlib.rst
> +   Return an absolute version of this path.  This function works
Maybe rephrase as "Return an absolute version of this path based on the current working directory"?

2017-03-01 19:07 UTC, brettcannon commented on Doc/library/pathlib.rst
> +   even if the path doesn't point to anything.
"even if the path doesn't exist".

2017-03-01 19:07 UTC, brettcannon commented on Doc/library/pathlib.rst
> +   No normalization is done, i.e all '.' and '..' will be kept along.
"will be kept along" -> "will not be normalized".

2017-03-01 19:25 UTC, DimitrisJim commented
Thanks @brettcannon, made the changes you requested.

2017-03-01 19:34 UTC, marco-buttu reviewed
Much better than the method docstring :-) Thanks @brettcannon :-)

2017-03-01 19:57 UTC, brettcannon approved these changes

2017-03-01 19:58 UTC, brettcannon commented
Thanks! When I have time to also do the cherry-pick PRs I will merge.

2017-03-02 17:46 UTC, vstinner requested changes

2017-03-02 17:46 UTC, haypo commented on Doc/library/pathlib.rst
> +   directory.  This function works even if the path doesn't exist.
This function => This method

I dislike "works even if", maybe: "This method doesn't check if the path exists." ?

2017-03-02 17:46 UTC, haypo commented on Doc/library/pathlib.rst
> +   Return an absolute version of this path based on the current working
Hum, maybe specify that only relative paths are resolved using the current working directory?

Return an absolute version of this path. Relative paths are resolved using the current working directory.

2017-03-03 10:55 UTC, berkerpeksag reviewed
Note that the `absolute` method is barely tested in `test_pathlib`. https://github.com/python/cpython/blob/master/Lib/test/test_pathlib.py#L1343 is the only place it's indirectly tested.

There is also the following comment in its implementation:

```py
# FIXME this must defer to the specific flavour (and, under Windows,
# use nt._getfullpathname())
```

https://github.com/python/cpython/blob/master/Lib/pathlib.py#L1096

2017-03-03 11:14 UTC, haypo commented
Oh wow, these comments are scary. I would feel more confortable with a change adding more tests and removing "# FIXME this must defer to the specific flavour (and, under Windows, use nt._getfullpathname())" comment.

2017-03-03 20:24 UTC, brettcannon commented
That would help explain why it isn't documented. 😉 

@DimitrisJim are you up for writing some tests for the function?

2017-03-03 21:04 UTC, DimitrisJim commented
I'd rather leave the testing for someone more aware of the intricacies of paths for different OS's.  Should we close the PR and rename the issue on b.p.o to something like "pathlib.absolute needs tests and documentation"?

2017-03-03 21:16 UTC, closed without merging

2017-03-03 21:16 UTC, brettcannon commented
Sure, we can close this for now and re-open if we decide to not deprecate Path.absolute(). Thanks for the PR regardless of whether it gets merged.