bpo-31728: Prevent crashes in _elementtree due to unsafe cleanup of Element.text and Element.tail
python/cpython pull request #3924
Opened 2017-10-08 21:09 UTC by orenmn

In addition, add tests to `test_xml_etree_c` to verify that the crashes are no more.

2017-10-09 21:55 UTC, serhiy-storchaka requested changes

2017-10-09 21:55 UTC, serhiy-storchaka commented on Modules/_elementtree.c
> +    _clear_joined_ptr(&self->text);
Setting `self->text` to NULL is not safe. In this case the "text" getter will return NULL without setting an exception.

2017-10-09 21:55 UTC, serhiy-storchaka commented on Lib/test/test_xml_etree_c.py
> +                elem.clear()
Getting elem.text or elem.tail before calling elem.clear() will crash.

2017-10-10 08:55 UTC, orenmn commented
In the end of `element_init()`, there are 8 lines that can be replaced by 2 calls to `_set_joined_ptr()`. I wasn't sure whether this would be an improvement or a code churn, so i didn't change it.

I didn't expect the Spanish Inquisition!

2017-10-10 09:49 UTC, serhiy-storchaka reviewed
I think this would be an improvement if use the new helper in `element_init()`, `_elementtree_Element___copy___impl()`, `_elementtree_Element___deepcopy___impl()`.

It may be worth to move `Py_INCREF()` out of `_set_joined_ptr()`. This will help in `_elementtree_Element___deepcopy___impl()` and will allow to implement `_clear_joined_ptr(p)` as `_set_joined_ptr(p, NULL)`.

2017-10-10 09:49 UTC, serhiy-storchaka commented on Modules/_elementtree.c
> +static void _set_joined_ptr(PyObject **p, PyObject *new_joined_ptr)
Move `static void` on a separate line. Or better even use `LOCAL(void)` or `Py_LOCAL_INLINE(void)`.

2017-10-10 17:08 UTC, serhiy-storchaka approved these changes

2017-10-10 17:08 UTC, serhiy-storchaka commented on Modules/_elementtree.c
>      Py_INCREF(JOIN_OBJ(element->text));
The new reference should be incremented before decrementing the old reference.

In this particular case the order doesn't matter since the old reference is None, and decrementing it can't trigger executing a user code. But for unifying the code I would move the incrementation above `_set_joined_ptr()`.

2017-10-10 17:08 UTC, serhiy-storchaka commented on Modules/_elementtree.c
> +    new_val = text ? JOIN_SET(text, PyList_CheckExact(text)) : Py_None;
You can reuse the `text` variable for the new value. The old value no longer used.

2017-10-10 17:47 UTC, serhiy-storchaka approved these changes

2017-10-10 18:49 UTC, serhiy-storchaka commented
And the last comment. The NEWS.d entry should be in the "Library" section.

2017-10-10 20:26 UTC, merged

2017-10-10 20:26 UTC, miss-islington commented
Thanks @orenmn for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6.
🐍🍒⛏🤖

2017-10-10 20:26 UTC, miss-islington commented
@orenmn and @serhiy-storchaka, Something is wrong... I can't backport for now.
                               Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                               ```
                               cherry_picker 39ecb9c71b6e55d8a61a710d0144231bd88f9ada 3.6
                               ```

2017-10-10 20:27 UTC, serhiy-storchaka commented
Thank you @orenmn! Do you mind to make backports?

2017-10-10 20:27 UTC, miss-islington commented
@orenmn and @serhiy-storchaka, Something is wrong... I can't backport for now.
                               Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                               ```
                               cherry_picker 39ecb9c71b6e55d8a61a710d0144231bd88f9ada 2.7
                               ```

2017-10-10 21:01 UTC, miss-islington commented
Thanks @orenmn for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2017-10-10 21:02 UTC, miss-islington commented
Sorry, @orenmn and @serhiy-storchaka, I could not cleanly backport this to `2.7` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker 39ecb9c71b6e55d8a61a710d0144231bd88f9ada 2.7
                            ```

2017-10-11 08:48 UTC, orenmn commented
(i am working on a backport to 2.7)