Don't require the Python org to mention someone
python/cpython pull request #393
Opened 2017-03-02 13:03 UTC by dstufft

**NOTE:** We may want to instead deploy our own bot that is a member of the Python org and has https://github.com/facebook/mention-bot/pull/212 added.

Previously we configured the mention-bot to only mention people who are members of the Python organization. However, this doesn't currently work if members don't have their membership public. Instead we will configure mention-bot to poke anyone, even non-members.

2017-03-02 13:11 UTC, berkerpeksag commented
Or we could ask them to make their membership status public :) There is already a public list of core developers so I don't think there is a privacy concern here.

2017-03-02 13:12 UTC, dstufft commented
Yea. This just seemed easier than tracking down 88 people and bugging them to fiddle with their Github settings.

2017-03-02 13:13 UTC, berkerpeksag commented
We could just send an email to python-committers list.

2017-03-02 13:15 UTC, dstufft commented
Ah yes, that's true!

2017-03-02 15:37 UTC, alex commented
I think this is also a good idea, because it encourages "sometimes contributors" to get more actively involved.

2017-03-02 15:40 UTC, dstufft commented
Yea, I've been going back and forth on it. For the time being at least I think we should try this out and see how it works. If we decide we really want to limit it, then we should probably at a minimum run our own bot to sidestep the private member issue completely.

2017-03-02 17:41 UTC, vstinner requested changes
Hum, the workflow is moving too fast. I just noticed a new "mention-bot" bot. Can you please give us time to experiment the new feature, before make it more noisy? (ex: test current config during 1 week)

2017-03-02 17:42 UTC, haypo commented
Even if I asked to wait, I concur with Alex "because it encourages "sometimes contributors" to get more actively involved." :-)

2017-03-02 18:28 UTC, dstufft commented
Yea. The main reason I made this PR was because currently mention-bot is ignoring anyone who doesn't have their Python membership as public.

Sent from my iPhone

> On Mar 2, 2017, at 12:42 PM, Victor Stinner <notifications@github.com> wrote:
> 
> Even if I asked to wait, I concur with Alex "because it encourages "sometimes contributors" to get more actively involved." :-)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-03-02 19:06 UTC, brettcannon commented
I agree with @dstufft that requiring the Python org _right now_ is not necessary as the vast majority of code is only from core devs due to the code's history. Eventually we will want to add back in the check when we have more code with proper attribution from git, but that will probably take years before it's a real issue.

2017-03-02 19:11 UTC, brettcannon commented
And in terms of the mention bot, this is an experiment that might be turned off. Basically this was the last "maybe/maybe not" idea that was on the table before the team review of the workflow and where things sit, so trying it for a week now seemed like the best idea prior to asking python-committers what is or is not working. (Plus turning off the bot is simple.)

2017-03-02 19:11 UTC, brettcannon approved these changes

2017-03-02 20:49 UTC, dstufft commented
I'm not sure the specific procedures here now. It seems @haypo has -1'd this PR, but not for the specific content of the PR just about the idea of tweaking it right now or not. Should I merge this or wait?

2017-03-02 22:38 UTC, brettcannon commented
@dstufft I actually don't know what @haypo wants because he said " the workflow is moving too fast" but then said "I concur with Alex".

Since the bot is on and not going away today, I say go ahead and merge since no one, including Victor, seems to think the tweak is bad for the bot itself.

2017-03-02 22:47 UTC, merged

2017-03-02 22:47 UTC, dstufft commented
Done!

2017-03-03 11:25 UTC, haypo commented
@brettcannon: "@dstufft I actually don't know what @haypo wants"

I fear that mention-bot will start spamming people who don't want to get notified by all these new CPython PR. We should help these people to unsubscribed or be blacklisted. Maybe write an email to python-dev to announce mention-bot and explain how to unsubscribe? At least, you already partially did that on the python-committers list, thank you for that!

In the meanwhile, the quick & hard way to work around spam is to mute the whole cpython project.

2017-03-03 11:26 UTC, dstufft commented
Or block the mention-bot too: https://github.com/mention-bot/how-to-unsubscribe, although adding to the black list is better.