Refactor/minor changes on Fractions
python/cpython pull request #3941
Opened 2017-10-10 11:10 UTC by sandordargo

2017-10-10 11:10 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-10-10 11:14 UTC, sandordargo commented
Signed CLA. Let's wait a day.

2017-10-12 15:00 UTC, sandordargo commented
How can I ask for a rerun of the CLA check plus add some labels?

2017-11-07 00:22 UTC, vstinner requested changes
This PR is mostly made on coding style changes, and usually we don't accept PR only changing the coding style. Moreover, I dislike the main change of this PR.

2017-11-07 00:22 UTC, haypo commented on Lib/fractions.py
> +        return bound2 if abs(bound2 - self) <= abs(bound1-self) else bound1
I prefer to write the code on multiple lines, IMHO it's more readable.

2017-11-07 00:22 UTC, haypo commented
@vadmium, @serhiy-storchaka, @berkerpeksag: I propose to reject this PR, what do you think?

2017-11-07 00:23 UTC, haypo commented
> How can I ask for a rerun of the CLA check plus add some labels?

I fixed the CLA label by removing the old red "CLA not signed" label: a new green "CLA signed" came automatically ;-)

2017-11-07 08:35 UTC, berkerpeksag commented
I agree with Victor. Thank you for opening a PR to improve Python, bu we usually prefer to avoid doing style-only changes in the codebase.

2017-11-07 08:53 UTC, serhiy-storchaka commented
I concur.

2017-11-07 08:53 UTC, closed without merging