bpo-31748: configure Werror
python/cpython pull request #3949
Opened 2017-10-11 08:44 UTC by tiran

Support configure with -Wall by avoiding unused variables, e.g.
(void)var.

Signed-off-by: Christian Heimes <christian@python.org>

2017-10-11 08:52 UTC, tiran commented
Patch is WIP, still fails to compile because AC_REPLACE_FUNC is broken:

```
gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Werror -Wall -Wextra   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration   -I. -I./Include    -DPy_BUILD_CORE -o Python/strdup.o Python/strdup.c
In file included from /usr/include/string.h:634:0,
                 from ./Include/Python.h:30,
                 from ./Include/pgenheaders.h:10,
                 from Python/strdup.c:3:
Python/strdup.c:6:1: error: expected identifier or ‘(’ before ‘__extension__’
 strdup(const char *str)
 ^

```

2017-10-11 09:26 UTC, haypo commented
While your PR fixes configure.ac for fchdir, fsync and fdatasync, there are still at least 39 compiler errors caused by -Werror -Wall. I started to write a list of them, but the list is too long :-)

2017-10-11 09:28 UTC, vstinner reviewed
LGTM, but please make sure to mention "-Werror -Wall" in the final commit message (once you click on [Merge]).

We can fix further compiler errors of configure in new PRs. This PR is already big enough :-)

2018-09-06 08:05 UTC, taleinat commented
Ping, @tiran.

2019-05-21 03:51 UTC, auvipy requested changes
plz rebase

2019-09-12 19:49 UTC, closed without merging