bpo-31758: Prevent crashes when using an uninitialized _elementtree.XMLParser object
python/cpython pull request #3997
Opened 2017-10-14 19:42 UTC by orenmn

In addition, add tests to `test_xml_etree_c` to make sure that the crashes are no more.

2019-06-02 10:47 UTC, auvipy requested changes
re base needed

2020-04-12 14:14 UTC, scoder commented on Lib/test/test_xml_etree_c.py
> +            parser.target
```suggestion
        self.assertIsNone(parser.entity)
        self.assertIsNone(parser.target)
```

2020-04-12 14:36 UTC, merged

2020-04-12 14:36 UTC, miss-islington commented
Thanks @orenmn for the PR, and @scoder for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2020-04-12 15:20 UTC, miss-islington commented
Thanks @orenmn for the PR, and @scoder for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2020-04-12 16:10 UTC, miss-islington commented
Thanks @orenmn for the PR, and @scoder for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖