bpo-31756: subprocess.run should alias universal_newlines to text
python/cpython pull request #4049
Opened 2017-10-19 10:50 UTC by andyclegg

Adds text=False as a keyword-only argument to subprocess.Popen.
Introduces a Popen attribute text_mode and sets this based on
encoding/errors/universal_newlines/text arguments.

2017-10-20 20:49 UTC, gpshead requested changes

2017-10-20 20:49 UTC, gpshead commented on Doc/library/subprocess.rst
> +      Added *text* parameter, as alias of *universal_newlines*
Added the *text* parameter, as a more understandable alias of *universal_newlines*.

2017-10-20 20:49 UTC, gpshead commented on Lib/subprocess.py
> +                 pass_fds=(), *, encoding=None, errors=None, text=False):
Change the defaults for `universal_newlines` and `text` from `False` to `None`.

and in the code below, raise an error when both are supplied but disagree:

```python
if (text is not None and universal_newlines is not None
    and bool(universal_newlines) != bool(text)):
    raise SubprocessError('Cannot disambiguate when both text '
                          'and universal_newlines are supplied but different. '
                          'Pass one or the other.')
```

2017-10-20 20:49 UTC, gpshead commented on Lib/subprocess.py
> -        self.universal_newlines = universal_newlines
The `universal_newlines` instance attribute is part of the public API of the class (even though not documented).

We should keep the name around.  Even if it is turned into a property with a setter and getter that ultimately sets/returns the value of the new `self.text_mode` attribute.

2017-10-20 20:49 UTC, gpshead commented on Lib/subprocess.py
> +        bytes or, if self.universal_newlines/self.text was True, a string.
self.text_mode?

2017-10-21 22:31 UTC, andyclegg commented
Thanks for your feedback. I've made the changes you suggested, and had another go at the documentation for Popen/run/communicate to make it a bit more consistent.

I have made the requested changes; please review again.

2017-10-23 01:57 UTC, gpshead approved these changes

2017-10-23 02:01 UTC, merged

2017-10-23 02:02 UTC, gpshead commented
thanks for this, `universal_newlines` has been an ugly wart of a name in the API for a long long time. :)