bpo-31821: allow pause_reading() from connection_made()
python/cpython pull request #4053
Opened 2017-10-19 18:53 UTC by pitrou

2017-10-19 19:07 UTC, 1st1 commented
Hm.  We'll need to run tests from the uvloop (has more functional tests) project with this patch.

2017-10-19 19:09 UTC, 1st1 commented
But I like the change.  Let me think about it for a few days.

2017-10-19 19:19 UTC, pitrou commented
No pb!

2017-12-21 18:09 UTC, pitrou commented
@1st1 any update here?

2017-12-21 18:19 UTC, asvetlov commented on Lib/asyncio/selector_events.py
> +        def _call_connection_made():
Convert nested function into instance method maybe?

2017-12-21 18:20 UTC, asvetlov commented
I like the PR but the came approach should be added to all transports (SSL and pipes) IMHO.

2019-01-10 16:01 UTC, vstinner commented
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

2022-12-10 09:27 UTC, kumaraditya303 requested changes
There are merge conflicts.

2023-04-18 11:08 UTC, kumaraditya303 commented
Closing as there are merge conflicts.

2023-04-18 11:08 UTC, closed without merging