bpo-31854: Added mmap.ACCESS_DEFAULT to namespace.
python/cpython pull request #4093
Opened 2017-10-23 20:34 UTC by jusjusjus

This request adds `mmap.ACCESS_DEFAULT` into the namespace.  Accessing the default value might be necessary, if one needs to overwrite an `ACCESS` keyword argument.

I have that situation in numpy.memap, and currently just overwrite by `access=0` (=mmap.ACCESS_DEFAULT) if needed.  However, it would be better to track  `enum access_mode`.

2017-10-23 20:34 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-11-06 23:54 UTC, vstinner requested changes
You have to document the new constant in Doc/library/mmap.rst:

*access* accepts one of three
values: :const:`ACCESS_READ`, :const:`ACCESS_WRITE`, or :const:`ACCESS_COPY`
to specify read-only, write-through or copy-on-write memory respectively.

Please add this to the doc as well:

```
... versionchanged:: 3.7
    Added :const:`ACCESS_DEFAULT` constant.
```

2017-11-06 23:54 UTC, haypo commented on Misc/NEWS.d/next/Library/2017-10-23.bpo-31854.fh8334f.rst
> +Add ``mmap.ACCESS_DEFAULT`` to namespace.
I don't understand "Add ... to namespace": which namespace?

I propose to rephase the NEWS entry as: "Add ``mmap.ACCESS_DEFAULT`` constant."

2017-11-07 17:29 UTC, jusjusjus commented
I have made the requested changes; please review again

2017-11-07 20:51 UTC, vstinner approved these changes
LGTM, thanks. It's perfect with the documentation update ;-)

2017-11-07 20:51 UTC, merged