add timeout parameter for get_server_certificate in ssl.py
python/cpython pull request #4126
Opened 2017-10-26 03:52 UTC by nixawk

The original [**get_server_certificate**](https://github.com/python/cpython/blob/master/Lib/ssl.py#L1221) in [ssl.py](https://github.com/python/cpython/blob/master/Lib/ssl.py#L1221) does not support socket timeout, 

```
def get_server_certificate(addr, ssl_version=PROTOCOL_TLS, ca_certs=None):
    """Retrieve the certificate from the server at the specified address,
    and return it as a PEM-encoded string.
    If 'ca_certs' is specified, validate the server cert against it.
    If 'ssl_version' is specified, use it in the connection attempt."""

    host, port = addr
    if ca_certs is not None:
        cert_reqs = CERT_REQUIRED
    else:
        cert_reqs = CERT_NONE
    context = _create_stdlib_context(ssl_version,
                                     cert_reqs=cert_reqs,
                                     cafile=ca_certs)
    with  create_connection(addr) as sock:
        with context.wrap_socket(sock) as sslsock:
            dercert = sslsock.getpeercert(True)
    return DER_cert_to_PEM_cert(dercert)

```

After the patch, ssl.py can do it with a timeout parameter, ex: **www.qq.com**.

```
>>> import ssl
>>> ssl.get_server_certificate(("www.qq.com", 443), timeout=6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ssl.py", line 1017, in get_server_certificate
    with closing(create_connection(addr, timeout)) as sock:
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 101] Network is unreachable
```

2017-10-26 03:52 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-11-03 21:49 UTC, tiran requested changes
Please update documentation and provide a test case.

2019-12-31 13:42 UTC, corona10 commented
@nixawk Do you want to rebase this PR and continue to work with this?

2020-01-26 01:02 UTC, csabella commented
Since this pull request seems to be abandoned, I'm going to close it.  If the original author is interested in continuing to work on it, it can be reopened or someone else can create a new pull request to replace it.  If the original author's work is used in a new PR, please give the appropriate credit.

2020-01-26 01:02 UTC, closed without merging