bpo-25720: Fix the method for checking pad state of curses WINDOW
python/cpython pull request #4164
Opened 2017-10-29 09:03 UTC by ma8ma

### Highlights of changes

- Modify configure check for the WINDOW `_flags` field.
- Add configure check for [`is_pad`][is_pad] function/macro.
- Remove the definition of `NCURSES_OPAQUE` for Apple-specific.
- Define `NCURSES_OPAQUE` as zero in the case of no `is_pad()` and having WINDOW `_flags`.
- Modify the requirement for defining `WINDOW_HAS_FLAGS` when having *ncurses.h*.
- Add requirement for defining `HAVE_CURSES_IS_PAD` when having *ncurses.h*.
- Define `py_is_pad()` macro if `HAVE_CURSES_IS_PAD` or `WINDOW_HAS_FLAGS` are defined.
- Change conditional compilation: replace `WINDOW_HAS_FLAGS` with `py_is_pad`.

### Motivation

`WINDOW_HAS_FLAGS` will be defined by configure check, but if your platform has *ncurses.h*, [defines the macro always][py_curses_h].  Therefore, codes which check the WINDOW `_flags` field are enabled regardless of `NCURSES_OPAQUE` (added since [ncurses 5.7][ncurses57]), and a compile error occurs on platforms where WINDOW is actually opaque.

For this reason, these codes are modified to use ncurses `is_pad()` instead of checking the field.  If your platform does not provide the `is_pad()` (added since [ncurses 5.8][ncurses58] as a ncurses-specific feature), the existing way that checks the field will be enabled. In this case, `NCURSES_OPAQUE` is defined as zero before including *[n]curses.h*, for exposing WINDOW fields regardless of the configuraton.

Note: This change does not drop support for platforms where do not have both WINDOW `_flags` field and `is_pad()`.

[is_pad]: http://invisible-island.net/ncurses/man/curs_opaque.3x.html
[py_curses_h]: https://github.com/python/cpython/blob/master/Include/py_curses.h#L57-L62
[ncurses57]: http://invisible-island.net/ncurses/announce-5.7.html
[ncurses58]: http://invisible-island.net/ncurses/announce-5.8.html

2017-10-31 20:35 UTC, serhiy-storchaka requested changes
The configure check doesn't work. The testing code is compiled successfully since implicit declaration of functions is not an error in C. This results to false detection of the `is_pad` function and compilation failure on NetBSD.

Look at recently added checks for other curses functions/macros.

2017-10-31 23:42 UTC, ma8ma commented
@serhiy-storchaka I see :+1:
I have made the requested changes; please review again.

2017-11-01 12:04 UTC, serhiy-storchaka approved these changes

2017-11-01 12:05 UTC, merged

2017-11-01 12:05 UTC, miss-islington commented
Thanks @ma8ma for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6.
🐍🍒⛏🤖

2017-11-01 18:00 UTC, ma8ma commented
@serhiy-storchaka Thank you for merging!