bpo-29649: struct.pack_into check boundary error message didn't respect offset
python/cpython pull request #424
Opened 2017-03-03 12:41 UTC by andrewnester

Fix for https://bugs.python.org/issue29649

2017-03-03 13:28 UTC, berkerpeksag requested changes

2017-03-03 13:28 UTC, berkerpeksag commented on Lib/test/test_struct.py
> +        import ctypes
I'd suggest moving this import module level and use the following pattern:

```py
try:
    import ctypes
except ImportError:
    ctypes = None
```

then add

```py
@unittest.skipUnless(ctypes, 'requires ctypes')
def test_boundary_error_message(self):
    ...
```

2017-03-03 13:28 UTC, berkerpeksag commented on Lib/test/test_struct.py
> +        except struct.error as e:
Using `assertRaises` would be better:

```py
with self.assertRaises(struct.error) as cm:
    struct.pack_into('b', byte_list, 5, 1)

self.assertEqual(str(cm.exception), '...')
```

2017-03-03 13:28 UTC, berkerpeksag commented on Misc/NEWS
> +- bpo-29649: struct.pack_into check boundary error message didn't respect offset.
This needs to be moved to "Library" section. And please add an empty line after the section header.

2017-03-03 13:33 UTC, andrewnester commented
@berkerpeksag thanks for review! I've just made changes required.

2017-03-03 13:36 UTC, serhiy-storchaka commented on Lib/test/test_struct.py
> +        byte_list = ctypes.create_string_buffer(1)
Using `ctypes` looks unnecessary here. Why not use `bytearray`?

2017-03-03 13:36 UTC, serhiy-storchaka commented on Lib/test/test_struct.py
> +        except struct.error as e:
Or `assertRaisesRegex()` if we want to be more lenient to error message.

2017-03-03 13:38 UTC, andrewnester commented on Lib/test/test_struct.py
> +        byte_list = ctypes.create_string_buffer(1)
@serhiy-storchaka absolutely agree, thanks!

2017-03-03 13:50 UTC, andrewnester commented
@berkerpeksag @serhiy-storchaka thank you for reviews! changes made. I also changed exception message a little bit as @serhiy-storchaka mentioned on corresponding issue.

2017-03-03 14:00 UTC, andrewnester commented
@berkerpeksag @serhiy-storchaka thank you for reviews! changes made. I also changed exception message a little bit as @serhiy-storchaka mentioned on corresponding issue.

2017-03-04 08:19 UTC, andrewnester commented
@berkerpeksag @serhiy-storchaka thank you for reviews! changes made. I also changed exception message a little bit as @serhiy-storchaka mentioned on corresponding issue.

2017-03-04 08:21 UTC, andrewnester commented
@berkerpeksag @serhiy-storchaka thank you for reviews! changes made. I also changed exception message a little bit as @serhiy-storchaka mentioned on corresponding issue.

2017-03-04 13:51 UTC, serhiy-storchaka commented on Lib/test/test_struct.py
> +                                    'pack_into requires a buffer of at least 6 bytes for packing 1 bytes at offset 5'):
Too long line.

2017-03-04 13:51 UTC, serhiy-storchaka commented on Misc/NEWS
> +- bpo-29649: struct.pack_into check boundary error message didn't respect offset.
The entry should be added at the start of corresponding section. Separate it with empty lines from other text.

Add `()` after `struct.pack_into`. Add "Patch by <yourname>".

2017-03-04 13:51 UTC, serhiy-storchaka commented on Modules/_struct.c
> +                     "pack_into requires a buffer of at least %zd bytes for packing %zd bytes at offset %zd)",
Too long lines.

2017-03-04 16:37 UTC, andrewnester commented
thanks @serhiy-storchaka for review, just made changes you requested.

2017-03-05 15:55 UTC, serhiy-storchaka requested changes
Please also address my comment on the tracker.

2017-03-05 15:55 UTC, serhiy-storchaka commented on Misc/NEWS
> +  didn't respect offset. Patch by Andrew Nester.
Use two spaces after sentence ending period.

2017-03-05 16:32 UTC, andrewnester commented
Thanks @serhiy-storchaka ! I've just added changes you requested + new error messages based on your comment from tracker. Thanks a lot!

2017-03-05 17:20 UTC, serhiy-storchaka commented on Modules/_struct.c
> +    if (offset < 0 && offset + soself->s_size > 0) {
I think three following `if`'s can be merged into one `if (offset < 0)`. This will speed up common case of non-negative `offset`.

2017-03-05 17:20 UTC, serhiy-storchaka commented on Modules/_struct.c
> +                     "pack_into requires negative offset not higher than %zd "
This just repeats the same number two times (but with different signs). It would be more helpful to output an actual value of `offset`.

2017-03-05 17:20 UTC, serhiy-storchaka commented on Modules/_struct.c
> +                     soself->s_size + (offset > 0 ? offset : 0),
I think it would be more helpful to output an actual size of the buffer rather of `soself->s_size + offset`. The user can add two reported numbers.

2017-03-05 18:19 UTC, andrewnester commented on Modules/_struct.c
> +                     soself->s_size + (offset > 0 ? offset : 0),
@serhiy-storchaka I would like to leave required size indicated explicitly but will add actual buffer size to this error message. Thanks!

2017-03-05 18:22 UTC, andrewnester commented
thanks @serhiy-storchaka for review, I just made couple of additional changes you requested.

2017-03-09 09:25 UTC, andrewnester commented
@serhiy-storchaka @berkerpeksag any updates on this?

2017-03-09 10:00 UTC, serhiy-storchaka commented
"not higher/lower than *some negative value*" doesn't look pretty clear. I afraid it can cause confusion. I prefer to output the offset and the size of the buffer or data. Something like

    pack_into() can't pack into buffer of size 10 at offset -11
    pack_into() can't pack the data of size 11 at offset -10
    pack_into() can't pack the data of size 11 into buffer of size 20 at offset 10

Maybe other developers can suggest better wording.

2017-03-11 04:26 UTC, vadmium reviewed
@Andrewnester’s current proposals are

1: pack_into requires a buffer of at least R bytes for packing P bytes at offset O (actual buffer size is B)
2: pack_into requires negative offset not higher than H (actual offset is O)
3: pack_into requires negative offset not lower than L (actual offset is O)

I agree the negative offset ones are awkward. My suggestions:

2: No space to pack 11 bytes at offset −10
3: Offset −11 out of range for 10-byte buffer

2017-03-11 04:26 UTC, vadmium commented on Lib/test/test_struct.py
> +                '\(actual buffer size is 1\)'):
I think it would be good to use a raw string here: `r'\(. . .\)'`

2017-03-11 08:42 UTC, andrewnester commented
thanks @vadmium @serhiy-storchaka 
I just changed error messages to ones proposed by @vadmium 
Thanks!

2017-03-12 23:46 UTC, vadmium commented on Lib/test/test_struct.py
> +                '\(actual buffer size is 1\)'):
Correct me if I am wrong (I haven’t caught up with Python after the Git Hub changeover), but I think you need to make the final part of the string a raw string:

```python-console
>>> (r'pack_into requires a buffer of at least 6 '
... 'bytes for packing 1 bytes at offset 5 '
... '\(actual buffer size is 1\)')
<stdin>:3: DeprecationWarning: invalid escape sequence \(
```

2017-03-13 07:04 UTC, andrewnester commented on Lib/test/test_struct.py
> +                '\(actual buffer size is 1\)'):
@vadmium Thanks! you're right, I updated my PR.

2017-03-13 07:31 UTC, serhiy-storchaka approved these changes

2017-03-20 22:59 UTC, andrewnester commented
@berkerpeksag could you please review it again?

2017-04-02 15:43 UTC, andrewnester commented
@serhiy-storchaka @berkerpeksag @vadmium any updates on this?

2017-04-04 01:23 UTC, berkerpeksag commented on Lib/test/test_struct.py
> +        byte_list = bytearray(1)
Do we need `byte_list`? Can't we just pass `bytearray(1)` to `pack_into()`?

2017-04-04 01:23 UTC, berkerpeksag commented on Lib/test/test_struct.py
> +                'pack_into requires a buffer of at least 6 '
This is just a style nit, but I find this style is a bit ugly. I prefer something like this:

```py
regex = (
    r'multi'
    r'line'
    r'regex'
)

with self.assertRaisesRegex(struct.error, regex):
    ...
```

2017-04-04 01:23 UTC, berkerpeksag commented on Modules/_struct.c
> +                         "No space to pack %zd bytes at offset %zd",
I admit that we are pretty inconsistent with the styles of our exception messages, but I think these two should start with lowercase letters.

2017-04-04 01:23 UTC, berkerpeksag commented on Misc/NEWS
> +  and wrong types.
This looks like an unrelated change to me.

2017-04-04 01:23 UTC, berkerpeksag commented on Misc/NEWS
> +- bpo-29649: struct.pack_into() check boundary error message
Perhaps something like "Exception message of struct.pack_into() now respects [...]" might be better. It's 4am here so perhaps @vadmium can come up with a better wording :)

2017-04-04 03:01 UTC, vadmium commented on Misc/NEWS
> +- bpo-29649: struct.pack_into() check boundary error message
It’s 1 p.m. here! Maybe something like “Improve ‘struct.pack_into’ exception messages for problems with the buffer size and offset”.

2017-04-04 09:16 UTC, andrewnester commented
@berkerpeksag @vadmium thanks for the review, seems reasonable. All changes done. Could you please review it again? Thanks!

2017-04-04 10:18 UTC, berkerpeksag approved these changes
LGTM, thanks! I will let Serhiy do the merging since he knows this part of CPython better than myself.

2017-04-04 10:46 UTC, merged