bpo-16355: fix a lack in inspect.getcomments()
python/cpython pull request #428
Opened 2017-03-03 14:02 UTC by marco-buttu

Fix [bpo-16355](https://bugs.python.org/issue16355).

2017-03-03 14:16 UTC, berkerpeksag commented
Note: Commit message should include "Initial patch by Vajrasky Kok.".

2017-03-08 01:28 UTC, berkerpeksag requested changes

2017-03-08 01:28 UTC, berkerpeksag commented on Lib/test/test_inspect.py
> +                          MISSING_C_DOCSTRINGS)
This doesn't look like a relevant change to bpo-16355. Please send a separate PR for this.

Anyway, I prefer hanging indentation style:

```py
from test.support import (
    MISSING_C_DOCSTRINGS, TESTFN, DirsOnSysPath, cpython_only, run_unittest,
)
```

2017-03-08 01:28 UTC, berkerpeksag commented on Lib/test/test_inspect.py
> +        fn = "_non_existing_filename_used_for_sourcefile_test.py"
`_non_existing_filename.py` is both short and descriptive. Also, this way you can avoid using a `fn` variable.

2017-03-08 01:28 UTC, berkerpeksag commented on Lib/test/test_inspect.py
> +        # If the object source file is not available, return None
Finish sentences with full stops.

2017-03-08 09:23 UTC, marco-buttu commented
Thanks @berkerpeksag, fixed

2017-03-16 17:55 UTC, berkerpeksag commented on Lib/test/test_inspect.py
> +        co = compile("x=1", '_non_existing_filename.py', "exec")
Please use single quotes like the rest of the test.

2017-03-16 18:21 UTC, 1st1 commented
Why don't we raise an error if we can't find the source? Why returning `None`?

2017-03-16 20:18 UTC, marco-buttu commented on Lib/test/test_inspect.py
> +        co = compile("x=1", '_non_existing_filename.py', "exec")
Thanks @berkerpeksag, done.

2017-03-16 20:26 UTC, marco-buttu commented
@1st1, in [bpo-16355](http://bugs.python.org/issue16355) @ezio-melotti and @bitdancer discussed about raising an error or not, and eventually they agreed to return `None`.

2017-03-16 20:33 UTC, 1st1 commented
I see. The idea is to preserve the backwards compatibility. Then LGTM.

2017-03-17 07:37 UTC, vadmium commented on Doc/library/inspect.rst
> +   defined in C or interactive shell.
or the interactive shell

2017-03-17 08:47 UTC, berkerpeksag approved these changes

2017-03-17 08:50 UTC, merged

2017-03-17 08:51 UTC, berkerpeksag commented
Thanks!