bpo-31955: Fixed incorrect string type check - use isinstance(value, basestring)…
python/cpython pull request #4316
Opened 2017-11-07 13:33 UTC by Mazay0

Fixed incorrect string type check. Previously if unicode string was passed as executable value it was considered not as string, but as list.

https://bugs.python.org/issue31955

Previous PR on this issue (#4296) was mistaken - for Python3 str is equivalent to basestring.

2017-11-07 13:33 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-11-07 13:56 UTC, Mazay0 commented
This PR is instead of PR #4296 . I agree, that this fix is necessary only for Python 2.

2017-11-07 14:34 UTC, vstinner requested changes

2017-11-07 14:34 UTC, haypo commented on Misc/NEWS.d/next/Library/2017-11-07-19-12-25.bpo-31955.1DWu-S.rst
> +found" at unixccompiler.py, line 122, in _compile().
NEWS entries are read by end users who don't care much to details. I suggest to be much more concise. For example:

Fix CCompiler.set_executable() of distutils to handle properly Unicode strings.

2017-11-07 16:52 UTC, merwok commented
Do you think you could add tests for set_executables in Lib/distutils/tests/test_ccompiler.py ?

2017-11-08 10:04 UTC, haypo commented on Lib/distutils/tests/test_ccompiler.py
> +            executables = {'compiler':'', 'compiler_cxx':'', 'linker':''}
PEP 8: {'compiler': '', 'compiler_cxx': '', 'linker': ''}

2017-11-08 10:04 UTC, haypo commented on Lib/distutils/tests/test_ccompiler.py
> +    def test_set_executables_unicode(self):
Please rename to test_set_executable(), since you test 3 types, not only Unicode.

2017-11-08 10:04 UTC, haypo commented on Lib/distutils/tests/test_ccompiler.py
> +        compiler.set_executables(compiler = ['/usr/bin/env', 'OMPI_MPICC=clang', '/usr/bin/mpicc.openmpi'])
PEP 8: no space around = when passing keyword argument: set_executables(compiler=[...])

2017-11-08 10:04 UTC, haypo commented on Lib/distutils/tests/test_ccompiler.py
> +        print(compiler.executables)
Remove debug prints please.

2017-11-08 10:04 UTC, haypo commented on Lib/distutils/tests/test_ccompiler.py
> +        self.assertEqual(len(compiler.executables['compiler'][2]) == '/usr/bin/mpicc.openmpi')
Hum, I dislike testing only one value. Please test:

self.assertEqual(compiler.executables['compiler'], ...)  # fill the dots ;-)

2017-11-08 10:04 UTC, haypo commented on Lib/distutils/tests/test_ccompiler.py
> +        self.assertEqual(len(compiler.executables['linker'][2]) == '/usr/bin/mpicxx.openmpi')
Use a Unicode string here as well.

2017-11-08 12:04 UTC, Mazay0 commented
I have made the requested changes; please review again.

2017-11-08 12:13 UTC, eamanu approved these changes
Good

2017-11-08 13:25 UTC, Mazay0 commented
I have made the requested changes; please review again.

2017-11-08 13:39 UTC, haypo commented on Lib/distutils/tests/test_ccompiler.py
> +        self.assertEqual(len(compiler.compiler), 3)
Checking the length became redundant with the following check and so should be removed.

2017-11-08 13:39 UTC, haypo commented on Lib/distutils/tests/test_ccompiler.py
> +        compiler.set_executables(linker=u'env OMPI_MPICXX=clang++ mpicxx')
Can you please use a different string, like "env OMPI_MPICXX=clang++ linker" or whatever different than the previous test.

2017-11-08 13:39 UTC, haypo commented
The change now looks to me, but I have a last minor request, sorry!

2017-11-08 14:32 UTC, Mazay0 commented
I have made the requested changes; please review again.

2017-11-08 15:37 UTC, haypo commented
Hum, @Mazay0, it seems like you didn't sign the CLA. What is your bugs.python.org login? If you are Dee Mee, please fill your GitHub login in your bugs.python.org profile: click on "Your Details".
https://bugs.python.org/user27322

2017-11-08 15:47 UTC, Mazay0 commented
>  If you are Dee Mee, please fill your GitHub login in your bugs.python.org profile: click on "Your Details".

Done!

2017-11-08 15:47 UTC, vstinner approved these changes

2017-11-08 15:48 UTC, haypo commented
> Done!

I confirm: after removing the "CLA not signed" label, the bot added the green "CLA signed" label.

2017-11-08 15:48 UTC, merged

2017-11-08 15:49 UTC, haypo commented
Thanks @Mazay0 and congratulations for your first PR! 🎉

2017-11-08 15:57 UTC, eamanu commented
@Mazay0  congratulation!