bpo-26187: Tests for sqlite3 trace callback
python/cpython pull request #434
Opened 2017-03-03 19:39 UTC by AnishShah

2017-03-04 00:32 UTC, berkerpeksag requested changes

2017-03-04 00:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +    def CheckTraceCallbackContent(self):
We should skip the test if sqlite3_prepare_v2 is not available.

2017-03-04 00:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +    def CheckTraceCallbackContent(self):
The test name doesn't explain what we actually testing here.

2017-03-04 00:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +        Test that the statement are correct. Fix for bpo-26187
Docstring is not needed.

2017-03-04 00:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +        queries.append("COMMIT")
These two lines can be removed. We only want to test that set_trace_callback doesn't produce any duplicate entries.

2017-03-04 09:33 UTC, palaviv commented
This test don't fail before the fix in #359. I opened another PR (#461) with fixed test.

2017-03-05 08:56 UTC, closed without merging

2017-03-06 17:17 UTC, berkerpeksag commented
Thanks, Aviv. Next time please send your feedback as a comment and give the PR author some time to address your comments. Otherwise, we will end up with duplicate PRs.

Also note that we always locally run tests and make sure that the test fails before the fix is applied so the chance of merging a broken test is minimal.

2017-03-10 10:32 UTC, palaviv commented
Sorry about that @berkerpeksag. I actually started by writing a comment on this PR but found out that what I do is to write the all test again. I am still having hard time understanding what @AnishShah did here as I wrote a test case in the issue.