Clarify the behavior of the staticmethod builtin
python/cpython pull request #4362
Opened 2017-11-10 11:15 UTC by haikuginger

It looks like the original staticmethod docstring might have been based on the classmethod docstring, and it seems like the current description might not be accurate. This change clarifies the docstring to explicitly state that neither the class nor instance is used at all in a static method.

2017-11-10 11:15 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-11-16 18:28 UTC, merwok commented
Can you open a ticket on bugs.python.org?  This will give a chance for more people to review this change, and make it easier to track backports.  Thanks!

2017-11-18 18:05 UTC, haikuginger commented
@merwok, done. Thanks; I wasn't sure if this was a substantial enough change to require that.

2017-11-18 20:08 UTC, merwok commented
Thanks!  If you edit your title the robots will add links between this PR and the ticket.
https://devguide.python.org/pullrequest/#submitting

2018-12-21 15:54 UTC, merwok requested changes
See Raymond’s reply on the ticket.

2018-12-24 07:47 UTC, merged