bpo-28197: Add start and stop keywords to range.index() method
python/cpython pull request #4378
Opened 2017-11-12 11:21 UTC by nitishch

Added start and stop as keywords to range.index method.

I created a temporary range object on which indexing will be done. Is there a better way to decref the temporary range object?

2021-04-14 16:50 UTC, ktbarrett commented
@nitishch Are you willing to get this rebased and ready for review again? If not I'll open an new PR and do that.

2021-04-14 19:25 UTC, shreyanavigyan requested changes
Found some code that requires little modifications.

2021-04-14 19:25 UTC, shreyanavigyan commented on Objects/rangeobject.c
> +        }
Make the code look a little bit cleaner.
```suggestion
        if(start && (!PyLong_CheckExact(start))){
            PyErr_Format(PyExc_TypeError,
                         "start value must be integer, not %.200s",
                         start->ob_type->tp_name);
            return NULL;
        }         
        if(stop && (!PyLong_CheckExact(stop))){
            PyErr_Format(PyExc_TypeError,
                         "stop value must be integer, not %.200s",
                         stop->ob_type->tp_name);
            return NULL;
        } 
```

2021-04-14 19:25 UTC, shreyanavigyan commented on Objects/rangeobject.c
> +        Py_DECREF(slice);
Slice object creation maybe unsuccessful in which case the return value maybe NULL. Therefore use Py_XDECREF. 

```suggestion
        Py_XDECREF(slice);
```

2022-10-30 19:06 UTC, iritkatriel commented
Closing as this PR is abandoned and out of date (see the issue).

2022-10-30 19:06 UTC, closed without merging