[3.6] bpo-31948: Fix broken links in msilib docs (GH-4397).
python/cpython pull request #4398
Opened 2017-11-14 23:30 UTC by Jesse-Bakker

(cherry picked from commit 3bda02222aa3783bf85fc3ff8bc042aefd9c4fd3)

2017-11-14 23:30 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-11-14 23:45 UTC, Mariatta requested changes

2017-11-14 23:45 UTC, Mariatta commented on Doc/library/msilib.rst
> +   `MsiCloseHandle <https://msdn.microsoft.com/en-us/library/windows/desktop/aa370067.aspx>`_
`Database.Close()` is new in 3.7, so the entry for MsiCloseHandle shouldn't be in 3.6.

2017-11-15 00:21 UTC, Jesse-Bakker commented
I have made the requested changes; please review again

2017-11-15 00:22 UTC, Mariatta approved these changes

2017-11-15 00:23 UTC, merged

2017-11-15 00:23 UTC, Mariatta commented
Awesome! Thanks @Jesse-Bakker!