bpo-28684: asyncio tests now handle PermissionError raised when bindi…
python/cpython pull request #4503
Opened 2017-11-22 17:00 UTC by xdegaye

…ng a unix socket

2017-11-22 17:02 UTC, 1st1 commented
I would prefer to use `@unittest.skipIf(android)` approach instead.  `PermissionError` can occur on a normal Linux machine as a result of some regression in asyncio.  I don't want such cases to slip through our CI just because it sometimes happens on Android.

2017-11-22 17:03 UTC, 1st1 requested changes
I would prefer to use `@unittest.skipIf(android)` approach instead.  `PermissionError` can occur on a normal Linux machine as a result of some regression in asyncio.  I don't want such cases to slip through our CI just because it sometimes happens on Android.

2017-11-23 16:58 UTC, xdegaye commented
@1st1 I understand your concern. Instead of ``@unittest.skipIf(android)`` I think it would be better to use a new decorator ``@support.skip_unless_bind_unix_socket`` to widen the scope of the changes:
* The root user on Android does not raise PermissionError, so it should be possible to run the asyncio test suite in that case without skipping those tests.
* Android runs now SElinux in enforcing mode and one of its policies restricts the access to unix sockets [1], so the problem is not Android specific and may impact other linux platforms depending on the way they are configured. As a confirmation of the fact that SElinux is involved, the remote command ``adb logcat`` prints this kind of AVC SElinux record whenever one of the asyncio tests fails with PermissionError:
```
11-23 15:36:11.859  2919  2919 W python  : type=1400 audit(0.0:20): avc: denied { create }
for name="tmpug8hwp0r" scontext=u:r:shell:s0 tcontext=u:object_r:shell_data_file:s0
tclass=sock_file permissive=0
```

[1] An interesting academic paper [The Misuse of Android Unix Domain Sockets and Security Implications](https://dl.acm.org/citation.cfm?id=2978297).

2017-11-23 17:00 UTC, 1st1 commented
SGTM, let's go for `@support.skip_unless_bind_unix_socket`

2017-11-24 15:16 UTC, 1st1 commented on Lib/test/support/__init__.py
> +                _bind_nix_socket_error = ''
`_bind_nix_socket_error = None`

2017-11-24 15:34 UTC, xdegaye commented on Lib/test/support/__init__.py
> +                _bind_nix_socket_error = ''
Yes, much better.

2017-11-24 15:40 UTC, 1st1 approved these changes

2017-11-24 15:40 UTC, 1st1 commented
LGTM

2017-11-24 15:41 UTC, xdegaye commented
I am not sure that these changes need to be backported to 3.6.

2017-11-24 16:35 UTC, merged