bpo-10544: Disallow "yield" in comprehensions and generator expressions.
python/cpython pull request #4564
Opened 2017-11-25 23:06 UTC by serhiy-storchaka

2017-12-01 07:32 UTC, ncoghlan requested changes
Just adding a blocking review to ensure we don't merge this until after the 3.7 maintenance branch has been created.

2018-02-03 20:05 UTC, serhiy-storchaka commented
Could you please look on this again Nick?

2018-02-04 08:11 UTC, ncoghlan approved these changes
LGTM, and the main branch is now open for 3.8 commits.

2018-02-04 08:11 UTC, ncoghlan commented on Misc/NEWS.d/next/Core and Builtins/2017-11-26-00-59-22.bpo-10544.fHOM3V.rst
> +Yield expressions now are disallowed in comprehensions and generator
Minor wording tweak: now are -> are now

2018-02-04 08:15 UTC, serhiy-storchaka commented
Maybe you can suggest better wording for What's New?

2018-02-04 08:32 UTC, ncoghlan commented
The What's New wording seemed fine to me.

2018-02-04 08:53 UTC, merged

2018-02-04 08:54 UTC, serhiy-storchaka commented
Thank you @ncoghlan for your review.