bpo-26187: Tests sqlite3 trace callback no duplicate on shcema changing
python/cpython pull request #461
Opened 2017-03-04 09:31 UTC by palaviv

Test for issue 26187

2017-03-06 17:32 UTC, berkerpeksag requested changes
Please also add a note to `Misc/NEWS` and mention the v2 API change.

2017-03-06 17:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +        Test that the statement are correct. Fix for bpo-26187
Docstring is not needed here. Just add a comment with a reference to bpo-26187.

2017-03-06 17:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +from tempfile import NamedTemporaryFile
Nitpick: I'd prefer `import tempfile`.

2017-03-06 17:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +            queries = ["create table foo(x)",
`traced_statements`, `trace` and `queries` can go outside of the with statements.

2017-03-06 17:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +        with NamedTemporaryFile(suffix='.sqlite') as db_path:
`NamedTemporaryFile` is known to be problematic on Windows. Did you check that it cleanups the temp file?

2017-03-06 17:32 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +
Nitpick: Please delete the extra new line.

2017-03-12 17:37 UTC, palaviv commented on Lib/sqlite3/test/hooks.py
> +        with NamedTemporaryFile(suffix='.sqlite') as db_path:
I will look what they do in other test's and copy it.

2017-03-14 00:02 UTC, berkerpeksag commented on Lib/sqlite3/test/hooks.py
> +        bpo-26187
I'd prefer a plain Python comment instead of a docstring:

```py
# set_trace_callback() shouldn't produce duplicate content (bpo-26187)
```

2017-03-14 00:02 UTC, berkerpeksag commented on Misc/NEWS
> +- bpo-26187: Test that sqlite trace callback is not called multiple
sqlite -> sqlite3?

2017-03-14 00:02 UTC, berkerpeksag commented on Misc/NEWS
> +  times when schema is changing. Fixed by bpo-9303
Add two spaces at the end of a sentence.

2017-03-14 00:02 UTC, berkerpeksag commented on Misc/NEWS
> +  times when schema is changing. Fixed by bpo-9303
Perhaps we can say something like "Indirectly fixed by switching to use sqlite3_prepare_v2() in bpo-9303."?

2017-03-14 00:02 UTC, berkerpeksag commented on Misc/NEWS
> +>>>>>>> upstream/master
This looks like a merge glitch :)

2017-04-09 08:25 UTC, berkerpeksag approved these changes

2017-04-09 08:26 UTC, berkerpeksag commented
Looks good, thanks! I just fixed the merge conflict and will merge it when Travis is done.

2017-04-09 09:11 UTC, merged