bpo-32173: linecache.py add lazycache to __all__ and use dict.clear to clear the cache
python/cpython pull request #4641
Opened 2017-11-30 03:12 UTC by GanZiQim

2017-11-30 03:12 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-12-02 02:42 UTC, lisroach approved these changes
I think this is a reasonable diff, lazycache should be added to __all__ and the clearcache is improved by using clear().

The extra code changes are just semantics which help code readability without changing any functionality.

2017-12-03 12:07 UTC, GanZiQim commented
I've been signed for three times, but the state has not changed

2017-12-03 13:23 UTC, asvetlov commented
CLA status updated

2017-12-04 02:17 UTC, GanZiQim commented
news entry added

2017-12-04 08:54 UTC, asvetlov approved these changes

2018-01-06 23:08 UTC, Mariatta requested changes

2018-01-06 23:08 UTC, Mariatta commented on Misc/NEWS.d/next/Library/2017-12-04-10-14-23.bpo-32173.e0C5dF.rst
> +linecache.py add lazycache to __all__ and use dict.clear to clear the cache
The news entry should be improved. The bpo issue title is not always appropriate as a News entry.

Your news says adding lazycache and use dict.clear to clear the cache, but this patch actually does a little more than those two.

Use reST markup, and end the sentence with a period.

2019-03-17 10:05 UTC, csabella commented
This issue is approved by 2 core developers, but was waiting on an update to the blurb.

@ganziqim Please make the last changes requested by Mariatta, after which I believe this will be ready to merge.  Thanks!

2019-03-18 07:45 UTC, ganziqim commented
> This issue is approved by 2 core developers, but was waiting on an update to the blurb.
> 
> @ganziqim Please make the last changes requested by Mariatta, after which I believe this will be ready to merge. Thanks!

done.

2019-03-18 09:39 UTC, csabella commented
@ganziqim Thanks!

@lisroach @asvetlov I believe Mariatta is out of open source starting today, so, if you can, please review the changes made to the news entry.  Thank you!

2020-01-26 02:07 UTC, merged