pdb/cmd: avoid creating exceptions
python/cpython pull request #4666
Opened 2017-12-01 18:23 UTC by blueyed

This allows for `sys.exc_info` being more useful, when it is not
swallowed by an (unnecessary) `AttributeError` in pdb itself.

There might be more places, but I had this local changes and wanted to ask for feedback on it already.

2019-06-02 12:36 UTC, auvipy approved these changes
news?

2019-06-03 11:27 UTC, blueyed commented
> news?

When it gets accepted finally.  As mentioned before, there are likely more places - this is rather old already.

2021-06-28 10:39 UTC, iritkatriel commented
@blueyed I agree with this. Are you still interested in working on it?

2021-08-25 18:09 UTC, serhiy-storchaka reviewed
Can any tests be added?

2021-08-25 18:09 UTC, serhiy-storchaka commented on Lib/cmd.py
> +            return self.default(line)
Would this work too?
```
            try:
                func = getattr(self, 'do_' + cmd)
            except AttributeError:
                pass  # restore the original sys.exc_info()
            else:
                return func(arg)
            return self.default(line)
```
I do not suggest this code, just ask.

2021-08-25 21:34 UTC, iritkatriel commented on Lib/cmd.py
> +            return self.default(line)
I think it works if you add a naked raise at the end of the except block. Try this:

```
try:
   raise ValueError(1)
except:
   try:
      raise AttributeError(2)
   except AttributeError:
      pass
   else:
      print(42)
   raise
else:
  print(53)
```

2021-08-25 21:41 UTC, iritkatriel commented on Lib/cmd.py
> +            return self.default(line)
In something like pdb you would need to check if there is an active exception. Something like this:

```
import sys

def maybe_reraise():
   if sys.exc_info() != (None, None, None):
       raise

try:
   raise ValueError(1)
except:
   try:
      raise AttributeError(2)
   except AttributeError:
      pass
   else:
      print(42)
   maybe_reraise()
else:
  print(53)
```

2021-08-25 23:31 UTC, iritkatriel commented on Lib/cmd.py
> +            return self.default(line)
Sorry, I missed the point - we don't want to raise the exception, just to restore it. In that case doesn't my example show that there is no issue?

I'm not sure this PR is needed after all. If we had a test we would know, but since @blueyed is no longer responding we may need to just close it until an actual bug is reported.

2021-09-07 11:09 UTC, iritkatriel commented
Closing as the bug is not clear and the OP is not responding to requests to clarify it. Please create a new issue if you are still seeing a problem.

2021-09-07 12:23 UTC, blueyed commented
See https://bugs.python.org/msg401253 for more info / a response.
I've created the issue for discussion / the reasoning in the first place - sorry for not having responded here earlier.

2023-03-29 08:01 UTC, auvipy requested changes
I think if appropriate test is provided, it would be easier to understand if the proposed change is still needed or not

2023-12-15 17:27 UTC, serhiy-storchaka commented
The original issue was fixed in #111740 which applied the same change in Lib/cmd.py. The change in Lib/pdb.py looks not necessary.

2023-12-15 17:27 UTC, closed without merging