Update ast.c
python/cpython pull request #4708
Opened 2017-12-04 23:42 UTC by aleaxit

Clarify one potentially confusing error message

!!! If this is a backport PR (PR made against branches other than `master`),
please ensure that the PR title is in the following format:
```
[X.Y] <title from the original PR> (GH-NNNN)
```
Where: [X.Y] is the branch name, e.g. [3.6].

GH-NNNN refers to the PR number from `master`.

2017-12-30 23:41 UTC, zware approved these changes

2018-02-24 00:18 UTC, Mariatta commented
@aleaxit Can you fix the failing tests?

2018-02-24 00:19 UTC, Mariatta requested changes
`test_syntax` failed. Once that's fixed we can merge this.

2018-02-25 20:21 UTC, Mariatta commented
Can this go to 3.7?

2018-03-24 06:16 UTC, serhiy-storchaka commented
The new error message is wrong. The keyword argument can be an expression. Only the keyword itself can't be an expression.

2018-03-24 06:16 UTC, closed without merging