Use UTF-8 encoding when reading config files
python/cpython pull request #4727
Opened 2017-12-05 12:35 UTC by delivrance

This simply adds the `encoding="UTF-8"` argument and fixes the encoding problem when reading setup.cfg.

2017-12-05 12:35 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-12-05 15:51 UTC, merwok commented
Hello!  Can you point to a discussion on bugs.python.org?  As is we don’t know what the problem is, in what environment, on what Python versions, etc.

2017-12-05 16:49 UTC, delivrance commented
Hi there! Sure, guess I should have done that before: https://bugs.python.org/issue32223

2018-07-09 09:39 UTC, methane requested changes
Would you sign CLA and add NEWS entry?

2019-01-10 16:03 UTC, vstinner commented
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

2019-03-18 10:56 UTC, csabella commented
@delivrance Please address @methane's requested changes from 9 July 2018.  CPython cannot accept any changes without a signed CLA.  Thanks!

2019-04-18 14:15 UTC, vstinner commented
The CLA is still not signed :-(

2019-04-18 15:40 UTC, merwok commented
Please reply to the bpo discussion too.

2019-05-06 16:02 UTC, matrixise commented
Hi,

I close this PR but not the issue, when @delivrance will sign the CLA, he will be free to re-open this PR and complete it. (add blurb entry, ...)

@delivrance Thank you for your contribution but without the CLA signed, we can not accept your contrib.

2019-05-06 16:02 UTC, closed without merging