bpo-30579: Allow TracebackType creation and tb_next mutation from Python
python/cpython pull request #4793
Opened 2017-12-11 10:09 UTC by njsmith

This is admittedly an obscure use case, but currently there are
projects like Jinja2 and Trio that are forced to work around this with
horrible ctypes hacks:

  https://github.com/pallets/jinja/blob/fe3dadacdf4cf411d0a5b6bbd4d5234697a28af2/jinja2/debug.py#L345
  https://github.com/python-trio/trio/blob/1e86b1aee8c0c759f6f239ae53a05d0d3963c629/trio/_core/_multierror.py#L296

2018-01-06 09:39 UTC, ncoghlan requested changes
The change itself looks good to me, but the remaining assert statements in the test case need to be converted to the appropriate unittest methods: https://docs.python.org/3/library/unittest.html#assert-methods

2018-01-06 09:39 UTC, ncoghlan commented on Lib/test/test_raise.py
> +        assert isinstance(tb.tb_next, types.TracebackType)
These assertions all need to use the unittest assert methods, not assert statements.

2018-01-06 10:38 UTC, njsmith commented
Whoops, good catch, thanks.

I have made the requested changes; please review again.

2018-01-06 15:11 UTC, ncoghlan approved these changes
This mostly looks good to me now, just a minor comment relating to the possible use of `assertIsInstance` for slightly nicer failure messages.

Marking my review as approved anyway though, as I'll be offline until tomorrow, and I'm fine with someone else merging this in the meantime :)

2018-01-06 15:11 UTC, ncoghlan commented on Lib/test/test_raise.py
> +        self.assertTrue(isinstance(tb.tb_next, types.TracebackType))
There's a dedicated method for this one that gives a nicer message when it fails: https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIsInstance

2018-01-07 03:23 UTC, njsmith commented
Well that's embarrassing -- I even looked for `assertIsInstance` and somehow concluded it didn't exist. Fixed now.

2018-01-07 13:30 UTC, merged