bpo-32299: unittest.mock.patch.dict now returns patched dict when used as context manager
python/cpython pull request #4834
Opened 2017-12-13 09:59 UTC by ts-taiye

example:
```python
>>> from unittest.mock import patch
>>> with patch.dict(a, a=2) as patched:
...     print(patched)
... 
{'a': 2}
>>> print(a)
{'a': '1'}
```

2017-12-13 09:59 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


We also demand... [A SHRUBBERY!](https://www.youtube.com/watch?v=zIV4poUZAQo)


Thanks again to your contribution and we look forward to looking at it!

2017-12-13 10:15 UTC, ts-taiye commented
Signed CLA, waiting my profile to be updated.
Should i add something to news?

2017-12-13 10:15 UTC, asvetlov requested changes
Looks good but NEWS entry and documentation update are required for the PR

2017-12-14 07:33 UTC, ts-taiye commented
up

2017-12-14 10:31 UTC, asvetlov commented
Docs update is required (https://docs.python.org/3.7/library/unittest.mock.html#patch-dict)
Source file is ./Docs/library/unittest-mock.rst

2017-12-15 08:33 UTC, ts-taiye commented
will update it in a hour

2017-12-26 06:52 UTC, srinivasreddy commented
@asvetlov  This is good to go.

2017-12-26 09:57 UTC, asvetlov commented
Documentation should be updated to reflect a value returned by context manager.

2017-12-27 12:03 UTC, ts-taiye commented
omg, forgot to push commit) sorry)

2017-12-27 12:22 UTC, asvetlov commented
Please add something like 
```   .. versionchanged:: 3.6
      :func:`patch.dict` returns a patched dictionary when used as context manager.
```
at very end of `patch.dict` chapter, just before next `patch.multiple` one.

2018-01-04 10:51 UTC, ts-taiye commented
done

2018-01-23 08:23 UTC, berkerpeksag requested changes

2018-01-23 08:23 UTC, berkerpeksag commented on Doc/library/unittest.mock.rst
> +:func:`patch.dict` returns a patched dictionary when used as context manager.
This needs to be moved after the paragraph that starts with ":func:\`patch.dict\` can be used as a context manager, [...]".

Also, add a versionchanged marker after that paragraph:

```rst
.. versionchanged:: 3.7
   :func:`patch.dict` now returns the patched dictionary when it used as a context manager.
```

(Feel free to use any wording you want, I just gave an example.)

2018-01-23 08:23 UTC, berkerpeksag commented on Lib/unittest/test/testmock/testpatch.py
> +            self.assertDictEqual(patched, {'a': 'c'})
No need to use `assertDictEqual` explicitly here. `assertEqual` will use `assertDictEqual` if `a` and `b` both dicts:

https://github.com/python/cpython/blob/83c8675edb4fe278c5d930f7865977a5d3c7168a/Lib/unittest/case.py#L423

2018-01-23 08:23 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2017-12-13-17-49-56.bpo-32299.eqAPWs.rst
> +Changed ``mock.patch.dict`` to return patched dictionary when used as context manager
You way want to add 'the' before 'patched'.

2018-01-23 08:23 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2017-12-13-17-49-56.bpo-32299.eqAPWs.rst
> +Changed ``mock.patch.dict`` to return patched dictionary when used as context manager
Nitpick: Please finish the sentence with a full stop.

2018-01-23 08:23 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2017-12-13-17-49-56.bpo-32299.eqAPWs.rst
> +Changed ``mock.patch.dict`` to return patched dictionary when used as context manager
Please add "Patch by Your Name.".

2018-01-23 08:23 UTC, berkerpeksag commented on Doc/library/unittest.mock.rst
>      ...
Could you also add the assignment example you gave in the issue?

```py
patched_foo['spam'] = 'eggs'

assert patched_foo['spam'] == 'eggs'
```

2018-01-23 14:03 UTC, csabella commented
@ts-taiye   It looks like your patch is really close to being finished.  If you include the last suggestions by @berkerpeksag , then they may be able to approve this.

2018-10-27 12:50 UTC, mariocj89 commented
@ts-taiye this would be neat! Many people ask about why `mock.patch.dict` does not return the patched object like `mock.patch.object` or `mock.patch`. It makes it not so intuitive

Do you plan on taking the changes? I'd be happy to help you out through the remaining bits if you want :)

2018-10-28 15:31 UTC, ts-taiye commented
> 
> 
> @ts-taiye this would be neat! Many people ask about why `mock.patch.dict` does not return the patched object like `mock.patch.object` or `mock.patch`. It makes it not so intuitive
> 
> Do you plan on taking the changes? I'd be happy to help you out through the remaining bits if you want :)

Yes, i plan to, try to do it tomorrow

2018-11-05 18:05 UTC, ts-taiye commented
> @ts-taiye this would be neat! Many people ask about why `mock.patch.dict` does not return the patched object like `mock.patch.object` or `mock.patch`. It makes it not so intuitive
> 
> Do you plan on taking the changes? I'd be happy to help you out through the remaining bits if you want :)

Sorry for misleading, still have no time, will really appreciate your help

2018-11-07 19:17 UTC, mariocj89 commented
I think I've addressed all comments in https://github.com/mariocj89/cpython/commit/ff1fbe7bdbbcb32e2f24ae9425ec53ab953771ee

Let me know if you want me to send a new PR which closes this one (you still get all the credit in the commit history 😉 ) or whether you want to apply the patch locally and update this PR. I've rebased it to remove the merge commit that was in this PR.

If you want to apply locally, just get a new version of master and apply [this patch](https://github.com/mariocj89/cpython/commit/ff1fbe7bdbbcb32e2f24ae9425ec53ab953771ee.patch).

We can then ask a core dev to review it 😄

2018-12-03 22:52 UTC, mariocj89 commented
Hi @ts-taiye, this change would be neat! Every time I use `patch.dict` I wish this was merged :)

As said, let me know if you don't have time to push the changes you asked and I put in mariocj89@ff1fbe7 and I will send a different PR (still with the commits and patch in your name).

2018-12-10 09:18 UTC, mariocj89 commented
@ts-taiye I've opened with your change: https://github.com/python/cpython/pull/11062

2019-05-28 12:53 UTC, closed without merging