bpo-32384 fix test.test_generators for other implementations
python/cpython pull request #4940
Opened 2017-12-20 11:36 UTC by isaiah

Added guard to the `test.test_generators.SignalAndYieldFromTest` to check the existence of `_testcapi.raise_SIGINT_then_send_None`

2017-12-20 11:36 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-12-20 16:10 UTC, 1st1 approved these changes

2017-12-20 16:10 UTC, 1st1 commented
Approved.  Please sign the CLA and I'll merge this.

2017-12-24 19:19 UTC, 1st1 requested changes

2017-12-24 19:19 UTC, 1st1 commented on Lib/test/test_generators.py
> +@unittest.skipUnless(_testcapi is not None and hasattr(_testcapi,
move hasattr on a new line.

2017-12-27 11:08 UTC, isaiah commented
@1st1 Thanks for your review, I've fixed the style. Just noticed that the CLA robot only checks if there are new commits, because I've signed the CLA after the PR is created.

2018-05-16 08:03 UTC, berkerpeksag approved these changes
LGTM and all of Yury's review comments have been addressed.

2018-05-16 08:05 UTC, merged

2018-05-16 08:05 UTC, miss-islington commented
Thanks @isaiah for the PR, and @berkerpeksag for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖