bpo-32403: Faster date and datetime constructors
python/cpython pull request #4993
Opened 2017-12-23 20:02 UTC by pganssle

This fixes [bpo-32403](https://bugs.python.org/issue32403) and [bpo-32404](https://bugs.python.org/issue32404). The first one is a performance enhancement, the second is a bugfix.

Using [this script to benchmark the alternate constructors](https://gist.github.com/pganssle/15875840f31be893e7c98958730657bb), I see significant improvements in speed across the board (note that since the subclasses don't take the fast path, they are a reasonable proxy for the speed from *before* this patch). You can see the results on my laptop (using the debug build, not the profiling optimized build) below:

```
Running with N = 10000, k=20
                   |           datetime           |       DateTimeSubclass       
=================================================================================
constructor        |  1416.5  [1463.9 (±71) ns]   |  1494.8  [1569.2 (±119) ns]  
fromordinal        |  1081.5  [1117.2 (±24) ns]   |  2180.7  [2357.3 (±279) ns]  
fromisoformat      |   928.8   [962.5 (±34) ns]   |  2834.8  [3179.7 (±281) ns]  
fromtimestamp      |  1504.3  [1600.9 (±63) ns]   |  3625.1  [3869.6 (±280) ns]  
utcfromtimestamp   |  1178.6  [1281.2 (±172) ns]  |  3242.6  [3445.0 (±205) ns]  
combine            |  1060.1  [1111.0 (±73) ns]   |  2808.7  [3013.0 (±236) ns]  
now                |  1219.3  [1325.0 (±216) ns]  |  3625.5  [3892.7 (±300) ns]  
today              |  4868.5  [5261.0 (±565) ns]  |  7189.5  [7663.0 (±436) ns]  
=================================================================================
                   |             date             |         DateSubclass         
=================================================================================
constructor        |  974.5   [1010.1 (±39) ns]   |  1114.7  [1298.8 (±229) ns]  
fromordinal        |  1059.7  [1109.4 (±59) ns]   |  1923.1  [2258.8 (±375) ns]  
fromisoformat      |  817.5   [905.1 (±123) ns]   |  1734.1  [2160.8 (±542) ns]  
fromtimestamp      |  1285.4  [1484.7 (±378) ns]  |  2363.6  [3038.6 (±783) ns]  
today              |  4551.7  [4976.6 (±584) ns]  |  5828.9  [6883.9 (±934) ns]  
=================================================================================
```

2017-12-24 17:51 UTC, pganssle commented on Modules/_datetimemodule.c
> +    } else if ((PyTypeObject *)cls == & PyDateTime_DateTimeType ) {
This is the part I'm not sure about. It feels weird to put special-case logic for a specific subclass in the base class logic, *but* it makes the methods that `datetime` inherits and doesn't re-implement itself (`datetime.today` and `datetime.toordinal`) considerably faster when I do this.

Another option might be to do a token implementation of all the `date` methods specifically calling the `new_datetime_subclass_ex`, or explicitly calling `date.themethod` and then using `datetime.combine` on the result.

2018-01-12 18:02 UTC, abalkin requested changes

2018-01-12 18:02 UTC, abalkin commented on Modules/_datetimemodule.c
> +    if ( (PyTypeObject *)cls == & PyDateTime_DateType ) {
Please try to follow the code style used in the rest of the file.  We don't leave space between `&` and the variable or inside the parentheses.

2018-01-12 18:02 UTC, abalkin commented on Modules/_datetimemodule.c
> +    } else if ((PyTypeObject *)cls == & PyDateTime_DateTimeType ) {
I don't see a problem here.

2018-01-16 18:06 UTC, abalkin approved these changes

2018-01-16 18:06 UTC, merged