bpo-32411: IDLE: Remove sorting by line number in browser.py
python/cpython pull request #5011
Opened 2017-12-25 23:56 UTC by csabella

Since the input dictionary is created in line number and dictionaries are guaranteed to be in insertion order, the sort is no longer needed.

2018-01-02 19:33 UTC, merwok commented on Misc/NEWS.d/next/IDLE/2017-12-25-18-48-50.bpo-32411.vNwDhe.rst
> +In browser.py, remove extraneous sorting by line number since dictionary was
`browser` is not a top-level module, I think this entry should mention `idlelib.browser` or `the IDLE xyz plugin`.

2018-05-20 23:25 UTC, terryjreedy requested changes
The requested 'change' is to wait for circumstances to change ;-).

2019-06-01 16:59 UTC, rhettinger commented
LGTM.

2019-06-01 20:19 UTC, terryjreedy approved these changes

2019-06-01 21:03 UTC, merged

2019-06-01 21:03 UTC, miss-islington commented
Thanks @csabella for the PR, and @terryjreedy for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2019-06-01 23:37 UTC, csabella commented
@terryjreedy, thank you!