Ensure two bytes objects of zero length compare equal
python/cpython pull request #5021
Opened 2017-12-27 15:01 UTC by jonathanunderwood

With the current logic in `Objects/bytesobject.c` in the function `bytes_compare_eq` can be the case that zero length bytes object object created in an extension module like this:

```c
val = PyBytes_FromStringAndSize (NULL, 20);
Py_SIZE(val) = 0;
```

won't compare equal to `b''` because the memory is not initialized, so the first two bytes won't be equal. Nonetheless, the Python interpreter does return `b''` for `print(repr(val))`, so this behaviour is very confusing. To get the correct behaviour, one would have to initialize the memory:

```c
val = PyBytes_FromStringAndSize (NULL, 20);
c = PyBytes_AS_STRING (val);
c[0] = '\0';
Py_SIZE(val) = 0;
```

This PR ensures that two zero length byte objects always compare equal irrespecitve of whether the memory has been initialized for either object.

2017-12-27 15:01 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-12-27 15:32 UTC, jonathanunderwood commented
Have now signed the CLA, in case it matters.

2018-09-22 10:31 UTC, jonathanunderwood commented
I don't think this fix merits a NEWS item, does it?

2019-02-04 11:13 UTC, jdemeyer requested changes

2019-02-04 11:13 UTC, jdemeyer commented on Objects/bytesobject.c
>      if (a->ob_sval[0] != b->ob_sval[0])
Why not just drop this `(a->ob_sval[0] != b->ob_sval[0])` check? That would be simpler and also solve your problem.

2019-04-02 21:54 UTC, brettcannon commented
For any other core devs, there is some debate on the issue tracker about changing these semantics.

2020-10-22 02:37 UTC, closed without merging