bpo-32469: Improve representation of the coroutines
python/cpython pull request #5068
Opened 2017-12-31 22:13 UTC by tarasmatsyk

Current representation:
<coroutine object f at 0x7f86c9733790>

A goal is to display more information:
<coroutine at 0x7f86c9733790, running, file "/home/antoine/cpython/default/Lib/logging/__init__.py", line 123, code getLogger>

2017-12-31 22:13 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-12-31 22:13 UTC, tarasmatsyk commented
Note: SLA is in the progress.

2017-12-31 22:29 UTC, pitrou commented
Hi @tarasmatsyk,

I think you misunderstood the enhancement request. What I mean is the repr() of actual generator objects, for example:
```
>>> 
>>> def g():
...     yield 1
... 
>>> g()
<generator object g at 0x7f80eb781ad8>
>>> async def f():
...     await None
... 
>>> f()
<coroutine object f at 0x7f80eb781b80>
```

2017-12-31 22:29 UTC, pitrou commented
I'm also not sure what `GeneratorWrapper` is for, it's the first time I see it. @1st1

2018-01-01 08:00 UTC, tarasmatsyk commented
I see, anyway I would be happy to see the right solution or if no one comes up with it - I might be able to figure it out on my own. I will wait to get a response regarding `GeneratorWrapper` and will close this PR.

2018-01-01 08:45 UTC, 1st1 commented
GeneratorWrapper is what generator-like objects (like generators compiled with Cython) are wrapped with to become awaitables.

2018-01-01 08:48 UTC, 1st1 requested changes

2018-01-01 08:48 UTC, 1st1 commented on Lib/types.py
> +        return '<coroutine at %s, %s, file %s, line %s, code %s>' % (
We can't just use 'coroutine' here, that would make it harder to debug things. I propose to use 'coroutine-like-object', which is a bit verbose but readable.

2018-01-01 11:37 UTC, tarasmatsyk commented
@pitrou, thanks for the hint, I have updated coroutine and generator representation. I am happy to make any other changes if I missed something.

@1st1, yep, that makes much more sense, a requested change has been applied.

2018-01-05 14:31 UTC, tarasmatsyk commented
An SLA is finally approved and all required changes have been made. If I missed anything - let me know, would be happy to update.

A code phrase:
I have made the requested changes; please review again.

2018-06-30 14:10 UTC, ahcub commented
nice work! 
looking forward to seeing those changes merged

2021-05-03 21:29 UTC, closed without merging