Add 2018
python/cpython pull request #5069
Opened 2018-01-01 00:02 UTC by m1guelpf

TO DO:

- [x] Wait to the next year (100% done, depends on timezone)
- [ ] Merge!

:octocat:

2018-01-01 00:02 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-01-01 05:18 UTC, duttaditya18 commented
@m1guelpf Signing the PSF Contributor Agreement is required for contributing to Python.

2018-01-01 13:13 UTC, m1guelpf commented
@the-knights-who-say-ni @duttaditya18 Signed!

2018-01-01 21:34 UTC, timgraham reviewed
There are more places to update based on last year's commit: e527dd34bc4d894b469f48af9369b0f8e1138ea9.

2018-01-01 21:34 UTC, timgraham commented on LICENSE
> +2011, 2012, 2013, 2014, 2015, 2016, 2017 2018 Python Software Foundation; All Rights
Missing a comma after 2017 and it looks like "Rights" should flow to the next line to maintain consistent wrapping.

2018-01-01 21:43 UTC, rooterkyberian requested changes

2018-01-01 21:43 UTC, rooterkyberian commented on LICENSE
> +2011, 2012, 2013, 2014, 2015, 2016, 2017 2018 Python Software Foundation; All Rights
missing comma
this addition makes also this line only one that has more than 80 characters (newline characters excluded)

Not sure if this is fine in legal-speak, but chaning it to `2001-2018` would make this thing much less of a hassle to maintain and read.

2018-01-03 06:26 UTC, duttaditya18 commented
@m1guelpf I would suggest you to squash the commits.

2018-01-03 09:36 UTC, asvetlov commented
@duttaditya18 Pull Request is squashed on merging anyway.

2018-01-03 09:47 UTC, duttaditya18 commented
@asvetlov Oh yeah! Forgot that!

2018-01-03 19:12 UTC, m1guelpf commented
@duttaditya18 Done!

2018-01-04 04:14 UTC, duttaditya18 commented
@m1guelpf Awesome!!

2018-01-04 04:19 UTC, duttaditya18 commented
@m1guelpf Awesome! Now wait for the merger!

2018-01-05 11:50 UTC, asvetlov commented
Done by @benjaminp in #5094 #5104 #5105

2018-01-05 11:50 UTC, closed without merging

2018-01-05 11:52 UTC, duttaditya18 commented
@m1guelpf Dang dude! Couldn't get your contribution to Python. Keep trying though.