advance copyright years to 2018
python/cpython pull request #5094
Opened 2018-01-04 07:53 UTC by benjaminp

2018-01-04 08:00 UTC, tinomist commented
thanks man um what do i do now or what would u do

2018-01-04 08:10 UTC, ned-deily requested changes
Also Doc/copyright.rst?  Otherwise LGTM.  Thanks!

2018-01-05 06:34 UTC, merged

2018-01-05 06:34 UTC, miss-islington commented
Thanks @benjaminp for the PR 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6.
🐍🍒⛏🤖

2018-01-05 06:35 UTC, miss-islington commented
Sorry, @benjaminp, I could not cleanly backport this to `2.7` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker 65f2a6dcc2bc28a8566b74c8e9273f982331ec48 2.7
                            ```