bpo-8243: Doc patch for curses.window.addstr and curses.window.addch
python/cpython pull request #5179
Opened 2018-01-14 03:52 UTC by jcrotts

bpo-8243: Doc patch for curses.window.addstr and curses.window.addch

Added documentation notes for two functions in curses.window . 
This is my first pr, please let me know what else I need to do.

2018-01-30 12:55 UTC, matrixise requested changes

2018-01-30 12:55 UTC, matrixise commented on Doc/library/curses.rst
> +      or pad will cause an exception to be raised after the character is printed.
replace `after the caracter is printed` by `after the string is printed`

2018-01-30 12:56 UTC, matrixise commented
Could you rebase your commits ? 5 commits should become 1 commit. Thank you,

2018-01-31 01:42 UTC, jcrotts commented
Sure, I will make the change, and then rebase.

2018-01-31 02:24 UTC, jcrotts commented
Okay, I made the changes, and squashed my commits.

Thanks for the help.

2018-04-07 01:27 UTC, merged

2018-04-07 01:27 UTC, miss-islington commented
Thanks @jcrotts for the PR, and @ned-deily for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6, 3.7.
🐍🍒⛏🤖