bpo-31900: Fix decimal for LC_NUMERIC != LC_CTYPE
python/cpython pull request #5191
Opened 2018-01-15 15:40 UTC by vstinner

Fix decimal.Decimal formatter when the LC_NUMERIC locale encoding is
different than the LC_CTYPE encoding: reuse
_Py_GetLocaleconvNumeric() to decode localeconv() correctly, set
tempoarily setlocale() if needed.

2018-01-15 22:31 UTC, vstinner commented
@skrah: So, what do you think?

2018-01-15 23:19 UTC, skrah requested changes
The patched version introduces errors in deccheck.py.  The formatting code is tricky, which is why I wasn't too enthusiastic about the patch to begin with.

I'd prefer to do nothing here.

2018-01-23 14:03 UTC, vstinner commented
> The patched version introduces errors in deccheck.py.

Oh. My type == 'n' test doesn't work, libmpdec replaces 'n' with 'g'. I don't know how I missed this.

I modified my PR to add a new mpd_spec_t.locale field.

2018-01-23 14:03 UTC, vstinner commented
I have made the requested changes; please review again.

2018-01-30 11:13 UTC, vstinner commented
@skrah: I fixed my obvious mistake. Would you mind to look again to my change? Is it now ok to merge it?

2018-01-30 11:48 UTC, skrah commented
@vstinner I'll look at it when I have time. I still think this is nice-to-have, but very low priority.

2018-02-01 02:34 UTC, closed without merging