bpo-29708: allow to force hash-based pycs
python/cpython pull request #5200
Opened 2018-01-16 10:10 UTC by bmwiedemann

allow to force hash-based pycs
using the well-established `SOURCE_DATE_EPOCH` environment variable
to allow for reproducible builds of python packages.

See https://reproducible-builds.org/ for why this is good.

This implements variant 1 from @brettcannon

note: not tested yet

2018-01-16 19:35 UTC, brettcannon requested changes
Just a request to expand the documentation and tweak the test to follow what is already there for hash-based .pyc files.

2018-01-16 19:35 UTC, brettcannon commented on Doc/library/py_compile.rst
> +      be forced to CHECKED_HASH.
This should also be mentioned in the main documentation. In other words, if the "version changed" note went away the docs should still cover what they need to cover. So this should say something like "Detecting the :envvar:`SOURCE_DATE_EPOCH` environment variable to force `CHECKED_HASH` was added."

2018-01-16 19:35 UTC, brettcannon commented on Lib/test/test_py_compile.py
> +        with open(self.pyc_path, "rb") as f:
I would look at https://github.com/python/cpython/blob/9f1b7b93f5f0ef589e7b272e127cacf4ce5d23f1/Lib/test/test_py_compile.py#L125 as an example on how to make this test a little bit more robust in the face of `.pyc` files changing.

2018-01-17 15:44 UTC, bmwiedemann commented
I have made the requested changes; please review again.

2018-01-17 21:26 UTC, brettcannon approved these changes
Just waiting until Friday to merge to give people enough time to comment on the proposed solution. Otherwise the PR LGTM!

2018-01-24 21:26 UTC, merged

2018-01-24 21:26 UTC, brettcannon commented
Thanks for your patience with this issue, @bmwiedemann !