bpo-32603: Deprecation warning on strings used in re module
python/cpython pull request #5255
Opened 2018-01-21 02:23 UTC by pablogsal

2018-01-21 21:33 UTC, csabella commented on Doc/library/re.rst
> +   :exc:`DeprecationWarning` and in the future this will become a :exc:`Syntaxerror`.
Syntaxerror -> SyntaxError

2018-01-21 21:42 UTC, csabella commented
IMHO, I actually thought the warning about the DeprecationWarning and SyntaxError should come in one of the introduction paragraphs since the raw strings are discussed there.

In the paragraph that starts with, `Regular expressions use the backslash character`, maybe a line at the end with something like 'Also, please note that any invalid escape sequences in Python's usage of the backslash now generate a DeprecationWarning and, in the future, a SyntaxError.  This will happen even if it is a valid escape sequence for a regular expression.'

2018-01-22 20:15 UTC, pablogsal commented
Thank you very much @csabella. I have added some lines as you suggested in the introductory paragraphs.

2018-05-15 12:02 UTC, matrixise requested changes

2018-05-15 12:02 UTC, matrixise commented on Doc/library/re.rst
> +usage of the backslash in string literals now generate a DeprecationWarning
Could you use a link to the DeprecationWarning exception like that 
```
:exc:`DeprecationWarning`
```

same for the SyntaxError exception

2018-11-09 15:37 UTC, pablogsal commented
CC: @JulienPalard

2019-01-20 18:57 UTC, merged