bpo-31972: Improve docstrings for pathlib classes
python/cpython pull request #5310
Opened 2018-01-25 05:14 UTC by chason

The classes that inherit from PurePath do not have docstrings,
and therefore inherit the docstrings from PurePath. This is confusing
because a developer may assume that Path works similarly to PurePath,
which of course it doesn't. This adds a docstring to Path as well as
to the other PurePath children that is more indicative of their role.

2018-01-25 05:14 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-01-25 05:29 UTC, chason commented
Not sure why this says my CLA is not signed, I have signed it.

2018-01-25 16:14 UTC, merwok commented on Lib/pathlib.py
> +    """
Thanks for the patch!

In the stdlib we try to follow the guidelines laid out in PEP 257. Mainly, the first line of a docstring should be a very short description that stands alone, and more information follows after a blank line (this is very similar to the recommendations for git commit messages).

Taking inspiration from the rst docs, here the first line could be something like `PurePath subclass for non-Windows systems.`, followed by a blank line then your original text.

2018-01-25 16:15 UTC, merwok requested changes
Style suggestions in comments

2018-01-25 16:18 UTC, merwok commented
Did you put your github username in your bugs.python.org profile?  I think that’s what the bot needs to check your CLA status.

2018-01-26 01:49 UTC, chason commented
I have made the requested changes; please review again

2018-01-26 01:51 UTC, chason commented
Yes, I added my github username but it was just yesterday that I signed the CLA so I think it just hasn't been updated yet.

As for the changes you requested, I've made them. I also updated the existing docstring for class PurePath as it seemed to be within the purview of this bug as well. Let me know if I should leave it the way it was.

2018-01-26 17:35 UTC, merwok approved these changes

2018-02-18 23:36 UTC, merged

2018-02-18 23:36 UTC, miss-islington commented
Thanks @chason for the PR, and @merwok for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6.
🐍🍒⛏🤖

2018-02-18 23:39 UTC, miss-islington commented
Thanks @chason for the PR, and @merwok for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖