bpo-27931adding patch set 3 to master
python/cpython pull request #5329
Opened 2018-01-26 01:51 UTC by jayyyin

https://bugs.python.org/issue27931

2018-01-26 01:51 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-01-26 02:17 UTC, bitdancer requested changes

2018-01-26 02:17 UTC, bitdancer commented on Misc/NEWS.d/next/Library/2018-01-25-21-04-11.bpo-27931.e4r52t.rst
> +Email parse IndexError <""@wiarcom.com> patch made by xiang.zhang
I suggest: Fix email address header parsing error when the username is an empty quoted string.  Patch by xian.zhang.

2018-01-26 02:25 UTC, jayyyin commented
did the change to the news file as requested

2018-01-26 02:25 UTC, zhangyangyu commented on Misc/NEWS.d/next/Library/2018-01-25-21-04-11.bpo-27931.e4r52t.rst
> +Fix email address header parsing error when the username is an empty quoted string. Patch by xian.zhang.
Hmm, my name is Xiang Zhang.

2018-01-26 02:27 UTC, jayyyin commented
fixed the typo in the name, sorry for not noticing the mistake

2018-01-29 18:06 UTC, bitdancer approved these changes

2018-01-29 18:07 UTC, merged

2018-01-29 18:07 UTC, miss-islington commented
Thanks @jayyyin for the PR, and @bitdancer for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6.
🐍🍒⛏🤖