bpo-32657 Removing mutable entry from send_message
python/cpython pull request #5334
Opened 2018-01-26 03:40 UTC by chason

The signature for send_message included mutable defaults for two sets of
options, mail_options and rcpt_options. Additionally, the default for
rcpt_options was a dictionary, not a list. These have now been changed
to have a default of None, which is set to a dictionary during function
execution.

2018-01-26 03:40 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-01-26 03:41 UTC, chason commented
I also have a test written for this, but it requires the changes from #5314 to work properly

2018-01-26 04:17 UTC, bitdancer requested changes

2018-01-26 04:17 UTC, bitdancer commented on Misc/NEWS.d/next/Library/2018-01-26-12-34-01.bpo-32657.gYp2Zz.rst
> +Removing mutable defaults for mail_options and rcpt_options from
Removed

2018-01-26 04:30 UTC, chason commented
I have made the requested changes; please review again

2018-01-26 14:57 UTC, csabella commented
The `smtplib` docs page needs to be updated to reflect the changes.

2018-02-06 07:56 UTC, matrixise commented
Hi @chason, good catch from @csabella , you have to update the documentation, after that, we will continue to review your PR. Have a nice day,

2018-02-06 08:41 UTC, chason commented
Hi @matrixise I added that documentation change after @csabella noted it. Thanks.

2018-08-20 03:03 UTC, chason commented
Hi guys, I know everyone is busy but I was hoping someone had a time to review this!

2019-02-22 07:51 UTC, methane commented
I think this is fixed by #8554.

2019-02-22 07:51 UTC, closed without merging