bpo-30622: Change NPN detection
python/cpython pull request #5343
Opened 2018-01-26 11:15 UTC by Sp1l

This aligns the way NPN support is detected in the code. It now works the same way that ALPN support is detected and used.

2018-01-26 11:15 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-01-26 11:27 UTC, tiran commented
Thanks! I have another NPN related fix in #5253. Are you ok if I merge your improvements with mine and give you credit for your work?

2018-01-26 11:28 UTC, Sp1l commented
@tiran No problemo. Let me check #5253 
You're OK with the general direction on the NPN feature detection?

2018-01-26 11:54 UTC, Sp1l commented
@tiran Merged your changes into this PR.

CLA has been signed based on my bugs.python.org id 'spil'

2018-01-26 14:20 UTC, tiran commented
Awesome! Thanks! 👍 
 
* The-knights-who-say-ni don't see your CLI yet. It may take a day or two until it is processed by a human being.
* You have to regenerate the argument clinic, please run ``make clinic`` and push the modified header file.
* I'm currently travelling. Your fix may not land in 3.7.0-beta 1.

2018-02-24 19:42 UTC, tiran requested changes
Please rebase your patch and simplify the check as explained.

2018-02-24 19:42 UTC, tiran commented on Modules/_ssl.c
> +# ifdef OPENSSL_NO_NEXTPROTONEG
I think it is safe to simplify the check even further. NPN is available if ``TLSEXT_TYPE_next_proto_neg`` and ``OPENSSL_NO_NEXTPROTONEG`` is not defined.

```
#ifdef OPENSSL_NO_NEXTPROTONEG
#  define HAVE_NPN 0
#elif defined(TLSEXT_TYPE_next_proto_neg)
#  define HAVE_NPN 1
#else
#  define HAVE_NPN 0
# endif
```

2018-02-24 20:21 UTC, tiran commented
I have resolved the merge conflict through GH ui. Tests are still failing because the clinic file is outdated.

2018-02-24 21:14 UTC, tiran commented
Somehow I messed up your PR with Github's UI. Since 3.7.0b2 is immanent, I created PR #5859 and gave you credit as co-author.

2018-02-24 21:14 UTC, closed without merging