issue 32682: test_zlib improve version parsing
python/cpython pull request #5347
Opened 2018-01-26 16:02 UTC by pmp-p

fix odd version number parsing of zlib found at least on some android versions.

https://bugs.python.org/issue32682

2018-01-26 16:02 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-01-26 16:26 UTC, vstinner requested changes

2018-01-26 16:26 UTC, vstinner commented on Lib/test/test_zlib.py
> +        if zlib.ZLIB_RUNTIME_VERSION.find('-')>=0:
"-" in zlib.ZLIB_RUNTIME_VERSION would be simpler

2018-01-26 16:26 UTC, vstinner commented on Lib/test/test_zlib.py
> +            v = (zlib.ZLIB_RUNTIME_VERSION + ".0").split(".", 4)
You should factorize the code between the if/else block. Something like:

v = zlib.ZLIB_RUNTIME_VERSION
if "-" in v:
  v = v.split('-',1)[0]
v = (v + ".0").split(".", 4)

2018-01-26 17:55 UTC, pmp-p reviewed
maybe this way

2018-01-26 18:03 UTC, pmp-p commented
or this way ? ( sorry learning interface :p )

2018-01-26 18:17 UTC, pmp-p reviewed
maybe a line too long

2018-02-04 20:15 UTC, zware requested changes
Just a couple of minor fixes needed.

2018-02-04 20:15 UTC, zware commented on Lib/test/test_zlib.py
> +                and ( v[3] >= 5 )
Why not `supports_wbits_0 = v >= (1, 2, 3, 5)`?

2018-02-04 20:15 UTC, zware commented on Lib/test/test_zlib.py
> +        v = tuple( map( int, v ) )
No need for the extra spaces around `(` or `)`; `v = tuple(map(int, v))`.  (See PEP 8.)

2018-02-04 20:15 UTC, zware commented on Lib/test/test_zlib.py
> +        del v
No need for `del v`.

2018-02-05 17:40 UTC, pmp-p commented
I have made the requested changes; please review again

2018-02-18 04:06 UTC, zware approved these changes
LGTM.

2018-02-18 11:12 UTC, serhiy-storchaka approved these changes

2018-02-19 03:45 UTC, merged

2018-02-19 03:45 UTC, miss-islington commented
Thanks @pmp-p for the PR, and @zware for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.6, 3.7.
🐍🍒⛏🤖

2018-02-19 03:47 UTC, miss-islington commented
Sorry, @pmp-p and @zware, I could not cleanly backport this to `2.7` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker 4c7108a77144493d0aa6fc0105b67d3797e143f5 2.7
                            ```

2018-02-19 03:53 UTC, zware commented
@serhiy-storchaka This doesn't appear to need to go back to 2.7; would you mind taking care of that one way or the other?  I would vote for the simple solution of just removing the label :)