Mark job as done
python/cpython pull request #5454
Opened 2018-01-30 22:03 UTC by hugobranquinho

In order to know how many jobs are running `ThreadPoolExecutor()._work_queue.unfinished_tasks`

2018-01-30 22:03 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-01-31 05:17 UTC, matrixise commented
Hi @hugobranquinho 

Thank you for your contribution...

but:

1. There is no Bug Report, associated to this PR
2. You didn't sign the CLA from the PSF for your contribution

Please, could you do these steps?

Thank you so much,

2018-03-26 09:22 UTC, serhiy-storchaka requested changes
Please open an issue on the [bug tracker](https://bugs.python.org/) for discussion.

2018-03-26 09:24 UTC, serhiy-storchaka commented
And the PR should be made to the master branch.

2018-06-07 01:31 UTC, ned-deily commented
@hugobranquinho Thanks for your contribution.  As mentioned above, we require that a proposed change be first brought up in a bugs.python.org issue and that a PR be against the "master" branch, not the 3.6 branch.  Therefore I'm closing this PR against 3.6.

https://devguide.python.org/pullrequest/

2018-06-07 01:31 UTC, closed without merging