bpo-10030: Sped up reading encrypted ZIP files by 2 times.
python/cpython pull request #550
Opened 2017-03-07 15:34 UTC by serhiy-storchaka

2017-03-07 15:58 UTC, freddrake commented
Not sure what @mention-bot is, but hopefully it's not using the NEWS file as a source for location "potential reviewers".

2017-03-07 16:51 UTC, briancurtin requested changes
No tests?

2017-03-07 16:57 UTC, Mariatta commented
@freddrake `Misc/ACKS`, `Misc/NEWS` and `Doc/whatsnew/*.rst` are all excluded from the mention-bot when finding potential reviewers. It's configured here https://github.com/python/cpython/blob/master/.mention-bot#L5-L8

2017-03-07 17:09 UTC, serhiy-storchaka commented
This change doesn't add new API and doesn't change behavior of public API. No new tests are needed.

2017-03-09 17:43 UTC, haypo commented on Lib/zipfile.py
> +def _ZipDecrypter(pwd):
I suggest to rename the parameter to "password".

2017-03-09 17:43 UTC, haypo commented on Lib/zipfile.py
> +# to be able to get data out of such a file.
IMHO it's worth it to add this warning, maybe just as a note, in zipfile documentation.

2017-03-09 18:02 UTC, serhiy-storchaka commented on Lib/zipfile.py
> +def _ZipDecrypter(pwd):
The name "pwd" is used for parameters of public API. It would be better to keep it consistent.

2017-03-09 18:07 UTC, serhiy-storchaka commented on Lib/zipfile.py
> +# to be able to get data out of such a file.
`zipfile` doesn't support creating encrypted ZIP archives. It just supports reading encrypted ZIP archives created by other programs. Thus this warning doesn't have relation to the use of the `zipfile` module. It has relation to the cause why encrypting is not implemented. It is useful for `zipfile` developers, not users.

2017-03-09 21:17 UTC, haypo commented on Lib/zipfile.py
> +def _ZipDecrypter(pwd):
Oh ok, in this case it's fine :-)

2017-03-09 21:17 UTC, haypo commented on Lib/zipfile.py
> +# to be able to get data out of such a file.
Ok. Anyway, it's unrelated to your change. I started a thread on security-SIG:
https://mail.python.org/pipermail/security-sig/2017-March/000238.html

2017-03-12 09:11 UTC, serhiy-storchaka commented
Have I satisfied your request @briancurtin? If you meant some specific tests say what tests are needed.

2017-03-30 16:09 UTC, merged