bpo-29619: Convert st_ino using unsigned integer
python/cpython pull request #557
Opened 2017-03-08 08:04 UTC by haypo

bpo-29619: os.stat() and os.DirEntry.inodeo() now convert inode
(st_ino) using unsigned integers.

2017-03-08 08:39 UTC, zhangyangyu approved these changes

2017-03-08 09:03 UTC, serhiy-storchaka requested changes

2017-03-08 09:03 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +    assert(sizeof(st->st_ino) >= sizeof(unsigned long long));
Use `Py_BUILD_ASSERT`.

Should test `sizeof(st->st_ino) <= sizeof(unsigned long long)`.

2017-03-08 09:03 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +    assert(sizeof(self->win32_file_index) >= sizeof(unsigned long long));
`sizeof(self->win32_file_index) <= sizeof(unsigned long long)`

2017-03-08 09:21 UTC, haypo commented on Modules/posixmodule.c
> +    assert(sizeof(st->st_ino) >= sizeof(unsigned long long));
Ooops, I wrote my assertion backwards... Fixed, thanks!

2017-03-08 09:21 UTC, haypo commented on Modules/posixmodule.c
> +    assert(sizeof(self->win32_file_index) >= sizeof(unsigned long long));
Fixed.

2017-03-08 09:23 UTC, serhiy-storchaka approved these changes

2017-03-09 16:34 UTC, merged

2017-03-09 16:42 UTC, haypo commented
Ok, let's start with a backport to 3.6: https://github.com/python/cpython/pull/584