Add str property to PurePath in PatLib package
python/cpython pull request #5595
Opened 2018-02-09 11:08 UTC by Arkanayan

Get string representation of Path with path.str instead of str(Path).

#32807

2018-02-09 11:08 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-02-09 12:29 UTC, WildCard65 requested changes

2018-02-09 12:29 UTC, WildCard65 commented on Lib/pathlib.py
> +    str = property(methodcaller('__str__',
methodcaller is redundant here, remove it (and it's import) and just pass __str__ directly as it's function signature matches the one required by property.

2018-02-09 12:31 UTC, WildCard65 commented
To reference a BPO in a Github PR, please modify the PR title to add the following prefix: "bpo-32807" @bedevere-bot will only accept the prefix as lowercase only.

2018-02-10 09:24 UTC, JulienPalard commented
Closing as rejected in b.p.o (`.str` is not a Pythonic way to get a string representation of someting). Thanks @Arkanayan for your time and intentions to enhance Python, appreciated,

2018-02-10 09:24 UTC, closed without merging