bpo-32731: Specify Exception type of getpass.getuser
python/cpython pull request #5616
Opened 2018-02-11 03:26 UTC by fangyi-zhou

2018-02-11 03:26 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


We also demand... [A SHRUBBERY!](https://www.youtube.com/watch?v=zIV4poUZAQo)


Thanks again to your contribution and we look forward to looking at it!

2018-02-12 20:52 UTC, fangyi-zhou commented
I've signed CLA, how do I ask the bot to check again?

2018-05-14 21:52 UTC, matrixise approved these changes
Thank you for your PR, the wording seems fine.

2019-04-17 22:41 UTC, brettcannon requested changes

2019-04-17 22:41 UTC, brettcannon commented on Misc/NEWS.d/next/Documentation/2018-02-11-03-23-36.bpo-32731.eHIUEe.rst
> +Improve documentation of exception raised in :func:`getpass.getuser()`
```suggestion
Improve documentation of exceptions raised in :func:`getpass.getuser()`.
```

2019-04-17 22:41 UTC, brettcannon commented on Doc/library/getpass.rst
> +   :exc:`KeyError` is raised :func:`pwd.getpwuid`.
What is the mention for `pwd.getwuid()` for? Is it to state that it's the function that causes `KeyError` to be raised?

And are there tests that these exception are raised in these scenarios?

2019-12-03 21:20 UTC, closed without merging