bpo-32844: subprocess: Fix a potential misredirection of a low fd to stderr
python/cpython pull request #5689
Opened 2018-02-14 21:16 UTC by izbyshev

When redirecting, subprocess attempts to achieve the following state:
each fd to be redirected to is less than or equal to the fd
it is redirected from, which is necessary because redirection
occurs in the ascending order of destination descriptors.
It fails to do so in a couple of corner cases,
for example, if 1 is redirected to 2 and 0 is closed in the parent.

2018-03-25 19:53 UTC, gpshead requested changes

2018-03-25 19:53 UTC, gpshead commented on Lib/test/test_subprocess.py
> +                self.assertEqual(read_bytes, exp_bytes)
To make debugging failures easier, add a msg= parameter to this assertion that contains the an explanation of the from_fds, to_fds, and skipped_fd configuration that was being tested.

2018-03-25 19:53 UTC, gpshead commented on Lib/test/test_subprocess.py
> +            skipped_fd = next(fd for fd in range(3) if fd not in to_fds)
I believe this works, but it feels like something using sets might be easier to understand?

`({0, 1, 2} - set(to_fds)).pop()` perhaps?

2018-03-25 21:37 UTC, izbyshev commented on Lib/test/test_subprocess.py
> +            skipped_fd = (set(range(3)) - set(to_fds)).pop()
I've used the suggested construct but with `range(3)` instead of `{0, 1, 2}` for consistency with the surrounding code.

2018-03-25 21:41 UTC, izbyshev commented on Lib/test/test_subprocess.py
> +                self.assertEqual([to_fd], read_fds, msg)
I thought that the assertion comparing bytes would be not very friendly even with a message, so I've decided it's not too dangerous to decode them.

2018-03-25 21:43 UTC, izbyshev commented
Thank you for the review! I have made the requested changes; please review again.

2018-03-26 19:48 UTC, gpshead approved these changes

2018-03-26 19:49 UTC, merged

2018-03-26 19:49 UTC, miss-islington commented
Thanks @izbyshev for the PR, and @gpshead for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖