bpo-29762: More use "raise from None".
python/cpython pull request #569
Opened 2017-03-08 21:19 UTC by serhiy-storchaka

This hides unwanted implementation details from tracebacks.

2017-03-09 08:18 UTC, wm75 requested changes
Generally, I think this is a good idea, but only if there is absolutely no loss of information, which happens at least for two of your changes (see comments, there may be others that I've missed)

2017-03-09 08:18 UTC, wm75 commented on Lib/encodings/punycode.py
> +                raise UnicodeError("incomplete punicode string") from None
information about extpos is lost here

2017-03-09 08:18 UTC, wm75 commented on Lib/mailbox.py
> +                "use bytes or a Message instead") from None
information about problematic character in the string is lost

2017-03-09 08:47 UTC, serhiy-storchaka commented on Lib/encodings/punycode.py
> +                raise UnicodeError("incomplete punicode string") from None
Done. And there are other bugs in this codec.

2017-03-09 08:47 UTC, serhiy-storchaka commented on Lib/mailbox.py
> +                "use bytes or a Message instead") from None
Done.

2017-03-09 17:04 UTC, haypo commented
FYI It's hard to review such change, because each change should be carefully reviewed, whereas the change modifies 31 files. So I decided to skip my turn, maybe review it another day :-)

2017-04-05 05:26 UTC, rhettinger commented on Lib/json/tool.py
> +            raise SystemExit(e) from None
I'm note sure about this one.

2017-04-05 05:28 UTC, rhettinger commented
Except for the one noted in the comment, these all look good.

2017-04-05 06:14 UTC, serhiy-storchaka commented on Lib/json/tool.py
> +            raise SystemExit(e) from None
Agree. It just doesn't have any visible effect. The original exception is passes to SystemExit, and `str(e)` is printed to stderr at exit. `__cause__` and `__context__` are ignored.

2017-04-05 06:37 UTC, merged

2017-04-05 06:38 UTC, serhiy-storchaka commented
Thank you for your review @wm75 and @rhettinger.