bpo-32642: adding compatibility for pathlike objects in sys.path
python/cpython pull request #5691
Opened 2018-02-15 05:42 UTC by jayyyin

I'm uncertain if that's all that needs to be done for the code to do what is intended since I'm kind of new to the whole path-like object concept, I've noticed that there's still self.path in the class and recall reading something about removing path attributes from classes, but I've been unable to find documentation on how to add compatibility to something for path-like objects.

2018-03-15 14:11 UTC, jayyyin commented
I'm having issues with my local changes for this PR, I'm unsure why my local machine takes a seemingly infinite amount of time on test_poplib, so again I think something to do with my local environment is causing issues again, any help would be appreciated...

2018-03-15 14:29 UTC, jayyyin commented
https://pastebin.com/q4FKnPZH

the trace for the test_poplib

2019-04-09 23:21 UTC, csabella commented
@jayyyin Please resolve the file conflict.

2019-04-26 22:25 UTC, brettcannon requested changes
Thanks for the PR but this needs tests.

2019-04-26 22:25 UTC, brettcannon commented on Lib/importlib/_bootstrap_external.py
> +            if hasattr(entry, '__fspath__'):
This is unnecessary as `os.fspath()` passes strings through without issue.

2019-04-26 22:25 UTC, brettcannon commented on Misc/NEWS.d/next/Library/2018-02-15-12-52-34.bpo-32642.e4g57h.rst
> +adding compatibility for pathlike objects in sys.path
```suggestion
Add compatibility for path-like objects in sys.path.
Patch by jayyin.
```

2020-01-12 13:27 UTC, csabella commented
The original author of the pull request hasn't been active on this issue for a long time, so I'm going to close it.  This can be reopened or a new pull request can be created for work to continue on the issue.  Thanks!

2020-01-12 13:27 UTC, closed without merging