json.from_file
python/cpython pull request #5735
Opened 2018-02-18 15:17 UTC by JustMaffie

Personally I read JSON from a file very frequently, and its honestly quite annoying how there isn't a built in function for this

2018-02-18 15:17 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-02-18 15:17 UTC, JustMaffie commented
Personally I don't know how the python documentation works, so this still needs documentation.

2018-02-18 23:33 UTC, merwok commented
Hello!  The links in the previous message go to all the useful information about the development process.
In particular, pull requests should be opened in relation to a ticket on bugs.python.org, sometimes after a discussion on the python-ideas mailing list (where you can see if many other people want the same thing, or if they point you to an existing way of doing what you need).

2018-04-10 00:10 UTC, chadmiller-amzn requested changes

2018-04-10 00:10 UTC, chadmiller-amzn commented on Lib/json/__init__.py
> +        data = _data
What's going on here?! You copy the file object out, then the `with` closes it (hopefully), then you try to read from the closed file?

2018-04-10 15:35 UTC, merwok commented
Please discuss this new feature proposal on python-ideas and reopen a pull request if there is agreement on its usefulness!

2018-04-10 15:35 UTC, closed without merging