bpo-32843: Additional changes to test.support docs
python/cpython pull request #5774
Opened 2018-02-20 16:19 UTC by csabella

2019-05-17 18:29 UTC, vstinner approved these changes
LGTM. Just the disable_faulthandler() doc is wrong.

2019-05-17 18:29 UTC, vstinner commented on Doc/library/test.rst
> +   with ``-W/--verbose3``.
Well, no. The purpose of this context manager is to disable temporarily faulthandler.

2019-09-11 13:42 UTC, matrixise commented
@csabella Could you update your PR? Thanks

2019-09-13 16:28 UTC, JulienPalard requested changes

2019-09-13 16:28 UTC, JulienPalard commented on Doc/library/test.rst
> +   A non-ASCII character encodable by :func:`os.fsencode`.  The function
"The function" may be a bit opaque here. Maybe replace `The function` by `Choosen at import time` (which breaks the rest of the sentence)?

2019-09-13 16:28 UTC, JulienPalard commented on Doc/library/test.rst
> +    Set to a non-ASCII filename containing several unicode characters.
Looks redundent to me (*non-ASCII* and *several unicode*). Also an "unicode character" may be one in the ASCII table.

Maybe "Set to a non-ASCII filename." is enough? In contrast this one is *not* tested against being fsencodable.

2019-09-13 16:28 UTC, JulienPalard commented on Doc/library/test.rst
> +   This makes a copy of ``sys.path``, appends any directories given
```:data:`sys.path` ```  was creating a link to it, ``` ``sys.path`` ``` won't, why changing it? (multiple occurrences following)

2020-11-03 22:41 UTC, JulienPalard commented
@csabella Hi Cheryl, long time no see, what about this PR? It accumulated a few conflicts :-(

2022-05-08 22:32 UTC, JelleZijlstra reviewed
This unfortunately has a lot of conflicts now, enough that it's easier to start from scratch. I'll close this and open a new

2022-05-08 22:32 UTC, JelleZijlstra commented on Doc/library/test.rst
> +.. data:: HOST
This no longer exists on main

2022-05-08 22:32 UTC, JelleZijlstra commented on Doc/library/test.rst
> +   A non-ASCII character encodable by :func:`os.fsencode`.  The function
I think the extra text is unnecessary here; we don't need to explain how the object is derived, only what it's for.

2022-05-08 22:32 UTC, JelleZijlstra commented on Doc/library/test.rst
> -.. data:: max_memuse
I think it's better to keep this documented for symmetry with `real_max_memuse`.

2022-05-08 22:32 UTC, JelleZijlstra commented on Doc/library/test.rst
> +.. function:: strip_python_stderr(stderr)
This was removed in 3.9.0a2

2022-05-08 22:32 UTC, closed without merging