bpo-32972: Add coroutine support to unittest
python/cpython pull request #5938
Opened 2018-02-28 18:45 UTC by pdxjohnny

2018-02-28 18:45 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-03-06 18:05 UTC, 1st1 requested changes
This needs more discussion in https://bugs.python.org/issue32972

2018-03-12 19:58 UTC, PetterS commented on Lib/unittest/case.py
> +        if inspect.iscoroutinefunction(meth):
This does not work if the method is decorated with @unittest.mock.patch.

2018-03-12 20:04 UTC, PetterS reviewed
n/a

2018-06-07 01:10 UTC, ned-deily commented
@pdxjohnny Sorry that the discussion about this issue has languished, especially since the submitting of an alternate PR.  However, I see your PR was created against the 3.6 branch; for enhancements, we require that PRs be against the "master" branch.  So I'm going to close this PR and you can decide how you want to proceed, either submitting an updated PR against "master" or perhaps commenting on the other open PR.  In any case, thanks for getting the discussion started and submitting this PR!

https://devguide.python.org/pullrequest/

2018-06-07 01:10 UTC, closed without merging

2018-06-07 01:13 UTC, pdxjohnny commented
I'm glad there has been discussion about it. Thank you!

On Wed, Jun 6, 2018, 6:10 PM Ned Deily <notifications@github.com> wrote:

> Closed #5938 <https://github.com/python/cpython/pull/5938>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/cpython/pull/5938#event-1667445074>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFrL4UCjapm1cNVtW2kOjgRAH9AaJ8biks5t6H2ggaJpZM4SXJWo>
> .
>