bpo-29782: Use __builtin_clzl for bits_in_digit if available
python/cpython pull request #594
Opened 2017-03-10 10:58 UTC by niklasf

2017-03-10 10:58 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow these steps to rectify the issue:

1. Sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/). The "bugs.python.org username" requested by the form is the "Login name" field in ["Your Details" at b.p.o](https://cloud.githubusercontent.com/assets/2680980/23276970/d14a380c-f9d1-11e6-883d-e13b6b211239.png)
2. **Wait at least one US business day** and then check the "Contributor form received entry under "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
3. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-03-10 18:31 UTC, mdickinson requested changes
Some comments left on the bpo issue. In brief:
- configuration decisions (deciding whether __builtin_clz is available and does the right thing) should be moved into the configuration machinery.
- the code currently assumes that `digit` is the same as `unsigned long`. That's not always the case.
- once the above issues are addressed, we still need to weigh any speed advantage against the costs in terms of maintainability, portability, readability.

2017-03-10 18:36 UTC, mdickinson commented
> the code currently assumes that digit is the same as unsigned long

Ah, no. I see. This should work whenever `digit` is no larger than `unsigned long`, thanks to the implicit type conversion. However, that's probably wasteful in the majority of cases; on many (most?) machines, we should be able to use `clz` rather than `clzl`, and it may be faster. And while it's probably true that on all current platforms `digit` is no larger than `unsigned long`, that's not an assumption we should hardwire in unnecessarily.

2017-03-10 22:56 UTC, niklasf commented
* Making an extra version for 16bit does not seem to be significantly faster, so I settled for `unsigned long`.
* Factored out so that `mathmodule.c` can also take advantage of the function.
* I might need help with the configuration process. Checking `__GNUC__` does not seem uncommon, but is this the place to do it? Note that `__GNUC__` is also defined by clang.
  I created a new source/header pair which might not be the way to go. Should the header contents go to `pyport.h` as you suggested? Where to put the C fallback?

2017-03-27 15:36 UTC, vstinner requested changes

2017-03-27 15:36 UTC, haypo commented on Python/pyintrinsics.c
> +int bit_length(unsigned long d) {
Please rename the function to _Py_bit_length().

Why the result is signed? Why not unsigned int?

2017-03-27 15:36 UTC, haypo commented on Include/pyintrinsics.h
> +#if defined(__GNUC__)
Is the builtin available in old GCC versions? Any idea when the function was added?

2017-03-27 15:36 UTC, haypo commented on Include/pyintrinsics.h
> +    return d ? (8 * sizeof(unsigned long) - __builtin_clzl(d)) : 0;
would it be possible to avoid the conditional code?

2017-03-27 15:36 UTC, haypo commented on Include/pyintrinsics.h
> +#include <intrin.h>
Do we need the following pragma?
#pragma intrinsic(_BitScanReverse)

2017-03-28 16:10 UTC, niklasf commented on Include/pyintrinsics.h
> +#if defined(__GNUC__)
[gcc 3.4](https://gcc.gnu.org/onlinedocs/gcc-3.4.6/gcc/Keyword-Index.html#Keyword-Index). I made the guard more precise. It also works for clang.

Btw. while looking how this is usually done in Python I found a typo that would affect gcc 3.x: https://github.com/python/cpython/blob/master/Include/pymacro.h#L56 should say `__GNU*C*_MINOR__`. I'll make a seperate PR.

2017-03-28 16:12 UTC, niklasf commented on Include/pyintrinsics.h
> +    return d ? (8 * sizeof(unsigned long) - __builtin_clzl(d)) : 0;
Unfortunately I don't think so. `__builtin_clzl(0)` is undefined or rather has different behavior on various processors.

2017-03-28 16:14 UTC, niklasf commented
@haypo Thanks for the review. I updated the PR based on your comments.

2017-04-26 21:50 UTC, haypo commented
http://bugs.python.org/issue29782 has been closed as REJECTED.

2017-04-26 21:50 UTC, closed without merging