bpo-32933: Implement dunder iter method on mock_open
python/cpython pull request #5974
Opened 2018-03-04 14:56 UTC by TonyFlury

2018-03-04 14:56 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-03-04 15:18 UTC, TonyFlury commented
I have signed the CLA - 11:10 GMT 4th March 2018 - not sure how often the bot runs

2018-04-29 12:21 UTC, gst approved these changes
LGTM

2018-04-29 14:22 UTC, 1st1 requested changes
The PR looks OK overall. The code formatting needs to be fixed in one place, and I also suggest to make code a bit more DRY, which should improve its readability.

2018-04-29 14:22 UTC, 1st1 commented on Lib/unittest/mock.py
> +            yield line
Can you refactor `def _readline_side_effect():` to use this new method for clarity:

```python
     def _readline_side_effect():
         yield from _iter_side_effect()
         while True:
              yield type(read_data)()
```

2018-04-29 14:22 UTC, 1st1 commented on Lib/unittest/test/testmock/testmock.py
> +        mocked_open = mock.mock_open(read_data='Remarkable Bird\nThe Norwegian Blue\nBeautiful Plumage')
This line is too long: trim your code to fit in 79 characters.

2018-04-29 17:49 UTC, TonyFlury commented
I have made the requested changes; please review again.

2018-04-30 20:07 UTC, 1st1 approved these changes

2018-04-30 20:08 UTC, 1st1 commented
Please add a NEWS entry (using the `blurb` tool). CI needs to be fixed too before we can merge this.

2018-04-30 21:53 UTC, TonyFlury commented
I have made the requested changes; please review again.

2018-06-16 23:12 UTC, TonyFlury commented
Is this approved or not - I have made the final changes asked for - even those it was already approved at that point. Can this be merged or not ?

2018-06-22 21:39 UTC, ned-deily commented
@voidspace, @rbtcollins Care to review this?  Should it be backported?

2018-07-09 16:26 UTC, berkerpeksag requested changes

2018-07-09 16:26 UTC, berkerpeksag commented on Doc/library/unittest.mock.rst
> +
Please remove this unrelated line.

2018-07-09 16:26 UTC, berkerpeksag commented on Lib/unittest/test/testmock/testmock.py
> +    def test_mock_open_dunder_iter_issue_32933(self):
No need to add the issue number to the test name.

2018-07-09 16:26 UTC, berkerpeksag commented on Lib/unittest/test/testmock/testwith.py
> +    def test_dunder_iter_data(self):
Style nit: I'd prefer one empty line as you already did, but we should be consistent and follow the existing style in the file.

2018-07-09 16:26 UTC, berkerpeksag commented on Lib/unittest/test/testmock/testwith.py
> +        # Added to test Issue 32933
No need to mention the issue number here too.

2018-07-09 16:26 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2018-04-30-22-43-31.bpo-32933.M3iI_y.rst
> +unittest.mock.mock_open now supports iteration over the file contents.
unittest.mock.mock_open -> :func:\`unittest.mock.mock_open\`

2018-07-09 16:26 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2018-04-30-22-43-31.bpo-32933.M3iI_y.rst
> +unittest.mock.mock_open now supports iteration over the file contents.
Please add "Patch by Your Name.".

2018-07-09 16:29 UTC, berkerpeksag commented on Lib/unittest/test/testmock/testwith.py
> +            result = h.readline()
Could you add another `h.readline()` call and check that it returns an empty string?

2018-07-09 16:47 UTC, TonyFlury commented on Lib/unittest/test/testmock/testmock.py
> +    def test_mock_open_dunder_iter_issue_32933(self):
I was following the style of the other test methods in the same file - which is better ?

2018-07-09 17:41 UTC, berkerpeksag commented on Lib/unittest/test/testmock/testmock.py
> +    def test_mock_open_dunder_iter_issue_32933(self):
IMO, the version without the issue number is better.

2018-07-09 22:13 UTC, TonyFlury commented
I have made the requested changes; please review again

2018-07-10 00:20 UTC, TonyFlury commented
I have made the requested changes; please review again

2018-09-12 21:34 UTC, berkerpeksag approved these changes

2018-09-12 22:21 UTC, merged

2018-09-14 17:03 UTC, miss-islington commented
Thanks @TonyFlury for the PR, and @berkerpeksag for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖