bpo-28955 : Clarified comparisons between Nan and number in reference…
python/cpython pull request #5982
Opened 2018-03-05 08:55 UTC by TonyFlury

… documentation

2018-03-05 08:55 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-03-05 08:56 UTC, TonyFlury commented
CLA signed - 11:10am GMT - 4th March 2018

2018-04-06 16:48 UTC, berkerpeksag requested changes

2018-04-06 16:48 UTC, berkerpeksag commented on Misc/NEWS.d/next/Documentation/2018-03-05-08-33-00.bpo-28955.-OSvYJ.rst
> +Issue 28955 - Clarified numeric comparisons with NaN. Patch by Tony Flury
We don't require news entries for trivial documentation changes. You can delete this file.

2018-04-06 16:48 UTC, berkerpeksag commented on Doc/reference/expressions.rst
> +  ``float('NaN') < 3`` will return ``False``. This is compliant with IEE 754.
Shouldn't this be IEEE 754?

2018-04-06 16:48 UTC, berkerpeksag commented on Doc/reference/expressions.rst
> +  ``float('NaN') < 3`` will return ``False``. This is compliant with IEE 754.
Style nit: Please start a new sentence with two spaces. See line 1338 for example:

```rst
...
are special.  They are identical to themselves (``x is x`` is true) but
...
```

2018-04-06 17:16 UTC, TonyFlury commented on Doc/reference/expressions.rst
> +  ``float('NaN') < 3`` will return ``False``. This is compliant with IEE 754.
Agreed.

2018-04-06 17:28 UTC, TonyFlury commented
I have made the requested changes; please review again.

2018-09-14 17:44 UTC, berkerpeksag approved these changes

2018-09-14 17:48 UTC, merged

2018-09-14 17:48 UTC, miss-islington commented
Thanks @TonyFlury for the PR, and @benjaminp for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖