bpo-28788: configparser.write() accepts also str as a filename to write to
python/cpython pull request #5999
Opened 2018-03-06 00:06 UTC by mcepl

Fix #28788

2018-03-06 00:07 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-03-06 00:40 UTC, mcepl commented
Could somebody explain me, what's going on with the Windows and not being able to unlink a temporary file? “Another process”??? I don’t understand.

2018-03-11 13:04 UTC, berkerpeksag requested changes
These are my review comments, but you may want to wait @ambv's approval on the idea before addressing them.

2018-03-11 13:04 UTC, berkerpeksag commented on Lib/test/test_configparser.py
> +            os.unlink(f.name)
`support.unlink()` has better support under Windows so it handles issues like the one Terry posted on the python-dev thread better. However, I wonder if there's a better option than `NamedTemporaryFile` (I just woke up so my brain doesn't work yet)

2018-03-11 13:04 UTC, berkerpeksag commented on Lib/configparser.py
> +    def write(self, file, space_around_delimiters=True):
Unfortunately, this is an API change that will break backwards compatibility (for example, `cp.write(fp=...)` won't work.) I would rather keep the old name.

2018-03-11 13:04 UTC, berkerpeksag commented on Doc/library/configparser.rst
> +      That could be either file name or :term:`file
This also needs to be documented as:

```rst
.. versionchanged:: 3.8
   Support for ...
```

2018-03-11 13:04 UTC, berkerpeksag commented on Lib/test/test_configparser.py
> +            os.unlink(f.name)
We can avoid try...finally block if we use [`self.addCleanup()`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.addCleanup).

2018-03-11 13:04 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2018-03-06-01-20-19.bpo-28788.iMieW_.rst
> +of just file handler. If the file with such name already exists its  content
Nitpick: Two spaces before 'content'

2018-03-11 13:04 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2018-03-06-01-20-19.bpo-28788.iMieW_.rst
> +will be removed first.
Please add "Patch by Matěj Cepl.".

2018-03-11 13:04 UTC, berkerpeksag commented on Misc/NEWS.d/next/Library/2018-03-06-01-20-19.bpo-28788.iMieW_.rst
> +``Configparser.write()`` can now accept filename as its parameters instead
\`\`Configparser.write()\`\` -> :meth:\`configparser.ConfigParser.write\` or :meth:\`ConfigParser.write() <configparser.ConfigParser.write>\`

2018-03-11 13:42 UTC, terryjreedy requested changes
I am dubious about the feature, but thought a new contributor should get feedback anyway.
Serhiy is -1 for reasons given on the issue.

2018-03-11 13:42 UTC, terryjreedy commented on Doc/library/configparser.rst
> +      That could be either file name or :term:`file
This can be either a filename  or ...

But see comment on issue.

2018-03-11 13:42 UTC, terryjreedy commented on Misc/NEWS.d/next/Library/2018-03-06-01-20-19.bpo-28788.iMieW_.rst
> +``Configparser.write()`` can now accept filename as its parameters instead
accept a filename as its argument

2018-03-11 13:42 UTC, terryjreedy commented on Misc/NEWS.d/next/Library/2018-03-06-01-20-19.bpo-28788.iMieW_.rst
> +of just file handler. If the file with such name already exists its  content
of just an open file.  ... its content [no double space]

2018-03-11 13:42 UTC, terryjreedy commented on Lib/test/test_configparser.py
> +            os.unlink(f.name)
For whatever reason, this fails 14 times on Windows, with 14 different tempfile names.  I have no idea how this happens.

2018-03-11 13:42 UTC, terryjreedy commented on Lib/test/test_configparser.py
> +                         space_around_delimiters=space_around_delimiters)
To test that cf.write can work given a filename, you must call with the filename.
The fix here would be to replace else to finally with
```
else:
    output = testfile
cf.write(output, ...
```
But see below.

2018-03-11 13:42 UTC, terryjreedy commented on Lib/test/test_configparser.py
> +            raise
I believe these two lines can be omitted.  `try; ... finally` without except is legal.

2018-03-11 15:41 UTC, mcepl commented
OK, I accept @serhiy-storchaka point: it is probably too much complications for no significant benefit.

2018-03-11 18:21 UTC, mcepl commented
OK, enough of playing.

2018-03-11 18:21 UTC, closed without merging