bpo-33006 - Correct filter doc string to clarify 2nd argument can be iterable
python/cpython pull request #6015
Opened 2018-03-07 09:27 UTC by TonyFlury

2018-04-06 20:56 UTC, ned-deily requested changes

2018-04-06 20:56 UTC, ned-deily commented on Python/bltinmodule.c
> +false are removed.");
While accurate, it seems a bit too verbose for a doc string.  How about using the current Python 3 docstring as a starting point?

>  |  Return an iterator yielding those items of iterable for which function(item)
>  |  is true. If function is None, return the items that are true.

`s/an iterator/a sequence/` and include the 'If iterable is a string or tuple ...' sentence?

2018-04-30 22:39 UTC, TonyFlury commented
I have made the requested changes; please review again.

2019-05-29 01:22 UTC, ned-deily approved these changes
LGTM, thanks for making the changes @TonyFlury.  And thanks for the reminder @csabella!

2019-05-29 01:36 UTC, miss-islington commented
@TonyFlury: Status check is done, and it's a success ✅ .

2019-05-29 01:36 UTC, merged