bpo-33021: Release the GIL during fstat() calls
python/cpython pull request #6019
Opened 2018-03-07 23:07 UTC by nirs

fstat may block for long time if the file descriptor is on a
non-responsive NFS server, hanging all threads. Most fstat() calls are
handled by _Py_fstat(), releasing the GIL internally, but but
_Py_fstat_noraise() does not release the GIL, and most calls release the
GIL explicitly around it.

This patch fixes last 2 calls to _Py_fstat_no_raise(), avoiding hangs
when calling:
- mmap.mmap()
- os.urandom()
- random.seed()

2018-03-11 02:13 UTC, nirs commented
@vstinner, can you review this?

2018-03-11 17:26 UTC, pitrou commented
Hi @nirs, sorry for the delay. @vstinner is currently unavailable, so I'm gonna review this.

2018-03-11 17:30 UTC, pitrou requested changes
Thanks for this. The changes look basically fine to me. The only thing missing is a NEWS entry with a short description of the fix. You should use the [blurb tool](https://pypi.python.org/pypi/blurb) to generate it.

2018-03-11 22:32 UTC, nirs commented
Thanks for the review @pitrou! I have made the requested changes; please review again.

2018-03-11 23:39 UTC, pitrou approved these changes

2018-03-11 23:39 UTC, merged

2018-03-11 23:39 UTC, pitrou commented
Thank you @nirs !

2018-03-20 18:50 UTC, miss-islington commented
Thanks @nirs for the PR, and @pitrou for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6.
🐍🍒⛏🤖

2018-03-20 18:50 UTC, miss-islington commented
Thanks @nirs for the PR, and @pitrou for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖