[2.7] bpo-33021: Release the GIL during fstat() calls (GH-6019)
python/cpython pull request #6020
Opened 2018-03-07 23:14 UTC by nirs

If the file descriptor is on a non-responsive NFS server, calling
fstat() can block for long time, hanging all threads. Most of the calls
release the GIL around the call, but some calls seems to be forgotten.

This patch fixes the last calls, affecting users of:
- imp.load_dynamic()
- imp.load_source()
- mmap.mmap()
- mmapobject.size()
- os.fdopen()
- os.urandom()
- random.seed()

2018-03-11 17:33 UTC, pitrou requested changes
As on the other PR, this looks good on the principle, but you'll need to generate a NEWS entry.

Also, since 2.7 is in maintenance mode, I'm cc'ing our release manager Benjamin to get his approval on this. @benjaminp

2018-03-11 22:37 UTC, nirs commented
Thanks for the review @pitrou! I have made the requested changes; please review again.

2018-03-11 23:41 UTC, pitrou approved these changes

2018-03-11 23:42 UTC, pitrou commented
Thanks for the update. This looks good on the principle. I'll defer to @benjaminp for the backport decision.

2018-03-12 18:41 UTC, benjaminp commented
Releasing the GIL in new places tends to open new and exciting opportunities for reëntrancy bugs, so I'm not sure this is completely safe.

2018-03-12 18:44 UTC, pitrou commented
I'm not sure about reëntrancy bugs, but I agree there may be thread-safetÿ issues on ill-behaving platforms (though for fstat() we already release the GIL in other places).

2018-03-12 18:45 UTC, pitrou commented
Actually, you're right, I remember about someone implementing a FUSE filesystem with Python and there were interesting reëntrancy issues with GIL releasing specifics.

2018-03-14 20:10 UTC, pitrou commented
Ok, I'm closing this PR as rejected.

2018-03-14 20:10 UTC, closed without merging

2018-03-14 20:31 UTC, nirs commented
@benjaminp, we are releasing the GIL on all fstat calls in python 3. Why is this correct and safe in python 3 but no in python 2?

I'm pretty sure that not releasing the GIL is not safe. Try to mmap a file on non-responsive NFS server - do you really want the entire process to hang?

I can extract the mmap.xxx and os.fdopen changes to a separate patch, since the other changes will are much less likely to block (e.g. fstat for /dev/urandom).

2018-03-15 05:31 UTC, benjaminp commented
I'm not sure throwing `Py_BEGIN_ALLOW_THREADS` around every `fstat` call is any better for Python 3. Releasing the GIL around operations on `/dev/urandom` FDs is probably pure overhead, since no actual IO ever ends up happening.

2018-03-17 00:01 UTC, nirs commented
@benjaminp I suggest to continue on the issue, I added more info there.