bpo-29481:  DOC: mark which version typing.Deque added
python/cpython pull request #61
Opened 2017-02-13 03:47 UTC by tacaswell

This is targeted at 3.6, but half of it should be backported to 3.5.

2017-02-13 03:47 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow these steps to help rectify the issue:

1. If you don't have an account on b.p.o, please [create one](http://bugs.python.org/user?@template=register)
2. Make sure your GitHub username is listed in "Your Details" at b.p.o
3. If you have not already done so, please sign the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/)
4. If you just signed the CLA, please **wait at least a day** and then check "Your Details" on [bugs.python.org](https://bugs.python.org/) to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA)
5. Reply here saying you have completed the above steps


Thanks again to your contribution and we look forward to looking at it!

2017-02-13 11:26 UTC, berkerpeksag requested changes
I've re-targeted this to master branch. We can then backport this to 3.6. For 3.5, we'll need a separate PR that adds `.. versionadded:: 3.5.4`.

2017-02-13 11:26 UTC, berkerpeksag commented on Doc/library/typing.rst
> +   .. versionadded:: 3.5.4
For 3.6 docs, we can remove `.. versionadded:: 3.5.4`.

2017-02-13 13:22 UTC, tacaswell commented
Should the 3.5 one also target master?

2017-02-13 13:24 UTC, tacaswell commented
fixed and force-pushed.

I am currently running the CLA by my employer, it may be faster to just have someone else do this (given how minor it is).

2017-02-13 14:41 UTC, berkerpeksag commented
> Should the 3.5 one also target master?

3.5 should be against 3.5 branch, but don't worry about that :) Core developers can do the 3.5 backport.

2017-02-15 13:32 UTC, tacaswell commented
Closing as this can be fixed faster by others than I expect to be able to sign the CLA.

2017-02-15 13:32 UTC, closed without merging