fix unaligned accesses in siphash24()
python/cpython pull request #6123
Opened 2018-03-15 21:25 UTC by DerDakon

The hash implementation casts the input pointer to uint64_t* and directly reads from this, which may cause unaligned accesses. Use memcpy() instead so this code will not crash with SIGBUS on sparc.

https://bugs.gentoo.org/show_bug.cgi?id=636400

2018-03-15 21:25 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-03-26 10:07 UTC, serhiy-storchaka requested changes
Please open an issue on the [bug tracker](https://bugs.python.org/) for discussion.

2018-03-26 16:31 UTC, DerDakon commented
https://bugs.python.org/issue33145

2018-03-26 18:14 UTC, serhiy-storchaka commented on Python/pyhash.c
> +    m = in;
`m` is not needed. Just use `in`.

2018-04-06 23:29 UTC, ned-deily commented
So other than a [NEWS entry](https://devguide.python.org/committing/#what-s-new-and-news-entries), is there anything else that needs to be done for this before merging?

2018-04-07 06:38 UTC, serhiy-storchaka approved these changes
Just a news entry is needed.

2018-05-06 18:41 UTC, DerDakon commented
Ping

2018-05-13 09:40 UTC, serhiy-storchaka commented on Misc/NEWS.d/next/Core and Builtins/2018-04-25-20-44-42.bpo-28055.f49kfC.rst
> +fix unaligned accesses in siphash24()
Start the sentence from the title case, add missed period, and please add "Patch by *yourname*."

2018-05-13 10:24 UTC, DerDakon commented on Misc/NEWS.d/next/Core and Builtins/2018-04-25-20-44-42.bpo-28055.f49kfC.rst
> +fix unaligned accesses in siphash24()
Fixed.

2018-05-13 10:57 UTC, merged

2018-05-13 10:57 UTC, miss-islington commented
Thanks @DerDakon for the PR, and @serhiy-storchaka for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖