bpo-27200: fix
python/cpython pull request #616
Opened 2017-03-11 15:10 UTC by marco-buttu

This PR partially fixes [bpo-27200](https://bugs.python.org/issue27200).  Partially and not completely, because we decided to split the patch in several patches.  This PR is the last but one in the series.  The first one was #240, the second one #401, and the third #604.

To run the doctests (from the `Doc` directory):

```
$ sphinx-build -b doctest . build/doctest \
library/pathlib.rst \
library/shlex.rst \
library/ssl.rst \
library/turtle.rst \
library/weakref.rst
```

2017-03-12 16:55 UTC, marco-buttu commented on Doc/library/decimal.rst
> +
The `setcontext(Context())` in `testsetup` does not guarantee that the tests outside this file get a fresh context.  We need to clean the context at the end of the tests.

2017-04-12 13:31 UTC, berkerpeksag requested changes
I think we also need to following change to ssl examples:

```diff
diff --git a/Doc/library/ssl.rst b/Doc/library/ssl.rst
index 01dbecd..02a0c79 100644
--- a/Doc/library/ssl.rst
+++ b/Doc/library/ssl.rst
@@ -2262,7 +2262,7 @@ SSL versions 2 and 3 are considered insecure and are therefore dangerous to
 use.  If you want maximum compatibility between clients and servers, it is
 recommended to use :const:`PROTOCOL_TLS_CLIENT` or
 :const:`PROTOCOL_TLS_SERVER` as the protocol version. SSLv2 and SSLv3 are
-disabled by default.
+disabled by default. ::
 
    >>> client_context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    >>> client_context.options |= ssl.OP_NO_TLSv1
```

And there are the other failures:

```
**********************************************************************
File "library/ssl.rst", line 421, in newcontext
Failed example:
    timestamp
Expected:
    1515144883
Got:
    1515134083.0
**********************************************************************
File "library/ssl.rst", line 424, in newcontext
Failed example:
    print(datetime.utcfromtimestamp(timestamp))
Expected:
    2018-01-05 09:34:43
Got:
    2018-01-05 06:34:43
```

2017-04-12 13:31 UTC, berkerpeksag commented on Doc/library/decimal.rst
> +
Please leave decimal.rst changes out of this PR and open a separate PR and then ping Stefan Krah.

2017-04-12 13:31 UTC, berkerpeksag commented on Doc/library/shlex.rst
> +   This idiom would be unsafe:
You have already modified this file in #604.

2017-04-12 13:31 UTC, berkerpeksag commented on Doc/library/pathlib.rst
> +Importing the main class:
Please revert this change. The current version looks correct to me and the tests passed when I revert it to use ::.

2017-04-12 16:59 UTC, marco-buttu commented
Thank you very much for your time @berkerpeksag! I made all changes you requested me.  Just one question: you got a `float` from `ssl.cert_time_to_seconds()`.  Is it not a bug in the code?  It is supposed to return both floats and ints?

2017-04-12 21:38 UTC, berkerpeksag commented
I don't know, it's probably worth doing some VCS archaeology :) I built and ran tests in Python 3.4 with an ancient OpenSSL so this might be the culprit.

2017-04-12 21:40 UTC, berkerpeksag commented on Doc/library/ssl.rst
> +disabled by default. ::
I know I suggested this style in my earlier comment, but could you move :: to a new line so we don't lose `git blame` information? This also applies to the changes in Doc/library/pathlib.rst.

2017-04-13 08:44 UTC, marco-buttu commented on Doc/library/ssl.rst
> +disabled by default. ::
Ok, done :-)  Thanks againt @berkerpeksag

2017-04-13 14:17 UTC, berkerpeksag approved these changes

2017-04-13 14:17 UTC, merged

2017-04-13 14:18 UTC, berkerpeksag commented
Thanks!