Fix PEP-8: entire file overhauled for PEP-8.
python/cpython pull request #6179
Opened 2018-03-21 16:36 UTC by toanant

2018-03-21 16:36 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-03-22 10:58 UTC, SylvainDe requested changes

2018-03-22 10:58 UTC, SylvainDe commented on Lib/Cookie.py
>  # Define an exception visible to External modules
I do not quite like this particular change. Maybe the right way to change this is to write this as a docstring...

2018-03-23 12:28 UTC, serhiy-storchaka commented
Usually we do not accept PRs which just snake sources. Especially if it is 2.7 only. If it fixes a real bug, please open an issue on the [bug tracker](https://bugs.python.org/) and try to minimize your patch.

2018-03-23 12:28 UTC, closed without merging