Use `__delitem__` in `clear` with each key
python/cpython pull request #6221
Opened 2018-03-24 22:34 UTC by jakirkham

Instead of using `popitem` to delete each value from a `MutableMapping`, just grab each key and delete it from the `MutableMapping` while it still has a non-trivial length. As `popitem` reads values, which are unused, for a potentially non-trivial cost, it is better to not read the values in `clear` and merely delete each value corresponding to the next key. Thus avoiding any cost associated with reading the value.

2018-03-24 22:34 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-03-26 10:20 UTC, serhiy-storchaka requested changes
Please open an issue on the [bug tracker](https://bugs.python.org/) for discussion.

2018-05-13 11:03 UTC, serhiy-storchaka commented
Closed due to the lack of response.

2018-05-13 11:03 UTC, closed without merging

2018-05-14 18:01 UTC, jakirkham commented
It's certainly reasonable to raise an issue. Unfortunately due to lack of time I have not. Though it would be nice if this sort of change were discussed.