bpo-20104: Improve error handling and fix a reference leak in os.posix_spawn().
python/cpython pull request #6332
Opened 2018-04-01 16:23 UTC by serhiy-storchaka

https://bugs.python.org/issue20104

2018-04-01 16:27 UTC, pablogsal commented
Should I close #6331 in favour of this one?

2018-04-01 18:23 UTC, gpshead requested changes
I made a couple of commits to fixup trivial issues.

2018-04-01 18:23 UTC, gpshead commented on Misc/NEWS.d/next/Library/2018-04-01-19-21-04.bpo-20104.-AKcGa.rst
> +Fixed numerous issues with :func:`os.posix_spawn()`.
This is not specific and meaningful to the reader.  Explain what Python user visible changes were made that a reader would encounter.  examples:

"Improved error handling in os.posix_spawn"
"Fixes a potential crash in the new os.posix_spawn implementation" (is that true?)

2018-04-01 18:23 UTC, gpshead commented on Modules/posixmodule.c
> +    if (!PyList_Check(argv) && !PyTuple_Check(argv)) {
PySequence_Check was correct.  There is no need to force this to be exactly a list or a tuple as parse_file_actions uses the sequence APIs.

2018-04-01 18:23 UTC, gpshead commented on Modules/posixmodule.c
> +        long tag = PyLong_AsLongAndOverflow(PyTuple_GET_ITEM(file_action, 0),
You never use overflow.  Just call PyLong_AsLong() as the original code did.

2018-04-01 18:23 UTC, gpshead commented on Modules/posixmodule.c
> +        Py_INCREF(file_action);
Why are you INCREFing this?  Borrowing the reference is the normal thing to do when looping over a sequence in C.

Get rid of the INCREF and you don't have to worry about the DECREFs.

2018-04-10 02:26 UTC, zware reviewed
Added my $0.02USD on the blurb contents below, and @gpshead's suggestions look sound to me as well.  Otherwise, this looks like a nice cleanup.

2018-04-10 02:26 UTC, zware commented on Misc/NEWS.d/next/Library/2018-04-01-19-21-04.bpo-20104.-AKcGa.rst
> +Fixed numerous issues with :func:`os.posix_spawn()`.
I'd go with ```Improved error handling and fixed a reference leak in :func:`os.posix_spawn()`.```

2018-04-10 13:09 UTC, serhiy-storchaka reviewed
Thank you for fixing these issues and for documenting the new function @gpshead.

But increfing a borrowed reference is neccessary, and supporting other sequences as argv can open a can of worms. It should be discussed separately if there is a need of this feature.

2018-04-10 13:09 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +        Py_INCREF(file_action);
This is a borrowed reference. The code inside a loop can call an arbitrary Python code, and this can invalidate borrowed references.

2018-04-10 13:09 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +    if (!PyList_Check(argv) && !PyTuple_Check(argv)) {
The docstring says that it should a tuple or a list, and other similar APIs accept only tuples and lists. If there is a need of supporting other sequences, it is better to implement this feature consistently for all APIs and in a separate issue.

Actually accepting arbitrary sequences can have negative consequences. `str` and `bytes` are sequences, and passing them by mistake will cause raising errors with unhelpful messages.

2018-04-10 13:09 UTC, serhiy-storchaka commented on Modules/posixmodule.c
> +        long tag = PyLong_AsLongAndOverflow(PyTuple_GET_ITEM(file_action, 0),
I just don't like if different exceptions are raised for different incorrect values of the same type. But this is not critical.

Actually I think that it would be better to make `POSIX_SPAWN_OPEN` etc just singletons and test for identity instead of converting them to C long.

2018-04-10 13:12 UTC, serhiy-storchaka commented
Added new tests (mainly inspired by tests for the third-party module https://github.com/projectcalico/posix_spawn) and improved the documentation.

2018-04-26 11:30 UTC, vstinner commented
@gpshead: @serhiy-storchaka updated his PR and replied to your comments, would you mind to review it again?

@serhiy-storchaka: Travis CI is unhappy. Did you check why?

This PR fixes a reference leak which makes the Linux Refleaks buildbot red:  https://bugs.python.org/issue33357

cc @pablogsal 

Note: I didn't review the PR.

2018-05-01 13:45 UTC, merged

2018-05-01 13:45 UTC, miss-islington commented
Thanks @serhiy-storchaka for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖