bpo-31201: Clarify command to re-run failing test(s) with example
python/cpython pull request #6417
Opened 2018-04-08 07:57 UTC by aaronang

https://bugs.python.org/issue31201

2018-04-08 07:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2018-04-08 18:43 UTC, ned-deily requested changes

2018-04-08 18:43 UTC, ned-deily commented on README.rst
> +     make test TESTOPTS="-v test_os test_gdb"
Why the preceding space?

2018-04-09 02:12 UTC, aaronang commented on README.rst
> +     make test TESTOPTS="-v test_os test_gdb"
Oops, nice catch.

2018-04-09 02:12 UTC, aaronang commented
I have made the requested changes; please review again

2018-04-09 21:05 UTC, ned-deily approved these changes

2018-04-09 21:09 UTC, merged

2018-04-09 21:09 UTC, miss-islington commented
Thanks @aaronang for the PR, and @ned-deily for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖