bpo-33222: Add canonicalisation to paths in site test suite.
python/cpython pull request #6434
Opened 2018-04-09 17:21 UTC by akshaysharma096

https://bugs.python.org/issue33222

2019-02-05 15:36 UTC, jdemeyer requested changes
There is also a failing test in `test_sysconfig`

2019-02-05 15:36 UTC, jdemeyer commented on Misc/NEWS.d/next/Tests/2018-04-09-22-49-40.bpo-33222.dWWouj.rst
> +Add canonicalization to paths in site test suite.
Not sure that we need a `NEWS` entry just for fixing the testsuite.

2022-12-07 18:57 UTC, iritkatriel requested changes
This has merge conflicts now.

2026-05-05 17:29 UTC, StanFromIreland commented
Closing, [issue](https://github.com/python/cpython/issues/77403) has been completed.

2026-05-05 17:29 UTC, closed without merging