bpo-33284 Add to a unit test to improve coverage for numbers.py
python/cpython pull request #6480
Opened 2018-04-15 18:19 UTC by londinburgh

Small change to improve unit test coverage. My first merge request for python. 

https://bugs.python.org/issue33284

2018-04-17 19:11 UTC, londinburgh commented
Hi, I have signed the CLA.

2018-04-17 19:52 UTC, zware commented
Hi @londinburgh.  While you are all set up on the CLA, the committer (@trevaskis) is not, and @the-knights-who-say-ni requires that all committers and authors on a PR have the CLA signed.

2018-04-19 20:31 UTC, londinburgh commented
Ok, now all contributors have signed!

2018-04-24 19:29 UTC, londinburgh commented
Have updated this.

2019-03-05 21:51 UTC, BoboTiG reviewed
Thanks for the patch @londinburgh. I did not test as I think there are 2 little mistakes :)

Also it may be worth adding a NEWs entry?

2019-03-05 21:51 UTC, BoboTiG commented on Lib/test/test_abstract_numbers.py
> +                return self._imag
It should be `return self._real`, right?

2019-03-05 21:51 UTC, BoboTiG commented on Lib/test/test_abstract_numbers.py
> +                return self._real
And same here with `self._imag`.

2019-05-18 01:35 UTC, csabella commented
@londinburgh, please make the changes requested by @BoboTiG.  Thanks!

2019-09-09 14:57 UTC, zware requested changes

2019-09-09 14:57 UTC, zware commented on Lib/test/test_abstract_numbers.py
> +                self._real = value
These setters would be better placed alongside the getters.

2020-01-26 00:01 UTC, csabella commented
Since this PR is against an unknown repository, I'm going to close it.  A new pull request can be opened for the issue, but if it's based on this PR, please credit the original author.

2020-01-26 00:01 UTC, closed without merging