Support complex expressions for py-print command.
python/cpython pull request #6481
Opened 2018-04-15 19:33 UTC by marxin

The patch is based on a blog post: http://kouk.surukle.me/2014/09/25/debugging-python-objects-and-fields-with-gdb/.
Adding him: @kouk

Purpose of the pull request is to support more complex expressions for py-print command.
Small example:

```
(gdb) py-print self
local 'self' = <OptimizationLevel(level='', options=[<MarchFlag(name='-mtune=', options={'x86_64': ('native', 'i386', 'i486', 'i586', 'pentium', 'lakemont', 'pentium-mmx', 'pentiumpro', 'i686', 'pentium2', 'pentium3', 'pentium3m', 'pentium-m', 'pentium4', 'pentium4m', 'prescott', 'nocona', 'core2', 'nehalem', 'westmere', 'sandybridge', 'ivybridge', 'haswell', 'broadwell', 'skylake', 'bonnell', 'silvermont', 'knl', 'skylake-avx512', 'k6', 'k6-2', 'k6-3', 'athlon', 'athlon-tbird', 'athlon-4', 'athlon-xp', 'athlon-mp', 'k8', 'opteron', 'athlon64', 'athlon-fx', 'k8-sse3', 'opteron-sse3', 'athlon64-sse3', 'amdfam10', 'barcelona', 'bdver1', 'bdver2', 'bdver3', 'bdver4', 'znver1', 'btver1', 'btver2', 'winchip-c6', 'winchip2', 'c3', 'c3-2', 'geode'), 'ppc64': ['401', '403', '405', '405fp', '440', '440fp', '464', '464fp', '476', '476fp', '505', '601', '602', '603', '603e', '604', '604e', '620', '630', '740', '7400', '7450', '750', '801', '821', '823', '860', '970', '8540', 'a2', 'e300c2', 'e300c3', 'e500mc', 'e500mc64', 'e5500', 'e6...(truncated)

(gdb) py-print self.options.0.options.x86_64.3
local 'self.options.0.options.x86_64.3' = 'i586'
```

I consider it very handy. For now I support objects, dictionary, tuple and list types of objects.
I guess a test-case and a documentation entry will be needed. But I would first like to get a feedback about the intention of the change.

Thanks

2018-04-15 19:33 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

2018-04-15 19:40 UTC, marxin commented
I've just signed CLA, please recheck it.

2018-04-17 01:01 UTC, pablogsal commented
@marxin Please, open an issue in http://bugs.python.org and reference that issue number in the pull request title. More info about the workflow:

https://devguide.python.org/pullrequest/#submitting

2018-04-17 07:36 UTC, pablogsal commented
@marxin Reference the issue number in the PR title. See other PRs for reference. Thanks

2018-04-17 07:45 UTC, marxin commented
Thanks @pablogsal. Done that.

2018-05-25 20:59 UTC, davidmalcolm requested changes
Thanks for this patch.

The patch is missing test coverage.  Please see: Lib/test/test_gdb.py for examples of how to test py-print.

2018-05-25 20:59 UTC, davidmalcolm commented on Misc/NEWS.d/next/Tools-Demos/2018-04-17-09-16-40.bpo-33294.J7sTti.rst
> +(gdb) py-print self local 'self' = <OptimizationLevel(level='',
Is this missing some line breaks?  (i.e. before the "local")

2018-05-25 20:59 UTC, davidmalcolm commented on Tools/gdb/libpython.py
> +    'Based on type of object, return field of the object'
Shouldn't this be a docstring i.e. within the function body?

2018-05-25 20:59 UTC, davidmalcolm commented on Tools/gdb/libpython.py
> +            # field must be an integer index
It seems a bit odd to be using dotted notation to access by index.  Is it possible to support square-bracket syntax here, or does it conflict with gdb's usage of square-bracket syntax for C level lookup?

2018-05-25 20:59 UTC, davidmalcolm commented on Tools/gdb/libpython.py
> +            dictionary = obj
Similarly for dict objects; wouldn't square bracket notation be more Pythonic?

2018-05-31 09:24 UTC, marxin commented on Misc/NEWS.d/next/Tools-Demos/2018-04-17-09-16-40.bpo-33294.J7sTti.rst
> +(gdb) py-print self local 'self' = <OptimizationLevel(level='',
Yes, fixed in newer version.

2018-05-31 09:24 UTC, marxin commented on Tools/gdb/libpython.py
> +    'Based on type of object, return field of the object'
Yes, fixed in newer version.

2018-05-31 09:24 UTC, marxin commented on Tools/gdb/libpython.py
> +            dictionary = obj
Yes, fixed in newer version.

2018-05-31 10:25 UTC, pablogsal commented on Tools/gdb/libpython.py
> +        Tokenize single expression of an array index of key of a dictionary
This docstring is confusing to read, could you elaborate a cleaner version of what this function does?

2018-05-31 12:50 UTC, marxin commented on Tools/gdb/libpython.py
> +        Tokenize single expression of an array index of key of a dictionary
Should be better now ;)

2018-05-31 12:50 UTC, marxin commented
I also added a test-case.

I have made the requested changes; please review again

2018-06-22 11:29 UTC, marxin commented
May I please ping review process?

2018-06-22 21:24 UTC, davidmalcolm requested changes

2018-06-22 21:24 UTC, davidmalcolm commented on Lib/test/test_gdb.py
> +                                          cmds_after_breakpoint=['py-up', 'py-print a[3].skills[defence]'])
The  `skills[defence]` syntax seems weird to me; shouldn't this be `skills["defence"]` or `skills['defence']`?

2018-06-22 21:24 UTC, davidmalcolm commented on Misc/NEWS.d/next/Tools-Demos/2018-04-17-09-16-40.bpo-33294.J7sTti.rst
> +(gdb) py-print t.t[4][a]
Likewise here; shouldn't this be `['a']` rather than `[a]`?

2018-06-22 21:24 UTC, davidmalcolm commented on Tools/gdb/libpython.py
> +                raise Exception("Can't find closing bracket")
Please add test coverage for this error

2018-06-22 21:24 UTC, davidmalcolm commented on Tools/gdb/libpython.py
> +                    print("Can't find field %s of %s" % (field, obj))
Please add test coverage for this error.

2018-06-22 21:24 UTC, davidmalcolm commented on Tools/gdb/libpython.py
> +        if isinstance(obj, PyListObjectPtr) or isinstance(obj, PyTupleObjectPtr):
Please add test coverage of a tuple

2018-06-29 13:21 UTC, marxin commented
Thanks @davidmalcolm  for review.
I have made the requested changes; please review again

2018-06-29 13:21 UTC, marxin commented on Tools/gdb/libpython.py
> +        if isinstance(obj, PyListObjectPtr) or isinstance(obj, PyTupleObjectPtr):
Done.

2018-07-09 07:47 UTC, marxin commented
I would like to remind review @davidmalcolm. Thanks.

2018-09-03 07:26 UTC, marxin commented
PING^2

2018-12-31 09:14 UTC, marxin commented
PING^3

2019-06-30 19:27 UTC, marxin commented
@davidmalcolm: Hi. Can we please move forward with this pull request?

2019-12-08 10:09 UTC, marxin commented
@davidmalcolm : ping

2020-05-25 10:04 UTC, marxin commented
@csabella Can you please find somebody else from David who can make the patch review?
I've been waiting for quite some time..

2021-10-12 15:26 UTC, closed without merging