bpo-28810: Document remaining bytecode changes in 3.6
python/cpython pull request #651
Opened 2017-03-13 00:17 UTC by ilevkivskyi

@serhiy-storchaka @brettcannon 
These are two remaining changes to close http://bugs.python.org/issue28810
This needs a backport to 3.6

2017-03-13 05:52 UTC, serhiy-storchaka commented on Doc/library/dis.rst
> +Every instruction takes 2 bytes.
I think this should be moved to the top of the document, under impl-detail block, and decorated with versionchanged.

2017-03-13 05:52 UTC, serhiy-storchaka commented on Doc/library/dis.rst
> +   Functions decoding directly ``co_lnotab`` should use a signed
Too much details for common user of the dis module, but too few details for reproducing decoding algorithm. I think just adding the reference to `Objects/lnotab_notes.txt` is enough.

2017-03-13 08:27 UTC, ilevkivskyi commented
@serhiy-storchaka Thanks!
> I think this should be moved to the top of the document, under impl-detail block

I was also thinking about this. I implemented both your comments in a new commit.

2017-03-13 10:17 UTC, ncoghlan commented on Doc/library/dis.rst
> +   See ``Objects/lnotab_notes.txt`` for the ``co_lnotab`` format and how to
Using a source ref here turn this into a suitable hyperlink to GitHub:

    :source:`Objects/lnotab_notes.txt`

2017-03-13 11:19 UTC, ilevkivskyi commented on Doc/library/dis.rst
> +   See ``Objects/lnotab_notes.txt`` for the ``co_lnotab`` format and how to
Thank you, Nick!
Implemented this is a new commit.

2017-03-13 11:23 UTC, ilevkivskyi commented
By the way, I have noticed that the example in [Objects/lnotab_notes.txt](https://github.com/python/cpython/blob/master/Objects/lnotab_notes.txt) is outdated. It still uses Python 2 and old bytecode (not 2 bytes per instruction).

Should I update it in this PR or open a separate issue and make a separate PR?

2017-03-13 17:36 UTC, brettcannon commented
@ilevkivskyi separate PR would be great!

2017-03-13 19:01 UTC, ilevkivskyi commented
> separate PR would be great!

OK, will do this.
So it looks like this PR could be merged now.

2017-03-13 19:19 UTC, serhiy-storchaka reviewed
The meaning of `HAVE_ARGUMENT` was changed too. Now all instructions have an argument, but opcodes `< HAVE_ARGUMENT` ignore it.

2017-03-13 19:19 UTC, serhiy-storchaka commented on Doc/library/dis.rst
> +      Added support for negative line number delta.
This looks as implementation detail that should be described in `lnotab_notes.txt`. The change visible for the user of `findlinestarts()` is that line numbers now can not be monotonically increasing.

2017-03-13 19:19 UTC, serhiy-storchaka commented on Doc/library/dis.rst
> +      Use fixed 2 bytes per instruction for all instructions.
May be worth to mention that instructions of variable length was used before.

2017-03-14 07:30 UTC, ilevkivskyi commented
@serhiy-storchaka Thanks, I implemented your comments.

2017-03-14 07:41 UTC, serhiy-storchaka approved these changes
I don't know whether the changes use good English, but in general LGTM.

2017-03-14 16:31 UTC, haypo commented on Doc/library/dis.rst
> +      Line numbers can be not monotonically increasing.
"not monotonically" is not easy to understand. In What's New in Python 3.6, I wrote:

"The format of the co_lnotab attribute of code objects changed to support a negative line number delta"

2017-03-14 16:39 UTC, ilevkivskyi commented on Doc/library/dis.rst
> +      Line numbers can be not monotonically increasing.
This is how I initially wrote it, but @serhiy-storchaka wanted me to change this to this wording. 
His motivation is that negative delta is not a visible effect for user, see https://github.com/python/cpython/pull/651#discussion_r105747359

2017-03-14 16:39 UTC, serhiy-storchaka commented on Doc/library/dis.rst
> +      Line numbers can be not monotonically increasing.
This is the wording for describing the implementation details of `co_lnotab`. What is important for the user `findlinestarts()` which shouldn't know anything about `co_lnotab` is that now this function can produce non-monotonic line numbers. That can affect user code.

2017-03-14 16:48 UTC, haypo commented on Doc/library/dis.rst
> +      Line numbers can be not monotonically increasing.
Just say "Line numbers can now go backwards." if you prefer. I would like to avoid "monotonically", especially "not monotonically".

2017-03-14 19:33 UTC, ilevkivskyi commented on Doc/library/dis.rst
> +      Line numbers can be not monotonically increasing.
> Line numbers can now go backwards.

This sounds not very clear to me. I changed this to an alternative formulation "Line numbers can be decreasing. Before, they were always increasing." I hope this works.

2017-03-17 23:10 UTC, brettcannon requested changes

2017-03-17 23:10 UTC, brettcannon commented on Doc/library/dis.rst
> +      of variable length were used before.
I would phrase this as "Use 2 bytes for each instruction. Previously the number of bytes varied by instruction."

2017-03-17 23:10 UTC, brettcannon commented on Doc/library/dis.rst
> +      Now every instruction have an argument, but opcodes ``< HAVE_ARGUMENT``
"Now every instruction has an argument"

2017-03-18 02:27 UTC, ilevkivskyi commented
@brettcannon Thanks! I fixed both points in a new commit.

2017-03-24 20:31 UTC, brettcannon approved these changes

2017-03-24 21:05 UTC, merged