bpo-33358 Fix test_pre_initialization_sys_options when building with --enable-shared
python/cpython pull request #6612
Opened 2018-04-26 21:17 UTC by pablogsal

2018-04-26 21:18 UTC, pablogsal commented
CC: @vstinner

2018-04-27 10:03 UTC, vstinner requested changes

2018-04-27 10:03 UTC, vstinner commented on Misc/NEWS.d/next/Core and Builtins/2018-04-26-22-40-08.bpo-33358.VRMsp2.rst
> +Fix `test_pre_initialization_sys_options` when building with --enable-
There is a better section for your fix: Tests.

If you write a NEWS entry, mention at least the name of the test (file): test_embed. Example:

```
Fix ``test_embed.test_pre_initialization_sys_options()``
```

2018-04-27 10:48 UTC, pablogsal commented
I have made the requested changes; please review again

2018-04-27 12:22 UTC, vstinner approved these changes

2018-04-27 12:23 UTC, merged

2018-04-27 12:27 UTC, miss-islington commented
Thanks @pablogsal for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖