bpo-32790: Added info about alt format using # for 'g' in chart
python/cpython pull request #6624
Opened 2018-04-28 09:13 UTC by bchhabra2490

Added additional information in the chart for format parameter 'g'. @CuriousLearner

2018-04-28 09:13 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

2019-09-10 13:31 UTC, JulienPalard commented
I think the paragraph is too long, especially "The alternate form is defined differently for different types." which is not specific to `g`, so it can be removed.

Beware, also, that the decimal point is also kept using the alternate form, not only trailing zeros. So I propose to extend the sentence:

> In both cases insignificant trailing zeros are removed from the significand, and the decimal point is also removed if there are no remaining digits following it.

by simply adding "unless the ``#`` flag is used.".

2019-09-10 13:32 UTC, JulienPalard requested changes
I think the paragraph is too long, especially "The alternate form is defined differently for different types." which is not specific to `g`, so it can be removed.

Beware, also, that the decimal point is also kept using the alternate form, not only trailing zeros. So I propose to extend the sentence:

> In both cases insignificant trailing zeros are removed from the significand, and the decimal point is also removed if there are no remaining digits following it.

by simply adding "unless the ``#`` flag is used.".

2019-09-13 17:20 UTC, merged

2019-09-13 17:20 UTC, miss-islington commented
Thanks @bchhabra2490 for the PR, and @matrixise for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8.
🐍🍒⛏🤖