bpo-33399: Handle when module __cache__ is None in site.abs_path()
python/cpython pull request #6675
Opened 2018-05-01 17:57 UTC by demianbrecht

I'll look at adding tests if this approach isn't just wrong. https://bugs.python.org/issue33399

2018-05-15 18:40 UTC, brettcannon requested changes

2018-05-15 18:40 UTC, brettcannon commented on Lib/site.py
> +        except (AttributeError, OSError, TypeError):
I would change the whole `try` block to:
```python
if getattr(m, '__cached__', None) is not None:
    try:
        m.__cached__ = os.path.abspath(m.__cached__)
    except OSError:
        pass
```

2019-05-19 00:27 UTC, csabella commented
@demianbrecht, please address the code review from @brettcannon.  Thanks!

2020-01-25 13:01 UTC, csabella commented
Since this PR seems to be abandoned, I am going to close it.  It can be reopened if the original author is interested in working on it again or a new PR can be created to replace it.

2020-01-25 13:01 UTC, closed without merging