bpo-33413: asyncio.gather without a special Future
python/cpython pull request #6694
Opened 2018-05-02 18:45 UTC by tecki

This re-implements asyncio.gather without the need of a special inherited Future.

Futures nowadays are created using loop.create_future(), so having a special-case Future is actually weird. This changes gather() to simply return a Task.

This patch goes at great length to stay backwards compatible. It splits the function gather() in two parts: a backwards-compatible gather() that wraps the coroutine _gather() into an ensure_future(). IMHO the _gather() is everything one would need.

2019-10-18 01:44 UTC, 1st1 commented
Ideally I'd like to not merge this is as this isn't backwards compatible.  We'll likely have TaskGroups in asyncio 3.9 and will simply deprecate `asyncio.gather`.

2022-08-17 00:22 UTC, gvanrossum commented
@serhiy-storchaka Could you review this?

2022-11-25 12:31 UTC, kumaraditya303 requested changes
This has merge conflicts now.

2022-11-29 18:31 UTC, gvanrossum commented
@tecki are you still interested in pushing this forward? The PR is over 4 years old and the merge conflict seems pretty serious -- your best approach may be to start over from scratch.

2023-04-26 22:28 UTC, willingc commented
Hi @tecki, Thanks for opening this PR. I'm going to go ahead and close this PR. Should you wish to work on this issue in the future, please open a new PR. Thank you. :sunny:

2023-04-26 22:28 UTC, closed without merging