fcntl.lockf() is more powerful than written
python/cpython pull request #6750
Opened 2018-05-10 11:59 UTC by lebigot

The fcntl.lockf() function is more powerful than written: it accepts more than only file descriptors, as indicated in the proposed change, which is consistent with the error message one gets from using an incorrect fd argument.

2018-05-10 11:59 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

2018-05-10 16:15 UTC, lebigot commented
I have signed the CLA (login Eric Lebigot, GitHub name lebigot).

Thanks!

2019-03-05 21:42 UTC, BoboTiG commented
Thanks @lebigot !

Do you mind opening an issue on http://bugs.python.org/, link it there and add a NEWs entry (you can use https://blurb-it.herokuapp.com/ for that)?

2019-03-06 11:00 UTC, BoboTiG approved these changes
:+1: (perhaps a NEWs entry + BPO is killer for such change)

2019-09-10 13:37 UTC, JulienPalard requested changes
Could you stick to the existing wording, like in flock and fcntl:
```
[...] fd (file objects providing a fileno() method are accepted as well).
```

?

(Issue and NEWs entry are not needed for such small changes.)

2019-09-13 17:24 UTC, matrixise approved these changes

2019-09-13 17:32 UTC, merged

2019-09-13 17:32 UTC, miss-islington commented
Thanks @lebigot for the PR, and @matrixise for merging it 🌮🎉.. I'm working now to backport this PR to: 3.8.
🐍🍒⛏🤖

2019-09-13 17:33 UTC, matrixise commented
Thank you for your contribution, I have merged into master and 3.8.