bpo-33466: Support compiling Objective-C++ (“.mm”) files
python/cpython pull request #6767
Opened 2018-05-11 17:01 UTC by fish2000

At the moment, Objective-C++ files suffixed with `.mm` are unrecognized; however, other parts of `distutils` suggest support for compiling these files – e.g. the suffix list found in `extension.py`: https://github.com/python/cpython/blob/7ec8f28656ea9d84048e9b5655375c6a74a59f53/Lib/distutils/extension.py#L193

Adding the `".mm"` string to the `src_extensions` list fixes this inequity.

https://bugs.python.org/issue33466

2018-05-11 17:15 UTC, fish2000 commented
I’ve signed the CLA: https://secure.na1.echosign.com/public/viewAgreement?tsid=CBFCIBAA3AAABLblqZhA8LWTFUrmOA3Wz1acrRIM7nkdXFW7eOvGqZZ70U1EXNOaYXC4mRkt-PLNUXm3AVxdjW74id8WQF-sRQGLAEx4A&

2018-05-13 19:49 UTC, grimreaper approved these changes

2018-05-14 16:56 UTC, fish2000 commented
It looks like b.p.o. has acknowledged my signature of the CLA:
![screen shot 2018-05-14 at 12 54 09 pm](https://user-images.githubusercontent.com/378969/40011571-39a3f62e-5776-11e8-868a-dbdca07b7a84.jpg)

2018-06-24 08:39 UTC, ronaldoussoren commented
Patch looks good to me. 

P.S. I'm not merging at this time because this would the first patch I'd merge in a long time and I need to check the devguide to ensure I follow the right process.

2018-06-26 14:57 UTC, merwok requested changes
Hello!  Could you edit the docs to mention this new feature?

2020-01-12 02:18 UTC, csabella commented
@fish2000, it looks like your pull request was approved by a core developer and had some changes requested by another.  If you're able to address the code review, perhaps this can be merged soon.  Thanks!

2020-10-20 15:40 UTC, merwok commented
@ronaldoussoren would you like to pronounce on this?

This looks innocuous and could be merged after a manual test (to confirm that it works) and a quick doc addition.  On the other hand, distutils is strongly deprecated and apparently on its way out, people have been advised to use setuptools or other build tools for years, so maybe distutils PRs should be closed and patches redirected to setuptools.

2020-10-31 13:08 UTC, ronaldoussoren approved these changes
LTGM

2021-05-03 21:29 UTC, closed without merging