bpo-33463: warn _asdict --> dict, not OrderedDict
python/cpython pull request #6772
Opened 2018-05-12 17:07 UTC by selik

Now that dict is tracking insertion order, namedtuple._asdict can be
switched to returning a basic dict instead of an OrderedDict. The
interface is largely similar, but some minor differences will require a
deprecation cycle before making the change.

2018-06-29 20:52 UTC, selik commented
I changed the docs to note the change as of Version 3.8. If this is accepted, I'll create separate pull requests to add warnings to the docs of older versions.

2018-06-30 08:26 UTC, serhiy-storchaka requested changes
Needed a test.

Please add a What's New entry and remove a duplicated news entry, and clarify the reason of reverting the 3.1 change.

2018-06-30 08:26 UTC, serhiy-storchaka commented on Doc/library/collections.rst
> +    Return a new :class:`dict` which maps field names to their corresponding
Maybe "Return a new ordered dictionary ..."?

2018-06-30 08:26 UTC, serhiy-storchaka commented on Doc/library/collections.rst
> +        Returns an :class:`dict` instead of a regular :class:`OrderedDict`.
Maybe a clarification is needed.

Why the "regular" adjective is used with OrderedDict.

2018-09-14 09:18 UTC, serhiy-storchaka commented
For testing just add something like:
```python
self.assertEqual(list(p._asdict().items()), [('x': 11), ('y': 22)])
```
`dict` equality doesn't take the order into account.

Since this change breaks compatibility, it needs to be mentioned in the What's New document, in the "Porting to 3.8" section.

2018-09-14 16:45 UTC, merwok commented on Doc/library/collections.rst
> +        Returns an :class:`dict` instead of a regular :class:`OrderedDict`.
an dict → a dict

2018-09-19 01:57 UTC, selik commented
I added a bit to What's New, but I just realized I need to move that to the "Porting to 3.8" section. I'll do that shortly.

2019-01-31 09:08 UTC, rhettinger commented
Thanks for the PR. 

Have applied an alternative version so the issue is taken care of.

2019-01-31 09:08 UTC, closed without merging