bpo-33487: improve BZ2File Deprecation and documentation.
python/cpython pull request #6785
Opened 2018-05-13 21:49 UTC by Carreau

Emit warning when None passed explicitly, list Python version since
deprecation in warning message and docs.

2018-05-14 15:38 UTC, matrixise requested changes
could you fix the NEWS entry, thank you

2018-05-14 15:38 UTC, matrixise commented on Misc/NEWS.d/next/Documentation/2018-05-13-14-44-30.bpo-33487.iLDzFb.rst
> +deprecation mesage and documentation also now explicitely state it is
there is a typo in your "message".

2018-05-14 18:57 UTC, Carreau commented on Misc/NEWS.d/next/Documentation/2018-05-13-14-44-30.bpo-33487.iLDzFb.rst
> +deprecation mesage and documentation also now explicitely state it is
Oops, thanks. Fixed.

2018-09-11 01:15 UTC, gpshead approved these changes

2018-09-11 01:15 UTC, merged

2018-09-11 07:38 UTC, Carreau commented
Thanks @matrixise amd @gpshead.