bpo-32414: PyCapsule_Import() now imports submodules if needed.
python/cpython pull request #6898
Opened 2018-05-16 10:57 UTC by serhiy-storchaka

2018-05-16 13:29 UTC, encukou commented
Do you plan to add tests, or are you OK leaving that to someone else?

2018-05-16 13:36 UTC, serhiy-storchaka commented
Currently there are no any tests for PyCapsule. I'm going to write them if possible, but this will take a time.

2018-05-16 13:58 UTC, encukou commented
I'm asking because writing tests would make a nice task for mentoring someone – but it would take even more time that way.

2018-05-17 18:01 UTC, zooba commented on Objects/capsule.c
>              object = object2;
`Py_SETREF`?

2018-05-17 18:02 UTC, zooba approved these changes

2018-05-18 09:21 UTC, lekma commented on Objects/capsule.c
> +                object = PyImport_ImportModule(name_dup);
aren't PyImport_ImportModuleNoBlock and PyImport_ImportModule the same thing now?

2018-05-18 13:21 UTC, serhiy-storchaka commented on Objects/capsule.c
> +                object = PyImport_ImportModule(name_dup);
Good point!

2018-05-18 14:16 UTC, serhiy-storchaka commented on Objects/capsule.c
>              object = object2;
Yes, it can be used here.

2018-10-19 23:47 UTC, vstinner requested changes

2018-10-19 23:47 UTC, vstinner commented on Objects/capsule.c
> +            Py_SETREF(object, PyObject_GetAttrString(object, trace));
I would expect error handling here, if PyObject_GetAttrString() fails for whatever reason. It seems like PyImport_ImportModule() is tried on the substring on error.

2020-01-25 23:53 UTC, csabella commented
@serhiy-storchaka, it looks like this one was close to being merged, so just putting it back on the radar.

2023-02-20 19:39 UTC, WillAyd commented
I have a use case for this and would be happy to rebase / take over from @serhiy-storchaka if you don't have the time for it

2026-07-24 10:04 UTC, serhiy-storchaka commented
Added tests for current capsule import in #154588. After it has been merged, I'll update this PR and add new test.

2026-07-24 15:32 UTC, serhiy-storchaka commented
I have made the requested changes; please review again.

2026-08-10 14:56 UTC, vstinner approved these changes
LGTM. I have some minor remarks.

The change is tested by test_submodule().

2026-08-10 14:56 UTC, vstinner commented on Objects/capsule.c
>      trace = name_dup;
nitpick: you can move *trace* declaration here, to avoid declarating it as undefined first.

```suggestion
    char *trace = name_dup;
```

2026-08-10 14:56 UTC, vstinner commented on Objects/capsule.c
>          }
You may add an empty line after, for readability.

2026-08-10 14:56 UTC, vstinner commented on Objects/capsule.c
> +            break;
Maybe add an explicit comment to say that the normal code path:

```suggestion
            // We are done
            break;
```

2026-08-10 14:56 UTC, vstinner commented on Doc/c-api/capsule.rst
> +      as in ``package.module.attribute``.
You may repeat that in the function documentation body (without "now").

2026-08-10 14:58 UTC, vstinner commented
Oh, "Docs / Docs" fails with "fatal: shallow file has changed since we read it". That's the issue gh-151365.

2026-08-10 18:36 UTC, merged