BPO-13474 Add -m reference  in context of code execution
python/cpython pull request #6901
Opened 2018-05-16 11:59 UTC by elusivenode

2019-09-10 14:10 UTC, JulienPalard commented
@ncoghlan, ping

2019-09-11 23:08 UTC, ncoghlan requested changes
Looks good, but needs a markup fix (I'm on my phone, or I'd fix it directly)

2019-09-11 23:08 UTC, ncoghlan commented on Doc/reference/executionmodel.rst
> +interpreter command line with the '**-c**' option) is a code block.  A module run as a top level script (as module `__main__`) from the command line using a '**-m**' argument is also a code block. Th
Double backticks on the markup

2019-09-11 23:11 UTC, ncoghlan commented
(I am puzzled as to why me-of-a-year-ago didn't just fix that. Sorry for the delay...)

2019-09-12 13:11 UTC, closed without merging