bpo-33582: Emit deprecation warning for `formatargspec`
python/cpython pull request #6994
Opened 2018-05-19 23:00 UTC by Carreau

Also assert it emits deprecation warnings in corresponding test, and add that into the docstring.

2018-06-06 07:49 UTC, methane approved these changes

2018-06-10 09:22 UTC, taleinat requested changes
Just two minor fixes before this can go in, IMO.

2018-06-10 09:22 UTC, taleinat commented on Lib/inspect.py
> +    Deprecated since Python 3.5 use, the `signature` function and `Signature`
IMO there should be a colon `:` before the word "use" and no comma after it.

2018-06-10 09:22 UTC, taleinat commented on Lib/test/test_inspect.py
> +                self.assertEqual(inspect.formatargspec(args, varargs, varkw, defaults),
Please fix the indentation of the continuation line here and further in this file.

2018-06-11 12:35 UTC, Carreau commented
I have made the requested changes; please review again

2018-06-11 12:39 UTC, taleinat approved these changes

2018-06-11 20:00 UTC, ned-deily commented
OK, let's get this in for 3.7.0.

2018-06-11 20:08 UTC, merged

2018-06-11 20:08 UTC, miss-islington commented
Thanks @Carreau for the PR, and @ned-deily for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2018-06-12 13:54 UTC, Carreau commented
Thanks !