bpo-33604: Remove deprecated HMAC default value marked for removal in 3.8
python/cpython pull request #7063
Opened 2018-05-22 20:29 UTC by Carreau

HMAC's digestmod was deprecated marked for removal in 3.6, then to 3.8 (in #7062).

This is on top of #7062, which fix the deprecation notice to use the correct Python version.

2018-05-22 21:39 UTC, gpshead requested changes
I made some minor edits.  overall I'm okay with this but lets wait for the PR marking it fully deprecated in 3.7 to go in first.

2018-05-23 02:12 UTC, Carreau commented
> I made some minor edits

AH, yes, thank you, much better. 

> overall I'm okay with this but lets wait for the PR marking it fully deprecated in 3.7 to go in first.

Yes that was the plan. 
I rebased because of conflict.
I have made the requested changes; please review again

2018-09-10 18:08 UTC, gpshead approved these changes

2018-09-10 18:10 UTC, merged

2018-09-10 19:58 UTC, Carreau commented
Thanks, Much appreciated. I'm guessing you'll be at the core-dev sprint, and wish you all to enjoy it (but still take some time off).