bpo-29849: fix memory leak in import_from
python/cpython pull request #712
Opened 2017-03-18 19:01 UTC by zhangyangyu

2017-03-18 19:15 UTC, serhiy-storchaka approved these changes

2017-03-19 17:01 UTC, brettcannon commented
The Travis failures were probably due to GH-697 which has now been fixed in GH-718. Please rebase your branch to pick up the change.

2017-03-19 17:35 UTC, brettcannon requested changes
Minor doc removal, otherwise LGTM.

2017-03-19 17:35 UTC, brettcannon commented on Python/ceval.c
> +        /* doesn't check NULL for errmsg, PyErr_SetImportError will catch */
I don't think the comment is necessary long-term.

2017-03-20 02:40 UTC, zhangyangyu commented on Python/ceval.c
> +        /* doesn't check NULL for errmsg, PyErr_SetImportError will catch */
This comment is to make others know the error check is left out deliberately. It is not an oversight.
IMHO it's useful for now. :-（

2017-03-20 19:56 UTC, brettcannon requested changes

2017-03-20 19:56 UTC, brettcannon commented on Python/ceval.c
>      } else {
While you're here you might as well fix the formatting for this.

2017-03-20 19:56 UTC, brettcannon commented on Python/ceval.c
> +        /* doesn't check NULL for errmsg, PyErr_SetImportError will catch */
If you want to keep it then please change it to "/* NULL check for errmsg done by PyErr_SetImportError. */".

2017-03-20 19:56 UTC, brettcannon commented on Python/ceval.c
> +        PyErr_SetImportError(errmsg, pkgname, pkgpath);
Need a similar comment here if you are going to leave it in.

2017-03-21 03:13 UTC, merged

2017-03-21 03:14 UTC, zhangyangyu commented
Thanks @serhiy-storchaka and @brettcannon !