bpo-33601: Document for Py_UTF8Mode
python/cpython pull request #7143
Opened 2018-05-27 21:06 UTC by y43ren

Adding documentation for Py_UTF8Mode.

2018-05-27 21:06 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

2018-05-28 10:21 UTC, vstinner requested changes

2018-05-28 10:21 UTC, vstinner commented on Doc/c-api/init.rst
> +   it is enabled in the POSIX locale.
The documentation is incorrect. Extract of Python/bltinmodule.c:

```
/* UTF-8 mode (PEP 540): if equals to 1, use the UTF-8 encoding, and change
   stdin and stdout error handler to "surrogateescape". It is equal to
   -1 by default: unknown, will be set by Py_Main() */
int Py_UTF8Mode = -1;
```

I suggest:

* If set to 1, enable the UTF-8 Mode
* If set to 0, disable the UTF-8 Mode
* If set to -1, look for the :envvar:`PYTHONUTF8` environment variable and the :option:`-X` ``utf8`` command line option

I would suggest to **not** document **here** the effects of the UTF-8 Mode.

Currently, the effects of the UTF-8 Mode are not documented. But I would prefer to not document it at 3 different places: C API doc, PYTHONUTF8 doc, -X utf8 doc.

I don't know what is the best place to document the UTF-8 Mode, but I would prefer to document it in a Python documentation (not in the C API).

2018-05-28 10:21 UTC, vstinner commented on Doc/c-api/init.rst
> +   See :pep:`540` for more details.
I suggest to add "the": See the :pep:`540` ...

2018-07-30 10:35 UTC, vstinner commented
@y43ren: Do you still plan to work on this PR? I don't see any change since I reviewed your first PR version.

2019-03-26 19:18 UTC, brettcannon commented
Thanks for the PR, but closing as the CLA has not been signed within the last month. If you do decide to sign the CLA we can re-open this PR.

2019-03-26 19:18 UTC, closed without merging