bpo-33197: Add description property for _ParameterKind
python/cpython pull request #7206
Opened 2018-05-29 15:21 UTC by corona10

This PR is originated from a discussion https://github.com/python/cpython/pull/6636#discussion_r190000263

2018-05-29 17:58 UTC, 1st1 requested changes
Please update the docs.

2018-05-30 06:49 UTC, corona10 commented
@1st1 
I have made the requested changes; please review again

2018-06-04 05:33 UTC, corona10 commented
@1st1 
Please take a look if you have a time :)

2018-06-08 03:46 UTC, 1st1 approved these changes

2018-06-08 03:46 UTC, merged