Issue 29326: Fixed skipping of empty paths while reading `pth`.
python/cpython pull request #7243
Opened 2018-05-30 13:46 UTC by excitoon

Follow up to Issue 29326.

Alexey erroneously broke adding empty paths to `sys.path` along with his patch.

Official embeddable Pythons do contain a blank line in its ._pth, and this allowed users to import modules from script directory.

2018-05-30 13:47 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

2018-05-30 15:45 UTC, izbyshev commented
This patch changes the [documented](https://docs.python.org/3.7/using/windows.html#finding-modules) `._pth` behavior in backwards incompatible way. I'm not sure that we want to do that, but if we do, the documentation should be updated.

2018-05-30 16:03 UTC, zooba requested changes
This change is incorrect and should not be merged.

2018-05-30 16:06 UTC, zooba commented
Please continue discussion on the bug (which will remain closed) so we can help figure out what you need and provide better alternatives.

2019-05-29 00:18 UTC, csabella commented
@VadimPushtaev, thank you for your suggestion for improving CPython.  Based on @zooba's comment and the discussion on the bug tracker, I'm going to close this issue.

2019-05-29 00:18 UTC, closed without merging

2019-05-30 15:15 UTC, VadimPushtaev commented
@csabella, do you really mean to highlight me?

2019-05-30 16:02 UTC, csabella commented
@VadimPushtaev, thank you for asking.  I apologize for my error.  Not sure how I picked your name instead of the creator of the pull request.