bpo-2504: Add pgettext() and variants to gettext
python/cpython pull request #7253
Opened 2018-05-30 20:12 UTC by csabella

Original patch by Franz Glasner.

2018-05-31 06:34 UTC, serhiy-storchaka commented on Doc/library/gettext.rst
> +      corresponding message string, as an 8-bit string encoded with the
This is not true in Python 3. The result is a Unicode string, not an encoded 8-bit string. Only `l*gettext` functions return bytes, and this makes them virtually useless.

2018-06-03 08:14 UTC, A3880036 commented
Accept

2018-10-26 12:54 UTC, damufo commented
Hello:
How is this?
I think it would be interesting to complete it.
Being able to use context in gettext would allow for example to specify the gender.

2018-10-27 16:36 UTC, serhiy-storchaka requested changes
Remove `l*gettext()` functions and fix the documentation.

2018-10-28 21:17 UTC, csabella commented
I have made the requested changes; please review again.

2018-10-29 11:07 UTC, serhiy-storchaka commented on Doc/library/gettext.rst
> +      ``'pgettext'``, ``'lgettext'``, and ``'lngettext'``.
Why is 'npgettext' omitted?

Maybe add `versionchanged`?

2018-10-29 11:07 UTC, serhiy-storchaka commented on Doc/library/gettext.rst
> +      determine which  plural form to use.  The returned message string is a
I think the sentence about a Unicode string can be removed.

2018-10-29 11:07 UTC, serhiy-storchaka commented on Lib/gettext.py
> +            tmsg = self._catalog[(ctxt_msg_id, self.plural(n))]
Parenthesis are not necessary: `self._catalog[ctxt_msg_id, self.plural(n)]`.

2018-10-29 11:07 UTC, serhiy-storchaka commented on Tools/i18n/msgfmt.py
> +            MESSAGES["%s\x04%s" % (ctxt, id)] = str
Is not `id` a bytes string?

2018-10-29 11:07 UTC, serhiy-storchaka commented on Tools/i18n/msgfmt.py
> +            msgctxt += l
Encode?

2018-10-29 11:08 UTC, serhiy-storchaka commented
Please add also a What's New entry.

2018-11-02 00:30 UTC, csabella commented on Doc/library/gettext.rst
> +      determine which  plural form to use.  The returned message string is a
Removed.  I think it was originally included as a copy of `ngettext`.

2018-11-02 00:30 UTC, csabella commented on Tools/i18n/msgfmt.py
> +            MESSAGES["%s\x04%s" % (ctxt, id)] = str
Thanks!  Fixed.

2018-11-02 00:31 UTC, csabella commented on Tools/i18n/msgfmt.py
> +            msgctxt += l
Thanks!

2018-11-02 06:10 UTC, serhiy-storchaka commented on Doc/library/gettext.rst
> +      Added ``'pgettext'`` and ``'npgettext'``.
Bad indentation.

2018-11-02 06:21 UTC, serhiy-storchaka commented on Doc/whatsnew/3.8.rst
> +(Contributed by Franz Glasner in :issue:`2504`.)
I think it is worth to add Éric and you as co-authors.

2018-11-02 21:55 UTC, csabella commented on Doc/library/gettext.rst
> +      Added ``'pgettext'`` and ``'npgettext'``.
Sorry about that.

2018-11-02 21:55 UTC, csabella commented on Doc/whatsnew/3.8.rst
> +(Contributed by Franz Glasner in :issue:`2504`.)
OK.

2018-11-04 21:49 UTC, merwok approved these changes

2018-11-07 10:29 UTC, serhiy-storchaka approved these changes

2018-11-07 14:12 UTC, merged