bpo-33684:parse failed for mutibytes characters, encode will show in \xxx
python/cpython pull request #7286
Opened 2018-05-31 14:45 UTC by zhouronghua

when type this command in windows(xp or win7, all the same):
python -m json.tool xxx.txt xxx.json
if xxx.txt contains Chinese(or other multibytes characters):
if xxx.txt is encoded in ansi, xxx.json will encode Chinese as \xxx, very bad to see what they are;
if xxx.txt is encoded in utf8(without bom for most of the time), because with no bom, json.tool will think it is encoded in ansi, and decode fail.

as now, utf8 is widely use, set default to utf8 for most of the time when auto detect encoding failed

2018-05-31 14:45 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

2018-06-14 13:29 UTC, pablogsal requested changes

2018-06-14 13:29 UTC, pablogsal commented on Lib/json/tool.py
> +        outfile.write(json.dumps(obj,ensure_ascii=False,sort_keys=sort_keys, indent=4))
Pep8: Please, separate every argument with space?:
```
outfile.write(json.dumps(obj, ensure_ascii=False, sort_keys=sort_keys, indent=4)
```

2019-03-26 19:18 UTC, brettcannon commented
Thanks for the PR, but closing as the CLA has not been signed within the last month. If you do decide to sign the CLA we can re-open this PR.

2019-03-26 19:18 UTC, closed without merging