bpo-28240: timeit: Update repeat() doc
python/cpython pull request #7419
Opened 2018-06-05 10:43 UTC by vstinner

Document that the default value of repeat changed from 3 to 5 in
Python 3.7.

2018-06-05 10:43 UTC, vstinner commented
@serhiy-storchaka: Is it what you expected in your https://bugs.python.org/issue33771 request? (Would you mind to review this PR please?)

2018-06-05 12:51 UTC, serhiy-storchaka requested changes
Update also the CLI docs and docstrings.

2018-06-06 10:54 UTC, vstinner commented
I have made the requested changes; please review again.

2018-06-06 15:08 UTC, serhiy-storchaka reviewed
And the CLI documentation please.

2018-06-06 15:22 UTC, vstinner commented
> And the CLI documentation please.

I updated timeit --help, but I missed that the CLI was also documented in Doc/library/timeit.rst. All documentation should now be up to date!

2018-06-06 15:27 UTC, serhiy-storchaka approved these changes

2018-06-06 15:55 UTC, merged

2018-06-06 15:55 UTC, miss-islington commented
Thanks @vstinner for the PR 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖