bpo-22708: Fix http protocol version in CONNECT method, support IDN
python/cpython pull request #742
Opened 2017-03-20 18:42 UTC by vo-va

Original author of this patch demianbrecht@gmail.com

HTTP/1.0 not supported CONNECT method, fix http version.
Support for IDN.

https://bugs.python.org/issue22708

2017-03-24 21:53 UTC, brettcannon commented
FYI for any other core dev, Demian Brecht has signed the CLA.

2017-04-15 01:49 UTC, berkerpeksag requested changes
Please also include the NEWS entry in the [original patch](https://bugs.python.org/file38808/issue22708.patch) and append "Patch by Demian Brecht.".

2017-04-15 01:49 UTC, berkerpeksag commented on Lib/test/test_httplib.py
> +        expected = 'CONNECT %s:%d HTTP/1.1\r\n'.encode('ascii') % (
Is there a reason to not use `b'CONNECT %s:%d HTTP/1.1\r\n'` instead? We already know that "HTTP/1.1", `dest.encode('idna')` and `client.HTTP_PORT` don't contain any non-ASCII chars so there is no need to encode it ASCII.

2017-04-15 01:49 UTC, berkerpeksag commented on Lib/test/test_httplib.py
> +        dest = '\u03b4\u03c0\u03b8.gr'
`host` would be a better name.

2017-04-15 01:50 UTC, berkerpeksag commented
And please rebase your branch so we can run the tests on AppVeyor.

2017-04-15 02:01 UTC, berkerpeksag commented on Lib/test/test_httplib.py
>          # This test should be removed when CONNECT gets the HTTP/1.1 blessing
This comment is now redundant and can be removed, but I don't see a reason to remove the test itself.

2018-02-21 01:51 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2018-07-17 14:09 UTC, berkerpeksag commented
Superseded by PR #8305.

2018-07-17 14:09 UTC, closed without merging