bpo-28557: error message for bad raw readinto
python/cpython pull request #7496
Opened 2018-06-07 20:57 UTC by davidszotten

2018-06-07 20:57 UTC, davidszotten commented
Would prefer to still return an OSError with the TypeError as a cause, but couldn't figure out how to do that. Hints/help would be appreciated.

2019-09-12 13:47 UTC, benjaminp requested changes
Yeah, I don't think you should change the exception type.

2019-09-12 13:47 UTC, benjaminp commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
Why did you make a new if statement? Can't you put this logic in the next one?

2019-09-12 13:47 UTC, benjaminp commented on Modules/_io/bufferedio.c
> +        _PyErr_TrySetFromCause(
I think you actually want `_PyErr_FormatFromCause`?

2019-09-12 13:47 UTC, benjaminp commented on Lib/test/test_io.py
> +    def test_bad_readinto_value(self):
You should put these tests in `BufferedReaderTest` and fix `_pyio.py`, too.

2019-09-12 14:27 UTC, davidszotten commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
not sure what you mean here. i may be wrong but i think i need a new if statement to check for this particular failure case.

or are you just suggesting i nest this if statement inside the `if (n < 0 || n > len)`?

2019-09-12 14:38 UTC, benjaminp commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
I was thinking you could simply change the `PyErr_Format` on line 1493 to `_PyErr_FormatFromCause` and the the exception from `PyNumber_AsSsize_t` would be set as the cause (if there was one).

2019-09-12 15:28 UTC, davidszotten commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
ah, i see. didn't realise that worked even if there was no exception. this is one of my first forays in to cpython so my knowledge level is a bit limited i'm afraid

2019-09-12 16:03 UTC, davidszotten commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
hm, i may be doing something else wrong, but i think calling `_PyErr_FormatFromCause` with no current exception causes a segfault

2019-09-12 16:20 UTC, davidszotten commented on Lib/test/test_io.py
> +    def test_bad_readinto_value(self):
i may be missing something but i can't see anything exactly analogous to this in the python version

2019-09-12 16:23 UTC, benjaminp commented on Lib/test/test_io.py
> +    def test_bad_readinto_value(self):
Okay, we can leave it then.

2019-09-12 16:25 UTC, benjaminp commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
Alright, I was wrong to try to be clever.

2019-09-13 12:49 UTC, benjaminp commented
I'm saying the error handling code should look like [this](https://github.com/python/cpython/blob/9eb35ab0d71a6bd680e84fa0f828cb634e72b681/Modules/_io/bufferedio.c#L711-L717).

2019-09-23 12:53 UTC, davidszotten commented
friendly bump @benjaminp

2020-03-08 18:07 UTC, davidszotten commented
@csabella should we change this from awaiting changes to awaiting review again?

2020-06-06 21:30 UTC, remilapeyre requested changes

2020-06-06 21:30 UTC, remilapeyre commented on Lib/test/test_io.py
> +        assert cm.exception.__cause__ is None
```suggestion
        self.assertIsNone(cm.exception.__cause__)
```

2020-06-06 21:30 UTC, remilapeyre commented on Lib/test/test_io.py
> +        assert isinstance(cm.exception.__cause__, TypeError)
```suggestion
        self.assertIsInstance(cm.exception.__cause__, TypeError)
```

2020-06-07 07:29 UTC, davidszotten commented
thanks for the suggestions @remilapeyre . updated

2020-06-10 21:44 UTC, remilapeyre approved these changes
Thanks @davidszotten ! Just one small nit, I'm pretty sure an error must be set when `n == 1` so you don't have to check `PyErr_Occurred()` too. Otherwise it looks good to me!

2020-06-10 21:44 UTC, remilapeyre commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
```suggestion
    if (n == -1) {
```

2020-06-11 08:51 UTC, davidszotten commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
i don't quite understand why, but removing that check i get a segfault

here's the bottom of the stack from lldb:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001001542f5 python.exe`_PyErr_FormatVFromCause [inlined] _Py_DECREF(op=0x0000000000000000) at object.h:441:9 [opt]
    frame #1: 0x00000001001542f5 python.exe`_PyErr_FormatVFromCause(tstate=0x0000000100506680, exception=0x0000000100292fc0, format="raw readinto() returned invalid value", vargs=0x00007ffeefbf9a40) at errors.c:586 [opt]
  * frame #2: 0x0000000100154460 python.exe`_PyErr_FormatFromCause(exception=<unavailable>, format=<unavailable>) at errors.c:626:5 [opt]
    frame #3: 0x00000001001e8508 python.exe`_bufferedreader_raw_read(self=<unavailable>, start=<unavailable>, len=8192) at bufferedio.c:1488:9 [opt]
```

2020-06-11 12:26 UTC, davidszotten commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
hang on, i think i get it now.  the point is that `n` is the return value of the (user-defined) `readinto` which means it _can_ sometimes be `-1` even without `PyErr_Occurred`. this is then caught in the next `if` block (and becomes "raw readinto() returned invalid length [..]")

the whole point of this pr is to help users debug bad `readinto` implementations by providing more granular error messages

2020-06-11 13:12 UTC, remilapeyre commented on Modules/_io/bufferedio.c
> +    if (n == -1 && PyErr_Occurred()) {
Yes sorry, this was a mistake :/

2020-06-11 13:41 UTC, davidszotten commented
@remilapeyre no worries

does that mean this is ready? pr is marked as "requested changes" from @benjaminp though he never replied to my [comment about his suggested change](https://github.com/python/cpython/pull/7496#issuecomment-531351841)

what's the next step?

2020-06-11 14:13 UTC, remilapeyre commented
> @remilapeyre no worries
> 
> does that mean this is ready? pr is marked as "requested changes" from @benjaminp though he never replied to my [comment about his suggested change](https://github.com/python/cpython/pull/7496#issuecomment-531351841)
> 
> what's the next step?

I think your change looks good, new it needs to be reviewed by a core developer like @benjaminp  and they will either merge it or ask you for changes. There is a lot of work going on on Python and they have  a lot of PR to review so it may take them some time but they will get there :)

2020-06-11 15:58 UTC, davidszotten commented
is there a difference between the tags for "awaiting review" and "awaiting core review" that's applicable here?

2020-06-11 20:02 UTC, remilapeyre approved these changes
The first is when nobody reviewed, the second is when someone who is not a core developer has made a review. It should have switched but the bot seems to have missed it.

2020-06-15 23:53 UTC, merged

2020-06-16 12:21 UTC, davidszotten commented
thank you!