bpo-31711: Fix for calling SSLSocket.send with empty input.
python/cpython pull request #7559
Opened 2018-06-09 14:03 UTC by rkondratenko

SSLSocket in Python wraps ordinary sockets and provides SSLSocket.send with same behaviour (except for nonblocking differences mentiond in the documentation). Internally cPython uses OpenSSL as SSL library.
SSLSocket.send() calls to SSL_write() with data to send. However calling SSL_write() with zero-length buffer is undefined behaviour. To emulate ordinary socket behaviour in this case and not to trigger 
 undefined behaviour from OpenSSL we explicitly check for zero-length buffer before calling SSL_write().

2018-06-09 14:03 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again to your contribution and we look forward to looking at it!

2018-06-15 10:20 UTC, rkondratenko commented
@njsmith I adopted your suggestions. Please take a look.

2018-06-16 12:27 UTC, vadmium commented on Lib/test/test_ssl.py
> +        ## Testing that SSLSopcet can handle empty input
Is this meant to be SSLSocket?

2018-07-03 10:59 UTC, rkondratenko commented
Any onther suggestions? Are you ready to merge?

2018-08-01 07:24 UTC, njsmith commented
The PR looks good to me, and I think the change is a good idea. @tiran, are you OK with this change? (Conversation in [bpo-31711](https://bugs.python.org/issue31711) was inconclusive.)

2018-08-01 08:38 UTC, tiran commented
I see a potential issue with this patch. Simply speaking, TLS/SSL has two different kinds of messages. There is application data and protocol data. SSL_write and SSL_read not only transmits application data, but they also flush and check for protocol data. That's why a read operation may also send data and a write operation may also read data.

This patch breaks the assumption that send() also takes care of protocol data. With TLS 1.2, it's not a big issue. Most critical protocol data like session and client cert auth are handled in the TLS handshake. However in TLS 1.3, the server side sends a TLS client auth request much later. Usually it occurs after the first write. Speaking of handshake, with this patch, send() may no longer establish a handshake with ``do_handshake_on_connect=False``, too.

I'm -1 on this patch. Let's figure out how to flush / check protocol data and handle implicit handshake correctly.

2018-08-01 08:39 UTC, tiran requested changes

2018-08-01 08:39 UTC, tiran commented on Modules/_ssl.c
> +        /*Sending 0 bytes to SSL_write is undefined behaviour per OpenSSL documentation.
Missing space after ``/*``.

2018-08-01 08:39 UTC, tiran commented on Modules/_ssl.c
> +        return PyLong_FromLong(0);
This breaks implicit handshake and possible TLS 1.3 edge cases, see comment.

2018-08-01 09:50 UTC, rkondratenko commented
I did a quick check of OpenSSL docs. There seems to be no easy way to process protocol messages without any other side-effects. Best candidate seems to be SSL_peek[_ex] but is has standard warning:

> When a read function operation has to be repeated because SSL_get_error(3) returned SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE, it must be repeated with the same arguments.

This means that we would have to save a flag in SSLSocket to call SSL_peek again with the same parameters on next calls. This would probably violate even more implicit assumtions.

Also, to send data before the end of the handshake in TLS 1.3 one has to explicitly call SSL_write_early_data. Current module doesn't do this anyway.

2019-05-31 11:06 UTC, slingamn commented
I recently encountered this issue and was very surprised by it. I very much agree that this patch improves on the current behavior.

Can anything be done to move forward with this?

2019-12-04 15:43 UTC, sylv3r commented
Just encountered this problem. What's the status of this issue ?
It seems staled for a year and a half now.

2019-12-04 23:18 UTC, njsmith commented
@tiran This still seems like an improvement to me, and I don't think your concerns are applicable to this case, but I don't want to just ignore them either...

2021-04-19 03:59 UTC, tiran commented
Thanks to PEP 644 the issue will be fixed in 3.10 by using SSL_read_ex and SSL_write_ex() functions. I couldn't use the functions earlier because Python had to support older OpenSSL versions and LibreSSL. https://github.com/python/cpython/pull/25468

2021-04-19 03:59 UTC, closed without merging