bpo-33818: PyExceptionClass_Name() will now return "const char *".
python/cpython pull request #7581
Opened 2018-06-10 06:45 UTC by serhiy-storchaka

This PR is purposed for backporting in 3.7. If this change will not be applied to 3.7, What's New will need to be changed.

2018-06-10 22:10 UTC, ned-deily requested changes
As noted on the bug issue, I do not see a compelling reason to introduce this interface change at this very late stage of the 3.7.0 release.   Let's target it for 3.8.

Also, note that the "make suspicious" check failed.

2018-06-10 22:29 UTC, ned-deily commented
I should note that I believe this arose because of the changes for bpo-33738 (#7585) which are trying to make the stable ABI usable again.  As I understand it, the change there should have minimal user impact as the stable ABI is obviously not being used with current versions of 3.x.

2018-06-11 13:17 UTC, serhiy-storchaka commented
Re-targeted for 3.8. I have made the requested changes; please review again.

2018-06-11 20:29 UTC, ned-deily approved these changes

2018-06-15 08:09 UTC, merged