bpo-33829: provide new object protocol helper for C API
python/cpython pull request #7625
Opened 2018-06-11 09:57 UTC by brgl

If we want to call an object's method from C code and pass it the args
and kwargs tuples unchanged, we need to first retrieve the callable
object using PyObject_GetAttrString(), then call it using
PyObject_Call().

This patch proposes to wrap the two calls in a new helper.

2018-06-11 09:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again for your contribution, we look forward to reviewing it!

2018-06-11 10:13 UTC, brgl commented
CLA is now signed.

2018-06-14 13:53 UTC, pablogsal requested changes

2018-06-14 13:53 UTC, pablogsal commented on Objects/call.c
> +    if (obj ==  NULL)
Please, use braces as indicated in pep 7: https://www.python.org/dev/peps/pep-0007/

2018-06-14 13:53 UTC, pablogsal commented on Objects/call.c
> +    if (callable == NULL)
Se comment above.

2018-06-14 13:55 UTC, pablogsal commented
Also, it seems that core developers are not sure that this change is needed. Can you discuss with them in the issue? Thanks! :)

2020-01-12 02:33 UTC, csabella commented
Closing this pull request as the bug tracker issue was rejected.

2020-01-12 02:33 UTC, closed without merging