[3.6] bpo-32356: idempotent pause_/resume_reading (GH-4914)
python/cpython pull request #7629
Opened 2018-06-11 11:54 UTC by vstinner

Backport note: don't add new is_reading() method from master to 3.6.

(cherry picked from commit d757aaf9dd767d13205bf9917e520ebf43e7f6e5)

2018-06-11 20:52 UTC, ned-deily requested changes

2018-06-11 20:52 UTC, ned-deily commented on Doc/library/asyncio-protocol.rst
> +      .. versionchanged:: 3.6.5
3.6.5 was already released, and you're going to have to hurry to make 3.6.6!

2018-06-11 20:52 UTC, ned-deily commented on Doc/library/asyncio-protocol.rst
> +      .. versionchanged:: 3.6.5
3.6.5 -> 3.6.?

2018-06-13 09:13 UTC, vstinner commented on Doc/library/asyncio-protocol.rst
> +      .. versionchanged:: 3.6.5
Oh. Fixed.

2018-06-13 09:13 UTC, vstinner commented
I have made the requested changes; please review again.

2018-06-13 09:38 UTC, ned-deily requested changes
The version should be 3.6.7, as it missed the cutoff for 3.6.6,

2018-06-13 09:45 UTC, vstinner commented
Oh. I missed the notification about 3.6.6 release (cut off). That's fine, it's a minor issue, no need to push it to 3.6.6.

I will merge this PR once 3.6.6 is released.

2018-06-13 09:45 UTC, vstinner commented
I have made the requested changes; please review again.

2018-06-13 09:49 UTC, ned-deily approved these changes

2018-06-13 10:05 UTC, merged

2018-06-13 10:06 UTC, vstinner commented
> I will merge this PR once 3.6.6 is released.

I read again @ned-deily's email: changes merged into 3.6 will be released as 3.6.7. So it's fine.