bpo-33832: Make "magic methods" a little more discoverable in the docs
python/cpython pull request #7630
Opened 2018-06-11 11:57 UTC by andresdelfino

2018-06-14 13:34 UTC, pablogsal commented on Doc/reference/datamodel.rst
> +operators.  For instance, if a class defines the special method :meth:`__getitem__`,
I think these are not the only occurrences of `method` referring to a magic method. A quick grep reveals that there are more places where the construction `the __something__ method` happens. Should we change these too to `__something__ special method`?

2018-06-14 13:44 UTC, pablogsal commented
Sorry for being repetitive over other PRs, but could you change the commit messages to include some context or squash them?

2018-06-14 14:54 UTC, andresdelfino commented on Doc/reference/datamodel.rst
> +operators.  For instance, if a class defines the special method :meth:`__getitem__`,
That's a pretty good question. After doing a couple of replacements, I tried a new grep search and found a lot more. I'm not really sure adding such verbosity helps.

IMHO, having just "method" everywhere, except in Data Model (where the special methods are described) is sufficient, also linking each reference to a special method to Data Model of couse.

The PR right now includes some "method" to "special method" changes. Please let me know what you think about this, and I'll continue with the replacements or revert the changes I made to the PR :)

2018-06-14 15:09 UTC, andresdelfino commented on Doc/reference/datamodel.rst
> +operators.  For instance, if a class defines the special method :meth:`__getitem__`,
A grep search shows that "special method" / "magic method" are not used much outside Data model. IMHO, we should keep this as it is. I believe it makes the documentation more readable.

2018-06-15 17:42 UTC, terryjreedy requested changes
I think these changes make the doc worse and that this PR should be closed.

2018-06-15 17:56 UTC, andresdelfino commented
@terryjreedy the initial commit was lost because I was asked to squash all commits, but it's intention was to just add "magic method" to the Glossary pointing to "special method", and add "magic method" as a synonym in Data model. I can revert this changes so you can see the original intention.

2018-06-15 18:33 UTC, pablogsal commented on Doc/reference/datamodel.rst
> +operators.  For instance, if a class defines the special method :meth:`__getitem__`,
As I said in the issue: Sorry if this question was interpreted as a change request. It was only me trying to understand the scope of the change (if you think this should be applied or not to the rest of the docs).

2018-06-15 18:42 UTC, andresdelfino commented on Doc/reference/datamodel.rst
> +operators.  For instance, if a class defines the special method :meth:`__getitem__`,
No problem, Pablo! We are all working to make Python better :)

2018-06-15 18:49 UTC, terryjreedy commented
PRs best stick to one subject.  I would be at least neutral to a simple glossary addition.
I don't want to promote the term 'magic method', but it is in use and I suspect various core developers are partly to blame.  So beginners do run across it and wonder how 'magic methods' are different from 'special methods'.  I would be even happier with 'an informal synonym ...'.

Add a blurb: Add glossary entry for 'magic method'.

Please get in the habit of including a blurb if you think one will be needed.  Once present, they are easy to edit through the web interface, without having to pull the PR.

2018-06-15 19:03 UTC, andresdelfino commented
I agree with marking the term informal.

Sorry for not adding the blurb. Didn't know it was needed, and have committed a couple of glossary terms with no blurb being requested, but I'll keep it in mind :)

I have made the requested changes; please review again

2018-06-15 19:08 UTC, terryjreedy commented
Never squash a PR.  The merge message (commit to master repository message) is ultimately written by the core dev who merges.  But it is nice if the initial commit message under the title is at least an approximation.  It can be edited in, as I just did.

The boilerplate message about backporting should be deleted before hitting the [submit PR] button.

2018-06-15 19:11 UTC, andresdelfino commented
Yes, that was my understanding too, but I was asked to squash the commits. I'll have this in mind next time.

2019-01-10 16:04 UTC, vstinner commented
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

2019-02-21 17:28 UTC, merwok commented
I like this addition!

Would one or two index entries also be useful?

2019-02-21 18:51 UTC, andresdelfino commented
> I like this addition!
> 
> Would one or two index entries also be useful?

I think so, good idea! I'll add it.

2019-02-22 21:22 UTC, andresdelfino commented
@merwok Done! I added index entries for magic method and special method as well.

2019-02-28 23:40 UTC, merwok approved these changes

2019-03-26 23:27 UTC, andresdelfino commented
@merwok perhaps we can merge this?

2019-03-27 01:21 UTC, merged

2019-03-27 01:21 UTC, miss-islington commented
Thanks @andresdelfino for the PR, and @merwok for merging it 🌮🎉.. I'm working now to backport this PR to: 2.7, 3.7.
🐍🍒⛏🤖