bpo-32568: make select.epoll() and its docs consistent
python/cpython pull request #7840
Opened 2018-06-21 06:45 UTC by taleinat

The docs for `select.epoll()` are currently out of sync with the implementation with regard to the `sizehint` and `flags` parameters.

* 'flags' is indeed deprecated, but there was a validation on its value, contrary to the docs saying it is "completely ignored".  This removes that check.
* 'sizehint' is still used when 'epoll_create1()' is unavailable, so this adds mention of this in the docs.
* Make 'sizehint' accept -1 again, which is replaced with FD_SETSIZE-1.  This is needed to have a default value available at the Python level  allowing to set this, since FD_SETSIZE is not exposed to Python.  (see: bpo-31938)

2018-06-22 11:26 UTC, vstinner requested changes
I don't think that it's correct to ignore flags. I prefer to keep the check rejecting invallid values like flags=12345.

I'm not sure why Python wants to reject unknown flags: can't we rely on the kernel/libc to validate flags?

2018-06-22 11:26 UTC, vstinner commented on Misc/NEWS.d/next/Library/2018-06-21-09-33-02.bpo-32568.f_meGY.rst
> +make select.epoll() and its docs consistent re. *sizehint* and *flags*
Please avoid abbreviation, english is not my first language and I don't know what "re." means. Add also an uppercase to "Make".

2018-06-22 11:47 UTC, taleinat commented
> I don't think that it's correct to ignore flags. I prefer to keep the check rejecting invallid values like flags=12345.
>
> I'm not sure why Python wants to reject unknown flags: can't we rely on the kernel/libc to validate flags?

Other than that value check, the existing code completely ignores the `flag` parameter.  It is not used at all and specifically isn't passed to any C function.  This change merely removes an unnecessary and meaningless value check.

2018-06-22 11:47 UTC, taleinat commented
I have made the requested changes; please review again.

2018-06-25 14:37 UTC, serhiy-storchaka commented
The argument passed to `epoll_create()` must be positive. Currently `select.epoll()` is always failed if `epoll_create1()` is unavailable. I think we should not accept `sizehint=0`.

And I think it is better to keep the check for *flags*. This can help to backport Python programs to older versions (the same reason as keeping the check for the argument of `epoll_create()` in the Linux kernel).

In future we will get rid of both parameters. Maybe will start producing a deprecation warning in 3.8.

2018-06-25 21:29 UTC, taleinat commented
@serhiy-storchaka, this is ready for another review.

2018-06-26 05:24 UTC, serhiy-storchaka approved these changes
Thanks @taleinat!

2018-06-30 12:43 UTC, merged

2018-06-30 12:43 UTC, miss-islington commented
Thanks @taleinat for the PR 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖

2018-06-30 12:45 UTC, miss-islington commented
Sorry, @taleinat, I could not cleanly backport this to `3.6` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker 0cdf5f42898350261c5ff65d96334e736130780f 3.6
                            ```