bpo-33922: Adding documentation for new "-64" suffix of python launcher
python/cpython pull request #7849
Opened 2018-06-21 19:01 UTC by mrh1997

since bpo-30291 it is possible to specify as bit length of the python
version to be not only 32bit but alternatively to be 64bit.

2019-03-19 23:11 UTC, csabella commented on Doc/using/windows.rst
> +located and used. Please note that the option to specifify "-64"
s/specifify/specify

2019-03-19 23:11 UTC, csabella commented on Doc/using/windows.rst
> +(in contrary to "-32") and the option to specifify an major and architecture
a/specifify/specify

2019-03-19 23:14 UTC, csabella commented on Doc/using/windows.rst
> +without minor are supported since the python launcher 3.7.
I don't think you need to mention the launcher version here.

2019-03-19 23:15 UTC, csabella commented on Doc/using/windows.rst
> +('.') and a minor version specifier. Furthermore it is possible to specifiy
s/specifiy/specify

2019-03-19 23:17 UTC, csabella commented on Doc/using/windows.rst
> +or newer.
Again, I don't think you need to mention the Python Launcher here.  Also, you would only need the versionadded in one place.

2019-03-19 23:17 UTC, csabella commented on Doc/using/windows.rst
> +3.7 or newer.
Same comment about mentioning the availability.

2019-04-12 18:23 UTC, zooba requested changes
Some readability improvements, but there's one particular section that is out of date so let's update the whole section now.

2019-04-12 18:23 UTC, zooba commented on Doc/using/windows.rst
> +Furthermore the 32bit version can be enforced by adding "-32" after the
"Request[ed]", not "enforce[d]". And we generally spell them "32-bit" and "64-bit" in prose, rather than omitting the hyphen.

2019-04-12 18:23 UTC, zooba commented on Doc/using/windows.rst
> +3.7 or newer.
There are a few outdated parts of this paragraph. How about:

```
If no version qualifiers are found in a command, the environment
variable :env:`PY_PYTHON` can be set to specify the default version
qualifier. If it is not set, the default is "3". The variable can
specify any value that may be passed on the command line, such as "3",
"3.7", "3.7-32" or "3.7-64". (Note that the "-64" option is only
available with the launcher included with Python 3.7 or newer.)
```

2019-04-12 18:23 UTC, zooba commented on Doc/using/windows.rst
> +installed last). As noted above, an optional "-32" / "-64" suffix can be
```suggestion
installed last). As noted above, an optional "-32" or "-64" suffix can be
```

2019-04-12 18:23 UTC, zooba commented on Doc/using/windows.rst
> +Furthermore the 32bit version can be enforced by adding "-32" after the
These come up a few times in the text below, but I'm not commenting on each indivdual one.

2019-04-12 21:49 UTC, mrh1997 commented
I have made the requested changes; please review again

2019-04-12 22:25 UTC, zooba commented
For what it's worth, when you force push an update it means I can't review your changes and have to re-review the whole thing again. We always squash and edit commit messages, which means the final result looks neat no matter how many commits it took to get there.

Thanks for the improvements!

2019-04-12 22:25 UTC, zooba approved these changes

2019-04-12 22:26 UTC, merged

2019-04-12 22:26 UTC, miss-islington commented
Thanks @mrh1997 for the PR, and @zooba for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖