bpo-33921: Clarify how to bind to all interfaces using socket
python/cpython pull request #7877
Opened 2018-06-23 14:54 UTC by johnthagen

Fixes https://bugs.python.org/issue33921

2018-06-23 14:54 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


When your account is ready, please add a comment in this pull request
and a Python core developer will remove the `CLA not signed` label
to make the bot check again.

Thanks again for your contribution, we look forward to reviewing it!

2018-06-23 14:57 UTC, johnthagen commented
Updated b.p.o account to associate GitHub username.

2018-06-23 18:13 UTC, ammaraskar requested changes

2018-06-23 18:13 UTC, ammaraskar commented on Doc/library/socket.rst
> +  - For IPv4 addresses, two special forms are accepted instead of a host
You've got trailing whitespace on some of these lines, aside from that the content looks good.

2018-06-23 19:08 UTC, ammaraskar commented
Still one line left with trailing whitespace: https://travis-ci.org/python/cpython/jobs/395902432#L544

fyi, you can catch these locally before pushing by running `make patchcheck` https://devguide.python.org/pullrequest/#patchcheck

2018-06-23 19:16 UTC, johnthagen commented
@ammaraskar  Thanks for the heads up. Been editing in the browser for this for simplicity, but I'll note that for next time if it's a more substantial PR.

2018-06-23 19:20 UTC, ammaraskar approved these changes
Looks good to me, can be marked with skip news since its a minor doc change.

2018-07-01 12:13 UTC, johnthagen commented
@ned-deily Are you available to review?

2018-07-28 10:02 UTC, tiran approved these changes

2018-07-28 10:03 UTC, merged

2018-07-28 10:03 UTC, miss-islington commented
Thanks @johnthagen for the PR, and @tiran for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!