bpo-33881: Use NFKC to find duplicate members in make_dataclass
python/cpython pull request #7916
Opened 2018-06-25 21:58 UTC by ValeriyaSinevich

I measured how it affected the performance by creating a dataclass with 10000 members.
python.bat -m timeit -s "from dataclasses import make_dataclass" -s "arg_list = [chr(k) * i for k in range(97, 123) for i in range(1, 500)]" "make_dataclass('a', arg_list)" 
The performance didn't change, both before and after the changes it takes around 14.5s.

2018-06-25 22:09 UTC, ericvsmith requested changes
This will require some tests. Can you add them?

I haven't had time to give a thorough review, but I will once there are some basic tests.

Thanks!

2019-05-23 22:25 UTC, csabella commented
@ValeriyaSinevich, please make the changes requested in the code review and please fix the merge conflict.  Thanks!

2020-01-07 15:03 UTC, ericvsmith commented
@ValeriyaSinevich : Any chance you can add the tests to the PR?

2020-06-12 11:59 UTC, csabella commented
I'm going to close this pull request as inactive.  It can be reopened if the original author comes back to working on it or someone else can create a new PR.  If a new PR is created and the original change is used, please credit the original author as co-author.

2020-06-12 11:59 UTC, closed without merging