bpo-33978: close resources before deletion of logging handlers
python/cpython pull request #8008
Opened 2018-06-29 12:36 UTC by tirkarthi

Close the file handlers before deleting the logging handlers so that there is no resource warning. Since the handlers are a weakreference I tried to close them by calling `self.close` on `__del__` but not all handlers have the `lock` attribute which resulted in `AttributeError`. `shutdown` handles the `AttributeError` and other scenarios but it will be a much cleaner if we close the handlers during weakref deletion instead of calling shudown which might miss some places.

Additionally shutdown is also registered at exit which should clean up the current handlers I hope but doesn't handle the ones that were deleted.

Attached tests and a NEWS entry. Kindly correct me if I am wrong on the approach since this is my first non-easy PR and I would like some help on this fix hoping the fix will not be much complex.

Thanks

2018-06-29 13:03 UTC, tirkarthi commented
Windows builds for `fileConfig` fails with unicodeescape error and the one for `dictConfig` fails with permission error to open the file though tests pass on Linux and MacOS. I don't have a windows machine to test this and any pointers will be helpful in fixing the tests.

2018-07-01 21:31 UTC, vsajip requested changes

2018-07-01 21:31 UTC, vsajip commented on Lib/logging/config.py
> +
The 3 lines
```
logging._handlers.clear()
logging.shutdown(logging._handlerList[:])
del logging._handlerList[:]
```
are now in two places - at line 76 and line 531. I suggest adding a module-level function `_clearExistingHandlers()` which does these operations, along with two calls to them from those locations.

Also, `logging.shutdown()` takes `_handlerList` as a default argument, so it is not necessary to pass the argument to it.

2018-07-01 21:31 UTC, vsajip commented on Misc/NEWS.d/next/Library/2018-06-29-12-23-34.bpo-33978.y4csIw.rst
> +Close resources before deleting logging handlers. Patch by Karthikeyan
Change to "Closed existing logging handlers before reconfiguration via fileConfig and dictConfig".

2018-07-01 21:31 UTC, vsajip commented on Lib/test/test_logging.py
> +    keys=file_handler
Could just name as `file` rather than `file_handler`. The section below then becomes `[handler_file]` rather than `[handler_file_handler]`.

2018-07-01 21:31 UTC, vsajip commented on Lib/test/test_logging.py
> +                self.apply_config(self.config8.format(tempfile=f.name))
You could do the formatting just once to a local string, and then use that.

2018-07-01 21:31 UTC, vsajip commented on Lib/test/test_logging.py
> +            with tempfile.NamedTemporaryFile() as f:
Use the approach used elsewhere in this file with `fd, fn = tempfile.mkstemp(".log", "test_logging-X-")` followed by closing the `fd`. This allows tracing of where the temp file came from, in the odd case where it isn't deleted for some reason. It should also ensure that the file is writable, or fail at this point rather than later.

2018-07-02 06:34 UTC, tirkarthi commented
I have made the requested changes; please review again

2018-07-02 06:49 UTC, tirkarthi commented
The windows build fails due to the below : 

1. With respect fileConfig test formatting the string results in path having `\Users` and hence a unicodeescape error is produced. I have tried raw string suggested in [SO answer](https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file) but as noted in the comments it seems not to work for ''' quoted strings and I have to manually escape \\ myself as per the [comment](https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file#comment48889405_1347854). 

2. With respect to dictConfig I can see two errors. One in VSTS there is permissionDenied error which I hope is due to permission error but there is a comment in https://github.com/python/cpython/commit/f315df31bd8a927768bb94c3342d155cdc87d997 that `This exception is thrown when a directory with the chosen name already exists on windows.` . In AppVeyor I cannot see the error and hence the file is created successfully but it seems that dicConfig uses the file handler and hence `os.unlink(fn)` fails since windows doesn't allow deleting files already used by the process. But trying to close the handler before calling `os.unlink` kind of removes the point of testing the resource leak.

[os.remove](https://docs.python.org/3.8/library/os.html#os.remove)

> On Windows, attempting to remove a file that is in use causes an exception to be raised; on Unix, the directory entry is removed but the storage allocated to the file is not made available until the original file is no longer in use.

I don't have a windows machine to test this and if mkstemp failure is due to the name being already present then I don't know why I could see it in other tests like test_tempfile.py. Perhaps there is a better way to test this I am not aware of?

Thanks

2018-07-02 08:47 UTC, tirkarthi commented
@vsajip I think I have fixed the issues with respect to windows. 

1. I have added code to replace '\\' with '\\\\' as I came across another [gotcha](https://pythonconquerstheuniverse.wordpress.com/2008/06/04/gotcha-%E2%80%94-backslashes-are-escape-characters/) where using raw string makes it look like it's escaping the backslash but actually only escapes while printing and the backslashes are not escaped in the string.

2. The case where deleting a file while it's used by another process in windows I have added a cleanup method like other tests in the file where the handler is closed and then the actual file is deleted safely using `os.remove`. I have verified that manually doing it doesn't affect the test cases for warnings by removing the `_cleanExistingHandlers` call that causes the warnings to happen in the tests.

On an additional note I think this bug is also present in Python 2.7 and I hope a backport is feasible. Ref : https://github.com/python/cpython/blob/9b84cc8771f52e9340ea5b676da9a15359c723b6/Lib/logging/config.py#L83

Thanks

2018-07-02 08:52 UTC, vsajip commented
> The case where deleting a file while it's used by another process in windows I have added a cleanup method like other tests in the file where the handler is closed and then the actual file is deleted safely using os.remove.

Removing the file shouldn't be needed, just closing it should be enough. If you can delete the file, it means it can't be held open in another process.

2018-07-02 08:55 UTC, vsajip approved these changes

2018-07-02 08:57 UTC, tirkarthi commented
Sorry, to be clear I am not deleting the file in logging handler I am talking about the test case related scenario in mkstemp where the file is not deleted automatically and the user has to delete the file on his own. Since the file is used only by the single test process then I think the file has to be deleted in the test case at the end in the cleanup method. Correct me if I am wrong or misunderstood your reply.

Thanks

2018-07-02 08:57 UTC, merged

2018-07-02 08:58 UTC, vsajip commented
Thanks for your work on this.

2018-07-02 08:59 UTC, tirkarthi commented
Sure, thanks much for your review comments and guidance. Does this need to be backported to 3.7, 3.6 and 2.7?

2018-07-02 09:02 UTC, miss-islington commented
Thanks @tirkarthi for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2018-07-02 09:03 UTC, miss-islington commented
Thanks @tirkarthi for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6.
🐍🍒⛏🤖

2018-07-02 09:03 UTC, miss-islington commented
Thanks @tirkarthi for the PR, and @vsajip for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7.
🐍🍒⛏🤖

2018-07-02 09:03 UTC, miss-islington commented
Sorry, @tirkarthi and @vsajip, I could not cleanly backport this to `3.6` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker 087570af6d5d39b51bdd5e660a53903960e58678 3.6
                            ```

2021-02-11 09:47 UTC, flyte commented
> Close the file handlers before deleting the logging handlers so that there is no resource warning.

Don't you only want to do this if `disable_existing_loggers == True`?

This change is causing the socket on configured SysLogHandlers to be closed, throwing an error when they're used, for example:

```python
import logging.config
import socket
from logging.handlers import SysLogHandler

log = logging.getLogger("logtest")
syslog_handler = SysLogHandler(("127.0.0.1", 12345), socktype=socket.SOCK_DGRAM)
log.addHandler(syslog_handler)

log.warning("Works")

logging.config.dictConfig(
    {
        "version": 1,
        "disable_existing_loggers": False,
    }
)

log.warning("Breaks")
```
Causes:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 940, in emit
    self.socket.sendto(msg, self.address)
OSError: [Errno 9] Bad file descriptor
Call stack:
  File "/home/flyte/workspaces/python/test.py", line 18, in <module>
    log.warning("Breaks")
```