bpo-34032: Add platlibdir as an option for distinguishing /usr/lib and /usr/lib64
python/cpython pull request #8068
Opened 2018-07-03 16:41 UTC by mcepl

Build system has been modified to allow /usr/lib64 as well as /usr/lib into install path as well as to the search path for the Linux distributions which distinguish between 32bit and 64bit libraries.

2018-07-04 15:39 UTC, vstinner requested changes
The new "platlibdir" variable should be documented in Doc/library/sysconfig.rst:
https://docs.python.org/dev/library/sysconfig.html#installation-paths

You have to add it to the list, and also add a ".. versionchanged:: 3.8 (...)" markup to document the change.

IMHO it's worth it to also add a *second* NEWS entry for the sysconfig change (new "platlibdir" variable).

2018-07-04 15:39 UTC, vstinner commented on Misc/NEWS.d/next/Build/2018-07-03-18-36-35.bpo-34032.bSAQzz.rst
> +distinguish between 32bit and 64bit libraries.
Can you mention the new --with-custom-platlibdir=<libdirname> configure option somewhere?

Nitpick: I would write "32 bit and 64 bit libraries" ;-) (or "32-bit and 64-bit libraries")

2018-07-04 15:48 UTC, vstinner reviewed
The OpenSUSE patch only changes the "unix_prefix" scheme, but the Fedora patch also changes the 'unix_home' scheme. To be honest, I don't understand well this change.

2018-07-04 16:11 UTC, mcepl commented
Hmm, this pull request fails on AppVeyor with:
```
======================================================================
ERROR: test_user_site (distutils.tests.test_install.InstallTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cpython\lib\distutils\tests\test_install.py", line 114, in test_user_site
    cmd.ensure_finalized()
  File "C:\projects\cpython\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "C:\projects\cpython\lib\distutils\command\install.py", line 330, in finalize_options
    self.create_home_path()
  File "C:\projects\cpython\lib\distutils\command\install.py", line 536, in create_home_path
    if path.startswith(home) and not os.path.isdir(path):
AttributeError: 'NoneType' object has no attribute 'startswith'
----------------------------------------------------------------------
Ran 246 tests in 32.131s
FAILED (errors=1, skipped=24)
test test_distutils failed
```
and with

```
test_user_similar (test.test_sysconfig.TestSysConfig) ... test test_sysconfig failed
ERROR
======================================================================
ERROR: test_get_path (test.test_sysconfig.TestSysConfig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cpython\lib\test\test_sysconfig.py", line 100, in test_get_path
    res = get_path(name, scheme)
  File "C:\projects\cpython\lib\sysconfig.py", line 506, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "C:\projects\cpython\lib\sysconfig.py", line 496, in get_paths
    return _expand_vars(scheme, vars)
  File "C:\projects\cpython\lib\sysconfig.py", line 170, in _expand_vars
    res[key] = os.path.normpath(_subst_vars(value, vars))
  File "C:\projects\cpython\lib\sysconfig.py", line 151, in _subst_vars
    raise AttributeError('{%s}' % var) from None
AttributeError: {'installed_base'}
======================================================================
ERROR: test_user_similar (test.test_sysconfig.TestSysConfig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\cpython\lib\test\test_sysconfig.py", line 267, in test_user_similar
    global_path = get_path(name, 'posix_prefix')
  File "C:\projects\cpython\lib\sysconfig.py", line 506, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "C:\projects\cpython\lib\sysconfig.py", line 496, in get_paths
    return _expand_vars(scheme, vars)
  File "C:\projects\cpython\lib\sysconfig.py", line 170, in _expand_vars
    res[key] = os.path.normpath(_subst_vars(value, vars))
  File "C:\projects\cpython\lib\sysconfig.py", line 151, in _subst_vars
    raise AttributeError('{%s}' % var) from None
AttributeError: {'installed_base'}
----------------------------------------------------------------------
Ran 21 tests in 0.084s
```

2019-07-27 18:25 UTC, Fak3 commented
Was this superseded by #11755 ?

2020-03-10 08:55 UTC, vstinner commented
I merged PR #18381 instead which is very similar. Thanks @mcepl for helping on PR #18381.

2020-03-10 08:55 UTC, closed without merging