bpo-23926: Fix handling for removed PyArg_ParseTuple formatters
python/cpython pull request #8204
Opened 2018-07-09 16:05 UTC by llllllllll

re-opening this as a github pull request @serhiy-storchaka 

The only difference from the old patch is that I used `blurb` to write the news entry.

2018-07-11 14:36 UTC, vstinner commented on Python/getargs.c
> +    case 'w': /* buffer, read-write */
Would you mind to move back this block to line 2323 to make the change simpler to follow/review? Here it seems like you are adding *new* code, rather than modifying existing code.

2018-07-23 19:01 UTC, llllllllll commented on Python/getargs.c
> +    case 'w': /* buffer, read-write */
This actually is new code, not just a change. Moving it would alter the functionality due to the way the fall through works.

2018-07-23 19:38 UTC, serhiy-storchaka commented
Please merge with master and resolve conflicts with bpo-23927.

2019-06-28 04:38 UTC, ZackerySpytz commented on Modules/_testcapimodule.c
> +            Py_DECREF(args);
I believe `kwargs` should be decrefed here as well.

2019-06-28 04:38 UTC, ZackerySpytz commented on Modules/_testcapimodule.c
> +            Py_DECREF(args);
I believe `kwargs` should be decrefed here as well.

2019-06-28 04:38 UTC, ZackerySpytz commented on Modules/_testcapimodule.c
> +    for (n = 0;formats_3[n];++n) {
```suggestion
    for (n = 0; formats_3[n]; ++n) {
```

2019-06-28 04:38 UTC, ZackerySpytz commented on Modules/_testcapimodule.c
> +    for (n = 0;formats_4[n];++n) {
```suggestion
    for (n = 0; formats_4[n]; ++n) {
```

2019-06-28 04:38 UTC, ZackerySpytz commented on Modules/_testcapimodule.c
> +    if (!(kwargs = PyDict_New()) || PyDict_SetItemString(kwargs, "c", Py_None)) {
Please limit lines to 79 chars.

2020-02-06 22:43 UTC, csabella commented
@llllllllll, please resolve the merge conflicts and address the code review.  Thank you!

2022-05-18 15:47 UTC, MaxwellDupre approved these changes
Test_capi produces:
Ran 40 tests in 7.553s
OK
Looks ok.

2022-12-07 18:58 UTC, iritkatriel requested changes, later dismissed
This has merge conflicts now.

2024-03-19 09:07 UTC, encukou commented on Python/getargs.c
> +    case 'w': /* buffer, read-write */
Unfortunately it's missing the `va_arg` call from the code it's replacing, so it fails to skip `w*` properly.

2024-03-19 09:14 UTC, encukou commented
After a few years of unresolved comments I think I can take over the PR.
I've updated the branch, and fixed conflicts and the functionality. But there's enough new content that I'd appreciate another review.

2024-04-23 11:15 UTC, merged