bpo-29910: IDLE no longer delete character after commenting out a region
python/cpython pull request #825
Opened 2017-03-26 17:31 UTC by serhiy-storchaka

by key shortcut.  Fixed also other potential conflicts between IDLE's and
default key bindings.

2017-03-26 22:21 UTC, terryjreedy requested changes
Review on b.p.o, tests needed

2017-06-27 02:38 UTC, terryjreedy commented on Misc/NEWS
> +
I will move this to separate file, as now required.

2017-06-27 02:53 UTC, terryjreedy commented on Misc/NEWS
> +
This news item was misplaced anyway, under the 3.6b1 section.

2017-06-27 04:02 UTC, merged

2017-06-27 04:33 UTC, serhiy-storchaka commented
Thanks for merging this Terry.