Issue20774
python/cpython pull request #830
Opened 2017-03-27 01:40 UTC by lisroach

PR for [issue 20774](http://bugs.python.org/issue20774), adding a JSON serializer to collections.deque.

2017-03-27 06:09 UTC, rhettinger requested changes
Over this looks good. Can you please add some tests.

2017-03-27 09:43 UTC, Birne94 commented on Modules/_json.c
> +    PyObject *mo = PyImport_ImportModule("collections");
Wouldn't you need to decrease the reference counter to `mo` and `deque_type` after using them?

2018-02-21 01:51 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2019-01-14 03:55 UTC, sakurai-youhei commented
For those who arrived here like me when searching quick solution to encode dqeue object into JSON; Below code (as per [documentation](https://docs.python.org/3/library/json.html#json.JSONEncoder.default)) shall be good enough.

```
from collections import deque
from json import dumps, JSONEncoder

class JSONEncoderSupportingArbitraryIterators(JSONEncoder):
    def default(self, o):
        try:
            iterable = iter(o)
        except TypeError:
            pass
        else:
            return list(iterable)
        # Let the base class default method raise the TypeError
        return json.JSONEncoder.default(self, o)

dumps(deque(range(10)), cls=JSONEncoderSupportingArbitraryIterators)
```

2019-03-04 20:45 UTC, carlbordum commented
@lisroach are you interested in writting the tests, or may I? :)

2019-03-06 05:18 UTC, lisroach commented
Sorry, just realized I had this sitting for so long! @carlbordum feel free to add more tests if you think of them :)

2019-03-06 05:24 UTC, matrixise commented on Lib/test/test_json/test_dump.py
> +
Maybe you could remove this blank line

2019-03-06 05:24 UTC, matrixise commented on Lib/test/test_json/test_dump.py
Why this line ?

2019-06-05 01:09 UTC, csabella commented
@lisroach, should this pull request be closed based on the performance benchmarks mentioned on the bug tracker or were you still working on this change?  Thanks!

2022-06-29 19:14 UTC, erlend-aasland commented
@lisroach, are you going to follow up this PR?

2022-07-09 15:03 UTC, kumaraditya303 commented
Closing because of lack of response and conflicts, feel free to reopen if you want to work on this.

2022-07-09 15:03 UTC, closed without merging