bpo-34125: enable profiling of method_descriptor in all cases
python/cpython pull request #8416
Opened 2018-07-23 14:44 UTC by jdemeyer

Needs backport to 3.7

2018-07-30 08:57 UTC, jdemeyer commented
@serhiy-storchaka @vstinner What do you think of this?

2018-07-31 15:20 UTC, vstinner requested changes
I would prefer to have a wider discussion on function calls: https://bugs.python.org/issue29502

2018-08-01 07:53 UTC, jdemeyer commented
> I would prefer to have a wider discussion on function calls: https://bugs.python.org/issue29502

Regardless of the wider discussion, I think that this is a bug which should be fixed anyway.

Anyway, if you don't like my PR, that's fine and I will close it. But I see no reason for waiting.

2018-08-02 07:46 UTC, jdemeyer commented
Which changes should be made?

2018-08-08 08:13 UTC, jdemeyer commented
I have made the requested changes; please review again (reason: no changes were actually requested)

2018-09-19 09:17 UTC, methane commented
@jdemeyer I think it's OK to merge this to move PEP 580 forward.
BTW, is this really need to backport?  I'm not sure this little inconsistency is really a bug.

2018-09-19 10:06 UTC, methane approved these changes

2018-09-19 10:06 UTC, merged

2018-09-20 05:52 UTC, jdemeyer commented
Thanks for merging it!

I have no strong opinions on the backport. I just see no reasons to *not* backport it: it's a tiny bug fix which can easily be backported. And having a few more C calls profiled seems unlikely to break stuff.