bpo-13407: Mention that tarfile doesn't support multistream bzip2 files
python/cpython pull request #8428
Opened 2018-07-23 22:56 UTC by andresdelfino

2018-07-28 15:32 UTC, BoboTiG approved these changes
Thanks!
It seems fine to me except that I would have used the word "Modules" instead of "Packages". But this is a detail :)

2018-09-29 16:28 UTC, briancurtin requested changes
I agree with @BoboTiG in that this should be called a module instead of package, as the listed workaround is a module. Otherwise this looks like a good idea.

Are you able to add a `news` entry for this? [This page](https://devguide.python.org/committing/?highlight=backport#what-s-new-and-news-entries) outlines how to do it.

2018-09-29 16:41 UTC, andresdelfino commented
Thanks for the comments!

I have made the requested changes; please review again

2018-09-29 16:55 UTC, briancurtin approved these changes

2018-09-29 16:57 UTC, merged