bpo-25083: Python 2 can sometimes create incorrect .pyc files
python/cpython pull request #8449
Opened 2018-07-24 19:08 UTC by tzickel

Python 2 never checked for I/O error when reading .py files and
thus could mistake an I/O error for EOF and create incorrect .pyc
files. This adds an check for this and aborts on an error.

2018-07-26 06:42 UTC, tzickel commented
If someone can add / remove a label to update the the-knights-who-say-ni bot.

2018-07-28 14:52 UTC, encukou commented
This looks good except for the use of `E_EOF`. That should be reserved for end-of-file, but in this case here we're *not* getting to the end of file.
I don't see a good `E_` constant for read errors in the current list. Could you add a new one in `Include/errcode.h` and `Python/pythonrun.c`, so that this gets a proper error message?

2018-07-28 15:02 UTC, encukou commented
And don't worry about the backport title; that's for the person who'll merge this.

2018-07-28 16:45 UTC, tzickel commented
Actually not doing this E_EOF causes this to behave badly...

2018-07-29 04:43 UTC, tzickel commented
Done.

2018-07-29 04:57 UTC, tzickel commented
Here is a script to check for the bug:
https://gist.github.com/tzickel/2ab09100ea21ca0e1e6709c337194bff
needs a recent strance (ubuntu 18.04 or debian sed is fine), and if run inside a docker, the docker needs to be run with --cap-add SYS_PTRACE for strace to work.

2018-07-31 15:33 UTC, vstinner requested changes

2018-07-31 15:33 UTC, vstinner commented on Parser/tokenizer.c
> +        tok->done = E_IO;
Hum, should we call clearerr() here? In case if fp is used again.

2018-08-01 08:01 UTC, tzickel commented
I have made the requested changes; please review again

2018-08-01 16:14 UTC, vstinner approved these changes
LGTM, but I would prefer that someone else merge it.

2018-09-03 18:02 UTC, tzickel commented
@encukou I'm waiting for the convincing part :) I think it's best to merge this ASAP (if it's plan to be used), so it has maximum exposure before a new release.

2018-09-10 18:46 UTC, merged