bpo-34240: Convert test_mmap to use tempfile
python/cpython pull request #8486
Opened 2018-07-26 19:38 UTC by tjguk

test_mmap currently uses the test.support.TESTFN functionality which creates a temporary file local to the test directory named around the pid.

This can give rise to race conditions where tests are competing with each other to delete and recreate the file.

This change converts the tests to use tempfile.mkstemp which gives a different file every time from the system's temp area

2018-07-27 06:56 UTC, berkerpeksag commented on Lib/test/test_bz2.py
> +        except FileNotFoundError:
You can use `unlink` from `test.support`. It already catches `FileNotFoundError` and works fine on Windows. (This comment also applies to https://github.com/python/cpython/commit/6a62e1d365934de82ff7c634981b3fbf218b4d5f.)

https://github.com/python/cpython/blob/master/Lib/test/support/__init__.py#L410-L414

2018-07-27 08:00 UTC, taleinat requested changes
ISTM the changes to `test_bz2.py` were included here by mistake.

2018-07-27 08:00 UTC, taleinat commented on Lib/test/test_mmap.py
> +        tp = str(type(m))  # SF g 128713:  segfaulted on Linux
?

2020-05-29 10:08 UTC, csabella commented
@tjguk please take a look at the code reviews and also please resolve the merge conflicts.  Thank you!

2020-05-29 10:09 UTC, closed without merging