Document cgitb.text and cgitb.html
python/cpython pull request #849
Opened 2017-03-27 13:57 UTC by masklinn

2017-03-27 13:57 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-03-27 16:49 UTC, marco-buttu commented on Doc/library/cgitb.rst
> +   Handles the exception described by *info* (a 3-tuple containing the result of
You should write _This function handles_, as in the rest of the file.

2017-03-27 16:49 UTC, marco-buttu commented on Doc/library/cgitb.rst
> +   :func:`sys.exc_info`), formatting its traceback as html and returning the
It should be `HTML` (uppercase), as in the rest of the file.  It is lowercase only for the string argument.

2017-03-27 22:21 UTC, vadmium commented on Doc/library/cgitb.rst
> +.. function:: text(info[, context=5])
The square bracket notation conflicts with the notation in the rest of the page

2017-04-15 02:09 UTC, berkerpeksag requested changes

2017-04-15 02:09 UTC, berkerpeksag commented on Doc/library/cgitb.rst
> +.. function:: text(info[, context=5])
Martin is correct. The signature should read `text(info, context=5)`.

2017-04-17 11:34 UTC, masklinn commented on Doc/library/cgitb.rst
> +   Handles the exception described by *info* (a 3-tuple containing the result of
Intro fixed.

2017-04-17 11:34 UTC, masklinn commented on Doc/library/cgitb.rst
> +   :func:`sys.exc_info`), formatting its traceback as html and returning the
Casing fixed.

2017-04-17 11:34 UTC, masklinn commented on Doc/library/cgitb.rst
> +.. function:: text(info[, context=5])
Argspec fixed.

2017-05-02 19:09 UTC, masklinn commented
PR updated to take reviews in account.

2017-05-05 08:14 UTC, berkerpeksag approved these changes

2017-05-05 08:15 UTC, merged

2017-05-05 08:15 UTC, berkerpeksag commented
Thanks!