bpo-34272: Reorganize C API tests.
python/cpython pull request #8551
Opened 2018-07-29 13:15 UTC by serhiy-storchaka

Move most C API tests into Lib/test/test_capi/.

2018-08-16 03:10 UTC, auvipy approved these changes

2022-03-27 04:56 UTC, arhadthedev commented
Is the idea to group C API tests still feasible? It would be great to immediately see from a file structure that `test_getargs2.py` and `test_structmembers.py` are not about Python libraries or their module backends.

2022-11-09 10:55 UTC, iritkatriel requested changes
Merge conflicts need to be resolved.

2022-11-10 06:17 UTC, serhiy-storchaka commented
Thank you for a reminder. I completely forget about this simple PR.

2022-11-10 06:54 UTC, merged

2022-11-10 06:55 UTC, miss-islington commented
Thanks @serhiy-storchaka for the PR 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2022-11-10 06:55 UTC, miss-islington commented
Thanks @serhiy-storchaka for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖