bpo-34246: Use no mutable default args in smtplib
python/cpython pull request #8554
Opened 2018-07-29 14:59 UTC by scorphus

Some methods of the SMTP class use mutable default arguments. Specially `send_message` is affected in which it mutates one of the args by appending items to it, whic has side effects on further calls.

2018-08-06 08:41 UTC, scorphus commented
Hello, @serhiy-storchaka.

Thanks so much for reviewing my changes. It's now cleaner with tuples 👍

I'm not sure whether I should ping you or if the new commit (67f70fd) triggers that automatically.

2018-08-06 09:32 UTC, serhiy-storchaka commented on Misc/NEWS.d/next/Library/2018-07-29-15-25-15.bpo-34246.xiKq-Q.rst
> +Use an empty tuple as the default argument for mail_options and avoid it from
The argument for what function? Using an empty tuple is an implementation detail, please describe the user visible behavior change. For example "```:meth:`smtplib.SMTP.send_message` no longer modifies the content of the *mail_options* argument.```" or something like.

Add also "Patch by Pablo S. Blum de Aguiar."

2018-08-06 09:52 UTC, methane commented on Lib/smtplib.py
> +                mail_options = (*mail_options, 'SMTPUTF8', 'BODY=8BITMIME')
I don't like this change.  `+=` seems more common/readable, and it's valid for immutable objects
like tuple and str.  (You need to change `[]` to `()` in this case)

```
>>> x = (1,2)
>>> x += (3,4)
>>> x
(1, 2, 3, 4)
```

2018-08-16 10:05 UTC, scorphus commented
Hey, I hope the 2 new commits I added *10 days ago* triggered a notification. I also hope this message isn't just additional noise – apologies if it is, I'm still new to contrubuting to CPython.

2018-08-16 10:34 UTC, serhiy-storchaka commented
Thank you for your reminder @scorphus. It is not a noise. This PR LGTM, but we need to get an approval from @bitdancer or @warsaw, the email module experts.

2018-08-20 08:24 UTC, serhiy-storchaka requested changes
Please update also the signature in `Doc/library/smtplib.rst`.

2018-08-20 11:17 UTC, scorphus commented
I have made the requested changes; please review again.

Regarding #5334 (and [issue32657](https://bugs.python.org/issue32657)) it proposes a change that was already discussed here and droped in favour of the current status of this very PR (#8554).

2018-08-20 11:25 UTC, serhiy-storchaka commented
If *rcpt_options* expected to be a sequence, not mapping, it is better to make a default value for options in `send_message()`, `sendmail()` and `rcpt()` an empty tuple than an empty list or dict.

2018-08-20 11:49 UTC, scorphus commented
Yeah, I thought so – and actually did exactly that in my initial change – but decided not to, as `rcpt_options` is not mutated anywhere – it's just `join`ed. Anyways, I agree it won't hurt :-)

2018-08-20 12:26 UTC, scorphus commented
Done, @serhiy-storchaka

How about `mail`'s default value for `options`?

2018-08-20 12:38 UTC, serhiy-storchaka commented
It won't hurt :-)

2018-08-20 13:13 UTC, scorphus commented
Cool! Thanks, @serhiy-storchaka.

2018-08-20 14:56 UTC, serhiy-storchaka approved these changes
LGTM! Thank you for your contribution Pablo!

2018-08-21 08:25 UTC, scorphus commented
YAY! Thanks for reviewing! I'm very happy to contribute!

2018-09-07 22:00 UTC, vstinner approved these changes
LGTM.

2018-09-07 22:04 UTC, merged

2018-09-07 22:04 UTC, miss-islington commented
Thanks @scorphus for the PR, and @pablogsal for merging it 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖

2018-09-07 22:04 UTC, miss-islington commented
Sorry, @scorphus and @pablogsal, I could not cleanly backport this to `3.6` due to a conflict. 
                            Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                            ```
                            cherry_picker d5fbe9b1a3d65ceeb9159c5ba999ee966a945f76 3.6
                            ```