bpo-34282: Fix Enum._convert
python/cpython pull request #8568
Opened 2018-07-30 17:40 UTC by orlnub123

https://bugs.python.org/issue34282

I've combined the third solution with the second from the issue above, circumventing its problem.

2018-07-30 17:43 UTC, orlnub123 commented
Is a news entry needed?

2018-08-31 06:39 UTC, orlnub123 commented
I've gone ahead and added a news entry.

2018-08-31 09:50 UTC, ethanfurman requested changes

2018-08-31 09:50 UTC, ethanfurman commented on Lib/enum.py
> +    def _convert(cls, name, module, filter, source=None):
See notes in bpo issue.  Thanks for your help in this!

2018-09-01 08:23 UTC, orlnub123 commented on Lib/enum.py
> +    def _convert(cls, name, module, filter, source=None):
Glad to help! I've got some questions about them in the issue.

2018-09-02 13:53 UTC, orlnub123 commented
I have made the requested changes; please review again.

2018-09-08 12:09 UTC, orlnub123 commented
I've merged the changes from #9034.

2018-09-10 16:29 UTC, ethanfurman requested changes
Looks good!  We just need one more test that verifies that usage of '_convert' in 3.8 raises a warning, and in 3.9+ raises an AttributeError.

Oh, and make sure you are in the contributors file.  :)

2018-09-12 16:11 UTC, orlnub123 commented
Thanks for the offer, I really appreciate it. I hope I've added myself to the right place!

I have made the requested changes; please review again.

2018-09-12 17:18 UTC, ethanfurman approved these changes

2018-09-12 17:28 UTC, merged