bpo-29913 fix documentation for compare_networks()
python/cpython pull request #865
Opened 2017-03-28 05:49 UTC by s-sanjay

updating the doc as discussed in issue 29913

2017-03-28 05:49 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-03-28 05:49 UTC, s-sanjay commented
@zhangyangyu I opened a new PR to fix the doc.

2017-03-28 05:56 UTC, zhangyangyu requested changes
We need to improve the documentation not docstring. You could edit Doc/library/ipaddress.rst. And deprecate means a `.. deprecated:: 3.7` command in the doc. You could refer to other files. :-)

2017-03-28 06:48 UTC, s-sanjay commented
@zhangyangyu ok 👍  I made the change in doc and dropped the change in documentation.

2017-03-28 07:19 UTC, zhangyangyu commented
You could add your name to Misc/NEWS. :-) And have you signed the CLA?

2017-03-28 07:19 UTC, zhangyangyu approved these changes

2017-03-28 07:59 UTC, s-sanjay commented
@zhangyangyu I did sign the CLA day before yesterday.

2017-03-28 10:18 UTC, zhangyangyu commented
It'll take some time for the CLA to take effect.
And sorry I made a mistake. I mean add your name to Misc/ACKS. This is a doc change and we don't need an entry in Misc/NEWS, sorry. :-(

2017-03-28 10:28 UTC, s-sanjay commented
@zhangyangyu yes I was wondering why it needs to go into NEWS. I updated the commit.

2017-03-30 07:44 UTC, merged

2017-03-30 07:44 UTC, zhangyangyu commented
Thanks @s-sanjay !

2017-03-31 09:04 UTC, s-sanjay commented
@zhangyangyu thank you !