bpo-34047: IDLE: fix mousewheel scrolling direction on macOS
python/cpython pull request #8678
Opened 2018-08-05 12:48 UTC by taleinat

Thanks to Vlad Tudorache for discovering the cause of the bug!

2018-08-06 02:11 UTC, terryjreedy requested changes
As explained on the issue, the correction exposed more bugs.  I am rewriting the function and will improve the doctest.

2018-08-06 02:55 UTC, terryjreedy approved these changes

2018-08-06 03:01 UTC, terryjreedy commented
Approved pending htest or equivalent passing on Mac by scrolling 'correctly' for Mac.

2018-08-10 06:01 UTC, taleinat commented
@terryjreedy, I tested this on my mac, both in IDLE proper and the htest, and all looks working as expected.

I specifically checked that scroll direction is consistent with the rest of the OS with system setting "Scroll direction: Natural" either on or off.

2018-08-10 06:02 UTC, merged

2018-08-10 06:02 UTC, miss-islington commented
Thanks @taleinat for the PR 🌮🎉.. I'm working now to backport this PR to: 3.6, 3.7.
🐍🍒⛏🤖