bpo-26515: Update C API docs to use PyModuleDef_Init()
python/cpython pull request #8682
Opened 2018-08-06 02:57 UTC by berkerpeksag

2018-08-22 13:20 UTC, ncoghlan reviewed
This looks like a nice improvement to me. There's a forward reference that I don't think is quite right any more, and one small syntactic tweak needed to fix the build.

2018-08-22 13:20 UTC, ncoghlan commented on Doc/extending/extending.rst
> +c:var:`Py_mod_exec` slot::
Missing the leading `:` here (that appears to be what the CI error is complaining about)

2018-08-22 13:20 UTC, ncoghlan commented on Doc/extending/extending.rst
> +We discuss the use of :c:macro:`PyMODINIT_FUNC` as a function return type later
With the modified example, this macro hasn't actually been referenced yet. Instead, the forward reference needs to explain that this list of slots will then be added to a `PyModuleDef` struct defining the module as a whole, which is described later.

2018-09-12 01:17 UTC, encukou requested changes
Sorry for getting to this so late -- I missed the review request notification.

2018-09-12 01:17 UTC, encukou commented on Doc/extending/extending.rst
>     static PyObject *SpamError;
This is a problem if the module is loaded more than once (for example, in multiple subinterpreters).
In that case, `spam_exec` would be executed multiple times, each time calling `PyErr_NewException` and setting `SpamError` to the newly created error object.

This pointer needs to be part of per-module state.

2019-01-10 16:05 UTC, vstinner commented
I removed the " needs backport to 3.6" label, the 3.6 branch no longer accept bugfixes (only security fixes are accepted): https://devguide.python.org/#status-of-python-branches

2019-02-19 14:16 UTC, csabella commented
@berkerpeksag It looks like this one was close to being merged.  When you have a chance, please review the changes requested by @ncoghlan and @encukou.  Thanks!

2019-09-10 16:42 UTC, JulienPalard commented
@berkerpeksag, ping

2019-09-11 03:53 UTC, berkerpeksag commented
I'll update my branch this weekend. Sorry for my late response!

2020-12-29 10:43 UTC, encukou commented
More detailed discussion/insructions is in PEP 630.

2021-01-06 01:22 UTC, berkerpeksag commented
@encukou so is this still needed or is PEP 630 the main reference point now?

2021-01-12 12:45 UTC, encukou commented
Because of PEP 630's open issues, making `PyModuleDef_Init` the default way to make classes would be leading some users into a trap. I am still not comfortable making it a default in the docs, and I'd rather have users read PEP 630 and understand the benefits and tradeoffs.
Until the open issues are solved, of course.

2021-01-12 12:50 UTC, berkerpeksag commented
Thank you. Closing this for now then.

2021-01-12 12:50 UTC, closed without merging