bpo-32367: Fix check for overflow when casting from a double to integ…
python/cpython pull request #8802
Opened 2018-08-17 23:45 UTC by enedil

…ral types

The added comment explains the issue. This fix disallows overflow: if a double `d` passes the test, it can mean that `d == 2**63`. When casted to `int64_t`, the variable overflows to -2**63.

2018-08-19 20:44 UTC, asottile commented
this appears linked to the wrong issue -- is this the right one? https://bugs.python.org/issue34423

2018-08-19 21:03 UTC, enedil commented
@asottile Yes, you're right. My branch is wrongly named too. Should I create new pull request?

2018-08-19 21:10 UTC, asottile commented
It might be enough to edit the commit message and title? I don't actually know

2018-08-20 22:05 UTC, vstinner reviewed
A test should be added to test_time.

2018-08-21 15:52 UTC, asottile commented on Lib/test/test_time.py
> +        + 1) / SEC_TO_NS)
unintentional change?

2019-02-04 10:56 UTC, jdemeyer requested changes
I don't think that the condition `sizeof(*v*) == sizeof(*type*)` is really the right condition. Besides, you are applying the fix (changing `<=` to `<`) unconditionally, also when the maximal value **can** be represented exactly.

The problem is that the maximal value `2^N - 1` is hard to work with. So I suggest to replace
```
v < _Py_IntegralTypeMax(type)
```
by something like
```
v < ldexp(_Py_IntegralTypeSigned(type) ? 0.5 : 1.0, CHAR_BIT * sizeof(type))
```

2019-02-13 17:19 UTC, vstinner commented
I'm not sure that we will be able to find a solution using a "simple" macro. Maybe we need new functions which takes a double as input and return an integer as output and report overflow. I'm not sure that it's possible to write a generic function.

Right now, _Py_InIntegralTypeRange() is only used to convert a double to _PyTime_t (int64_t) and time_t in pytime.c. Maybe 2 functions would be enough?

About generic code, we can maybe use the preprocessor as a template engine to generate these functions.

2019-02-13 20:38 UTC, jdemeyer commented
> Right now, _Py_InIntegralTypeRange() is only used to convert a double to _PyTime_t (int64_t) and time_t in pytime.c. Maybe 2 functions would be enough?

It would certainly be easier to support specific types only instead of being generic. We could for example assume that the number of bits in a `double` (53 assuming IEEE-754) is less than the number of bits in a `int64_t` (63).

2022-12-07 19:01 UTC, iritkatriel requested changes
This has merge conflicts, as well as several unresolved issues raised by reviewers.

2022-12-07 23:17 UTC, enedil commented
I'm fine with leaving this as unresolved.

2022-12-08 11:15 UTC, iritkatriel commented
> I'm fine with leaving this as unresolved.

Sure, thanks.

2022-12-08 11:15 UTC, closed without merging