bpo-34427: islice values when calling MutableSequence.extend on self
python/cpython pull request #8813
Opened 2018-08-19 02:03 UTC by KittenHero

2018-08-19 02:04 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-08-20 00:45 UTC, rhettinger requested changes
* We don't want to create another dependency.

* Instead, is it better to use plain Python with no external calls.

* Instead of an islice() approach, emulate what was done for list_extend() in Objects/listobject.c and for deque_extend() in Modules/_collectionsmodule.c.  When "values is self", create a copy first using "list(values)".

* The patch also needs tests and a news blurb.

2018-08-21 13:00 UTC, KittenHero commented
I made the requested changes I think

2018-08-30 16:55 UTC, rhettinger approved these changes

2018-08-30 16:56 UTC, merged