bpo-28415: Note 0 conversion different between Python and C
python/cpython pull request #885
Opened 2017-03-29 10:18 UTC by grapherd

2017-03-29 10:52 UTC, zhangyangyu requested changes
I think instead of a `.. note::`, it's better to follow the style of the table in https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting since we may find more exceptions in future. And I think the examples are not needed.

2017-03-29 13:19 UTC, serhiy-storchaka commented
Too much words for minor difference.

2017-03-29 13:51 UTC, grapherd commented
@zhangyangyu @serhiy-storchaka After reference the description from [cpp - printf](http://www.cplusplus.com/reference/cstdio/printf/), simplify the note about it.

2017-03-29 14:28 UTC, zhangyangyu commented
Actually I prefer the previous wording:
> the '0' conversion flag **IS NOT** ignored when a precision is given for 'd', 'i', 'o', 'u', 'x' and 'X' conversion types.
It's more direct to me and the current wording gives a feeling that the precision formatter won't take effects. :-(
And I am not sure this deserves a highlight.

2017-03-30 20:40 UTC, terryjreedy commented
See comment on https://bugs.python.org/issue28415 for minimal and terse alternatives.

2017-03-30 20:41 UTC, terryjreedy requested changes
See link to issue in comment

2017-04-05 04:50 UTC, rhettinger commented
Just adding the two notes will suffice.  I don't think readers are helped at all by changing "exactly" to "nearly" over such a minor distinction.  The word "nearly" creates an unnecessary sense of risk and uncertainty in the minds of readers.   Also, I think this is so unimportant that it shouldn't be backported.

2017-04-05 11:00 UTC, terryjreedy requested changes
The proposed addition is not proper English.  I give a different version on the issue.  I also think 'exactly' should just be removed when not exactly true, but will not push for that.

2017-04-21 23:25 UTC, vstinner requested changes

2017-04-21 23:25 UTC, haypo commented on Doc/c-api/bytes.rst
>     |                   |               | ``printf("%d")``.              |
Please add a reference to the note, like (1).

I would prefer to remove Nearly/Exactly. I don't think that the subtle difference is major enough to justify a "Nearly".

2017-04-21 23:25 UTC, haypo commented on Doc/c-api/unicode.rst
> +   | :attr:`%d`        | int                 | Nearly equivalent to           |
Ditto

2017-04-22 00:25 UTC, terryjreedy commented on Doc/c-api/bytes.rst
>     |                   |               | ``printf("%d")``.              |
So we agree dropping 'exactly' when not exactly true.

2017-04-26 06:17 UTC, lulouie commented
@terryjreedy, @haypo, could you help for review the latest addressed?
Thanks!

2017-04-27 02:08 UTC, terryjreedy approved these changes

2017-04-27 02:08 UTC, terryjreedy commented
Replacing the original 'Exactly' with a note marker looks good to me.  I cannot apply patch to test generated html for correct formatting, but assuming you have, I approve net result.

2017-04-27 02:21 UTC, lulouie commented
I put down the unicode footnote under the original note block

2017-04-27 03:36 UTC, merged

2017-04-27 03:39 UTC, zhangyangyu commented
Thanks @lulouie ! This style looks good and is actually what I want at first.