bpo-22872: multiprocessing.Queue's put() and get() now raise ValueError if the queue is closed
python/cpython pull request #9010
Opened 2018-08-30 20:50 UTC by ZackerySpytz

Previously, put() and get() would raise AssertionError and OSError,
respectively.

2018-09-10 05:47 UTC, auvipy reviewed
Looks good

2018-10-12 06:51 UTC, serhiy-storchaka requested changes

2018-10-12 06:51 UTC, serhiy-storchaka commented on Lib/test/_test_multiprocessing.py
> +            for meth, args in (q.put, ('foo',)), (q.get, ()):
It would look clearer (and just one line longer) if unroll this loop.

2018-10-13 04:47 UTC, serhiy-storchaka commented on Misc/NEWS.d/next/Library/2018-08-30-14-44-11.bpo-22872.NhIaZ9.rst
> +instead of :exc:`AssertionError` and :exc:`OSError`, respectively.
Do you mind to add "Patch by *yourname*."?

2018-10-13 09:26 UTC, merged