Simplified implementation of _sre.ascii_iscased().
python/cpython pull request #9097
Opened 2018-09-07 10:47 UTC by sir-sigurd

2018-09-10 08:55 UTC, zhangyangyu approved these changes

2018-09-10 11:31 UTC, serhiy-storchaka commented on Modules/_sre.c
> +    return ch <= 'z' && Py_ISALPHA(ch);
I would use `127` instead of `'z'`.

2018-09-10 17:33 UTC, benjaminp requested changes
Agreed that `< 128` would be better.

2018-09-12 10:20 UTC, serhiy-storchaka commented
Performance is not critical here, but readability matters. It took a while for me to figure out why this code is written in such way and to ensure that it is correct. It can be looking more cryptic for other readers. The meaning of `< 128` is more clear: it is for ASCII only.

2018-09-12 11:11 UTC, sir-sigurd commented
I have made the requested changes; please review again.

2018-09-12 12:47 UTC, serhiy-storchaka approved these changes

2018-09-12 12:49 UTC, merged