Remove bugs.python.org from bugs.rst
python/cpython pull request #91425
Opened 2022-04-10 21:12 UTC by royreznik

fix #91423

2022-04-10 21:18 UTC, eamanu commented on Doc/bugs.rst
>  Bug reports for Python itself should be submitted via the Python Bug Tracker
I would update  the 'Python Bug Tracker' part.

2022-04-10 21:43 UTC, eamanu approved these changes

2022-04-11 02:45 UTC, methane commented on Doc/bugs.rst
> +"Versions" to which the issue relates.
We don't have fields yet...

2022-04-11 04:39 UTC, hugovk commented on Doc/bugs.rst
> +Issue reports for Python itself should be submitted via the Github issues tracker
Here and elsewhere, GitHub has a capital H:
```suggestion
Issue reports for Python itself should be submitted via the GitHub issues tracker
```

2022-04-11 04:53 UTC, hugovk commented on Doc/bugs.rst
> +(https://github.com/python/cpython/issues).  Github issues tracker offers a web form which allows
```suggestion
(https://github.com/python/cpython/issues).  The GitHub issue tracker offers a web form which allows
```

2022-04-11 04:53 UTC, hugovk commented on Doc/bugs.rst
> +To do this, search the issue using the search box on the top of the page.
```suggestion
To do this, search the tracker using the search box at the top of the page.
```

2022-04-11 04:53 UTC, hugovk commented on Doc/bugs.rst
>  developers time, is that you learn what has been done to fix it; it may be that
```suggestion
developers' time, is that you learn what has been done to fix it; it may be that
```

2022-04-11 04:53 UTC, hugovk commented on Doc/bugs.rst
> +If the problem you're reporting is not already in the issues, go back to
```suggestion
If the problem you're reporting is not already in the list, log in to GitHub.
```

2022-04-11 04:53 UTC, hugovk commented on Doc/bugs.rst
> +the issues tracker and log in.  If you don't already have a Github account,
```suggestion
If you don't already have a GitHub account,
```

2022-04-11 04:53 UTC, hugovk commented on Doc/bugs.rst
> +Each issue report will be assigned to a developer who will determine what needs to
I don't think new issues are auto-assigned to anyone?

2022-04-11 08:05 UTC, m-aciek commented on Doc/bugs.rst
> -"Versions" to which the bug relates.
Shouldn't we encourage to enter the information about type, component and versions affected "inline" in the comment section?

2022-04-11 08:20 UTC, methane commented on Doc/bugs.rst
> -"Versions" to which the bug relates.
It will be discussed later.
This PR is just a quickfix.

2022-04-11 08:22 UTC, methane approved these changes
LGTM.
But please wait for another review from who is good at English.

2022-04-11 14:25 UTC, ezio-melotti requested changes

2022-04-11 14:25 UTC, ezio-melotti commented on Doc/bugs.rst
> +If you don't already have a GitHub account, create new account using the
```suggestion
If you don't already have a GitHub account, create a new account using the
```

2022-04-11 14:25 UTC, ezio-melotti commented on Doc/bugs.rst
> +Select the "New issue" link in the top bar to open the issue reporting form.
```suggestion
Click on the "New issue" button in the top bar to report a new issue.
```

2022-04-11 14:32 UTC, ezio-melotti approved these changes

2022-04-11 15:10 UTC, merged

2022-04-11 15:12 UTC, ezio-melotti commented
Thanks for the PR!

2022-04-11 18:16 UTC, miss-islington commented
Thanks @royreznik for the PR, and @ezio-melotti for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖

2022-04-11 18:16 UTC, miss-islington commented
Thanks @royreznik for the PR, and @ezio-melotti for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖

2022-04-11 18:17 UTC, miss-islington commented
Sorry, @royreznik and @ezio-melotti, I could not cleanly backport this to `3.9` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker df81d2892eed3a256eb61ce59304f2173fb0c945 3.9
                                ```

2022-04-11 18:17 UTC, miss-islington commented
Sorry @royreznik and @ezio-melotti, I had trouble checking out the `3.10` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker df81d2892eed3a256eb61ce59304f2173fb0c945 3.10
                                ```