gh-91539: improve performance of get_proxies_environment
python/cpython pull request #91566
Opened 2022-04-15 11:27 UTC by eendebakpt

Improve performance of `get_proxies_environment` when there are many environment variables

2022-05-17 15:49 UTC, carljm commented on Lib/urllib/request.py
> +            proxies[name_lower[:-6]] = value
There probably won't be lots of env vars with underscore sixth-from-last, so it likely won't make a big difference, but I think there's really no need for three separate loops here. We can get the same benefits with a single loop and just better ordering of checks/operations. Also, every use of the lowered name wants to strip off final "_proxy", so we can do that early.
```suggestion
    proxies = {}
    environment = []
    for name in os.environ.keys():
        # fast screen underscore position before more expensive case-folding
        if len(name) > 5 and name[-6] == "_" and name[-5:].lower() == "proxy":
            value = os.environ[name]
            proxy_name = name[:-6].lower()
            environment.append((name, value, proxy_name))
            if value:
                proxies[proxy_name] = value
```

2022-05-17 15:49 UTC, carljm commented on Lib/urllib/request.py
> +    for name, value, name_lower in environment:
```suggestion
    for name, value, proxy_name in environment:
```

2022-05-17 15:49 UTC, carljm commented on Lib/urllib/request.py
> +                proxies[name_lower[:-6]] = value
```suggestion
                proxies[proxy_name] = value
```

2022-05-17 15:49 UTC, carljm commented on Lib/urllib/request.py
> +                proxies.pop(name_lower[:-6], None)
```suggestion
                proxies.pop(proxy_name, None)
```

2022-05-18 16:07 UTC, carljm requested changes
Sorry I missed this in first review, but the name of the function has a typo (extra underscore) in the NEWS entry.

Also suggested an added comment. (Wouldn't have bothered with this if it was the only thing, but may be worth it if you are doing one more update to fix NEWS anyway.)

Thanks for the improvements to this function!

2022-05-18 16:07 UTC, carljm commented on Misc/NEWS.d/next/Library/2022-04-15-11-29-38.gh-issue-91539.7WgVuA.rst
> +Improve performance of ``urllib.request.get_proxies_environment`` when there are many environment variables
```suggestion
Improve performance of ``urllib.request.getproxies_environment`` when there are many environment variables
```

2022-05-18 16:07 UTC, carljm commented on Lib/urllib/request.py
>          if name[-6:] == '_proxy':
Every time I read this code again I find myself thinking this check is redundant, and then I remember that it is not redundant because this is not case-folded. May be worth a comment?
```suggestion
        # not case-folded, checking here for lower-case env vars only
        if name[-6:] == '_proxy':
```

2022-05-18 16:50 UTC, eendebakpt commented on Lib/urllib/request.py
>          if name[-6:] == '_proxy':
I think a comment is good. At least people will know the second loop is there for a reason and people tried to remove it before 😀

2022-05-18 22:37 UTC, carljm approved these changes

2022-08-10 20:49 UTC, eendebakpt commented
@ambv As the latest core dev touching `Lib/urllib/request.py`, would you be able to review this PR?

2022-10-05 17:57 UTC, orsenthil approved these changes
LGTM

2022-10-05 17:57 UTC, merged

2022-10-05 17:57 UTC, miss-islington commented
Thanks @eendebakpt for the PR, and @orsenthil for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖