[3.9] gh-91118: Fix docstrings that do not honor --without-doc-strings (GH-31769)
python/cpython pull request #91664
Opened 2022-04-18 13:15 UTC by arhadthedev

Co-authored-by: Éric [merwok@netwok.org](mailto:merwok@netwok.org)
Co-authored-by: Jelle Zijlstra [jelle.zijlstra@gmail.com](mailto:jelle.zijlstra@gmail.com)
(cherry picked from commit https://github.com/python/cpython/commit/a573cb2fec664c645ab744658d7e941d72e1a398)

Co-authored-by: Oleg Iarygin [oleg@arhadthedev.net](mailto:oleg@arhadthedev.net)

2022-04-18 20:43 UTC, JelleZijlstra requested changes

2022-04-18 20:43 UTC, JelleZijlstra commented on Objects/unionobject.c
> +// types.UnionType -- used to represent e.g. Union[int, str], int | str
Looks like you accidentally added this file

2022-04-19 05:18 UTC, arhadthedev commented
I have made the requested changes; please review again.

2022-04-19 19:58 UTC, JelleZijlstra approved these changes

2022-04-19 19:58 UTC, merged

2022-04-19 19:59 UTC, JelleZijlstra commented
Thank you!