Added @requires_zlib to test_freeze_simple_script.(GH-91752)
python/cpython pull request #91758
Opened 2022-04-20 17:51 UTC by AbhigyanBose

```
gh-91752: Added @requires_zlib to test_freeze_simple_script
```

Added @requires_zlib to class TestFreeze, resulting in the test, test_freeze_simple_script being skipped when zlib is not present.

2022-04-22 14:27 UTC, tiran requested changes
Please move the blurb from ``Library`` to ``Tests`` category.

2022-04-22 14:32 UTC, tiran reviewed
You don't have to import the function, just it from support module directly.

2022-04-22 14:32 UTC, tiran commented on Lib/test/test_tools/test_freeze.py
> +@requires_zlib()
```suggestion
@support.requires_zlib()
```

2022-04-22 14:32 UTC, tiran commented on Lib/test/test_tools/test_freeze.py
> +from test.support import requires_zlib
```suggestion
```

2022-04-22 14:51 UTC, tiran approved these changes
LGTM, thanks for the quick fix!

2022-04-24 04:12 UTC, AbhigyanBose commented
@tiran 

Is there anything else I need to do here ?
Or should I just wait for someone to merge this ?

2022-05-03 17:19 UTC, gvanrossum approved these changes
Looks like this simply fell between the cracks. Since @tiran approved it I am just going to merge it for you.

2022-05-03 17:19 UTC, merged

2022-05-03 18:19 UTC, gvanrossum commented
Let's try 3.10, 3.9.

2022-05-03 18:20 UTC, miss-islington commented
Thanks @AbhigyanBose for the PR, and @gvanrossum for merging it 🌮🎉.. I'm working now to backport this PR to: 3.9.
🐍🍒⛏🤖

2022-05-03 18:20 UTC, miss-islington commented
Thanks @AbhigyanBose for the PR, and @gvanrossum for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10.
🐍🍒⛏🤖

2022-05-03 18:20 UTC, miss-islington commented
Sorry, @AbhigyanBose and @gvanrossum, I could not cleanly backport this to `3.9` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 77e7a04cd235f1bcd6fc69bcb15e2683c365d637 3.9
                                ```

2022-05-03 18:20 UTC, miss-islington commented
Sorry @AbhigyanBose and @gvanrossum, I had trouble checking out the `3.10` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 77e7a04cd235f1bcd6fc69bcb15e2683c365d637 3.10
                                ```

2022-05-03 18:21 UTC, gvanrossum commented
I don't care enough about the backports, I'll remove the labels. @AbhigyanBose If you want to see if manually backporting makes sense, go ahead, but don't spend much time on it (the likely cause of the failure is that the code doesn't exist in that form in 3.10 or 3.9). Start with 3.10 first, if any.

2022-05-03 18:29 UTC, AbhigyanBose commented
I'm testing if backport's needed right now. But this issue seems to occur only for fresh installs of the OS (some dependency for a different application resolved the missing module issue on my daily os, currently testing with Docker containers)

2022-05-03 18:44 UTC, AbhigyanBose commented
Checked both 3.10 and 3.9, no backports required.