Improving readability of argparse.rst
python/cpython pull request #91751
Opened 2022-04-20 15:34 UTC by xandrade

Fixed few typos and enhanced few paragraphs for your review and consideration.
Trivial contribution towards continuous improvement, so no issue was raised.

2022-04-20 19:23 UTC, Mariatta requested changes
Some of the changes here make sense, but the rest, I don't think the change adds any more value, so I'd like to keep them.

I've identified the ones which I'd like you to revert.

2022-04-20 19:23 UTC, Mariatta commented on Doc/library/argparse.rst
> -If invalid arguments are passed in, it will issue an error:
I would keep this unchanged.

2022-04-20 19:23 UTC, Mariatta commented on Doc/library/argparse.rst
> -be run at the command line and provides useful help messages:
I would keep the original text on both lines here.

2022-04-20 19:23 UTC, Mariatta commented on Doc/library/argparse.rst
> +"issues errors" when users provide invalid arguments to the program.
Please keep the original text on this pargraph.

2022-04-30 22:05 UTC, rhettinger approved these changes

2022-04-30 22:20 UTC, miss-islington commented
@xandrade: Status check is done, and it's a success ✅ .

2022-04-30 22:20 UTC, merged