gh-91768: C API no longer use "const PyObject*" type
python/cpython pull request #91769
Opened 2022-04-20 23:51 UTC by vstinner

Py_REFCNT(), Py_TYPE(), Py_SIZE() and Py_IS_TYPE() functions argument
type is now "PyObject*", rather than "const PyObject*".

* Replace also "const PyObject*" with "PyObject*" in functions:

  * _Py_strhex_impl()
  * _Py_strhex_with_sep()
  * _Py_strhex_bytes_with_sep()

* Remove _PyObject_CAST_CONST() and _PyVarObject_CAST_CONST() macros
* Py_IS_TYPE() can now use Py_TYPE() in its implementation

2022-04-20 23:54 UTC, vstinner commented
This change is backward compatible since modified macros cast their argument to ``PyObject*``.

2022-04-21 01:12 UTC, vstinner commented
cc @erlend-aasland

2022-04-21 07:37 UTC, erlend-aasland requested changes
You also need to update the documentation.

2022-04-21 14:39 UTC, vstinner commented
> You also need to update the documentation.

Done.

2022-04-21 20:07 UTC, merged