bpo-34663: Add support for POSIX_SPAWN_USEVFORK in posix_spawn when available
python/cpython pull request #9271
Opened 2018-09-13 18:15 UTC by pablogsal

2018-09-13 19:08 UTC, vstinner requested changes

2018-09-13 19:08 UTC, vstinner commented on Modules/posixmodule.c
> +                "The UseVFork option is not supported in this system.");
The parameter is called "usevfork", the error message should use the same name (not "UseVFork").

2018-09-13 19:08 UTC, vstinner commented on Modules/posixmodule.c
> +    usevfork: bool(accept={int}) = False
I suggest the name "use_vfork", or maybe even "vfork".

2018-09-13 19:19 UTC, pablogsal commented
I have made the requested changes; please review again

2018-09-13 20:41 UTC, vstinner commented on Modules/posixmodule.c
> +        PyErr_SetString(PyExc_NotImplementedError,
You can use argument_unavailable_error() here.

2018-09-13 20:41 UTC, vstinner commented on Modules/posixmodule.c
> +        If the value is `True` the POSIX_SPAWN_USEVFORK will be activated.
"If the value is true": use_vfork=1 should be equivalent to use_vfork=True.

2018-09-13 20:41 UTC, vstinner commented on Lib/test/test_posix.py
> +            pid = posix.posix_spawn(
You might use args = self.python_args() and  posix.posix_spawn(args[0], args, ...)

2018-09-13 20:43 UTC, vstinner commented
Please also document the use_vfork parameter in Doc/library/os.html

2018-09-13 21:12 UTC, vstinner requested changes

2018-09-13 21:12 UTC, vstinner commented on Doc/library/os.rst
> +
Oh, "Availability: ..." is missing: this function is not available on Windows, right?

I would suggest to document in "Availability: ..." that the flag is only available on Linux.

2018-09-13 21:12 UTC, vstinner commented on Doc/library/os.rst
> +  GNU specific flag :c:data:`POSIX_SPAWN_USEVFORK`.
You should document that the function raises an exception if the flag is unavailable on the platform.

2018-09-13 21:12 UTC, vstinner commented on Lib/test/test_posix.py
> +            unittest.SkipTest("POSIX_SPAWN_USEVFORK not available on this system")
Hum, you can just reuse the exception message as part of this error message.

2018-09-13 21:12 UTC, vstinner commented on Misc/NEWS.d/next/Core and Builtins/2018-09-13-11-14-38.bpo-34663.BtJz-5.rst
> +Added support for `usevfork` parameters of `posix_spawn`, which allows to
use_vfork with underscore, no?

`posix_spawn` can be written :func:`os.posix_spawn` to get a link to the function in the generated doc.

2018-09-14 21:03 UTC, vstinner commented on Doc/library/os.rst
> +   Availability: Using *use_vfork* is only available on Linux.
You should document that the function is only available on Unix. Example:
https://docs.python.org/dev/library/os.html#os.fork

2018-09-14 21:03 UTC, vstinner commented on Lib/test/test_posix.py
> +        except NotImplementedError as e:
nitpick: i prefer to avoid single character variable, i suggest the name "exc".

2018-09-14 21:03 UTC, vstinner commented on Lib/test/test_posix.py
> +            raise unittest.SkipTest(e)
You can use: raise self.skipTest(str(exc)).

2018-09-14 21:03 UTC, vstinner commented on Modules/posixmodule.c
> +        PyErr_SetString(PyExc_NotImplementedError,
I discussed with Pablo and using "posix_spawn()" function name is less useless than mentioning the "POSIX_SPAWN_USEVFORK flag".

2018-09-14 21:54 UTC, vstinner approved these changes
LGTM.

@gpshead: Would you mind to double check this PR?

@benjaminp: Would you be interested to have a look as well? (the plan is then to experiment to use it in subprocess for performance.)

2018-09-20 10:49 UTC, closed without merging