gh-92932: dis._unpack_opargs should handle EXTENDED_ARG_QUICK
python/cpython pull request #92945
Opened 2022-05-19 08:46 UTC by corona10

2022-05-19 09:01 UTC, Fidget-Spinner commented
Sorry Dong-hee, I'm useless at `dis`. Can't help you review this here :).

2022-05-19 09:06 UTC, corona10 commented
`````diff

230261,230262c230261,230262
<            1118398 EXTENDED_ARG_QUICK       1
<            1118400 LOAD_GLOBAL            248 (g125)
---
>            1118398 EXTENDED_ARG_QUICK     513
>            1118400 LOAD_GLOBAL          131576 (g65789)
230265,230266c230265,230266
<            1118416 EXTENDED_ARG_QUICK       1
<            1118418 LOAD_GLOBAL            250 (g126)
---
>            1118416 EXTENDED_ARG_QUICK     513
>            1118418 LOAD_GLOBAL          131578 (g65790)
230269,230270c230269,230270
<            1118434 EXTENDED_ARG_QUICK       1
<            1118436 LOAD_GLOBAL            252 (g127)
---
>            1118434 EXTENDED_ARG_QUICK     513
>            1118436 LOAD_GLOBAL          131580 (g65791)
230273,230274c230273,230274
<            1118452 EXTENDED_ARG_QUICK       1
<            1118454 LOAD_GLOBAL            254 (g128)
---
>            1118452 EXTENDED_ARG_QUICK     513
>            1118454 LOAD_GLOBAL          131582 (g65792)
230277,230278c230277,230278
<            1118470 EXTENDED_ARG_QUICK       2
<            1118472 LOAD_GLOBAL              0 (g1)
---
>            1118470 EXTENDED_ARG_QUICK     514
>            1118472 LOAD_GLOBAL          131584 (g65793)
230281,230282c230281,230282
<            1118488 EXTENDED_ARG_QUICK       2
<            1118490 LOAD_GLOBAL              2 (g2)
---
>            1118488 EXTENDED_ARG_QUICK     514
>            1118490 LOAD_GLOBAL          131586 (g65794)
`````

2022-05-19 16:57 UTC, brandtbucher requested changes
Thanks for the fix!

This should also have a test in `test_dis`. As a simple example, the statement `*_, _ = ...` should always generate an instruction `UNPACK_EX(256)` (proving that `EXTENDED_ARG` works correctly).

2022-05-19 16:57 UTC, brandtbucher commented on Lib/dis.py
> +            extended_arg = (arg << 8) if EXTENDED_ARG in (op, deop) else 0
```suggestion
            extended_arg = (arg << 8) if deop == EXTENDED_ARG else 0
```

2022-05-20 09:19 UTC, corona10 commented
I have made the requested changes; please review again

2022-05-23 17:35 UTC, corona10 commented
@brandtbucher gentle ping :)

2022-06-02 20:04 UTC, brandtbucher approved these changes
Looks good! I found a couple of spelling nits, but feel free to merge otherwise:

2022-06-02 20:04 UTC, brandtbucher commented on Lib/test/test_dis.py
> +    def test_extenaded_arg_quick(self):
```suggestion
    def test_extended_arg_quick(self):
```

2022-06-02 20:04 UTC, brandtbucher commented on Lib/test/test_dis.py
> +      extend_arg_quick.__code__.co_firstlineno + 1,)
```suggestion
def extended_arg_quick():
    *_, _ = ...

dis_extended_arg_quick_code = """\
%3d           0 RESUME                   0

%3d           2 LOAD_CONST               1 (Ellipsis)
              4 EXTENDED_ARG_QUICK       1
              6 UNPACK_EX              256
              8 STORE_FAST               0 (_)
             10 STORE_FAST               0 (_)
             12 LOAD_CONST               0 (None)
             14 RETURN_VALUE
"""% (extended_arg_quick.__code__.co_firstlineno,
      extended_arg_quick.__code__.co_firstlineno + 1,)
```

2022-06-02 20:04 UTC, brandtbucher commented on Lib/test/test_dis.py
> +        got = self.get_disassembly(extend_arg_quick)
```suggestion
        got = self.get_disassembly(extended_arg_quick)
```

2022-06-03 02:29 UTC, merged

2022-06-03 02:29 UTC, miss-islington commented
Thanks @corona10 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2022-06-03 02:29 UTC, corona10 commented
Thank you Brandt for review!