gh-92898: Make _Py_Cast C++ version compatible with cast operator
python/cpython pull request #92951
Opened 2022-05-19 10:00 UTC by serge-sans-paille

Use the adequate kind of cast based on the macro argument: const ref, cont
pointer, ref or pointer.

This should be compatible with C++ overloads.

Fix #92898

2022-05-19 10:06 UTC, serge-sans-paille commented
cc @vstinner

2022-05-19 13:25 UTC, corona10 requested changes
Would you like to add NEWS.d about compatible?

2022-05-19 13:26 UTC, corona10 commented on Lib/test/_testcppext.cpp
> +
```suggestion
```

2022-05-19 14:57 UTC, serge-sans-paille commented
@corona10 I'm not sure, there's already an entry

```
.. date: 2022-04-26-16-51-31
.. gh-issue: 91320
.. nonce: QDHmTv
.. section: C API

Fix C++ compiler warnings about "old-style cast" (``g++ -Wold-style-cast``)
in the Python C API. Use C++ ``reinterpret_cast<>`` and ``static_cast<>``
casts when the Python C API is used in C++. Patch by Victor Stinner.
```

And this is just patching that  entry

2022-05-19 15:51 UTC, tacaswell commented
I am now seeing errors compiling numpy with this branch:

```
      In file included from /home/tcaswell/.pybuild/bleeding/include/python3.12/Python.h:38,
                       from numpy/core/include/numpy/npy_common.h:5,
                       from numpy/core/include/numpy/npy_math.h:8,
                       from numpy/core/src/npysort/selection.cpp:18:
      /home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:31:1: error: template with C linkage
         31 | template <typename type, typename expr_type>
            | ^~~~~~~~
      numpy/core/include/numpy/npy_math.h:5:1: note: ‘extern "C"’ linkage started here
          5 | extern "C" {
            | ^~~~~~~~~~
      /home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:36:1: error: template with C linkage
         36 | template <typename type, typename expr_type>
            | ^~~~~~~~
      numpy/core/include/numpy/npy_math.h:5:1: note: ‘extern "C"’ linkage started here
          5 | extern "C" {
            | ^~~~~~~~~~
      /home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:41:1: error: template with C linkage
         41 | template <typename type, typename expr_type>
            | ^~~~~~~~
      numpy/core/include/numpy/npy_math.h:5:1: note: ‘extern "C"’ linkage started here
          5 | extern "C" {
            | ^~~~~~~~~~
      /home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:46:1: error: template with C linkage
         46 | template <typename type, typename expr_type>
            | ^~~~~~~~
      numpy/core/include/numpy/npy_math.h:5:1: note: ‘extern "C"’ linkage started here
          5 | extern "C" {
            | ^~~~~~~~~~

```

```
g++ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -I/usr/local/include -I/home/tcaswell/.virtualenvs/bleeding/include -Ibuild/src.linux-x86_64-3.12/numpy/core/src/multiarray -Ibuild/src.linux-x86_64-3.12/numpy/core/src/common -Ibuild/src.linux-x86_64-3.12/numpy/core/src/umath -Inumpy/core/include -Ibuild/src.linux-x86_64-3.12/numpy/core/include/numpy -Ibuild/src.linux-x86_64-3.12/numpy/distutils/include -Ibuild/src.linux-x86_64-3.12/numpy/core/src/npysort -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/home/tcaswell/.virtualenvs/bleeding/include -I/home/tcaswell/.pybuild/bleeding/include/python3.12 -Ibuild/src.linux-x86_64-3.12/numpy/core/src/common -Ibuild/src.linux-x86_64-3.12/numpy/core/src/npymath -c numpy/core/src/npysort/selection.cpp -o build/temp.linux-x86_64-3.12/numpy/core/src/npysort/selection.o -MMD -MF build/temp.linux-x86_64-3.12/numpy/core/src/npysort/selection.o.d -msse -msse2 -msse3 -std=c++11 -D__STDC_VERSION__=0 -fno-exceptions -fno-rtti
```

2022-05-19 16:41 UTC, serge-sans-paille commented
@tacaswell indeed. I can work around this :-)

2022-05-19 18:24 UTC, tacaswell commented
@serge-sans-paille I should note this is with numpy main, I have not gone back to see if released versions work or not.

2022-05-19 18:28 UTC, serge-sans-paille commented
@tacaswell should be good now?

2022-05-19 18:43 UTC, tacaswell commented
Through numpy, starting scipy.  Will update if the whole environment builds cleanly (including greenlet main).

2022-05-19 21:28 UTC, tacaswell commented
It built clean including master-branch greenlet 👍🏻

2022-05-21 13:15 UTC, corona10 approved these changes

2022-05-21 13:16 UTC, merged

2022-05-21 13:16 UTC, miss-islington commented
Thanks @serge-sans-paille for the PR, and @corona10 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2022-05-21 13:16 UTC, miss-islington commented
Sorry @serge-sans-paille and @corona10, I had trouble checking out the `3.11` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 5b71b519f966e1017c868ea2b27c61a5eac38c1f 3.11
                                ```

2022-05-23 13:23 UTC, vstinner commented
I created a follow-up PR: https://github.com/python/cpython/pull/93111

2022-12-24 20:15 UTC, miss-islington commented
Thanks @serge-sans-paille for the PR, and @corona10 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2022-12-24 20:15 UTC, miss-islington commented
Sorry, @serge-sans-paille and @corona10, I could not cleanly backport this to `3.11` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 5b71b519f966e1017c868ea2b27c61a5eac38c1f 3.11
                                ```