gh-93018: Fix for the compatibility problems with expat started in 2.4.4, not just 2.4.5
python/cpython pull request #93022
Opened 2022-05-20 15:51 UTC by mcepl

Adjust compatibility fixed for libexpat.

Fixes #93018.

2022-06-01 13:49 UTC, hartwork requested changes
Hi @mcepl, I'm working on libexpat upstream. From a quick look, my impression is that this PR is not about "vanilla" libexpat from upstream but about some distro backport with security fixes backported from after 2.4.4. If it indeed is about a backport, then the distro with the backport needs these fixes downstream, not CPython upstream. For the libexpat change log of 2.4.4, please see https://github.com/libexpat/libexpat/blob/f4501351122606348065d58f62ac06cb7e68a910/expat/Changes#L129-L151 . ~We may needed changes in CPython tests for the changes in libexpat 2.4.7 though, will need a closer look, and different version guards.~ What do you think, am I missing something? Best, Sebastian

2022-06-02 00:00 UTC, mcepl commented
Hmm, just patches for:

 * CVE-2022-25235
 * CVE-2022-25236-relax-fix
 * CVE-2022-25236
 * CVE-2022-25313-fix-regression
 * CVE-2022-25313
 * CVE-2022-25314
 * CVE-2022-25315

2022-06-02 20:08 UTC, hartwork requested changes
> Hmm, just patches for:

@mcepl thanks for sharing. That list includes all of the changes introduced in 2.4.5 and more. As-is the changes in this pull request would break the test suite for vanilla libexpat 2.4.4. Any ideas how to not produce that new problem?

2022-06-02 22:48 UTC, mcepl commented
Hmm, you are probably right. This is a local change caused by our abundance of patches. Sorry for bothering you.

2022-06-03 05:07 UTC, corona10 commented
closing the issue: https://github.com/python/cpython/pull/93022#issuecomment-1145415371

2022-06-03 05:07 UTC, closed without merging