[3.10] gh-93108: Bump sphinx to fix rendering issue.
python/cpython pull request #93159
Opened 2022-05-24 07:54 UTC by JulienPalard

Bug was visible on [SysLogHandler](https://docs.python.org/3.10/library/logging.handlers.html#sysloghandler) in Python 3.10 only (3.9 uses an older Sphinx version without the issue, 3.11 uses a newer Sphinx version without the issue).

bad: `SysLogHandler(address='localhost', SYSLOG_UDP_PORT, ...`
good: `SysLogHandler(address=('localhost', SYSLOG_UDP_PORT), ...`

So this commit only lives on 3.10, hope that's ok! @pablogsal what do you think?

2022-05-24 09:24 UTC, DanielNoord requested changes
The comments in this file also mention `3.2.1` and should probably be updated.

The 3.9 branch also refers to the actual pinned version of `Sphinx` in its comments, see https://github.com/python/cpython/blob/3.9/Doc/requirements.txt.

2022-05-24 10:12 UTC, JulienPalard commented
@DanielNoord you're right, I updated the surrouding comments.

2022-05-24 10:12 UTC, DanielNoord approved these changes

2022-05-27 21:40 UTC, AA-Turner approved these changes

2022-06-06 16:59 UTC, merged