gh-84508: tool to generate cjk traditional chinese mappings
python/cpython pull request #93272
Opened 2022-05-26 20:37 UTC by sorcio

This adds a script to generate the mapping files for Traditional Chinese Big-5-based codecs, as discussed in the issue.

I initially planned to add support for later versions of HKSCS, but I decided to keep this minimal so to close gh-84508. The topic of refreshing the mappings is split to its own issue in gh-93271.

So this generates `mappings_tw.h` and `mappings_hk.h` files identical to the existing versions (with only one new line difference).

Notes about the mapping files:

- I did not include the BIG5.TXT and CP950.TXT files that are available on the Unicode website. It looks like these are [available for redistribution](https://www.unicode.org/license.txt), so I can add them to the PR if needed.
- I also did not include the hkscs-2004-big5-iso.txt file, but that's a different story. The [terms of use](https://www.ccli.gov.hk/en/archive/terms_hkscs-2004-big5-iso.html) from the source website include a clause that unilaterally binds to any update to the terms (clause 2), which I believe is incompatible with redistribution as part of CPython.

2022-05-28 02:55 UTC, corona10 requested changes
Super cool, thanks for your contribution.
This issue was painful to me because we can not re-generate mapping files without this tool.

I left a small suggestion for this.

2022-05-28 02:55 UTC, corona10 commented on Tools/unicode/genmap_tchinese.py
> +        writer = DecodeMapWriter(fp, 'big5hkscs', hkscsdecmap)
```suggestion
        print_autogen(fp, os.path.basename(__file__))
        writer = DecodeMapWriter(fp, 'big5hkscs', hkscsdecmap)
```

2022-05-28 02:55 UTC, corona10 commented on Tools/unicode/genmap_tchinese.py
> +)
```suggestion
import os

from genmap_support import *
```

2022-05-28 02:55 UTC, corona10 commented on Tools/unicode/genmap_tchinese.py
> +        write_big5_maps(fp, 'BIG5', 'big5', big5decmap, big5encmap)
```suggestion
        print_autogen(fp, os.path.basename(__file__))
        write_big5_maps(fp, 'BIG5', 'big5', big5decmap, big5encmap)
```

2022-05-28 02:56 UTC, corona10 reviewed
> I did not include the BIG5.TXT and CP950.TXT files that are available on the Unicode website. It looks like these are [available for redistribution](https://www.unicode.org/license.txt), so I can add them to the PR if needed.

Please addig it.

2022-05-28 10:12 UTC, ezio-melotti reviewed
The two files are somewhat big -- @corona10 do you think it's ok to include them in the repo?
If they are added the size of the repo will increase, making downloading/cloning it slower.  I'm not sure if it might affect other things too.

2022-05-28 10:12 UTC, ezio-melotti commented on Tools/unicode/genmap_tchinese.py
> +# Original Author:  Hye-Shik Chang <perky@FreeBSD.org>
FWIW @hyeshik doesn't seem to be active on this repo, but he signed the CLA in 2005 (https://bugs.python.org/user1298), so it should be ok to include it here.

If this script is based on his script, you might want to clarify that in the comment.

2022-05-28 10:24 UTC, sorcio commented on Tools/unicode/genmap_tchinese.py
> +# Original Author:  Hye-Shik Chang <perky@FreeBSD.org>
@ezio-melotti do you have a suggestion on how to amend the comment to clarify that? The mention of "Original Author" is what it currently looks like in the other genmap_* scripts, so I didn't take the liberty to sway from that style.

The original source (as for the other equivalent scripts) is https://github.com/BackupTheBerlios/cjkpython/blob/master/cjkcodecs/tools/genmap_tchinese.py which was originally under 2-clause BSD. I might have made a wrong assumption that it was ok to include in CPython, since the other scripts followed the same process?

2022-05-28 10:28 UTC, sorcio commented on Tools/unicode/genmap_tchinese.py
> +# Original Author:  Hye-Shik Chang <perky@FreeBSD.org>
(In case it matters, the script in this PR is heavily modified, so while it probably still counts as derivative, it would be easy to do a full rewrite)

2022-05-28 14:43 UTC, corona10 commented
@ezio-melotti 
Yes, it's worth adding it. There are two reasons or we can separate the repo in the future as the submodule.
1. Mapping files have existed already in the CPython repo.
https://github.com/python/cpython/tree/main/Tools/unicode/python-mappings

2. And I noticed that mapping files were not maintained well even if they should contain the diff file like https://github.com/python/cpython/tree/main/Tools/unicode/python-mappings/diff 
I am focusing on maintaining a well reproducible environment even if the external environment is changed.
No one was interested in regenerating this file until I was concerned about the situation. This is an issue that can recur over time. Freezing the environment is important to prevent this from happening again.

2022-05-28 14:46 UTC, corona10 requested changes
Please regenerate Modules/cjkcodecs/mappings_hk.h and Modules/cjkcodecs/mappings_tw.h with new script.

2022-05-28 15:24 UTC, corona10 approved these changes
LGTM, but I will send a mail to @hyeshik to discuss this issue.
And also waiting for @ezio-melotti opinion about storing mapping files.
(I prefer to store at the own mapping repo under python org as a submodule, but let's do it at a separate issue.)

2022-05-28 17:05 UTC, ezio-melotti commented
The files that were there before were just a few kB (about 40kB in [9d5c071](https://github.com/python/cpython/tree/9d5c0710609320e51631750d1cf60c90cc618172/Tools/unicode/python-mappings)).  GH-19602 introduced more files (~1.3MB, 2 years ago).  GH-93309 recently added another ~1.4MB.  The files included in this PR add yet another ~800kB.

The CPython source (without the Git history) is ~27MB zipped and ~92MB once extracted.  With the Git history it's about 585MB (quite a bit more than I thought).

Compared to the rest, an extra 800kB is not particularly significant so it's probably ok to include them.

If you are planning to include more files, maybe it would be better to think about a different approach, depending on the goal (e.g. host copies somewhere on python.org and add a script to download them from there).  Note that since the other PRs have already been merged, even if we (re)move the files from the repo we might be able to reduce the repo size by ~3MB but they will be included in the history forever.

2022-05-28 17:55 UTC, corona10 requested changes
> The files that were there before were just a few kB (about 40kB in [9d5c071]>>(https://github.com/python/cpython/tree/9d5c0710609320e51631750d1cf60c90cc618172/Tools/unicode/python-mappings)). https://github.com/python/cpython/pull/19602 introduced more files (~1.3MB, 2 years ago). https://github.com/python/cpython/pull/93309 recently added another ~1.4MB. The files included in this PR add yet another ~800kB.

Okay, I never thought that it will be a burden.

@sorcio 
Can you please remove Tools/unicode/python-mappings/BIG5.TXT and Tools/unicode/python-mappings/CP950.TXT as a middle ground? (Sorry for duplicated works)

@ezio-melotti
I will revert https://github.com/python/cpython/pull/93309 too.
But can you open the discussion about storing mapping files that can be managed by CPython developers?
I think that you can understand what I was concerned about and what I intended to do.
It will cover all files under Tools/unicode/python-mappings/.

> (e.g. host copies somewhere on python.org and add a script to download them from there).

That looks like a good suggestion as much as maintaining a submodule repository through GitHub.

Thank you for understanding.

2022-05-30 04:31 UTC, ezio-melotti commented on Tools/unicode/genmap_tchinese.py
> +MAPPINGS_CP950 = 'http://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP950.TXT'
```suggestion
MAPPINGS_CP950 = 'https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP950.TXT'
```

2022-05-30 12:12 UTC, ezio-melotti approved these changes
The patch looks good to me.  The script could be improved a bit (e.g. more docstring), but I'm assuming those parts were already in the original script and you didn't touch them.

I was also looking at e.g. `open_mapping_file` (defined in `genmap_support`) and noticed that it could be improved to report a clearer message.  This however is out of the scope of this PR. @corona10, are you planning to do more work related to this?  Do you think it would be worth to refactor these scripts?

I also noticed that the PR doesn't include any tests.  For the tool itself is probably ok, however the resulting mapping should be tested.  Are there already tests for that?  It might also be useful to add some tests for the characters that diverge from one codec variant to the other, in order to avoid regressions.

2022-05-30 14:21 UTC, corona10 approved these changes
> I was also looking at e.g. open_mapping_file (defined in genmap_support) and noticed that it could be improved to report a clearer message. This however is out of the scope of this PR. @corona10, are you planning to do more work related to this? Do you think it would be worth to refactor these scripts?

Please go ahead.

lgtm

2022-06-11 06:01 UTC, hyeshik commented
Thank you for your efforts in resolving this old problem, @sorcio, @ezio-melotti, and @corona10. All the changes look good to me. Also, I would like to put all my work included in the CJKCodecs releases into the public domain to allow more flexible adoptions in any derivative work. Please feel free to change the copyright conditions as needed.

2022-06-11 14:19 UTC, merged

2022-06-11 14:20 UTC, corona10 commented
Thank you @hyeshik!