bpo-34660: Replace offensive words
python/cpython pull request #9335
Opened 2018-09-15 18:59 UTC by jonsees

This is a work in progress. Contributor Form has not been reviewed yet, apparently. I'll push more commits in the meantime.

2018-09-15 18:59 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-09-15 21:45 UTC, terryjreedy requested changes
I think the proposed changes are plausible improvements somewhat independent of any offensiveness.

To me, the 'sin' of these words is that they tend to be vague and say more about the writer's opinion than about the ostensible subject.  If I were to merge this, I would be tempted to change the title to "Replace vague negative words in code." or "Replacy vague negative value judgments".

I removed the change to idlelib/todo.txt because it is not code and  because the decade old file needs much heavier editing, which I would want to backport if and when I do so.

2018-09-15 21:45 UTC, terryjreedy commented on Lib/test/test_keyword.py
> +            "        'weird but legal',",
Change breaks tests because list must be alphabetically sorted.  'weird by legal' belongs just before 'wigii'.

2018-09-15 21:45 UTC, terryjreedy commented on Lib/test/test_decimal.py
> +        weird = {
There might be an even better name and custom example. 
```
phone = {
	'decimal_point': 'x',
	'grouping': make_grouping([4, 3, 3, CHAR_MAX]),
	'thousands_sep': '-',
	}
```
would be useful if one were confronted with phone numbers with extensions stored as Decimals.

2018-09-15 21:45 UTC, terryjreedy commented on Lib/test/test_pprint.py
> +        # against a random mix of types.
From the technical side, I would prefer 'haphazard' or 'arbitrary', as 'random' implies a probability distribution.

2018-09-15 21:45 UTC, terryjreedy commented on Lib/test/test_unicode_file_functions.py
> -        # Windows is lunatic. Issue #13366.
The perjorative dig should just go.  Replace with 'Two exceptions are possible.'

2018-09-15 23:35 UTC, jonsees commented
It shouldn't be this hard to make small good changes that are _at least_ harmless (except for one that slipped, my bad). There are _so_ many occurrences of problematic words, some of which I haven't even touched. I admit I didn't expect I'd have to debate each one of a few dozen suggestions, and I won't do it, if *"'random' implies a probability distribution"* counts as a valid argument against them. I see that Python developers have no desire of actually accepting any of these changes, and there's only so much I can do in this case.

Status quo wins then. You should still remove the phrase "brain-dead" from your documentation. Hope it's not too controversial for you.

2018-09-16 18:55 UTC, jonsees commented
No, I won't entertain you. Major open-source projects are removing dated offensive terminology, and you can see evidence of that on the original BPO page. The change _will_ eventually come, whether you like it or not, @hawran.

2018-09-16 19:32 UTC, hawran commented
> No, I won't entertain you. Major open-source projects are removing dated offensive terminology, and you can see evidence of that on the original BPO page. The change _will_ eventually come, whether you like it or not, @hawran.

No, I'm NOT having fun.
It's **sad**, to be honest.

Well, I'm going to write letters to both Iron Maiden and Metallica demanding to rename some albums of theirs.
Then...
Ad nauseam.

**When is this insanity going to end?**

2018-09-16 19:39 UTC, jonsees commented
It is going to end when people stop throwing around insults like "insane" and "mad", and understand that these words make others feel uncomfortable. I won't reply specifically to you anymore, just FYI.

2018-09-16 19:40 UTC, suic86 commented
> and you can see evidence of that on the original BPO page

@jonsees are you serious? How can you call that evidence? When you compile 5 random links it doesn't constitute evidence.

> There are so many occurrences of problematic words, some of which I haven't even touched.

When @jonsees says that something is problematic then it's problematic? Defined what a problematic word is. IMO there's no consensus about.

2018-09-16 19:46 UTC, hawran commented
To whom it may concern:

_jonsees
Joined **a day ago**_
(as of 16 Sep 2018)

Is this a common situation?

2018-09-16 19:49 UTC, jonsees commented
Yes, it's common to make alternative accounts to avoid IRL harassment from you guys.

2018-09-16 20:35 UTC, RaresDima commented
This is the same principle that was going on with the master/slave deal a couple days ago. 
Ideology and subjective things like what *you personally believe* are insulting or offensive words are not meant to be and it is obvious beyond any reasonable doubt that they are jokes and are in good fun and removing those serves no other reason than to boost someone's ego.

Quite simply the fact that some people feel insecure about some words does not give you the right to censor the world. If you do not like a food, you simply don't go to the restaurant serving it anymore, you don't try to argue with the restaurant that because you don't like it they should not serve it. 
 
The words used are used in good humor and anyone that is not specifically looking for something to be angry about and use as a slingshot to boost their own ago will most likely see it.

2018-09-16 21:26 UTC, terryjreedy commented
@jonsees  I am a real-life person using my real-life name while I volunteer my time trying to improve Python, which I have done for over 21 years.  I have real feelings.  I consider your response to my review rude and insulting. Since you do not wish to revise the PR, I close it.

@RaresDima Thank you for writing the rest of what I would like to have said.

2018-09-16 21:26 UTC, closed without merging

2018-09-17 01:37 UTC, willingc commented
I've locked this discussion thread for a 7 day cool down period.