docs: datetime: Encoding is no longer relevant
python/cpython pull request #93365
Opened 2022-05-30 22:13 UTC by wjandrea

The `.strftime()` methods return a Unicode string as of Python 3.0.

---

For reference, under the hood, the `.strftime()` methods use `time.strftime()`, whose return value is defined [here](https://github.com/python/cpython/blob/5893b5db98b38b17750c0572c7209774a5034898/Modules/timemodule.c#L881-L897) for the current tip of the main branch and [here](https://github.com/python/cpython/blob/3.0/Modules/timemodule.c#L535-L539) for 3.0.

---

Please check my work before merging to make sure I've understood what the docs are saying. I'm also not super familiar with C or RST, but I'm quite sure I've understood them correctly.

Backports should be made to all current versions.

---

BTW, encoding isn't mentioned in the `time` docs, so no changes required there I don't think.

2022-06-08 12:42 UTC, DanielNoord approved these changes

2022-06-08 13:32 UTC, AA-Turner approved these changes

2022-09-29 21:57 UTC, merwok commented
Could you create a ticket to describe the issue and make it easier to track the fixes?  Thanks

2022-10-07 00:52 UTC, nanjekyejoannah reviewed
I agree, maybe we need an issue to track this.

2022-10-14 20:13 UTC, wjandrea commented
@merwok @nanjekyejoannah I could open an issue, sure, I'm just not sure what to say beyond what I've written here. Maybe,

> The docs say that `strptime()` will return an encoded string (i.e. `bytes`), but actually it returns a Unicode string as of Python 3.0 (i.e. `str`).

Actually, now that I think about it again, maybe it'd be better to change the warning from "may contain Unicode characters encoded ..." to "may contain non-ASCII characters." Say the word and I'll open an issue so we can discuss that.

2022-10-14 20:27 UTC, merwok commented
That’s just the process we follow to keep things manageable 🙂 
A bug report doesn’t have to be very long, if the title is clear and the description tells clearly what the problem is, then we can apply labels to categorize the problem, note all versions that need a fix, people get notified about it, etc.
The issue describes the problem and the PR discussion can focus on the solution.  That’s all!

Full details here: https://devguide.python.org/triage/issue-tracker/

2022-11-03 09:27 UTC, Jason-Y-Z commented
Thanks for the PR. I think you will need to include the issue number in your PR title :)

2023-04-24 18:01 UTC, pganssle requested changes

2023-04-24 18:01 UTC, pganssle commented on Doc/library/datetime.rst
> +   example, "month/day/year" versus "day/month/year").
```suggestion
   example, "month/day/year" versus "day/month/year"), and the output may
   contain non-ASCII characters.
```

I think this change is a net positive, but I'm wondering if we might want to give people a head's up that they shouldn't assume that the output is ASCII, even though `str` is now a Unicode object? Maybe the world is at a point where we don't have to point this out, but maybe it won't hurt?

2023-04-24 18:14 UTC, merwok commented on Doc/library/datetime.rst
> +   example, "month/day/year" versus "day/month/year").
I think this suggestion is a good idea!

2023-04-24 18:36 UTC, pganssle approved these changes

2023-04-24 18:37 UTC, pganssle commented on Doc/library/datetime.rst
> +   example, "month/day/year" versus "day/month/year").
Good enough for me ☺

2023-04-24 18:40 UTC, abalkin approved these changes
LGTM

2023-04-24 18:54 UTC, merged

2023-04-24 18:54 UTC, miss-islington commented
Thanks @wjandrea for the PR, and @pganssle for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖