bpo-34659: Adds initial kwarg to itertools.accumulate()
python/cpython pull request #9345
Opened 2018-09-16 21:18 UTC by lisroach

https://bugs.python.org/issue34659

2018-09-17 04:26 UTC, rhettinger approved these changes

2018-09-17 04:57 UTC, tim-one approved these changes
Looks good!  Thank you - I'll even use it ;-)

2018-09-17 06:11 UTC, serhiy-storchaka requested changes
There are following technical problems with current changes:
1. The default value for *initial* is documented and exposed in the signature as `None`, but passing `None` is not the same as omitting the *initial* argument.
2. Pickling and copying the `accumulate` iterator loses the initial value.

2018-09-17 06:37 UTC, rhettinger commented
The pickling and copying should be a separate tracker item for Kristjan Jonnson to update his own code (I think he is the only user of that feature and would be willing to shoulder some of the recurring maintenance burden arising from that code).

2018-09-17 06:58 UTC, serhiy-storchaka commented
I don't think that ignoring `initial=None` is right. And you did not think this too, according to your [initial implementation](https://mail.python.org/pipermail/python-ideas/2018-April/049649.html).

2018-09-17 08:05 UTC, rhettinger commented
It depends on whether you think *None* would be a useful input value to an accumulation.

The `start=_sentinel` approach gives more flexibility but is problematic for complicating the pure python version in the docs and for wrestling with argument clinic (I suspect we would have to remove the clinic code entirely and forgo the signature it generates).  If so, I'm inclined to leave the PR as is.

2018-09-17 08:29 UTC, serhiy-storchaka commented
This will make a subtle difference between `accumulate()` and `reduce()`, and also `max()`, `iter()`, `next()`, `getattr()`, etc which accept an optional argument, but distinguish `None` from no argument. I think this will be a bug magnet.

As for the pure python version in the docs, the pure python version of `reduce()` uses `None` as a sentinel.

2018-09-19 07:33 UTC, rhettinger commented
Added pickle support (when *initial* is set, use `chain([initial], it)`).  Please take a look.

2018-09-20 10:00 UTC, serhiy-storchaka reviewed
Please add an entry in What's New.

2018-09-20 10:00 UTC, serhiy-storchaka commented on Modules/itertoolsmodule.c
> +        return Py_BuildValue("O(OO)O", Py_TYPE(lz),
`"O(NO)O"`

2018-09-20 10:00 UTC, serhiy-storchaka commented on Modules/itertoolsmodule.c
> +                            it, lz->binop?lz->binop:Py_None, Py_None);
Please add spaces around `?` and `:` for PEP 7.

2018-09-20 15:10 UTC, rhettinger commented on Modules/itertoolsmodule.c
> +                            it, lz->binop?lz->binop:Py_None, Py_None);
It's better without the spaces to show the grouping and for consistency with the surrounding code.

2018-09-20 15:12 UTC, rhettinger commented on Modules/itertoolsmodule.c
> +        return Py_BuildValue("O(OO)O", Py_TYPE(lz),
IMO this is to minor to warrant a WhatsNew entry.  Whatsnew should be much more selective.  The reason we have whatsnew is that NEWS is already unmanageably lengthy to read.

2018-09-20 15:31 UTC, rhettinger commented on Modules/itertoolsmodule.c
> +        return Py_BuildValue("O(OO)O", Py_TYPE(lz),
Fixed.

2018-09-21 06:16 UTC, serhiy-storchaka commented
The pickling part LGTM. But I think that `initial=None` should not be ignored.

2018-09-21 07:09 UTC, rhettinger commented
Serhiy, thank you for the suggestion about `initial=None`, but I'm going to decline.  I want to keep the argument clinic here and I agree with [Tim's post on the subject](https://bugs.python.org/msg325616). As module maintainer, I get to make the final call on the API.

Let's clear the way for Lisa to apply her first patch own her own.  Please clear the review request so this can move forward. It has already consumed far too much time in relative to the value of the feature.

2018-09-21 07:43 UTC, serhiy-storchaka commented
This feature is just too complex for its value.

2018-09-21 07:44 UTC, serhiy-storchaka approved these changes

2018-09-24 00:35 UTC, merged