GH-93521: Filter out `__weakref__` slot if present in bases
python/cpython pull request #93535
Opened 2022-06-06 13:14 UTC by Bluenix2

This PR fixes #93521 by moving the `('__weakref__',) if weakref_slot else ()` ternary *into* the iterator that filters out already present slots.

2022-06-06 13:53 UTC, Bluenix2 commented
I am not sure why my commit was changed to `pythonGH` rather than `GH` by GitHub...

2022-06-06 14:13 UTC, ericvsmith requested changes

2022-06-06 14:13 UTC, ericvsmith commented on Lib/test/test_dataclasses.py
> +        class Base:
You should also check the case where `Base` is a normal class which includes `__weakref__` in `slots`.

2022-06-06 14:13 UTC, ericvsmith commented on Lib/test/test_dataclasses.py
> +        weakref.ref(a)
And you should also probably test where `Base` is a dataclass with `weakref_slot=True`, and `A` is a dataclass where `weakref_slot` is not specified (or is specified as `False`).

2022-06-06 14:13 UTC, ericvsmith commented on Misc/NEWS.d/next/Library/2022-06-06-13-19-43.gh-issue-93521._vE8m9.rst
> +Allow specifying ``weakref_slot`` several times in dataclass MRO
"MRO" is jargony, how about "base classes" instead? Also, this isn't just about `weakref_slot`, it's about `__weakref__` in any base class's `__slots__`, whether or not that class is a dataclass. I'm not sure the best way to word all of this, maybe drop any reference to dataclass here and just mention `__weakref__` in base classes. Or maybe start with the generic base class statement, and add another sentence saying this includes base dataclasses that have `weakref_slot=True`.

And by convention, please end the blurb with a period. They should contain one or more sentences. (I know this is a trivial point.)

2022-06-06 15:08 UTC, Bluenix2 commented on Lib/test/test_dataclasses.py
> +        class Base:
~~This is tested by [`test_slots_weakref_base_tuple`](https://github.com/python/cpython/blob/8584981a5894ba79fbabbfe7e3ef37ba6f3c2f14/Lib/test/test_dataclasses.py#L3077-L3092) already.~~ I was wrong and have fixed this locally, I had already written this comment and accidentally sent it instead of discarding it.

2022-06-06 15:18 UTC, Bluenix2 commented on Misc/NEWS.d/next/Library/2022-06-06-13-19-43.gh-issue-93521._vE8m9.rst
> +Allow specifying ``weakref_slot`` several times in dataclass MRO
Thank you. I wrote it more like a commit message, than a point on a page of patch notes for a game.

2022-06-08 00:51 UTC, ericvsmith approved these changes

2022-06-08 00:53 UTC, merged

2022-06-08 00:53 UTC, miss-islington commented
Thanks @Bluenix2 for the PR, and @ericvsmith for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!