gh-93600: Clarify the meaning of buffering=-1 in open()
python/cpython pull request #93685
Opened 2022-06-10 14:17 UTC by eamanu

This commit clarify the meaning of buffering=-1 in open() function. Add
this information in Docs and in source code docstring.

2022-06-10 18:41 UTC, AA-Turner requested changes
Grammar, and a minor change from "default buffer size" to "default buffering policy" -- this ties in the following text and helps communicate that `-1` is the same as passing no argument.

A

2022-06-10 18:41 UTC, AA-Turner commented on Doc/library/functions.rst
>     buffering (only usable in text mode), and an integer > 1 to indicate the size
As you've added to the list, remove the previous joining 'and'. I also might consider reformatting this list as a definition list or a bulleted list as there are now four items (-1, 0, 1, >=2)
```suggestion
   buffering (only usable in text mode), an integer > 1 to indicate the size
```

2022-06-10 18:41 UTC, AA-Turner commented on Lib/_pyio.py
>      line buffering (only usable in text mode), and an integer > 1 to indicate
As above
```suggestion
    line buffering (only usable in text mode), an integer > 1 to indicate
```

2022-06-10 18:41 UTC, AA-Turner commented on Lib/_pyio.py
> +    the size of a fixed-size chunk buffer, or-1 to use the default buffer size.
As above, spacing
```suggestion
    the size of a fixed-size chunk buffer, or -1 to use the default buffering policy.
```

2022-06-10 18:41 UTC, AA-Turner commented on Modules/_io/_iomodule.c
>  line buffering (only usable in text mode), and an integer > 1 to indicate
As above
```suggestion
line buffering (only usable in text mode), an integer > 1 to indicate
```

2022-06-10 18:41 UTC, AA-Turner commented on Modules/_io/_iomodule.c
> +size.  When no buffering argument is given, the default buffering policy
```suggestion
the size of a fixed-size chunk buffer, or -1 to use the default buffering
policy.  When no buffering argument is given, the default buffering policy
```

2022-06-10 18:41 UTC, AA-Turner commented on Doc/library/functions.rst
> +   in bytes of a fixed-size chunk buffer, or -1 to use the default buffer size.
```suggestion
   in bytes of a fixed-size chunk buffer, or -1 to use the default buffering policy.
```

2022-06-10 23:33 UTC, eamanu commented
HI @AA-Turner I've just push some changes, I applied the your recommendations and I pushed a commit running clinic.py, I hope that fix the build :-)

2022-06-11 01:45 UTC, AA-Turner reviewed
Thanks, it did fix the build -- you need to re-wrap two lines though and then go through the regen dance again!

A

2022-06-11 01:45 UTC, AA-Turner commented on Lib/_pyio.py
> +    the size of a fixed-size chunk buffer, or -1 to use the default buffering policy.
Please re-wrap this line to 70-80 chars

2022-06-11 01:45 UTC, AA-Turner commented on Doc/library/functions.rst
> +   in bytes of a fixed-size chunk buffer, or -1 to use the default buffering policy.
Please re-wrap this line to 70-80 chars

2022-06-11 13:01 UTC, eamanu commented on Doc/library/functions.rst
> +   in bytes of a fixed-size chunk buffer, or -1 to use the default buffering policy.
@AA-Turner Ready thanks!

2022-08-04 15:21 UTC, merwok reviewed
Suggest changes to minimize diff churn.
Lines shorter than the limit are no problem, and this keeps git history slightly more useful 🙂

2022-08-04 15:21 UTC, merwok commented on Doc/library/functions.rst
> +   the default buffering policy works as follows:
```suggestion
   policy. Note that specifying a buffer size this way
   applies for binary buffered I/O, but ``TextIOWrapper`` (i.e., files opened
   with ``mode='r+'``) would have another buffering. To disable buffering in
   ``TextIOWrapper``, consider using the ``write_through`` flag for
   :func:`io.TextIOWrapper.reconfigure`. When no *buffering* argument is
   given, the default buffering policy works as follows:
```

2022-08-04 15:21 UTC, merwok commented on Lib/_pyio.py
> +    works as follows:
```suggestion
    line buffering (only usable in text mode), an integer > 1 to indicate
    the size of a fixed-size chunk buffer, or -1 to use the default buffering
    policy. When no buffering argument is
    given, the default buffering policy works as follows:
```

2022-08-04 15:21 UTC, merwok commented on Modules/_io/_iomodule.c
> +works as follows:
```suggestion
policy.  When no buffering argument is
given, the default buffering policy works as follows:
```

2022-08-09 10:20 UTC, eamanu commented
Ready thanks @merwok

2022-08-09 14:12 UTC, merwok commented on Doc/library/functions.rst
> +   applies for binary buffered I/O, but ``TextIOWrapper`` (i.e., files opened
```suggestion
   policy. Note that specifying a buffer size this
   way applies for binary buffered I/O, but ``TextIOWrapper`` (i.e., files opened
```

2024-10-31 08:32 UTC, willingc commented
Thanks @eamanu. It looks like the merge conflicts need to be resolved. Please ping me once they are updated. Thanks.

2026-09-10 20:10 UTC, StanFromIreland commented
Sorry, but I'm going to close this as stale. It has several conflicts and has not been updated in a long time.

2026-09-10 20:10 UTC, closed without merging