bpo-23033:  consider wildcard in left most segment only
python/cpython pull request #937
Opened 2017-04-01 04:59 UTC by daxlab

2017-04-01 22:10 UTC, alex commented
Looks like there is a relevant failing `ssl` test.

2017-04-02 10:02 UTC, daxlab commented
@alex review now.

2017-04-02 12:47 UTC, alex requested changes
I have a few small comments.

Thanks for working on this! This is a great improvement to making `match_hostname` behave more like the rest of the PKI infrastructure.

2017-04-02 12:47 UTC, alex commented on Lib/ssl.py
> +        """
Nit: Please use a `#` style comment. `"""` is for docstrings.

2017-04-02 12:47 UTC, alex commented on Lib/test/test_ssl.py
> +        # only match wildcard in left-most segment
This comment still doesn't fell right, there is a wildcard _in_ the left-most segment. I think it should say something like "only match wildcards when they are the only thing in the left-most segment". What do you think?

2017-04-02 13:33 UTC, daxlab commented on Lib/test/test_ssl.py
> +        # only match wildcard in left-most segment
Sounds much better, pushing the changes.

2017-04-02 13:40 UTC, alex commented
Doc failures are not your fault, https://github.com/sphinx-doc/sphinx/issues/3597 is the cause.

2017-04-02 13:41 UTC, alex approved these changes

2017-04-02 13:49 UTC, daxlab commented
@alex  anything else needed from my side ?

2017-04-02 13:50 UTC, alex commented
This looks good to me. I'll probably ask for another review before landing. Thanks so much!

2017-04-02 14:06 UTC, reaperhulk approved these changes
Looks good to me. Wildcards should be honored iff they are the leftmost fragment and are the only character in that fragment.

2017-04-02 15:55 UTC, tiran commented
You are almost there! Please add a ```versionchanged:: 3.7``` to ```match_hostname``` documentation in ```Doc/library/ssl.rst```.

2017-04-02 15:56 UTC, tiran requested changes
versionchanged in documentation is missing.

2017-04-02 17:23 UTC, daxlab commented
@tiran version changed docs added.

2017-04-02 18:07 UTC, tiran approved these changes
Thank you very much for your contribution, @daxlab. Your work is an excellent base to clean up and simplify the host matching code even further.

@alex the change is backwards incompatible. I've asked Ben and Ned if they are fine with backports to 2.7 and 3.6.

2017-04-03 09:27 UTC, daxlab commented
@tiran @alex can we merge this ?

2017-04-04 06:58 UTC, tiran commented
@daxlab @alex I'm waiting for confirmation regarding backport to 3.6 and 2.7.

2017-04-19 04:24 UTC, berkerpeksag reviewed
I think we also need to add an entry to `Misc/NEWS`.

2017-04-19 04:24 UTC, berkerpeksag commented on Doc/whatsnew/3.7.rst
> +  left most segment of hostname in second argument of :meth:`match_hostname`.
I'd change :meth:\`match_hostname\` to :meth:\`ssl.match_hostname\`. This would create a link to the `ssl.match_hostname()` documentation.

2017-04-19 05:21 UTC, daxlab commented on Doc/whatsnew/3.7.rst
> +  left most segment of hostname in second argument of :meth:`match_hostname`.
@berkerpeksag thanks for review. I have pushed a fix.

2017-05-28 13:28 UTC, daxlab commented
@tiran any updates ?

2017-06-12 04:16 UTC, Mariatta commented on Misc/NEWS
> +  character in the left most segment of hostname.
Please add "Patch by Mandeep Singh."

2017-06-12 04:16 UTC, Mariatta commented
Please add yourself to Misc/ACKS, resolve the conflict and update Misc/NEWS.
Thanks.

2017-06-12 12:32 UTC, daxlab commented on Misc/NEWS
> +  character in the left most segment of hostname.
done.

2017-06-12 12:33 UTC, daxlab commented
@Mariatta changes pushed.

2017-07-02 10:32 UTC, daxlab commented
@Mariatta changes pushed.

2017-08-27 16:24 UTC, daxlab commented
any update ?

2017-10-01 07:20 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-11-24 00:44 UTC, Mariatta commented
Thanks @daxlab for your patience with this PR, sorry it's taking a while.
I think this can go to 3.7.
Could you rebase this to make it up to date? We need the news entry in Misc/NEWS.d/, it can be generated using [blurb](https://pypi.org/project/blurb).

2017-11-24 07:18 UTC, daxlab commented
@Mariatta will update the PR tonight.

2017-11-26 11:33 UTC, daxlab commented
@Mariatta I have rebased the PR and added news entry in Misc/NEWS.d/

2017-11-26 15:49 UTC, Mariatta approved these changes

2017-11-26 15:57 UTC, Mariatta commented
Thanks. I made minor changes and added you to Misc/ACKs. Waiting until CI is done.

2017-11-26 22:31 UTC, merged

2017-11-26 22:32 UTC, Mariatta commented
Thanks again @daxlab and congrats on your first contribution to CPython :taco: