fix client_context example from ssl protocol versions docs
python/cpython pull request #93798
Opened 2022-06-14 09:46 UTC by graingert

2022-06-14 09:48 UTC, graingert commented on Doc/library/ssl.rst
>  The SSL context created above will only allow TLSv1.2 and later (if
this states the context above supports TLSv1.2-max but the example was TLSv1.3 only

2022-06-14 09:50 UTC, graingert commented on Doc/library/ssl.rst
> -   >>> client_context.maximum_version = ssl.TLSVersion.TLSv1_3
introduced here https://github.com/python/cpython/pull/25455/files#diff-df0c7115ade453321aadb2eb534941f2ec87c4b52563bae70421918dce5435dcR2653-R2654

2022-06-14 09:52 UTC, graingert commented
I'm not sure if it's better to update the code example or the description here

2022-08-09 17:15 UTC, graingert commented
https://github.com/python/cpython/issues/95816

2023-12-19 20:02 UTC, janbrasna commented on Doc/library/ssl.rst
>  The SSL context created above will only allow TLSv1.2 and later (if
@graingert If you update to current `main` the wording now states _"TLSv1.3 and later"_ — so I'd recommend to match ssl.* min version with main too, but definitely propose the `MAXIMUM_SUPPORTED` anyways which makes much more sense compared to the current docs.

(While the docs specify _"Deprecated since version 3.10: All TLSVersion members except TLSVersion.TLSv1_2 and TLSVersion.TLSv1_3 are deprecated."_ I believe that doesn't include the magic constants, as I can't see any proof in the deprecation warning code to raise any warnings for the MIN_/MAX_ constants, so it's just the description that's written too broadly.)

2023-12-19 20:13 UTC, janbrasna requested changes
There have been some minor changes in the past year, so updating few bits would align this more with the currently published docs, as the explainer bumped versions in https://github.com/python/cpython/commit/e5252c6127ad788b39221982964f935bd1513028 (see https://github.com/python/cpython/issues/95816#issuecomment-1863394886 for progress)

2023-12-19 20:13 UTC, janbrasna commented on Doc/library/ssl.rst
> +   >>> client_context.minimum_version = ssl.TLSVersion.TLSv1_2
```suggestion
   >>> client_context.minimum_version = ssl.TLSVersion.TLSv1_3
```

to match the current description.

2023-12-22 10:22 UTC, janbrasna requested changes
The magic constant added since 3.7 is in reality not MAXIMUM_**VERSION**, but  MAXIMUM_**SUPPORTED**

2023-12-22 10:22 UTC, janbrasna commented on Doc/library/ssl.rst
> +   >>> client_context.maximum_version = ssl.TLSVersion.MAXIMUM_VERSION
The correct constant is `ssl.TLSVersion.MAXIMUM_SUPPORTED`

```suggestion
   >>> client_context.maximum_version = ssl.TLSVersion.MAXIMUM_SUPPORTED
```

https://docs.python.org/3/library/ssl.html#ssl.TLSVersion.MINIMUM_SUPPORTED

I don't see any constant alias with _VERSION, only _SUPPORTED according to:
https://github.com/python/cpython/blob/5a4af3ab030a3f3e708ee83d7d4ca3cb2d5b7360/Modules/_ssl.c#L220-L236

2023-12-22 12:29 UTC, janbrasna commented on Doc/library/ssl.rst
>  The SSL context created above will only allow TLSv1.2 and later (if
On the other hand, configuring the max version in this way is superfluous, as that is by the definition the default:
> "SSLContext.maximum_version — A TLSVersion enum member representing the highest supported TLS version. The value defaults to TLSVersion.MAXIMUM_SUPPORTED."
— https://docs.python.org/3/library/ssl.html#ssl.SSLContext.minimum_version

so there's no point of showing an example set this way.

I'd personally vouch for showing a real range as in https://github.com/python/cpython/pull/107273#pullrequestreview-1794398142 …

2025-01-09 09:19 UTC, kumaraditya303 requested changes

2025-01-09 09:19 UTC, kumaraditya303 commented on Doc/library/ssl.rst
> +   >>> client_context.maximum_version = ssl.TLSVersion.MAXIMUM_SUPPORTED
I think just removing `maximum_version` would automatically make it v1.3+ itself.

2026-05-18 18:01 UTC, closed without merging