[3.10] GH-93964: Harden overflow checks before _PyBytes_Resize in compile.c
python/cpython pull request #94045
Opened 2022-06-21 03:02 UTC by sweeneyde

https://github.com/python/cpython/issues/93964

2022-06-21 03:30 UTC, sweeneyde commented
I confirmed that this successfully raises instead of crashing:
```
>>> import english_data  # from the issue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
```

2022-06-21 09:57 UTC, markshannon requested changes
A couple of minor issues, otherwise LGTM.

2022-06-21 09:57 UTC, markshannon commented on Python/compile.c
> +        PyErr_NoMemory();
Strictly this isn't a memory error, but a limitation of the VM.
Maybe raise an OverflowError?

(Likewise for the two cases below)

2022-06-21 09:57 UTC, markshannon commented on Python/compile.c
> +        if (len > PY_SSIZE_T_MAX / 2) {
This needs to be `INT_MAX / 2` not `PY_SSIZE_T_MAX / 2`.
We assume throughout the interpreter that various offsets and indexes fit into `int`.

2022-06-22 08:37 UTC, markshannon commented
Thanks.

2022-06-22 08:37 UTC, merged