hg-94018: Remove trailing spaces in _sanitize_windows_name
python/cpython pull request #94040
Opened 2022-06-20 20:52 UTC by Rygone

2022-06-20 21:54 UTC, hauntsaninja commented
You'll want to rename your PR to "gh-94018 [...]" instead of "hg-94018"

2022-06-20 22:48 UTC, hauntsaninja commented on Misc/NEWS.d/next/Windows/2022-06-20-22-32-14.gh-issue-94018.bycC3A.rst
> +Remove trailing spaces in :func:`Lib.zipfile._sanitize_windows_name`
```suggestion
Remove trailing spaces in :func:`zipfile._sanitize_windows_name`
```

2022-06-21 18:34 UTC, zware requested changes
There should be one or more tests added for this.  See `Lib/test/test_zipfile.py`.

The change itself looks reasonable enough to me, but this should be reviewed by someone who is more versed in the inner workings of zip files before it is merged.

2022-06-21 18:34 UTC, zware commented on Misc/NEWS.d/next/Windows/2022-06-20-22-32-14.gh-issue-94018.bycC3A.rst
> +Remove trailing spaces in :func:`zipfile._sanitize_windows_name`
`_sanitize_windows_name` is not a public or documented function, so it should not be mentioned here.

```suggestion
:mod:`zipfile` will now remove trailing spaces from path components on extraction.
```

2022-06-23 15:21 UTC, zware approved these changes
LGTM, but I'm not comfortable merging without an OK from one of our `zipfile` maintainers.

2022-06-23 18:17 UTC, dignissimus commented on Misc/NEWS.d/next/Windows/2022-06-20-22-32-14.gh-issue-94018.bycC3A.rst
> +:mod:`zipfile` will now remove trailing spaces from path components on extraction.
```suggestion
:mod:`zipfile` will now remove trailing spaces from path components when extracting files on Windows.
```

2022-06-28 10:08 UTC, ambv commented
LGTM. Leading or trailing spaces (ASCII `0x20`) are indeed not allowed on Windows and those characters are silently removed by the OS:
https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/file-folder-name-whitespace-characters

2022-06-28 10:09 UTC, merged