gh-81054: Document that SimpleHTTPRequestHandler follows symbolic links
python/cpython pull request #94416
Opened 2022-06-29 13:59 UTC by dignissimus

Documents that [`SimpleHTTPRequestHandler`](https://docs.python.org/3/library/http.server.html#http.server.SimpleHTTPRequestHandler) follows symbolic links when handling requests and explains the security implications.

Resolves #81054

* Issue: gh-81054

2022-06-29 17:12 UTC, ambv requested changes
Thanks for addressing this!

The current wording would suggest that following symlinks is the main (or even the *only*) security consideration of `http.server` which is far from the truth.

Instead of putting this information right in the "Warning" bar at the top, please create a "Security Considerations" section on the bottom of this page (`http.server.rst`). You can put your information there and we can later expand on it as needed.

Then you can link the word "security" in the "Warning" box to the new section, but more importantly you can put the new section here:

https://docs.python.org/3/library/security_warnings.html

2022-07-01 16:21 UTC, merged

2022-07-01 16:21 UTC, miss-islington commented
Thanks @dignissimus for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.7, 3.8, 3.9, 3.10, 3.11.
🐍🍒⛏🤖

2022-07-01 16:21 UTC, miss-islington commented
Sorry @dignissimus and @ambv, I had trouble checking out the `3.7` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 80aaeabb8bd1e6b49598a7e23e0f8d99b3fcecaf 3.7
                                ```

2022-07-03 16:00 UTC, vstinner commented
Oh, thank you that clarifying this in the documentation! That's helpful.