gh-91330: Tests and docs for dataclass descriptor-typed fields
python/cpython pull request #94424
Opened 2022-06-29 16:49 UTC by debonte

Add unit tests and documentation covering the behaviors of descriptor-typed fields on dataclasses.

2022-06-29 18:08 UTC, ambv requested changes
I left some smaller-scale comments inline but there's a bigger omission in this change: **what you are describing only works for data descriptors**. Consider this non-data descriptor (doesn't define either ``__set__`` or ``__delete__``) example:

```py3
class NDD:
    def __get__(self, obj, type):
        if obj is None:
            raise AttributeError

        return "NDD Internal Value"


@dataclasses.dataclass
class Cls:
    ndd: NDD = NDD()


obj = Cls(ndd="Something else!")
print(obj.ndd)
```

This will print "Something else!" because setting the value will cause `ndd` to appear as a key in `obj.__dict__`.

While non-data descriptors have little value as dataclass fields, I think it's worth pointing out explicitly that we're talking about data descriptors.

Another thing that irks me is that the example is using ``obj._x`` as internal storage for the data. This means that you cannot have two fields on the same dataclass of type `Descriptor` because they will overwrite each other's internal storage. (On the other hand storing state on the object allows it to be trivially picklable.)

Maybe you can come up with a more realistic example. We could also use an example of setting and retrieving a value, both of which would trigger the descriptor. This is currently missing.

2022-06-29 18:08 UTC, ambv commented on Doc/library/dataclasses.rst
> +* Similiarly, when getting or setting the field, the descriptor's
```suggestion
* Similarly, when getting or setting the field, the descriptor's
```

2022-06-29 18:08 UTC, ambv commented on Doc/library/dataclasses.rst
> +  is ``None``, the field will not have a default value.
What dataclasses is doing here is a simple case of doing `getattr(cls, FIELDNAME)` instead of `getattr(obj, FIELDNAME)`. If we're explaining this, how about we do it like this:

```suggestion
* To determine whether a field contains a default value, ``dataclasses``
  will call the descriptor's ``__get__`` method using its class access
  form (i.e. ``descriptor.__get__(obj=None, type=cls)``.  If the
  descriptor returns a value in this case, it will be used as the
  field's default. On the other hand, if the descriptor raises
  :exc:`AttributeError` in this situation, no default value will be
  provided for the field.
```

2022-06-29 18:08 UTC, ambv commented on Doc/library/dataclasses.rst
> +Note that if a field is annotated with a desriptor type, but is not assigned
```suggestion
Note that if a field is annotated with a descriptor type, but is not assigned
```

2022-06-29 18:08 UTC, ambv commented on Doc/library/dataclasses.rst
> +  class Descriptor():
```suggestion
  class Descriptor:
```

2022-06-29 18:08 UTC, ambv commented on Doc/library/dataclasses.rst
> +    def __get__(self, obj, objtype):
```suggestion
    def __get__(self, obj, type):
```

per https://docs.python.org/3/howto/descriptor.html#descriptor-protocol

2022-06-29 18:08 UTC, ambv commented on Doc/library/dataclasses.rst
> +      return getattr(obj, "_x")
As a defensive programming measure, I'd use the three-argument variant with the default. This isn't necessary due to current dataclasses behavior but makes things more obvious to the reader.

```suggestion
      return getattr(obj, "_x", self._default)
```

2022-06-29 18:08 UTC, ambv commented on Doc/library/dataclasses.rst
> +      if obj is not None:
I don't think `obj` can ever be ``None`` when ``__set__`` is used.

2022-06-29 19:12 UTC, debonte commented on Doc/library/dataclasses.rst
> +    def __get__(self, obj, objtype):
Ok, the docs are inconsistent about this. I wasn't sure which names to use. For example, [Implementing Descriptors](https://docs.python.org/3/reference/datamodel.html#descriptors) refers to them as `instance` and `owner` rather than `obj` and `type`.

2022-06-29 20:52 UTC, debonte commented
Thanks for your feedback @ambv!

> I think it's worth pointing out explicitly that we're talking about data descriptors.

It looks like it only works properly if you have both `__get__` and `__set__`. Is there a term for that? Data descriptor isn't quite right. If you have `__get__` and `__delete__` but no `__set__` you'll get an `AttributeError` when constructing a new `InventoryItem`.

> Another thing that irks me is that the example is using obj._x as internal storage for the data.

Fixed to leverage `__set_name__`

> Maybe you can come up with a more realistic example.

I changed the descriptor to convert inputs to `int`. This doesn't add much code, but it's easy to tell that `__set__` is actually being called from the examples. Is that realistic enough?

> We could also use an example of setting and retrieving a value, both of which would trigger the descriptor. This is currently missing.

Fixed

2022-07-05 15:51 UTC, ambv commented
Beautiful! I love the current example. Short but realistically scalable to non-trivial use cases. And includes `__set_name__` as a best practice. Thanks for this improvement.

2022-07-05 18:09 UTC, merged

2022-07-05 18:09 UTC, miss-islington commented
Thanks @debonte for the PR, and @ambv for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖