bpo-34755: Add few minor optimizations in _asynciomodule.c.
python/cpython pull request #9455
Opened 2018-09-20 16:52 UTC by serhiy-storchaka

2018-09-20 17:00 UTC, 1st1 requested changes

2018-09-20 17:00 UTC, 1st1 commented on Modules/_asynciomodule.c
> +    if (PyGen_Check(result)) {
This is incorrect; the old code called `inspect.isgenerator` on purpose as it recognizes generator-like objects compiled with Cython.  I suggest to first call `PyGen_Check` (fast path) and then `inspect.isgenerator`.

2018-09-20 18:11 UTC, serhiy-storchaka commented on Modules/_asynciomodule.c
> +    if (PyGen_Check(result)) {
`inspect.isgenerator(obj)` is literally `isinstance(obj, types.GeneratorType)`. This is translated to C as `PyObject_IsInstance(obj, &PyGen_Type)`. This is almost equivalent to `PyObject_TypeCheck(obj, &PyGen_Type)`, but falls back to `issubclass(obj.__class__, types.GeneratorType)` if `PyObject_TypeCheck` returns false. `PyGen_Check(obj)` is expanded to just `PyObject_TypeCheck(obj, &PyGen_Type)`.

Thus there is a difference if the generator-like object itself is not an instance of a GeneratorType subclass, but sets a fake `__class__`.

2018-09-20 18:17 UTC, 1st1 commented on Modules/_asynciomodule.c
> +    if (PyGen_Check(result)) {
Ah, sorry Serhiy, you're right.  I worked before on multiple issues with Cython and I think we fixed them by adding `isinstance(o, collections.abc.Generator)` or `isinstance(o, collections.abc.Coroutine)`.  Anyways, never mind, please go ahead with this PR.

2018-09-20 18:18 UTC, 1st1 approved these changes

2018-09-20 18:26 UTC, serhiy-storchaka commented on Modules/_asynciomodule.c
> +    if (PyGen_Check(result)) {
Should we use `PyGen_Check()` or `PyObject_IsInstance()`? The only difference is that different error messages are produced for generator-like objects with fake `__class__` (is this a case of Cython?). The code with `PyObject_IsInstance()` is more verbose.

2018-09-20 18:34 UTC, 1st1 commented on Modules/_asynciomodule.c
> +    if (PyGen_Check(result)) {
We should try to maintain the exact same behaviour between Python and C versions so I'd say let's use `PyObject_IsInstance()` (even though this code path is for legacy coroutines and will eventually be removed).

2018-09-21 06:11 UTC, merged

2018-09-21 06:12 UTC, serhiy-storchaka commented
Thank you for your review @1st1!