gh-94619: Remove long deprecated methods module_repr() and load_module()
python/cpython pull request #94624
Opened 2022-07-06 21:59 UTC by warsaw

Closes #94619

2022-07-28 18:20 UTC, warsaw commented
@brettcannon ping

2022-07-29 18:04 UTC, brettcannon requested changes

2022-07-29 18:04 UTC, brettcannon commented on Misc/NEWS.d/next/Library/2022-07-06-14-57-33.gh-issue-94619.PRqKVX.rst
> +Remove long deprecated methods `module_repr()` and `load_module()`.
```suggestion
Remove the long-deprecated `module_repr()` from `importlib`.
```

2022-07-30 19:50 UTC, warsaw commented
I have made the requested changes; please review again.

2022-08-03 20:01 UTC, warsaw commented
@brettcannon re-ping!

2022-08-05 00:22 UTC, brettcannon approved these changes

2022-08-05 00:24 UTC, merged