gh-94518: [_posixsubprocess] Replace each variable validity flag with a reserved value of that variable
python/cpython pull request #94687
Opened 2022-07-08 11:31 UTC by arhadthedev

Currently, `Modules/_posixsubprocess.c` uses variables supplied with flags of whether the variable was initialized with a value. However it confuses both a reader (another mental connection required to constantly keep in mind) and a compiler (warnings on potentially uninitialized variables). We can use a fact that these variables are of types with special values not used by anything else. This PR replaces the dedicated flags with these token values.

Namely:

- `gid`: `call_setgid = False` → `gid = -1`
- `uid`: `call_setuid = False` → `uid = -1`
- `groups`: `call_setgroups = False` → `groups = NULL` (obtained with `(groups_list != Py_None) ? groups : NULL`)

This PR is required for gh-94519.

---

PS.: @tiran I applied your suggestion as this, separate PR to keep gh-94519 reviewable.

2022-07-12 17:51 UTC, arhadthedev commented
This change has no user-visible effect so no NEWS entry is required.

2022-07-22 11:15 UTC, arhadthedev commented
> Please include a news entry.
>
> We typically only skip news if the change is a trivial internal change or change is already covered by a previous PR. Non-trivial commits get a news entry so other core devs, release manager, distributors, and users have an easier way to locate a problem when a change introduces a regression.

@tiran Done (initially I've thought this change is invisible to users so skipped it).

2022-07-27 00:17 UTC, gpshead requested changes
I like this PR :)

2022-07-27 00:17 UTC, gpshead commented on Modules/_posixsubprocess.c
> +        /* Checked by our caller; verify this in debug builds. */
keep equivalent assertions in here:

```
assert(uid == (uid_t)-1);
assert(gid == (gid_t)-1);
assert(groups_size < 0);
```

2022-07-27 00:17 UTC, gpshead commented on Modules/_posixsubprocess.c
> +             size_t groups_size, const gid_t *groups,
change groups_size to a Py_ssize_t as that is what we pass in. We can then use it being < 0 to mean the former `!call_setgroups`.  A call to C's `setgroups(0, NULL)` via an empty list of groups has meaning.

2022-07-27 00:17 UTC, gpshead commented on Modules/_posixsubprocess.c
> +           size_t groups_size, const gid_t *groups,
Use Py_ssize_t for groups_size so that < 0 can mean "don't call setgroups".

2022-07-27 00:17 UTC, gpshead commented on Modules/_posixsubprocess.c
> +    if (groups)
`if (groups_size >= 0)`

`setgroups(0, NULL)` is valid.

2022-07-27 00:17 UTC, gpshead commented on Modules/_posixsubprocess.c
>              }
Change

```
if ((groups = PyMem_RawMalloc(num_groups * sizeof(gid_t))) == NULL) {
```

to

```
if (num_groups > 0 && (groups = PyMem_RawMalloc(num_groups * sizeof(gid_t))) == NULL) {
```

2022-07-27 00:17 UTC, gpshead commented on Modules/_posixsubprocess.c
> +        uid == (uid_t)-1 && gid == (gid_t)-1 && groups_list == Py_None) {
for consistency, use `num_groups < 0` here and below instead of the groups_list Py_None check.

2022-07-27 21:17 UTC, arhadthedev commented
> `if (groups_size >= 0)`
>
> `setgroups(0, NULL) is valid.`

For some reason, `setgroups(0, NULL)` causes *Doctest*, *Check if generated files are up to date*, and SSL workflows to fail child processes with `PermissionError: [Errno 1] Operation not permitted` exception:

<details><summary>Stacktrace</summary>

```plain
Run ./python Lib/test/ssltests.py
Traceback (most recent call last):
OpenSSL 1.1.1n  15 Mar 2022
  File "/home/runner/work/cpython/cpython/Lib/test/ssltests.py", line 37, in <module>
    run_regrtests(*sys.argv[1:])
  File "/home/runner/work/cpython/cpython/Lib/test/ssltests.py", line 33, in run_regrtests
    result = subprocess.call(args)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/subprocess.py", line 378, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/cpython/cpython/Lib/subprocess.py", line 1011, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/runner/work/cpython/cpython/Lib/subprocess.py", line 1888, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 1] Operation not permitted
Error: Process completed with exit code 1.
```

</details>

However, this is fixed by excluding a zero from the comparison: `if (groups_size > 0)`. I think we may leave it as is because `setgroups(0, NULL)` is a no-op in `child_exec` (a positive returned value is dropped anyway):

> If size is zero, list is not modified, but the total number of supplementary group IDs for the process is returned.
>
> -- https://linux.die.net/man/2/setgroups

*For Bedevere: I have made the requested changes; please review again. For correct jump from Mentioned to this message instead of the following Bedevere's one: @gpshead.*

2022-08-18 08:58 UTC, arhadthedev commented
@gpshead @tiran could you reconsider this PR please? This is a prerequirement for gh-94519, created to get rid of uninitialized variables.

2022-08-18 09:07 UTC, tiran commented
We are currently busy with 3.11 release. It may take until 3.11.0 final before we come back to this patch. It's definitely on the list for 3.12.

2022-10-06 03:35 UTC, arhadthedev commented
Todo: replace `groups_size`/`groups` parameter names with `extra_group_size`/`extra_groups` across the whole file to avoid confusion of passers-by. It's necessary to mitigate a misleading name of `setgroups` that supposes replacement of not supplimentary group affinities, but all ones. The mislead results in seeing the omission of `setgroups` call for `groups_size == 0` as a bug (like we should reset the inherited affinities but do nothing instead).

I'll do it in a separate PR because both this PR and gh-94519 are already big enough to clobber them with extra details.

2023-01-14 19:17 UTC, arhadthedev commented
@tiran could you review and possibly merge this PR please? It's an implementation of your proposal https://github.com/python/cpython/pull/94519#issuecomment-1174734993 created as a separate PR to preserve diffs of both PRs readable.

2023-01-14 20:08 UTC, gpshead approved these changes
thanks for doing this!

2023-01-14 20:11 UTC, merged

2023-01-15 04:59 UTC, arhadthedev commented
Thank you for merging, Gregory!