Improve dataclass docstring
python/cpython pull request #94686
Opened 2022-07-08 10:33 UTC by TomFryers

This fixes three trivial issues:
* The summary line was in the wrong tense.
* Assuming the underscores are not pronounced, 'an \_\_slots\_\_' should be 'a'. If they should be, then the earlier 'a \_\_hash\_\_' would be wrong.
* 'method function' is a bit of an odd phrase that seems unnecessary.

2022-07-08 10:35 UTC, TomFryers commented
> Most changes to Python [require a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
> 
> Please add it using the [blurb_it](https://blurb-it.herokuapp.com) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.

My guess is that this is too small for NEWS, but I'm happy to add it if necessary.

2022-07-08 15:28 UTC, ericvsmith commented on Lib/dataclasses.py
> +    """Return the same class as was passed in, with dunder methods added
It's actually no longer true that the same class is returned (in the case of `slots=True`). I'm not sure of the exact wording that should be used. Otherwise looks good.

2022-07-08 15:29 UTC, ericvsmith commented
> My guess is that this is too small for NEWS, but I'm happy to add it if necessary.

Agreed.

2022-07-09 00:22 UTC, ericvsmith commented on Lib/dataclasses.py
> +    """Return the same class as was passed in, with dunder methods added
Now that I think about it more, I think we should just drop "Return the same class as was passed in", and say "Add dunder methods based on ...".

2022-07-09 00:22 UTC, ericvsmith requested changes

2022-07-09 00:22 UTC, ericvsmith commented on Lib/dataclasses.py
> +    is added.
Here is where it should say that if slots is true, a new class is returned.

2022-07-09 10:10 UTC, TomFryers commented
I have made the requested changes; please review again.

2022-07-09 10:14 UTC, ericvsmith approved these changes
Thanks!

2022-07-09 10:15 UTC, ericvsmith commented
I will commit once @TomFryers has signed the CLA.

2022-07-09 18:26 UTC, merged