gh-94823: Improve coverage in tokenizer.c:valid_utf8
python/cpython pull request #94856
Opened 2022-07-14 15:34 UTC by mdboom

When loading a source file from disk, there is a separate UTF-8 validator
distinct from the one in `unicode_decode_utf8`. This exercises that code path
with the same set of invalid inputs as we use for testing the "other" UTF-8
decoder.

* Issue: gh-94823

Automerge-Triggered-By: GH:ericsnowcurrently

2022-08-12 19:34 UTC, ericsnowcurrently requested changes
Thanks for working on this!  It mostly looks good.  I noticed a couple of small typos.

2022-08-12 19:34 UTC, ericsnowcurrently commented on Lib/test/test_source_encoding.py
> +        # This is port of test_utf8_decode_invalid_sequences in test_unicode.py
```suggestion
        # This is a port of test_utf8_decode_invalid_sequences in test_unicode.py
```

2022-08-12 19:34 UTC, ericsnowcurrently commented on Lib/test/test_source_encoding.py
> +        # to exercise the separate utf8 validator in tokenize.c used when
Do you mean Parser/tokenizer.c?

2022-08-16 14:15 UTC, mdboom commented
I have made the requested changes; please review again

2022-08-16 15:53 UTC, ericsnowcurrently approved these changes
LGTM

2022-08-16 15:54 UTC, merged

2022-08-16 15:54 UTC, miss-islington commented
Thanks @mdboom for the PR 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2022-08-16 15:56 UTC, ericsnowcurrently commented
Thanks for the test!