GH-94857: fix test_io refleak
python/cpython pull request #94858
Opened 2022-07-14 16:42 UTC by kumaraditya303

2022-07-14 17:59 UTC, tiran requested changes
There are more possible refleaks in error paths. It would be better to incref ``encodings`` eagerly and ``decref`` it in error paths.

2022-07-14 18:12 UTC, serhiy-storchaka reviewed
There are still leaks in three `return` statements between lines 1260 and 1280.

2022-07-15 08:16 UTC, kumaraditya303 commented
I have made the requested changes; please review again

2022-07-15 08:24 UTC, tiran commented on Modules/_io/textio.c
>          if (_PyUnicode_EqualToASCIIString(encoding, "locale")) {
You have to ``Py_INCREF(encoding)`` when ``encoding != "locale"``.

2022-07-15 08:27 UTC, kumaraditya303 commented on Modules/_io/textio.c
>          if (_PyUnicode_EqualToASCIIString(encoding, "locale")) {
Good catch! done

2022-07-15 12:49 UTC, kumaraditya303 commented
PTAL @tiran Thanks!

2022-07-18 12:32 UTC, tiran approved these changes
Looks good to me, thanks!

2022-07-18 13:48 UTC, merged