gh-94808: Add coverage for boolobject.c:bool_new
python/cpython pull request #94859
Opened 2022-07-14 17:36 UTC by mdboom

`bool_new` had no coverage.

2022-07-14 21:34 UTC, brandtbucher requested changes

2022-07-14 21:34 UTC, brandtbucher commented on Lib/test/test_bool.py
> +        assert bool.__new__(bool, True) is True
```suggestion
        self.assertIs(bool.__new__(bool), False)
        self.assertIs(bool.__new__(bool, 1), True)
        self.assertIs(bool.__new__(bool, 0), False)
        self.assertIs(bool.__new__(bool, False), False)
        self.assertIs(bool.__new__(bool, True), True)
```

2022-07-14 23:12 UTC, mdboom commented
I have made the requested changes; please review again

2022-07-14 23:37 UTC, brandtbucher approved these changes

2022-07-14 23:53 UTC, miss-islington commented
Status check is done, and it's a success ✅ .

2022-07-14 23:53 UTC, merged

2022-07-15 16:44 UTC, miss-islington commented
Thanks @mdboom for the PR 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!