Raise TypeError in genrandbits method
python/cpython pull request #95000
Opened 2022-07-19 08:08 UTC by Akasurde

Raise TypeError when values other than integer are
supplied to genrandbits method.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

2022-07-19 16:47 UTC, graingert commented on Lib/random.py
> +            raise TypeError('number of bits must be integer')
I already get a TypeError when I call this:

```
>>> random.SystemRandom().getrandbits(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graingert/miniconda3/lib/python3.9/random.py", line 793, in getrandbits
    if k < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

2022-07-19 17:01 UTC, graingert commented on Lib/test/test_random.py
> +        self.assertRaises(TypeError, self.gen.getrandbits, 'test')
These tests already pass for me, without your changes - you should assert on the specific message

2022-07-19 17:02 UTC, graingert requested changes
Can you update the title of this PR so that it's clear you're changing the exception message and not the exception type

2022-07-21 00:04 UTC, closed without merging

2022-07-21 03:10 UTC, Akasurde commented
@rhettinger Thanks for the review and I felt the same after @graingert's review.