gh-95097: support custom tasks with missing uncancel methods
python/cpython pull request #95098
Opened 2022-07-21 17:11 UTC by graingert

2022-07-21 17:15 UTC, graingert commented on Lib/asyncio/tasks.py
> +                name="missing asyncioTask.set_name()",
```suggestion
                name="missing asyncio.Task.set_name()",
```

2022-07-21 17:16 UTC, graingert commented on Lib/asyncio/tasks.py
> +        warnings._deprecated("Task.uncancel() was added in Python 3.11, "
```suggestion
        warnings._deprecated(
            name="missing asyncio.Task.uncancel()",
            message="Task.uncancel() was added in Python 3.11, "
```

2022-07-21 17:16 UTC, graingert commented on Lib/asyncio/taskgroups.py
> +                if self._parent_cancel_requested and not tasks._uncancel(self._parent_task.uncancel):
```suggestion
                if self._parent_cancel_requested and tasks._uncancel(self._parent_task.uncancel) == 0:
```

2022-07-21 17:42 UTC, graingert commented on Lib/asyncio/tasks.py
>              set_name = task.set_name
If a task is missing set_name it's probably missing uncancel

2022-07-24 15:53 UTC, kumaraditya303 requested changes
Can you add a test with custom task factory ?

2022-07-29 16:26 UTC, kumaraditya303 commented
Closing as the issue was fixed by https://github.com/python/cpython/pull/95211

2022-07-29 16:26 UTC, closed without merging