GH-93899: fix checks for eventfd flags
python/cpython pull request #95170
Opened 2022-07-23 10:47 UTC by kumaraditya303

2022-07-24 10:04 UTC, erlend-aasland requested changes
LGTM, but `os_eventfd_impl` could also use a wrapper, and some of the tests should skip if these flags are not present.

2022-07-24 13:56 UTC, kumaraditya303 commented
> but os_eventfd_impl could also use a wrapper,

Added guard to `os.eventfd`.

> and some of the tests should skip if these flags are not present.

The test are already skipped on older kernel versions.

https://github.com/python/cpython/blob/3c94d3395edbcd299cbdacd09660ed88e654eeef/Lib/test/test_os.py#L3686-L3690

I have made the requested changes; please review again

2022-07-24 18:42 UTC, tiran requested changes
If you actually want to support ancient Kernels, then let's use consistent checks.

2022-07-24 18:42 UTC, tiran commented on Modules/posixmodule.c
> +#ifdef EFD_CLOEXEC
```suggestion
#if defined(HAVE_EVENTFD) && defined(EFD_CLOEXEC)
```

2022-07-24 18:42 UTC, tiran commented on Modules/posixmodule.c
> +#endif
```suggestion
```

2022-07-24 18:42 UTC, tiran commented on Modules/posixmodule.c
> +#endif
```suggestion
#endif  /* HAVE_EVENTFD && EFD_CLOEXEC */
```

2022-07-25 07:41 UTC, erlend-aasland approved these changes
LGTM. You may consider to make the NEWS entry a little bit more specific ("older kernel versions" is a bit vague).

2022-07-27 12:27 UTC, kumaraditya303 commented
> LGTM. You may consider to make the NEWS entry a little bit more specific ("older kernel versions" is a bit vague).

Thanks for the review! I have reworded news entry, should be better now!

2022-07-27 12:45 UTC, erlend-aasland commented
Thanks, I'm fine with that. I'll land it as soon as the CI is green. Thanks!

2022-07-27 13:05 UTC, tiran approved these changes

2022-07-27 13:05 UTC, merged

2022-07-27 13:05 UTC, miss-islington commented
Thanks @kumaraditya303 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖 I'm not a witch! I'm not a witch!

2022-07-27 13:05 UTC, miss-islington commented
Sorry, @kumaraditya303, I could not cleanly backport this to `3.11` due to a conflict. 
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 4dd099bafff14639ef5d2185965016d8f253353f 3.11
                                ```

2022-07-27 13:05 UTC, miss-islington commented
Sorry @kumaraditya303, I had trouble checking out the `3.10` backport branch.
                                Please backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on command line.
                                ```
                                cherry_picker 4dd099bafff14639ef5d2185965016d8f253353f 3.10
                                ```

2022-07-27 13:15 UTC, erlend-aasland commented
Will you fix the backports, Kumar? It's probably just a clinic regen that's missing. (Can we teach Miss I to do that?)

2022-07-27 18:16 UTC, kumaraditya303 commented
> Will you fix the backports, Kumar?

Done