gh-95371: Add support for other image formats(e.g. PNG) to the turtle…
python/cpython pull request #95378
Opened 2022-07-28 12:27 UTC by relent95

- *Shape.__init__()*
 The existing buggy code calling class method *TurtleScreen._image()* was removed.(It has never been reached via *turtle.register_shape()*)

- *TurtleScreen.register_shape()*
  The existing redundant code checking the filename extension was removed because the backend *tkinter.PhotoImage* does that.
  A new pattern for arguments, such as *register_shape("turtle", "turtle.gif")* was added to be consistent with cases for polygon shapes.(It will be useful when the filename is quite long, as in case of using a full path.)

- *TurtleScreen.bgpic()*
  This already supports other image formats. So only the documentation was changed.

2022-07-29 11:49 UTC, hugovk reviewed
Some little spacing nits.

Also, any particular reason to list them in order PGM, PPM, GIF, and PNG?

I'd either put them in some sort of order of "popularity/ease of use" (e.g. "PNG, GIF, PGM, and PPM") or alphabetically ("GIF,PGM, PNG, and PPM").

2022-07-29 11:49 UTC, hugovk commented on Doc/library/turtle.rst
> +   (2) *name* is an arbitrary string and *shape* is the name of an image file(PGM, PPM, GIF, and PNG): Install the
```suggestion
   (2) *name* is an arbitrary string and *shape* is the name of an image file (PGM, PPM, GIF, and PNG): Install the
```

2022-07-29 11:49 UTC, hugovk commented on Lib/turtle.py
> +        picname -- a string, name of an image file(PGM, PPM, GIF, and PNG) or "nopic".
```suggestion
        picname -- a string, name of an image file (PGM, PPM, GIF, and PNG) or "nopic".
```

2022-07-29 11:49 UTC, hugovk commented on Misc/NEWS.d/next/Library/2022-07-28-12-32-59.gh-issue-95371.F24IFC.rst
> +Added support for other image formats(e.g. PNG) to the turtle module. Patch by Shin-myoung-serp.
```suggestion
Added support for other image formats (e.g. PNG) to the turtle module. Patch by Shin-myoung-serp.
```

2022-07-29 11:49 UTC, hugovk commented on Doc/library/turtle.rst
> +   :param picname: a string, name of an image file(PGM, PPM, GIF, and PNG) or ``"nopic"``, or ``None``
```suggestion
   :param picname: a string, name of an image file (PGM, PPM, GIF, and PNG) or ``"nopic"``, or ``None``
```

2022-07-29 11:51 UTC, hugovk commented on Lib/turtle.py
> +        (1) name is the name of an image file(PGM, PPM, GIF, and PNG) and shape is None.
```suggestion
        (1) name is the name of an image file (PGM, PPM, GIF, and PNG) and shape is None.
```

2022-07-29 11:51 UTC, hugovk commented on Lib/turtle.py
> +        (2) name is an arbitrary string and shape is the name of an image file(PGM, PPM, GIF, and PNG).
```suggestion
        (2) name is an arbitrary string and shape is the name of an image file (PGM, PPM, GIF, and PNG).
```

2022-08-01 01:38 UTC, relent95 commented
1. Spaces were added as you suggested.
2. The list of supported formats were taken from the existing tkinter documentation(https://docs.python.org/3/library/tkinter.html). But I like your idea to list popular formats first and I did that.

2023-02-03 08:38 UTC, arhadthedev commented
Merging `main` into this PR to check if https://github.com/python/cpython/issues/95371#issuecomment-1415347596 is necessary:

> [...] Because its base version is quite old, I can prepare a new PR if it's required.

2023-02-06 16:21 UTC, hugovk requested changes
Please could you add some `versionchanged` or `versionadded` to document the changes/additions at the end of each function?

The next version will be 3.12.

Docs: https://devguide.python.org/documentation/markup/#paragraph-level-markup

2024-12-07 12:59 UTC, adorilson commented
@relent95 Will you finish this?

2024-12-14 10:16 UTC, hugovk commented
@adorilson Would you like to continue this in a new PR?

2024-12-21 14:53 UTC, adorilson commented
> @adorilson Would you like to continue this in a new PR?

Yes, I would. In fact, it is the idea.
I just wanted to ping the @relent95 before and while I finish other tasks (aka finishing other PRs).

However, if someone want to do this, go ahead.

2024-12-21 22:36 UTC, hugovk commented
@adorilson Yeah, the OP hasn't been active on GitHub for a long time, but thanks for giving them a ping. Please go ahead whenever you're ready :)

2024-12-28 10:22 UTC, relent95 commented
@adorilson @hugovk I'll continue this work. Sorry for being too late. I updated the document by adding the versionchanged information. Can you review the change?

2024-12-28 16:37 UTC, adorilson commented
> @adorilson @hugovk I'll continue this work. Sorry for being too late. I updated the document by adding the versionchanged information. Can you review the change?

Great news, @relent95 .

Now, the recommendation is that you use `I have made the requested changes; please review again` to the @bedevere-bot to do his work.

2024-12-29 14:16 UTC, hugovk reviewed
Thanks, nearly there :)

2024-12-29 14:16 UTC, hugovk commented on Doc/library/turtle.rst
> +      Both a shape name and an image file name can be specified.(Second case)
```suggestion
      Added support for PNG, PGM, and PPM image formats.
      Both a shape name and an image file name can be specified.
```

2024-12-29 14:16 UTC, hugovk commented on Misc/NEWS.d/next/Library/2022-07-28-12-32-59.gh-issue-95371.F24IFC.rst
> +Added support for other image formats (e.g. PNG) to the turtle module. Patch by Shin-myoung-serp.
```suggestion
Added support for other image formats (PNG, PGM, and PPM) to the turtle module. Patch by Shin-myoung-serp.
```

2024-12-29 14:16 UTC, hugovk commented on Doc/library/turtle.rst
> +
We don't need to document that the docs have been updated.
```suggestion
```

2024-12-29 14:16 UTC, hugovk commented on Doc/library/turtle.rst
> +   :param picname: a string, name of an image file (PNG, GIF, PGM, and PPM) or ``"nopic"``, or ``None``
Wrap long line:
```suggestion
   :param picname: a string, name of an image file (PNG, GIF, PGM, and PPM)
   or ``"nopic"``, or ``None``
```

2024-12-30 01:53 UTC, relent95 commented
@bedevere-bot I have made the requested changes; please review again.

2024-12-30 18:39 UTC, hugovk commented on Doc/library/turtle.rst
> +   or ``"nopic"``, or ``None``
Sorry, I got the indentation wrong here. Let's try:
```suggestion
                   or ``"nopic"``, or ``None``
```

2024-12-31 06:42 UTC, relent95 commented
@bedevere-bot I have made the requested changes; please review again.

2025-01-02 09:39 UTC, hugovk approved these changes
Thank you!

2025-01-02 09:45 UTC, merged