Trivial change: Misleading zip64 limit error message
python/cpython pull request #95892
Opened 2022-08-11 14:14 UTC by dmjohnsson23

This error message is confusing as it seems to indicate that the file is already using zip64. This new message makes it more clear what the problem is, and will help guide developers to find the solution. (That is, to use in `ZipFile.open(force_zip64=True`))

2022-08-11 14:19 UTC, dmjohnsson23 commented
Trying to sign the CLA results in an internal server error for me. However, I have read and agree.

2022-11-27 07:04 UTC, kumaraditya303 requested changes
There are merge conflicts.

2022-11-28 22:46 UTC, dmjohnsson23 commented
I have made the requested changes; please review again

2022-11-29 21:12 UTC, gpshead approved these changes

2022-11-30 11:13 UTC, kumaraditya303 approved these changes

2022-11-30 11:14 UTC, merged