Docs: Fix asyncio-task.rst
python/cpython pull request #96307
Opened 2022-08-26 12:04 UTC by zhanpon

A trivial fix. I believe this doesn't require an issue.

2022-08-26 12:12 UTC, AlexWaygood approved these changes

2022-08-27 01:50 UTC, gvanrossum requested changes
I recommend we stop counting and instead just say “the following”.

Also, Spanish Inquisition reference. :-)

2022-08-27 03:38 UTC, zhanpon commented
Thanks for the reviews!

I have made the requested changes; please review again

2022-08-27 03:50 UTC, gvanrossum approved these changes
Yup!

2022-08-27 03:50 UTC, merged

2022-08-27 03:50 UTC, miss-islington commented
Thanks @zhanpon for the PR, and @gvanrossum for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖