bpo-34843: Remove recent from logging cookbook
python/cpython pull request #9636
Opened 2018-09-29 13:30 UTC by csabella

Remove the word 'recent' when referring to multiprocessing in the logging cookbook.

2018-10-01 03:39 UTC, rhettinger requested changes
Please only change the "If you are using a recent version of Python" part. 

Also, for doc changes, it is helpful to not rewrap the paragraphs. That helps reviewers see what changed and what didn't.

For module internal class references, we tend to use the full qualifier in only a handful of cases.  The problem is that the full markup generates many unnecessary links to the same targets.  This makes the text harder to read and less usable.

2018-10-01 09:58 UTC, csabella commented
I have made the requested changes; please review again.

Sorry about making the extra changes to the links.  It had looked like they had been originally intended to be links, but had broken at some point, which led me to try to fix them.

2018-10-02 02:35 UTC, asottile approved these changes

2018-10-02 06:58 UTC, rhettinger approved these changes

2018-10-02 16:19 UTC, rhettinger commented
Close and reopen to retrigger the Appveyor bot which was stuck for some reason.

2018-10-02 16:35 UTC, merged