[3.5] bpo-19225: Lack of c api exceptions doc
python/cpython pull request #965
Opened 2017-04-02 23:42 UTC by cocoatomo

backports to 3.5 for #881

2017-04-03 09:51 UTC, cocoatomo commented
Related Sphinx bug report: https://github.com/sphinx-doc/sphinx/issues/3598

2017-04-03 16:26 UTC, serhiy-storchaka requested changes

2017-04-03 16:26 UTC, serhiy-storchaka commented on Doc/c-api/exceptions.rst
> +   single: PyExc_ModuleNotFoundError
New in 3.6.

2017-04-03 22:48 UTC, cocoatomo commented on Doc/c-api/exceptions.rst
> +   single: PyExc_ModuleNotFoundError
Thanks!

2017-04-06 13:56 UTC, cocoatomo commented
@serhiy-storchaka Is there additional work needed?

2017-04-06 13:58 UTC, serhiy-storchaka approved these changes

2017-04-06 14:00 UTC, merged

2017-04-06 14:01 UTC, serhiy-storchaka commented
All LGTM. Thanks.