gh-94808: Add test coverage for HasAttrString
python/cpython pull request #96627
Opened 2022-09-06 22:57 UTC by MonadChains

Add test to cover the function `HasAttrString` of the C API.

2022-09-07 12:37 UTC, mdboom requested changes
Thanks so much for the contribution.  It looks great other than a few minor comments.

2022-09-07 12:37 UTC, mdboom commented on Modules/_testcapimodule.c
> +}
Sorry for the nit, but I don't think there's automatic tooling to check this.  Can you reformat this to comply with [PEP7](https://peps.python.org/pep-0007/).

2022-09-07 12:37 UTC, mdboom commented on Lib/test/test_class.py
> +        self.assertEqual(_testcapi.hasattr_string(a, "noattr"), False)
It might also be worth asserting that there's no exception set in this case:

```
self.assertEqual(sys.exc_info(), (None, None, None))
```

2022-09-11 15:53 UTC, mdboom approved these changes
LGTM

2022-10-03 20:37 UTC, orsenthil approved these changes
LGTM.

2022-10-03 20:37 UTC, merged