gh-64373: Convert `_functools` to Argument Clinic
python/cpython pull request #96640
Opened 2022-09-07 10:11 UTC by sobolevn

A couple of extra notes:
- `functools.reduce` is not converted, because its `args` parsing / in-place mutation is optimized
- `partial_new` and `partial_call` require `*args, **kwargs`, as far as I know AC does not support that at the moment, they are not converted
- The same for `_lru_cache_wrapper.__call__`
- I've also noticed a couple of other oddities that I will report in two separate issue later

2022-09-07 10:22 UTC, sobolevn commented
Now, let's compare `help()` before and after!

## cmp_to_key

Before:

```python
>>> help(_functools.cmp_to_key)
Help on built-in function cmp_to_key in module _functools:

cmp_to_key(...)
    Convert a cmp= function into a key= function.
```

After:

```python
>>> help(_functools.cmp_to_key)
Help on built-in function cmp_to_key in module _functools:

cmp_to_key(mycmp)
    Convert a cmp= function into a key= function.

    mycmp
      Function that compares two objects.
```

## _lru_cache_wrapper

Before:

```python
>>> help(_functools._lru_cache_wrapper)
Help on class _lru_cache_wrapper in module functools:

class _lru_cache_wrapper(builtins.object)
 |  Create a cached callable that wraps another function.
 |
 |  user_function:      the function being cached
 |
 |  maxsize:  0         for no caching
 |            None      for unlimited cache size
 |            n         for a bounded cache
 |
 |  typed:    False     cache f(3) and f(3.0) as identical calls
 |            True      cache f(3) and f(3.0) as distinct calls
 |
 |  cache_info_type:    namedtuple class with the fields:
 |                          hits misses currsize maxsize
 |
 |  Methods defined here:
```

After:

```python
>>> help(_functools._lru_cache_wrapper)
Help on class _lru_cache_wrapper in module functools:

class _lru_cache_wrapper(builtins.object)
 |  _lru_cache_wrapper(user_function, maxsize, typed, cache_info_type)
 |
 |  Create a cached callable that wraps another function.
 |
 |  user_function
 |    the function being cached
 |  maxsize
 |    0         for no caching
 |    None      for unlimited cache size
 |    n         for a bounded cache
 |  typed
 |    False     cache f(3) and f(3.0) as identical calls
 |    True      cache f(3) and f(3.0) as distinct calls
 |  cache_info_type
 |    namedtuple class with the fields:
 |    hits misses currsize maxsize
 |
 |  Methods defined here:
```

### `.cache_clear` and `.cache_info`

Before:

```python
>>> help(_functools._lru_cache_wrapper.cache_clear)
Help on method_descriptor:

cache_clear(...)

>>> help(_functools._lru_cache_wrapper.cache_info)
Help on method_descriptor:

cache_info(...)
```

After:

```python
>>> help(_functools._lru_cache_wrapper.cache_clear)
Help on method_descriptor:

cache_clear(self, /)
    Clear the cache and cache statistics

>>> help(_functools._lru_cache_wrapper.cache_info)
Help on method_descriptor:

cache_info(self, /)
    Report cache statistics
```

2022-09-07 20:06 UTC, rhettinger commented
We generally only apply argclinic to functions directly visible to the user. Otherwise, it is mostly pointless since no one sees the signature.   So, I would leave the lru cache internals alone -- iirc, we had an issue for this previously.  The `cmp_to_key` part can stay.

2022-09-07 20:39 UTC, sobolevn commented
Thank you for the insight! This is my first clinic-related PR.

I will remove things like `__copy__` and other internals tomorrow 👍 

> to functions directly visible to the user
> I would leave the lru cache internals alone

I think that `.clear_cache` and `.cache_info` are user-facing functions, aren't they?

2022-09-09 03:20 UTC, rhettinger requested changes

2022-09-09 03:20 UTC, rhettinger commented on Modules/_functoolsmodule.c
> +    state = get_functools_state(module);
Duplicated line.

2022-09-12 08:50 UTC, sobolevn commented
I have made the requested changes; please review again

2022-10-07 17:36 UTC, merged