Update README.rst
python/cpython pull request #9673
Opened 2018-10-02 07:15 UTC by ayush1208

2018-10-02 07:15 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-11-01 20:25 UTC, davidak requested changes

2018-11-01 20:25 UTC, davidak commented on README.rst
> +Python is an interpreted high-level programming language for general-purpose programming.It is one of the easiest and simplest languages to learn and is currently in popular demand.
```suggestion
Python is an interpreted high-level programming language for general-purpose programming. It is one of the easiest and simplest languages to learn and is currently in popular demand.
```

2019-03-28 20:31 UTC, brettcannon commented
Thanks for the PR, but closing as the CLA has not been signed within the last month. If you do decide to sign the CLA we can re-open this PR.

2019-03-28 20:31 UTC, closed without merging