gh-71141: Add note on rejecting "leading-dot" syntax for with statements
python/cpython pull request #96928
Opened 2022-09-19 08:15 UTC by slateny

2022-09-19 21:45 UTC, DanielNoord requested changes

2022-09-19 21:45 UTC, DanielNoord commented on Doc/faq/design.rst
> +such as using a 'leading dot', are rejected in favour of explicitness (see
```suggestion
such as using a 'leading dot', have been rejected in favour of explicitness (see
```

2022-09-20 06:41 UTC, DanielNoord approved these changes

2022-09-21 04:16 UTC, gvanrossum approved these changes

2022-09-21 04:16 UTC, merged