gh-87092: in compiler, move the detection of exception handlers before  the CFG optimization stage
python/cpython pull request #96935
Opened 2022-09-19 14:04 UTC by iritkatriel

2022-09-19 16:30 UTC, hauntsaninja commented on Python/compile.c
>      /* Number of predecssors that a block has. */
(unrelated typo)
```suggestion
    /* Number of predecessors that a block has. */
```

2022-09-19 17:08 UTC, markshannon requested changes
One minor issue, otherwise LGTM.

2022-09-19 17:08 UTC, markshannon commented on Python/compile.c
> +    for (basicblock *b = entryblock; b != NULL; b = b->b_next) {
This gets evaluated in non debug mode. Maybe wrap in `#ifndef NDEBUG`?

2022-09-20 09:48 UTC, iritkatriel commented
I have made the requested changes; please review again.

2022-09-20 12:14 UTC, merged