Added support for secure websocket cookies
python/cpython pull request #9734
Opened 2018-10-05 23:44 UTC by pizzapanther

# Added support for secure websocket cookies

bpo-34911: Added support for secure websocket cookies

2018-10-05 23:44 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-10-06 06:26 UTC, asvetlov requested changes
Please add a test

2018-10-07 06:18 UTC, asvetlov requested changes
Cool!

Next two steps are left.
1. Update docs please. You've added a new argument to `DefaultCookiePolicy` constructor, it should be at least mentioned here: https://docs.python.org/3/library/http.cookiejar.html#http.cookiejar.DefaultCookiePolicy
2. Please add a NEWS fragment. Use [blurb](https://pypi.org/project/blurb/) for it.

2018-10-08 16:55 UTC, asvetlov approved these changes

2018-10-08 16:58 UTC, asvetlov commented
Please sign the CLA as the bot suggested in the very beginning of the conversation.

2018-10-08 18:20 UTC, pizzapanther commented
@asvetlov 
![screenshot 2018-10-08 at 1 19 25 pm](https://user-images.githubusercontent.com/552478/46626410-e3f73b00-cafc-11e8-9584-79202b022ae4.png)

2018-10-08 18:49 UTC, merged

2018-10-08 18:49 UTC, asvetlov commented
Thanks!

2018-10-12 14:21 UTC, pizzapanther commented
will this go into python 3.7 or 3.8?

2018-10-13 07:41 UTC, asvetlov commented
3.8 only: it is a new functionality