GH-97592: Fix crash in C remove_done_callback due to evil code
python/cpython pull request #97660
Opened 2022-09-29 23:10 UTC by gvanrossum

2022-09-29 23:24 UTC, gvanrossum commented
@xiaxinmeng Feel free to add your review.

2022-09-30 03:17 UTC, JelleZijlstra approved these changes

2022-09-30 03:25 UTC, kumaraditya303 commented on Misc/NEWS.d/next/Library/2022-09-29-23-22-24.gh-issue-97592.tpJg_J.rst
> +Avoid a crash in the C version of `asyncio.Future.remove_done_callback()` when an evil argument is passed.
```suggestion
Avoid a crash in the C version of :meth:`asyncio.Future.remove_done_callback` when an evil argument is passed.
```

2022-09-30 03:26 UTC, kumaraditya303 approved these changes
LGTM

2022-09-30 03:39 UTC, CharlieZhao95 requested changes

2022-09-30 03:39 UTC, CharlieZhao95 commented on Lib/test/test_asyncio/test_futures.py
> +        fut.remove_done_callback(evil())
> Class names should normally use the CapWords convention.

```suggestion
        class Evil:
            def __eq__(self, other):
                fut.remove_done_callback(other)

        fut.remove_done_callback(Evil())
```
```

2022-09-30 03:39 UTC, CharlieZhao95 commented on Lib/test/test_asyncio/test_futures.py
> +        fut.remove_done_callback(evil())
All callbacks added by `fut.add_done_callback()` will be cleared when calling `fut.remove_done_callback(Evil())`, but the return value will be the number of callbacks added last.

I'm not sure if we need to improve the return value of `remove done callback` further, the current changes are good enough to fix the crash. :)

2022-09-30 19:57 UTC, merged

2022-09-30 19:57 UTC, miss-islington commented
Thanks @gvanrossum for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖