gh-95756: Lazily created cached co_* attrs
python/cpython pull request #97791
Opened 2022-10-03 20:31 UTC by Fidget-Spinner

2022-10-03 20:40 UTC, Fidget-Spinner commented
Note that these were all O(1) in 3.10. This restores their behavior. 
https://github.com/python/cpython/blame/08eb754d840696914928355014c2d424131f8835/Objects/codeobject.c

2022-10-03 21:44 UTC, markshannon commented
I'd like to reduce the size of code objects for a few reasons. PEP 649 will create lots of small code objects and we want multiple interpreters to share as much data as possible.

2022-10-07 01:10 UTC, markshannon requested changes

2022-10-07 01:10 UTC, markshannon commented on Doc/c-api/code.rst
> -   Returns a new reference to a :c:type:`PyTupleObject` containing the names of
I think the original form "new reference" is clearer than "strong reference".

2022-10-07 01:10 UTC, markshannon commented on Doc/c-api/code.rst
> -   Returns a new reference to a :c:type:`PyTupleObject` containing the names of
ditto

2022-10-07 01:10 UTC, markshannon commented on Doc/c-api/code.rst
> -   Returns a new reference to a :c:type:`PyTupleObject` containing the names of
ditto

2022-10-07 01:10 UTC, markshannon commented on Objects/codeobject.c
> +            return 1;
Conventionally `-1` for failure.

2022-10-07 01:10 UTC, markshannon commented on Objects/codeobject.c
> +    if (co->_co_cached->_co_varnames != NULL) {
You can factor the body of these functions out. `get_cached_locals()` which takes the code object, the flag, and a pointer to the field to be set.

2022-10-10 14:40 UTC, markshannon commented on Objects/codeobject.c
> +    assert(*cached_field == NULL);
No need to assert this. The test two lines above ensures that it is true.

2022-10-10 14:43 UTC, markshannon approved these changes
One assert that could be removed, but it's harmless.

2022-10-11 03:25 UTC, Fidget-Spinner commented
I'll leave the assert in since it communicates some info should the code change in the future. And like you mentioned it's harmless anyways.

2022-10-11 03:26 UTC, merged

2022-10-11 05:15 UTC, Fidget-Spinner commented
I'm confused. Why is this the only buildbot failing? In any case I will revert this within 24 hours.

2022-10-11 07:37 UTC, vstinner commented
> I'm confused. Why is this the only buildbot failing? In any case I might revert this within 24 hours.

I created https://github.com/python/cpython/issues/98178 about this crash. It seems to be specific to macOS and unrelated to your change. If your change would introduce a bug, more tests would crash on more platforms.