Convert remaining importlib format uses to f-str.
python/cpython pull request #98005
Opened 2022-10-07 00:22 UTC by gpshead

Converts the remaining importlib `str.format()` uses to f-strings.

2022-10-07 00:41 UTC, gpshead commented on Lib/importlib/__init__.py
> +            raise ValueError('{name}.__loader__ is None')
I need to add the `f` :)

2022-10-07 00:42 UTC, ericvsmith requested changes
Other than the one error, looks okay to me.

2022-10-07 00:42 UTC, ericvsmith commented on Lib/importlib/__init__.py
> +            raise ValueError('{name}.__loader__ is None')
Missing an "f" prefix.

2022-10-07 00:45 UTC, ericvsmith approved these changes

2022-10-07 00:47 UTC, brettcannon approved these changes

2022-10-07 01:27 UTC, merged

2022-12-29 20:56 UTC, jaraco commented
I cherry-picked this to python/importlib_resources@222aaed5.