bpo-29974: typing.TYPE_CHECKING doc example is incorrect
python/cpython pull request #982
Opened 2017-04-03 17:33 UTC by Mortal

The documentation of typing.TYPE_CHECKING has an example (introduced in issue #26141) that would lead to NameError at runtime. The example shows how to limit the import of "expensive_mod" to type checkers, but then goes on to use "expensive_mod.some_type" in a type annotation that is evaluated at runtime ("local_var: expensive_mod.some_type"). The use case of TYPE_CHECKING is probably meant for type annotations placed in comments, e.g. "local_var  # type: expensive_mod.some_type".

2017-04-03 17:33 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-04-04 01:38 UTC, berkerpeksag approved these changes
Looks good to me, but I'm not really a typing guru so I'm just pinging the author of the original commit. @ilevkivskyi could you confirm that the proposed patch is correct?

2017-04-04 07:10 UTC, ilevkivskyi commented
The original example is correct, annotations for local variables (i.e. in function scope) are not evaluated at runtime. The motivation for this was to reduce the possible runtime overhead of using annotations, but it also helps with forward references/import cycles.

I think this example should stay. Maybe we could extend it with a function parameter annotation, to show that types should be string literals in the places where they are actually evaluated. For example something like this:
```python
if TYPE_CHECKING:
    import expensive_mod
 
def fun(arg: 'expensive_mod.some_type') -> None:
    local_var: expensive_mod.another_type = other_fun()
```

2017-04-04 07:14 UTC, ilevkivskyi commented
Also it is probably worth fixing PEP 8 here and use ``SomeType`` instead of ``some_type``.

2017-04-04 11:56 UTC, Mortal commented
@ilevkivskyi Thanks for the explanation -- I did not know that type annotations on local variables in function scope are not evaluated. I had naively tested with a type annotation on a variable in module-scope. (I guess it makes sense to ensure that a type annotation is evaluated at most once.)

I will update the patch with @ilevkivskyi's proposed changes.

2017-04-04 12:16 UTC, Mortal commented
@berkerpeksag It seems GitHub thinks your approval of the old patch still applies even though I've rewritten *the entire* patch. Is my addition of a short recap of PEP 484/526 OK?

2017-04-08 16:03 UTC, berkerpeksag requested changes

2017-04-08 16:03 UTC, berkerpeksag commented on Doc/library/typing.rst
> +   (Note that the first type annotation must be enclosed in quotes, making it a
Nitpick: Parentheses are not needed.

2017-04-08 16:03 UTC, berkerpeksag commented on Doc/library/typing.rst
> +   interpreter runtime. Type annotations for local variables are not evaluated,
Please add two spaces after a full stop. See http://cpython-devguide.readthedocs.io/documenting.html#use-of-whitespace for details.

2017-04-10 22:58 UTC, Mariatta commented
Please keep the issue number in the PR description. I added `bpo-29974:` back to the PR title.

2017-04-20 17:23 UTC, Mortal commented
I've updated the docs according to review from @berkerpeksag.

Sorry about removing the issue number in the PR title.

2017-04-20 22:22 UTC, ilevkivskyi commented on Doc/library/typing.rst
> +   "forward reference", to hide the expensive_mod reference from the
I would propose to use back-quotes for expensive_mod here. Like this:
```
``expensive_mod``
```
Otherwise LGTM.

2017-04-20 22:47 UTC, Mortal commented
Good catch about using backquotes. I've updated according to review from @ilevkivskyi and squashed to a single commit.

2017-04-20 22:59 UTC, ilevkivskyi approved these changes

2017-04-26 10:48 UTC, berkerpeksag approved these changes

2017-04-26 10:49 UTC, merged

2017-04-26 10:50 UTC, berkerpeksag commented
Thanks!