gh-81611: Improve `range` paragraph in 8.3 of language reference
python/cpython pull request #98353
Opened 2022-10-17 11:47 UTC by x41lakazam

#gh-81611: Improve `range` paragraph in 8.3 of language reference docs

Remove comparison to Pascal language
Fix 'built-in function' appellation of the range type
Improve range definition

2023-01-01 21:20 UTC, terryjreedy requested changes

2023-01-01 21:20 UTC, terryjreedy commented on Doc/reference/compound_stmts.rst
> +to a specified number; e.g., ``list(range(3))`` returns the list ``[0, 1, 2]``.
Yes, dump the Pascal reference.  I suggest an even better replacement.
```suggestion
the built-in type :func:`range` represents immutable arithmetic sequences of integers.  For instance, iterating ``range(3)`` successively yields 0, 1, and then 2.
```
Types represent the concept that covers all possible instances, not any one instance.  In the context of looping, the iteration behavior of ranges is relevant, not what the list constructor does with one.

2023-01-03 07:26 UTC, kumaraditya303 commented on Doc/reference/compound_stmts.rst
> +the built-in type :func:`range` represents immutable arithmetic sequences of integers.  For instance, iterating ``range(3)`` successively yields 0, 1, and then 2.
```suggestion
the built-in type :func:`range` represents immutable arithmetic sequences of integers.
For instance, iterating ``range(3)`` successively yields 0, 1, and then 2.
```

2023-01-03 07:29 UTC, kumaraditya303 approved these changes

2023-01-03 08:16 UTC, merged

2023-01-03 08:16 UTC, miss-islington commented
Thanks @x41lakazam for the PR, and @kumaraditya303 for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖