gh-98415: Fix UUID ifconfig MAC address detection
python/cpython pull request #98423
Opened 2022-10-19 00:55 UTC by csanders-git

See #98415 for explanation

2022-10-22 10:16 UTC, corona10 requested changes
Nice catch!

I reproduce the issue with the following script:


````python

import subprocess
"""Get the hardware address on Unix by running ifconfig."""
# This works on Linux ('' or '-a'), Tru64 ('-av'), but not all Unixes.

def foo(*args):
    command = ("/sbin/ifconfig",) + args
    proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    if not proc:
        return
    stdout, stderr = proc.communicate()
    mac = stdout # This is fine for this example (normally it'd have parsed out a mac
    if not mac:
        print(args, mac, stderr)


for args in ('', '-a', '-av'):
    foo(args)

````

2022-10-22 10:16 UTC, corona10 commented on Lib/uuid.py
> +        proc = subprocess.Popen(command,
```suggestion
        # Empty strings will be quoted by popen so we should just ommit it
        command = (executable,)
        if args != ('',):
            command = (executable,) + args
        proc = subprocess.Popen(command,
```

2022-10-22 10:21 UTC, corona10 commented on Misc/NEWS.d/next/Core and Builtins/2022-10-19-01-01-08.gh-issue-98415.ZS2eWh.rst
> +Fix detection of MAC addresses for UUID on certain OSs . Patch by Chaim Sanders
```suggestion
Fix detection of MAC addresses for UUID on certain OSs. Patch by Chaim Sanders
```

2022-10-31 12:00 UTC, corona10 commented on Lib/uuid.py
> +            command = (executable,) + args
```suggestion
        # Empty strings will be quoted by popen so we should just ommit it
        if args != ('',):
            command = (executable,) + args
        else:
            command = (executable,)
```

2022-10-31 12:08 UTC, vstinner commented
I have a preference for ``(executable, *args)`` syntax when building command line arguments :-) IMO it's more readable.

2022-10-31 12:09 UTC, vstinner reviewed
Would it be possible to write an unit test with unittest.mock to check that subprocess is not called with an empty string argument?

2022-11-02 14:57 UTC, corona10 commented on Lib/uuid.py
> +            command = (executable,) + args
```suggestion
            command = (executable, *args)
```

2022-11-02 14:59 UTC, corona10 commented
> Would it be possible to write an unit test with unittest.mock to check that subprocess is not called with an empty string argument?

It looks hard to write the unittest due to system-specific implementation.
I would like to skip the writing test code at this moment,

2022-11-02 18:41 UTC, merged

2022-11-02 18:41 UTC, miss-islington commented
Thanks @csanders-git for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖

2022-11-02 18:41 UTC, miss-islington commented
Sorry @csanders-git and @vstinner, I had trouble checking out the `3.11` backport branch.
                                Please retry by removing and re-adding the "needs backport to 3.11" label.
                                Alternatively, you can backport using [cherry_picker](https://pypi.org/project/cherry-picker/) on the command line.
                                ```
                                cherry_picker e3ec272f57c3948834a6159cf2604978d3db67a0 3.11
                                ```

2022-11-02 18:42 UTC, miss-islington commented
Thanks @csanders-git for the PR, and @vstinner for merging it 🌮🎉.. I'm working now to backport this PR to: 3.11.
🐍🍒⛏🤖

2022-11-02 18:45 UTC, vstinner commented
Ok, thanks @csanders-git for the fix: I merged it. I rewrote the commit message to clarify its scope.

2022-11-02 18:46 UTC, vstinner commented
@corona10:
> It looks hard to write the unittest due to system-specific implementation.
> I would like to skip the writing test code at this moment,

It makes me sad, but I'm fine with not adding a test :-)

2022-11-02 18:47 UTC, vstinner commented
In the past, I fixed a risk of shell injection by avoiding a shell in the uuid module: commit b9d0199c073fc963b27106f4b7752dcbe39bfed3. I didn't add any test for that neither :-(