bpo-31522: mailbox: pass `from_` parameter to `get_bytes`
python/cpython pull request #9857
Opened 2018-10-13 23:13 UTC by csabella

Added tests that failed before the change and pass after the change.

2018-10-16 19:39 UTC, bitdancer requested changes

2018-10-16 19:39 UTC, bitdancer commented on Misc/NEWS.d/next/Library/2018-10-13-18-16-20.bpo-31522.rWBb43.rst
> +In `mailbox._mboxMMDF.get_string`, pass *from_* parameter to ``get_bytes``.
This describes what was done, but the changelog should in general describe the externally visible affects of the change.  In this case, I would write "The mailbox mbox get_string function `from_` parameter can now successfully be set to a non-default value".

2018-10-16 22:25 UTC, csabella commented on Misc/NEWS.d/next/Library/2018-10-13-18-16-20.bpo-31522.rWBb43.rst
> +In `mailbox._mboxMMDF.get_string`, pass *from_* parameter to ``get_bytes``.
Thanks for the suggestion!  :-)

2018-10-19 00:19 UTC, bitdancer approved these changes

2018-10-19 00:21 UTC, merged