gh-98586: expose more of the PEP-590 vector call API
python/cpython pull request #98587
Opened 2022-10-24 08:33 UTC by wjakob

This PR constains tentative changes needed to expose the facilities for making PEP-590-style vector calls through Python's limited API.

2022-10-24 10:51 UTC, erlend-aasland commented
@markshannon might be interested in reviewing this as the author of PEP 590.

2022-10-24 11:49 UTC, erlend-aasland reviewed
Could you add tests to `Modules/_testcapimodule/vectorcall_limited.c` and also adjust the NEWS entry to use Sphinx directives for linking to the relevant parts of the C-API docs and PEP-590?

2022-10-24 19:01 UTC, erlend-aasland commented
What is the reason for not adding `PyVectorcall_Function` to the Limited API?

2022-10-24 19:03 UTC, wjakob commented
> What is the reason for not adding PyVectorcall_Function to the Limited API?

It seemed like sort of an implementation detail. I am happy to add it (& tests) if there is consensus to do so.

2022-10-24 19:22 UTC, erlend-aasland commented
> It seemed like sort of an implementation detail. I am happy to add it (& tests) if there is consensus to do so.

I've never had use for it myself, so I have no opinion about this; I was just curious. Let's hear what the others say when they chime in.

2022-10-25 09:39 UTC, erlend-aasland commented on Misc/NEWS.d/next/Core and Builtins/2022-10-24-10-30-30.gh-issue-98586.Tha5Iy.rst
> +the limited API along with the auxiliary macro constant
```suggestion
the :ref:`Limited API <stable>` along with the auxiliary macro constant
```

2022-10-25 09:42 UTC, erlend-aasland commented on Modules/_testcapi/vectorcall_limited.c
> +        PyTuple_SetItem(kwnames, 0, kwname)) {
Minor PEP 7 nit (ditto for the `if`s below): 

```suggestion
        PyTuple_SetItem(kwnames, 0, kwname))
    {
```

2022-10-25 10:41 UTC, markshannon commented
Two questions.

##### First question
Why include `PyObject_VectorcallDict`? It seem to be an internal function for efficiently supporting the old calling convention for callables that support vectorcall.

#### Second question
The vectorcall API has two parts. 
1. Calling through `PyObject_Vectorcall` 
2. Declaring that an object can be called as "vector callable" by setting the `Py_TPFLAGS_HAVE_VECTORCALL` flag and `type.tp_vectorcall_offset`.

Any plans to add the ability to declare classes as having "vector callable" instances?

2022-10-25 10:45 UTC, wjakob commented
Thanks for the review @markshannon.

> Why include PyObject_VectorcallDict? It seem to be an internal function for efficiently supporting the old calling convention for callables that support vectorcall.

I am happy to hear it. I have never had the need to use this function myself. I included in the PR for reasons of symmetry, and because it was prominently advertised in the docs next to `PyObject_Vectorcall` and `PyObject_VectorcallMethod`.

> Any plans to add the ability to declare classes as having "vector callable" instances?

I think that this was already done in PR https://github.com/python/cpython/issues/93274. Please let me know if I misunderstood.

Finally, do you have any thoughts on `PyVectorcall_Function` brought up by @erlend-aasland ?

2022-10-25 10:56 UTC, markshannon commented
One other question.

Why add `PyObject_VectorcallMethod`, rather than exposing the lower level method-getting machinery?
`PyObject_VectorcallMethod` forces the attribute lookup to happen after the arguments are evaluated which is different from Python.
A `PyObject *LoadMethod(PyObject *obj, PyObject *name, PyObject **self)` function would allow C code to use Python evaluation order. `PyObject_VectorcallMethod` could be added as a utility function if desirable.

This is a sketch and is probably missing some error handling and/or incref/decrefs.
```C
PyObject *PyObject_VectorcallMethod(
    PyObject *name, PyObject *const *args,
    size_t nargsf, PyObject *kwnames)
{
      /* Error if nargs < 1 */
      PyObject *obj = args[0];
      PyObject *callable = LoadMethod(obj, name, &args[0]);
      /* TO DO --- Handle error if callable == NULL */
      if (args[0] == NULL) {
            /* No self */
           return PyObject_Vectorcall(callable, args+1, (nargsf-1) | PY_VECTORCALL_ARGUMENTS_OFFSET, kwnames);
      }
      return PyObject_Vectorcall(callable, args, nargsf, kwnames);
}
```

2022-10-25 11:03 UTC, markshannon commented
> Finally, do you have any thoughts on PyVectorcall_Function brought up by @erlend-aasland ?

I'd rather not add it.
Unless it is specified in such a way as to be useless, its existence would unnecessarily constrain the implementation.

2022-10-25 11:05 UTC, wjakob commented
> Why add `PyObject_VectorcallMethod`, rather than exposing the lower level method-getting machinery?
`PyObject_VectorcallMethod` forces the attribute lookup to happen after the arguments are evaluated which is different from Python.

It is convenient to use a 1-function-does-it-all interface like `PyObject_VectorcallMethod` for performing method calls from binding projects. This is particularly true for the `Py_LIMITED_API` that is already heavy on CPython API calls due to the opaque nature of the interfaces. The difference in attribute lookup ordering is an interesting point. I was not aware of this, but it strikes me as a quite minor/subtle issue. (Maybe others will disagree though!)

Altogether, it sounds to me more like a general question about why `PyObject_VectorcallMethod` was designed the way it was? My goal with this PR was to expose something that is already in general use.

2022-10-25 13:24 UTC, wjakob commented
Update: removed `PyObject_VectorcallDict`, incorporated suggestions by @erlend-aasland.

2022-10-25 13:27 UTC, erlend-aasland commented
> Update: removed `PyObject_VectorcallDict`

No, it's still added to the Limited API; you only removed the tests.

> incorporated suggestions by @erlend-aasland.

Thanks

2022-10-25 14:19 UTC, wjakob commented
@erlend-aasland — Oops, you are right. Should be fixed now.

2022-10-25 18:29 UTC, erlend-aasland approved these changes
LGTM. Thanks! This is a very nice addition to the Limited API.

2022-10-25 19:06 UTC, Cammiec91 approved these changes

2022-10-26 11:32 UTC, markshannon requested changes, later dismissed
A couple of potential memory leaks, otherwise LGTM.

2022-10-26 11:32 UTC, markshannon commented on Modules/_testcapi/vectorcall_limited.c
> +    args[2] = PyUnicode_FromString("bar");
You need to check for errors after every call. Otherwise the exception object could leak.

2022-10-26 11:32 UTC, markshannon commented on Modules/_testcapi/vectorcall_limited.c
> +    args[1] = PyUnicode_FromString("foo");
ditto

2022-10-26 12:54 UTC, wjakob commented
Is this okay @markshannon? (with a goto to avoid lots of `if` blocks with different numbers of `Py_DECREF`s)

I have made the requested changes; please review again

2022-10-26 14:07 UTC, wjakob commented
The `test_asyncio` test fails on Windows (Azure Pipelines). Potentially a fluke/unrelated issue? I don't see how it could be related.

2022-10-26 14:28 UTC, AlexWaygood commented
> The `test_asyncio` test fails on Windows (Azure Pipelines). Potentially a fluke/unrelated issue? I don't see how it could be related.

It's a known issue that will be fixed by #98704

2022-10-26 20:11 UTC, erlend-aasland commented on Modules/_testcapi/vectorcall_limited.c
> +static PyObject *call_vectorcall(PyObject* self, PyObject *callable) {
```suggestion
static PyObject *
call_vectorcall(PyObject *self, PyObject *callable)
{
```

2022-10-26 20:11 UTC, erlend-aasland commented on Modules/_testcapi/vectorcall_limited.c
> +static PyObject *call_vectorcall_method(PyObject* self, PyObject *callable) {
```suggestion
static PyObject *
call_vectorcall_method(PyObject *self, PyObject *callable)
{
```

2022-10-27 09:00 UTC, encukou approved these changes
I also have a nitpick, otherwise LGTM.
I'll push a commit to your branch to avoid another round of review ping-pong.

2022-10-27 09:00 UTC, encukou commented on Modules/_testcapi/vectorcall_limited.c
>       */
The comment can go away now.

2022-10-27 09:45 UTC, merged

2022-10-27 09:45 UTC, encukou commented
Thank you for the PR!

2022-10-27 10:54 UTC, wjakob commented
Awesome, many thanks for your help in getting it merged!

2022-11-03 11:40 UTC, wjakob commented
I realized that I forgot to add an entry to `Doc/whatsnew/3.12.rst`. Should I open a separate PR, or will somebody from the maintainers team do this?

2022-11-03 11:41 UTC, markshannon commented
Open a new PR please.