gh-98832: Change wording in `pathlib.Path.iterdir`
python/cpython pull request #98833
Opened 2022-10-28 23:35 UTC by sobolevn

2022-10-29 01:28 UTC, hauntsaninja commented on Lib/pathlib.py
>          """
iterdir also iterates over subdirectories, not just files.

Maybe we could steal from the wording in the docs:
```suggestion
        """Yields path objects of the directory contents.
        The children are yielded in arbitrary order, and the
        special entries '.' and '..' are not included.
        """
```

2022-10-29 16:49 UTC, AlexWaygood commented on Lib/pathlib.py
> +        """Yields path objects of the directory contents.
Nit: I'd prefer to keep the imperative mood here 

```suggestion
        """Yield path objects of the directory contents.
```

2022-10-29 17:22 UTC, AlexWaygood approved these changes
LGTM (but I won't merge just yet, in case Brett has some feedback)

2022-11-09 21:16 UTC, brettcannon requested changes
Stdlib practice is a single sentence summarizing what something does, a newline, and then any relevant details. We should probably go ahead and fix that now.

Otherwise LGTM!

2022-11-09 21:16 UTC, brettcannon commented on Lib/pathlib.py
> +        special entries '.' and '..' are not included.
```suggestion
        """Yield path objects of the directory contents.

        The children are yielded in arbitrary order, and the
        special entries '.' and '..' are not included.
```

2022-11-09 21:37 UTC, sobolevn commented
Thanks! Applied.

To make our bot happy:

I have made the requested changes; please review again.

2022-11-09 21:37 UTC, AlexWaygood approved these changes

2022-11-09 21:38 UTC, miss-islington commented
Status check is done, and it's a success ✅.

2022-11-09 21:39 UTC, miss-islington commented
Sorry, I can't merge this PR. Reason: `5 of 7 required status checks are expected.`.

2022-11-09 22:05 UTC, miss-islington commented
Status check is done, and it's a success ✅.

2022-11-09 22:05 UTC, merged