bpo-32321: Add pure Python fallback for functools.reduce
python/cpython pull request #9884
Opened 2018-10-14 23:55 UTC by bradengroom

2018-10-14 23:55 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-10-15 06:18 UTC, eric-wieser requested changes

2018-10-15 06:18 UTC, eric-wieser commented on Lib/functools.py
> +            value = next(it)
This raises `StopIteration` when it should raise `TypeError: reduce() of empty sequence with no initial value`

2018-10-16 04:06 UTC, bradengroom commented
@eric-wieser Realized I was missing some other pieces here. My fixup commit tests the new implementation as well as the C module. It also should raise the same exceptions as the C implementation now.

2018-10-18 03:03 UTC, pppery commented on Lib/functools.py
> +            raise TypeError('reduce() arg 2 must support iteration')
```suggestion
            raise TypeError('reduce() arg 2 must support iteration') from None
```
You don't want the first TypeError to show up in the traceback

2018-10-18 03:03 UTC, pppery commented on Lib/functools.py
> +                raise TypeError("reduce() of empty sequence with no initial value")
```suggestion
                raise TypeError("reduce() of empty sequence with no initial value") from None
```
See above

2018-10-18 14:40 UTC, bradengroom commented
@pppery Thanks
https://github.com/python/cpython/pull/9884/commits/63bfc75a1973801b6faca4b3e67c4cbb009fa115

2018-10-22 22:52 UTC, bradengroom commented
@rhettinger This is ready for core review. It looks like you are a code owner for this file. What's the proper way to ping for review?

2018-10-25 14:04 UTC, vstinner commented
Oh. I wasn't aware that there were two PRs implementing the same thing. Sorry, I just merged the PR #8548.

2018-10-25 14:04 UTC, closed without merging

2018-10-25 14:33 UTC, bradengroom commented
Oh I missed the other PR in the issue tracker somehow. Thanks