gh-94199: Remove ssl.wrap_socket() documentation
python/cpython pull request #99023
Opened 2022-11-02 19:13 UTC by vstinner

The function has been removed. In the ssl documentation, replace references to the ssl.wrap_socket() function with references to the ssl.SSLContext.wrap_socket() method.

2022-11-02 19:14 UTC, vstinner commented
cc @illia-v

2022-11-02 19:22 UTC, illia-v requested changes
Thanks for updating the doc!

Some arguments of `ssl.wrap_socket` are no longer present in `SSLContext.wrap_socket`.

2022-11-02 19:22 UTC, illia-v commented on Doc/library/ssl.rst
> +   parameter to :meth:`SSLContext.wrap_socket`.  Except for :const:`PROTOCOL_TLS_CLIENT`,
`SSLContext.wrap_socket` does not have the `cert_reqs` parameter

2022-11-02 19:22 UTC, illia-v commented on Doc/library/ssl.rst
> +   value of the ``ca_certs`` parameter to :meth:`SSLContext.wrap_socket`.
No such parameter too

2022-11-02 19:22 UTC, illia-v commented on Doc/library/ssl.rst
> +   value of the ``ca_certs`` parameter to :meth:`SSLContext.wrap_socket`.
A few other lines have such a problem too

2022-11-02 21:32 UTC, vstinner commented
@illia-v: I updated my PR, would you mind to review it? I removed references to non-existing parameters.

I made it clear the wrap_socket() is now the only way to create SSL socket objects, as already stated in the SSLSocket documentation: https://docs.python.org/dev/library/ssl.html#ssl.SSLSocket

> Instances of SSLSocket must be created using the SSLContext.wrap_socket() method.

2022-11-03 10:58 UTC, illia-v requested changes

2022-11-03 10:58 UTC, illia-v commented on Doc/library/ssl.rst
>     :meth:`SSLContext.wrap_socket`.  The call will attempt to validate the
[`SSLContext.wrap_socket`](https://docs.python.org/3.12/library/ssl.html#ssl.SSLContext.wrap_socket) has no `cafile` parameter, [`SSLContext.load_verify_locations`](https://docs.python.org/3.12/library/ssl.html#ssl.SSLContext.load_verify_locations) has it

2022-11-03 10:58 UTC, illia-v commented on Doc/library/ssl.rst
> +and :meth:`SSLContext.wrap_socket` needs to be passed.  If the private key is stored
[`SSLContext.wrap_socket`](https://docs.python.org/3.12/library/ssl.html#ssl.SSLContext.wrap_socket) has no `certfile` parameter

2022-11-03 11:01 UTC, illia-v commented on Doc/library/ssl.rst
>     :meth:`SSLContext.wrap_socket`.  The call will attempt to validate the
```suggestion
   same format as used for the *cafile* parameter in
   :meth:`SSLContext.load_verify_locations`.  The call will attempt to validate the
```

2022-11-03 11:01 UTC, illia-v commented on Doc/library/ssl.rst
> +and :meth:`SSLContext.wrap_socket` needs to be passed.  If the private key is stored
```suggestion
needs to be passed.  If the private key is stored
```

2022-11-03 11:41 UTC, illia-v approved these changes

2022-11-03 12:33 UTC, merged

2022-11-03 12:34 UTC, vstinner commented
Thanks @illia-v, it was more complicated than expected. Not just a simple text replace before/after ;-)