bpo-34995: Maintain func.__isabstractmethod__ in functools.cached_property
python/cpython pull request #9904
Opened 2018-10-15 23:47 UTC by mwilbz

# bpo-34995: Maintain func.__isabstractmethod__ in functools.cached_property

2018-10-15 23:47 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately our records indicate you have not signed the CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-10-25 00:05 UTC, vstinner commented on Lib/functools.py
> +        self.__isabstractmethod__ = getattr(func, '__isabstractmethod__', False)
Would it be possible to only set the attribute (on self) if the attribute exists on func?

2018-10-25 00:06 UTC, vstinner commented on Lib/test/test_functools.py
> +        with self.assertRaises(TypeError):
Would it be possible to (also) directly check the __isabstractmethod__ attribute?

2018-10-25 00:24 UTC, mwilbz commented on Lib/functools.py
> +        self.__isabstractmethod__ = getattr(func, '__isabstractmethod__', False)
Sure! Updated the implementation

2018-10-25 00:24 UTC, mwilbz commented on Lib/test/test_functools.py
> +        with self.assertRaises(TypeError):
Good suggestion, added an assertion for that

2018-10-25 00:27 UTC, vstinner commented on Lib/functools.py
> +        func_isabstractmethod = getattr(func, '__isabstractmethod__')
Used like that, getattr() raises an exception if the attribute doesn't exist.

You can use:

```
try: self.__isabstractmethod__ = func.__isabstractmethod__
except AttributeError: pass
```

2018-10-25 00:32 UTC, mwilbz commented on Lib/functools.py
> +        func_isabstractmethod = getattr(func, '__isabstractmethod__')
Ah, thank you. I opened the implementation in my IDE and it said `default=None` so I was mislead. Pushing the version you're suggesting

2018-10-25 09:40 UTC, vstinner requested changes

2018-10-25 09:40 UTC, vstinner commented on Lib/test/test_functools.py
> +        self.assertTrue(getattr(AbstractExpensiveCalculator.calculate, '__isabstractmethod__', False))
self.assertTrue(AbstractExpensiveCalculator.calculate.__isabstractmethod__) is enough.

2018-10-25 09:40 UTC, vstinner commented on Lib/test/test_functools.py
> +
Can you add a test on a method which doesn't have the ``__isabstractmethod__`` attribute? I expect such test:

```
self.assertFalse(hasattr(AbstractExpensiveCalculator.calculate, '__isabstractmethod__'))
```

2018-10-25 09:40 UTC, vstinner commented on Misc/NEWS.d/next/Library/2018-10-15-23-56-39.bpo-34995.kNA9ge.rst
> +Maintain wrapped method's __isabstractmethod__ in functools.cached_property
I suggest: 

```
:func:`functools.cached_property` now also copies the wrapped method's ``__isabstractmethod__`` attribute.
```

2018-10-25 18:34 UTC, mwilbz commented
I have made the requested changes; please review again

Thank you for your comments @vstinner ! Good suggestions around better test coverage + documentation. :)

2018-10-25 21:05 UTC, vstinner approved these changes
LGTM.

But it seems like @serhiy-storchaka and @methane dislike the overall idea: https://bugs.python.org/issue34995

2018-10-26 05:31 UTC, serhiy-storchaka approved these changes
I still think that it is better to use `@property` instead of `@cached_property` in abstract classes, but I have no strong objections. What would say ABC experts?

2018-10-26 05:31 UTC, serhiy-storchaka commented on Lib/test/test_functools.py
> +        self.assertTrue(AbstractExpensiveCalculator.calculate.__isabstractmethod__)
Too long line. Maybe make the class or property name a little shorter?

2018-11-16 20:12 UTC, mwilbz commented
Possibly outside the scope of this change, but I noticed that `update_wrapper` in `functools` is a common way to inherit various standard fields in a wrapped method. For example, it's used here: https://github.com/python/cpython/blob/master/Lib/functools.py#L906 This example also happens to maintain `__isabstractmethod__` in its own way, slightly different from this PR's current implementation.

Is it worth considering more generally modifying the standard fields to update via `update_wrapper` to include `__isabstractmethod__` as well? https://github.com/python/cpython/blob/master/Lib/functools.py#L30 Then `cached_property` can simply reuse `update_wrapper` to be consistent with other wrappers in `functools`.

2018-11-16 20:13 UTC, mwilbz commented
Regardless of my previous comment, what are the next steps to move forward with this PR? Anything I can do? Thanks again for the reviews up until now =)

2019-03-27 20:55 UTC, mwilbz commented
It sounds like there isn't interest from core contributors in merging this change, so I'll close the PR. Thanks reviewers for your time and feedback!

2019-03-27 20:55 UTC, closed without merging