bpo-34996: Add name parameter to multiprocessing.Pool
python/cpython pull request #9906
Opened 2018-10-16 06:21 UTC by RazManorAllegro

Contributed byt Allegro.ai

https://bugs.python.org/issue34996

2018-10-16 09:57 UTC, tirkarthi commented
Hi @RazManorAllegro , 

Can you please change the title to `bpo-34996: Add name parameter to proccess and thread pool` so that the PR is linked to the bug tracker. Also please add some description in the bug tracker about the goal or use case of the issue so that the reviewers have more context. I can also see #9907 raised to 2.7 and it's up to the reviewer to decide whether this needs to be back ported once the PR to master is reviewed and merged. 

You can find more information about the process : https://devguide.python.org/

Thanks

2018-10-17 14:35 UTC, matrixise requested changes

2018-10-17 14:35 UTC, matrixise commented on Misc/NEWS.d/next/Library/2018-10-17-09-09-51.bpo-34996.lzdfsg.rst
> +Add name paramter to process and thread pool
after the CLA signed, could you fix the typo?

2018-10-22 07:35 UTC, tirkarthi commented on Lib/multiprocessing/pool.py
> +			            name='{}-Worker-{}'.format(name, i),
`make patchcheck` fails in CI in this line due to alignment. Please run `make patchcheck` locally that fixes this issue for you so that it's aligned with `ctx` and `args` .

2018-10-22 16:52 UTC, tirkarthi commented
Apologies if there were multiple notifications for my [comment](https://github.com/python/cpython/pull/9906#discussion_r226918723) I wasn't aware of the GitHub outage and clicked on submit 4-5 times thinking it was a network issue from my end.

2019-03-29 21:12 UTC, brettcannon commented
Thanks for the PR, but closing as the CLA has not been signed within the last month. If you do decide to sign the CLA we can re-open this PR.

2019-03-29 21:12 UTC, closed without merging