bpo-28015: Support LTO build with clang
python/cpython pull request #9908
Opened 2018-10-16 09:15 UTC by serge-sans-paille

.o generated by clang in LTO mode actually are LLVM bitcode files, which
leads to a few errors during configure/build step:

- add lto flags to the BASECFLAGS instead of CFLAGS, as CFLAGS are used
  to build autoconf test case, and some are not compatible with clang LTO
  (they assume binary in the .o, not bitcode)
- force llvm-ar instead of ar, as ar is not aware of .o files generated
  by clang -flto

2018-10-16 09:15 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](https://bugs.python.org/) (b.p.o) to verify you have signed the CLA (this might be simply due to a missing "GitHub Name" entry in your b.p.o account settings). This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

2018-10-16 09:45 UTC, vstinner requested changes
Python source code includes configure for practical reasons, you must run autoconf and include the modified configure in your PR.

2018-10-16 09:59 UTC, vstinner requested changes
It would be convenient if configure fails with an error and an explanation how to fix it if llvm-ar is missing:

```
AC_PATH_TARGET_TOOL(LLVM_AR, llvm-ar, '', ${llvm_path})
(...)
AR="${LLVM_AR}"
```

2018-10-16 10:13 UTC, vstinner commented
I tested the 3rd version. It seems like -flto is passed during the compilation of object files and to the final linker step:

```
$ grep lto Makefile
BASECFLAGS=	 -flto -g -Wno-unused-result -Wsign-compare
CONFIGURE_LDFLAGS=	 -flto -g
CONFIG_ARGS=	 '--with-pydebug' 'CC=clang' '--with-lto'

$ make
...
clang -pthread -fPIC -flto (...)
...
/usr/bin/llvm-ar rcs libpython3.8dm.a Modules/getbuildinfo.o (...) Python/frozen.o
clang -pthread -flto -g  -Xlinker -export-dynamic -o python Programs/python.o libpython3.8dm.a -lpthread -ldl  -lutil -lm   -lm 
```

2018-10-16 10:16 UTC, vstinner approved these changes
LGTM. It works as expected (see my comment above) and it fix an obvious bug https://bugs.python.org/issue28015#msg327817

2018-10-16 10:18 UTC, vstinner commented
You may add a NEWS entry using the tool "blurb".

@serge-sans-paille signed the CLA, but I have to wait until someone review his signature.

2018-10-16 10:20 UTC, vstinner commented
I will remove the "CLA not signed" label once "Contrib Form Received" will become Yes on https://bugs.python.org/user22883

2018-10-24 23:54 UTC, merged

2018-10-25 00:01 UTC, vstinner commented
@serge-sans-paille: The backport to 3.7 was straighfoward and could be automated, but backport to 3.6 creates a conflict on configure.ac. Do you want to try the backport? I'm not sure if it's worth it to backport the change up to 3.6. It's up to you.

2018-10-29 12:44 UTC, serge-sans-paille commented
Finally, there a re many complex interactions with RANLIB and AR, dropping the backport.

2018-10-29 12:47 UTC, vstinner commented
> Finally, there a re many complex interactions with RANLIB and AR, dropping the backport.

The Python 3.6 backport? It's too complex? It's ok to only fix Python 3.7 and newer. (I just need your confirmation to close the issue.)

2018-10-29 12:56 UTC, serge-sans-paille commented
Yeah, the 3.6 backport would require some more thoughts, better drop it
and close the issue. Thanks!

2018-10-31 17:43 UTC, stratakis commented
The 3.6 backport works fine if https://bugs.python.org/issue31625 is applied for 3.6 as well.