bpo-34187: _WindowsConsoleIO rises correct exception
python/cpython pull request #9922
Opened 2018-10-17 01:11 UTC by augustogoulart

`_WindowsConsoleIO` implementation of fileno should raise a `ValueError`
instead of `io.UnsupportedOperation` if the internal handle value is
INVALID_HANDLE_VALUE.

Closes:
https://bugs.python.org/issue34187

Previous issue that originated issue34187:
https://bugs.python.org/issue34115

2018-10-18 02:48 UTC, augustogoulart commented
@taleinat

2018-10-25 11:59 UTC, taleinat commented on Modules/_io/winconsoleio.c
> +    if (self->handle == INVALID_HANDLE_VALUE)
This `if` needs curly braces.

2018-10-25 12:10 UTC, taleinat requested changes
Thanks for making this PR!

ISTM that the potential issue in `internal_close` is separate from the main issue regarding `fileno`. I recommend removing the `internal_close` change from this PR, and possibly creating a separate PR for it.

Regarding the `fileno` issue, please add a test that reproduces the relevant bug.

2018-10-26 03:10 UTC, augustogoulart commented
I have made the requested changes; please review again.

2018-11-05 13:02 UTC, taleinat requested changes
ISTM this change does more than just raise a different exception, since it also makes sure to close the file handle in a certain case. I'd like to see a test for that too.

This will need a NEWS entry; install [blurb](https://pypi.org/project/blurb/) and run `blurb add` to create one.

Also a minor inline comment.

2018-11-05 13:02 UTC, taleinat commented on Lib/test/test_winconsoleio.py
> +    def test_fileno_raises_correct_exception(self):
I suggest replacing "correct_exception" with something about the file being closed.

2022-03-04 12:11 UTC, closed without merging