[Skip Issue] In _PyIO_trap_eintr(), check if "val" is not an OSError after PyErr_NormalizeException()
python/cpython pull request #9929
Opened 2018-10-17 13:19 UTC by ZackerySpytz

It is not safe to assume that "val" will be an OSError after
PyErr_NormalizeException(). "val" may be an arbitrary exception (for
example, MemoryError) if an error occurs during the
PyErr_NormalizeException() call.

2018-10-25 09:15 UTC, pitrou commented
@ZackerySpytz Could you open an issue explaining the underlying concern? Is this something you witnessed concretely?

2018-10-25 09:15 UTC, pitrou requested changes
Thanks for submitting this PR. See comment below. Also, please open an issue about this.

2018-10-25 09:15 UTC, pitrou commented on Modules/_io/bufferedio.c
> +    if (!PyObject_TypeCheck(val, (PyTypeObject *)PyExc_OSError)) {
Please add a comment explaining why this check is necessary.

2018-11-08 10:00 UTC, serhiy-storchaka commented
LGTM, but please add comments.

2018-11-08 10:12 UTC, Carole1 commented on Modules/_io/bufferedio.c
> +    if (!PyObject_TypeCheck(val, (PyTypeObject *)PyExc_OSError)) {
What is LGTM...?

2018-11-09 12:05 UTC, serhiy-storchaka commented
[LGTM](https://www.urbandictionary.com/define.php?term=LGTM) = Looks Good To Me.

2020-01-10 12:15 UTC, csabella commented
@ZackerySpytz , please address the review comments.  Thanks!

2020-05-28 23:05 UTC, csabella commented
@ZackerySpytz ping

2025-10-09 21:19 UTC, StanFromIreland commented
5 years and the requested issue has not been opened, closing.

2025-10-09 21:19 UTC, closed without merging