bpo-29905: Fix TypeError is asyncio/proactor_events
python/cpython pull request #993
Opened 2017-04-04 20:49 UTC by DimitrisJim

A new PR for issue29905, without including the TypeError reformatting for `asynchat` which, if my interpretation of  #issue25002 and specifically #msg250151 was correct, should probably not be included. 

If my interpretation was incorrect, I'll push a change for it too :-).

2017-04-19 04:59 UTC, berkerpeksag requested changes
That if branch doesn't seem to be tested in `Lib/test/test_asyncio/test_proactor_events.py`. Could you add a simple test that triggers `TypeError`? The `ProactorSocketTransportTests.socket_transport()` helper already provides most of the needed infrastructure so I guess it should be easy to write a test case.

Please add a note to `Misc/NEWS`.

Also, "is" in your PR title should be "in", right? :)

2017-04-19 04:59 UTC, berkerpeksag commented on Lib/asyncio/proactor_events.py
> +            msg = ("data argument must be a bytes-like object, not '%s'" %
`%r` looks OK to me. Is there a reason to use `'%s'` with `type(data).__name__`?

2017-04-19 05:11 UTC, AraHaan commented on Lib/asyncio/proactor_events.py
> +            msg = ("data argument must be a bytes-like object, not '%s'" %
Why not use string tuples for ``format`` like this?

```py
            msg = ("data argument must be a bytes-like object, not '{}'"
            ).format(data)
```

also are you missing an

```py
            raise TypeError(msg)
```
anywhere?

2017-04-19 13:14 UTC, DimitrisJim commented on Lib/asyncio/proactor_events.py
> +            msg = ("data argument must be a bytes-like object, not '%s'" %
@berkerpeksag AFAIK `repr`ing in error messages is used to play it safe in cases where the object happens to be an instance of `bytes`; the `__name__` special attribute is always a string so `%s` is always certain to work. Apart from that, I followed along with other cases of formatting `__name__` I encountered in other error messages. 

@AraHaan The author of the module prefers using old-style formatting, so I stuck with that to keep it consistent. :-)

2017-04-19 13:15 UTC, DimitrisJim commented
I'll address the requests soon, thanks! 

(Yes, silly typo :-))

2017-06-10 02:56 UTC, 1st1 approved these changes

2017-06-10 02:56 UTC, merged

2017-06-10 03:16 UTC, 1st1 commented
Thanks! Will be shipped in 3.6.2