WIP: [2.7] bpo-24658: Fix read/write greater than 2 GiB on macOS (GH-1705)
python/cpython pull request #9938
Opened 2018-10-18 00:22 UTC by matrixise

On macOS, fix reading from and writing into a file with a size larger
than 2 GiB.

https://bugs.python.org/issue24658

2018-10-18 06:43 UTC, vstinner requested changes
You should also patch:

* Modules/_io/fileio.c: fileio_readinto(), fileio_readall(), fileio_read(), fileio_write()
* Modules/posixmodule.c: posix_read(), posix_write()

You can add the #define at the end of Include/pyport.h.

2018-10-18 06:59 UTC, matrixise commented
@vstinner In fact, I should mark this PR as "DO-NOT-MERGE" because I didn't finish it yesterday :/

2018-10-18 08:37 UTC, vstinner requested changes

2018-10-18 08:37 UTC, vstinner commented on Modules/posixmodule.c
> +        size = _PY_READ_MAX;
Hum. It seems inefficient to allocate size bytes and only later pass _PY_READ_MAX. This truncation should be done *before* PyString_FromStringAndSize().

2018-10-18 09:32 UTC, serhiy-storchaka commented
Shouldn't we update also `Py_UniversalNewlineFread()`?

2018-10-18 14:11 UTC, vstinner commented
> Shouldn't we update also Py_UniversalNewlineFread()?

It's implemented with fread() which uses size_t for the length parameter. I hope that the libc on macOS implements fread() properly for read larger than 2 GiB. If it's not the case, it's would be a bug in the libc, no? :-)

2018-10-18 14:14 UTC, vstinner commented
> I hope that the libc on macOS implements fread() properly for read larger than 2 GiB.

This old issue https://bugs.python.org/issue9015#msg107966 explains that fwrite() on **Windows** should not be called with a buffer larger than 2**31 bytes. See also https://bugs.python.org/issue9611#msg120388

2018-10-24 23:33 UTC, vstinner commented on Modules/posixmodule.c
> +        size = _PY_READ_MAX;
ping @matrixise

2019-03-25 20:00 UTC, matrixise commented
Need to finish this PR, I have macOS, will try to port the patch to Python 2.7.

Thank you for your patience and I am really sorry for the big delay :-1:

2019-03-26 12:24 UTC, vstinner commented
> Need to finish this PR, I have macOS, will try to port the patch to Python 2.7. Thank you for your patience and I am really sorry for the big delay -1

I don't understand the purpose of such comment. It sends me an unsolicited notification (email).

2020-01-19 18:15 UTC, zware commented
@matrixise EOL snuck up on you before this got finished, so I'm closing it for you :)

2020-01-19 18:15 UTC, closed without merging