bpo-29981: Update Index for set, dict, and generator 'comprehensions'
python/cpython pull request #995
Opened 2017-04-05 05:08 UTC by louisom

2017-04-08 05:54 UTC, orsenthil approved these changes
This change looks good to me.

2017-04-08 06:12 UTC, serhiy-storchaka commented on Doc/glossary.rst
> +      return a set with the results. ``results = {'foo' for _ in range(10)}``
This is bad example. The result is just `{'foo'}`.

2017-04-08 06:16 UTC, serhiy-storchaka commented on Doc/glossary.rst
> +      return a set with the results. ``results = {'foo' for _ in range(10)}``
See an example in tutorial.

2017-04-08 06:17 UTC, serhiy-storchaka commented
It may be worth to mention set and dict comprehensions as ways of creating sets and dicts in `stdtypes.rst`.

2017-04-10 04:17 UTC, grapherd commented
@serhiy-storchaka there are already mention set and dict omprehensions in `stdtypes.rst`, but not like link comprehension using one section.

2017-04-10 04:18 UTC, grapherd commented on Doc/glossary.rst
> +      return a set with the results. ``results = {'foo' for _ in range(10)}``
@serhiy-storchaka thanks for mention, change another example for set comprehension.

2017-04-10 04:20 UTC, orsenthil commented on Doc/glossary.rst
> +      c not in 'abc'`` generates a set of strings with ``{'r', 'd'}``.
This is missing `}`

2017-04-10 05:51 UTC, serhiy-storchaka commented
I can't find mentions of set and dict comprehensions in `stdtypes.rst`.

A list comprehension is mentioned as the one of three ways of creating lists (in addition to the constructor and the bracket construction). But for sets and dicts only two ways of creating are mentioned (the constructor and the brace construction).

2017-04-10 06:06 UTC, grapherd commented
I mistake the outcome, it had written in `tutorial/datastructure.rst`, not `stdtypes.rst`

2017-04-10 06:49 UTC, serhiy-storchaka commented on Doc/library/stdtypes.rst
> +Non-empty sets (not frozensets) canb be created by several ways:
Typo: ``canb``.

2017-04-10 06:49 UTC, serhiy-storchaka commented on Doc/library/stdtypes.rst
> +Non-empty sets (not frozensets) canb be created by several ways:
Empty sets also can be created by using the constructor and set comprehension.

2017-04-10 06:49 UTC, serhiy-storchaka commented on Doc/library/stdtypes.rst
> +* Using dict comprehension: ``{x: x ** 2 for x in range(10)}``
Maybe "Using a dict comprehension"?

2017-04-10 06:53 UTC, grapherd commented on Doc/library/stdtypes.rst
> +Non-empty sets (not frozensets) canb be created by several ways:
I think empty set can't created by set comprehension, `{}` return a dict, I'll add up the constructor.

2017-04-10 06:58 UTC, serhiy-storchaka commented on Doc/library/stdtypes.rst
> +Non-empty sets (not frozensets) canb be created by several ways:
`{x for x in ()}`

We can't say that the set created by a set comprehension is non-empty until we have created it.

2017-04-10 07:01 UTC, grapherd commented on Doc/library/stdtypes.rst
> +Non-empty sets (not frozensets) canb be created by several ways:
Great, I didn't thought that way to create a set before.

2017-04-10 07:03 UTC, grapherd commented on Doc/library/stdtypes.rst
> +* Using dict comprehension: ``{x: x ** 2 for x in range(10)}``
Another question, so `{}` is a dict comprehension, or a `dict` constructor?

2017-04-10 07:27 UTC, serhiy-storchaka commented on Doc/library/stdtypes.rst
> +* Using dict comprehension: ``{x: x ** 2 for x in range(10)}``
``{}`` is a dict display.

2017-04-10 17:09 UTC, bitdancer requested changes
Thanks for working on this. I have some suggestions.

2017-04-10 17:09 UTC, bitdancer commented on Doc/glossary.rst
> +      A compact way to process all or part of the pair elements in a sequence
"process all or part of the pair elements in a sequence" makes no sense to me in this context.  Most likely you just want "to process all or part of the items in a sequence" as with the set comprehension.

I think it would be good include a link to the reference documentation.

2017-04-10 17:09 UTC, bitdancer commented on Doc/glossary.rst
> +      c not in 'abc'}`` generates a set of strings with ``{'r', 'd'}``.
I think you mean "generates the set of strings ``{'r', 'd'}``.

I think it would be good to include a link to the reference documentation.

2017-04-10 17:09 UTC, bitdancer commented on Doc/library/stdtypes.rst
> +  ``{c for c in 'abracadabra' if c not in 'abc'}``
Given that you adding this paragraph in parallel to the way it is done in list and tuple, it would be best to put it at the beginning of the section, the way it is in list and tuple.  I would drop the example of creating the empty set via comprehension, it will just confuse the reader.  Please also reorder the sentences so that they are in an order parallel to that used in list and tuple (ie: the constructor sentence is last).  This is mostly a trivial style nit, but consistency is good :)

2017-04-10 17:09 UTC, bitdancer commented on Doc/library/stdtypes.rst
> +* Using a dict comprehension: ``{}``, ``{x: x ** 2 for x in range(10)}``
As above, I think this would be better at the start of the section, with the constructor sentence last.

2017-04-26 06:42 UTC, lulouie commented on Doc/library/stdtypes.rst
> +  ``{c for c in 'abracadabra' if c not in 'abc'}``
I move this into class dict, not sure if you are saying this section. But it is now consistent with `list` and `tuple`.

2017-04-26 06:42 UTC, lulouie commented on Doc/library/stdtypes.rst
> +  ``{c for c in 'abracadabra' if c not in 'abc'}``
Remove empty set comprehension

2017-04-26 06:43 UTC, lulouie commented on Doc/glossary.rst
> +      c not in 'abc'}`` generates a set of strings with ``{'r', 'd'}``.
fixed

2017-04-26 06:43 UTC, lulouie commented on Doc/glossary.rst
> +      A compact way to process all or part of the pair elements in a sequence
fixed

2017-04-26 06:43 UTC, lulouie commented on Doc/library/stdtypes.rst
> +* Using a dict comprehension: ``{}``, ``{x: x ** 2 for x in range(10)}``
fixed

2017-04-26 13:23 UTC, bitdancer requested changes
With this exception of the one typo, this looks good to me.

2017-04-26 13:23 UTC, bitdancer commented on Doc/library/stdtypes.rst
> +   Sets can be created by several ways:b
Looks like you have a stray 'b' there at the end of the sentence.

2017-04-26 14:34 UTC, lulouie commented on Doc/library/stdtypes.rst
> +   Sets can be created by several ways:b
Yes, I should self-check this one.

2017-04-26 19:37 UTC, bitdancer approved these changes

2017-06-08 00:14 UTC, terryjreedy requested changes

2017-06-08 00:14 UTC, terryjreedy commented on Doc/glossary.rst
> +      A compact way to process all or part of the items in a sequence
A list/set/dict comprehension processes the items in an iterable.
If the entry for listcomp says 'sequence', it should be changed.  I also do not like the 'all or part of' phrase.  The iteration runs to completion.  If one wants to not run the iteration to completion, one must use an explicit for loop.  Perhaps the 'or part' refers to 'if' clauses.  But that is a form of processing.  If the iterable yields volatile items, they are gone.

2017-06-08 00:14 UTC, terryjreedy commented on Doc/glossary.rst
> +      return a set with the results. ``results = {c for c in 'abracadabra' if
Ditto

2017-06-08 00:14 UTC, terryjreedy commented on Doc/library/stdtypes.rst
> +   * Using a comma-separated list of elements within braces: ``{'jack', 'sjoerd'}``
I would use 'Use' instead of 'Using' here and rest of list

2017-06-08 00:14 UTC, terryjreedy commented on Doc/library/stdtypes.rst
> +   Sets can be created by several ways:
'by several ways' is not idiomatic.  Either 'by several means' or 'in several ways'.  The latter is used below for dicts.

2017-06-08 00:17 UTC, terryjreedy commented
Have any of the other reviewers downloaded and applied the patch and rebuilt the doc to check the changes, especially the new index entries?

2017-06-21 16:25 UTC, berkerpeksag commented on Doc/library/stdtypes.rst
> +   * Using the type constructor: ``set()``, ``set('foobar')``, ``set(['a', 'b', 'foo'])``
I'm wondering if we should still advertise the use of `set([...])`. We replaced all instances of it with set literals in the stdlib. See http://bugs.python.org/issue22823 for details.

2017-06-21 18:15 UTC, serhiy-storchaka commented on Doc/library/stdtypes.rst
> +   * Using the type constructor: ``set()``, ``set('foobar')``, ``set(['a', 'b', 'foo'])``
IMHO these examples are not for creating set literals. They demonstrate creating sets from iterables using the type constructor. Without these examples the user can though that `{x for x in iterable}` is the only way.

2018-02-21 01:51 UTC, brettcannon commented
To try and help move older pull requests forward, we are going through and backfilling 'awaiting' labels on pull requests that are lacking the label. Based on the current reviews, the best we can tell in an automated fashion is that a core developer requested changes to be made to this pull request.

If/when the requested changes have been made, please leave a comment that says, `I have made the requested changes; please review again`. That will trigger a bot to flag this pull request as ready for a follow-up review.

2018-05-21 04:29 UTC, willingc commented
Thanks @louisom for submitting a PR and @serhiy-storchaka, @orsenthil, @terryjreedy, @bitdancer, and @berkerpeksag for the reviews.

To try and help move older pull requests forward, I'm closing this PR since it has been languishing for almost a year.

2018-05-21 04:29 UTC, closed without merging