bpo-34963: Make the repr of the typing.NewType() result more meaningful.
python/cpython pull request #9951
Opened 2018-10-18 11:09 UTC by serhiy-storchaka

Add attributes `__qualname__` and `__module__`.
If the name argument is dotted, the `__name__` attribute will be set to its last component.

2018-10-21 22:03 UTC, ilevkivskyi reviewed
I actually like this solution. But before merging let us wait for the benchmarks for other approach, if they are OK, maybe we can have an even nicer repr in https://github.com/python/cpython/pull/9808

2018-10-24 23:37 UTC, vstinner requested changes

2018-10-24 23:37 UTC, vstinner commented on Lib/typing.py
> +    new_type.__name__ = name
It looks like a line is duplicated?

2018-10-28 12:19 UTC, serhiy-storchaka commented on Lib/typing.py
> +    new_type.__name__ = name
Thanks, removed.

2018-10-28 15:39 UTC, vstinner approved these changes
LGTM, but I would prefer that one of the typing maintainer double check this change. @ilevkivskyi?

2018-10-28 15:46 UTC, ilevkivskyi commented
@vstinner The PR looks good. However, there is a "competing" PR (alternative solution) in #9808. I asked the author for benchmarks, but he didn't respond yet. If he will not respond next week, I would propose to merge this one.

2019-01-10 15:36 UTC, vstinner commented
@serhiy-storchaka: This PR still LGTM. You can merge it.

> However, there is a "competing" PR (alternative solution) in #9808.

It doesn't seem to define __module__. It doesn't seem to be directly related. This PR looks simple enough.

2019-01-11 13:37 UTC, ilevkivskyi commented
It looks like the author of other PR is not responding. I leave up to Serhiy whether to just move with this PR or incorporate some ideas from other one too as I proposed in https://bugs.python.org/issue34963#msg328707

(This PR LGTM as is.)

2020-06-05 09:33 UTC, gaborbernat commented
@serhiy-storchaka shall we move ahead with this or the alternate PR?

2021-05-02 20:42 UTC, JelleZijlstra commented
This PR still applies and it would be useful, is there anything blocking it from being merged?

2021-06-22 00:32 UTC, gvanrossum approved these changes
Okay, looks fine to me. I'll merge.

2021-06-22 00:34 UTC, gvanrossum commented
Closing and reopening since it looks like some tests are hanging.

2021-06-22 01:02 UTC, gvanrossum commented
@serhiy-storchaka Can you look at the test failure? Maybe it just needs a merge from a more recent main branch?

2021-06-22 06:18 UTC, serhiy-storchaka commented
It needs some correction in `is_new_type()` in `Objects/unionobject.c`.

2021-06-22 18:28 UTC, gvanrossum commented
Go for it!

2021-07-24 07:12 UTC, serhiy-storchaka commented
typing.NewType has been reimplemented as a class in bpo-44353, so this trick is no longer needed.

2021-07-24 07:12 UTC, closed without merging