Set headersonly for parsing header data.
python/cpython pull request #996
Opened 2017-04-05 05:31 UTC by pareshverma91

http.client's parse_headers ends up providing only header data to parsestr, but
doesn't set the headersonly option. This ends up generating warning for
StartBoundaryNotFoundDefect. This only corrects this defect.

https://github.com/shazow/urllib3/issues/800 is related.

2017-04-05 05:31 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Unfortunately we couldn't find an account corresponding to your GitHub username on [bugs.python.org](http://bugs.python.org/) (b.p.o) to verify you have signed the CLA. This is necessary for legal reasons before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://cpython-devguide.readthedocs.io/pullrequest.html#licensing) to rectify this issue.


Thanks again to your contribution and we look forward to looking at it!

2017-04-05 05:41 UTC, orsenthil requested changes

2017-04-05 05:41 UTC, orsenthil commented on Lib/http/client.py
> +    return email.parser.Parser(_class=_class).parsestr(hstring, headersonly=True)
For a change like this, please

1) Please create  bugs.python.org ticket, and show us the problem with steps to reproduce.
2) Show how this fixes along with a tests.
3) We need to document this too. 

This patch is incomplete (even for review) without all three above.

2017-04-05 05:43 UTC, pareshverma91 commented on Lib/http/client.py
> +    return email.parser.Parser(_class=_class).parsestr(hstring, headersonly=True)
Sounds good. Will send out an update to the PR.

2017-04-05 08:42 UTC, grapherd commented
@pareshverma91 small problem, the title of this commit should change,  start with `bpo-29991: `.

2017-04-07 01:56 UTC, pareshverma91 commented
It seems the same resolution was suggested under https://bugs.python.org/issue29353 2 months ago. The discussion is still ongoing, but closing this PR and the corresponding bug as duplicate. Thanks.

2017-04-07 01:56 UTC, closed without merging