[2.7] bpo-34866: Adding max_num_fields to cgi.FieldStorage (GH-9660)
python/cpython pull request #9969
Opened 2018-10-19 16:20 UTC by matthewbelisle-wf

Adding `max_num_fields` to `cgi.FieldStorage` to make DOS attacks harder by
limiting the number of `MiniFieldStorage` objects created by `FieldStorage`.

(cherry picked from commit 209144831b0a19715bda3bd72b14a3e6192d9cc1)

2018-10-24 23:16 UTC, vstinner requested changes
You must update the documentation as well: https://bugs.python.org/issue34866#msg328401

2018-10-30 15:22 UTC, matthewbelisle-wf commented
Thanks for the info @vstinner , I added those changes in 90ab0d5acd.

For @bedevere-bot : I have made the requested changes; please review again.

2018-10-30 15:58 UTC, vstinner approved these changes
LGTM.

Please write a PR for the master branch to document the new parameter.

2018-10-30 19:31 UTC, matthewbelisle-wf commented
Thanks @vstinner . Here are the PRs for `master`, `3.7`, and `3.6`:

https://github.com/python/cpython/pull/10247
https://github.com/python/cpython/pull/10246
https://github.com/python/cpython/pull/10248

2018-10-30 19:50 UTC, vstinner commented on Doc/library/urlparse.rst
> +      Added *max_num_fields* param.
oh, please replace "param" with "parameter.

2018-10-30 19:50 UTC, vstinner commented on Doc/library/urlparse.rst
> +      Added *max_num_fields* param.
Ditto.

2018-10-30 19:55 UTC, matthewbelisle-wf commented
@vstinner Sure thing, fixed in commit 1767079.

2018-10-30 20:39 UTC, matthewbelisle-wf commented
Okay this is ready for review again @vstinner

2018-10-30 21:16 UTC, merged