gh-99770: Make the correct call specialization fail kind show up
python/cpython pull request #99771
Opened 2022-11-25 11:47 UTC by penguin-wwy

2022-12-20 10:18 UTC, markshannon commented
@penguin-wwy 

Sorry, this got overlooked when I was updating the stats for `LOAD_ATTR` and `CALL`.

We still don't specify whether the failure is for a builtin function or method descriptor, so this PR would still be a valuable addition, if you are willing to update it.

2022-12-21 09:20 UTC, penguin-wwy commented
I updated the failure for the method descriptor.

2022-12-22 08:49 UTC, penguin-wwy commented on Python/specialize.c
> +        return SPEC_FAIL_CODE_COMPLEX_PARAMETERS;
`function_kind` used in `subscr`、`attr` and `call` specialize, move the failure to the common category.

2022-12-22 11:19 UTC, markshannon requested changes
Thanks for doing this. There a couple more values that need changing.

2022-12-22 11:19 UTC, markshannon commented on Python/specialize.c
> +#define SPEC_FAIL_CODE_NOT_OPTIMIZED 8
You will need to update the summarize_stats script
https://github.com/python/cpython/blob/main/Tools/scripts/summarize_stats.py#L227

2022-12-22 11:19 UTC, markshannon commented on Python/specialize.c
> +#define SPEC_FAIL_CODE_NOT_OPTIMIZED 8
You will also need to change `SPEC_FAIL_UNPACK_SEQUENCE_ITERATOR`

2022-12-22 12:13 UTC, penguin-wwy commented on Python/specialize.c
> +#define SPEC_FAIL_CODE_NOT_OPTIMIZED 8
Done

2022-12-22 12:14 UTC, penguin-wwy commented on Python/specialize.c
> +#define SPEC_FAIL_CODE_NOT_OPTIMIZED 8
Done

2022-12-22 12:14 UTC, penguin-wwy commented
I have made the requested changes; please review again.

2022-12-22 12:44 UTC, markshannon approved these changes
That's great. Thanks.

2022-12-22 12:44 UTC, merged