gh-99925: Fix inconsistency in `json.dumps()` error messages
python/cpython pull request #99926
Opened 2022-12-01 14:29 UTC by fnesveda

Fixes #99925.

When you try to serialize a `NaN`, `inf` or `-inf` with `json.dumps(..., allow_nan=False)`, the error messages are inconsistent, depending on whether you use `indent` or not.

```python
>>> json.dumps(float('nan'), allow_nan=False)
ValueError: Out of range float values are not JSON compliant

>>> json.dumps(float('nan'), allow_nan=False, indent=4)
ValueError: Out of range float values are not JSON compliant: nan
```

That is because if you don't use `indent`, the encoding is done in C code [here](https://github.com/python/cpython/blob/0563be23a557917228a8b48cbb31bda285a3a815/Modules/_json.c#L1321-L1327),
but if you use `indent`, the encoding is done in pure Python code [here](https://github.com/python/cpython/blob/0563be23a557917228a8b48cbb31bda285a3a815/Lib/json/encoder.py#L239-L242), and the error messages are different between the two.

This PR unifies the error messages, so that both now include the representation of the invalid value.

2022-12-17 12:57 UTC, serhiy-storchaka requested changes
`PyOS_double_to_string()` returns a pointer to an array allocated on the heap. You should use `PyMem_Free()` to deallocate it.

But it would be simpler to use format `%R` with the Python object `obj`.

Please add also a test for error message.

2022-12-19 10:41 UTC, fnesveda commented
@serhiy-storchaka Thanks for the review, makes sense 🙂 

I have made the requested changes; please review again.

2022-12-20 10:53 UTC, serhiy-storchaka approved these changes

2022-12-20 10:54 UTC, serhiy-storchaka commented
LGTM.

2022-12-20 10:54 UTC, merged