ENH: Ensure unreported error is chained for SystemError during import
python/cpython pull request #99946
Opened 2022-12-02 09:20 UTC by seberg

Debugging a small issue in SciPy was made a bit tricky by the error being cleared seemingly unnecessary here.

This ensures that module load errors chain their exceptions when this occurs (similar to function calls).

Expanded the test to check that the `__cause__` is set where it seems that it should be.

2022-12-02 23:49 UTC, brettcannon requested changes
Some minor tweaks, but otherwise I'm good with the proposed change.

2022-12-02 23:49 UTC, brettcannon commented on Lib/test/test_importlib/extension/test_loader.py
> +                # If there is an unreported exception, it should be chained
```suggestion
                # If there is an unreported exception, it should be chained with the `SystemError`.
```

2022-12-02 23:49 UTC, brettcannon commented on Lib/test/test_importlib/extension/test_loader.py
> +                    self.assertIsNot(cm.exception.__cause__, None)
```suggestion
                    self.assertIsNotNone(cm.exception.__cause__)
```

2022-12-02 23:50 UTC, brettcannon commented on Misc/NEWS.d/next/C API/2022-12-02-09-31-19.gh-issue-99947.Ski7OC.rst
> +SystemErrors on import now chain the original unexpected exception
```suggestion
Raising SystemError on import will now have its cause be set to the original unexpected exception.
```

2022-12-03 00:31 UTC, ericsnowcurrently reviewed
I agree with Brett. :)

2022-12-03 07:50 UTC, seberg commented
Adopted the improvements, thanks.  Its a minor help with debugging, but would have saved me time twice in the past 1-2 months.

2022-12-07 11:45 UTC, seberg commented
"I have made the requested changes; please review again"

2022-12-23 23:18 UTC, brettcannon approved these changes

2022-12-23 23:18 UTC, brettcannon commented on Lib/test/test_importlib/extension/test_loader.py
> +                # with the `SystemError`
```suggestion
                # with the `SystemError`.
```

2022-12-23 23:43 UTC, merged