remove hardcoded check that op is LOAD_CONST
python/cpython pull request #99943
Opened 2022-12-02 05:46 UTC by chilaxan

3.11 adds a new opcode KW_NAMES that has an entry in co_consts, however the hardcoded check here causes dis to not grab the constant

2022-12-04 08:58 UTC, sobolevn reviewed
Please, add a test-case and change your PR title to start with `gh-99944: `

2022-12-04 23:28 UTC, chilaxan commented
> Please, add a test-case and change your PR title to start with `gh-99944: `

can you give me a resource for adding a test case?

2023-03-14 14:11 UTC, carljm requested changes
> can you give me a resource for adding a test case?

The tests for `Lib/dis.py` are in `Lib/test/test_dis.py`. You should be able to look through existing test cases there and find some tests that are suitable to copy and modify. You just want a test that verifies the `dis` output for some code that includes `KW_NAMES` opcode.

Also, please add a What's New entry.

If those things are done, this PR looks good to me.

2023-03-14 14:18 UTC, AlexWaygood commented
Just to build on @carljm's excellent advice — there's also some resources on running and writing tests for CPython here: https://devguide.python.org/testing/run-write-tests/

2023-04-26 18:02 UTC, iritkatriel commented
This was completed during the sprint in https://github.com/python/cpython/pull/103856.

Thank you!

2023-04-26 18:02 UTC, closed without merging