gh-98778: Update HTTPError to initialize properly even if fp is None
python/cpython pull request #99966
Opened 2022-12-03 11:06 UTC by corona10

2022-12-03 11:11 UTC, corona10 commented
Since the `_TemporaryFileCloser` is used for internal usage, this change will not impact to 3rd party libraries.

2022-12-03 12:05 UTC, corona10 commented
````

(.oss) ➜  cpython git:(gh-98778) ✗ ./python.exe -m test test_urllib2 -R 3:3
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 1.44 Run tests sequentially
0:00:00 load avg: 1.44 [1/1] test_urllib2
beginning 6 repetitions
123456
......

== Tests result: SUCCESS ==

1 test OK.

Total duration: 1.5 sec
Tests result: SUCCESS
````

2022-12-07 14:08 UTC, ambv requested changes
You made changes to `_TemporaryFileCloser` but `urllib.response.addinfourl` here is a subclass of `_TemporaryFileWrapper`. Now after your changes the `.close()` and `.cleanup()` operations work but the wrapper is still in an inconsistent state. It cannot be used as a context manager, and cannot be iterated. The wrapper proxies attribute access to the file handle so asking things like `exc.mode`, `exc.seekable()`, etc. will all fail.

The cleanest solution would be to change `HTTPError` to not subclass this thing at all... but that ship has sailed a long time ago.

Your change weakens `_TemporaryFileCloser` by allowing it to silently accept `None` in lieu of a file handle. This makes `tempfile` worse, I'm not convinced this is a good compromise.

Instead, since `HTTPError` is already a hack (and there was literally a comment about why it's hacky where the bug was created), I would just replace the hack with a different one: set `fp` to `io.StringIO()` if the passed `fp` is `None`. It's still not perfect but I feel that would be more robust.

2022-12-07 14:32 UTC, corona10 commented
> Instead, since HTTPError is already a hack (and there was literally a comment about why it's hacky where the bug was created), I would just replace the hack with a different one: set fp to io.StringIO() if the passed fp is None. It's still not perfect but I feel that would be more robust.

+1

2022-12-07 15:28 UTC, corona10 commented
@ambv 

Thank you for the review and for pointing out what I missed :)

I have made the requested changes; please review again

2022-12-07 16:14 UTC, ambv approved these changes

2022-12-07 16:14 UTC, ambv commented on Lib/urllib/error.py
> +            self.__super_init(io.StringIO(), hdrs, url, code)
It's both fewer lines and less redundant to do it in one go.

```suggestion
        if fp is None:
            fp = io.StringIO()
        self.__super_init(fp, hdrs, url, code)
```

2022-12-08 02:20 UTC, merged

2022-12-08 02:20 UTC, miss-islington commented
Thanks @corona10 for the PR 🌮🎉.. I'm working now to backport this PR to: 3.10, 3.11.
🐍🍒⛏🤖

2023-02-15 17:47 UTC, gaborbernat commented on Lib/urllib/error.py
> +            fp = io.StringIO()
Shouldn't this be BytesIO? 

```python
from urllib.request import urlopen
from urllib.error import HTTPError
try:
    urlopen('http://asadsad.sd')
except HTTPError as exception:
    content = exception.fp.read()
    print(type(content))
```
```
<class 'bytes'>
```